- src/features/identityCheck/api.ts
- src/features/identityCheck/components/SomeAdviceBeforeIdentityCheckModal.tsx
- src/features/identityCheck/pages/identification/IdentityCheckWebview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11727
I have:
> (PC-11727) fix(IdentityCheck): redirect to app when ubble journey is finished

- src/libs/batch/batch-sdk.js
- src/libs/react-native-batch.web.ts
- src/service-worker.ts
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11793
I have:
> (PC-11793) feat(Batch): Ajout des push notification safari desktop (test)

- src/libs/react-native-batch.web.ts
- src/service-worker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11925
Related to https://passculture.atlassian.net/browse/PC-11793
I have:
> (PC-11925) fix(Batch): correction d'une erreur Safari mobile

- public/batchsdk-shared-worker.js
- src/service-worker.ts
> fix(Batch): maj de  to BATCHSDK_MAJOR_VERSION en v3

- src/libs/react-native-batch.web.ts
- src/service-worker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11793
I have:
> (PC-11793) fix(Batch): support pour safari macos

- src/features/navigation/RootNavigator/routes.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11761
I have:
> (PC-11761) feat(routes): meet french routes names standard

- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/search/components/SearchLandingPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11945
I have:
|     |![image](https://user-images.githubusercontent.com/77674046/143061697-81b37d94-a44d-499f-8343-c5a7b0ef5eb2.png)|                 |![image](https://user-images.githubusercontent.com/77674046/143061793-b71775c2-bf3e-48e0-939b-49ae22e3e40d.png)|    ![image](https://user-images.githubusercontent.com/77674046/143061912-1decd950-4154-42ba-b4a5-887f3ca64d8b.png)              |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6 …
> (PC-11945) fix(SearchLandingPage): les éléments centraux sont trop serrés

- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
- __snapshots__/ui/components/SlantTag.native.test.tsx.native-snap
- src/features/auth/__mocks__/api.ts
- src/features/auth/api.ts
- src/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
- src/features/auth/signup/VerifyEligiblity/VerifyEligibility.tsx
- src/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.tsx
- src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx
- src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.tsx
- src/features/profile/components/NonBeneficiaryHeader.native.test.tsx
- src/features/profile/components/NonBeneficiaryHeader.tsx
- src/features/profile/components/NonBeneficiaryHeader.web.test.tsx
- src/features/profile/components/YoungerBadge.test.tsx
- src/features/profile/components/YoungerBadge.tsx
- src/features/profile/pages/Profile.native.test.tsx
- src/locales/fr/messages.po
- src/ui/components/SlantTag.native.test.tsx
- src/ui/components/SlantTag.tsx
- src/ui/components/achievements/components/GenericAchievementCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11654
I have:
https://passculture.atlassian.net/browse/PC-11951 : Fixing the button height will be addressed as a technical improvement in this ticket.
| iOS | iOS small | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|   <img width="373" alt="Capture d’écran 2021-11-23 à 17 34 27" src="https://user-images.githubusercontent.com/44037911/143065788-d187780d-4520-49dd-93ca-2e79491e55cf.png">  |   <img width="282" alt="Capture d’écran 2021-11-23 à 15 59 53" src="https://user-images.githubusercontent.com/44037911/143065914-74248e59-c39d-4fb0-9351-b9237489c0ef.png">      |                 |        <img width="1429" alt="Capture d’écran …
> (PC-11654) feat(EAC): add credit visuals for tutorial step 2

- src/App.web.tsx
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/cheatcodes/pages/NavigationNotScreensPages.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/web/SupportedBrowsersGate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11511
I have:
> (PC-11511) feat(supportedBrowsers): Add supported browsers gate

- package.json
- src/features/auth/IdcheckUnavailable/IdCheckUnavailable.test.tsx
- src/features/auth/IdcheckUnavailable/IdCheckUnavailable.tsx
- src/locales/fr/messages.po
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11760
I have:
|     |     
> (PC-11760) feat(idCheckUnavailable): update wording to fit with underage

- .circleci/config.yml
> ci(Webapp): suppression de true inutile sur le job deploy web

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11964
I have:
> (PC-11964) ci(GCP): Mise à jour des SA

- src/features/identityCheck/pages/identification/IdentityCheckWebview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11727
Sous recommendation de l'équipe ubble.
I have:
> (PC-11727) fix(ubble): allow inline media playback for Ubble webview

- __snapshots__/features/identityCheck/pages/profile/__test__/Status.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/Status.test.tsx.web-snap
- src/features/identityCheck/pages/profile/Status.tsx
- src/features/identityCheck/pages/profile/__test__/Status.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11899
I have:
| Desktop - Chrome no FF | Desktop - Chrome FF |
| ---------------: | ---------------: |
|           <img width="715" alt="Capture d’écran 2021-11-24 à 16 07 05" src="https://user-images.githubusercontent.com/44037911/143263345-5ee0ae03-8521-4914-ab1b-f35bcd99f8bd.png">       |          <img width="715" alt="Capture d’écran 2021-11-24 à 16 06 56" src="https://user-images.githubusercontent.com/44037911/143263258-adb5b0d5-98b8-4b03-8fef-3f04610f68cb.png">        |
> (PC-11899) feat(EAC): add collégien status and feature flag it

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11803
> (PC-11803) fix(translations): bump lingui and fix translation script

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
- src/locales/fr/messages.po
- src/ui/components/modals/AppInformationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11615
I have:
| <img width="366" alt="Capture d’écran 2021-11-25 à 11 50 43" src="https://user-images.githubusercontent.com/44037911/143428122-fd95db4b-5740-4bb5-993b-b5c5a985938a.png">    |         |                 |                  |                  |
> (PC-11615) fix(EAC): dispatch modal title on three lines

- src/libs/react-native-batch.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11983
I have:
> (PC-11983) fix(BatchSDK): chargement du batch sdk plus tot

- __snapshots__/features/auth/signup/SetName/SetName.native.test.tsx.native-snap
- src/features/auth/signup/SetName/SetName.native.test.tsx
- src/features/auth/signup/SetName/SetName.tsx
- src/features/identityCheck/context/reducer.ts
- src/features/identityCheck/context/types.ts
- src/features/identityCheck/pages/profile/SetAddress.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11978
I have:
|  ![Capture d’écran 2021-11-25 à 18 23 13](https://user-images.githubusercontent.com/62059034/143482443-6a218e5a-9e92-4594-844c-f0e8433f6710.png) ![Capture d’écran 2021-11-25 à 18 23 39](https://user-images.githubusercontent.com/62059034/143482460-735b6d7d-73f1-4de8-bead-fcff99ccf04a.png) ![Capture d’écran 2021-11-25 à 18 24 19](https://user-images.githubusercontent.com/62059034/143482492-e6ac2670-3413-4877-a44d-a248b4fc37d7.png) |         |                 |                  |                  |
[1]: …
> (PC-11978) feat(identityCheck): Update design for SetName

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11885
I have:
> (PC-11885) fix(idcheck): bump idcheck version

- src/features/auth/signup/underageSignup/UnderageAccountCreated.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11648
I have:
> (PC-11648) fix(underageAccountCreated): update anim

- src/features/favorites/pages/useFavorites.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11775
I have:
> (PC-11775) fix(favorites): Make useFavorite() internals more defensive

- src/features/auth/__mocks__/settings.ts
- src/features/identityCheck/context/reducer.ts
- src/features/identityCheck/context/types.ts
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx
- src/libs/place/useAddresses.ts
- src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12002
I have:
> (PC-12002) feat(SetAddress): enable free typing of address depending on FF and API status

- src/libs/campaign/campaignTracker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12020
I have:
> (PC-12020) fix(AppFlyers): __DEV__ mode fix

- __snapshots__/features/profile/pages/PersonalData.native.test.tsx.native-snap
- src/features/profile/pages/PersonalData.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12034
I have:
> (PC-12034) fix(personalData): increase clickable zone for modify button

- src/features/search/components/CalendarPicker.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12043
I have:
|     |         |                 |![image](https://user-images.githubusercontent.com/77674046/143862298-ed1a7971-9883-4362-b444-8fdcda2d46b5.png) |                  |
> (PC-12043) fix(CalendarPicker): add minHeight and minDate

- __mocks__/algoliasearch.ts
- src/libs/algolia/__tests__/fetchAlgolia.test.ts
- src/libs/algolia/fetchAlgolia/fetchAlgolia.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11950
I have:
> (PC-11950) feat(fetchAlgoliaHomeModules): filter home modules for underage

- web/config/paths.js
- web/config/webpack.config.js
> (PC-10087) fix(Sentry): sourcemap configuraiton for the web

- src/api/gen/api.ts
- src/features/home/api.test.ts
- src/features/offer/components/__tests__/OfferIconCaptions.native.test.tsx
- src/features/offer/components/__tests__/OfferIconCaptions.web.test.tsx
- src/features/profile/components/ProfileHeader.native.test.tsx
- src/features/profile/components/ProfileHeader.tsx
- src/features/profile/components/ProfileHeader.web.test.tsx
- src/fixtures/user.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11952
I have:
> (PC-11952) fix(EAC): fix profile header message for ex underage beneficiary

- src/features/bookOffer/components/Calendar/Calendar.tsx
- src/features/search/components/CalendarPicker.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12043
I have:
> (PC-12043) fix(Calendar): adjust minHeight for bookOffer and search Calendar

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- src/ui/components/inputs/DateInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11706
I have:
| iOS Safari | Android | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-11-26 at 14 16 38](https://user-images.githubusercontent.com/90036171/143587357-009e9d92-5c75-4afe-8db1-2069a799234d.png)|         |                 |                  |                  |
> (PC-11706) fix(SetBirthday): Update Input appearance for Safari

- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
- src/features/profile/pages/ChangePassword/ChangePassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12056
I have:
| ![video_ecran](https://user-images.githubusercontent.com/26742386/144025366-0d282ed6-a383-4344-bdb0-a17ba325bead.gif) |         |                 |                  |                  |
> (PC-12056) fix(changeEmail): handle click on button when the keyboard is open

- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/screenParamsUtils.ts
- src/features/profile/pages/AfterChangeEmailValidationBuffer/AfterChangeEmailValidationBuffer.tsx
- src/features/profile/pages/AfterChangeEmailValidationBuffer/__tests__/AfterChangeEmailValidationBuffer.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12035
I have:
> (PC-12035) fix(changeEmailValidation): fix new email link handling

- __snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- __snapshots__/features/auth/signup/idCheck/DenyAccessToIdCheck.native.test.tsx.native-snap
- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
- src/locales/fr/messages.po
- src/ui/components/modals/ModalHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11615
And add padding between title and icons.
The colored backgrounds are not in the code, of course.
I have:
| iOS small screen | iOS  | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|   <img width="333" alt="Capture d’écran 2021-11-30 à 16 33 28" src="https://user-images.githubusercontent.com/44037911/144079102-18cd84eb-14c5-45be-8f12-14b5339a73dc.png">  |    <img width="333" alt="Capture d’écran 2021-11-30 à 16 33 14" src="https://user-images.githubusercontent.com/44037911/144079262-060d43a8-0dde-4713-9744-1d4044ef49ac.png">     |                 |       <img width="491" alt="Capture d’écran 2021-11-30 à 16 33 50" …
> (PC-11615) fix(modals): freeze icon position modal header

- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- src/features/identityCheck/api.ts
- src/features/identityCheck/components/SomeAdviceBeforeIdentityCheckModal.tsx
- src/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx
- src/features/identityCheck/pages/identification/IdentityCheckStart.tsx
- src/features/identityCheck/pages/identification/IdentityCheckWebview.tsx
- src/features/identityCheck/pages/identification/IdentityCheckWebview.web.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx
- src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11746
I have:
> (PC-11746) refactor(IdentityCheckWebview): do not useMutation inside Modal but on dedicated page

- src/features/favorites/components/NoFavoritesResult.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12072
I have:
| iOS | Android | Mobile - Chrome responsive iPhone 5 | Desktop - Chrome | Desktop - Safari |
|     | ![image](https://user-images.githubusercontent.com/77674046/144027670-a995e8e4-39f6-4039-96f4-129a103d2b0f.png)| ![image](https://user-images.githubusercontent.com/77674046/144026385-f3c380ce-6bad-49cc-bbef-e680c170dae6.png)| ![image](https://user-images.githubusercontent.com/77674046/144026354-a3b80906-c539-45f5-b8c4-c37182f4b5e6.png) |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f …
> (PC-12072) fix(NoFavoritesResults): responsive for web orientation landscape

- __mocks__/@pass-culture/id-check.tsx
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/EduConnectForm.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/EduConnectForm.web.test.tsx.web-snap
- src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/pages/profile/IdentityCheckEduConnectForm.tsx
- src/features/identityCheck/pages/profile/IdentityCheckEduConnectForm.web.tsx
- src/features/identityCheck/pages/profile/__test__/EduConnectForm.native.test.tsx
- src/features/identityCheck/pages/profile/__test__/EduConnectForm.web.test.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11989
I have:
|     |      
> (PC-11989) feat(EduConnect): migrate from idCheck to app repository

- src/web/SupportedBrowsersGate.tsx
> fix(browsersGate): display gate if browser not in supported list

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.native.test.tsx.native-snap
- src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.native.test.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11988
*** Testing in progress
I have:
| iPhone SE | iPhone X | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|<img width="335" alt="Schermata 2021-11-30 alle 11 01 45" src="https://user-images.githubusercontent.com/90036171/144026703-cb3b9cca-3814-456a-87f5-63def9cfcf64.png">|<img width="386" alt="Schermata 2021-11-30 alle 11 02 07" src="https://user-images.githubusercontent.com/90036171/144026697-401746e6-a9fe-4a33-a372-8ac5c89e437f.png">|                 |<img width="1920" alt="Schermata 2021-11-30 alle 11 02 18" src="https://user-images.githubusercontent.com/90036171/144026651-782f04ce-f87f-4849-af8d-eda0372f2562.png">|                  | …
> (PC-11988) feat(idCheckEduConnect): Create Educonnect Page

- src/features/navigation/RootNavigator/types.ts
- src/libs/firestore/__tests__/ubbleLoad.native.test.ts
- src/libs/firestore/types.ts
- src/libs/firestore/ubbleLoad.ts
- src/libs/monitoring/services.ts
- src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11977
I have:
> (PC-11977) feat(ubble): redirect to ubble according to firestore load [1/2]

- __snapshots__/features/auth/signup/idCheck/DenyAccessToIdCheck.native.test.tsx.native-snap
- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- src/features/auth/signup/idCheck/DenyAccessToIdCheck.tsx
- src/features/bookOffer/pages/BookingOfferModal.tsx
- src/ui/components/modals/AppModal.tsx
- src/ui/components/modals/ModalHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11399
I have:
| iOS | Android | Mobile - Chrome - iphone5 | Desktop - Chrome | Desktop - Safari |
|     |         |  ![image](https://user-images.githubusercontent.com/22399093/144083270-59a0214a-dc57-49e7-a0d1-7e2c76860fb3.png) |  ![image](https://user-images.githubusercontent.com/22399093/144083328-18ba0017-3f8d-4dd0-9f98-484ffc42fe8e.png)  |                  |
> (PC-11399) feat(ui): Adapt modals for desktop viewports

- src/features/auth/signup/idCheck/useNavigateToIdCheck.test.tsx
- src/features/auth/signup/idCheck/useNavigateToIdCheck.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11977
I have:
> (PC-11977) refactor(useNavigateToIdCheck): remove useless param

- src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
- src/features/auth/signup/UserProfiling.tsx
- src/features/auth/signup/useBeneficiaryValidationNavigation.test.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.ts
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11895
I have:
> (PC-11895) feat(signup): navigate to UserProfiling component on UserProfiling next step

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12078
I have:
> (PC-12078) ci(copy_assetlinks): refactor assetlinks copy to use parameters

- src/features/auth/AuthContext.tsx
- src/features/favorites/atoms/BicolorFavoriteCount.tsx
- src/features/favorites/atoms/__tests__/BicolorFavoriteCount.native.test.tsx
- src/features/favorites/atoms/__tests__/BicolorFavoriteCount.web.test.tsx
- src/features/favorites/pages/useFavorites.ts
- src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12095
I have:
| Platform | No favorites (disconnected) | No favorites (connected) | 3 favorites | 3 favorites + |
| ---- | ---- | ---- | ---- | ---- |
| Web | ![Capture d’écran 2021-12-03 à 13 31 58](https://user-images.githubusercontent.com/10118284/144603567-bc239351-8120-44b1-ad1e-d1e3ba902a28.png) | ![image](https://user-images.githubusercontent.com/10118284/144605557-87163dc9-c478-470d-8aa5-e20db902f4aa.png) | ![Capture d’écran 2021-12-03 à 13 31 21](https://user-images.githubusercontent.com/10118284/144603606-bf3e2d79-2bb3-4588-860b-c91b62fa4f66.png) | ![Capture d’écran 2021-12-03 à 13 30 56](https://user-images.githubusercontent.com/10118284/144603659-1fc173fa-5c48-4e88-92fa-3f94145462ec.png) |
| Mobile | <img …
> (PC-12095) fix(favorites): center number of favorites on tabbar

- src/api/gen/api.ts
- src/features/identityCheck/api.ts
- src/features/identityCheck/components/QuitIdentityCheckModal.tsx
- src/features/identityCheck/components/__test__/QuitIdentityCheckModal.native.test.tsx
- src/features/identityCheck/components/__test__/QuitIdentityCheckModal.web.test.tsx
- src/features/identityCheck/pages/Stepper.tsx
- src/features/identityCheck/pages/profile/Status.tsx
- src/features/identityCheck/pages/profile/__test__/Status.test.tsx
- src/features/identityCheck/useIdentityCheckNavigation.ts
- src/libs/queryKeys.ts
> (PC-12081) feat(identityCheck): add usePatchProfile

- __mocks__/fixtures/booking.ts
- src/api/gen/api.ts
- src/features/bookOffer/components/BookingDetails.tsx
- src/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx
- src/features/bookOffer/fixtures/offer.ts
- src/features/bookings/api/bookingsSnap.ts
- src/features/favorites/api/snaps/favorisResponseSnap.ts
- src/features/favorites/atoms/__tests__/BookingButton.test.tsx
- src/features/favorites/atoms/__tests__/Favorite.native.test.tsx
- src/features/offer/api/snaps/offerResponseSnap.ts
- src/features/offer/atoms/OfferTile.tsx
- src/features/offer/atoms/__tests__/OfferTile.native.test.tsx
- src/features/offer/atoms/__tests__/OfferTile.web.test.tsx
- src/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx
- src/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx
PR sur l'API: https://github.com/pass-culture/pass-culture-main/pull/645
> feat(categories): remove use of categories

- src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/offer/components/__tests__/OfferHeader.native.test.tsx
- src/features/offer/services/useShareOffer.ts
- src/features/venue/components/__tests__/VenueHeader.native.test.tsx
- src/features/venue/services/useShareVenue.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8822
I have:
> (PC-8822) feat(share): simplify links we share

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- src/features/identityCheck/atoms/DMSInformation.tsx
- src/features/identityCheck/atoms/DMSInformation.web.tsx
- src/features/identityCheck/components/DMSModal.tsx
- src/features/identityCheck/components/__test__/DMSModal.native.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12138
I have:
|  <img width="316" alt="Capture d’écran 2021-12-03 à 18 13 24" src="https://user-images.githubusercontent.com/62059034/144644429-dd634d99-2377-440c-a0c5-4c3c49064d95.png">   |         |                 |          <img width="1792" alt="Capture d’écran 2021-12-03 à 18 12 59" src="https://user-images.githubusercontent.com/62059034/144644472-3598f3d5-e099-4b9a-996b-343190273460.png">  |                  |
> (PC-12138) feat(identityCheck): Add DMS modal

- src/features/auth/AuthContext.tsx
- src/features/auth/login/Login.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10783
I have:
> (PC-10783) fix(SearchContext): erase search and ID contexts when logging in and out

- package.json
- web/config/webpack.config.js
- yarn.lock
> build(webpack): re-enable postcss

- android/app/build.gradle
https://medium.com/@rishii.kumar.chawda/reduce-your-react-native-app-size-dramatically-5430d773c92f
https://developer.android.com/studio/build/shrink-code
> build(android): enable Proguard and reduce bundle size

- __snapshots__/features/identityCheck/pages/identification/__test__/EduConnectForm.web.test.tsx.web-snap
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11989
I have:
|     |         |                 |                  |           
|
> (PC-11989) feat(EduConnectForm): meet design

- src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12094
I have:
| iOS | Android | Mobile - Chrome (iphone 5) | Desktop - Chrome | Desktop - Safari |
|     |         | ![image](https://user-images.githubusercontent.com/22399093/144829374-52256709-0d55-4264-a350-77321da31799.png) | ![image](https://user-images.githubusercontent.com/22399093/144829583-ddabf16c-163f-4eca-94ce-f3aa85851d60.png) |                  |
> (PC-12094) fix(phoneValidation): Reduce input width

- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- src/features/auth/signup/SetEmail/SetEmail.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12177
I have:
|  <img width="315" alt="Capture d’écran 2021-12-06 à 12 33 52" src="https://user-images.githubusercontent.com/62059034/144840064-c4dc0d46-718b-4d1b-b338-544ef943a610.png"> <img width="316" alt="Capture d’écran 2021-12-06 à 12 43 45" src="https://user-images.githubusercontent.com/62059034/144840482-4e6d4b27-4598-4e1b-8a4b-712ca2f40bbc.png">  |         |                 |                  |                  |
> (PC-12177) feat(signup): udpate wording SetEmail

- __snapshots__/features/auth/signup/idCheck/DenyAccessToIdCheck.native.test.tsx.native-snap
- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12156
I have:
|     | ![image](https://user-images.githubusercontent.com/22399093/144843115-7e0024b2-a28e-43cd-96d0-ddcea5718b0f.png) |                 |  ![image](https://user-images.githubusercontent.com/22399093/144843049-6b5b50d5-547e-4d3d-a552-3fa5f13a8fba.png) |                  |
> (PC-12156) fix(modal): Make modal take full width

- src/api/gen/api.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.test.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11977
I have:
> (PC-11977) feat(ubble): Partial release de Ubble avec Firestore

- src/libs/algolia/__tests__/fetchAlgolia.test.ts
- src/libs/algolia/enums/facetsEnums.ts
- src/libs/algolia/fetchAlgolia/fetchAlgolia.facetFilters.ts
- src/libs/algolia/fetchAlgolia/fetchAlgolia.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12158
I have:
> (PC-12158) fix(recommendations): fix algolia call crashing

- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/withWebWrapper.web.tsx
- src/features/profile/pages/Profile.tsx
- src/features/smartBanner/SmartBanner.web.tsx
- src/libs/react-smartbanner/index.d.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12074
I have:
> (PC-12074) fix(SmartBanner): disable ignoreIosVersion and move to profile

- src/features/identityCheck/pages/identification/IdentityCheckWebview.tsx
- src/features/identityCheck/pages/identification/IdentityCheckWebview.web.tsx
- src/libs/analytics/__mocks__/analytics.ts
- src/libs/analytics/analytics.ts
- src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12109
I have:
> (PC-12109) feat(UbbleWebview): redirect to home on abort

- doc/installation/setup.md
Remplace https://github.com/pass-culture/pass-culture-app-native/pull/2195
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12137
I have:
> (PC-12137) docs(developement): use Node frow Brew in XCode builds' steps

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12207
I have:
> (PC-12207) ci(Webapp): added manual trigger for deploying staging/integration/production

- __snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/ui/components/inputs/BaseTextInput.native.test.tsx.native-snap
- __snapshots__/ui/components/inputs/PasswordInput.native.test.tsx.native-snap
- __snapshots__/ui/components/inputs/TextInput.native.test.tsx.native-snap
- src/features/profile/pages/ChangeEmail/AlreadyChangedEmailDisclaimer.tsx
- src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
- src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx
- src/features/profile/pages/ChangeEmail/utils/useCheckHasCurrentEmailChange.ts
- src/libs/queryKeys.ts
- src/ui/components/inputs/BaseTextInput.tsx
- src/ui/components/inputs/PasswordInput.tsx
- src/ui/components/inputs/StyledInputContainer.tsx
- src/ui/components/inputs/TextInput.tsx
- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11421
I have:
> (PC-11421) feat(changeEmail): je vois le disclaimer de confirmation d'envoi de mail d'activation

- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- src/features/profile/pages/ChangeEmail/AlreadyChangedEmailDisclaimer.tsx
- src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
- src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx
- src/libs/analytics/__mocks__/analytics.ts
- src/libs/analytics/analytics.ts
- src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11736
I have:
> (PC-11736) feat(changeEmail): log ConsultDisclaimerValidationMail event when showing the disclaimer

- src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
> (PC-11759) feat(educonnectInvalidInfo): navigate to next beneficiary validation step

- src/features/auth/AuthContext.tsx
- src/features/auth/login/Login.native.test.tsx
This reverts commit b5ad502b13dec5f9a95817900218dbf238f0fb88.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10783
Related to : https://passculture.atlassian.net/browse/PC-12190
I have:
> (PC-12190) fix(Profile): Revert "(PC-10783) erase search and ID contexts when logging in/out (#2202)"

- src/features/identityCheck/context/__mocks__/IdentityCheckContextProvider.tsx
- src/features/identityCheck/context/reducer.ts
- src/features/identityCheck/context/types.ts
- src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
- src/features/identityCheck/pages/identification/IdentityCheckValidation.tsx
- src/features/identityCheck/pages/identification/__test__/EduConnectForm.native.test.tsx
- src/features/identityCheck/pages/identification/__test__/EduConnectForm.web.test.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.native.test.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckValidation.native.test.tsx
- src/features/identityCheck/useIdentityCheckSteps.tsx
- src/features/identityCheck/utils/__mocks__/useEduConnect.tsx
- src/features/identityCheck/utils/useEduConnect.tsx
- src/libs/__mocks__/eduConnectClient.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12075
I have:
> (PC-12075) feat(EduConnectNav): id check migration navigation

- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
- src/features/profile/pages/ConsentSettings.native.test.tsx
- src/features/profile/pages/ConsentSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12196
I have:
|     |         | ![image](https://user-images.githubusercontent.com/22399093/145065047-4e8ad599-c8c7-4965-9e14-23d2e7fb2770.png) |                  |                  |
> (PC-12196) feat(privacy): Add refuse button to modal

- src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx
- src/ui/components/inputs/StyledInputContainer.tsx
- src/ui/components/inputs/TextInput.tsx
- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12094
I have:
|     |         | ![image](https://user-images.githubusercontent.com/22399093/145187939-1e3d1ec9-2cd0-495f-bcd6-a2ce03c2635d.png) | ![image](https://user-images.githubusercontent.com/22399093/145188016-546c2ee0-0090-44e3-97ce-8269aad24ce3.png) |                  |
> (PC-12094) fix(phone): Make input more responsive

- __snapshots__/features/identityCheck/pages/identification/__test__/EduConnectForm.web.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/Icons.tsx
- src/features/identityCheck/context/__mocks__/IdentityCheckContextProvider.tsx
- src/features/identityCheck/context/reducer.ts
- src/features/identityCheck/context/types.ts
- src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
- src/features/identityCheck/pages/identification/IdentityCheckStart.tsx
- src/features/identityCheck/pages/identification/IdentityCheckStart.web.tsx
- src/features/identityCheck/pages/identification/IdentityCheckValidation.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckValidation.native.test.tsx
- src/ui/svg/icons/BicolorIdCardWithMagnifyingGlass.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12075
I have:
|     |         |                 |                  |          
|
> (PC-12075) feat(EduconnectPages): migrate id check module to app

- src/features/identityCheck/context/reducer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12075
I have:
|  
|         |                 |                  |                  |
> (PC-12075) feat(IdCheck): store identification info

- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- src/features/identityCheck/components/FastEduconnectConnectionRequestModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12122
I have:
No Screenshots required
> (PC-12122) feat(FastEduconnectConnection): Update all cta of the Modal FastEduconnectConnectionRequestModal

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12130
I have:
> (PC-12130) build(slack): clarify slack notifications

- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12196
I have:
|     |         |  ![image](https://user-images.githubusercontent.com/22399093/145565749-4331ce95-cb0d-43fc-88e6-70947bd3a2f8.png)  | ![image](https://user-images.githubusercontent.com/22399093/145565725-5e0fd2e9-98e1-4df0-8e77-8a76aaa2c237.png)   |                  |
> (PC-12196) fix(privacyModal): Remove button to consent settings

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12257
Depend on https://github.com/pass-culture/id-check-front/pull/268 + https://github.com/pass-culture/id-check-front/pull/269
I have:
> (PC-12257) fix(idcheck): upgrade version v2.11.0 (openUrl fix)

- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- src/features/auth/components/signupComponents.tsx
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
- src/features/auth/signup/SetEmail/SetEmail.tsx
- src/features/auth/signup/SetPassword/AcceptCgu.tsx
- src/features/auth/signup/SetPassword/SetPassword.tsx
- src/features/auth/signup/SignupForm.tsx
- src/ui/components/BottomCardContentContainer.tsx
- src/ui/components/BottomContentPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11980
I have:
> (PC-11980) fix(signup): Various fixes relative to new signup implementation

- src/features/auth/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx
- src/features/auth/signup/useBeneficiaryValidationNavigation.test.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.ts
- src/features/profile/components/NonBeneficiaryHeader.native.test.tsx
- src/features/profile/components/NonBeneficiaryHeader.tsx
- src/features/profile/components/NonBeneficiaryHeader.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12055
I have:
> (PC-12055) feat(VerifyEligibility): handle underage generalisation

- __snapshots__/features/cheatcodes/pages/CheatCodes/tests/CheatCodes.native.test.tsx.native-snap
- ios/Podfile.lock
- package.json
- src/features/cheatcodes/pages/CheatCodes/CheatCodes.tsx
- src/features/identityCheck/components/FastEduconnectConnectionRequestModal.tsx
- src/ui/svg/icons/ExternalSite_deprecated.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12250
I have:
> (PC-12250) fix(uploadCNI): fix upload image of id-check

- package.json
- yarn.lock
https://sentry.internal-passculture.app/organizations/sentry/issues/239152/?environment=testing&project=6&query=is%3Aunresolved+os.name%3AAndroid&statsPeriod=1h
https://github.com/software-mansion/react-native-reanimated/issues/2702
> build(android): fix version of react-native-reanimated to a stable version

- __mocks__/@sentry/react.ts
- src/libs/monitoring/__tests__/services.native.test.ts
- src/libs/monitoring/__tests__/services.web.test.ts
- src/libs/monitoring/config.ts
- src/libs/monitoring/config.web.ts
- src/libs/monitoring/sentry.ts
- src/libs/monitoring/sentry.web.ts
- src/libs/monitoring/services.ts
- web/config/webpack.config.js
Applying advice from : https://github.com/getsentry/sentry-webpack-plugin/issues/332#issuecomment-988963441
NOTE: does not fix sentry source map but remove complexity
I have:
> (PC-10087) fix(Sentry): remove webpack resolve alias

- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/PersonalData.native.test.tsx.native-snap
- src/features/profile/pages/AfterChangeEmailValidationBuffer/AfterChangeEmailValidationBuffer.tsx
- src/features/profile/pages/AfterChangeEmailValidationBuffer/__tests__/AfterChangeEmailValidationBuffer.native.test.tsx
- src/features/profile/pages/ChangeEmail/ChangeEmailDisclaimer.tsx
- src/features/profile/pages/PersonalData.native.test.tsx
- src/features/profile/pages/PersonalData.tsx
- src/features/profile/pages/PersonalData.web.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12270
I have:
> (PC-12270) feat(changeEmail): update wordings

- __snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.native-snap
- __snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.web-snap
- src/features/auth/signup/VerifyEligiblity/VerifyEligibility.tsx
- src/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12265
I have:
|     |    
> (PC-12265) feat(VerifyEligibility): handle underage generalisation

- .env.production
- .env.staging
- .env.testing
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12122
I have:
No Screenshots required 
> (PC-12122) fix(FastEduConnectModal): Fix URL in environnement files

- src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx
- src/libs/country-picker/CountryPicker.tsx
- src/libs/country-picker/constants.ts
- src/libs/country-picker/index.ts
- src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12192
I have:
|     |         | ![image](https://user-images.githubusercontent.com/22399093/146008419-6c631182-cb85-4f36-aecc-be4e13815943.png) |  ![image](https://user-images.githubusercontent.com/22399093/146008333-f54915c3-946c-44c7-84de-5984201f872a.png)  |                  |
> (PC-12192) feat(countryPicker): Adapt picker for cross-platform use

- src/libs/country-picker/CountryPicker.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12192
I have:
> (PC-12192) fix(countrypicker): Use new icon and (try) fix log ignore

- src/features/auth/__mocks__/settings.ts
- src/features/auth/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12055
I have:
> (PC-12055) feat(VerifyEligibility): handle underage generalisation before compute navigation

- src/features/profile/components/NonBeneficiaryHeader.tsx
- src/features/profile/components/YoungerBadge.test.tsx
- src/features/profile/components/YoungerBadge.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12316
I have:
| ![Capture d’écran 2021-12-14 à 17 06 47](https://user-images.githubusercontent.com/62059034/146039340-dbd32fac-5589-42f0-a965-36b175e18135.png)  |         |                 |      ![Capture d’écran 2021-12-14 à 17 07 38](https://user-images.githubusercontent.com/62059034/146039420-9cb86a90-e496-4294-8d31-db2e98aca5fa.png) |                  |
> (PC-12316) feat(profile): udpate wording for YoungerBadge

- src/features/identityCheck/atoms/AddressOption.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12277
I have:
| <img width="329" alt="Capture d’écran 2021-12-15 à 11 04 55" src="https://user-images.githubusercontent.com/62059034/146166309-3a6345c3-a2b0-48f5-ba13-c48a794e820a.png">   |         |                 |  <img width="1792" alt="Capture d’écran 2021-12-15 à 10 52 52" src="https://user-images.githubusercontent.com/62059034/146166344-c32f7dd5-4391-43b5-aca7-7c175c678b8f.png"> |                  |
> (PC-12277) fix(identityCheck): udpate design for AddressOption

- src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12239
I have:
> (PC-12239) feat(IdentityCheckEduConnectFormWeb): handle errors

- src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12307
I have:
| ![image](https://user-images.githubusercontent.com/10118284/146085319-98c14a25-4f78-4e3e-b5ec-d1e08e3da068.png) |         |                 |                  |                  |
> (PC-12307) feat(educonnectForm): redirect not whitelisted users

- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.web.test.tsx.web-snap
- src/features/auth/forgottenPassword/ResetPasswordExpiredLink/ResetPasswordExpiredLink.tsx
- src/features/auth/signup/SignupConfirmationExpiredLink/SignupConfirmationExpiredLink.tsx
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/screenParamsUtils.ts
- src/features/profile/pages/AfterChangeEmailValidationBuffer/AfterChangeEmailValidationBuffer.tsx
- src/features/profile/pages/AfterChangeEmailValidationBuffer/__tests__/AfterChangeEmailValidationBuffer.native.test.tsx
- src/features/profile/pages/ChangeEmail/ChangeEmailExpiredLink.tsx
- src/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx
- src/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.web.test.tsx
- src/ui/components/LayoutExpiredLink.tsx
- src/ui/components/__tests__/LayoutExpiredLink.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11697
I have:
| ![image](https://user-images.githubusercontent.com/26742386/146163314-6caa726b-cf96-450e-b472-d1be0a958246.png) |         | ![image](https://user-images.githubusercontent.com/26742386/146030464-063de020-e991-47f1-a5e5-d8851186d63e.png) | ![image](https://user-images.githubusercontent.com/26742386/146029976-fb2cff40-d3cb-472f-92fd-326e438e92eb.png) |                  |
| ![image](https://user-images.githubusercontent.com/26742386/146163154-c1a77b5d-45b4-4eba-9c97-1794609fda37.png) |  | ![image](https://user-images.githubusercontent.com/26742386/146030305-c76fafbc-b8 …
> (PC-11697) feat(changeEmailError): add cta to restart the email change flow

- src/features/identityCheck/errors/eduConnect/EduConnectErrorBoundary.tsx
- src/features/identityCheck/pages/errors/EduConnectErrors.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12239
Urls à tester:
- http://localhost:3000/idcheck/educonnect/erreur?code=UserAgeNotValid18YearsOld
- http://localhost:3000/idcheck/educonnect/erreur?code=UserAgeNotValid
- http://localhost:3000/idcheck/educonnect/erreur?code=UserTypeNotStudent
- http://localhost:3000/idcheck/educonnect/erreur?code=OutOfTestPhase
- http://localhost:3000/idcheck/educonnect/erreur?code=UserNotWhitelisted
- http://localhost:3000/idcheck/educonnect/erreur?code=unknown
Pareil sans idcheck:
- http://localhost:3000/educonnect/erreur?code=UserAgeNotValid18YearsOld
- http://localhost:3000/educonnect/erreur?code=UserAgeNotValid
- http://localhost:3000/educonnect/erreur?code=UserTypeNotStudent
- …
> (PC-12239) feat(educonnect): redirect to error page on educonnect web error

- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12239
I have:
> (PC-12239) fix(educonnect): fix loading of webview

- src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12278
I have:
> (PC-12278) feat(IdentityCheckEduConnectForm): refresh page on UserTypeNotStudent error

- src/features/identityCheck/useIdentityCheckSteps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11755
I have:
> (PC-11755) fix(EduConnect): fix educonnect redirection from modal

- __mocks__/react-native-svg.tsx
- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/ui/components/DotComponent.native.test.tsx.native-snap
- __snapshots__/ui/components/DotComponent.web.test.tsx.web-snap
- src/features/auth/signup/SignupForm.native.test.tsx
- src/ui/components/DotComponent.native.test.tsx
- src/ui/components/DotComponent.tsx
- src/ui/components/DotComponent.web.test.tsx
- src/ui/components/StepDots.native.test.tsx
- src/ui/components/StepDots.tsx
- src/ui/components/achievements/components/GenericAchievement.tsx
- src/ui/svg/icons/Dot.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12337
I have:
|     |         |                 |  ![image](https://user-images.githubusercontent.com/22399093/146226960-2b55a7f3-abbe-415f-950b-027969e39322.png)  |                  |
> (PC-12337) feat(accessibility): Use transparent fill for not completed dots

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/features/profile/components/ProfileBadge.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/auth/signup/AcceptCgu/AcceptCgu.tsx
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
- src/features/auth/signup/SetEmail/SetEmail.tsx
- src/features/auth/signup/SetPassword/SetPassword.tsx
- src/features/auth/signup/SignupForm.tsx
- src/features/auth/signup/types.ts
- src/tests/utils.tsx
- src/ui/components/PassPlaylist.tsx
- src/ui/components/buttons/AppButton.tsx
- src/ui/components/inputs/DateInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12176
I have:
> (PC-12176) feat(accessibility): Modify some labels and make accessibilityAndTestId(...) more flexible

- src/features/identityCheck/api.ts
- src/features/identityCheck/pages/profile/SetSchoolType.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11901
I have:
> (PC-11901) feat(signup): send schoolType in /subscription/profile

- src/features/auth/signup/useBeneficiaryValidationNavigation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11895
I have:
> (PC-11895) fix(nextBeneficiaryValidationStep): fix useNextBeneficiaryValidationStep hook

- src/features/search/components/CalendarPicker.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12185
I have:
> (PC-12185) feat(accessibility): Increase contrast on web calendar picker

- src/features/identityCheck/pages/errors/EduConnectErrors.tsx
> (PC-12382) feat(EduConnectErrors): logout user

- src/features/auth/signup/underageSignup/SelectSchool.tsx
- src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/errors/eduConnect/NotEligibleEduConnect.tsx
- src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
- src/features/identityCheck/pages/errors/EduConnectErrors.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12376
I have:
|     |         |                 |       <img width="798" alt="Capture d’écran 2021-12-17 à 14 50 45" src="https://user-images.githubusercontent.com/44037911/146554796-dd771b08-6b27-4c12-bce1-eade6fbdb220.png">           |                  |
> (PC-12376) feat(EAC): fix user not whitelisted error page and add it to signup process

- src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx
- src/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.native.test.tsx
- src/features/identityCheck/useIdentityCheckSteps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11649
I have:
No screenshots required
> (PC-11649) fix(UnderageAccountCreated): fix redirection for UnderageAccountCreated

- src/features/identityCheck/atoms/layout/PageHeader.tsx
- src/features/identityCheck/components/FastEduconnectConnectionRequestModal.tsx
- src/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx
- src/features/identityCheck/components/layout/PageWithHeader.tsx
- src/features/identityCheck/context/reducer.ts
- src/features/identityCheck/context/types.ts
- src/features/identityCheck/pages/Stepper.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx
- src/features/identityCheck/pages/identification/IdentityCheckStart.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.native.test.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx
- src/features/identityCheck/useIdentityCheckSteps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12387
I have:
> (PC-12387) fix(signup): enable underage access to ubble from modal

- __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
- __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
- __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.native.test.tsx.native-snap
- __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.web.test.tsx.web-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
- __snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap
- src/ui/theme/typography.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12097
I have:
| ![image](https://user-images.githubusercontent.com/26742386/146793288-83177f2e-424e-451f-9639-6f82d3a7fb53.png) | ![image](https://user-images.githubusercontent.com/26742386/146793058-51e04616-d970-4940-aaa5-5e3b9545581a.png) |                 | ![image](https://user-images.githubusercontent.com/26742386/146792951-21f0f255-4b45-48dd-8a21-a74dd04a0007.png) |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e …
> (PC-12097) fix(android): display the font of title 1 correctly

- src/features/identityCheck/pages/profile/Status.tsx
- src/features/identityCheck/pages/profile/__mocks__/utils.ts
- src/features/identityCheck/pages/profile/__test__/Status.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12409
I have:
> (PC-12409) fix(EAC): fix activity and school types display

- src/features/home/pages/useHomeRecommendedHits.ts
- src/features/home/pages/useOfferModule.ts
- src/features/search/pages/useSearchResults.ts
- src/features/venue/api/useVenueOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11811
I have:
> (PC-11811) fix(Search): filter offers based on underage

- package.json
- src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12412
I have:
> (PC-12412) fix(EduConnect): fix edu connect web

- src/features/home/api.test.ts
- src/features/home/api.ts
- src/libs/analytics/__mocks__/analytics.ts
- src/libs/analytics/analytics.ts
- src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12325
I have:
> (PC-12325) feat(analytics): log consultHome with entryId from contentful

- __snapshots__/features/profile/components/CreditCeiling.native.test.tsx.native-snap
- __snapshots__/features/profile/components/CreditCeiling.web.test.tsx.web-snap
- __snapshots__/ui/components/bars/ProgressBar.native.test.tsx.native-snap
- __snapshots__/ui/components/bars/ProgressBar.web.test.tsx.web-snap
- src/features/identityCheck/pages/confirmation/UnderageAccountCreated.tsx
- src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx
- src/ui/components/bars/ProgressBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11649
I have:
> (PC-11649) fix(signupNotification): fix progress bar icon

- src/features/identityCheck/pages/identification/IdentityCheckValidation.tsx
- src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx
- src/features/identityCheck/useIdentityCheckNavigation.ts
- src/features/identityCheck/useIdentityCheckSteps.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
> fix(Webapp): educonnect validation

- src/libs/algolia/__tests__/fetchAlgolia.test.ts
- src/libs/algolia/enums/facetsEnums.ts
- src/libs/algolia/fetchAlgolia/fetchAlgolia.facetFilters.ts
- src/libs/algolia/fetchAlgolia/fetchAlgolia.ts
> (PC-11999) feat(isForbiddenToUnderage): use isForbiddenToUnderage for home and search

- src/features/identityCheck/pages/Stepper.tsx
- src/features/identityCheck/useSetCurrentSubscriptionStep.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12455
I have:
> (PC-12455) fix(IdentifyCheckContext): dispatch SET_METHOD on stepper focus effect

- __snapshots__/features/identityCheck/pages/identification/__test__/EduConnectForm.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/EduConnectForm.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckValidation.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/Status.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/Status.test.tsx.web-snap
- src/features/identityCheck/atoms/layout/CustomKeyboardAvoidingView.tsx
- src/features/identityCheck/components/layout/PageWithHeader.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/SetCity.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
- src/features/identityCheck/pages/profile/SetSchoolType.tsx
- src/features/identityCheck/pages/profile/Status.tsx
- src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
- src/features/profile/pages/ChangePassword/ChangePassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12340
I have:
|     |         |                 |  ![Capture d’écran 2021-12-22 à 10 14 12](https://user-images.githubusercontent.com/62059034/147067822-d44b3449-b788-489c-95ca-8079e1df6787.png) ![Capture d’écran 2021-12-22 à 10 14 03](https://user-images.githubusercontent.com/62059034/147067830-338f259c-db71-4af5-bc9e-10ffc2edcc23.png) ![Capture d’écran 2021-12-22 à 10 13 55](https://user-images.githubusercontent.com/62059034/147067835-6a53dada-cd6c-4fa8-bae6-7009cb682087.png) ![Capture d’écran 2021-12-22 à 10 13 …
> (PC-12340) feat(identityCheck): update design for web

- __snapshots__/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx.native-snap
- src/api/gen/api.ts
- src/features/bookOffer/components/BookingDetails.tsx
- src/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx
- src/features/bookOffer/fixtures/offer.ts
- src/features/bookOffer/services/__tests__/useModalContent.test.tsx
- src/features/offer/api/snaps/offerResponseSnap.ts
- src/features/offer/atoms/OfferTile.tsx
- src/features/offer/atoms/__tests__/OfferTile.native.test.tsx
- src/features/offer/atoms/__tests__/OfferTile.web.test.tsx
- src/features/offer/components/__tests__/OfferIconCaptions.native.test.tsx
- src/features/offer/components/__tests__/OfferIconCaptions.web.test.tsx
- src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts
- src/features/offer/services/useCtaWordingAndAction.testsFixtures.ts
- src/features/offer/services/useCtaWordingAndAction.ts
- src/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx
- src/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx
> (PC-11999) feat(isForbiddenToUnderage): use isForbiddenToUnderage for CTA home and search

- src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx
- src/features/recreditBirthdayNotification/pages/components/__test__/RecreditBirthdayNotification.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12457
I have:
| iPhone |
| --: |
|<img width="329" alt="Capture d’écran 2021-12-22 à 15 02 57" src="https://user-images.githubusercontent.com/90036171/147104673-c245deb3-df2a-48b7-acbe-5c545fa725d7.png">|
> (PC-12457) fix(UnderageAccountCreated): Fix creditedAmount by adding formatToFrenchDecimal

- src/features/bookings/pages/BookingNotFound.tsx
- src/features/home/pages/useShowSkeleton.ts
- src/features/identityCheck/errors/eduConnect/NotEligibleEduConnect.tsx
- src/features/offer/pages/OfferNotFound.tsx
- src/features/search/pages/Search.tsx
- src/features/venue/pages/VenueNotFound.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12461
I have:
> (PC-12461) fix(App): using globalThis.setTimeout

- __snapshots__/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx.native-snap
- src/features/bookOffer/components/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12408
I have:
> (PC-12408) fix(booking): remove unneeded scrollbar on booking confirmation modal

- __snapshots__/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx.native-snap
- src/App.web.tsx
- src/features/bookOffer/pages/BookingOfferWrapper.tsx
- src/features/offer/pages/Offer.tsx
- src/ui/components/modals/AppModal.tsx
> refactor(modal): Minor refactoring

- fastlane/Fastfile
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7627
I have:
> (PC-7627) fix(fastlane): escape release notes

- __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
- __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
- src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12432
I have:
|     |    
> (PC-12432) feat(EighteenBirthdayCard): update wording

- src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx
- src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx
- src/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.native.test.tsx
- src/features/profile/utils.test.ts
- src/fixtures/user.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12471
I have:
> (PC-12471) fix(HonorStatement): refetch /me properly and invalidate /subsciption/next_step

- src/features/search/components/CalendarPicker.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12185
Changement:
- Mois en `theme.colors.greyDark`
- Aujourd'hui en `theme.colors.greyDark`
- Dates disabled en `theme.colors.greyMedium`
- Dates enabled en `theme.colors.black`
I have:
| iOS | Android | Desktop - Chrome (avant) | Desktop - Chrome (après) | Desktop - Safari |
|     |         |  ![image](https://user-images.githubusercontent.com/77674046/147231122-8d6bc3d7-8614-4e7a-a080-839ef41d852f.png)  |![image](https://user-images.githubusercontent.com/77674046/147248161-01b9927e-ea2c-442d-8ee0-aeb62173eaec.png) |                  |
[2]: …
> (PC-12185) fix(SearchFilters): improve accessibility of react-native-calendar

- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.test.tsx.web-snap
- src/features/identityCheck/pages/profile/SetSchoolType.tsx
- src/features/identityCheck/pages/profile/__test__/utils.test.ts
- src/features/identityCheck/pages/profile/fixtures/mockedSchoolTypes.ts
- src/features/identityCheck/pages/profile/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12402
I have:
| iOS small | Android | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|    <img width="290" alt="Capture d’écran 2021-12-23 à 16 26 25" src="https://user-images.githubusercontent.com/44037911/147260774-56c2f974-d1f0-4041-a7c7-7fe6ec5d7eef.png"> |         |                 |        <img width="944" alt="Capture d’écran 2021-12-23 à 16 02 44" src="https://user-images.githubusercontent.com/44037911/147259281-228d05dc-c20b-47e9-934c-f8b7cdc8c38d.png">          |                  |
[2]: …
> (PC-12402) feat(EAC): add description to school types

- src/api/gen/api.ts
- src/features/bookings/pages/BookingDetails.tsx
in order to display the location instead of the GPS location in maps app
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8871
I have:
|avant|après|
|:--|:--|
|![image](https://user-images.githubusercontent.com/95220086/147336651-f6fc513b-fcb8-4cf4-9727-fd87fce3d42c.png)|![image](https://user-images.githubusercontent.com/95220086/147336656-e4132240-d064-4f62-87c2-8ec93917803f.png)|
> (PC-8871) feat(booking): add venue address and venue postal code

- src/features/cheatcodes/pages/AppComponents/Icons.tsx
> feat(icons): reorder icons alphabetically in cheatcodes

- __snapshots__/features/auth/signup/idCheck/DenyAccessToIdCheck.native.test.tsx.native-snap
- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/DMSModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12429
I have:
Firefox Desktop écran large
Firefox Desktop écran petit
iPhone SE
> (PC-12429) fix(modal): do not close on click on the modal

- .circleci/config.yml
- package.json
- sonar-project.properties
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12407
Sonarcube is useful to monitor code smells, code coverage, security, and bugs reports on `Pull requests` and on `push to master`.
Dashboard:
Details on bugs:
Comment on pull request:
I have:
> (PC-12407) ci(sonarcube): setup sonarcube to inspect codebase

- src/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11904
I have:
| iPhone 5S | iPhone 11 | Desktop - Chrome |
| --: | --: | --------------: |
|<img width="330" alt="Capture d’écran 2021-12-29 à 10 26 01" src="https://user-images.githubusercontent.com/90036171/147647402-db6619ad-8021-40ee-ac0c-89f071ecb290.png">|<img width="372" alt="Capture d’écran 2021-12-29 à 10 26 13" src="https://user-images.githubusercontent.com/90036171/147647367-20d60ecc-bac3-4bcc-b8f6-74cb96d0e376.png">|<img width="1680" alt="Capture d’écran 2021-12-29 à 10 26 34" src="https://user-images.githubusercontent.com/90036171/147647331-d61f4e5d-8487-4388-b285-e5d6218c9ddc.png">|
[2]: …
> (PC-11904) fix(SetBirthday): Modify deposit value for 15-18

- __snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.native-snap
- __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/QuitIdentityCheckModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ConfirmDeleteProfile.test.tsx.native-snap
- __snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.native-snap
- __snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.web-snap
- src/features/auth/signup/PhoneValidation/PhoneValidationTooManyAttempts/PhoneValidationTooManyAttempts.tsx
- src/ui/components/LayoutExpiredLink.tsx
- src/ui/components/buttons/ButtonTertiaryWhite.tsx
- src/ui/svg/icons/PlainArrowPrevious.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12540
I have:
> (PC-12540) refactor(icons): uniformize ButtonTertiaryWhite

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
- src/features/identityCheck/pages/identification/IdentityCheckUnavailable.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12530
I have:
|   <img width="331" alt="Capture d’écran 2021-12-30 à 11 09 32" src="https://user-images.githubusercontent.com/44037911/147742179-b86575d0-62f9-4c9a-806d-fc6dee90bace.png">  |         |                 |        <img width="631" alt="Capture d’écran 2021-12-30 à 10 31 00" src="https://user-images.githubusercontent.com/44037911/147739404-6e74607c-1d9c-47e8-8506-382d030867b1.png">          |                  |
[2]: …
> (PC-12530) feat(EAC): change "Transmettre un document" to open DMSModal

- src/ui/components/snackBar/SnackBar.tsx
I have:
|  <img width="321" alt="Capture d’écran 2021-12-30 à 16 47 11" src="https://user-images.githubusercontent.com/44037911/147766955-056d2485-aa90-4d05-abf5-e75976f1d66d.png">   |         |                 |                  |                  |
> fix(icons): add marginRight to snackbarText

- src/features/search/components/CalendarPicker.web.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12044
I have:
|     |         |  <img width="416" alt="Capture d’écran 2022-01-03 à 11 20 55" src="https://user-images.githubusercontent.com/62059034/147920083-02a0dec4-b74d-47c0-a7de-7f3fd2258b9c.png"> <img width="415" alt="Capture d’écran 2022-01-03 à 10 10 21" src="https://user-images.githubusercontent.com/62059034/147915873-69c24a02-f51e-46a4-bbee-ec772bac3a98.png">   |                  |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur …
> (PC-12044) fix(calendarPicker): fix error message

- doc/development/localApi.md
- scripts/generate_api_client.sh
2 commits qui trainait sur une vieille branche d'un ticket qui a finalement été remplacé par un autre
I have:
> docs(wording): minor stuffs

- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/ui/components/buttons/externalLink/ExternalLink.tsx
- src/ui/components/buttons/externalLink/ExternalLink.web.tsx
- src/ui/components/buttons/externalLink/__tests__/ExternalLink.web.test.tsx
I have:
|     |     
|          
|                  |                  |
> (PC-12528) feat(ExternalLink): do not break icon text

- __snapshots__/features/bookOffer/components/__tests__/BookingImpossible.deprecated.native.test.tsx.native-snap
- src/features/bookOffer/components/BookingImpossible.tsx
- src/features/bookOffer/components/__tests__/BookingImpossible.deprecated.native.test.tsx
- src/features/bookOffer/components/__tests__/BookingImpossible.deprecated.web.test.tsx
- src/features/bookOffer/components/__tests__/BookingImpossible.test.tsx
- src/features/navigation/RootNavigator/types.ts
- src/libs/analytics/analytics.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8274
I have:
| iOS | Android | Web |
| :--: | :--: | :--: |
|![image](https://user-images.githubusercontent.com/95220086/147678408-359a53ed-b025-4e19-aa37-1ef73417bf2a.png)|N/A|N/A|
> (PC-8274) feat(favorite): add button to close modal when booking impossible

- src/features/auth/__mocks__/support.services.ts
- src/features/auth/signup/SignupConfirmationEmailSent/tests/SignupConfirmationExpiredLink.native.test.tsx
- src/features/auth/signup/SignupConfirmationEmailSent/tests/SignupConfirmationExpiredLink.web.test.tsx
- src/features/auth/signup/SignupConfirmationExpiredLink/SignupConfirmationExpiredLink.tsx
- src/features/auth/support.services.test.ts
- src/features/auth/support.services.ts
- src/libs/analytics/analytics.ts
> refactor(contactSupport): clean unused code

- src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12453
retour de revue graphique
I have:
|Firefox Desktop large|FF Desktop|iPhone SE|
|:--|:--|:--|
|![image](https://user-images.githubusercontent.com/95220086/148040906-c4b354e9-d7eb-46c9-9c42-344a42e65995.png)|![image](https://user-images.githubusercontent.com/95220086/148041038-9d441de9-0412-4a6c-bf6e-83e94e770ea0.png)|![image](https://user-images.githubusercontent.com/95220086/148041067-e38e0f65-9f4c-417d-a041-dbdec6e24dd9.png)|
> (PC-12453) fix(phone): add space between text and button

- src/features/bookOffer/components/BookingImpossible.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8274
I have:
> (PC-8274) feat(favorite): close modal before navigating to offer

- src/libs/analytics/analytics.native.test.ts
- src/libs/analytics/provider.ts
- src/libs/analytics/provider.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12600
I have:
> (PC-12600) feat(analytics): add agent type to each event

- package.json
- src/features/bookOffer/components/BookHourChoice.tsx
- src/features/bookOffer/components/BookingImpossible.tsx
- src/features/bookOffer/services/useNotifyWebappLinkSent.ts
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
- src/features/search/utils/availableCategories.ts
- src/features/search/utils/tests/availableCategories.test.ts
- yarn.lock
> refactor(lodash): prefer specific import of lodash libs

- src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12453
* changement de wording mineur
* réalignement sur l'axe vertical du texte et du bouton
* retour à la ligne sur les petits écrans
I have:
> (PC-12453) fix(phone): break line on small devices

- src/libs/analytics/provider.ts
- src/libs/analytics/provider.web.ts
- src/libs/analytics/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12600
I have:
> (PC-12600) fix(analytics): send agentType for events without params

- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.native-snap
- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.web-snap
- __snapshots__/ui/svg/__tests__/PhoneError.test.tsx.native-snap
- __snapshots__/ui/svg/__tests__/PhoneError.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/Illustrations.tsx
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/errors/pages/ScreenErrorProvider.tsx
- src/features/landscapePosition/LandscapePositionPage.tsx
- src/features/landscapePosition/tests/LandscapePositionPage.test.tsx
- src/features/landscapePosition/useIsLandscapePosition.tsx
- src/features/landscapePosition/useIsLandscapePosition.web.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
- src/ui/svg/PhoneError.tsx
- src/ui/svg/__tests__/PhoneError.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12596
https://user-images.githubusercontent.com/43779561/148363228-b2c9017c-2dee-4ff3-8425-baeacda3b89c.mp4
I have:
> (PC-12596) feat(LandscapePositionPage): display blocking page on mobile browser on landscape mode

- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/ui/components/accessibility/AccessibilityAtom.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12641
I have:
> (PC-12641) fix(accessibility): make sure handicap icon fits

- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- __snapshots__/ui/components/inputs/PasswordInput.native.test.tsx.native-snap
- src/ui/components/inputs/PasswordInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12642
I have:
> (PC-12642) fix(password): align eye icon to the right

- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.native-snap
- src/features/landscapePosition/LandscapePositionPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12695
I have:
> (PC-12695) fix(LandscapePositionPage): fix unit test

- src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12454
I have:
> (PC-12454) fix(IdentityCheckValidation): navigate explicitly to stepper on web

- src/features/bookOffer/components/Calendar/Calendar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12552
I have:
> (PC-12552) fix(calendar): reduce size of previous/next icons

- src/features/identityCheck/pages/errors/EduConnectErrors.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12678
Un merci à  AETHLIOS pour avoir permis d'améliorer cette partie du code source.
Voir avec @viconnex ou Mariam pour compléter la validation.
I have:
> (PC-12678) fix(YWHPGM244615): Open redirect security fix

- __mocks__/react-native-modal.tsx
- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.native-snap
- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.web-snap
- jest/jest.setup.ts
- jest/jest.web.setup.ts
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/errors/pages/ScreenErrorProvider.tsx
- src/features/landscapePosition/LandscapePositionPage.tsx
- src/features/landscapePosition/tests/LandscapePositionPage.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12596
I have:
- [ x] Made sure the title of my PR follows the [convention](1) `($jira) $type($scope): $summary`.
|     |         |           
|                  |                  |
> (PC-12596) feat(LandscapePositionPage): dio not reload under content

- .circleci/config.yml
> ci(node): ensure to use the right version before installing node modules

- .circleci/config.yml
Check if cache is preventing app from building
> build(node): update node_modules cache after node upgrade

- .circleci/config.yml
> ci(gcp): we didn't build `node-gcp:16` yet

- __snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- src/features/auth/components/PasswordSecurityRules.tsx
- src/features/auth/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx
- src/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx
- src/features/auth/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx
- src/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx
- src/features/auth/login/Login.native.test.tsx
- src/features/auth/login/Login.tsx
- src/features/auth/signup/SetEmail/SetEmail.native.test.tsx
- src/features/auth/signup/SetEmail/SetEmail.tsx
- src/features/cheatcodes/pages/AppComponents/Icons.tsx
- src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
- src/features/profile/pages/ChangeEmail/utils/useValidateEmail.test.ts
- src/features/profile/pages/ChangeEmail/utils/useValidateEmail.ts
- src/features/profile/pages/ChangePassword/ChangePassword.tsx
- src/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx
- src/locales/fr/messages.po
- src/ui/components/inputs/EmailInput.tsx
- src/ui/components/inputs/InputError.tsx
- src/ui/components/inputs/LabelContainer.tsx
- src/ui/components/inputs/PasswordInput.tsx
- src/ui/components/inputs/RequiredLabel.tsx
- src/ui/components/inputs/rules/InputRule.tsx
- src/ui/components/inputs/types.ts
- src/ui/svg/icons/Key.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12175
I have:
|   ![Capture d’écran 2022-01-10 à 14 10 14](https://user-images.githubusercontent.com/62059034/148771455-293f7c1e-3dac-4add-99f7-04f1b591edbf.png)  ![Capture d’écran 2022-01-10 à 14 10 01](https://user-images.githubusercontent.com/62059034/148771465-ee839c30-3ac0-4c48-8581-5ad0172fca10.png)  ![Capture d’écran 2022-01-10 à 14 14 08](https://user-images.githubusercontent.com/62059034/148772006-a0a41920-e291-4d41-8314-b7b53c9b838f.png) ![Capture d’écran 2022-01-10 à 14 13 12](https://user-images.githubusercontent.com/62059034/148772298-9029d26b-602b-4b10-be18-7 …
> (PC-12175) feat(accessibility): add require label for forms with multiple inputs

- .circleci/config.yml
je pense que le problème c'est qu'il n'execute pas `$BASH_ENV`
https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/12351/workflows/fee9f4c2-0a39-414e-87a7-e2eaf2e5162b/jobs/35250
I have:
> fix(ci): simplify CI

- src/features/identityCheck/pages/identification/IdentityCheckEnd.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckEnd.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12724
I have:
> (PC-12724) feat(identityCheck): add navigateToHome if !nextSubcriptionStep for IdentityCheck

- .circleci/config.yml
> ci(node): upgrade NVM to have `--default` option

- src/features/home/components/ExclusivityModule.tsx
- src/features/home/components/ExclusivityModule.utils.tsx
- src/features/home/components/tests/ExclusivityModule.native.test.tsx
- src/features/home/components/tests/ExclusivityModule.utils.test.ts
- src/features/home/components/tests/ExclusivityModule.web.test.tsx
- src/features/search/components/SearchBox.tsx
- src/features/search/components/__tests__/SearchBox.test.tsx
- src/libs/search/useParseSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12693
I have:
Pour le commit n°2 (connecté avec bene_15):
- Avant
- Après
> (PC-12693) fix(search): do not show offers which price is above user max credit

- src/features/search/atoms/Buttons/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12699
I have:
> (PC-12699) fix(Search): change type of button to submit

- src/features/auth/login/Login.native.test.tsx
- src/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx
- src/features/firstLogin/CulturalSurvey.native.test.tsx
- src/features/firstLogin/helpers.tsx
- src/features/identityCheck/pages/confirmation/__test__/BeneficiaryRequestSent.test.tsx
- src/features/navigation/__tests__/useInitialScreenConfig.native.test.tsx
as the condition is now checked in the backend
See: https://github.com/pass-culture/pass-culture-main/pull/795/commits/e8f6c2b3761e1d7b5223478539bcc3739450bd48#diff-897cae4b5ded6b942475f226f8214d3d5d4624fa2d446043efd819a0c8fe7976R269
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12565
I have:
> (PC-12565) fix(culturalSurvey): remove unnecessary condition

- __snapshots__/features/home/components/tests/BusinessModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/BusinessModule.web.test.tsx.web-snap
- src/features/home/components/BusinessModule.tsx
- src/features/home/components/tests/BusinessModule.native.test.tsx
- src/features/home/components/tests/BusinessModule.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12657
I have:
> (PC-12657) feat(businessModule): disable when no URL

- jest/jest.setup.ts
- public/manifest.json
- src/features/bookings/pages/BookingNotFound.tsx
- src/features/offer/pages/OfferNotFound.tsx
- src/features/venue/pages/VenueNotFound.tsx
- src/libs/i18n.native.test.ts
- src/locales/fr/messages.po
https://passcultureteam.slack.com/archives/C02GU0WU8UA/p1642154760029400?thread_ts=1642154621.029100&cid=C02GU0WU8UA
I have:
> feat(wording): reword to lowercase `Pass Culture` -> `pass Culture`

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12698
I have:
> (PC-12698) ci(fix): deploy

- src/libs/parsers/highlightLinks.tsx
- src/libs/parsers/tests/highlightLinks.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9881
I have:
[2]: https://www.notion.so/passcultureapp/Safari-et-RegExp-Lookahead-Lookbehind-b881e151e62f48aabf6724647eb0ed5f
> (PC-9881) feat(url): highlight URL even without http://

- src/features/home/pages/useOfferModule.ts
- src/libs/search/useParseSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12760
I have:
> (PC-12760) fix(home): refresh offer modules when user become beneficiary

- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
https://passculture.atlassian.net/browse/PC-12807
testé sur Safari et Chrome
> (PC-12807) feat(IdentityCheckEduConnectForm): open educonnect tab on safari

- __snapshots__/ui/svg/__tests__/PhoneError.test.tsx.native-snap
- __snapshots__/ui/svg/__tests__/PhoneError.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/Illustrations.tsx
- src/features/errors/pages/AsyncErrorBoundary.tsx
- src/ui/svg/BrokenConnection.tsx
- src/ui/svg/PhoneError.tsx
- src/ui/svg/icons/BicolorPhonePending.tsx
- src/ui/theme/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12857
I have:
> (PC-12857) refactor(Icons): unify illustration formatting

- ios/Podfile.lock
- package.json
- yarn.lock
> fix(build): update react-native-appsflyer

- src/features/bookOffer/components/Calendar/Calendar.tsx
- src/features/bookings/components/OnGoingBookingItem.tsx
- src/features/favorites/atoms/Buttons/Sort.tsx
- src/features/favorites/atoms/Favorite.tsx
- src/features/favorites/pages/FavoritesSorts.tsx
- src/features/home/components/HomeHeader.tsx
- src/features/identityCheck/atoms/form/RadioButton.tsx
- src/features/identityCheck/atoms/layout/PageHeader.tsx
- src/features/search/atoms/Buttons/Filter.tsx
- src/features/search/atoms/Hit.tsx
- src/features/search/atoms/SelectionLabel.tsx
- src/features/search/components/LocationChoice.tsx
- src/features/search/components/SearchLandingPage.tsx
- src/features/search/pages/Categories.tsx
- src/features/search/pages/SuggestedPlaces.tsx
- src/features/search/sections/Location.tsx
- src/features/venue/components/VenueIconCaptions.tsx
- src/libs/geolocation/components/WhereSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12958
I have:
> (PC-12958) fix(activeOpacity): remove constant import in profit of theme.activeOpacity

- src/features/bookings/components/BookingDetailsHeader.tsx
- src/features/favorites/atoms/BicolorFavoriteCount.tsx
- src/features/home/atoms/Cover.tsx
- src/features/home/components/HomeHeader.tsx
- src/features/search/components/SearchHeader.tsx
- src/ui/components/Playlist.tsx
- src/ui/components/bars/ProgressBar.tsx
- src/ui/components/modals/ModalHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12961
I have:
> (PC-12961) fix(ZIndex): remove usage of constant in profit theme.zIndex

- .circleci/config.yml
according to https://github.com/pass-culture/pass-culture-main/commit/24d7ceddcd06615ee5053af846f7713a574ab93a
I have:
> ci(web): fix invalidate cache step

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/DMSModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
- src/features/home/atoms/SkeletonTile.tsx
- src/features/home/atoms/VenueTile.tsx
- src/features/identityCheck/pages/confirmation/UnderageAccountCreated.tsx
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/navigation/RootNavigator/Header/NavItem.tsx
- src/features/profile/pages/NotificationSettings.native.test.tsx
- src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx
- src/theme/index.ts
- src/ui/components/FilterSwitch.tsx
- src/ui/components/bars/ProgressBar.tsx
- src/ui/components/modals/AppModal.tsx
- src/ui/svg/BackgroundSecondary.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12964
I have:
> (PC-12964) fix(UniqueColors): fix uniqueColors in theme and usage of theme

- __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.native.test.tsx.native-snap
- __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.web.test.tsx.web-snap
- src/features/errors/pages/AsyncErrorBoundary.tsx
- src/ui/components/GenericInfoPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12953
I have:
> (PC-12953) fix(AsyncErrorBoundary): using template from GenericInfoPage

- __snapshots__/features/home/components/tests/BusinessModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/BusinessModule.web.test.tsx.web-snap
- src/features/home/components/BusinessModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12657
I have:
| avant | Après |
|   ![image](https://user-images.githubusercontent.com/95220086/150373571-38e56cf3-7f9f-457d-be7e-0b777d9b20cd.png)  |    ![image](https://user-images.githubusercontent.com/95220086/150373281-96be4c87-25c4-4d80-a039-e4b144318843.png)     |
> (PC-12657) feat(home): remove arrow on business module when no url

- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/IconWithCaption.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/VenueType.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- src/features/bookOffer/atoms/ChoiceBloc.tsx
- src/features/favorites/atoms/Buttons/Sort.tsx
- src/features/home/atoms/Cover.tsx
- src/features/home/atoms/VenueTile.tsx
- src/features/home/components/BusinessModule.tsx
- src/features/home/components/ExclusivityModule.tsx
- src/features/identityCheck/atoms/StepButton.tsx
- src/features/offer/atoms/OfferTile.tsx
- src/features/search/atoms/Buttons/Filter.tsx
- src/features/venue/atoms/IconWithCaption.tsx
- src/ui/components/ClippedTag.tsx
- src/ui/components/ImageCaption.tsx
- src/ui/components/ModuleBanner/ModuleBanner.tsx
- src/ui/components/accessibility/AccessibilityAtom.tsx
- src/ui/components/buttons/AppButton.tsx
- src/ui/components/hero/useHeroDimensions.tsx
- src/ui/components/inputs/CheckboxInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12971
I have:
> (PC-12971) fix(BorderRadiusEnum): usage of theme.borderRadius instead of constants

- src/features/offer/components/ReportOfferOtherReason.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12849
I have:
> (PC-12849) feat(accessiblity): add Form to ReportOfferOtherReason

- __mocks__/uuid.ts
- __snapshots__/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/bookOffer/components/BookingDetails.tsx
- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchLandingPage.tsx
- src/features/search/pages/LocationPicker.tsx
- src/locales/fr/messages.po
- src/ui/components/HiddenText.tsx
- src/ui/components/buttons/AppButton.tsx
- src/ui/components/inputs/SearchInput.tsx
- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12665
I have:
|     |         |                 |  Champ recherche :<br/> <img width="242" alt="Capture d’écran 2022-01-21 à 15 51 26" src="https://user-images.githubusercontent.com/46637324/150547798-0da31e9b-e306-460e-8f1a-d8fa16afe5a2.png">     |                  |
|     |         |                 |  Filtre "Je cherche" :<br/> <img width="242" alt="Capture d’écran 2022-01-21 à 15 55 11" src="https://user-images.githubusercontent.com/46637324/150548662-b136c602-4d30-4aac-ba1d-b7f8445b24bc.png">       |                  |
|     |         |                 |  Filtre "Où" …
> (PC-12665) feat(accessiblity): add aria-describedby to search and to booking confirmation

- src/ui/components/inputs/DateInput.native.test.tsx
- src/ui/components/inputs/DateInput.tsx
- src/ui/components/inputs/DateInput.web.test.tsx
> (fix)linter: fix errors

- ios/PassCulture/AppDelegate.m
- src/features/navigation/RootNavigator/linking/getInitialUrl.ios.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13105
I have:
> (PC-13105) fix(batch): correct initialisation to open notifs on ios

- __snapshots__/features/favorites/components/__tests__/NotConnectedFavorites.test.tsx.native-snap
- src/features/favorites/atoms/Favorite.tsx
- src/features/favorites/components/NoFavoritesResult.tsx
- src/features/favorites/components/NotConnectedFavorites.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12955
I have:
> (PC-12955) fix(Favorites): remove usage of AppButtons in favorites

- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- src/features/auth/components/PasswordSecurityRules.tsx
- src/features/search/pages/SuggestedPlaces.tsx
- src/locales/fr/messages.po
- src/ui/components/AriaLive.tsx
- src/ui/components/AriaLive.web.tsx
- src/ui/components/inputs/rules/PasswordRule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12997
I have:
|     |         |                 |                  |  1 critère validé <br/> <img width="195" alt="Capture d’écran 2022-01-25 à 12 23 24" src="https://user-images.githubusercontent.com/46637324/150968803-16be9e41-4a76-4ee4-9606-ad20ffb416d9.png"><img width="483" alt="Capture d’écran 2022-01-25 à 12 23 40" src="https://user-images.githubusercontent.com/46637324/150968821-b304ce7b-89eb-4069-a62b-61153de53d6a.png">  |
|     |         |                 |                  |  Tous les critères sont validés <br/> <img width="194" alt="Capture d’écran 2022-01-25 à …
> (PC-12997) feat(accessiblity): add aria-live to announce password rules validation

- package.json
- web/config/webpack.config.js
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13048
I have:
> (PC-13048) fix(Web): added plugin babel-plugin-styled-components

- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/RootNavigator.tsx
- src/ui/web/global/Main.tsx
- src/ui/web/global/Main.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13001
I have:
|     |         |                 |                   <img width="270" alt="Capture d’écran 2022-01-25 à 17 46 40" src="https://user-images.githubusercontent.com/46637324/151021104-21c306c6-fdeb-4ec6-b7e6-b480b8ab256c.png"> |   |
> (PC-13001) feat(accessibility): Wrap all pages in main tag

- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/ui/components/headers/PageHeader.tsx
- src/ui/components/modals/ModalHeader.tsx
- src/ui/web/global/Header.tsx
- src/ui/web/global/Header.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12999
I have:
|     |         |                 |                    <img width="1058" alt="Capture d’écran 2022-01-26 à 16 17 32" src="https://user-images.githubusercontent.com/46637324/151192094-005a6ed7-1082-47a5-a09a-44c46f0071ba.png">    |     |
|     |         |                 |                   <img width="300" alt="Capture d’écran 2022-01-26 à 16 16 59" src="https://user-images.githubusercontent.com/46637324/151192476-f5abe688-3f51-45f5-b918-13ad699172fb.png">    |   |
|     |         |                 |                   <img width="200" alt="Capture d’écran …
> (PC-12999) feat(accessiblity): add header tags

- src/features/navigation/RootNavigator/Header/Nav.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13000
I have:
|     |         |                 |   <img width="986" alt="Capture d’écran 2022-01-26 à 17 40 04" src="https://user-images.githubusercontent.com/46637324/151206776-0c16cf80-a8dd-4c5c-a370-dbccc45a7468.png">   |        |
> (PC-13000) feat(accessibility): Add nav tag to web navigation header

- src/features/home/pages/Home.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13134
I have:
> (PC-13134) fix(exclusivity): make sure module has display parameters

- src/features/bookings/components/OnGoingBookingsList.native.test.tsx
- src/features/bookings/components/OnGoingBookingsList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13138
I have:
j'ai testé avec cette offre https://app.testing.passculture.team/offre/190
> (PC-13138) fix(bookings): crash with new subcategories

- babel.config.js
- package.json
- src/ui/components/inputs/nameCheck.test.ts
- src/ui/components/inputs/nameCheck.ts
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13089
I have:
> (PC-13089) fix(signup): check that name contain only latin and allowed characters

- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx
- src/features/navigation/RootNavigator/Header/Nav.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12840
I have:
> (PC-12840) fix(accessibility): Make Link inaccessible to avoid duplicate focus

- src/theme/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12960
I have:
> (PC-12960) fix(Quaternary): set PRIMARY for quaternary button icon color

- ios/Podfile.lock
- package.json
- src/features/navigation/RootNavigator/linking/subscribe.ios.ts
- src/libs/appState.ts
- src/libs/react-query/ReactQueryClientProvider.tsx
- yarn.lock
https://github.com/oblador/react-native-keychain/releases
> build(security): clean warnings due to removeEventListener

- doc/customize/icons.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13248
I have:
> (PC-13248) docs(icons): update icons documentation to use theme

- __snapshots__/ui/components/buttons/__tests__/ScrollButtonForNotTouchDevice.test.tsx.native-snap
- __snapshots__/ui/components/buttons/__tests__/ScrollButtonForNotTouchDevice.test.tsx.web-snap
- src/locales/fr/messages.po
- src/theme/index.ts
- src/ui/components/Playlist.tsx
- src/ui/components/buttons/ScrollButtonForNotTouchDevice.tsx
- src/ui/components/buttons/__tests__/ScrollButtonForNotTouchDevice.test.tsx
- src/ui/svg/icons/BicolorArrowRight.tsx
I have:
|     |         |                 |                  |         
|
> (PC-12604) feat(ScrollButtonForNotTouchDevice): make next caroussel accessible

- src/features/navigation/RootNavigator/Header/NavItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13114
I have:
|     |         |                 |       <img width="262" alt="Capture d’écran 2022-02-02 à 18 18 05" src="https://user-images.githubusercontent.com/46637324/152204042-8362729e-e010-4880-b6a4-9bb116019809.png">           |                  |
> (PC-13114) fix(accessibility): Fix nav item color when selected

- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
- src/ui/components/inputs/TextInput.tsx
- src/ui/components/inputs/addressCheck.test.ts
- src/ui/components/inputs/addressCheck.ts
- src/ui/components/inputs/nameCheck.test.ts
- src/ui/components/inputs/nameCheck.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13202
I have:
> (PC-13202) feat(signup): add required field to set name

- src/ui/components/inputs/addressCheck.test.ts
- src/ui/components/inputs/addressCheck.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13202
I have:
> (PC-13202) feat(signup): align address regex with backend

- src/ui/svg/Background.tsx
- src/ui/svg/BackgroundSecondary.tsx
- src/ui/svg/ImagePlaceholderVenue.tsx
- src/ui/svg/Rectangle.tsx
- src/ui/svg/icons/BicolorSelector.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13249
I have:
> (PC-13249) fix(UI): Fix background display on mobile

- __snapshots__/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/bookOffer/components/__tests__/BookingInformations.test.tsx.native-snap
- __snapshots__/features/bookOffer/components/__tests__/BookingInformations.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- src/features/bookOffer/components/BookingInformations.tsx
- src/ui/components/Banner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13296
I have:
| FF avant | FF après |
|![image](https://user-images.githubusercontent.com/95220086/152542889-f52f50d4-2ddc-4100-b844-0d4d95d3441a.png)   | ![image](https://user-images.githubusercontent.com/95220086/152557723-ec0fb8f7-b822-4310-bd3f-4709291921c5.png)|
> (PC-13296) fix(booking): icon on small device

- __snapshots__/features/home/components/tests/NoContentError.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/favorites/pages/FavoritesSorts.tsx
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
- src/features/home/components/NoContentError.tsx
- src/features/identityCheck/components/FastEduconnectConnectionRequestModal.tsx
- src/features/profile/pages/ConsentSettings.tsx
- src/features/profile/pages/NotificationSettings.tsx
- src/libs/share/WebShareModal.web.tsx
- src/theme/index.ts
- src/ui/components/buttons/AppButton.tsx
- src/ui/theme/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13300
I have:
:warning:  , sur le bouton Rechercher une offre de la page NoContentError.ts des customisations on été enlevé à prioris sans changement, bien retester sur iOS., Android et Web (iconSize, width et padding du button)
| iOS | Android | Mobile - Chrome | Desktop - avant | Desktop - après |
|     |         |                 | ![image](https://user-images.githubusercontent.com/77674046/152759801-693097f9-0ae3-4f07-a685-84841650 …
> (PC-13300) fix(Button): remove customization done userland on Buttons

- src/features/profile/pages/NotificationSettings.tsx
- src/ui/components/FilterSwitch.tsx
- src/ui/web/inputs/HiddenCheckbox.tsx
- src/ui/web/inputs/HiddenCheckbox.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12862
I have:
> (PC-12862) feat(accessibility): Use hidden checkbox with filter switch

- .github/workflows/chromatic.yml
- package.json
- src/ui/components/buttons/ButtonPrimary.stories.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13111
I have:
> (PC-13111) feat(storybook): add chromatic for better code review of components

- __snapshots__/features/identityCheck/components/layout/PageWithHeader.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnectForm.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckValidation.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/Status.web.test.tsx.web-snap
- __snapshots__/features/profile/components/SectionWithSwitch.test.tsx.native-snap
- __snapshots__/features/profile/components/SectionWithSwitch.test.tsx.web-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- src/features/auth/signup/SetEmail/SetEmail.tsx
- src/features/identityCheck/atoms/layout/PageHeader.tsx
- src/features/identityCheck/pages/Stepper.tsx
- src/features/profile/components/BeneficiaryHeader.tsx
- src/features/profile/components/LoggedOutHeader.tsx
- src/features/profile/components/SectionWithSwitch.tsx
- src/features/profile/pages/NotificationSettings.tsx
- src/features/search/atoms/SelectionLabel.tsx
- src/features/search/components/SectionWithSwitch.tsx
- src/ui/components/FilterSwitch.tsx
- src/ui/components/InputLabel.tsx
- src/ui/web/inputs/HiddenCheckbox.tsx
- src/ui/web/inputs/HiddenCheckbox.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13224
I have:
> (PC-13224) feat(accessibility): Use hidden checkbox with newsletter checkbox and search filters

- .storybook/main.js
- .storybook/preview.js
- src/ui/components/buttons/ButtonPrimary.stories.tsx
- src/ui/components/hero/Hero.stories.tsx
> test(storybook): add stories

- __snapshots__/features/favorites/atoms/__tests__/Favorite.native.test.tsx.native-snap
- src/features/favorites/atoms/Favorite.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13130
I have:
|     | ![image](https://user-images.githubusercontent.com/77674046/153196996-31d4a945-54da-4fc8-aa2d-3ca10c7a6cf7.png)        | ![image](https://user-images.githubusercontent.com/77674046/153197071-9f466c18-a0bb-44fd-9635-e30c910b4186.png)  |                  |                  |
> (PC-13130) fix(Favorite): add hyperlinks to favorite

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- src/features/auth/signup/SetBirthday/DatePicker/DatePickerTouch.web.tsx
- src/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13388
I have:
|  ![Capture d’écran 2022-02-09 à 17 56 12](https://user-images.githubusercontent.com/62059034/153250588-489880d5-da98-4b0e-af58-265040a63402.png) ![Capture d’écran 2022-02-09 à 17 56 02](https://user-images.githubusercontent.com/62059034/153250591-91a93cb3-a6f9-4c4b-9406-4514fba08945.png) ![Capture d’écran 2022-02-09 à 17 57 34](https://user-images.githubusercontent.com/62059034/153250583-8b83a0fc-5b72-4e3a-9f9b-00833b7cd910.png) |         |       ![Capture d’écran 2022-02-09 à 17 53 43](https://user-images.githubusercontent.com/62059034/153250087-14ef434f-e …
> (PC-13388) fix(SetBirthday): fix minimum date for ios / android / web touch spinner

- __snapshots__/features/favorites/atoms/__tests__/Favorite.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/ExclusivityModule.web.test.tsx.web-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.web.test.tsx.web-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.web-snap
- src/features/bookings/components/EndedBookingItem.tsx
- src/features/bookings/components/OnGoingBookingItem.tsx
- src/features/bookings/pages/BookingDetails.tsx
- src/features/bookings/pages/EndedBookingsSection.tsx
- src/features/home/atoms/SeeMore.tsx
- src/features/home/components/ExclusivityModule.tsx
- src/features/home/components/OffersModule.tsx
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/offer/atoms/OfferSeeMore.tsx
- src/features/offer/atoms/OfferTile.tsx
- src/features/profile/pages/Profile.tsx
- src/features/search/atoms/Hit.tsx
- src/features/venue/components/VenueOffers.tsx
- src/libs/geolocation/components/WhereSection.tsx
- src/ui/components/PassPlaylist.tsx
- src/ui/web/link/Link.tsx
- src/ui/web/link/Link.web.tsx
- src/ui/web/link/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13383
I have:
> (PC-13383) fix(A11y): added hyperlinks on client navigation

- src/features/search/atoms/Hit.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13383
I have:
> (PC-13383) fix(Search): fix hyperlink

- src/libs/algolia/__tests__/fetchMultipleVenues.test.ts
- src/libs/algolia/enums/facetsEnums.ts
- src/libs/algolia/fetchAlgolia/fetchMultipleVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12482
I have:
> (PC-12482) feat(tags): filter venues by tags on homepage

- src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12669
I have:
> (PC-12669) feat(accessibility): Make slider controllable with keyboard

- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- patches/@ptomasroos+react-native-multi-slider+2.2.2.patch
- src/features/navigation/helpers/useCurrentRoute.ts
- src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12669
I have:
> (PC-12669) fix(accessibility): Change query selector attribute to control slider

- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/libs/monitoring/__tests__/services.native.test.ts
- src/libs/monitoring/config.ts
- web/config/paths.js
- web/config/webpack.config.js
> (PC-10087) fix(Web): configure webpack sourcemaps

- src/libs/monitoring/config.web.ts
> (PC-10087) build(Sentry): add dist to web sdk init

- src/libs/monitoring/__tests__/services.web.test.ts
> (PC-10087) test(Web): fix test

- src/ui/components/ImagePlaceholder.stories.tsx
> feat(storybook): add ImagePlaceholder

- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx.native-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx.web-snap
- __snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.native-snap
- __snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.web-snap
- src/features/auth/login/Login.tsx
- src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
- src/features/favorites/atoms/BookingButton.tsx
- src/features/favorites/atoms/Favorite.tsx
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/SetCity.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
- src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
- src/features/profile/pages/ChangePassword/ChangePassword.tsx
- src/features/profile/pages/ConsentSettings.tsx
- src/features/profile/pages/NotificationSettings.tsx
- src/features/search/atoms/Buttons/Filter.tsx
- src/libs/accessibilityAndTestId.web.ts
- src/locales/fr/messages.po
- src/ui/components/LayoutExpiredLink.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13390
I have:
> (PC-13390) feat(accessibility): Add accessibility label to buttons

- src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
- src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx
- src/features/profile/pages/ChangeEmail/utils/useValidateEmail.test.ts
- src/features/profile/pages/ChangeEmail/utils/useValidateEmail.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12882
I have:
> (PC-12882) feat(changeEmail): disable submitButton if email is empty in ChangeEmail

- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
- __snapshots__/features/home/atoms/tests/SeeMore.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/navigation/RootNavigator/Header/tests/Header.web.test.tsx
- src/ui/components/ClippedImage.tsx
- src/ui/theme/shadow.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13023
I have:
> (PC-13023) fix(shadows): Update shadows for offer images, booking images and main header

- src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13300
I have:
| --: | ------: | --------------: | ---------------: | ---------------: | 
|  ![image](https://user-images.githubusercontent.com/46637324/154500783-43724c7a-a9e4-4f9e-9797-1a69ed05f3a2.png)   |    ![image](https://user-images.githubusercontent.com/46637324/154500697-1e062dd7-99c1-4573-8001-2c4cee69c502.png)     |                |      <img width="1440" alt="Capture d’écran 2022-02-17 à 15 38 50" src="https://user-images.githubusercontent.com/46637324/154504856-7c2b92b5-cb01-48d8-91ef-5e73df951cb0.png">      |
[2]: …
> (PC-13300) fix(PhoneValidation): Fix phone validation modal

- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
- __snapshots__/features/home/atoms/tests/SeeMore.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/navigation/RootNavigator/Header/tests/Header.web.test.tsx
- src/ui/components/ClippedImage.tsx
- src/ui/theme/shadow.ts
This reverts commit 4f477ed1ea67b4705a50ce075264ed7064fef6bb.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13023
I have:
> (PC-13023) fix(shadows): Revert because of bad color node module

- package.json
- src/libs/environment/__mocks__/envFixtures.ts
- src/libs/environment/types.ts
- src/libs/monitoring/__tests__/services.web.test.ts
- src/libs/monitoring/config.web.ts
- web/config/webpack.config.js
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13560
I have:
> (PC-13560) fix(Web): added -web suffix and -web-$hash to dist

- src/features/bookings/components/EndedBookingItem.tsx
- src/ui/components/ClippedImage.native.test.tsx
- src/ui/components/ClippedImage.tsx
- src/ui/components/ClippedImage.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13299
I have:
| Before | After | 
| --: | --------: | 
| ![image](https://user-images.githubusercontent.com/78556024/154651468-31b02702-b7d7-459a-9f1c-a92117f31165.png) |<img width="336" alt="Capture d’écran 2022-02-17 à 18 32 04" src="https://user-images.githubusercontent.com/78556024/154649828-9c3cf168-a26a-4517-8f73-b99d038c36cc.png">              |                
> (PC-13299) fix(bookings): ended booking list ui

- src/api/gen/api.ts
- src/features/cheatcodes/pages/AppComponents/Icons.tsx
- src/features/home/atoms/VenueCaption.tsx
- src/features/home/atoms/tests/VenueCaption.test.tsx
- src/features/search/enums.ts
- src/features/venue/atoms/VenueType.tsx
- src/features/venue/components/VenueIconCaptions.tsx
- src/features/venue/pages/VenueBody.tsx
- src/libs/algolia/fetchAlgolia/fetchMultipleVenues.ts
- src/libs/parsers/venueType.ts
- src/libs/search/index.ts
- src/ui/components/hero/Hero.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10099
I have:
> (PC-10099) build(api): generate API schema [part 1/2]

- src/api/gen/api.ts
- src/features/home/atoms/VenueTile.tsx
- src/features/venue/pages/VenueBody.tsx
- src/libs/algolia/algolia.d.ts
- src/libs/algolia/fetchAlgolia/fetchMultipleVenues.ts
- src/libs/algolia/fetchAlgolia/index.ts
- src/libs/algolia/fetchAlgolia/transformAlgoliaHit.ts
- src/libs/algolia/mockedResponses/mockedVenues.ts
- src/libs/firestore/types.ts
- src/libs/search/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10099
I have:
| Details | Home |
| --- | --- |
| <img width="357" alt="Capture d’écran 2022-02-21 à 10 53 38" src="https://user-images.githubusercontent.com/10118284/154933064-12582ab4-c12e-4063-86e4-106578540efd.png"> | <img width="343" alt="image" src="https://user-images.githubusercontent.com/10118284/154939029-55177171-5856-46ae-a811-487160d35aa2.png"> |
> (PC-10099) feat(venue): show bannerUrl on home and venue details

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- src/features/bookings/components/ThreeShapesTicket.web.tsx
- src/ui/svg/TicketFooter.tsx
- src/ui/svg/TicketHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13020
I have:
> (PC-13020) fix(Ticket): Add border to the reservation ticket

- src/libs/react-query/queryClient.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13582
I have:
> (PC-13582) feat(cache): consider requests as stale by default

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13561
I have:
> (PC-13461) feat(DropDown): update snapshot

- android/app/build.gradle
- ios/PassCulture.xcodeproj/project.pbxproj
- scripts/deploy.sh
- scripts/upload_sourcemaps_to_sentry.sh
- src/libs/monitoring/__tests__/services.native.test.ts
- src/libs/monitoring/__tests__/services.web.test.ts
- src/libs/monitoring/config.ts
- src/libs/monitoring/config.web.ts
- src/libs/monitoring/services.ts
Exemple d'erreur avec source map : https://sentry.internal-passculture.app/organizations/sentry/issues/300631/?project=6&query=is%3Aunresolved+06754&statsPeriod=14d
Cmds:
```bash
npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output index.android.bundle --sourcemap-output index.android.bundle.packager.map
node_modules/hermes-engine/linux64-bin//hermesc -O -emit-binary -output-source-map -out=index.android.bundle.hbc index.android.bundle
node node_modules/react-native/scripts/compose-source-maps.js index.android.bundle.packager.map index.android.bundle.hbc.map -o index.android.bundle.map
node_modules/@sentry/cli/bin/sentry-cli releases \
files 1.175.4 \
upload-sourcemaps \
--dist …
```
> (PC-13509) fix(Sentry): configure sourcesmaps for iOS/Android

- scripts/deploy.sh
> (PC-13509) fix(Sentry): set VERSION in deploy.sh

- scripts/upload_sourcemaps_to_sentry.sh
> (PC-13509) fix(native): fix source map upload for sentry

- scripts/upload_sourcemaps_to_sentry.sh
> (PC-13509) fix(Sentry): feature detect OS when building source map

- scripts/upload_sourcemaps_to_sentry.sh
- src/libs/environment/types.ts
- web/config/env.js
- web/config/webpack.config.js
> (PC-13509) fix(Sentry): fix COMMIT_HASH, test prefix app:///

- web/config/webpack.config.js
> (PC-13509) fix(Sentry): fix web sourcemap upload

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/OfferIconCaptions.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.web-snap
- __snapshots__/ui/web/touchable/__tests__/Touchable.test.tsx.native-snap
- __snapshots__/ui/web/touchable/__tests__/Touchable.test.tsx.web-snap
- src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx
- src/features/search/atoms/Buttons/ReinitializeFilters.tsx
- src/features/search/components/SearchLandingPage.tsx
- src/locales/fr/messages.po
- src/ui/components/buttons/AppButton/styleUtils.ts
- src/ui/components/inputs/PasswordInput.tsx
- src/ui/components/inputs/SearchInput.tsx
- src/ui/web/touchable/Touchable.tsx
- src/ui/web/touchable/Touchable.web.tsx
- src/ui/web/touchable/__tests__/Touchable.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13384
I have:
|     |         |                 |           
|                  |
> (PC-13384) feat(Touchable): use button balises

- scripts/upload_sourcemaps_to_sentry.sh
> (PC-13509) fix(Native): added version and codepush in sourcemap name

- scripts/upload_sourcemaps_to_sentry.sh
> (PC-13509) fix(Sentry): rename map

- scripts/upload_sourcemaps_to_sentry.sh
> (PC-13509) fix(Sentry): fix soft & hard deploy without rewrite

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13384
I have:
> (PC-13384) test(Web): update snapshots

- scripts/upload_sourcemaps_to_sentry.sh
> (PC-13509) fix(Sentry): restore rewrite+stripPrefix and remove urlPrefix

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- src/features/auth/signup/SetBirthday/atoms/DropDown/DropDown.web.tsx
- src/ui/web/form/Option.tsx
- src/ui/web/form/Option.web.tsx
- src/ui/web/form/Select.tsx
- src/ui/web/form/Select.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13461
I have:
> (PC-13461) fix(DropDown): fix snapshot

- scripts/upload_sourcemaps_to_sentry.sh
> (PC-13509) fix(Sentry): fix upload command

- src/features/navigation/RootNavigator/Header/Header.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13584
I have:
> (PC-13584) feat(accessibility): Remove logo instead of hiding to avoid reading aria-label

- src/libs/storybook/__tests__/selectArgTypeFromObject.test.ts
- src/libs/storybook/selectArgTypeFromObject.ts
- src/ui/components/buttons/ButtonPrimary.stories.tsx
Fix of the source code snippet :
Icon selector for the Primary Button :
> docs(storybook): add icon selector for primary button

- src/ui/components/SlantTag.stories.tsx
- src/ui/components/SlantTag.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13603
[Voir le Storybook](https://PC-13603--61fd537ecf081f003a135235.chromatic.com)
I have:
> (PC-13603) feat(Storybook): Create SlantTag Stories

- src/ui/components/ClippedTag.stories.tsx
- src/ui/components/ClippedTag.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13602
[Voir le Storybook](https://pc-13602--61fd537ecf081f003a135235.chromatic.com/)
I have:
> (PC-13602) feat(Storybook): Create ClippedTag Stories

- src/features/navigation/RootNavigator/Header/NavItem.tsx
- src/features/navigation/TabBar/TabBarComponent.tsx
- src/features/navigation/TabBar/routes.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13566
I have:
> (PC-13566) feat(accessibility): Add accessibility labels to tab bar

- __snapshots__/features/favorites/atoms/__tests__/Favorite.native.test.tsx.native-snap
- __snapshots__/features/favorites/pages/__tests__/Favorites.native.test.tsx.native-snap
- __snapshots__/features/home/atoms/tests/VenueTile.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/BusinessModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/BusinessModule.web.test.tsx.web-snap
- __snapshots__/features/home/components/tests/ExclusivityModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx.native-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx.web-snap
- __snapshots__/features/search/atoms/__tests__/Hit.native.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/ui/components/__tests__/ImageTile.native.test.tsx.native-snap
- src/features/favorites/atoms/Buttons/Sort.tsx
- src/features/home/components/BusinessModule.tsx
- src/features/home/components/ExclusivityModule.tsx
- src/features/search/atoms/Buttons/Filter.tsx
- src/features/search/atoms/OfferImage.tsx
- src/ui/components/ImagePlaceholder.tsx
- src/ui/components/ImageTile.tsx
- src/ui/components/ModuleBanner/ModuleBanner.tsx
- src/ui/components/hero/Hero.stories.tsx
- src/ui/components/hero/Hero.tsx
- src/ui/svg/ImagePlaceholderVenue.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12992
I have:
|     |         |                 |                     <img width="400" alt="Capture d’écran 2022-02-24 à 11 34 26" src="https://user-images.githubusercontent.com/46637324/155508656-f5c06972-f69c-47d7-bd50-d65adf388d57.png">   |    |
|     |         |                 |                    <img width="200" alt="Capture d’écran 2022-02-24 à 11 33 51" src="https://user-images.githubusercontent.com/46637324/155508736-f8fc9457-d688-4523-8a7f-bdb8ecc6be44.png">|    |
|     |         |                 |                   <img width="200" alt="Capture d’écran …
> (PC-12992) feat(accessibility): Add background colors to gradient containers containing text

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/OfferIconCaptions.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferIconCaptions.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx.native-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.native-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.web-snap
- src/features/search/atoms/Buttons/Filter.tsx
- src/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx
I have:
|     |         |                 |        
|                  |
> (PC-13384) feat(Filter): use button balise

- .circleci/config.yml
> (PC-13685) fix(Sonar): remove sonar for test-native

- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13384
I have:
> (PC-13384) feat(Filter): fix CI test after rebase

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13687
I have:
> (PC-13687) fix(Sonar): reactive sonar

- src/features/bookOffer/services/useBookOfferMutation.ts
> (PC-13507) fix(booking): improve mutation booking validation

- src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13438
I have:
> (PC-13438) fix(DeeplinksGenerator): update utms descriptions

- src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13440
I have:
> (PC-13440) fix(DeeplinksGenerator): added utm_content marketing params

- src/web/SupportedBrowsersGate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13695
I have:
> (PC-13695) fix(BrowserGate): skip browser gate when instagram browsing

- src/features/navigation/TabBar/TabBarComponent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13678
I have:
|  https://user-images.githubusercontent.com/46637324/155704512-848a0f4c-905f-4b01-af10-d4f772b67dde.mp4   |         |                 |                  |                  |
> (PC-13678) fix(tabBar): Fix bounce animation in tabBar

- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- src/features/search/atoms/SelectionLabel.stories.tsx
- src/features/search/atoms/SelectionLabel.tsx
- src/ui/components/FilterSwitch.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13686
I have:
> (PC-13686) feat(Storybook): Add stories for SelectionLabel and FilterSwitch

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- src/features/bookings/atoms/TicketCode.tsx
- src/features/bookings/atoms/TicketCode.web.tsx
- src/features/bookings/atoms/TicketCodeTitle.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/bookings/pages/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12990
I have:
> (PC-12990) feat(accessibility): Copy reservation token on click for web

- src/features/favorites/atoms/BicolorFavoriteCount.tsx
- src/features/navigation/RootNavigator/Header/NavItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13678
I have:
> (PC-13678) fix(Header): Fix bounce animation in web header and center fav count

- src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/_marketingAndCommunication/components/DeeplinksHistory.tsx
- src/features/_marketingAndCommunication/components/DeeplinksResult.tsx
- src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13437
I have:
> (PC-13437) fix(Deeplinks): add URL params to Search

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- src/features/auth/signup/SetBirthday/SetBirthday.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13598
I have:
> (PC-13598) feat(accessibility): Add aria label to set birthday button

- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/search/atoms/Buttons/Search.tsx
- src/features/venue/components/VenueOffers.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.native.test.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.stories.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.web.test.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.web.tsx
- src/ui/components/buttons/buttonWithLinearGradientTypes.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13706
I have:
native/blob/master/doc/standards/pr-title.md
> (PC-13706) feat(stories): added story for ButtonWithLinearGradient and StepDots

- src/features/home/components/OffersModule.tsx
- src/libs/geolocation/hooks/useDistance.ts
- src/ui/components/Playlist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13621
Fix + action mergé dans : https://github.com/pass-culture/pass-culture-app-native/pull/2725
Mais l'introduction de warning ESLint casse la CI de déploiement web : https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/13711/workflows/1ba4b2f7-f4e4-4e41-bee0-dbcfa045d20e/jobs/41344/parallel-runs/0/steps/0-115
Je pousse donc le fix, sans l'action (ajout de la règle ESLint) pour l'instant. On discutera de l'action en point synchro tech le 02/03
I have:
[1]: …
> (PC-13621) fix(home): re-render offer to display distances

- src/features/home/pages/useHomeRecommendedHits.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12896
I have:
> (PC-12896) feat(tracking): track abc test from recommendation algo

- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/ui/components/buttons/__tests__/ScrollButtonForNotTouchDevice.test.tsx.web-snap
- __snapshots__/ui/components/touchable/__tests__/Touchable.test.tsx.web-snap
- src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
- src/ui/components/buttons/AppButton/styleUtils.ts
- src/ui/components/buttons/ButtonWithLinearGradient.web.tsx
- src/ui/components/buttons/ScrollButtonForNotTouchDevice.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12581
I have:
|     |         |                 |    <img width="540" alt="Capture d’écran 2022-03-01 à 12 06 28" src="https://user-images.githubusercontent.com/62059034/156158242-b92281a9-10a1-4549-954c-fa95e4a25731.png"> <img width="1055" alt="Capture d’écran 2022-03-01 à 12 06 21" src="https://user-images.githubusercontent.com/62059034/156158248-94560c45-2252-46b1-b464-fb2a25d562f3.png">              |                  |
> (PC-12581) feat(accessibility): add focus to ButtonWithLinearGradient

- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/ui/components/buttons/externalLink/ExternalLink.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13581
I have:
|     |         |                 | <img width="1107" alt="Capture d’écran 2022-03-02 à 08 36 45" src="https://user-images.githubusercontent.com/62059034/156316075-cc3d8f52-1a31-40fe-ac63-38d7c2195a50.png">                 |                  |
> (PC-13581) fix(ExternalLink): add focus to external link

- src/ui/components/ClippedImage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13023
I have:
> (PC-13023) fix(shadow): Add shadow to ClippedImage placeholder

- __snapshots__/features/home/atoms/tests/VenueTile.web.test.tsx.web-snap
- src/features/home/atoms/VenueTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13720
I have:
> (PC-13720) feat(accessibility): Add missing web hyperlink to venue tile in homepage

- patches/react-native-calendars+1.1271.0.patch
- src/features/search/components/CalendarPicker.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13707
I have:
> (PC-13707) feat(accessibility): Make disabled days inaccessible via tab in date filter

- __snapshots__/features/favorites/atoms/__tests__/Favorite.native.test.tsx.native-snap
- __snapshots__/features/home/atoms/tests/VenueTile.native.test.tsx.native-snap
- __snapshots__/features/home/atoms/tests/VenueTile.web.test.tsx.web-snap
- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.native.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.web.test.tsx.web-snap
- __snapshots__/features/search/atoms/__tests__/Hit.native.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/bookings/components/EndedBookingItem.tsx
- src/features/bookings/components/OnGoingBookingItem.tsx
- src/features/favorites/atoms/Favorite.tsx
- src/features/home/atoms/VenueTile.tsx
- src/features/offer/atoms/OfferTile.tsx
- src/features/search/atoms/Hit.tsx
- src/libs/tileAccessibilityLabel.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13715
I have:
|     |         |                 |                          |                  |
> (PC-13715) feat(accessibility): Add accessibility label to offer tiles in homepage and search results

- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/ui/components/buttons/ButtonWithLinearGradient.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12992
I have:
|     |         |                 |     <img width="424" alt="Capture d’écran 2022-03-03 à 11 51 36" src="https://user-images.githubusercontent.com/46637324/156550972-ad40d8c2-2178-4c0e-96aa-f18371387f86.png"><img width="425" alt="Capture d’écran 2022-03-03 à 11 51 50" src="https://user-images.githubusercontent.com/46637324/156550974-7a272069-f9e2-4f96-89be-f2fe6c8308ac.png">      |                  |
[2]: …
> (PC-12992) feat(accessibility): Replace background attribute by backgroundImage for web gradient

- src/ui/components/snackBar/SnackBar.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13736
I have:
> (PC-13736) feat(storybook): add snackbar to storybook

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.native-snap
- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- src/features/_marketingAndCommunication/atoms/ControlledFilterSwitch.tsx
- src/features/_marketingAndCommunication/atoms/DateChoice.tsx
- src/features/_marketingAndCommunication/atoms/LocationFilterChoice.tsx
- src/features/_marketingAndCommunication/atoms/OfferCategoryChoices.tsx
- src/features/_marketingAndCommunication/atoms/OfferTypeChoices.tsx
- src/features/_marketingAndCommunication/atoms/tests/ControlledFilterSwitch.native.test.tsx
- src/features/_marketingAndCommunication/atoms/tests/ControlledFilterSwitch.web.test.tsx
- src/features/_marketingAndCommunication/atoms/tests/DateChoice.native.test.tsx
- src/features/_marketingAndCommunication/atoms/tests/DateChoice.web.test.tsx
- src/features/_marketingAndCommunication/atoms/tests/DeepLinkItem.web.test.tsx
- src/features/_marketingAndCommunication/atoms/tests/LocationFilterChoice.test.tsx
- src/features/_marketingAndCommunication/atoms/tests/OfferCategoryChoices.test.tsx
- src/features/_marketingAndCommunication/atoms/tests/OfferTypeChoices.test.tsx
- src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/_marketingAndCommunication/components/DeeplinksHistory.tsx
- src/features/_marketingAndCommunication/components/DeeplinksResult.tsx
- src/features/_marketingAndCommunication/components/tests/DeeplinksGeneratorForm.native.test.tsx
- src/features/_marketingAndCommunication/components/tests/DeeplinksHistory.test.tsx
- src/features/_marketingAndCommunication/components/tests/DeeplinksResults.test.tsx
- src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts
- src/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx
- src/features/search/components/LocationChoice.tsx
- src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13434
I have:
> (PC-13434) feat(DeeplinksGenerator): added search params query, priceRange and tags

- src/features/favorites/components/FavoritesResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13636
Related to https://sentry.internal-passculture.app/organizations/sentry/issues/288586/?project=6
I have:
> (PC-13636) fix(FavoritesResults): return empty list if no list passed to sortBy

- src/features/bookings/api/queries.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13637
Related to https://sentry.internal-passculture.app/organizations/sentry/issues/291067
I have:
> (PC-13637) fix(bookings): sentry/issues/291067

- src/theme/index.ts
- src/ui/components/buttons/ButtonPrimary.ts
- src/ui/components/buttons/ButtonPrimaryWhite.stories.tsx
- src/ui/storybook/ContainerWithBackgound.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13735
I have:
> (PC-13735) feat(storybook): add ButtonPrimaryWhite stories

- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/ui/components/buttons/externalLink/ExternalLink.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13581
I have:
> (PC-13581) fix(accessibility): Fix keyboard enter on ExternalLink

- .storybook/main.js
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- src/ui/components/inputs/Slider.stories.tsx
- src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13772
I have:
> (PC-13772) feat(storybook): Add stories for slider input

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13804
Il y a eu divers fix sur notre version, notamment l'ajout d'un `useMemo` sur react-query, et un fix sur les `Observable`
- https://github.com/tannerlinsley/react-query/commit/c6906b3c4d3fd73900610a0b452a17f2eb63518f
- https://github.com/tannerlinsley/react-query/pull/2992/files
et
- https://github.com/tannerlinsley/react-query/pull/3052
Ça peut valoir le coup d'essayer
I have:
[2]: …
> (PC-13804) fix(ReactQuery): upgrade from 3.34.0 to 3.34.16

- src/theme/index.ts
- src/ui/components/buttons/ButtonSecondary.stories.tsx
- src/ui/components/buttons/ButtonSecondaryWhite.stories.tsx
- src/ui/components/buttons/ButtonSecondaryWhite.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13737
I have:
> (PC-13737) feat(storybook): Add stories ButtonSecondary and ButtonSecondaryWhite

- public/index.html
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13021
I have:
Take a look into the ticket for the before-after
> (PC-13021) fix(typo): Update global font weight for title and body

- src/ui/components/inputs/TextInput.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13741
I have:
> (PC-13741) feat(storybook): add TexteInput stories

- src/ui/components/AccordionItem.stories.tsx
Co-authored-by: bruno ebstein <bruno.ebstein@passculture.app>
Co-authored-by: Hugo Voisin <hugov@bam.tech>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13828
I have:
> (PC-13828) feat(storybook): add AccordionItem

- src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts
- src/features/offer/services/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13862
I have:
> (PC-13862) fix(Bookings): no external link to view in app booking

- src/features/bookOffer/services/useBookOfferMutation.ts
> (PC-13507) fix(bookings): make invalidateCache synchronous

- src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13866
I have:
> (PC-13866) fix(search): bad behavior when scrolling on search results

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/DMSModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
- src/features/search/components/CalendarPicker.web.tsx
- src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12994
I have:
|     |         |                 |   https://user-images.githubusercontent.com/46637324/157408379-cc5a7480-52d3-468d-a8e9-82b13785ec1c.mp4         |                  |
> (PC-12994) feat(accessibility): Handle up to 200% zoom in calendar filter

- src/features/bookOffer/services/useBookOfferMutation.ts
- src/features/bookings/api/queries.ts
- src/features/offer/pages/Offer.tsx
- src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts
- src/features/offer/services/useCtaWordingAndAction.ts
> (PC-13507) fix(Bookings): select one bookings after refreshing bookings

- src/ui/components/ClippedImage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13023
I have:
|     |<img width="404" alt="Capture d’écran 2022-03-09 à 11 46 07" src="https://user-images.githubusercontent.com/90036171/157427422-588533b6-c961-47bb-a587-49914cd3db8c.png">|                 |                  |                  |
> (PC-13023) fix(ClippedImage): Fix shadow on android only

- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- src/ui/components/ValidationMark.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13879
I have:
|     |         |                 |  ![Capture d’écran 2022-03-09 à 18 42 22](https://user-images.githubusercontent.com/62059034/157499689-64b95405-0f70-490d-a3e7-3ed024b9222f.png)                |                  |
> (PC-13879) fix(ValidationMark): add correct color for InvalidateGreyDark icon

- src/features/search/atoms/NoSearchResult.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13840
I have:
|     |         |                 |       ![Capture d’écran 2022-03-09 à 15 20 05](https://user-images.githubusercontent.com/62059034/157489375-03d52134-aa90-44fb-a676-4006888c621d.png)     |                  |
> (PC-13840) feat(NoSearchResult): add focus for AroundMeText

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/home/components/tests/HomeBodyPlaceholder.test.tsx.native-snap
- __snapshots__/features/home/components/tests/HomeBodyPlaceholder.test.tsx.web-snap
- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/OfferIconCaptions.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferIconCaptions.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.native-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.web-snap
- src/features/home/components/HomeBodyPlaceholder.tsx
- src/features/search/pages/SuggestedPlaces.tsx
- src/ui/components/Playlist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13868
I have:
> (PC-13868) feat(accessibility): Revert Ul and Li tags on FlatList

- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- src/features/offer/components/OfferHeader.tsx
- src/features/search/atoms/SelectionLabel.tsx
- src/ui/components/TouchableOpacity.tsx
- src/ui/components/headers/HeaderIcon.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13867
I have:
> (PC-13867) feat(accessibility): Add checkbox accessibility role to filter choices and favorite

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.native-snap
- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
- __snapshots__/features/offer/atoms/__tests__/OfferCategory.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferCategory.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/OfferIconCaptions.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferIconCaptions.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/features/profile/components/SectionWithSwitch.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/theme/index.ts
- src/ui/theme/typography.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13380
I have:
|     |    ![Screenshot_1646919074](https://user-images.githubusercontent.com/46637324/157672037-753ab659-d4d6-44c3-9b8c-9da13935b56f.png)   |                 |                  |                  |
> (PC-13880) fix(accessibility): Fix text color for android dark mode

- src/ui/components/inputs/SearchInput.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13846
I have:
> (PC-13846) feat(storybook): add SearchInput

- src/features/bookings/pages/BookingDetails.tsx
> (PC-13507) fix(Bookings): add log when showing 404 on native

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- src/features/bookings/atoms/TicketCodeTitle.tsx
- src/features/bookings/pages/BookingDetails.tsx
- src/ui/components/SectionRow.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13841
I have:
> (PC-13841) feat(accessibility): Fix focus and component order in booking details

- src/features/auth/signup/AcceptCgu/AcceptCgu.tsx
- src/features/auth/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13842
I have:
> (PC-13842) feat(accessibility): Remove EnterKeyAction in AcceptCGU and change icon signup confirmation

- src/ui/components/snackBar/SnackBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13851
I have:
> (PC-13851) feat(accessibility): Announce snackbar message with voiceover

- src/ui/components/Banner.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13742
I have:
> (PC-13742) feat(storybook): add Banner

- src/locales/fr/messages.po
- src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13872
I have:
> (PC-13872) feat(accessibility): Make slider cursors more accessible

- src/features/bookOffer/services/useBookOfferMutation.ts
- src/features/bookings/pages/BookingDetails.tsx
> (PC-13507) fix(Bookings): manually update cache after new booking

- __snapshots__/ui/components/buttons/__tests__/ScrollButtonForNotTouchDevice.test.tsx.web-snap
- src/features/bookOffer/components/Calendar/Calendar.tsx
- src/features/offer/pages/Offer.tsx
- src/locales/fr/messages.po
- src/ui/components/buttons/ScrollButtonForNotTouchDevice.web.ts
- src/ui/components/buttons/scrollButtonForNotTouchDeviceUtils.ts
- src/ui/svg/icons/ArrowNext.tsx
- src/ui/svg/icons/ArrowPrevious.tsx
- src/ui/web/link/A.web.tsx
- src/ui/web/link/Link.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13977
I have:
> (PC-13977) feat(accessibility): Fix link interaction with voiceover

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- src/features/bookings/components/BookingPropertiesSection.tsx
- src/features/bookings/pages/Bookings.native.test.tsx
- src/features/bookings/pages/Bookings.web.test.tsx
- src/features/profile/pages/LegalNotices/tests/LegalNotices.native.test.tsx
- src/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx
- src/features/profile/pages/Profile.native.test.tsx
- src/locales/fr/messages.po
- src/ui/components/SectionRow.native.test.tsx
- src/ui/components/SectionRow.tsx
- src/ui/components/SectionRow.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13976
I have:
> (PC-13976) feat(accessibility): add new accessibilityLabel for BookingProperties

- src/features/search/sections/OfferDate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13978
I have:
> (PC-13978) feat(accessibility): add ul li for OfferDate

- src/features/bookOffer/pages/BookingOfferModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13987
I have:
> (PC-13987) fix(booking): weird behavior when navigating from venue

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13093
I have:
> (PC-13093) feat(ci): Add slack notification for failed testing deploy

- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14074
I have:
> (PC-14074) feat(vulnerability): upgrade msw version

- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- src/features/bookOffer/components/__tests__/BookingImpossible.deprecated.web.test.tsx
- src/features/bookings/components/BookingPropertiesSection.web.test.tsx
- src/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx
- src/features/offer/components/__tests__/OfferPartialDescription.web.test.tsx
- src/features/profile/components/NonBeneficiaryHeader.web.test.tsx
- src/features/search/atoms/TitleWithCount.tsx
- src/features/search/sections/tests/Location.web.test.tsx
- src/ui/components/__tests__/AnimatedIcon.web.test.tsx
- src/ui/components/achievements/components/GenericAchievement.web.test.tsx
- src/ui/components/achievements/components/GenericAchievementCard.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14070
I have:
> (PC-14070) fix(FIXME): Fix and remove all FIXME tasks

- src/features/cheatcodes/pages/AppComponents/Icons.tsx
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/cheatcodes/pages/NavigationCulturalSurvey/NavigationCulturalSurvey.tsx
- src/features/cheatcodes/pages/NavigationCulturalSurvey/index.tsx
- src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
- src/features/navigation/RootNavigator/culturalSurveyRoutes.ts
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
- src/ui/components/GenericInfoPageWhite.tsx
- src/ui/svg/icons/ClockFilled.tsx
- src/ui/theme/typography.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13338
I have:
| iOS | iPhone SE | Android | Desktop - Chrome | 
| --: | ------: | --------------: | ---------------: | 
|<img width="363" alt="Capture d’écran 2022-03-10 à 12 16 14" src="https://user-images.githubusercontent.com/90036171/157651927-57990c4c-6225-42e2-a49d-8615e2b39dc2.png">|<img width="377" alt="Capture d’écran 2022-03-10 à 12 16 23" src="https://user-images.githubusercontent.com/90036171/157651971-dc1f8897-4e4d-4bf4-be27-7b23510dad5e.png">|<img width="363" alt="Capture d’écran 2022-03-10 à 12 16 50" src="https://user-images.githubusercontent.com/90036171/157652092-46c78fad-356d-4326-974c-aaebb47688a5.png">|<img width="1680" alt="Capture d’écran 2022-03-10 à 12 16 02" …
> (PC-13338) feat(CulturalSurvey): Create Cultural Survey Intro page

- src/features/cheatcodes/pages/AppComponents/Illustrations.stories.tsx
- src/features/cheatcodes/pages/AppComponents/Illustrations.tsx
- src/ui/storybook/Illustration.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13962
I have:
> (PC-13962) feat(storybook): add Illustrations stories

- .circleci/config.yml
- scripts/transition_jira_ticket.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13865
I have:
> (PC-13865) fix(process): allow script to fail and fix ci

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14078
I have:
> (PC-14078) fix(vulnerability): update cross-fetch

- patches/@react-navigation+native+6.0.6.patch
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13027
I have:
> (PC-13027) fix(navigation): Add patch to reload location on useLinking error

- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.web-snap
- src/libs/geolocation/components/WhereSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14071
I have:
|     |         |   https://user-images.githubusercontent.com/46637324/159470867-f86d921b-2bb5-4dbb-8aa6-8c50fb7db8ff.mp4    |                  |                  |
> (PC-14071) fix(itinerary): Add city and postal code to itinerary address

- .circleci/config.yml
- doc/deployment/circleci.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14085
I have:
> (PC-14085) fix(CodePush): iOS and added documentation for debugging the CI

- doc/deployment/deployment.md
Mise à jour de la doc de déploiement suite à la possibilité d'avoir des tags de staging en `patch/v1.X.Y`
I have:
> docs(deployment): update deployment documentation

- src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13338
Sur l'iPhone 8 et certain Android, le PrimaryButton n'était pas centré et formaté correctement.
I have:
> (PC-13338) fix(CulturalSurveyIntro): Fix iPhone 8 layout

- src/libs/analytics/provider.ts
- src/libs/analytics/provider.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14124
I have:
> (PC-14124) fix(firebase): normnalize android/web integration

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/DMSModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
- src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13996
I have:
> (PC-13996) fix(AppModal): add paddingBottom and paddingHorizontal to solve outline overflow issue

- src/ui/components/RadioButton.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13738
I have:
> (PC-13738) feat(storybook): add RadioButton

- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.native.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.web.test.tsx.web-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/ui/components/__tests__/ClippedTag.native.test.tsx.native-snap
- __snapshots__/ui/components/__tests__/ClippedTag.web.test.tsx.web-snap
- src/features/offer/atoms/OfferTile.tsx
- src/features/offer/atoms/__tests__/OfferTile.web.test.tsx
- src/ui/components/ClippedTag.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13319
I have:
> (PC-13319) feat(sahi): Make offer tiles and clipped tags accessible to Sahi

- src/ui/components/inputs/CheckboxInput.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13966
I have:
> (PC-13966) feat(storybook): add CheckboxInput

- __snapshots__/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.native.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.web.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/culturalSurvey/components/CulturalSurveyCheckbox.stories.tsx
- src/features/culturalSurvey/components/CulturalSurveyCheckbox.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.native.test.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13342
I have:
| iOS | iOS small screen | Android | Desktop - Chrome | 
| --: | ------: | --------------: | ---------------: | 
|  ![Capture d’écran 2022-03-23 à 16 41 19](https://user-images.githubusercontent.com/44037911/159741257-e3efb051-255b-4d83-9475-94ba26d76729.png)   |      ![Capture d’écran 2022-03-23 à 16 44 15](https://user-images.githubusercontent.com/44037911/159741086-32cef5ab-7615-45c6-80e0-5f4556abc526.png)   |        ![Capture d’écran 2022-03-23 à 16 41 08](https://user-images.githubusercontent.com/44037911/159741709-e16efd53-ffe5-448d-8662-4ee574c3c027.png)         |           <img width="1282" alt="Capture d’écran 2022-03-23 à 16 41 38" src="https://user-images.githubusercontent.com/44037911/1597417 …
> (PC-13342) feat(QPI): create culturalsurvey checkbox component

- src/ui/components/RadioButton.stories.tsx
> feat(storybook): add multiple RadioButton story

- src/ui/components/SectionWithDivider.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14062
I have:
> (PC-14062) feat(storybook): add SectionWithDivider

- package.json
- src/features/landscapePosition/useIsLandscapePosition.web.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14150
I have:
> (PC-14150) fix(landscape): Fix landscape detection on web on keyboard open

- __snapshots__/features/identityCheck/pages/confirmation/__test__/UnderageAccountCreated.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/UnderageAccountCreated.test.tsx.web-snap
- __snapshots__/features/profile/components/CreditCeiling.native.test.tsx.native-snap
- __snapshots__/features/profile/components/CreditCeiling.web.test.tsx.web-snap
- __snapshots__/ui/components/bars/AnimatedProgressBar.native.test.tsx.native-snap
- __snapshots__/ui/components/bars/AnimatedProgressBar.web.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/culturalSurvey/components/CulturalSurveyProgressBar.tsx
- src/features/identityCheck/pages/confirmation/UnderageAccountCreated.tsx
- src/features/profile/components/BeneficiaryCeilings.native.test.tsx
- src/features/profile/components/BeneficiaryCeilings.web.test.tsx
- src/features/profile/components/BeneficiaryHeader.native.test.tsx
- src/features/profile/components/BeneficiaryHeader.web.test.tsx
- src/features/profile/components/CreditCeiling.native.test.tsx
- src/features/profile/components/CreditCeiling.tsx
- src/features/profile/components/CreditCeiling.web.test.tsx
- src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx
- src/ui/components/bars/AnimatedProgressBar.native.test.tsx
- src/ui/components/bars/AnimatedProgressBar.stories.tsx
- src/ui/components/bars/AnimatedProgressBar.tsx
- src/ui/components/bars/AnimatedProgressBar.web.test.tsx
- src/ui/components/bars/ProgressBar.stories.tsx
- src/ui/components/bars/ProgressBar.tsx
- src/ui/components/snackBar/SnackBar.tsx
- src/ui/components/snackBar/SnackBarProgressBa.tsx
- src/ui/components/snackBar/SnackBarProgressBar.tsx
- src/ui/components/snackBar/SnackBarProgressBar.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13343
I have:
|    <img width="325" alt="Capture d’écran 2022-03-29 à 12 00 39" src="https://user-images.githubusercontent.com/44037911/160586940-3c9d05e2-69bb-4ee0-942f-66dd6eef34d3.png"> |         |                 |        <img width="1170" alt="Capture d’écran 2022-03-29 à 12 01 12" src="https://user-images.githubusercontent.com/44037911/160586985-74d9d5ed-1279-489e-b978-7d4ef345a971.png">          |                  |
[2]: …
> (PC-13343) feat(QPI): create cultural survey progress bar component

- .storybook/preview.js
- src/features/profile/components/BeneficiaryCeilings.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13960
> (PC-13960) feat(storybook): add BeneficiaryCeilings

- __snapshots__/features/home/components/tests/HomeBodyPlaceholder.test.tsx.native-snap
- __snapshots__/features/home/components/tests/HomeBodyPlaceholder.test.tsx.web-snap
- src/features/home/components/HomeBodyPlaceholder.stories.tsx
- src/features/home/components/HomeBodyPlaceholder.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13972
I have:
> (PC-13972) feat(storybook): add HomeBodyPlaceholder

- __snapshots__/features/search/pages/__tests__/LocationFilter.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- src/features/search/atoms/Buttons/DateFilter.tsx
- src/features/search/components/LocationChoice.tsx
- src/features/search/sections/OfferDate.tsx
- src/features/search/sections/tests/OfferDate.native.test.tsx
- src/features/search/sections/tests/OfferDate.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14257
I have:
|  (Aucun changement concernant le placement de l'icône) <img width="400" alt="Simulator Screen Shot - iPhone 13 - 2022-03-31 at 14 43 18" src="https://user-images.githubusercontent.com/46637324/161061240-00336e72-eac2-48a8-a820-0d34f3da7098.png"> <img width="400" alt="Simulator Screen Shot - iPhone 13 - 2022-03-31 at 14 44 33" src="https://user-images.githubusercontent.com/46637324/161061245-5a14c4a4-9322-4d27-8697-0d9acb7d7579.png">  |         |                 |    <img width="928" alt="Capture d’écran 2022-03-31 à 14 44 08" …
> (PC-14257) fix(accessibility): Refactor filter radio buttons and make them more accessible

- src/api/gen/api.ts
- src/features/auth/__mocks__/settings.ts
- src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/bookings/components/BookingDetailsTicketContent.web.test.tsx
- src/features/bookings/pages/BookingDetails.tsx
- src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14138
I have:
> (PC-14138) feat(bookings): add QR code feature flag

- __snapshots__/features/identityCheck/pages/confirmation/__test__/UnderageAccountCreated.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/UnderageAccountCreated.test.tsx.web-snap
- src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
- src/ui/components/GenericInfoPageWhite.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13338
I have:
> (PC-13338) fix(CulturalSurveyIntro): Update Generic Info Page White

- src/features/profile/pages/NotificationSettings.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14104
I have:
> (PC-14104) fix(test): Allow console.error for flaky test

- scripts/deploy.sh
https://passcultureteam.slack.com/archives/G01C85B6DHA/p1649061565224659?thread_ts=1647017407.776569&cid=G01C85B6DHA
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14310
Related to https://github.com/pass-culture/pass-culture-app-native/pull/2773
I have:
> (PC-14310) ci(deploy): fix deploy script

- __snapshots__/features/home/atoms/tests/VenueTile.native.test.tsx.native-snap
- __snapshots__/features/home/atoms/tests/VenueTile.web.test.tsx.web-snap
- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.native.test.tsx.native-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.web.test.tsx.web-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/home/atoms/VenueTile.tsx
- src/features/offer/atoms/OfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14191
I have:
> (PC-14191) feat(accessibility): Refactor Offer/Venue Tiles to make them more accessible

- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/cheatcodes/pages/NavigationCulturalSurvey/NavigationCulturalSurvey.tsx
- src/features/culturalSurvey/components/CulturalSurveyCheckbox.tsx
- src/features/culturalSurvey/components/CulturalSurveyProgressBar.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.native.test.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.web.test.tsx
- src/features/culturalSurvey/components/layout/CulturalSurveyPageHeader.tsx
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
- src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.test.tsx
- src/features/navigation/RootNavigator/culturalSurveyRoutes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
- src/ui/components/bars/ProgressBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13344
I have:
https://user-images.githubusercontent.com/44037911/161505810-652358c8-cd70-4cf1-9263-f8482433941e.mp4
| 271x... | 341x... | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|    <img width="1437" alt="Capture d’écran 2022-04-04 à 10 08 57" src="https://user-images.githubusercontent.com/44037911/161505958-e1089140-d735-4ad6-85b9-59e02e2432e9.png"> |    <img width="1437" alt="Capture d’écran 2022-04-04 à 10 09 01" src="https://user-images.githubusercontent.com/44037911/161506028-8807f901-2da7-4d42-b8f6-2e436defaf75.png">      |                 |        <img width="1437" alt="Capture d’écran 2022-04-04 à 10 09 24" …
> (PC-13344) feat(QPI): create cultural survey answer page

- src/features/_marketingAndCommunication/pages/UTMParameters.tsx
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/home/components/HomeHeader.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/ui/components/SectionRow.stories.tsx
- src/ui/components/SectionWithDivider.stories.tsx
- src/ui/components/bars/AnimatedProgressBar.stories.tsx
- src/ui/components/bars/ProgressBar.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14330
I have:
> (PC-14330) refactor(cheatcode): change cheatcode navigation

- public/index.html
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14356
I have:
> (PC-14356) fix(Web): ajout de metas dans index.html

- public/index.html
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14356
I have:
> (PC-14356) fix(Web): added metas

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/AccessibleTabBar.tsx
- src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx
- src/features/navigation/RootNavigator/Header/Header.tsx
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx
- src/features/navigation/RootNavigator/Header/tests/Header.web.test.tsx
- src/features/navigation/RootNavigator/RootNavigator.tsx
- src/ui/web/global/Main.tsx
- src/ui/web/link/QuickAccess.tsx
- src/ui/web/link/QuickAccess.web.tsx
- src/ui/web/link/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14334
I have:
> (PC-14334) feat(accessibility): Add quick access links for main content and tabBar

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/iconsExports.ts
- src/features/search/components/AutoScrollSwitch.tsx
- src/features/search/components/AutoScrollSwitch.web.tsx
- src/features/search/components/ScrollToTopButton.tsx
- src/features/search/components/SearchResults.tsx
- src/ui/components/touchable/Touchable.tsx
- src/ui/components/touchable/types.ts
- src/ui/svg/icons/More.tsx
- src/ui/svg/icons/ScrollToTop.tsx
- src/ui/web/link/QuickAccess.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14335
I have:
| ![Simulator Screen Shot - iPhone 13 - 2022-04-07 at 17 04 34](https://user-images.githubusercontent.com/46637324/162230866-31176147-1684-44a7-b973-436ae7cdd040.png)    |         |            |        <img width="1000" alt="Capture d’écran 2022-04-07 à 16 38 04" src="https://user-images.githubusercontent.com/46637324/162226985-8a0437a1-ea97-44db-80bd-b68570620922.png"> <img width="1000" alt="Capture d’écran 2022-04-07 à 16 38 34" src="https://user-images.githubusercontent.com/46637324/162226961-6e1168c8-0b6d-4c82-beaa-c15c57d44bdc.png">        | …
> (PC-14335) feat(accessibility): Control search results autoscroll and add scrollToTop button

- src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14335
I have:
> (PC-14335) fix(accessibility): Fix wording for autoscroll switch

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- src/features/bookings/atoms/TicketCode.tsx
- src/features/bookings/atoms/TicketCode.web.tsx
- src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/cheatcodes/pages/AppComponents/illustrationsExports.ts
- src/locales/fr/messages.po
- src/ui/svg/icons/BicolorCircledCheck.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14140
I have:
> (PC-14140) feat(booking): new display no ticket collect

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/Nav.tsx
> (PC-13000) fix(accessibility): Include separator in list item for valid html structure

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- src/features/bookings/components/BookingDetailsTicketContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14140
I have:
> (PC-14140) fix(booking): reduce spacing no ticket

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.native-snap
- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/home/components/tests/BusinessModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/ExclusivityModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/layout/PageWithHeader.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.web-snap
- __snapshots__/features/offer/atoms/__tests__/OfferTile.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/search/atoms/__tests__/Hit.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/NavItem.tsx
- src/features/search/atoms/Hit.tsx
- src/ui/components/AccordionItem.tsx
- src/ui/components/TouchableOpacity.tsx
- src/ui/theme/customFocusOutline/touchableFocusOutline.tsx
- src/ui/web/link/TouchableLink.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14373
I have:
**(Aucune régression sur les focus existants : tuiles d'offres, boutons etc.)**
Desktop - Firefox | Desktop - Chrome | Desktop - Safari |
| --------------: | ---------------: | ---------------: |
|    <img width="176" alt="Capture d’écran 2022-04-11 à 17 47 56" src="https://user-images.githubusercontent.com/46637324/162780163-6fb1dd9f-b7fb-433e-b118-99697514cb18.png"><img width="459" alt="Capture d’écran 2022-04-11 à 17 47 38" src="https://user-images.githubusercontent.com/46637324/162780166-6a9841db-f545-459d-a2d1-55c1648e2fd2.png"><img width="686" alt="Capture d’écran 2022-04-11 à 17 46 39" src="https://user-images.githubusercontent.com/46637324/162780169-64e70971-6b33-4460-9235-e1be1df48972.png"> …
> (PC-14373) fix(accessibility): Fix focus on firefox and safari for TouchableOpacity

- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/venue/atoms/IconWithCaption.tsx
- src/features/venue/components/VenueIconCaptions.tsx
- src/features/venue/components/__tests__/VenueIconCaptions.native.test.tsx
- src/features/venue/components/__tests__/VenueIconCaptions.web.test.tsx
- src/features/venue/pages/__tests__/Venue.web.test.tsx
- src/features/venue/pages/__tests__/VenueBody.web.test.tsx
- src/locales/fr/messages.po
- src/ui/components/touchable/Touchable.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14273
I have:
|     | ![image](https://user-images.githubusercontent.com/77674046/162751686-551b4b27-da10-4b69-a707-76b7d99f7c81.png) |                 |        ![image](https://user-images.githubusercontent.com/77674046/162751717-8586a823-a12d-4b85-9593-ea3e2a9ac278.png)          |                  |
> (PC-14273) fix(a11y): activation de la géolocalisation de la page Lieu

- src/ui/components/ModuleBanner/ModuleBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14430
I have:
|  ![Capture d’écran 2022-04-12 à 18 46 39](https://user-images.githubusercontent.com/62059034/163013181-eacda4af-4907-4373-8b58-d66c5698854b.png)  |         |                 |   ![Capture d’écran 2022-04-12 à 18 46 46](https://user-images.githubusercontent.com/62059034/163013219-8ef3eaf3-c224-4ead-b2eb-e6a7c00a101c.png)  |                  |
> (PC-14430) fix(ModuleBanner): add correct color for title

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/ui/components/buttons/ButtonWithLinearGradient.native.test.tsx.native-snap
- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/offer/pages/Offer.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.stories.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.tsx
- src/ui/components/buttons/ButtonWithLinearGradient.web.tsx
- src/ui/components/buttons/buttonWithLinearGradientTypes.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14383
I have:
> (PC-14383) feat(buttonGradient): add dynamic icon

- __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
- __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/ui/components/DotComponent.native.test.tsx.native-snap
- __snapshots__/ui/components/DotComponent.web.test.tsx.web-snap
- __snapshots__/ui/components/achievements/components/ControlComponent.web.test.tsx.web-snap
- __snapshots__/ui/components/touchable/__tests__/Touchable.test.tsx.web-snap
- src/ui/components/DotComponent.tsx
- src/ui/components/achievements/components/ControlComponent.tsx
- src/ui/components/achievements/components/GenericAchievementCard.tsx
- src/ui/components/buttons/AppButton/styleUtils.ts
- src/ui/svg/icons/Dot.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14389
I have:
> (PC-14389) fix(accessibility): Make FirstTutorial more accessible

- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14469
I have:
> (PC-14469) fix(booking): update wording on site collect

- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/venue/pages/VenueBody.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14471
I have:
> (PC-14471) fix(accessibility): Add label to introduce venue name

- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/TabBar/__tests__/TabBar.native.test.tsx.native-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- src/features/favorites/atoms/BicolorFavoriteCount.tsx
- src/features/favorites/components/FavoritesResults.tsx
- src/features/favorites/components/NoFavoritesResult.tsx
- src/features/navigation/TabBar/TabBarComponent.tsx
- src/features/navigation/TabBar/TabBarContainer.tsx
- src/features/search/components/SearchLandingPage.tsx
- src/features/search/components/SearchResults.tsx
- src/libs/styled/useComputedTheme.ts
- src/locales/fr/messages.po
- src/theme/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14425
I have:
(Pas de changement au niveau du header web)
| ![Simulator Screen Shot - iPhone 13 - 2022-04-14 at 09 18 40](https://user-images.githubusercontent.com/46637324/163336738-48c59597-0afa-4ff0-ac65-8aec54ea4301.png)   |   ![Screenshot_1649921408](https://user-images.githubusercontent.com/46637324/163336792-0315a2a8-ccdc-48a9-91eb-e0a2aeba210a.png)     |  ![Simulator Screen Shot - iPhone 13 - 2022-04-14 at 10 23 15](https://user-images.githubusercontent.com/46637324/163345001-ff3d99f5-50b6-4961-8714-0cf9c9264fd5.png)       |  Screen 320px :<img width="320" alt="Capture …
> (PC-14425) feat(accessibility): Add text labels to tabBar

- src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14493
I have:
> (PC-14493) fix(booking): QR code deletion restriction

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14519
PR pour fix 3 vulnérabilités critiques 
I have:
> (PC-14519) fix(vulnerability): update appcenter-cli

- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx.native-snap
- src/api/gen/api.ts
- src/libs/parsers/culturalSurveyType.ts
- src/libs/parsers/tests/culturalSurveyType.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13341
I have:
> (PC-13341) fix(CulturalSurvey): Update mapping api

- src/features/bookings/atoms/TicketCode.tsx
- src/features/bookings/atoms/TicketCode.web.tsx
- src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/bookings/components/BookingDetailsTicketContent.web.test.tsx
- src/features/bookings/helpers.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14472
I have:
> (PC-14472) fix(booking): refactor naming collect by withdrawal

- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- src/ui/components/achievements/components/GenericAchievement.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14470
I have:
|      |         |                 |                    https://user-images.githubusercontent.com/46637324/163558929-7f6e1976-dd8b-43b7-99e0-267f653cd5c4.mp4      |     |
> (PC-14470) fix(accessibility): Autofocus on skip button after click on next icon

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
- src/features/profile/pages/ConsentSettings.tsx
- src/features/search/atoms/NoSearchResult.tsx
- src/ui/components/buttons/buttonInsideText/ButtonInsideText.stories.tsx
- src/ui/components/buttons/buttonInsideText/ButtonInsideText.tsx
- src/ui/components/buttons/buttonInsideText/ButtonInsideText.web.tsx
- src/ui/components/buttons/buttonInsideText/ButtonInsideTextInner.tsx
- src/ui/components/buttons/buttonInsideText/__tests__/ButtonInsideText.native.test.tsx
- src/ui/components/buttons/buttonInsideText/__tests__/ButtonInsideText.web.test.tsx
- src/ui/components/buttons/buttonInsideText/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14439
I have:
|  <img width="322" alt="Capture d’écran 2022-04-14 à 18 48 43" src="https://user-images.githubusercontent.com/62059034/163436155-002daa1a-fa11-4f01-aab2-5462af6b43a2.png"> <img width="322" alt="Capture d’écran 2022-04-14 à 18 48 29" src="https://user-images.githubusercontent.com/62059034/163436159-f533bfab-88eb-4ed5-adf4-24b6518bf042.png"> <img width="324" alt="Capture d’écran 2022-04-14 à 18 49 03" src="https://user-images.githubusercontent.com/62059034/163436150-9ea4e44c-b476-4ccc-87dd-57a501a6950e.png">   |         |                 |       <img …
> (PC-14439) feat(accessibility): align button with text 

- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx.web-snap
- src/features/culturalSurvey/__tests__/useCulturalSurveyProgress.test.ts
- src/features/culturalSurvey/context/CulturalSurveyContextProvider.tsx
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
- src/features/culturalSurvey/useCulturalSurveyProgress.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13346
I have:
> (PC-13346) feat(CulturalSurvey): Link the progress with the reducer

- src/api/gen/api.ts
- src/features/auth/__mocks__/settings.ts
- src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/bookings/components/BookingDetailsTicketContent.web.test.tsx
- src/features/bookings/pages/BookingDetails.tsx
- src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14139
I have:
> (PC-14139) feat(booking): remove feature flag qr code

- src/features/bookings/components/BookingDetailsTicketContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14139
I have:
> (PC-14139) fix(booking): add missing space delay

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14028
I have:
> (PC-14028) ci(prod): update wording for prod build notification

- src/ui/components/achievements/components/GenericAchievement.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14470
I have:
> (PC-14470) fix(accessibility): Focus on skip button on previous click in tutorial

- src/features/bookings/components/BookingDetailsTicketContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14139
I have:
> (PC-14139) fix(booking): add missing space on site withdrawal

- src/ui/components/StepDots.stories.tsx
- src/ui/components/StepDots.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14650
I have:
|   <img width="323" alt="Capture d’écran 2022-04-25 à 09 48 15" src="https://user-images.githubusercontent.com/62059034/165085405-dd76498f-db0e-4e1c-a869-e36a08e5c2f3.png">  |         |        |    <img width="1792" alt="Capture d’écran 2022-04-25 à 09 48 27" src="https://user-images.githubusercontent.com/62059034/165085448-6bb5caed-bf49-4fe5-a22b-10b0a3f71cac.png">     |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-b …
> (PC-14650) feat(StepDots): align stepDots

- src/features/bookings/components/OnGoingBookingItem.native.test.tsx
- src/features/bookings/components/OnGoingBookingItem.tsx
- src/features/bookings/helpers.test.ts
- src/features/bookings/helpers.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14448
I have:
> (PC-14448) fix(booking): show withdrawal delay booking list

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.native-snap
- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14652
I have:
|     |         |                 |    ![Capture d’écran 2022-04-26 à 14 48 43](https://user-images.githubusercontent.com/62059034/165303381-68f3f36a-0a83-48d1-82d2-bdec5ff51432.png)   |                  |
> (PC-14652) feat(deeplinksGenerator): update wording

- scripts/upload_sourcemaps_to_sentry.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-1235
I have:
> fix(upload_sourcemaps_to_sentry): improve source map generation script

- src/api/__tests__/apiHelpers.test.ts
- src/api/apiHelpers.ts
À reviewer après https://github.com/pass-culture/pass-culture-app-native/pull/2938
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14060
On se demandait s'il fallait ajouter un délai d'attendre avant de lancer la seconde requete et si oui de combien de temps
I have:
> (PC-14060) feat(apiHelpers): retry to generate access token when it fails

- __snapshots__/features/identityCheck/components/layout/PageWithHeader.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnectForm.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckValidation.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetStatus.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetStatus.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/Status.native.test.tsx.native-snap
- src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/components/layout/PageWithHeader.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
- src/features/identityCheck/pages/profile/SetStatus.tsx
- src/features/identityCheck/pages/profile/__test__/SetStatus.native.test.tsx
- src/features/identityCheck/pages/profile/__test__/SetStatus.web.test.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14121
I have:
| iOS | Android | Desktop - Chrome |
| --: | ------: | --------------: | 
|   <img width="365" alt="Capture d’écran 2022-04-27 à 15 22 07" src="https://user-images.githubusercontent.com/44037911/165527699-b06ccaf0-b7bb-407c-b71b-f0338f7d72fc.png">  |         |     <img width="1163" alt="Capture d’écran 2022-04-27 à 15 22 43" src="https://user-images.githubusercontent.com/44037911/165527805-a2479ca2-7961-4bc2-a205-b8a4ef8c9ef2.png">            |
> (PC-14121) feat(signup): add info banner in set name screen

- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/culturalSurvey/components/CulturalSurveyCheckbox.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.native.test.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.web.test.tsx
- src/features/culturalSurvey/context/CulturalSurveyContextProvider.tsx
- src/features/culturalSurvey/context/__mocks__/CulturalSurveyContextProvider.tsx
- src/features/culturalSurvey/context/reducer.ts
- src/features/culturalSurvey/context/types.ts
- src/features/culturalSurvey/helpers/__tests__/utils.test.ts
- src/features/culturalSurvey/helpers/utils.ts
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
- src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx
- src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14395
I have:
> (PC-14395) feat(CulturalSurvey): Save answers on reducer for the questions navigation

- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/libs/ABTesting/ABTestingPOC.tsx
- src/libs/ABTesting/ABTestingPOC.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14553
I have:
hots
> (PC-14553) feat(firebase): POC A/B Testing

- src/libs/ABTesting/ABTestingPOC.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14553
I have:
> (PC-14553) fix(ci): add missing dep on ABTesting web

- src/ui/components/SocialNetworkCard.tsx
- src/ui/components/__tests__/SocialNetworkCard.test.tsx
- src/ui/components/touchableLink/TouchableLink.tsx
- src/ui/components/touchableLink/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14629
Multiple click on TouchableLink generated a popup error message because redirect was requested when it was already done.
I have:
|https://user-images.githubusercontent.com/78556024/165928447-3395b1b5-3b91-4d0d-819f-d339fbf0c599.mov| https://user-images.githubusercontent.com/78556024/165928538-6a6c0617-618d-4d48-9bfc-543395e1ce1d.mov| 
> (PC-14629) fix(link): avoid multiple click

- src/features/profile/pages/DeleteProfile/DeleteProfileSuccessV2.tsx
- src/locales/fr/messages.po
- src/ui/components/Emoji.stories.tsx
- src/ui/components/Emoji.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14804
I have:
|    ![Simulator Screen Shot - iPhone 13 - 2022-05-02 at 11 34 20](https://user-images.githubusercontent.com/46637324/166214417-e022e7be-ebf4-447a-ab42-864f91a8a1a9.png) |      ![Screenshot_1651484055](https://user-images.githubusercontent.com/46637324/166214406-9f872908-7d75-4838-ad0c-bbe28ff5da68.png)   |                 |     <img width="1440" alt="Capture d’écran 2022-05-02 à 11 34 32" src="https://user-images.githubusercontent.com/46637324/166214392-7666e759-2fc2-45c3-bb5a-a7b5193c8632.png">    |                  |
[1]: …
> (PC-14804) feat(emojis): Add component to handle emojis correctly

- src/features/offer/pages/Offer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14799
I have:
> (PC-14799) fix(offer): avoid multiple click

- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
- src/features/auth/components/OpenInboxButton.tsx
- src/features/auth/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14806
I have:
|   ![Simulator Screen Shot - iPhone 13 - 2022-05-02 at 14 57 26](https://user-images.githubusercontent.com/46637324/166237362-0c9e3bc4-e047-419f-9722-bc3af009550c.png)  |         |                 |    <img width="1174" alt="Capture d’écran 2022-05-02 à 14 57 38" src="https://user-images.githubusercontent.com/46637324/166237345-e0053abd-179b-49f2-a296-674d279ecbe2.png">         |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur …
> (PC-14806) feat(ProfileDeletion): Update wording in ResetPasswordEmailSent

- src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14832
I have:
| Generator form | Universal Link | FDL | 
| --: | ------: | --------------: | 
| ![image](https://user-images.githubusercontent.com/77674046/166429474-e8b7396b-e842-489f-ad00-a3d0e5efa072.png) |![image](https://user-images.githubusercontent.com/77674046/166429537-c21d255e-e846-4744-afe6-dd15d56d2bc1.png) |![image](https://user-images.githubusercontent.com/77674046/166429590-a3c1dd90-dfe6-4e67-9678-de241ae8cfe8.png) |
> (PC-14832) fix(DeeplinkGenerator): fix configuration for tags

- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14571
I have:
|  ![Simulator Screen Shot - iPhone SE (2nd gen) - 2022-05-03 at 12 00 51](https://user-images.githubusercontent.com/46637324/166435923-68152ed1-66dc-4ca2-a2a5-a6babdb889ed.png)   |         |                 |                  |                  |
> (PC-14571) fix(ProfileDeletion): Fix buttons not aligned

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.web-snap
- src/api/apiHelpers.ts
- src/features/identityCheck/errors/eduConnect/EduConnectErrorBoundary.tsx
- src/features/identityCheck/errors/eduConnect/__test__/EduConnectErrorBoundary.test.tsx
- src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
- src/features/identityCheck/pages/errors/EduConnectErrors.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx
- src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
- src/features/identityCheck/utils/useEduConnectLogin.ts
- src/libs/eduConnectClient.ts
> (PC-14256) feat(educonnect): better handle errors

- .env.integration
- .env.production
- .env.staging
- .env.testing
- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- ios/PassCulture/PassCulture.entitlements
- src/features/navigation/RootNavigator/linking/index.ts
- src/libs/environment/__mocks__/env.ts
- src/libs/environment/__mocks__/env.web.ts
- src/libs/environment/__mocks__/envFixtures.ts
- src/libs/environment/env.ts
- src/libs/environment/index.ts
- src/libs/environment/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14910
I have:
> (PC-14910) fix(Applinks): remove unecessary r.email.passculture.app applinks

- src/api/__tests__/apiHelpers.test.ts
- src/api/apiHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14890
I have:
> (PC-14890) feat(apiHelpers): add random request-id to request headers in safeFetch

- android/app/src/main/AndroidManifest.xml
- public/.well-known/assetlinks-production.json
- public/.well-known/assetlinks-staging.json
- public/.well-known/assetlinks-testing.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14839
I have:
> (PC-14839) fix(Applinks): correct applinks, assetlinks all envs (required Android 12)

- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx.web-snap
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14827
I have:
|     |         |                 |            https://user-images.githubusercontent.com/44037911/166902921-69facbce-5c85-484b-a3c2-690e9e29a9b4.mov      |                  |
> (PC-14827) fix(QPI): fix cultural survey questions display

- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/navigation/RootNavigator/Header/Nav.tsx
- src/features/navigation/RootNavigator/Header/NavItem.tsx
- src/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx
- src/features/navigation/RootNavigator/Header/tests/Header.web.test.tsx
- src/features/navigation/TabBar/TabBarComponent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14796
I have:
> (PC-14796) fix(accessibility): Identify current page and fix style in navigation bar

- src/libs/analytics/provider.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15003
https://sentry.internal-passculture.app/organizations/sentry/issues/376671/?environment=production&project=6&query=is%3Aunresolved&statsPeriod=1h
https://sentry.internal-passculture.app/organizations/sentry/issues/376044/?environment=production&project=6&query=is%3Aunresolved&statsPeriod=1h
https://sentry.internal-passculture.app/organizations/sentry/issues/375957/?environment=production&project=6&query=is%3Aunresolved&statsPeriod=1h
https://sentry.internal-passculture.app/organizations/sentry/issues/378266/?environment=production&project=6&query=is%3Aunresolved&statsPeriod=1h
https://sentry.internal-passculture.app/organizations/sentry/issues/376060/?environment=production&project=6&query=is%3Aunresolved&statsPeriod=1h …
> (PC-15003) fix(analytics): do not call setDefaultEventParameters on the Web (Sentry error)

- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- src/ui/components/inputs/PasswordInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15047
I have:
> (PC-15047) fix(PasswordInput): do not capitalize first letter

- src/features/bookOffer/components/BookDateChoice.tsx
- src/features/bookOffer/components/BookDuoChoice.tsx
- src/features/bookOffer/components/BookHourChoice.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
- src/features/offer/pages/OfferDescription.tsx
- src/ui/components/GenericInfoPage.tsx
- src/ui/components/hero/HeroHeader.tsx
- src/ui/components/inputs/InputContainer.tsx
- src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14039
issue sonar: https://sonarcloud.io/project/issues?issues=AX37aHNLk-Fb4wgiIWuc&open=AX37aHNLk-Fb4wgiIWuc&id=pass-culture_pass-culture-app-native
I have:
> (PC-14039) refactor(quality): extract nested ternary operations

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- src/features/identityCheck/atoms/StepButton.tsx
- src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/navigation/RootNavigator/Header/Nav.tsx
- src/locales/fr/messages.po
- src/ui/components/ValidationMark.tsx
- src/ui/web/global/Footer.web.tsx
- src/ui/web/global/Header.web.tsx
- src/ui/web/global/Main.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14953
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14956
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14965
I have:
> (PC-14953) fix(accessibility): Fix various aria attributes (PC-14956) (PC-14965)

- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.native.test.tsx.native-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetStatus.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetStatus.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- src/features/favorites/pages/FavoritesSorts.tsx
- src/features/identityCheck/atoms/CenteredTitle.tsx
- src/features/identityCheck/pages/profile/SetSchoolType.tsx
- src/features/identityCheck/pages/profile/SetStatus.tsx
- src/features/search/atoms/TitleWithCount.tsx
- src/features/search/pages/Categories.tsx
- src/features/search/pages/LocationFilter.tsx
- src/features/search/pages/LocationPicker.tsx
- src/features/search/pages/SuggestedPlaces.tsx
- src/features/search/sections/Category.tsx
- src/features/search/sections/OfferDate.tsx
- src/features/search/sections/OfferType.tsx
- src/ui/components/headers/PageHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15000
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14995
I have:
> (PC-15000) fix(accessibility): Nest radio buttons and checkboxes in group role (PC-14995)

- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- src/libs/share/SocialButton.tsx
- src/libs/share/WebShareModal.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14964
I have:
> (PC-14964) fix(accessibility): Use unordered list for social buttons

- src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15085
I have:
| Avant | Après | 
| --: | ------: | 
| <img width="1440" alt="Capture d’écran 2022-05-16 à 15 32 20" src="https://user-images.githubusercontent.com/78556024/168761633-1256dfd4-3e40-476d-9d0f-f7cb4ebcbd9a.png">|<img width="1440" alt="Capture d’écran 2022-05-16 à 15 32 02" src="https://user-images.githubusercontent.com/78556024/168761726-337f7e58-ce50-41d5-9863-94cc7379a202.png">| 
> (PC-15085) fix(search): add more space accessibility phrase

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- src/ui/components/InputLabel/FlexInputLabel.tsx
- src/ui/components/InputLabel/FlexInputLabel.web.tsx
- src/ui/components/inputs/PasswordInput.tsx
- src/ui/components/inputs/TextInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15076
I have:
**Pas de régression visuelle**
|  ![Simulator Screen Shot - iPhone 13 - 2022-05-17 at 15 55 03](https://user-images.githubusercontent.com/46637324/168815729-af7728dc-3384-4e63-b2f1-974643940771.png) |    ![Screenshot_1652796602](https://user-images.githubusercontent.com/46637324/168831475-83a955d1-5ba0-4394-96fe-89904dbd623c.png)     |                 |                  | <img width="1123" alt="Capture d’écran 2022-05-17 à 15 55 30" src="https://user-images.githubusercontent.com/46637324/168815696-d33f332c-2fdb-4817-acbe-b7471693688d.png">      |
[1]: …
> (PC-15076) fix(accessibility): Include required in label tag

- src/features/cheatcodes/pages/AppComponents/iconsExports.ts
- src/features/identityCheck/pages/Stepper.tsx
- src/features/identityCheck/types.ts
- src/features/identityCheck/useIdentityCheckSteps.tsx
- src/locales/fr/messages.po
- src/ui/components/ValidationMark.tsx
- src/ui/svg/icons/Invalidate.tsx
- src/ui/svg/icons/Smartphone.tsx
- src/ui/svg/icons/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14454
I have:
> (PC-14454) feat(Stepper): Create Stepper V2 for identitycheck

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/ui/components/inputs/TextInput.native.test.tsx.native-snap
- src/ui/components/inputs/InputContainer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15095
I have:
|  ![Simulator Screen Shot - iPhone 13 - 2022-05-23 at 10 59 55](https://user-images.githubusercontent.com/46637324/169783872-4f5ec308-0fdc-468c-b265-7803327b1166.png) ![Simulator Screen Shot - iPhone 13 - 2022-05-23 at 11 00 50](https://user-images.githubusercontent.com/46637324/169783885-93758226-32d8-44b0-937c-b1e9e554f44e.png) ![Simulator Screen Shot - iPhone 13 - 2022-05-23 at 11 01 38](https://user-images.githubusercontent.com/46637324/169783887-6a3a7ded-febf-4590-923f-18ebe147868f.png)  ![Simulator Screen Shot - iPhone 13 - 2022-05-23 at 11 03 …
> (PC-15095) fix(accessibility): Remove shadows for text inputs

- src/libs/algolia/__tests__/fetchMultipleVenues.test.ts
- src/libs/algolia/enums/facetsEnums.ts
- src/libs/algolia/fetchAlgolia/fetchMultipleVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14947
I have:
> (PC-14947) feat(home): do not show venues without searchable offers on home page

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.native-snap
- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.native.test.tsx.native-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/PersonalData/__tests__/PersonalData.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
- src/locales/fr/messages.po
- src/ui/components/FilterSwitch.tsx
- src/ui/components/headers/PageHeader.tsx
- src/ui/components/modals/ModalHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15078
I have:
|     |         |                 |       <img width="660" alt="Capture d’écran 2022-05-23 à 15 05 48" src="https://user-images.githubusercontent.com/62059034/169826234-3d6b7931-83ec-4995-81ab-c468aaaa105c.png">   |                  |
> (PC-15078) feat(accessibility): add HiddenText for previous button and toggle

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueHeader.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/ui/components/achievements/components/ControlComponent.web.test.tsx.web-snap
- src/ui/components/touchable/Touchable.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15096
I have:
|     |         |                 | <img width="264" alt="Capture d’écran 2022-05-24 à 11 36 14" src="https://user-images.githubusercontent.com/62059034/170001117-17b4fad5-8fe8-47fc-aada-08cf034b0a35.png">   |                  |
> (PC-15096) feat(accessibility): add title to Touchable

- __snapshots__/ui/components/inputs/Slider.native.test.tsx.native-snap
- src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/search/sections/Price.tsx
- src/features/search/sections/Radius.tsx
- src/features/search/sections/TimeSlot.tsx
- src/locales/fr/messages.po
- src/ui/components/inputs/Slider.native.test.tsx
- src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15094
I have:
|     |         |                 |           <img width="1055" alt="Capture d’écran 2022-05-24 à 13 26 52" src="https://user-images.githubusercontent.com/62059034/170026320-227e31dd-cecc-4672-b215-5938c2aa4cc5.png"> |                  |
> (PC-15094) feat(accessibility): add custom label for Slider

- src/features/identityCheck/__mocks__/nextSubscriptionStepFixture.ts
- src/features/identityCheck/__test__/useIdentityCheckSteps.test.tsx
- src/features/identityCheck/atoms/StepButton.tsx
- src/features/identityCheck/pages/__test__/Stepper.test.tsx
- src/features/identityCheck/pages/identification/__test__/IdentityCheckEnd.test.tsx
- src/features/profile/components/NonBeneficiaryHeader.native.test.tsx
- src/features/profile/components/NonBeneficiaryHeader.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14454
I have:
> (PC-14454) fix(PhoneVal): Fix stepper display for smaller screens

- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.native-snap
- __snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.web-snap
- src/features/landscapePosition/LandscapePositionPage.tsx
- src/features/landscapePosition/useIsLandscapePosition.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15024
I have:
> (PC-15024) fix(accessibility): Fix landscape detection for ios in web

- src/libs/algolia/fetchAlgolia/fetchAlgolia.ts
- src/libs/algolia/fetchAlgolia/fetchVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15126
I have:
> (PC-15126) refactor(algolia): minor refactors before doing feature

- .vscode/settings.json
> build(vscode): improve VSCode LiveShare's experience for participants

- src/features/auth/AuthContext.tsx
- src/features/auth/signup/SignupForm.tsx
- src/features/bookOffer/pages/BookingOfferWrapper.tsx
- src/features/identityCheck/pages/profile/utils.ts
- src/features/navigation/helpers/usePreviousRoute.ts
- src/libs/ABTesting/ABTesting.services.ts
- src/libs/algolia/fetchAlgolia/fetchAlgolia.ts
- src/libs/fetch.ts
- src/ui/theme/grid.ts
[Résolution de l'issue Sonar des variables inutiles](https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS1488&types=CODE_SMELL&id=pass-culture_pass-culture-app-native&open=AX37aG-yk-Fb4wgiIWsG)
> fix(sonar): remove 9 warnings based on useless variables

- src/theme/index.ts
- src/ui/components/FilterSwitch.tsx
- src/ui/theme/colors.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15293
I have:
|     |         |                 |   <img width="1792" alt="Capture d’écran 2022-05-27 à 09 38 00" src="https://user-images.githubusercontent.com/62059034/170657831-ffe24e4c-10c7-4a01-af6a-9a4ce6ea3e7a.png"> <img width="1792" alt="Capture d’écran 2022-05-27 à 14 39 12" src="https://user-images.githubusercontent.com/62059034/170700862-478fd8b8-0f18-49b1-b538-98eba0547474.png">  |                  |
> (PC-15293) feat(theme): add new GreySemiDark color and remove unused color FilterButton

- __snapshots__/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.native.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.web.test.tsx.web-snap
- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx.web-snap
- src/features/culturalSurvey/components/CulturalSurveyCheckbox.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.native.test.tsx
- src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.web.test.tsx
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
- src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx
- src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15183
I have:
> (PC-15183) fix(QPI): gray out continue button if nothing selected qpi

- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx.web-snap
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15252
I have:
| iOS 12 | iOS iPhone 8 | Desktop - Chrome | 
| --: | ------: | --------------: | 
|    <img width="313" alt="Capture d’écran 2022-05-27 à 15 03 34" src="https://user-images.githubusercontent.com/44037911/170707654-fa8ce1f3-0736-4553-b904-c763b290b8bd.png"> |   <img width="313" alt="Capture d’écran 2022-05-27 à 15 03 41" src="https://user-images.githubusercontent.com/44037911/170707687-25435700-a970-46d7-9dbe-36cf0c028fb9.png">      |        <img width="955" alt="Capture d’écran 2022-05-27 à 15 21 47" src="https://user-images.githubusercontent.com/44037911/170707720-929f4aa9-31ac-400c-9e8b-701daf0db1f5.png">         |               
[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/d …
> (PC-15252) fix(QPI): lower header to prevent status bar overlap

- src/libs/hooks/__tests__/useShowReview.test.tsx
- src/libs/network/__tests__/useNetwork.native.test.ts
- src/libs/trackingConsent/__tests__/useTrackingConsent.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15067
> (PC-15067) feat(tests): add tests hooks 

- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/ui/components/inputs/SearchInput.native.test.tsx.native-snap
- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchBoxRework.tsx
- src/features/search/components/__tests__/SearchBox.native.test.tsx
- src/features/search/components/__tests__/SearchBoxRework.native.test.tsx
- src/ui/components/inputs/SearchInput.tsx
- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14846
I have:
> (PC-14846) feat(search): execute search with at least one letter

- src/features/search/components/CalendarPicker.web.tsx
- src/features/search/utils/isBeforeToday.ts
- src/features/search/utils/tests/isBeforeToday.test.ts
- src/libs/i18n.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15317
issues : 
- https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS1301&id=pass-culture_pass-culture-app-native  
- https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS1871&types=CODE_SMELL&id=pass-culture_pass-culture-app-native&open=AX37aHEWk-Fb4wgiIWtC
> (PC-15317) fix(sonar): remove unnecessary switch

- scripts/upload_sourcemaps_to_sentry.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14133
Related to https://passculture.atlassian.net/browse/PC-15330
[Exemple erreur Sentry iOS Hard](https://sentry.internal-passculture.app/organizations/sentry/issues/382353/?environment=testing&project=6&query=is%3Aunresolved+665&statsPeriod=1h):
À faire ensuite pour les code pushs: https://passculture.atlassian.net/browse/PC-15344
I have:
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur- …
> (PC-14133) fix(Sentry): sourcemap for iOS hard

- src/features/auth/signup/SetEmail/SetEmail.tsx
- src/features/bookings/pages/BookingDetails.tsx
- src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
- src/features/navigation/RootNavigator/linking/getScreensConfig.ts
- src/libs/country-picker/CountryPicker.tsx
- src/ui/components/achievements/components/GenericAchievement.tsx
- src/ui/components/inputs/Slider.tsx
- src/ui/components/modals/useModal.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15302
> (PC-15302) fix(sonar): fix "already declared in upper scope" warning

- __snapshots__/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx.native-snap
- __snapshots__/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx.web-snap
- src/api/gen/api.ts
- src/features/auth/suspendedAccount/SuspendedAccount/SuspendedAccount.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/tests/useAccountUnsuspend.test.ts
- src/features/auth/suspendedAccount/SuspendedAccount/useAccountUnsuspend.ts
- src/features/auth/suspendedAccount/SuspensionScreen/SuspensionScreen.tsx
- src/features/auth/suspendedAccount/SuspensionScreen/tests/SuspensionScreen.test.tsx
- src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileSuccessV2.tsx
- src/features/profile/pages/DeleteProfile/__tests__/DeleteProfileSuccess.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14564
I have:
> (PC-14564) feat(AccountReactivation): Handle account reactivation

- src/features/forceUpdate/useMustUpdateApp.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14954
I have:
> (PC-14954) fix(mustUpdateApp): added logging

- __snapshots__/features/search/components/__tests__/CategoryButton.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/CategoryButton.test.tsx.web-snap
- src/features/search/components/CategoryButton.stories.tsx
- src/features/search/components/CategoryButton.tsx
- src/features/search/components/__tests__/CategoryButton.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14994
I have:
|     |         |                 |<img width="1437" alt="Capture d’écran 2022-06-01 à 12 14 54" src="https://user-images.githubusercontent.com/78556024/171415322-3acfb570-0689-4e50-8042-c436ee83aa63.png">|                  |
> (PC-14994) feat(categoryButton): visual updates

- src/features/bookings/pages/BookingDetails.tsx
if consultation booking
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15268
I have:
|     |         |                 |![Capture d’écran 2022-05-31 à 18 27 44](https://user-images.githubusercontent.com/78556024/171225858-0d7d92b6-a378-436b-bd52-5805ddf7dbcb.png)|                  |
> (PC-15268) fix(booking): show error cancelation Flask Admin if booking consultation

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
- src/features/auth/components/PasswordSecurityRules.tsx
- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchBoxRework.tsx
- src/features/search/components/SearchHeaderRework.tsx
- src/features/search/components/SearchLandingPage.tsx
- src/features/search/pages/LocationPicker.tsx
- src/features/search/pages/SuggestedPlaces.tsx
- src/locales/fr/messages.po
- src/ui/components/FilterSwitch.tsx
- src/ui/components/HiddenAccessibleText.tsx
- src/ui/components/HiddenText.tsx
- src/ui/components/headers/PageHeader.tsx
- src/ui/components/modals/ModalHeader.tsx
- src/ui/web/text/HiddenAccessibleText.tsx
- src/ui/web/text/HiddenAccessibleText.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14144
Co-authored-by: Ali RAIKI <ali.raiki@polyconseil.fr>
I have:
> (PC-15144) feat(search): add conditional hidden title to searchBoxRework

- __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
- __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
- src/ui/components/achievements/components/GenericAchievementCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14259
I have:
|  ![Capture d’écran 2022-06-02 à 17 48 32](https://user-images.githubusercontent.com/62059034/171674899-8edaefe7-d5ac-4412-be79-626be76facf7.png) ![Capture d’écran 2022-06-02 à 17 48 40](https://user-images.githubusercontent.com/62059034/171674904-56ef3834-9b59-4be1-b51e-ac212e50b8fd.png) ![Capture d’écran 2022-06-02 à 17 48 46](https://user-images.githubusercontent.com/62059034/171674909-69caf1dd-5cc6-48a1-9619-48eaa84afa1d.png) ![Capture d’écran 2022-06-02 à 17 48 52](https://user-images.githubusercontent.com/62059034/171674911-f3a81f0b-86c5-4748-9e80-3e37 …
> (PC-14259) fix(GenericAchievementCard): fix scrollbar

- __snapshots__/features/search/components/__tests__/CategoryButton.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/CategoryButton.test.tsx.web-snap
- src/features/search/components/CategoryButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14994
I have:
|     |         |                 |<img width="721" alt="Capture d’écran 2022-06-02 à 18 00 03" src="https://user-images.githubusercontent.com/78556024/171673827-5c3a99e1-8898-4c1d-86dd-ca4d6e3e5921.png">|                  |
> (PC-14994) refactor(categoryButton): visual adaptations

- server/jest.config.ts
> test(server): increase test threshold to 100%

- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchBoxRework.tsx
- src/ui/components/inputs/SearchInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14846
I have:
> (PC-14846) feat(search): remove block search without value android

- .circleci/config.yml
> ci(server): manual deploy of server

- src/features/bookings/pages/BookingDetails.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15268
This PR corrects the Lingui bug display in testing (in local it was ok without) :
I have:
> (PC-15268) fix(booking): lingui bug canceled booking

- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/DMSModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
- __snapshots__/libs/country-picker/CountryPicker.native.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.native-snap
- src/theme/index.ts
- src/ui/components/modals/AppModal.tsx
- src/ui/theme/accessibilityRole/accessibilityRole.ts
- src/ui/theme/accessibilityRole/accessibilityRole.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15305
I have:
> (PC-15305) fix(AppModal): add AccessibilityRoleEnum dialog

- src/features/forceUpdate/useMustUpdateApp.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14954
I have:
> (PC-14954) fix(mustUpdate): added some sentry logging to check if value as not been updated

- src/api/gen/api.ts
- src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx
- src/features/bookings/components/BookingDetailsTicketContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15389
I have:
|     |         |                 |     <img width="1792" alt="Capture d’écran 2022-06-07 à 12 00 05" src="https://user-images.githubusercontent.com/62059034/172353193-aca95889-419c-4739-a154-6390fe40da40.png"> |                  |
> (PC-15389) fix(BookingDetails): not display ticket token when is null

- package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15476
I have:
> (PC-15476) fix(indexhtml): update description

- __snapshots__/features/search/components/__tests__/CategoryButton.test.tsx.native-snap
- src/features/search/components/CategoriesButtons.stories.tsx
- src/features/search/components/CategoriesButtons.tsx
- src/features/search/components/CategoryButton.stories.tsx
- src/features/search/components/CategoryButton.tsx
- src/features/search/components/__tests__/CategoriesButtons.test.tsx
- src/features/search/components/__tests__/CategoryButton.test.tsx
- src/features/search/pages/Search.tsx
- src/features/search/pages/__tests__/Search.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14996
I have:
> (PC-14996) feat(search): add `CategoriesButtons` component

- src/features/bookings/components/BookingPropertiesSection.native.test.tsx
- src/features/bookings/getLocationLabel.test.ts
- src/features/bookings/getLocationLabel.ts
- src/features/bookings/helpers.test.ts
- src/features/bookings/helpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9655
I have:
> (PC-9655) feat(booking): display venue public name

- server/src/index.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15528
I have:
> (PC-15528) test(server): fix flacky test

- src/libs/share/WebShareModal.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15526
I have:
> (PC-15526) fix(Web): sharing on telegram iOS/Android with URL

- src/api/gen/api.ts
- src/features/auth/__mocks__/settings.ts
- src/features/auth/login/Login.native.test.tsx
- src/features/auth/login/Login.tsx
- src/features/auth/suspendedAccount/AccountReactivationSuccess/AccountReactivationSuccess.tsx
- src/features/auth/suspendedAccount/AccountReactivationSuccess/tests/AccountReactivation.test.tsx
- src/features/auth/suspendedAccount/FraudulentAccount/FraudulentAccount.tsx
- src/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.native.test.tsx
- src/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.web.test.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/SuspendedAccount.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx
- src/features/auth/suspendedAccount/SuspensionScreen/SuspensionScreen.tsx
- src/features/auth/suspendedAccount/SuspensionScreen/tests/SuspensionScreen.test.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileSuccess.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileSuccessV2.tsx
- src/features/profile/pages/DeleteProfile/__tests__/DeleteProfileSuccess.test.tsx
- src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15329
I have:
> (PC-15329) refactor(AccountReactivation): Rename account reactivation feature flip

- patches/@sentry+browser+6.19.2.patch
while waiting for sentry feedback here https://github.com/getsentry/sentry-javascript/issues/5230
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15472
I have:
> (PC-15472) fix(Sentry): do not use sendBeacon, use fetch instead

- src/features/bookOffer/components/Calendar/MonthHeader.tsx
- src/features/search/components/CalendarPicker.tsx
- src/features/search/components/CalendarPicker.web.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15504
I have:
|     |         |                 |     ![Capture d’écran 2022-06-08 à 12 57 40](https://user-images.githubusercontent.com/62059034/172600073-e485e30a-307e-4474-85f8-14a6e5383bfe.png)  |                  |
> (PC-15504) feat(accessiblity): add title to CalendarPicker web

- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/ui/components/inputs/SearchInput.native.test.tsx.native-snap
- src/features/search/components/SearchBoxRework.tsx
- src/features/search/components/SearchHeaderRework.tsx
- src/features/search/components/__tests__/SearchBoxRework.native.test.tsx
- src/ui/components/inputs/SearchInput.native.test.tsx
- src/ui/components/inputs/SearchInput.stories.tsx
- src/ui/components/inputs/SearchInput.tsx
- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14845
I have:
|<img width="367" alt="Capture d’écran 2022-06-07 à 15 27 54" src="https://user-images.githubusercontent.com/78556024/172392604-5b31ac99-066e-47e3-8c0d-820cfe2ef0d8.png"> <img width="360" alt="Capture d’écran 2022-06-07 à 15 28 12" src="https://user-images.githubusercontent.com/78556024/172392619-c39c42c9-73a9-4369-abc5-ed649e7fcfdd.png">||<img width="1440" alt="Capture d’écran 2022-06-07 à 15 27 14" src="https://user-images.githubusercontent.com/78556024/172392702-b5eb7648-cd4f-4e04-a9a5-c3fe4d94eaab.png"> <img width="1440" alt="Capture d’écran 2022-06-07 à …
> (PC-14845) feat(search): input space adaptations

- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- src/features/search/components/CategoriesButtons.tsx
- src/features/search/pages/Search.tsx
- src/features/search/pages/SearchLegacy.tsx
- src/features/search/pages/SearchRework.tsx
* reworked is the new version behind a feature flag
* legacy will be deleted after the feature flag has been enabled
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14996
I have:
> (PC-14996) refactor(search): split legacy and reworked search

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.native.test.tsx.native-snap
- __snapshots__/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.web.test.tsx.web-snap
- __snapshots__/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx.native-snap
- __snapshots__/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx.web-snap
- __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.web-snap
- src/features/auth/suspendedAccount/FraudulentAccount/FraudulentAccount.tsx
- src/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.native.test.tsx
- src/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.web.test.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/SuspendedAccount.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx
- src/ui/components/GenericInfoPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15880
I have:
> (PC-15880) fix(GenericInfoPage): remove headerGoBack

- src/features/bookOffer/components/Calendar/Calendar.tsx
- src/features/search/pages/reducer.ts
- src/libs/parsers/getDisplayPrice.ts
- src/libs/search/datetime/date.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15273
https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS4043&types=CODE_SMELL&id=pass-culture_pass-culture-app-native
I have:
> (PC-15273) fix(sonar): fix array sort code smell

- __snapshots__/features/bookings/components/Ticket/TicketWithContent.test.tsx.native-snap
- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- src/features/auth/signup/VerifyEligiblity/VerifyEligibility.tsx
- src/features/bookings/components/ThreeShapesTicket.tsx
- src/features/bookings/components/Ticket/TicketSwiper.tsx
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/locales/fr/messages.po
- src/theme/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15603
I have:
|  <img width="743" alt="Capture d’écran 2022-06-10 à 16 16 01" src="https://user-images.githubusercontent.com/62059034/173090863-9a5e154f-92f0-414a-8f9e-a9554592c623.png"> <img width="746" alt="Capture d’écran 2022-06-10 à 16 15 28" src="https://user-images.githubusercontent.com/62059034/173090870-6413c55d-6a97-42ab-a4d2-542559030a7d.png"> |    <img width="435" alt="Capture d’écran 2022-06-10 à 16 43 06" src="https://user-images.githubusercontent.com/62059034/173090801-db282243-678c-4e6d-8e8d-3a80407fb26a.png"> <img width="428" alt="Capture d’écran …
> (PC-15603) fix(ThreeShapeTicket): fix ticket header and footer size

- src/features/home/api/tests/useHomeRecommendedHits.test.ts
- src/features/home/api/useHomeRecommendedHits.ts
- src/features/home/components/RecommendationModule.tsx
- src/features/home/components/tests/RecommendationModule.test.tsx
- src/libs/analytics/__mocks__/analytics.ts
- src/libs/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15503
I have:
Avant:
Après:
> (PC-15503) fix(home): fix recommendation playlists display

- src/features/forceUpdate/ForceUpdate.tsx
- src/features/forceUpdate/__tests__/ForceUpdate.test.tsx
- src/features/maintenance/MaintenanceErrorPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15610
I have:
> (PC-15610) fix(ForceUpdate): can switch down minimalBuildVersion

- __mocks__/react-query.ts
- src/features/auth/AuthContext.test.tsx
- src/features/auth/AuthContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15490
I have:
> (PC-15490) refactor(logout): move removeQueries after clear token

- __snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.native-snap
- __snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.web-snap
- src/ui/components/GenericOfficialPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14453
I have:
| iOS and  small iOS | big iOS | Desktop - Chrome | 
| --: | --------------: | ---------------: | 
|        ![Capture d’écran 2022-06-13 à 15 53 25](https://user-images.githubusercontent.com/44037911/173370965-bed5e357-3158-4848-98e2-b36c0fa015c8.png)      |    ![Capture d’écran 2022-06-13 à 16 02 29](https://user-images.githubusercontent.com/44037911/173371092-d1d91621-d548-4a9a-8447-0fd40964a99e.png)             |      <img width="1433" alt="Capture d’écran 2022-06-13 à 15 52 58" src="https://user-images.githubusercontent.com/44037911/173371141-ec17a179-2d99-45f9-b920-d97c8361a13a.png">            | 
[2]: …
> (PC-14453) fix(GenericOfficialPage): fix page layout for all sizes

- __snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/components/SectionWithSwitch.test.tsx.native-snap
- __snapshots__/features/profile/components/SectionWithSwitch.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/profile/components/SectionWithSwitch.tsx
- src/ui/components/FilterSwitch.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15091
I have:
> (PC-15091) feat(accessibility): add accessible label and improve keyboard interaction for switch

- src/features/auth/suspendedAccount/FraudulentAccount/FraudulentAccount.tsx
- src/features/auth/suspendedAccount/SuspendedAccount/SuspendedAccount.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileSuccessV2.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15694
I have:
> (PC-15694) fix(AccountSuspension): Fix redirection to home

- src/features/auth/signup/PhoneValidation/components/CountryPicker.tsx
- src/features/search/components/SearchResults.tsx
- src/libs/environment/env.ts
- src/libs/parsers/getDisplayPrice.ts
- src/libs/react-native-batch/index.web.ts
- src/libs/share/WebShareModal.web.tsx
- src/locales/fr/messages.po
- src/service-worker.ts
- src/ui/components/OfferCaption.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15303
- https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS4325&types=CODE_SMELL&id=pass-culture_pass-culture-app-native
- https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS4624&types=CODE_SMELL&id=pass-culture_pass-culture-app-native
- https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS3317&types=CODE_SMELL&id=pass-culture_pass-culture-app-native
I have:
> (PC-15303) fix(Sonar): fix some issues

- src/features/search/components/SearchResults.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15303
I have:
> (PC-15303) fix(SearchResults): fix helmet title

- ios/Podfile.lock
> (BSR) podfile.lock: update checksum

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15740
I have:
> (PC-15740) fix(server): automatic deploy in testing using orbs

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15740
I have:
>  (PC-15740) fix(server): automatic deploy in testing #2

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15740
I have:
>  (PC-15740) fix(server): automatic deploy in testing #3

- server/package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15740
I have:
>  (PC-15740) fix(server): automatic deploy in testing #4 (test deploy)

- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx.native-snap
- src/features/auth/signup/PhoneValidation/SetPhoneNumberDeprecated.tsx
- src/features/auth/signup/PhoneValidation/tests/SetPhoneNumberDeprecated.native.test.tsx
- src/features/auth/signup/useBeneficiaryValidationNavigation.test.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.ts
- src/features/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx
- src/features/identityCheck/useIdentityCheckSteps.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14456
I have:
| iOS small phone| iOS | Desktop - Chrome | Mobile - Chrome | Desktop - Safari |
|    <img width="293" alt="Capture d’écran 2022-06-16 à 16 28 52" src="https://user-images.githubusercontent.com/44037911/174093221-76beaeb1-e0a7-4f24-afd6-331604e3a077.png"> |     <img width="315" alt="Capture d’écran 2022-06-16 à 16 28 58" src="https://user-images.githubusercontent.com/44037911/174093271-38837f51-cbc4-4b48-a200-e80784955e5a.png">    |            <img width="1437" alt="Capture d’écran 2022-06-16 à 16 33 36" src="https://user-images.githubusercontent.com/44037911/174093792-b8db7b9b-2bb2-4f03-b818-58596c25ba15.png">    |   <img …
> (PC-14456) feat(phoneValidation): create new standalone phone number page

- src/features/home/components/BusinessModule.tsx
- src/features/offer/services/useCtaWordingAndAction.ts
- src/ui/components/keyboard/useKeyboardEvents.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15388
I have:
> (PC-15388) fix(sonar): Remove redundant jumps

- .circleci/config.yml
- package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15383
I have:
> (PC-15383) feat(circle): add JUnit coverage reporter to unit_test_web

- doc/deployment/deployment.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15800
Co-auteur [cedricls1](https://github.com/cedricls1)
I have:
Lien pour voir le changement https://github.com/pass-culture/pass-culture-app-native/blob/PC-15800/doc/deployment/deployment.md#add-new-commit-on-staging
> (PC-15800) docs(deployement): add new process to patch staging

- __snapshots__/features/bookings/components/NoBookingsView.test.tsx.native-snap
- __snapshots__/features/bookings/components/NoBookingsView.test.tsx.web-snap
- src/features/bookings/components/NoBookingsView.test.tsx
- src/features/bookings/components/NoBookingsView.tsx
- src/libs/network/__tests__/OfflineModeContainer.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15711
La target branch est `PC-15704`,  le merge sur `master` se fera en fin d'épique.
I have:
| Connected | Android Disconnected | Mobile - Chrome Disconnect | Desktop - Chrome | Desktop - Safari |
|![image](https://user-images.githubusercontent.com/77674046/174589431-ecc4d539-53f5-4538-84b0-21114cdbd69e.png)     |  ![image](https://user-images.githubusercontent.com/77674046/174591705-16e2a2f6-5597-4e78-883a-4ecd41b1c2e6.png)       |  ![image](https://user-images.githubusercontent.com/77674046/174591744-d37e8c3d-bd3c-4d8b-933e-7927167e185f.png)            |                  |                  |
[1]: …
> (PC-15711) feat(Offline): bookings without data template

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx.native-snap
- src/features/auth/signup/PhoneValidation/SetPhoneNumberDeprecated.tsx
- src/features/auth/signup/PhoneValidation/SetPhoneValidationCodeDeprecated.tsx
- src/features/auth/signup/PhoneValidation/tests/SetPhoneNumberDeprecated.native.test.tsx
- src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCodeDeprecated.native.test.tsx
- src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCodeDeprecated.web.test.tsx
- src/features/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NavigationIdentityCheck.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
- src/ui/components/inputs/InputCaption.ts
- src/ui/components/inputs/RequiredLabel.tsx
- src/ui/components/inputs/TextInput.tsx
- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14481
I have:
|![Simulator Screen Shot - iPhone 13 - 2022-06-20 at 18 24 04](https://user-images.githubusercontent.com/22886846/174644605-0b048f0b-8cc2-4428-9582-1aafb9584ce0.png)|<img width="262" alt="Capture d’écran 2022-06-20 à 18 24 29" src="https://user-images.githubusercontent.com/22886846/174644555-63217015-0c42-4330-9747-987bcd342bf0.png">|                 |<img width="1174" alt="Capture d’écran 2022-06-20 à 18 23 02" src="https://user-images.githubusercontent.com/22886846/174644347-d786adde-b7e7-43c2-8297-8bd4935b0466.png">|                  |
[1]: …
> (PC-14481) feat(identityCheck): add new set phone validation code page

- doc/customize/icons.md
- public/index.html
- src/ui/svg/ImagePlaceholderVenue.tsx
- src/ui/svg/VenueHeaderBackground.tsx
- src/ui/svg/icons/BicolorArrowRight.tsx
- src/ui/svg/icons/BicolorCircledCheck.tsx
- src/ui/svg/icons/BicolorEmailSent.tsx
- src/ui/svg/icons/BicolorIdCardWithMagnifyingGlass.tsx
- src/ui/svg/icons/BicolorPhonePending.tsx
- src/ui/svg/icons/socialNetwork/Telegram.tsx
- src/ui/svg/icons/socialNetwork/WhatsApp.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13009
I have:
> (PC-13009) fix(accessibility): Fix some w3c errors

- src/features/auth/AuthContext.tsx
- src/features/auth/settings.ts
- src/features/auth/suspendedAccount/SuspendedAccount/useAccountSuspensionDate.ts
- src/features/auth/suspendedAccount/SuspensionScreen/useAccountSuspensionStatus.ts
- src/features/bookings/api/__tests__/queries.test.ts
- src/features/bookings/api/queries.ts
- src/features/bookings/components/ArchiveBookingModal.native.test.tsx
- src/features/culturalSurvey/useCulturalSurvey.ts
- src/features/favorites/pages/useFavorites.ts
- src/features/home/api/useExcluOffer.ts
- src/features/home/api/useHomeRecommendedHits.ts
- src/features/home/api/useOfferModule.ts
- src/features/home/api/useVenueModule.ts
- src/features/offer/components/__tests__/OfferIconCaptions.native.test.tsx
- src/features/offer/services/useReasonsForReporting.ts
- src/features/profile/api.ts
- src/features/profile/pages/ChangeEmail/utils/useCheckHasCurrentEmailChange.ts
- src/features/profile/pages/PersonalData/__tests__/PersonalData.web.test.tsx
- src/features/profile/tests/api.test.ts
- src/features/venue/api/useVenueOffers.ts
- src/libs/address/__tests__/useFormatFullAddress.test.ts
- src/libs/place/useCities.ts
- src/libs/react-query/tests/usePersistQuery.test.tsx
- src/libs/react-query/usePersistQuery.ts
- src/libs/react-query/usePrefetchQueries.ts
- src/libs/subcategories/useSubcategories.ts
- src/ui/components/modals/AppModal.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15710
I have:
> (PC-15710) feat(OfflineMode): added usePersistQuery

- src/features/search/components/SearchResults.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15303
I have:
|     |         |                 |  <img width="1792" alt="Capture d’écran 2022-06-24 à 10 47 26" src="https://user-images.githubusercontent.com/62059034/175499443-0be3a2cd-1674-4d99-9a06-64b97fdd67ae.png"> |                  |
> (PC-15303) fix(SearchResults): extract new searchStateQuery translation

- __snapshots__/features/home/atoms/tests/SeeMore.native.test.tsx.native-snap
- __snapshots__/features/home/atoms/tests/SeeMore.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- src/features/home/atoms/SeeMore.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15917
I have:
> (PC-15917) feat(accessibility): Fix unresponsive icon in SeeMore

- src/features/search/components/CategoriesButtons/CategoriesButtons.native.test.tsx
- src/features/search/components/CategoriesButtons/CategoriesButtons.tsx
- src/features/search/components/CategoriesButtons/index.ts
- src/features/search/components/CategoriesButtons/useSortedSearchCategories.test.tsx
- src/features/search/components/CategoriesButtons/useSortedSearchCategories.tsx
- src/features/search/pages/SearchRework.tsx
- src/features/search/pages/__tests__/Search.native.test.tsx
- src/features/search/pages/__tests__/SearchRework.native.test.tsx
- src/features/search/pages/__tests__/useShowResultsForCategory.test.ts
- src/features/search/pages/useShowResultsForCategory.ts
à reviewer après https://github.com/pass-culture/pass-culture-app-native/pull/3156
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15130
I have:
> (PC-15130) feat(search): show results for a category when pressing on a category button

- src/features/bookings/components/CancelBookingModal.native.test.tsx
- src/features/bookings/components/CancelBookingModal.tsx
- src/features/bookings/pages/BookingDetails.native.test.tsx
- src/features/bookings/pages/BookingDetails.tsx
- src/locales/fr/messages.po
- src/ui/components/touchableLink/TouchableLink.tsx
- src/ui/components/touchableLink/__tests__/TouchableLink.native.test.tsx
- src/ui/components/touchableLink/__tests__/TouchableLink.web.test.tsx
- src/ui/components/touchableLink/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15714
I have:
> (PC-15714) fix(OfflineMode): added snackbar when trying to cancel booking or access offer

- src/libs/algolia/__tests__/fetchMultipleVenues.test.ts
- src/libs/algolia/enums/facetsEnums.ts
- src/libs/algolia/fetchAlgolia/fetchMultipleVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15233
I have:
> (PC-15233) refactor(algolia): rename eligible_for_strict_search to more explicit name

- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14459
Fixing the following anomaly on testing:
> (PC-14459) fix(phoneValidation): update translations

- .env.production
- .env.staging
- .env.testing
- __snapshots__/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.native.test.tsx.native-snap
- __snapshots__/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.web.test.tsx.web-snap
- src/features/auth/suspendedAccount/FraudulentAccount/FraudulentAccount.tsx
- src/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.native.test.tsx
- src/features/auth/suspendedAccount/FraudulentAccount/tests/FraudulentAccount.web.test.tsx
- src/libs/environment/__mocks__/envFixtures.ts
- src/libs/environment/types.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15968
I have:
> (PC-15968) fix(FraudulentAccount): Change wording and email contact

- __snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap
- src/features/home/components/HomeHeader.tsx
- src/features/home/pages/Home.tsx
- src/ui/svg/BouncyHeaderBackground.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15964
I have:
| https://user-images.githubusercontent.com/46637324/176398910-b876445c-d2da-4bf4-84a4-81d86de32d49.mp4   |         |                 |                  |                  |
> (PC-15964) fix(home): Make playlist scroll smoother and add bounce

- src/features/home/atoms/VenueTile.tsx
- src/features/home/atoms/tests/VenueTile.native.test.tsx
- src/features/home/atoms/tests/VenueTile.web.test.tsx
- src/features/home/components/VenuesModule.tsx
- src/libs/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15824
I have:
> (PC-15824) feat(tracking): add moduleName and Id to conlustVenue log

- __snapshots__/features/search/components/CategoryButton/CategoryButton.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.stories.tsx
- src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.tsx
- src/features/search/components/CategoryButton/CategoryButton.tsx
- src/ui/storybook/StoryViewport.stories.tsx
- src/ui/storybook/StoryViewport.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15856
I have:
> (PC-15856) feat(search): improve categories buttons' UI

- src/features/identityCheck/pages/phoneValidation/CodeNotReceivedModal.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/CodeNotReceivedModal.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14461
I have:
https://user-images.githubusercontent.com/22886846/176480693-d987a26e-2688-4603-9fea-b7a60a5c20d2.mov
https://user-images.githubusercontent.com/22886846/176482885-78425ece-9934-4010-8f94-b591cd41692d.mov
> (PC-14461) feat(phoneValidation): request new code on CodeNotReceivedModal

- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15940
I have:
> (PC-15940) fix(lingui): update translations

- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyIntro.native.test.tsx.native-snap
- __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyIntro.web.test.tsx.web-snap
- src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15541
I have:
> (PC-15541) feat(culturalSurvey): update wording

- src/features/navigation/TabBar/TabBar.tsx
- src/features/navigation/TabBar/__tests__/TabBar.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15983
I have:
> (PC-15983) fix(SeeMore): Use correct screen and params for native TabBar navigation

- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.stories.tsx
- src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.tsx
- src/features/search/pages/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15856
I have:
* web : oui
* iOS / Android : impossible de les lancer en local
> (PC-15856) feat(search): scroll issue

- __snapshots__/features/search/components/CategoryButton/CategoryButton.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/search/components/CategoryButton/CategoryButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15856
I have:
> (PC-15856) fix(search): text aligment

- src/features/navigation/__tests__/sanitizeNavigationState.test.ts
- src/features/navigation/sanitizeNavigationState.ts
- src/features/navigation/services.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16045
I have:
> (PC-16045) fix(Search): do not persist query params of search

- .eslintrc.js
- .github/PULL_REQUEST_TEMPLATE.md
- eslint-custom-rules/todo-format.js
- eslint-local-rules.js
- server/src/index.ts
- server/src/middlewares/webAppProxyMiddleware.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.test.ts
- src/features/auth/signup/useBeneficiaryValidationNavigation.ts
- src/features/auth/suspendedAccount/SuspendedAccount/tests/useAccountUnsuspend.test.ts
- src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx
- src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx
- src/features/identityCheck/pages/Stepper.tsx
- src/features/identityCheck/pages/phoneValidation/CodeNotReceivedModal.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/CodeNotReceivedModal.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx
- src/features/identityCheck/useIdentityCheckSteps.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14155
I have:
> (PC-14155) feat(eslint): Enforce TODO/FIXME format in comments

- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- src/ui/components/SocialNetworkCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16061
I have:
|     |     <img width="304" alt="Capture d’écran 2022-07-06 à 09 44 38" src="https://user-images.githubusercontent.com/62059034/177501257-d9fa073f-1751-441f-8b10-2ac2c20a4335.png"> <img width="303" alt="Capture d’écran 2022-07-06 à 09 43 59" src="https://user-images.githubusercontent.com/62059034/177501266-a508efc4-6c85-439f-9752-53b154223352.png"> <img width="303" alt="Capture d’écran 2022-07-06 à 09 43 39" src="https://user-images.githubusercontent.com/62059034/177501270-40ae4181-507b-4102-a3a8-dc17cd7a7688.png"> |                 |                  | …
> (PC-16061) feat(profile): fix social network card width

- src/features/landscapePosition/tests/useIsLandscapePosition.web.test.tsx
- src/libs/itinerary/useItinerary.web.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15976
I have:
> (PC-15976) test(hooks): Add tests for hooks

- __mocks__/@react-navigation/native.ts
- src/features/search/atoms/NoSearchResult.tsx
- src/features/search/atoms/__tests__/NoSearchResult.native.test.tsx
- src/features/search/atoms/__tests__/NoSearchResult.web.test.tsx
- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchDetails.tsx
- src/features/search/components/SearchHeader.tsx
- src/features/search/components/__tests__/SearchBox.native.test.tsx
- src/features/search/components/__tests__/SearchDetails.native.test.tsx
- src/features/search/pages/__tests__/Search.native.test.tsx
- src/features/search/pages/__tests__/useShowResultsWithStagedSearch.test.ts
- src/features/search/pages/usePushWithStagedSearch.ts
- src/features/search/pages/useShowResultsForCategory.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16053
I have:
> (PC-16053) fix(Search): SearchBox query and NoResults handled with URL

- src/features/navigation/__tests__/sanitizeNavigationState.test.ts
- src/features/navigation/sanitizeNavigationState.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16116
I have:
> (PC-16116) fix(Search): limit state size used in localStorage for navigation

- __snapshots__/features/bookings/components/NoBookingsView.test.tsx.web-snap
- package.json
- src/libs/network/useNetInfo.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15713
I have:
> (PC-15713) fix(OfflineMode): internet always reachable on the web

- src/features/bookings/components/OnGoingBookingsList.native.test.tsx
- src/features/bookings/components/OnGoingBookingsList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16150
I have:
> (PC-16150) fix(Search): disable pull to refetch if offline

- src/libs/hooks/__tests__/useFunctionOnce.test.ts
- src/libs/hooks/__tests__/useIsFalseWithDelay.test.ts
- src/libs/hooks/__tests__/useIsMounted.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16149
I have:
> (PC-16149) feat(tests): Add tests for various hooks

- src/features/auth/signup/useNextSubscriptionStep.test.ts
- src/features/auth/signup/useNextSubscriptionStep.ts
- src/features/bookings/components/EndedBookingItem.tsx
- src/features/favorites/pages/__tests__/useFavorites.test.tsx
- src/features/favorites/pages/useFavorites.ts
- src/features/offer/pages/__tests__/OfferBody.deprecated.native.test.tsx
- src/features/offer/services/useReportedOffers.ts
- src/libs/place/usePlaces.ts
- src/libs/place/useVenues.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16163
I have:
> (PC-16163) fix(Offline): disable click on endedbookingsitems + 3x useQuery must check connexion

- __snapshots__/features/identityCheck/components/layout/PageWithHeader.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/layout/PageWithHeader.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckDMS.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnectForm.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnectForm.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckValidation.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckValidation.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetStatus.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetStatus.web.test.tsx.web-snap
- src/features/identityCheck/atoms/layout/CustomKeyboardAvoidingView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15883
I have:
|    https://user-images.githubusercontent.com/46637324/178676693-94a760d2-a222-4b9b-a1d1-da14f43b2f42.mp4 |  ![AndroidVid](https://user-images.githubusercontent.com/46637324/178684722-06abd6cc-3f27-4ca2-b892-7586ecfd1932.gif)  | https://user-images.githubusercontent.com/46637324/178676743-efaafba9-edcf-497c-a69f-da4208552ff7.mp4   |    <img width="1118" alt="Capture d’écran 2022-07-13 à 09 33 30" src="https://user-images.githubusercontent.com/46637324/178677242-dca531fd-4225-429c-a074-b7422d950cba.png">      |        |
[1]: …
> (PC-15883) feat(identityCheck): Fix visible background on ios when keyboard opens

- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16022
I have:
https://user-images.githubusercontent.com/44037911/178756058-55224521-4754-4738-b0a2-4abfdd12b00e.mp4
> (PC-16022) fix(phoneVal): prevent modal from appearing on go back

- scripts/upload_sourcemaps_to_sentry.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16207
I have:
> (PC-16207) fix(Sentry): React Native v0.69 or higher support for sourcecemaps

- src/libs/network/OfflineModeContainer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16119
I have:
> (PC-16119) fix(Offline): reduce delay to 15sec when internet is not reachable

- src/features/bookings/components/OnGoingBookingsList.native.test.tsx
- src/features/bookings/components/OnGoingBookingsList.tsx
- src/features/bookings/pages/Bookings.native.test.tsx
- src/features/bookings/pages/Bookings.web.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16209
I have:
- [x Made sure the title of my PR follows the [convention](1) `($jira) $type($scope): $summary`.
> (PC-16209) fix(Search): Pull to refresh offline with snackbar error

- __snapshots__/features/bookings/components/NoBookingsView.test.tsx.native-snap
- __snapshots__/features/bookings/components/NoBookingsView.test.tsx.web-snap
- src/features/bookings/components/NoBookingsView.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15711
I have:
|![image](https://user-images.githubusercontent.com/77674046/178817086-f4698869-a9d5-4183-bd4d-6edd3c6294be.png)     | ![image](https://user-images.githubusercontent.com/77674046/178817099-3f4e4742-3d71-47a5-a235-3584f20dbe0f.png)        |                 |                  |                  |
> (PC-15711) fix(Search): Réservations sans data layout

- scripts/upload_sourcemaps_to_sentry.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16168
Example with SDK7: https://sentry.internal-passculture.app/organizations/sentry/issues/388732/?environment=staging&project=6&query=is%3Aunresolved+80985&statsPeriod=1h 
I have:
> (PC-16168) fix(Sentry): proper sourcemaps Sentry iOS hard

- src/web/useServiceWorker.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16221
I have:
> (PC-16221) fix(Web): clean unnecessary logging in service-worker.ts

- sonar-project.properties
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16225
I have:
> (PC-16225) feat(sonar): update sonar.exclusions

- __snapshots__/features/bookings/components/NoBookingsView.test.tsx.native-snap
- __snapshots__/features/bookings/components/NoBookingsView.test.tsx.web-snap
- src/features/bookings/components/NoBookingsView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15711
I have:
| ![image](https://user-images.githubusercontent.com/77674046/179534924-28c41869-8228-494c-adfe-ae33b985af27.png)| ![image](https://user-images.githubusercontent.com/77674046/179534937-71e86c9a-9ddf-4fe4-b41b-bf0b53b6930f.png)|![image](https://user-images.githubusercontent.com/77674046/179534949-e3595a67-0e3b-4d00-9c03-5c80adcfa9aa.png)|![image](https://user-images.githubusercontent.com/77674046/179534962-d5f7d0df-27a1-44ab-8a42-3c2878cf40c2.png)||
[2]: …
> (PC-15711) fix(NoBookingsView): fix responsive bottom link

- __snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchMainInput/SearchMainInput.stories.tsx
- src/features/search/components/SearchMainInput/SearchMainInput.tsx
- src/features/search/components/SearchMainInput/index.ts
- src/locales/fr/messages.po
- src/ui/components/inputs/SearchInput.native.test.tsx
- src/ui/components/inputs/SearchInput.stories.tsx
- src/ui/components/inputs/SearchInput.tsx
- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15523
I have:
> (PC-15523) refactor(search): split generic search input and specific location button into a new search main input

- server/src/middlewares/webAppProxyMiddleware.ts
- src/features/deeplinks/utils.ts
- src/web/serviceWorkerRegistration.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16122
I have:
> (PC-16122) fix(TODO): remove some old todo

- __snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchHeader.tsx
- src/features/search/components/SearchMainInput/SearchMainInput.tsx
- src/ui/components/inputs/SearchInput.tsx
- src/ui/components/inputs/types.ts
à review après que https://github.com/pass-culture/pass-culture-app-native/pull/3246 soit mergée
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15523
I have:
> (PC-15523) feat(search): ensure search box grow respecting the available space

- __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- src/features/search/components/SearchHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15523
I have:
> (PC-15523) fix(search): main search input was only clickable on an half of this size

- __snapshots__/features/auth/signup/PhoneValidation/components/CountryPicker.native.test.tsx.native-snap
- __snapshots__/features/auth/signup/SetBirthday/BirthdayInformationModal/BirthdayInformationModal.native.test.tsx.native-snap
- __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
- __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/DMSModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/CodeNotReceivedModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/PhoneValidationTipsModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
- __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/__tests__/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/offer/pages/__tests__/OfferBody.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueHeader.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
- src/libs/share/SocialButton.tsx
- src/libs/share/WebShareModal.web.tsx
- src/libs/share/__tests__/WebShareModal.web.test.tsx
- src/ui/components/modals/AppInformationModal.tsx
- src/ui/components/modals/AppModal.tsx
- src/ui/components/modals/ModalHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16248
I have:
> (PC-16248) fix(accessibility): Make share modal accessible

- src/features/search/components/SearchBox.tsx
- src/features/search/pages/__tests__/useShowResultsForCategory.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16240
I have:
> (PC-16240) fix(Search): increase hitSlops on back button

- __snapshots__/features/search/pages/__tests__/LocationPicker.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/LocationPicker.test.tsx.web-snap
- src/features/search/pages/LocationPicker.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16247
I have:
> (PC-16247) feat(accessibility): Change aria-label and placeholder of LocationPicker

- src/features/navigation/__tests__/sanitizeNavigationState.test.ts
- src/features/navigation/sanitizeNavigationState.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16268
Je ne me souviens plus de ce qu'on cherchait a éviter précisément en supprimant les params, et les conséquences que cela peut avoir @bruno-ebstein-pass-culture .
I have:
> (PC-16268) fix(Search): do not clearSearchParams

- __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
- __snapshots__/features/auth/login/Login.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
- src/features/auth/components/PasswordSecurityRules.tsx
- src/ui/components/inputs/rules/InputRule.tsx
- src/ui/components/inputs/rules/PasswordRule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13597
I have:
> (PC-13597) fix(accessibility): Fix PasswordRule voiceover restitution

- .env.integration
- .env.production
- .env.staging
- .env.testing
- src/features/bookOffer/components/AlreadyBooked.tsx
- src/features/bookOffer/pages/BookingOfferModal.tsx
- src/features/bookOffer/pages/__tests__/BookingOfferModal.native.test.tsx
- src/features/bookOffer/services/__tests__/useModalContent.test.tsx
- src/features/bookOffer/services/useModalContent.tsx
- src/features/bookings/api/__tests__/queries.test.ts
- src/features/bookings/api/queries.ts
- src/features/offer/pages/Offer.tsx
- src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts
- src/features/offer/services/useCtaWordingAndAction.ts
- src/libs/environment/__mocks__/envFixtures.ts
- src/libs/environment/types.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15512
I have:
| iOS | Android | External Link - Chrome Desktop | Desktop - Chrome | Desktop - Safari |
|     | ![image](https://user-images.githubusercontent.com/77674046/180204591-dd1271eb-3065-4dd8-84be-79c06c47ea65.png) |      ![image](https://user-images.githubusercontent.com/77674046/180205066-754207bd-7261-4c0d-a9db-86f32a8fad14.png)           |                  |                  |
> (PC-15512) fix(OfferDetails): custom CTA and modal when already booked offer

- src/features/_marketingAndCommunication/atoms/__tests__/ControlledFilterSwitch.native.test.tsx
- src/features/_marketingAndCommunication/atoms/__tests__/ControlledFilterSwitch.web.test.tsx
- src/ui/components/FilterSwitch.native.test.tsx
- src/ui/components/FilterSwitch.stories.tsx
- src/ui/components/FilterSwitch.tsx
- src/ui/components/FilterSwitch.web.test.tsx
- src/ui/components/buttons/buttonInsideText/ButtonInsideText.tsx
- src/ui/hooks/__mocks__/useEnterKeyAction.ts
- src/ui/hooks/__mocks__/useEscapeKeyAction.ts
- src/ui/hooks/useEnterKeyAction.web.ts
- src/ui/hooks/useSpaceBarAction.ts
- src/ui/hooks/useSpaceBarAction.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16230
I have:
> (PC-16230) feat(accessibility): add useSpaceBarAction

- src/features/auth/AuthContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16152
I have:
> (PC-16152) fix(Profile): Clean NextSubscriptionStep on logout

- src/features/auth/signup/PhoneValidation/components/CountryPicker.tsx
- src/features/search/components/LocationChoice.tsx
- src/features/search/pages/SuggestedPlaces.tsx
- src/ui/components/radioButtons/RadioButton.tsx
- src/ui/components/radioButtons/RadioButtonWithBorder.tsx
- src/ui/hooks/useArrowNavigationForRadioButton.ts
- src/ui/hooks/useArrowNavigationForRadioButton.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16272
I have:
|     |         |                 |      https://user-images.githubusercontent.com/46637324/180148991-0225d665-ba4d-4a21-b1ee-fa51a76e29c1.mov        |                  |
> (PC-16272) feat(accessibility): Allow arrow navigation for radio buttons

- src/features/profile/pages/ChangePassword/ChangePassword.tsx
- src/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx
- src/features/profile/pages/ConsentSettings.native.test.tsx
- src/features/profile/pages/ConsentSettings.tsx
- src/features/profile/pages/NotificationSettings.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7802
I have:
> (PC-7802) feat(Profile): Normalize on save success behavior

- src/features/auth/signup/PhoneValidation/components/CountryPicker.tsx
- src/features/search/components/LocationChoice.tsx
- src/features/search/pages/SuggestedPlaces.tsx
- src/features/search/pages/__tests__/SuggestedPlaces.web.test.tsx
- src/ui/components/radioButtons/RadioButton.stories.tsx
- src/ui/components/radioButtons/RadioButton.tsx
- src/ui/components/radioButtons/RadioButtonWithBorder.stories.tsx
- src/ui/components/radioButtons/RadioButtonWithBorder.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16237
I have:
> (PC-16237) feat(accessibility): Allow radio button selection with space key

- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/VenuesModule.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/home/components/OffersModule.tsx
- src/features/home/components/RecommendationModule.tsx
- src/features/home/components/VenuesModule.tsx
- src/features/home/contentful/contentful.ts
- src/ui/components/PassPlaylist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15997
I have:
| iPhone 13 | iPhone 8 | iPhone 5s | Desktop - Chrome | Desktop - Safari |
|![Simulator Screen Shot - iPhone 13 - 2022-07-19 at 10 52 09](https://user-images.githubusercontent.com/22886846/179725414-0e651d47-9370-44d6-b951-f6b8da4ad998.png)|![Simulator Screen Shot - iPhone 8 - 2022-07-19 at 10 49 59](https://user-images.githubusercontent.com/22886846/179725500-07876d4d-1ccd-4c58-9d21-5b4454c7a17a.png)|![Simulator Screen Shot - iPhone 5s - 2022-07-19 at 10 50 48](https://user-images.githubusercontent.com/22886846/179725605-89cf34e0-4d92-438e-a262-86025ec86d14.png)|<img width="805" alt="Capture d’écran 2022-07-19 à 10 53 54" …
> (PC-15997) feat(home): add playlist subtitle

- __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
- __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
- src/features/auth/signup/PhoneValidation/SetPhoneValidationCodeDeprecated.tsx
- src/features/bookings/components/OnGoingBookingsList.tsx
- src/features/firstTutorial/pages/FirstTutorial/components/FirstCard.tsx
- src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.tsx
- src/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx
- src/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.tsx
- src/features/search/components/CalendarPicker.web.tsx
- src/locales/fr/messages.po
- src/ui/components/LoadingPage.tsx
- src/ui/components/achievements/components/GenericAchievementCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16273
I have:
|     |         |                 |    
> (PC-16273) feat(firstTutorial): udpate wording and design + (PC-16345)

- src/features/bookOffer/components/AlreadyBooked.tsx
- src/features/bookOffer/components/__tests__/AlreadyBooked.test.tsx
- src/features/bookOffer/pages/BookingOfferModal.tsx
- src/features/bookOffer/pages/__tests__/BookingOfferModal.native.test.tsx
- src/features/bookOffer/services/__tests__/useModalContent.test.tsx
- src/features/bookOffer/services/useModalContent.tsx
- src/features/offer/pages/Offer.tsx
- src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts
- src/features/offer/services/useCtaWordingAndAction.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15512
I have:
> (PC-15512) fix(Bookings): check if booking was used

- src/ui/components/snackBar/SnackBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16343
I have:
Pas de changement au niveau du style
|  ![Simulator Screen Shot - iPhone 13 - 2022-07-22 at 11 35 38](https://user-images.githubusercontent.com/46637324/180415468-1d1e3303-2380-4e0b-ae74-6bb8ae1f3a2c.png)   |         |                 |<img width="1077" alt="Capture d’écran 2022-07-22 à 11 58 16" src="https://user-images.githubusercontent.com/46637324/180415481-b5ddcdcb-c8d8-4cd1-9639-f6f0f8ca6c6f.png">     |                  |
[2]: …
> (PC-16343) fix(accessibility): Hide SnackBar close button from accessibility when not visible

- __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
- __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
- src/ui/components/achievements/components/GenericAchievementCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16273
I have:
> (PC-16273) fix(GenericAchievementCard): fix header for accessibility

- __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
- __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
- __snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
- src/ui/components/achievements/components/GenericAchievementCard.native.test.tsx
- src/ui/components/achievements/components/GenericAchievementCard.tsx
- src/ui/components/achievements/components/GenericAchievementCard.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16345
I have:
|  ![Simulator Screen Shot - iPhone 13 - 2022-07-25 at 11 54 24](https://user-images.githubusercontent.com/46637324/180750339-4d64eae8-144e-43fe-8341-e1f88fac0104.png)   |         |                 |<img width="1079" alt="Capture d’écran 2022-07-25 à 11 54 06" src="https://user-images.githubusercontent.com/46637324/180750310-fd720975-b226-4ecf-ac99-55620ac76a7a.png">      |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bu …
> (PC-16345) fix(firstTutorial): Use same style for main title and subtitle

- .github/workflows/chromatic.yml
https://www.chromatic.com/docs/turbosnap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13951
I have:
> (PC-13951) feat(chromatic): triggers snapshots only on changed files

- src/ui/components/ModuleBanner/ModuleBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16372
I have:
|     |         |                 |   <img width="1078" alt="Capture d’écran 2022-07-26 à 11 09 43" src="https://user-images.githubusercontent.com/46637324/180969572-f46b51ba-dbaf-4e6e-be13-8252e3932b1b.png">       |                  |
> (PC-16372) fix(accessibility): Use correct hover underline color for profile banner

- fastlane/Fastfile
- scripts/deploy.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16304
- Android CodePush : https://sentry.internal-passculture.app/organizations/sentry/issues/388732/?environment=staging&project=6&query=is%3Aunresolved+D0A9B&statsPeriod=1h
- iOS CodePush : https://sentry.internal-passculture.app/organizations/sentry/issues/388732/?environment=staging&project=6&query=is%3Aunresolved+30EC7&statsPeriod=1h
I have:
[2]: …
> (PC-16304) fix(Sentry): code push with sourcemaps

- src/ui/svg/icons/socialNetwork/Instagram.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16388
I have:
|    https://user-images.githubusercontent.com/46637324/181207283-55ded7fa-4225-4159-a25d-905d6c021e28.mp4 |         |                 |      https://user-images.githubusercontent.com/46637324/181207244-ce5949f8-de93-4cd0-98fb-7fcceb81f9b8.mov |                  |
> (PC-16388) fix(Svg): Fix instagram logo display on web

- .circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16424
I have:
> (PC-16424) ci(build_web): fix memory issue

- src/features/search/pages/Search.tsx
Co-authored-by: Hugo Voisin <hugov@bam.tech>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16363
I have:
> (PC-16363) feat(search): no suggestions query empty

- src/features/search/components/SearchHeader.tsx
- src/features/search/pages/SearchWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15523
I have:
> (PC-15523) perf(search): avoid rerender when not needed

- __snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/auth/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/__test__/SetSchoolType.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/tests/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap
- __snapshots__/features/offer/pages/__tests__/OfferDescription.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/share/__tests__/WebShareModal.web.test.tsx.web-snap
- src/features/search/components/SearchBoxAutocomplete.tsx
- src/features/search/components/__tests__/SearchBox.native.test.tsx
- src/features/search/components/__tests__/SearchBoxAutocomplete.native.test.tsx
- src/ui/components/inputs/SearchInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16451
I have:
> (PC-16451) feat(search): no landing redirection on clear button

- src/features/profile/pages/ChangePassword/ChangePassword.tsx
- src/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16182
I have:
> (PC-16182) fix(changePassword): update wording

- __snapshots__/features/profile/components/CreditCeilingsModal.native.test.tsx.native-snap
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx
- src/features/cheatcodes/pages/NavigationProfile/index.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/profile/components/CreditCeilingsModal.native.test.tsx
- src/features/profile/components/CreditCeilingsModal.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16403
I have:
|   ![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 18 02 24](https://user-images.githubusercontent.com/46637324/181584829-97b1c603-656a-4938-b11e-788b233f4bc3.png) ![Simulator Screen Shot - iPhone 13 - 2022-07-28 at 18 02 28](https://user-images.githubusercontent.com/46637324/181584836-6136a4c0-e5a4-4dbd-aaca-50866ab1770d.png)  |         |                 |    <img width="1009" alt="Capture d’écran 2022-07-28 à 18 02 44" src="https://user-images.githubusercontent.com/46637324/181584852-02228523-1698-4ddb-bb1a-01ef9fe1665f.png">   <img width="1008" …
> (PC-16403) feat(Profile): Add new modal for credit ceiling explanation (PC-16406)

- __snapshots__/features/profile/components/ExpiredCreditModal.native.test.tsx.native-snap
- src/features/auth/signup/SetBirthday/BirthdayInformationModal/BirthdayInformationModal.tsx
- src/features/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx
- src/features/profile/components/CreditCeilingsModal.tsx
- src/features/profile/components/ExpiredCreditModal.native.test.tsx
- src/features/profile/components/ExpiredCreditModal.tsx
- src/features/search/components/SearchResults.tsx
- src/locales/fr/messages.po
- src/ui/components/achievements/components/GenericAchievementCard.tsx
- src/ui/theme/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16325
I have:
| ![Simulator Screen Shot - iPhone 13 - 2022-07-29 at 09 16 19](https://user-images.githubusercontent.com/46637324/181704356-7b05f78c-ad51-4f44-9901-9ff0142139b3.png)    |         |                 |       <img width="1007" alt="Capture d’écran 2022-07-29 à 09 11 23" src="https://user-images.githubusercontent.com/46637324/181704305-dfeccb0e-dd12-4f65-9744-37db546e3c77.png">     |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur- …
> (PC-16325) feat(Profile): Add new modal for expired credit

- __snapshots__/features/profile/components/ProfileHeader.native.test.tsx.native-snap
- src/features/cheatcodes/pages/AppComponents/iconsExports.ts
- src/features/profile/components/LoggedOutHeader.tsx
- src/ui/svg/icons/Connect.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16321
I have:
|    ![Simulator Screen Shot - iPhone 13 - 2022-07-29 at 09 36 39](https://user-images.githubusercontent.com/46637324/181708972-2c7f5f7f-a4b7-4221-b8ae-b624b02002f3.png) |         |                 | <img width="1010" alt="Capture d’écran 2022-07-29 à 09 36 54" src="https://user-images.githubusercontent.com/46637324/181708955-f11dec4b-81df-4ae5-afe3-8262f047d902.png">        |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les …
> (PC-16321) feat(Profile): Add icon to login CTA in logged out header (PC-16322)

- __snapshots__/features/profile/components/ProfileHeader.native.test.tsx.native-snap
- src/features/profile/components/LoggedOutHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16320
I have:
|  ![Simulator Screen Shot - iPhone 13 - 2022-07-29 at 17 01 13](https://user-images.githubusercontent.com/46637324/181788589-aa3e751e-96d9-41ca-b0b6-47cc40f4a90a.png) |![Screenshot_1659106984](https://user-images.githubusercontent.com/46637324/181788609-d42112f6-bee7-4309-9070-ae637c9d1722.png)         |                 |   <img width="1011" alt="Capture d’écran 2022-07-29 à 10 45 58" src="https://user-images.githubusercontent.com/46637324/181721853-e7c97c98-186c-4087-aa50-d4608c4edefa.png">     |                  |
[1]: …
> (PC-16320) feat(Profile): Remove logged out header gradient background

- .env.integration
- .env.production
- .env.staging
- .env.testing
- __snapshots__/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx.web-snap
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/libs/environment/__mocks__/envFixtures.ts
- src/libs/environment/types.ts
- src/libs/share/WebShareModal.web.tsx
- src/libs/share/__tests__/WebShareModal.native.test.tsx
- src/libs/share/__tests__/WebShareModal.web.test.tsx
- src/libs/share/shareApp/ShareAppModal.tsx
- src/libs/share/shareApp/__tests__/ShareAppModal.native.test.tsx
- src/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx
- src/libs/share/shareApp/shareApp.ts
- src/libs/share/shareApp/shareAppContent.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16271
I have:
| <img width="330" alt="Capture d’écran 2022-07-28 à 14 54 54" src="https://user-images.githubusercontent.com/62059034/181510158-7fe6b776-52bd-401b-8510-457441dba002.png">   |         |                 |   <img width="1792" alt="Capture d’écran 2022-07-28 à 14 47 24" src="https://user-images.githubusercontent.com/62059034/181509977-1cbd1371-aabe-43d3-90cf-bb236e950a66.png">  <img width="1201" alt="Capture d’écran 2022-07-28 à 14 55 56" src="https://user-images.githubusercontent.com/62059034/181510354-08912b67-44d2-4ec2-a911-6770cee1f31f.png"> |     |
[1]: …
> (PC-16271) feat(ShareApp): add share app modal to cheatcode

- .circleci/config.yml
It will be decreased later
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16424
I have:
> (PC-16424) fix(Web): increase resource_class from medium+ to large

- __snapshots__/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx.web-snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16271
I have:
> (PC-16271) fix(test): fix ShareAppModal snapshot

- src/features/profile/components/BeneficiaryHeaderNew.stories.tsx
- src/features/profile/components/BeneficiaryHeaderNew.tsx
- src/libs/i18n.native.test.ts
- src/locales/fr/messages.po
- src/ui/components/SectionRow.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16477
I have:
|  <img width="325" alt="Capture d’écran 2022-08-01 à 13 22 20" src="https://user-images.githubusercontent.com/62059034/182147326-cd6349ae-5999-4837-8b6a-49ed1c27cb24.png"> |         |            |   <img width="948" alt="Capture d’écran 2022-08-01 à 13 16 09" src="https://user-images.githubusercontent.com/62059034/182147355-0fda6fa8-4961-4309-b593-602a965d3cac.png"> |            |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df …
> (PC-16477) feat(profile): add BeneficiaryHeaderNew

- __snapshots__/features/profile/components/ExhaustedCreditModal.native.test.tsx.native-snap
- src/features/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx
- src/features/profile/components/ExhaustedCreditModal.native.test.tsx
- src/features/profile/components/ExhaustedCreditModal.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16464
I have:
|    ![Simulator Screen Shot - iPhone 13 - 2022-08-01 at 09 47 08](https://user-images.githubusercontent.com/46637324/182101452-5aa0d540-a712-44b7-8fe1-90f5808d8930.png) |         |                 |      <img width="1008" alt="Capture d’écran 2022-08-01 à 09 47 20 1" src="https://user-images.githubusercontent.com/46637324/182101488-82dc617c-752e-4bbd-86e9-85888a9b9da4.png">           |                  |
[2]: …
> (PC-16464) feat(Profile): Add new modal for exhausted credit

- src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.stories.tsx
- src/features/search/components/CategoryButton/CategoryButton.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15160
I have:
> (PC-15160) refactor(search): move stories from UI to Search Storybook's group

- __snapshots__/features/profile/components/CreditInfo.native.test.tsx.native-snap
- __snapshots__/features/profile/components/CreditProgressBar.native.test.tsx.native-snap
- src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
- src/features/profile/components/BeneficiaryHeaderNew.tsx
- src/features/profile/components/CreditInfo.native.test.tsx
- src/features/profile/components/CreditInfo.tsx
- src/features/profile/components/CreditProgressBar.native.test.tsx
- src/features/profile/components/CreditProgressBar.stories.tsx
- src/features/profile/components/CreditProgressBar.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16465
I have:
|   ![Simulator Screen Shot - iPhone 13 - 2022-08-01 at 16 25 10](https://user-images.githubusercontent.com/46637324/182172992-e266fc50-4ade-4d16-bf04-d741e7bee01b.png)  |     ![Screenshot_1659364180](https://user-images.githubusercontent.com/46637324/182173137-84196ad3-ef9e-45b6-bdae-8bfeb508b132.png)    |       <img width="305" alt="Capture d’écran 2022-08-01 à 16 43 06" src="https://user-images.githubusercontent.com/46637324/182175624-ed99b4ca-fc39-4721-afe1-0c9d54ffe3d4.png">          |        <img width="1220" alt="Capture d’écran 2022-08-01 à 16 18 52" …
> (PC-16465) feat(Profile): Make new credit progress bar

- src/features/profile/components/CreditExplanation/CreditExplanation.native.test.tsx
- src/features/profile/components/CreditExplanation/CreditExplanation.tsx
- src/features/profile/components/CreditExplanation/getCreditModal.test.ts
- src/features/profile/components/CreditExplanation/getCreditModal.ts
- src/features/profile/components/headers/BeneficiaryHeader/BeneficiaryHeaderNew.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16544
I have:
|    ![Simulator Screen Shot - iPhone 13 - 2022-08-02 at 12 01 31](https://user-images.githubusercontent.com/46637324/182348874-a03865df-0b73-42c9-9dbd-543e25d3f8a0.png)![Simulator Screen Shot - iPhone 13 - 2022-08-02 at 12 02 38](https://user-images.githubusercontent.com/46637324/182348878-150be699-caa3-465e-a127-7ddc69a13975.png) |         |                 |             <img width="923" alt="Capture d’écran 2022-08-02 à 12 01 13" src="https://user-images.githubusercontent.com/46637324/182348864-f89fa668-d8fa-4f08-83da-5614dac32c8a.png"><img width="921" …
> (PC-16544) feat(Profile): Display correct credit text for expired deposit

- src/features/profile/components/headers/BeneficiaryCeilings/BeneficiaryCeilingsNew.tsx
- src/features/profile/components/headers/BeneficiaryHeader/BeneficiaryHeaderNew.native.test.tsx
- src/features/profile/components/headers/BeneficiaryHeader/BeneficiaryHeaderNew.tsx
- src/features/profile/components/headers/ProfileHeader/ProfileHeader.native.test.tsx
- src/features/profile/components/headers/ProfileHeader/ProfileHeader.web.test.tsx
- src/features/profile/tests/api.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16465
I have:
|  <img width="321" alt="Capture d’écran 2022-08-02 à 12 55 08" src="https://user-images.githubusercontent.com/62059034/182362319-9fa5e8e8-d7b0-4f82-bc8e-bddbe881f3e1.png">   |         |                 |                  |                  |
> (PC-16465) fix(profile): fix breaking line for BeneficiaryCeilings

- .storybook/preview.js
- src/features/bookings/components/ThreeShapesTicket.stories.tsx
- src/features/cheatcodes/pages/AppComponents/Icons.stories.tsx
- src/features/cheatcodes/pages/AppComponents/Illustrations.stories.tsx
- src/features/culturalSurvey/components/CulturalSurveyCheckbox.stories.tsx
- src/features/profile/components/BeneficiaryCeilings.stories.tsx
- src/features/profile/components/CreditInfo/CreditProgressBar.stories.tsx
- src/features/search/atoms/SelectionLabel.stories.tsx
- src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.stories.tsx
- src/features/search/components/CategoryButton/CategoryButton.stories.tsx
- src/features/search/components/SearchMainInput/SearchMainInput.stories.tsx
- src/ui/components/Emoji.stories.tsx
- src/ui/theme/colors.stories.tsx
- src/ui/theme/typography.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15160
I have:
|     |         |                 |   <img width="266" alt="Capture d’écran 2022-08-02 à 11 19 43" src="https://user-images.githubusercontent.com/62059034/182340640-b8f587c5-3fd7-46d6-bae7-fb4770d9cbf1.png">    |                  |
> (PC-15160) refactor(storybook): reorganise stories

- __snapshots__/features/profile/components/CreditInfo/CreditInfo.native.test.tsx.native-snap
- __snapshots__/features/profile/components/headers/BeneficiaryHeader/BeneficiaryHeaderNew.native.test.tsx.native-snap
- src/features/profile/components/CreditExplanation/CreditExplanation.native.test.tsx
- src/features/profile/components/CreditExplanation/getCreditModal.test.ts
- src/features/profile/components/CreditInfo/CreditInfo.tsx
- src/features/profile/components/headers/BeneficiaryHeader/BeneficiaryHeaderNew.native.test.tsx
- src/features/profile/components/headers/BeneficiaryHeader/BeneficiaryHeaderNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16544
I have:
|  ![Simulator Screen Shot - iPhone 13 - 2022-08-02 at 15 26 26](https://user-images.githubusercontent.com/46637324/182386037-408b639f-06d5-429f-aa7a-5fe407db7141.png)   |         |    <img width="923" alt="Capture d’écran 2022-08-02 à 15 26 17" src="https://user-images.githubusercontent.com/46637324/182386014-c984ae78-f384-4244-ae84-0f747c5dd69b.png">              |                  |                 |
[2]: …
> (PC-16544) feat(Profile): Add tests for new BeneficiaryHeader

- src/features/profile/components/NonBeneficiaryHeader.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16466
I have:
|     |         |                 |          <img width="1174" alt="Capture d’écran 2022-08-02 à 16 46 15" src="https://user-images.githubusercontent.com/46637324/182403547-fb3bda07-944f-4b27-ac9b-ba4d4e39ba09.png">        |                  |
> (PC-16466) feat(Profile): Update eligibility wording in non beneficiary header

- src/ui/components/inputs/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15578
I have:
> (PC-15578) refactor(props): input types

- __snapshots__/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx.web-snap
- src/libs/share/shareApp/ShareAppModal.tsx
- src/libs/share/shareApp/shareAppContent.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16271
I have:
> (PC-16271) fix(shareApp): udpate wording

- doc/development/optimization.md
- package.json
- web/config/webpack.config.js
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16623
I have:
> (PC-16623) build(Web): webpack bundle visualizer for production build

- doc/development/optimization.md
- package.json
- web/config/webpack.config.js
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16639
I have:
> (PC-16639) build(Web): added inspectpack to show deduping info during prod build

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/profile/components/CreditExplanation/CreditExplanation.native.test.tsx.native-snap
- __snapshots__/features/profile/components/headers/CreditHeader/CreditHeader.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- src/features/profile/components/CreditExplanation/CreditExplanation.tsx
- src/features/profile/components/CreditInfo/CreditProgressBar.native.test.tsx
- src/features/profile/components/CreditInfo/CreditProgressBar.tsx
- src/features/profile/components/headers/CreditHeader/CreditHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16474
I have:
|  ![Simulator Screen Shot - iPhone 13 - 2022-08-05 at 09 27 25](https://user-images.githubusercontent.com/46637324/183025532-4f48c2d4-e132-4ef1-b405-c05d3fa5ffc4.png)![Simulator Screen Shot - iPhone 13 - 2022-08-05 at 09 27 56](https://user-images.githubusercontent.com/46637324/183025546-baae8648-73bf-4317-baa6-41dfae56db0a.png) ![Simulator Screen Shot - iPhone 13 - 2022-08-05 at 09 29 16](https://user-images.githubusercontent.com/46637324/183025757-34cb6e0d-ef29-4779-b644-ad572bc372b4.png) |         |                 |       <img width="1025" alt="Capture d’écran …
> (PC-16474) fix(Profile): Fix spacing in CreditHeader and add min ProgressBar size

- __snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/LocationPicker.test.tsx.web-snap
- src/ui/components/inputs/SearchInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16715
I have:
|     |         |          ![Simulator Screen Shot - iPhone 13 - 2022-08-08 at 15 34 29](https://user-images.githubusercontent.com/46637324/183433856-87230e23-8f63-4bdc-9842-185e4fe963f1.png)       |           <img width="421" alt="Capture d’écran 2022-08-08 à 15 34 09" src="https://user-images.githubusercontent.com/46637324/183433900-85708195-f565-45e4-9513-9581ec5731c5.png">       |                  |
[2]: …
> (PC-16715) fix(accessibility): Set type attribute to search in web for SearchInput

- src/features/home/components/RecommendationModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16673
I have:
> (PC-16673) feat(tracking): add moduleId to HomeOffer props in reco module

- src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/_marketingAndCommunication/components/__tests__/DeeplinksGeneratorForm.native.test.tsx
Co-authored-by: bruno ebstein <bruno.ebstein@passculture.app>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16695
I have:
> feat(deeplinksGenerator): force showResults

- src/libs/itinerary/useItinerary.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16687
I have:
> (PC-16687) fix(useItinerary): Prefer useRef to useState when possible

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- __snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- package.json
- src/features/search/components/SearchBox.tsx
- src/features/search/components/SearchHeader.tsx
- src/features/search/components/__tests__/SearchHeader.web.test.tsx
- src/ui/web/displayOnFocus/displayOnFocus.stories.tsx
- src/ui/web/displayOnFocus/displayOnFocus.tsx
- src/ui/web/displayOnFocus/displayOnFocus.web.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15578
I have:
> (PC-15578) feat(search): add button to go to the suggestions with keyboard

- src/features/profile/components/Badges/SubscriptionMessageBadge.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16175
I have:
> (PC-16175) refactor(subscription): update profile badge wordings

- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx
- src/features/identityCheck/useIdentityCheckSteps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15926
I have:
https://user-images.githubusercontent.com/44037911/183658430-fde4478d-a59d-424b-bc8f-b0af9fd39043.mov
> (PC-15926) feat(phoneVal): make navigation dynamic in phone Validation

- src/service-worker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16586
I have:
> (PC-16586) fix(batch): remove unused import batch sdk service worker

- src/features/search/atoms/Hit.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15695
I have:
|<img width="379" alt="Capture d’écran 2022-08-09 à 18 13 32" src="https://user-images.githubusercontent.com/78556024/183703871-2cc91b3d-2d23-4ec4-ac92-5e5047bd7166.png">|         |                 |                  |                  |
> (PC-15695) feat(search): truncate search group name

- __snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/profile/components/Badges/ProfileBadge.native.test.tsx.native-snap
- __snapshots__/features/profile/components/CreditExplanation/CreditExplanation.native.test.tsx.native-snap
- __snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/PersonalData/__tests__/PersonalData.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- src/features/profile/components/CreditExplanation/CreditExplanation.tsx
- src/ui/components/buttons/ButtonQuaternary.ts
- src/ui/components/buttons/ButtonQuaternaryBlack.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16474
I have:
|     |         |                 |    <img width="1024" alt="Capture d’écran 2022-08-10 à 14 57 05" src="https://user-images.githubusercontent.com/62059034/183906910-b8dc428d-69f6-42b6-9cdd-9044f1e10571.png">  |                  |
> (PC-16474) refactor(Button): change ButtonText to Caption

- src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/_marketingAndCommunication/components/__tests__/DeeplinksGeneratorForm.native.test.tsx
- src/features/navigation/screenParamsUtils.ts
- src/features/search/components/SearchBox.tsx
- src/features/search/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16770
I have:
> (PC-16770) fix(Search): do not focus input when opening FDL/UL

- package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16787
I have:
> (PC-16787) build(Web): set SHOW_DUPLICATES_PLUGIN to defaut true when building web

- src/features/identityCheck/pages/profile/SetSchoolType.tsx
- src/features/identityCheck/pages/profile/SetStatus.tsx
- src/features/identityCheck/pages/profile/__test__/SetSchoolType.native.test.tsx
- src/features/identityCheck/pages/profile/__test__/SetStatus.native.test.tsx
- src/features/identityCheck/useIdentityCheckNavigation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16265
I have:
https://user-images.githubusercontent.com/44037911/183939616-7a22a10d-0caf-4df4-ace1-384e91f4f8c6.mov
https://user-images.githubusercontent.com/44037911/183939675-ddb792a1-4e4a-4808-9ae1-585c36ecbcf0.mov
> (PC-16265) fix(signUp): prevent status button from bouncing

- src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16264
I have:
https://user-images.githubusercontent.com/44037911/183909784-27769ec5-814c-4e75-a2bc-36147a07c69b.mov
https://user-images.githubusercontent.com/44037911/183909843-352bfec1-eb13-4df5-9b82-a6e2a9fcefd1.mov
> (PC-16264) fix(signUp): prevent Honor button from bouncing when submitting Honor statement

- __snapshots__/features/cookies/pages/CookiesConsentModal.native.test.tsx.native-snap
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/cookies/pages/CookiesConsentModal.native.test.tsx
- src/features/cookies/pages/CookiesConsentModal.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16407
I have:
|  <img width="328" alt="Capture d’écran 2022-08-11 à 17 48 47" src="https://user-images.githubusercontent.com/62059034/184175331-18bc031d-987e-426c-897b-5804357fa8d2.png">   |         |                 |        <img width="1792" alt="Capture d’écran 2022-08-11 à 17 42 50" src="https://user-images.githubusercontent.com/62059034/184175366-cd5e6495-3c5f-48f1-ad1c-c507538616d8.png"> |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes- …
> (PC-16407) feat(cookies): add CookiesConsentModal to cheatcode

- __mocks__/libs/react-native-batch.ts
- ios/Podfile.lock
- jest/jest.setup.ts
- package.json
- react-native.config.js
- src/libs/notifications/useStartBatchNotification.native.test.ts
- src/libs/notifications/useStartBatchNotification.ts
- src/libs/react-native-batch/index.ts
- src/libs/react-native-batch/index.web.ts
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16809
I have:
> (PC-16809) fix(batch): replace @bam.tech/react-native-batch by @batch.com/react-native-plugin

- doc/deployment/web-upgrade-detection-service-worker.md
- public/batchsdk-shared-worker.js
- src/service-worker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16584
I have:
> (PC-16584) fix(ServiceWorker): undo deletion of importScript, add doc and empty file for batchsdk

- __mocks__/libs/react-native-batch.ts
- src/features/home/pages/Home.tsx
- src/features/home/pages/tests/Home.native.test.tsx
- src/features/offer/pages/Offer.tsx
- src/libs/react-native-batch/index.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16677
I have:
> (PC-16677) feat(batch): Add event tracker in home and offer

- src/features/navigation/screenParamsUtils.ts
- src/features/search/components/SearchBox.tsx
- src/features/search/components/__tests__/SearchBox.native.test.tsx
- src/features/search/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16747
I have:
> (PC-16747) fix(search): back button view redirection

- web/config/webpack.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16917
> (PC-16917) build(Web): Clean useless comment in configuration

- ios/Podfile.lock
> build(Podfile): update podfile

- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx.native-snap
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16768
I have:
|  <img width="356" alt="Capture d’écran 2022-08-17 à 17 29 12" src="https://user-images.githubusercontent.com/44037911/185180153-599bc68b-c936-4438-88ac-f46f22015098.png">   |         |                 |      <img width="1080" alt="Capture d’écran 2022-08-17 à 17 27 33" src="https://user-images.githubusercontent.com/44037911/185179795-979a57f5-06c7-414a-9a7e-dc9a61d8943a.png">            |                  |
[2]: …
> (PC-16768) feat(phoneVal): remove phone number placeholder

- __snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.native-snap
- __snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap
- __snapshots__/features/offer/pages/__tests__/OfferBody.deprecated.native.test.tsx.native-snap
- __snapshots__/features/profile/components/SectionWithSwitch/SectionWithSwitch.test.tsx.native-snap
- __snapshots__/features/profile/components/SectionWithSwitch/SectionWithSwitch.test.tsx.web-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- src/features/profile/components/SectionWithSwitch/SectionWithSwitch.tsx
- src/features/search/components/SectionWithSwitch.tsx
- src/ui/components/AccordionItem.stories.tsx
- src/ui/components/AccordionItem.tsx
- src/ui/components/FilterSwitch.stories.tsx
- src/ui/components/FilterSwitch.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16506
I have:
|   ![Simulator Screen Shot - iPhone 13 - 2022-08-18 at 14 27 47](https://user-images.githubusercontent.com/46637324/185400397-80ed4b90-eed7-4528-b193-78f004641223.png)  |         |                 |     Voir storybook             |                  |
> (PC-16506) feat(cookies): Add Switch to AccordionItem

- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- src/features/search/components/SearchResults.tsx
- src/features/search/components/__tests__/SearchResults.native.test.tsx
- src/features/search/pages/Categories.tsx
- src/features/search/pages/__tests__/Categories.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16059
Maquette web temporaire validée par Gabilux
I have:
| <img width="475" alt="image" src="https://user-images.githubusercontent.com/26742386/185163492-7b0328c5-82b0-4d84-a42d-482bd95b734a.png"> |         | <img width="272" alt="image" src="https://user-images.githubusercontent.com/26742386/185163913-c866d62f-dde9-4aa9-aaba-31d9abc7777c.png"> | <img width="1440" alt="image" src="https://user-images.githubusercontent.com/26742386/185163685-1487f053-f756-4271-809a-8aea0169ad3b.png"> |                  |
[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/ …
> (PC-16059) feat(search): add search category filter page

- __snapshots__/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx.native-snap
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16767
I have:
Avant:
Après:
> (PC-16767) feat(SetPhoneNumber): disable phone number input autofill

- src/App.tsx
- src/App.web.tsx
- src/features/cookies/CookiesContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16906
I have:
> (PC-16906) feat(cookies): Add context to store user's choice

- __snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesConsentModal.native.test.tsx.native-snap
- src/features/cookies/CookiesContext.tsx
- src/features/cookies/components/CookiesSettings.native.test.tsx
- src/features/cookies/components/CookiesSettings.tsx
- src/features/cookies/components/cookiesInfo.ts
- src/features/cookies/pages/CookiesConsentModal.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16410
I have:
|   ![Simulator Screen Shot - iPhone 13 - 2022-08-19 at 13 23 22](https://user-images.githubusercontent.com/46637324/185608585-b7e09ac0-00e1-4d3f-96bc-816f4ed87988.png)  |         |                 | https://user-images.githubusercontent.com/46637324/185608745-ba51bfb8-651e-47ab-a6f0-9edea7466a90.mov <img width="1133" alt="Capture d’écran 2022-08-19 à 13 23 37" src="https://user-images.githubusercontent.com/46637324/185608660-398a464d-04d6-4226-93ea-9dbffef793d2.png">                 |                  
[1]: …
> (PC-16410) feat(cookies): Add CookiesSettings component for detailed choice

- __snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesConsentModal.native.test.tsx.native-snap
- src/features/cookies/components/CookiesSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16410
I have:
> (PC-16410) feat(cookies): Fix icon and text alignment in info caption

- src/features/auth/signup/PhoneValidation/SetPhoneNumberDeprecated.tsx
- src/features/auth/signup/PhoneValidation/SetPhoneValidationCodeDeprecated.tsx
- src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCodeDeprecated.native.test.tsx
- src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCodeDeprecated.web.test.tsx
- src/features/identityCheck/context/types.ts
- src/features/identityCheck/pages/phoneValidation/CodeNotReceivedModal.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/CodeNotReceivedModal.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneNumber.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/__tests__/utils.test.ts
- src/features/identityCheck/pages/phoneValidation/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16766
I have:
https://user-images.githubusercontent.com/44037911/185924315-2b63ca0a-010c-4553-8530-6f6ef66b4cd7.mov
https://user-images.githubusercontent.com/44037911/185924339-455a84ff-41d1-4e67-8fa0-d02f2762c2fc.mov
> (PC-16766) feat(phoneVal): improve phone number regex

- src/features/search/atoms/NumberOfResults.tsx
- src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16057
I have:
|<img width="394" alt="Capture d’écran 2022-08-22 à 15 08 24" src="https://user-images.githubusercontent.com/78556024/185939129-5673eb56-fc72-4375-8af5-639d5e3297a8.png"><img width="356" alt="Capture d’écran 2022-08-22 à 16 17 48" src="https://user-images.githubusercontent.com/78556024/185943638-290b24aa-3ec7-419a-bc3d-7ede3b7d862f.png">|<img width="418" alt="Capture d’écran 2022-08-22 à 15 08 57" src="https://user-images.githubusercontent.com/78556024/185939212-cd7d4a81-42a2-4831-875b-c0f6e47352fd.png"><img width="412" alt="Capture d’écran 2022-08-22 à 16 …
> (PC-16057) feat(search): add whitspace filters scroll view search results

- __snapshots__/features/search/components/__tests__/Highlight.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchAutocomplete.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchAutocompleteItem.native.test.tsx.native-snap
- jest.config.js
- package.json
- src/features/search/components/Highlight.tsx
- src/features/search/components/SearchAutocompleteItem.tsx
- src/features/search/components/SearchBox.tsx
- src/features/search/components/__tests__/Highlight.native.test.tsx
- src/features/search/components/__tests__/SearchAutocomplete.native.test.tsx
- src/features/search/components/__tests__/SearchAutocompleteItem.native.test.tsx
- src/libs/algolia/algolia.d.ts
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15891
I have:
|<img width="388" alt="Capture d’écran 2022-08-19 à 17 09 36" src="https://user-images.githubusercontent.com/78556024/185650177-2e5092fa-92f9-40c5-b69a-56d898b0d211.png">|<img width="366" alt="Capture d’écran 2022-08-19 à 17 09 44" src="https://user-images.githubusercontent.com/78556024/185650217-76e21084-d4f6-4f15-9a35-a7a468c1bb94.png">|<img width="1726" alt="Capture d’écran 2022-08-19 à 17 09 55" src="https://user-images.githubusercontent.com/78556024/185650271-ad7b7f03-b052-46c8-a379-8cd50e851a3e.png">|                  |                  |
[1]: …
> (PC-15891) feat(search): add autocompletion highlight

- __snapshots__/features/bookOffer/components/__tests__/BookDuoChoice.web.test.tsx.web-snap
- __snapshots__/features/bookOffer/components/__tests__/BookHourChoice.web.test.tsx.web-snap
- __snapshots__/features/bookOffer/components/__tests__/BookingEventChoices.web.test.tsx.web-snap
- __snapshots__/features/cookies/components/useCookiesModalContent.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap
- __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- __snapshots__/libs/geolocation/components/WhereSection.test.tsx.web-snap
- src/features/cookies/components/CookiesSettings.tsx
- src/features/cookies/components/useCookiesModalContent.native.test.tsx
- src/features/cookies/components/useCookiesModalContent.tsx
- src/features/cookies/pages/CookiesConsent.tsx
- src/features/cookies/pages/CookiesDetails.native.test.tsx
- src/features/cookies/pages/CookiesDetails.tsx
- src/features/profile/pages/ConsentSettings/NewConsentSettings.tsx
- src/locales/fr/messages.po
- src/ui/theme/typography.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16596
I have:
|   ![ios](https://user-images.githubusercontent.com/46637324/186100054-3aa15399-2ec2-4392-bcdb-a16a686a1a35.gif)  |     ![Android](https://user-images.githubusercontent.com/46637324/186100029-626d8554-4259-4e7b-ae4d-6477eec7f967.gif)    |                 |            ![desktop](https://user-images.githubusercontent.com/46637324/186100146-36585335-fdea-4fed-9714-a5136c579d25.gif)      |                  |
[2]: …
> (PC-16596) feat(cookies): Add CookiesDetails step to cookie modal

- .circleci/config.yml
> (BSR) feat(ci) Use bigger machine for test-native CI

- src/features/cookies/pages/CookiesDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16596
I have:
> (PC-16596) fix(cookies): Fix heading level in cookies details

- __snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx.native-snap
- src/features/cookies/components/CookiesConsentModal.tsx
- src/features/cookies/components/CookiesSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16410
I have:
|     |    <img width="427" alt="Capture d’écran 2022-08-24 à 12 20 58" src="https://user-images.githubusercontent.com/62059034/186417677-1555ec1f-79cb-4815-8021-017d47cac408.png">   |                 |   <img width="1792" alt="Capture d’écran 2022-08-24 à 14 25 29" src="https://user-images.githubusercontent.com/62059034/186417808-c0e93745-2d8c-4b29-bbfc-d8ff6102817a.png"> |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les …
> (PC-16410) fix(cookies): update modal design

- src/features/bookOffer/components/AlreadyBooked.tsx
- src/features/bookOffer/pages/__tests__/BookingOfferModal.native.test.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16989
I have:
> (PC-16989) fix(AlreadyBooked): update message

- .env.integration
- .env.production
- .env.staging
- .env.testing
- src/features/search/pages/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17051
I have:
> (PC-17051) fix(Web): do not end .env files with a slash

- __snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx.native-snap
- src/features/cookies/components/cookiesInfo.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16599
I have:
> (PC-16599) fix(cookies): Fix wording

- __snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap
- __snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap
- __snapshots__/features/search/components/__tests__/SearchResults.web.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.native-snap
- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/CategoriesModal.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- src/features/search/components/SearchResults.tsx
- src/features/search/components/__tests__/SearchResults.native.test.tsx
- src/features/search/components/__tests__/SearchResults.web.test.tsx
- src/features/search/pages/Categories.tsx
- src/features/search/pages/CategoriesModal.tsx
- src/features/search/pages/__tests__/Categories.test.tsx
- src/features/search/pages/__tests__/CategoriesModal.web.test.tsx
- src/ui/components/headers/PageHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16921
I have:
|<img width="386" alt="Capture d’écran 2022-08-25 à 11 36 46" src="https://user-images.githubusercontent.com/78556024/186632780-98b181ea-24fb-491f-a133-f4c0f4467ad8.png">|         |<img width="398" alt="Capture d’écran 2022-08-25 à 11 34 56" src="https://user-images.githubusercontent.com/78556024/186632828-d16e48cf-582e-435b-9ca2-e08c45cc5901.png">|<img width="1723" alt="Capture d’écran 2022-08-25 à 11 33 45" src="https://user-images.githubusercontent.com/78556024/186632871-114e9f1c-9db7-4f98-9e6c-f595b0ec16ef.png">|                  |
[1]: …
> (PC-16921) feat(search): use modal web category filter page

- .circleci/config.yml
- server/package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17063
I have:
> (PC-17063) ci(Proxy): fix deploy proxy job due to node18 upgrade

- __snapshots__/features/identityCheck/pages/confirmation/__test__/BeneficiaryAccountCreated.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/BeneficiaryAccountCreated.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/UnderageAccountCreated.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/confirmation/__test__/UnderageAccountCreated.test.tsx.web-snap
- src/features/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/cheatcodes/pages/NavigationSignUp/NavigationSignUp.tsx
- src/features/identityCheck/pages/Stepper.tsx
- src/features/identityCheck/pages/__test__/Stepper.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
- src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx
- src/features/identityCheck/pages/confirmation/UnderageAccountCreated.tsx
- src/features/identityCheck/pages/confirmation/__test__/BeneficiaryAccountCreated.test.tsx
- src/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx
- src/features/identityCheck/pages/confirmation/__test__/UnderageAccountCreated.test.tsx
- src/features/navigation/RootNavigator/identityCheckRoutes.ts
- src/features/navigation/RootNavigator/types.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16932
I have:
https://user-images.githubusercontent.com/44037911/186903816-fa64f7e4-017f-4668-9096-df5686ea2622.mp4
> (PC-16932) feat(signUp): make beneficiaryAccountCreated page more generic

- src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15778
I have:
> (PC-15778) fix(accessibility): Use appropriate heading in search page

- src/libs/search/__tests__/parseSearchParameters.test.ts
- src/libs/search/__tests__/useParseSearchParameters.test.ts
- src/libs/search/useParseSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16658
I have:
**Playlist duo à - de 20e AVANT :**
**Playlist duo à - de 20e MAINTENANT :**
> (PC-16658) fix(home): fix price max parameter

- __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/tests/VenuesModule.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
- __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
- ios/Podfile.lock
- jest/jest.setup.ts
- package.json
- src/ui/components/Playlist.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16689
I have:
Voir [staging](https://appcenter.ms/orgs/pass-Culture/applications) v1.202.90
| https://user-images.githubusercontent.com/46637324/187250362-c4825cd3-8b50-42f6-957f-af444dfc072e.mp4   |         |                 |                  |                  |
> (PC-16689) perf(home): Use FlashList horizontally for playlists

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16689
I have:
> (PC-16689) build(web): Remove duplicate package

- __snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap
- src/features/cookies/components/CookiesConsentButtons.tsx
- src/features/cookies/components/CookiesConsentModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16596
I have:
|  <img width="362" alt="Capture d’écran 2022-08-30 à 10 53 23" src="https://user-images.githubusercontent.com/62059034/187395039-8318cbbd-ec8d-4231-a320-7a1737ad5349.png">  |         |                 |                  |                  |
> (PC-16596) fix(cookies): add custom Safe Insets top to CookiesConsentModal

- src/features/cheatcodes/pages/AppComponents/iconsExports.ts
- src/features/search/atoms/FilterRow.stories.tsx
- src/features/search/atoms/FilterRow.tsx
- src/ui/svg/icons/OtherOffer.tsx
- src/ui/svg/icons/Sort.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17061
I have:
> (PC-17061) fix(Search): added FilterRow on storybook

- src/features/search/pages/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17118
I have:
> (PC-17118) fix(Search): remove integration workaround

- __snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap
- src/features/search/components/SearchResults.tsx
- src/features/search/components/__tests__/SearchResults.native.test.tsx
and location filters
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17114
I have:
> (PC-17114) feat(search): remove use ff categories and location filters

- __snapshots__/features/cookies/components/useCookiesModalContent.native.test.tsx.native-snap
- src/features/cookies/components/CookiesSettings.native.test.tsx
- src/features/cookies/components/CookiesSettings.tsx
- src/features/cookies/components/useCookiesModalContent.native.test.tsx
- src/features/cookies/components/useCookiesModalContent.tsx
- src/features/cookies/getCookiesChoiceFromCategories.test.ts
- src/features/cookies/getCookiesChoiceFromCategories.ts
- src/features/cookies/pages/CookiesConsent.native.test.tsx
- src/features/cookies/pages/CookiesConsent.tsx
- src/features/cookies/pages/CookiesDetails.native.test.tsx
- src/features/cookies/pages/CookiesDetails.tsx
- src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx
- src/features/profile/pages/ConsentSettings/NewConsentSettings.tsx
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16598
I have:
> (PC-16598) feat(cookies): Save user's detailed consent choice

- src/features/bookings/pages/BookingDetails.tsx
- src/features/identityCheck/api/api.ts
- src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx
- src/features/profile/pages/ChangeEmail/utils/useValidateEmail.test.ts
- src/features/profile/pages/ChangeEmail/utils/useValidateEmail.ts
- src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16975
I have:
> (PC-16975) fix(wording): update wording

- __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
- __snapshots__/features/search/pages/__tests__/CategoriesModal.web.test.tsx.web-snap
- src/features/search/components/FilterPageButtons/FilterPageButtons.native.test.tsx
- src/features/search/components/FilterPageButtons/FilterPageButtons.tsx
- src/features/search/pages/Categories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17056
I have:
> (PC-17056) refactor(search): extract localisation filter bottom buttons
