pass-culture/pass-culture-app-native

.github/PULL_REQUEST_TEMPLATE.md

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4710
I have:
If native code (ios/android) was modified, after the PR is merged go to master and upgrade the __app version__ (+1 patch):\$
- use `yarn version --patch` (it will create a commit and a tag)
- then `git push`

[PC-4710] script to bump verison and template

---

.gitignore

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4727
I have:
If native code (ios/android) was modified, after the PR is merged go to master and upgrade the __app version__ (+1 patch):
(later there will be a script to embed these commands) 
- use `yarn version --patch` (it will create a commit and a tag)
- then `git push && git push origin <tag_name>`
- then use the deploy script (temporary -> waiting for CI/CD to be ready)

[PC-4727] ignore bundle install file in CI

---

README.md
android/keystores/development.keystore.properties

Le merge de la PR sur l'authentification (PC-4562) a cassé le déploiement en testing sur android, à cause de ce commit: https://github.com/pass-culture/pass-culture-app-native/commit/763efe1dfb42e690fe8e1dea4c4d399bfa361959. Pour pouvoir lancer le build android en local et en environnement de dev, j'avais ajouté le fichier `android/keystores/development.keystore.properties` mais du coup ça plante le déploiement: https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/156/workflows/58570709-bf77-4cbf-b59b-3d3d895d7d6a/jobs/164. Pour corriger ça j'ai supprimé le fichier, et pour que le build de l'app en environnement de dev fonctionne, il faut le créer à la main (il sera ignoré par git ensuite) => cf README

Fix android deploy on testing

---

.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE.md
package.json
scripts/update_testing_version.sh

I have:
If native code (ios/android) was modified, after the PR is merged go to master and upgrade the __app version__ (+1 patch):
(later there will be a script to embed these commands) 
- use `yarn version --patch` (it will create a commit and a tag)
- then `git push && git push origin <tag_name>`
- then use the deploy script (temporary -> waiting for CI/CD to be ready)

[PC-4728] Yarn version tool for testing & CI for android hard deployment in testing

---

.circleci/config.yml
fastlane/Fastfile

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4729
I have:
If native code (ios/android) was modified, **before** the PR is merged, on the working branch, upgrade the **app version** (+1 patch):

(PC-4729): Add soft deploy for ios in testing

---

.eslintrc.js
android/app/build.gradle
package.json
src/features/auth/api.ts
src/features/auth/pages/Login.test.tsx
src/features/auth/pages/Login.tsx
src/features/home/pages/Home.test.tsx
src/features/home/pages/Home.tsx
src/features/home/pages/__snapshots__/Home.test.tsx.snap
src/libs/fetch.ts
src/libs/storage.ts
src/locales/fr/messages.po

I have:
- [] Explained my technical strategy below if feature is complex.
If native code (ios/android) was modified, after the PR is merged go to master and upgrade the **app version** (+1 patch):
(later there will be a script to embed these commands)
- use `yarn version --patch` (it will create a commit and a tag)
- if you want an hard deployment of the testing environment, use `yarn version:testing` instead.
- then `git push && git push origin <tag_name>`
- then use the deploy script (temporary -> waiting for CI/CD to be ready)
voici mon avancement sur les cookies pour celui qui veut reprendre le ticket demain:
- l’authentification de la requete react-query fonctionne sur Android (device) et iOS (simulateur)
- quelques …

[PC-4792] Integrate React-query

---

babel.config.js

I have:
If native code (ios/android) was modified, **before** the PR is merged, on the working branch, upgrade the **app version** (+1 patch):
* La ligne `root: ['./src/', './__mocks__'],` faisait que `./__mocks__` était présent dans le build
* Résultat, on a une erreur `ReferenceError: Can't find variable: jest` et plein d'autres au lancement de l'app "compilée"
* On a toujours besoin de l'alias, notamment pour runner les tests

(PC-4408) fix: babel plugin resolver not to include mocks in build

---

.circleci/config.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5029
I have:
-  [ ] ~Made sure my feature is working on the relevant real / virtual devices.~

[PC-5029] Circle CI - Ajouter le fichier GoogleService-Info.plist dans le dossier /ios avant le build iOS

---

README.md
package.json
scripts/deploy_new_staging_version.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4997
I have:
Je pensais faire un déploiement sur l'événement 'nouveau tag' mais apparemment pas possible côté circleci :(
Donc j'ai ajouté un script qui permet d'ajouter un nouveau tag sur master + push sur la branche staging pour effectuer un nouveau déploiement

(PC-4997): Add tag for deploy staging command

---

src/features/cheatcodes/pages/Navigation.tsx
src/features/home/pages/Home.test.tsx
src/features/home/pages/Home.tsx
src/features/home/pages/__snapshots__/Home.test.tsx.snap
src/features/navigation/RootNavigator.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4371
I have:
| Home page | Navigation page |
| --------------- | ----------------------- |
| ![image](https://user-images.githubusercontent.com/22399093/97978637-22d84780-1dce-11eb-8cb3-8e9353b8ebc6.png) | ![image](https://user-images.githubusercontent.com/22399093/97978672-2c61af80-1dce-11eb-8b78-57f7ce2347be.png) |

(PC-4371) Dev : display access button  to "cheat" navigation page on home page

---

README.md
package.json
src/features/cheatcodes/components/IdCheckButton.test.tsx
src/features/cheatcodes/components/IdCheckButton.tsx
src/features/cheatcodes/pages/CheatCodes.tsx
src/features/cheatcodes/pages/IdCheck.test.tsx
src/features/cheatcodes/pages/IdCheck.tsx
src/features/cheatcodes/pages/__snapshots__/CheatCodes.test.tsx.snap
src/features/cheatcodes/pages/__snapshots__/IdCheck.test.tsx.snap
src/features/navigation/RootNavigator.tsx
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4838
I have:
Exemple d'utilisation d'une webview avec le parcours Id check de la web app:
Pour que ce soit un minimum testable en l'état, j'ai fait en sorte de rediriger l'app vers la page de cheatcodes lorsque l'on quitte le parcours id check (qui redirige normalement vers la page d'accueil de la webapp). J'aimerais bien tester cette redirection mais je n'ai pas réussi ce matin.

[PC-4838] test webview

---

src/features/home/api.test.ts
src/features/home/api.ts
src/features/home/contentful/contentful.ts
src/features/home/contentful/processHomepageEntries.test.ts
src/features/home/contentful/processHomepageEntries.ts
src/tests/fixtures/homepageEntries.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5189
I have:
- Rajout d'un ContentType `homepageNatif` dans [Contentful](https://app.contentful.com/spaces/2bg01iqy0isv/environments/testing/content_types)
- Modification du code pour appeler ce content type (au lieu de `homepage` => réservé pour la web app)
-  en passant, j'ai créé un content de contentType `homepageNatif` pour que la transition soit smooth pour les devs.
Content Types:
Content:

[PC-5189] Création du contentmodel Contentful homepageNatif

---

src/features/auth/pages/Login.test.tsx
src/features/auth/pages/Login.tsx
src/features/auth/pages/__snapshots__/Login.test.tsx.snap
src/ui/components/inputs/helpers.test.ts
src/ui/components/inputs/helpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4371
I have:
| Android phone button disabled | Android phone button enabled |
| -------------------- | -------------- |
| ![image](https://user-images.githubusercontent.com/22399093/98944261-1308e380-24f1-11eb-8a4d-7ec62d2ca68f.png) | ![image](https://user-images.githubusercontent.com/22399093/98944292-1ac88800-24f1-11eb-9403-bf3f7c71118b.png) |

(PC-4371) Le bouton login est disabled si les deux text inputs ne sont pas remplis

---

src/App.test.tsx
src/App.tsx
src/libs/notifications/index.ts
src/libs/notifications/startBatchNotification.ts
src/libs/notifications/useStartBatchNotification.test.ts
src/libs/notifications/useStartBatchNotification.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5161
I have:

(PC-5161) use Batch.start() inside useEffect

---

__mocks__/@react-navigation/native.ts
src/features/auth/pages/ReinitializePassword.test.tsx
src/features/auth/pages/ReinitializePassword.tsx

I have:
- [] Written **unit tests** for my feature.

(PC-5142) Change the way error message is shown

---

src/features/auth/pages/ResetPasswordExpiredLink.tsx
src/ui/components/GenericInfoPage.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-4939
I have:
| \*iOS - [Phone name] | \*Android - [Phone name] | Tablet - Pixel C | Little - [Phone name] |
|                      |                          |   ![Screenshot_1605869056](https://user-images.githubusercontent.com/22399093/99791463-f2aadb80-2b25-11eb-811b-ec1333af6683.png)        | |

(PC-4939) Rendre la page "Icon - Titre" réutilisable

---

src/features/auth/api.ts

C'était possible pour les utilisateurs qui ne se sont jamais connectés d'avoir un crash à cause d'une requête 422 sur la page des cheatcodes. Si ça arrive, maintenant, on ne throw pas l'erreur.

Avoid crash on Cheatcode page for unauthenticated users

---

src/features/deeplinks/routing.test.ts
src/features/deeplinks/routing.ts
src/features/deeplinks/types.ts
src/features/deeplinks/useDeeplinkUrlHandler.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5143
Fix suite au retour de validation PO : https://passculture.atlassian.net/browse/PC-5143?focusedCommentId=17486
Problème : le param `email` n'était pas passé au Screen `ResetPasswordExpiredLink`.
I have:

(PC-5143) Fix du renvoie de l'email si le lien reset MDP est expiré

---

src/libs/keychain.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5544
Lien doc: https://github.com/oblador/react-native-keychain#resetgenericpassword-service-
I have:

[PC-5544] Fix signout Android

---

src/features/home/components/ExclusivityModule.tsx
src/features/home/components/tests/ExclusivityModule.test.tsx
src/libs/__mocks__/analytics.ts
src/libs/analytics.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5531
I have:
|![image](https://user-images.githubusercontent.com/66383742/100747564-84e29780-33e2-11eb-92e9-c4c63b01a4ad.png)|                          |                       |                       |

(PC-5531) feat: add analytics event for click on exlcu block

---

src/features/cheatcodes/pages/CheatCodes.test.tsx
src/features/cheatcodes/pages/CheatCodes.tsx
src/features/cheatcodes/pages/__snapshots__/CheatCodes.test.tsx.snap

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5737
I have:

[PC-5737] display code push button testing env

---

src/features/home/pages/Home.tsx
src/features/navigation/TabBar/TabBar.tsx
src/features/navigation/TabBar/__tests__/TabBar.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5657
I have:

(PC-5657) afficher la modale de connexion depuis le bouton profil de la navbar

---

src/features/home/atoms/ImageCaption.tsx
src/features/home/atoms/tests/ImageCaption.test.tsx
src/features/home/atoms/tests/__snapshots__/ImageCaption.test.tsx.snap
src/features/home/atoms/tests/__snapshots__/OfferTile.test.tsx.snap
src/features/home/components/OffersModule.tsx
src/features/home/components/tests/__snapshots__/OffersModule.test.tsx.snap
src/libs/parsers/category.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5746
I have:
Catégorie la pus longue = 'Rencontre', distance la plus longue= '900+ km'

[PC-5746] Offer Tiles categories not trunc

---

scripts/detect_ko_test.py
src/tests/reactQueryProviderHOC.tsx
src/tests/setupTests.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5740
| ------- | ----- |
|![image](https://user-images.githubusercontent.com/66383742/102102533-35fa2080-3e2c-11eb-9efb-79b8f16bce23.png) |![image](https://user-images.githubusercontent.com/66383742/102102462-2084f680-3e2c-11eb-890d-15a724c39cc9.png)| 
Jest conseille `yarn jest --detectOpenHandles --runInBand` pour détecter les fuites, faire cela sur notre répo donnera le même résultat qu'en CI: les tests finis en ~70s et la commande qui continue de tourner dans le vide 5min.
Pour identifier la source j'ai lancé chaque test avec `yarn jest <test_name> --detectOpenHandles`
Et identifier ceux qui sont anormalement longs. (script)
```
...
Offer.test.tsx
---- Time it took to do this test:  310.40674090385437s …
```

(PC-5740) feat: clear react-query cache after each test file

---

src/features/auth/login/Login.test.tsx
src/features/auth/login/Login.tsx
src/features/navigation/helpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5831
I have:

(PC-5831) Réinitialisation de mot de passe : le retour arrière sur l'écran de connexion n'est pas correct

---

src/features/offer/components/OfferPartialDescription.tsx
src/features/offer/components/__tests__/OfferPartialDescription.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-c
I have:

[PC-6100] Masquer le bouton 'Voir plus' si le descriptif détaillé est vide

---

src/features/home/pages/Home.tsx
src/features/home/pages/__snapshots__/Home.test.tsx.snap
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6288
I have:

[PC-6288] Use familiarization on homepage

---

src/features/auth/forgottenPassword/__snapshots__/ReinitializePassword.test.tsx.snap
src/features/auth/login/__snapshots__/Login.test.tsx.snap
src/features/auth/signup/QuitSignupModal.tsx
src/locales/fr/messages.po
src/ui/components/inputs/rules/InputRule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6344
I have:

(PC-6344) Réduire l'espace entre l'icône et le texte sur les messages d'information (cf. pages SetEmail, SetPassword etc...)

---

src/features/auth/signup/AccountCreated.test.tsx
src/features/auth/signup/AccountCreated.tsx
src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx
src/features/auth/signup/AfterSignupEmailValidationBuffer.tsx
src/features/auth/signup/__snapshots__/AccountCreated.test.tsx.snap
src/features/cheatcodes/pages/Navigation.tsx
src/features/navigation/RootNavigator/RootNavigator.tsx
src/features/navigation/RootNavigator/types.ts
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6346
I have:
| \*iOS - [Phone name] | 
| ![simulator_screenshot_41B9E249-65E4-40BC-9FDF-2C9D3D7AA873](https://user-images.githubusercontent.com/22399093/105340358-0fbf6180-5bde-11eb-8e35-f7af5b43d7fa.png) |

(PC-6346) Add AccountCreated page to display for non-beneficiary users

---

.github/PULL_REQUEST_TEMPLATE.md
package.json
scripts/deploy_new_staging_version.sh
scripts/deploy_new_testing_version.sh
scripts/update_testing_version.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6414
I have:
- if you want an hard deployment of the testing environment, use `yarn trigger:testing:version`

[PC-6414] Harmonize way to deploy to testing and staging

---

__mocks__/@bam.tech/react-native-batch.ts
src/features/cheatcodes/pages/CheatCodes.test.tsx
src/features/cheatcodes/pages/CheatCodes.tsx

(PC-6532) set batch custom id from the cheatcodes page

---

src/features/firstLogin/CulturalSurvey.test.tsx
src/features/firstLogin/CulturalSurvey.tsx
src/features/firstLogin/__snapshots__/CulturalSurvey.test.tsx.snap

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5965
I have:

(PC-5965) Close cultural survey on navigation state change instead of onSubmit

---

src/features/auth/signup/IdCheck.tsx
src/features/auth/signup/__snapshots__/IdCheck.test.tsx.snap

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-5438?focusedCommentId=19317
I have:
Solution temporaire au bug repéré par Lina (cf lien du commentaire dans le ticket): forcer un retour en arrière sur l'historique de la webview. Si on clique sur le lien "Contacter le support" (que ce soit sur la page "session expirée" ou "document invalide" du parcours idcheck) et que l'erreur survient (il semblerait que cela arrive au tout premier clic sur ce lien quand on lance l'appli), au retour en arrière sur l'appli on se retrouve sur la page où l'utilisateur est invité à ajouter sa carte d'identité, et non sur la page "session expirée" ou "document invalide".
On va créé un ticket de bug pour apporter …

(PC-5438) IdCheck: fix temporarily mailto link error on webview

---

src/features/firstLogin/tutorials/components/GenericCard.test.tsx
src/features/firstLogin/tutorials/components/GenericCard.tsx
src/features/firstLogin/tutorials/components/GenericTutorial.test.tsx
src/features/firstLogin/tutorials/components/GenericTutorial.tsx

App native - Tutoriels & Typeform - Ajouter l'analytics à l'affichage d'une carte
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6789
I have:

[PC-6789] App native - Tutoriels & Typeform - Ajouter l'analytics à l'affichage d'une carte

---

src/api/gen/api.ts
src/features/home/api.test.ts
src/features/offer/components/__tests__/OfferIconCaptions.test.tsx
src/features/profile/components/BeneficiaryCeilings.tsx
src/features/profile/components/BeneficiaryHeader.tsx
src/features/profile/components/ProfileHeader.test.tsx
src/features/profile/components/ProfileHeader.tsx
src/features/profile/components/types.ts
src/features/profile/pages/Profile.test.tsx
src/features/profile/utils.test.ts
src/features/profile/utils.ts
src/libs/parsers/pricesConversion.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6169
I have:

(PC-6169) intégrer le header bénéficiaire dans la page profile

---

src/features/auth/login/Login.tsx
src/features/auth/signup/SetEmail.tsx
src/features/navigation/RootNavigator/types.ts
src/features/navigation/backNavigation.ts
src/features/profile/components/LoggedOutHeader.test.tsx
src/features/profile/components/LoggedOutHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6372
I have:
- [-] Added new reusable components to the AppComponents page and communicate to the team on slack
- [-] Attached a **ticket number** for any added TODO/FIXME \
| \*iOS - [Set Email] | \*iOS - [Login] | Tablet - [Phone name] | Little - [Phone name] |
| ![image](https://user-images.githubusercontent.com/6025710/108087512-d14f8200-7077-11eb-9b6e-eb73a9f3e890.png)| ![image](https://user-images.githubusercontent.com/6025710/108087627-e9270600-7077-11eb-88cc-c7dbbb955544.png) |                       |                       |
If native …

Hide Close icon on Login/SetEmail when coming from the profile page

---

src/features/offer/atoms/AccessibilityAtom.tsx
src/features/offer/components/OfferHeader.tsx
src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap
src/features/offer/pages/tests/__snapshots__/Offer.test.tsx.snap
src/features/offer/pages/tests/__snapshots__/Offer.transition.test.tsx.snap

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6340
I have:
=> **VETO**: il faut être en police extrêmement large pour reproduire, et c'est très léger.

[PC-6340]  Détail de l'offre - Polices large et rendu tablettes

---

src/features/navigation/TabBar/TabBar.tsx
src/features/navigation/TabBar/TabNavigator.tsx
src/features/navigation/TabBar/__tests__/TabBar.test.tsx
src/features/navigation/TabBar/__tests__/__snapshots__/TabBar.test.tsx.snap

**Bonus** : use actual routes in TabBar.test.tsx
Link to JIRA ticket: fix without ticket
I have:
| \*iOS - iPhone 11 | 
| -------------------- | 
| <img width="326" alt="Capture d’écran 2021-03-02 à 11 59 23" src="https://user-images.githubusercontent.com/22399093/109638806-be947d00-7b4e-11eb-9e1d-4ba769f89057.png"> |

Fix InitialRoutingScreen icon displayed in tab bar

---

src/api/gen/api.ts
src/features/auth/signup/AcceptCgu.test.tsx
src/features/auth/signup/AcceptCgu.tsx
src/features/home/api.test.ts
src/features/offer/components/__tests__/OfferIconCaptions.test.tsx
src/features/profile/components/ProfileHeader.test.tsx

(PC-7214) App native - Backend - déplacer l'information  hasAllowedRecommendations dans la colonne notification_subscriptions
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7214
I have: …

(PC-7214) App native - Backend - déplacer l'information  hasAllowedRecommendations dans la colonne notification_subscriptions

---

src/libs/parsers/getDisplayPrice.ts
src/libs/parsers/tests/getDisplayPrice.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7394
I have:
In javascript:
```js
> [2, 10, 30].sort()
[ 10, 2, 30 ]
```
=> instead of "Dès 2€", we thus showed "Dès 10€".

(PC-7394) Fix price displayed on search page: sort improperly

---

package.json
src/features/cheatcodes/pages/Navigation.tsx
yarn.lock

(Tech): remove POC geolib and use previous distance method

---

src/features/profile/pages/ChangePassword.tsx
src/features/profile/pages/ConsentSettings.tsx
src/features/profile/pages/LegalNotices.tsx
src/features/profile/pages/NotificationSettings.tsx
src/features/profile/pages/PersonalData.tsx
src/features/profile/pages/__snapshots__/ChangePassword.test.tsx.snap
src/ui/components/headers/PageHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7014
Sur iOS, le chevron back ne fonctionne pas si le composant PageHeader est situé avant les composants de spacing en haut de l'écran.
I have: …

(PC-7014) profile pages: fix PageHeader position

---

scripts/deploy_new_production_version.sh
scripts/deploy_new_staging_version.sh
scripts/deploy_new_testing_version.sh

There are two types of tags: lightweight and annotated. 
Ref: https://git-scm.com/book/en/v2/Git-Basics-Tagging

(FIX-CI) --follow-tags only pushed annotated tags

---

src/features/auth/signup/AcceptCgu.test.tsx
src/features/auth/signup/AcceptCgu.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7595
I have:

(PC-7595) Disable loading button when signup call resolves successfully

---

src/App.tsx

https://passculture.atlassian.net/browse/PC-7617
(Tech) remove all YellowBox warning "Setting a timer..." thrown when using FlatList
I have:

(PC-7617) (Tech) remove all YellowBox warning "Setting a timer..." thrown when using FlatList

---

src/features/favorites/atoms/Favorite.tsx
src/features/favorites/atoms/__tests__/Favorite.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7149
I have:

(PC-7149) App native - Favoris - Bouton Crédit insuffisant fix

---

src/features/favorites/atoms/BicolorFavoriteCount.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7022
I have:
| \*iOS - [Phone name] | \*Android - [s9] | Tablet - [Phone name] | Little - [Phone name] |
|                      | ![image](https://user-images.githubusercontent.com/77674046/111465906-ebd25500-8722-11eb-89a3-473afe0367e8.png) |                       |                       |

(PC-7022) App native - Favoris - Afficher le nombre de favoris dans la navbar fix

---

src/features/bookOffer/components/Calendar/DayComponent.tsx

`new Date("2021-03-21")` in a GMT-3 timezone results to the day before : `2021-03-20T21:00 GMT-3`.
So use the year, month, day to construct the desired "date".
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6690
I have:

(PC-6690) Fix booking date selection in western timezones

---

README.md
src/api/gen/api.ts
src/features/cheatcodes/pages/AppComponents.tsx
src/features/home/api.test.ts
src/features/offer/components/__tests__/OfferIconCaptions.test.tsx
src/features/profile/components/NonBeneficiaryHeader.test.tsx
src/features/profile/components/NonBeneficiaryHeader.tsx
src/features/profile/components/ProfileHeader.test.tsx
src/features/profile/components/ProfileHeader.tsx
src/features/profile/utils.test.ts
src/features/profile/utils.ts

This prevents from having timezone offsets: In china frontend hour would say the user is 18, although the user is still 17 for the server which would reject id-check request.
I have:

(PC-6690) Use eligibility start/end date for NonBeneficiaryHeader

---

src/features/bookings/pages/Bookings.test.tsx
src/features/bookings/pages/Bookings.tsx
src/features/bookings/pages/EndedBookings.test.tsx
src/features/bookings/pages/EndedBookings.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7428
I have:
|![Simulator Screen Shot - iPhone 12 - 2021-03-23 at 20 03 13](https://user-images.githubusercontent.com/22886846/112203599-028d1600-8c13-11eb-8df7-1d477b8afe8c.png)
- if you want an hard deployment of the testing environment, …

(PC-7428) réservations terminées: affichage du header et du nombre de résas terminées

---

src/features/bookings/components/OnGoingBookingsList.tsx
src/features/bookings/pages/EndedBookings.tsx
src/locales/fr/messages.po

L'utilisation de `i18n.plural` introduisait un bug "Cannot find variable intl" et malgré l'installation du package le bug persiste, il faut donc creuser un peu plus le problème. Pour ne pas bloquer la recette PO et graphique on repasse à la méthode de pluriel "fait main" et on essaiera d'utiliser `i18n.plural` dans un ticket d'amélioration technique.
I have:
|                      |                          |                       | …

(PC-7428) Bookings: fix plural

---

src/features/favorites/pages/__tests__/__snapshots__/FavoritesSorts.test.tsx.snap
src/features/offer/pages/tests/__snapshots__/OfferDescription.test.tsx.snap
src/features/search/pages/__tests__/__snapshots__/Categories.test.tsx.snap
src/features/search/pages/__tests__/__snapshots__/LocationFilter.test.tsx.snap
src/features/search/pages/__tests__/__snapshots__/SearchFilter.test.tsx.snap
src/ui/components/headers/PageHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7499
I have:
| \*iOS - iPhone 11 | \*Android - Pixel 3a |
| <img width="335" alt="Capture d’écran 2021-03-29 à 17 57 23" src="https://user-images.githubusercontent.com/22399093/112864580-399e7400-90b8-11eb-91df-542b2b8c2c5d.png"> |  <img width="311" alt="Capture d’écran 2021-03-29 à 18 14 08" src="https://user-images.githubusercontent.com/22399093/112866943-a61a7280-90ba-11eb-8f21-51a8229de9f8.png">     |

(PC-7499) Make headers titles perfectly centered no matter the icons sizes

---

src/features/search/components/SearchResults.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7827
I have:

(PC-7827) App native - Recherche - Le scroll ne remonte pas en début de page lorsqu'on reboot la recherche en appliquant des filtres

---

src/libs/i18n.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7917
```tsx
console.log(
_({
value: (new Date().getTime() % 2) + 1,
one: '# book',
other: '# books',
})
)
```
```
[Wed Mar 31 2021 17:40:42.581]  LOG      2 books
[Wed Mar 31 2021 17:40:42.592]  LOG      1 book
[Wed Mar 31 2021 17:40:42.602]  LOG      2 books
[Wed Mar 31 2021 17:40:42.612]  LOG      2 books
[Wed Mar 31 2021 17:40:42.622]  LOG      1 book
[Wed Mar 31 2021 17:40:42.634]  LOG      1 book
```
Autre implémentation possible avec `i18n._`: https://github.com/pass-culture/pass-culture-app-native/pull/816
I have: …

(PC-7917) App Native - Amélioration tech - Mise en place de la traduction au pluriel (avec i18n.plural)

---

src/features/bookOffer/components/BookingDetails.tsx
src/features/bookOffer/components/__tests__/BookingDetails.test.tsx
src/features/bookOffer/pages/BookingConfirmation.tsx
src/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx
src/features/navigation/RootNavigator/types.ts
src/libs/__mocks__/analytics.ts
src/libs/analytics.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7849
**SVP: n'ayant pas travaillé sur booking, l'intégration implique que l'`offerId` est toujours défini dans le `onSuccess` du mutate de `useBookOfferMutation` (et donc dans le navigate) : 
```jsx
if (offerId) {
navigate('BookingConfirmation', { offerId })
}
```
Merci de confirmer ici que c'est bien le cas, et donc que l'intégration est OK
I have:

(PC-7849) App Native - Tunnel de résa - Tracking -  Clic sur le bouton voir ma réservation de fin de tunnel

---

src/features/profile/pages/Profile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7767
When scrolling on iOS on the profile page, you get this warning:
> You specified `onScroll` on a <ScrollView> but not `scrollEventThrottle`. You will only receive one event. Using `16` you get all the events but be aware that it may cause frame drops, use a bigger number if you don't need as much precision.
Indeed [scrollEventThrottle](https://reactnative.dev/docs/scrollview#scrolleventthrottle-ios) is required if we want to detect if we have reach the bottom of the screen (to send the appropriate analytics event).
If we don't specify this property, `isCloseToBottom` will be called only once during a continuous scrolling, thus we may miss the moment when we reach the bottom of the screen.

(PC-7767) Fix scrolling detection behaviour

---

src/features/bookings/helpers.ts
src/features/bookings/pages/BookingDetails.tsx
src/features/profile/components/BeneficiaryCeilings.tsx
src/features/profile/components/LoggedOutHeader.tsx
src/features/profile/components/NonBeneficiaryHeader.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7917
I have:

(PC-7917) (Tech) Lingui, extract unicode characteres from translations

---

src/features/eighteenBirthday/pages/EighteenBirthday.tsx
src/features/firstTutorial/pages/FirstTutorial/FirstTutorial.tsx
src/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.test.tsx
src/ui/components/achievements/components/GenericAchievement.test.tsx
src/ui/components/achievements/components/GenericAchievement.tsx
src/ui/components/achievements/components/GenericAchievementCard.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7631
I have:
| -------------------- | :---------------------: |

(PC-7631) Enable device go back button on FirstTutorial

---

src/features/cheatcodes/pages/Navigation.tsx
src/features/firstTutorial/pages/FirstTutorial/FirstTutorial.test.tsx
src/features/firstTutorial/pages/FirstTutorial/FirstTutorial.tsx
src/features/navigation/RootNavigator/types.ts
src/features/navigation/RootNavigator/useInitialScreenConfig.tsx
src/features/navigation/__tests__/useInitialScreenConfig.test.tsx
src/features/profile/pages/Profile.test.tsx
src/features/profile/pages/Profile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7631
I have:

(PC-7631) Do not close app with back action (android) when tutorials are opened from profile screen

---

src/features/home/pages/Home.tsx
src/features/home/pages/tests/HomeWithModal.test.tsx

The refetch make the app fail with this error : The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting.
I have:
- …

Fix app launching

---

src/features/profile/pages/Profile.tsx

The refetch make the app fail with this error : The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting.
I have:
- …

Fix profile page crash

---

ios/PassCulture/Info.plist

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8106
I have:

(PC-8106) App native - Inscription - ID check - La fonctionnalité prendre une photo de ma CNI fait crasher l app

---

src/features/deeplinks/listener.ios.test.ts
src/features/deeplinks/listener.ios.ts
src/features/navigation/__tests__/useInitialScreenConfig.test.tsx

- https://passcultureapptesting.page.link/recherche
Universal Links listener => isFirebaseShortDynamicLink // do nothing
Dynamic Links listener ✅
- https://app.passculture-testing.beta.gouv.fr/offer/?id=220134
Universal Links listener => isUniversalLink ✅
- https://passcultureapptesting.page.link/?link=https://app.passculture-testing.beta.gouv.fr/offer/?id=220134&apn=app.passculture.testing&isi=1557887412&ibi=app.passculture.test&efr=1
Universal Links listener => isFirebaseLongDynamicLink ✅
- https://passcultureapptesting.page.link/recherche
Universal Links listener => isFirebaseShortDynamicLink // do nothing
Dynamic Links listener ✅
- https://app.passculture-testing.beta.gouv.fr/offer/?id=220134
Ouvre la webapp. ❌
- https://passcultureapptesting.page.link/?link=https://app.passculture-tes …

(PC-7393) Fix deeplink and universal link clash

---

src/features/bookings/components/CancelBookingModal.tsx
src/features/profile/components/BeneficiaryHeader.tsx
src/features/profile/components/ExBeneficiaryHeader.test.tsx
src/features/profile/components/ExBeneficiaryHeader.tsx
src/features/profile/components/LoggedOutHeader.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8348
I have:
| \*iOS - [Phone name] | \*Android - [Galaxy] | Tablet - [Phone name] | Little - [Phone name] |
|                      |     ![Capture d’écran 2021-04-27 à 11 28 28](https://user-images.githubusercontent.com/62059034/116389201-fa7d5300-a81c-11eb-8bdd-fe5fd8740533.png)                     |                       |                       |
- if you want an hard deployment of the testing environment, use …

(PC-8348) App Native - Profil - Personnaliser l'intitulé des profils des ex-bénéficaires

---

scripts/deploy.sh

Currently the ci jobs fails on new hard deploy:
because the CircleCi job is not linked to a branch:

(CircleCI) deploy hard on tag as well

---

src/features/auth/signup/IdCheck.test.tsx
src/features/auth/signup/IdCheck.tsx
src/features/firstLogin/CulturalSurvey.test.tsx
src/features/firstLogin/CulturalSurvey.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8336
I have:

(PC-8336) CulturalSurvey: invalidate userprofile request before navigating to home

---

src/features/home/pages/tests/useHomeAlgoliaModules.test.ts
src/features/home/pages/useHomeAlgoliaModules.ts
src/libs/geolocation/GeolocationWrapper.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8501
I have:
La vidéo montre un utilisateur non connecté => pas de module de recommendation donc ce n'est pas un soucis de perf à ce niveau là.
Il s'agit d'une régression récente probablement dû à [cette PR](https://github.com/pass-culture/pass-culture-app-native/pull/972) (une des seules sur le chargement de la home).
Pour moi, l'explication est qu'on ne lance pas les requêtes à Algolia tant qu'on a pas la position, d'où le temps de latence.
Ce qui confirme le manque de skeleton puisque rien n'est en train d'être requêté (cf hook `useShowSkeleton`)

(PC-8501) Le temps de chargement des playlists est démesurément long

---

src/features/auth/signup/SetPhoneNumberValidationCode.test.tsx
src/features/auth/signup/SetPhoneNumberValidationCode.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8164
I have:
|                      |![Screenshot from 2021-05-04 18-31-25](https://user-images.githubusercontent.com/22886846/117037745-1b571400-ad07-11eb-996b-6a9d750cb221.png)![Screenshot from 2021-05-04 18-31-12](https://user-images.githubusercontent.com/22886846/117037749-1befaa80-ad07-11eb-8fc8-4c4afd097445.png)|                       |                       |
If native code (ios/android) was modified, **after** the PR is merged, on the …

(PC-8164) modale de saisie du code de vérification: comportement du bouton continuer

---

src/features/bookings/components/BookingDetailsCancelButton.test.tsx
src/features/bookings/components/BookingDetailsCancelButton.tsx
src/features/bookings/pages/BookingDetails.test.tsx
src/features/bookings/pages/BookingDetails.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8357
I have:

(PC-8357) Refacto: move the cancellation button in a dedicated component

---

src/features/firstTutorial/pages/FirstTutorial/components/FourthCard.test.tsx
src/features/firstTutorial/pages/FirstTutorial/components/FourthCard.tsx
src/features/navigation/RootNavigator/useInitialScreenConfig.tsx
src/features/navigation/__tests__/useInitialScreenConfig.test.tsx
src/libs/splashscreen.tsx
src/ui/components/achievements/components/GenericAchievement.test.tsx
src/ui/components/achievements/components/GenericAchievement.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8413
I have:
Avant cette PR, quand on ouvre l'application, on va sur la `Home` puis on est redirigé vers les cartes Tuto (possibilité dee swiper en arrière et donc d'afficher la Home de façon impromptue, cf ticket).
Maintenant, au lieu d'être redirigé vers les cartes Tutos, on reset l'état de navigation pour que ce soit le premier tuto soit à la racine.
Par conséquent, pour sortir de ces tutos, on remplace la racine de l'état de navigation par la Home.

[PC-8413] Affichage de la home impromptu au swipe sur les cartes tutos

---

ios/PassCulture/AppDelegate.m
ios/Podfile
ios/Podfile.lock
package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8768
The android build fails (cf [circle ci](https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/5392/workflows/610e2317-dc52-46c1-a585-7c2f0b4d96e1/jobs/8776)).
We temporarily revert this PR to prepare for the MES/MEP.
batch android changelog: https://github.com/BatchLabs/Batch-Android-SDK/releases
and commits: https://github.com/BatchLabs/Batch-Android-SDK/commits/master.
Release 1.17.0 seems to break the build, with:
> Added a package query entry in AndroidManifest.xml for com.huawei.appmarket to enable detection of the Huawei AppGallery.
- update gradle tools (cf [react-native-batch breaking changes](https://github.com/bamlab/react-native-batch-push/releases))
> [BREAKING] Make sure to have …

[PC-8768] Revert commit

---

src/features/navigation/RootNavigator/RootNavigator.tsx
src/features/navigation/__tests__/RootNavigator.test.tsx
src/libs/notifications/useStartBatchNotification.test.ts
src/libs/notifications/useStartBatchNotification.ts
src/libs/trackingConsent/useTrackingConsent.ts

Revert of https://github.com/pass-culture/pass-culture-app-native/commit/c2ed62f36ec64687977541162ba26252f6c14ac3
Because the popups for batch do not appear on iOS14.4.2 anymore.
Reason ? not clear

(Tech) show all popup at the same time so we don't miss any

---

ios/Podfile.lock
package.json
src/features/favorites/pages/FavoritesSorts.tsx
src/features/search/pages/LocationFilter.tsx
yarn.lock

(PC-8696) Upgrade react-native-geolocation-service from 5.0.0 to 5.3.0-beta.1 to get android LocationManager Fallback 

---

ios/Podfile.lock
package.json
yarn.lock

This reverts commit 3e1d5bbd5666a3f218495f2a95f1f6e1ec7eed02.
I have:

Revert "Upgrade react-native-geolocation-service from 5.0.0 to 5.3.0-beta.1 to get android LocationManager Fallback"

---

src/features/auth/signup/idCheck/useNavigateToIdCheck.test.tsx
src/features/auth/signup/idCheck/useNavigateToIdCheck.ts
src/features/deeplinks/useDeeplinkUrlHandler.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8877
I have:

(PC-8877) Bug fix : Add option to ignore allowIdCheckRegistration setting in useNavigateToIdCheck()

---

android/gradle.properties

La CI android fail lors du build (exemple [ici](https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/5691/workflows/1ccd277e-81e3-47ab-a813-dbceed81018a/jobs/9360/parallel-runs/0/steps/0-110)).
```
* What went wrong:
Execution failed for task ':app:bundleApptestingReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 137
```
Gradle [needs more memory](https://rnfirebase.io/#increasing-android-build-memory) for firebase librairies.

(CI Android) Increase gradle memory for android builds

---

src/features/auth/signup/IdCheck.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8948 => On veut qu'au clic sur "déposer un dossier en ligne" l'utilisateur soit redirigé vers le navigateur de son téléphone, sans cette redirection, le site de DMS s'ouvre dans la webview
I have:
/!\ ne pas faire attention au design, j'ai bidouillé un truc pour pouvoir tester rapidement en local, la vidéo sert à montrer le comportement au clic sur …

(PC-8948) IdCheck: catch webview DMS redirection

---

src/features/auth/login/Login.test.tsx
src/features/auth/signup/AccountCreated.test.tsx
src/features/auth/signup/AccountCreated.tsx
src/features/auth/signup/BeneficiaryRequestSent.test.tsx
src/features/auth/signup/BeneficiaryRequestSent.tsx
src/features/auth/signup/EligibilityConfirmed.test.tsx
src/features/auth/signup/EligibilityConfirmed.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8941
I have:

(PC-8941) Navigate to cultural survey only if needsToFillCulturalSurvey is true

---

src/features/auth/signup/SetPhoneValidationCodeModal.test.tsx
src/features/auth/signup/SetPhoneValidationCodeModal.tsx
src/ui/components/buttons/ButtonPrimaryWhite.tsx
src/ui/components/buttons/ButtonQuaternary.tsx
src/ui/components/buttons/ButtonSecondary.tsx
src/ui/components/buttons/ButtonTertiary.tsx
src/ui/components/buttons/ButtonTertiaryWhite.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8139
I have:
|                      |![Screenshot from 2021-05-25 14-42-51](https://user-images.githubusercontent.com/22886846/119513078-2f28ef80-bd74-11eb-97ab-0b0ac97d235d.png)|                       |                       | …

(PC-8139) bouton réessayer avec timer sur la modale de saisie du code de vérification

---

src/features/auth/signup/SetPhoneValidationCodeModal.test.tsx
src/features/auth/signup/SetPhoneValidationCodeModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8135
I have:

(PC-8135) SetPhoneValidationCode: dismiss modal on navigate to TooManyAttempts

---

scripts/update_app_version.sh

```
INFO [2021-05-27 17:06:21.37]: Updating track 'internal'...
INFO [2021-05-27 17:06:21.67]: Uploading all changes to Google Play...
WARN [2021-05-27 17:06:22.20]: Lane Context:
INFO [2021-05-27 17:06:22.20]: {:ENVIRONMENT=>"production", :PLATFORM_NAME=>:android, :LANE_NAME=>"android deploy", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/home/circleci/pass-culture/android/app/build/outputs/apk/production/release/app-production-release.apk"], :GRADLE_ALL_AAB_OUTPUT_PATHS=>[], :GRADLE_ALL_OUTPUT_JSON_OUTPUT_PATHS=>["/home/circleci/pass-culture/android/app/build/outputs/apk/production/release/output.json"], :GRADLE_ALL_MAPPING_TXT_OUTPUT_PATHS=>[], :GRADLE_APK_OUTPUT_PATH=>"/home/circleci/pass-culture/android/app/build/outputs/apk/production/release/app-production-release.apk", …
```

Make sure versionCode is striclty increasing

---

__mocks__/react-native-geolocation-service.ts
src/features/favorites/pages/FavoritesSorts.tsx
src/features/favorites/pages/__tests__/FavoritesSorts.test.tsx
src/features/favorites/pages/__tests__/__snapshots__/FavoritesSorts.test.tsx.snap
src/features/profile/pages/Profile.test.tsx
src/features/profile/pages/Profile.tsx
src/features/search/pages/LocationFilter.tsx
src/features/search/pages/__tests__/LocationFilter.test.tsx
src/features/search/pages/__tests__/__snapshots__/LocationFilter.test.tsx.snap
src/libs/geolocation/GeolocationWrapper.tsx
src/libs/geolocation/getPosition.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9110
I have:

(PC-9110) Affichage d'un message d'erreur custom selon l'erreur de géoloc

---

ios/Podfile.lock
package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9332
Instructions for XCode installation : 
1. Install XCode 12.5 (go to app store to see the update)
2. Launch XCode which will ask you to download and install additional components
3. `cd ios & bundle exec pod install` to update ios dependencies
I have:
|                      |                          |  

(PC-9332) Update lottie-react-native for RN 0.64 and XCode 12.5 compatibility

---

src/features/bookings/components/OnGoingBookingsList.tsx

The banner was displayed but underneath the TabBar.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10118284/121923433-37ed5f80-cd3b-11eb-8bb1-39858a622602.png) | ![image](https://user-images.githubusercontent.com/10118284/121923349-2015db80-cd3b-11eb-9949-c5319e9b315f.png) |

(Booking) Update Booking footer when new props

---

.circleci/config.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9384
I have:

(PC-9384) App Native - Build hard testing à chaque master merge

---

src/features/profile/pages/Profile.tsx
src/libs/appState.ts
src/libs/geolocation/GeolocationWrapper.ios.test.tsx
src/libs/geolocation/GeolocationWrapper.tsx
src/libs/geolocation/getPosition.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9110
I have:

(PC-9110) Ne pas afficher la modale système pour demander la permission géoloc si celle-ci est désactivée de manière globale

---

__mocks__/fragmentMock.ts
jest/jest.setup.ts
package.json
yarn.lock

(Tech) undo jest-mock-canvas-test-utils

---

src/features/home/contentful/processHomepageEntry.test.ts
src/features/home/contentful/processHomepageEntry.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9975
I have:
Contentful précise que les modules non publiés ne sont pas listés dans la réponse. Ce qui n'est pas le cas 😡
Au lieu d'avoir un module complet avec les champs `sys` et `fields`, on a que `sys`.. Example:
Sous-module publié:
```json
"additionalAlgoliaParameters": [
{
"metadata": { "tags": [] },
"sys": {
"space": { "sys": { "type": "Link", "linkType": "Space", "id": "2bg01iqy0isv" } },
"id": "XSfVIg1577cOcs23K6m3n",
"type": "Entry",
"createdAt": "2020-11-12T11:10:41.542Z",
"updatedAt": "2021-07-07T08:53:35.350Z",
"environment": {
"sys": { "id": "testing", "type": "Link", "linkType": "Environment" }
},
"revision": 35,
"contentType": {
"sys": { "type": "Link", "linkType": "ContentType", "id": "algoliaParameters" } …
```

(PC-9975) Page d'Accueil - Empêcher les regressions contentful

---

src/features/home/atoms/OfferTile.tsx
src/features/home/components/ExclusivityModule.tsx
src/features/offer/atoms/OfferSeeMore.tsx
src/features/offer/components/OfferHero.tsx
src/features/search/atoms/OfferImage.tsx

I have:
After debugging with why-did-you-render on https://github.com/pass-culture/pass-culture-app-native/blob/f7d4077d48c1987c86bc8e05efccb884bd8d266e/src/why-did-you-render.js#L7, we can see that the home renders many times on load (due to the skeletons).
The props to FastImages (algolia modules) that are objects changes (like `source` or `style`) which means that those images re-renders.
To avoid that, we memoize those props.

(PC-9844) Make sure the FastImages are not re-rendered too often [Perf]

---

__snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
src/features/bookings/api/__tests__/queries.test.ts
src/features/bookings/api/queries.ts
src/features/bookings/pages/BookingDetails.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10050
I have:
When we access the details of a booking without going to the bookings page first, the hook `useBookings` was not called. Thus the hook `useOngoingOrEndedBooking` returned `undefined` which caused a blank page.
Now, we make sure to call `useBookings` inside the hook `useOngoingOrEndedBooking`.
Furthermore, to prevent calling `/native/v1/bookings` too often, we cache the result using react-query's `staleTime`. To do that, we have to make sure we invalidate the cache when needed (ex: when booking a reservation).

(PC-10050) See BookingDetails without crashing

---

src/features/bookOffer/components/Calendar/Calendar.tsx
src/features/bookOffer/components/Calendar/DayComponent.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8273
I have:
| \*iOS  | \*Android  | 
| -------------------- | ---------------------- | 
| ![ios](https://user-images.githubusercontent.com/10118284/126347066-c109143d-4170-4ed2-8384-d67c6f9ab91b.png) | ![android](https://user-images.githubusercontent.com/10118284/126347156-cb16e816-6374-4a3d-abc2-fdd611f6428c.png) |
For Android, the touchable area is in green.
For iOS, it's the green area + a "padding" of 8 in each direction due to the `hitSlop`.

(PC-8273) Make touchable area when selecting day for Android

---

README.md

There are several errors in the readme, in the 'Build the app' section about Sentry.
First you can build the app without the sentry step.
Second the command `yarn sentry:configure` does not exist anymore.
Third, there are no available token on my sentry account.

Doc: remove outdated sentry section from readme

---

src/features/deeplinks/routing.ts
src/features/navigation/RootNavigator/routes.web.tsx
src/features/navigation/screenParamsParser.ts

(PC-10260) Use screen name instead of "path" as key of screenParamsParser

---

__snapshots__/libs/recaptcha/ReCaptcha.native.test.tsx.native-snap
jest/jest.setup.ts
src/features/cheatcodes/pages/Navigation/Navigation.tsx
src/features/deeplinks/analytics.test.ts
src/features/deeplinks/pages/DeeplinkImporter.native.test.tsx
src/features/deeplinks/useDeeplinkUrlHandler.test.ts
src/features/deeplinks/useDeeplinkUrlHandler.ts
src/features/deeplinks/utils.test.ts
src/features/deeplinks/utils.ts
src/features/navigation/__tests__/helpers.test.ts
src/features/offer/components/__tests__/OfferHeader.native.test.tsx
src/features/offer/components/__tests__/OfferHeader.web.test.tsx
src/features/offer/services/useShareOffer.ts
src/features/venue/components/__tests__/VenueHeader.native.test.tsx
src/features/venue/services/useShareVenue.ts
src/libs/environment/__mocks__/useWebAppUrl.ts

(PC-10260) Use dynamic webapp url in generateLongFirebaseDynamicLink()

---

src/features/offer/pages/OfferBody.tsx
src/features/offer/services/useReasonsForReporting.ts

I have:
La page de détail de l'offre ne peut pas s'afficher et affiche 'Oops' car les appels aux routes /native/v1/offers/reports et /native/v1/offers/reports/reasons échouent (réponse 401).
Il semble que cela arrive lorsque l'app est inactive pendant au moins 15 minutes (délai d'expiration du token d'authentification). Au retour sur l'app sur la page de détail de l'offre, les appels aux routes sont renouvelés, or le token est expiré. Après l'appel à la route /native/v1/refresh_access_token, les appels à reports et reports/reasons ne sont pas à nouveau exécutés ce qui provoque le crash de la page de détail de l'offre.
L'utilisation du paramètre `retry: true` dans useQuery permet de forcer le renouvellement des appels si le dernier appel a échoué (par défaut les appels qui échouent sont …

fix report offer request crash

---

src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.native.test.tsx
src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10494
I have:

(PC-10494) App Native - FrontEnd - Corriger le delai entre l appel au getProfile et le call backend sessionId

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9998
```bash
$ react-native start --reset-cache
error ENOENT: no such file or directory, stat '/Users/agarcia/passculture/pass-culture-app-native/node_modules/@babel/plugin-transform-react-jsx-source/node_modules/semver/bin/semver'.
Error: ENOENT: no such file or directory, stat '/Users/agarcia/passculture/pass-culture-app-native/node_modules/@babel/plugin-transform-react-jsx-source/node_modules/semver/bin/semver'
at statSync (fs.js:1016:3)
at /Users/agarcia/passculture/pass-culture-app-native/metro.config.js:43:26
at Array.forEach (<anonymous>)
at findPackageDirs (/Users/agarcia/passculture/pass-culture-app-native/metro.config.js:34:28)
at /Users/agarcia/passculture/pass-culture-app-native/metro.config.js:63:9
at …
```

(PC-9998) Fix iOS build

---

src/features/search/utils/tests/sanitizeSearchStateParams.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10293
I have:

(PC-10293) improve sanitizeSearchStateParams readability

---

src/features/search/utils/sanitizeSearchStateParams.ts
src/features/search/utils/tests/sanitizeSearchStateParams.test.ts

Suite à l'ajout de la feature de sanitization des query params de search:
React Navigation 5 merge les `route.params`.
React Navigation 6 change ce comportement par un override et introduit un `{ merge: true }`
Source: https://reactnavigation.org/docs/params/#passing-params-to-a-previous-screen | https://reactnavigation.org/blog/2021/03/12/react-navigation-6.0-next/#highlights
Actuellement, si on set un `route.params`, à moins de le unset, re-naviguer vers `Search` qui autorise ces params à pour conséquence que les routes params se mergent.
Ce `route.params`, ensuite modifie le state ici : https://github.com/pass-culture/pass-culture-app-native/blob/master/src/features/search/pages/reducer.ts#L67
Donc la => https://github.com/pass-culture/pass-culture-app-native/blob/master/src/features/se …

(tech) do not sanitize geolocation when not provided

---

__snapshots__/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx.native-snap
__snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap
src/ui/components/GenericInfoPage.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9674
I have:

[pc-9674] Prevent info page from bouncing

---

__snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
__snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
src/features/offer/components/OfferHeader.tsx
src/features/offer/components/__tests__/OfferHeader.native.test.tsx
src/features/offer/components/__tests__/OfferHeader.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10560
I have:

(PC-10560) Offer - Add safeAreaTop inset to OfferHeader height (fix iPhone 11)

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10595
L'upgrade en v2.4.7 force le mode retention causant un rerender du hook et un bug.
Une autre version remplacera le hook par un hoc class component
I have:
- if you want an hard deployment of the testing …

(PC-10595) Upgrade @pass-culture/id-check to v2.4.7

---

src/features/deeplinks/utils.ts
src/features/offer/components/__tests__/OfferHeader.native.test.tsx
src/features/offer/services/useShareOffer.ts
src/features/venue/components/__tests__/VenueHeader.native.test.tsx
src/features/venue/services/useShareVenue.ts
src/libs/environment/__mocks__/useWebAppUrl.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10657
I have:
Voir la [résolution de bug](https://www.notion.so/passcultureapp/Fonction-de-partage-KO-les-liens-n-aboutissent-pas-l-offre-b141797ba4f342cb9fa169b2f1a121f9)
Sur le master de la 148 (et donc en prod actuellement, voir ticket), un lien ressemble à ça:
- https://passcultureapp.page.link/?link=https://web.passculture.app/offer?id=13899281&apn=app.passculture.webapp&isi=1557887412&ibi=app.passculture&efr=1&ofl=https://web.passculture.app/accueil/details/2QLBC
- soit `${FDL_prefix}/?link=${active_webapp_domain}/${screen}?${universalLinkParams}&${FDL_parameters}`
- d'où la combinaison de "web.passculture.app/offer?id=13899281" qui n'a …

(PC-10657) Correction du bug en prod de partage d'offre

---

src/features/deeplinks/utils.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10657
> `efr`: If set to '1', skip the app preview page when the Dynamic Link is opened, and instead redirect to the app or store. The app preview page (enabled by default) can more reliably send users to the most appropriate destination when they open Dynamic Links in apps; however, if you expect a Dynamic Link to be opened only in apps that can open Dynamic Links reliably without this page, you can disable it with this parameter. This parameter will affect the behavior of the Dynamic Link only on iOS.
Source: https://firebase.google.com/docs/dynamic-links/create-manually
I have:

(PC-10657) FDL: skip preview page by default

---

src/features/auth/login/Login.tsx

Bots can easily use 429 status codes which are standard to know there is too many attempts going on for trying to signin.
Instead we would like to be more discreet and use an error code

Add signin error code instead of using status code

---

src/features/search/utils/tests/useNavigateToSearchResults.test.ts
src/features/search/utils/useNavigateToSearchResults.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8393
I have:

(PC-8393) Bug fix: Les filtres d'une précédente recherche restent activés lorsque j'explore les offres depuis les favoris

---

__snapshots__/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx.native-snap
__snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap
__snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.web-snap
src/features/auth/components/QuitSignupModal.tsx
src/ui/components/GenericInfoPage.tsx
src/ui/components/modals/AppFullPageModal.tsx

Suite au fix sur le back btn, j'ai modifié le comportement de la generic page en ayant vérifié au préalable son utilisation, unique pour cette modal d'abandon. J'ai visiblement fait ce check sur le workspace id check car je n'avais vu que un usage.
J'ai donc rajouté la `props.flex` pour conserver le comportement defaut et le comportement voulu par le fix.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10699
I have:
|                      |                          |                       | …

(PC-10699) Try another fix for back button and preserving GenericPage

---

src/features/search/pages/Search.tsx
src/features/search/pages/__tests__/Search.native.test.tsx
src/features/search/pages/__tests__/reducer.test.ts
src/features/search/pages/reducer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10484
I have:

(PC-10484) Search Reducer - renommer action INIT_FROM_SEE_MORE en SET_STATE_FROM_NAVIGATE

---

src/features/bookings/components/NoBookingsView.test.tsx
src/features/favorites/components/__tests__/NoFavoritesResult.test.tsx
src/features/home/components/OffersModule.tsx
src/features/navigation/TabBar/helpers.ts
src/features/navigation/TabBar/types.ts
src/features/navigation/helpers.ts
src/features/offer/components/OfferHeader.tsx
src/features/search/components/SearchBox.tsx
src/features/search/components/__tests__/SearchBox.test.tsx
src/features/search/pages/LocationFilter.tsx
src/features/search/pages/SearchWrapper.tsx
src/features/search/pages/SuggestedPlaces.tsx
src/features/search/utils/tests/useNavigateToSearchResults.test.ts
src/features/search/utils/useNavigateToSearchResults.ts
src/features/venue/components/VenueHeader.tsx
src/features/venue/components/VenueOffers.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10549
I have:

(PC-10549) Use nested navigate config for Search screen to avoid missing screen issue on web after reload

---

src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx
src/features/auth/signup/PhoneValidation/tests/SetPhoneNumber.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10745
I have:

[PC-10745] add new error page to setPhoneNumber

---

src/features/deeplinks/getScreenFromDeeplink.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10796
Description : 
- Il se trouve que lorsqu'on choisi le deeplink associé à un autre onglet que `Home`, il a y plusieurs routes dans le state, et notamment Home en premier. Il faut donc choisir la dernière route au lieu de la première.
I have:

(PC-10796) Custom deeplink listener : fix get of current nested route

---

src/features/auth/signup/SetEmail/SetEmail.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10598
I have:
No screenshot needed
[PC-10598]: https://passculture.atlassian.net/browse/PC-10598

[PC-10598][FIX] add TouchableOpacity to the checkbox

---

__snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap
src/features/home/components/HomeBody.tsx
src/features/home/components/HomeHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10403
I have:
| \*iOS - [iPhone 6] | \*Android - [s9] | Web - [Chrome] | Little - [Phone name] |
| ![image](https://user-images.githubusercontent.com/77674046/133761677-ddb86273-fd9f-49d0-8440-e004803a6d5c.png) | ![image](https://user-images.githubusercontent.com/77674046/133760774-945d9f21-e6df-4ef8-80c8-b2838ef648fc.png) | ![image](https://user-images.githubusercontent.com/77674046/133760652-3f2dda2c-7734-4b55-9a10-769fb69bc747.png) |                       |
If native code (ios/android) was modified, **after** the PR is merged, on the master …

(PC-10403) Home - Image principal mal positionné sur le Web

---

src/features/home/components/OffersModule.tsx
src/features/home/selectPlaylist.ts
src/features/offer/services/useCtaWordingAndAction.ts
src/features/profile/utils.ts
src/features/search/pages/SearchWrapper.tsx
src/features/search/pages/reducer.ts
src/features/search/pages/useSearchResults.ts
src/features/search/sections/Category.tsx
src/features/search/types.ts
src/features/search/utils/useAvailableCategories.ts
src/libs/algolia/fetchAlgolia/fetchAlgolia.ts
src/libs/algolia/types.ts
src/libs/search/fetch/search.ts
src/libs/search/filters/buildFacetFilters.ts
src/libs/search/filters/buildNumericFilters.ts
src/libs/search/filters/index.ts
src/libs/search/useParseSearchParameters.ts
src/libs/search/utils/filterAvailableCategories.ts
src/libs/search/utils/getCategoriesFacetFilters.ts
src/libs/search/utils/index.ts
src/libs/search/utils/tests/filterAvailableCategories.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10934
I have:
**Bugs** 🐛
Plusieurs bugs corrigés dans cette PR (depuis master):
- https://github.com/pass-culture/pass-culture-app-native/pull/1687/commits/23d1499a85170b1956f3593951cdb20120b40f17: Quand on clique sur le bouton "Voir plus" d'une playlist de la home:
- la pagination affiche des pages de `hitsPerPage` configurée dans contentful (donc par exemple par pages de 2)
- la catégorie choisie ne correspond pas à la catégorie du premier module affichée.
- https://github.com/pass-culture/pass-culture-app-native/pull/1687/commits/529ceb76892091a864c62d09542eba56d334b98c: le filtre par catégories dans la page de recherche ne fonctionnait pas (utilisation des labels au lieu des facetFilters)
- …

(PC-10934) Optimisation des requêtes de la page de recherche

---

__snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
__snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
__snapshots__/features/errors/pages/tests/AsyncErrorBoundary.native.test.tsx.native-snap
__snapshots__/features/errors/pages/tests/AsyncErrorBoundary.web.test.tsx.web-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
__snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap
public/index.html
src/ui/theme/typography.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10839
Test with the URL : http://localhost:3000/first-tutorial?shouldCloseAppOnBackAction=true
I have:
| \*Chrome - [Desktop] | \*Firefox - [Desktop] | Safari - [Desktop] |
| -------------------- | :----------------------: | --------------------: |
|<img width="1920" alt="Schermata 2021-09-21 alle 11 59 58" src="https://user-images.githubusercontent.com/90036171/134151900-ff4fda0d-6924-4102-a94c-8527c0bce580.png">|<img width="1920" alt="Schermata 2021-09-21 alle 12 00 13" src="https://user-images.githubusercontent.com/90036171/134151941-40a7789c-8fc8-4bc1-ade3-0196f3ad51b1.png">|<img width="1920" alt="Schermata 2021-09-21 alle 12 00 27" …

[PC-10839][FIX] App Native - Decli Web - Regler les fonts sur Firefox (ex: Page d'erreur 404)

---

src/features/auth/signup/NextBeneficiaryStep/tests/NextBeneficiaryStep.native.test.tsx

Remove warning:
```
●  Cannot log after tests are done. Did you forget to wait for something async in your test?
Attempted to log "Warning: An update to NextBeneficiaryStep inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
act(() => {
/* fire events that update state */
});
/* assert on the output */
This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
at NextBeneficiaryStep (/home/circleci/pass-culture/src/features/auth/signup/NextBeneficiaryStep/NextBeneficiaryStep.tsx:8:62)
at QueryClientProvider (/home/circleci/pass-culture/node_modules/react-query/lib/react/QueryClientProvider.js:41:22)
at I18nProvider …
```

(Tech) remove warning for NextBeneficiaryStep

---

__snapshots__/features/favorites/pages/__tests__/Favorites.native.test.tsx.native-snap
src/features/favorites/atoms/BicolorFavoriteCount.tsx
src/features/favorites/components/FavoritesResults.tsx
src/features/favorites/pages/Favorites.tsx
src/features/favorites/pages/__tests__/useFavorites.test.tsx
src/features/favorites/pages/useFavorites.ts
src/features/offer/pages/OfferBody.tsx
src/features/offer/services/useReportedOffers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9254
I have:
Chemin:
- chargement de l'application (en étant connecté)
- visite de la page des favoris
- visite d'une page de détail d'une offre favoris
- visite de la recherche
- ajout en favoris d'une offre
- visite de la page des favoris
- suppression d'une offre favoris
Voici  toutes les requêtes sur ce chemin utilisateurs effectuées à `/me/favorites` (POST/GET/DELETE inclus):
=> Au total sur ce chemin, on évite 6 requêtes inutiles.

(PC-9254) Réduction du nombre de requêtes - Favoris

---

src/features/auth/signup/SetEmail/SetEmail.tsx
src/ui/components/inputs/CheckboxInput.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10598
I have:
| \*Web - [Phone name] | \*Android - [Phone name] | Tablet - [Phone name] | Little - [Phone name] |
|  ![image](https://user-images.githubusercontent.com/77674046/134371026-1c4a0166-e860-4fce-8aa1-40b7784fb04e.png)  |                          |                       |                       |

(PC-10598) Fix checkbox included in touchable opacity on setpassword

---

ios/Podfile.lock
src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.tsx
src/libs/trackingConsent/useTrackingConsent.ts

Voir issue https://github.com/mrousavy/react-native-tracking-transparency/issues/15
La popup ATT ne s'affiche plus pour les iOS 15 d'elle-même. On l'affiche maintenant après avoir accepté/refusé le contenu du modal sur la Privacy.

Show ATT pop-up for iOS 15

---

__snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
__snapshots__/features/venue/components/__tests__/VenueOffers.test.tsx.native-snap
__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
src/features/favorites/atoms/Favorite.tsx
src/features/home/atoms/OfferTile.tsx
src/features/home/atoms/tests/OfferTile.native.test.tsx
src/features/home/atoms/tests/OfferTile.web.test.tsx
src/features/home/components/OffersModule.tsx
src/features/home/components/RecommendationModule.tsx
src/features/search/atoms/Hit.tsx
src/features/search/types.ts
src/features/venue/atoms/VenueOfferTile.tsx
src/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx
src/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx
src/features/venue/components/VenueOffers.tsx
src/features/venue/components/__tests__/VenueOffers.test.tsx
src/features/venue/fixtures/venueOffersResponseSnap.ts
src/libs/algolia/algolia.d.ts
src/libs/algolia/mockedResponses/mockedAlgoliaResponse.ts
src/libs/search/filters/buildBoosts.ts
src/libs/search/filters/buildQueryOptions.ts
src/libs/search/filters/buildVenuesQueryOptions.ts
src/libs/search/filters/constants.ts
src/libs/search/filters/tests/buildBoosts.test.ts
src/libs/search/utils/buildAlgoliaHit.ts
src/types/@elastic/app-search-javascript/index.d.ts

-  https://github.com/pass-culture/pass-culture-app-native/pull/1716/commits/ae212996d1ac65c40d240de0b249dccb74bc1e5e: on n'utilise pas le champ `description` qui provient d'Algolia/AppSearch. Par conséquent, on peut l'enlever des champs récupérés. Impact léger et principalement sur les données transférées  via l'appel réseau. Ça permet aussi de se préparer au moment éventuel où le champ description ne sera plus indexé sur AppSearch.
- https://github.com/pass-culture/pass-culture-app-native/pull/1716/commits/251a3617dc48b2200713f5774b1f7180603e11a5 : Impact conséquent sur les temps de requêtes à ElasticSearch. Par exemple pour les playlist non géolocalisées de la home, on appliquait un boost par proximité si l'utilisateur avec sa geoloc activée. Ceci entraine un calcul de la distance …

[Tech] Performance improvement for AppSearch

---

src/features/forceUpdate/ForceUpdate.tsx

(PC-10931) Added redirect to home when refreshing succeed

---

src/features/forceUpdate/ForceUpdate.tsx

This reverts commit fcf4d810c07a4a2848a520fbbef428182b3dbdb7.
I have:
190

Revert "(PC-10931) Added redirect to home when refreshing succeed"

---

patches/react-native-web+0.17.1.patch
src/ui/components/hero/HeroHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11070
Added tweak of react-native-web `Image` component until https://github.com/necolas/react-native-web/issues/2139 is resolved.
- `props.transform` : apply transform to `<img />` styles.
I have:
| \*Web - [avant] | \*Web - [Après] | Tablet - [Phone name] | Little - [Phone name] |
| ![image](https://user-images.githubusercontent.com/77674046/134939303-78fd2d31-a957-44f8-ac9b-702f18091acc.png) | ![image](https://user-images.githubusercontent.com/77674046/134939173-06c8f1f3-9c34-4f9c-b777-804efa4ffde1.png) |                       | …

(PC-11070) Tweak react-native-web Image component to support css transformation (Offer/Venue)

---

src/ui/components/ModuleBanner/ModuleBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10546
I have:
| \*Chrome - [Desktop] | \*Chrome - [Small] |
|<img width="1920" alt="Schermata 2021-09-27 alle 17 19 04" src="https://user-images.githubusercontent.com/90036171/134938153-a6addaed-af6b-490f-80c2-09939ca4a412.png">|<img width="500" alt="Schermata 2021-09-27 alle 17 19 13" src="https://user-images.githubusercontent.com/90036171/134938194-4ea7dbe1-4593-4755-a803-99e4b2e76dd9.png">| …

(PC-10546) App Native - Decli Web - Page Profile - Pas d'espace après "300€" sur la bannière

---

src/libs/geolocation/getPosition.ts
src/libs/geolocation/getPosition.web.ts

Beaucoup de logs sur les erreurs lié à la position. On a eu l'information, si on veut l'analyser, on peut.
On va éviter de flooder sentry avec ces messages maintenant.

(Tech) clean sentry from geoloc related logs

---

src/features/bookings/components/EndedBookingItem.native.test.tsx
src/features/bookings/components/EndedBookingItem.tsx
src/features/bookings/components/EndedBookingItem.web.test.tsx
src/features/bookings/pages/BookingDetails.tsx
src/features/bookings/pages/EndedBookings.test.tsx
src/features/favorites/atoms/Favorite.tsx

The goal of this PR is to make sure we have the same behaviour when we go to the page OfferDetails:
- analytics event `ConsultOffer` triggered
- no blank page => pre-caching the offer response (image, name, etc...)

[UX - Analytics] Uniformise transition to Offer details page

---

src/features/auth/signup/AcceptCgu.native.test.tsx
src/features/navigation/helpers.ts
src/libs/itinerary/useItinerary.ts
src/ui/components/contact/helpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11104
I have:

(PC-11104) Fix openExternalUrl() on some androids by not relying on canOpenURL()

---

__snapshots__/features/profile/components/ProfileBadge.native.test.tsx.native-snap
src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
src/features/profile/components/IdCheckProcessingBadge.tsx
src/features/profile/components/NonBeneficiaryHeader.tsx
src/features/profile/components/ProfileBadge.native.test.tsx
src/features/profile/components/ProfileBadge.tsx
src/features/profile/components/YoungerBadge.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10972
I have:
|<img width="357" alt="Capture d’écran 2021-10-05 à 11 53 36" src="https://user-images.githubusercontent.com/44037911/136001938-e2f8d2da-53fb-40d5-8bb5-2d6a2dea86e6.png">  |       <img width="338" alt="Capture d’écran 2021-10-05 à 15 07 56" src="https://user-images.githubusercontent.com/44037911/136028978-173ad48b-8fbd-405f-a511-cb4e856fb90b.png">  |                 |          <img width="495" alt="Capture d’écran 2021-10-05 à 11 58 36" src="https://user-images.githubusercontent.com/44037911/136002142-a20cb967-f86d-403a-a477-565553dcac6b.png">        | …

[PC-10972] Allow ProfileBadge to show no icon

---

package.json
src/features/auth/signup/IdCheckV2.tsx
src/features/auth/signup/useBeneficiaryValidationNavigation.test.ts
src/features/auth/signup/useBeneficiaryValidationNavigation.ts
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10886
- (PC-10886) Upgrade `@pass-culture/id-check` to `v2.6.0` (added `initialStep`) [(PR)](https://github.com/pass-culture/id-check-front/pull/227)
- (PC-10886) Added `BeneficiaryValidationStep.BeneficiaryInformation` as a valid `nextStep` to enter id-check
We should update our `api.ts` first and rebase here in order to fix `ci/circleci: test-lint-and-types` GitHub check
I have:

(PC-10886) Added BeneficiaryValidationStep.BeneficiaryInformation as a valid nextStep to enter idCheck

---

src/features/navigation/RootNavigator/linking/getStateFromPath.ts
src/libs/analytics/analytics.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11022
I have:

(PC-11022) call setParams right after parsing to have correct  analytics when app is already open

---

src/libs/geolocation/checkGeolocPermission.web.ts
src/libs/geolocation/requestGeolocPermission.web.test.ts
src/libs/geolocation/requestGeolocPermission.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11100
I have:

(PC-11100) Safari fix : ask for geoloc when app starts

---

src/features/bookOffer/components/BookingDetails.tsx

Lorsque nous réservons depuis la page favoris, nous voyons un bandeau rouge snack bar avec l'erreur : 
```
TypeError: Cannot read properties of undefined (reading 'label')
at onSuccess (BookingDetails.tsx:53)
at Object.onSuccess (useBookOfferMutation.ts:19)
at mutation.js:86
BookingDetails.tsx:61 TypeError: Cannot read properties of undefined (reading 'label')
at onSuccess (BookingDetails.tsx:53)
at Object.onSuccess (useBookOfferMutation.ts:19)
at mutation.js:86
```
Pourtant la réservation est un succès.
Ça casse ici exactement : https://github.com/pass-culture/pass-culture-app-native/blob/master/src/features/bookOffer/components/BookingDetails.tsx#L53
N'ayant pas suivi le sujet des bookings, j'ai juste ignoré le category label de l'analytics si pas disponible.
Related to : …

(PC-10559) fix category booking details label

---

src/features/navigation/__tests__/helpers.test.ts
src/features/navigation/helpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11314
Bug introduced in https://github.com/pass-culture/pass-culture-app-native/pull/1811
I have:

[PC-11314] Fixing alert showing even when opening valid fallback link

---

src/features/auth/AuthContext.tsx
src/libs/jwt.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11249
I have:
When the user opens the application after 15minutes of inactivity (an access token is valid for 15mins by default), the apps:
- considers the user as `logged in`
- hence make calls to backend as logged in. This fails with error code 401:
Note: We have a retry mechanism on the app so the user doesn't actually see the error message.
But it's better to refresh the token before any call fi we know it's expired => that's what we do in this PR.
Note 2: I don't think the impact on the number of crash is significant. The cause is probably elsewhere.

[PC-11249] Perfs - Certains jeunes n'arrivent pas à charger l'application

---

src/App.tsx
src/api/apiHelpers.ts
src/libs/jwt.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10213
I have:
Quand le token est expiré et que l'appel à `refresh_token` échoue, la traceback est: 
(exactement comme cette [évènement Sentry](https://sentry.internal-passculture.app/organizations/sentry/issues/35/events/e3c08ce032b0429a85fb0f960ca857e0/?project=6&query=is%3Aunresolved))
```
WARN  undefined
ERROR  Unspecified error
This error is located at:
in SearchWrapper (at App.tsx:89)
in FavoritesWrapper (at App.tsx:88)
in GeolocationWrapper (at App.tsx:87)
in ErrorBoundary (at App.tsx:86)
in AuthWrapper (at App.tsx:85)
in QueryClientProvider (at App.tsx:84)
in RNCSafeAreaProvider (at SafeAreaContext.tsx:74)
in SafeAreaProvider (at App.tsx:83)
in ThemeProvider (at ThemeProvider.tsx:21)
in ThemeProvider (at App.tsx:82) …
```

(PC-10213) Investigation du crash de l'app au démarrage

---

src/features/home/api.ts

Reduce the number of calls from 15 to 1 when loading and processing the homepage from contentful.

(Perf) remember the processed homepage

---

__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx.native-snap
__snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.native-snap
src/ui/components/LayoutExpiredLink.tsx

I have:
| Avant : <img width="380" alt="Capture d’écran 2021-11-04 à 16 55 28" src="https://user-images.githubusercontent.com/62059034/140373781-4637ff2b-733f-4e4c-a63e-737d2b72411f.png">  Après: <img width="380" alt="Capture d’écran 2021-11-04 à 14 37 55" src="https://user-images.githubusercontent.com/62059034/140373528-6369c0f3-09d7-4ae1-bd7f-5e095ffeaed9.png">    |         |                 |                  |                  |

fix(Tech) LayoutExpired: use EmailFilled icon

---

package.json
src/App.web.tsx
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11509
This will fix tutorial and birthday cards on safar mobile ios 10 
I have:
| iOS | Android | Mobile - Safari | Mobile - Safari | Desktop - Safari |
|     |         | ![image](https://user-images.githubusercontent.com/77674046/140486197-a1a09796-45b9-4614-a5c0-f137e83d1b8a.png) | ![image](https://user-images.githubusercontent.com/77674046/140486417-7bc5ca43-4b66-4c83-ac37-d962cf8af2d5.png)  |                  |

(PC-11509) Using resize-observer-polyfill

---

src/features/profile/__mocks__/mutations.ts
src/features/profile/mutations.ts
src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11420
I have:
| ![image](https://user-images.githubusercontent.com/26742386/140526273-780826d4-4829-4d5b-8bab-cbe47daf397d.png) |         |                 |                  |                  |

[PC-11420] feat(changeEmail): handle errors according to mocked API responses

---

src/libs/geolocation/GeolocationWrapper.test.tsx
src/libs/geolocation/GeolocationWrapper.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11702
I have:

(PC-11702) Nullify user position when geoloc permission is rejected

---

src/features/auth/support.services.ts
src/features/bookings/components/BookingDetailsTicketContent.tsx
src/features/bookings/pages/BookingDetails.native.test.tsx
src/features/favorites/atoms/BookingButton.tsx
src/features/favorites/atoms/__tests__/BookingButton.test.tsx
src/features/navigation/__tests__/helpers.test.ts
src/features/navigation/helpers/openUrl.ts
src/libs/analytics/__mocks__/analytics.ts
src/libs/analytics/analytics.ts
src/ui/components/SocialNetworkCard.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11454
I have:

(PC-11454) add offer id to openExternalURL log

---

src/features/navigation/RootNavigator/linking/__tests__/getScreenPath.test.ts
src/features/navigation/RootNavigator/linking/__tests__/getStateFromPath.test.ts
src/features/navigation/TabBar/routes.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11752
Depuis la dernière mise en production, le `ForceUpdate` est affiché pour tout nos utilisateurs ayant une version inférieur à la version v1.158.1.
Dans cette version, la home supporte déjà `/home` et `/accueil`. Ce changement sera donc transparent pour la communication et les utilisateurs au niveau du partage du lien.
Cela permet également :
- En Web: de rediriger sur `/accueil` plutôt que `/home` 
I have:

(PC-11752) WebApp v2 - Path /home remplacé par /accueil

---

src/features/profile/pages/NotificationSettings.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11769
I have:
|     |         | ![image](https://user-images.githubusercontent.com/77674046/141434124-c6ed1ba0-c7a3-4c31-a855-98bab7a234a9.png) | ![image](https://user-images.githubusercontent.com/77674046/141434136-6efcdc98-8131-43e7-9259-12b8599dce94.png)|                  |

(PC-11769) Centrer le CTA sur la page Notification

---

package.json
src/api/apiHelpers.ts
src/libs/react-native-device-info/getUniqueId.ts
src/libs/react-native-device-info/getUniqueId.web.ts
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9623
J’ai créé une PR pour la stratégie avec identifiant navigateur unique (qui sera le même si on passe en incognito ou change de session google par exemple)
Avant de merger celui ci, est-ce que cela pourrait avoir des conséquences ? Par exemple, est-ce que coté back & ops le `device-id` est utilisé quelque part pour autre chose que du logging ?
On peut également imaginer renommer le header en `browser-unique-id`, par exemple.
| Actuellement | Avec browser fingerprint |
|![image](https://user-images.githubusercontent.com/77674046/141339038-d00880a2-5ab7-404b-92a2-f9bf62e818fa.png) |![image](https://user-images.githubusercontent.com/77674046/141339048-47482b8e-c0dc-4a73-8c23-cd4f31f59903.png)         |

(PC-9623) Stratégie header "unique-id" Web

---

__snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
__snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
src/features/offer/components/OfferHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11507
I have:
|     |         | ![image](https://user-images.githubusercontent.com/77674046/141762443-0fef6052-8ade-41e8-b4d3-505493a778ac.png) |                  |                  |

(PC-11507) OfferHeader - Text ellipsis title color forced to white

---

__snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
__snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap
src/features/offer/components/OfferHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11790
- Use two lines for `title` in `<OfferHeader />`
- Fix `text-overflow: ellipsis` by adding a `whiteSpace: 'pre-wrap'` on the WEB
I have:
| Desktop - Safari | Android | Mobile - Safari | Desktop - Chrome | Mobile - Chrome | 
| --: | ------: | --------------: | ---------------: | ---------------: | 
| ![image](https://user-images.githubusercontent.com/77674046/141776617-2aa3d210-614f-4d38-93d0-2da3fb3a48f8.png) | ![image](https://user-images.githubusercontent.com/77674046/141777722-7586c43c-ae5b-4141-8db6-198a2b2af3b2.png)          | ![image](https://user-images.githubusercontent.com/77674046/141776006-782b8d93-1e1f-414a-9aaa-c9375f15bbbc.png) | ![image](https://user-images.githubusercontent.com/77674046/141775659-63ec7ab …

PC-11790 fix(OfferHeader): Title on two lignes and fixed Safari title too long

---

.github/PULL_REQUEST_TEMPLATE.md
.github/pr-title-checker.test.ts
.github/workflows/pr-title-checker.yml
README.md
doc/standards/pr-title.md

In this PR:
- added github action to check on PR title
- Remove line from PR template (now automatic).
- added test to verify regex.
⚠  Make sure every PR title follows the following format:
```
<jira> <type>(<scope>): <short summary>
│       │      |             │
│       │      |             └─⫸ PR Summary: short summary of the Jira ticket title in English. Present tense.
│       │      |                  Not capitalized. No period at the end.
│       │      |
│       │      └─⫸ PR Scope: Hierarchical scope. Not capitalized, but snakeCase. For instance:
│       │           app, core, themeProvider... > identityCheck, eac, booking, search... > useSelectPlaylist...
│       │
│       └─⫸ PR Type: build, ci, docs, feat, fix, perf, refactor or test.
|            See …
```

ci(standards): add automated check on PR title

---

src/libs/react-native-batch.web.ts
src/service-worker.ts
src/web/utils/index.ts
src/web/utils/index.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11793
Testé sur MacOS et iPhone, le fix exclus l'initialisation de batch sdk safari, n'étant toujours pas supporté.
>  Concernant le push web Safari, il n'est pas (encore) supporté par Batch.
Nos équipes travaillent déjà sur ce sujet, les développements sont en cours et la sortie de ce nouveau canal aura lieu très prochainement.
I have:

(PC-11793) fix(BatchSDK): Safari is not yet supported, this commit will disable BatchSDK on Safari

---

src/features/deeplinks/utils.test.ts
src/features/deeplinks/utils.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11721
I have:
But :
au lieu de générer :
`https://passcultureapptesting.page.link/?link=https://app.testing.passculture.team/offre/3197?utm_campaign=rap_hiphop&utm_medium=email&utm_source=jeuconcours&apn=app.passculture.testing&isi=1557887412&ibi=app.passculture.test&efr=1&ofl=https://web.passculture.app/accueil/details/BR6Q`
, on génère (sera mieux parsé):
`https://passcultureapptesting.page.link/?link=https%3A%2F%2Fapp.testing.passculture.team%2Foffre%2F3197%3Futm_campaign%3Drap_hiphop%26utm_medium%3Demail%26utm_source%3Djeuconcours&apn=app.passculture.testing&isi=1557887412&ibi=app.passculture.test&efr=1&ofl=https://web.passculture.app/accueil/details/BR6Q`

(PC-11721) fix(dynamicLink): encode links in a long dynamic link

---

doc/standards/sentry.md

Learn how to generate your sentry auth token. This is mandatory if you are building for iOS.
I have:
Added:

docs(Sentry): add auth-token generation instruction

---

package.json
yarn.lock

Depuis master
```
84 vulnerabilities found - Packages audited: 4257
Severity: 4 Low | 55 Moderate | 23 High | 2 Critical
```
En enlevant `appcenter-cli`:
```
79 vulnerabilities found - Packages audited: 3999
Severity: 4 Low | 52 Moderate | 21 High | 2 Critical
```
En mettant à jour `react-native-code-push`:
```
73 vulnerabilities found - Packages audited: 4029
Severity: 3 Low | 50 Moderate | 20 High | 1 Critical
```
La plupart des autres erreurs (lancer `yarn audit --level high`) sont dues à `jest`, `react-dev-utils`, ou `webpack` et ses plugins, donc sont difficiles à màj.

build(secu): remove/upgrade breached libraries

---

src/features/identityCheck/pages/identification/IdentityCheckWebview.tsx
src/features/identityCheck/pages/identification/IdentityCheckWebview.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11727
I have:
```
➜  pass-culture-app-native git:(master) ✗ yarn build
yarn run v1.22.10
$ node web/scripts/build.js
Creating an optimized production build...
(node:45850) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Failed to compile.
./node_modules/react-native-webview/lib/WebView.js
SyntaxError: /Users/agarcia/passculture/pass-culture-app-native/node_modules/react-native-webview/lib/WebView.js: Support for the experimental syntax 'jsx' isn't currently enabled (7:37):
5 | // implementation which is produced by Expo SDK 37.0.0.1 implementation, with
6 | // similar interface than the native ones have.
>  7 | var WebView = function () { return (<View style={{
| …
```

(PC-11727) build(IdentityCheck): fix build on web

---

__snapshots__/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx.native-snap
src/features/bookOffer/components/BookingDetails.tsx
src/libs/parsers/getDisplayPrice.ts
src/libs/parsers/tests/getDisplayPrice.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11686
I have:

(PC-11686) fix(booking): Display 0€ when price is 0

---

__snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap
src/features/identityCheck/atoms/AddressOption.tsx
src/features/identityCheck/atoms/Declaration.tsx

Objectifs : 
* Avoir les villes / adresses qui s'affiche dans l'axe du code postal ou de l'adresse => Plus facile à lire 
* Centrer la page Honor sur décli-web
I have:
| <img width="429" alt="Capture d’écran 2021-11-30 à 12 02 42" src="https://user-images.githubusercontent.com/62059034/144035894-eab1141e-13c5-447b-973c-c7cb401efb2e.png">    |         |     <img width="1792" alt="Capture d’écran 2021-11-30 à 11 54 22" src="https://user-images.githubusercontent.com/62059034/144035943-125337a9-0d84-4913-9324-752a592c148e.png">    |                  |                  |
[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/do …

fix(identityCheck): Update design for Declaration and AddressOption

---

.circleci/config.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12128
I have:

(PC-12128) ci(Webapp): MES does not trigger MEP for webapp

---

src/libs/algolia/fetchAlgolia/AlgoliaError.ts

Too many errors due to Algolia on Sentry. To prevent the flood we stop sending them.

feat(AlgoliaError): stop sending algolia errors to sentry

---

__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.native.test.tsx.native-snap
src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11988
I have:
|<img width="386" alt="Schermata 2021-12-02 alle 09 51 39" src="https://user-images.githubusercontent.com/90036171/144389892-b3b1c090-8df7-45ff-8030-2cd9b0c64cfc.png">|<img width="338" alt="Schermata 2021-12-02 alle 09 49 08" src="https://user-images.githubusercontent.com/90036171/144390074-c5899658-7ca2-493d-95e2-c80b2a0681d8.png">| |<img width="1920" alt="Schermata 2021-12-02 alle 09 49 17" src="https://user-images.githubusercontent.com/90036171/144389951-3132d398-bec0-49f6-bace-fca2ce6558d6.png">|                  |
[1]: …

(PC-11988) fix(identityCheckEduConnect): Fix icon spacing

---

android/app/build.gradle

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12103
Error:
```
java.lang.RuntimeException: 
at android.app.ActivityThread.handleBindApplication (ActivityThread.java:7218)
at android.app.ActivityThread.access$2200 (ActivityThread.java:296)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2208)
at android.os.Handler.dispatchMessage (Handler.java:107)
at android.os.Looper.loop (Looper.java:213)
at android.app.ActivityThread.main (ActivityThread.java:8178)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1101)
Caused by: com.microsoft.codepush.react.CodePushUnknownException: 
at …
```

(PC-12103) fix(codepush): fix crash on android when no codepush

---

android/app/build.gradle
fastlane/.env.production
fastlane/.env.staging
fastlane/.env.testing
fastlane/Fastfile

Plusieurs ressources intéressantes:
- https://developer.android.com/studio/build/configure-apk-splits
- https://developer.android.com/guide/app-bundle
- https://developer.android.com/studio/build/shrink-code
- https://infinum.com/the-capsized-eight/optimize-app-delivery-with-android-app-bundles
Il y a plusieurs bonnes pratiques Android qu'on n'avait pas encore mis en place (jusqu'à cette PR: https://github.com/pass-culture/pass-culture-app-native/pull/2207).
Notamment:
- Code shrinking, Obfuscation & Optimisation avec Proguard: `minifyEnabled true`
- Resource shrinking: `shrinkResources true`
- Native crash support: upload des debug symbols pour débugger les crashs: `debugSymbolLevel 'FULL'`
Tout ça est fait dans cette PR: https://github.com/pass-culture/pass-culture-app-native/pull/2207 …

build(android): upload universal apk to appcenter

---

src/features/profile/pages/ConsentSettings.native.test.tsx
src/features/profile/pages/ConsentSettings.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12196
I have:

(PC-12196) feat(privacy): Consent settings page does not automatically enable tracking

---

src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
src/features/identityCheck/errors/eduConnect/EduConnectErrorBoundary.tsx
src/features/identityCheck/errors/eduConnect/types.ts
src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts
src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.tsx
src/libs/eduConnectClient.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11781
I have:

(PC-11781) feat(EduConnect): map not eligible error to error pages

---

src/features/smartBanner/SmartBanner.web.tsx
src/features/smartBanner/tests/SmartBanner.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12074
I have:

(PC-12074) fix(SmartBanner): disable react-smartbanner on the Web temporary

---

.eslintrc.js
__mocks__/lottie-react-native.tsx
jest.web.config.js
src/features/auth/signup/UserProfiling.web.test.tsx
src/features/auth/signup/underageSignup/SelectSchoolHome.tsx
src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx
src/libs/lottie/index.ts
src/libs/lottie/index.web.ts
src/ui/components/GenericInfoPage.tsx
src/ui/components/GenericInfoPageWhite.tsx
src/ui/components/LoadingPage.tsx
src/ui/components/achievements/components/GenericAchievementCard.tsx
src/ui/components/achievements/components/GenericAchievementCard.web.test.tsx
web/config/webpack.config.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12318
I have:

(PC-12318) fix(Lottie): suppression du webpack resolve alias

---

src/features/search/components/SearchBox.tsx
src/features/search/components/__tests__/SearchBox.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12306
I have:

(PC-12306) fix(searchbox): Stage query in state when typing it

---

src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12192
I have:

(PC-12192) fix(countryPicker): Make more room to country picker on desktop

---

__snapshots__/features/auth/signup/VerifyEligiblity/tests/NotYetUnderageEligibility.test.tsx.native-snap
__snapshots__/features/auth/signup/VerifyEligiblity/tests/NotYetUnderageEligibility.test.tsx.web-snap
src/libs/dates.test.ts
src/libs/dates.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11780
I have:

(PC-11780) feat(NotYetUnderageEligibility): handle different eligibility ages

---

__snapshots__/features/maintenance/tests/Maintenance.test.tsx.native-snap
__snapshots__/features/maintenance/tests/Maintenance.test.tsx.web-snap
src/features/cheatcodes/pages/Navigation/Navigation.tsx
src/features/errors/pages/ScreenErrorProvider.tsx
src/features/maintenance/Maintenance.tsx
src/features/maintenance/MaintenanceErrorPage.tsx
src/features/maintenance/tests/Maintenance.test.tsx
src/features/maintenance/useMaintenance.tsx
src/libs/firestore/__tests__/maintenance.native.test.ts
src/libs/firestore/maintenance.ts
src/libs/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12252
I have:
| iOS | Android | Mobile - Chrome | Desktop - Chrome | Desktop - Safari | Desktop Firefox
| --: | ------: | --------------: | ---------------: | ---------------: |--:
|  ![image](https://user-images.githubusercontent.com/95220086/146036021-6939bdda-539b-44b4-9456-22810606a3ac.png)   |         |                 |                  |                  |![image](https://user-images.githubusercontent.com/95220086/146036496-bf2c91ce-f116-4015-9203-1ec83d70980e.png)
J'aurais bien aimé pouvoir ajouter des tests …

(PC-12252) feat(maintenance): custom message in maintenance mode

---

src/features/auth/signup/SetBirthday/SetBirthday.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12358
I have:

(PC-12358) fix(setBirthday): use variable translation with nbsp

---

src/features/profile/pages/ChangeEmail/ChangeEmailExpiredLink.tsx
src/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11697
- ETQUtilisateur déconnecté, sur la page d'erreur de lien, quand je clique sur "Se connnecter", je suis redirigé vers le login, et quand je clique sur back, je reviens sur le message d’erreur
- ETQUtilisateur déconnecté, sur la page d'erreur de lien, quand je clique sur "Se connnecter", je suis redirigé vers le login, et quand je me connecte, je suis redirigé sur la page d’accueil (comportement standard de la page)
I have:
[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/sta …

(PC-11697) fix(changeEmailError): navigate to connection when logged out

---

src/features/identityCheck/pages/errors/EduConnectErrors.tsx
src/features/navigation/RootNavigator/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12341
I have:

(PC-12341) feat(EduConnectErrors): logout user

---

src/features/home/pages/Home.tsx

because removeClippedSubviews is true by default on Android
https://reactnative.dev/docs/flatlist#removeclippedsubviews
so when the user scrolls to the first child, the header isnt focused anymore (even if we still see it), so it is not rendered anymore
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12096
I have:
| -----: | ------: |
| ![Capture2](https://user-images.githubusercontent.com/26742386/146418808-972ded17-8cdd-46af-ba93-0fbcbc06e57f.gif) | ![Capture](https://user-images.githubusercontent.com/26742386/146419161-c47f832c-234f-4e69-b2f5-d3b27c5ce464.gif) |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6 …

(PC-12096) fix(home): header isnt removed when scrolling to first child

---

src/features/identityCheck/pages/profile/Status.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11901
**Desciption du bug**: le call à /subscription/profile plantait si on sélectionnait un statut autre que lycéen ou collégien
I have:

(PC-11901) fix(signup): make sure status is in context before patchProfile

---

src/features/bookOffer/components/Calendar/Calendar.utils.ts
src/features/bookOffer/components/__tests__/Calendar.utils.test.ts
src/features/search/components/CalendarPicker.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12044
I have:

(PC-12044) fix(mobileDatePicker): Disable choice for past dates

---

doc/development/localApi.md
src/features/identityCheck/pages/Stepper.tsx
src/features/identityCheck/useSetCurrentSubscriptionStep.ts
src/features/navigation/RootNavigator/identityCheckRoutes.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12378
I have:

(PC-12378) feat(signup): show maintenance page on stepper if nextSubscriptionStep is maintenance

---

__snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.native-snap
__snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.web-snap
eslint-custom-rules/nbsp-in-french-translations.js
src/locales/fr/messages.po
src/ui/components/LayoutExpiredLink.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12415
I have:

(PC-12415) fix(translations): replace space before » and after « with nbsp

---

web/config/webpack.config.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12412
I have:

(PC-12412) fix(Web): restore webpack alias for react-native-web-lottie

---

src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12412
I have:

(PC-12412) fix(IdentityCheckValidation): replace idcheck validation page with custom one

---

src/features/identityCheck/atoms/StepButton.tsx
src/features/identityCheck/atoms/__test__/StepButton.native.test.tsx
src/features/identityCheck/atoms/__test__/StepButton.web.test.tsx
src/features/identityCheck/pages/identification/IdentityCheckWebview.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12440
I have:
| avant | après |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10118284/146984286-35a160b4-7b35-48ba-8019-15d1cb92d2df.png) | ![image](https://user-images.githubusercontent.com/10118284/146984171-b4dace71-f070-4962-8c6e-f74c0c62ade0.png) |

(PC-12440) feat(identityCheck): disable steps that are completed

---

src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12453
Le `y` du bouton `Réessayer` était coupé
Reviewer, tu peux utiliser la branche `PC-12453-fix-cropped-button-easy-test` si tu veux tester
I have:
iOS
|avant|après|
|:--|:--|
|![image](https://user-images.githubusercontent.com/95220086/147077955-38ad15ca-be54-4c44-be46-f0d6c71b5f78.png)|![image](https://user-images.githubusercontent.com/95220086/147078074-5d819d70-d57b-4d94-856e-54ff5d252859.png)|
Firefox Desktop (le problème n'était pas présent, donc il n'y a pas de changement)
|avant|après|
|:--|:--|
|![image](https://user-images.githubusercontent.com/95220086/147077883-ac6905bd-7ede-4bfc-9ed3-6215b76cc551.png)|![image](https://user-images.githubusercontent.com/95220086/147078262-b7ed4960-a483-4bbb-b9a2-0e4578d24f0f.png …

(PC-12453) fix(phone): button was a bit cropped

---

ios/PassCulture/Info.plist

Le problème : Le parcours Ubble ne démarre pas car il est mal supporté sur les versions inférieures d'iOS14.5
Le fix : Selon Ubble, il faut ajouter la permission Microphone dans `Info.plist`
```
<key>NSMicrophoneUsageDescription</key>
<string>Video and Audio Recording</string>

fix(ubbleWebview): add NSMicrophoneUsageDescription

---

src/features/auth/AuthContext.tsx
src/features/auth/login/Login.native.test.tsx
src/features/auth/useResetContexts.ts

Link to JIRA tickets:
- https://passculture.atlassian.net/browse/PC-10783
- https://passculture.atlassian.net/browse/PC-12442
I have:

(PC-10783) fix(context): reset search and identityCheck context on login

---

.circleci/config.yml

To include the fix of a Log4Shell vulnerability (will be fixed at the upload with Xcode 13.2.1):
https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2_1-release-notes
Confirmed in this post, validated by Apple:
https://developer.apple.com/forums/thread/696785

ci(xcode): update used xcode version

---

src/features/auth/signup/SetBirthday/SetBirthday.tsx
src/features/auth/signup/underageSignup/SelectSchool.tsx
src/features/bookings/components/BookingDetailsCancelButton.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12428
I have:

(PC-12428) fix(translations): merge translation with nbsp and variable

---

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
src/features/search/sections/Location.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12500
I have:
|   <img width="282" alt="Capture d’écran 2021-12-24 à 15 30 18" src="https://user-images.githubusercontent.com/44037911/147359364-1ea1798b-42b8-408b-a488-53f18cf461f3.png">  |         |                 |                  |                  |

(PC-12500) fix(icons): add missing margin in search location filter

---

.circleci/config.yml
package.json

5m30 => moins de 4min
How:
- use CircleCi cache
- increase number of workers to 4.

ci(tests): improve time to run tests on ci

---

src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx
src/features/identityCheck/errors/eduConnect/NotEligibleEduConnect.tsx
src/libs/analytics/__mocks__/analytics.ts
src/libs/analytics/analytics.ts
src/libs/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12519
I have:

(PC-12519) feat(EAC): add tracker on go Back to home from educonnect error

---

__snapshots__/features/errors/pages/tests/AsyncErrorBoundary.native.test.tsx.native-snap
__snapshots__/features/favorites/pages/__tests__/FavoritesSorts.native.test.tsx.native-snap
__snapshots__/features/offer/pages/tests/OfferDescription.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
__snapshots__/features/profile/pages/PersonalData.native.test.tsx.native-snap
__snapshots__/features/search/pages/__tests__/Categories.test.tsx.native-snap
__snapshots__/features/search/pages/__tests__/LocationFilter.native.test.tsx.native-snap
__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
src/features/bookOffer/services/__tests__/useModalContent.test.tsx
src/features/bookOffer/services/useModalContent.tsx
src/features/cheatcodes/pages/AppComponents/Icons.tsx
src/features/errors/pages/AsyncErrorBoundary.tsx
src/features/offer/components/__mocks__/useReportOfferModalContent.tsx
src/features/offer/components/useReportOfferModalContent.tsx
src/ui/components/headers/PageHeader.tsx
src/ui/components/modals/ModalHeader.native.test.tsx
src/ui/components/modals/ModalHeader.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12535
I have:

(PC-12535) refactor(icons): replace back icons in headers

---

__snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
__snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
src/ui/components/achievements/components/GenericAchievementCard.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11951
I have:
| iOS | iOS | iOS | iOS | 
| --: | --: | --: | --: | 
|<img width="332" alt="Capture d’écran 2021-12-22 à 11 10 49" src="https://user-images.githubusercontent.com/90036171/147077103-ac1d3026-f765-4cde-b8b7-b7af779574e0.png">|<img width="332" alt="Capture d’écran 2021-12-22 à 11 10 57" src="https://user-images.githubusercontent.com/90036171/147076848-856173d5-356f-4a46-aa18-4b478dcb4441.png">|     <img width="331" alt="Capture d’écran 2021-12-22 à 11 11 05" src="https://user-images.githubusercontent.com/90036171/147076880-275b5e79-f63e-476a-bd7f-9cc3b79b9041.png">|<img width="330" alt="Capture d’écran 2021-12-22 à 11 11 12" src="https://user-images.githubusercontent.com/90036171/147076937-8d70838d-4eae-44 …

(PC-11951) fix(FirstTutorial): Fix GenericAchievementCard to fit the bottom button

---

src/features/auth/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx
src/features/auth/signup/AfterSignupEmailValidationBuffer/tests/AfterSignupEmailValidationBuffer.native.test.tsx
src/features/auth/signup/VerifyEligiblity/NotYetUnderageEligibility.tsx
src/features/auth/signup/VerifyEligiblity/tests/NotYetUnderageEligibility.test.tsx
src/features/cheatcodes/pages/Navigation/Navigation.tsx
src/features/navigation/RootNavigator/types.ts
src/libs/dates.test.ts
src/libs/dates.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12404
I have:
|     |         |                 |          
|                  |

(PC-12404) feat(NotYetUnderageEligibility): handle string date on nav

---

src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx
src/features/identityCheck/useIdentityCheckSteps.tsx
src/features/navigation/RootNavigator/identityCheckRoutes.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12454
PR qui renomme les path côté API https://github.com/pass-culture/pass-culture-main/pull/919
I have:

(PC-12454) refactor(routes): remove old idcheck/educonnect routes

---

__snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
__snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.native.test.tsx.native-snap
__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
__snapshots__/features/auth/login/Login.native.test.tsx.native-snap
__snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
__snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
__snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
__snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/components/__test__/DMSModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/components/__test__/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
__snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
__snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap
__snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
__snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
__snapshots__/ui/components/modals/AppModal.test.tsx.native-snap
__snapshots__/ui/components/modals/AppModal.test.tsx.web-snap
src/ui/components/modals/ModalHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12511
I have:
| Plateforme | Avant | Après |
| --- | --- | --- |
| Web | <img width="1081" alt="avant web" src="https://user-images.githubusercontent.com/10118284/148441490-643ff2e9-e8d9-492e-b473-45404070fe2b.png"> | <img width="1050" alt="après web" src="https://user-images.githubusercontent.com/10118284/148441497-6caa3a5f-4fda-4f5e-997f-ff55b431732b.png"> | 
| Mobile | <img width="343" alt="avant mobile" src="https://user-images.githubusercontent.com/10118284/148441546-6b9c9311-3650-4b99-82fa-4354187f0999.png"> | <img width="342" alt="après mobile" src="https://user-images.githubusercontent.com/10118284/148441563-c1d32a0f-3367-458e-96f9-5381824ade9c.png"> |
[1]: …

(PC-12511) feat(modal): increase modal header icons

---

src/libs/parsers/highlightLinks.tsx
src/libs/parsers/tests/highlightLinks.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9881
I have:
|Input coté Pro|Affichage Firefox Desktop (avant)|Affichage Firefox Desktop (après)|
|:--:|:--:|:--:|
|![image](https://user-images.githubusercontent.com/95220086/148574336-6e43b663-130c-4a09-be57-6ddd1a352dd2.png)|![image](https://user-images.githubusercontent.com/95220086/148575230-e4ce6152-a52c-4784-8401-186994205a65.png)|![image](https://user-images.githubusercontent.com/95220086/148574383-07e793ad-b273-4985-a238-6bcc553542ab.png)|

(PC-9881) feat(url): highlight URL even without http://

---

src/web/SupportedBrowsersGate.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12395
Testé sur messenger version iOS sur iPhone.
I have:

(PC-12395) fix(SupportedBrowsersGate): Add FacebookMessenger to supported browsers gate

---

__snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
src/features/offer/components/OfferPartialDescription.tsx
src/features/offer/components/__tests__/OfferPartialDescription.native.test.tsx
src/features/offer/components/__tests__/OfferPartialDescription.web.test.tsx
src/features/offer/components/useShouldDisplaySeeMoreButton.tsx
src/tests/utils.tsx
src/tests/utils/web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8471
I have:
| iOS description courte | iOS description longue | Firefox desktop (pas de changement) |
| :--: | :------: | :--------------: |
|![image](https://user-images.githubusercontent.com/95220086/147658087-cf8b5f86-f376-4a16-8716-6e14f3a5d065.png)|![image](https://user-images.githubusercontent.com/95220086/147658101-b8933500-ebde-44ab-9fea-5a496d0e6e8b.png)| ![image](https://user-images.githubusercontent.com/95220086/147657978-7df74848-7e79-44aa-85d5-9afe91aeb4b5.png)|

(PC-8471) feat(offer): hide see more button when description is small

---

src/features/cheatcodes/pages/AppComponents/Icons.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12709
I have:

(PC-12709) refactor(icons): update icon separation in cheatcodes

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12727
I have:

(PC-12727) fix(ReactNativeSreens): upgrade to 3.10.1 (latest) to remove console warning

---

src/libs/parsers/highlightLinks.tsx
src/libs/parsers/tests/highlightLinks.test.tsx

This reverts commit 93be2f4d54b5c66dbae2012d161ba6ecada7fee5.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9881
I have:
|     |         |  <img width="340" alt="Capture d’écran 2022-01-12 à 10 54 30" src="https://user-images.githubusercontent.com/62059034/149117884-37f54ba6-f86d-4a71-b099-c27c5721a797.png">    |                  |                  |

(PC-9881) feat(url): revert commit - highlight URL even without http:// 

---

src/features/landscapePosition/useIsLandscapePosition.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12596
I have:

(PC-12596) feat(LandscapePositionPage): do not sett landscape page when keyboard open

---

__snapshots__/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx.native-snap
__snapshots__/features/auth/signup/VerifyEligiblity/tests/NotYetUnderageEligibility.test.tsx.native-snap
__snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.native-snap
__snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap
__snapshots__/features/forceUpdate/__tests__/ForceUpdate.test.tsx.native-snap
__snapshots__/features/home/components/tests/NoContentError.native.test.tsx.native-snap
__snapshots__/features/identityCheck/components/__test__/QuitIdentityCheckModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/confirmation/__test__/BeneficiaryRequestSent.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEnd.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckPending.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckUnavailable.test.tsx.native-snap
__snapshots__/features/landscapePosition/tests/LandscapePositionPage.test.tsx.native-snap
__snapshots__/features/maintenance/tests/Maintenance.test.tsx.native-snap
__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ConfirmDeleteProfile.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfileSuccess.test.tsx.native-snap
__snapshots__/ui/components/__tests__/LayoutExpiredLink.test.tsx.native-snap
src/features/home/components/NoContentError.tsx
src/features/identityCheck/errors/eduConnect/NotEligibleEduConnect.tsx
src/ui/components/GenericInfoPage.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12063
I have:
|    ![image](https://user-images.githubusercontent.com/77674046/149192396-6c080d57-e8a2-4ef6-9ed9-ea63d75e1255.png)![image](https://user-images.githubusercontent.com/77674046/149192458-40a34c10-8226-43eb-9119-956053c1baad.png) |  ![image](https://user-images.githubusercontent.com/77674046/149190032-0ae2506a-891a-4682-a6ba-5e15426a4b75.png) ![image](https://user-images.githubusercontent.com/77674046/149190156-890c675b-2afc-4e94-8d25-b6bdc97a0204.png)      |   ![image](https://user-images.githubusercontent.com/77674046/149190306-3c2b36b9-278f-4a9e-b171-3ffbb6d58cd3.pn …

(PC-12063) fix(GenericInfoPage): remove custom text size in EduConnect errors

---

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
src/features/search/components/CalendarPicker.web.tsx
src/features/search/pages/SearchFilter.tsx
src/features/search/sections/OfferDate.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12044
I have:

(PC-12044) fix(CalendarWeb): no scroll on SearchFilter on Web mobile

---

src/features/identityCheck/pages/errors/EduConnectErrors.tsx
src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx
src/features/identityCheck/utils/logoutFromEduConnectIfAllowed.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12740
I have:

(PC-12740) fix(educonnect): call logout url on the web

---

src/features/offer/components/__tests__/OfferPartialDescription.native.test.tsx
src/features/offer/components/__tests__/OfferPartialDescription.web.test.tsx
src/features/offer/components/useShouldDisplaySeeMoreButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8471
I have:
|app description courte metada|app description longue|app description courte|
|:--:|:--:|:--:|
|![image](https://user-images.githubusercontent.com/95220086/148990162-90b7c757-7196-4283-9d6b-2af3807d2c41.png)|![image](https://user-images.githubusercontent.com/95220086/148990881-b8458e6a-8730-44a6-aed8-d48f3905e081.png)|![image](https://user-images.githubusercontent.com/95220086/148991012-09ab6209-25fb-4178-899f-b0f3d0a569d8.png)|
|web mobile description courte metada|web mobile description longue|web mobile description courte|
|:--:|:--:|:--:|
|![image](https://user-images.githubusercontent.com/95220086/148991071-8d35d056-3e77-4b65-93c4-81e69f45b308.png)|![image](https://user-images.githubusercontent.com/95220086/ …

(PC-8471) fix(offer): display see more with small description and image

---

__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnect.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckEduConnectForm.web.test.tsx.web-snap
src/features/identityCheck/pages/identification/IdentityCheckEduConnect.tsx
src/features/identityCheck/pages/identification/IdentityCheckEduConnectForm.web.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12805
I have:
|     |         |                 |        <img width="686" alt="Capture d’écran 2022-01-14 à 10 23 28" src="https://user-images.githubusercontent.com/44037911/149491483-4fe6fce7-c440-4104-91e1-e97530b3e407.png">          |                  |

(PC-12805) feat(EduConnect): clarify wording for blocked users on the web

---

src/libs/parsers/highlightLinks.tsx
src/libs/parsers/tests/highlightLinks.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9881
I have:
| Avant | Arpès |
| ![image](https://user-images.githubusercontent.com/95220086/149792974-2b2ec4b9-91c3-4a39-a7b9-b703375e52f6.png) |![image](https://user-images.githubusercontent.com/95220086/149793010-9601f50c-9700-4f4a-90b2-bc587ccee1a5.png) |

(PC-9881) fix(url): can have 1 URL per line

---

__snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap
__snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap
__snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap
src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.tsx
src/ui/components/achievements/components/GenericAchievementCard.tsx
src/ui/theme/grid.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12581
I have:
| iOS iPhone SE | Android Pixel 5 | Mobile - Chrome | Desktop - Chrome (Résolution: 1566 x 768) | Desktop - Safari |
|<img width="366" alt="Capture d’écran 2022-01-18 à 09 28 51" src="https://user-images.githubusercontent.com/90036171/149899487-42985edf-575b-4bef-b0a5-ae84485d49c9.png">|<img width="385" alt="Capture d’écran 2022-01-18 à 09 24 55" src="https://user-images.githubusercontent.com/90036171/149899497-95493da0-c90c-41bd-881b-3ab763ab3523.png">|                 |                  |<img width="1163" alt="Capture d’écran 2022-01-18 à 09 34 50" src="https://user-images.githubusercontent.com/90036171/149900287-4b6c3190-4f3a-4f5b …

(PC-12581) fix(EighteenBirthday): Fix bottom padding only for this card

---

src/ui/components/snackBar/SnackBar.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12961
I have:

(PC-12961) fix(ZIndex): remove last import of ZIndex constant in profit of theme

---

src/features/bookOffer/atoms/ChoiceBloc.tsx
src/features/bookOffer/components/BookDateChoice.tsx
src/features/bookOffer/components/BookDuoChoice.tsx
src/features/bookOffer/components/BookHourChoice.tsx
src/features/identityCheck/atoms/AddressOption.tsx
src/features/identityCheck/atoms/StepButton.tsx
src/features/search/atoms/Buttons/DateFilter.tsx
src/features/search/atoms/Buttons/ReinitializeFilters.tsx
src/features/search/sections/OfferDate.tsx
src/ui/components/buttons/AppButton.tsx
src/ui/components/snackBar/SnackBar.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12958
I have:

(PC-12958) fix(activeOpacity): remove last constants imports in profit of theme

---

__snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
__snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap
__snapshots__/features/auth/login/Login.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/profile/__test__/SetAddress.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/profile/__test__/SetCity.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/profile/__test__/SetCity.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/profile/__test__/SetName.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/profile/__test__/SetName.web.test.tsx.web-snap
__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
__snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap
__snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
__snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
__snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
__snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
__snapshots__/ui/components/inputs/TextInput.native.test.tsx.native-snap
__snapshots__/ui/components/inputs/TextInput.web.test.tsx.web-snap
src/features/auth/components/PasswordSecurityRules.tsx
src/features/auth/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx
src/features/auth/signup/SetPassword/SetPassword.tsx
src/features/profile/pages/ChangePassword/ChangePassword.tsx
src/locales/fr/messages.po
src/ui/components/InputLabel.tsx
src/ui/components/InputLabel.web.tsx
src/ui/components/inputs/EmailInput.tsx
src/ui/components/inputs/PasswordInput.tsx
src/ui/components/inputs/SearchInput.tsx
src/ui/components/inputs/TextInput.tsx
src/ui/components/inputs/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12981
I have:
|     |         |                 |                  |     Email : <br/> <img width="272" alt="Capture d’écran 2022-01-24 à 14 20 43" src="https://user-images.githubusercontent.com/46637324/150790326-0f82b75b-4ecb-46bc-ae21-5614084916fa.png">        |
|     |         |                 |                  |    Password : <br/> <img width="280" alt="Capture d’écran 2022-01-24 à 14 21 54" src="https://user-images.githubusercontent.com/46637324/150790359-fe54ebcf-b479-483d-91b1-e9cb6cccb667.png">      |
[1]: …

(PC-12981) feat(accessiblity): add label and aria-describedby to email and password inputs

---

__snapshots__/ui/web/errors/__tests__/ErrorMessage.test.tsx.native-snap
__snapshots__/ui/web/errors/__tests__/ErrorMessage.test.tsx.web-snap
src/ui/components/inputs/InputError.tsx
src/ui/web/errors/ErrorMessage.tsx
src/ui/web/errors/ErrorMessage.web.tsx
src/ui/web/errors/__tests__/ErrorMessage.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12864
I have:
|     |         |                 |         
|                  |

(PC-12864) feat(InputError): handle accessibility on input error

---

__snapshots__/features/bookOffer/components/__tests__/BookDuoChoice.native.test.tsx.native-snap
__snapshots__/features/bookOffer/components/__tests__/BookDuoChoice.web.test.tsx.web-snap
__snapshots__/features/bookOffer/components/__tests__/BookingEventChoices.native.test.tsx.native-snap
__snapshots__/features/bookOffer/components/__tests__/BookingEventChoices.web.test.tsx.web-snap
src/features/bookOffer/components/BookDuoChoice.tsx
src/features/bookOffer/components/BookingDetails.tsx
src/features/bookOffer/components/DuoChoiceSelector.tsx
src/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx
src/features/bookings/helpers.test.ts
src/features/bookings/helpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12835
I have:
|Avant|Après|
|:--:|:--:|
|![image](https://user-images.githubusercontent.com/95220086/149962412-88202c28-cfd9-476c-8a33-025af433a265.png)|![image](https://user-images.githubusercontent.com/95220086/149962558-d15681b5-6d81-40fb-b5d2-b926651768a8.png)|
|![image](https://user-images.githubusercontent.com/95220086/149962736-f38c1b9a-4f34-4368-ac90-5f02b61e246a.png)|![image](https://user-images.githubusercontent.com/95220086/149962793-938351b1-24b5-4bc8-8110-718776fee225.png)|
|![image](https://user-images.githubusercontent.com/95220086/149962861-c7fc6c0d-472a-4c6e-bd16-ac340b4c2296.png)|![image](https://user-images.githubusercontent.com/95220086/149962886-862b344d-c994-446c-828f-31f2a06ca376.png)|
[1]: …

(PC-12835) feat(bookingDetails): display the Duo selector when the offer is duo

---

src/ui/svg/icons/icons.md

Add icons.md to enforce consistency
- Illustrations (rectangular frame)
- Pictograms (square frame)
Illustrations are meant to be used in Generic info pages and modals. They have a ratio of 200x156 and thus cannot be replaced by pictograms in generic components: the render would differ.
Pictograms can be linear or filled.
- Linear pictograms have to be used at size 20px or bigger for Accessibility reasons. Typical use cases include Primary and Secondary buttons.
- Filled pictograms have to be used at size 20 px or smaller. Typical use cases include Tertiary and Quaternary buttons.
All types of icons should be imported the same way to enforce consistency in use throughout the codebase. Follow the given templates (or existing icons) to import your icons correctly.
Illustrations should be …

docs(icons): add icons.md

---

__snapshots__/features/firstLogin/CulturalSurvey.native.test.tsx.native-snap
__snapshots__/libs/recaptcha/ReCaptcha.native.test.tsx.native-snap
android/gradle.properties
ios/Podfile.lock
package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12045
Chaque erreur est différente, exemple:
> Invariant Violation: Module WebViewMessageHandler6 is not a registered callable module (calling onShouldStartLoadWithRequest). A frequent cause of the error is that the application entry file path is incorrect.
> Invariant Violation: Module WebViewMessageHandler3 is not a registered callable module (calling onShouldStartLoadWithRequest). A frequent cause of the error is that the application entry file path is incorrect.
Étonnamment, le nom du module change à chaque nouvelle webview: https://github.com/react-native-webview/react-native-webview/blob/404e3e69e23d8c73bc4deb688c77b9a1a0bb55f8/src/WebView.android.tsx#L88.
I have:
[1]: …

(PC-12045) fix(webview): bump version to tentatively fix crash

---

__snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap
__snapshots__/features/offer/pages/tests/OfferDescription.web.test.tsx.web-snap
__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap
__snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap
__snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap
__snapshots__/features/search/pages/__tests__/LocationFilter.web.test.tsx.web-snap
src/ui/web/global/Header.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12999
I have:
|     |         |                 |                     <img width="550" alt="Capture d’écran 2022-01-28 à 16 58 06" src="https://user-images.githubusercontent.com/46637324/151579583-31835993-6edd-49dd-8c5c-4dd3f3ed4422.png">  |     |

(PC-12999) fix(accessibility): Fix header width for app modal

---

__snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
__snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
src/features/profile/pages/ConsentSettings.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12960
I have:
| iOS | Android | Mobile - Chrome | Desktop - Chrome | Desktop - Chrome 2 |
|     |         |                 | ![image](https://user-images.githubusercontent.com/77674046/151952724-9ec4734e-96cf-45e2-824c-97566b4e7575.png)|![image](https://user-images.githubusercontent.com/77674046/151952932-7315ec70-7fe5-4b51-a7c7-7114d59c72c1.png)|

(PC-12960) fix(Style): usage of ButtonQuaternary instead of ButtonTertiary in PrivacyPolicyModal and ConsentSettings

---

src/features/bookOffer/components/BookingDetails.tsx
src/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13229
I have:
avec une offre de type event
| avant  | après |
| :--: | :-----: |
|  ![image](https://user-images.githubusercontent.com/95220086/152141266-927bf579-5d57-446b-a993-1432abdb5f1d.png)   | ![image](https://user-images.githubusercontent.com/95220086/152141324-a938be9e-1ef4-49b5-8064-3d3e70dda2ca.png)|

(PC-13229) feat(booking): display duo selector only for not event offer

---

src/ui/components/buttons/ButtonPrimary.tsx
src/ui/components/buttons/ButtonSecondary.tsx
src/ui/components/buttons/ButtonSecondaryWhite.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12797
I have:

(PC-12797) fix(AppButtons): fix loading being overwritten by disabled state

---

src/ui/components/inputs/addressCheck.test.ts
src/ui/components/inputs/addressCheck.ts
src/ui/components/inputs/nameCheck.test.ts
src/ui/components/inputs/nameCheck.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13202
I have:
|   <img width="310" alt="Capture d’écran 2022-02-07 à 11 01 21" src="https://user-images.githubusercontent.com/44037911/152766481-a5e58ab5-80de-422e-869a-ddb4e106de8a.png">  |         |                 |                  |                  |

(PC-13202) fix(signup): add tilted apostrophe in name regex

---

doc/installation/iOS.md

Lorsque j'ai fait mon installation, j'ai cru que la dernière partie de la doc d'installation pour iOS n'était nécessaire que pour l'utilisation d'un smartphone branché sur PC. 
Or, elle est aussi nécessaire pour installer et lancer l'app sous le simulateur de Xcode.

docs(iOS): clarify installation for ios

---

__snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap
__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
__snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
__snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
src/features/bookings/components/BookingItemTitle.tsx
src/features/bookings/components/OnGoingBookingsList.tsx
src/features/favorites/atoms/Favorite.tsx
src/features/favorites/atoms/NumberOfResults.tsx
src/features/home/components/HomeHeader.tsx
src/features/identityCheck/atoms/CenteredTitle.tsx
src/features/identityCheck/atoms/layout/PageHeader.tsx
src/features/identityCheck/pages/Stepper.tsx
src/features/profile/components/BeneficiaryHeader.tsx
src/features/profile/components/LoggedOutHeader.tsx
src/features/search/atoms/Sections.tsx
src/ui/components/AccordionItem.tsx
src/ui/components/GenericErrorPage.tsx
src/ui/components/GenericInfoPage.tsx
src/ui/components/headers/PageHeader.tsx
src/ui/components/headers/SvgPageHeader.tsx
src/ui/components/modals/ModalHeader.tsx
src/ui/theme/typography.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12843
I have:

(PC-12843) feat(accessibility): Hide accordion's children when not expanded

---

sonar-project.properties

ça devrait permettre d'éviter que Sonar soit au rouge sur le test coverage https://github.com/pass-culture/pass-culture-app-native/pull/2595#issuecomment-1032836874
I have:

build(sonar): Sonar should ignore coverage of Storybook

---

src/features/search/atoms/NumberOfResults.tsx
src/features/search/atoms/__tests__/NumberOfResults.native.test.tsx
src/features/search/atoms/__tests__/NumberOfResults.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13502
I have:

(PC-13502) fix(Search): allow removal of locationFilter in current and staged search

---

src/libs/network/__mocks__/useNetwork.web.ts
src/libs/network/useNetwork.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13506
Le problème était uniquement sur web et apparaissait quand on consultais le détail d'une réservation sans appeler `/bookings` avant.
Ceci se passait dans 2 cas:
- après un refresh de l'app: accéder au détail d'une réservation depuis la home ou la recherche
- après un refresh de l'app: accéder au détail d'une réservation directement avec l'url.
Idéalement il faudrait revoir le système de caching des réservations dans react-query. Pour l'instant il y a une seule clef utilisée `QueryKeys.BOOKINGS` et pour avoir un booking on va chercher dans cet les bookings (ongoing ou ended). Ce serait avantageux d'avoir une clef `[QueryKeys.BOOKING, bookingId]` comme les offres pour ne pas avoir à requêter tous les bookings lors de la …

(PC-13506) fix(bookings): on web, fix booking details page

---

src/features/auth/signup/SignupForm.tsx
src/features/bookings/pages/BookingDetails.tsx
src/features/firstTutorial/pages/FirstTutorial/components/FirstCard.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/TabBar/routes.ts
src/features/offer/pages/OfferWebHead/OfferWebHead.tsx
src/features/search/components/SearchResults.tsx
src/features/search/components/__tests__/SearchResults.native.test.tsx
src/features/venue/components/VenueWebHeader.tsx
src/libs/appWebHead.tsx
src/locales/fr/messages.po
src/ui/web/global/Helmet.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13004
I have:

(PC-13004) feat(accessibility): Correctly identify tab titles based on focused screen

---

__snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap
__snapshots__/ui/components/DotComponent.native.test.tsx.native-snap
src/ui/components/DotComponent.tsx
src/ui/svg/icons/Dot.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12998
I have:

(PC-12998) feat(accessibility): Make dot component inaccessible if not interactive

---

src/features/navigation/RootNavigator/Header/NavItem.tsx
src/features/navigation/TabBar/TabBarComponent.tsx
src/features/navigation/TabBar/routes.ts
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13566
I have:

(PC-13566) fix(accessibility): Revert accessibility labels for tab bar

---

src/features/search/components/CalendarPicker.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13691
I have:

(PC-13691) fix(WebCalendarPicker): Display error only when date is invalid

---

src/ui/components/bars/ProgressBar.stories.tsx
src/ui/components/bars/ProgressBar.tsx

feat(ui): add ProgressBar component to storybook

---

src/ui/components/bars/ProgressBar.stories.tsx

Chromatic have different screenshot because of the animation
https://www.chromatic.com/test?appId=61fd537ecf081f003a135235&id=621cb013459f04003a267c7b
I have:

fix(pipeline): remove animated storybook

---

.eslintrc.js
src/features/home/components/OffersModule.tsx
src/libs/geolocation/hooks/useDistance.ts
src/ui/components/Playlist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13621
Analyse du bug → https://www.notion.so/passcultureapp/Homepage-La-distance-de-certaines-offres-n-est-pas-affich-e-85cc17514152436e8546847e792dee0d
I have:

(PC-13621) fix(home): show distance for offers

---

src/libs/parsers/pricesConversion.ts
src/libs/parsers/tests/getDisplayPrice.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13805
I have:
|     |         |                 |      <img width="280" alt="Capture d’écran 2022-03-04 à 17 05 55" src="https://user-images.githubusercontent.com/46637324/156798001-52a41a53-6b47-4f1c-bb20-bfee7b153c08.png"><img width="450" alt="Capture d’écran 2022-03-04 à 17 05 41" src="https://user-images.githubusercontent.com/46637324/156798014-001c722d-57e1-4fb6-a7e0-e62e86a5dccd.png">. <img width="280" alt="Capture d’écran 2022-03-04 à 17 05 47" src="https://user-images.githubusercontent.com/46637324/156798012-df794844-4a52-46ac-900b-4b144ffb6725.png"><img width="450" …

(PC-13805) fix(PriceConversion): Fix number of decimals in price conversion from euro to cents

---

__snapshots__/features/favorites/atoms/__tests__/Favorite.native.test.tsx.native-snap
__snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap
__snapshots__/features/offer/atoms/__tests__/OfferTile.native.test.tsx.native-snap
__snapshots__/features/offer/atoms/__tests__/OfferTile.web.test.tsx.web-snap
__snapshots__/features/search/atoms/__tests__/Hit.native.test.tsx.native-snap
__snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap
__snapshots__/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx.web-snap
__snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap
__snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap
__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap
__snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap
__snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap
src/features/search/atoms/Hit.tsx
src/libs/tileAccessibilityLabel.ts
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13715
I have:

(PC-13715) fix(accessibility): Add duo aria label to offer tiles and date aria label to search hits

---

.circleci/config.yml

The previous CI config [pull request](https://github.com/pass-culture/pass-culture-app-native/pull/2773) did not include the web deployment process.
This fixes it.

fix(ci): fix deploy web for staging patches

---

src/libs/parsers/highlightLinks.tsx
src/libs/parsers/tests/highlightLinks.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13993
I have:
|<img width="1438" alt="Capture d’écran 2022-03-16 à 10 12 47" src="https://user-images.githubusercontent.com/78556024/158557068-a694dd3a-88ac-4412-906d-7d5aa0ee25b4.png">|<img width="721" alt="Capture d’écran 2022-03-16 à 10 12 24" src="https://user-images.githubusercontent.com/78556024/158557138-cd7fd837-cc60-4afb-ac07-e4d3210854ab.png">|

(PC-13993) fix(offer): do not parse email as link

---

src/features/identityCheck/pages/Stepper.tsx
src/features/identityCheck/pages/__test__/Stepper.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13769
L'ajout de fonctionnalité du back DMS Orphan permet de faire correspondre les dossiers déposés sur Démarches-Simplifiées (DMS) avant inscription sur l'application avec les nouveaux comptes créés sur l'application.
Pour tous les dossiers qui ont déjà été validés, on ne veut pas que l'utilisateur ait à soumettre à nouveau son document d'identité. 
On fetch donc le nextSubscriptionStep sur le stepper. S'il est `null` et que le crédit attribué au jeune est non-nul, c'est que le compte a été rattaché au dossier DMS orphelin (il a été "adopté"). Dans ce cas, on force la sortie du stepper et le jeune peut profiter de l'application.
Le code est alourdi, il devra être nettoyé lors de la prochaine amélioration du stepper (en …

(PC-13769) fix(signup): navigate to AccountCreated or UnderageAccoundCreated for DMS oprhans

---

__snapshots__/features/_marketingAndCommunication/pages/tests/DeeplinksGenerator.test.tsx.web-snap
__snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap
__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.native.test.tsx.native-snap
__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap
__snapshots__/features/favorites/components/__tests__/NotConnectedFavorites.test.tsx.native-snap
__snapshots__/features/favorites/components/__tests__/NotConnectedFavorites.test.tsx.web-snap
__snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap
__snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/components/__test__/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/__test__/IdentityCheckStart.native.test.tsx.native-snap
__snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap
__snapshots__/features/profile/components/CreditCeiling.native.test.tsx.native-snap
__snapshots__/features/profile/components/CreditCeiling.web.test.tsx.web-snap
src/features/_marketingAndCommunication/atoms/DeeplinkItem.tsx
src/features/_marketingAndCommunication/components/DeeplinksHistory.tsx
src/features/auth/components/signupComponents.tsx
src/features/auth/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx
src/features/auth/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.tsx
src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx
src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
src/features/cheatcodes/pages/Navigation/Navigation.tsx
src/features/favorites/components/NotConnectedFavorites.tsx
src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
src/features/identityCheck/components/SomeAdviceBeforeIdentityCheckModal.tsx
src/features/offer/components/SignUpSignInChoiceOfferModal.tsx
src/features/profile/components/CreditCeiling.tsx
src/features/search/atoms/NoSearchResult.tsx
src/features/search/pages/SuggestedPlaces.tsx
src/ui/components/ModuleBanner/ModuleBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14394
I have:
On a déjà rencontré ce problème dans la page des offres, j'avais fait une analyse de bugs, le problème était qu'on ne fixait pas de couleur au composant `Text` -> il faut privilégier l'utilisation des composants Typo
|     | Pas de différence entre mode sombre et clair : <img width="310" alt="Capture d’écran 2022-04-11 à 18 06 53" src="https://user-images.githubusercontent.com/46637324/162783409-0693d43d-cfac-4ac4-9443-b580fb457411.png">   |                 |                  |                  |
[1]: https://github.com/pass-culture/pass-culture-app-native/blob/mas …

(PC-14394) fix(accessibility): Use existant typography component for credit label

---

src/api/gen/api.ts
src/features/auth/__mocks__/settings.ts
src/features/auth/login/Login.native.test.tsx
src/features/auth/login/Login.tsx
src/features/auth/signup/AccountCreated/AccountCreated.tsx
src/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx
src/features/culturalSurvey/helpers/utils.ts
src/features/identityCheck/pages/confirmation/BeneficiaryRequestSent.tsx
src/features/identityCheck/pages/confirmation/__test__/BeneficiaryRequestSent.test.tsx
src/features/navigation/RootNavigator/useInitialScreenConfig.tsx
src/features/navigation/__tests__/useInitialScreenConfig.native.test.tsx
src/tests/server.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14400
I have:

(PC-14400) feat(CulturalSurvey): redirect to the right cultural survey on login/signup/initialScreen

---

src/features/identityCheck/errors/eduConnect/NotEligibleEduConnect.tsx
src/features/identityCheck/errors/hooks/useNotEligibleEduConnectErrorData.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14355
I have:

(PC-14355) fix(accessibility): Separate navigation and onPress in NotEligibleEduconnect screen

---

src/features/offer/components/__tests__/OfferHeader.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14104
I have:

(PC-14104) fix(test): Fix OfferHeader flaky test

---

src/features/firstLogin/CulturalSurvey.native.test.tsx
src/features/firstLogin/CulturalSurvey.tsx
src/features/firstLogin/CulturalSurvey.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14591
On souhaite montrer le QPI à l'ouverture de l'app si `user.needsToFillCulturalSurvey=true`. Problème: à l'ouverture de l'app, si les settings sont `undefined`, on redirige vers le typeform et on ne peut plus rediriger vers le QPI natif (même si le FF ENABLE_NATIVE_CULTURAL_SURVEY est true). Cette PR sert à rediriger vers le typeform vers le QPI natif si le FF est activé.
I have:

(PC-14591) feat(CulturalSurvey): make sure we redirect to native cultural survey when FF is active

---

__snapshots__/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx.native-snap
__snapshots__/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx.web-snap
src/features/auth/suspendedAccount/SuspendedAccount/SuspendedAccount.tsx
src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx
src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx
src/features/cheatcodes/pages/Navigation/Navigation.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14556
I have:
|   ![Simulator Screen Shot - iPhone 13 - 2022-04-28 at 16 03 35](https://user-images.githubusercontent.com/46637324/165770640-a0f24012-08ad-4adc-84bb-5df159ec381f.png)  |         |                 | <img width="1173" alt="Capture d’écran 2022-04-28 à 16 03 20" src="https://user-images.githubusercontent.com/46637324/165770658-518c29eb-841a-4542-b511-d2943428c5e2.png">       |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les- …

(PC-14556) feat(ProfileDeletion): Add new info screen for suspended users

---

src/api/__tests__/apiHelpers.test.ts
src/api/apiHelpers.ts
src/features/auth/AuthContext.tsx
src/libs/eduConnectClient.ts
src/libs/fetch.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14413
I have:

(PC-14413) feat(apiHelpers): better log when user are disconnected because refresh token is expired

---

src/features/favorites/atoms/BicolorFavoriteCount.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14471
I have:

(PC-14471) fix(accessibility): Add label to favorite icon when user is logged out and no label is shown

---

scripts/update_app_version.sh

This warning is no longer necessary since we do not release a hard build of testing when we patch staging.
Therefore, no need to bump master.

build(patch_script): remove now useless warning for patches

---

src/features/home/pages/Home.tsx
src/features/home/selectPlaylist.ts
src/libs/ABTesting/ABTesting.constants.ts
src/libs/ABTesting/ABTesting.services.ts
src/libs/ABTesting/ABTesting.types.ts
src/libs/ABTesting/ABTestingProvider.tsx
src/libs/firebase/shims/firebase-init.ts
src/libs/firebase/shims/remote-config/index.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14856
On veut faire de l'A/B testing sur la homepage de l'app. Pour cela on utilise le service d'A/B testing de firebase. Celui ci se base sur le service de remote config.
Cette PR sert à utiliser le paramètre `homeEntryId` défini dans firebase remote config :
Cet identifiant correspond à l'id d'une playlist sur contentful :
Pour rappel, si aucun `entryId` n'est spécifié à l'arrivée sur la home, l'app sélectionne par défaut les playlists selon leurs tags => https://www.notion.so/passcultureapp/Cr-er-une-home-sur-Contentful-627cdd67c44f4da88a370b21cbe1746b#0df79a3cc974481fb014832cccd06a8e
I have:
[2]: …

(PC-14856) feat(home): use remote config homeEntryId to select playlist

---

src/api/gen/api.ts
src/features/auth/__mocks__/settings.ts
src/features/profile/pages/DeleteProfile/DeleteProfileSuccessV2.tsx
src/locales/fr/messages.po
src/tests/server.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14826
I have:

(PC-14826) feat(ProfileDeletion): Get account reactivation limit from settings

---

.circleci/config.yml
package.json
scripts/create_and_push_tag_from_package_json_version.sh
scripts/get_version.sh
scripts/release_staging_minor.sh
scripts/update_app_version.sh
scripts/update_build_number_from_package_json_version.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-14340
When we develop a new version on our codebase (available on `master`), we want the `testing` app on AppCenter to have a minor version higher than the version avaibable on staging and in production. Therefore, when we deploy code to the staging environment, the released version number is based on the version number we developed on `master`.
We always had the same minor version on testing and staging. On the days of deploying a new staging version, we bumped both `testing` and `staging` from `v1.X.Y` to `v1.(X+1).0`. It means that what we had on `master` known as `v1.X.Y`
is released with a different name on staging.
I have changed the `trigger:staging:deploy` script so that it does two different things:
- it gets the …

(PC-14340) build(versions): update versioning system

---

scripts/upload_sourcemaps_to_sentry.sh

- https://github.com/getsentry/sentry-react-native/issues/2087
- https://github.com/pass-culture/pass-culture-app-native/pull/2917
- Test if Android source map still work in our project.
- Test if iOS source maps work.
- Test if code push version are always having correct source map (if no, try to use sha from commit and always create different `DIST` and `RELEASE`
I have:
[2]: …

(PC-13509) fix(Sentry): android source map (maybe codepush and ios)

---

src/features/errors/pages/AsyncErrorBoundary.tsx
src/ui/components/GenericErrorPage.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15100
On essayait de d'appeler le hook `useGoBack` dans le composant `GenericErrorPage` qui était monté dans la page d'erreur `AsyncErrorBoundaryWithoutNavigation`. Ce composant sert de "FallbackComponent" à `ErrorBoundary` qui est défini avant la navigation dans l'arborescence de `App.tsx`.
Pour reproduire le bug je me suis loggé avec un utilisateur qui a ensuite été supprimé. A l'ouverture de l'app, le premier appel à /me (qui retournait une 401) était catché par l'error boundary qui faisait l'appel à `useGoBack` via le composant `AsyncErrorBoundaryWithoutNavigation` et la `GenericErrorPage`.
I have:
Avant:
Après:
[2]: …

(PC-15100) fix(navigation): fix missing navigation object crash

---

src/features/auth/login/Login.native.test.tsx
src/features/auth/login/Login.tsx
src/features/auth/suspendedAccount/SuspensionScreen/SuspensionScreen.tsx
src/features/auth/suspendedAccount/SuspensionScreen/tests/SuspensionScreen.test.tsx

Link to JIRA ticket: 
https://passculture.atlassian.net/browse/PC-15248
https://passculture.atlassian.net/browse/PC-14854
I have:

(PC-15248) feat(AccountSuspension): Logout user when quitting suspension screen (PC-14854)

---

src/features/navigation/RootNavigator/RootNavigator.tsx
src/features/navigation/__tests__/RootNavigator.native.test.tsx
src/features/navigation/__tests__/RootNavigator.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15261
I have:

(PC-15261) feat(header): hide QuickAccess button if no tabNav or Nav

---

src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx
src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx
src/features/auth/suspendedAccount/SuspendedAccount/useAccountUnsuspend.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15631
I have:
| https://user-images.githubusercontent.com/46637324/173512932-a71c6af5-7432-4706-98d5-56c9fa7cfdba.mp4 |         |                 |                  |                  |

(PC-15631) fix(AccountReactivation): Invalidate booking and favorite queries on account reactivation

---

src/features/favorites/pages/Favorites.tsx
src/features/favorites/pages/__tests__/Favorites.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15707
I have:

(PC-15707) feat(OfflineMode): use not connected template on favorite

---

src/features/favorites/atoms/BicolorFavoriteCount.tsx
src/features/favorites/atoms/__tests__/BicolorFavoriteCount.native.test.tsx
src/features/favorites/atoms/__tests__/BicolorFavoriteCount.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15712
I have:

(PC-15712) fix(OfflineMode): do not show favorites count when not connected

---

src/features/auth/suspendedAccount/SuspendedAccount/SuspendedAccount.tsx
src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.native.test.tsx
src/features/auth/suspendedAccount/SuspendedAccount/tests/SuspendedAccount.web.test.tsx
src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx
src/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.native.test.tsx
src/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15797
I have:

(PC-15797) fix(AccountReactivation): use replace instead of navigate to redirect to success screen

---

src/features/home/api/tests/useAlgoliaRecommendedHits.test.ts
src/features/home/api/tests/useHomeRecommendedHits.test.ts
src/features/home/api/tests/useHomeRecommendedIdsMutation.test.ts
src/features/home/api/useAlgoliaRecommendedHits.ts
src/features/home/api/useHomeRecommendedHits.ts
src/features/home/api/useHomeRecommendedIdsMutation.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15471
I have:

(PC-15471) fix(recommendation): do not fetch endpoint when user is not connected

---

src/features/search/pages/Search.tsx
src/features/search/pages/__tests__/Search.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15909
Target branch is `PC-15704`
I have:

(PC-15909) fix(OfflineMode): added offline template on search when not connected

---

src/features/profile/pages/Profile.native.test.tsx
src/features/profile/pages/Profile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15708
I have:

(PC-15708) fix(OfflineMode): show offline template on profil when net connected

---

src/features/search/components/SearchBoxRework.tsx
src/features/search/pages/__tests__/useShowResultsForCategory.test.ts
src/features/search/pages/__tests__/useShowResultsWithStagedSearch.test.ts
src/features/search/pages/useShowResultsForCategory.ts
src/features/search/pages/useShowResultsWithStagedSearch.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15130
I have:

(PC-15130) fix(search): categories buttons must keep search context

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16106
Mettre a jour lottie-react-native permet de ne plus avoir les warning des ViewPropTypes sur la Home en lien avec Lottie
I have:

(PC-16106) feat(lottie): udpate lottie-react-native from v5.0.1 to 5.1.3

---

src/features/search/components/SearchBox.tsx
src/features/search/components/__tests__/SearchBox.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16143
I have:

(PC-16143) fix(Search): back reset default search expect locationFilter

---

src/libs/network/OfflineModeContainer.tsx
src/libs/network/__tests__/OfflineModeContainer.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16119
Live demo  https://codesandbox.io/s/react-native-test-forked-7nc5zc
I have:

(PC-16119) fix(Offline): show banner when isInternetReachable stay false for more than 30secs

---

src/libs/algolia/analytics/__tests__/logClickOnOffer.test.ts
src/libs/algolia/analytics/initAlgoliaAnalytics.ts
src/libs/algolia/analytics/logClickOnOffer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16233
Le tracking Algolia ne fonctionne pas sur mobile car nous utilisons une fonctionnalité d'Algolia, qui génère un userToken et le stocke dans un cookie. Or il n'y a pas de cookie sur mobile (confirmé par le support: https://support.algolia.com/hc/en-us/requests/504416) 
En suivant une des recommandations du support, on génère alors un userToken en début de session (un uuid), qui sera utilisé dans les events envoyés plus tard. Ce token n'étant pas stocké, il ne durera que le temps de la session, mais cela n'a pas l'air d'avoir d'impact avec les fonctionnalités qu'on utilise du tracking algolia (confirmé par le support: "Though if you wish the users remain anonymous between sessions, generating a new one each session would …

(PC-16233) feat(algolia): add algolia tracking to mobile

---

src/features/search/atoms/__tests__/NoSearchResult.native.test.tsx
src/features/search/components/__tests__/SearchBox.native.test.tsx
src/features/search/pages/__tests__/useShowResultsForCategory.test.ts
src/features/search/pages/__tests__/useShowResultsWithStagedSearch.test.ts
src/features/search/pages/usePushWithStagedSearch.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16252
I have:

(PC-16252) fix(SearchV2): navigate instead of push on Native apps

---

rn-cli.config.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16256
To prevent refreshing the native while starting the web app of development.
I have:

(PC-16256) build(metro): set blacklistRE in rn-cli.config.js

---

src/features/auth/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx
src/features/profile/pages/AfterChangeEmailValidationBuffer/AfterChangeEmailValidationBuffer.tsx
src/features/profile/pages/AfterChangeEmailValidationBuffer/__tests__/AfterChangeEmailValidationBuffer.native.test.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16182
I have:
https://user-images.githubusercontent.com/44037911/180412498-f025e704-a317-4d7f-8720-d27d854c8075.mov

(PC-16182) feat(wording): change wordings in two pages

---

src/features/home/api/tests/useHomeRecommendedHits.test.ts
src/features/home/api/useHomeRecommendedHits.ts
src/features/home/api/useHomeRecommendedIdsMutation.ts
src/features/home/contentful/contentful.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15998
I have:
Les id n'ont pas l'air d'être présent sur algolia donc les playlists ne peuvent pas s'afficher sur la home

(PC-15998) feat(home):  add subcategories to recommendation playlists parameters

---

__snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap
__snapshots__/features/search/components/__tests__/SearchBoxAutocomplete.native.test.tsx.native-snap
__snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap
__snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap
src/features/search/components/SearchBox.tsx
src/features/search/components/SearchBoxAutocomplete.tsx
src/features/search/components/SearchHeader.tsx
src/features/search/components/SearchMainInput/SearchMainInput.tsx
src/features/search/components/__tests__/SearchBox.native.test.tsx
src/features/search/pages/Search.tsx
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16395
Reason why the keyboard was opening twice:
We used two `TextInput` so it was un/mounting when not focused/focused, and keyboard was closing before reopening again.
Solution was to use only one `<TextInput />`. I also added a bit of `memo` to optimize some component, and removed some useless `props` spreaded for no reason.
I have:
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bu …

(PC-16395) fix(Search): no keyboard flickering on Android

---

src/features/search/components/SearchBox.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16478
I have:

(PC-16478) fix(Search): reset input does not work on the web

---

src/features/home/api/tests/useHomeRecommendedIdsMutation.test.ts
src/features/home/api/useHomeRecommendedIdsMutation.ts
src/libs/firebase/analytics/provider.ts
src/libs/firebase/analytics/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16469
On utiliser la méthode `setDefaultEventParameters` pour que l'on puisse retrouver les infos de l'algo de reco sur les événements du type `ConsultOffer` ou `HasAddedOfferToFavorites`
I have:

(PC-16469) feat(recommendation): log recommendation parameters on firebase

---

src/features/home/components/HomeHeader.tsx
src/features/home/pages/tests/Home.native.test.tsx
src/features/profile/components/ProfileHeader.native.test.tsx
src/features/profile/components/ProfileHeader.tsx
src/features/profile/components/ProfileHeader.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16526
I have:

(PC-16526) fix(header): no header when user disconnected

---

src/features/bookOffer/pages/BookingOfferModal.tsx
src/features/bookings/components/ArchiveBookingModal.tsx
src/features/bookings/components/CancelBookingModal.tsx
src/ui/components/modals/AppModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16351
Due to navigation when action success on those modal, it is preferable to prevent overlap of the modal after navigation, to totally disable the `slideOutDown` animation by setting the `animationOutTiming` to `0`
Read more: https://github.com/react-native-modal/react-native-modal
I have:

(PC-16351) fix(AppModal): disable animationOut for BookingOfferModal, ArchiveBookingModal, CancelBookingModal

---

src/features/bookings/helpers.test.ts
src/features/bookings/helpers.ts

for old offers
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16239
I have:

(PC-16239) feat(booking): show msg when no withdrawal type

---

src/features/culturalSurvey/context/reducer.ts
src/features/culturalSurvey/context/types.ts
src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15491
I have:

(PC-15491) fix(QPI): flush answers on submit success, avoid cached answers

---

package.json
patches/react-native-calendars+1.1284.0.patch
src/features/bookOffer/components/Calendar/Calendar.tsx
src/features/identityCheck/pages/identification/IdentityCheckValidation.tsx
src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx
src/features/search/components/CalendarPicker.web.tsx
src/features/search/utils/isBeforeToday.ts
src/features/search/utils/tests/isBeforeToday.test.ts
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16720
En plus de la suppression de l’usage de `moment` (au profit de `date-fns`) dans 4 sources à nous: 
- `src/features/bookOffer/components/Calendar/Calendar.tsx`
- `src/features/identityCheck/pages/identification/IdentityCheckValidation.tsx`
- `src/features/identityCheck/pages/identification/IdentityCheckValidation.web.tsx`
- `src/features/search/components/CalendarPicker.web.tsx`
Pour supprimer `moment`, nous devons modifier `react-native-calendars`, j’ai ouvert une issue sur leur repo GitHub :  https://github.com/wix/react-native-calendars/issues/1968
Aussi `moment` était importé mais non présent dans les dépendances de notre `package.json`, donc il n'était pas nécessaire de le supprimer.
Exemple de format/parse du fait …

(PC-16720) fix(Date): remove duplicate unecessary date lib moment

---

src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx
src/ui/components/GenericInfoPage.tsx
src/ui/components/GenericInfoPageWhite.tsx
src/ui/components/achievements/components/GenericAchievementCard.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16664
I have:
|    ![Simulator Screen Recording - iPhone 12 - 2022-08-11 at 15 52 12](https://user-images.githubusercontent.com/62059034/184150646-997ec9d8-fb67-49ab-8729-a9f65f1e1f2e.gif) ![Simulator Screen Recording - iPhone 12 - 2022-08-11 at 15 55 03](https://user-images.githubusercontent.com/62059034/184150676-be39e8cb-3844-4cf7-ab8d-c95366b6676f.gif) ![Simulator Screen Recording - iPhone 12 - 2022-08-11 at 15 55 37](https://user-images.githubusercontent.com/62059034/184150686-c9290622-b44e-409d-8faf-3c198a73c2cf.gif) ![Simulator Screen Recording - iPhone 12 - 2022-08-11 at …

(PC-16664) fix(lottie): play animation after app in background for all lottie animations

---

src/features/navigation/RootNavigator/identityCheckRoutes.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16790
Exchange path names between deprecated and new SetPhoneNumber pages.
I have:

(PC-16790) refactor(phoneVal): replace old SetPhoneNumber paths with new

---

src/features/navigation/RootNavigator/linking/getInitialUrl.ios.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16810
I have:

(PC-16810) fix(notification): add break before load batch url

---

.circleci/config.yml

Following the bundle web optimization, we will try to hold the resource_class to the minimum of ram needed, until our app grows and we'll increased it again later.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16541
I have:

(PC-16541) ci(Web): reducing resource_class for build_web from large to medium+

---

.circleci/config.yml

This reverts commit 38c78daf88b930e58ea8b026a5e731845b58b841.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16541
Finalement, on ne peut pas réduire la RAM, ex de CI qui fail depuis ce commit : https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/17702/workflows/7a9e1fc6-6a90-4af1-918d-393c397ec297/jobs/64984
Donc je revert
I have:
| [CI Failed](https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/17702/workflows/7a9e1fc6-6a90-4af1-918d-393c397ec297/jobs/64984) | 
| --: |
| ![image](https://user-images.githubusercontent.com/77674046/185145406-796ca882-3e4c-4a16-9ad5-ce160a199e84.png)    |
[2]: …

(PC-16541) ci(Web): reducing resource_class for build_web from large to medium+ (Revert)

---

src/features/search/atoms/Buttons/__tests__/ShowResults.native.test.tsx
src/features/search/pages/SearchWrapper.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16537
I have:

(PC-16537) fix(Search): show results view after submitting reinitialized filters

---

src/libs/firebase/analytics/provider.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16938
This PR is inspired from https://stackoverflow.com/a/61339074/2127277
However, it seems it may not work : https://stackoverflow.com/a/60206450/2127277
And params is not documented https://developers.google.com/tag-platform/gtagjs/reference/events so perhaps the first SO link is wrong
- `env.COMMIT_HASH` is set within the webpack config [here](https://github.com/pass-culture/pass-culture-app-native/blob/master/web/config/env.js#L101)
- `agentType` is already set in `logEvent`, no need to pass it again
I have:
| Revision is in build | Analytics added |
|  ![image](https://user-images.githubusercontent.com/77674046/185587367-5f93a81e-440f-4dbd-8e3f-cb2f38cf7252.png)  | …

(PC-16938) fix(Web): set version and revision in analytics

---

src/api/__tests__/apiHelpers.test.ts
src/api/apiHelpers.ts
src/features/auth/login/Login.tsx
src/features/auth/login/Login.web.test.tsx
src/features/navigation/RootNavigator/types.ts
src/features/navigation/screenParamsUtils.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15156
I have:
https://user-images.githubusercontent.com/22886846/185447436-f98c7e3c-22d9-43e2-8eab-de765130c362.mov

(PC-15156) feat(login): show help message when user is forced to login because of refresh token expiration

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15891
I have:

(PC-15891) ci(search): remove instantsearch.js already installed by react-instantsearch-hook

---

__snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap
src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx
src/features/bookings/components/BookingDetailsTicketContent.tsx
src/features/bookings/pages/BookingDetails.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17108
I have:

(PC-17108) fix(Bookings): completedUrl instead of stock.offer.url

---

src/libs/amplitude/amplitude.web.ts
src/libs/storage.ts
src/libs/utm/getUtmParamsConsent.test.ts
src/libs/utm/getUtmParamsConsent.ts
src/libs/utm/storeUtmParams.test.ts
src/libs/utm/storeUtmParams.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17198
I have:

(PC-17198) feat(cookies): Store utm params only when user consents

---

doc/standards/codeStructure.md

- Actuellement la codebase suit partiellement le standard décrit ici, mais certaines parties semblent désorganisées. Le but de la PR est d'améliorer le standard d'archi du projet, trancher sur certains points (par exemple où mettre les tests: /tests ? /__test__? /__tests__?) et avoir une structure de code propre et lisible.
- Je propose de placer les tests directements à côté des composants/pages testés et de supprimer les dossiers /tests, /__test__, /__tests__...
- On a un dossier /theme et un sous-dossier /ui/theme. Cela porte un peu à confusion, je propose de renommer le sous-dossier /ui/theme en /ui/styleguide mais si vous avez d'autres idées n'hésitez pas
- Ajouter des TODO pour corriger la structure de code actuelle
- s'assurer que tous les devs sont formés à ce sujet
- intégrer la …

(BSR) docs(codeStructure): improve architecture standard

---

src/features/profile/pages/ChangePassword/ChangePassword.tsx
src/features/profile/pages/ChangePassword/schema/changePasswordSchema.test.ts
src/features/profile/pages/ChangePassword/schema/changePasswordSchema.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17254
- Au niveau des `onChange`, la page reflow avec ou sans `useCallback`, je n'ai pas trouvé comment éviter ça, je vais faire un 2nd POC avec `react-hook-form` : https://react-hook-form.com/
I have:

(PC-17254) fix(ChangePassword): improve formik form

---

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
__snapshots__/features/search/sections/tests/Category.native.test.tsx.native-snap
src/features/search/atoms/FilterRow.tsx
src/features/search/pages/Categories.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17311
I have:
|<img width="387" alt="Capture d’écran 2022-09-19 à 17 32 47" src="https://user-images.githubusercontent.com/78556024/191055816-ca5cd7fb-bae1-4a84-b561-0ed9daf826ee.png"> <img width="396" alt="Capture d’écran 2022-09-19 à 17 32 58" src="https://user-images.githubusercontent.com/78556024/191055826-8dd3fc29-a819-4bdb-b141-ebedc07d6922.png">|         |                 |                  |                  |
[2]: …

(PC-17311) fix(search): category after reset general filters

---

package.json
scripts/appcenter-download-release.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17575
I have:

(PC-17575) perf(AppCenter): Download and install appcenter apks in a command line

---

src/features/search/pages/useSearchResults.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildFilters.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildOfferSearchParameters.ts.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/tests/buildFilters.test.ts
src/libs/algolia/fetchAlgolia/fetchOffer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17201
Il c'est avéré que algolia d'une page à l'autre quand on scroll dans les résultats de recherche, retourne des offres déjà reçu.
Ceci à pour conséquence d'avoir des duplicates key dans la `FlatList`, ceci est vérifiable en modifiant le `useMemo` pour obtenir `hits` dans `useSearchResults.ts` par ceci:
```tsx
const hits = useMemo(
() => {
if (data?.pages) {
const allIDs = flatten(data?.pages.map((page) => page.hits.map((h) => h.objectID)))
const map = new Map()
allIDs.forEach((id) => {
if (map.get(id)) {
console.log('duplicate', id, 'in page', data?.pages[data?.pages.length - 1].page)
}
map.set(id, true)
})
}
return flatten(data?.pages.map((page) => page.hits.map(transformHits))).filter(
(hit) => typeof …
```

(PC-17201) fix(Search): exclude objectIDs from previous page to prevent duplicate

---

scripts/appcenter-download-release.sh
scripts/check_branch.sh
scripts/check_diff.sh
scripts/check_server_diff.sh
scripts/create_and_push_tag_from_package_json_version.sh
scripts/deploy.sh
scripts/deploy_new_production_version.sh
scripts/deploy_new_version.sh
scripts/get_version.sh
scripts/print_project_version.sh
scripts/release_staging_minor.sh
scripts/transition_jira_ticket.sh
scripts/update_app_version.sh
scripts/update_build_number_from_package_json_version.sh
scripts/upload_sourcemaps_to_sentry.sh

Problème rencontré :
Aujourd’hui, pas d’impossibilité technique de lancer un patch de staging si on est positionné sur master.
Cas de reproduction possible :
- On a fait une MES le jeudi `v1.X.Y`, testing passe donc à `testing/v1.(X+1).0`
- On se rend compte qu’on voudrait cherry pick de nombreux commits différents pour patcher la v1.X.Y → on se dit qu’il vaut mieux embarquer tout `master`
- On se place sur `master` et on lance `yarn trigger:staging:deploy:patch`
- Conséquence :
- comme la commande de tag se base sur la version du package.json et que le package.json de master correspond à la version de testing, on pose un tag `v1.(X+1).1` qui se déploie en staging. La mineure de staging est donc à nouveau alignée avec testing, alors qu’elle doit avoir une mineure de retard.
Cette PR …

(BSR) chore(deploy): prevent staging patches to be launched from the master branch

---

.github/workflows/pr-title-checker.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17625
I have:

(PC-17625) chore(PrTitleChecker): allow lint type

---

__snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferTypeChoices.test.tsx.native-snap
__snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferTypeChoices.test.tsx.web-snap
__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
src/features/_marketingAndCommunication/atoms/OfferTypeChoices.tsx
src/features/_marketingAndCommunication/atoms/__tests__/OfferTypeChoices.test.tsx
src/features/search/pages/OfferTypeModal.tsx
src/features/search/pages/__tests__/OfferTypeModal.native.test.tsx
src/features/search/sections/OfferType.tsx
src/features/search/sections/tests/OfferType.native.test.tsx
src/features/search/sections/tests/analytics.native.test.tsx
src/features/search/types.ts
src/locales/fr/messages.po

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17485
I have:

(PC-17485) refactor(SearchV2): remove duplicate offerType labels

---

src/features/auth/support.services.ts
src/features/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NavigationIdentityCheck.tsx
src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnectForm.tsx
src/features/identityCheck/pages/identification/errors/eduConnect/EduConnectErrors.ts
src/features/identityCheck/pages/identification/errors/eduConnect/NotEligibleEduConnect.tsx
src/features/identityCheck/pages/identification/errors/eduConnect/computePrimaryButtonToDisplay.test.tsx
src/features/identityCheck/pages/identification/errors/eduConnect/computePrimaryButtonToDisplay.tsx
src/features/identityCheck/pages/identification/errors/hooks/computePrimaryButtonToDisplay.tsx
src/features/identityCheck/pages/identification/errors/hooks/useNotEligibleEduConnectErrorData.test.ts
src/features/identityCheck/pages/identification/errors/hooks/useNotEligibleEduConnectErrorData.ts
src/ui/components/touchableLink/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12372
I have:
| <img width="352" alt="image" src="https://user-images.githubusercontent.com/89008469/192488367-2190bc0d-36f8-408e-aeda-73801868b09f.png"> |         |                 |                  |                  |

(PC-12372) feat(EduConnectErrors): Create a Duplicate User error screen

---

src/features/search/components/__tests__/SearchResults.native.test.tsx
src/features/search/pages/OfferTypeModal.tsx
src/features/search/pages/__tests__/OfferTypeModal.native.test.tsx
src/features/search/sections/tests/OfferType.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17486
I have:

(PC-17486) fix(searchV2): display duo offer when user is benificiary

---

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
src/ui/components/FilterSwitch.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17482
I have:
| Desktop - Chrome |  ![image](https://user-images.githubusercontent.com/77674046/193562347-a5204a6e-d466-4518-986e-95dabf3e9e6c.png)
|       |

(PC-17482) fix(FilterSwitch): show checked icon when not disabled and active

---

doc/installation/setup.md

Not having `jq` on your system will cause the following error if you try to build for iOS:
`The application's Info.plist does not contain a valid CFBundleVersion`

(BSR) docs(setup): add jq installation instruction

---

src/features/notifications/askNotificationsModal/components/AskNotificationsModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17516
I have:
| iOS              |<img width="333" alt="image" src="https://user-images.githubusercontent.com/68000368/194509119-868f0fe7-d508-4f02-a91b-95ecb1095ff2.png">| <img width="328" alt="image" src="https://user-images.githubusercontent.com/68000368/194508952-d67dc591-6e00-4c9f-b79b-91bdf477443c.png">|
| Android          |<img width="403" alt="image" src="https://user-images.githubusercontent.com/68000368/194509169-7f7ef14e-472f-41ef-8018-156047002ed1.png">|<img width="406" alt="image" src="https://user-images.githubusercontent.com/68000368/194508350-15473bf6-6ba5-4247-9236-34b037238fd5.png">|
[1]: …

(PC-17516) fix(Notifications): fix illustration size on modal

---

src/features/search/pages/LocationModal.tsx
src/libs/geolocation/GeolocationWrapper.tsx
src/libs/geolocation/__mocks__/index.ts
src/libs/geolocation/types.ts
src/ui/components/modals/AppModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17865
Tried portal and nested modal
Nested modal requires no lib but to have twice the modal rendered, which is not a problem since it was already available as a component.
I have:
| Android          |        |    ![image](https://user-images.githubusercontent.com/77674046/195380172-caabd29a-9cb4-4dae-a227-652adb2ac0ec.png)   |
| Desktop - Chrome |        |   ![image](https://user-images.githubusercontent.com/77674046/195380325-d01aad00-ff1b-44c0-b7ad-b48e4b7f34da.png)    | …

(PC-17865) fix(Search): fix iOS modal not opening

---

src/features/identityCheck/pages/identification/ubble/UbbleWebview.tsx
src/features/identityCheck/pages/identification/ubble/UbbleWebview.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17895
I have:
https://passcultureteam.slack.com/archives/C01APVCG22J/p1665751452342409
Après avoir complété le parcours ubble, avec le nouveau flux activé, la navigation de la webview vers la page "ta pièce d'identité a été transmise" plante et on se retrouve sur un écran blanc.
Le fix consiste à **naviguer explicitement vers la page IdentityCheckEnd** plutôt que d'utiliser le hook useIdentityCheckNavigation qui se retrouve perdu avec le nouveau flux.
Des tests en local on montré que le fix corrige le nouveau flux, et ne casse pas l'ancien (j'ai oublié de faire un screenshot)

(PC-17895) fix(ubbleFlow): fix navigation from ubble webview to identity check end

---

src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.test.tsx
src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.tsx
src/features/identityCheck/pages/identification/ubble/UbbleWebview.tsx
src/features/identityCheck/pages/identification/ubble/UbbleWebview.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17895
I have:
Même problème que cette PR https://github.com/pass-culture/pass-culture-app-native/pull/3768 mais sur la page IdentityCheckEnd

(PC-17895) fix(ubbleFlow): navigate explicitly to stepper after identitycheck end

---

src/features/search/pages/LocationModal.tsx
src/features/search/pages/__tests__/LocationModal.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18018
I have:

(PC-18018) fix(SearchV2): LocationModal close when opening settings

---

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap
src/features/search/sections/Location.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17362
I have:
| Tablet - Chrome  |  ![image](https://user-images.githubusercontent.com/77674046/196900060-80a9704c-38ef-4a6d-b399-e38a21e4fb68.png)      |  ![image](https://user-images.githubusercontent.com/77674046/196899894-9fb8eb53-603f-4212-9c45-302eb5eeacdc.png)|

(PC-17362) fix(SearchV2): SearchFilters use bicolor icon for location

---

src/features/navigation/helpers/isAppUrl.native.test.ts
src/features/navigation/helpers/navigateToBooking.native.test.ts
src/features/navigation/helpers/openUrl.native.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17493
I have:
L'event OpenExternalUrl remonte bien sur firebase. Étant donné que l'on teste déjà le comportement de tracking sur les liens externes, j'en ai profité pour refacto les tests helpers.test.ts de la feature navigation

(PC-17493) chore(navigation): reorganise navigation helpers tests

---

src/features/profile/components/SocialNetwork/SocialNetwork.stories.tsx
src/features/profile/components/SocialNetwork/SocialNetwork.tsx
src/features/profile/pages/Profile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17883
I have:
| iOS              |        |<img width="386" alt="image" src="https://user-images.githubusercontent.com/114914696/196664295-06f89527-5f8d-41e3-b3eb-79d5a375aa63.png">|
| Android          |        | <img width="347" alt="image" src="https://user-images.githubusercontent.com/114914696/196664552-cee2e842-52ca-4ee5-afd2-79e5c27e9f74.png">|
| Desktop - Chrome |<img width="1437" alt="image" src="https://user-images.githubusercontent.com/114914696/196664968-224be39c-d383-47f6-a601-fae4113bf771.png">|<img width="1438" alt="image" …

(PC-17883) fix(Profile): align social media icons on the left in large devices

---

android/app/proguard-rules.pro

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18151
Je pense qu'à la mise à jour de la librairie `react-native-keychain`, cette modification n'a pas été incluse, ce qui causait un crash pour les Android API 21 et 22 :
> <img width="809" alt="Capture d’écran 2022-10-24 à 13 50 43" src="https://user-images.githubusercontent.com/46637324/197519288-ce9dcd35-6dd5-4ad7-857d-9285af550e70.png">
I have:
[1]: …

(PC-18151) fix(keychain): Fix android crash for API 22 and lower

---

src/features/auth/login/Login.tsx
src/features/auth/signup/SetEmail/SetEmail.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17635
Apparemment les boutons étaient trop rapprochés ce qui causait des fausses manip de temps en temps
I have:
| iOS              |  ![simulator_screenshot_85085770-6276-4CE2-9181-9AAFC693CA5D](https://user-images.githubusercontent.com/46637324/198660481-431dda06-5cf4-4e3b-8263-5af04927d3b9.png) ![Simulator Screen Shot - iPhone 11 Pro Max - 2022-10-28 at 16 28 29](https://user-images.githubusercontent.com/46637324/198658971-c81bc0bd-96e8-4a63-a639-dc946cb2ac1c.png)     | ![Simulator Screen Shot - iPhone 11 Pro Max - 2022-10-28 at 16 53 13](https://user-images.githubusercontent.com/46637324/198660200-cf9904e7-0c9d-4312-9b23-2d1a090463b9.png) …

(PC-17635) fix(ui): Adjust spacing between Submit and Authentication buttons

---

.github/workflows/e2e-android-chrome.yml
.github/workflows/e2e-android-native.yml
.github/workflows/e2e-desktop-chrome.yml
.github/workflows/e2e-ios-native.yml
.github/workflows/e2e-ios-safari.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18308
Ajout des fichiers suivant:
```
├── e2e-android-chrome.yml
├── e2e-android-native.yml
├── e2e-desktop-chrome.yml
├── e2e-ios-native.yml
├── e2e-ios-safari.yml
```
Le contenu est minimaliste, ex :  
```yml
name: Tests e2e Desktop Chrome
on:
workflow_dispatch:
inputs:
tbd:
description: "tbd"
required: false
type: string
```
Leur présence sur `master` est nécessaire pour débuter l'intégration.

(PC-18308) ci(e2e): added empty workflows

---

__snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap
src/features/home/components/headers/HomeHeader.tsx
src/features/home/pages/Home.tsx

Il y avait un `Spacer.TopScreen` en trop ce qui ajoutait une marge qui décalait le titre de la home par rapport aux autres titres de l'app
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18334
I have:
| iOS              |    ![Simulator Screen Shot - iPhone 13 - 2022-11-04 at 10 33 14](https://user-images.githubusercontent.com/46637324/199940412-39bd1b86-da09-446d-a9ed-f24ca3000638.png) **Petit écran :** ![Simulator Screen Shot - iPhone 5s - 2022-11-04 at 10 33 15](https://user-images.githubusercontent.com/46637324/199940392-a391c138-b112-4c1f-b9ac-c28abfa383f8.png)    |   ![Simulator Screen Shot - iPhone 13 - 2022-11-04 at 10 32 …

(PC-18334) fix(home): Use reusable components for page title and fix top margin

---

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
src/features/home/components/headers/ThematicHomeHeader.native.test.tsx
src/features/home/components/headers/ThematicHomeHeader.tsx
src/features/home/pages/Home.tsx
src/features/navigation/TabBar/TabBar.tsx
src/features/navigation/TabBar/__tests__/TabBar.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17989
I have:
| Platform         | Before |
| iOS              |![Simulator Screen Shot - iPhone 13 - 2022-11-04 at 16 48 44](https://user-images.githubusercontent.com/22886846/200019108-4c68cda6-ff30-4a43-b85c-cb55a4f0d409.png)|
| Android          |<img width="295" alt="Capture d’écran 2022-11-04 à 16 48 32" src="https://user-images.githubusercontent.com/22886846/200019080-caddbffb-d11f-4305-a246-f0a95687c893.png">|
| Desktop - Chrome |<img width="1020" alt="Capture d’écran 2022-11-04 à 16 51 23" src="https://user-images.githubusercontent.com/22886846/200019340-4d662a40-2034-4211-a46f-69f25a6971c5.png">|
**pour le clic sur la flèche de retour** : …

(PC-17989) feat(ThematicHome): go back to home (without params) on press tab and go back button

---

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap
src/ui/components/accessibility/AccessibilityList.tsx

Lists should only have <Li /> elements as children for accessibility matters

(BSR) feat(AccessbilityList): move the separator inside the Li element

---

package.json
yarn.lock

PR pour corriger le build android qui fail avec cette erreur
D'après cet issue, il suffit de bumper la version de patch de RN pour corriger
https://github.com/facebook/react-native/issues/35210
Ça a fonctionné sur[ cette branche ](https://github.com/pass-culture/pass-culture-app-native/commits/test-build-android)
https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native?branch=test-build-android

(BSR) fix(build): bump react native patch version to fix android build

---

src/features/home/components/modules/exclusivity/ExclusivityModule.tsx

so if the component is not displayed, the style isn't either
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18664
I have:
| Phone - Chrome   | <img width="295" alt="image" src="https://user-images.githubusercontent.com/26742386/203020133-f755bc62-4d6b-4020-853e-8b9ae379c74a.png"> | <img width="295" alt="image" src="https://user-images.githubusercontent.com/26742386/203021831-dd90edce-f3b0-4576-b634-8abfd70f6ec2.png"> |
| Desktop - Chrome | <img width="1440" alt="image" src="https://user-images.githubusercontent.com/26742386/203020266-8d4da9c2-29c7-437e-98fe-bc8eabeb5291.png"> | <img width="1440" alt="image" …

(PC-18664) fix(home): move style to exclusivity module component

---

src/features/home/components/modules/exclusivity/ExclusivityBanner.tsx
src/features/home/components/modules/exclusivity/ExclusivityExternalLink.tsx
src/features/home/components/modules/exclusivity/ExclusivityModule.tsx
src/features/home/components/modules/exclusivity/ExclusivityOffer.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18833
I have:
| iOS (part 1) |        | <img width="511" alt="image" src="https://user-images.githubusercontent.com/26742386/203753971-031ec4a4-6a70-4673-afcc-af3934977465.png"> |
| iOS (part 2) |        | <img width="511" alt="image" src="https://user-images.githubusercontent.com/26742386/203754010-19384fab-34ca-46c2-adc7-882f009cde55.png"> |
| Phone - Chrome   | <img width="294" alt="image" src="https://user-images.githubusercontent.com/26742386/203753492-8957f1b3-b646-4d1c-910a-284abedfbe27.png">> | <img width="294" alt="image" src="https://user-images.githubusercontent.com/26742386/203753354-2c94c600-8d91-4552-b344-46c22764ac64.png"> |

(PC-18833) fix(home): propagate style to exclusivity components

---

src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx
src/features/search/pages/modals/PriceModal/PriceModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18908
I have:

(PC-18908) fix(search): only free offers when min & max prices at 0

---

android/app/src/main/java/com/passculture/MainActivity.java

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18972
I have:

(PC-18972) fix(android): avoid crash when re-entering the app

---

src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx
src/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx
src/features/identityCheck/pages/identification/dms/DMSIntroduction.native.test.tsx
src/features/identityCheck/pages/identification/dms/DMSIntroduction.tsx
src/features/identityCheck/pages/identification/identificationStart/ComeBackLater.native.test.tsx
src/features/identityCheck/pages/identification/identificationStart/ComeBackLater.tsx
src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx
src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx
src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx
src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.tsx
src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx
src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx
src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.test.tsx
src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18773
I have:

(PC-18773) feat(amplitude): add amplitude logs on identification and confirmation screens

---

package.json
yarn.lock

I have:
Renovate propose de bumper la version de cli-table mais la lib n'a pas l'air d'être réellement utilisée, elle avait été introduite dans ce commit https://github.com/pass-culture/pass-culture-app-native/commit/9775326e3eb56090579e0c6462c61ecad600e1e7 qui bumpait lingui. On n'utilise plus lingui donc on peut sans doute supprimer cli-table

(BSR) chore(deps): remove unused package cli-table

---

src/libs/geolocation/getPosition.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18521
**Vu avec la data**: pour garder la position précise de l'utilisateur on a décidé d'augmenter le temps de cache de la position en web (pas de spam depuis l'app) plutôt que d'arrondir la position de l'utilisateur et perdre en précision.
I have:
Avant:
https://user-images.githubusercontent.com/22886846/207003129-fe3fbffc-f9a3-4eb1-8baa-a0d3686211f3.mov

(PC-18521) fix(position): increase position cache time in web

---

.github/workflows/e2e-android-app.yml
.github/workflows/e2e-android-browser.yml
.github/workflows/e2e-browser-chrome.yml
.github/workflows/e2e-browser-firefox.yml
.github/workflows/e2e-browser-safari.yml
.github/workflows/e2e-ios-app.yml
.github/workflows/e2e-ios-browser.yml
e2e/config/wdio.shared.conf.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19213
I have:

(PC-19213) ci(e2e): move manuel e2e to #alertes-qa-manuel

---

doc/standards/testStrategy.md
src/features/navigation/__tests__/RootNavigator.native.test.tsx
src/features/navigation/__tests__/RootNavigator.web.test.tsx
src/features/navigation/__tests__/services.test.tsx

Unmount is made directly with jest, we don't need to use it at the end of our tests.

(BSR) test(Unmount): remove unmount when it is useless

---

src/features/home/components/headers/HomeHeader.native.test.tsx
src/features/home/components/headers/HomeHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18688
I have:
| iOS              | https://user-images.githubusercontent.com/89008469/207348773-f13a7a30-8fe4-4b29-8501-73412034a65d.mp4 | https://user-images.githubusercontent.com/89008469/207346934-4eeeff13-07cc-47bb-833c-a13ce78ed9dc.mp4 |

(PC-18688) feat(HomeHeader): use the same display condition as the system bloc on the NonBeneficiaryHeader Component

---

ios/PassCulture/Info.plist

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19243
J'ai bien testé sur un simulateur, ça build bien et je n'ai pas plus de modale de permission (j'ai toujours celle de géoloc comme avant)
Normalement, c'est 3 clés sont nécessaires seulement pour utiliser la géoloc en background (ce que nous ne faisons pas, ce qui se voit du fait qu'on a pas la capability BackgroundMode), mais Apple détecte de façon erronée que nous avons besoin de ces clés, donc on les rajoute quand même.

(PC-19243) fix(ios): add permission for location

---

e2e/tests/pc/helpers/FirstLaunch.ts
src/features/navigation/RootNavigator/useInitialScreenConfig.tsx
src/features/navigation/__tests__/useInitialScreenConfig.native.test.tsx
src/features/navigation/__tests__/useInitialScreenConfig.web.test.tsx
src/features/onboarding/pages/OnboardingWelcome.native.test.tsx
src/features/onboarding/pages/OnboardingWelcome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19246
I have:

(PC-19246) feat(onboarding): Redirect to new onboarding instead of tutorials

---

doc/standards/testStrategy.md
src/features/_marketingAndCommunication/atoms/__tests__/DeepLinkItem.web.test.tsx
src/features/auth/signup/SetEmail/SetEmail.native.test.tsx
src/features/auth/signup/SetPassword/SetPassword.native.test.tsx
src/features/auth/signup/SignupForm.native.test.tsx
src/features/bookings/helpers/getBookingLabels.test.ts
src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyThanks.native.test.tsx
src/features/home/components/modules/RecommendationModule.native.test.tsx
src/features/home/pages/Home.native.test.tsx
src/features/identityCheck/pages/profile/SetSchoolType.native.test.tsx
src/features/identityCheck/pages/profile/SetStatus.native.test.tsx
src/features/identityCheck/useSubscriptionSteps.test.tsx
src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx
src/features/search/pages/modals/OfferTypeModal/OfferTypeModal.native.test.tsx
src/libs/geolocation/GeolocationWrapper.test.tsx
src/libs/itinerary/openGoogleMapsItinerary.test.ts

Remove useless jest.clearMocks(), as it is run by default after each test, thanks to `clearMocks: true` in jest.config.js

(BSR) refactor(tests): remove useless clear mocks

---

src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/libs/firebase/analytics/__mocks__/analytics.ts
src/libs/firebase/analytics/analytics.ts
src/libs/firebase/analytics/events.ts

Cette PR a pour but de tracker des logs sur les offres similaires lorsqu'on scroll horizontalement visible sur Firebase.
Un test natif a été ajouté lorsqu'on scroll pour vérifier si l'event s'affiche correctement.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19294
I have:

(PC-19294) feat(offer): add log on similar offer on scroll

---

src/features/navigation/RootNavigator/linking/__tests__/getScreenConfig.test.ts
src/features/navigation/RootNavigator/linking/getScreenComponent.tsx
src/features/navigation/RootNavigator/withScreenWrapper.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17620
Goal is to have a unique identifier for detecting when a screen is displayed in e2e tests
- We cannot wrap in `NavigationContainer`  with a `View` (it has to be `RootStack.Screen`)
- Settings each `testID` in existing screen is cumbersome
I have:

(PC-17620) fix(RootNavigator): add and testID to all app screens

---

.github/workflows/e2e-android-app.yml
.github/workflows/e2e-android-browser.yml
.github/workflows/e2e-browser-chrome.yml
.github/workflows/e2e-browser-firefox.yml
.github/workflows/e2e-browser-safari.yml
.github/workflows/e2e-ios-app.yml
.github/workflows/e2e-ios-browser.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19412
When failure happen before running test, nos report goes up to slack, this fix it.
I have:

(PC-19412) ci(e2e): add logging even if failure

---

src/features/offer/pages/Offer/Offer.native.test.tsx
src/features/offer/pages/Offer/Offer.tsx
src/libs/firebase/analytics/__mocks__/analytics.ts
src/libs/firebase/analytics/analytics.ts
src/libs/firebase/analytics/events.ts

Cette PR a pour but de tracker des logs sur les offres similaires lorsqu'on scroll verticalement jusqu'à atteindre le bas de la page d'une offre, ces logs seront visible sur Firebase.
Deux test natif ont été ajouté : 
- lorsqu'on scroll bien jusqu'au bas de la page d'une offre, l'event s'affiche correctement .
- lorsqu'on ne scroll pas jusqu'au bas de la page l'event ne s'affiche pas.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19293
I have: …

(PC-19293) feat(offer): Add log on Offer on scroll vertical when reaching similar offers

---

src/api/gen/api.ts
src/features/auth/__mocks__/SettingsContext.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18120
I have:

(BSR) chore(api): Remove old feature flag from response

---

e2e/config/wdio.shared.conf.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19687
Exemple d'échec: https://github.com/pass-culture/pass-culture-app-native/actions/runs/3873041069/jobs/6602593942
Erreur:
```bash
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Error: Artifact path is not valid: /screenshots/202301091139_profile registration_should-click-on-"Créer-un-compte".png. Contains the following character:  Double quote "
Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n
```

(PC-19687) ci(e2e): fix not allowed pattern for artifact

---

src/features/home/api/useHomeRecommendedHits.native.test.ts
src/features/home/api/useHomeRecommendedHits.ts
src/features/home/fixtures/homepage.fixture.ts
src/features/home/types.ts
src/features/search/helpers/useFilterCount/useFilterCount.ts
src/features/search/types.ts
src/libs/contentful/adapters/modules/adaptRecommendationModule.ts
src/libs/contentful/fixtures/homepageNatifEntry.fixture.ts
src/libs/contentful/fixtures/recommendationNatifModule.fixture.ts
src/libs/contentful/types.ts
src/libs/recommendation/types.ts
src/libs/search/parseSearchParameters.test.ts
src/libs/search/parseSearchParameters.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19324
I have:
Pour remplacer isFree, on utilise priceMax = 0, ce qui donne : 
qui retourne bien des résultats
isFree ne remonte pas, et priceMax et priceMin remonte bien (pas d'offres proposées, je pense à cause du manque d'offre dispo pour les tests de l'API de reco)
[PC-19324]: https://passculture.atlassian.net/browse/PC-19324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(PC-19324) feat(contentful): handle is free and price min parameters

---

src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.native.test.tsx
src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19779
I have:

(PC-19779) fix(search): reset native category & genre when pressing suggestion

---

src/features/auth/signup/SetEmail/SetEmail.tsx
src/shared/forms/controllers/EmailInputController.tsx

This reverts commit 64d9a86eb88fcb240e00f08130369948f1382740.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19733
I have:

(PC-19733) fix(SetEmail): Revert use of input with spelling help"

---

src/api/gen/api.ts
src/features/bookings/components/OnGoingBookingsList.native.test.tsx
src/features/bookings/fixtures/bookingsSnap.ts
src/features/home/helpers/selectHomepageEntry.native.test.ts
src/features/home/helpers/selectHomepageEntry.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19371
I have:
Tests effectués : 
- Si beneficiaire 18 ans sans resa => homeEntryId : 62Th0gKULQPyTR9kJkXbnd (Page d'accueil 18 - sans réservation)
- Si beneficiaire 18 ans avec resa => homeEntryId : a7y5X9eAxgL4RLMSCD3Wn (Page d'accueil 18 - avec réservation)

(PC-19371) feat(selectHomepageEntry): display home pre reservation 18

---

src/features/home/components/modules/categories/CategoryBlock.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19233
I have:
| Desktop - Chrome | <img width="97" alt="image" src="https://user-images.githubusercontent.com/26742386/212287212-02a2185f-a1b2-4c38-88dc-81a103434ef9.png"> | <img width="94" alt="image" src="https://user-images.githubusercontent.com/26742386/212288226-66151314-6e02-4136-a514-ebda8c2c17a3.png"> |

(PC-19233) fix(categoryBlock): use white underline on hover

---

e2e/tests/pc/helpers/Browser.ts
e2e/tests/pc/helpers/FirstLaunch.ts
e2e/tests/pc/helpers/utils/deeplink.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19814
I have:

(PC-19814) ci(e2e): added openDeepLink that support iOS/Android/Web

---

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx
src/features/home/components/modules/HomeModule.tsx
src/features/home/components/modules/categories/CategoryListModule.native.test.tsx
src/features/home/components/modules/categories/CategoryListModule.stories.tsx
src/features/home/components/modules/categories/CategoryListModule.tsx
src/libs/firebase/analytics/analytics.ts

Ticket : https://passculture.atlassian.net/browse/PC-19987
Fix the logCategoryBlockClicked function so the event params are transmitted to firebase.
On the right screenshot you can see the moduleID, moduleListID ans toEntryId params
| firebase logCategoryBlockClicked            | <img width="329" alt="image" src="https://user-images.githubusercontent.com/89008469/213412424-ff4fa67c-1c1f-4e56-ab42-58fea26821d0.png"> | <img width="335" alt="image" src="https://user-images.githubusercontent.com/89008469/213411581-282c087f-4b2d-432c-ad68-b5fc77e9053c.png"> |
| firebase logModuleDisplayedOnHome        |  | <img width="350" alt="image" src="https://user-images.githubusercontent.com/89008469/213427521-d697758c-9a7b-4ec5-a …

(PC-19987) feat(logCategoryBlock): fix the params so they can be seen on firebase console

---

src/features/home/components/modules/HomeModule.tsx
src/features/home/components/modules/ThematicHighlightModule.native.test.tsx
src/features/home/components/modules/ThematicHighlightModule.stories.tsx
src/features/home/components/modules/ThematicHighlightModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19909
I have:
Dans Firebase DebugView, je vois un event avec le bon moduleType

(PC-19909) feat(analytics): add display tracker for thematic highlight module

---

__snapshots__/features/favorites/components/NotConnectedFavorites.test.tsx.native-snap
src/features/favorites/components/NotConnectedFavorites.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19697
I have:
| iOS small phone  (iPhone 5s)           |    ![Simulator Screen Shot - iPhone 5s - 2023-01-25 at 09 06 14](https://user-images.githubusercontent.com/46637324/214510755-a152b40c-2c02-47a3-893a-a7fe62db8069.png)    |  ![Simulator Screen Shot - iPhone 5s - 2023-01-25 at 08 59 37](https://user-images.githubusercontent.com/46637324/214510366-10f2a693-9913-4c87-9414-f6ee4e01536b.png)     |
| iOS big phone   (iPhone 13)          |  ![Simulator Screen Shot - iPhone 13 - 2023-01-25 at 09 06 13](https://user-images.githubusercontent.com/46637324/214510743-506c440e-45ca-49b4-a6dc-fb75e86cf0fc.png)     | …

(PC-19697) fix(ui): Center page with tabBar taken into account

---

src/features/home/components/headers/HomeHeader.tsx
src/features/home/pages/Home.native.test.tsx
src/features/home/pages/Home.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20054
I have:
| Platform         | Home N-1 with new deeplink | Home N-1 with old deeplink |
| Desktop - Chrome | <img width="1440" alt="image" src="https://user-images.githubusercontent.com/26742386/214352701-40e93a52-96eb-466d-8117-2897cb9a5ffa.png"> | <img width="1440" alt="image" src="https://user-images.githubusercontent.com/26742386/214352893-ba3f3762-b80c-43fa-8e26-844e62f5b467.png"> |
| Mobile - Chrome | <img width="375" alt="image" src="https://user-images.githubusercontent.com/26742386/214353313-90edc4f1-f848-42dd-94f7-ebbbdd99fd81.png"> | <img width="375" alt="image" src="https://user-images.githubusercontent.com/26742386/214353584-18f98d7b-2364-4c4 …

(PC-20054) feat(home): display thematic home title for old dynamic links

---

src/features/search/components/Hit/Hit.tsx
src/features/search/components/NativeCategoryValue/NativeCategoryValue.native.test.tsx
src/features/search/components/NativeCategoryValue/NativeCategoryValue.tsx
src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts

Cette PR a pour but de changer l'affichage des intitulés de résultats de recherche d'offres, qui aujourd'hui affiche les sous catégories. On affiche désormais les sous-catégories.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19822
I have:
| iOS              |![Capture d’écran 2023-01-24 à 13 26 32](https://user-images.githubusercontent.com/62058919/214291442-41591ade-8bea-43e1-9cf5-fd7e910ed38e.png)|![Capture d’écran 2023-01-24 à 13 24 00](https://user-images.githubusercontent.com/62058919/214291005-5bd19959-63c1-4983-8358-26011dbb75a1.png)|
| …

(PC-19822) feat(Hit): display nativeCategory (subCatgeory) label instead of categeory label

---

src/features/home/components/modules/ThematicHighlightModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20133
I have:
--> (https://www.notion.so/passcultureapp/Sur-la-Home-pour-un-module-Temps-Fort-l-opacit-sous-le-titre-se-coupe-net-4d01ae2a6df1476282c6f1ead047833d)
| iOS              | <img width="511" alt="image" src="https://user-images.githubusercontent.com/26742386/214816176-0355d2e2-1595-406c-bb08-71abe3595535.png"> | <img width="511" alt="image" src="https://user-images.githubusercontent.com/26742386/214816236-b260f07e-bc73-417d-b7cb-2b91586f7ac7.png"> |
| Phone - Chrome   | <img width="375" alt="image" src="https://user-images.githubusercontent.com/26742386/214817219-18462364-a3b9-4c34-9157-7317ff51c89c.png"> | <img width="377" alt="image" …

(PC-20133) fix(thematicHighlight): use the whole length for the title's background

---

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx.native-snap
src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.tsx
src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19097
I have:
| iOS selectIDStatus             | <img width="362" alt="image" src="https://user-images.githubusercontent.com/89008469/214589465-9e434980-5e03-43d2-b097-9d3b7bcbaa9f.png"> | <img width="389" alt="image" src="https://user-images.githubusercontent.com/89008469/214588831-255fd8ab-c98d-47cf-82a9-f9effd7e1883.png"> |
| iOS selectIDOrigin          | <img width="361" alt="image" src="https://user-images.githubusercontent.com/89008469/214589410-b1a151a8-d250-4c9f-8b98-80f23dfbcbfb.png"> | <img width="367" alt="image" src="https://user-images.githubusercontent.com/89008469/214588944-acaa9dbb-f43a-47a6-b5ad-d037dc4693 …

(PC-19097) feat(identityCheck): retour UX icon + separator

---

src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx
src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.web.test.tsx

replace flushAllPromise and act with waitFor To be closer to the user experience and be less tied to implementation and react life cycle details

(BSR) chore(SetPhoneNumber): replace flushAllPromise and act with waitFor

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/network_security_config.xml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20198
During e2e workflow android.app , it is necessary to allow clear text traffic from `10.0.2.2`, 
1. Create an `xml` directory in : `android/app/src/main/res/`
```bash
mkdir -p android/app/src/main/res/xml
```
2. Create file in `android/app/src/main/res/network_security_config.xml`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
<domain-config cleartextTrafficPermitted="true">
<domain includeSubdomains="true">10.0.2.2</domain>
</domain-config>
</network-security-config>
```
3. Edited `AndroidManifest.xml` by adding `android:networkSecurityConfig="@xml/network_security_config"` in `application`.
Source : https://medium.com/livefront/how-to-connect-your-android-emulator-to-a-local-web-service-47c380 …

(PC-20198) fix(Android): allow clear text traffic from 10.0.2.2

---

__snapshots__/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.native.test.tsx.native-snap
src/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20067
I have:
| Android          |        |<img width="351" alt="Capture d’écran 2023-01-26 à 16 53 36" src="https://user-images.githubusercontent.com/59031393/214883861-f6cc9c11-337b-4742-9f2e-061c9d0ddfc6.png">|
| Phone - Chrome   |        |<img width="326" alt="Capture d’écran 2023-01-26 à 16 53 56" src="https://user-images.githubusercontent.com/59031393/214883793-0330f026-92d5-4dbd-be57-0a0a7a18ebb0.png">|
| Desktop - Chrome |        |<img width="1439" alt="Capture d’écran 2023-01-26 à 16 54 18" …

(PC-20067) feat(resetPassword): fix blank space display on ios and android

---

src/features/home/components/modules/categories/CategoryListModule.tsx

"Uncaught Invariant Violation: Changing numColumns on the fly is not supported.
Change the key prop on FlatList when changing the number of columns to force a fresh render of the component."
I have:
Avant :  
https://user-images.githubusercontent.com/22886846/217029861-47a2addb-f9e2-4ce6-9c91-f4e0c79a182a.mov
Après :
https://user-images.githubusercontent.com/22886846/217029838-c92b8353-7521-47f8-8eb5-9d5faa5b5b6f.mov

(BSR) fix(CategoryListModule): add key prop to flatlist to avoid error

---

src/features/home/fixtures/homepage.fixture.ts
src/features/home/types.ts
src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts
src/libs/contentful/adapters/modules/adaptOffersModule.ts
src/libs/contentful/fixtures/algoliaModules.fixture.ts
src/libs/contentful/fixtures/movieGenres.fixture.ts
src/libs/contentful/fixtures/musicTypes.fixture.ts
src/libs/contentful/types.ts
src/libs/search/parseSearchParameters.native.test.ts
src/libs/search/parseSearchParameters.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18748
I have:
Pas possible de tester l'apparition de la playlist sur la home car les offres qui remontent n'ont pas d'image mais le call à algolia retourne bien des résultats : 

(PC-18748) feat(contentful): add music type filter to OffersModule

---

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
src/features/home/components/SignupBanner.native.test.tsx
src/features/home/components/SignupBanner.tsx
src/features/home/components/headers/HomeHeader.native.test.tsx
src/features/home/components/headers/HomeHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20135
I have:
| Platform         | Before |
| iOS              |![Simulator Screen Shot - iPhone 13 mini - 2023-02-16 at 16 48 14](https://user-images.githubusercontent.com/22886846/219429638-df94d323-ce95-4ae9-8819-f73c71318b33.png)|
| Android          |<img width="412" alt="Capture d’écran 2023-02-16 à 17 55 04" src="https://user-images.githubusercontent.com/22886846/219434102-6d8f4162-e034-4858-86a8-1961324806de.png">|
| Desktop - Chrome |<img width="1722" alt="Capture d’écran 2023-02-16 à 16 47 54" src="https://user-images.githubusercontent.com/22886846/219429345-2b27a6ec-901f-4bd0-89b4-84d9bbc009ec.png">| …

(PC-20135) feat(home): show signup banner when user is not logged in

---

.github/workflows/dev_on_workflow_linter_ts.yaml

The purpose of this PR is to make a linter (and typescript checker) on github-actions.
This workflow will not run for the moment, until we create a dev-on-push-workflow-main.yml with this type of code
```
name: Validate dev branch
on:
push:
jobs:
yarn-install:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- uses: actions/setup-node@v3
with:
node-version: 16
cache: 'yarn'
- uses: actions/cache@v3
id: yarn-modules-cache
with:
path: |
node_modules
~/.cache/yarn
key: v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
restore-keys: |
v1-yarn-dependency-cache-${{ hashFiles('**/yarn.lock') }}
v1-yarn-dependency-cache-
- run: yarn install --immutable
if: steps.yarn-modules-cache.outputs.cache-hit != 'true'
yarn-linter:
needs: yarn-install
uses: …
```

(PC-20476) feat(ci): check linter and typescript throught ci

---

src/libs/contentful/adapters/modules/adaptThematicHighlightModule.ts
src/libs/contentful/fixtures/thematicHighlightInfo.fixture.ts
src/libs/contentful/fixtures/thematicHighlightModule.fixture.ts
src/libs/contentful/types.ts

so that it can be reused in thematic highlight homes in a future ticket
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20029
I have:

(PC-20029) feat(contentful): use data from thematic highlight info

---

__mocks__/react-native-share.ts
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/shareMessagingOffer/InstalledMessagingApps.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20600
I have:
| iOS              |        |   [TestIOS.mov](https://user-images.githubusercontent.com/46637324/220690301-6fc903d4-494b-4c68-8f6f-eaca4b93b3c5.mov)   |
| Desktop - Chrome |        |   [TestWeb.mov](https://user-images.githubusercontent.com/46637324/220689342-8fe0845d-225f-4f81-b474-987b9fa7fd4c.mov)    |

(PC-20600) fix(MessagingApps): Separate webUrl from share url

---

src/libs/contentful/adapters/modules/adaptCategoryListModule.ts
src/libs/contentful/fixtures/categoryList.fixture.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20641
I have:

(PC-20641) feat(contentful): move category block info to its own content model

---

src/libs/firebase/analytics/__tests__/provider.native.test.ts
src/libs/firebase/analytics/__tests__/provider.web.test.ts
src/libs/firebase/analytics/provider.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20493
I have:

(PC-20493) fix(firebase): Return null for app instance id in web since it is not supported

---

.github/workflows/.sentryclirc
.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/dev_on_workflow_install.yml
.github/workflows/dev_on_workflow_linter_ts.yml
.github/workflows/dev_on_workflow_sentry_on_deploy.yml
.github/workflows/dev_on_workflow_tester.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19088
I have:
+ Use as much as possible github workflow to avoid duplicate code
+ Push the use of specific container when we can
+ Config sentry cli
+ Run bundle to publish for android and ios (currently comment to avoid duplicate push with circle)
+ Use slack notify to add a message when test are ok on master and deploy ok (will not run for the moment to avoid spam)

(PC-19088) feat(ci): Use github action to deploy soft testing

---

src/features/home/api/helpers/buildRecommendationOfferTypesList.native.test.ts
src/features/home/api/helpers/buildRecommendationOfferTypesList.ts
src/features/home/api/useHomeRecommendedHits.native.test.ts
src/features/home/api/useHomeRecommendedHits.ts
src/features/home/fixtures/homepage.fixture.ts
src/features/home/types.ts
src/libs/contentful/adapters/modules/adaptRecommendationModule.ts
src/libs/contentful/fixtures/recommendationNatifModule.fixture.ts
src/libs/contentful/types.ts
src/libs/recommendation/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18727
I have:
| Contentful Playlist reco avec musicTypes              | <img width="950" alt="image" src="https://user-images.githubusercontent.com/89008469/223495632-9433975d-9ac5-40f5-b974-76585afe66d7.png"> | <img width="591" alt="image" src="https://user-images.githubusercontent.com/89008469/223495454-100d1d7d-62de-4f7a-a4d7-268878882fe1.png"> |

(PC-18727) feat(Contentful): add a music types field for recommended playlist

---

src/features/profile/components/Badges/SubscriptionMessageBadge.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20807
When 3 KO ubble occur, the backend send a subscription message to the front with an error message and a redirection url to dms (app screen). 
Few month ago a a prop 'openInNewWindow' as been add to the ExternalTouchableLink with a default value set to true. Therefore, if no counter specification, an externalTouchableLink should open an external url. In our case, the openNewWindow prop wasn't set, which caused the link opening failure

(PC-20807) feat(DMSRedirection): fix DMS redirection after 3 KO Ubble

---

.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/dev_on_workflow_environment_deploy.yml

I have:
Add a distinction between soft and hard deploy for environment testing, for the moment it will only echo the environment to avoid building twice with circleci

(PC-19089) feat(ci): Use github action to deploy hard testing

---

src/features/bookOffer/components/BookingDetails.native.test.tsx
src/features/bookOffer/components/BookingDetails.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20952
I have:
| Phone - Chrome   |<img width="418" alt="Capture d’écran 2023-03-17 à 12 43 11" src="https://user-images.githubusercontent.com/78556024/225896254-e4a2a45c-3996-4c48-8f7d-3a3f8d522c40.png">|<img width="456" alt="Capture d’écran 2023-03-17 à 09 34 16" src="https://user-images.githubusercontent.com/78556024/225896291-6d475588-76df-4fbe-b8bf-69486a638ab0.png">|
[1]: …

(PC-20952) feat(bookOffer): dismiss modal when there is an error on booking confirmation

---

src/features/bookOffer/components/DuoChoice.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21145
I have:
| Desktop - Chrome | <img width="258" alt="CleanShot 2023-03-24 at 10 53 17@2x" src="https://user-images.githubusercontent.com/114916654/227488572-6601abb7-6d51-4501-9dd4-641db4aa01c6.png"> | <img width="244" alt="CleanShot 2023-03-24 at 10 54 12@2x" src="https://user-images.githubusercontent.com/114916654/227488714-2e957295-2974-4488-bf61-1cbf762daae6.png"> |
[1]: …

(PC-21145) fix(bookOffer): duo icon color choice

---

__snapshots__/features/share/pages/WebShareModal.web.test.tsx.web-snap
src/features/bookOffer/components/BookingCloseInformation.native.test.tsx
src/features/bookOffer/components/BookingCloseInformation.tsx
src/features/bookOffer/components/BookingDetails.native.test.tsx
src/features/bookOffer/components/BookingDetails.tsx
src/features/bookOffer/components/BookingEventChoices.tsx
src/features/bookOffer/components/BookingOfferModalHeader.tsx
src/features/bookOffer/helpers/useModalContent.test.tsx
src/features/bookOffer/helpers/useModalContent.tsx
src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
src/features/bookOffer/pages/BookingOfferModal.tsx
src/ui/svg/icons/BicolorInfo.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21120
I have:
| iOS              |        |<img width="428" alt="Capture d’écran 2023-03-28 à 15 21 09" src="https://user-images.githubusercontent.com/62058919/228250231-4e38b691-57c3-496f-9160-8bf92da8c78b.png">|
| Android          |        |<img width="412" alt="Capture d’écran 2023-03-28 à 14 53 03" src="https://user-images.githubusercontent.com/62058919/228242322-0e064405-111a-4551-9827-bb699cf637e0.png">|
| Desktop - Chrome |        |<img width="1282" alt="Capture d’écran 2023-03-28 à 14 58 28" …

(PC-21120) feat(BookingCloseInformation): add booking close modale information when the booking is loading

---

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap
src/features/identityCheck/components/StepButton.stories.tsx
src/features/identityCheck/components/StepButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21060
On a [previous PR ](https://github.com/pass-culture/pass-culture-app-native/pull/4596) I accidentaly introduced a design bug by changing the label color condition.
This PR fixes the bug + add new snapshots tests to highligth any design changes on the stepButtons
I have:
| iOS              | <img width="386" alt="image" src="https://user-images.githubusercontent.com/89008469/229460705-74180a3c-3c7a-4037-8b86-edec3f7f9a55.png"> | <img width="384" alt="image" src="https://user-images.githubusercontent.com/89008469/229477811-e2b41342-d26d-42e7-95ba-d1ec39d8ecf3.png"> |
| Desktop - …

(PC-21060) chore(stepButton): fix step button label colors

---

src/features/identityCheck/components/StepButton.native.test.tsx
src/features/identityCheck/components/StepButton.tsx

StepButton should be enable if stepState is CURRENT or RETRY. In previous version, RETRY state was disabled
I have:
| iOS              | [ retry button disabled](https://user-images.githubusercontent.com/89008469/230593527-944d9eea-e105-49ad-a836-b497b914ddc5.mp4) | [retry button enabled](https://user-images.githubusercontent.com/89008469/230593373-3159412c-4c80-4bee-b884-3b5f8706b4c0.mp4) |

(BSR) feat(StepButton): fix stepButton wrongly disabled

---

.circleci/config.yml

Suite au passage à iOS 16, il faut qu'on build iOS sur une version d'Xcode >14.1. Cette PR met à jour la version indiquée pour CircleCI.
Cf.: https://developer.apple.com/news/?id=jd9wcyov

(BSR) chore(circleCI): update Xcode version

---

src/api/getCodePushId.native.test.ts
src/api/getCodePushId.ts

(BSR) feat(getCodePushId): Fetch metadata once

---

src/features/home/pages/GenericHome.tsx

Le spinner reste toujours afficher en web, alors que le chargement progressif n'est pas implémenté.
I have:
| iOS              |        |   https://user-images.githubusercontent.com/46637324/235642693-dbe587a7-35f2-4e8a-9569-11c285b64579.mp4    |
| Desktop - Chrome |        |      <img width="717" alt="Capture d’écran 2023-05-02 à 12 14 41" src="https://user-images.githubusercontent.com/46637324/235642674-eaa71e0a-0eb6-485e-93e8-b0f9552eef23.png"> |

(BSR) fix(home): Dont display spinner on web

---

src/features/auth/components/PasswordSecurityRules.tsx
src/features/auth/pages/suspendedAccount/SuspendedAccount/SuspendedAccount.tsx
src/features/favorites/components/FavoritesResults.tsx
src/features/navigation/RootNavigator/linking/__mocks__/withAuthProtection.tsx
src/features/navigation/RootNavigator/linking/withAuthProtection.tsx

N°1 : [Prefer using nullish coalescing operator (`??`) instead of a logical or (`||`), as it is a safer operator.](https://sonarcloud.io/project/issues?resolved=false&rules=typescript%3AS6606&types=CODE_SMELL&id=pass-culture_pass-culture-app-native&open=AYfcmBJq1_2M_ybCqkZo)
**Exemple de résolution** : https://github.com/pass-culture/pass-culture-app-native/pull/4761/commits/c4d33e8ef1a36ad7dc59506802b61b8f0edd3439
**Pourquoi cette règle ?**
_L'opérateur `??` retourne la première valeur qui n'est pas `null` ou `undefined`. Cela signifie qu'il ne remplacera pas les valeurs `falsy` par une valeur de secours, contrairement à l'opérateur `||`. Il est plus sûr que l'opérateur `||` car il n'interprète pas certaines valeurs `falsy` (comme la chaîne de caractères vide) comme n'étant pas …

(BSR) fix(sonar): fix some new Sonar issues

---

server/src/utils/metas.ts
server/src/utils/tests/__snapshots__/metas.test.ts.snap

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21532
On soupçonne que React écrase le contenu du body pour afficher les pages qu'il veut, donc on déplace les métadonnées  à la fin de la balise `head`
I have:

(PC-21532) feat(proxy): move metadata to the end of head

---

src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx
src/features/offer/components/OfferHeader/OfferHeader.tsx
src/ui/components/buttons/RoundedButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22096
I have:
https://user-images.githubusercontent.com/62058919/236169606-4c601c64-e99a-4484-b9cf-d4e772eef712.mov

(PC-22096) fix(OfferHeader): fix double Tap / click causes blocking of favorites / removal from the offer consultation

---

src/features/identityCheck/pages/profile/SetSchoolType.native.test.tsx
src/features/identityCheck/pages/profile/SetSchoolType.tsx
src/features/identityCheck/pages/profile/SetStatus.native.test.tsx
src/features/identityCheck/pages/profile/SetStatus.tsx

I have:
| iOS              |        |    
https://github.com/pass-culture/pass-culture-app-native/assets/47600889/a5baa0df-94e1-4ec7-b5a3-41c6f9a0f1dc
|

(PC-21980) fix(identification): add forward navigation to profile step screens

---

__snapshots__/features/trustedDevice/pages/SuspensionChoice.native.test.tsx.native-snap
src/features/internal/cheatcodes/pages/NavigationTrustedDevice/NavigationTrustedDevice.tsx
src/features/navigation/RootNavigator/trustedDeviceRoutes.ts
src/features/navigation/RootNavigator/types.ts
src/features/trustedDevice/pages/SuspensionChoice.native.test.tsx
src/features/trustedDevice/pages/SuspensionChoice.tsx
src/features/trustedDevice/pages/SuspensionChoice.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21674
I have:
| Phone - Chrome   |        | <img width="396" alt="Capture d’écran 2023-06-01 à 14 05 05" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/ba188e23-0250-416c-848b-b33f9be53da8"> |

(PC-21674) feat(TrustedDevice): add SuspencionChoice screen and tests

---

e2e/tests/pc/helpers/FeatureClient.ts
src/api/gen/api.ts

The endpoint will be used by tests of the pro portal as well, so it
has been moved from the app API schema.
See pass-culture/pass-culture-main@a61e144c012dc8df219b317f6784327288bc2d63.

(BSR) test(e2e): Use new URL to toggle feature flags in e2e tests

---

src/features/bookings/components/BookingDetailsCancelButton.native.test.tsx
src/features/bookings/components/BookingDetailsCancelButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22621
I have:
| Desktop - Chrome |![Capture d’écran 2023-06-07 à 17 22 00](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/1490d4a4-9f4e-4a93-a744-4666f036c6d6)|![Capture d’écran 2023-06-07 à 17 22 12](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/908329ea-3ba3-4abf-912f-46cded088cb3)| …

(PC-22621) feat(BookingDetailsCancelButton): fix the display of the button depending on whether they are free physical offers

---

src/features/home/components/modals/VideoModal.native.test.tsx
src/features/home/components/modals/VideoModal.tsx
src/features/home/components/modules/VideoModule.native.test.tsx
src/features/home/components/modules/VideoModule.tsx
src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22421
I have:
| iOS              |[Uploading Simulator Screen Recording - iPhone 13 - 2023-06-08 at 18.18.52.mp4…](https://github.com/pass-culture/pass-culture-app-native/assets/22886846/e693a9de-f52c-4a89-ae07-3026601e7004)|
| Android          |https://github.com/pass-culture/pass-culture-app-native/assets/22886846/65e51cbb-1f69-4568-b617-8dcbdc6667f5|

(PC-22421) home(VideoModule): show VideoModal from home VideoModule

---

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/auth/pages/signup/SignupFormV2.tsx
src/features/bookings/components/BookingDetailsHeader.tsx
src/features/home/components/headers/ThematicHomeHeader.tsx
src/features/identityCheck/components/layout/PageWithHeader.tsx
src/features/offer/components/OfferHeader/OfferHeader.tsx
src/features/venue/components/VenueHeader/VenueHeader.tsx
src/ui/animations/helpers/getAnimationState.ts
src/ui/components/BlurView.tsx
src/ui/components/BlurView.web.tsx
src/ui/components/headers/AnimatedBlurHeader.tsx
src/ui/components/headers/BlurHeader.tsx
src/ui/components/headers/BlurHeader.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20703
I have:
Changes only for Android
| :-: | :-: |
| <img width="292" alt="Capture d’écran 2023-06-13 à 23 47 21" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/4db5c131-0d25-4779-b9ef-5606b1447154"> | <img width="284" alt="Capture d’écran 2023-06-13 à 23 46 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/64484b24-276c-4a0c-91c2-a415d8c3709d"> |
|<img width="1512" alt="Capture d’écran 2023-06-15 à 13 47 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/753777c7-47a1-409a-9df2-4c486cbd1876">|<img width="1512" alt="Capture d’écran 2023-06-15 à 13 53 02" …

(PC-20703) fix(Header): set header in white for android

---

src/features/home/components/modules/VideoModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22172
Tested on Android and iOS
I have:
| iOS              |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/aab30e06-66ac-4c64-a9d0-03a268c809a7|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/35f8601d-4b81-4123-a02c-577babbd4a5b|

(PC-22172) fix(video): add a white underlay on VideoModule player press

---

src/features/bookOffer/components/BookingDetails.tsx
src/features/bookings/components/BookingExpiration.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22611
I have:
| Desktop - Chrome |        |![Capture d’écran 2023-06-15 à 14 21 49](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/0163ca87-2c1b-48b2-8ceb-12f01202e54c)![Capture d’écran 2023-06-15 à 14 22 22](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/a2f0c3e7-1cb8-46ee-9304-d9bcd0e11bfa)|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a75 …

(PC-22611) fix(BookingDetails): fix spacing and cancelletion details display when offers are free

---

src/features/home/components/helpers/getGradientColors.native.test.ts
src/features/home/components/helpers/getGradientColors.ts
src/features/home/components/modules/OfferVideoModule.tsx
src/features/home/components/modules/VideoModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22765
I have:
2 exemples de couleurs :
| iOS              | <img width="325" alt="Capture d’écran 2023-06-19 à 16 04 21" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/d274bf8f-233b-40c6-bfe4-c7d3b53fd396"> | <img width="330" alt="Capture d’écran 2023-06-19 à 16 04 30" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/d10b4f63-e739-4fef-8b33-824b18990936"> |
| Android          | <img width="294" alt="Capture d’écran 2023-06-19 à 16 04 40" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/decc878b-7b28-415d-84ff-3e55628c7e4a"> | <img width="275" alt="Capture …

(PC-22765) feat(VideoModule): update color to be dynamic

---

android/app/src/main/java/com/passculture/DefaultBrowserModule.java
android/app/src/main/java/com/passculture/DefaultBrowserPackage.java
android/app/src/main/java/com/passculture/MainApplication.java
src/features/navigation/helpers/openUrl.native.test.ts
src/features/navigation/helpers/openUrl.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22517
I have:
| Platform         | Si un browser disponible | Si aucun browser disponible |
| Android          |   [available_browser.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/119bc93f-da0e-443b-9ada-06b4c5279c2f)    |   [no_available_browser.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/35061da5-6014-4f6b-84a2-1838269506c8)   |

(PC-22517) fix(openUrl): Open external url in browser for Android

---

__snapshots__/features/home/components/modals/VideoModal.native.test.tsx.native-snap
src/features/home/components/VideoPlayer.tsx
src/features/home/components/helpers/getVideoPlayerDimensions.native.test.ts
src/features/home/components/helpers/getVideoPlayerDimensions.ts
src/features/home/components/modals/VideoModal.tsx
src/features/home/components/modules/OfferVideoModule.native.test.tsx
src/features/home/components/modules/OfferVideoModule.tsx
src/features/home/components/modules/VideoModule.tsx
src/features/home/components/modules/video/ButtonWithCaption.tsx
src/features/home/components/modules/video/VideoEndView.native.test.tsx
src/features/home/components/modules/video/VideoEndView.tsx
src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts
src/ui/svg/icons/Offers.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21766
I have:
| Platform         | Screenshot video | 
| Android          |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/99ef244a-36c4-41ff-bf9f-a54d990ec15a|  
| iOS          |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/7f84b7ab-ab1e-48c4-bd69-8e50e5535d29|  

(PC-21766) feat(video): add calque to video when it ends

---

package.json
src/features/search/pages/Search/Search.perf.test.tsx
src/features/venue/pages/Venue/Venue.perf.test.tsx

(BSR) test(perf): Use different node env for performance tests

---

__snapshots__/features/home/components/modals/VideoModal.native.test.tsx.native-snap
src/features/home/components/modules/OfferVideoModule.native.test.tsx
src/features/home/components/modules/OfferVideoModule.tsx
src/theme/index.ts
src/ui/components/tiles/OfferImage.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22963
I have:
| Platform         | Before | After | After with placeholder |
| :--------------- | :----: | :---: | :-: |
| iOS              |        |       |   |
| Phone - Chrome   | <img width="375" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/33a53f45-21d4-48ea-af17-1a7c6685ae66"> | <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/f6b9cf65-4106-459e-babe-a6df59c79b78"> | <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/2c0360c8-74ed-4a72-b4ef-178c3c0773af"> |
| Desktop - Chrome |        |       |   |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-su …

(PC-22963) feat(videoModule): use placeholder when no offer image provided 

---

README.md
package.json
scripts/generate_api_client_silicon.sh

Les développeurs sous puces Apple Silicon ne peuvent pas lancer `generate:api:client`.
J'ai donc créé un script `generate:api:client:silicon` pour remédier à cela en attendant que [cette PR](https://github.com/swagger-api/swagger-codegen/pull/11772) de chez Swagger soit mergée.

(BSR) chore(api): add script to allow generating codegen on silicon

---

server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap
server/src/middlewares/tests/webAppProxyMiddleware.test.ts
server/src/services/apiClient.ts

We chose to use the staging proxy, because the offer/venue data doesn't change every week: when using testing proxy, the snapshots were broken every Thursday.
The inconvenient is that, if the backend changes and breaks the offer/venue data model, we only see the issue after deploying to staging, but we think that the risk is low enough, so it is negligible.

(BSR) test(proxy): fix flakiness by using staging backend

---

__snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap
src/features/home/components/modules/video/VideoModal.tsx
src/features/home/components/modules/video/VideoMultiOfferTile.tsx
src/ui/components/modals/AppModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23326
I have:
| iOS - fix scroll  |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/d1deae7a-54c3-4a10-a42b-d5ad5e0c3051|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/230548df-1760-49c3-bb9b-4f1cfd7bfb5f|
| Android - fix scroll  |    --    |[after_android.webm](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/68409a43-d8a2-4f4b-bf8e-e8393571acf6)|
| iOS - fix tile  |![before_tile](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/35b71021-1d86-4ac6-913f-444974b18c02)|![after_tile](https://github.com/pass-culture/pass-culture-app-n …

(PC-23326) fix(video): fix swipe and scroll inside modale + design

---

src/features/home/api/useVideoOffer.ts
src/features/home/components/modules/video/VideoModule.tsx
src/features/home/fixtures/videoModule.fixture.ts
src/features/home/types.ts
src/libs/contentful/adapters/modules/adaptVideoModule.ts
src/libs/contentful/fixtures/videoContentModel.fixture.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23134
On ré-utilise `fetchOfferHits` qui permet déjà de faire des requêtes d'offres par id.
Côté Contentful le champ ID d'offres accepte une liste d'IDs
Si le champ est complété la playlist sera ignorée.
L'affichage du composant vidéo mono ou multi-offre est conditionné au nombre d'offres que l'on récupère suite à la requête Algolia (fonctionnement idem que pour le cas d'une playlist) 
I have:
| Platform         | Mono-offer | Multi-offer |
| iOS |<img width="1512" alt="Capture d’écran 2023-07-17 à 14 00 48" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/1be5fd31-ad50-4f58-8c22-93b3670a9987">|<img width="1512" alt="Capture d’écran 2023-07-17 à 14 00 08" …

(PC-23134) feat(video): add the possibility to set video module offers by ID

---

src/features/home/components/modules/HomeModule.native.test.tsx
src/features/home/components/modules/HomeModule.tsx
src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23167
I have:
feature flag (en v260) pour simuler le nouveau bloc exclu non sorti -> affichage de l'actuel bloc exclu :
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/e8120aa4-ee77-4fda-a83c-f5b5c5bbf6af
feature flag (en v220) pour simuler l'arriver du nouveau bloc exclu -> non affichage de l'actuel bloc exclu :
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/92caf8f1-beb2-4730-86d4-33d63c71ee9b
les features flags (v260) en testing, staging et prod :
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/1cd9903a-9a69-4279-8b34-ffbf333fa6b6

(PC-23167) feat(HomeModule): add a feature flag for future new exclusivity block 

---

__snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityActionPlan.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclaration.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityEngagement.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/RecommendedPaths.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx.native-snap
__snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
__snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap
src/features/profile/components/PageProfileSection/PageProfileSection.tsx
src/ui/components/headers/PageHeaderWithoutPlaceholder.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21531
I have:
rapide screenVidéo (pour bien montrer le blur) :
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/b05aa8eb-d708-4eed-a79c-8cce01001211
Toutes les pages : 
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/180d4b56-b17a-4768-9745-226c6793bf6d
Platform | Before | After |
iOS | <img width="354" alt="Capture d’écran 2023-07-25 à 13 47 54" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/4fa47887-69a5-4707-aea6-cea0fc98df54"> | <img width="354" alt="Capture d’écran 2023-07-25 à 13 46 04" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/6d8e9971-cd2a-4010-b99c-6712306ae9e6"> |
Android | <img width="331" …

(PC-21531) feat(Profile): transition to blur header in profile

---

src/features/identityCheck/pages/profile/SetStatus.tsx

I have:
Avant:
https://github.com/pass-culture/pass-culture-app-native/assets/22886846/e628fe58-cfee-4fd6-bcc4-6d8c3c425adf
Après:
https://github.com/pass-culture/pass-culture-app-native/assets/22886846/c643fe01-4474-4d94-98e1-8aaf8c238c41

(BSR) fix(profileStep): make sure we put profile information in subscription contexte before calling API

---

__snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap
__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
src/features/home/pages/GenericHome.tsx
src/features/profile/pages/Profile.tsx
src/ui/components/headers/AnimatedBlurHeader.tsx
src/ui/components/headers/BlurHeader.tsx
src/ui/components/statusBar/statusBarBlurredBackground.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21416
I have:
| iOS              | <img width="352" alt="Capture d’écran 2023-07-28 à 13 58 27" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/b8f1afc8-f01f-4f70-a221-3f396dd88314"> | <img width="352" alt="Capture d’écran 2023-07-28 à 13 58 00" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/19416e4c-004e-4cf3-821c-7dca6ed81768"> |
| Android          | <img width="336" alt="Capture d’écran 2023-07-28 à 13 58 45" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/82317999-6017-437c-afc8-7e81ae643fc8"> | <img width="336" alt="Capture d’écran 2023-07-28 à 13 …

(PC-21416) feat(statusBar): blur/white status bar home and profile

---

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
src/features/profile/pages/Profile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21416
I have:
| iOS              | <img width="353" alt="Capture d’écran 2023-08-01 à 12 06 38" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/81514448-d660-4b05-a234-019df65defc3"> | <img width="350" alt="Capture d’écran 2023-08-01 à 12 05 32" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/6f06a046-d011-40de-8138-bcbcfd9602ac"> |
| Android          | <img width="334" alt="Capture d’écran 2023-08-01 à 12 07 58" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/1d78fbf3-35ba-449d-807d-110a200c3f20"> | <img width="333" alt="Capture d’écran 2023-08-01 à 12 …

(PC-21416) fix(statusBar): flex the container of Profile page

---

src/features/home/components/modules/HighlightOfferModule.tsx
src/features/home/components/modules/video/VideoModuleDesktop.tsx
src/features/home/components/modules/video/VideoModuleMobile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23231
I have:
VideoModule et HighlightModule, image enlever manuellement :
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/929b3eae-2afa-4e86-976f-21256855b950
HighlightModule, tester avec simulateur de connexion:
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/273a0921-4420-42a3-bea3-2115033a4bb5
VideoModule, au clic:
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/eb0232bd-9023-4f0d-ac6c-15ec9d45a508
Version Web Vidéo Module:

(PC-23231) feat(Module): add grey background on Video Thumbnail and Highlight Image for accessibility

---

src/features/bookings/components/BookingDetailsCancelButton.native.test.tsx
src/features/bookings/components/BookingDetailsCancelButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23707
I have:
| iOS              |![Capture d’écran 2023-08-04 à 12 46 32](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/951c9abd-a092-444a-bf0d-c5acfc4983c7)|![Capture d’écran 2023-08-04 à 12 43 51](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/fef5286d-9b46-4c5f-814b-177b26a1ee5f)|
| Android          |![Capture d’écran 2023-08-04 à 12 46 24](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/064b6a85-1946-41dc-a4ec-8d8b494900ae)|![Capture d’écran 2023-08-04 à 12 43 56](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/5 …

(PC-23707) fix(booking): display cancel button when it's an offer to archieve and it's not free

---

package.json
yarn.lock

Le déploiement web échoue depuis ce commit https://github.com/pass-culture/pass-culture-app-native/commit/072d5439609629c602a7fe617a7be12444eb8d3a
`````
yarn run v1.22.18
$ ENV=testing yarn build
$ SHOW_DUPLICATES_PLUGIN=${SHOW_DUPLICATES_PLUGIN:-true} node web/scripts/build.js
Creating an optimized production build...
Compiled with warnings.
Duplicate Sources / Packages - Duplicates found! ⚠️
* Duplicates: Found 34 similar files across 68 code sources (both identical + similar)
accounting for 403112 bundled bytes.
* Packages: Found 2 packages with 2 resolved, 4 installed, and 9 depended versions.
`````
`````
yarn run v1.22.18
$ ENV=testing yarn build
$ SHOW_DUPLICATES_PLUGIN=${SHOW_DUPLICATES_PLUGIN:-true} node …
```

(BSR) fix(deploy): fix duplicate error in web deploy process

---

src/features/home/components/modules/categories/CategoryBlock.tsx

by using margin instead of padding for a text
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22468
I have:
| Desktop - Chrome | <img width="1025" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/b79adfc9-6513-429a-b400-1aebdc94d1fc"> | <img width="1026" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/8be3d577-8f06-4d13-a793-f08f536b3bb8"> |

(PC-22468) fix(category): limit text height

---

src/ui/animations/helpers/getAnimationState.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23962
I have:
| iOS              |        | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/c489562d-7dfa-4838-a1c3-29697c231cf2"> |
| Phone - Safari   | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/e328f396-0f96-49b0-bc4f-d5db513cb8f2"> | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/7cb62617-1eef-47a6-9dde-b8d914f56c06"> |
| Desktop - Safari | <img width="1436" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/7bd8202a-7775-4fcc-ba0a-2 …

(PC-23962) fix(safari): fix blur on offer header

---

.eslintrc.js
doc/development/how-to/eslint-custom-rule.md
eslint-custom-rules/__tests__/no-hardcoded-id-in-svg.test.js
eslint-custom-rules/no-hardcoded-id-in-svg.js
eslint-local-rules.js
src/ui/svg/icons/Ubble.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24042
https://www.notion.so/passcultureapp/SVG-utiliser-des-id-variables-au-lieu-d-id-en-dur-deac58a24a1241db89310b783fbb0feb?pvs=4

(PC-24042) feat(eslint): add rule to avoid hardcoded id in svg

---

__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap
src/features/search/components/SearchVenueItems/SearchVenueItem.tsx
src/features/search/components/SearchVenueItemsDetails/SearchVenueItemDetails.native.test.tsx
src/features/search/components/SearchVenueItemsDetails/SearchVenueItemDetails.tsx
src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.native.test.ts
src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24058
I have:
| iOS              |<img width="467" alt="Capture d’écran 2023-08-28 à 18 36 09" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/738f68cc-80a4-47cd-a6f5-418b6783b96e">|<img width="443" alt="Capture d’écran 2023-08-28 à 18 29 32" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/edaad123-c92d-49fd-8c95-d942a8037adc"> <img width="470" alt="Capture d’écran 2023-08-28 à 18 42 35" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/90595a91-559b-4498-9d6f-e0233ece2b12">|
| Android          |<img width="432" alt="Capture …

(PC-24058) feat(search): force min height for venue playlist item

---

.github/workflows/dev_on_workflow_web_proxy_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23621
Test CI: https://github.com/pass-culture/pass-culture-app-native/actions/runs/6001805852/job/16276796309#step:12:25
During deployment: 
```
$ gcloud app versions list --service=web-proxy-testing 
SERVICE            VERSION.ID       TRAFFIC_SPLIT  LAST_DEPLOYED              SERVING_STATUS
web-proxy-testing  20230720t163425  0.00           2023-07-20T18:35:59+02:00  SERVING
web-proxy-testing  20230828t152440  1.00           2023-08-28T17:26:10+02:00  SERVING
```
After deployment:
```
$ gcloud app versions list --service=web-proxy-testing 
SERVICE            VERSION.ID       TRAFFIC_SPLIT  LAST_DEPLOYED              SERVING_STATUS
web-proxy-testing  20230828t153356  1.00           2023-08-28T17:35:07+02:00  SERVING
```
I …

(PC-23621) fix(proxy): clean unused proxy instances

---

src/features/search/components/SearchListHeader/SearchListHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24066
I have:
| iOS              |<img width="470" alt="Capture d’écran 2023-08-29 à 15 04 55" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/84a4e950-3a51-4258-bde4-9987830666cb">|<img width="465" alt="Capture d’écran 2023-08-29 à 14 56 03" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/da959a08-313a-4f68-9e41-718e34cabd99">|
| Android          |<img width="455" alt="Capture d’écran 2023-08-29 à 15 04 48" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/8bfe6d61-22bd-4888-a641-2cb7a68338f1">|<img width="455" alt="Capture …

(PC-24066) fix(search): remove separator when no search venues playlist

---

src/features/location/components/LocationWidget.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22949
I have:

(PC-22949) fix(ui): add left margin to LocationWidget

---

__snapshots__/features/trustedDevice/pages/SuspensionChoice.native.test.tsx.native-snap
src/features/trustedDevice/pages/SuspensionChoice.native.test.tsx
src/features/trustedDevice/pages/SuspensionChoice.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24162
I have:

(PC-24162) fix(AccountSuspension): Direct user to fraud instead of support

---

src/features/home/components/modules/HighlightOfferModule.native.test.tsx
src/features/home/components/modules/HighlightOfferModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23831
I have:
| Platform         | Not duo offer | Duo offer |
| iOS              |![Simulator Screen Shot - iPhone 14 - 2023-09-01 at 11 10 39](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/50918ce2-5823-4ad4-98e4-87c450b3e878)|![Simulator Screen Shot - iPhone 14 - 2023-09-01 at 11 22 44](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/b2214521-ab53-45ef-a55e-0435d846d0f1)|

(PC-23831) feat(home): add highlight block duo offer info

---

src/features/location/components/LocationWidget.native.test.tsx
src/features/location/components/LocationWidget.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23704
I have:

(PC-23704) fix(home): show tooltip once the splash screen is hidden

---

.github/workflows/dev_on_schedule_e2e_android_browser.yml
.github/workflows/dev_on_schedule_e2e_browser.yml
.github/workflows/dev_on_schedule_e2e_ios_browser.yml
package.json

à chaque fois qu'on lance le serveur web (`yarn start:web:testing`), on a l'erreur suivante
```js
{
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
Une solution est d'exporter une variable pour changer les options de node
```sh
export NODE_OPTIONS='--openssl-legacy-provider'
```
Il faut le faire à chaque fois, c'est pénible (ou le mettre dans sa config globale mais c'est une mauvaise solution)
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24167
En ajoutant l'argument à la commande le bug n'est plus là
Il faut avoir Node>=18 pour que ça fonctionne
Node<=16 fera une erreur
Notre `.nvmrc` impose d'avoir Node 18, donc ça ne devrait pas …

(PC-24167) chore(tech): avoid error when start web server

---

src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
src/features/bookOffer/pages/BookingOfferModal.tsx

A booking can run out of stock between the moment it was accessed and the attempt to book it. In such cases, the provider API won't let us book the offer, hence a new code to handle (PROVIDER_STOCK_SOLD_OUT)
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24407
[PR back](https://github.com/pass-culture/pass-culture-main/pull/8163)
I have:
->

(PC-24407) feat(offer): Handle no session left when booking an offer

---

src/features/bookings/components/BookingDetailsCancelButton.native.test.tsx
src/features/bookings/components/BookingDetailsCancelButton.tsx

I have:
| iOS              |<img width="457" alt="Capture d’écran 2023-09-14 à 10 08 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/80988743-b400-4f09-ae78-65a756d44684">|<img width="438" alt="Capture d’écran 2023-09-14 à 10 10 26" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/9d37c986-7b6c-4f11-9e71-6cac33fa59f2">|
| Android          |<img width="432" alt="Capture d’écran 2023-09-14 à 10 09 32" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/8bec5047-4c47-4931-a1a7-c9cfddc156a0">|<img width="420" alt="Capture …

(PC-24237) feat(booking): no displaying cancel button when category to archieve offer is free at booking time and becomes paid

---

.vscode/settings.json

by replacing deprecated options by the new one
-> to avoid ESLint VSCode plugin to be broken :

(BSR) chore(vscode): fix eslint plugin config

---

src/shared/offer/components/AuthenticationModal/AuthenticationModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24700
Explications : 
Le thème était importé de /theme directement au lieu de passer par useTheme, la propriété fitContentWidth de la modale était donc toujours à false car on avait pas encore compute le thème. En fixant cela, un bug a été introduit en passant fitContentWidth à true. On fix le bug en supprimant cet prop.
I have:
| iOS              | <img width="328" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/9ac432ac-ea16-4574-875b-1f905610090c"> |<img width="326" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ec799827-e2f …

(PC-24700) fix(AuthenticationModal): fix buttons alignment

---

src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/share/components/MessagingApps/InstalledMessagingApps.native.test.tsx
src/features/share/components/MessagingApps/MessagingAppButton.tsx
src/features/share/components/MessagingApps/MessagingApps.tsx
src/features/share/helpers/shareApp.ts
src/features/share/helpers/useShareOffer.native.test.ts
src/features/share/helpers/useShareOffer.ts
src/features/share/helpers/useShareVenue.native.test.ts
src/features/share/helpers/useShareVenue.ts
src/features/share/pages/WebShareModal.native.test.tsx
src/features/share/pages/WebShareModal.web.test.tsx
src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/libs/share/share.native.test.ts
src/libs/share/share.ts
src/libs/share/share.web.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24404
I have:
| iOS              |     [bug.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/006a37c2-b3a1-4e21-9b7e-17a9846d0e97)       |     [fix.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/9f820438-f2d1-4d72-8a1a-6a8dfedf0b9f)  |
| Android          |      [bug.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/69aba3ca-ad7f-4154-9005-4311099f31b9)        |   [fix.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/19f19bd4-a69d-44bd-8115-041b611d398e)    |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bu …

(PC-24404) fix(MessagingApps): Send single url in share message

---

src/features/home/components/headers/AnimatedHighlightThematicHomeHeader.tsx
src/features/home/components/headers/HighlightThematicHomeHeader.tsx
src/features/home/components/headers/highlightThematic/Introduction.tsx
src/features/home/pages/ThematicHome.native.test.tsx
src/features/home/pages/ThematicHome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24749
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/59bd7479-2bd8-414e-a6da-b1fe3d4fed68
| iOS              | <img width="546" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/d600cc8e-3a26-4af0-83c6-52c91d41ac62"> | <img width="546" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/4b10ec39-56b9-47c1-9fb9-af2b96cfcf6f"> |
| iOS          |               | <img width="546" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/fe34e730-ac62-4f6d-9193-c63e9db9c825"> |
| Phone - Chrome   | <img …

(PC-24749) fix(ios): fix zoom in highlight thematic home

---

__snapshots__/features/search/components/Highlight/Highlight.native.test.tsx.native-snap
src/features/search/components/Highlight/Highlight.native.test.tsx
src/features/search/components/Highlight/Highlight.tsx
src/features/search/components/SearchHistory/SearchHistory.native.test.tsx
src/features/search/components/SearchHistory/SearchHistory.tsx
src/features/search/components/SearchHistoryItem/SearchHistoryItem.native.test.tsx
src/features/search/components/SearchHistoryItem/SearchHistoryItem.tsx
src/features/search/helpers/addHighlightedAttribute/addHighlightedAttribute.test.ts
src/features/search/helpers/addHighlightedAttribute/addHighlightedAttribute.ts
src/features/search/helpers/getHighlightedQuery/getHighlightedQuery.test.ts
src/features/search/helpers/getHighlightedQuery/getHighlightedQuery.ts
src/features/search/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24618
I have:
| iOS              |<img width="386" alt="Capture d’écran 2023-10-02 à 14 00 13" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/5c77254a-4af7-45c8-94d4-ec478e8251ae">|<img width="456" alt="Capture d’écran 2023-10-02 à 13 58 26" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/ba20bbb0-d6a4-4ed2-a03e-3c5a6a8216ec">|
| Android          |               |<img width="435" alt="Capture d’écran 2023-10-02 à 13 57 53" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0aaf2a0b-04d5-470f-ab57-4a61f7c0f104">|
| …

(PC-24618) feat(search): use item history highlight

---

__snapshots__/web/SupportedBrowsersGate.native.test.tsx.native-snap
src/App.web.tsx
src/features/internal/cheatcodes/pages/NavigationNotScreensPages.tsx
src/web/SupportedBrowsersGate.native.test.tsx
src/web/SupportedBrowsersGate.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21434
Une sous-dépendance (`ua-parser-js`) a été mise à jour, de la `0.7.30` à la `1.0.34` ([dans cette PR](https://github.com/pass-culture/pass-culture-app-native/pull/4583)).
À partir de la version `1.0.34`, Brave est détecté comme un navigateur "à part entière" (cf [changelog](https://github.com/faisalman/ua-parser-js/blob/master/CHANGELOG.md#version-0734--1034), il était détecté juste comme Chrome avant). La webapp essayait donc d'afficher la page "Ce navigateur n'est pas supporté", mais avait des erreurs `reading property ... of undefined`, parce qu'il n'arrivait pas accéder au thème de l'app (`SupportedBrowsersGate` était défini avant le `ThemeProvider`).
1er commit : Déplacement du détecteur de navigateur dans le …

(PC-21434) fix(web): Fix webapp on Brave

---

.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_soft_deploy.yml
.github/workflows/dev_on_workflow_update_jira_issues.yml
.github/workflows/dev_on_workflow_web_deploy.yml
.github/workflows/dev_on_workflow_web_proxy_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24931
- Split du job android hard et soft ios/android en 2 workflow
- Notifications slacks sur #alertes-deploiement-native alerte si le déploiement a eu lieu, et tolère l'échec de d'autres étapes (comme déplacé le ticket jira)
- Le ticket jira ne termine plus la CI en échec si le job fail.
I have:

(PC-24931) ci(notification): improve slack notifications and rename android workflow

---

.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_environment_soft_deploy.yml

See doc here :  https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
See Warning here :  https://github.com/pass-culture/pass-culture-app-native/actions/runs/6394734967/job/17384663425#step:12:20
I have:

(BSR) ci(fastlane): add env LANG and LC_ALL set to en_US.UTF-8

---

fastlane/Fastfile

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24945
Reason for this change as it seems that: 
- `--sourcemap-output` now expect the relative filepath where to generate the sourcemaps but it is not possible to pass this value (see https://github.com/microsoft/appcenter-cli/issues/2462#issue-1933337023)
- by reading appcenter-cli repo, there is a `--sourcemap-output-dir` available, and seems to works fine (https://github.com/microsoft/appcenter-cli/blob/v2.12.0/src/commands/codepush/release-react.ts#L188)
I have:
| Desktop …

(PC-24945) fix(sourcemaps): use --sourcemap-output-dir instead

---

src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.native.test.tsx
src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.tsx
src/features/search/fixtures/autocompleteHits.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25021
I have:
| Phone - Chrome   |![Capture d’écran 2023-10-12 à 18 30 38](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/f06451bd-2ca0-43bd-b414-331eab225cdb)|![Capture d’écran 2023-10-12 à 18 30 11](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0a16c817-712a-4ccd-bda4-78d56ada1d69)|
| Desktop - Chrome |![Capture d’écran 2023-10-12 à 18 31 00](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/57471c7d-9f47-4270-90a6-2f110a189085)|![Capture …

(PC-25021) fix(search): not use native category and category in autocomplete item when there are unknown in the app

---

src/libs/recaptcha/ReCaptcha.web.tsx
src/types.ts

Link to JIRA ticket: [PC-25603](https://passculture.atlassian.net/browse/PC-25603
)
On doit initialiser un widget Recaptcha pour chaque formulaire pour lequel on veut activer Recaptcha. Vu qu'on l'a ajouté à la connexion et au formulaire "Mot de passe oublié", on avait un conflit : le deuxième formulaire initialiser le widget dans le premier formulaire, ce qui générait des erreurs. Pour fixer ça, on utilise la référence du container et la référence du widget pour cibler les bons éléments à utiliser. 
| Desktop - Chrome |   [bug.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/d11d71ae-b26f-44a4-be99-75c9e249febd)     | …

(PC-25063) fix(web): Support multiple recaptcha widgets in dom

---

src/features/tutorial/components/profileTutorial/Timelines/CommonSteps.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25084
I have:
- [] Written **unit tests** native (and web when implementation is different) for my feature.
| Desktop - Chrome | <img width="265" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ced8006c-5293-4765-877d-9b0cc453f3a4"> | <img width="278" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/70c97acd-401d-4d25-91e5-5117e8a1718b"> |

(PC-25084) fix(Profiletutorial): fix warning icon color

---

__snapshots__/features/search/components/SearchResults/SearchResults.native.test.tsx.native-snap
__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap
src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24687
I have:
| iOS              |![ios_before](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/1f9886a1-4c9c-443e-ae0e-9ce0c76817f2)|![ios_after](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/d9ff1666-e939-4ec8-bf0e-877c4f2400bb)|
| Android          |![androis_before](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/f313a5d0-67c6-4070-bfda-f6ab005d8b69)|![Screenshot_20231012-135623_pass Culture T](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/428e078d-e6c5-4c47-89fd-fc610fd24e8c)|
| Web - Arc |<img width="565" …

(PC-24687) fix(search): fix cropped filter label on android

---

.maestro/tests/ReservationsOffresDuo.yml
.maestro/tests/ReservationsOffresEvent.yml
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/helpers/getVenueSectionTitle/getVenueSectionTitle.test.ts
src/features/offer/helpers/getVenueSectionTitle/getVenueSectionTitle.ts

Both forms are correct but we should use one consistently, not both.
See pass-culture/pass-culture-main@206bede290a1a3135119c6c6eeb05be21f6b3247 for a precedent.
---
Pas de ticket, pas de nouveau test, pas de capture d'écran.

(BSR) fix(typo): Spell it "évènement", not "événement"

---

src/api/gen/api.ts
src/features/offer/components/OfferTile/OfferTile.native.test.tsx
src/features/venue/components/VenueOfferTile/VenueOfferTile.native.test.tsx

Update part of gen/api.ts after clean of dead code in the api
See https://github.com/pass-culture/pass-culture-main/pull/8640
Both can be merged independently, since the removed route is not used in the app anymore
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20310
I have:

(PC-20310) refactor(api): remove dead code related to subcategories

---

__snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap
src/features/search/pages/SearchFilter/SearchFilter.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23729
-> fix de la taille des espaces entre les section suite à un raté de lecture de la maquette
I have:
Desktop
iPhone11

(PC-23729) fix(UI): spacing between sections

---

package.json

Added `openssl-legacy-provider` to build command because of the upgrade to node 18

(BSR) fix(CI): add openssl-legacy-provider option to build command

---

src/features/tutorial/components/CreditBlock.tsx
src/ui/components/touchable/TouchableWithoutFeedback.tsx
src/ui/components/touchable/TouchableWithoutFeedback.web.test.tsx
src/ui/components/touchable/TouchableWithoutFeedback.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25284
I have:
| Desktop - Chrome |[Video accessibility bug](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/e9a189e4-df70-462b-bbf2-2d920279004e)|[Video bug fixed](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/409cf2e9-7b31-40bc-bf7a-b739cfd12a09)|

(PC-25284) fix(Accessibility): make profile tutorial step block not focusable

---

src/features/location/components/LocationSearchWidget.tsx
src/features/search/components/SearchBox/SearchBox.native.test.tsx
src/features/search/components/SearchBox/SearchBox.tsx
src/features/search/components/SearchMainInput/SearchMainInput.tsx
src/ui/components/inputs/SearchInput.tsx
src/ui/components/inputs/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23726
I have:
| iOS              |![search_befors](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/1d027357-eb58-4ccb-8f0b-912e00b9e67d)|![search_after](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/5642ec12-c33d-4404-846f-4a959be9caa7)|
| iOS - Video screenshot    |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/bd203d5d-73d9-45a5-a580-6edc3f4c0e9c|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/515471f3-7175-4ca3-8054-db5e35fbc3a2|
| Phone - Chrome   |<img width="1512" alt="Capture d’écran 2023-10-26 à 16 39 34" …

(PC-23726) fix(locationSearch): remove search input clear cross and adjust spaces

---

src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25347
I have:
| iOS              |<img width="462" alt="Capture d’écran 2023-10-27 à 12 40 52" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/6bf9ba83-db9f-4f51-9f1a-23b86da6d95d">|<img width="439" alt="Capture d’écran 2023-10-27 à 12 39 48" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/5631398f-3243-462d-8580-a8857f6540a5">|
| Android          |<img width="426" alt="Capture d’écran 2023-10-27 à 12 40 47" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/188d84cf-4187-4497-86f4-81d5a61f67ec">|<img width="424" …

(PC-25347) fix(offer): CTA when offer is digital and free and user not eligible

---

src/libs/geolocation/hooks/useDistance.test.ts
src/libs/geolocation/hooks/useDistance.ts
src/libs/parsers/formatDistance.ts
src/libs/parsers/tests/formatDistance.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25102
I have:
| No localisation              |<img width="831" alt="nothing" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/1acd9921-013c-41dc-9368-985600217ef8">|<img width="831" alt="nothing" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/1acd9921-013c-41dc-9368-985600217ef8">|
| Only custom loc          |![image](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/fb2c4c99-e5a5-4cfa-a79b-85ebb3087448)|<img width="830" alt="only_custom" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/47666d37-dcde-44f8-af20-042773089908">|
| …

(PC-25102) feat(location): adapt displayed distance to custom location when set

---

server/src/middlewares/tests/webAppProxyMiddleware.test.ts
server/src/middlewares/webAppProxyMiddleware.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24999
I have:

(PC-24999) feat(SEO): add homeId in canonical link of thematic homes

---

src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.native.test.ts
src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25557
I have:

(PC-25557) fix(search): reset param from history when pressing category button

---

.github/workflows/jira_create_and_push_staging_testing_deploy_tags.yml

- Added the skip-push option for the bump version action on testing as we commit and push later in the workflow
- Specified the branch to master for more clarity

(BSR) fix(CI): fix testing bump tag workflow

---

package.json
yarn.lock

Issue: https://github.com/microsoft/playwright/issues/24028
Autrement `yarn install` fail sur Debian 12 : 
```bash
Output:
/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/@chanzuckerberg/axe-storybook-testing/node_modules/playwright-core/lib/server/registry/index.js:684
if (!downloadURLs.length) throw new Error(`ERROR: Playwright does not support ${descriptor.name} on ${_hostPlatform.hostPlatform}`);
^
Error: ERROR: Playwright does not support firefox on debian12
at Registry._downloadExecutable (/home/dka/workspace/github.com/pass-culture/pass-culture-app-native/node_modules/@chanzuckerberg/axe-storybook-testing/node_modules/playwright-core/lib/server/registry/index.js:684:37)
at …
```

(BSR) build(storybook): upgrade @chanzuckerberg/axe-storybook-testing from 7.1.1 to 7.1.2

---

server/src/middlewares/tests/webAppProxyMiddleware.test.ts
server/src/middlewares/webAppProxyMiddleware.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25610
I have:

(PC-25610) fix(security): Encode home id params to avoid xss attack

---

src/features/search/components/FilterRow/FilterRow.tsx
src/ui/components/radioButtons/RadioButton.tsx

…
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24769
I have:
| iOS              |               |![Capture d’écran 2023-11-08 à 11 03 11](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/cc0f92e0-0f44-4f04-b870-b52fe612d6a3)|
| Android          |               |![Capture d’écran 2023-11-08 à 11 18 19](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/58b61845-7cf2-4e3e-addc-95dd81ed0e72)|
| Phone - Chrome   |               |![Capture d’écran 2023-11-08 à 10 55 44](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/8e4c2eca-ac8b-455c-b444-da6bec622d6a)| …

(PC-24769) fix(nbResultsFacet): fix ui of nbResultFacets complement & ValidateIcon

---

__snapshots__/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx.native-snap
src/features/search/pages/modals/LocationModal/LocationModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25839
I have:
| iOS              |<img width="329" alt="Capture d’écran 2023-11-16 à 11 04 20" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/6c3f4574-e2c1-49af-8d2a-051f0ae4004f">|<img width="334" alt="Capture d’écran 2023-11-16 à 12 01 36" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/677d7c0a-b117-4dad-9fe2-79e86fdcdc9c">|
| Android          |<img width="372" alt="Capture d’écran 2023-11-16 à 11 53 31" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/f1e7ddba-2046-44ae-b705-757fb97f1229">|<img width="375" alt="Capture d’écran 2023-11-16 à …

(PC-25839) fix(location): fix header design issue on the location modal

---

scripts/upload_sourcemaps_to_sentry.sh

This config option was added recently to the script and when we call the script without a third argument it is now failing:
`set -o nounset`
I added a default value for the third argument (empty string) to fix it.

(BSR) fix(CI): add default value for third argument in sentry sourcemap upload script

---

src/api/apiHelpers.native.test.ts
src/api/apiHelpers.ts

This fixes untimely redirections on iOS.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25774
I have:
| iOS              | https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a3d29ffc-98e9-4412-868e-ba58fff558c0 | https://github.com/pass-culture/pass-culture-app-native/assets/68000368/428eaa1e-3a35-4ab3-9087-ba0d3319f417 |

(PC-25774) fix(Auth): refresh access token when it is unknow but refresh token is still valid

---

__snapshots__/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx.web-snap
src/ui/pages/GenericInfoPageWhite.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24309
I have:
| Desktop - Chrome |<img width="865" alt="Capture d’écran 2023-11-23 à 14 48 50" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/1c342e25-7bcf-4364-8545-6d10b9dd1351"> <img width="1727" alt="Capture d’écran 2023-11-23 à 14 48 13" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/55c54899-dc5c-4c81-a454-9b3e0256fd11">|<img width="1724" alt="Capture d’écran 2023-11-23 à 14 47 16" …

(PC-24309) fix(ui): GenericInfoPageWhite with overflow auto on web platform

---

.vscode/extensions.json

(BSR) fix(extensions): fix deprecated ruby extension

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/venue/components/VenueBodyNew/VenueBodyNew.native.test.tsx
src/features/venue/components/VenueBodyNew/VenueBodyNew.tsx
src/ui/InformationTags/InformationTags.native.test.tsx
src/ui/InformationTags/InformationTags.stories.tsx
src/ui/InformationTags/InformationTags.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26250
I have:
| iOS              |<img width="517" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/7964574c-5139-40aa-932b-af06dcfa5591">|<img width="315" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a3627b15-c624-43cd-98fa-13c457bc3a08">|
| Android          |<img width="517" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/fc934228-30a2-45a8-9acd-16d70f609f75">|<img width="406" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/93eaf398-e16b-4584-a …

(PC-26250) feat(Venue): add tags in new venue body

---

.github/workflows/dev_on_workflow_tester.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26030
Split jest test unit on five differents pods to avoid OMM killed. Then a new step will bring back the different coverage, merge them in one big file and upload it

(PC-26030) feat(ci): Split yarn test-native-ci into five differents pods

---

.github/workflows/dev_on_push_workflow_main.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26567
**Problème :**
Ce [workflow](https://github.com/pass-culture/pass-culture-app-native/actions/runs/7275320663) n'a pas créé la version testing iOS/Android appcenter alors qu’il aurait du. 
Il a été trigger via Jira puis [ce workflow](https://github.com/pass-culture/pass-culture-app-native/actions/runs/7275319749)
**Solution :** 
- L95 : on ne veut pas de code push sur la première version de testing après une MES, pour annuler le code push, on vérifie que le commit message ne commence pas par un `v`
- L122 et L131 : on veut une nouvelle release hard iOS et Android si le commit message sur master commence par `v` (en plus de quand on trigger un tag manuelle qui commence par testing)
- L175 à 177 : on a 3 needs, mais on …

(PC-26567) ci(native): fix deploy testing on MES

---

__snapshots__/libs/recaptcha/ReCaptcha.native.test.tsx.native-snap
src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.native.test.tsx
src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx
src/features/auth/pages/login/Login.native.test.tsx
src/features/auth/pages/login/Login.tsx
src/libs/recaptcha/webviewHTML.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26333
Quelques précisions : 
- Le composant AcceptCgu gère déjà le cas hors ligne autrement dans l'affichage donc pas besoin de changer la notification à l'utilisateur
- Le test sur Android n'était pas vraiment concluant, mais je me demande si ce n'est pas du au test sur émulateur... Il faudrait recetter sur vrai device mais en tout cas le nombre d'erreurs devrait bien descendre
I have:
| iOS              |               |<img width="320" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/893f50aa-7a85-4864-9898-dc6b9fca07ec">|
| Android          |               | …

(PC-26333) fix(ReCaptcha): Fix wording and logging to sentry on network failure when doing ReCaptcha

---

.github/workflows/dev_on_push_workflow_main.yml

(BSR) ci(web): deploy web testing only on master

---

scripts/enableNativeAppRecaptcha.ts
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25011
I have:

(PC-25011) feat(maestro): Disable recaptcha before tests

---

__snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap
__snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap
__snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/ui/components/AccordionItem.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26571
I have:
| Android          |     ![5d2ddc34-5928-40d7-bf0c-09c6a3a09302](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/385b6b4f-92f9-4f86-b0cf-92dc9dfff427)          | <img alt="Capture d’écran 2023-12-26 à 11 57 03" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/4dd6aa9f-69b8-4566-9cd7-d23b20d6ae2f">      |
| iOS              |               |     ![Simulator Screenshot - iPhone 5 - 2023-12-26 at 11 57 15](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/24f6558f-dcd4-4ade-bb87-61284a122d14)  |
| Phone - Chrome   |               | …

(PC-26571) fix(cookies): Display full text in accordion

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/venue/components/VenueCTA/VenueCTA.tsx
src/ui/components/BlurryWrapper/BlurryWrapper.tsx
src/ui/components/BlurryWrapper/BlurryWrapper.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26572
I have:
| iOS              | ![Capture d’écran 2023-12-27 à 11 12 36](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/aac66ff2-de29-4c26-a5d7-ca0713f114a6) |  ![Capture d’écran 2023-12-27 à 11 12 24](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/0b36461c-5ce0-495d-b59e-34d32f37e17d)  |
| Android          | <img width="410" alt="Capture d’écran 2023-12-27 à 14 55 59" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/4539c7b8-20bd-4345-baba-78a65fec8c37"> |  <img width="407" alt="Capture d’écran 2023-12-27 à 14 55 36" …

(PC-26572) feat(venue): reduce blurry background for CTA venue

---

src/ui/components/Tooltip.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26512
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/8f348ad6-7836-4ddb-90c5-64ad77068fa5

(PC-26512) fix(Tooltip): clickable only on cross

---

src/features/venue/components/PracticalInformation.native.test.tsx
src/features/venue/components/PracticalInformation.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26714
I have:
| Phone - Chrome   |<img width="344" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/f5811fbc-51f0-4c04-a8d1-b7bce78be7a8">|<img width="346" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/71daa355-4254-4d9a-a884-90a9c9d3e652">|
| Desktop - Chrome |<img width="1020" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/709320bf-9753-4042-bf51-93e51da8b9b3">|<img width="1023" alt="image" …

(PC-26714) fix(Venue): hide practical information titles when sections are empty

---

src/features/home/components/modules/HomeModule.native.test.tsx
src/features/home/components/modules/HomeModule.tsx
src/features/home/components/modules/HomeModule.web.test.tsx
src/features/home/types.ts

Ticket : https://passculture.atlassian.net/browse/PC-26879

(PC-26879) fix(homeModule): put back condition to not show ExclusivityModules

---

src/features/venue/components/NoInformationPlaceholder.tsx
src/features/venue/components/PracticalInformation.native.test.tsx
src/features/venue/components/PracticalInformation.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26715
I have:
| iOS              | <img width="489" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/a18bbb8e-abe0-4bc3-8866-7135a17da570"> | <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/58cb70fe-d156-41d5-97da-69fd5f384f41"> |
| Phone - Chrome   | <img width="489" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/ca7da4e7-6b0a-4ce3-8368-4b2ef9d9d50d"> | <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/fd152352-5cf4-459a-88e1-e184ed667c27"> | …

(PC-26715) feat(venue): add placeholder when no practical information

---

src/libs/firebase/firestore/client.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26799
cf [cette issue](https://github.com/firebase/firebase-js-sdk/issues/6951)
I have:
| Desktop - Chrome |               |   Mouna a validé que ça marchait    |

(PC-26799) fix(firestore): Fix Could not reach Cloud Firestore backend error

---

src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/features/offer/components/OfferContent/OfferContent.tsx
src/features/offer/components/OfferPlaylist/hook/useSameArtistPlaylist.tsx
src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.test.ts
src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.ts
src/features/offer/pages/Offer/Offer.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26803
I have:
Première vidéo avant puis deuxième après
https://github.com/pass-culture/pass-culture-app-native/assets/78556024/4f614271-7382-455c-aaa2-7572fae81b69
https://github.com/pass-culture/pass-culture-app-native/assets/78556024/eee8abfa-0eb5-477c-99ef-8ca48d60c21d

(PC-26803) fix(offer): reload query cache when ean change

---

__snapshots__/features/auth/pages/signup/SetPassword/SetPassword.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
src/features/auth/pages/signup/SetPassword/SetPassword.native.test.tsx
src/features/auth/pages/signup/SetPassword/SetPassword.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26917
I have:
| Desktop - Chrome | <img width="1440" alt="Screenshot 2024-01-22 at 10 31 08" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/9e305984-6320-421d-9a53-d21a261497f5"> | <img width="1440" alt="Screenshot 2024-01-22 at 10 31 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/33c7baf9-980e-49ce-a28c-3d4e62924bb2"> |

(PC-26917) fix(SetPassword): Removed "Obligatoire" from screen to set password

---

__snapshots__/features/search/components/SearchResults/SearchResults.native.test.tsx.native-snap
__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap
__snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx
src/features/search/components/SearchListHeader/SearchListHeader.tsx
src/features/search/components/SearchResults/SearchResults.tsx
src/features/search/components/SearchSuggestions/SearchSuggestions.tsx
src/features/search/pages/Search/Search.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25003
I have:
| iOS              |               |<img width="438" alt="Capture d’écran 2024-01-22 à 18 25 52" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/ced2ac9b-c5b9-4c66-b2cf-61a596bced77"> <img width="445" alt="Capture d’écran 2024-01-22 à 18 25 58" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/62d995d1-647d-45e1-94ec-58609c2c7b58"> <img width="448" alt="Capture d’écran 2024-01-22 à 18 26 17" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/79bed39d-be28-4cd7-921a-a0cc3c34ae17"> <img width="439" …

(PC-25003) fix(search): visual harmonization

---

src/App.tsx
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx
src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/ui/theme/shadow.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21174
I have:

fix(android): cast elevation to string to avoid warning

---

src/features/offer/helpers/useLogPlaylistVertical/useLogPlaylistVertical.test.ts
src/features/offer/helpers/useLogPlaylistVertical/useLogPlaylistVertical.tsx
src/features/offerv2/components/OfferContent/OfferContent.tsx
src/features/offerv2/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx
src/features/offerv2/components/OfferPlaylistList/OfferPlaylistList.tsx

When we going to clean offer v1 legacy we can remove useOfferAnalytics hook
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27171
I have:

(PC-27171) refactor(useOfferAnalytics): create useLogPlaylistVertical.

---

server/src/middlewares/tests/webAppProxyMiddleware.test.ts
server/src/middlewares/webAppProxyMiddleware.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27722
Need to be tested in testing, once merged!
I prefer to keep using encodeURIComponent in webAppProxyMiddleware.ts, because new URL() encode characters, but not "/"

(PC-27722) feat(proxy): add offer canonical url to its description page

---

__snapshots__/features/offerv2/components/MovieCalendar/MovieCalendar.native.test.tsx.native-snap
src/features/offerv2/components/MovieCalendar/MovieCalendar.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27872
I have:
| iOS              | ![Simulator Screenshot - iPhone Xs - 2024-02-08 at 12 02 09](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/b3b0e5e9-f9a0-4de5-95c4-ce035d93a7e1)| ![Simulator Screenshot - iPhone Xs - 2024-02-08 at 11 58 48](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/11daa540-4195-4caf-bd65-e7cfac795ecb)|
| Android          |![Screenshot_1707388425](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/08c8f258-dee2-4f76-b757-48a9e3ba1723)| ![Screenshot_1707390400](https://github.com/pass-culture/pass-culture-app-nati …

(PC-27872) fix(UI): add container to add margin to calendar only and not BottomBar

---

.eslintrc.js
src/features/navigation/RootNavigator/useScreenshotListener.ts
src/features/search/helpers/getIsVenuePreviousRoute/getIsVenuePreviousRoute.ts
src/shared/getRouteFromIndex/getRouteFromIndex.test.ts
src/shared/getRouteFromIndex/getRouteFromIndex.ts
src/ui/components/Tooltip.tsx

I have:
Pourquoi on veut cela:
@react-navigation/native est conçu pour envelopper @react-navigation/core et fournir une intégration plus profonde avec l'environnement spécifique de React Native. Il utilise des composants natifs et des API spécifiques à la plateforme pour offrir une expérience utilisateur plus fluide et naturelle sur les appareils mobiles. (il peut s'en déduire des avantages de perf, de facilité d'utilisation et d'intégration et une sensation de comportement plus "natif")

(BSR) feat(eslintrc): use react-navigation/native instead of react-navigation/core

---

src/ui/components/CollapsibleText/CollapsibleText.native.test.tsx
src/ui/components/CollapsibleText/CollapsibleText.tsx
src/ui/components/CollapsibleText/types.ts
src/ui/components/CollapsibleText/useIsTextEllipsis.android.test.tsx
src/ui/components/CollapsibleText/useIsTextEllipsis.android.ts
src/ui/components/CollapsibleText/useIsTextEllipsis.ios.ts
src/ui/components/CollapsibleText/useIsTextEllipsis.ts
src/ui/components/CollapsibleText/useIsTextEllipsis.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27006
Not fixed in web ! :'( 
I have:
| Platform         | Mockup/Before | After | After |
| iOS              | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/d20df413-d2d1-4eef-b8dc-ab7d09c33ee3) | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/a85f60f0-faaf-4aaf-9722-369f1b756f44) | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/f818d48e-e32d-43f4-a36c-db72d6c2194d) |
| Android          | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/0b0dbd80-f3d5-47ff-9576-20c50e5cb075) | ![image](https://github.com/pass-culture/pass-culture-app-native/ …

(PC-27006) fix(collapsible): do not collapse text when last line not filled

---

src/features/search/components/SearchBox/SearchBox.native.test.tsx
src/features/search/components/SearchBox/SearchBox.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27901
I have:
Uploading Simulator Screen Recording - iPhone SE (3rd generation) - 2024-02-09 at 17.06.14.mp4…

(PC-27901) fix(search): fix query reset on goback

---

src/ui/components/eventCard/EventCard.stories.tsx
src/ui/components/eventCard/EventCard.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27840
I have made a Story.
| Platform         | Design | Code |
| Default             | ![Capture d’écran 2024-02-13 à 11 54 33](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/4afa4775-d940-428b-a289-1b099743955c)| ![Capture d’écran 2024-02-13 à 10 07 50](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/b0490a6c-ed86-4ba4-b35e-c080cc037919) |
| Disabled          |![Capture d’écran 2024-02-13 à 11 58 36](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/6199627a-42d5-4c7c-917b-7d6e629d2277) |![Capture d’écran 2024-02-13 à 10 08 …

(PC-27840) feat(cinema): component EventCard
