__snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17008
I have:
|![Capture d’écran 2022-09-01 à 11 53 31](https://user-images.githubusercontent.com/78556024/187886836-7cd0d022-c55c-4f98-aac1-6a5d368b0ab6.png)|![Capture d’écran 2022-09-01 à 11 53 52](https://user-images.githubusercontent.com/78556024/187886885-00008c6b-3b3a-4ed7-a98b-238baeda6f12.png)|<img width="423" alt="Capture d’écran 2022-09-01 à 17 21 21" src="https://user-images.githubusercontent.com/78556024/187951473-ebb17aec-7a89-43a5-84f8-40a021a38fa6.png">|<img width="1726" alt="Capture d’écran 2022-09-01 à 17 18 12" …
=> (PC-17008) feat(search): add reset button prices filter page

src/features/search/pages/__tests__/useSearchResults.test.ts, src/features/search/pages/useSearchResults.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17145
I have:
=> (PC-17145) fix(search): improve change page search results

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap, __snapshots__/features/search/sections/tests/Category.native.test.tsx.native-snap, __snapshots__/features/search/sections/tests/Category.web.test.tsx.web-snap, src/features/search/atoms/TitleWithCount.tsx, src/features/search/components/SearchResults.tsx, src/features/search/pages/SearchFilter.tsx, src/features/search/pages/__tests__/SearchFilter.native.test.tsx, src/features/search/sections/Category.tsx, src/features/search/sections/tests/Category.native.test.tsx, src/features/search/sections/tests/Category.web.test.tsx, src/features/search/sections/tests/analytics.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17101
I have:
|![Capture d’écran 2022-08-31 à 17 17 23](https://user-images.githubusercontent.com/78556024/187725892-ce032db3-f777-4b9d-b506-7f9a7a1492c2.png)|<img width="396" alt="Capture d’écran 2022-08-31 à 17 14 11" src="https://user-images.githubusercontent.com/78556024/187726001-efcadebc-3236-41d4-93d1-e8d86a77f497.png">|![Capture d’écran 2022-08-31 à 17 17 04](https://user-images.githubusercontent.com/78556024/187726063-3a17c28f-e106-4210-b927-c10d66e5b84c.png)|<img width="1476" alt="Capture d’écran 2022-08-31 à 17 13 58" …
=> (PC-17101) feat(search): add link categories filter page on general filters page

__snapshots__/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx.web-snap, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/libs/share/__tests__/WebShareModal.native.test.tsx, src/libs/share/shareApp/ShareAppModal.tsx, src/libs/share/shareApp/__tests__/ShareAppModal.native.test.tsx, src/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16983
I have:
|  https://user-images.githubusercontent.com/46637324/188104185-7776b857-e8dd-4734-846d-f1761caee8d5.mp4  |       https://user-images.githubusercontent.com/46637324/188104261-5d6e309b-962d-4fa9-acec-9fbf00160b0c.mp4|   |  https://user-images.githubusercontent.com/46637324/188104675-19725a97-40dd-429e-9ee5-ea51e2b75a91.mp4       |         |
=> (PC-16983) feat(share): Add route for ShareAppModal

src/api/gen/api.ts, src/features/cookies/CookiesPolicy.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesConsent.tsx, src/features/cookies/useCookies.ts, src/features/cookies/useLogCookiesConsent.ts, src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16411
https://passculture.atlassian.net/browse/PC-16502
I have:
=> (PC-16411) feat(cookies): Use API to log user's consent (PC-16502)

src/features/home/services/useAvailableCredit.test.ts, src/features/home/services/useAvailableCredit.ts, src/features/identityCheck/pages/Stepper.tsx, src/features/identityCheck/pages/__test__/Stepper.test.tsx, src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx, src/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16932
I have:
|     |     https://user-images.githubusercontent.com/89008469/188155847-4ace4e0c-167e-4224-8e79-4e5c33aa9c7c.mp4    |                 |                  |                  |
=> (PC-16932) fix(activation): Navigation beneficiary account created

__snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/components/FilterSwitchWithLabel.stories.tsx, src/features/search/components/FilterSwitchWithLabel.tsx, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx
Co-authored-by: Cédric Le Sausse <cedric.lesausse@passculture.app>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16953
I have:
|<img width="377" alt="Capture d’écran 2022-09-05 à 12 10 55" src="https://user-images.githubusercontent.com/78556024/188426021-af5f233d-6244-4fa9-9729-1fbfcecba390.png"> <img width="382" alt="Capture d’écran 2022-09-05 à 12 11 04" src="https://user-images.githubusercontent.com/78556024/188426065-19f6b6c3-edd3-46ec-97c2-e4bd2134a92b.png">|<img width="417" alt="Capture d’écran 2022-09-05 à 12 12 58" src="https://user-images.githubusercontent.com/78556024/188426141-54dbc603-78d3-4ae4-b273-13ad33e6 …
=> (PC-16953) feat(search): credit limit search

src/features/auth/AuthContext.tsx, src/features/cookies/CookiesPolicy.ts, src/features/cookies/getAcceptedCookieConsent.test.ts, src/features/cookies/getAcceptedCookieConsent.ts, src/features/cookies/logGoogleAnalytics.test.ts, src/features/cookies/logGoogleAnalytics.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesConsent.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.tsx, src/libs/algolia/analytics/__tests__/logClickOnOffer.test.ts, src/libs/algolia/analytics/__tests__/logOfferConversion.test.ts, src/libs/algolia/analytics/logClickOnOffer.ts, src/libs/algolia/analytics/logOfferConversion.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17157
I have:
=> (PC-17157) feat(cookies): add useAcceptedCookiesConsent

__snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16956
I have:
|<img width="388" alt="Capture d’écran 2022-09-06 à 11 08 06" src="https://user-images.githubusercontent.com/78556024/188596328-5a091c8e-32d8-4c0a-8d93-a83bac1dcf3f.png"> <img width="406" alt="Capture d’écran 2022-09-06 à 11 08 15" src="https://user-images.githubusercontent.com/78556024/188596357-95b4c8f5-a159-4c44-80de-d291785c3ff2.png">|<img width="419" alt="Capture d’écran 2022-09-06 à 11 10 21" src="https://user-images.githubusercontent.com/78556024/188596398-4f5f6db0-0e87-49b6-bf8b-7d8f6887956d.png"> <img width="410" alt="Capture d’écran 2022-09-06 à 11 …
=> (PC-16956) feat(search): add only free offers toggle

__snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16940
I have:
|<img width="390" alt="Capture d’écran 2022-09-06 à 15 44 08" src="https://user-images.githubusercontent.com/78556024/188652787-f52f861d-a263-4848-98a6-8ee03ef9ee3a.png">|<img width="421" alt="Capture d’écran 2022-09-06 à 15 45 17" src="https://user-images.githubusercontent.com/78556024/188652877-f9a4773d-042c-418e-9162-831a5947f5ad.png">|                 |<img width="1725" alt="Capture d’écran 2022-09-06 à 15 43 29" src="https://user-images.githubusercontent.com/78556024/188652944-9feee793-b6f1-4dc7-a634-07b889765a8a.png">|                  |
[1]: …
=> (PC-16940) feat(search): add credit disclaimer banner

src/libs/share/shareApp/ShareAppModal.tsx, src/libs/share/shareApp/__tests__/ShareAppModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16983
I have:
=> (PC-16983) feat(share): Edit component for ShareAppModal

src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesConsent.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.tsx, src/libs/campaign/__mocks__/campaignTracker.ts, src/libs/campaign/campaignTracker.ts, src/libs/campaign/campaignTracker.web.ts, src/libs/campaign/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16709
I have:
=> (PC-16709) feat(cookies): Disable AppsFlyer if marketing cookies are refused

__mocks__/libs/react-native-batch.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesConsent.tsx, src/features/cookies/startBatch.ts, src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17196
I have:
=> (PC-17196) feat(cookies): Disable Batch if customization cookies are refused

src/libs/react-native-batch/index.web.ts
=> (PC-17196) fix(cookies): Add missing method to web Batch

src/features/search/pages/LocationFilter.tsx, src/features/search/pages/__tests__/LocationFilter.native.test.tsx
as the implemented feature wasn't correct
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17058
I have:
=> (PC-17058) fix(locationFilter): fix reset button

__snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17005
I have:
|     |  ![image](https://user-images.githubusercontent.com/77674046/188891344-e3556a9c-f8f8-411b-9ec5-3b6c14d39173.png)       |   ![image](https://user-images.githubusercontent.com/77674046/188888281-227e94f3-8590-4d7a-b423-bbb6d5b8c1bc.png)              |  ![image](https://user-images.githubusercontent.com/77674046/188888178-eb406591-038c-43a9-bc4e-64c0357fdffd.png)                |                  |
[2]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-s …
=> (PC-17005) fix(Search): usage of Ul > Li for landing

__mocks__/libs/react-native-batch.ts, src/features/auth/signup/AccountCreated/AccountCreated.tsx, src/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx, src/features/bookOffer/pages/BookingConfirmation.tsx, src/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx, src/features/home/pages/Home.tsx, src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx, src/features/identityCheck/pages/confirmation/__test__/BeneficiaryAccountCreated.test.tsx, src/features/offer/pages/Offer.tsx, src/libs/react-native-batch/enums.ts, src/libs/react-native-batch/index.ts, src/libs/react-native-batch/index.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17001
I have:
=> (PC-17001) feat(tracking): Add Batch event trackers

__snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx.web-snap, __snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferTypeChoices.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferTypeChoices.test.tsx.web-snap, src/features/_marketingAndCommunication/atoms/OfferCategoryChoices.tsx, src/features/_marketingAndCommunication/atoms/OfferTypeChoices.tsx, src/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx, src/features/_marketingAndCommunication/atoms/__tests__/OfferTypeChoices.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17274
I have:
=> (PC-17274) fix(DeeplinkGenerator): fix display and add snapshots

.github/workflows/service-worker-test.yml, package.json, scripts/service-worker-test.mjs, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17275
Fix tested with testing version 1.125.100: it is working 🙌
=> (PC-17275) fix(build): install puppeteer only in the sw test

src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx
search price
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16956
I have:
=> (PC-16956) feat(search): UI remakrs toggle free offers

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/identityCheck/components/HeroButtonList.stories.tsx, src/features/identityCheck/components/HeroButtonList.tsx, src/ui/components/Emoji.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16826
I have:
|  
|    
|                 | 
|
|
=> (PC-16826) feat(HeroButtonList): create a HeroButtonList component

__snapshots__/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx.web-snap, src/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx, src/libs/share/shareApp/shareAppContent.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16413
I have:
=> (PC-16413) feat(shareApp): Update wording and url

src/features/identityCheck/__test__/useIdentityCheckSteps.test.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx, src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx, src/features/identityCheck/useIdentityCheckSteps.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16769
I have:
https://user-images.githubusercontent.com/44037911/189371925-71d35f60-ce2e-4e40-9a97-b5f9452e3b6e.mp4
=> (PC-16769) feat(phoneVal): navigate to too many attempts from phone number

.circleci/config.yml, .env.integration, .env.production, .env.staging, .env.testing, doc/standards/sentry.md
Change sentry DNS from internal-passculture.app to passculture.team
=> (PC-17313) fix(Sentry): DNS migration to sentry.passculture.team

__snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap, __snapshots__/features/offer/atoms/__tests__/OfferTile.native.test.tsx.native-snap, __snapshots__/features/offer/atoms/__tests__/OfferTile.web.test.tsx.web-snap, __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap, __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx.web-snap, __snapshots__/features/venue/components/__tests__/VenueOffers.native.test.tsx.native-snap, __snapshots__/features/venue/components/__tests__/VenueOffers.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/offer/atoms/OfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17266
I have:
AVANT:
| iOS | Android |
|<img width="331" alt="Capture d’écran 2022-09-12 à 16 50 22" src="https://user-images.githubusercontent.com/22886846/189691565-de636fcf-2b29-4e13-9f4e-50605914f945.png">|<img width="339" alt="Capture d’écran 2022-09-12 à 16 49 54" src="https://user-images.githubusercontent.com/22886846/189692184-87a41953-d911-4ee5-ae38-2788b6289464.png">|
APRÈS:
| iOS | Android |
|<img width="331" alt="Capture d’écran 2022-09-12 à 16 51 17" src="https://user-images.githubusercontent.com/22886846/189691586-1633629e-e38d-4bf1-9867-19327a88b201.png">|<img width="338" alt="Capture d’écran 2022-09-12 à 16 51 41" …
=> (PC-17266) fix(home): fix offer caption display

src/ui/components/modals/AppModal.native.test.tsx, src/ui/components/modals/AppModal.test.tsx, src/ui/components/modals/AppModal.tsx, src/ui/components/modals/ModalHeader.tsx, src/ui/components/modals/appModalContainerStyle.ts, src/ui/components/modals/enum.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17215
I have:
Use example for categories :
|<img width="453" alt="Capture d’écran 2022-09-13 à 12 33 54" src="https://user-images.githubusercontent.com/78556024/189879804-4ea989ab-9869-44ff-9052-38ae73c2d235.png">|         |                 |<img width="740" alt="Capture d’écran 2022-09-13 à 12 41 35" src="https://user-images.githubusercontent.com/78556024/189881157-8eb7d151-0ffb-4429-ae71-49c038c46b7d.png">|                  |
[2]: …
=> (PC-17215) feat(fullscreenModal): test use specific modal

src/libs/share/WebShareModal.web.tsx, src/libs/share/share.ts, src/libs/share/shareApp/__tests__/ShareAppModal.web.test.tsx, src/libs/share/shareApp/shareAppContent.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16413
I have:
=> (PC-16413) fix(shareApp): Include URL in message for iOS and Android

__snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx.web-snap, __snapshots__/features/favorites/atoms/__tests__/Favorite.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Categories.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Categories.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Categories.test.tsx.web-snap, __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtons/useSortedSearchCategories.test.tsx, src/libs/search/utils/getCategoriesFacetFilters.ts, src/libs/subcategories/__tests__/useSearchGroupLabel.test.ts, src/libs/subcategories/fixtures/mappings.ts, src/libs/subcategories/placeholderData.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17285
I have:
=> (PC-17285) fix(search): add s to vinyle

src/features/auth/AuthContext.test.tsx, src/features/cookies/api/usePostCookiesConsent.ts, src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16988
I have:
=> (PC-16988) refactor(cookies): simpler API for better tests

package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17419
I have:
=> (PC-17419) build(Web): fix build testing with dedupe

__snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx.native-snap, __snapshots__/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.web.test.tsx.web-snap, src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx, src/features/culturalSurvey/pages/__tests__/CulturalSurveyQuestions.native.test.tsx, src/features/profile/pages/Profile.native.test.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts, src/tests/utils.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-13355
I have:
=> (PC-13355) feat(CulturalSurvey): track scroll to bottom on question screen

__snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap, __snapshots__/features/auth/login/Login.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ChangePassword/tests/ChangePassword.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/components/FilterPageButtons/FilterPageButtons.tsx, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx, src/features/search/pages/schema/priceSchema.test.ts, src/features/search/pages/schema/priceSchema.ts, src/ui/components/inputs/rules/InputRule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17379
I have:
|<img width="438" alt="Capture d’écran 2022-09-15 à 18 02 15" src="https://user-images.githubusercontent.com/78556024/190454662-314a3196-e31b-497a-b725-b680eb5bc6fe.png"> <img width="443" alt="Capture d’écran 2022-09-15 à 18 02 26" src="https://user-images.githubusercontent.com/78556024/190454701-a036c8f4-5852-4013-aa69-14438e31d18a.png">|<img width="411" alt="Capture d’écran 2022-09-15 à 18 51 01" src="https://user-images.githubusercontent.com/78556024/190462390-476518a4-a3e5-45aa-ba6d-24baa05619fd.png"> <img width="434" alt="Capture d’écran 2022-09-15 à 18 …
=> (PC-17379) feat(search): formik search price filter

__snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17168
I have:
|     |         |<img width="449" alt="Capture d’écran 2022-09-16 à 10 03 15" src="https://user-images.githubusercontent.com/78556024/190588679-dfa82995-3f45-4c71-ade1-0d2bb0812cdd.png"> <img width="482" alt="Capture d’écran 2022-09-16 à 10 02 11" src="https://user-images.githubusercontent.com/78556024/190588700-b5f90275-0158-456f-946a-cde2ee76b7e0.png"> <img width="473" alt="Capture d’écran 2022-09-16 à 10 01 04" src="https://user-images.githubusercontent.com/78556024/190588703-8250ebb3-46db-4d7a-8b91-e139dfa2d25d.png"> <img width="440" alt="Capture d’écran …
=> (PC-17168) feat(search): max price placeholder search

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17099
I have:
=> (PC-17099) feat(search): remove ff for search filter price

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.test.tsx.web-snap, src/features/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NewIdentificationFlow/NewIdentificationFlow.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16830
I have:
| iOS | iOS small |  Desktop - Chrome | 
| --: | ------: | --------------: | 
|   <img width="351" alt="Capture d’écran 2022-09-16 à 15 28 15" src="https://user-images.githubusercontent.com/44037911/190651293-d8e57b28-8685-4299-9430-f038e5448935.png">  |   <img width="300" alt="Capture d’écran 2022-09-16 à 15 27 46" src="https://user-images.githubusercontent.com/44037911/190651385-3fdef4a7-fb85-4ff0-a32f-9f0095416a11.png">      |        <img width="1440" alt="Capture d’écran 2022-09-16 à 15 28 20" src="https://user-images.githubusercontent.com/44037911/190651524-297ecfc4-139d-4b06-8b98-1b909b9f13a5.png">         |        
[1]: https://github.com/pass-culture/pass-culture-app-native/blob/master/doc/standard …
=> (PC-16830) feat(newIdentificationFlow): create SelectIDStatus page

__snapshots__/features/offer/pages/__tests__/OfferDescription.web.test.tsx.web-snap, src/features/cookies/helpers/isConsentChoiceExpired.test.ts, src/features/cookies/helpers/isConsentChoiceExpired.ts, src/features/cookies/helpers/useCookies.test.ts, src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyV1.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyV2.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16408
I have:
=> (PC-16408) feat(cookies): Show PrivacyPolicy if consent is older than 6 months

__snapshots__/features/identityCheck/pages/identification/identificationStart/IdentityCheckStart.web.test.tsx.web-snap, __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap, __snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, src/features/navigation/RootNavigator/routes.ts, src/features/search/components/SearchCustomModalHeader.tsx, src/features/search/components/SearchFixedModalBottom.tsx, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx, src/features/search/pages/Categories.tsx, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/Categories.native.test.tsx, src/features/search/pages/__tests__/Search.native.test.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx, src/features/search/pages/__tests__/SearchPrice.web.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17107
I have:
|<img width="458" alt="Capture d’écran 2022-09-16 à 17 15 06" src="https://user-images.githubusercontent.com/78556024/191000255-c79bdbbd-02eb-442b-b6fc-b175032730b2.png">|<img width="423" alt="Capture d’écran 2022-09-16 à 17 26 03" src="https://user-images.githubusercontent.com/78556024/191000302-5b1db8f8-a098-4405-a313-3bf2fec6de43.png">|<img width="409" alt="Capture d’écran 2022-09-16 à 17 14 12" src="https://user-images.githubusercontent.com/78556024/191000334-f28046d2-a046-4ce9-8898-c9397dd38aab.png">|<img width="1724" alt="Capture d’écran 2022-09-16 à …
=> (PC-17107) feat(search): use fullscreen modal price filter

src/libs/share/shareApp/shareAppContent.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16983
I have:
=> (PC-16983) fix(share): Edit subject message

__snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap, src/features/cookies/components/CookiesConsentButtons.tsx, src/theme/index.ts, src/ui/theme/grid.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17435
I have:
|  width<=350px   ![localhost_3000_cheat-navigation(iPhone 5_SE)](https://user-images.githubusercontent.com/46637324/191019567-1ce7ef0d-b94e-4542-859b-1404271bbb9d.png) width>350px ![localhost_3000_cheat-navigation(iPhone 12 Pro)](https://user-images.githubusercontent.com/46637324/191019581-a318ba39-3d43-4210-8572-4dd215945d98.png) |         |                 |      ![localhost_3000_cheat-navigation (2)](https://user-images.githubusercontent.com/46637324/191019624-4b7682c3-6228-4c08-95f6-b512d56e04eb.png)      |                  |
[1]: …
=> (PC-17435) fix(cookies): Adjust buttons based on screen width

__snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx, src/features/search/pages/schema/makeSearchPriceSchema.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17450
I have:
=> (PC-17450) fix(SearchPrice): add tests and reset errors when toggling

src/features/bookOffer/components/DuoChoiceSelector.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17137
I have:
| Avant | Après | 
| --: | ------: | 
|   ![Capture d’écran 2022-09-20 à 09 23 23](https://user-images.githubusercontent.com/44037911/191193597-b4dbaa8e-15f3-4713-98b8-34df04629509.png)  |     ![Capture d’écran 2022-09-20 à 09 23 18](https://user-images.githubusercontent.com/44037911/191193647-2124449f-ee3e-401c-a39c-e6f02d89f298.png)    |      
=> (PC-17137) fix(icons): correctly pass props to Profile icon in BookOffer

__snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Categories.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/cookies/components/CookiesConsentModal.tsx, src/features/cookies/components/useCookiesModalContent.tsx, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17435
I have:
| ![Simulator Screen Shot - iPhone 13 - 2022-09-19 at 17 46 39](https://user-images.githubusercontent.com/46637324/191059856-44f6cfd2-f350-4065-af6f-23e21f78158d.png) ![Simulator Screen Shot - iPhone 13 - 2022-09-19 at 17 46 43](https://user-images.githubusercontent.com/46637324/191059858-5ff9a454-239a-4c7a-9e30-9f5867a31679.png)  ![Simulator Screen Shot - iPhone 13 - 2022-09-19 at 17 54 12](https://user-images.githubusercontent.com/46637324/191060592-361aff25-6627-4095-8768-80621ee9ffed.png)![Simulator Screen Shot - iPhone 13 - 2022-09-19 at 17 55 …
=> (PC-17435) refactor(cookies): Use AppModal component instead of custom one

src/ui/components/modals/types.ts
Suite de : https://github.com/pass-culture/pass-culture-app-native/pull/3566
La solution précédente menait à un code smell chez SonarCloud
=> refactor(modal): improve modal props type

src/features/search/atoms/NumberOfResults.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17503
I have:
=> (PC-17503) fix(numberOfResults): use lingui plural

src/features/search/pages/schema/makeSearchPriceSchema.ts
price
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17562
I have:
|     |         |                 |<img width="865" alt="Capture d’écran 2022-09-22 à 10 25 19" src="https://user-images.githubusercontent.com/78556024/191697141-c1212748-c48b-4fbe-b1dd-17f68261bec1.png">|                  |
=> (PC-17562) fix(search): correct wording min/max

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, src/features/search/atoms/NoSearchResult.tsx, src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17219
I have:
|<img width="391" alt="Capture d’écran 2022-09-22 à 12 13 24" src="https://user-images.githubusercontent.com/78556024/191726465-1775638a-2eb5-41da-81ab-9a3f36794e7b.png">|<img width="434" alt="Capture d’écran 2022-09-22 à 12 37 27" src="https://user-images.githubusercontent.com/78556024/191726503-4937494c-14e0-4824-bb77-3971554968ab.png">|<img width="439" alt="Capture d’écran 2022-09-22 à 12 18 44" src="https://user-images.githubusercontent.com/78556024/191726542-390218a8-6ed8-4996-a36a-d0b387fe8c3e.png">|<img width="1474" alt="Capture d’écran 2022-09-22 à …
=> (PC-17219) feat(search): update size no result img

src/features/cookies/__mocks__/useIsCookiesListUpToDate.ts, src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts, src/features/cookies/helpers/useIsCookiesListUpToDate.native.test.ts, src/features/cookies/helpers/useIsCookiesListUpToDate.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/types.ts, src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyV2.tsx, src/features/navigation/__tests__/RootNavigator.web.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx, src/libs/firebase/firestore/__tests__/getCookiesLastUpdate.native.test.ts, src/libs/firebase/firestore/getCookiesLastUpdate.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16604
I have:
=> (PC-16604) feat(cookies): Show modal if cookies list is updated

.github/pr-title-checker.test.ts, .github/workflows/pr-title-checker.yml
New PR title accepted format : 
(BSR) chore(lib): update lib version
=> (BSR) chore(ciTitleCheck): update pr-title-checker regex so it accepts (BSR) and chore

__snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap, eslint-custom-rules/nbsp-in-french-translations.js, src/features/_marketingAndCommunication/atoms/DeeplinkItem.tsx, src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts, src/features/_marketingAndCommunication/pages/DeeplinksGenerator.tsx, src/features/auth/components/QuitSignupModal.native.test.tsx, src/features/auth/components/QuitSignupModal.tsx, src/features/auth/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx, src/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx, src/features/auth/signup/SignupForm.native.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16806
I have:
=> (PC-16806) feat(lingui): remove some nbsp translations

src/features/cookies/api/usePostCookiesConsent.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx
=> fix(cookie): log cookies

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, src/features/search/atoms/NoSearchResult.tsx, src/features/search/atoms/__tests__/NoSearchResult.native.test.tsx
no result
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17221
I have:
|<img width="414" alt="Capture d’écran 2022-09-22 à 16 43 13" src="https://user-images.githubusercontent.com/78556024/191789716-fd2e7263-dfd7-444c-902c-aaa653e50be1.png">|<img width="420" alt="Capture d’écran 2022-09-22 à 16 43 28" src="https://user-images.githubusercontent.com/78556024/191789761-cdf0e98f-5a10-4554-926e-d0a5bf50885f.png">|<img width="489" alt="Capture d’écran 2022-09-22 à 16 43 02" src="https://user-images.githubusercontent.com/78556024/191789810-957f3c84-b027-45b3-8d21-2c6b3a3d085f.png">|<img width="741" alt="Capture d’écran …
=> (PC-17221) feat(search): add update filters button

.circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17580
Avec le `or`, cela ne se lancait pas, donc j'ai modifié le workflow à l'image de ce qui est déjà fait pour `checkout-and-install-deps` en rajoutant `filters.tags.only`:
```tsx
- checkout-and-install-deps:
filters:
tags:
only: /.*/
```
- native: https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/18850/workflows/f227ca19-062b-4d97-85ca-69e5c1619de2/jobs/73698
- web: https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/18850/workflows/f227ca19-062b-4d97-85ca-69e5c1619de2/jobs/73697
- native: https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/18849/workflows/7309288a-9b3e-40b8-b64a-faeb32acacff/jobs/73691
- web: …
=> (PC-17580) ci(Patch): run unit tests on patch and hotfix

.eslintrc.js, server/.eslintrc.js, src/features/bookOffer/pages/BookingOfferWrapper.tsx, src/libs/algolia/analytics/SearchAnalyticsWrapper.tsx, src/libs/geolocation/GeolocationWrapper.tsx, src/libs/splashscreen/splashscreen.tsx
to force, in non-test files, to memo the value provided to the contexts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16443
Amélioration continue justifiée ici : https://www.notion.so/passcultureapp/R-gle-ESLint-pour-nos-contexts-perf-7cc4f1c299b74c22a2f0928eea99def6
=> (PC-16443) chore(eslint): add rule for context perfs

src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17481
I have:
|<img width="410" alt="Capture d’écran 2022-09-23 à 16 35 38" src="https://user-images.githubusercontent.com/78556024/191985831-28d908f7-65e1-4317-a3a0-a14395b8f0f2.png">|         |<img width="413" alt="Capture d’écran 2022-09-23 à 16 35 20" src="https://user-images.githubusercontent.com/78556024/191985877-92e113f0-5eec-4d98-9ecd-700d73229954.png">|<img width="1474" alt="Capture d’écran 2022-09-23 à 16 34 48" src="https://user-images.githubusercontent.com/78556024/191985914-630f2df9-9fa9-48c1-9c57-ce11d3ed9df5.png">|                  |
[1]: …
=> (PC-17481) feat(search): add type filter button search results

.env.integration, .env.production, .env.staging, .env.testing
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17604
=> (PC-17604) feat(resizingImage): use load balancer to retrieve image from cache

src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16988
I have:
=> (PC-16988) feat(cookies): do not send useless request

src/features/auth/signup/VerifyEligiblity/VerifyEligibility.tsx, src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.tsx, src/features/home/atoms/SeeMore.tsx, src/ui/components/Banner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17210
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17021
I have:
=> (PC-17210) feat(Storybook): Update captions and button texts

__snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap, __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/search/components/SearchBox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16732
Tab navigation validated by Gabilux (I demoed it to him)
=> (PC-16732) feat(search): add keyboard tab navigation

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap, patches/eslint-plugin-react-native+3.11.0.patch, src/features/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NewIdentificationFlow/NewIdentificationFlow.tsx, src/features/identityCheck/components/HeroButtonList.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/types.ts, src/ui/svg/icons/BicolorPhonePending.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16995
I have:
https://user-images.githubusercontent.com/44037911/191984041-98a4c7fa-cfb7-4ff2-8d6b-d61dc7931ff2.mov
=> (PC-16995) feat(newIdentificationFlow): create SelectPhoneStatus web page

src/features/favorites/pages/utils/__tests__/sorts.test.ts, src/features/favorites/pages/utils/sorts.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17438
I have:
|     |         |             ![image](https://user-images.githubusercontent.com/77674046/192515085-0ce406dc-167c-4b2c-b770-44af69cd0353.png)    |                  |                  |
=> (PC-17438) fix(Favorites): sort by price place free offers first

__snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Categories.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/components/SearchFixedModalBottom.tsx, src/features/search/pages/SearchPrice.tsx, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17578
I have:
|<img width="404" alt="Capture d’écran 2022-09-27 à 10 25 43" src="https://user-images.githubusercontent.com/78556024/192477916-4d2d238e-360f-4c8e-8e4d-12a7a3f12a53.png"> <img width="379" alt="Capture d’écran 2022-09-27 à 11 07 43" src="https://user-images.githubusercontent.com/78556024/192484626-aaaa6664-cb34-49f0-87bc-3c0e8248a14b.png">|<img width="459" alt="Capture d’écran 2022-09-27 à 10 40 19" src="https://user-images.githubusercontent.com/78556024/192477975-f1f038a7-da1d-418b-b180-783a4129152e.png">|<img width="416" alt="Capture d’écran 2022-09-27 à 10 …
=> (PC-17578) fix(search): improve displaying search price form

src/features/search/atoms/NoSearchResult.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17220
I have:
=> (PC-17220) feat(search): improve accessibility no results

__snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.tsx, src/features/search/pages/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17437
I have:
=> (PC-17437) fix(search): displaying categories landing page

src/libs/utm/getUtmParamsConsent.test.ts, src/libs/utm/getUtmParamsConsent.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17666
I have:
=> (PC-17666) fix(cookies): Check if consent is defined before reading

__snapshots__/features/errors/pages/tests/BannedCountry.native.test.tsx.native-snap, src/features/errors/pages/BannedCountryError.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17368
I have:
=> (PC-17368) fix(countryBan): Fix wording for banned countries

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/navigation/RootNavigator/types.ts, src/features/search/components/FilterSwitchWithLabel.tsx, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx, src/features/search/pages/OfferTypeModal.tsx, src/features/search/pages/__tests__/OfferTypeModal.native.test.tsx, src/ui/svg/icons/bicolor/Thing.tsx, src/ui/svg/icons/bicolor/exports/categoriesIcons.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17482
I have:
| ![Capture d’écran 2022-09-27 à 17 26 03](https://user-images.githubusercontent.com/3414698/192568935-f348758b-f18d-48c4-baa7-91c45530adbb.png) |  
|                 |         |    ![Capture d’écran 2022-09-27 à 17 28 03](https://user-images.githubusercontent.com/3414698/192569231-09be6868-5bf7-450e-95ff-2e6c42a3d6b7.png)              |
=> (PC-17482) feat(SearchV2): ajout de la modal de types

src/features/auth/signup/SignupForm.tsx, src/features/cookies/helpers/startTracking.test.ts, src/features/cookies/helpers/startTracking.ts, src/features/cookies/helpers/startTrackingAcceptedCookies.test.ts, src/features/cookies/helpers/startTrackingAcceptedCookies.ts, src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx, src/libs/amplitude/__mocks__/amplitude.ts, src/libs/amplitude/__mocks__/amplitude.web.ts, src/libs/amplitude/amplitude.ts, src/libs/amplitude/amplitude.web.ts, src/libs/firebase/analytics/__tests__/logEvent.native.test.ts, src/libs/firebase/analytics/provider.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17681
I have:
=> (PC-17681) fix(cookies): Opt out by default from firebase and amplitude

.eslintrc.js, eslint-custom-rules/no-raw-text.js, eslint-custom-rules/no-raw-text.test.js, eslint-local-rules.js, package.json, server/.eslintrc.js, src/features/home/components/HomeHeader.tsx, src/features/identityCheck/pages/identification/identificationStart/IdentityCheckStartContentDesktop.tsx, src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx, src/ui/components/Emoji.tsx, yarn.lock
co-auteurs @bruno-ebstein-pass-culture @marineshaw @voisinhugo 
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17610
I have:
=> (PC-17610) feat(lingui): update no-row-text eslint rule

src/features/search/enums.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17485
I have:
=> (PC-17485) fix(SearchV2): add OfferType ENUM

src/features/search/components/FilterSwitchWithLabel.tsx, src/features/search/pages/OfferTypeModal.tsx, src/features/search/pages/__tests__/OfferTypeModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17485
I have:
=> (PC-17485) fix(SearchV2): CTA on search offer type

src/libs/hooks/useShowReview.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17514
I have:
=> (PC-17514) fix(reviewApp): update useEffect condition for useShowReview

__snapshots__/features/auth/signup/SetBirthday/BirthdayInformationModal/BirthdayInformationModal.native.test.tsx.native-snap, __snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.native-snap, __snapshots__/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx.web-snap, __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap, __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap, src/features/auth/signup/SetBirthday/BirthdayInformationModal/BirthdayInformationModal.tsx, src/features/auth/signup/VerifyEligiblity/VerifyEligibility.tsx, src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.tsx, src/features/firstTutorial/pages/FirstTutorial/components/FirstCard.tsx, src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx, src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.tsx, src/features/identityCheck/pages/identification/errors/hooks/useNotEligibleEduConnectErrorData.ts, src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx, src/features/recreditBirthdayNotification/pages/components/__test__/RecreditBirthdayNotification.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17412
I have:
=> (PC-17412) feat(wording): replace "Gouvernement" by "État"

src/features/profile/components/CreditExplanation/CreditExplanation.native.test.tsx, src/features/profile/components/CreditExplanation/CreditExplanation.tsx, src/features/profile/components/CreditExplanation/getCreditModal.ts, src/features/profile/components/Modals/CreditCeilingsModal.native.test.tsx, src/features/profile/components/Modals/CreditCeilingsModal.tsx, src/features/profile/components/Modals/ExhaustedCreditModal.native.test.tsx, src/features/profile/components/Modals/ExhaustedCreditModal.tsx, src/features/profile/components/Modals/ExpiredCreditModal.native.test.tsx, src/features/profile/components/Modals/ExpiredCreditModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17508
I have:
=> (PC-17508) fix(analytics): remove analytics in useEffect

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.test.tsx.web-snap, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16996
I have:
https://user-images.githubusercontent.com/22886846/192830823-0d7f9fd2-b662-4ff7-be9c-07a6d90fad37.mov
=> (PC-16996) feat(ubbleFlow): navigate from selectIDOrigin to selectPhoneStatus

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap, src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16998
I have:
https://user-images.githubusercontent.com/22886846/192803630-b8561c14-8a9c-4a85-9733-d95fd356b17a.mov
=> (PC-16998) feat(ubbleFlow): navigate from SelectPhoneStatus to SelectIDStatus

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap, src/features/search/atoms/Buttons/ReinitializeFilters.tsx, src/features/search/atoms/Buttons/__tests__/ReinitializeFilters.native.test.tsx, src/features/search/pages/OfferTypeModal.tsx, src/features/search/pages/SearchFilter.tsx, src/features/search/pages/__tests__/OfferTypeModal.native.test.tsx, src/features/search/sections/OfferType.tsx, src/features/search/sections/tests/OfferType.native.test.tsx, src/features/search/sections/tests/analytics.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17489
I have:
=> (PC-17489) fix(SearchV2): use offerType modal in SearchFilter

.github/PULL_REQUEST_TEMPLATE.md
On a fait un post moterm avec @voisinhugo d'une US qui s'est mal passée et qui a été mergée alors que le scénario de base de fonctionnait pas
Un des points remontés par le post mortem : c'est que dans l'urgence, j'ai oublié de vérifier le parcours entier d'un user
J'y aurais peut etre pensé s'il y avait un check ou si la personne qui a fait la review n'avait pas vu la case cochée
=> ci(github): simplify pull request template

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17490
I have:
=> (PC-17490) feat(search): remove ff on offer type search

src/features/identityCheck/pages/identification/errors/hooks/useNotEligibleEduConnectErrorData.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17412
I have:
=> (PC-17412) fix(wording): fix test

src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17464
I have:
=> (PC-17464) feat(cookie): notify sentry when can not log cookies consent choice

src/features/search/pages/Categories.tsx, src/features/search/pages/LocationFilter.tsx, src/features/search/pages/SearchFilter.tsx, src/features/search/pages/SearchPrice.tsx, src/features/search/pages/__tests__/LocationFilter.native.test.tsx, src/features/search/pages/__tests__/SearchFilter.native.test.tsx, src/features/search/pages/__tests__/SearchPrice.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17705
I have:
=> (PC-17705) fix(search): remove useless dispatch + fix bugs

src/features/search/pages/OfferTypeModal.tsx, src/features/search/pages/__tests__/OfferTypeModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17644
I have:
=> (PC-17644) fix(searchV2): manage reset btn in offer type modal

.github/workflows/service-worker-test.yml
…pository
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17188
I have:
=> (PC-17188) ci(Docker): usage of pc image for puppeteer

src/features/search/pages/OfferTypeModal.tsx, src/features/search/pages/__tests__/OfferTypeModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17486
I have:
=> (PC-17486) fix(searchV2): add missing rule to display duo offer

.github/workflows/service-worker-test.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17727
I have:
=> (PC-17727) ci(ServiceWorkerTest): send message to slack

__snapshots__/libs/recaptcha/ReCaptcha.native.test.tsx.native-snap
=> (PC-17231) fix(android): Update snapshot

.github/workflows/repository-test-dispatch.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-PC-17727
I have:
=> (PC-17727) ci(testDispatch): add file to test dispatch

.circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17727
I have:
=> (PC-17727) ci(ServiceWorkerTest): add service worker test

__snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap, __snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap, __snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap, __snapshots__/features/offer/pages/__tests__/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/cookies/components/CookiesSettings.tsx, src/ui/components/AccordionItem.tsx, src/ui/components/FilterSwitch.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17165
I have:
(Pas de régression visuelle)
| iOS              |  ![Simulator Screen Shot - iPhone 13 - 2022-09-30 at 18 58 07](https://user-images.githubusercontent.com/46637324/193320386-0efdf3fd-9352-4134-9004-3cfb9099c089.png) |  ![Simulator Screen Shot - iPhone 13 - 2022-09-30 at 18 56 12](https://user-images.githubusercontent.com/46637324/193320026-25fc4cff-4c40-4bb0-93cf-5ebddb859fc6.png) |
| Android          |  ![Screenshot_20220930_185827](https://user-images.githubusercontent.com/46637324/193320369-7e5d49ae-6822-4e38-bc6e-60dc235b3c08.png) |  ![Screenshot_20220930_184833](https://user-images.githubusercontent.com/ …
=> (PC-17165) fix(accessibility): Make cookie switches accessible

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/LocationModal.native.test.tsx.native-snap, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx, src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx, src/features/search/pages/__tests__/LocationModal.web.test.tsx, src/features/search/pages/__tests__/Search.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17647
I have:
| iOS              |        |<img width="401" alt="Capture d’écran 2022-10-03 à 10 46 51" src="https://user-images.githubusercontent.com/78556024/193540784-ccc20eb4-34b8-4bf3-b561-c8209c414a77.png">|
| Android          |        |<img width="426" alt="Capture d’écran 2022-10-03 à 10 47 37" src="https://user-images.githubusercontent.com/78556024/193540884-4e8216c8-4b5d-49c3-8fa3-253e8555656d.png">|
| Phone - Chrome   |        |<img width="404" alt="Capture d’écran 2022-10-03 à 10 36 06" src="https://user-images.githubusercontent.com/78556024/193540937-15bd8a23-032f-4d9c-907a-f74fcc618500.png">|
| Tablet …
=> (PC-17647) feat(search): add new location filter page

src/features/auth/AuthContext.test.tsx, src/features/cookies/components/CookiesSettings.native.test.tsx, src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesDetails.native.test.tsx, src/features/firstLogin/CulturalSurvey.native.test.tsx, src/features/profile/pages/ConsentSettings/NewConsentSettings.native.test.tsx, src/libs/recaptcha/ReCaptcha.native.test.tsx, src/libs/utm/getUtmParamsConsent.test.ts, src/libs/utm/storeUtmParams.test.ts
Co-authored-by: bruno ebstein <bruno.ebstein@passculture.app>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17645
I have:
=> (PC-17645) fix(cookies): add FF appEnableCookiesV2 to useCookies

src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16981
I have:
| Desktop - Chrome |   ![image (10)](https://user-images.githubusercontent.com/62059034/193560798-2eda1588-1bb5-4fa2-acd3-64d6acac7fae.png)  |  <img width="1060" alt="Capture d’écran 2022-10-03 à 12 54 18" src="https://user-images.githubusercontent.com/62059034/193560699-74a78331-db26-4f08-8677-23d0c7451564.png"> |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf61346 …
=> (PC-16981) fix(profile): add space to NonBeneficiaryHeader (PC-17764)

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.test.tsx.web-snap, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx
| Desktop - Chrome | <img width="1015" alt="image" src="https://user-images.githubusercontent.com/89008469/193588125-40ba3aac-6209-440e-8f69-dab6ad4fee7c.png"> | <img width="1017" alt="image" src="https://user-images.githubusercontent.com/89008469/193587908-be7faf6d-d815-43a2-bc9b-46086f68757c.png"> |
=> (PC-16830) fix(SelectIdStatus): add a testAlign style property to the page subtitle

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap, __snapshots__/ui/components/inputs/Slider.native.test.tsx.native-snap, src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx, src/ui/components/inputs/Slider.native.test.tsx, src/ui/components/inputs/Slider.stories.tsx, src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17648
I have:
| iOS              |        |<img width="401" alt="Capture d’écran 2022-10-04 à 12 19 11" src="https://user-images.githubusercontent.com/78556024/193796357-f8ea9e74-5cc6-4c7e-9df8-9e491bb44044.png"> <img width="400" alt="Capture d’écran 2022-10-04 à 12 19 19" src="https://user-images.githubusercontent.com/78556024/193796361-8ff9b217-0ff9-4a53-bf6e-ce90fc3a0a9b.png"> <img width="431" alt="Capture d’écran 2022-10-04 à 12 19 27" src="https://user-images.githubusercontent.com/78556024/193796363-ace182f2-af45-4153-a45d-afdcf8a02ebd.png">|
| Android          |        |<img width="434" alt="Capture d’écran …
=> (PC-17648) feat(search): add precise radius around me

__snapshots__/libs/recaptcha/ReCaptcha.native.test.tsx.native-snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16960
I have:
=> (PC-16960) fix(snapshots): update snapshots

src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17793
I have:
=> (PC-17793) feat(search): reset location following position

__snapshots__/features/search/pages/__tests__/Categories.native.test.tsx.native-snap, src/features/search/pages/Categories.tsx, src/features/search/pages/__tests__/Categories.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17801
I have:
| Phone - Chrome   |        |   ![image](https://user-images.githubusercontent.com/77674046/193857375-0beecd72-3c93-4aaf-9801-8fd61afcbec1.png)    |
| Desktop - Chrome |        |  ![image](https://user-images.githubusercontent.com/77674046/193857315-22e90e4f-5c6d-4667-b499-d6431701f384.png)     |
=> (PC-17801) fix(SearchV2): form for categories

src/features/search/pages/OfferTypeModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17800
I have:
=> (PC-17800) fix(SearchV2): use Ul > Li in OfferType form

__snapshots__/features/identityCheck/pages/identification/identificationStart/IdentityCheckStart.web.test.tsx.web-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap, __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap, __snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap, __snapshots__/features/search/sections/tests/Category.native.test.tsx.native-snap, __snapshots__/features/search/sections/tests/Price.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, src/features/search/atoms/FilterRow.tsx
Co-authored-by: Ali RAIKI <aliraiki@users.noreply.github.com>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17798
I have:
(Pas de régression)
| iOS              |   ![Simulator Screen Shot - iPhone 13 - 2022-10-05 at 10 48 15](https://user-images.githubusercontent.com/46637324/194020092-4bef82b4-64b7-4aca-9acb-30b309499ce9.png)     |   ![Simulator Screen Shot - iPhone 13 - 2022-10-05 at 10 44 08](https://user-images.githubusercontent.com/46637324/194019647-e9d6ed8f-31ce-41a0-aae8-390c0ff46d87.png)    |
| Desktop - Chrome |     <img width="1440" alt="Capture d’écran 2022-10-05 à 10 …
=> (PC-17798) fix(filterPage): fix a11y for filter

.eslintrc.js, __snapshots__/ui/components/inputs/Slider.native.test.tsx.native-snap, src/features/cookies/components/CookiesConsentModal.tsx, src/features/search/components/FilterPageButtons/FilterPageButtons.tsx, src/features/search/components/SearchFixedModalBottom.tsx, src/features/search/pages/Categories.tsx, src/features/search/pages/LocationModal.tsx, src/features/search/pages/OfferTypeModal.tsx, src/features/search/pages/SearchPrice.tsx, src/theme/index.ts, src/ui/components/inputs/Slider.tsx, src/ui/components/modals/AppModal.tsx, src/ui/components/modals/ModalHeader.tsx, src/ui/components/modals/appModalContainerStyle.ts
Co-authored-by: anoukhello <anoukhello@users.noreply.github.com>
Co-authored-by: Lucas BENESTON <Lucasbeneston@users.noreply.github.com>
Co-authored-by: dbenfouzari-pass <dbenfouzari-pass@users.noreply.github.com>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17819
I have:
| iOS              |<img width="351" alt="Capture d’écran 2022-10-05 à 11 42 48" src="https://user-images.githubusercontent.com/78556024/194031316-afcbd1b8-3511-41f3-b895-4ccb48318205.png">|<img width="402" alt="Capture d’écran 2022-10-05 à 11 38 22" src="https://user-images.githubusercontent.com/78556024/194030747-7b0f3f45-f8df-4e44-86c6-17c0da417a5e.png">|
| Android          |<img width="416" …
=> (PC-17819) feat(search): slider accessibility

src/features/search/components/SearchBox.tsx, src/features/search/components/__tests__/SearchBox.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17004
I have:
=> (PC-17004) feat(search): back button accessible

__snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.tsx, src/features/search/components/SearchHeader.tsx, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchHeader.native.test.tsx, src/features/search/pages/__tests__/Search.native.test.tsx
Co-authored-by: Lucas BENESTON <Lucasbeneston@users.noreply.github.com>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17821
I have:
| iOS              |        |  <img width="358" alt="Capture d’écran 2022-10-05 à 18 15 28" src="https://user-images.githubusercontent.com/62059034/194236982-570b20ea-a640-4df5-a58c-2a5f83fa0970.png"> <img width="427" alt="Capture d’écran 2022-10-05 à 18 15 49" src="https://user-images.githubusercontent.com/62059034/194236990-315bae67-77ed-43e7-9ebc-a50bac7dc33d.png"> <img width="408" alt="Capture d’écran 2022-10-05 à 18 15 58" src="https://user-images.githubusercontent.com/62059034/194236998-dd303f42-1f5a-422a-8df7-7cf75f1843f2.png"> …
=> (PC-17821) feat(search): add title to result page

src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts, src/features/cookies/helpers/useCookiesChoiceByCategory.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesDetails.native.test.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyV2.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17630
I have:
=> (PC-17630) fix(privacy): modale not showing

__snapshots__/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx.native-snap, src/features/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NewIdentificationFlow/NewIdentificationFlow.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16838
I have:
| iOS              |![Simulator Screen Shot - iPhone 13 - 2022-10-04 at 17 59 13](https://user-images.githubusercontent.com/22886846/193872493-98e58882-6103-4539-8704-095b23b4bc89.png)|
| Android          |<img width="508" alt="Capture d’écran 2022-10-04 à 17 59 10" src="https://user-images.githubusercontent.com/22886846/193872355-74c417b4-7f68-4dcf-8a29-929f04c020ca.png">|
| Desktop - Chrome |<img width="1049" alt="Capture d’écran 2022-10-04 à 17 58 59" src="https://user-images.githubusercontent.com/22886846/193872334-00f77d44-b351-4d10-8a6c-b96133b4454e.png">|
[1]: …
=> (PC-16838) feat(ubbleFlow): add expired or lost ID page

src/features/search/components/SearchHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17797
I have:
=> (PC-17797) fix(ci): Fix test due to merge conflict

src/features/identityCheck/pages/profile/SetStatus.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17380
I have:
=> (PC-17380) feat(profile): update SetStatus page to use `react-hook-form`

src/features/search/components/SearchAutocomplete.tsx, src/features/search/components/SearchAutocompleteItem.tsx, src/features/search/components/__tests__/Highlight.native.test.tsx, src/features/search/components/__tests__/SearchAutocompleteItem.native.test.tsx, src/features/search/pages/Search.tsx, src/features/search/pages/__tests__/Search.native.test.tsx, src/libs/algolia/algolia.d.ts, src/libs/algolia/analytics/InsightsMiddleware.ts, src/libs/algolia/analytics/logClickOnOffer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17348
I have:
~- Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change~
~- If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion](1)~
=> (PC-17348) feat(search): send event on search suggestion click

__snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Categories.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/LocationModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx, src/ui/components/modals/AppModal.tsx
Autour de moi
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17648
I have:
=> (PC-17648) feat(search): desactivation scroll around me

__snapshots__/features/profile/components/Modals/ExhaustedCreditModal.native.test.tsx.native-snap, __snapshots__/features/profile/components/Modals/ExpiredCreditModal.native.test.tsx.native-snap, src/features/profile/components/Modals/ExpiredOrExhaustedCreditModalContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17794
I have:
=> (PC-17794) fix(Credit): remove false info in ExpiredOrExhaust credit modal

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap, src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/identityCheck/components/HeroButtonList.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17695
I have:
=> (PC-17695) feat(HeroButtonList): update component to make it a TouchableLink

__snapshots__/features/identityCheck/pages/identification/dms/DMSIntroduction.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx.native-snap, src/features/identityCheck/pages/identification/dms/DMSIntroduction.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16832
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16838
I have:
**DMSIntroduction**
| iOS (iPhone 13) |![IMG_2636](https://user-images.githubusercontent.com/22886846/194569525-8ef13c57-40f0-4952-85c7-15156a1bd64e.PNG)|![Simulator Screen Shot - iPhone 13 - 2022-10-07 at 15 25 08](https://user-images.githubusercontent.com/22886846/194569019-58317df5-4ee5-471b-a89d-20fdf4613f7c.png)|
| iOS (iPhone 5s) |![Simulator Screen Shot - iPhone 5s - 2022-10-07 at 15 49 43](https://user-images.githubusercontent.com/22886846/194569299-3aa66d7b-d689-4152-a229-d3881fe21a26.png)|![Simulator Screen Shot - iPhone 5s - 2022-10-07 at 15 49 …
=> (PC-16832) fix(ubbleFlow): update ui to fit mockup

__snapshots__/features/identityCheck/pages/identification/ComeBackLater.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/ComeBackLater.test.tsx.web-snap, src/features/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NewIdentificationFlow/NewIdentificationFlow.tsx, src/features/identityCheck/pages/identification/ComeBackLater.test.tsx, src/features/identityCheck/pages/identification/ComeBackLater.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16836
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16842
I have:
| Platform         | Before |
| iOS              | <img width="374" alt="image" src="https://user-images.githubusercontent.com/89008469/194343323-dd150265-5808-40b7-bf98-051973cc2022.png"> |
| Desktop - Chrome | <img width="1048" alt="image" src="https://user-images.githubusercontent.com/89008469/194343418-a69ead20-4404-47ad-abbd-a4537986e7e4.png"> |
=> (PC-16836) feat(ComeBackLater): create comeBackLater screen

__mocks__/libs/react-native-batch.ts, src/App.native.test.tsx, src/App.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17777
I have:
| iOS              |        |  ![Simulator Screen Shot - iPhone 13 - 2022-10-10 at 06 06 46](https://user-images.githubusercontent.com/46637324/194798054-978c9860-7cd6-4d0d-9146-024fe8df1aa9.png)     |
| Android          |        |     ![Screenshot_20221010_061315](https://user-images.githubusercontent.com/46637324/194798450-81ba9621-c022-4de1-9333-ae62123674f4.png)  |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754 …
=> (PC-17777) feat(notifications): Override Batch font

__snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx.web-snap, __snapshots__/features/bookings/components/TicketBody/NoTicket/NoTicket.test.tsx.native-snap, __snapshots__/features/bookings/components/TicketBody/NoTicket/NoTicket.test.tsx.web-snap, __snapshots__/features/offer/pages/__tests__/OfferBody.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Categories.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/bookings/components/TicketBody/NoTicket/NoTicket.tsx, src/features/bookings/components/TicketBody/TicketWithdrawal/TicketWithdrawal.tsx, src/features/search/components/CategoriesButtons/useSortedSearchCategories.test.tsx, src/libs/search/utils/getCategoriesFacetFilters.ts, src/libs/subcategories/__tests__/useSearchGroupLabel.test.ts, src/libs/subcategories/fixtures/mappings.ts, src/libs/subcategories/placeholderData.ts
Both forms are correct but we should use one consistently, not both.
---
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-17842 
Lien vers la PR correspondante côté API et portail pro : https://github.com/pass-culture/pass-culture-main/pull/3816
Je n'ai fait aucune vérification ci-dessous parce qu'elles ne me semblent pas pertinentes :
=> (PC-17842) fix(spelling): Use "évènement", not "événement"

__snapshots__/features/bookings/components/NoBookingsView.test.tsx.native-snap, __snapshots__/features/bookings/components/NoBookingsView.test.tsx.web-snap, __snapshots__/features/favorites/pages/__tests__/Favorites.native.test.tsx.native-snap, src/features/bookings/components/NoBookingsView.test.tsx, src/features/bookings/components/NoBookingsView.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/bookings/pages/Bookings.native.test.tsx, src/features/bookings/pages/Bookings.web.test.tsx, src/features/favorites/atoms/NumberOfResults.tsx, src/features/favorites/components/NoFavoritesResult.tsx, src/features/favorites/components/__tests__/FavoritesResults.native.test.tsx, src/features/favorites/components/__tests__/FavoritesResults.web.test.tsx, src/features/favorites/components/__tests__/NoFavoritesResult.test.tsx, src/ui/components/NoResults.tsx, src/ui/components/NoResultsView.tsx, src/ui/components/placeholders/Placeholders.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16925
I have:
| Desktop - Chrome |  ![Capture d’écran 2022-10-07 à 16 07 30](https://user-images.githubusercontent.com/62059034/194834340-3a7a0bc8-d06a-4016-92ac-2c1551685dcb.png)  |   <img width="1021" alt="Capture d’écran 2022-10-10 à 11 00 36" src="https://user-images.githubusercontent.com/62059034/194834406-8ca8592a-9669-47ed-a152-ade153e27646.png">  |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bug …
=> (PC-16965) feat(favoritesAndBookings): update wording and design for NoBookingsView and NoFavoritesResult

src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16840
I have:
https://user-images.githubusercontent.com/22886846/194585356-15bb2488-e24e-46d6-aa01-1beff36074c9.mov
=> (PC-16840) feat(expiredID): open ants url on 'Demander un renouvellement' press

patches/instantsearch.js+4.43.1.patch, src/features/search/components/SearchAutocomplete.tsx, src/features/search/components/SearchAutocompleteItem.tsx, src/features/search/components/__tests__/Highlight.native.test.tsx, src/features/search/components/__tests__/SearchAutocompleteItem.native.test.tsx, src/features/search/pages/Search.tsx, src/features/search/pages/__tests__/Search.native.test.tsx, src/libs/algolia/algolia.d.ts, src/libs/algolia/analytics/InsightsMiddleware.ts, src/libs/algolia/analytics/logClickOnOffer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17348
I have:
=> (PC-17348) feat(search): send event on search suggestion click 

src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16839
I have:
| iOS              | https://user-images.githubusercontent.com/89008469/194901946-5e753ca9-b7ac-4dcf-87e5-2b3b472b5d86.mp4 |       |
=> (PC-16839) feat(SelectIDStatus): add navigation from SelectIDStatus to ExpiredOrLostID

doc/installation/iOS.md
Add 2 classic troubleshootings to the documentation
=> (BSR) chore(iOS): add 2 troubleshootings to the iOS set up documentation

src/features/identityCheck/pages/identification/dms/DMSIntroduction.native.test.tsx, src/features/identityCheck/pages/identification/dms/DMSIntroduction.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17774
I have:
https://user-images.githubusercontent.com/22886846/195060616-e2e4ddad-cd2c-41ab-9a89-e95f7327e8ab.mov
=> (PC-17774) feat(DMSIntroduction): open DMS link

src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16997
I have:
| iOS              |https://user-images.githubusercontent.com/89008469/195048455-a075339a-2d95-4c32-b30c-040ba29fac61.mp4|       |
=> (PC-16997) feat(SelectPhoneStatus): navigate to DMS Introduction FR

__snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, src/features/profile/atoms/Title.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16966
I have:
| iOS              |   <img width="349" alt="Capture d’écran 2022-10-12 à 09 34 00" src="https://user-images.githubusercontent.com/62059034/195279115-3bb471eb-eb27-4158-950e-38537afa156f.png">  |  <img width="339" alt="Capture d’écran 2022-10-12 à 09 18 03" src="https://user-images.githubusercontent.com/62059034/195279162-3728bf6d-7930-460f-a5ab-a5308c85e9ef.png">   |
[1]: …
=> (PC-16966) fix(profile): add TopScreen to title

__snapshots__/features/auth/login/Login.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/EndedBookings.native.test.tsx.native-snap, src/features/bookings/components/BookingItemTitle.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/pages/EndedBookings.native.test.tsx, src/features/bookings/pages/EndedBookings.tsx, src/features/cheatcodes/pages/AppComponents/iconsExports.ts, src/ui/components/inputs/InputError.tsx, src/ui/components/inputs/rules/InputRule.tsx, src/ui/svg/icons/Valid.tsx, src/ui/svg/icons/Wrong.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17857
I have:
| Desktop - Chrome |        |  ![Capture d’écran 2022-10-11 à 17 12 56](https://user-images.githubusercontent.com/62059034/195134346-8899dca8-3008-4a9f-802a-5fa5c146f92b.png) ![Capture d’écran 2022-10-11 à 16 58 28](https://user-images.githubusercontent.com/62059034/195134507-03e81a0d-b196-415e-806b-f15f107b7f98.png) ![Capture d’écran 2022-10-11 à 17 01 04](https://user-images.githubusercontent.com/62059034/195134660-3b00241f-e5eb-420b-b8d0-815c1e5cde8d. …
=> (PC-17857) feat(bookings): update design for EndedBookingItem and EndedBookings

src/features/home/api.test.ts, src/features/home/api.ts, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17803
I have:
=> (PC-17803) refactor(LogConsultHome): rename param key

__snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap, __snapshots__/features/_marketingAndCommunication/pages/__tests__/UTMParameters.test.tsx.web-snap, __snapshots__/features/favorites/pages/__tests__/Favorites.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.web.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap, __snapshots__/features/offer/pages/__tests__/OfferDescription.web.test.tsx.web-snap, __snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap, __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap, src/features/bookings/pages/Bookings.tsx, src/features/favorites/pages/Favorites.tsx, src/features/profile/components/Header/HeaderWithGreyContainer/HeaderWithGreyContainer.tsx, src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx, src/ui/components/PageTitle.stories.tsx, src/ui/components/PageTitle.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16966
I have:
| iOS              |   ![Simulator Screen Shot - iPhone 13 - 2022-10-12 at 19 18 51](https://user-images.githubusercontent.com/46637324/195407351-646060c6-d13c-4a9b-b738-929fe463bbcd.png)![Simulator Screen Shot - iPhone 13 - 2022-10-12 at 19 18 53](https://user-images.githubusercontent.com/46637324/195407354-6ea3bd39-06c9-4c9d-bd7a-3d382acde375.png)![Simulator Screen Shot - iPhone 13 - 2022-10-12 at 19 18 55](https://user-images.githubusercontent.com/46637324/195407356-76767cb5-9138-4e2a-97fd-7e5b83ff6db4.png)    |     ![Simulator Screen Shot - iPhone 13 - 2022-10-12 at 19 11 …
=> (PC-16966) fix(headers): Use same components for page headers

__snapshots__/features/identityCheck/pages/identification/identificationStart/ComeBackLater.native.test.tsx.native-snap, src/features/identityCheck/pages/identification/identificationStart/ComeBackLater.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16836
I have:
| iOS              | <img width="388" alt="image" src="https://user-images.githubusercontent.com/89008469/195376061-da5c294d-7c60-4b21-882b-1280c0c4602c.png"> | <img width="394" alt="image" src="https://user-images.githubusercontent.com/89008469/195375366-e8b840c1-fd27-4e3f-b74d-eae19f9e94e7.png">|
=> (PC-16836) fix(ComeBackLater): fix ui for button

src/features/identityCheck/components/FastEduconnectConnectionRequestModal.native.test.tsx, src/features/identityCheck/components/FastEduconnectConnectionRequestModal.tsx, src/features/identityCheck/pages/Stepper.native.test.tsx, src/features/identityCheck/pages/__test__/Stepper.test.tsx, src/features/identityCheck/useIdentityCheckSteps.test.tsx, src/features/identityCheck/useIdentityCheckSteps.tsx, src/libs/firebase/firestore/featureFlags/index.ts, src/libs/firebase/firestore/featureFlags/newIdentificationFlow.native.test.ts, src/libs/firebase/firestore/featureFlags/newIdentificationFlow.ts, src/libs/firebase/firestore/getCookiesLastUpdate.native.test.ts, src/libs/firebase/firestore/maintenance.native.test.ts, src/libs/firebase/firestore/types.ts, src/libs/firebase/firestore/ubbleETAMessage.native.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17895
I have:
https://user-images.githubusercontent.com/22886846/195403299-71f7ed7c-a414-4413-8546-7a516337266a.mov
https://user-images.githubusercontent.com/22886846/195403371-1e434ba0-0989-4c61-bd6e-ee77512fc5fb.mov
=> (PC-17895) feat(ubbleFlow): use firestore feature flag

__snapshots__/features/identityCheck/pages/identification/dms/DMSIntroduction.native.test.tsx.native-snap, src/features/identityCheck/pages/identification/dms/DMSIntroduction.native.test.tsx, src/features/identityCheck/pages/identification/dms/DMSIntroduction.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17491
I have:
=> (PC-17491) feat(IntroDMS): add tracker to DMS nav button press

doc/development/trackers.md, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx, src/features/identityCheck/pages/phoneValidation/__tests__/SetPhoneValidationCode.native.test.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17203
I have:
=> (PC-17203) feat(SetPhoneValidationCode): add tracker to missing code button press

src/features/identityCheck/pages/phoneValidation/CodeNotReceivedModal.tsx, src/features/identityCheck/pages/phoneValidation/__tests__/CodeNotReceivedModal.native.test.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17202
I have:
=> (PC-17202) feat(CodeNotReceivedModal): add tracker to 'Demander un autre code' button press

__snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap, __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.native.test.tsx.native-snap, __snapshots__/features/favorites/pages/__tests__/FavoritesSorts.web.test.tsx.web-snap, __snapshots__/features/search/pages/__tests__/Categories.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/LocationModal.native.test.tsx.native-snap, src/features/search/pages/Categories.tsx, src/ui/components/radioButtons/RadioButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17166
I have:
| iOS              |<img width="407" alt="Capture d’écran 2022-10-17 à 18 08 17" src="https://user-images.githubusercontent.com/78556024/196228104-8f88c89e-9b64-4e96-a1f4-c56f48bb1006.png">|<img width="401" alt="Capture d’écran 2022-10-17 à 17 42 07" src="https://user-images.githubusercontent.com/78556024/196226098-a8dc0191-f243-4429-b428-f4d8d7e90d11.png">|
| Android          |<img width="442" alt="Capture d’écran 2022-10-17 à 18 08 21" src="https://user-images.githubusercontent.com/78556024/196228169-681db4bb-a906-4680-ace2-757bcb8ef62e.png">|<img width="433" alt="Capture d’écran 2022-10-17 à 17 42 …
=> (PC-17166) fix(search): UI improvements

src/features/auth/signup/SetEmail/SetEmail.tsx, src/features/auth/signup/SetEmail/SetEmail.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18030
I have:
| Desktop - Chrome |        |   https://user-images.githubusercontent.com/46637324/196367643-82e8cd2d-78da-41f1-b043-1f437e5b80f4.mov    |
=> (PC-18030) fix(accessibility): Check newsletter checkbox on spacebar press

__snapshots__/features/search/pages/__tests__/LocationModal.native.test.tsx.native-snap, src/features/search/pages/LocationModal.tsx, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18018
I have:
=> (PC-18018) fix(search): avoid double tap choose venue or place

__snapshots__/features/auth/signup/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx.native-snap, src/features/auth/signup/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx, src/features/auth/signup/FinishSubscriptionModal/FinishSubscriptionModal.tsx, src/features/cheatcodes/pages/NavigationSignUp/NavigationSignUp.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17891
I have:
| Desktop - Chrome |        |   ![Capture d’écran 2022-10-18 à 17 05 26](https://user-images.githubusercontent.com/62059034/196469226-35c26e80-f378-4fcc-a39c-e99b1bc8fd9e.png) ![Capture d’écran 2022-10-18 à 17 05 17](https://user-images.githubusercontent.com/62059034/196469230-0bc65ee8-e922-4c59-af99-872045006448.png)  | …
=> (PC-17891) feat(cta): add FinishSubscriptionModal to cheatcode

src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnectForm.tsx
[Lien Erreur Sentry corrigée](https://sentry.passculture.team/organizations/sentry/issues/397685/?environment=development&query=is%3Aunresolved)
[Lien Jira Erreur Sentry](https://passculture.atlassian.net/browse/PC-17886 )
=> (PC-17886) fix(Sentry): Module WebViewMessageHandler7 is not a registered callable module

src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18028
I have:
=> (PC-18028) fix(search): preserve values location filter

__snapshots__/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx.native-snap, src/features/auth/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx, src/features/auth/forgottenPassword/ForgottenPassword/tests/ForgottenPassword.native.test.tsx, src/libs/network/NetInfoWrapper.tsx, src/libs/network/__mocks__/NetInfoWrapper.tsx, src/libs/network/__mocks__/useNetInfo.ts, src/libs/network/__mocks__/useNetInfo.web.ts, src/libs/network/__tests__/NetInfoWrapper.native.test.tsx, src/libs/network/__tests__/useNetInfo.native.test.ts, src/libs/network/__tests__/useNetInfo.web.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17381
I have:
=> (PC-17381) feat(ForgottenPassword): use `react-hook-form`

__snapshots__/features/identityCheck/pages/identification/identificationStart/IdentityCheckStart.web.test.tsx.web-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap, __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap, __snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, src/features/search/atoms/Buttons/GeolocationButton.stories.tsx, src/features/search/atoms/Buttons/GeolocationButton.tsx, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18044
I have:
| iOS              |<img width="439" alt="Capture d’écran 2022-10-20 à 11 41 43" src="https://user-images.githubusercontent.com/78556024/196915749-81422376-d7d7-404a-8ed6-2bebcb122a8d.png">|<img width="448" alt="Capture d’écran 2022-10-20 à 11 40 09" src="https://user-images.githubusercontent.com/78556024/196915703-14b54a86-d960-4e8f-8cfc-aeb13ecd5d29.png">|
| Android          |<img width="424" alt="Capture d’écran 2022-10-20 à 11 41 49" src="https://user-images.githubusercontent.com/78556024/196915868-26d654de-3f5d-4e40-9e66-b5d340a75620.png">|<img width="424" alt="Capture d’écran 2022-10-20 à 11 41 …
=> (PC-18044) feat(search): add location incitation button

.vscode/story.code-snippets
https://www.loom.com/share/f9f99221751a403d84a31897c6e68122
=> (BSR) feat(Storybook): create snippet for stories

src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18044
I have:
| iOS             |<img width="381" alt="Capture d’écran 2022-10-21 à 15 38 25" src="https://user-images.githubusercontent.com/78556024/197213129-933be9b0-4fdc-4201-9b12-68778f189d5a.png">|<img width="409" alt="Capture d’écran 2022-10-21 à 15 41 27" src="https://user-images.githubusercontent.com/78556024/197213203-e8eba913-ba71-43b0-b1fd-54862c70a275.png">|
| Android          |<img width="431" alt="Capture d’écran 2022-10-21 à 15 37 48" src="https://user-images.githubusercontent.com/78556024/197212964-7670dcb6-c11f-4a50-9f46-0d7b34ecf180.png">|<img width="429" alt="Capture d’écran 2022-10-21 à 15 41 …
=> (PC-18044) fix(search): spacing geolocation incitation no results

__snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtons/CategoriesButtonsDisplay.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17805
I have:
(Pas de modif)
| iOS              |    ![Simulator Screen Shot - iPhone 11 Pro Max - 2022-10-24 at 09 58 40](https://user-images.githubusercontent.com/46637324/197476519-228bd94a-24fa-4fb0-8ffa-088dd0080fba.png)    |   ![Simulator Screen Shot - iPhone 11 Pro Max - 2022-10-24 at 09 46 45](https://user-images.githubusercontent.com/46637324/197476040-0ce3dba9-0190-4770-be64-cf57ef411176.png)    |
| Desktop - Chrome |   <img width="1189" alt="Capture d’écran 2022-10-24 à 09 57 11" …
=> (PC-17805) fix(accessibility): Structure landing page categories

.gitignore, scripts/appcenter-download-release.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18153
I have:
=> (PC-18153) ci(scripts): ability to keep download apk from command line

__snapshots__/features/offer/components/redirectionModals/AuthenticationModal/AuthenticationModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/redirectionModals/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx.native-snap, src/features/offer/components/redirectionModals/AuthenticationModal/AuthenticationModal.tsx, src/features/offer/components/redirectionModals/FinishSubscriptionModal/FinishSubscriptionModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17981
I have:
| Desktop - Chrome |        |    <img width="1792" alt="Capture d’écran 2022-10-24 à 15 46 16" src="https://user-images.githubusercontent.com/62059034/197543073-f2cc3726-13af-421b-bbf4-672042c61051.png"> <img width="1792" alt="Capture d’écran 2022-10-24 à 15 46 07" src="https://user-images.githubusercontent.com/62059034/197543084-867fe690-defc-46b6-bb01-111f73f42b56.png">   |
[1]: …
=> (PC-17891) feat(offer): add line break to FinishSubscriptionModal title

src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx, src/features/search/sections/tests/Location.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18127
I have:
Before : https://user-images.githubusercontent.com/78556024/197484333-9a2dc166-45cf-4ea6-882e-a8b76337325d.mov
After : https://user-images.githubusercontent.com/78556024/197484385-5c5f1a65-7360-450c-b39b-b88c87a49b32.mov
=> (PC-18127) fix(search): no search execution when changing location in search box

src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx, src/features/search/pages/useSetFocusWithCondition.android.ts, src/features/search/pages/useSetFocusWithCondition.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18054
I have:
=> (PC-18054) feat(search): improve focus running place or venue input

__snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap, __snapshots__/features/_marketingAndCommunication/pages/__tests__/UTMParameters.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.web.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap, __snapshots__/features/offer/pages/__tests__/OfferDescription.web.test.tsx.web-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap, __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap, __snapshots__/features/search/components/__tests__/SearchBox.native.test.tsx.native-snap, __snapshots__/features/search/components/__tests__/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/search/atoms/Buttons/HiddenNavigateToSuggestionsButton.tsx, src/features/search/components/SearchBox.tsx, src/features/search/components/SearchHeader.tsx, src/features/search/components/__tests__/SearchHeader.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17858
I have:
Pas de changement en native, voir vidéo pour le comportement web
| iOS              |        |  ![Simulator Screen Shot - iPhone 11 Pro Max - 2022-10-24 at 11 25 25](https://user-images.githubusercontent.com/46637324/197497910-b67ee7b5-746c-41df-8f6d-df5d69f075a7.png)   ![Simulator Screen Shot - iPhone 11 Pro Max - 2022-10-24 at 11 25 30](https://user-images.githubusercontent.com/46637324/197497918-9cfd3c4c-e253-4473-a0b4-62a57c815944.png)    |
| Desktop - Chrome |        | …
=> (PC-17858) fix(accessibility): Make results page accessible

src/features/auth/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17381
I have:
=> (PC-17381) fix(ForgottenPassword): fixed infinite loop

src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/cheatcodes/pages/NavigationAccountSuspension/NavigationAccountSuspension.tsx, src/features/cheatcodes/pages/NavigationErrors/NavigationErrors.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18070
I have:
| Phone - Chrome   |        | |
| Desktop - Chrome | <img width="1186" alt="image" src="https://user-images.githubusercontent.com/68000368/197790728-1ecab64b-5f38-4ac0-97c6-0add918d4c2f.png"> | <img width="1066" alt="image" src="https://user-images.githubusercontent.com/68000368/197790272-967e9445-3386-466a-b126-cc94228008f5.png"> <img width="1119" alt="image" src="https://user-images.githubusercontent.com/68000368/197790350-a7d8d788-7bf9-4f5a-98b3-1ff1a6a14250.png"> <img width="1081" alt="image" …
=> (PC-18070) feat(Cheatcodes): organize errors and email sent

.circleci/config.yml, patches/react-native-web+0.17.5.patch
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18209
I have:
| Desktop - Chrome |        |   <img width="1440" alt="Capture d’écran 2022-10-26 à 09 12 47" src="https://user-images.githubusercontent.com/46637324/197959050-088daadc-56cf-4b6c-8239-3e438589b5d0.png">    |
=> (PC-18209) fix(accessibility): Remove empty list component from ul/li

src/features/search/components/SearchBox.tsx, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchBox.native.test.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx, src/features/search/components/__tests__/useHasPosition.test.ts, src/features/search/components/__tests__/useLocationChoice.test.ts, src/features/search/components/useHasPosition.ts, src/features/search/components/useLocationChoice.ts, src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/LocationModal.native.test.tsx, src/features/search/sections/tests/Location.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18048
I have:
| iOS              |<img width="412" alt="Capture d’écran 2022-10-25 à 16 38 19" src="https://user-images.githubusercontent.com/78556024/197805304-64196d68-ab6d-47f2-8bef-bc83e9ee3a87.png"> <img width="403" alt="Capture d’écran 2022-10-25 à 16 38 26" src="https://user-images.githubusercontent.com/78556024/197805310-92b0407b-844f-4a6f-ac9f-653dfd09ca71.png"> <img width="388" alt="Capture d’écran 2022-10-25 à 16 38 46" src="https://user-images.githubusercontent.com/78556024/197805312-465db8e6-034e-409f-a141-3f3be62cc22c.png">|<img width="402" alt="Capture d’écran 2022-10-25 à 16 39 08" …
=> (PC-18048) feat(search): finalization no location

src/libs/network/__tests__/OfflineModeContainer.test.tsx
=> (BSR) test(OfflineModeContainer): clean test

__snapshots__/features/offer/components/redirectionModals/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx.native-snap, src/features/cheatcodes/pages/AppComponents/illustrationsExports.ts, src/features/cheatcodes/pages/NavigationSignUp/NavigationSignUp.tsx, src/features/offer/components/redirectionModals/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx, src/features/offer/components/redirectionModals/ApplicationProcessingModal/ApplicationProcessingModal.tsx, src/features/offer/components/redirectionModals/components/AddToFavoritesButton.stories.tsx, src/features/offer/components/redirectionModals/components/AddToFavoritesButton.tsx, src/ui/svg/BicolorBookingHold.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17889
I have:
| Android          |        |<img width="407" alt="image" src="https://user-images.githubusercontent.com/68000368/197796915-c8e4d6ab-3398-4e14-aeda-0b60e197338d.png">|
| Phone - Chrome   |        |<img width="387" alt="image" src="https://user-images.githubusercontent.com/68000368/197797075-08875899-4e31-4cff-b4b4-f3bdfeddecee.png">|
| Desktop - Chrome |        |<img width="1440" alt="image" src="https://user-images.githubusercontent.com/68000368/197796976-97dcab06-120a-4373-be15-0030370dd4fb.png">| …
=> (PC-17889) feat(Offer): create application processing modal

CODEOWNERS
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18195
I have:
=> (PC-18195) chore(CODEOWNERS): do not spam at each pull requests

src/api/gen/api.ts, src/features/auth/__mocks__/settings.ts, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18207
I have:
=> (PC-18207) feat(search): remove ff APP_ENABLE_CATEGORY_FILTER_PAGE

src/features/navigation/RootNavigator/linking/getInitialUrl.ios.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18020
I have:
=> (PC-18020) fix(navigation): good redirect

src/App.native.test.tsx, src/App.tsx, src/features/home/pages/Home.tsx, src/features/home/selectHomepageEntry.test.ts, src/features/navigation/RootNavigator/RootNavigator.tsx, src/libs/firebase/remoteConfig/remoteConfig.constants.ts, src/libs/firebase/remoteConfig/remoteConfig.services.ts, src/libs/firebase/remoteConfig/remoteConfig.services.web.ts, src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18239
I have:
=> (PC-18239) fix(notifications): Remove AB Test and request permission at startup

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18167
I have:
| iOS              |<img width="433" alt="Capture d’écran 2022-10-26 à 16 35 39" src="https://user-images.githubusercontent.com/78556024/198056115-5df9025f-3cd2-4ee2-b26d-bdd373d24979.png">|<img width="444" alt="Capture d’écran 2022-10-26 à 16 35 55" src="https://user-images.githubusercontent.com/78556024/198056185-470d9209-ec9a-486a-b464-e9dbcd1ea5c3.png">|
| Desktop - Chrome |<img width="866" alt="Capture d’écran 2022-10-26 à 16 36 14" …
=> (PC-18167) feat(search): add dates & hours filter button results

src/features/offer/components/__tests__/OfferHeader.native.test.tsx, src/features/offer/components/__tests__/OfferHeader.web.test.tsx
=> (BSR) fix(tests): fix offer header tests

src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/cheatcodes/pages/NavigationErrors/NavigationErrors.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18070
I have:
| Phone - Chrome   |        |<img width="1079" alt="image" src="https://user-images.githubusercontent.com/68000368/198075822-c1a4c1fa-694a-4ef7-8877-c7e192790756.png">|
=> (PC-18070) fix(Cheatcodes): update emoji and add one more error in error page

.github/workflows/e2e-android-chrome.yml, .github/workflows/e2e-android-native.yml, .github/workflows/e2e-desktop-chrome.yml, .github/workflows/e2e-ios-native.yml, .github/workflows/e2e-ios-safari.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18308
I have:
=> (PC-18308) ci(e2e): add required jobs

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/DatesHoursModal.native.test.tsx.native-snap, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx, src/features/search/pages/DatesHoursModal.tsx, src/features/search/pages/LocationModal.tsx, src/features/search/pages/__tests__/DatesHoursModal.native.test.tsx, src/features/search/pages/__tests__/DatesHoursModal.web.test.tsx, src/features/search/pages/schema/datesHoursSchema.test.ts, src/features/search/pages/schema/datesHoursSchema.ts, src/features/search/pages/useGetFullscreenModalSliderLength.ts, src/ui/components/inputs/Slider.native.test.tsx, src/ui/components/inputs/Slider.stories.tsx, src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18165
I have:
| iOS              |        |<img width="408" alt="Capture d’écran 2022-10-28 à 16 03 32" src="https://user-images.githubusercontent.com/78556024/198631367-87816049-9486-4a86-9edd-a59d7ceabc95.png"> <img width="416" alt="Capture d’écran 2022-10-28 à 15 46 13" src="https://user-images.githubusercontent.com/78556024/198621643-d4c6fd88-c087-4569-89ca-d2de5010a1d2.png">|
| Android          |        |<img width="452" alt="Capture d’écran 2022-10-28 à 16 03 26" src="https://user-images.githubusercontent.com/78556024/198631494-849160ad-259a-47ea-bd87-2e9a68d26388.png"> <img width="449" alt="Capture d’écran …
=> (PC-18165) feat(search): date & hours modal filter

sonar-project.properties
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17611
I have:
=> (PC-17611) feat(sonar): exclude .web files for scan analysis

src/features/search/pages/DatesHoursModal.tsx, src/features/search/pages/__tests__/DatesHoursModal.native.test.tsx, src/features/search/pages/__tests__/DatesHoursModal.web.test.tsx, src/features/search/pages/__tests__/reducer.test.ts, src/features/search/pages/reducer.ts, src/features/search/sections/DateHour.tsx, src/features/search/types.ts, src/libs/algolia/__tests__/fetchAlgolia.test.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildNumericFilters.ts, src/libs/search/__tests__/parseSearchParameters.test.ts, src/libs/search/parseSearchParameters.ts
filter
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18293
I have:
=> (PC-18293) fix(search): refresh results with date

src/features/search/sections/DateHour.tsx, src/features/search/sections/tests/DateHour.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18332
I have:
| Desktop - Chrome |<img width="320" alt="image" src="https://user-images.githubusercontent.com/114916654/199465667-3edbc006-37e3-4483-95ee-90023b43d60c.png">|<img width="290" alt="image" src="https://user-images.githubusercontent.com/114916654/199465979-5bee34bc-fea9-4689-8a2d-6ed32492749c.png">|
=> (PC-18332) feat(search): better date parsing

__snapshots__/features/search/pages/__tests__/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/features/search/components/FilterSwitchWithLabel.tsx, src/features/search/pages/schema/makeSearchPriceSchema.test.ts, src/features/search/pages/schema/makeSearchPriceSchema.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18328
I have:
| Phone - Chrome   |<img width="378" alt="Capture d’écran 2022-11-02 à 12 08 12" src="https://user-images.githubusercontent.com/78556024/199474922-e0967030-3a25-4842-badc-6e21f2b45425.png">|<img width="374" alt="Capture d’écran 2022-11-02 à 14 57 21" src="https://user-images.githubusercontent.com/78556024/199508781-ded35f33-3ac5-4635-9b29-a82b04cfbf20.png">|
[1]: …
=> (PC-18328) fix(search): min price validator with decimal + ui improvement

src/features/search/pages/DatesHoursModal.tsx, src/features/search/pages/__tests__/DatesHoursModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18336
I have:
=> (PC-18336) fix(search): reset dates link generator

src/features/search/sections/DateHour.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18166
I have:
=> (PC-18166) fix(search): fix icon

src/features/navigation/RootNavigator/linking/getInitialUrl.ios.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18349
I have:
=> (PC-18349) docs(navigation): improve comment timeout

__snapshots__/features/shareApp/components/ShareAppModalNew.native.test.tsx.native-snap, src/features/shareApp/helpers/shareAppModalInformations.test.ts, src/features/shareApp/helpers/shareAppModalInformations.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18244
I have:
| Desktop - Chrome |        |  <img width="1792" alt="Capture d’écran 2022-11-03 à 10 20 21" src="https://user-images.githubusercontent.com/62059034/199685066-f659ed0c-c9d8-4b4d-8f98-2ebbfdf5b577.png"> |
=> (PC-18244) feat(shareApp): update wording for beneficiary modal

src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18366
I have:
=> (PC-18366) feat(search): tracking geoloc incitation button click

src/features/search/pages/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18393
I have:
| iOS              |<img width="483" alt="image" src="https://user-images.githubusercontent.com/114916654/199928565-522404f2-20a5-4ddc-92ba-b78d20163fdf.png">|<img width="487" alt="image" src="https://user-images.githubusercontent.com/114916654/199928625-d322a99e-a94f-4a51-be7e-ac9c67780296.png">|
=> (PC-18393) fix(statusbar): enable dark status bar on search screen

jest.config.js, jest.excludeCollectCoverageFrom.config.js, jest.web.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18317
I have:
| Test | Before | After |
| :----: | :----: | :---: |
| web              |   <img width="958" alt="Capture d’écran 2022-11-02 à 08 58 39" src="https://user-images.githubusercontent.com/62059034/199432296-4ba09137-2925-49d4-9893-57d3fb769980.png"> |  <img width="956" alt="Capture d’écran 2022-11-02 à 09 15 34" src="https://user-images.githubusercontent.com/62059034/199435678-90e86d5d-3682-4f0f-b21e-fddaeaba52fc.png"> |
| native          |  <img width="1097" alt="native-coverage-master" src="https://user-images.githubusercontent.com/62059034/199064195-94c78561-8fb0-4514-a027-813166de71de.png"> | <img width="991" alt="native-coverage-branch" …
=> (PC-18317) feat(jest): update coverage config for web / native

doc/standards/codeStructure.md
=> (BSR) chore(doc): update code structure standard

.eslintrc.js
=> (BSR) feat(eslint): add rule to ban imports from stories

src/ui/svg/icons/BicolorShout.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18243
I have:
| iOS              |  ![Capture d’écran 2022-11-07 à 15 01 59](https://user-images.githubusercontent.com/62059034/200329240-c9103afb-e107-4f53-b5e6-a89cba50266e.png)      |   ![Capture d’écran 2022-11-07 à 15 00 30](https://user-images.githubusercontent.com/62059034/200329308-b1020398-1de1-4e66-827a-0ba492bfe7bd.png) |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066c …
=> (PC-18243) fix(shareApp): update gradient for BicolorShout

__snapshots__/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx.native-snap, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18117
I have:
| iOS              |   ![Capture d’écran 2022-11-07 à 16 25 53](https://user-images.githubusercontent.com/62059034/200348561-5e51d23c-4c42-4242-9866-4c04524633be.png) |  ![Capture d’écran 2022-11-07 à 16 01 25](https://user-images.githubusercontent.com/62059034/200345970-3a1bcfde-c773-4cbc-92de-c92879813230.png) |
| Desktop - Chrome | ![Capture d’écran 2022-11-07 à 16 26 01](https://user-images.githubusercontent.com/62059034/200348668-f9323d0e-9770-43f6-8dfd-ba620cd1e429.png)  |   ![Capture …
=> (PC-18117) feat(offer): update design for SignUpSignInChoiceOfferModal

src/features/search/components/SearchAutocompleteItem.tsx, src/features/search/components/SearchBox.tsx, src/features/search/components/__tests__/SearchAutocompleteItem.native.test.tsx, src/features/search/components/__tests__/SearchBox.native.test.tsx, src/features/search/components/__tests__/useAppliedFilters.test.ts, src/features/search/components/useAppliedFilters.ts, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18371
I have:
=> (PC-18371) feat(search): add applied filters SearchQuery tracker

doc/user_status.mmd
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17880
I have:
=> (PC-17880) docs(userStatus): add state diagram for user status

__snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.web-snap, __snapshots__/features/_marketingAndCommunication/pages/__tests__/UTMParameters.test.tsx.web-snap, __snapshots__/features/home/components/GeolocationBanner.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/confirmation/__test__/IdentityCheckHonor.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.web.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/IdentityCheckStart.web.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap, __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap, __snapshots__/features/profile/pages/LegalNotices/tests/LegalNotices.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, src/features/identityCheck/components/HeroButtonList.tsx, src/ui/components/GeolocationButton/GeolocationButton.tsx, src/ui/components/ModuleBanner/GenericBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18275
**N.-B.:** 2 changements par rapport à l'implèm précédente : 
- la marge à droite de l'icône de gauche -> c'est 16px sur les maquettes (c'était 8px sur l'implèm sur la Home)
- l'icône de droite avait une taille de 20px dans le flux pré-Hubble, alors que c'était 24px sur les maquettes
I have:
| Phone - Chrome   | <img width="294" alt="image" src="https://user-images.githubusercontent.com/26742386/200296864-b11bbfbf-5a1b-4f23-81a5-70e35021f606.png"> | <img width="295" alt="image" src="https://user-images.githubusercontent.com/26742386/200296942-d7f41620-dfa6-4b58-99c0-2f67 …
=> (PC-18275) refactor(banners): extract design in a generic component

src/features/shareApp/helpers/shareApp.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18401
I have:
=> (PC-18401) feat(shareApp): update url for ShareAppModal

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap, src/features/cheatcodes/pages/ThematicHomeHeaderCheatcode/ThematicHomeHeaderCheatcode.tsx, src/features/home/components/headers/ThematicHomeHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17988
**RECETTE UI KO** cf commentaire Eloise sur le ticket Jira
I have:
| iOS              | <img width="384" alt="image" src="https://user-images.githubusercontent.com/89008469/200346084-edd6d755-838b-4dc5-be6e-fc737915f020.png"> | <img width="389" alt="image" src="https://user-images.githubusercontent.com/89008469/200346019-e5a318e6-04ea-4c6f-8270-ca8ad72982b2.png"> |
| Desktop - Chrome | <img width="1490" alt="image" src="https://user-images.githubusercontent.com/89008469/200346178-157203f0-5265-4b67-b84b-03c8d8dbb985.png"> | <img width="1492" alt="image" src="https://user-images.githubusercontent.com/89008469/20034500 …
=> (PC-17988) fix(thematicHeader): fix UI thematic header

src/features/search/components/SearchAutocompleteItem.tsx, src/features/search/components/SearchBox.tsx, src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchBox.native.test.tsx, src/features/search/components/__tests__/useAppliedFilters.test.ts, src/features/search/components/useAppliedFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18452
I have:
=> (PC-18452) feat(search): use applied filters hook search results

__snapshots__/features/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, src/features/auth/components/AuthenticationButton/AuthenticationButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18437
I have:
| Phone - Chrome   |<img width="377" alt="image" src="https://user-images.githubusercontent.com/68000368/200600835-bb399ae9-cc1b-4fc9-9004-16106f1c3cf8.png"> <img width="325" alt="image" src="https://user-images.githubusercontent.com/68000368/200601480-d7a3a68a-d610-4554-a193-42388bad1395.png"> |<img width="376" alt="image" src="https://user-images.githubusercontent.com/68000368/200600724-79757758-3cad-444f-835e-1d2e43b52410.png"> <img width="323" alt="image" src="https://user-images.githubusercontent.com/68000368/200601600-41316ee2-c …
=> (PC-18437) fix(Auth): fix authentication button alignment

src/features/home/components/modules/HomeModule.tsx, src/features/home/components/modules/exclusivity/ExclusivityBanner.tsx, src/features/home/components/modules/exclusivity/ExclusivityExternalLink.native.test.tsx, src/features/home/components/modules/exclusivity/ExclusivityExternalLink.tsx, src/features/home/components/modules/exclusivity/ExclusivityModule.native.test.tsx, src/features/home/components/modules/exclusivity/ExclusivityModule.tsx, src/features/home/components/modules/exclusivity/ExclusivityOffer.tsx, src/features/home/contentful/contentful.ts, src/features/home/contentful/moduleTypes.ts, src/features/home/contentful/processHomepageEntry.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18835
I have:
https://user-images.githubusercontent.com/22886846/200591481-7b41186e-e7fc-4a24-899e-640a594acf68.mov
=> (PC-18835) feat(home): add exclusivity external link component

ios/Podfile.lock
=> (BSR) fix(dep): update Podfile.lock after react native bump

.github/workflows/e2e-ios-native.yml, e2e/config/wdio.ios.app.conf.ts
It is a blind fix to run ios tests on gh actions
cc @kopax-polyconseil
=> Try to fix running ios e2e tests on gh actions

src/features/search/atoms/NoSearchResult.tsx, src/features/search/components/FilterSwitchWithLabel.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18461
I have:
| Desktop - Chrome |  ![Capture d’écran 2022-11-08 à 17 59 32](https://user-images.githubusercontent.com/62059034/200630489-a637e752-452b-43e7-abbb-74bb3dfb951d.png)  ![Capture d’écran 2022-11-08 à 18 12 12](https://user-images.githubusercontent.com/62059034/200630894-d7c3b4fe-8ae0-43ee-98a7-946f5b154b14.png)  |   ![Capture d’écran 2022-11-08 à 17 56 52](https://user-images.githubusercontent.com/62059034/200630436-44e44f20-6eb6-4ada-aefc-374baa2350c4.png …
=> (PC-18461) feat(accessibility): update heading level in search

.github/workflows/e2e-android-app.yml, .github/workflows/e2e-android-browser.yml, .github/workflows/e2e-browser-chrome.yml, .github/workflows/e2e-browser-safari.yml, .github/workflows/e2e-ios-app.yml, .github/workflows/e2e-ios-browser.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18308
I have:
=> (PC-18308) ci(workflows): added safari and rename workflows

src/features/search/components/SearchResults.tsx, src/features/search/components/__tests__/SearchResults.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18403
I have:
| iOS              |![Capture d’écran 2022-11-10 à 14 23 58](https://user-images.githubusercontent.com/78556024/201103576-324e0395-5e81-4eb6-ac1a-ad4eeeadb078.png)|![Capture d’écran 2022-11-10 à 14 21 21](https://user-images.githubusercontent.com/78556024/201103608-05fa8036-27e7-4fbb-a300-1d45715a3437.png)|
| Desktop - Chrome |<img width="1727" alt="Capture d’écran 2022-11-10 à 14 20 20" src="https://user-images.githubusercontent.com/78556024/201103662-bf1a5d81-f4cb-414f-9e31-ebecf301f451.pn …
=> (PC-18403) feat(search): remove geolocation incitation no results search

__snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap, __snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/__tests__/SearchPrice.native.test.tsx.native-snap, src/ui/components/FilterSwitch.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18482
I have:
=> (PC-18482) feat(accessibility): update hidden wording for FilterSwitch

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/components/__tests__/SearchResults.web.test.tsx.web-snap, src/features/search/atoms/Buttons/FilterButton/SingleFilterButton.tsx, src/features/search/atoms/NumberOfResults.tsx, src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18458
I have:
| Desktop - Chrome |  ![Capture d’écran 2022-11-10 à 16 43 37](https://user-images.githubusercontent.com/62059034/201140381-03aabebd-0dcf-48f7-81b1-bd1fcffe9a6c.png)  |  ![Capture d’écran 2022-11-10 à 16 44 12](https://user-images.githubusercontent.com/62059034/201140331-82c896c2-442f-4214-8e29-5781bf2574a7.png)  |
| Desktop - Firefox |  ![Capture d’écran 2022-11-10 à 16 40 …
=> (PC-18458) feat(accessibility): fix focus on SingleFilterButton

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap, src/features/home/components/headers/ThematicHomeHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17988
I have:
| iOS              | <img width="386" alt="image" src="https://user-images.githubusercontent.com/89008469/201079466-49dbd4f8-3317-493d-8b2d-a64ed035bf73.png"> | <img width="389" alt="image" src="https://user-images.githubusercontent.com/89008469/201079276-b7a87d05-14a6-470a-b47e-ace3016d9400.png"> |
| Desktop - Chrome | <img width="1920" alt="image" src="https://user-images.githubusercontent.com/89008469/201080206-e39b1ff8-8fe3-4337-b847-6e36bc14398a.png"> | <img width="1512" alt="image" …
=> (PC-17988) fix(thematicHeader): UI thematic header 2

__snapshots__/features/identityCheck/pages/identification/identificationStart/IdentityCheckStart.web.test.tsx.web-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap, __snapshots__/features/profile/pages/DeleteProfile/__tests__/ConfirmDeleteProfile.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18648
I have:
=> (PC-18648) fix(search): repare location incitation

__snapshots__/features/search/components/__tests__/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/components/__tests__/SearchResults.web.test.tsx.web-snap, src/features/search/atoms/Buttons/FilterButton/SingleFilterButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18642
Je pense que le bug venait du fait d'ajouter une marge + un comportement felx sur un composant Typo. 
Il vaut mieux utiliser un Spacer ou mettre la Typo dans une view pour garantir le flex. 
I have:
=> (PC-18642) feat(search): fix bug on filter button

.eslintrc.js, src/libs/resizing-image-on-demand/FastImage.tsx, src/libs/resizing-image-on-demand/ImageBackground.tsx, src/ui/components/hero/Hero.tsx, src/ui/components/tiles/OfferImage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18635
I have:
=> (PC-18635) chore(eslint): add rule image

__snapshots__/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx.native-snap, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18216
I have:
| iOS              | <img width="395" alt="image" src="https://user-images.githubusercontent.com/89008469/202432790-645e973f-587a-4195-b5c6-1bcf9a362e3e.png"> | <img width="383" alt="image" src="https://user-images.githubusercontent.com/89008469/202432663-6f2f65e8-2b98-48aa-bc29-dc6211e8a918.png"> |
| Android          | <img width="441" alt="image" src="https://user-images.githubusercontent.com/89008469/202434033-0c1c1142-d6fc-4b0b-9d3f-367aa3cd2aa6.png"> | <img width="441" alt="image" src="https://user-images.githubusercontent.com/89008469/202434092-f71804f1-a458-4fa8-b41b-7fa2d9617f09.png"> |
| Phone - …
=> (PC-18216) feat(ExpiredOrLostId): update wording

src/features/_marketingAndCommunication/atoms/LocationFilterChoice.tsx, src/features/_marketingAndCommunication/atoms/__tests__/LocationFilterChoice.test.tsx, src/features/search/pages/SearchWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18347
I have:
Avant:
Après:
=> (PC-18347) feat(search): remove force around me location

src/features/onboarding/components/AuthenticationHeader.native.test.tsx, src/features/onboarding/components/AuthenticationHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18583
I have:
=> (PC-18583) feat(onboarding): Redirect to home without navigation reset

__snapshots__/features/home/components/modules/BusinessModule.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, src/libs/resizing-image-on-demand/FastImage.tsx, src/libs/resizing-image-on-demand/Image.tsx, src/libs/resizing-image-on-demand/ImageBackground.tsx, src/libs/resizing-image-on-demand/useResizeImageURL.native.test.tsx, src/libs/resizing-image-on-demand/useResizeImageURL.ts, src/ui/components/ImageTile.tsx, src/ui/components/hero/HeroHeader.tsx, src/ui/components/tiles/OfferImage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18636
I have:
=> (PC-18636) feat(resizeImage): use custom size

.gitignore
=> (BSR) ci(gitignore): ignore zip files

doc/development/e2e.md
=> (BSR) docs(e2e): fix iOS build command

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap, src/features/home/pages/Home.native.test.tsx, src/features/home/pages/Home.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18444
I have:
https://user-images.githubusercontent.com/22886846/203124204-ba4c1c0d-6019-46f0-bf8a-d8838ad77f96.mov
https://user-images.githubusercontent.com/22886846/203124237-746da631-6ef4-4691-bb9c-f7676f504baa.mov
https://user-images.githubusercontent.com/22886846/203124227-2842e0bd-e33c-4aaa-8969-5a43127a1eb9.mov
=> (PC-18444) fix(home): fix thematic home display

__snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Accessibility/AccessibilityActionPlan.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Accessibility/AccessibilityEngagement.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, src/features/navigation/RootNavigator/accessibilityRoutes.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/profile/pages/Accessibility/Accessibility.native.test.tsx, src/features/profile/pages/Accessibility/Accessibility.tsx, src/features/profile/pages/Accessibility/Accessibility.web.test.tsx, src/features/profile/pages/Accessibility/AccessibilityActionPlan.native.test.tsx, src/features/profile/pages/Accessibility/AccessibilityActionPlan.tsx, src/features/profile/pages/Accessibility/AccessibilityActionPlan.web.test.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.tsx, src/features/profile/pages/Accessibility/AccessibilityEngagement.native.test.tsx, src/features/profile/pages/Accessibility/AccessibilityEngagement.tsx, src/features/profile/pages/Accessibility/AccessibilityEngagement.web.test.tsx, src/features/profile/pages/Accessibility/RecommendedPaths.tsx, src/features/profile/pages/Accessibility/components/ActionPlanTag.stories.tsx, src/features/profile/pages/Accessibility/components/ActionPlanTag.tsx, src/features/profile/pages/Accessibility/components/ContactSupportButton.native.test.tsx, src/features/profile/pages/Accessibility/components/ContactSupportButton.tsx, src/features/profile/pages/Profile.native.test.tsx, src/features/profile/pages/Profile.tsx, src/ui/components/BulletListItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18609
I have:
| iOS              |        |  https://user-images.githubusercontent.com/46637324/203368064-85b5fd9a-1798-4628-8bf0-bb9e38a98bed.mp4  |
| Desktop - Chrome |        |   https://user-images.githubusercontent.com/46637324/203368092-48f3231b-e030-41af-976d-91e2d75e1fb0.mov    |
=> (PC-18609) feat(profile): Add Accessibility section (part 1)

__snapshots__/features/onboarding/pages/OnboardingAuthentication.native.test.tsx.native-snap, src/features/onboarding/components/AuthenticationHeader.native.test.tsx, src/features/onboarding/components/AuthenticationHeader.tsx, src/features/onboarding/pages/OnboardingAuthentication.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18489
I have:
=> (PC-18489) fix(onboarding): Remove goBack button

__snapshots__/features/onboarding/pages/OnboardingAuthentication.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclaration.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Accessibility/RecommendedPaths.native.test.tsx.native-snap, src/features/onboarding/pages/OnboardingAuthentication.native.test.tsx, src/features/onboarding/pages/OnboardingAuthentication.tsx, src/features/profile/pages/Accessibility/Accessibility.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.native.test.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.web.test.tsx, src/features/profile/pages/Accessibility/RecommendedPaths.native.test.tsx, src/features/profile/pages/Accessibility/RecommendedPaths.tsx, src/features/profile/pages/Accessibility/RecommendedPaths.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18787
I have:
| iOS              |        |     https://user-images.githubusercontent.com/46637324/203526650-0cbe94c8-a84e-4665-89c8-946dcfb80a9b.mp4   |
=> (PC-18787) feat(profile): Add new Accessibility pages

src/api/gen/api.ts, src/features/offer/enums.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.test.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts, src/features/offer/helpers/useOfferModal/useOfferModal.native.test.tsx, src/features/offer/helpers/useOfferModal/useOfferModal.tsx, src/features/offer/pages/Offer/Offer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17894
I have:
=> (PC-17894) feat(offer): link modals to user status in offer

__snapshots__/features/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/ErrorApplicationModal/ErrorApplicationModal.native.test.tsx.native-snap, src/features/cheatcodes/pages/NavigationSignUp/NavigationSignUp.tsx, src/features/offer/components/AddToFavoritesButton/__mocks__/AddToFavoritesButton.tsx, src/features/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx, src/features/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.tsx, src/features/offer/components/ErrorApplicationModal/ErrorApplicationModal.native.test.tsx, src/features/offer/components/ErrorApplicationModal/ErrorApplicationModal.tsx, src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx, src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18743
I have:
=> (PC-18743) feat(offer): add analytics for FinishSubscriptionModal

__snapshots__/features/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/ErrorApplicationModal/ErrorApplicationModal.native.test.tsx.native-snap, src/features/offer/helpers/useOfferModal/useOfferModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18743
I have:
=> (PC-18743) feat(offer): fix snapshots and types

__snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap, src/features/onboarding/components/CreditStatusTag.stories.tsx, src/features/onboarding/components/CreditStatusTag.tsx, src/features/onboarding/helpers/getTagColor.test.ts, src/features/onboarding/helpers/getTagColor.ts, src/features/profile/pages/Accessibility/Accessibility.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18726
I have:
**Voir storybook**
=> (PC-18726) feat(onboarding): Add credit status tag component

.vscode/a11y-test.code-snippets, doc/standards/testStrategy.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18515
I have:
Lien vers le standard a jour https://github.com/pass-culture/pass-culture-app-native/blob/PC-18515-update-doc/doc/standards/testStrategy.md
=> (PC-18515) feat(accessibility): update doc for accessibility tests

src/features/offer/api/useAlgoliaSimilarOffers.test.ts, src/features/offer/api/useAlgoliaSimilarOffers.ts, src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/api/useSimilarOffers.ts, src/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/pages/Offer/Offer.tsx, src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18517
I have:
| Desktop - Chrome |        |<img width="1060" alt="image" src="https://user-images.githubusercontent.com/114916654/203824538-169ff9d2-c1cc-48d7-87f1-4d8cb2e49ea2.png">|
=> (PC-18517) feat(offer): Add similar offers

CODEOWNERS
Co-authored-by: Ali RAIKI <ali.raiki@polyconseil.fr>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17928
I have:
=> (PC-17928) chore(codeowner): remove comment and remove @pass-culture/jeunes

src/features/offer/api/useSimilarOffers.ts, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18406
I have:
=> (PC-18406) feat(offer): Add position to similar offers

__snapshots__/features/home/components/GeolocationBanner.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectPhoneStatus.web.test.tsx.web-snap, src/features/onboarding/components/AgeButton.stories.tsx, src/features/onboarding/components/AgeButton.tsx, src/ui/components/ModuleBanner/GenericBanner.stories.tsx, src/ui/components/ModuleBanner/GenericBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18722
I have:
**Voir storybook**
=> (PC-18722) feat(onboarding): Make GenericBanner reusable for age selection component

src/features/profile/pages/Accessibility/AccessibilityDeclaration.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18787
I have:
=> (PC-18787) chore(sonar): Remove TODO

src/ui/theme/grid.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18836
I have:
| Desktop - Chrome |   ![Capture d’écran 2022-11-25 à 15 08 25](https://user-images.githubusercontent.com/62059034/204002669-8e300c66-5aa7-4847-a67a-442b993ab104.png)   |  ![Capture d’écran 2022-11-25 à 15 08 42](https://user-images.githubusercontent.com/62059034/204002706-f65a79dc-36b6-437c-ad6c-f483866a73dd.png) |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf61 …
=> (PC-18836) feat(cookies): update breakpoint xs value

src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/ui/components/inputs/SearchInput.tsx
I have:
| iOS              |        | <img width="511" alt="image" src="https://user-images.githubusercontent.com/26742386/203818674-09b9e622-aae1-46a3-8514-37f497358cd0.png"> |
| Chrome - A11y    | <img width="294" alt="image" src="https://user-images.githubusercontent.com/26742386/203819190-d12ecf7c-7f2b-43b2-94c1-263c526a0009.png"> | <img width="295" alt="image" src="https://user-images.githubusercontent.com/26742386/203819107-b7515eb8-6186-46a3-9c16-d19baa50404a.png"> |
| Phone - Chrome   | <img width="293" alt="image" src="https://user-images.githubusercontent.com/26742386/203818943-6802bf77-81f6-45b8-9f78-b39f27228432.png"> | <img width="294" alt="image" …
=> (BSR) fix(search): use label for location filter input

src/features/home/api/helpers/computeBeginningAndEndingDateTime.test.ts, src/features/home/api/helpers/computeBeginningAndEndingDateTime.ts, src/features/home/api/useHomeRecommendedHits.test.ts, src/features/home/api/useHomeRecommendedHits.ts, src/features/home/contentful/contentful.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18592
I have:
=> (PC-18592) feat(Contentful): add contentful week event

__snapshots__/features/search/components/SearchBox/SearchBox.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchHeader/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, __snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap, src/features/offer/api/useSimilarOffers.native.test.ts, src/features/search/components/SearchBox/SearchBox.tsx, src/features/search/components/SearchMainInput/SearchMainInput.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.web.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.web.test.tsx, src/features/search/pages/SuggestedPlaces/SuggestedPlaces.native.test.tsx, src/features/search/pages/SuggestedPlaces/SuggestedPlaces.web.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.web.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.web.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.web.test.tsx, src/features/search/pages/modals/OfferTypeModal/OfferTypeModal.native.test.tsx, src/features/search/pages/modals/OfferTypeModal/OfferTypeModal.web.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18831
I have:
=> (PC-18831) test(search): accessibility

src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18870
I have:
=> (PC-18870) fix(offer): better navigation

src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18811
I have:
=> (PC-18811) feat(search): add ff subcategories filter

src/features/onboarding/components/CreditBlock.stories.tsx, src/features/onboarding/components/CreditBlock.tsx, src/features/onboarding/components/CreditStatusTag.stories.tsx, src/features/onboarding/components/CreditStatusTag.tsx, src/features/onboarding/helpers/getBackgroundColor.test.ts, src/features/onboarding/helpers/getBackgroundColor.ts, src/features/onboarding/helpers/getBorderStyle.test.ts, src/features/onboarding/helpers/getBorderStyle.ts, src/features/onboarding/helpers/getTagColor.test.ts, src/features/onboarding/helpers/getTagColor.ts, src/features/onboarding/helpers/getTextComponent.ts, src/features/onboarding/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18726
I have:
=> (PC-18725) feat(onboarding): Add credit block component

__snapshots__/features/_marketingAndCommunication/pages/__tests__/DeeplinksGenerator.test.tsx.native-snap, __snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap, __snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/venue/pages/VenueBody.tsx, src/ui/components/AccordionItem.tsx, src/ui/components/SectionWithDivider.tsx, src/ui/hooks/useScrollWhenAccordionOpens.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18762
I have:
=> (PC-18762) fix(accordion): fix scroll on open

src/features/navigation/screenParamsUtils.ts, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.tsx, src/features/search/types.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildNumericFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18922
I have:
=> (PC-18922) fix(search): use max possible price without max price entered

src/features/home/api/useHomeRecommendedHits.test.ts, src/features/home/api/useHomeRecommendedHits.ts, src/features/home/api/useHomeRecommendedIdsMutation.ts, src/features/home/contentful/contentful.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18588
I have:
Dans les recommendation_parameters sur contentful : 
Résultats dans la console de chrome :
Dans les recommendation_parameters sur contentful : 
Résultat dans la console de chrome :
=> (PC-18588) feat(contentful): add isRecoShuffled parameter

src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildOfferSearchParameters.ts.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18922
I have:
=> (PC-18922) fix(search): add missing param build search

src/ui/components/Form.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18889
I have:
| Desktop - Chrome |![Capture d’écran 2022-12-01 à 09 50 29](https://user-images.githubusercontent.com/78556024/205008104-121b6633-4cea-46d4-b406-9abd798d0ed3.png) ![Capture d’écran 2022-12-01 à 09 50 01](https://user-images.githubusercontent.com/78556024/205008141-8ef42076-c789-4191-ab9c-b2a4f5a9b96b.png)|![Capture d’écran 2022-12-01 à 09 53 18](https://user-images.githubusercontent.com/78556024/205008783-99f514ee-45a5-4a5f-b71d-707a96fb0b94.png) …
=> (PC-18889) fix(search): web display

src/features/venue/pages/Venue/Venue.web.test.tsx, src/features/venue/pages/VenueNotFound/VenueNotFound.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18969
I have:
=> (PC-18969) test(venue): accessibility

src/App.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17103
I have:
- [] Written **unit tests** native (and web when implementation is different) for my feature.
| iOS              |        |   https://user-images.githubusercontent.com/46637324/205247721-414cc30e-8ddc-4c38-81ab-8ef2eacb4d1b.mp4    |
=> (PC-17103) fix(user): Move NetInfo context above AuthContext

__snapshots__/features/onboarding/pages/AgeSelection.native.test.tsx.native-snap, __snapshots__/features/onboarding/pages/OnboardingPage.native.test.tsx.native-snap, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/cheatcodes/pages/NavigationOnboarding/NavigationOnboarding.tsx, src/features/navigation/RootNavigator/onboardingRoutes.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/onboarding/components/CreditBlock.stories.tsx, src/features/onboarding/components/CreditBlock.tsx, src/features/onboarding/pages/AgeSelection.native.test.tsx, src/features/onboarding/pages/AgeSelection.tsx, src/features/onboarding/pages/AgeSelection.web.test.tsx, src/features/onboarding/pages/OnboardingPage.native.test.tsx, src/features/onboarding/pages/OnboardingPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18859
I have:
| iOS              |        |    ![Simulator Screen Shot - iPhone 13 - 2022-12-02 at 11 02 03](https://user-images.githubusercontent.com/46637324/205267401-165144bf-4523-4945-a01b-b058470ada86.png)   |
| Android          |        |     ![Screenshot_20221202_111649](https://user-images.githubusercontent.com/46637324/205270160-fa614e96-df60-468a-a076-43d28d811ad8.png)  |
| Desktop - Chrome |        |  <img width="1440" alt="Capture d’écran 2022-12-02 à 11 02 33" src="https://user-images.githubusercontent.com/46637324/205267499-65db4d0 …
=> (PC-18859) feat(onboarding): Make template for onboarding pages (PC-18723)

.github/workflows/e2e-browser-chrome.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18680
- This is a test with 1 e2e cron that runs every 15 min
I have:
=> (PC-18680) ci(e2e): test with cron

.github/workflows/e2e-android-app.yml, .github/workflows/e2e-android-browser.yml, .github/workflows/e2e-browser-chrome.yml, .github/workflows/e2e-browser-firefox.yml, .github/workflows/e2e-browser-safari.yml, .github/workflows/e2e-ios-app.yml, .github/workflows/e2e-ios-browser.yml, .github/workflows/reusable-e2e-buildsimuioszip.yml, doc/development/e2e.md, e2e/config/environment/env.ts, e2e/config/environment/types.ts, e2e/config/wdio.shared.conf.ts, e2e/tests/pc/features/cookies/CookiesConsent.ts, e2e/tests/pc/helpers/FirstLaunch.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18990
I have:
=> (PC-18990) ci(e2e): split iOS e2e with reusable

.github/workflows/e2e-browser-chrome.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18680
I have:
=> (PC-18680) ci(e2e): add defaults input for scheduled

__snapshots__/features/onboarding/pages/AgeInformation.native.test.tsx.native-snap, __snapshots__/features/onboarding/pages/OnboardingPage.native.test.tsx.native-snap, src/features/cheatcodes/pages/NavigationOnboarding/NavigationOnboarding.tsx, src/features/navigation/RootNavigator/onboardingRoutes.ts, src/features/navigation/RootNavigator/types.ts, src/features/onboarding/components/AgeSeparator.stories.tsx, src/features/onboarding/components/AgeSeparator.tsx, src/features/onboarding/components/CreditBlock.tsx, src/features/onboarding/helpers/getCreditStatusFromAge.test.ts, src/features/onboarding/helpers/getCreditStatusFromAge.ts, src/features/onboarding/pages/AgeInformation.native.test.tsx, src/features/onboarding/pages/AgeInformation.tsx, src/features/onboarding/pages/AgeInformation.web.test.tsx, src/features/onboarding/pages/AgeInformation.web.tsx, src/features/onboarding/pages/AgeSelection.web.test.tsx, src/features/onboarding/pages/AgeSelection.web.tsx, src/features/onboarding/pages/OnboardingPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18764
I have:
| | 15 ans | 16 ans | 17 ans | 18 ans |
| :--------------- | :----: | :---: | :----: | :---: |
| iOS     |     ![Simulator Screen Shot - iPhone 13 - 2022-12-05 at 09 02 44](https://user-images.githubusercontent.com/46637324/205585050-3a317cef-d17b-4af2-85b5-bb6382604417.png)   |  ![Simulator Screen Shot - iPhone 13 - 2022-12-05 at 09 02 49](https://user-images.githubusercontent.com/46637324/205585031-3e724392-e88b-4d5e-b22c-0fc2854986a8.png)     |    ![Simulator Screen Shot - iPhone 13 - 2022-12-05 at 09 02 52](https://user-images.githubusercontent.com/46637324/205585087-703a2c10-005b-47a7-a724-0fb2128430cd.png)   |   ![Simulator Screen Shot - iPhone 13 - 2022-12-05 at 09 02 …
=> (PC-18764) feat(onboarding): Add AgeInformation page for eligible users

.github/workflows/e2e-android-app.yml, .github/workflows/e2e-android-browser.yml, .github/workflows/e2e-browser-chrome.yml, .github/workflows/e2e-browser-firefox.yml, .github/workflows/e2e-browser-safari.yml, .github/workflows/e2e-ios-app.yml, .github/workflows/e2e-ios-browser.yml, .github/workflows/reusable-e2e-buildsimuioszip.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18680
=> (PC-18680) ci(e2e): scheduled nightly e2e cron

.github/workflows/e2e-android-app.yml, .github/workflows/e2e-android-browser.yml, .github/workflows/e2e-browser-chrome.yml, .github/workflows/e2e-browser-firefox.yml, .github/workflows/e2e-browser-safari.yml, .github/workflows/e2e-ios-app.yml, .github/workflows/e2e-ios-browser.yml, e2e/config/wdio.browser.chrome.conf.ts, e2e/config/wdio.browser.firefox.conf.ts, e2e/config/wdio.browser.safari.conf.ts, e2e/config/wdio.shared.conf.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18993
=> (PC-18993) ci(e2e): add slack service

.github/workflows/e2e-ios-app.yml, e2e/config/wdio.shared.conf.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18993
=> (PC-18993) ci(e2e): e2e reporting on slack even on success

__snapshots__/features/cookies/components/CookiesSettings.native.test.tsx.native-snap, __snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx.native-snap, src/features/cookies/components/CookiesSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18885
I have:
| iOS              |        |<img width="311" alt="image" src="https://user-images.githubusercontent.com/68000368/205910188-2d9153fb-7d55-4bb6-9108-c5bb39e61dfb.png">|
| Android          |        |<img width="479" alt="image" src="https://user-images.githubusercontent.com/68000368/205910127-3515d321-fbe8-4112-bdba-ef1b4ff68805.png">|
=> (PC-18885) fix(Cookies): Fix text wrap for small screens

ios/Podfile.lock
=> (BSR) chore(deps): Update dependency react-native-geolocation-service  to v5.3.1

__snapshots__/features/onboarding/pages/AgeInformation.native.test.tsx.native-snap, __snapshots__/features/onboarding/pages/AgeSelectionOther.native.test.tsx.native-snap, src/features/onboarding/components/CreditBlock.tsx, src/features/onboarding/components/CreditStatusTag.tsx, src/features/onboarding/helpers/getBorderStyle.test.ts, src/features/onboarding/helpers/getBorderStyle.ts, src/features/onboarding/pages/AgeSelectionOther.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18765
I have:
| iOS    |  ![Simulator Screen Shot - iPhone 13 - 2022-12-06 at 15 05 07](https://user-images.githubusercontent.com/46637324/205933206-a19b9ed9-751e-4491-8cbe-f285c6d92694.png) <img width="12" alt="Capture d’écran 2022-12-06 à 14 33 42" src="https://user-images.githubusercontent.com/46637324/205933060-5eed2822-6932-4e59-b89a-4a2c465672ef.png">     | ![Simulator Screen Shot - iPhone 13 - 2022-12-06 at 15 03 10](https://user-images.githubusercontent.com/46637324/205933135-47258cd8-645e-44cf-b038-9afab1605306.png) <img width="14" alt="Capture d’écran 2022-12-06 à 15 01 27" …
=> (PC-18765) fix(onboarding): Fix design

e2e/config/wdio.shared.conf.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19130
=> (PC-19130) ci(e2e): enable e2e reporting on success

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap, src/features/home/components/headers/ThematicHomeHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18710
I have:
| Pas de dépassement | Pas de titre | Sous titre sur 2 lignes |titre sur 2 lignes et sous-titre coupé |sous titre qui dépasse |
| :----- | :----: | :---: | :---: | :---: |
|![normal](https://user-images.githubusercontent.com/22886846/205939839-6baae1d1-12c4-4373-8d4b-14bfe0681071.png)|![pasdetitre](https://user-images.githubusercontent.com/22886846/205939860-698c73d2-524d-4951-be68-dd11f7c5430f.png)|![sous-titre-2-lignes](https://user-images.githubusercontent.com/22886846/205939872-d6c04090-72dd-40c3-83a5-5226c561abe3.png)|![titre-2-lignes-sous-titre-croppé](https://user-images.githubusercontent.com/22886846/205939880-863e25f2-6b20-477e-b6a4-121c8e0d2068.png)|![sous-titre-qui-dépasse](https://user-images.githu …
=> (PC-18710) feat(ThematicHeader): make sure title and subtitle do not exceed 3 lines

__snapshots__/features/search/components/SearchResults/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/api/useSearchResults/useSearchResults.ts, src/features/search/components/NoSearchResults/NoSearchResult.tsx, src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/features/search/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19078
I have:
| iOS              |<img width="450" alt="Capture d’écran 2022-12-06 à 17 38 43" src="https://user-images.githubusercontent.com/78556024/205970744-4d830f80-808d-4503-9e23-b52eee03eb06.png"> ![Capture d’écran 2022-12-06 à 17 38 15](https://user-images.githubusercontent.com/78556024/205970833-75778faf-9c48-4e56-b203-b83e16a26a29.png) ![Capture d’écran 2022-12-06 à 17 37 30](https://user-images.githubusercontent.com/78556024/205970924-ec87323d-f3b1-4283-9305-dfb4194f4336.png) <img width="440" alt="Capture d’écran 2022-12-06 à 17 37 08" src="https://user-images.githubusercontent.com/78556024/205971026-188 …
=> (PC-19078) feat(search): add unavailable offer message

doc/standards/testStrategy.md, src/features/search/pages/Search/Search.web.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19037
I have:
=> (PC-19037) test(search): fix duplicate-id-aria

__snapshots__/features/onboarding/pages/AgeSelection.native.test.tsx.native-snap, __snapshots__/features/onboarding/pages/AgeSelectionOther.native.test.tsx.native-snap, e2e/tests/pc/features/onboarding/AgeInformation.ts, e2e/tests/pc/features/onboarding/AgeSelection.ts, e2e/tests/pc/helpers/FirstLaunch.ts, src/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx, src/features/firstTutorial/pages/FirstTutorial/FirstTutorial.tsx, src/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx, src/features/firstTutorial/pages/FirstTutorial/components/FourthCard.tsx, src/features/onboarding/components/AgeButton.tsx, src/features/onboarding/pages/AgeSelection.tsx, src/features/onboarding/pages/AgeSelectionOther.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18862
I have:
=> (PC-18862) feat(onboarding): Redirect to AgeSelection after FirstTutorial

e2e/tests/pc/features/onboarding/AgeSelection.ts, e2e/tests/pc/helpers/FirstLaunch.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18862
=> (PC-18862) ci(e2e): Add RandomChoice for AgeSelection

src/ui/components/touchableLink/InternalTouchableLink.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17958
I have:
=> (PC-17958) fix(app): Fix link error

src/features/home/contentful/contentful.ts, src/libs/search/parseSearchParameters.test.ts, src/libs/search/parseSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18756
I have:
| Terminal              |        | https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fpass-culture%2Fpass-culture-app-native%2Fpull%2Fnew%2FPC-18756%2Falgolia-semaine-en-cours |
La capture d'écran est prise à le 09/12/22 à 16h36 et on voit bien que les beginningDatetime et endingDatetime vont de l'heure de na requete au dimanche à venir, le 11/12/22 à 23h59
=> (PC-18756) feat(contentful): add currentWeekEvent algolia parameters fields

.github/workflows/e2e-android-app.yml, .github/workflows/e2e-android-browser.yml, .github/workflows/e2e-browser-chrome.yml, .github/workflows/e2e-browser-firefox.yml, .github/workflows/e2e-browser-safari.yml, .github/workflows/e2e-ios-app.yml, .github/workflows/e2e-ios-browser.yml, e2e/config/wdio.shared.conf.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19175
=> (PC-19175) ci(e2e): add useful URL to slack report title

__snapshots__/features/onboarding/pages/AgeInformation.native.test.tsx.native-snap, src/features/onboarding/components/CreditBlock.tsx, src/features/onboarding/pages/AgeInformation.native.test.tsx, src/features/onboarding/pages/AgeInformation.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19153
I have:
=> (PC-19153) feat(onboarding): Add tracker for credit block press attempt

src/libs/react-native-web-fast-image/index.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17667
Co auteurs @bruno-ebstein-pass-culture @lixxday 
I have:
=> (PC-17667) fix(FastImage): Improved image performance with lazy loading

src/features/auth/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/signup/SetEmail/SetEmail.tsx, src/features/auth/signup/SetEmail/schema/emailSchema.test.ts, src/features/auth/signup/SetEmail/schema/emailSchema.ts, src/features/auth/signup/SetEmail/schema/setEmailSchema.test.ts, src/features/auth/signup/SetEmail/schema/setEmailSchema.ts, src/ui/components/inputs/Checkbox/Checkbox.tsx, src/ui/components/inputs/Checkbox/Checkbox.web.test.tsx, todo.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17385
I have:
=> (PC-17385) refactor(auth): set email react hook form

src/features/home/components/headers/HomeHeader.native.test.tsx, src/features/home/components/headers/HomeHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18688
I have:
| iOS              | https://user-images.githubusercontent.com/89008469/207602623-5df95101-039f-4eae-a862-3b25c5719846.MP4 | https://user-images.githubusercontent.com/89008469/207602769-334248ce-dfe8-4527-92ee-122cfdd57449.mp4 |
| iOS  error case |   | https://user-images.githubusercontent.com/89008469/207618150-4cd3899d-6062-4cb3-bb0b-b7979ab576ca.mp4 |
=> (PC-18688) feat(HomeHeader): fix bloc display conditions

src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19280
I have:
=> (PC-19280) feat(search): simplify unavailable offer message

src/ui/components/__tests__/GenericInfoPage.test.tsx, src/ui/pages/GenericInfoPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19279
I have:
=> (PC-19279) fix(StatusBar): Fix crash

__snapshots__/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx.native-snap, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18798
I have:
| iOS              | <img width="387" alt="image" src="https://user-images.githubusercontent.com/89008469/208083045-61bdb06d-e222-4f44-89db-ccb7c33b08bf.png"> | <img width="390" alt="image" src="https://user-images.githubusercontent.com/89008469/208082946-7d4b863c-71f5-48fd-8844-2ed7d9d6ffba.png"> |
=> (PC-18798) feat(ExpiredOrLostId): update redirection from ants to dms

__snapshots__/features/search/components/SearchBox/SearchBox.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchHeader/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/search/components/SearchBox/SearchBox.tsx
Co-authored-by: YassinL <YassinL@users.noreply.github.com>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18483
I have:
=> (PC-18483) feat(search): improve accessibility

package.json, src/features/firstLogin/CulturalSurvey.web.test.tsx, src/features/firstLogin/CulturalSurvey.web.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19053
=> (PC-19053) test(culturalSurvey): add a11y test

.eslintrc.js, e2e/tests/pc/helpers/FirstLaunch.ts, src/App.tsx, src/App.web.tsx, src/libs/e2e/E2eContextProvider.tsx, src/libs/e2e/constants.android.ts, src/libs/e2e/constants.ts, src/libs/e2e/getIsE2e.ts, src/libs/e2e/getIsE2e.web.ts, src/libs/e2e/tests/E2eContextProvider.native.test.tsx, src/libs/e2e/tests/getIsE2e.native.test.ts, src/libs/e2e/tests/getIsE2e.web.test.ts, src/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19305
I have:
=> (PC-19305) feat(e2e): add useIsE2e hook

src/libs/contentful/types.ts, src/libs/search/parseSearchParameters.test.ts, src/libs/search/parseSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18757
I have:
=> (PC-18757) feat(filters): ajout d'un filtre algolia les x prochains jours

src/ui/components/hero/Hero.stories.tsx, src/ui/components/tiles/OfferImage.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17667
I have:
=> (PC-17667) feat(accessibility): add default alt to FastImage

__snapshots__/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx.native-snap, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18798
I have:
| iOS              | <img width="391" alt="image" src="https://user-images.githubusercontent.com/89008469/208451711-d36f69ff-b771-401d-b404-fea21e12e705.png"> | <img width="384" alt="image" src="https://user-images.githubusercontent.com/89008469/208451161-ea5e3f6e-1c1a-4531-bc6c-1847cabd5ae1.png"> |
=> (PC-18798) feat(ExpiredOrLostId): Replace ExpiredOrLostId primary CTA

doc/user_status.mmd
Clarification des transitions entre les sous états des utilisateurs éligibles
Avant
Après
=> (BSR) docs(status): fix misunderstanding

src/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx, src/features/auth/signup/SetBirthday/SetBirthday.tsx, src/features/onboarding/pages/AgeSelection.native.test.tsx, src/features/onboarding/pages/AgeSelection.tsx, src/features/onboarding/pages/AgeSelectionOther.native.test.tsx, src/features/onboarding/pages/AgeSelectionOther.tsx, src/features/onboarding/types.ts, src/libs/storage.ts, src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19082
I have:
=> (PC-19082) feat(onboarding): Save user age in storage and use it in SetBirthday

src/features/auth/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/signup/SetEmail/SetEmail.tsx, src/features/auth/signup/SetEmail/schema/emailSchema.test.ts, src/features/auth/signup/SetEmail/schema/emailSchema.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17385
I have:
=> (PC-17385) feat(auth): display help message on submit

src/features/navigation/RootNavigator/types.ts, src/features/offer/components/OfferTile/OfferTile.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19292
I have:
=> (PC-19292) feat(offer): add info tracker

.github/workflows/chromatic.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18669
I have:
=> (PC-18669) feat(storybook): add storybook accessibility tests after chromatic build

.circleci/config.yml, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19425
Version de test sur appcenter ios android testing : Version 1.219.91 (10219091)
I have:
=> (PC-19425) fix(dependencies): upgrade react-native-svg

src/features/onboarding/components/AgeButton.tsx, src/features/onboarding/pages/AgeInformation.native.test.tsx, src/features/onboarding/pages/AgeInformation.tsx, src/features/onboarding/pages/AgeSelectionOther.native.test.tsx, src/features/onboarding/pages/AgeSelectionOther.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19395
I have:
=> (PC-19395) fix(onboarding): Fix native goBack behavior after onboarding

__snapshots__/features/search/components/CategoryButton/CategoryButton.native.test.tsx.native-snap, __snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/search/components/CategoryButton/CategoryButton.native.test.tsx, src/features/search/components/CategoryButton/CategoryButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19358
I have:
| Desktop - Chrome |  ![Capture d’écran 2022-12-26 à 18 07 18](https://user-images.githubusercontent.com/62059034/209570282-b19e3f09-06a1-46ef-8441-39fe9431ab8d.png)  |   ![Capture d’écran 2022-12-26 à 18 06 25](https://user-images.githubusercontent.com/62059034/209570241-0d3627c0-367c-45ce-a348-454aa3267107.png) |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613 …
=> (PC-19358) feat(search): update accessibilité label for CategoryButton

.eslintrc.js, __snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap, src/features/bookings/components/Ticket/TicketSwiper.native.test.tsx, src/features/cheatcodes/components/CodePushButton/CodePushButton.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx, src/features/offer/components/ReportOfferOtherReason/ReportOfferOtherReason.native.test.tsx, src/features/offer/components/ReportOfferReason/ReportOfferReason.native.test.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/libs/algolia/__tests__/fetchAlgolia.test.ts, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.native.test.tsx, src/ui/components/inputs/DropDown/DropDown.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18854
I have:
=> (PC-18854) feat(tests): add new eslint rules for jest

src/features/onboarding/pages/AgeInformation.tsx, src/features/onboarding/pages/AgeSelectionOther.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19395
I have:
=> (BSR) perf(onboarding): Improve perf in new onboarding

ios/Podfile.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19425
=> (PC-19425) build(Podfile): maj podfile for react-native-svg

src/ui/components/inputs/EmailInputWithSpellingHelp/SpellingHelp.stories.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/SpellingHelp.tsx
si tu veux avancer sur le redesign de la banner, autant ne pas faire de conflit et commencer par fusionner le composant utilisé dans la branche en cours
I have:
=> feat(auth): add EmailInputWithSpellingHelp/SpellingHelp

src/features/offer/components/OfferTile/OfferTile.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx, src/features/venue/components/VenueOfferTile/VenueOfferTile.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19416
I have:
=> (PC-19416) fix(navigationOffer): fix navigation, force push instead of navigation

ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19471
I have:
=> (PC-19471) fix(dependencies): upgrade react-native-flipper

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19435
I have:
=> (PC-19435) fix(dependencies): upgrade @react-navigation/bottom-tabs

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, package.json, yarn.lock
This reverts commit bb32a9537da2abe82f0cbd130ca0b4eea5b7ac02.
I have:
=> (PC-19435) fix(dependencies): revert upgrade @react-navigation/bottom-tabs (#4132)

__snapshots__/features/home/components/modules/OffersModule.native.test.tsx.native-snap, __snapshots__/features/home/components/modules/venues/VenueTile.native.test.tsx.native-snap, __snapshots__/features/home/components/modules/venues/VenuesModule.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferTile/OfferTile.native.test.tsx.native-snap, __snapshots__/features/venue/components/VenueBody/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/components/VenueOfferTile/VenueOfferTile.native.test.tsx.native-snap, __snapshots__/features/venue/components/VenueOffers/VenueOffers.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, __snapshots__/ui/components/__tests__/ImageTile.native.test.tsx.native-snap, ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19478
I have:
=> (PC-19478) fix(dependencies): upgrade react-native-fast-image

.circleci/config.yml, ios/Podfile.lock, package.json, scripts/check_branch.sh, scripts/deploy.sh, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19465
I have:
=> (PC-19465) fix(dependencies): upgrade lib react-native-safe-area-context

src/features/culturalSurvey/components/CulturalSurveyCheckbox.tsx, src/features/culturalSurvey/components/__tests__/CulturalSurveyCheckbox.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19429
I have:
=> (PC-19429) feat(accessibility): Make CulturalSurvey answers accessible

e2e/tests/pc/features/onboarding/OnboardingGeolocation.ts, e2e/tests/pc/helpers/FirstLaunch.ts, src/features/onboarding/pages/AgeSelection.native.test.tsx, src/features/onboarding/pages/AgeSelection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19499
I have:
=> (PC-19499) fix(onboarding): Remove custom goBack behavior

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19468
I have:
=> (PC-19468) fix(dependencies): upgrade react-native-qrcode-svg

src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/ui/components/radioButtons/RadioButton.stories.tsx, src/ui/components/radioButtons/RadioButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19477
I have:
=> (PC-19477) fix(search): around me slider display

src/features/home/api/useHomepageData.ts, src/libs/contentful/adapters/helpers/hasAtLeastOneField.ts
Fix typescript warning causing web build to fail (https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/22176/workflows/f9d28535-c3f8-48b1-83f6-b462d132aa77/jobs/96393)
=> (BSR) chore(typescript): fix typescript warnings

package.json, src/ui/components/inputs/EmailInputWithSpellingHelp/EmailInputWithSpellingHelp.native.test.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/EmailInputWithSpellingHelp.stories.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/EmailInputWithSpellingHelp.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/SpellingHelp.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/suggestEmail.test.ts, src/ui/components/inputs/EmailInputWithSpellingHelp/suggestEmail.ts, src/ui/components/inputs/EmailInputWithSpellingHelp/useEmailSpellingHelp.native.test.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/useEmailSpellingHelp.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19410
Cette US a pour but de définir le comportement pas l'UI
I have:
=> (PC-19410) feat(ui): email input with spelling help

.circleci/config.yml, package.json, scripts/check_branch.sh, scripts/deploy.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19465
I have:
[PC-19465]: https://passculture.atlassian.net/browse/PC-19465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-19465) fix(deploy): Revert changes made to deploy

src/ui/components/radioButtons/RadioButton.stories.tsx
=> (BSR) fix(storybook): remove story radio button with loading

src/features/offer/helpers/renderOfferPageTestUtil.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19293
I have:
[PC-19293]: https://passculture.atlassian.net/browse/PC-19293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-19293) feat(offer): add missing event param fromOfferId

src/features/search/components/SearchBox/SearchBox.tsx, src/libs/firebase/analytics/__tests__/utils.test.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/types.ts, src/libs/firebase/analytics/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19296
I have:
[PC-19296]: https://passculture.atlassian.net/browse/PC-19296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-19296) fix(search): send filters values PerformSearch log

src/features/auth/signup/SetPassword/SetPassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19553
I have:
[PC-19553]: https://passculture.atlassian.net/browse/PC-19553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-19553) fix(SetPassword): restore auto focus

__snapshots__/features/venue/components/VenueBody/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/components/VenueOffers/VenueOffers.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffers.tsx, src/features/venue/helpers/useVenueSearchParameters/useVenueSearchParameters.native.test.ts, src/features/venue/helpers/useVenueSearchParameters/useVenueSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19383
I have:
| iOS              |<img width="453" alt="Capture d’écran 2023-01-04 à 13 54 26" src="https://user-images.githubusercontent.com/78556024/210567191-acd2475e-b726-489a-8c5d-186503d9145b.png">|<img width="430" alt="Capture d’écran 2023-01-04 à 14 35 19" src="https://user-images.githubusercontent.com/78556024/210567475-b57eabe2-a0ec-45c4-a8cd-28fd66c13e33.png">|
| Android          |<img width="417" alt="Capture d’écran 2023-01-04 à 14 27 59" src="https://user-images.githubusercontent.com/78556024/210567248-afba69f3-14ca-4594-ac28-a015c1aab219.png">|<img width="429" alt="Capture d’écran 2023-01-04 à 14 34 …
=> (PC-19383) feat(venueOffers): update carousel displaying

src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19561
I have:
[PC-19561]: https://passculture.atlassian.net/browse/PC-19561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-19561) fix(search): improve reset genre/type

doc/standards/codeStructure.md
as discussed in decembre 2022 -> see: https://passcultureteam.slack.com/archives/G01C85B6DHA/p1671444377798619
=> (BSR) docs(codeStructure): add shared folder for reusable helpers

src/features/home/api/useHomepageData.ts, src/features/home/fixtures/homepage.fixture.ts, src/features/home/fixtures/homepageList.fixtures.ts, src/features/home/helpers/selectHomepageEntry.native.test.ts, src/features/home/helpers/selectHomepageEntry.ts, src/features/home/types.ts, src/libs/contentful/adapters/adaptHomepageEntries.ts
In order to remove the dependency between home types and contentful types
=> (BSR) chore(homepageType): create a HomepageTag type 

src/features/home/api/helpers/getRecommendationEndpoint.native.test.ts, src/features/home/api/helpers/getRecommendationEndpoint.ts, src/features/home/api/useHomeRecommendedHits.native.test.ts, src/features/home/api/useHomeRecommendedHits.ts, src/features/home/types.ts, src/libs/contentful/types.ts, src/libs/recommendation/types.ts, src/libs/recommendation/useHomeRecommendedIdsMutation.test.ts, src/libs/recommendation/useHomeRecommendedIdsMutation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19402
I have:
| flipper/contentful             | <img width="593" alt="image" src="https://user-images.githubusercontent.com/89008469/210573984-cbd88670-29a0-4a8b-881f-651af8b3ae2e.png"> | <img width="901" alt="image" src="https://user-images.githubusercontent.com/89008469/210574093-a66cfa04-ce43-42a3-a0c3-02770905b978.png"> |
[PC-19402]: https://passculture.atlassian.net/browse/PC-19402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-19402) feat(RecommendedOffers): add a model endpoint param

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/home/components/modules/HomeModule.tsx, src/features/home/components/modules/categories/CategoryBlock.stories.tsx, src/features/home/components/modules/categories/CategoryBlock.tsx, src/features/home/components/modules/categories/CategoryListModule.stories.tsx, src/features/home/components/modules/categories/CategoryListModule.tsx, src/features/home/fixtures/homepage.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/adaptHomepageModules.native.test.ts, src/libs/contentful/adapters/adaptHomepageModules.ts, src/libs/contentful/adapters/modules/adaptCategoryListModule.native.test.ts, src/libs/contentful/adapters/modules/adaptCategoryListModule.ts, src/libs/contentful/fixtures/categoryList.fixture.ts, src/libs/contentful/fixtures/homepageNatifEntry.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18781
I have:
| iOS              |        |![Simulator Screen Shot - iPhone 13 mini - 2023-01-03 at 13 20 09](https://user-images.githubusercontent.com/22886846/210364623-7ce0e248-a6d4-44c6-96be-8037c58f0416.png)|
| contentful - category list |        |<img width="997" alt="Capture d’écran 2023-01-03 à 14 57 27" src="https://user-images.githubusercontent.com/22886846/210371555-f591363e-4da6-4061-a8c4-127e3c196622.png">|
| contentful - category block |        |<img width="1073" alt="Capture d’écran 2023-01-03 à 14 57 35" src="https://user-images.githubusercontent.com/22886846/210371 …
=> (PC-18781) feat(home): add category module

__snapshots__/features/identityCheck/pages/profile/SetAddress.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/profile/SetAddress.web.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/profile/SetCity.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap, __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap, src/features/search/components/FilterSwitchWithLabel/FilterSwitchWithLabel.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/ui/components/inputs/SearchInput.tsx, src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19460
I have:
**Pas de régression**
| iOS              |    |      ![Simulator Screen Shot - iPhone 13 - 2023-01-05 at 10 43 47](https://user-images.githubusercontent.com/46637324/210750807-125956c2-52ed-4e46-8da4-8eada66f144c.png) ![Simulator Screen Shot - iPhone 13 - 2023-01-05 at 11 52 59](https://user-images.githubusercontent.com/46637324/210763820-1fe68708-1a3a-4329-b11e-93c82be2c378.png)|
| Android          |       |   ![Screenshot_20230105_104407](https://user-images.githubusercontent.com/46637324/210750790-3a691a59-c577-42ee-b910-37bff6b30dea.png) ![Screenshot_20230105_115249](https://user-images.githubusercontent.com/46637324/210763844-31192d …
=> (PC-19460) fix(accessibility): Make search pages more accessible

__snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap, src/features/search/components/FilterPageButtons/FilterPageButtons.tsx, src/features/search/components/SearchBox/SearchBox.tsx, src/features/search/components/SearchMainInput/SearchMainInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19462
I have:
| Téléphone normal              |        |  ![tel-1](https://user-images.githubusercontent.com/46637324/210820134-c973e061-1eca-4ecb-9649-1c6af23cb33e.png) ![tel-3](https://user-images.githubusercontent.com/46637324/210820426-7a30ed03-f0b4-42eb-834d-59230303cc2a.png) ![tel-4](https://user-images.githubusercontent.com/46637324/210820429-692bf4be-6565-47a7-a4de-a4ef19bb3dc9.png) |
| Très petit téléphone              |        |     ![petit-1](https://user-images.githubusercontent.com/46637324/210819478-87e4b5bb-e3e7-4d92-80d9-ce192936cbd7.png) ![petit-2](https://user-images.githubusercontent.com/46637324/2108194 …
=> (PC-19462) fix(accessibility): Make filter buttons more accessible

__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/pages/OfferDescription/OfferDescription.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19428
I have:
=> (PC-19428) fix(dependencies): upgrade react-native-screens

doc/development/e2e.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19275
I have:
[PC-19275]: https://passculture.atlassian.net/browse/PC-19275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (PC-19275) docs(e2e): Update doc

src/features/home/components/modules/ThematicHighlightModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18782
I have:
| iOS              |        | <img width="333" alt="image" src="https://user-images.githubusercontent.com/26742386/211031252-35ee9264-1481-41ad-8001-2640fdd6512b.png"> |
| Phone - Chrome   | <img width="376" alt="image" src="https://user-images.githubusercontent.com/26742386/211030815-7c152b5d-684f-48af-8a13-45f09fa797ed.png"> | <img width="376" alt="image" src="https://user-images.githubusercontent.com/26742386/211030763-6004100b-5f00-4723-bb10-a1001ea3dc57.png"> |
| Desktop - Chrome | <img width="1024" alt="image" src="https://user-images.githubusercontent.com/26742386/211030870-79a5adcd-ec6a-4648-adaf-6c1148a34062.png"> | <img …
=> (PC-18782) fix(thematicHighlight): add non-gradient background behind title

doc/development/e2e.md, src/libs/e2e/tests/useE2eTestId.test.ts, src/libs/e2e/useE2eTestId.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19651
I have:
=> (PC-19651) feat(e2e): added useE2eTestId

src/features/home/components/modules/exclusivity/ExclusivityOffer.tsx, src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/TabBarComponent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19577
I have:
https://www.notion.so/passcultureapp/RDP-bug-5dc0881d13e44681ac76636220f03940
=> (PC-19577) fix(InternalTouchableLink): fix some typing for navigateTo props

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/home/components/modules/categories/CategoryBlock.stories.tsx, src/features/home/components/modules/categories/CategoryBlock.tsx, src/features/home/components/modules/categories/CategoryListModule.native.test.tsx, src/features/home/components/modules/categories/CategoryListModule.stories.tsx, src/features/home/components/modules/categories/CategoryListModule.tsx, src/features/home/fixtures/homepage.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/modules/adaptCategoryListModule.ts, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19328
I have:
=> (PC-19328) feat(categoryBlock): tracker category block

__snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferNativeCategoryChoices.test.tsx.native-snap, __snapshots__/features/_marketingAndCommunication/atoms/__tests__/OfferNativeCategoryChoices.test.tsx.web-snap, src/features/_marketingAndCommunication/atoms/OfferCategoryChoices.tsx, src/features/_marketingAndCommunication/atoms/OfferNativeCategoryChoices.tsx, src/features/_marketingAndCommunication/atoms/__tests__/OfferCategoryChoices.test.tsx, src/features/_marketingAndCommunication/atoms/__tests__/OfferNativeCategoryChoices.test.tsx, src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/_marketingAndCommunication/components/__tests__/DeeplinksGeneratorForm.native.test.tsx, src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts, src/features/search/components/sections/Category/Category.tsx, src/features/search/helpers/categoriesHelpers.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.tsx, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19533
I have:
| Desktop - Chrome |<img width="1728" alt="Capture d’écran 2023-01-06 à 12 20 03" src="https://user-images.githubusercontent.com/78556024/211002652-f38c12f3-c201-4d42-97bc-04677d7853e9.png">|<img width="1725" alt="Capture d’écran 2023-01-06 à 12 20 15" src="https://user-images.githubusercontent.com/78556024/211002679-1c741d0c-19b9-4d73-8ac2-fa272547e39d.png">|
[1]: …
=> (PC-19533) feat(deeplinkGenerator): filter on subcategory & alphabetical sorting

src/features/home/components/modules/exclusivity/ExclusivityImage.tsx, src/libs/react-native-web-fast-image/index.js, src/libs/resizing-image-on-demand/FastImage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19715
I have:
=> (PC-19715) fix(accessibility): Pass accessibilityLabel as alt attribute for image

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, package.json, patches/@react-navigation+core+6.2.2.patch, patches/@react-navigation+native+6.0.12.patch, src/features/auth/signup/SignupForm.native.test.tsx, src/features/navigation/__mocks__/navigationRef.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19447
I have:
=> (PC-19447) fix(dependencies): upgrade lib react-navigation/native & react-navigation/stack

android/app/src/main/AndroidManifest.xml, ios/PassCulture/Info.plist, src/features/cheatcodes/pages/GetDynamicSocials/GetDynamicSocials.tsx, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19260
I have:
=> (PC-19260) feat(shareOffer): spike get socials

src/features/home/components/modules/exclusivity/ExclusivityExternalLink.native.test.tsx, src/features/home/components/modules/exclusivity/ExclusivityExternalLink.tsx, src/ui/components/touchableLink/ExternalTouchableLink.test.tsx, src/ui/components/touchableLink/ExternalTouchableLink.tsx, src/ui/components/touchableLink/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19273
I have:
=> (PC-19273) fix(exclusivity): Open ExclusivityModule in app

__snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap, src/features/search/pages/SearchFilter/SearchFilter.tsx
=> (BSR) fix(SearchFilter): fix spacing

src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19623
I have:
=> (PC-19623) feat(Offer): rewording tracker and adding the param fromOfferId

e2e/tests/pc/helpers/utils/theme.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19413
I have:
=> (PC-19413) fix(e2e): Update theme breakpoint

src/features/search/components/Highlight/Highlight.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19761
I have:
| iOS              |<img width="467" alt="Capture d’écran 2023-01-11 à 15 25 44" src="https://user-images.githubusercontent.com/78556024/211831204-c20ea8f9-e547-4ac9-831a-aa4a0a86f7e7.png">|<img width="466" alt="Capture d’écran 2023-01-11 à 15 25 28" src="https://user-images.githubusercontent.com/78556024/211831234-79724a6f-7a1f-49dc-af92-f720dfebeb58.png">|
| Desktop - Chrome |<img width="865" alt="Capture d’écran 2023-01-11 à 15 01 11" …
=> (PC-19761) fix(search): encoding apostrophe autocomplete

src/features/auth/signup/SetEmail/SetEmail.tsx, src/shared/forms/controllers/EmailInputController.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19733
I have:
| iOS              |        |  ![Simulator Screen Shot - iPhone 13 - 2023-01-12 at 10 03 04](https://user-images.githubusercontent.com/46637324/212024239-43fe0d93-b835-4b3e-896d-1d54db9c2af6.png)     |
| Desktop - Chrome |        |   <img width="921" alt="Capture d’écran 2023-01-12 à 10 02 48" src="https://user-images.githubusercontent.com/46637324/212024227-a670beda-fbf3-48e5-87e8-f6ad071259aa.png">   |
[1]: …
=> (PC-19733) feat(SetEmail): Use input with spelling help

.circleci/config.yml
=> (BSR) ci(fingerprint): update fingerprint

src/features/home/components/modules/categories/CategoryListModule.tsx, src/features/home/components/modules/categories/helpers/getColorFilter.native.test.ts, src/features/home/components/modules/categories/helpers/getColorFilter.ts, src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19397
I have:
| iOS              |        |![Simulator Screen Shot - iPhone 13 mini - 2023-01-11 at 09 23 44](https://user-images.githubusercontent.com/22886846/211755127-4e766f51-404a-4eae-a814-37b29b17cf09.png)|
| Phone - Safari   |        |![Simulator Screen Shot - iPhone 13 mini - 2023-01-11 at 09 27 57](https://user-images.githubusercontent.com/22886846/211755790-1452478e-bbb1-4d0f-9a21-a10bb71c4533.png)|
| Desktop - Chrome |        |<img width="1048" alt="Capture d’écran 2023-01-11 à 09 27 48" …
=> (PC-19397) feat(home): add design implementation for category list module on desktop

.circleci/config.yml, .env.integration, .env.production, .env.staging
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19799
=> (PC-19799) ci(AppsFlyer): move public key to dotenv

.github/workflows/reusable-e2e-buildsimuioszip.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19802
I have:
=> (PC-19802) ci(e2e): remove unused secrets + usage

src/features/auth/signup/SetEmail/SetEmail.tsx, src/shared/forms/controllers/EmailInputController.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/EmailInputWithSpellingHelp.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/SpellingHelp.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19733
I have:
=> (PC-19733) feat(signup): add spelling help to SetEmail

__snapshots__/features/profile/components/Modals/CreditCeilingsModal.native.test.tsx.native-snap, src/features/profile/components/Modals/CreditCeilingsModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19852
I have:
| iOS              |      ![Simulator Screen Shot - iPhone 13 - 2023-01-16 at 17 11 39](https://user-images.githubusercontent.com/46637324/212722857-4a15af14-9ab8-4117-9f35-8773e1db6539.png)  |   ![Simulator Screen Shot - iPhone 13 - 2023-01-16 at 17 06 03](https://user-images.githubusercontent.com/46637324/212722616-308a9465-d8a7-49a0-b190-afe31839e8b8.png)    |
| Android          |  ![Screenshot_20230116_171128](https://user-images.githubusercontent.com/46637324/212722826-942902ad-f525-4c60-9057-a67d5989c575.png)     |    ![Screenshot_20230116_170558](https://user-images.githubusercontent.com/46637324/212722604-e34fab8c-362d-4a4b-a828- …
=> (PC-19852) fix(credits): Fix bullet list display

__snapshots__/features/onboarding/pages/OnboardingWelcome.native.test.tsx.native-snap, src/features/onboarding/pages/OnboardingWelcome.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19594
I have:
| Android          |        |![Capture d’écran 2023-01-13 à 18 05 58](https://user-images.githubusercontent.com/59031393/212379586-1b83f842-aa65-408e-a7b0-1a7835e82c6e.png)|
=> (PC-19594) feat(onboarding): Wording change on welcome page

src/ui/components/modals/AppInformationModal.tsx, src/ui/components/modals/MarketingModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19413
I have:
| iOS              | Au clic sur l'arrière-plan   ![Simulator Screen Shot - iPhone 13 - 2023-01-17 at 10 25 53](https://user-images.githubusercontent.com/46637324/212860231-7e6cdc17-4be7-419c-9c8d-33cae2e685f9.png)  |  Au clic sur l'arrière-plan   ![Simulator Screen Shot - iPhone 13 - 2023-01-17 at 10 26 28](https://user-images.githubusercontent.com/46637324/212860212-9c87155a-c4a1-4e62-85d3-805994b73825.png)  |
[1]: …
=> (PC-19413) fix(modals): Keep same opacity on backdrop click

.vscode/todo-mob.code-snippets
=> (BSR) docs(snippets): add todo-mob snippets v1

__snapshots__/features/bookOffer/pages/BookingConfirmation.native.test.tsx.native-snap, src/features/bookOffer/pages/BookingConfirmation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19501
I have:
| iOS              | ![Capture d’écran 2023-01-17 à 13 08 20](https://user-images.githubusercontent.com/62059034/212895378-0c72455b-84b3-4d5b-8310-677a9e9d4f32.png)       |     ![Capture d’écran 2023-01-17 à 13 07 51](https://user-images.githubusercontent.com/62059034/212895466-96e1ffda-c3fd-4822-b84b-d1d6e7d40a06.png) | …
=> (PC-19501) feat(bookOffer): update design for BookingConfirmation

src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.native.test.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx, src/features/identityCheck/pages/profile/SetAddress.native.test.tsx, src/features/identityCheck/pages/profile/SetAddress.tsx, src/features/identityCheck/pages/profile/SetCity.native.test.tsx, src/features/identityCheck/pages/profile/SetCity.tsx, src/features/identityCheck/pages/profile/SetName.native.test.tsx, src/features/identityCheck/pages/profile/SetName.tsx, src/features/identityCheck/pages/profile/SetSchoolType.native.test.tsx, src/features/identityCheck/pages/profile/SetSchoolType.tsx, src/features/identityCheck/pages/profile/SetStatus.native.test.tsx, src/features/identityCheck/pages/profile/SetStatus.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19744
I have:
=> (PC-19744) feat(tracking): add amplitude click events on phone validation and profile pages

public/.well-known/assetlinks-staging.json, public/.well-known/assetlinks-testing.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19915
I have:
=> (PC-19915) fix(assetlinks): support old and new keystores testing+staging

doc/development/e2e.md
=> (BSR) docs(e2e): clean doc

public/.well-known/assetlinks-production.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19959
I have:
=> (PC-19959) build(keystore): add signature for next prod keystore

src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/navigation/RootNavigator/types.ts, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts, src/shared/forms/controllers/EmailInputController.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/EmailInputWithSpellingHelp.native.test.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/EmailInputWithSpellingHelp.tsx, src/ui/components/inputs/EmailInputWithSpellingHelp/SpellingHelp.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19461
I have:
=> (PC-19461) feat(auth): add tracking for spellingHelp in SetEmail

__snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx.native-snap, __snapshots__/features/onboarding/pages/AgeInformation.native.test.tsx.native-snap, src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/identityCheck/components/HeroButtonList.tsx, src/features/identityCheck/components/SecondButtonList.stories.tsx, src/features/identityCheck/components/SecondButtonList.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx, src/features/onboarding/components/AgeSeparator.tsx, src/ui/components/SeparatorWithText.stories.tsx, src/ui/components/SeparatorWithText.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19097
I have:
| Platform         | Before | After | Before | After |
| :--------------- | :----: | :---: | :----: | :---: |
| iOS              | <img width="385" alt="image" src="https://user-images.githubusercontent.com/89008469/212645091-765e861a-3033-4737-9914-bc6426715911.png"> | <img width="386" alt="image" src="https://user-images.githubusercontent.com/89008469/212112767-15a70c3b-2688-44da-a96b-a09df37979fe.png"> | <img width="387" alt="image" src="https://user-images.githubusercontent.com/89008469/212644992-6cb62b83-e811-433f-940a-c45bb2dd949d.png"> | <img width="390" alt="image" src="https://user-images.githubusercontent.com/89008469/212641874-c19cc12b-d4ba-4791-a37c-5597c6f7b35c.png"> | …
=> (PC-19097) feat(ubble): update Ubble flow design 

src/features/auth/components/AuthenticationButton/AuthenticationButton.native.test.tsx, src/features/auth/components/AuthenticationButton/AuthenticationButton.tsx, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/favorites/components/NotConnectedFavorites.test.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19542
I have:
=> (PC-19542) feat(offer): Add offer to favorite on login when coming from favorite modal

__snapshots__/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx.native-snap, src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19543
I have:
=> (PC-19543) test(ChangeEmail): Refactor and improve tests

src/features/identityCheck/components/FastEduconnectConnectionRequestModal.native.test.tsx, src/features/identityCheck/components/FastEduconnectConnectionRequestModal.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnect.native.test.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnect.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.native.test.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.tsx, src/features/identityCheck/pages/identification/identificationStart/ComeBackLater.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/ComeBackLater.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19749
I have:
| Platform         | screen | amplitude |
| M'identifier plus tard              | <img width="358" alt="image" src="https://user-images.githubusercontent.com/89008469/213730701-bfb00917-2988-4d1b-aec8-f84b8f274c50.png"> | <img width="1698" alt="image" src="https://user-images.githubusercontent.com/89008469/213729123-c0697da9-39e2-4e8c-97c9-bb344c54022d.png"> |
| Valider mes informations       | <img width="347" alt="image" src="https://user-images.githubusercontent.com/89008469/213730330-30357efb-c32d-4fdd-9618-1b47755a3484.png"> | <img width="1568" alt="image" src="https://user-images.githubusercontent.com/89008469/213729365-2b791424-74e2-4d53-9 …
=> (PC-19749) feat(amplitude): trackers 4/4

src/features/identityCheck/components/HeroButtonList.tsx, src/features/identityCheck/components/SecondButtonList.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDOrigin.web.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/SelectIDStatus.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19747
I have:
=> (PC-19747) feat(amplitude): track click on select id status and origin pages

src/ui/components/SectionRow.stories.tsx
=> (BSR) fix(storybook): disable sectionRow stories

src/features/home/components/modules/ThematicHighlightModule.native.test.tsx, src/features/home/components/modules/ThematicHighlightModule.tsx, src/features/home/fixtures/homepage.fixture.ts, src/libs/contentful/fixtures/thematicHighlightModule.fixture.ts, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19909
I have:
=> (PC-19909) feat(analytics): add tracker to click on thematic highlight module

src/features/home/components/modules/OffersModule.native.test.tsx, src/features/home/fixtures/homepage.fixture.ts, src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/libs/contentful/fetchHomepageNatifContent.ts, src/libs/contentful/fixtures/algoliaModules.fixture.ts, src/libs/contentful/fixtures/businessModule.fixture.ts, src/libs/contentful/fixtures/exclusivityModule.fixture.ts, src/libs/contentful/fixtures/recommendationNatifModule.fixture.ts, src/libs/contentful/fixtures/thematicHighlightModule.fixture.ts, src/libs/contentful/fixtures/venuesModule.fixture.ts, src/libs/contentful/types.ts, src/libs/search/parseSearchParameters.test.ts, src/libs/search/parseSearchParameters.ts, src/libs/search/useParseSearchParameters.test.ts, src/libs/search/useParseSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16476
I have:
Dans l'appel à Algolia d'une playlist :
=> (PC-16476) feat(contentful): add subcategories to algolia parameters from separate entry

src/features/home/api/useHomeRecommendedHits.native.test.ts, src/features/home/fixtures/homepage.fixture.ts, src/libs/contentful/adapters/modules/adaptRecommendationModule.ts, src/libs/contentful/fixtures/algoliaModules.fixture.ts, src/libs/contentful/fixtures/recommendationNatifModule.fixture.ts, src/libs/contentful/fixtures/subcategoriesEntry.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19755
I have:
Request body de l'appel à Algolia, pour une entrée Subcategories avec ces valeurs sélectionnées :
=> (PC-19755) feat(contentful): use subcategories entry for recommendation parameters

__snapshots__/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx.native-snap, src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx, src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19754
I have:
| iOS              |        |     ![Simulator Screen Shot - iPhone 13 - 2023-01-23 at 16 04 01](https://user-images.githubusercontent.com/46637324/214085832-4b51d220-8ddf-48f7-aad7-3034306cd535.png)  |
| Android          |        |   ![Screenshot_20230123_160433](https://user-images.githubusercontent.com/46637324/214085850-0e692a29-39e0-42eb-8435-fa370bf8952f.png)    |
| Desktop - Chrome |        |  <img width="1440" alt="Capture d’écran 2023-01-23 à 16 03 56" src="https://user-images.githubusercontent.com/46637324/214085792-ead3d666-bb82-4305-9d4e-7584b92f278f.png">     | …
=> (PC-19754) fix(ConfirmDeleteProfile): Update wording

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, src/features/profile/pages/Profile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19690
I have:
| iOS              | <img width="300" src="https://user-images.githubusercontent.com/46637324/214525231-adddc78a-579c-4b7d-bdef-961b624ffba5.png" />     |   <img  width="300" src="https://user-images.githubusercontent.com/46637324/214525463-f6959957-fbe1-4eb1-a79b-065b6e8ec6b6.png" />   |
| iOS - small phone   |   <img  width="300" src="https://user-images.githubusercontent.com/46637324/214525261-d57337d0-16ae-490a-bd99-4c6b3c14115a.png" />    |   <img width="300" src="https://user-images.githubusercontent.com/46637324/214525446-3b8ba4b1-2a77-4fb8-93a9-68ef420d67c2.png" />   |
| Android          |   <img …
=> (PC-19690) fix(profile): Change share wording

src/features/home/components/modules/categories/CategoryListModule.stories.tsx
J'ai ajouté un nouveau ticket pour investiguer sur le problème des analytics avec les stories.  https://passculture.atlassian.net/browse/PC-20094
I have:
=> (BSR) fix(storybook): disable CategoryListModule stories

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap, src/features/bookings/components/ActivationCodeButton.tsx, src/features/bookings/components/BookingDetailsCancelButton.native.test.tsx, src/features/bookings/components/BookingDetailsCancelButton.tsx, src/features/bookings/components/BookingExpiration.tsx, src/features/bookings/components/CancelBookingButton.tsx, src/features/bookings/helpers/expirationDateUtils.test.ts, src/features/bookings/helpers/expirationDateUtils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19509
I have:
| iOS              |        |![Capture d’écran 2023-01-23 à 16 38 22](https://user-images.githubusercontent.com/62058919/214081668-b46d0697-0d02-4848-8f26-8a492e22b5e8.png)|
=> (PC-19509) feat(BookingDetailsCancel): display an expiration date message if the booking is digital

src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20101
I have:
=> (PC-20101) fix(ForgottenPassword): support for enableRecaptcha

src/features/internal/marketingAndCommunication/atoms/OfferCategoryChoices.test.tsx, src/features/internal/marketingAndCommunication/atoms/OfferCategoryChoices.tsx, src/features/search/components/CategoriesButtons/CategoriesButtons.native.test.tsx, src/features/search/helpers/useAvailableCategories/useAvailableCategories.test.tsx, src/features/search/helpers/useAvailableCategories/useAvailableCategories.tsx, src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.test.tsx, src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20050
I have:
=> (PC-20050) fix(search): display categories from backend existing in CATEGORY_CRITERIA

__snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap, src/features/search/components/SearchCustomModalHeader.tsx, src/features/search/components/sections/Category/Category.tsx, src/features/search/components/sections/DateHour/DateHour.tsx, src/features/search/components/sections/Location/Location.tsx, src/features/search/components/sections/OfferDuo/OfferDuo.tsx, src/features/search/components/sections/Price/Price.tsx, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.tsx, src/features/search/pages/SearchFilter/SearchFilter.web.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.web.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.tsx, src/ui/components/headers/CloseButton.tsx, src/ui/components/headers/PageHeaderSecondary.stories.tsx, src/ui/components/headers/PageHeaderSecondary.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19725
I have:
| iOS              |<img width="453" alt="Capture d’écran 2023-01-25 à 15 53 02" src="https://user-images.githubusercontent.com/78556024/214596499-ffb7b544-dca7-42b8-bbcd-0798c1e1a11c.png"> <img width="466" alt="Capture d’écran 2023-01-25 à 15 53 13" src="https://user-images.githubusercontent.com/78556024/214596512-0576334c-eccd-47c9-88ea-544adc2de399.png">|<img width="441" alt="Capture d’écran 2023-01-25 à 15 53 50" src="https://user-images.githubusercontent.com/78556024/214596576-cdc00865-5997-4a2a-b0bf-be8254f0086a.png"> <img width="473" alt="Capture d’écran 2023-01-25 à 15 53 57" …
=> (PC-19725) feat(search): use close and back buttons in all search filters modals

__snapshots__/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx.native-snap, __snapshots__/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx.web-snap, __snapshots__/features/culturalSurvey/pages/FAQWebview.native.test.tsx.native-snap, src/features/culturalSurvey/constants.ts, src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx, src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx, src/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx, src/features/culturalSurvey/pages/FAQWebview.native.test.tsx, src/features/culturalSurvey/pages/FAQWebview.tsx, src/features/culturalSurvey/pages/FAQWebview.web.tsx, src/features/navigation/RootNavigator/culturalSurveyRoutes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18982
I have:
| Platform         | Before | After | FAQ | 
| :--------------- | :----: | :---: | :---: |
| iOS              |![Simulator Screen Shot - iPhone 13 mini - 2023-01-25 at 11 54 19](https://user-images.githubusercontent.com/22886846/214545758-c4de18cc-f09f-4690-886d-a59d773a981b.png)|![Simulator Screen Shot - iPhone 13 mini - 2023-01-25 at 11 55 21](https://user-images.githubusercontent.com/22886846/214545797-0d02cbfb-6ef1-4a11-8fbf-683358a15b82.png)|.   |
| Android          |        |<img width="258" alt="Capture d’écran 2023-01-25 à 11 51 31" src="https://user-images.githubusercontent.com/22886846/214546630-b2474468-9303-4a37-af1c-c36bcaf161bd.png">|https://user-images.githubusercontent.com/22886846/214548551-aa …
=> (PC-18982) feat(CulturalSurvey): update introduction design + add FAQ link

src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19919
I have:
=> (PC-19919) test(SetEmail): Add email suggestion test

src/features/search/components/FilterRow/FilterRow.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.web.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19722
I have:
| Desktop - Chrome |<img width="1725" alt="Capture d’écran 2023-01-27 à 09 28 23" src="https://user-images.githubusercontent.com/78556024/215051346-f7246b0f-d551-4670-8855-6633f395d550.png">|<img width="1728" alt="Capture d’écran 2023-01-27 à 09 30 41" src="https://user-images.githubusercontent.com/78556024/215051380-9aecd96b-ff90-47d4-9397-b011e89ec9bd.png">|
[1]: …
=> (PC-19722) feat(search): add chevrons categories filter desktop web

__snapshots__/features/search/components/SearchAutocomplete/SearchAutocomplete.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.native.test.tsx.native-snap, src/features/search/components/Highlight/Highlight.native.test.tsx, src/features/search/components/SearchAutocomplete/SearchAutocomplete.native.test.tsx, src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.native.test.tsx, src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.tsx, src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/libs/algolia/algolia.d.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19824
I have:
| iOS              |<img width="420" alt="Capture d’écran 2023-01-26 à 15 12 21" src="https://user-images.githubusercontent.com/78556024/214858960-43e427b8-beb5-489e-bc47-bf915cb480bb.png">|<img width="422" alt="Capture d’écran 2023-01-26 à 14 59 38" src="https://user-images.githubusercontent.com/78556024/214858593-aaa3d094-1c3b-479e-b378-a0cbe14c9e40.png">|
| Phone - Chrome   ||       |
| Desktop - Chrome |<img width="866" alt="Capture d’écran 2023-01-26 à 14 51 29" src="https://user-images.githubusercontent.com/78556024/214858 …
=> (PC-19824) feat(search): add native category in autocomplete

__snapshots__/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.native.test.tsx.native-snap, src/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20067
I have:
| Android          |        |<img width="351" alt="Capture d’écran 2023-01-26 à 16 53 36" src="https://user-images.githubusercontent.com/59031393/214883861-f6cc9c11-337b-4742-9f2e-061c9d0ddfc6.png">|
| Phone - Chrome   |        |<img width="326" alt="Capture d’écran 2023-01-26 à 16 53 56" src="https://user-images.githubusercontent.com/59031393/214883793-0330f026-92d5-4dbd-be57-0a0a7a18ebb0.png">|
| Desktop - Chrome |        |<img width="1439" alt="Capture d’écran 2023-01-26 à 16 54 18" …
=> (PC-20067) feat(resetPassword): update wording in reset password modal

src/ui/components/buttons/RoundedButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20072
I have:
| Desktop - Chrome |        |<img width="1029" alt="Capture d’écran 2023-01-26 à 16 14 36" src="https://user-images.githubusercontent.com/59031393/214873378-5b8c96c5-23dd-4d0a-88a9-d1566d45191d.png">|
=> (PC-20072) feat(accessibility): change focus color for buttons in venue/offer header

__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap, src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.web.test.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19652
I have:
=> (PC-19652) feat(SetBirthday): add input in mobile date picker

src/features/identityCheck/pages/identification/identificationStart/ComeBackLater.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/ComeBackLater.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.native.test.tsx, src/features/identityCheck/pages/identification/identificationStart/ExpiredOrLostID.tsx, src/libs/react-native-batch/enums.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18797
I have:
=> (PC-18797) feat(ComeBackLater): add user events for come back later

src/features/home/components/modules/categories/CategoryListModule.native.test.tsx, src/features/home/components/modules/categories/CategoryListModule.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20183
I have:
| Firebase              | <img width="350" alt="image" src="https://user-images.githubusercontent.com/89008469/215442321-f60257eb-4361-4acb-899d-e479b33e04fd.png"> | <img width="350" alt="image" src="https://user-images.githubusercontent.com/89008469/215441961-ee68bb11-4b40-4801-a9e7-d3bc053a9ec8.png"> |
=> (PC-20183) chore(analytic): change param name to fit data requirements

__snapshots__/features/offer/pages/OfferDescription/OfferDescription.native.test.tsx.native-snap, src/features/offer/pages/Offer/Offer.web.test.tsx, src/features/offer/pages/OfferDescription/OfferDescription.native.test.tsx, src/features/offer/pages/OfferDescription/OfferDescription.web.test.tsx, src/features/offer/pages/OfferNotFound/OfferNotFound.web.test.tsx, src/ui/components/hero/Hero.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19061
I have:
=> (PC-19061) feat(Offer): add accessibility test for all Offer Pages

e2e/tests/pc/helpers/utils/logger.ts
To remove it's dependency to the test env
=> (BSR) ci(e2e): simplify logger

e2e/tests/pc/helpers/utils/deeplink.ts
=> (BSR) ci(e2e): fix openDeeplinks

e2e/tests/pc/helpers/utils/theme.ts, src/ui/theme/grid.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20071
I have:
| Desktop - Chrome |        |<img width="939" alt="Capture d’écran 2023-01-27 à 15 48 07" src="https://user-images.githubusercontent.com/59031393/215115115-97e2477f-522b-447c-b2e2-9cb5ebe6597b.png"><img width="941" alt="Capture d’écran 2023-01-27 à 15 47 35" src="https://user-images.githubusercontent.com/59031393/215115123-396854d3-f9b4-4376-a91c-a9aec84f576f.png">|
[1]: …
=> (PC-20071) feat(navBar): fix navBar in desktop view

src/features/navigation/RootNavigator/withScreenWrapper.tsx, src/ui/components/inputs/PasswordInput.tsx
=> (BSR) ci(e2e): add e2e test ids

src/api/api.ts, src/api/gen/api.ts, src/libs/e2e/constants.android.ts, src/libs/e2e/constants.ts, src/libs/e2e/getIsE2e.ts, src/libs/e2e/getIsE2e.web.ts, src/libs/e2e/tests/E2eContextProviderFalse.native.test.tsx, src/libs/e2e/tests/getIsE2e.native.test.ts, src/libs/e2e/tests/getIsE2e.web.test.ts, src/libs/e2e/tests/getIsE2eFalse.native.test.ts, src/libs/e2e/tests/getIsE2eFalse.web.test.ts, src/libs/e2e/tests/getIsE2eiOSSafariWorkaround.web.test.ts, swagger_codegen/gen_templates/api.mustache
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20209
I have:
=> (PC-20209) fix(e2e): improve getE2e method and change api basePath in e2e

src/features/search/enums.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx, src/libs/search/utils/__tests__/getCategoriesFacetFilters.test.ts, src/libs/search/utils/getCategoriesFacetFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20208
I have:
=> (PC-20208) fix(search): add partial CATEGORY_CRITERIA

src/ui/components/inputs/EmailInput/EmailInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20234
I have:
=> (PC-20234) fix(EmailInput): add e2e test id

e2e/tests/pc/helpers/FeatureClient.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20101
I have:
=> (PC-20101) ci(e2e): fix FeatureClient API_BASE_URL

src/features/auth/components/AuthenticationButton/AuthenticationButton.stories.tsx, src/features/identityCheck/components/HeroButtonList.stories.tsx
Fix flagged stories by : 
- exporting them
- adding a NavigationContainer
=> (BSR) chore(story): fix flagged stories

.github/workflows/e2e-browser.yml
Il faut mergé cela que je puisse avoir le workflow sur master et mergé les 3 workflows e2e browser dedans
=> (BSR) ci(e2e): add empty workflow for browser

src/features/bookings/helpers/expirationDateUtils.ts, src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx, src/features/bookings/pages/EndedBookings/EndedBookings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20259
I have:
=> (PC-20259) fix(expirationDate): fix days left

src/features/home/components/modules/OffersModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20266
I have:
=> (PC-20266) feat(OffersModule): remove subtitle display condition

src/libs/e2e/getIsE2e.web.ts, src/libs/e2e/tests/getIsE2eiOSSafariWorkaround.web.test.ts
=> (BSR) ci(e2e): increase getE2e safari.ios fix

e2e/tests/pc/helpers/Browser.ts, src/libs/e2e/getIsE2e.web.ts, src/libs/e2e/tests/getIsE2eiOSSafariWorkaround.web.test.ts
=> (BSR) ci(e2e): improve safari ios e2e detection

.github/workflows/e2e-android-app.yml, .github/workflows/e2e-android-browser.yml, .github/workflows/e2e-ios-app.yml, .github/workflows/e2e-ios-browser.yml, doc/development/e2e.md
=> (BSR) ci(e2e): appium allow cors

e2e/tests/pc/helpers/FirstLaunch.ts, src/App.native.test.tsx, src/App.tsx, src/features/cookies/helpers/startTracking.test.ts, src/features/cookies/helpers/startTracking.ts, src/features/cookies/helpers/startTrackingAcceptedCookies.test.ts, src/features/cookies/helpers/startTrackingAcceptedCookies.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesConsent.tsx, src/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx, src/features/profile/pages/ConsentSettings/ConsentSettings.tsx, src/libs/campaign/campaignTracker.native.test.ts, src/libs/campaign/campaignTracker.ts, src/libs/campaign/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20283
I have:
Démo : 
https://user-images.githubusercontent.com/46637324/216646947-7ea1692e-9ca7-45f8-b919-99a3923c2bcb.mp4
=> (PC-20283) fix(ATT): Display ATT only if user has accepted marketing cookies

public/index.html
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20088
I have:
=> (PC-20088) feat(seo): add google site verification

src/features/home/fixtures/homepage.fixture.ts, src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/libs/contentful/fixtures/algoliaModules.fixture.ts, src/libs/contentful/fixtures/categoriesFixture.ts, src/libs/contentful/fixtures/homepageEntriesAPIResponse.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19767
I have:
| Platform         | App | Algolia_parameters | Catégories |
| :--------------- | :----: | :---: | :---: |
| iOS              | <img width="397" alt="image" src="https://user-images.githubusercontent.com/89008469/216576074-4fcec79d-2eb8-4167-b9e1-2af89e8b27ff.png"> | <img width="729" alt="image" src="https://user-images.githubusercontent.com/89008469/216576421-ca6f2d05-fa25-4ba0-aa37-291ac6ca47cd.png"> | <img width="721" alt="image" src="https://user-images.githubusercontent.com/89008469/216576621-be8bd0a3-4d71-416e-a455-c6254a911017.png"> |
=> (PC-19767) feat(contentful): mutualisation categories contentful

src/features/offer/pages/OfferDescription/OfferDescription.native.test.tsx, src/features/offer/pages/OfferDescription/OfferDescription.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20288
I have:
| iOS              |<img width="458" alt="Capture d’écran 2023-02-06 à 09 49 40" src="https://user-images.githubusercontent.com/78556024/216926711-6cf94dfa-05ee-4b2b-931d-734f46c846a5.png">|<img width="440" alt="Capture d’écran 2023-02-06 à 09 49 28" src="https://user-images.githubusercontent.com/78556024/216926678-96498b47-1c29-4565-bfa3-a7752cbf086b.png">|
| Phone - Chrome   |<img width="409" alt="Capture d’écran 2023-02-03 à 16 44 20" src="https://user-images.githubusercontent.com/78556024/216925255-44606a14-a621-4461-b6f1-f1c2a16a3bb1.png">|<img width="406" …
=> (PC-20288) fix(offer): not display extra data not defined

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20293
I have:
=> (PC-20293) feat(booking): add feature flag for booking by categories prices

src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.test.ts, src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.ts, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/__tests__/utils.test.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts, src/libs/firebase/analytics/types.ts, src/libs/firebase/analytics/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20178
I have:
=> (PC-20178) feat(search): use perform search log rather than use landing category log

yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19579
I have:
=> (PC-19579) fix(Web): upgrade browserslist to latest

src/features/home/fixtures/homepage.fixture.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/libs/contentful/adapters/modules/adaptRecommendationModule.ts, src/libs/contentful/fixtures/recommendationNatifModule.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19768
I have:
| Platform         | Flipper | Contentful |
| iOS              | <img width="1080" alt="image" src="https://user-images.githubusercontent.com/89008469/216959232-11e16737-03cd-4942-94cd-96a0060dc2ba.png"> | <img width="606" alt="image" src="https://user-images.githubusercontent.com/89008469/216959119-54fe2257-ab3e-453d-9ded-c9ce8ea7d333.png"> |
=> (PC-19768) feat(contentful): mutualisation categories reco

__snapshots__/features/FavoriteList/FakeDoor/FavoriteListSurveyModal.native.test.tsx.native-snap, src/features/FavoriteList/FakeDoor/FavoriteListSurveyModal.native.test.tsx, src/features/FavoriteList/FakeDoor/FavoriteListSurveyModal.tsx, src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/features/internal/cheatcodes/pages/AppComponents/illustrationsExports.ts, src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx, src/features/internal/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx, src/ui/svg/icons/BicolorCircledClock.tsx, src/ui/svg/icons/ScreenPlay.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20222
I have:
| Android          |        |<img width="352" alt="Capture d’écran 2023-02-06 à 14 57 17" src="https://user-images.githubusercontent.com/59031393/217011503-81f7476b-def5-445c-b2c0-6836f12bdf7c.png">|
| Phone - Chrome   |        |<img width="391" alt="Capture d’écran 2023-02-06 à 14 57 33" src="https://user-images.githubusercontent.com/59031393/217011560-8325fcf3-2677-4c97-a50b-2d78c769984f.png">|
| Desktop - Chrome |        |<img width="1411" alt="Capture d’écran 2023-02-06 à 14 57 46" …
=> (PC-20222) feat(favoritesList): favorites list redirection popin

src/features/bookings/components/EndedBookingItem.native.test.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/helpers/expirationDateUtils.test.ts, src/features/bookings/helpers/expirationDateUtils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20316
I have:
| iOS              |<img width="447" alt="Capture d’écran 2023-02-07 à 09 05 51" src="https://user-images.githubusercontent.com/78556024/217187142-25a49bb0-0789-4483-be4b-0bb07b91efa9.png">|<img width="501" alt="Capture d’écran 2023-02-06 à 17 38 29" src="https://user-images.githubusercontent.com/78556024/217185439-55d356f6-ebbb-4e59-8e9f-70a72d67b89f.png">|
| Phone - Chrome   |<img width="400" alt="Capture d’écran 2023-02-07 à 09 02 32" src="https://user-images.githubusercontent.com/78556024/217186611-6f2b1e12-603c-4c72-961d-a542e45be839.png">|<img width="429" …
=> (PC-20316) feat(booking): open booking when booking is ended and is a digital offer without expiration date

src/features/bookOffer/pages/BookingOfferModal.web.test.tsx
Tests cassés suite à cette PR https://github.com/pass-culture/pass-culture-app-native/pull/4361
I have:
=> (BSR) test(BookingOfferModal): fix web tests

__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.tsx, src/features/search/components/sections/Category/Category.tsx, src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/features/search/helpers/categoriesHelpers/mapping-tree.test.ts, src/features/search/helpers/categoriesHelpers/mapping-tree.ts, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx, src/features/search/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19806
I have:
| Desktop - Chrome |<img width="579" alt="image" src="https://user-images.githubusercontent.com/114916654/216373046-10bd6575-9123-45e8-bec5-bab3c8f587ce.png"> |<img width="619" alt="image" src="https://user-images.githubusercontent.com/114916654/216372927-d1430f28-9b7f-4d4c-b232-26bb026d2ec0.png">|
=> (PC-19806) feat(search): Remove "cartes jeunes" native category

src/features/offer/pages/Offer/Offer.web.test.tsx
=> (BSR) test(offer): fix web test

.eslintrc.js, __snapshots__/features/onboarding/pages/AgeInformation.native.test.tsx.native-snap, __snapshots__/features/onboarding/pages/OnboardingPage.native.test.tsx.native-snap, patches/react-native-animatable+1.3.3.patch, src/features/onboarding/components/CreditBlock.tsx, src/features/onboarding/components/CreditBlockIcon.tsx, src/features/onboarding/helpers/animationProps.ts, src/features/onboarding/pages/OnboardingPage.tsx, src/libs/react-native-animatable/index.ts, src/ui/components/SectionWithDivider.stories.tsx, src/ui/components/achievements/components/GenericAchievementCard/GenericAchievementCard.tsx, src/ui/components/bars/AnimatedProgressBar.tsx, src/ui/components/snackBar/SnackBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20317
I have:
| iOS              |        |  [Screen Recording iPhone 5s](https://user-images.githubusercontent.com/46637324/216995937-87999987-e1a9-4c49-963a-b10906ca7789.mp4) |
| Android          |        |    [Screen Recording Samsung S10e](https://user-images.githubusercontent.com/46637324/216998464-28348ebc-ef9a-4905-a9b6-cc831205bc1a.mp4)   |
| Desktop - Chrome |        |  Pas d'onboarding en web  |
=> (PC-20317) feat(onboarding): Animate AgeInformation screen

__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclaration.native.test.tsx.native-snap, src/features/profile/pages/Accessibility/AccessibilityDeclaration.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20113
I have:
=> (PC-20113) fix(accessibility): Update declaration

src/shared/forms/controllers/EmailInputController.test.tsx, src/shared/forms/controllers/PasswordInputController.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19620
=> (PC-19620) test(Form): add test for generic controller

.github/workflows/chromatic.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20325
=> (PC-20325) ci(chromatic): add filter on path

package.json, yarn.lock
https://github.com/testing-library/jest-native/releases
I have:
=> (BSR) chore(deps): update jest-native from 4.0.5 to 5.4.1

package.json, yarn.lock
https://github.com/testing-library/jest-dom/releases
I have:
=> (BSR) chore(deps): update jest-dom from 5.16.2 to 5.16.5

src/features/home/fixtures/homepage.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/libs/contentful/fixtures/algoliaModules.fixture.ts, src/libs/contentful/fixtures/showTypes.fixture.ts, src/libs/contentful/types.ts, src/libs/search/parseSearchParameters.native.test.ts, src/libs/search/parseSearchParameters.ts, src/libs/search/utils/buildOfferGenreTypesValues.native.test.ts, src/libs/search/utils/buildOfferGenreTypesValues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18751
I have:
| Platform         | flipper | contetnful |
| showType param              | <img width="527" alt="image" src="https://user-images.githubusercontent.com/89008469/217799399-48b8d93a-51d2-4738-a5ef-b20c1a36c568.png"> | <img width="712" alt="image" src="https://user-images.githubusercontent.com/89008469/217799238-0ba77cbb-6829-4a81-9b6f-da886a332184.png"> |
=> (PC-18751) feat(showType): add a showType contentModel and link it in algolia playlist

src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20191
https://user-images.githubusercontent.com/62058919/216634130-10aa5217-c674-4838-91a5-daa1295b9cc8.mov
I have:
| iOS              |        |      |
| Desktop - Chrome |        |  |
=> (PC-20191) feat(Categories): change the way of CategoriesModal navigation

src/features/offer/components/shareMessagingOffer/MessagingApps.tsx, src/ui/components/ShareMessagingAppOther.stories.tsx, src/ui/components/ShareMessagingAppOther.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19349
I have:
| Phone - Chrome   |<img width="321" alt="image" src="https://user-images.githubusercontent.com/59031393/218050137-a79651f9-1943-41d2-a9a3-b86456d571bd.png">|<img width="319" alt="Capture d’écran 2023-02-10 à 10 05 34" src="https://user-images.githubusercontent.com/59031393/218049858-1840d5fd-8d99-4cc3-a55c-760147bb1cb8.png">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e68 …
=> (PC-19349) feat(messagingApps): fix overlapping touchableOpacities on small screen 

doc/development/e2e.md
=> (BSR) docs(e2e): fix doc

public/.well-known/assetlinks-production.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19959
**Pour la nextmep :** 
Après MEP, vérifier que l'ancien et le nouveau SHA 256 sont bien en production, faire un CURL:
```bash
curl https://passculture.app/.well-known/assetlinks.json | jq '.[1].target.sha256_cert_fingerprints'
```
L'output attendu est:
```json
[
"C4:07:64:27:1C:CC:B3:A6:A9:5D:BE:2E:D8:3E:07:0E:7F:20:CF:0A:FF:3A:AD:97:54:C4:B5:3B:5F:63:EF:9E",
"AC:90:3F:00:92:9A:50:A1:E7:7B:A7:FA:5E:BD:16:7B:55:14:BD:E9:B5:73:8D:0C:08:3A:FE:6D:A8:F2:30:ED"
]
```
I have:
| Tablet - Chrome  |        | …
=> (PC-19959) fix(deeplinks): update production SHA256

__snapshots__/features/auth/pages/signup/QuitSignupModal/QuitSignupModal.native.test.tsx.native-snap, src/features/auth/pages/signup/QuitSignupModal/QuitSignupModal.native.test.tsx, src/features/auth/pages/signup/QuitSignupModal/QuitSignupModal.tsx, src/features/auth/pages/signup/QuitSignupModal/QuitSignupModal.web.test.tsx, src/features/identityCheck/components/modals/QuitIdentityCheckModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12715
I have:
| Desktop - Chrome |  ![Capture d’écran 2023-02-10 à 15 39 38](https://user-images.githubusercontent.com/62059034/218130716-b42a7560-554d-4869-8751-8b51a8745a8e.png) ![Capture d’écran 2023-02-10 à 16 11 38](https://user-images.githubusercontent.com/62059034/218130874-2e3cb3c1-350f-4702-8bd4-f64c9427cc60.png) |   ![Capture d’écran 2023-02-10 à 16 09 39](https://user-images.githubusercontent.com/62059034/218130744-95be9e57-1b63-42e7-a126-1123d5cab191.png) …
=> (PC-12715) feat(ui): add some icon to CTA

__snapshots__/features/FavoriteList/FakeDoor/FavoriteListOfferModal.native.test.tsx.native-snap, __snapshots__/features/identityCheck/components/modals/DMSModal.native.test.tsx.native-snap, __snapshots__/features/identityCheck/components/modals/FastEduconnectConnectionRequestModal.native.test.tsx.native-snap, __snapshots__/features/identityCheck/components/modals/SomeAdviceBeforeIdentityCheckModal.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/phoneValidation/CodeNotReceivedModal.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/phoneValidation/PhoneValidationTipsModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/ErrorApplicationModal/ErrorApplicationModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, __snapshots__/features/offer/components/ReportOfferModal/ReportOfferModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx.native-snap, __snapshots__/features/share/pages/WebShareModal.web.test.tsx.web-snap, __snapshots__/ui/components/modals/AppModal.native.test.tsx.native-snap, src/features/bookOffer/components/BookDateChoice.tsx, src/features/bookOffer/components/BookingEventChoices.native.test.tsx, src/features/bookOffer/components/BookingEventChoices.tsx, src/features/bookOffer/pages/BookingOfferModal.tsx, src/ui/components/modals/AppModal.native.test.tsx, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20361
I have:
| iOS              |<img width="431" alt="Capture d’écran 2023-02-13 à 14 10 45" src="https://user-images.githubusercontent.com/78556024/218469925-aacbdced-10ce-4ef7-bca3-ee1b8417e4b6.png"> <img width="440" alt="Capture d’écran 2023-02-13 à 14 10 53" src="https://user-images.githubusercontent.com/78556024/218469927-1f223321-1428-45f7-9daa-d83bd3bcaa3e.png"> <img width="457" alt="Capture d’écran 2023-02-13 à 14 11 00" src="https://user-images.githubusercontent.com/78556024/218469929-8c56c5f4-2a33-4003-b1e9-ceb91d8cd49a.png">|<img width="435" alt="Capture d’écran 2023-02-13 à 14 14 11" …
=> (PC-20361) feat(booking): add progress bar

__snapshots__/features/bookOffer/components/BookingImpossible.deprecated.native.test.tsx.native-snap, src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookings/components/ArchiveBookingModal.tsx, src/features/bookings/components/CancelBookingModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12715
I have:
| iOS              |   ![Capture d’écran 2023-02-14 à 17 07 01](https://user-images.githubusercontent.com/62059034/218793067-43d0dbb5-7955-466f-8f13-2d19e2f2c18c.png) |   ![Capture d’écran 2023-02-14 à 17 06 28](https://user-images.githubusercontent.com/62059034/218793132-5036f7c8-75f0-444f-9142-c8a0afd83949.png) |
| Desktop - Chrome | ![Capture d’écran 2023-02-14 à 16 43 06](https://user-images.githubusercontent.com/62059034/218793210-7d014fe7-e1de-48d2-b87b-935197c8a371.png)  | …
=> (PC-12715) feat(ui): add some icons to tertiary primary buttons

src/features/home/fixtures/homepage.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/libs/contentful/adapters/modules/helpers/offersModuleMappers.ts, src/libs/contentful/fixtures/algoliaModules.fixture.ts, src/libs/contentful/fixtures/bookTypes.fixture.ts, src/libs/contentful/types.ts, src/libs/search/parseSearchParameters.ts, src/libs/search/utils/buildOfferGenreTypesValues.native.test.ts, src/libs/search/utils/buildOfferGenreTypesValues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18735
I have:
Dans l'appel API fait à Algolia, on retrouve des filtres de types de livres :
=> (PC-18735) feat(algolia): use book type filter from contentful

.github/workflows/chromatic.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20552
I have:
=> (PC-20552) feat(chromatic): disabled chromatic workflow

src/libs/e2e/fetchWithTimeout.ts, src/libs/e2e/getIsE2e.ts, src/libs/e2e/getIsE2e.web.ts, src/tests/setupTests.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20458
I have:
=> (PC-20458) fix(e2e): Add timeout to appium address fetch

__mocks__/fixtures/booking.ts, src/features/auth/components/AuthenticationButton/AuthenticationButton.native.test.tsx, src/features/auth/components/AuthenticationButton/AuthenticationButton.tsx, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/internal/cheatcodes/pages/NavigationSignUp/NavigationSignUp.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx, src/features/offer/components/AuthenticationModal/AuthenticationModal.tsx, src/features/offer/components/AuthenticationModal/fromEnum.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.tsx, src/features/offer/helpers/renderOfferPageTestUtil.tsx, src/features/offer/helpers/useOfferModal/useOfferModal.native.test.tsx, src/features/offer/helpers/useOfferModal/useOfferModal.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/features/onboarding/pages/OnboardingWelcome.tsx, src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19538
I have:
=> (PC-19538) feat(Offer): update redirection after auth modal on booking

src/libs/e2e/fetchWithTimeout.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20458
I have:
=> (PC-20458) fix(e2e): Fix timeout callback

src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20563
I have:
=> (PC-20563) fix(Offer): rewording log for PlaylistVerticalScroll and add offerId params

src/features/home/components/modules/ThematicHighlightModule.native.test.tsx, src/features/home/components/modules/ThematicHighlightModule.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20447
I have:
Sur Firebase, on voit l'event avec les 2 nouveaux params :
=> (PC-20447) feat(thematicHighlight): enrich analytics on press

src/features/home/components/headers/HomeHeader.tsx
=> (PC-20135) fix(HomeHeader): fix eslint error

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/features/identityCheck/components/StepButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19996
I have:
=> (PC-19996) fix(StepButton): add completed state design for touchable component

__snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx.native-snap, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-15884
I have:
https://user-images.githubusercontent.com/22886846/219660969-c3cf96db-1382-429f-92a5-d3ba70b836bf.mov
=> (PC-15884) feat(SetPhoneNumber): update title wording and design

src/features/FavoriteList/FakeDoor/FavoriteListBanner.native.test.tsx, src/features/FavoriteList/FakeDoor/FavoriteListBanner.tsx, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/libs/firebase/firestore/featureFlags/__mocks__/useFeatureFlag.ts, src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20573
I have:
=> (PC-20573) feat(FavList): add feature flag to fake door

src/features/identityCheck/components/countryPicker/constants.ts, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx, src/features/identityCheck/pages/phoneValidation/helpers/isPhoneNumberValid.native.test.ts, src/features/identityCheck/pages/phoneValidation/helpers/isPhoneNumberValid.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17544
I have:
| iOS              | <img width="382" alt="Tu vas recevoir un code de validation pour" src="https://user-images.githubusercontent.com/89008469/219704654-90923b6b-83ed-4171-a6b1-8b9f30b097ea.png">  | <img width="389" alt="Ton numéro de téléphone" src="https://user-images.githubusercontent.com/89008469/219705281-93b3138f-177e-4a66-bb6b-f75f530bde17.png"> |
=> (PC-17544) feat(phoneIndicator): remove NC and PF indicator

__snapshots__/features/culturalSurvey/pages/CulturalSurveyQuestions.native.test.tsx.native-snap, src/features/bookOffer/components/BookDateChoice.tsx, src/features/bookOffer/components/BookingEventChoices.tsx, src/ui/components/bars/ProgressBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20361
I have:
| iOS              |<img width="458" alt="Capture d’écran 2023-02-20 à 09 59 33" src="https://user-images.githubusercontent.com/78556024/220060419-5683e3cb-84c6-40a6-a3a1-a3668770119f.png">|<img width="443" alt="Capture d’écran 2023-02-20 à 09 59 18" src="https://user-images.githubusercontent.com/78556024/220059981-81a54da2-f870-4c2b-b897-3d83c5ade80e.png">|
| Phone - Chrome   |<img width="424" alt="Capture d’écran 2023-02-20 à 09 59 53" src="https://user-images.githubusercontent.com/78556024/220060526-1fa4f178-4e7d-4b9f-bacf-fef473ed41bb.png">|<img width="411" …
=> (PC-20361) fix(booking): change caption and spacer

.github/PULL_REQUEST_TEMPLATE.md
Explication ici : https://www.markdownguide.org/basic-syntax#formatting-the-first-part-of-the-link
=> (BSR) fix(prTemplate): fix link to bug Notion page

__snapshots__/features/identityCheck/pages/profile/SetSchoolType.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/profile/SetStatus.native.test.tsx.native-snap, src/features/identityCheck/pages/profile/SetSchoolType.tsx, src/features/identityCheck/pages/profile/SetStatus.tsx, src/ui/components/radioSelector/RadioSelector.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20562
I have:
| iOS              |        |<img width="441" alt="Capture d’écran 2023-02-20 à 10 04 55" src="https://user-images.githubusercontent.com/62058919/220063962-182ad0b9-21a8-411a-921f-86bd582b128d.png">|
| Desktop - Chrome |        |<img width="1289" alt="Capture d’écran 2023-02-20 à 09 56 23" src="https://user-images.githubusercontent.com/62058919/220059208-92706428-ed6e-49d9-a278-3ebceaa4fe7a.png">|
[1]: …
=> (PC-20562) feat(RadioSelector): use RadioSelector instead of RadioButton in accord with designer

.github/workflows/prod_on_push_deploy_storybook.yml, README.md, doc/storybook.md, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20591
https://pass-culture.github.io/pass-culture-app-native/
I have:
=> (PC-20591) feat(storybook): deploy storybook to github pages

.storybook/main.js, __mocks__/react-native-share.ts, __snapshots__/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, src/features/internal/cheatcodes/pages/DynamicSocials/DynamicSocials.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferBody/OfferBody.web.test.tsx, src/features/offer/components/shareMessagingOffer/InstalledMessagingApps.tsx, src/features/offer/components/shareMessagingOffer/MessagingAppContainer.tsx, src/features/offer/components/shareMessagingOffer/MessagingApps.stories.tsx, src/features/offer/components/shareMessagingOffer/MessagingApps.tsx, src/features/offer/pages/Offer/Offer.web.test.tsx, src/features/share/helpers/useShareOffer.ts, src/features/share/helpers/useShareOfferMessage.test.ts, src/features/share/helpers/useShareOfferMessage.ts, src/ui/components/ShareMessagingApp.tsx, src/ui/components/ShareMessagingAppOther.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19359
I have:
| **iPhone 5s "small device"**     |  [iPhone5s.mp4](https://user-images.githubusercontent.com/46637324/220121884-76c25c23-5eec-41e4-8fc6-57772d00afd2.mp4)  | 
| **iPad**            |    [iPad.mp4](https://user-images.githubusercontent.com/46637324/220121921-bbfaf703-af6a-453c-832d-c88d547a7ced.mp4)    |    
| **Android Pixel XL**             |   [PixelXL.webm](https://user-images.githubusercontent.com/46637324/220122021-b1920e8b-5210-40a1-a0bc-51c4cc156dbd.webm)     |   
| **Web - Chrome**   |   [WebChrome.mov](https://user-images.githubusercontent.com/46637324/220121947-999b77a4-b685-4282-a3e3-dc5a024f1abe.mov)     |       
[1]: …
=> (PC-19359) feat(offer): Add messaging apps buttons to offer

src/features/auth/components/AuthenticationButton/AuthenticationButton.stories.tsx, src/features/bookings/components/ThreeShapesTicket.stories.tsx, src/features/culturalSurvey/components/CulturalSurveyCheckbox.stories.tsx, src/features/identityCheck/components/HeroButtonList.stories.tsx, src/features/profile/components/SectionWithSwitch/SectionWithSwitch.stories.tsx, src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.stories.tsx, src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.stories.tsx, src/features/search/components/CategoryButton/CategoryButton.stories.tsx, src/features/search/components/FilterRow/FilterRow.stories.tsx, src/features/search/components/FilterSwitchWithLabel/FilterSwitchWithLabel.stories.tsx, src/features/search/components/SearchMainInput/SearchMainInput.stories.tsx, src/features/search/components/SelectionLabel/SelectionLabel.stories.tsx, src/ui/components/Banner.stories.tsx, src/ui/components/ModuleBanner/BannerWithBackground.stories.tsx, src/ui/components/ModuleBanner/GenericBanner.stories.tsx
=> (BSR) feat(storybook): reorganize stories

src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx, src/features/offer/components/shareMessagingOffer/InstalledMessagingApps.tsx, src/features/offer/components/shareMessagingOffer/MessagingApps.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19482
I have:
=> (PC-19482) feat(MessagingApps): Add share analytics

src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx, src/features/bookings/pages/BookingDetails/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20316
I have:
=> (PC-20316) fix(booking): not display cancellation message for archived booking

src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/features/offer/components/OfferBody/OfferBody.web.test.tsx, src/features/offer/components/shareMessagingOffer/InstalledMessagingApps.tsx, src/features/offer/helpers/checkInstalledApps/checkInstalledApps.ts, src/features/offer/helpers/checkInstalledApps/checkInstalledApps.web.test.ts, src/features/offer/helpers/checkInstalledApps/checkInstalledApps.web.ts, src/ui/components/ShareMessagingApp.tsx, src/ui/svg/icons/socialNetwork/TwitterRound.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20600
I have:
| Platform         | After | 
| Chrome Web              |      [MediaWeb.mov](https://user-images.githubusercontent.com/46637324/220165604-9c78a3d8-02f9-49ed-9f79-1a3224a4e444.mov)  |  
=> (PC-20600) feat(MessagingApps): Open socials in web

src/features/FavoriteList/FakeDoor/FavoriteListSurveyModal.native.test.tsx, src/features/FavoriteList/FakeDoor/FavoriteListSurveyModal.tsx, src/features/favorites/components/FavoritesResults.native.test.tsx, src/features/favorites/components/FavoritesResults.tsx, src/features/favorites/pages/Favorites.native.test.tsx, src/features/favorites/pages/Favorites.tsx, src/features/favorites/pages/Favorites.web.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.tsx, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20564
I have:
=> (PC-20564) feat(FavoritesList): add disparition rules for fake door

src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19910
I have:
=> (PC-19910) fix(analytics): Pass params without nesting object

src/libs/algolia/fetchAlgolia/fetchOffer.native.test.ts, src/libs/algolia/fetchAlgolia/fetchOfferHits.native.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20410
I have:
=> (PC-20410) fix(tests): Fix mock path

__snapshots__/features/identityCheck/pages/profile/SetSchoolType.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/profile/SetStatus.native.test.tsx.native-snap, src/ui/components/radioSelector/RadioSelector.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20442
I have:
=> (PC-20442) feat(RadioSelector): after UI review add a spacer of 4px between label and description

src/features/offer/components/OfferBody/OfferBody.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20090
I have:
=> (PC-20090) feat(OfferBody): Fix web test

package.json, src/features/home/helpers/selectHomepageEntry.native.test.ts, src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/api/useSimilarOffers.ts, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/helpers/getAlgoliaRecommendParams/getAlgoliaRecommendParams.test.ts, src/features/offer/helpers/getAlgoliaRecommendParams/getAlgoliaRecommendParams.ts, src/features/offer/helpers/getSearchGroupIdFromSubcategoryId/getSearchGroupIdFromSubcategoryId.test.ts, src/features/offer/helpers/getSearchGroupIdFromSubcategoryId/getSearchGroupIdFromSubcategoryId.ts, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildFacetFilters.ts, src/libs/firebase/remoteConfig/__mocks__/remoteConfigProvider.tsx, src/libs/firebase/remoteConfig/remoteConfig.constants.ts, src/libs/firebase/remoteConfig/remoteConfig.services.ts, src/libs/firebase/remoteConfig/remoteConfig.services.web.ts, src/libs/firebase/remoteConfig/remoteConfig.types.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20531
I have:
| iOS              |        |<img width="452" alt="Capture d’écran 2023-02-20 à 15 57 39" src="https://user-images.githubusercontent.com/78556024/220140129-9d5887a3-cea4-43b1-b31a-be13387b0941.png"> <img width="446" alt="Capture d’écran 2023-02-20 à 15 57 32" src="https://user-images.githubusercontent.com/78556024/220140135-146c4ed4-3408-4166-9ff9-d5d405332932.png">|
| Phone - Chrome   |        |<img width="413" alt="Capture d’écran 2023-02-20 à 15 44 53" src="https://user-images.githubusercontent.com/78556024/220139340-657d765c-4cc9-4493-824b-4dbf749a2edd.png"> …
=> (PC-20531) feat(offer): use Algolia Recommend

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/features/identityCheck/pages/Stepper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19952
I have:
| iOS              |![Simulator Screen Shot - iPhone 13 mini - 2023-02-22 at 13 20 12](https://user-images.githubusercontent.com/22886846/220618299-c310487e-293c-4b00-8926-6aba830e6cac.png)|![Simulator Screen Shot - iPhone 13 mini - 2023-02-22 at 12 31 24](https://user-images.githubusercontent.com/22886846/220618204-0130454a-406e-4b73-ac02-590021bf964c.png)|
| Android          |<img width="253" alt="Capture d’écran 2023-02-22 à 13 20 44" src="https://user-images.githubusercontent.com/22886846/220618127-63e58cf8-70ed-498f-9bc1-42f000153a58.png">|<img width="265" alt="Capture d’écran 2023-02-22 à 12 54 40" …
=> (PC-19952) fix(stepper): update margins to fit design

src/features/auth/pages/signup/AccountCreated/AccountCreated.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx, src/libs/campaign/campaignTracker.ts, src/libs/campaign/events.ts, src/libs/campaign/logOpenApp.test.ts, src/libs/campaign/logOpenApp.ts, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/__mocks__/provider.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/provider.ts, src/libs/firebase/analytics/types.ts, src/libs/trackingConsent/useTrackingConsent.native.test.tsx, src/libs/trackingConsent/useTrackingConsent.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20493
I have:
=> (PC-20493) feat(appsFlyer): Track app open and account registration

src/features/auth/components/PasswordSecurityRules.tsx, src/features/auth/pages/signup/SetPassword/SetPassword.native.test.tsx, src/features/auth/pages/signup/SetPassword/SetPassword.tsx, src/features/auth/pages/signup/SetPassword/schema/setPasswordSchema.tsx, src/features/profile/pages/ChangePassword/schema/changePasswordSchema.ts, src/shared/forms/controllers/PasswordInputController.test.tsx, src/shared/forms/controllers/PasswordInputController.tsx, src/shared/forms/schemas/passwordSchema.test.ts, src/shared/forms/schemas/passwordSchema.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17386
I have:
=> (PC-17386) feat(setPassword): react hook-formisation de setPassword

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/features/identityCheck/components/StepButton.tsx, src/features/identityCheck/pages/Stepper.tsx, src/features/search/components/Hit/Hit.tsx, src/ui/components/PassPlaylist.tsx, src/ui/components/SeeMore.tsx, src/ui/components/SeeMoreWithEye.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19849
I have:
| iOS              |        |<img width="298" alt="image" src="https://user-images.githubusercontent.com/68000368/221148837-30305408-9726-4f94-9492-7149a8c6cf62.png">|
| Phone - Chrome   |        |<img width="388" alt="image" src="https://user-images.githubusercontent.com/68000368/221145461-9c318c44-989a-4340-8b04-cca8687c25bd.png">|
| Desktop - Chrome |        |<img width="559" alt="image" src="https://user-images.githubusercontent.com/68000368/221145525-fee785c2-6aa4-495a-aa02-a8985be43c09.png">| …
=> (PC-19849) fix(TouchableLink): type internal touchable link correctly in styledComponent

public/index.html, web/config/webpack.config.js, web/js/chunk-protection.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20716
Ce code est automatiquement minimifié au moment du build
I have:
Au départ nous avons 3 retry avec timeout de 3 seconds:
Après 3 retry, on reset le compteur et on affiche un bouton:
=> (PC-20716) feat(web): add chunk failure protection to index.html

src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.tsx, src/features/offer/pages/Offer/Offer.tsx, src/features/search/components/Hit/Hit.native.test.tsx, src/features/search/components/Hit/Hit.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20680
I have:
=> (PC-20680) feat(offer): add search id in logHasAddedOfferToFavorites call when offer consulted from search

ios/PassCulture.xcodeproj/project.pbxproj, ios/Podfile.lock, package.json, src/features/auth/context/AuthContext.native.test.tsx, src/features/auth/context/AuthContext.tsx, src/libs/amplitude/amplitude.native.test.ts, src/libs/amplitude/amplitude.ts, src/libs/amplitude/types.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19249
I have:
Les user events remontent toujours : 
Les event properties aussi : 
=> (PC-19249) chore(amplitude): use beta amplitude lib instead of the deprecated one

src/features/offer/enums.ts, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20662
I have:
=> (PC-20662) feat(offer): add type playlist when playlist vertical scroll event triggered

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_linter_ts.yml, .github/workflows/dev_on_workflow_tester.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20477
I have:
We push concurrency job to avoid running same job on a dev branch and wait previous job to be finish (it will be canceled) and we had a sonarcloud scanner on native + proxy
=> (PC-20477) feat(ci): Push concurrency to avoid same run on same branch and add sonarcloud

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/features/identityCheck/components/StepButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19849
I have:
| iOS              |        |<img width="301" alt="image" src="https://user-images.githubusercontent.com/68000368/221867000-ca952e6d-687e-4dc7-a0ae-4e8d5626bcf7.png">|
| Phone - Chrome   |        |<img width="378" alt="image" src="https://user-images.githubusercontent.com/68000368/221864143-083e6600-b011-4150-8043-88590639cb56.png">|
| Desktop - Chrome |        |<img width="536" alt="image" src="https://user-images.githubusercontent.com/68000368/221864078-16d7a773-f734-4bdf-aa7f-1a4a7b36739e.png">| …
=> (PC-19849) fix(Stepper): fix design

.github/workflows/e2e-android-app.yml, doc/development/e2e.md, e2e/.env.local.secret.tpl, e2e/config/environment/env.ts, e2e/config/wdio.android.app.conf.ts, e2e/config/wdio.shared.conf.ts, e2e/tests/pc/features/auth/SignupScreens.ts, e2e/tests/pc/helpers/FirstLaunch.ts, e2e/tests/pc/specs/18YearsRegistration.spec.ts, src/libs/e2e/fetchWithTimeout.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20645
I have:
=> (PC-20645) fix(e2e): Fix launch and tests (1/2)

src/features/birthdayNotifications/components/EighteenBirthdayCard.native.test.tsx, src/features/cookies/components/CookiesSettings.native.test.tsx, src/features/cookies/helpers/setMarketingParams.test.ts, src/features/cookies/pages/CookiesDetails.native.test.tsx, src/features/cookies/pages/CookiesDetails.web.test.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/libs/hooks/__tests__/useShowReview.test.tsx
Amélioration de certains tests en prévision de la [mise à jour de Jest](https://passculture.atlassian.net/browse/PC-16305)
=> (BSR) feat(tests): improve some tests

src/features/home/components/headers/HighlightThematicHomeHeader.native.test.tsx, src/features/home/components/headers/HighlightThematicHomeHeader.tsx, src/features/home/fixtures/homepageList.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/adaptHomepageEntries.ts, src/libs/contentful/fixtures/thematicHighlightInfo.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20803
I have:
| Platform         | iphone 13 | iphone 5S |  android | chrome | sans intro |
| :--------------- | :----: | :---: | :---: | :---: | :---: |
| screenshot        |![Simulator Screen Shot - iPhone 13 mini - 2023-03-01 at 16 56 43](https://user-images.githubusercontent.com/22886846/222202558-e328d1d3-8616-4398-999c-6bfb42dc6acb.png)|![Simulator Screen Shot - iPhone 5s - 2023-03-01 at 17 22 26](https://user-images.githubusercontent.com/22886846/222202503-2b7e9da9-6751-46d5-b542-692bce6d8ed0.png)|<img width="292" alt="Capture d’écran 2023-03-01 à 17 27 37" src="https://user-images.githubusercontent.com/22886846/222202282-300a3fb6-9937-4f8e-852d-4ccdc72707c3.png">|<img width="1728" …
=> (PC-20803) feat(highlightHeader): add introduction section

src/features/internal/marketingAndCommunication/pages/UTMParameters.native.test.tsx, src/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx
https://passculture.atlassian.net/browse/PC-20828
https://passculture.atlassian.net/browse/PC-20833
I have:
=> (PC-20828) chore(test): Improve tests (PC-20833) 

src/features/identityCheck/pages/phoneValidation/errors/PhoneValidationTooManyAttempts.web.test.tsx, src/features/offer/pages/Offer/Offer.web.test.tsx, src/features/offer/pages/OfferDescription/OfferDescription.web.test.tsx, src/features/offer/pages/OfferNotFound/OfferNotFound.web.test.tsx
=> (BSR) chore(tests): add some describe to accessiblity tests

package.json, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.web.test.tsx, yarn.lock
=> (BSR) feat(identityCheck): fix flaky accessibility test set phone number

src/features/bookings/pages/BookingDetails/BookingDetails.web.test.tsx, src/features/bookings/pages/BookingNotFound/BookingNotFound.web.test.tsx, src/features/bookings/pages/Bookings/Bookings.web.test.tsx, src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx, src/features/cookies/pages/CookiesConsent.web.test.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.web.test.tsx, src/features/offer/pages/OfferDescription/OfferDescription.web.test.tsx, src/features/offer/pages/OfferNotFound/OfferNotFound.web.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx
=> (BSR) chore(tests): fix somes flaky tests

src/libs/algolia/fetchAlgolia/fetchMultipleVenues.ts, src/libs/firebase/analytics/provider.ts
=> (BSR) chore(sonar): Fix codesmells

web/js/chunk-protection.js
- Corriger Firefox qui a un message d'erreur différent
- @pierrecanthelou pour ton safari, je pense que c'€st que tu n'avais pas de service worker donc tu ne rentres pas dans la condition d'éxécution, j'ai retest en local et safari est ok en cas de cache service worker.
Je pense qu'on peut juste attendre que ce ticket soit livré en prod puisqu'on a bien oserver l'impact sur un navigateur et corriger les messages en local
=> (BSR) fix(Firefox): chunk protection

jest.config.js, src/tests/utils.tsx
Ticket créé : https://passculture.atlassian.net/browse/PC-20887
I have:
=> (BSR) ci(tests): Increase timeout to avoid flakiness

src/features/favorites/components/FavoritesResults.native.test.tsx, src/features/favorites/pages/Favorites.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20823
I have:
=> (PC-20823) refactor(favorites): improve some tests

src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx, src/features/bookings/pages/Bookings/Bookings.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20910
I have:
=> (PC-20910) chore(booking): update BookingDetails and Bookings tests

src/features/favorites/pages/Favorites.native.test.tsx
=> (BSR) chore(favorites): fix favorites snapshots

ios/PassCulture/Info.plist
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20892
I have:
=> (PC-20892) fix(share): Fix sentry error  Unable to open URL sms

src/features/home/api/helpers/buildRecommendationOfferTypesList.test.ts, src/features/home/api/helpers/buildRecommendationOfferTypesList.ts, src/features/home/api/useHomeRecommendedHits.native.test.ts, src/features/home/api/useHomeRecommendedHits.ts, src/features/home/fixtures/homepage.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/modules/adaptRecommendationModule.ts, src/libs/contentful/fixtures/recommendationNatifModule.fixture.ts, src/libs/contentful/types.ts, src/libs/recommendation/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18753
I have:
| Playlist Contentful sans bookType              | <img width="752" alt="image" src="https://user-images.githubusercontent.com/89008469/223161536-7662bdf7-bbac-46ba-a0c1-4979d7ba54c9.png"> | <img width="399" alt="image" src="https://user-images.githubusercontent.com/89008469/223161592-27fd72c5-9a15-48f4-9656-225043719464.png"> |
| Playlist Contentful avec bookType          | <img width="766" alt="image" src="https://user-images.githubusercontent.com/89008469/223161927-60dd4800-fe98-40c9-b252-90d60abab03c.png"> | <img width="411" alt="image" src="https://user-images.githubusercontent.com/89008469/223162105-ed3 …
=> (PC-18753) feat(Contentful): add a bookType filter on recommendation playlist

src/features/home/pages/Home.native.test.tsx, src/features/home/pages/ThematicHome.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20824
=> (PC-20824) refactor(Home): improve some tests

src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/OfferPartialDescription/OfferPartialDescription.native.test.tsx, src/features/offer/helpers/renderOfferPageTestUtil.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20832
=> (PC-20832) refactor(offer): improve tests

src/features/home/api/helpers/buildRecommendationOfferTypesList.native.test.ts, src/features/home/api/helpers/buildRecommendationOfferTypesList.ts, src/features/home/api/useHomeRecommendedHits.native.test.ts, src/features/home/api/useHomeRecommendedHits.ts, src/features/home/fixtures/homepage.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/modules/adaptRecommendationModule.ts, src/libs/contentful/fixtures/algoliaModules.fixture.ts, src/libs/contentful/fixtures/recommendationNatifModule.fixture.ts, src/libs/contentful/fixtures/showTypes.fixture.ts, src/libs/contentful/types.ts, src/libs/recommendation/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18733
I have:
| Contentful Playlist reco avec musicTypes              | <img width="950" alt="image" src="https://user-images.githubusercontent.com/89008469/223495632-9433975d-9ac5-40f5-b974-76585afe66d7.png"> | <img width="591" alt="image" src="https://user-images.githubusercontent.com/89008469/223495454-100d1d7d-62de-4f7a-a4d7-268878882fe1.png"> |
=> (PC-18733) feat(Contentful): add a show types field for recommended playlist

src/features/onboarding/pages/OnboardingWelcome.native.test.tsx, src/features/onboarding/pages/OnboardingWelcome.tsx, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20957
I have:
=> (PC-20957) feat(onboarding): Add tracker on onboarding started

__snapshots__/features/bookOffer/components/BookingDetails.native.test.tsx.native-snap, src/features/bookOffer/components/BookDateChoice.tsx, src/features/bookOffer/components/BookHourChoice.native.test.tsx, src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/BookPricesChoice.native.test.tsx, src/features/bookOffer/components/BookPricesChoice.tsx, src/features/bookOffer/components/BookingDetails.native.test.tsx, src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/BookingEventChoices.native.test.tsx, src/features/bookOffer/components/BookingEventChoices.tsx, src/features/bookOffer/components/BookingOfferModalFooter.native.test.tsx, src/features/bookOffer/components/BookingOfferModalFooter.tsx, src/features/bookOffer/components/BookingOfferModalHeader.native.test.tsx, src/features/bookOffer/components/BookingOfferModalHeader.tsx, src/features/bookOffer/components/Calendar/Calendar.test.tsx, src/features/bookOffer/components/Calendar/Calendar.tsx, src/features/bookOffer/components/Calendar/useMarkedDates.test.ts, src/features/bookOffer/components/HourChoice.tsx, src/features/bookOffer/context/reducer.test.ts, src/features/bookOffer/context/reducer.ts, src/features/bookOffer/fixtures/stocks.ts, src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.test.ts, src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts, src/features/bookOffer/helpers/useModalContent.tsx, src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.tsx, src/ui/components/modals/AppModal.tsx, src/ui/components/radioSelector/RadioSelector.native.test.tsx, src/ui/components/radioSelector/RadioSelector.stories.tsx, src/ui/components/radioSelector/RadioSelector.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20290
I have:
| iOS              |![Capture d’écran 2023-03-07 à 16 33 14](https://user-images.githubusercontent.com/78556024/223469830-273dd7d4-db29-4bc3-beb6-7536469110a7.png) ![Capture d’écran 2023-03-07 à 16 33 21](https://user-images.githubusercontent.com/78556024/223469836-fab63e0d-af4a-4320-b877-74686ea2f24d.png)|![Capture d’écran 2023-03-07 à 16 31 38](https://user-images.githubusercontent.com/78556024/223469484-0d7d9aad-fd96-4739-8f9c-a9b0fc33f156.png) ![Capture d’écran 2023-03-07 à 16 31 47](https://user-images.githubusercontent.com/78556024/223469492-caa82566-a94d-4115-80ad-65094accfe66.png) ![Capture …
=> (PC-20290) feat(booking): prices by categories selection

src/features/favorites/components/Favorite.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20823
I have:
=> (PC-20823) feat(favorites): update Favorite tests

src/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20821
I have:
=> (PC-20821) test(Auth): Improve tests

src/features/offer/pages/Offer/Offer.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20832
I have:
=> (PC-20832) test(Offer): Improve tests

src/features/home/pages/ThematicHome.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20824
I have:
=> (PC-20824) test(ThematicHome): Improve test

src/features/bookOffer/components/BookingImpossible.deprecated.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20826
I have:
=> (PC-20826) feat(bookOffer): update BookingImpossible tests

src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferTile/OfferTile.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx, src/features/offer/pages/Offer/Offer.tsx, src/features/offer/types.ts, src/libs/firebase/analytics/analytics.ts, src/ui/components/PassPlaylist.tsx, src/ui/components/Playlist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20709
I have:
=> (PC-20709) feat(offer): add parameters to similar offer consultation log

__mocks__/fixtures/booking.ts, __snapshots__/features/bookOffer/components/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/bookOffer/components/BookingInformations.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/bookOffer/components/PriceLine.tsx, src/features/bookings/components/BookingPropertiesSection.native.test.tsx, src/features/bookings/components/BookingPropertiesSection.tsx, src/features/bookings/fixtures/bookingsSnap.ts, src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20948
I have:
| Desktop - Chrome |<img width="257" alt="image" src="https://user-images.githubusercontent.com/114916654/223753723-7cb4ed86-eed2-4322-836b-9b4d6195747e.png">|<img width="355" alt="image" src="https://user-images.githubusercontent.com/114916654/223753773-32939fd4-ac64-48cf-8763-af7e233dbe8f.png">|
=> (PC-20948) feat(bookings): add price details on booking detail

src/features/bookOffer/components/BookingDetails.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20826
I have:
=> (PC-20826) test(bookOffer): Improve tests

src/features/auth/pages/login/Login.web.test.tsx, src/features/bookings/pages/Bookings/Bookings.web.test.tsx, src/features/favorites/components/FavoritesResults.web.test.tsx, src/features/search/components/SearchHeader/SearchHeader.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20982
I have:
=> (PC-20982) chore(tests): update some web tests before update jest 27

src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/BookPricesChoice.native.test.tsx, src/features/bookOffer/components/BookPricesChoice.tsx, src/features/bookOffer/fixtures/stocks.ts, src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.test.ts, src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20290
I have:
=> (PC-20290) fix(bookOffer): display only prices from selected hour

src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.test.ts, src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20989
I have:
| iOS              |![Capture d’écran 2023-03-09 à 13 59 56](https://user-images.githubusercontent.com/78556024/224030903-dc4db4e3-1a85-446f-817f-f3f3973e63b5.png)|! ![Capture d’écran 2023-03-09 à 14 01 21](https://user-images.githubusercontent.com/78556024/224031189-334b6ec8-4404-437c-a650-f439a0341eaa.png)[Capture d’écran 2023-03-09 à 13 59 31](https://user-images.githubusercontent.com/78556024/224030833-a03333df-dd12-455f-91d4-89d524f4bfcc.png)|
| …
=> (PC-20989) feat(bookOffer): remove remaining stock quantity when stock is not sold

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20117
I have:
| Platform         | Before |
| Firebase testing              | <img width="894" alt="image" src="https://user-images.githubusercontent.com/89008469/223771280-bbdb0013-4a3d-4ec4-851a-7f18512f1cd7.png"> |
| Firebase staging          | <img width="890" alt="image" src="https://user-images.githubusercontent.com/89008469/223771342-847b49bc-6b69-4fe1-ab8c-bf8ea028c8a3.png"> |
| Firebase production   | <img width="677" alt="image" src="https://user-images.githubusercontent.com/89008469/223771396-06f2790f-a830-4d54-93a8-fe9b2aa996e2.png"> |
=> (PC-20117) feat(Firebase): add wipStepperRetryUbble FF

src/features/FavoriteList/FakeDoor/FavoriteListBanner.native.test.tsx, src/features/bookOffer/helpers/useModalContent.test.tsx, src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.web.test.tsx, src/features/favorites/components/FavoritesResults.native.test.tsx, src/features/favorites/components/FavoritesResults.web.test.tsx, src/features/favorites/pages/Favorites.native.test.tsx, src/features/favorites/pages/Favorites.web.test.tsx, src/features/identityCheck/pages/profile/SetCity.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.web.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.web.test.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx, src/features/offer/pages/Offer/Offer.analytics.native.test.tsx, src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx, src/features/profile/pages/Profile.native.test.tsx, src/libs/firebase/firestore/featureFlags/__mocks__/useFeatureFlag.ts, src/libs/hooks/__tests__/useShowReview.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20988
I have:
=> (PC-20988) fix(Tests): flacky test with firestore

src/features/offer/pages/Offer/Offer.native.test.tsx
=> (BSR) fix(tests): Fix FF mock

src/features/bookOffer/components/AlreadyBooked.native.test.tsx, src/features/bookOffer/components/AlreadyBooked.tsx, src/features/bookOffer/components/BookingImpossible.native.test.tsx, src/features/bookOffer/components/BookingImpossible.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21013
I have:
| iOS              |<img width="464" alt="Capture d’écran 2023-03-10 à 12 32 25" src="https://user-images.githubusercontent.com/78556024/224326453-8380627c-a382-4d5b-bb1b-806e5e0b7f6d.png"> <img width="449" alt="Capture d’écran 2023-03-10 à 12 53 44" src="https://user-images.githubusercontent.com/78556024/224326516-ae1009c6-c4a6-4dc7-b92b-52c4dcc270b3.png">|<img width="447" alt="Capture d’écran 2023-03-10 à 12 32 02" src="https://user-images.githubusercontent.com/78556024/224326670-b44668ce-e78b-47a8-affe-5844a239eed4.png"> <img width="451" alt="Capture d’écran 2023-03-10 à 12 54 23" …
=> (PC-21013) fix(bookOffer): remove step & footer on already booked modal

__snapshots__/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, src/features/bookings/components/BookingPropertiesSection.tsx, src/features/bookings/components/Ticket/getTickets.tsx, src/features/home/components/HomeBodyPlaceholder.tsx, src/features/identityCheck/pages/identification/dms/DMSIntroduction.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/onboarding/pages/AgeInformation.tsx, src/features/onboarding/pages/AgeSelection.tsx, src/features/search/components/Highlight/Highlight.tsx, src/ui/svg/icons/BicolorProfile.tsx
=> (BSR) chore(sonar): fix some sonar issues

__snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap, src/features/profile/pages/PersonalData/PersonalData.native.test.tsx, src/features/profile/pages/PersonalData/PersonalData.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20923
I have:
| iOS              |        |     ![Simulator Screen Shot - iPhone 13 - 2023-03-10 at 11 08 58](https://user-images.githubusercontent.com/46637324/224325292-b6cde3bd-ff22-4b2d-9479-89536bf0bbcc.png)  |
| Android          |        |      ![Screenshot_20230310_111010](https://user-images.githubusercontent.com/46637324/224325383-e2dd5488-f8fa-4dd3-b9c3-0d6f13189f21.png) |
| Desktop - Chrome |        |    <img width="1440" alt="Capture d’écran 2023-03-10 à 11 09 09" src="https://user-images.githubusercontent.com/46637324/224325347-007a8f35-50f2-4e69-99bd-cb76727cc913.png">   |
[1]: …
=> (PC-20923) feat(PersonalData): Add section to comply with GDPR

android/app/src/main/res/xml/network_security_config.xml
Cf.: https://stackoverflow.com/questions/67182769/network-security-config-results-in-react-native-app-not-connecting-to-metro-serv
=> (BSR) fix(android): fix connection to Metro in local

__snapshots__/features/offer/components/OfferBody/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/venue/components/VenueBody/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, src/ui/components/accessibility/AccessibilityAtom.native.test.tsx, src/ui/components/accessibility/AccessibilityAtom.tsx, src/ui/components/accessibility/AccessibilityBlock.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20693
I have:
| iOS              |<img width="479" alt="image (67)" src="https://user-images.githubusercontent.com/62058919/222149260-b4cb7153-7c76-4ae3-a8c2-35cc24e727f1.png">|<img width="437" alt="Capture d’écran 2023-03-01 à 14 09 53" src="https://user-images.githubusercontent.com/62058919/222148685-4184189a-7c2d-4c1a-abee-324a20a8c6a6.png">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a7 …
=> (PC-20693) fix(AccessibilityBlock): fix UI accessibility info block

src/api/apiHelpers.ts
Première partie du ticket : https://passculture.atlassian.net/browse/PC-17698
I have:
=> (PC-17698) chore(apiHelpers): Log detailed error to sentry

.github/workflows/dev_on_workflow_environment_deploy.yml, .github/workflows/dev_on_workflow_install.yml, .github/workflows/dev_on_workflow_tester.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21010
I have:
=> (PC-21010) fix(ci): fix label for selfhosted runner

src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/helpers/useRotatingText.test.ts, src/features/bookOffer/helpers/useRotatingText.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20949
I have:
https://user-images.githubusercontent.com/114916654/224373502-d4651358-a232-4fd6-88aa-35e13273f926.mov
=> (PC-20949) feat(bookOffer): add loader when booking

src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21003
I have:
=> (PC-21003) fix(search): add possibility nativeCategory not present in nativeCategories

src/features/bookOffer/components/BookDateChoice.tsx, src/features/bookOffer/components/BookHourChoice.native.test.tsx, src/features/bookOffer/components/BookHourChoice.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21154
I have:
| iOS              |<img width="485" alt="Capture d’écran 2023-03-16 à 12 02 53" src="https://user-images.githubusercontent.com/78556024/225597946-87687089-7749-47fe-9097-bbc3e1854cd0.png"> <img width="474" alt="Capture d’écran 2023-03-16 à 12 02 48" src="https://user-images.githubusercontent.com/78556024/225597952-de3c830e-b276-433c-bb9f-e03cf8baad7f.png"> <img width="522" alt="Capture d’écran 2023-03-16 à 12 02 40" src="https://user-images.githubusercontent.com/78556024/225597955-10c2e39b-9500-442a-85e4-adc247f942b0.png">|<img width="457" alt="Capture d’écran 2023-03-16 à 12 01 11" …
=> (PC-21154) fix(bookOffer): stock preselection only one price with category

README.md
=> (BSR) chore(readme): update some informations in README.md

src/features/profile/pages/PersonalData/PersonalData.native.test.tsx, src/features/profile/pages/PersonalData/PersonalData.tsx, src/features/profile/pages/PersonalData/PersonalData.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21083
I have:
| Desktop - Chrome |  <img width="1079" alt="Capture d’écran 2023-03-16 à 11 02 59" src="https://user-images.githubusercontent.com/62059034/225590619-c79a7b24-34ac-488a-990d-94144de3c4c4.png">      |   <img width="1080" alt="Capture d’écran 2023-03-16 à 11 33 44" src="https://user-images.githubusercontent.com/62059034/225590777-fdb9f381-eaed-4661-9c7b-acd791207c19.png"> |
[1]: …
=> (PC-21083) feat(profile): hide phone number if no value in PersonnalData

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21031
I have:
=> (PC-21031) chore(whyDidYouRender): upgrade to v7

src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.native.test.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.native.test.tsx, src/features/auth/pages/suspendedAccount/AccountReactivationSuccess/AccountReactivationSuccess.native.test.tsx, src/features/auth/pages/suspendedAccount/FraudulentAccount/FraudulentAccount.native.test.tsx, src/features/auth/pages/suspendedAccount/SuspendedAccount/SuspendedAccount.native.test.tsx, src/features/auth/pages/suspendedAccount/SuspensionScreen/SuspensionScreen.native.test.tsx, src/features/bookings/components/TicketBody/EmailSent/EmailSent.native.test.tsx, src/features/favorites/components/NotConnectedFavorites.native.test.tsx, src/features/identityCheck/components/modals/QuitIdentityCheckModal.native.test.tsx, src/features/identityCheck/pages/confirmation/IdentityCheckHonor.native.test.tsx, src/features/identityCheck/pages/identification/ubble/IdentityCheckPending.native.test.tsx, src/features/identityCheck/pages/profile/SetCity.native.test.tsx, src/features/identityCheck/pages/profile/SetName.native.test.tsx
=> (BSR) chore(tests): remove wait for expect for some tests - part 1

eslint-custom-rules/__tests__/nbsp-in-text.test.js, src/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx, src/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx, src/features/culturalSurvey/pages/CulturalSurveyQuestions.native.test.tsx, src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx, src/ui/components/inputs/DateInput/DateInput.web.test.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.web.test.tsx, web/config/webpack.config.js
=> (BSR) chore(todo): update some TODO 

src/libs/algolia/fetchAlgolia/fetchVenues/fetchVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20417
use the adaptors previously created into fetchVenues
=> (PC-20417) refactor(fetchVenues): use adaptors in fetchVenues

src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx, src/features/profile/pages/DeleteProfile/DeleteProfileSuccess.native.test.tsx, src/features/share/pages/ShareAppModal.native.test.tsx, src/libs/firebase/remoteConfig/RemoteConfigProvider.native.test.tsx, src/libs/share/share.native.test.ts, src/ui/components/__tests__/AnimatedIcon.native.test.tsx, src/ui/components/__tests__/SocialNetworkCard.test.tsx, src/ui/components/achievements/components/GenericAchievement/GenericAchievement.native.test.tsx, src/ui/components/achievements/components/GenericAchievementCard/GenericAchievementCard.native.test.tsx
=> (BSR) chore(tests): remove wait for expect for some tests - part 3

src/features/identityCheck/pages/profile/SetStatus.native.test.tsx, src/features/navigation/RootNavigator/useInitialScreenConfig.native.test.tsx, src/features/navigation/helpers/openUrl.native.test.ts, src/features/notifications/pages/AskNotificationsModal.native.test.tsx, src/features/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx, src/features/offer/components/OfferIconCaptions/OfferIconCaptions.native.test.tsx, src/features/offer/components/ReportOfferOtherReason/ReportOfferOtherReason.native.test.tsx, src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.native.test.tsx, src/features/profile/pages/AfterChangeEmailValidationBuffer/AfterChangeEmailValidationBuffer.native.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmailExpiredLink.native.test.tsx
=> (BSR) chore(tests): remove wait for expect for some tests - part 2

src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx, src/ui/components/buttons/RoundedButton.native.test.tsx, src/ui/components/buttons/externalLink/ExternalLink.native.test.tsx, src/ui/components/buttons/externalLink/__tests__/ExternalLink.web.test.tsx, src/ui/components/contact/__tests__/helpers.test.ts, src/ui/components/touchableLink/ExternalTouchableLink.test.tsx, src/ui/components/touchableLink/InternalTouchableLink.test.tsx, src/ui/components/touchableLink/TouchableLink.test.tsx
=> (BSR) chore(tests): remove wait for expect for some tests - part 4

doc/standards/testStrategy.deprecated.md, package.json, src/features/auth/helpers/useBeneficiaryValidationNavigation.test.ts, src/features/auth/pages/suspendedAccount/FraudulentAccount/FraudulentAccount.native.test.tsx, src/features/cookies/helpers/useCookies.test.ts, src/features/identityCheck/components/modals/QuitIdentityCheckModal.web.test.tsx, src/features/identityCheck/pages/phoneValidation/errors/PhoneValidationTooManyAttempts.web.test.tsx, src/features/navigation/RootNavigator/linking/__tests__/getStateFromPath.test.ts, src/features/profile/pages/Profile.native.test.tsx, src/libs/itinerary/useItinerary.native.test.ts, src/libs/react-query/tests/usePersistQuery.native.test.tsx, yarn.lock
=> (BSR) chore(tests): remove wait for expect for some tests - part 5

src/api/gen/api.ts, src/features/home/api/useHomeBanner.ts, src/features/home/components/banners/GeolocationBanner.native.test.tsx, src/features/home/components/banners/GeolocationBanner.tsx, src/features/home/components/headers/HomeHeader.native.test.tsx, src/features/home/components/headers/HomeHeader.tsx, swagger_codegen/gen_templates/api.mustache
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20795
I have:
=> (PC-20795) feat(home): show geoloc banner from backend response

src/libs/firebase/analytics/events.ts
=> (BSR) refactor(anaylitcs): Rename event

src/libs/hooks/__tests__/useShowReview.native.test.tsx, src/libs/hooks/__tests__/useShowReview.web.test.tsx, src/libs/hooks/useShowReview.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21144
I have:
=> (PC-21144) test(useShowReview): Add tests for web

ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21258
I have:
=> (PC-21258) chore(deps): Update dependency react-native-permissions to v3.8.0

src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/api/useSimilarOffers.ts, src/features/offer/types.ts
Co-authored-by: YassinL <YassinL@users.noreply.github.com>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21205
I have:
=> (PC-21205) feat(offer): add params api log in similar offers call

src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/helpers/useRotatingText.test.ts, src/features/bookOffer/helpers/useRotatingText.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21297
I have:
=> (PC-21297) fix(bookOffer): messages start changing once mutation started

.env.integration, .env.production, .env.staging, .env.testing
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20784
I have:
=> (PC-20784) chore(env): update reco api URLs

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/features/identityCheck/components/StepButton.tsx, src/ui/components/ModuleBanner/BannerWithBackground.tsx, src/ui/components/ModuleBanner/GenericBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20978
I have:
| iOS              | <img width="511" alt="image" src="https://user-images.githubusercontent.com/26742386/227559965-485a88de-a57c-4159-b793-89ff261cd2a4.png"> | <img width="511" alt="image" src="https://user-images.githubusercontent.com/26742386/227559869-8a63f66c-001b-42f4-8fc0-93109e17cc9c.png"> |
| Phone - Chrome   | <img width="377" alt="image" src="https://user-images.githubusercontent.com/26742386/227560240-6a398053-6709-4e3f-8256-0b7ac418c912.png"> | <img width="377" alt="image" src="https://user-images.githubusercontent.com/26742386/227560491-6c20173d-0c7f-42b3-b8fd-a43d6fa8618b.png"> |
| Desktop - …
=> (PC-20978) feat(activation): upgrade stepper design

src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildFacetFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21371
I have:
=> (PC-21371) fix(algolia): add sentry context to help debug

src/libs/firebase/analytics/__tests__/utils.test.ts, src/libs/firebase/analytics/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21372
I have:
=> (PC-21372) fix(search): customize searchLocationFilter param when location type is PLACE or VENUE

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21033
I have:
=> (PC-21033) chore(deps): update dependency react-device-detect to v2.2.3

.gitignore, lighthouserc.yml, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20650
I have:
=> (PC-20650) perf(web): Add lighthouse for manual performance test

.env.integration, .env.staging, .env.testing
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20784
I have:
=> (PC-20784) fix(reco): fix url in env files

src/features/search/api/useSearchResults/useSearchResults.test.ts, src/features/search/api/useSearchResults/useSearchResults.ts, src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.native.test.tsx, src/features/search/components/SearchAutocompleteItem/SearchAutocompleteItem.tsx, src/features/search/components/SearchBox/SearchBox.native.test.tsx, src/features/search/components/SearchBox/SearchBox.tsx, src/features/search/components/SearchList/SearchList.native.test.tsx, src/features/search/components/SearchList/SearchList.tsx, src/features/search/components/SearchList/SearchList.web.tsx, src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.test.ts, src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.ts, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.tsx, src/features/search/types.ts, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21196
I have:
=> (PC-21196) feat(search): track search results number to perform search log

yarn.lock
Utilisation de la lib yarn-audit-fix pour fix quelques vulnérabilités
https://github.com/antongolub/yarn-audit-fix
```npx yarn-audit-fix```
I have:
| vulnérabilités  |  <img width="389" alt="Capture d’écran 2023-03-27 à 17 51 35" src="https://user-images.githubusercontent.com/62059034/227997598-d8950c5c-0914-46dc-8f8c-337ed2dab553.png"> | <img width="378" alt="Capture d’écran 2023-03-27 à 17 50 08" src="https://user-images.githubusercontent.com/62059034/227997726-660a3680-e390-4ab5-8528-38a8a357f854.png"> |
=> (BSR) chore(deps): fix some vulnerability with yarn audit fix

src/libs/monitoring/__tests__/services.native.test.ts, src/libs/monitoring/config.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21310
to add screenshots to sentry https://docs.sentry.io/platforms/react-native/enriching-events/screenshots/
I have:
=> (PC-21310) feat(sentry): add screenshots to sentry

.github/workflows/dev_on_push_workflow_chromatic.yml, .github/workflows/dev_on_push_workflow_main.yml, src/features/offer/components/shareMessagingOffer/MessagingApps.stories.tsx, src/ui/components/ShareMessagingApp.stories.tsx, src/ui/components/ShareMessagingAppOther.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21324
I have:
=> (PC-21438) feat(chromatic): enable chromatic on push

.github/dependabot.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18420
Doc dependabot utilisée : 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers
=> (PC-18420) chore(security): add reviewers for dependabot PR

doc/standards/testStrategy/FullPageTest.md
Complete docs about our test strategy
=> (BSR) docs(tests): update test strategy with render function part

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_check_folder_change.yml, .github/workflows/dev_on_workflow_install.yml, .github/workflows/dev_on_workflow_tester.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19092
* Rsync build web and push to bucket
* Build proxy if a change has been detected on directory "server"
For the moment rysnc and build proxy are commented, it will be uncommented in a futur PR
=> (PC-19092) feat(ci): Add deploy web and deploy web proxy

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21504
I have:
=> (PC-21504) chore(deps): Update dependency react-query to v3.39.3

.github/workflows/dev_on_push_workflow_chromatic.yml, .github/workflows/dev_on_workflow_linter_ts.yml, src/features/offer/components/BottomBanner/BottomBanner.stories.tsx
=> (BSR) fix(chromatic): fix turboSnap

.vscode/todo-mob.code-snippets
=> (BSR) chore(vscode): update url mobtime in todo-mob.code-snippets

src/api/gen/api.ts, src/libs/parsers/culturalSurveyType.ts, src/libs/parsers/tests/culturalSurveyType.test.ts
=> Fix: wtf i can push on master

.github/workflows/dev_on_pull_request_reassure.yml
=> (PC-20631) fix(reassure): Run script only once

.github/workflows/dev_on_schedule_lighthouse.yml, lighthouserc.yml, package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21429
[Workflow d'exemple](https://github.com/pass-culture/pass-culture-app-native/actions/runs/4627464915) : job qui fail parce que le score est inférieur à notre threshold et artifact disponible avec le rapport lighthouse.
I have:
=> (PC-21429) feat(lighthouse): Run performance score daily

src/features/search/components/Hit/Hit.native.test.tsx, src/features/search/components/Hit/Hit.tsx, src/libs/firebase/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-211297
I have:
=> (PC-21197) feat(Hit): add a new params offer_display_index to ConsultOffer tracker

src/features/home/api/useHomeBanner.ts, src/features/home/components/headers/HomeHeader.tsx, src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21500
I have:
Bannière d'activation avant :
https://user-images.githubusercontent.com/22886846/230587846-f51459d6-b74a-4d4c-8534-fae3568d1904.mov
Bannière d'activation après :
https://user-images.githubusercontent.com/22886846/230587869-6983efaf-3b6a-4eb7-814c-34e4abebfb4a.mov
Bannière de géoloc avant : 
https://user-images.githubusercontent.com/22886846/230588003-d9ca2f05-c96d-48df-bf27-36c0cb690ca6.mov
Bannière de géoloc après :
https://user-images.githubusercontent.com/22886846/230589422-f5ad27d4-d48f-426c-8780-7c27640c8a33.mov
=> (PC-21500) fix(home): fix banner persistency

src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.native.test.tsx, src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/venue/pages/Venue/Venue.native.test.tsx, src/features/venue/pages/Venue/Venue.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21405
I have:
=> (PC-21405) feat(venue): log consult venue when venue consulted from deeplink

src/features/identityCheck/components/StepButton.stories.tsx, src/features/identityCheck/components/StepButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20928
I have:
| Phone - Chrome   | <img width="398" alt="image" src="https://user-images.githubusercontent.com/26742386/231177621-78c4735c-bf26-4a3f-a901-57f755e8f694.png"> | <img width="394" alt="image" src="https://user-images.githubusercontent.com/26742386/231176785-d99efc95-1083-419f-9bb9-055c15ed2b96.png"> |
=> (PC-20928) fix(stepper): fix stepper button design

__snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, src/features/offer/components/OfferBody/OfferBody.tsx, src/libs/parsers/formatDates.ts, src/libs/parsers/tests/formatDates.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21600
I have:
| Desktop - Chrome |        |<img width="392" alt="Capture d’écran 2023-04-12 à 12 23 23" src="https://user-images.githubusercontent.com/62058919/231430252-51c311e6-4f75-41ef-80e9-61174c11b2e7.png"><img width="390" alt="Capture d’écran 2023-04-12 à 16 49 10" src="https://user-images.githubusercontent.com/62058919/231496618-73795111-e5b3-4011-a8a5-4d6daf20d0f1.png"><img width="392" alt="Capture d’écran 2023-04-12 à 16 53 19" …
=> (PC-21600) fix(formatDates): adjust the date to fit with different scenario

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21710
I have:
[Link to verify the presence of the feature flag](https://console.firebase.google.com/u/0/project/passculture-native/firestore/data/~2FfeatureFlags~2Ftesting) 
=> (PC-21710) feat(offer): add WIP_ENABLE_MULTIVENUE_OFFER feature flag

src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21711
I have:
| iOS              |![Capture d’écran 2023-04-14 à 11 41 54](https://user-images.githubusercontent.com/78556024/232009210-d90c1e53-f317-4a0f-922d-2b73b9e7cc20.png)|![Capture d’écran 2023-04-14 à 11 55 58](https://user-images.githubusercontent.com/78556024/232013660-90be2aa6-1277-4b26-8a6b-67c52e2989e2.png)|
| Phone - Chrome   |<img width="416" alt="Capture d’écran 2023-04-14 à 11 41 34" src="https://user-images.githubusercontent.com/78556024/232009239-326ac5e5-33ce-437a-b7b6-b3f95fe5dd39.png">|<img width="466" alt="Capture d’écran 2023-04-14 à 11 58 28" …
=> (PC-21711) feat(offer): add CTA other venues available

src/features/offer/components/DistanceTag/DistanceTag.stories.tsx, src/features/offer/components/DistanceTag/DistanceTag.tsx, src/features/offer/components/VenueCard/VenueCard.native.test.tsx, src/features/offer/components/VenueCard/VenueCard.stories.tsx, src/features/offer/components/VenueCard/VenueCard.tsx, src/features/offer/components/VenueDetails/VenueDetails.native.test.tsx, src/features/offer/components/VenueDetails/VenueDetails.stories.tsx, src/features/offer/components/VenueDetails/VenueDetails.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.native.test.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.stories.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21735
I have:
_With image_:
_Without image, with venue type_:
_Hover_:
_Focus_:
_Hover_:
_Focus_:
=> (PC-21735) feat(offer): create venue components

__snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap, __snapshots__/features/home/pages/Home.native.test.tsx.native-snap, __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap, src/features/home/pages/GenericHome.native.test.tsx, src/features/home/pages/GenericHome.tsx, src/ui/components/Spinner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21656
I have:
| iOS              |        |   [ios.mp4](https://user-images.githubusercontent.com/46637324/231802181-8c596b65-1c05-43e0-a792-e3a6d57f1542.mp4) |
| Android          |        |    [android.webm](https://user-images.githubusercontent.com/46637324/231802377-4fd515d5-164f-4806-989d-eee2bed6e58d.webm)   |
=> (PC-21656) feat(home): Fix spinner display for progressive loading

public/index.html
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21421
I have:
=> (PC-21421) feat(webapp): Add commit hash to head

src/features/offer/components/shareMessagingOffer/InstalledMessagingApps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21557
I have:
| Android          |        |   https://user-images.githubusercontent.com/46637324/231972108-342427cb-1620-4a9c-a1ec-f817f7f819db.mp4    |
=> (PC-21557) feat(share): Open SMS app with prefilled message

src/features/search/api/useSearchResults/useSearchResults.test.ts, src/features/search/api/useSearchResults/useSearchResults.ts, src/features/search/components/SearchBox/SearchBox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21628
I have:
=> (PC-21628) fix(search): previous button handling

doc/development/e2e.md, e2e/tests/pc/helpers/NativeAlert.ts, e2e/tests/pc/helpers/utils/selector.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21700
I have:
=> (PC-21700) feat(e2e): add findAll selector

src/features/offer/components/VenueCard/VenueCard.native.test.tsx, src/features/offer/components/VenueCard/VenueCard.stories.tsx, src/features/offer/components/VenueDetails/VenueDetails.native.test.tsx, src/features/offer/components/VenueDetails/VenueDetails.stories.tsx, src/features/offer/components/VenueDetails/VenueDetails.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.native.test.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21812
I have:
| Desktop - Chrome |<img width="344" alt="CleanShot 2023-04-17 at 17 19 54@2x" src="https://user-images.githubusercontent.com/114916654/232533096-0adff0e2-de28-4619-8d99-4be4324d8764.png"> | <img width="343" alt="CleanShot 2023-04-17 at 17 18 32@2x" src="https://user-images.githubusercontent.com/114916654/232532872-e7e6bdf8-4792-4573-85cd-fae8283601b9.png">|
[1]: …
=> (PC-21812) feat(offer): remove useless image

src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20931
PR to fix web accessibility tests
=> (PC-20931) feat(server): add a msw mock for the new stepper route

src/libs/campaign/logOpenApp.test.ts, src/libs/campaign/logOpenApp.ts, src/libs/firebase/analytics/__mocks__/analytics.ts, src/libs/firebase/analytics/analytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21793
I have:
=> (PC-21793) feat(tracking): Add firebase tracker for app opening

src/libs/contentful/adapters/adaptHomepageModules.native.test.ts, src/libs/contentful/adapters/adaptHomepageModules.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21362
I have:
=> (PC-21362) feat(contentful): add a safe net to the adapters

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/home/helpers/selectHomepageEntry.native.test.ts, src/features/identityCheck/api/useGetStepperInfo.native.test.ts, src/features/identityCheck/api/useGetStepperInfo.ts, src/features/identityCheck/pages/Stepper.tsx, src/features/identityCheck/pages/helpers/computeIdentificationMethod.native.test.ts, src/features/identityCheck/pages/helpers/computeIdentificationMethod.ts, src/features/identityCheck/pages/helpers/stepperInfo.fixture.ts, src/features/identityCheck/pages/helpers/useStepperInfo.native.test.tsx, src/features/identityCheck/pages/helpers/useStepperInfo.tsx, src/libs/firebase/remoteConfig/remoteConfig.constants.ts, src/libs/firebase/remoteConfig/remoteConfig.services.ts, src/libs/firebase/remoteConfig/remoteConfig.services.web.ts, src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21347
I have:
Vidéo : https://user-images.githubusercontent.com/47600889/232517151-79f90817-e6ae-4e71-9759-d4f300e4e69c.mp4
=> (PC-21347) feat(identityCheck): fork navigation + setup AB testing

android/app/src/main/AndroidManifest.xml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21557
I have:
Test avec Messages (normal), Google Messages, Signal, Messenger
[Video_Demo.mp4](https://user-images.githubusercontent.com/46637324/232976794-374f976d-7cbe-4513-9473-373af972302f.mp4)
=> (PC-21557) feat(share): Support others messaging apps

src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/VenueCard/VenueCard.tsx, src/features/offer/components/VenueDetails/VenueDetails.tsx, src/features/offer/components/VenueSection/VenueSection.native.test.tsx, src/features/offer/components/VenueSection/VenueSection.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.native.test.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.stories.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.web.test.tsx, src/features/offer/helpers/getVenueSectionTitle/getVenueSectionTitle.test.ts, src/features/offer/helpers/getVenueSectionTitle/getVenueSectionTitle.ts, src/libs/address/__mocks__/useFormatFullAddress.ts, src/libs/address/__tests__/useFormatFullAddress.test.ts, src/libs/address/useFormatFullAddress.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21779
I have:
| iOS              |<img width="448" alt="Capture d’écran 2023-04-18 à 12 34 08" src="https://user-images.githubusercontent.com/78556024/232751579-bedaa4d9-8ec4-4622-8cfd-e8d8c1b5ee35.png"> <img width="449" alt="Capture d’écran 2023-04-18 à 12 33 40" src="https://user-images.githubusercontent.com/78556024/232751586-2b2e38a0-e818-4e25-9e87-44c7b7506e2e.png"> <img width="435" alt="Capture d’écran 2023-04-18 à 12 33 26" src="https://user-images.githubusercontent.com/78556024/232751588-983ae16f-2f08-46f7-8970-add98a7e58f7.png">|<img width="506" alt="Capture d’écran 2023-04-18 à 12 31 45" …
=> (PC-21779) feat(offer): new venue section

__snapshots__/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.native.test.tsx.native-snap, src/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.native.test.tsx, src/features/auth/pages/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.tsx
=> (BSR) refactor(Tests): clean ResetPasswordEmailSent tests

src/api/apiHelpers.test.ts, src/api/apiHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17698
I have:
=> (PC-17698) feat(api): complete needs authentication error for Sentry

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21724
I have:
=> (PC-21724) feat(trustedDevice): Add feature flag

__snapshots__/features/identityCheck/pages/profile/SetAddress.web.test.tsx.web-snap, __snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap, src/features/search/components/BodySearch/BodySearch.native.test.tsx, src/features/search/components/BodySearch/BodySearch.tsx, src/features/search/components/SearchAutocomplete/SearchAutocomplete.native.test.tsx, src/features/search/fixtures/algolia.ts, src/features/search/pages/Search/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21625
I have:
=> (PC-21625) refactor(search): export bodysearch component

.github/workflows/dev_on_schedule_e2e_browser.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21679
I have:
=> (PC-21679) feat(e2e): run e2e workflow automatically in CI

src/features/identityCheck/pages/identification/IdentificationForkEduconnect.native.test.tsx, src/features/identityCheck/pages/identification/IdentificationForkEduconnect.tsx, src/features/identityCheck/pages/identification/IdentificationForkUbble.native.test.tsx, src/features/identityCheck/pages/identification/IdentificationForkUbble.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21562
I have:
=> (PC-21562) feat(identification): add amplitude tracking for the fork screens

.circleci/config.yml
This reverts commit 43a858403406df8615c1d168386478cacb472b99.
I have:
=> Revert "(BSR) chore(circleCI): update Xcode version (#4682)"

src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/api/useSimilarOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21629
I have:
=> (PC-21629) feat(offer): decrease similar offers API call

src/features/identityCheck/pages/helpers/computeIdentificationMethod.native.test.ts, src/features/identityCheck/pages/helpers/computeIdentificationMethod.ts, src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnect.native.test.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnect.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnect.web.test.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckEduConnectForm.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.native.test.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-19098
I have:
https://user-images.githubusercontent.com/47600889/233972558-2ed38ed9-34e6-4490-bfc2-6d6542e731d1.mp4
=> (PC-19098) fix(identification): educonnect navigation flow from the fork

src/features/search/api/useSearchResults/useSearchResults.ts, src/features/venue/api/useVenueOffers.ts, src/libs/algolia/fetchAlgolia/fetchOffers/adaptAlgoliaHits.ts, src/libs/algolia/fetchAlgolia/fetchOffers/fetchOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21956
I have:
=> (PC-21956) fix(search): fix offer images

src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildGeolocationParameter.test.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildGeolocationParameter.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/tests/buildGeolocationParameter.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21911
I have:
=> (PC-21911) test(buildGeolocationParameter): add some tests for buildGeolocationParameter to increase the coverage

jest/jest.setup.ts, src/features/profile/helpers/TrustedDevices/useDeviceInfo.test.ts, src/features/profile/helpers/TrustedDevices/useDeviceInfos.ts, src/libs/react-native-device-info/__mocks__/getUniqueId.ts, src/libs/react-native-device-info/__mocks__/getUniqueId.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21835
I have:
=> (PC-21835) feat(TrustedDevice): add device info hook

doc/installation/Android.md, doc/installation/iOS.md, doc/installation/setup.md
Pas de JIRA ticket
Update la doc de setup.md, Android.md et iOS.md
I have:
=> (BSR) update doc for installation

src/features/auth/context/SettingsContext.tsx, src/features/search/components/SearchBox/SearchBox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21976
I have:
=> (PC-21976) fix(search): fix search bar focus

server/src/index.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21961
I have:
=> (PC-21961) fix(proxy): Fix proxy tests

doc/development/e2e.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21695
I have:
=> (PC-21695) feat(e2e): update e2e doc

src/features/profile/components/VerticalStepper/VerticalStepper.native.test.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.stories.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.tsx, src/features/profile/components/VerticalStepper/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21988
I have:
=> (PC-21988) feat(profile): add stepper component

src/features/profile/components/Step/Step.native.test.tsx, src/features/profile/components/Step/Step.stories.tsx, src/features/profile/components/Step/Step.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.stories.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.tsx, src/features/profile/components/VerticalStepper/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22000
I have:
=> (PC-22000) feat(profile): add step component

src/libs/contentful/adapters/adaptHomepageEntries.ts, src/libs/contentful/adapters/adaptHomepageModules.native.test.ts, src/libs/contentful/adapters/helpers/buildImageUrl.native.test.ts, src/libs/contentful/adapters/helpers/buildImageUrl.ts, src/libs/contentful/adapters/modules/adaptBusinessModule.native.test.ts, src/libs/contentful/adapters/modules/adaptBusinessModule.ts, src/libs/contentful/adapters/modules/adaptCategoryListModule.ts, src/libs/contentful/adapters/modules/adaptExclusivityModule.native.test.ts, src/libs/contentful/adapters/modules/adaptExclusivityModule.ts, src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/libs/contentful/adapters/modules/adaptRecommendationModule.native.test.ts, src/libs/contentful/adapters/modules/adaptRecommendationModule.ts, src/libs/contentful/adapters/modules/adaptThematicHighlightModule.native.test.ts, src/libs/contentful/adapters/modules/adaptThematicHighlightModule.ts, src/libs/contentful/adapters/modules/adaptVenuesModule.native.test.ts, src/libs/contentful/adapters/modules/adaptVenuesModule.ts, src/libs/contentful/fixtures/algoliaModules.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21979
J'ai testé en dé-publiant un [displayParameters d'une playlist Algolia](https://app.contentful.com/spaces/2bg01iqy0isv/environments/testing/entries/6ReJznVoJT74ST0XSPUUjB) : sur testing, la Home est down, en local, elle s'affiche sans cette playlist.
I have:
=> (PC-21979) feat(contentful): improve adapters by improving typing

src/features/internal/cheatcodes/pages/TrustedDevice/TrustedDevice.tsx, src/features/profile/helpers/TrustedDevices/getDeviceModelFromUserAgent.native.test.ts, src/features/profile/helpers/TrustedDevices/getDeviceModelFromUserAgent.ts, src/features/profile/helpers/TrustedDevices/getDeviceModelFromUserAgent.web.test.ts, src/features/profile/helpers/TrustedDevices/useDeviceInfo.test.ts, src/features/profile/helpers/TrustedDevices/useDeviceInfos.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21835
Co-authored-by: Marine Shaw <marineshaw@users.noreply.github.com>
I have:
=> (PC-21835) feat(trustedDevice): update useDeviceInfos() 

src/features/auth/pages/forgottenPassword/ResetPasswordExpiredLink/ResetPasswordExpiredLink.native.test.tsx, src/features/cookies/helpers/useIsCookiesListUpToDate.native.test.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/cookies/pages/CookiesDetails.native.test.tsx, src/features/home/components/modules/ThematicHighlightModule.native.test.tsx, src/features/home/components/modules/categories/CategoryListModule.native.test.tsx, src/features/identityCheck/components/countryPicker/CountryPicker.native.test.tsx, src/features/internal/cheatcodes/pages/CheatCodes/CheatCodes.native.test.tsx, src/features/navigation/RootNavigator/RootNavigator.native.test.tsx, src/features/navigation/RootNavigator/RootNavigator.web.test.tsx, src/features/navigation/services.test.tsx, src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/libs/campaign/isAppsFlyerTrackingEnabled.test.ts
=> (BSR) refactor(tests): remove more flush promises

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/identityCheck/api/useProfileInfo.ts, src/features/identityCheck/components/StepButton.tsx, src/features/identityCheck/context/reducer.ts, src/features/identityCheck/context/types.ts, src/features/identityCheck/pages/Stepper.tsx, src/features/identityCheck/pages/helpers/useRehydrateProfile.ts, src/features/identityCheck/pages/profile/SetCity.tsx, src/features/identityCheck/types.ts, src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20005
I have:
| iOS      
https://user-images.githubusercontent.com/47600889/234633254-84de5142-52d2-46e1-aef3-f4c82b661233.mp4
|        |       |
=> (PC-20005) feat(identification): pre-fill profile for transition 17-18

src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/useAdaptOffersPlaylistParameters.native.test.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/useAdaptOffersPlaylistParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21969
I have:
https://user-images.githubusercontent.com/22886846/235198112-e1cd5ccf-2ad3-4bb8-a9b3-d9087b00520f.mov
https://user-images.githubusercontent.com/22886846/235198149-a05329ca-13e6-4089-9009-cc49700f71b5.mov
=> (PC-21969) fix(home): fix price min parameter on offers playlists

src/api/apiHelpers.test.ts, src/api/apiHelpers.ts, src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx, src/features/bookOffer/api/useBookOfferMutation.ts, src/features/errors/pages/AsyncErrorBoundary.native.test.tsx, src/features/errors/pages/AsyncErrorBoundary.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21900
I have:
=> (PC-21900) feat(apiCall): add no capture exception for 5xx API errors

src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx, src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21364
I have:
| iOS              |   
https://user-images.githubusercontent.com/47600889/235882033-d466e436-5273-4aee-b343-f17cdd6e1781.mp4
|    
https://user-images.githubusercontent.com/47600889/235882083-f51e90ba-6b93-45da-9ab7-0d8aa0a5d3dc.mp4
|
| Desktop - Chrome |    
https://user-images.githubusercontent.com/47600889/235882134-601e3750-a115-482e-95ab-40cb83e7c91a.mov
|   
https://user-images.githubusercontent.com/47600889/235882168-c73766ae-fb89-4fdd-a993-b7e8b4a8e512.mov
| …
=> (PC-21364) feat(offer): navigate to stepper instead of Profile tab from CTA FinishSubscription

src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22119
I have:
https://user-images.githubusercontent.com/62058919/235979260-3d4f362f-4383-49ec-9524-ac812b9861b4.mov
=> (PC-22119) fix(DatePickerSpinner): fix year scroll selection

package.json, yarn.lock
=> (BSR) chore(deps): update axe-storybook-testing and storybook/addon-react-native-web

__snapshots__/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/identityCheck/pages/profile/SetCity.tsx, src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx, src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.tsx, src/features/offer/components/OfferIconCaptions/OfferIconCaptions.native.test.tsx, src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx, src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx, src/features/profile/helpers/TrustedDevices/getDeviceModelFromUserAgent.ts, src/fixtures/user.ts
I have:
| Phone - !idCheck | ![Capture d’écran 2023-05-02 à 16 51 00](https://user-images.githubusercontent.com/26742386/235703008-46b8f8f0-2bc3-4f51-88c3-a128cb1cb610.png) | ![Capture d’écran 2023-05-02 à 16 45 42](https://user-images.githubusercontent.com/26742386/235702520-4f019467-fcac-44fa-be61-85c2710a3d96.png) |
| Phone - idCheck | ![Capture d’écran 2023-05-02 à 16 51 00](https://user-images.githubusercontent.com/26742386/235703008-46b8f8f0-2bc3-4f51-88c3-a128cb1cb610.png) | ![Capture d’écran 2023-05-02 à 16 59 33](https://user-images.githubusercontent.com/26742386/235705317-0d05cb61-4321-415c-aaa8-991b167591d1.png) |
| Desktop - …
=> (PC-20858) feat(offer): improve modal for 17 18

src/features/auth/context/AuthContext.native.test.tsx, src/features/auth/context/AuthContext.tsx, src/libs/amplitude/__mocks__/amplitude.ts, src/libs/amplitude/__mocks__/amplitude.web.ts, src/libs/amplitude/amplitude.ts, src/libs/amplitude/amplitude.web.ts, src/libs/amplitude/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20401
Testé : Le userId remonte correctement sur Amplitude en web et en mobile - il est bien le même en back et en front
I have:
=> (PC-20401) feat(amplitude): add user id to amplitude

.vscode/perf-test.code-snippets, src/features/offer/pages/Offer/Offer.perf.test.tsx, src/features/profile/pages/Profile.perf.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21754
I have:
=> (PC-21754) test(perfs): Add perf test for Profile page

server/src/utils/metas.ts, server/src/utils/tests/__snapshots__/metas.test.ts.snap, server/tests/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21532
I have:
Pas facile à tester de bout en bout mais ça fonctionne
=> (PC-21532) feat(offer): add metadata for the SEO

__mocks__/@react-navigation/native.ts, src/features/identityCheck/helpers/useNavigateForwardToStepper.ts, src/features/identityCheck/pages/helpers/useSubscriptionNavigation.ts, src/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.native.test.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.tsx, src/features/identityCheck/pages/identification/educonnect/IdentityCheckValidation.web.tsx, src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.native.test.tsx, src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.native.test.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21980
I have:
=> (PC-21980) feat(stepper): improve navigation to stepper

src/features/auth/context/AuthContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22214
I have:
=> (PC-22214) fix(sentry): fix user id amplitude error

src/features/auth/components/OpenInboxButton.tsx, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx, src/features/auth/pages/signup/AccountCreated/AccountCreated.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.tsx, src/features/favorites/components/NotConnectedFavorites.native.test.tsx, src/features/favorites/components/NotConnectedFavorites.tsx, src/features/home/components/banners/SignupBanner.native.test.tsx, src/features/home/components/banners/SignupBanner.tsx, src/features/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx, src/features/offer/components/AuthenticationModal/AuthenticationModal.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.tsx, src/features/onboarding/pages/AgeInformation.native.test.tsx, src/features/onboarding/pages/AgeInformation.tsx, src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.native.test.tsx, src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.tsx, src/libs/amplitude/events.ts, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/ui/components/ModuleBanner/BannerWithBackground.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22127
I have:
=> (PC-22127) feat(tracking): Track signup with amplitude

src/features/profile/components/InternalStep/InternalStep.native.test.tsx, src/features/profile/components/InternalStep/InternalStep.tsx, src/features/profile/components/ValidateIcon.tsx, src/features/profile/components/VerticalDots/AutomaticVerticalDots.tsx, src/features/profile/components/VerticalDots/VerticalDots.stories.tsx, src/features/profile/components/VerticalDots/VerticalDots.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.native.test.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21988
I have:
=> (PC-21988) fix(profile): better design

src/features/bookings/pages/Bookings/Bookings.perf.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21751
I have:
=> (PC-21751) test(Bookings): Add performance test for Bookings page

src/features/venue/pages/Venue/Venue.perf.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21748
I have:
=> (PC-21748) test(perfs): Add performance test for Venue page

src/api/gen/api.ts, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.tsx, src/features/auth/pages/signup/SignupForm.web.test.tsx, src/features/internal/cheatcodes/pages/TrustedDevice/TrustedDevice.tsx, src/features/profile/helpers/TrustedDevices/useDeviceInfo.test.ts, src/features/profile/helpers/TrustedDevices/useDeviceInfo.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21727
I have:
Petit test de création de compte en activant les FF, ça marche bien :
=> (PC-21727) feat(trustedDevice): Send device info on signup

src/features/bookings/pages/Bookings/Bookings.perf.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21751
I have:
=> (PC-21751) fix(Bookings): fix test with timeout

src/features/cookies/components/CookiesSettings.native.test.tsx, src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts, src/features/cookies/pages/CookiesDetails.native.test.tsx, src/features/cookies/pages/CookiesDetails.web.test.tsx, src/features/navigation/RootNavigator/RootNavigator.native.test.tsx, src/libs/campaign/isAppsFlyerTrackingEnabled.test.ts, src/libs/utm/getUtmParamsConsent.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17759
I have:
=> (PC-17759) feat(cookies): Use react-query for api call

src/api/gen/api.ts, src/features/auth/api/useSignIn.ts, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21683
I have:
=> (PC-21683) feat(login): Send device info on sign in

__snapshots__/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx.native-snap, src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx, src/features/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.tsx
I have:
| Platform         | Maquette | Réalisé |
| Phone - Chrome   | <img width="325" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/a0e8c8d3-f7b7-44de-9ec7-f80bbf37b8be"> | <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/8397095e-2b01-41f6-8c72-c66451db038d"> |
| Phone - Chrome  | <img width="289" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/f0f2726e-3aaf-4904-b86e-1fe37c4e0bde"> | <img width="377" alt="image" …
=> (PC-20858) feat(offer): update design according to mockup

src/features/auth/context/__mocks__/AuthContext.tsx, src/features/navigation/RootNavigator/Header/Header.web.test.tsx, src/features/navigation/RootNavigator/RootNavigator.web.test.tsx
=> (BSR) test(AuthContext): put isLoggedIn true for consistency

src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.tsx
=> (BSR) feat(signup): change wording

src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.tsx
=> (BSR) fix(ci): Fix linter

src/features/auth/pages/signup/SignupForm.native.test.tsx, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22301
I have:
=> (PC-22301) test(SignupForm): Remove mock and test component behavior

src/features/home/components/BlackGradient.tsx, src/features/home/components/constants.ts, src/features/home/components/headers/BlackBackground.tsx, src/features/home/components/headers/CategoryThematicHomeHeader.tsx, src/features/home/components/headers/HighlightThematicHomeHeader.tsx, src/features/home/components/modules/HomeModule.tsx, src/features/home/components/modules/ThematicHighlightModule.tsx, src/features/home/components/modules/VideoModule.stories.tsx, src/features/home/components/modules/VideoModule.tsx, src/features/home/fixtures/videoModule.fixture.ts, src/features/home/types.ts, src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/libs/contentful/adapters/adaptHomepageModules.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/libs/contentful/adapters/modules/adaptVideoModule.native.test.ts, src/libs/contentful/adapters/modules/adaptVideoModule.ts, src/libs/contentful/adapters/modules/helpers/adaptOffersModuleParameters.ts, src/libs/contentful/fixtures/videoContentModel.fixture.ts, src/libs/contentful/types.ts, src/ui/svg/icons/Play.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21761
I have:
| Platform         | one line | two lines |
| iOS              | <img width="334" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/e130f58c-e1cb-48b3-87cd-92c2d70ddda1"> | <img width="334" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/e7575c05-b21e-4c94-8c49-207d02783dbd"> |
| Phone - Chrome   | <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/498d2f3d-4bbb-4544-aea6-d2314c926e8d"> | <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/49ebd36d-cbfd-4622-b0db-448f99313021"> |
[1]: …
=> (PC-21761) feat(home): add first design for video module

src/features/internal/cheatcodes/pages/TrustedDevice/TrustedDevice.tsx
=> (BSR) feat(TrusedDevice): update trustedDevice infos in cheatcode

src/features/bookOffer/components/BookingDetails.native.test.tsx, src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.tsx, src/features/bookOffer/pages/BookingOfferModal.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21986
I have:
| iOS              |        |![Capture d’écran 2023-05-25 à 15 47 23](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/3ca22939-bb31-4a52-9c60-964a4d86a945) ![Capture d’écran 2023-05-25 à 15 47 31](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/d1a91427-3352-4980-8f6e-a39383080726) ![Capture d’écran 2023-05-25 à 15 47 38](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/6f84fb6a-889f-4705-a7ce-24be0536e952) ![Capture d’écran 2023-05-25 à 15 47 43](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/f7810841-883d …
=> (PC-21986) feat(bookOffer): add possibility to update venue offer in booking summary

src/features/auth/pages/signup/ProgressBar/ProgressBar.stories.tsx, src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx, src/features/internal/cheatcodes/pages/CheatCodes/SignupProgressBar.tsx, src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22329
I have:
| Android          |        | https://github.com/pass-culture/pass-culture-app-native/assets/68000368/877b9878-72dd-4905-b4c3-e5f8c45e791c |
=> (PC-22329) feat(Signup): add new signup progress bar

.github/workflows/dev_on_workflow_environment_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22460
Slack should notify if the previous job failed currently it's not the case because slack is one of the step of the job failing.
=> (PC-21770) fix(ci): slack should notify if a error arrived

.github/workflows/dev_on_push_workflow_main.yml
Après avoir merge cette PR je vais devoir refaire un hard deploy `yarn trigger:testing:deploy`
I have:
=> (BSR) fix(CI): fix hard deploy for testing ios and android

src/api/apiHelpers.test.ts, src/api/apiHelpers.ts, src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx, src/features/bookOffer/api/useBookOfferMutation.ts, src/features/errors/pages/AsyncErrorBoundary.native.test.tsx, src/features/errors/pages/AsyncErrorBoundary.tsx, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22086
I have:
=> (PC-22086) feat(apiCall): capture info for some API errors

src/features/auth/pages/signup/ProgressBar/ProgressBar.stories.tsx, src/features/auth/pages/signup/ProgressBar/ProgressBar.tsx, src/features/home/components/modules/VideoModule.stories.tsx, src/features/onboarding/components/CreditBlockIcon.stories.tsx
=> (BSR) fix(storybook): Fix storybook deploy

src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/OnGoingBookingItem.native.test.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/bookings/constants.ts, src/features/bookings/helpers/expirationDateUtils.test.ts, src/features/bookings/helpers/expirationDateUtils.ts, src/features/bookings/pages/BookingDetails/BookingDetails.tsx, src/features/bookings/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21975
I have:
=> (PC-21975) feat(booking): archive free booking from subcategories

jest/jest.setup.ts, package.json, src/api/apiHelpers.ts, src/features/cookies/helpers/useCookies.test.ts, src/features/cookies/helpers/useCookies.ts, src/features/cookies/pages/CookiesConsent.native.test.tsx, src/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx, src/features/trustedDevice/helpers/useDeviceInfo.ts, src/libs/monitoring/services.ts, src/libs/react-native-device-info/__mocks__/getDeviceId.ts, src/libs/react-native-device-info/__mocks__/getDeviceId.web.ts, src/libs/react-native-device-info/__mocks__/getUniqueId.ts, src/libs/react-native-device-info/__mocks__/getUniqueId.web.ts, src/libs/react-native-device-info/getDeviceId.ts, src/libs/react-native-device-info/getDeviceId.web.test.tsx, src/libs/react-native-device-info/getDeviceId.web.ts, src/libs/react-native-device-info/getUniqueId.ts, src/libs/storage.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22092
I have:
=> (PC-22092) feat(TrustedDevice): remove fingerprint and use UUID in getDeviceId

__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/bookOffer/components/BookingDetails.native.test.tsx, src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/BookingOfferLoader/BookingOfferLoader.native.test.tsx, src/features/bookOffer/components/BookingOfferLoader/BookingOfferLoader.stories.tsx, src/features/bookOffer/components/BookingOfferLoader/BookingOfferLoader.tsx, src/features/bookOffer/context/reducer.ts, src/features/bookOffer/helpers/useModalContent.test.tsx, src/features/bookOffer/helpers/useModalContent.tsx, src/features/home/components/banners/GeolocationBanner.native.test.tsx, src/features/home/components/banners/GeolocationBanner.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/VenueSelectionList/VenueSelectionList.native.test.tsx, src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.native.test.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.stories.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx, src/features/search/components/SearchList/SearchList.web.tsx, src/features/search/components/SearchListFooter/SearchListFooter.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22512
I have:
| iOS              |<img width="454" alt="Capture d’écran 2023-05-31 à 16 56 08" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/1b8fbf01-ab7b-4499-93a7-e5e3b1c9abc2"> <img width="454" alt="Capture d’écran 2023-05-31 à 17 27 40" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/dde4104a-0bca-4daf-ba15-f5879bf3c016">|<img width="467" alt="Capture d’écran 2023-05-31 à 17 33 06" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/ce3b5e09-0010-45df-8082-ceca955d3de0"> <img width="462" alt="Capture d’écran 2023-05-31 à 17 32 …
=> (PC-22512) fix(offer): finalization modal choice another venue

src/features/profile/components/StepCard/StepCard.tsx, src/features/profile/components/StepList/StepList.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChange.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21989
I have:
| iOS              |        |![Capture d’écran 2023-06-02 à 15 39 54](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/bdd47c59-8531-4bae-bc04-07379994f476)|
| Android          |        |![Capture d’écran 2023-06-02 à 15 40 06](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/52e47ebc-1b92-42a0-9409-aa0e0411bc84)|
| Desktop - Chrome |        |![Capture d’écran 2023-06-02 à 15 39 45](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/010a1040-330c-4d31-8b55-7ce12e …
=> (PC-21989) fix(TrackEmailChange): adjust component for web

src/ui/svg/icons/UserBlocked.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22543
I have:
| Android          |        | |
| Desktop - Chrome |<img width="488" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/b89e55a9-6fca-487f-8b8f-46aff53ed97c">|<img width="551" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/1dc2664e-d5f1-4b36-a781-301bd51b45cf">|
=> (PC-22543) fix(TrustedDevice): fix design for user blocked icon

src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.native.test.tsx, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.tsx, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22205
I have:
| iOS              |        |![Capture d’écran 2023-06-01 à 15 41 59](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/4a561c70-872f-445b-b273-76e09ab8f2a1)|
| Android          |        |![Capture d’écran 2023-06-01 à 15 55 39](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/5289919f-756b-4768-bf77-c4213a55be53)|
| Desktop - Chrome |        |![Capture d’écran 2023-06-01 à 15 45 34](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/3f5a1562-5d26-4fcc-bcde-e0a70e …
=> (PC-22205) feat(ConfirmChangeEmail): add new screen ConfirmChangeEmail

src/features/bookOffer/components/BookingOfferLoader/BookingOfferLoader.tsx
=> (BSR) fix(bookOffer): add accessibility label loader

doc/standards/testStrategy/ComponentTest.md, doc/standards/testStrategy/FullPageTest.md
=> (BSR) docs(test): update test on doc

src/api/gen/api.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/profile/helpers/useEmailUpdateStatus.test.ts, src/features/profile/helpers/useEmailUpdateStatus.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.native.test.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.web.test.tsx, src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22208
I have:
| Phone - Chrome   |        |<img width="432" alt="Capture d’écran 2023-06-05 à 09 56 09" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/a37f6469-6d32-4ee7-807d-b67b35fe24cd">|
| Desktop - Chrome |        |<img width="1726" alt="Capture d’écran 2023-06-05 à 09 56 19" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/6d074eb7-0224-4e67-b6ef-f1c87c8f6265">|
[1]: …
=> (PC-22208) feat(profile): add suspend account confirmation screen

src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22546
I have:
=> (PC-22546) fix(EmailValidationBuffer): add snackbar timeout

src/features/auth/pages/login/Login.tsx, src/features/home/components/modules/BusinessModule.native.test.tsx, src/features/home/components/modules/BusinessModule.tsx, src/libs/itinerary/useItinerary.native.test.ts, src/libs/itinerary/useItinerary.ts, src/ui/components/snackBar/SnackBarContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22546
I have:
- [] Made sure my feature is working on the relevant real / virtual devices (native and web).
=> (PC-22546) fix(Snackbar): add more timeout to snackbars
