src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22512
I have:
| iOS              |![Capture d’écran 2023-06-06 à 16 49 49](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/9979df0f-bbf1-4874-8f54-369ce1cca412) ![Capture d’écran 2023-06-06 à 16 49 55](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/7f82cf7a-f442-4d9d-b854-c867c0b53bad)|![Capture d’écran 2023-06-06 à 16 49 30](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/1012c099-1be9-495b-90f3-7f8399f03147) ![Capture d’écran 2023-06-06 à 16 49 35](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/531175e9-1e6b-4faa-a16 …
=> (PC-22512) refactor(offer): only venue modal title and toggle sticky

src/features/navigation/RootNavigator/routes.ts, src/features/profile/helpers/useEmailUpdateStatus.test.ts, src/features/profile/helpers/useEmailUpdateStatus.ts, src/features/profile/helpers/useEmailUpdateStatus.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.native.test.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22208
I have:
=> (PC-22208) feat(profile): manage 404 errors and log in sentry when calling email update status API

src/features/favorites/components/Favorite.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22673
I have:
| Phone - Chrome   |  <img width="521" alt="Capture d’écran 2023-06-08 à 16 12 13" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/162ff970-753b-4bcc-9c9b-20dd6531c2b2"> <img width="521" alt="Capture d’écran 2023-06-08 à 16 07 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/2f2732f8-281e-4d26-81ba-31fbc0d9a67b"> |   <img width="521" alt="Capture d’écran 2023-06-08 à 16 06 26" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/32fbad04-ca47-4d …
=> (PC-22673) feat(Favorite): update design for favorite screen

src/libs/contentful/adapters/adaptHomepageModules.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22712
I have:
| iOS              |        |![Simulator Screen Shot - iPhone 13 - 2023-06-08 at 17 35 50](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/47a4377f-8096-46d5-93da-ce7a1fa321d8)|
| Android          |        |<img width="349" alt="Capture d’écran 2023-06-08 à 17 37 00" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/497ce07b-8fd6-4d50-8692-bdd3d26ccc6f">|
| Desktop - Chrome |        |<img width="1512" alt="video_web" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/bba46d3d-de9b-49b2-8353-fad871f7d5ec">|
| Desktop - Safari | …
=> (PC-22712) feat(home): block the video module on web

src/features/navigation/helpers/openUrl.native.test.ts, src/features/navigation/helpers/openUrl.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22087
I have:
=> (PC-22087) feat(openUrl): log info in Sentry when there is a problem with a link

src/features/home/pages/Home.native.test.tsx, src/features/home/pages/Home.tsx, src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20066
I have:
=> (PC-20066) feat(Home): remove deprecated support for thematic header

.circleci/config.yml, .github/workflows/dev_on_push_workflow_main.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22411
Activate deployment of staging throught github actions
=> (PC-22411) feat(ci): Activate deployment for staging with github action

src/ui/components/snackBar/SnackBarContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22546
I have:
=> (PC-22546) feat(SnackBar): add default timeout in snackbar context

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/bookOffer/components/BookingDetails.native.test.tsx, src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/fixtures/offer.ts, src/features/bookings/components/BookingDetailsTicketContent.native.test.tsx, src/features/bookings/components/BookingDetailsTicketContent.tsx, src/features/bookings/components/TicketBody/Ean/Ean.test.tsx, src/features/bookings/components/TicketBody/Ean/Ean.tsx, src/features/bookings/fixtures/bookingsSnap.ts, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/pages/OfferDescription/OfferDescription.native.test.tsx, src/features/offer/pages/OfferDescription/OfferDescription.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22639
I have:
=> (PC-22639) feat(app): use ean rather than isbn everywhere

package.json, src/features/home/components/VideoPlayer.web.tsx, web/config/webpack.config.js, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22712
I have:
| iOS              |![Simulator Screen Shot - iPhone 13 - 2023-06-07 at 13 09 22](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/980e1a74-83fb-48d9-a35a-3e6788ed9427)|![simulator_screenshot_FC700C93-5B6C-4DBB-8072-CB1E0246C690](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/fd177202-7d34-4932-ba3e-9df74d2160ad)|
[1]: …
=> (PC-22712) fix(video): fix the build for web and remove react-native-web-webview

package.json, yarn.lock
=> (BSR) fix web deploy

__snapshots__/features/trustedDevice/pages/AccountSecurity.native.test.tsx.native-snap, src/features/internal/cheatcodes/pages/NavigationTrustedDevice/NavigationTrustedDevice.tsx, src/features/navigation/RootNavigator/trustedDeviceRoutes.ts, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/trustedDevice/helpers/formatTokenInfo.test.ts, src/features/trustedDevice/helpers/formatTokenInfo.ts, src/features/trustedDevice/helpers/getTokenInfo.test.ts, src/features/trustedDevice/helpers/getTokenInfo.ts, src/features/trustedDevice/pages/AccountSecurity.native.test.tsx, src/features/trustedDevice/pages/AccountSecurity.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22590
I have:
| Desktop - Chrome |        |    <img width="1440" alt="Capture d’écran 2023-06-12 à 10 40 18" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/3cb1654c-60ce-46b6-96d5-f42454a27eda">   |
=> (PC-22590) feat(AccountSecurity): Display login info from token 

src/features/home/components/modules/VideoModule.stories.tsx, src/features/home/components/modules/VideoModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22712
I have:
| iOS              |        |![simulator_screenshot_69415FC1-702B-4CE1-9045-158226C20D51](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/604528cd-1339-4fca-adcf-496b1e855684)|
| Desktop - Chrome |        |<img width="589" alt="Capture d’écran 2023-06-12 à 14 51 38" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/de4ab74a-1741-404d-b525-872d7b537e57">|
[1]: …
=> (PC-22712) fix(video): fix VideoModule Story 

web/js/chunk-protection.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22273
I have:
=> (PC-22273) fix(sw): Unregister existing service workers

src/features/home/api/useVideoOffer.ts, src/features/home/components/modules/OfferVideoModule.tsx, src/features/home/components/modules/VideoModule.native.test.tsx, src/features/home/components/modules/VideoModule.stories.tsx, src/features/home/components/modules/VideoModule.tsx, src/features/home/components/modules/venues/VenueTile.stories.tsx, src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22172
I have:
iOS:
Android:
=> (PC-22172) feat(VideoModule): VideoOffer component design

src/features/cookies/helpers/useCookies.native.test.ts
=> (BSR) test(cookies): Unskip test

src/features/cookies/helpers/useCookies.native.test.ts
This reverts commit 4e72430adfd6f87aeecee97c69254b507ff88f96.
I have:
=> (BSR) test(cookies): Revert unskip test (#4901)

src/features/cookies/helpers/getAcceptedCookieConsent.ts, src/features/home/components/modules/exclusivity/helpers/useShouldDisplayExcluOffer.ts, src/libs/algolia/fetchAlgolia/transformOfferHit.ts, src/ui/components/inputs/BaseTextInput.tsx
as it's more concise and easier to read.
split de https://github.com/pass-culture/pass-culture-app-native/pull/4896
=> (BSR) fix(global): Prefer using an optional chain expression instead

src/web/SupportedBrowsersGate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22548
I have:
| :--------------| :---: |
| iOS               |   [Messenger_iOS.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/c2b76889-97f0-4421-abba-c06ba4734e2e)   |
| Android          |     [Messenger_Android.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/899e4709-2da4-4cd0-9772-11232989b16b)   |
=> (PC-22548) fix(webapp): Support messenger browser

package.json, yarn.lock
=> (BSR) fix(codepush): Update appcenter

__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthdayV2.native.test.tsx.native-snap, __snapshots__/features/auth/pages/signup/SetBirthday/SetBirthdayV2.web.test.tsx.web-snap, src/features/auth/pages/signup/SetBirthday/SetBirthdayV2.native.test.tsx, src/features/auth/pages/signup/SetBirthday/SetBirthdayV2.tsx, src/features/auth/pages/signup/SetBirthday/SetBirthdayV2.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22322
I have:
| Android          |        |<img width="401" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/888c903d-fff0-432e-a312-fc9f8ac11ce1">|
| Phone - Chrome   |        |<img width="326" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ce38d98b-50d1-4e7b-ae4c-4f9c0b1a3660">|
| Desktop - Chrome |        |<img width="1065" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/c9475068-1673-42b3-b4e6-906050b8863a">|
| Desktop - …
=> (PC-22322) feat(Signup): add new design for SetBirthday

.github/workflows/dev_on_workflow_web_proxy_deploy.yml
=> (BSR) fix(ci): add proxy package install

__snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap, src/features/auth/components/PasswordSecurityRules.native.test.tsx, src/features/auth/components/PasswordSecurityRules.tsx, src/features/auth/components/PasswordSecurityRules.web.test.tsx, src/features/auth/pages/signup/SetPassword/SetPassword.native.test.tsx, src/features/auth/pages/signup/SetPassword/SetPasswordV2.native.test.tsx, src/features/auth/pages/signup/SetPassword/SetPasswordV2.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/internal/cheatcodes/pages/AppComponents/AppComponents.tsx, src/shared/forms/controllers/PasswordInputController.native.test.tsx, src/ui/components/inputs/InputError.tsx, src/ui/components/inputs/rules/InputRule.tsx, src/ui/components/inputs/rules/PasswordRule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22320
I have:
| Android          |        |<img width="404" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/9881330c-113d-400b-94f8-c20006b6aaf7">|
| Phone - Chrome   |        |<img width="321" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/9b206f4c-39d7-41a9-8b32-1bd7b19bf302">|
| Desktop - Chrome |        |<img width="1020" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/9823a10a-f30b-45ed-9ee8-2cf31df012c2">|
| Desktop - …
=> (PC-22320) feat(SignUp): add new set password

server/CI_TRIGGER.md
=> (BSR) fix(ci): add md file to server folder

__snapshots__/features/forceUpdate/pages/ForceUpdate.native.test.tsx.native-snap, src/features/forceUpdate/constants.ts, src/features/forceUpdate/pages/ForceUpdate.native.test.tsx, src/features/forceUpdate/pages/ForceUpdate.tsx, src/features/forceUpdate/pages/ForceUpdate.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22517
I have:
| iOS              |        | <img width="411" alt="Capture d’écran 2023-06-19 à 10 25 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/5986247e-f0ad-4917-89d5-d72f23fd28a0"> |
| Desktop - Chrome |        |  <img width="1792" alt="Capture d’écran 2023-06-19 à 10 23 00" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/2c948a2b-0bf0-43b6-aa7c-8b24f9737b55"> |
[1]: …
=> (PC-22517) feat(forceUpdate): udpate design for ForceUpdate screen

.github/workflows/dev_on_workflow_web_proxy_deploy.yml, server/CI_TRIGGER.md
=> (BSR) fix(ci): add gcloud setup

src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferTile/OfferTile.tsx, src/features/offer/types.ts, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22693
I have:
=> (PC-22693) feat(MultivenueOptionDisplayed): add new tracker

src/features/auth/pages/signup/AcceptCgu/AcceptCguV2.native.test.tsx, src/features/auth/pages/signup/AcceptCgu/AcceptCguV2.tsx, src/features/auth/pages/signup/SetEmail/SetEmailV2.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22324
I have:
| Phone - Chrome   |        |  <img width="500" alt="Capture d’écran 2023-06-16 à 15 22 00" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/0d9edee9-1662-42f0-b2e2-522827813921">     |
| Desktop - Chrome |        | <img width="1792" alt="Capture d’écran 2023-06-16 à 15 21 50" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/61391ac1-7eb8-486b-8c0d-59f4b2938739">      |
[1]: …
=> (PC-22324) feat(signup): update design for AcceptCGU v2

server/package.json
=> (BSR) fix(ci): remove gcloud beta usage

server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap, src/features/favorites/components/Favorite.native.test.tsx, src/features/favorites/components/Favorite.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22855
I have:
| Desktop - Chrome |   <img width="721" alt="Capture d’écran 2023-06-20 à 09 27 11" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/d3b9b213-0dac-4fc0-8147-0c980f7fb4b3">     |   <img width="720" alt="Capture d’écran 2023-06-20 à 09 26 56" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/99deb474-d03c-4f5d-8600-60934cbb3ccf">    |
=> (PC-22855) fix(favorites): Remove share button to avoid fetching invalid offer

__snapshots__/features/home/components/modals/VideoModal.native.test.tsx.native-snap, src/features/home/components/VideoPlayer.tsx, src/features/home/components/helpers/getVideoPlayerDimensions.native.test.ts, src/features/home/components/helpers/getVideoPlayerDimensions.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21765
I have:
No screenshots as it needs a real test device
=> (PC-21765) fix(video): fix inner scroll on player

__snapshots__/features/search/components/SearchHeader/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx, src/features/search/components/SearchHeader/SearchHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22551
I have:
| Phone - Chrome   | <img width="447" alt="CleanShot 2023-06-20 at 10 04 55@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/7defa21c-119d-48a2-9686-cf0e74e0ebb7"> |<img width="448" alt="CleanShot 2023-06-20 at 10 04 27@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/f41a310e-9ec4-4dc9-bdcc-6eafeb17371b">|
[1]: …
=> (PC-22551) feat(search): improve title

src/features/forceUpdate/pages/ForceUpdate.native.test.tsx, src/features/forceUpdate/pages/ForceUpdate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22517
I have:
=> (PC-22517) feat(ForceUpdate): use useWebAppUrl instead env + https

src/libs/algolia/fetchAlgolia/fetchOffersModules.ts
Algolia.multipleQueries has a limit of 50 queries per call https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/#about-this-method
I have:
=> fix(algolia): handle the limit for multi-queries

server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap, server/src/middlewares/tests/webAppProxyMiddleware.test.ts, server/tsconfig.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22130
I have:
=> (PC-22130) test(proxy): remove offer id from snapshots tests

doc/development/e2e.md
=> (BSR) docs(e2e): add class link

sonar-project.properties
=> (BSR) feat(Sonar): disabled sonar rule

__snapshots__/features/home/components/modals/VideoModal.native.test.tsx.native-snap, src/features/home/components/modals/VideoModal.native.test.tsx, src/features/home/components/modals/VideoModal.tsx, src/features/home/components/modules/OfferVideoModule.tsx, src/features/home/components/modules/VideoModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22422
I have:
| iOS              | ![OffreVidéo - Ios avant](https://github.com/pass-culture/pass-culture-app-native/assets/131354212/2cfa4873-9539-4ed7-b051-ae19ef5c1418) | ![OffreVidéo - Ios après](https://github.com/pass-culture/pass-culture-app-native/assets/131354212/ba818c18-dc23-4754-ae8c-c7219378beb6) |
| Android          | ![OffreVidéo - Android avant](https://github.com/pass-culture/pass-culture-app-native/assets/131354212/a4a1d3ad-9a3c-4aef-af57-68e8b41e9b5c) | ![OffreVidéo - Android après](https://github.com/pass-culture/pass-culture-app-native/assets/131354212/dd6c9418-6bb6-4a49-a0c9-9cd8c6289b0f) |
=> (PC-22422) feat(VideoModule): add offer on modal video

__snapshots__/features/home/components/modals/VideoModal.native.test.tsx.native-snap, src/features/home/components/VideoPlayer.tsx, src/features/home/components/modals/VideoModal.tsx, src/features/home/fixtures/videoModule.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/modules/adaptVideoModule.ts, src/libs/contentful/fixtures/videoContentModel.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22466
I have:
| Type         | Screenshot |
| With description              |![Simulator Screen Shot - iPhone 13 - 2023-06-22 at 18 25 56](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/f1820125-d097-4f87-919d-a9872a8061fd)| 
| Without description              |![Simulator Screen Shot - iPhone 13 - 2023-06-22 at 18 31 43](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/84bd88b4-1b58-4542-b51a-1e6a911372bf)| 
=> (PC-22466) feat(video): add description and publication date

__snapshots__/features/home/components/modals/VideoModal.native.test.tsx.native-snap, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/pages/BookingDetails/BookingDetails.tsx, src/features/favorites/components/Favorite.tsx, src/features/home/components/modules/OfferVideoModule.native.test.tsx, src/features/home/components/modules/OfferVideoModule.tsx, src/features/offer/components/OfferTile/OfferTile.tsx, src/features/search/components/Hit/Hit.tsx, src/shared/offer/usePrePopulateOffer.ts, src/ui/components/touchableLink/InternalTouchableLink.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21767
I have:
| iOS              |        | ![Screen Recording 2023-06-21 at 17 49 39](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/ab7eeb3a-154b-4129-96e2-7e5f4669851f) |
| Web mobile |        |  ![Screen Recording 2023-06-21 at 18 13 38](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/62aadd87-151f-45c2-8739-3bbbf5062579) |
=> (PC-21767) feat(videoModule): make offer pressable

src/features/auth/constants.ts, src/features/auth/enums.ts, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentV2.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentV2.tsx, src/features/auth/pages/signup/SignupFormV2.native.test.tsx, src/features/auth/pages/signup/SignupFormV2.tsx, src/ui/components/headers/CloseButtonText.tsx, src/ui/components/headers/PageHeaderWithoutPlaceholder.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22325
I have:
| Android          |        |<img width="331" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/def10fcb-e3aa-44eb-b8ec-d25d575db951">|
| Phone - Chrome   |        |<img width="326" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/cf16a720-9f8e-4678-a5ec-87b39ea92412">|
| Desktop - Chrome |        |<img width="1024" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/f665e424-2370-47a9-a418-40b7f925fd53">|
| Desktop - …
=> (PC-22325) feat(signup): new email confirmation

src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.web.test.tsx, src/features/identityCheck/pages/profile/SetAddress.web.test.tsx, src/features/identityCheck/pages/profile/SetCity.web.test.tsx, src/features/identityCheck/pages/profile/SetName.web.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.web.test.tsx
=> (BSR) fix(tests): Fix flaky accessibility tests

src/features/home/components/VideoPlayer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21766
I have:
=> (PC-21766) fix(video): fix replay multiple press

server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap, server/src/middlewares/tests/webAppProxyMiddleware.test.ts
=> (BSR) fix(ci): Update proxy snapshots

public/.well-known/assetlinks-staging.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22865
I have:
=> (PC-22865) fix(build): fix certificate signature on staging

src/features/birthdayNotifications/pages/RecreditBirthdayNotification.native.test.tsx, src/features/birthdayNotifications/pages/RecreditBirthdayNotification.tsx, src/features/birthdayNotifications/pages/RecreditBirthdayNotification.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22722
I have:
| 16 ans   | <img width="375" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/ef9a02a8-2ccf-40d5-97ff-735cdf67faf1"> | <img width="375" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/cff348d3-83df-46cd-9962-2da11ddbd1a8"> |
| 17 ans   | <img width="375" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/1d9a806f-153c-4d10-b1b2-955edb8c903c"> | <img width="376" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/aff28892-5f98-4167-9008-f9a53b353498"> |
[1]: …
=> (PC-22722) feat(recreditNotification): change wording

doc/standards/testStrategy/GeneralGuidelines.md
=> (BSR) docs(test): update test strategy to erase .test files alone

__snapshots__/ui/pages/SecondaryPageWithBlurHeader.native.test.tsx.native-snap, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/ui/pages/SecondaryPageWithBlurHeader.native.test.tsx, src/ui/pages/SecondaryPageWithBlurHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22845
I have:
| iOS              |  <img width="377" alt="Capture d’écran 2023-06-30 à 09 32 18" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/5ccfeffd-7ed2-4833-851c-ed20dcacf6ff">  |  <img width="375" alt="Capture d’écran 2023-06-30 à 09 30 14" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/ac9c2cc7-5a41-4b1b-914b-14f27401514a">  |
| Desktop - Chrome | <img width="1399" alt="Capture d’écran 2023-06-30 à 09 32 31" …
=> (PC-22845) feat(Login): update design for Login page

src/features/home/components/VideoPlayer.native.test.tsx, src/features/home/components/VideoPlayer.tsx, src/features/home/components/modals/VideoModal.tsx, src/features/home/components/modules/video/VideoEndView.native.test.tsx, src/features/home/components/modules/video/VideoEndView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21766
I have:
| iOS              |![simulator_screenshot_5A92B9B8-18A4-4EF2-AEC6-4324C1207F3E](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/df5e12eb-bf0f-4a5f-bfba-74a86c1b66ae)|![image](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/855c8447-05b7-4c41-8430-e590eda16534)|
| Android          |![image](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/b5d00b63-b1aa-405b-bdce-9f64354fee2f)|![image](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/43a2250e-a16e-466d-a227-abb4173042c3)|
[1]: …
=> (PC-21766) fix(videoPlayer): remove thumbnail from calque

package.json, src/features/home/components/modules/categories/CategoryBlock.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx, src/features/internal/cheatcodes/pages/NavigationCulturalSurvey/index.tsx, src/features/offer/components/DistanceTag/DistanceTag.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.tsx, src/features/profile/components/InternalStep/InternalStep.tsx, src/features/profile/components/VerticalDots/AutomaticVerticalDots.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.tsx, src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/features/search/helpers/categoriesHelpers/mapping-tree.ts, src/features/search/pages/SuggestedPlaces/SuggestedPlaces.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx, src/ui/components/buttons/AppButton/styleUtils.ts, src/ui/components/buttons/AppButton/types.ts, src/ui/svg/icons/types.ts
I have:
|         | Before | After |
| prune issues              |  <img width="193" alt="Capture d’écran 2023-07-03 à 08 47 10" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/70a10168-3a08-44be-859e-919dff5c7566"> | <img width="187" alt="Capture d’écran 2023-07-03 à 08 48 25" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/36036d16-588d-4c31-9195-40490ed4347e"> |
=> (BSR) fix(prune): fix some prune issues

__snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap, src/features/home/components/modules/video/OfferVideoModule.tsx, src/features/home/components/modules/video/VideoModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22172
I have:
| iOS - no date             |![before_no_date](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/92832d5d-1402-4141-863b-2204d9c7c904)|![after_price_only](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/fdc79558-e700-47f6-a575-bfad233cc80c)|
| iOS - no price             |![before_no_price](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/ff06a51e-dcef-4529-9b6a-44e07654c8cc)|![after_date_only](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/f83862d3-0503-4d21-b117-244bf1f2f0f1)|
| iOS - nothing …
=> (PC-22172) fix(video): adjust gradient with title and center info when missing

.github/workflows/dev_on_schedule_e2e_android_app.yml, .github/workflows/dev_on_schedule_e2e_android_browser.yml, .github/workflows/dev_on_schedule_e2e_browser.yml, .github/workflows/dev_on_schedule_e2e_ios_browser.yml
=> (BSR) feat(e2e): disabled all e2e workflow

__snapshots__/features/search/components/SearchHeader/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx, src/features/search/components/SearchHeader/SearchHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22550
I have:
| Desktop - Chrome |<img width="1030" alt="CleanShot 2023-06-30 at 15 34 41@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/4ef4b3c2-2be0-46a5-83d4-0116184a8297"><img width="411" alt="CleanShot 2023-06-30 at 15 35 08@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/3e331987-8cdf-4864-86a5-d02baf233cb4">|<img width="1034" alt="CleanShot 2023-06-30 at 15 35 33@2x" …
=> (PC-22550) feat(search): improve styling

__snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap, src/features/home/components/modules/video/VideoModal.tsx, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22467
I have:
iOS: 
https://github.com/pass-culture/pass-culture-app-native/assets/22886846/a1d91d82-9f8a-466d-bc25-1661443c2c35
android: 
https://github.com/pass-culture/pass-culture-app-native/assets/22886846/58925b36-a673-44b3-9e57-328141b006f7
=> (PC-22467) feat(videoModal): close modal when swiping down

public/robots.txt
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22117
I have:
=> (PC-22117) feat(SEO): Remove indexing from Search feature

__snapshots__/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx.native-snap, __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.tsx, src/features/auth/pages/signup/SignupForm.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22848
I have:
=> (PC-22848) feat(signup): update title for ReinitializePassword

package.json, src/features/home/components/modules/video/ButtonWithCaption.tsx, src/features/home/components/modules/video/VideoPlayer.web.tsx, src/features/home/components/modules/video/types.ts, src/libs/contentful/adapters/adaptHomepageModules.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22106
I have:
Desktop - Firefox : 
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/b609d159-6822-4cf8-89b2-c1789b270d5d
Desktop - Safari :
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/1932d060-a678-46d1-96b0-26a3aa85a48a
Desktop - Chrome :
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/af8e0e49-8c65-435c-8a70-382e18b0753c
Desktop - Firefox - mobile:
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/4b99282d-0fa6-4831-999f-c4f457f3872c
Desktop - Chrome - mobile:
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/f8fa76fa-cf93-4c46-b7e4-0f02b33a1426
=> (PC-22106) feat(VideoModal): Modal Video is working on web

src/features/bookOffer/components/BookingDetails.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/VenueSection/VenueSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22961
I have:
=> (PC-22961) feat(venue): use || instead ?? for venue name

__snapshots__/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx.native-snap, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.web.test.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/schema/reinitializePasswordSchema.test.ts, src/features/auth/pages/forgottenPassword/ReinitializePassword/schema/reinitializePasswordSchema.ts, src/features/profile/pages/ChangeEmail/ChangeEmail.web.test.tsx, src/features/profile/pages/ChangePassword/ChangePassword.native.test.tsx, src/features/profile/pages/ChangePassword/ChangePassword.tsx, src/features/profile/pages/ChangePassword/ChangePassword.web.test.tsx, src/shared/forms/controllers/PasswordInputController.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17382
I have:
=> (PC-17382) feat(signup): react hook formisation reinitialize password

.gitignore, doc/installation/iOS.md
Improvements after installing the projects on my new computer (M2 Pro)
=> (BSR) docs(ios): improve install guide

.circleci/config.yml, .github/workflows/dev_on_workflow_tester.yml
=> (BSR) fix(ci): Skip sonar job because of upload fail

.circleci/config.yml, .github/workflows/dev_on_workflow_tester.yml
=> (BSR) fix(CI): unskip sonar job

src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.native.test.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.web.test.tsx, src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22601
I have:
=> (PC-22601) feat(profile): add API call to suspend account

src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.native.test.tsx, src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22211
I have:
=> (PC-22211) fix(profile): validation new email

__snapshots__/features/bookOffer/components/BookingInformations.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/bookOffer/components/BookingInformations.native.test.tsx, src/features/bookOffer/components/BookingInformations.tsx, src/features/bookOffer/components/PriceLine.native.test.tsx, src/features/bookOffer/components/PriceLine.tsx, src/features/bookOffer/fixtures/offer.ts, src/features/bookOffer/fixtures/stocks.ts, src/features/bookOffer/helpers/useModalContent.native.test.tsx, src/features/offer/components/OfferIconCaptions/OfferIconCaptions.native.test.tsx, src/features/offer/fixtures/offerResponse.ts, src/features/offer/fixtures/offerStockResponse.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23094
I have:
| Desktop - Chrome |![Capture d’écran 2023-07-18 à 10 34 34](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/48805bdf-8578-4034-ba2a-bc3462608eb6)|<img width="522" alt="Capture d’écran 2023-07-18 à 09 43 43" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/0df390dd-0211-4d40-9882-0be13a00a97b">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les …
=> (PC-23094) feat(PriceLine): add cinema's attributes

src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23141
I have:
| iOS              |        |<img width="293" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/8bda37ae-5a32-4a44-8d8a-4c367b908d98"> <img width="293" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/8dc1909e-fc5c-4651-9595-2028679b2d81"> |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613 …
=> (PC-23141) feat(ChangeEmail): add spelling help in email field

src/features/profile/pages/TrackEmailChange/TrackEmailChange.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23377
I have:
| iOS              |        |![Capture d’écran 2023-07-19 à 14 31 46](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/385fd958-9226-4994-bcae-3a09e238dc99)|
| Desktop - Chrome |        |![Capture d’écran 2023-07-19 à 14 31 06](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/2d0ff1b2-0313-4817-8a69-d1c691f8185b)|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e68870 …
=> (PC-23377) feat(TrackEmailChange): fix ui for mobile

__snapshots__/features/bookOffer/components/BookHourChoice.native.test.tsx.native-snap, __snapshots__/features/bookOffer/components/BookingEventChoices.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/profile/SetSchoolType.native.test.tsx.native-snap, __snapshots__/features/identityCheck/pages/profile/SetStatus.native.test.tsx.native-snap, src/features/bookOffer/components/BookHourChoice.native.test.tsx, src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/BookPricesChoice.tsx, src/features/bookOffer/components/BookingEventChoices.native.test.tsx, src/features/bookOffer/components/HourChoice.tsx, src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.test.ts, src/features/bookOffer/helpers/bookingHelpers/bookingHelpers.ts, src/features/identityCheck/pages/profile/SetSchoolType.tsx, src/features/identityCheck/pages/profile/SetStatus.tsx, src/features/offer/components/SelectableListItem/SelectableListItem.stories.tsx, src/features/offer/components/SelectableListItem/SelectableListItem.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.stories.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.tsx, src/ui/components/radioSelector/RadioSelector.native.test.tsx, src/ui/components/radioSelector/RadioSelector.stories.tsx, src/ui/components/radioSelector/RadioSelector.tsx, src/ui/components/radioSelector/RadioSelector.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23093
I have:
| Desktop - Chrome |<img width="553" alt="CleanShot 2023-07-18 at 10 23 19@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/9ebec95e-f92d-440c-a687-23fb525ebe6d">|<img width="554" alt="CleanShot 2023-07-18 at 10 23 48@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/46ba4072-6824-40ec-af73-577201c99cfb">|
[1]: …
=> (PC-23093) feat(offers): offer options

src/features/offer/components/SelectableListItem/SelectableListItem.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23093
I have:
=> (PC-23093) fix(storybook): fix a11y issue

src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.native.test.tsx, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.native.test.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChange.tsx, src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.native.test.tsx, src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21255
I have:
=> (PC-21255) feat(profile): improve user experience when updating email

src/features/search/components/CategoryButton/CategoryButton.tsx, src/features/search/components/CategoryButton/CategoryButton.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23021
I have:
| Desktop - Chrome |![Capture d’écran 2023-07-19 à 17 32 22](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/9c2d5d77-8044-48cc-a114-828caf0b77f3)|![Capture d’écran 2023-07-19 à 17 32 28](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/1c044d81-ac10-4464-8c32-dc40d354de68)| …
=> (PC-23021) feat(CategoryButton): render CategoryButton accessible with the focus

__mocks__/fixtures/booking.ts, __snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/bookings/components/BookingPropertiesSection.native.test.tsx, src/features/bookings/components/BookingPropertiesSection.tsx, src/features/bookings/fixtures/bookingsSnap.ts, src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23098
I have:
| Desktop - Chrome |![Capture d’écran 2023-07-20 à 16 10 40](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/26c95c65-3009-46e2-9056-c9a612e95746)![Capture d’écran 2023-07-20 à 16 12 24](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/5f0aac9e-3a35-4290-a1e6-1adf19e68e22)|![Capture d’écran 2023-07-20 à 15 58 37](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/1f7a532f-6f6c-4965-a7d5- …
=> (PC-23098) feat(BookingPropertiesSection): add cinema's attributes

__snapshots__/features/bookOffer/components/BookHourChoice.native.test.tsx.native-snap, src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/HourChoice.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23093
I have:
| Desktop - Chrome |<img width="564" alt="CleanShot 2023-07-20 at 14 46 07@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/cae214ed-af0e-4e10-b497-c8a3e611dc86">|<img width="560" alt="CleanShot 2023-07-20 at 14 46 27@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/c8f59d05-df37-4750-868d-b56a347d9c37">|
[1]: …
=> (PC-23093) fix(bookings): fix alignment and spacing

src/features/home/components/modules/HomeModule.tsx, src/features/home/components/modules/video/VideoModule.native.test.tsx, src/features/home/components/modules/video/VideoModule.tsx, src/features/home/pages/GenericHome.tsx, src/features/home/pages/Home.tsx, src/features/home/pages/ThematicHome.tsx, src/features/internal/marketingAndCommunication/config/deeplinksExportConfig.ts, src/features/navigation/RootNavigator/types.ts, src/features/navigation/TabBar/types.ts, src/features/navigation/screenParamsUtils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23101
I have:
Web (la vidéo ne se lance pas automatiquement............) :
https://github.com/pass-culture/pass-culture-app-native/assets/22886846/a3385412-9580-4181-8ac5-6e7801691067
Home :
https://github.com/pass-culture/pass-culture-app-native/assets/22886846/ab80e6d9-85d4-4a99-b695-ab5b3b561d85
Thematic home:
https://github.com/pass-culture/pass-culture-app-native/assets/22886846/f06c9cd7-a184-42c4-98cc-133ad6a44744
Pas réussi à tester sur android, j'arrivais pas à coller le deeplink sur mon simulateur
=> (PC-23101) feat(deeplink): add deeplink to show videomodal on home and thematic home pages

__snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23101
I have:
=> (PC-23101) fix(tests): update snapshot after adding  videomodule deeplink

src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-17383
I have:
=> (PC-17383) feat(Login): improve errors behaviour on login form

.github/workflows/TODO.md, .github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_ts_prune.yml, package.json, scripts/check_dead_code_introduced.sh
Inspired from: https://www.bam.tech/en/article/seek-and-destroy-dead-code-for-good-a-strategy-using-ts-prune
=> (BSR) ci(github): add ts-prune action to avoid adding dead code

package.json, yarn.lock
=> (BSR) feat(accessibility): udpate axe-storybook-testing to 7.1.1

lighthouserc.yml
=> (BSR) fix(lighthouse): Increase threshold to avoid flaky workflow

.github/workflows/dev_on_workflow_environment_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_tester.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23528
=> (PC-23528) fix(ci): To get token output need to be write correctly

src/App.tsx, src/libs/codepush/options.tsx
to improve install speed and rate
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23218
=> (PC-23218) chore(codepush): check update and install on next resume

src/features/home/api/useVideoOffers.ts, src/features/home/components/modules/video/VideoModule.native.test.tsx, src/features/home/components/modules/video/VideoModule.tsx, src/features/home/components/modules/video/VideoModuleDesktop.tsx, src/features/home/components/modules/video/VideoModuleMobile.tsx, src/features/home/components/modules/video/VideoMultiOfferList.tsx, src/features/home/components/modules/video/VideoMultiOfferPlaylist.tsx, src/features/home/types.ts, src/features/search/components/SearchResults/SearchResults.tsx, src/ui/components/SeeMoreWithEye.tsx, src/ui/components/tiles/HorizontalOfferTile.native.test.tsx, src/ui/components/tiles/HorizontalOfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22939
I have:
| Usecase         | Before |
| More than 3 offers              |<img width="1512" alt="more_than_three" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/63ae6551-d3a4-4cd9-9c1c-758db7e94c22">|
| Only 3 offers          |<img width="1512" alt="only_three" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/6c4e6fad-5800-4b59-82a5-1e8313a8e374">|
| Only 2 offers   |<img width="1512" alt="only_two" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/a765793a-5fa7-41f3-880d-c22fea6690c8">|
=> (PC-22939) feat(video): add web video mutli offer design

.github/workflows/dev_on_workflow_ts_prune.yml, .gitignore, scripts/check_dead_code_introduced.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23546
I have:
=> (PC-23546) feat(prune): update check_dead_code_introduced script

src/libs/parsers/venueType.ts
=> (BSR) fix(home): fix venue type label

__mocks__/algoliasearch.ts, src/api/useSearchVenuesOffer/useSearchVenueOffers.ts, src/features/search/api/useSearchResults/useSearchResults.native.test.ts, src/features/search/api/useSearchResults/useSearchResults.ts, src/features/venue/types.ts, src/libs/algolia/__mocks__/mockedAlgoliaResponse.ts, src/libs/algolia/fetchAlgolia/fetchOffers.native.test.ts, src/libs/algolia/fetchAlgolia/fetchOffers.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.test.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/helpers/buildSearchVenuePosition.test.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/helpers/buildSearchVenuePosition.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/helpers/getSearchVenueQuery.test.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/helpers/getSearchVenueQuery.ts, src/libs/algolia/fetchAlgolia/fetchVenues/adaptAlgoliaVenues.test.ts, src/libs/algolia/fetchAlgolia/fetchVenues/adaptAlgoliaVenues.ts, src/libs/algolia/fetchAlgolia/fetchVenues/fetchVenues.native.test.ts, src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts, src/libs/venue/fixtures/mockedSuggestedVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23457
I have:
=> (PC-23457) feat(search): use multi-search offers and venues when wipEnableVenuesInSearchResults feature flag activated

__snapshots__/features/search/components/SearchResults/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/components/SearchResults/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23512
I have:
| Phone - Chrome   |![Capture d’écran 2023-07-27 à 14 39 17](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/5fa42225-e3c3-4013-aff7-21a4c8595fa8) ![Capture d’écran 2023-07-27 à 14 39 22](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/250fd796-6e5b-4ab3-98b3-fe41b34106fe)|   ![Capture d’écran 2023-07-27 à 14 38 45](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/f689aa4f-6b33-415f-8d03-73d18bbe9185) ![Capture d’écran 2023-07-27 à 14 38 …
=> (PC-23512) fix(search): spacing between search bar and filter buttons

src/features/home/components/headers/CategoryThematicHomeHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20703
I have:
| iOS              | <img width="355" alt="Capture d’écran 2023-07-28 à 14 27 48" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/28f5a814-d71e-4a4c-9a3a-90f51bb5aa8f"> | <img width="355" alt="Capture d’écran 2023-07-28 à 14 28 02" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/5d137345-df21-4e96-b229-23a26d9f7916"> |
| Android          | <img width="336" alt="Capture d’écran 2023-07-28 à 14 27 27" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/a6f89498-e4f9-4a61-8be7-c3421ccc4a77"> | <img width="336" alt="Capture d’écran 2023-07-28 à 14 …
=> (PC-20703) fix(Category): increase background height for space for 2 lines of subheader

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/bookings/fixtures/bookingsSnap.ts, src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx, src/features/bookings/pages/BookingDetails/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23392
I have:
| iOS              |        |![Capture d’écran 2023-07-27 à 17 28 00](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/e5078452-40cd-415f-a04a-f0d2d0baaf6f)|
| Desktop - Chrome |        |![Capture d’écran 2023-07-27 à 17 28 15](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/9df4aa34-8f87-4576-8b70-62191533b332)|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e68870 …
=> (PC-23392) feat(BookingDetails): add booking email contact

templates_github_ci/production.keystore.properties
=> (BSR) fix(production): missing production.keystore.properties file

src/libs/campaign/campaignTracker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22544
I have:
=> (PC-23589) fix(AppsFlyer): Catch inexistant app error for Android

src/features/home/components/modules/HighlightOfferModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23469
https://app.contentful.com/spaces/2bg01iqy0isv/environments/testing/entries/fH2FmoYeTzZPjhbz4ZHUW
I have:
=> (PC-23469) feat(home): add HighlightOfferModule desktop design

.circleci/config.yml, .github/workflows/dev_on_push_workflow_main.yml
This reverts commit 5b5149ab3d2c19497f297b545579919b228e0c8b.
I have:
=> (BSR) fix(circleci): Revert "(PC-22911) feat(ci): Use github to deploy production and integration (#4986)"

__snapshots__/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx.native-snap, __snapshots__/features/trustedDevice/pages/SuspensionChoice.native.test.tsx.native-snap, src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx, src/features/trustedDevice/pages/SuspensionChoice.tsx
=> (BSR) feat(trustedDevice): fix typo

__snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap, __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap, src/features/home/pages/GenericHome.tsx, src/features/home/pages/Home.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21416
I have:
iOS:
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/3827ed36-36c6-449c-a904-de9a9846be50
Android:
https://github.com/pass-culture/pass-culture-app-native/assets/131354212/e859d75c-27b5-4729-a85c-53c94137c568
=> (PC-21416) fix(statusBar): remove blurred StatusBar on Thematic Home

.eslintrc.js, eslint-custom-rules/__tests__/no-use-of-algolia-multiple-queries.test.js, eslint-custom-rules/no-use-of-algolia-multiple-queries.js, eslint-local-rules.js, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/fetchMultipleOffers.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.ts, src/libs/algolia/fetchAlgolia/fetchOffersModules.ts, src/libs/algolia/fetchAlgolia/fetchVenuesModules.ts, src/libs/algolia/fetchAlgolia/multipleQueries.native.test.ts, src/libs/algolia/fetchAlgolia/multipleQueries.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22866
I have:
=> (PC-22866) refactor(algolia): clean fix for multiple queries

src/features/bookings/components/TicketBody/EmailSent/EmailSent.tsx, src/features/offer/pages/Offer/Offer.tsx, src/ui/components/SocialNetworkCard.tsx, src/ui/components/buttons/AppButton/AppButton.web.tsx, src/ui/components/buttons/AppButton/utils.test.ts, src/ui/components/buttons/buttonInsideText/ButtonInsideText.native.test.tsx, src/ui/components/buttons/buttonInsideText/ButtonInsideText.web.test.tsx, src/ui/components/buttons/buttonInsideText/ButtonInsideText.web.tsx, src/ui/components/buttons/buttonWithLinearGradient/ButtonWithLinearGradient.web.tsx, src/ui/components/buttons/buttonWithLinearGradient/types.ts, src/ui/components/touchableLink/TouchableLink.tsx, src/ui/components/touchableLink/TouchableLink.web.test.tsx, src/ui/components/touchableLink/handleNavigationWrapper.ts, src/ui/components/touchableLink/handleNavigationWrapper.web.ts, src/ui/components/touchableLink/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22272
I have:
=> (PC-22272) feat(accessibility): enable cmd + clic for TouchableLink in web

src/api/gen/api.ts, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx, src/features/bookOffer/components/BookingDetails.native.test.tsx, src/features/bookOffer/components/BookingInformations.native.test.tsx, src/features/bookOffer/components/PriceLine.native.test.tsx, src/features/bookOffer/helpers/useModalContent.tsx, src/features/bookOffer/pages/BookingConfirmation.native.test.tsx, src/features/profile/pages/PersonalData/PersonalData.native.test.tsx, src/libs/firebase/firestore/featureFlags/useFeatureFlag.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23517
I have:
=> (PC-23517) feat(trustedDevice): Send device info to api when validating email

src/features/home/components/modules/video/VideoMultiOfferList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23569
I have:
| iOS              | <img width="362" alt="Capture d’écran 2023-08-07 à 16 12 17" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/a5594b35-b758-41f4-8a83-d7853f3dea2a"> | <img width="355" alt="Capture d’écran 2023-08-07 à 16 11 33" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/e7a519a2-cd5a-4c58-b6ee-2a224820e564"> |
| Android          | <img width="336" alt="Capture d’écran 2023-08-07 à 16 12 08" src="https://github.com/pass-culture/pass-culture-app-native/assets/131354212/d248ea1a-07ca-4981-928e-a5e2cc9376bf"> | <img width="336" alt="Capture d’écran 2023-08-07 à 16 …
=> (PC-23569) fix(videoMultiOffer): change last separator by a spacer

src/features/home/pages/GenericHome.native.test.tsx, src/features/home/pages/ThematicHome.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21142
I have:
=> (PC-21142) fix(home): test thematic and generic home

package.json, yarn.lock
Fix a warning when building webapp.
=> (BSR) chore(deps): update broswerlist latest

doc/eslintCustomRule.md, eslint-custom-rules/__tests__/nbsp-in-text.test.js
Au passage, j'ai fait le ticket : https://passculture.atlassian.net/browse/PC-21172
=> (BSR) docs(eslint): add autofix to custom eslint rule doc

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
I have:
https://console.firebase.google.com/u/0/project/passculture-native/firestore/data/~2FfeatureFlags~2Ftesting?hl=fr
=> (PC-22968) feat(location): add wipEnableAppLocation feature flag

yarn.lock
=> (BSR) feat(web): update caniuse in yarn.lock

ios/Podfile.lock, package.json, src/features/navigation/RootNavigator/useScreenshotListener.native.test.ts, src/features/navigation/RootNavigator/useScreenshotListener.ts, src/features/navigation/RootNavigator/withScreenWrapper.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23664
I have:
=> (PC-23664) feat(screenshot): Track screenshots on ios

__snapshots__/features/trustedDevice/pages/AccountSecurity.native.test.tsx.native-snap, src/features/internal/cheatcodes/pages/NavigationSignUp/NavigationSignUp.tsx, src/features/internal/cheatcodes/pages/NavigationTrustedDevice/NavigationTrustedDevice.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/trustedDevice/fixtures/fixtures.ts, src/features/trustedDevice/pages/AccountSecurity.native.test.tsx, src/features/trustedDevice/pages/AccountSecurity.tsx, src/features/trustedDevice/pages/AccountSecurityBuffer.native.test.tsx, src/features/trustedDevice/pages/AccountSecurityBuffer.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23491
I have:
=> (PC-23491) feat(trustedDevice): add redirect to reinitialize password from account security screen

patches/react-native-detector+0.2.3.patch
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23644
- Je dois faire un patch-package pour ne pas avoir [cette erreur au déploiement](https://github.com/pass-culture/pass-culture-app-native/actions/runs/5831797227/job/15816773698).
- Il y a déjà une [issue ouverte](https://github.com/AzizAK/react-native-detector/issues/51) à ce sujet.
I have:
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf61 …
=> (PC-23664) fix(deploy): Override react-native-detector kotlin version

src/features/offer/components/VenueCard/VenueCard.tsx, src/features/offer/components/VenueDetails/VenueDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23544
I have:
| iOS              |![Capture d’écran 2023-08-11 à 15 44 53](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/41cdf16c-e85f-421a-967e-b86f242451fc)|![Capture d’écran 2023-08-11 à 15 36 25](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/335a204b-2ed4-4150-9722-50441a4e66e5)|
| Phone - Chrome   |![Capture d’écran 2023-08-11 à 15 40 05](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/ec2451a9-1895-4922-bd28-abf6da18f631)|![Capture d’écran 2023-08-11 à 15 36 …
=> (PC-23544) feat(VenueCard): update VenueCard component, adding an arrow icon to be more explicit

src/features/search/components/SearchVenueItems/SearchVenueItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23459
I have:
=> (PC-23459) fix(SearchVenueItem): fix background color icon

src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/birthdayNotifications/components/EighteenBirthdayCard.native.test.tsx, src/features/bookOffer/components/BookingImpossible.native.test.tsx, src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx, src/features/favorites/pages/Favorites.native.test.tsx, src/features/home/api/useVideoOffers.native.test.ts, src/features/home/pages/GenericHome.native.test.tsx, src/features/home/pages/Home.native.test.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx, src/features/profile/pages/ChangePassword/ChangePassword.web.test.tsx, src/features/search/components/SearchHeader/SearchHeader.native.test.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/libs/geolocation/components/WhereSection.native.test.tsx, src/libs/hooks/__tests__/useIsFalseWithDelay.native.test.ts
=> (BSR) refactor(tests): remove useless await act(async () => {})

src/features/bookings/pages/Bookings/Bookings.web.test.tsx, src/features/favorites/pages/Favorites.web.test.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.web.test.tsx, src/features/search/pages/Search/Search.web.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21801
I have:
=> (PC-21801) feat(accessibility): unskip accessibility tests

src/features/search/components/SearchBox/SearchBox.native.test.tsx, src/features/search/components/SearchBox/SearchBox.tsx, src/features/search/helpers/getIsSearchPreviousRoute/getIsSearchPreviousRoute.test.ts, src/features/search/helpers/getIsSearchPreviousRoute/getIsSearchPreviousRoute.ts, src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffers.tsx, src/shared/getRouteFromIndex/getRouteFromIndex.test.ts, src/shared/getRouteFromIndex/getRouteFromIndex.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23551
I have:
=> (PC-23551) feat(search): improve redirection between search and venue pages

src/features/bookings/components/BookingDetailsTicketContent.tsx, src/features/offer/components/CTAButton/CTAButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23434
I have:
| Desktop - Chrome |<img width="865" alt="Capture d’écran 2023-08-14 à 11 11 50" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/30bb35f2-b48e-4cde-b378-398aa3253121"> <img width="1728" alt="Capture d’écran 2023-08-14 à 11 11 20" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/1cf72d70-5302-4cd1-9fde-13f551eb3d1c">|<img width="865" alt="Capture d’écran 2023-08-14 à 11 05 47" …
=> (PC-23434) feat(icon): use external site filled

__snapshots__/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/auth/api/useResetPasswordMutation.ts, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.web.test.tsx, src/libs/firebase/analytics/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22282
I have:
=> (PC-22282) feat(reinitializePassword): connect user after reinitialize password

__snapshots__/features/bookings/components/NoBookingsView.native.test.tsx.native-snap, __snapshots__/features/favorites/pages/Favorites.native.test.tsx.native-snap, __snapshots__/features/home/pages/Home.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchHeader/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/favorites/components/NumberOfResults.tsx, src/features/home/components/headers/HomeHeader.tsx, src/features/profile/components/Header/HeaderWithGreyContainer/HeaderWithGreyContainer.tsx, src/features/profile/components/Subtitle/Subtitle.tsx, src/features/search/components/SearchHeader/SearchHeader.native.test.tsx, src/features/search/components/SearchHeader/SearchHeader.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.tsx, src/ui/components/NoResultsView.tsx, src/ui/components/headers/PageHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23743
I have:
=> (PC-23743) feat(ui): update main pages subtitles

server/src/middlewares/tests/webAppProxyMiddleware.test.ts, server/src/middlewares/webAppProxyMiddleware.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23559
I have:
=> (PC-23559) feat(seo): De-index search pages with params

src/features/offer/components/VenueCard/VenueCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23544
I have:
=> (PC-23544) fix(VenueCard): fix icon size and improvement on the width for the card

__snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, src/features/offer/components/LocationCaption.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23896
I have:
| iOS              |        | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/4431cbd0-aefa-4dd8-bd02-9d8aaed11c80"> |
| Phone - Chrome   | <img width="376" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/8d44c087-b79e-47be-8490-662a445444e4"> | <img width="376" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/8912abd8-6927-4ccb-a2bf-6fea6b5e1b35"> |
| Desktop - Chrome | <img width="1512" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/ass …
=> (PC-23896) fix(offer): fix space for digital offer location

__snapshots__/features/bookings/pages/Bookings/Bookings.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap, src/features/bookings/components/EndedBookingItem.native.test.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/OnGoingBookingItem.native.test.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/pages/Bookings/Bookings.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23211
I have:
| iOS              |        |   <img width="274" alt="Capture d’écran 2023-08-16 à 15 47 56" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/23090f0b-4a71-458d-9120-ac107212b79f"> <img width="275" alt="Capture d’écran 2023-08-16 à 14 51 21" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/682a2510-1954-47eb-83f8-89b4f872605a"> |
| Desktop - Chrome |        |  <img width="1018" alt="Capture d’écran 2023-08-16 à 15 48 43" …
=> (PC-23211) feat(bookings): add share button for booking offers

src/features/offer/api/useAlgoliaSimilarOffers.native.test.ts, src/features/offer/api/useAlgoliaSimilarOffers.ts, src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/api/useSimilarOffers.ts, src/features/offer/helpers/getSimilarOffersInOrder/getSimilarOffersInOrder.test.ts, src/features/offer/helpers/getSimilarOffersInOrder/getSimilarOffersInOrder.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23685
I have:
| Desktop - Chrome |<img width="1728" alt="Capture d’écran 2023-08-17 à 15 01 11" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/fb92ce27-fba3-45e7-97d9-26b92acaa0fd">|<img width="1723" alt="Capture d’écran 2023-08-17 à 15 00 47" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/06c2e2cc-7659-4d7f-a264-6c8fe3853093">|
[1]: …
=> (PC-23685) feat(offer): display similar offers in the order received by the API

src/features/onboarding/components/OnboardingTimeline.stories.tsx, src/features/onboarding/components/OnboardingTimeline.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22665
I have:
| Desktop - Chrome |        | <img width="92" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/8f25b501-51b6-4ece-9302-d60d22b91cf7"> |
=> (PC-22665) feat(onboarding): Create onboarding timeline component

src/features/home/api/useHomepageData.ts, src/features/home/fixtures/homepageList.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/adaptHomepageEntries.ts, src/libs/contentful/fixtures/homepageEntriesAPIResponse.ts, src/libs/contentful/fixtures/homepageNatifEntry.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21345
I have:
=> (PC-21345) feat(home): align contentful structure for thematic headers

src/features/offer/components/VenueCard/VenueCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23544
I have:
=> (PC-23544) fix(VenueCard): using the correct icon

src/api/apiHelpers.native.test.ts, src/api/apiHelpers.ts, src/features/auth/context/AuthContext.native.test.tsx, src/features/auth/context/AuthContext.tsx, src/features/bookings/pages/Bookings/Bookings.perf.test.tsx, src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx, src/features/favorites/pages/Favorites.perf.test.tsx, src/features/profile/pages/Profile.perf.test.tsx, src/features/profile/pages/Profile.tsx, src/libs/__mocks__/jwt.ts, src/libs/eduConnectClient.ts, src/libs/jwt/__mocks__/jwt.ts, src/libs/jwt/jwt.test.ts, src/libs/jwt/jwt.ts, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21132
I have:
=> (PC-21132) feat(auth): Remove token logic redundant with apiHelpers

src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23349
I have:
=> (PC-23349) feat(search): add VenuePlaylistDisplayedOnSearchResults tracker

src/features/home/components/headers/AnimatedHighlightThematicHomeHeader.tsx, src/features/home/pages/ThematicHome.native.test.tsx, src/features/home/pages/ThematicHome.tsx, src/features/home/types.ts, src/ui/animations/helpers/useOpacityTransition.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22484
Implemented only for iOS
I have:
| iOS              |    https://github.com/pass-culture/pass-culture-app-native/assets/47600889/2163152b-73ab-4854-a749-bbe634e02e9c|
| Web (non-reg) |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/b4c4c99b-629d-40e1-b159-476a215d5a0c| 
=> (PC-22484) feat(home): add header image zoom animation on scroll

src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.test.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23882
I have:
=> (PC-23882) feat(fetchOffersAndVenues): use new index

src/features/home/pages/GenericHome.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22102
Testé avec différentes configurations réseau avec l'outil Network Link Conditioner
I have:
| Desktop - Chrome |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/a3789f23-aeb4-47cd-8d60-ac87fc75cf89|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/5373a90c-2b76-4abd-aabb-762a821dbf24|
| Desktop - Chrome |        |<img width="1511" alt="Capture d’écran 2023-08-21 à 11 47 23" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/101f6a7c-6b6a-44c2-afac-ca515fd24bc3">|
=> (PC-22102) feat(home): add progressive modules loading for web

src/features/auth/context/AuthContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21132
PR pour corriger la connexion qui ne marchait plus, à cause d'un délai trop élevé pour setTimeout.
I have:
=> (PC-21132) fix(AuthContext): Handle max delay for setTimeout

src/features/auth/context/AuthContext.tsx
=> (BSR) fix(ci): Fix native and web build

__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/search/components/SearchVenueItems/SearchVenueItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23458
I have:
| Desktop - Chrome |<img width="1109" alt="Capture d’écran 2023-08-21 à 14 24 21" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/a93f8e65-7e9a-422d-84eb-954eb815b5e1">|<img width="1130" alt="Capture d’écran 2023-08-21 à 14 23 15" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/379355d7-698d-4eaa-b055-b5bc0afb7225">|
[1]: …
=> (PC-23458) feat(search): visual improvement playlist

src/features/home/components/modules/OffersModule.native.test.tsx, src/features/home/components/modules/OffersModule.tsx, src/features/home/components/modules/RecommendationModule.tsx, src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23350
I have:
=> (PC-23350) feat(search): call AllTilesSeen log when scrolling to the end of search venue playlist

__snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap, src/features/bookings/pages/EndedBookings/EndedBookings.tsx, src/features/home/components/modules/HomeModule.tsx, src/features/home/components/modules/video/VideoPlayer.web.tsx, src/ui/components/headers/PageHeaderWithoutPlaceholder.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23816
Sondage en cours pour mettre en commun la logique du Header : 
https://passcultureteam.slack.com/archives/G01C85B6DHA/p1692711903404469
I have:
-> https://www.notion.so/passcultureapp/Safari-Blur-manquant-dans-un-header-932b3d35542b465fbe9ac20cdd5eabe1
| Phone - Chrome   | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/3c1de940-edeb-4bb5-9275-16d72429d209) | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/f4242646-1d28-4ed3-9d62-c9c0bc6162e8) |
=> (PC-23816) feat(endedBookings): make header white and blurred

src/api/apiHelpers.native.test.ts, src/api/apiHelpers.ts, src/features/auth/context/AuthContext.native.test.tsx, src/features/auth/context/AuthContext.tsx, src/features/bookings/pages/Bookings/Bookings.perf.test.tsx, src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx, src/features/favorites/pages/Favorites.perf.test.tsx, src/features/profile/pages/Profile.perf.test.tsx, src/features/profile/pages/Profile.tsx, src/libs/__mocks__/jwt.ts, src/libs/eduConnectClient.ts, src/libs/jwt/__mocks__/jwt.ts, src/libs/jwt/jwt.test.ts, src/libs/jwt/jwt.ts, src/libs/storage.ts
Revert des 3 commits qui ont changés le comportement
Si tu approuves, et que tout passes, tu peux toi meme merger si tu veux
I have:
=> (BSR) fix(login): there is login issues since the behavior improvements

src/features/navigation/RootNavigator/types.ts, src/features/offer/components/OfferTile/OfferTile.tsx, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.test.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts, src/features/offer/pages/Offer/Offer.tsx, src/features/offer/types.ts, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/search/components/SearchVenueItems/SearchVenueItem.native.test.tsx, src/features/search/components/SearchVenueItems/SearchVenueItem.tsx, src/features/venue/components/VenueOffers/VenueOffers.tsx, src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23354
I have:
=> (PC-23354) feat(search): add params to ClickBookoffer log

__snapshots__/features/onboarding/pages/AgeInformation.native.test.tsx.native-snap, src/features/onboarding/components/OnboardingTimeline.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22663
I have:
| iOS              |<img width="308" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/08d8df29-89aa-4a6d-955d-cb83b4c6d33f">|<img width="312" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/9190cdb1-a837-4954-8700-1e74fedde7e4">|
=> (PC-22663) fix(onboarding): add description for 18 credit block

.github/workflows/dev_on_workflow_environment_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22911
Fastlane need an extra secret to run "pilot". To be able to deploy on production this secret has to be had
=> (PC-22911) fix(ci): add new secret for fastlane

src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/search/components/AutocompleteVenue/AutocompleteVenue.native.test.tsx, src/features/search/components/AutocompleteVenue/AutocompleteVenue.tsx, src/features/search/components/AutocompleteVenueItem/AutocompleteVenueItem.native.test.tsx, src/features/search/components/AutocompleteVenueItem/AutocompleteVenueItem.tsx, src/features/search/components/SearchVenueItems/SearchVenueItem.native.test.tsx, src/features/search/components/SearchVenueItems/SearchVenueItem.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.tsx, src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23352
I have:
=> (PC-23352) feat(venue): add tracker on venue suggestion press

.github/workflows/dev_on_workflow_environment_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22911
=> (PC-22911) fix(ci): Service account android is only present for production env

src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24055
I have:
| Desktop - Chrome | <img width="401" alt="CleanShot 2023-08-25 at 10 44 53@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/d7e72412-f02c-440a-939a-ac8b73c7f28c"> | <img width="404" alt="CleanShot 2023-08-25 at 10 43 57@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/ea36bd94-ca64-4908-bd8f-9875d57ac7ee"> |
[1]: …
=> (PC-24055) feat(search): do not display venues playlist if search from venue

.eslintrc.js, doc/development/how-to/trackers.md, package.json, scripts/add_tracker.py, src/libs/amplitude/events.ts, src/libs/analytics/logEventAnalytics.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23884
Réalisé en mob avec @anoukhello @tanguyprache @thconte et @voisinhugo
=> (PC-23884) chore(analytics): add script to add tracker

src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23702
I have:
=> (PC-23702) feat(search): dismiss keyboard on scroll on autocomplete menu

src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22293
I have:
=> (PC-22293) fix(sentry): fix error with data being undefined

__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/components/SearchResults/SearchResults.web.test.tsx, src/features/search/helpers/usePrevious.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.test.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/helpers/buildSearchVenuePosition.test.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/helpers/buildSearchVenuePosition.ts, src/libs/algolia/fetchAlgolia/helpers/getCurrentVenuesIndex.test.ts, src/libs/algolia/fetchAlgolia/helpers/getCurrentVenuesIndex.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23999
I have:
=> (PC-23999) feat(search): use user position when location filter is everywhere to build search query

src/features/profile/helpers/formatDateToLastUpdatedAtMessage.native.test.ts, src/features/profile/helpers/formatDateToLastUpdatedAtMessage.ts, src/libs/parsers/formatDates.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23523
I have:
| iOS              |![IMG_8209](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/5bb52288-bf7c-41a9-a429-b71dc40611e4)|![IMG_8208](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/961ed8dc-367f-4959-aa39-bb11cba7bfa4)|
=> (PC-23523) feat(profile): localize ubble instruction update date

server/src/utils/metas.ts, server/src/utils/tests/metas.test.ts, server/tests/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23963
I have:
=> (PC-23963) feat(security): Encode metadata before injecting in html

.eslintrc.js, eslint-custom-rules/__tests__/no-truthy-check-after-queryAll-matchers.test.js, eslint-custom-rules/no-truthy-check-after-queryAll-matchers.js, eslint-local-rules.js, src/features/navigation/RootNavigator/RootNavigator.native.test.tsx, src/features/navigation/RootNavigator/RootNavigator.web.test.tsx, src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24059
=> (PC-24059) feat(eslint): add rules to avoid queryAll with toBeTruthy()

src/features/offer/components/OfferTile/OfferTile.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23353
I have:
=> (PC-23353) feat(offer): use searchId in ConsultOffer log

src/features/auth/pages/signup/SetBirthday/SetBirthday.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.web.test.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.web.tsx, src/ui/components/inputs/DateInput/DatePicker/types.ts, src/ui/components/inputs/DateInput/atoms/DateInputDesktop.web.tsx, src/ui/components/inputs/DropDown/DropDown.stories.tsx, src/ui/components/inputs/DropDown/DropDown.tsx, src/ui/components/inputs/DropDown/DropDown.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23973
I have:
[screen-recording (1).webm](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/e8718b7f-2d08-487f-b316-769e99a407de)
=> (PC-23973) feat(signup): make email and birthdate persistant for web desktop

__snapshots__/features/location/components/LocationModal.native.test.tsx.native-snap, src/features/home/components/modules/video/VideoModal.native.test.tsx, src/features/location/components/LocationModal.native.test.tsx, src/features/location/components/LocationModal.tsx, src/features/location/components/LocationModalButton.tsx, src/features/location/components/LocationWidget.native.test.tsx, src/features/location/components/LocationWidget.stories.tsx, src/features/location/components/LocationWidget.tsx, src/features/location/enums.ts, src/tests/utils.tsx, src/ui/svg/icons/PositionFilled.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23179
I have:
| Platform         | iOS |  Android  |
| :--------------- | :----: | :----: |
| No selection              |![Simulator Screen Shot - iPhone 14 - 2023-08-29 at 12 09 31](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/f2b50c54-0308-4454-af31-2cdc4b246ff7)|<img width="370" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/ff4de60e-1f14-42e4-8dcd-0af2b44c036f">|
| First option selected          |![Simulator Screen Shot - iPhone 14 - 2023-08-29 at 12 09 34](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/09cdd2d2-f3b1-4737-b6a9-1efcd8540151)|<img width="368" alt="Capture d’écran 2023-08-29 à 12 25 …
=> (PC-23179) feat(localization): localization modal design

.github/workflows/dev_on_push_workflow_main.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24112)
=> (PC-24112) feat(ci): Add a soft deploy staging

.github/dependabot.yml
=> (BSR) chore(dependabot): update dependabot config

.github/dependabot.yml
=> (BSR) fix(dependabot): fix dependabot config

server/jest.config.ts, server/package.json, server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap, server/src/middlewares/tests/webAppProxyMiddleware.test.ts, server/yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24014
I have:
=> (PC-24014) test(proxy): Check metadata fields instead of snapshot

__snapshots__/features/bookings/pages/Bookings/Bookings.native.test.tsx.native-snap, __snapshots__/features/favorites/pages/Favorites.native.test.tsx.native-snap, __snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap, __snapshots__/features/home/pages/Home.native.test.tsx.native-snap, __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, android/app/build.gradle, src/features/home/pages/GenericHome.tsx, src/features/home/pages/Home.tsx, src/features/location/components/LocationWidget.native.test.tsx, src/features/location/components/LocationWidget.tsx, src/features/location/components/LocationWidget.web.test.tsx, src/libs/accessibilityRole/accessibilityRole.ts, src/libs/accessibilityRole/accessibilityRole.web.ts, src/libs/react-native-animatable/index.ts, src/libs/storage.ts, src/theme/index.ts, src/ui/components/Tooltip.stories.tsx, src/ui/components/Tooltip.tsx, src/ui/components/headers/PageHeader.tsx, src/ui/components/snackBar/SnackBar.native.test.tsx, src/ui/components/snackBar/SnackBar.tsx, src/ui/theme/colors.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23704
I have:
| Platform         | Mockup | Implemented |
| iOS              |  | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/0d00316d-78bb-43cd-9411-dd469595e03e"> |
| iOS - loading          |        | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/cc4b97e1-f21f-4512-979e-3fbc5cc2e9af"> |
| iOS - short widget |  | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/b154debd-750e-4ff1-9cd3-38c7d112b26b"> |
| iOS - wide widget |  | <img width="503" alt="image" …
=> (PC-23704) feat(home): add tooltip to location widget

__snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, src/features/internal/cheatcodes/components/CheatMenuButton.tsx, src/ui/theme/layers.ts
=> (BSR) fix(cheatcode): increase button click size

__snapshots__/features/home/components/modules/venues/VenueDetails.native.test.tsx.native-snap, __snapshots__/features/home/components/modules/venues/VenueTile.native.test.tsx.native-snap, __snapshots__/features/home/components/modules/venues/VenuesModule.native.test.tsx.native-snap, src/features/home/components/modules/venues/VenueDetails.native.test.tsx, src/features/home/components/modules/venues/VenueDetails.tsx, src/features/home/components/modules/venues/VenueTile.native.test.tsx, src/features/home/components/modules/venues/VenueTile.tsx, src/features/home/types.ts, src/libs/algolia/fetchAlgolia/fetchVenuesModules.ts, src/libs/algolia/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23850
I have:
| Desktop - Chrome | <img width="804" alt="CleanShot 2023-09-01 at 15 31 43@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/19b52dcb-c035-4a57-af25-65de2d19002a"> | <img width="809" alt="CleanShot 2023-09-01 at 15 32 00@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/230173b2-63b0-49f7-9dd6-98ec413eb700"> |
[1]: …
=> (PC-23850) feat(home): add similar info to home

__mocks__/react-native-keychain.ts, src/api/apiHelpers.native.test.ts, src/api/apiHelpers.ts, src/features/auth/context/AuthContext.native.test.tsx, src/features/auth/context/AuthContext.tsx, src/features/bookings/pages/Bookings/Bookings.perf.test.tsx, src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx, src/features/favorites/pages/Favorites.perf.test.tsx, src/features/profile/pages/Profile.perf.test.tsx, src/features/profile/pages/Profile.tsx, src/libs/__mocks__/jwt.ts, src/libs/eduConnectClient.ts, src/libs/jwt/__mocks__/jwt.ts, src/libs/jwt/fixtures.ts, src/libs/jwt/jwt.test.ts, src/libs/jwt/jwt.ts, src/libs/keychain/keychain.native.test.ts, src/libs/keychain/keychain.web.ts, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23996
I have:
=> (PC-23996) feat(AuthContext): Remove refresh token call redundant with apiHelpers

__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/api/useSearchResults/useSearchResults.native.test.ts, src/features/search/api/useSearchResults/useSearchResults.ts, src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/search/context/SearchVenuesWrapper.tsx, src/features/search/context/reducer.test.ts, src/features/search/context/reducer.ts, src/features/search/types.ts, src/libs/algolia/__mocks__/mockedAlgoliaResponse.ts, src/libs/algolia/fetchAlgolia/fetchOffersAndVenues/fetchOffersAndVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24070
I have:
| Desktop - Chrome | <img width="312" alt="CleanShot 2023-09-06 at 15 34 12@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/b5a5babc-b6c0-4e8f-a89b-e0dd76be43b7"> | <img width="287" alt="CleanShot 2023-09-06 at 15 34 30@2x" src="https://github.com/pass-culture/pass-culture-app-native/assets/114916654/0c326a2b-3025-4fbb-adba-f41e18f7db1b"> |
[1]: …
=> (PC-24070) feat(search): show custom playlist title

src/features/home/components/headers/HomeHeader.native.test.tsx, src/features/location/components/LocationWidget.native.test.tsx, src/features/location/components/LocationWidget.tsx, src/features/location/components/LocationWidget.web.test.tsx, src/ui/components/Tooltip.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23704
I have:
=> (PC-23704) fix(home): hide tooltip when navigating

__snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap, src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.native.test.tsx, src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/internal/marketingAndCommunication/config/deeplinksExportConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24211
I have:
Ouverture de la modale vidéo qui s'ouvre également testé sur iPhone physique ✅
| Platform         | Generator / Before| Result / After |
| Stepper  not connected            |<img width="1512" alt="gen_stepper" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/0d36fb01-d531-422c-b63e-fb67f816f022">|<img width="1512" alt="steppe_not_connected" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/45a591b7-f2f9-4f49-a488-eede6a8ec20e">|
| Stepper connected            |<img width="1512" alt="gen_stepper" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/0d36fb01-d531-422c-b63e-fb67f816f022">|<img …
=> (PC-24211) feat(deeplink): add stepper deeplink and from parameter

src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/api/useSimilarOffers.ts, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferTile/OfferTile.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx, src/features/offer/helpers/getIsLoadedOfferPosition/getIsLoadedOfferPosition.test.ts, src/features/offer/helpers/getIsLoadedOfferPosition/getIsLoadedOfferPosition.ts, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/features/offer/types.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/__tests__/logEvent.native.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23950
I have:
=> (PC-23950) feat(offer): preserve api reco params

src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx
…
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23539
I have:
=> (PC-23539) feat(OfferBody): add tracker ConsultOffer when new offerVenue is selected

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, src/features/identityCheck/components/IconRetryStep.tsx, src/features/identityCheck/components/IconStepDone.tsx, src/features/identityCheck/components/StepButton.tsx, src/features/identityCheck/pages/Stepper.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23570
I have:
=> (PC-23570) refactor(UI): reshape subscription stepper

src/features/bookOffer/pages/BookingConfirmation.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/favorites/components/Favorite.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.web.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.tsx, src/features/offer/components/OfferMessagingApps/OfferMessagingApps.tsx, src/features/profile/pages/Profile.tsx, src/features/share/components/MessagingApps/InstalledMessagingApps.native.test.tsx, src/features/share/components/MessagingApps/InstalledMessagingApps.tsx, src/features/share/helpers/getOfferUrl.test.ts, src/features/share/helpers/getOfferUrl.ts, src/features/share/helpers/shareApp.ts, src/features/share/helpers/useShareOffer.native.test.ts, src/features/share/helpers/useShareOffer.ts, src/features/share/helpers/useShareVenue.native.test.ts, src/features/share/helpers/useShareVenue.ts, src/features/share/pages/ShareAppModal.tsx, src/features/venue/components/VenueBody/VenueBody.native.test.tsx, src/features/venue/components/VenueHeader/VenueHeader.tsx, src/features/venue/components/VenueMessagingApps/VenueMessagingApps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24083
I have:
=> (PC-24083) feat(share): Add utm params to share url

src/features/home/components/modules/RecommendationModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23946
I have:
Nouveau paramètre dans l'event ConsultOffer, depuis une playlist de recommendation : 
=> (PC-23946) feat(analytics): send home entry id from reco

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24319
I have:
=> (PC-24319) feat(offer): add wipEnableGTLPlaylistsInBookstoreVenues feature flag

src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23895
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/1a8a7f11-387e-4ba9-95d7-5cc989b72baf
=> (PC-23895) fix(LocationModal): fix bug on geolocalisation for Search Landing page

src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.tsx, src/features/search/pages/Search/Search.web.test.tsx, src/features/tutorial/helpers/getBackgroundColor.native.test.ts, src/features/tutorial/helpers/getTagColor.native.test.ts, src/libs/styled/index.web.tsx, src/libs/styled/native/ThemeProvider.tsx, src/libs/styled/useComputedTheme.ts, src/shared/offer/components/AuthenticationModal/AuthenticationModal.tsx, src/tests/computedTheme.tsx, src/theme/index.ts, src/ui/components/achievements/components/GenericAchievementCard/GenericAchievementCard.tsx, src/ui/components/buttons/ButtonPrimary.ts, src/ui/components/buttons/ButtonSecondary.ts, src/ui/components/buttons/ButtonSecondaryWhite.ts, src/ui/components/hero/Hero.tsx, src/ui/components/snackBar/SnackBar.stories.tsx, src/ui/theme/buttonHeights.ts, src/ui/theme/iconSizes.ts, src/ui/theme/illustrationSizes.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24386
=> (PC-24386) test(types): simplify theme typing

src/features/bookings/helpers/expirationDateUtils.test.ts, src/features/bookings/helpers/expirationDateUtils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24238
I have:
| iOS              |<img width="445" alt="Capture d’écran 2023-09-14 à 10 28 59" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/e162ae53-3929-473f-a7f4-548f986ee4f1">|<img width="444" alt="Capture d’écran 2023-09-14 à 10 30 06" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/531f8cf3-d85f-4a7c-851b-3bc4b74317f9">|
| Android          |<img width="427" alt="Capture d’écran 2023-09-14 à 10 28 50" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/9efe310e-fa4d-4699-ae15-97c132a53d92">|<img width="426" alt="Capture …
=> (PC-24238) feat(booking): display that the offer will be archived when category to archieve offer is free at booking time and becomes paid

src/features/tutorial/components/profileTutorial/EligibleFooter.native.test.tsx, src/features/tutorial/components/profileTutorial/EligibleFooter.test.tsx, src/features/tutorial/components/profileTutorial/EligibleFooter.tsx, src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx, src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24298
I have:
| iOS              |        |<img width="334" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a2731acc-3552-4ecf-8da0-f3f341d36d68">|
| Android          |        |<img width="406" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/bb393d5a-63e5-4dd2-b982-122e928daf28">|
| Phone - Chrome   |        | <img width="396" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/45b11137-0d95-44e3-907a-7d409dc102ca"> |
| Desktop - Chrome |        |<img width="1190" …
=> (PC-24298) feat(ProfileTutorial): create eligible footer in tutorial

src/features/offer/pages/OfferDescription/OfferDescription.native.test.tsx, src/features/offer/pages/OfferDescription/OfferDescription.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24363
I have:
| :---------------| :---: |
| Web               |     [web.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/74a63453-690d-4883-9458-eb55ab85b45f)  |
=> (PC-24363) fix(OfferDescription): Navigate to offer on go back click

src/features/offer/components/SelectableListItem/SelectableListItem.tsx, src/features/offer/components/VenueDetails/VenueDetails.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.stories.tsx, src/features/offer/components/VenueSelectionListItem/VenueSelectionListItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24431
I have:
| Desktop - Chrome |        |![Capture d’écran 2023-09-13 à 16 51 28](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/8140c681-2b2d-42bb-9c2c-6fef28e848b0)![Capture d’écran 2023-09-13 à 16 51 58](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/99679f0f-eaf6-400d-815a-40455159b0e4)|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a75 …
=> (PC-24431) fix(SelectableListItem): fix the height when we have a distance tag

.github/workflows/dev_on_workflow_tester.yml, package.json, server/app.yaml, server/package.json, server/yarn.lock, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24491
To fix : https://github.com/pass-culture/pass-culture-app-native/security/dependabot/35
=> (PC-24491) chore(deps): update eslint lib for security purpose

src/api/gen/api.ts, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24048
I have:
| Platform         |  After |
| iOS              |      [ios.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/c8d8b9a8-d580-402b-8a9e-1edbd9ec398f)   |
| Desktop - Chrome |     [web.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/9c97480c-4695-405d-b5e7-a6a361b6ccdd)   |
=> (PC-24048) feat(Login): Add recaptcha to login

src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx, src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23885
I have:
=> (PC-23885) feat(booking): add playlistType from Offer route to BookingConfirmation log

src/features/home/api/useVideoOffers.native.test.ts, src/features/home/api/useVideoOffers.ts, src/features/home/components/modules/video/VideoMultiOfferPlaylist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24183
I have:
| iOS / Android          |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/b56f28d0-a0a1-4bc1-a7d9-2f7b48810fec|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/11553e40-4b9c-483a-acd2-506448358b9c|
| Desktop - Arc |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/e17eaa88-39a7-41ec-a44b-11631248702b|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/f5be9b62-1647-4da6-8780-1d25f269968a|
=> (PC-24183) feat(video): increase video multi offers limit

.github/workflows/README.md
Using app-native instead of main
I have:
=> (BSR) docs(README): fix repository url

doc/installation/iOS.md, doc/installation/setup.md
=> (BSR) fix(devtools): fix clean setup

src/features/gtlPlaylist/hooks/useGTLPlaylists.native.test.ts, src/features/gtlPlaylist/hooks/useGTLPlaylists.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24306
I have:
=> (PC-24306) feat(gtl): do not display empty playlist

package.json, scripts/add_tracker.py, src/features/favorites/components/Favorite.tsx, src/features/home/components/banners/ActivationBanner.native.test.tsx, src/features/home/components/banners/ActivationBanner.tsx, src/features/home/components/headers/HomeHeader.tsx, src/features/identityCheck/pages/Stepper.native.test.tsx, src/features/identityCheck/pages/Stepper.tsx, src/features/internal/cheatcodes/pages/NavigationSignUp/NavigationSignUp.tsx, src/features/navigation/RootNavigator/types.ts, src/features/offer/pages/Offer/Offer.tsx, src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts, src/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx, src/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.tsx, src/shared/offer/helpers/useBookOfferModal.native.test.tsx, src/shared/offer/helpers/useBookOfferModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21366
I have:
=> (PC-21366) feat(stepper): log "stepper displayed" event with from parameter and step to complete

.eslintrc.js, jest.web.config.js, jest/fixJestEnvironmentJsdom.ts, package.json, src/features/auth/context/AuthContext.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx, src/features/bookOffer/helpers/useRotatingText.ts, src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx, src/features/bookings/pages/BookingNotFound/BookingNotFound.tsx, src/features/home/api/useShowSkeleton.ts, src/features/home/pages/GenericHome.tsx, src/features/identityCheck/pages/identification/errors/eduConnect/NotEligibleEduConnect.tsx, src/features/navigation/sanitizeNavigationState.ts, src/features/offer/pages/Offer/Offer.tsx, src/features/offer/pages/OfferNotFound/OfferNotFound.tsx, src/features/venue/pages/VenueNotFound/VenueNotFound.tsx, src/libs/contentful/adapters/adaptHomepageModules.native.test.ts, src/libs/hooks/useIsFalseWithDelay.ts, src/libs/hooks/useWhiteStatusBar.ts, src/libs/hooks/useWhiteStatusBarWithoutReactNavigation.ts, src/libs/network/OfflineModeContainer.tsx, yarn.lock
https://passculture.atlassian.net/browse/PC-24626
`structuredClone` is available in JS, no need to use `lodash` here.
https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
=> (BSR) refactor(lodash): use structuredClone instead of lodash cloneDeep

.github/workflows/dev_on_workflow_environment_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24607
=> (PC-24607) fix(ci): Create and upload source map for sentry

__snapshots__/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.native.test.tsx.native-snap, src/features/auth/api/useResendEmailValidation.ts, src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentPage.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentPage.web.test.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22326
I have:
| Android          |      ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/af057f5c-e1d4-4f0d-84f1-e57f48ceceb2)        |    ![Screenshot_20230922_141235](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/ddf3b4f8-9acc-455a-be51-79320001a886) ![Screenshot_20230922_141845](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/d5b0d8a9-8e21-4021-bbe7-e8f2f6b79a23)   |
| Desktop - Chrome |        -       |   <img width="1438" alt="Capture d’écran 2023-09-22 à 14 18 25" src="https://github.com/pass-culture/pass-culture-app-native/asse …
=> (PC-22326) feat(signup): Handle email validation resends

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_install.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24682
I have:
=> (PC-24682) ci(yarn): POC using gsc for action cache

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_install.yml
This reverts commit 392a275c3f17cea9e73e8be0a5e620187f6514c2.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24652
I have:
=> (PC-24652) ci(yarn): POC using gsc for action cache (#5334) [revert]

src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts, src/features/offer/pages/Offer/Offer.native.test.tsx
Co-authored-by: YassinL <YassinL@users.noreply.github.com>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24674
I have:
=> (PC-24674) feat(booking): add BookingConfirmation log when booked a digital free offer

ios/PassCulture.xcodeproj/project.pbxproj
=> (BSR) fix(ios): project file

src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.native.test.tsx, src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.tsx, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21366
I have:
=> (PC-21366) fix(tracking): log stepper displayed event from verify eligibility page 

.github/workflows/dev_on_workflow_environment_ios_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24607
=> (PC-24607) fix(ci): add missing quote to ios source map upload command

__snapshots__/features/favorites/pages/FavoritesSorts.native.test.tsx.native-snap, __snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx.native-snap, src/ui/components/radioButtons/RadioButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24419
I have:
| iOS              |![Capture d’écran 2023-09-28 à 11 51 50](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/9898fac0-24fa-4e3b-904d-00e0ac4cc854)|![Capture d’écran 2023-09-28 à 11 51 20](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/d572ee19-c0dd-4b1e-b2ce-deb7e0116b82)|
| Android          |![Capture d’écran 2023-09-28 à 11 51 44](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/40c055f4-b526-4111-90b0-6c9079ccb49a)|![Capture d’écran 2023-09-28 à 11 51 12](https://github.com/pass-culture/pass-culture-app-native/ass …
=> (PC-24419) fix(RadioButton): crop the value

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_install.yml, .github/workflows/dev_on_workflow_linter_ts.yml, .github/workflows/dev_on_workflow_tester.yml, .github/workflows/dev_on_workflow_ts_prune.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24682
I have:
=> (PC-24682) ci(yarn): POC cache using mansagroup/gcs-cache-action

src/api/useSearchVenuesOffer/useSearchVenueOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24621
I have:
=> (PC-24621) fix(useSearchVenueOffers): fix sentry error

__snapshots__/features/search/components/SearchHeader/SearchHeader.native.test.tsx.native-snap, __snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/home/components/headers/HomeHeader.tsx, src/features/location/components/LocationWidget.native.test.tsx, src/features/location/components/LocationWidget.stories.tsx, src/features/location/components/LocationWidget.tsx, src/features/location/components/LocationWidget.web.test.tsx, src/features/search/components/SearchHeader/SearchHeader.native.test.tsx, src/features/search/components/SearchHeader/SearchHeader.tsx, src/features/search/components/SearchHeader/SearchHeader.web.test.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23725
I have:
| Platform         | Mockup/Before/Feature flag not enabled | After |
| iOS              |![Simulator Screen Shot - iPhone 13 - 2023-09-25 at 11 21 12](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/fc8ad327-6047-4523-b661-cb5f1ebc3370)|![Simulator Screen Shot - iPhone 13 - 2023-09-25 at 11 20 26](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/5334c018-2db4-40bb-8926-10fa2711591d)|
| Phone - Arc   |<img width="470" alt="Capture d’écran 2023-09-25 à 11 26 06" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/42e90329-1 …
=> (PC-23725) feat(location): add location widget on search page

src/features/bookOffer/pages/BookingConfirmation.native.test.tsx, src/features/bookOffer/pages/BookingConfirmation.tsx, src/features/bookings/components/EndedBookingItem.native.test.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/OnGoingBookingItem.native.test.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/favorites/components/Favorite.native.test.tsx, src/features/favorites/components/Favorite.tsx, src/features/navigation/RootNavigator/useScreenshotListener.native.test.ts, src/features/navigation/RootNavigator/useScreenshotListener.ts, src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.tsx, src/features/offer/components/OfferMessagingApps/OfferMessagingApps.tsx, src/features/venue/components/VenueBody/VenueBody.analytics.native.test.tsx, src/features/venue/components/VenueHeader/VenueHeader.native.test.tsx, src/features/venue/components/VenueHeader/VenueHeader.tsx, src/features/venue/components/VenueMessagingApps/VenueMessagingApps.tsx, src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24095
I have:
=> (PC-24095) fix(analytics): Use distinct params for offer, venue and booking id

doc/installation/iOS.md
Lien vers la doc d'installation d'iOS modifiée : https://github.com/pass-culture/pass-culture-app-native/blob/update-doc/doc/installation/iOS.md
=> (BSR) fix(doc): update iOS installation doc

__snapshots__/features/tutorial/pages/NonEligibleModal.native.test.tsx.native-snap, src/features/tutorial/pages/NonEligibleModal.native.test.tsx, src/features/tutorial/pages/NonEligibleModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24676
I have:
=> (PC-24676) feat(tutorial): Redirect to home on button press

src/features/home/api/useGetOffersData.ts, src/features/home/api/useGetVenuesData.ts, src/features/home/api/useVideoOffers.ts, src/features/home/components/modules/RecommendationModule.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23862
I have:
=> (PC-23862) feat(home): locate home modules according to location mode

__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap, src/features/home/pages/ThematicHome.native.test.tsx, src/features/home/pages/ThematicHome.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23965
I have:
| Platform         | pas géoloc | géoloc |
| home temps fort |![Simulator Screen Shot - iPhone 8 - 2023-10-02 at 14 26 48](https://github.com/pass-culture/pass-culture-app-native/assets/22886846/a77bb34a-d868-42a9-ab1b-384c111fbae8)|![Simulator Screen Shot - iPhone 8 - 2023-10-02 at 14 27 19](https://github.com/pass-culture/pass-culture-app-native/assets/22886846/366e8001-b90c-433e-b7f1-e7e21ac10538)|
| home catégorie |![Simulator Screen Shot - iPhone 8 - 2023-10-02 at 14 27 51](https://github.com/pass-culture/pass-culture-app-native/assets/22886846/a1f85bb1-0eee-48b3-9591-0e86f15bcf5d)|![Simulator Screen Shot - iPhone 8 - 2023-10-02 at 14 29 …
=> (PC-23965) feat(ThematicHome): add geolocation banner

README.md, doc/installation/setup.md, doc/pull-request.md
Lien de la doc : https://github.com/pass-culture/pass-culture-app-native/tree/bsr-fix-links-in-doc
I have:
=> (BSR) fix(doc): fix links in doc

src/libs/hooks/__tests__/useShowReview.native.test.tsx, src/libs/hooks/useShowReview.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24698
I have:
=> (PC-24698) fix(StoreReview): Do not show review if app is in background

src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.tsx, src/libs/hooks/useTimer.native.test.ts, src/libs/hooks/useTimer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24594
I have:
| Platform         | Mockup | After |
| iOS              | <img width="282" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/36abab91-0931-4502-80da-41881bbab4f9"> |  <img width="327" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/98f34575-63da-46b4-b8b1-2f1a7e431841"> |
| Phone - Chrome   |               |<img width="403" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a686631c-889e-434a-888b-71c4f51d055e">|
| Desktop - Chrome |               |<img width="521" alt="image" …
=> (PC-24594) feat(EmailResend): add timer in resend email modal

src/features/location/components/LocationModal.tsx, src/features/search/pages/SuggestedPlacesOrVenues/SuggestedPlaces.tsx, src/features/search/pages/SuggestedPlacesOrVenues/SuggestedResult.tsx, src/features/search/pages/SuggestedPlacesOrVenues/SuggestedVenues.tsx, src/ui/components/TouchableOpacity.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24827
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/ee2d20c6-e930-4dc0-819f-03db82bf4f07
| iOS              | <img width="381" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/59a3be1e-98cd-46fe-ad8d-7f6a1a8a21f6"> | <img width="546" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/3c62d6a3-af70-42a0-90fe-f4ad692654a4"> |
| iOS          | <img width="368" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/405adbb5-aaab-449e-9a0f-38f5fea7f127"> | <img width="546" alt="image" …
=> (PC-24827) fix(modal): fix click on suggestion result

src/features/offer/pages/Offer/Offer.analytics.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/libs/react-native-batch/enums.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24620
I have:
=> (PC-24620) feat(offer): add batch events

.github/dependabot.yml
=> (BSR) chore(deps): update reviewers for dependabot config

__snapshots__/features/search/components/SearchResults/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/components/Buttons/FilterButton/FilterButton.tsx, src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.tsx, src/features/search/components/SearchBox/SearchBox.native.test.tsx, src/features/search/components/SearchBox/SearchBox.tsx, src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/ui/components/Badge/Badge.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24687
I have:
| iOS              | <img width="363" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/2dee359b-14b9-4e0e-a1b5-06f0d844bbb8"> | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/8f780cba-360d-4a3b-9e3e-490437ae1fb1) |
| Phone - Chrome   | <img width="363" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/b13db70f-721e-4fd2-a526-cbce2dce325e"> | <img width="374" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/43e71911-279b-4463-a79c-aa727948950f"> |
| Desktop - Chrome |<img …
=> (PC-24687) feat(search): update design for search filters

src/features/favorites/helpers/getBookingButtonProperties.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24882
I have:
=> (PC-24882) fix(statusType): add conditionnal to get rid off the type error

src/features/search/components/SearchHistory/SearchHistory.native.test.tsx, src/features/search/components/SearchHistory/SearchHistory.stories.tsx, src/features/search/components/SearchHistory/SearchHistory.tsx, src/features/search/components/SearchHistoryItem/SearchHistoryItem.native.test.tsx, src/features/search/components/SearchHistoryItem/SearchHistoryItem.stories.tsx, src/features/search/components/SearchHistoryItem/SearchHistoryItem.tsx, src/features/search/constants.ts, src/features/search/helpers/useSearchHistory/useSearchHistory.native.test.ts, src/features/search/helpers/useSearchHistory/useSearchHistory.ts, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.tsx, src/features/search/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24732
I have:
=> (PC-24732) feat(refactor): search history components

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24448
I have:
=> (PC-24448) fix(instantsearch): avoid dupplicates lib

__snapshots__/features/internal/marketingAndCommunication/pages/UTMParameters.native.test.tsx.native-snap, src/features/cookies/CookiesPolicy.ts, src/features/cookies/enums.ts, src/features/cookies/helpers/setMarketingParams.native.test.ts, src/features/cookies/types.ts, src/features/internal/marketingAndCommunication/pages/UTMParameters.tsx, src/features/navigation/RootNavigator/linking/__tests__/getStateFromPath.test.ts, src/features/navigation/RootNavigator/linking/getStateFromPath.ts, src/libs/storage.ts, src/libs/utm/storeUtmParams.test.ts, src/libs/utm/storeUtmParams.ts, src/libs/utm/types.ts, src/libs/utm/useUtmParams.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24839
I have:
| Desktop - Chrome |      <img width="1440" alt="Capture d’écran 2023-10-06 à 09 24 02" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/cdf3e0b6-c546-435a-a37d-d91b402b57b4">         |   <img width="1440" alt="Capture d’écran 2023-10-06 à 09 23 44" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/885d7f67-dc4c-44b7-9b58-4c5c99801988">    |
=> (PC-24839) feat(utm): Add utm content to firebase parameters

server/src/services/apiClient.ts, server/src/services/tests/apiClient.test.tsx, server/src/utils/__mocks__/logging.ts, server/src/utils/metas.ts, server/src/utils/tests/metas.test.ts, server/tests/constants.ts, server/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24915
I have:
=> (PC-24915) fix(server): fix 502 on bad metadata or 404

src/libs/hooks/useTimer.native.test.ts, src/libs/hooks/useTimer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24892
I have:
| iOS              |     Le timer n'était pas mis à jour          | https://github.com/pass-culture/pass-culture-app-native/assets/46637324/98c3d7bd-6b78-4bf1-884a-8b3781612989  |
=> (PC-24892) feat(timer): Update timer on app resume

scripts/update_app_version.sh, server/package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24923
- Sera utile plus tard pour exposer la version du proxy.
I have:
=> (PC-24923) fix(server): maintain proxy version in package.json

__snapshots__/features/profile/components/CreditExplanation/CreditExplanation.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap, src/features/birthdayNotifications/pages/RecreditBirthdayNotification.tsx, src/features/profile/components/CreditExplanation/CreditExplanation.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.tsx, src/features/profile/components/Header/ProfileHeader/ProfileHeader.tsx, src/features/profile/pages/Profile.tsx, src/shared/user/getAge.ts, src/shared/user/useGetDepositAmountsByAge.ts, src/web/serviceWorkerRegistration.ts, web/js/chunk-protection.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24773
I have:
| iOS              | <img width="356" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/af7e9017-3179-4817-8548-c3fe5f87987b"> | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/3d6670f2-842b-467b-ba6a-b6fd975a2ec8"> |
| Phone - Chrome   | <img width="356" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/df5bb5e8-88ac-4e4e-872b-c2e51426c371"> | <img width="376" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/13190cf7-8692-4a52-b0bc-cc3971632861"> | …
=> (PC-24773) feat(profile): show incoming credit

src/features/search/components/SearchHistory/SearchHistory.tsx, src/features/search/constants.ts, src/features/search/helpers/useSearchHistory/useSearchHistory.native.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24618
I have:
| iOS              |![Capture d’écran 2023-10-09 à 14 28 25](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/e25735cb-ba29-4e21-8a4e-90e7f9b52417)|<img width="450" alt="Capture d’écran 2023-10-09 à 14 26 58" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/e85011d3-ed47-42c0-9f01-3852decbf0c3"> <img width="455" alt="Capture d’écran 2023-10-09 à 14 27 25" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/7f3c06c2-2dca-4a81-ac6f-6031f93df78a">|
| Android          |               |<img width="457" alt="Capture …
=> (PC-24618) feat(search): visual changes search history

src/features/location/components/LocationWidget.stories.tsx, src/ui/components/placeholders/__stories__/BookingHitPlaceholder.stories.tsx, src/ui/components/placeholders/__stories__/FavoriteHitPlaceholder.stories.tsx, src/ui/components/placeholders/__stories__/HitPlaceholder.stories.tsx, src/ui/components/placeholders/__stories__/NumberOfBookingsPlaceholder.stories.tsx, src/ui/components/placeholders/__stories__/NumberOfResultsPlaceholder.stories.tsx
=> (BSR) fix(chromatic): fix stories

server/src/app.ts, server/src/routes/tests/version.test.ts, server/src/routes/version.ts, server/tsconfig.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24938
I have:
=> (PC-24938) feat(proxy): expose proxy version

server/package.json, server/src/app.ts, server/src/routes/tests/version.test.ts, server/src/routes/version.ts, server/tsconfig.json
This reverts commit d6a267a3f08e853c3698daaa7fd09eabaec18e0a.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24938
I have:
=> (PC-24938) feat(proxy): expose proxy version (#5406) [unrevert]

__snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap, __snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/features/profile/components/CreditExplanation/CreditExplanation.tsx, src/features/profile/components/EmptyCredit/EmptyCredit.native.test.tsx, src/features/profile/components/EmptyCredit/EmptyCredit.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.tsx, src/features/profile/components/Header/HeaderWithGreyContainer/HeaderWithGreyContainer.tsx, src/features/profile/components/Subtitle/Subtitle.tsx, src/features/profile/helpers/getHeaderSubtitleProps.ts, src/features/profile/pages/Profile.native.test.tsx, src/features/profile/pages/Profile.tsx, src/ui/svg/icons/BicolorOffers.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24796
I have:
| Platform         | Mockup | After |
| iOS              |       <img width="400" alt="Capture d’écran 2023-10-10 à 11 13 17" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/75d32ab4-daad-49ee-b04b-6436fd3a1cf8">        |     <img width="200" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/c65f5604-c203-4ed6-8cd9-c61f95799609"/>  |
| Desktop - Chrome |               |    <img width="1189" alt="Capture d’écran 2023-10-10 à 11 18 41" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/6947418a-a7d9-46f5-805f-6735464b1094">   |
[1]: …
=> (PC-24796) feat(CreditHeader): Add banner for expired and exhausted credit for users with no upcoming credit

README.md
=> (BSR) docs(installation): enrich doc with errors met during yarn installation

web/config/webpack.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24077
I have:
=> (PC-24077) fix(ubble): Add script to content security policy

src/features/bookings/components/EndedBookingsSection.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/bookings/helpers/getOfferRules.ts, src/features/bookings/pages/EndedBookings/EndedBookings.tsx, src/features/favorites/components/NumberOfResults.tsx, src/features/identityCheck/pages/phoneValidation/CodeNotReceivedModal.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx, src/features/identityCheck/pages/phoneValidation/errors/PhoneValidationTooManySMSSent.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.tsx, src/features/profile/components/Header/CreditHeader/getCreditExpirationText.native.test.ts, src/features/profile/components/Header/CreditHeader/getCreditExpirationText.ts, src/features/search/components/Buttons/FilterButton/FilterButton.tsx, src/features/search/components/NumberOfResults/NumberOfResults.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/pages/SuggestedPlacesOrVenues/HiddenAccessibleResultNumber.tsx, src/features/search/pages/SuggestedPlacesOrVenues/SuggestedPlacesOrVenues.tsx, src/libs/plural.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24795
I have:
| Phone - Chrome   | <img width="267" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/781d9a92-98d1-407e-9928-490146141bc8"> | <img width="378" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/320bfc0d-3b93-41ca-b6d0-889da69cd863"> |
| Desktop - Chrome |               | <img width="1512" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/231d1820-62de-43ac-a3d5-386d067073e6"> |
[1]: …
=> (PC-24795) feat(profile): add warning message for bene 18 expiration

__snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx.native-snap, src/features/tutorial/components/profileTutorial/Timelines/CommonSteps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25039
I have:
| Phone - Chrome   | <img width="399" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/8aa66c5d-c4fc-4ec6-8629-8f9091d002ad">|<img width="400" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/d92a9b25-edce-4a99-b58c-25ebe92006be">|
| Desktop - Chrome | <img width="665" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/bad99cf2-ed17-4e3e-8837-723080645935"> | <img width="663" alt="image" …
=> (PC-25039) feat(ProfileTutorial): add spacers around eighteen separator Step

src/features/offer/api/useOffer.ts, src/libs/monitoring/__tests__/errors.test.ts, src/libs/monitoring/errors.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24943
I have:
=> (PC-24943) feat(offer): capture 404 API error as info

CODEOWNERS
=> (BSR) feat(codeowners): add link to Sentry

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_check_folder_change.yml, .github/workflows/dev_on_workflow_check_proxy_version.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24877
Demo CI : https://github.com/pass-culture/pass-culture-app-native/actions/runs/6482073653/job/17600910037
I have:
=> (PC-24877) ci(webproxy): fix staging/integration/production deployment

src/features/venue/api/useVenue.ts, src/libs/monitoring/errors.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24944
I have:
=> (PC-24944) feat(venue): capture screen error as info

.github/workflows/dev_on_push_workflow_main.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-249877
I have:
=> (PC-249877) ci(webproxy): fix staging/integration/production rollback security

server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap, server/src/services/entities/offer.ts, server/src/services/entities/types.ts, server/src/services/entities/venue.ts, server/src/utils/metas.ts, server/src/utils/tests/__snapshots__/metas.test.ts.snap, server/src/utils/tests/metas.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24485
I have:
=> (PC-24485) feat(proxy): add offer title to <title>

.eslintrc.js, src/features/navigation/sanitizeNavigationState.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24942
as it is not supported on old browser versions
(1.2k users in 11 days)
QRQC : https://www.notion.so/passcultureapp/Sentry-ReferenceError-Can-t-find-variable-structuredClone-c43066602b6f4ee89bc46841c22b59c3
=> (PC-24942) fix(revert): stop using structuredClone

__snapshots__/features/location/components/HomeLocationModal.native.test.tsx.native-snap, __snapshots__/features/location/components/SearchLocationModal.native.test.tsx.native-snap, src/features/location/components/HomeLocationModal.tsx, src/features/location/components/SearchLocationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23862
I have:
| iOS          
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/d6f76529-d367-4978-bff2-7509e39c679d
| Android       
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/18a3be7d-67b3-4edf-b00c-9d0cb84f64eb
=> (PC-23862) feat(SearchLocationModal): scrollable and dismiss keyboard

.github/workflows/wip_create_and_push_tag.yml, .jira.d/templates/view
=> (PC-24028)  ci(GA): add workflow to create and push tag from JIRA automation

src/features/identityCheck/pages/phoneValidation/errors/PhoneValidationTooManyAttempts.tsx, src/ui/components/buttons/externalLink/ExternalLink.tsx, src/ui/components/buttons/externalLink/ExternalLink.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-12710
I have:
| Desktop - Chrome |<img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/548159cf-6570-4545-9830-fb6768f8b74c"><img width="854" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/ff38f8a9-a9a8-453e-86b0-1da28530aba5"><img width="425" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/834dd607-3ed2-461d-94f7-c2a1d88abcf2">|<img width="336" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/da5645ff-bb2e-464e-9b11-b96867ac78a0"><img width="858" alt="image" …
=> (PC-12710) fix(icons): remove last unaccessible icons

__snapshots__/features/location/components/SearchLocationModal.native.test.tsx.native-snap, src/features/location/components/SearchLocationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24879
I have:
screenshot ios : 
screenshot Android :
=> (PC-24879) feat(SearchLocationModal): change default radius

src/features/search/api/useSearchResults/useSearchResults.native.test.ts, src/features/search/api/useSearchResults/useSearchResults.ts, src/features/search/components/NoSearchResults/NoSearchResult.native.test.tsx, src/features/search/components/NoSearchResults/NoSearchResult.tsx, src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25097
I have:
=> (PC-25097) fix(search): improve using of PerformSearch and NoSearchResult logs

src/features/search/components/SearchBox/SearchBox.native.test.tsx, src/features/search/components/SearchMainInput/SearchMainInput.tsx
Link to JIRA ticket:  https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-23726
I have:
| Android          |               |  <img width="458" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/53b2ce3e-b84e-46bb-81a4-ea204ccd957d">  |
| Phone - Chrome   |               |  <img width="484" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/bea4234c-bcb9-45a8-aa0a-f0acd2e33433"> |
| Desktop - Chrome |               |  <img width="1552" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/faa20a1c-045b-4d19-bc98-a30c05be879a"> …
=> (PC-23276) feat(SearchLocationWidget): hide searchLocationWidget on web

src/api/useSearchVenuesOffer/useSearchVenueOffers.ts, src/libs/algolia/fetchAlgolia/fetchOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24980
I have:
=> (PC-24980) fix(offer): fix sentry error by adding type-safe operator

.maestro/README.md
=> (BSR) feat(maestro): update README.md

src/features/search/components/SearchMainInput/SearchMainInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-23726
I have:
=> (PC-23276) feat(SearchLocationWidget): fix useTheme imports

src/libs/analytics/provider.test.ts, src/libs/analytics/provider.ts, src/libs/firebase/analytics/__tests__/logEvent.native.test.ts, src/libs/geolocation/LocationWrapper.native.test.tsx, src/libs/geolocation/LocationWrapper.tsx, src/libs/storage.ts
Link to JIRA ticket:  https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-24991
I have:
- add unit test
- check on web with firebase analytics debugger
=> (PC-24991) feat(LocationType): add location type to logevent

web/config/webpack.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25285
**Avant**
**Après**
I have:
=> (PC-25285) fix(home): add csp *.youtube.com

src/features/location/components/HomeLocationModal.native.test.tsx, src/features/location/components/HomeLocationModal.tsx, src/features/location/components/SearchLocationModal.native.test.tsx, src/features/location/components/SearchLocationModal.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24992
I have:
=> (PC-24992) feat(analytics): tracker UserSetLocation

src/features/search/helpers/categoriesHelpers/mapping-tree.test.ts, src/features/search/helpers/categoriesHelpers/mapping-tree.ts, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24782
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/a7c8e16d-1b76-493d-a9a2-cd47540668f4
=> (PC-24782) feat(CategoriesModal): add nbRsultFacets only for level 2 of categories

__snapshots__/features/tutorial/pages/AgeSelection.native.test.tsx.native-snap, __snapshots__/features/tutorial/pages/TutorialPage.native.test.tsx.native-snap, __snapshots__/features/tutorial/pages/onboarding/OnboardingAgeInformation.native.test.tsx.native-snap, __snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx.native-snap, src/features/tutorial/components/CreditStatusTag.tsx, src/features/tutorial/pages/TutorialPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24832
Parmi les 4 retours a11y, 2 sont fix ici, les 2 autres ont des tickets créés (car + complexes)
- https://passculture.atlassian.net/browse/PC-25283
- https://passculture.atlassian.net/browse/PC-25284
=> (PC-24832) fix(a11y): a11y fixes for the tutorial page

src/features/gtlPlaylist/components/GtlPlaylist.native.test.tsx, src/features/gtlPlaylist/components/GtlPlaylist.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25050
I have:
=> (PC-25050) feat(gtlPlaylist): use ModuleDisplayed log

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25138
I have:
=> (PC-25138) feat(wipSameAuthorPlaylist): add a new feature flag wipSameAuthorPlaylist

.vscode/extensions.json
Add jestRunner to recommended extensios
=> (BSR) docs(devtools): add JestRunner to recommendations

src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25280
I have:
=> (PC-25280) fix(ProfileTutorial): fix sentry error on user status

.github/workflows/dev_on_push_workflow_main.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25299
To avoid hight load cpu on nodes we should limit pipeline execute on master/tags/pull request
=> (PC-25299) feat(ci): limit pipeline run on master, pull request and tags

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20118
I have:
=> (PC-20118) chore(lib): update appcenter cli

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_check_folder_change.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25127
I have:
=> (PC-25127) ci(storybook): fix deployment

__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/components/SearchList/SearchList.web.tsx, src/features/search/components/SearchListItem.web.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/components/SearchResults/SearchResults.web.test.tsx, src/features/search/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24929
Cette PR prend en compte les nouvelles remarques qui ont émergé sur mon ancienne PR https://github.com/pass-culture/pass-culture-app-native/pull/5448
I have:
=> (PC-24929) refactor(search): apply PR feedbacks

src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24769
I have:
| iOS              |               |![Capture d’écran 2023-10-19 à 18 05 17](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/bae27c27-0db9-47c6-956b-884900f6ff5f)|
| Phone - Chrome   |<img width="392" alt="Capture d’écran 2023-10-19 à 18 02 25" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/9aa34b65-4714-4f94-847b-213207108ad7">|<img width="392" alt="Capture d’écran 2023-10-19 à 17 58 03" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/f0ba2442-79c9-4a09-b22d-6942 …
=> (PC-24769) feat(Categories): adjust wording for nbResultFacets

__snapshots__/features/location/components/HomeLocationModal.native.test.tsx.native-snap, __snapshots__/features/location/components/SearchLocationModal.native.test.tsx.native-snap, src/features/location/components/HomeLocationModal.tsx, src/features/location/components/SearchLocationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23862
Added StyledScrollView to modals that needed to Scroll. Removed padding to the AppModal component to gat the right placement of the scrollbar. Added custom Header with padding.
I have:
Android            
=> (PC-23862) fix(UI): scrollbar placement in location modals

src/features/tutorial/pages/AgeSelection.native.test.tsx, src/features/tutorial/pages/AgeSelection.tsx, src/features/tutorial/pages/AgeSelectionOther.native.test.tsx, src/features/tutorial/pages/AgeSelectionOther.tsx, src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25344
I have:
=> (PC-25344) fix(tracking): fix SelectAge tracker params age

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/jira_create_and_push_staging_testing_deploy_tags.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25417
I have:
=> (PC-25417) fix(ci): correction tag workflow

.github/workflows/dev_on_push_workflow_main.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25417
I have:
=> (PC-25417) fix(ci): correction glob pattern pour la ci tag

package.json, server/package.json
=> (BSR) fix(ci): revert package version bump

src/api/gen/api.ts, src/features/auth/context/__mocks__/SettingsContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24587
I have:
=> (PC-24587) refactor(app): remove useless proDisableEventsQrcode feature flag

.github/workflows/dev_on_workflow_check_proxy_version.yml
Switch to predicate with `ge` comparator 
**Exemple**
```
on ⛵ teleport.passculture.team in (database-operations) pass-culture-app-native on  master [$!] via  v18.7.0 via 💎 v2.7.4 on ☁️  gcpadmin.dimitri.kopriwa@passculture.app(passculture-metier-prod) 
❯ semver-compare 1.260.2 ge 1.262.2; echo $?
1
on ⛵ teleport.passculture.team in (database-operations) pass-culture-app-native on  master [$!] via  v18.7.0 via 💎 v2.7.4 on ☁️  gcpadmin.dimitri.kopriwa@passculture.app(passculture-metier-prod) 
❯ semver-compare 1.262.2 ge 1.262.2; echo $?
0
on ⛵ teleport.passculture.team in (database-operations) pass-culture-app-native on  master [$!] via  v18.7.0 via 💎 v2.7.4 on ☁️  gcpadmin.dimitri.kopriwa@passculture.app(passculture-metier-prod) 
❯ semver-compare 1.262.3 ge 1.262.2; echo $?
0
```
I …
=> (BSR) ci(proxy): fix check version greater or equal

src/features/offer/components/OfferBody/OfferBody.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24936
I have:
=> (PC-24936) fix(offer): empty object when subcategory mapping undefined

.github/workflows/jira_create_and_push_staging_testing_deploy_tags.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24028
I have:
https://github.com/pass-culture/pass-culture-app-native/commit/ebb0144bb83dc13bb1f688b1f8e0bbfe8191377a
=> (PC-24028) fix(CI): fix build number bump

src/features/home/components/modules/OffersModule.native.test.tsx, src/features/home/components/modules/OffersModule.tsx, src/features/home/fixtures/homepage.fixture.ts, src/features/home/fixtures/homepageList.fixture.ts, src/features/home/types.ts, src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts, src/libs/contentful/adapters/modules/adaptOffersModule.ts, src/ui/components/PassPlaylist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25349
I have:
| Phone - Chrome   |![Capture d’écran 2023-10-30 à 12 39 40](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/ca27a446-01b6-47ce-a25f-71bfaf5577f6)|<img width="420" alt="Capture d’écran 2023-10-30 à 12 10 28" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/267cb762-263c-4a74-a98d-54dc8be405ed">|
| Desktop - Chrome |![Capture d’écran 2023-10-30 à 12 39 25](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/7a833129-7a41-4b0e-883a- …
=> (PC-25349) feat(home): remove cover from Contentful offers playlists

__snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24997
I have:
=> (PC-24997) feat(SearchResults): keep only venue pill for location filters

src/features/home/components/modules/video/VideoErrorView.tsx
I have:
| Desktop - Chrome   |<img width="536" alt="Capture d’écran 2023-10-31 à 16 38 06" src="https://github.com/pass-culture/pass-culture-app-native/assets/22886846/1c0c67d6-a398-4ab8-a5fd-e2db97649658">|<img width="540" alt="Capture d’écran 2023-10-31 à 16 37 01" src="https://github.com/pass-culture/pass-culture-app-native/assets/22886846/95c8a8db-1f0d-4db4-9767-d4195640064a">|
| Desktop - firefox |![Capture d’écran 2023-10-31 à 15 11 58](https://github.com/pass-culture/pass-culture-app-native/assets/2288 …
=> (PC-25286) fix(video): fix end view on firefox

doc/development/tests/unit-test/cook-book.md, src/features/gtlPlaylist/api/gtlPlaylistApi.native.test.ts, src/features/gtlPlaylist/api/gtlPlaylistApi.ts, src/features/identityCheck/pages/profile/SetCity.native.test.tsx, src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/pages/Offer/Offer.perf.test.tsx, src/features/profile/helpers/useEmailUpdateStatus.native.test.ts, src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx, src/features/profile/pages/ChangePassword/ChangePassword.native.test.tsx, src/features/profile/pages/Profile.perf.test.tsx, src/libs/contentful/constants.ts, src/libs/contentful/fetchHomepageNatifContent.ts, src/libs/recommendation/useHomeRecommendedIdsMutation.native.test.ts, src/tests/mockServer.ts, src/tests/mswServer.ts, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22229
I have:
=> (PC-22229) refactor(tests): add new msw server

__snapshots__/features/search/components/SearchResults/SearchResults.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25336
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/c26b2a8d-4c65-4df7-86e5-442f46605221
=> (PC-25336) feat(SearchResults): venue filter pill open VenueModal

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, src/features/venue/pages/Venue/Venue.native.test.tsx, src/features/venue/pages/Venue/Venue.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25510
I have:
| Desktop - Chrome |               | <img width="1512" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/a9ff225a-84b2-45d0-bb58-02d6e6921d0c"> |
=> (PC-25510) feat(venue): add ff for new venue page

package.json, src/shared/IntersectionObserver/IntersectionObserver.native.test.tsx, src/shared/IntersectionObserver/IntersectionObserver.stories.tsx, src/shared/IntersectionObserver/IntersectionObserver.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25160
I have:
=> (PC-25160) feat(intersectionObserver): add it to detect something visible on the screen

__snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferMessagingApps/OfferMessagingApps.stories.tsx, src/features/offer/components/OfferMessagingApps/OfferMessagingApps.tsx, src/features/share/components/MessagingApps/MessagingApps.tsx, src/features/venue/components/VenueMessagingApps/VenueMessagingApps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25506
I have:
| Desktop - Chrome |<img width="963" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/48abec18-e5b1-4308-abd9-76615838883f"> <img width="908" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/54e8157e-89fa-45a0-b36d-2dc893b7bc19">|<img width="1121" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a7da5e38-8527-46da-82dc-1224b7123372">|
=> (PC-25506) feat(Share): remove bande organisée from messagingApps titles

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25531
I have:
=> (PC-25531) feat(offer): add wipOfferV2 feature flag

__snapshots__/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx.native-snap, src/features/location/components/SearchLocationModal.tsx, src/features/search/components/sections/Venue/Venue.native.test.tsx, src/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx, src/features/search/pages/modals/VenueModal/VenueModal.tsx, src/features/search/pages/modals/VenueModal/type.ts, src/features/search/pages/modals/VenueModal/useVenueModal.native.test.tsx, src/features/search/pages/modals/VenueModal/useVenueModal.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25343
I have:
| iOS              |![simulator_screenshot_AB60ACC1-0B21-496D-A023-3E2B7B5C9C17](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/2c7effa5-5e0a-468b-80fc-c29c54efa138)|![simulator_screenshot_8ABBB713-8C79-4987-8166-AB10B8C06194](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/cffb3715-a06f-4098-b8df-ccabc5bdb923)|
| iOS with keyboard up          |![simulator_screenshot_8CFE5697-EAC6-41B5-A6C3-5B8F657F5F5A](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/f26067c1-0d14-4e34-b7dd-17e9e637b7a5)|![simulator_screenshot_6CBD785C-436F-418B-A6AB-8240E219D89A](htt …
=> (PC-25343) feat(location): add reset button and refacto venue modal

src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25455
=> (PC-25455) fix(venue): remove bannerUrl = undefined from venuebodynew

package.json, yarn.lock
This reverts commit 57baa7606e31100e92588874c77acb919ecc47a2. because https://github.com/chanzuckerberg/axe-storybook-testing/issues/84 
I have:
=> (BSR) build(storybook): upgrade @chanzuckerberg/axe-storybook-testing from 7.1.1 to 7.1.2 [revert]

src/features/location/components/SearchLocationModal.tsx, src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25605
I have:
| iOS              |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/79197065-3858-430e-b4aa-178fd35e8641|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/af5f6a3b-9c3c-4c7d-9192-742d182884cd|
| Android          |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/cb575ae1-485c-4ad3-9ab0-d68dbec385af|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/82e50711-11c5-46f6-8fbd-fe52c895c14a|
=> (PC-25605) fix(location): fix error on search location modal

src/features/location/components/LocationWidgetDesktop.tsx, src/features/search/components/SearchHeader/SearchHeader.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24679
Just a lint fix :(
Rebase commits from 33a59ed to f8f00cf
=> (PC-24679) fix(search): eslint broken in ci

src/features/auth/api/useAccountSuspensionDate.native.test.ts, src/features/auth/api/useAccountSuspensionStatus.native.test.ts, src/features/auth/api/useAccountUnsuspend.native.test.ts, src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ResetPasswordExpiredLink/ResetPasswordExpiredLink.native.test.tsx, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentPage.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentPage.web.test.tsx, src/features/auth/pages/signup/SignupConfirmationExpiredLink/SignupConfirmationExpiredLink.native.test.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/tests/mswServer.ts, src/tests/server.ts, src/tests/utils.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22229
I have:
=> (PC-22229) refactor(msw): use new msw server in auth feature

__snapshots__/features/favorites/pages/FavoritesSorts.native.test.tsx.native-snap, __snapshots__/features/offer/pages/OfferDescription/OfferDescription.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap, src/features/favorites/pages/FavoritesSorts.tsx, src/features/offer/pages/OfferDescription/OfferDescription.tsx, src/features/search/components/SearchCustomModalHeader.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.web.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24948
I have:
iOS 
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/9f949a78-036b-49bd-9033-c3970bb5734e
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/044e3927-fc19-4138-90ba-91b060b430c1
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/806b442e-7f4b-4d96-9407-c4979b5f9e98
Android  
Arc
=> (PC-24948) feat(Headers): harmonisation 

src/features/location/components/LocationSearchWidget.native.test.tsx, src/features/location/components/LocationWidgetDesktop.native.test.tsx, src/features/location/components/LocationWidgetDesktop.tsx, src/features/location/components/LocationWidgetDesktop.web.test.tsx, src/features/location/components/LocationWidgetWrapperDesktop.tsx, src/features/location/components/SearchLocationWidgetDesktop.tsx, src/features/location/components/useLocationForLocationWidgetDesktop.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-24677
I have:
| Desktop - Chrome |    <img width="424" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/f763f81f-755e-460a-af2a-a878c142f23e">   |   https://github.com/pass-culture/pass-culture-app-native/assets/70148476/04dace98-2f02-406d-b4e1-c167e9278a03    |
=> (PC-24677) feat(LocationWidgetWrapperDesktop): home localisation web tooltip

src/features/offer/components/OfferTitle/OfferTitle.native.test.tsx, src/features/offer/components/OfferTitle/OfferTitle.stories.tsx, src/features/offer/components/OfferTitle/OfferTitle.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25526
I have:
=> (PC-25526) feat(offer): add title component

src/features/offer/components/OfferArtists/OfferArtists.native.test.tsx, src/features/offer/components/OfferArtists/OfferArtists.stories.tsx, src/features/offer/components/OfferArtists/OfferArtists.tsx, src/features/offer/helpers/getOfferArtists/getOfferArtists.test.ts, src/features/offer/helpers/getOfferArtists/getOfferArtists.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25473
I have:
=> (PC-25473) feat(offer): add artists component

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/venue/helpers/useVenueBackgroundStyle.native.test.tsx, src/features/venue/helpers/useVenueBackgroundStyle.ts, src/features/venue/pages/Venue/Venue.web.test.tsx, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25509
I have:
| Phone - Chrome   |               |<img width="430" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/030e7a13-b23c-47ed-935a-a5dca0c41d10">|
| Desktop - Chrome |<img width="799" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/b30f61cf-6101-4c4b-ad3f-3b68393bc653">|<img width="1023" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/c9377e4d-0981-47eb-a160-110b497f623f">|
[1]: …
=> (PC-25509) feat(venue): new adress block in venue desktop

src/features/navigation/RootNavigator/types.ts, src/features/profile/components/CreditExplanation/CreditExplanation.native.test.tsx, src/features/profile/components/CreditExplanation/CreditExplanation.tsx, src/features/profile/pages/Profile.native.test.tsx, src/features/profile/pages/Profile.tsx, src/features/tutorial/components/profileTutorial/EligibleFooter.native.test.tsx, src/features/tutorial/components/profileTutorial/EligibleFooter.tsx, src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx, src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/ui/components/touchableLink/TouchableLink.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25611
I have:
=> (PC-25611) feat(tutorial): Add trackers

__snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx, src/features/search/pages/Search/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-24951
I have:
| iOS              | <img width="341" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/4d08c3c5-b695-43ee-8964-b4e6ddde9063">   |   <img width="456" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/8fd9104e-4888-4b43-805e-82ffc9bcf6af"> |
| Android          |               |  <img width="458" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/d698fa17-01fb-4e2f-bbed-7718f9b3417c"> |
| Phone - Chrome   |               |  <img …
=> (PC-24951) feat(Search): add fixed margin in search bottom

scripts/dead_code_snapshot.txt
=> (BSR) fix(ci): Update deadcode snapshot

src/api/apiHelpers.native.test.ts, src/features/bookOffer/api/useBookOfferMutation.native.test.ts, src/features/bookOffer/components/BookingImpossible.native.test.tsx, src/features/bookings/api/useEndedBookingFromOfferId.native.test.ts, src/features/bookings/api/useOngoingOrEndedBooking.native.test.ts, src/features/bookings/components/ArchiveBookingModal.native.test.tsx, src/features/home/components/headers/HomeHeader.native.test.tsx, src/features/home/components/modules/HomeModule.native.test.tsx, src/features/home/components/modules/HomeModule.web.test.tsx, src/features/identityCheck/api/useGetStepperInfo.native.test.ts, src/features/identityCheck/api/usePhoneValidationRemainingAttempts.native.test.ts, src/features/identityCheck/pages/confirmation/IdentityCheckHonor.native.test.tsx, src/features/identityCheck/pages/identification/ubble/UbbleWebview.web.test.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.native.test.tsx, src/features/identityCheck/pages/profile/SetStatus.native.test.tsx, src/features/navigation/RootNavigator/RootNavigator.web.test.tsx, src/features/navigation/RootNavigator/useInitialScreenConfig.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/offer/components/OfferPartialDescription/OfferPartialDescription.native.test.tsx, src/features/trustedDevice/pages/AccountSecurityBuffer.native.test.tsx, src/tests/mswServer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22229
I have:
=> (PC-22229) refactor(Tests): use new msw server in some feature

scripts/dead_code_snapshot.txt, src/features/venue/pages/Venue/Venue.web.test.tsx, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25509
I have:
| Desktop - Chrome |<img width="812" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/2504a776-30bb-4d2e-a7ad-e08989fbf041">| <img width="857" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/12f72d73-3498-434c-bfc5-7986aa948fac"> |
=> (PC-25509) feat(NewVenue): remove divider in venue web

scripts/dead_code_snapshot.txt, src/features/offer/components/OfferTags/OfferTags.native.test.tsx, src/features/offer/components/OfferTags/OfferTags.stories.tsx, src/features/offer/components/OfferTags/OfferTags.tsx, src/features/offer/helpers/getOfferTags/getOfferTags.test.ts, src/features/offer/helpers/getOfferTags/getOfferTags.ts, src/ui/components/Tag/Tag.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25469
I have:
=> (PC-25469) feat(offer): add tags component

src/libs/recommendation/useHomeRecommendedIdsMutation.native.test.ts, src/libs/recommendation/useHomeRecommendedIdsMutation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25569
=> (PC-25569) fix(sentry): attempt to give error stack trace to sentry when error on recommendation endpoint

__snapshots__/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/venue/components/TabLayout/TabLayout.tsx, src/features/venue/components/TabLayout/useTabArrowNavigation.ts, src/features/venue/components/TabLayout/useTabArrowNavigation.web.ts, src/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx, src/features/venue/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25459
I have:
| iOS              |<img width="234" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/f6833082-546a-4635-ba73-257de702d1c0">|<img width="316" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/e4a8e7a3-ee7b-4bac-8efe-a108b22cd7e2"> |
| Android          |<img width="234" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/2938e193-3c0d-42af-bf9a-54abcd1cfed4">|<img width="402" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/2fbbd580-42c2-4c19- …
=> (PC-25459) feat(Venue): add offer playlist in new venue

server/src/utils/metas.ts, server/src/utils/tests/metas.test.ts, server/tests/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25772
I have:
=> (PC-25772) feat(proxy): Support list metadata

src/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx, src/features/search/pages/modals/VenueModal/useVenueModal.ts
oLink to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-25751
I have:
| iOS              |               |  https://github.com/pass-culture/pass-culture-app-native/assets/70148476/eca33633-d2cb-4d83-a5d4-62a0a1e4aecf     |
| Android          |               |   https://github.com/pass-culture/pass-culture-app-native/assets/70148476/7753360b-8c27-441c-b8a8-8fae6eb62ca1   |
| Phone - Chrome   |               |  https://github.com/pass-culture/pass-culture-app-native/assets/70148476/54ced03f-19dd-488e-b57b-01ebb49d00d4  |
| Desktop - Chrome |               | https://github.com/pass-culture/pass-culture-app-native/assets/7 …
=> (PC-25751) feat(useVenue): remove display of venue suggestion when re-opening modal

public/.well-known/security.txt
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25801
I have:
=> (PC-25801) build(assets): add security.txt

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_install.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22280
I have:
=> (PC-22280) ci(lock): use gcp artifact registry

src/features/search/components/SearchHeader/SearchHeader.native.test.tsx, src/features/search/components/SearchHeader/SearchHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25788
I have:
| Platform         | With FF ON| With FF OFF |
| Desktop - Chrome - Landing |<img width="1512" alt="Capture d’écran 2023-11-14 à 16 16 14" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/908cbd70-8078-4375-9b6a-ce518539d0a5">|<img width="1512" alt="Capture d’écran 2023-11-14 à 16 16 55" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/060b1d26-8530-4592-9fd0-b59280685abf">|
| Desktop - Chrome - Results |<img width="1512" alt="Capture d’écran 2023-11-14 à 16 16 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/2254900e-eee3-4992-b7e4-5f9ba57b586f">|<img width="1512" …
=> (PC-25788) feat(location): add feature flag on search widget for desktop view

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_install.yml
=> (BSR) ci(main): clean workflow main unused secrets

src/features/bookOffer/components/BookingOfferModalFooter.native.test.tsx, src/features/bookOffer/components/BookingOfferModalFooter.tsx, src/features/bookOffer/context/reducer.test.ts, src/features/bookOffer/context/reducer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25131
I have:
| iOS              |https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0556645a-6672-4ca7-97c2-6aae6711d46b|https://github.com/pass-culture/pass-culture-app-native/assets/78556024/bb6bed71-2dbf-4ed2-abfa-80c294794e5d|
| Android          |https://github.com/pass-culture/pass-culture-app-native/assets/78556024/3c3d8089-952c-4fab-a67a-d314fbdb912c|https://github.com/pass-culture/pass-culture-app-native/assets/78556024/c58cf9fe-c07e-4e11-bdc7-8b8aaee2320c|
| Desktop - Chrome …
=> (PC-25131) fix(bookOffer): reset potential previous hour when we validate a new date

__snapshots__/features/location/components/SearchLocationModal.native.test.tsx.native-snap, src/features/location/components/SearchLocationModal.native.test.tsx, src/features/location/components/SearchLocationModal.tsx, src/libs/geolocation/LocationWrapper.tsx, src/shared/location/LocationSearchFilters.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25445
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/10df9bac-447c-470e-8d4a-b0658411082e
=> (PC-25445) feat(SearchLocationModal): disconnect radius geoloc loc

src/App.native.test.tsx, src/App.tsx, src/libs/e2e/getIsMaestro.test.ts, src/libs/e2e/getIsMaestro.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25772
I have:
=> (PC-25772) feat(maestro): Disable yellow box for maestro

src/features/location/components/LocationWidgetDesktop.native.test.tsx, src/features/location/components/LocationWidgetWrapperDesktop.tsx
Link to JIRA ticket:  https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-25752
I have:
| Platform         |  After |
| :--------------- | :-----------: | 
| Desktop - Chrome |     https://github.com/pass-culture/pass-culture-app-native/assets/70148476/4b2d462c-655c-4823-808f-e8282d167c58      | 
| Desktop - Chrome |          https://github.com/pass-culture/pass-culture-app-native/assets/70148476/5e1632aa-a60b-494d-9269-94fef944d7de     |
=> (PC-25752) feat(LocationWidgetWrapperDesktop): fix web tooltip

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25848
I have:
| Phone - Chrome   |<img width="392" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/e3ec399e-e702-4f8b-a3f0-2bc157cb97a2">|<img width="393" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/959707ad-cf8e-4e5b-8c87-5a72d6523b33">|
| Desktop - Chrome |<img width="1024" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/65c52a89-dcec-4ec1-8be4-8b67ca0f8e2c">|<img width="1099" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a37a1a6f-a0e0-4f00 …
=> (PC-25848) fix(Venue): fix venue title in new desktop version

scripts/check_dead_code_introduced.sh
=> (BSR) chore(deadcode): improve explanations

__snapshots__/features/venue/components/ContactBlockNew/ContactBlockNew.web.test.tsx.web-snap, src/features/venue/components/ContactBlockNew/ContactBlockNew.native.test.tsx, src/features/venue/components/ContactBlockNew/ContactBlockNew.tsx, src/features/venue/components/ContactBlockNew/ContactBlockNew.web.test.tsx, src/features/venue/components/ContactBlockNew/ContactBlockNew.web.tsx, src/features/venue/components/ContactBlockNew/helpers.test.ts, src/features/venue/components/ContactBlockNew/helpers.ts, src/features/venue/components/PracticalInformation.native.test.tsx, src/features/venue/components/PracticalInformation.tsx, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx, src/ui/components/accessibility/AccessibilityBlock.native.test.tsx, src/ui/components/accessibility/AccessibilityBlock.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25852
I have:
| iOS              | <img width="358" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/3787cdd9-fcf9-4166-98b0-2e59aaa573b0"> | <img width="503" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/9497a678-311d-451f-8b5c-cb91d05dd7c6"> |
| Phone - Chrome   | <img width="358" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/684936df-0c21-4767-bf34-ef1491a5d009"> | <img width="376" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/71376852-a898-45d3-8a9c-a59a4f8cbea5"> | …
=> (PC-25852) feat(venue): add practical information

e2e/entrypoint.sh, e2e/generate-env.sh, scripts/appcenter-download-release.sh, scripts/check_branch.sh, scripts/check_dead_code_introduced.sh, scripts/check_diff.sh, scripts/check_server_diff.sh, scripts/create_and_push_tag_from_package_json_version.sh, scripts/deploy.sh, scripts/deploy_new_production_version.sh, scripts/deploy_new_version.sh, scripts/generate_api_client.sh, scripts/generate_api_client_silicon.sh, scripts/get_version.sh, scripts/print_project_version.sh, scripts/reassure_test.sh, scripts/release_staging_minor.sh, scripts/transition_jira_ticket.sh, scripts/update_app_version.sh, scripts/update_build_number_from_package_json_version.sh, scripts/upload_sourcemaps_to_sentry.sh
This reverts commit e76d7219bf0c50645ce890afe608ab62f76102be.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25559
=> (PC-25559) chore(script): fail on first error (#5531) [REVERT]

__snapshots__/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx.web-snap, __snapshots__/features/search/components/SearchResults/SearchResults.web.test.tsx.web-snap, src/features/location/components/SearchLocationModal.native.test.tsx, src/features/location/components/SearchLocationModal.tsx, src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx, src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx, src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/__tests__/TabBar.native.test.tsx, src/features/search/context/SearchWrapper.native.test.tsx, src/features/search/context/SearchWrapper.tsx, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.tsx
Link to JIRA ticket:  https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-25843
I have:
| iOS              |      https://github.com/pass-culture/pass-culture-app-native/assets/70148476/98268004-4457-4815-a04f-a2596b0a3f71         |    
| Desktop - Chrome | https://github.com/pass-culture/pass-culture-app-native/assets/70148476/5a9d7bdf-f798-4ed5-8b5e-e66e3cf97657              |    
-
=> (PC-25843) feat(SearchWrapper): update searchContext with locationContext

.github/workflows/dev_on_workflow_install.yml
=> (PC-22280) ci(yarn): Revert artifact registry

src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx, src/features/search/pages/modals/VenueModal/useVenueModal.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-25845
I have:
| :--------------- | :-----------: | 
| iOS              |     https://github.com/pass-culture/pass-culture-app-native/assets/70148476/ac5c6877-c15f-40e0-b6cc-b35f76ec4e25       |     
| Phone - Chrome   |         https://github.com/pass-culture/pass-culture-app-native/assets/70148476/0d890e32-d0d7-4520-b1df-46951a165244      |    
| Desktop - Chrome |       https://github.com/pass-culture/pass-culture-app-native/assets/70148476/b2b20ab9-b85a-4586-9255-820a1edc79e0        |
=> (PC-25845) feat(SearchResult): fix venue pill synchro

__snapshots__/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/gtlPlaylist/fixtures/gtlPlaylistAlgoliaSnapshot.ts, src/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx, src/features/venue/pages/Venue/Venue.tsx, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25525
I have:
| Phone - Chrome   | <img width="440" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/39de3313-0e44-4c4b-815e-c88a4a2a53e6"> | <img width="376" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/dd4b23cb-4b39-4cdd-86bb-fc8374c4cc85"> |
| Desktop - Chrome | <img width="964" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/1c907d51-edbb-4344-8f4f-61c62c6a378c"> | <img width="1512" alt="image" …
=> (PC-25525) feat(venue): handle multi playlists on new venue page

.env.integration, .env.production, .env.staging, .env.testing, .eslintrc.js, android/app/build.gradle, android/app/src/main/res/values/strings.xml, android/build.gradle, doc/development/how-to/sso.md, ios/PassCulture.xcodeproj/project.pbxproj, ios/PassCulture/Info.plist, ios/Podfile.lock, jest.config.js, package.json, src/App.native.test.tsx, src/App.tsx, src/features/auth/helpers/useLogoutRoutine.native.test.ts, src/features/auth/helpers/useLogoutRoutine.ts, src/features/auth/pages/login/Login.native.test.tsx, src/libs/environment/__mocks__/envFixtures.ts, src/libs/environment/types.ts, src/libs/react-native-google-sso/configureGoogleSignin.ts, src/libs/react-native-google-sso/configureGoogleSignin.web.ts, src/libs/react-native-google-sso/googleLogout.ts, src/libs/react-native-google-sso/googleLogout.web.ts, src/libs/react-native-google-sso/useGoogleLogin.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25581
I have:
=> (PC-25581) feat(sso): Implement native login POC

src/features/venue/components/VenueOffers/NoOfferPlaceholder.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25830
I have:
| iOS              | <img width="359" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/f69fd329-b744-4c4f-8260-f76f4242aaef"> | <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/84496af1-a337-488d-bd73-bf133c762d33"> |
| Phone - Chrome   | <img width="359" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/0396bbdc-0d49-4164-b6e2-2fe10448ba0c"> | <img width="378" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/eb36c63e-93ee-457a-9df4-487ce30ce24f"> | …
=> (PC-25830) feat(venue): add placeholder when no offers

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/features/venue/pages/VenueBodyNew/VenueBodyNew.tsx, src/ui/svg/icons/Venue.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25598
I have:
| iOS              |<img width="339" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/7fdc77cf-5ff2-4fe5-a0e6-54f085591972">|<img width="311" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/5a75cab6-efea-4149-b3bc-70b016b93a4d">|
| Android          |<img width="339" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/6c57a863-05e6-42f5-be5c-f27b34bccc39">|<img width="405" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a2a462ee-1be1-4828-9 …
=> (PC-25598) feat(Venue): add new empty image venue header

src/features/search/components/sections/Category/Category.native.test.tsx, src/features/search/components/sections/Category/Category.tsx, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25923
I have:
| Desktop - Chrome |![Capture d’écran 2023-11-20 à 18 01 24](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/56ab72a2-6554-4861-b9b6-e34fa9baa0e6)|![Capture d’écran 2023-11-20 à 18 01 04](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/63e028fc-8ec9-4568-a7f0-ae5586de3bac)|
=> (PC-25923) fix(category): missing nbResultFacets for Catgeory used in SearchFilter

.github/workflows/dev_on_workflow_install.yml, .github/workflows/dev_on_workflow_linter_ts.yml, .github/workflows/dev_on_workflow_tester.yml, .github/workflows/dev_on_workflow_ts_prune.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
=> (BSR) ci(cache): upgrade gcs cache to v1.0.1

src/features/cookies/helpers/setMarketingParams.native.test.ts, src/libs/analytics/__mocks__/provider.ts, src/libs/analytics/provider.test.ts, src/libs/analytics/provider.ts, src/libs/analytics/types.ts, src/libs/firebase/analytics/__tests__/logEvent.native.test.ts, src/libs/firebase/analytics/__tests__/useInit.native.test.ts, src/libs/firebase/analytics/provider.ts, src/libs/firebase/analytics/types.ts, src/libs/firebase/analytics/useInit.ts, src/libs/geolocation/LocationWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-25750
I have:
=> (PC-25750) feat(analytics): firebase location type on every event

src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx
=> (BSR) fix(tests): tests are flaky without mock animation

src/features/location/components/SearchLocationModal.native.test.tsx, src/features/search/components/HoursSlider/HoursSlider.native.test.tsx, src/features/search/components/HoursSlider/HoursSlider.stories.tsx, src/features/search/components/HoursSlider/HoursSlider.tsx, src/features/search/components/LocationSlider/LocationSlider.native.test.tsx, src/features/search/components/LocationSlider/LocationSlider.stories.tsx, src/features/search/components/LocationSlider/LocationSlider.tsx, src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.test.ts, src/features/search/helpers/schema/datesHoursSchema/datesHoursSchema.ts, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.tsx, src/ui/components/inputs/Slider.native.test.tsx, src/ui/components/inputs/Slider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24896
I have:
=> (PC-24896) fix(Slider): fix Slider infinite loop

src/features/location/components/LocationWidget.tsx, src/features/location/components/LocationWidgetDesktop.native.test.tsx, src/features/location/components/LocationWidgetWrapperDesktop.tsx, src/features/location/helpers/useLocationWidgetTooltip.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-25779
I have:
| Platform         |  After |
| iOS              |   <img width="456" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/6f673772-3ba2-47e4-92d1-fe4d692854c3">  |       
| Phone - Chrome   |   <img width="1440" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/04aafffa-a82f-480b-ad8b-33dccabe78ee">  |       
| Desktop - Chrome |  <img width="1440" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/3b5f7097-0391-456d-8029-e8b63528f6e1"> |
=> (PC-25779) feat(LocationWidgetTooltip): refacto location tooltip

src/features/bookOffer/components/Calendar/Calendar.tsx, src/features/bookOffer/components/Calendar/DayComponent.tsx, src/features/bookings/components/BookingDetailsTicketContent.tsx, src/features/bookings/components/Ticket/TicketWithContent.tsx, src/features/favorites/components/FavoritesResults.tsx, src/features/home/components/modules/categories/CategoryBlock.tsx, src/features/offer/components/OfferHeader/OfferHeader.tsx, src/features/offer/pages/Offer/Offer.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx, src/features/venue/components/VenueOffers/VenueOffers.tsx, src/ui/components/InputLabel/FlexInputLabel.tsx, src/ui/pages/GenericOfficialPage.tsx, src/ui/web/errors/ErrorMessage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25274
I have:
=> (PC-25274) fix(app): XXX PropType is defined but prop is never used"

src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-23887
**This is not a real bug but an exception badly managed**
I have:
- [-] Written **unit tests** native (and web when implementation is different) for my feature.
- [-] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
- [-] If my PR is a bugfix, I add the link of the "résolution de problème sur le bug" [on Notion][1]
=> (PC-23887) fix(CulturalSurvey): Error in hook to count survey's questions

src/features/offer/components/SameArtistPlaylist/api/fetchOffersByArtist.test.ts, src/features/offer/components/SameArtistPlaylist/api/fetchOffersByArtist.ts, src/features/offer/components/SameArtistPlaylist/hook/useSameArtistPlaylist.native.test.ts, src/features/offer/components/SameArtistPlaylist/hook/useSameArtistPlaylist.tsx, src/features/offer/helpers/renderOfferPageTestUtil.tsx, src/features/offer/pages/Offer/Offer.analytics.native.test.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26006
I have:
=> (PC-26006) fix(SameArtistPlaylist): If this is not a book handle case and do not return the playlist

.github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml, .github/workflows/dev_on_workflow_web_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26086
I have:
=> (PC-26086) ci(slack): add slack notify web/ios/android during mes

src/features/trustedDevice/fixtures/fixtures.ts, src/features/trustedDevice/helpers/formatTokenInfo.native.test.ts, src/features/trustedDevice/helpers/formatTokenInfo.ts, src/features/trustedDevice/helpers/getTokenInfo.native.test.ts, src/features/trustedDevice/helpers/getTokenInfo.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26096
I have:
| Desktop - Chrome |               |   <img width="491" alt="Capture d’écran 2023-11-30 à 12 41 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/799f228c-c9f0-4932-b889-b58879cd416b">    |
=> (PC-26096) fix(AccountSecurity): Handle new token format

src/features/search/components/SearchResults/SearchResults.native.test.tsx, src/features/search/pages/modals/VenueModal/useVenueModal.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-26122
- lors du reset de la venu dans la venue modal je suis bien en capacité de remettre la place en tant que contexte de recherche
- Par contre impossible de récupéré le rayon de localisation puisque à ce moment la le seul endroit ou se trouve la source de vérité du rayon de localisation de la place c’est est dans la modal de localisation (c'est d'ailleurs déja un problème prod sur la geolocalisation)
- Pire si je pars du principe que je reset le rayon de localisation (ce qui est pas ouff mais bon toujours moins pire...) et bien lorsque l’on retourne dans la modal de localisation on voit toujours le rayon de localisation choisi par l’utilisateur précédemment et pas celui qui a …
=> (PC-26122) fix(useVenueModal): on reset venue set place as search location 

src/features/bookOffer/components/BookHourChoice.native.test.tsx, src/features/bookOffer/components/BookHourChoice.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26047
I have:
=> (PC-26047) refactor(bookings): reduce cognitive complexity

src/features/offerv2/components/OfferAccessibility/OfferAccessibility.native.test.tsx, src/features/offerv2/components/OfferAccessibility/OfferAccessibility.stories.tsx, src/features/offerv2/components/OfferAccessibility/OfferAccessibility.tsx, src/shared/isNullOrUndefined/isNullOrUndefined.test.ts, src/shared/isNullOrUndefined/isNullOrUndefined.ts, src/ui/components/accessibility/AccessibilityBlock.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25495
I have:
| Phone - Chrome   |<img width="461" alt="image-20231030-141429" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0d1f754d-5629-4d06-872b-0151942c0ef1">|<img width="454" alt="Capture d’écran 2023-12-04 à 15 45 59" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/75908f01-ed5f-443f-b202-c308e8e7ee3c"> <img width="361" alt="Capture d’écran 2023-12-04 à 15 46 07" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/2ee48d92-6a5 …
=> (PC-25495) feat(offer): add accessibility component

.github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26328
La condition était inversé: 
Doc: https://docs.github.com/en/actions/learn-github-actions/expressions#operators
I have:
=> (PC-26328) ci(slack): notification picto fix condition

__snapshots__/features/offer/components/OfferBody/OfferBody.native.test.tsx.native-snap, jest.web.config.js, src/features/offer/components/OfferBody/OfferBody.analytics.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.native.test.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferBody/OfferBody.web.test.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25990
I have:
=> (PC-25990) feat(offer): log PlaylistVerticalScroll when scrolling to same artist playlist

src/ui/components/CollapsibleText/CollapsibleText.native.test.tsx, src/ui/components/CollapsibleText/CollapsibleText.stories.tsx, src/ui/components/CollapsibleText/CollapsibleText.tsx, src/ui/components/buttons/ButtonTertiaryBlack.ts, src/ui/svg/icons/ArrowUp.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25494
I have:
| iOS              |      |       |
| Phone - Chrome   |<img width="407" alt="Capture d’écran 2023-12-08 à 12 04 45" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/cb4fffce-092d-4531-847d-a4577cdecf42">|<img width="450" alt="Capture d’écran 2023-12-08 à 12 07 38" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/4b5c4be7-242c-4bc4-ba88-cee27c2f4cf2"> <img width="451" alt="Capture d’écran 2023-12-08 à 12 07 45" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/b34 …
=> (PC-25494) feat(ui): add CollapsibleText

src/features/auth/helpers/useIsMailAppAvailable.native.test.ts, src/features/auth/helpers/useIsMailAppAvailable.ts
Fix for 'exhaustive-deps' lint rule in hook
https://github.com/facebook/react/issues/14920
=> (BSR) fix(hook): remove dep warning

server/src/middlewares/tests/webAppProxyMiddleware.test.ts, server/src/middlewares/webAppProxyMiddleware.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26374
I have:
=> (PC-26374) fix(proxy): rm cache and do not edit res when chunk is html

.maestro/README.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26252
=> (PC-26252) docs(maestro): Added more details to readme

.github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
=> (BSR) ci(slack): improve slack notification on deploy

scripts/dead_code_snapshot.txt, sonar-project.properties, src/features/cookies/helpers/useCookies.ts, src/features/culturalSurvey/components/CulturalSurveyCheckbox.tsx, src/features/venue/components/ContactBlockNew/helpers.ts, src/libs/react-native-web-fast-image/index.js, src/ui/components/snackBar/SnackBar.tsx
=> (BSR) fix(sonar): issues

eslint-custom-rules/__tests__/todo-format.test.js, eslint-custom-rules/todo-format.js, jest/fixJestEnvironmentJsdom.ts, scripts/dead_code_snapshot.txt, src/features/bookOffer/api/useBookOfferMutation.ts, src/features/bookings/pages/BookingNotFound/BookingNotFound.tsx, src/features/cookies/pages/CookiesDetails.web.test.tsx, src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx, src/features/identityCheck/pages/Stepper.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx, src/features/search/components/SearchBox/SearchBox.tsx, src/features/search/components/SearchResults/SearchResults.tsx, src/features/search/helpers/useHasPosition/useHasPosition.ts, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx, src/features/search/types.ts, src/libs/algolia/types.ts, src/libs/geolocation/getPosition.ts, src/libs/geolocation/getPosition.web.ts, src/ui/components/hero/HeroHeader.tsx, src/ui/components/inputs/Checkbox/Checkbox.web.test.tsx, src/ui/components/snackBar/SnackBar.native.test.tsx, src/ui/svg/icons/UserBlocked.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26454
Now supports only `TODO(PC-****)` and `FIXME(PC-****)` (no github pseudo or whatever between the parentheses).
=> (PC-26454) chore(eslint): update todo format rule

src/features/bookings/components/TicketCode.web.tsx, src/features/internal/marketingAndCommunication/atoms/DeepLinkItem.web.test.tsx, src/features/internal/marketingAndCommunication/atoms/DeeplinkItem.tsx, src/features/share/pages/WebShareModal.web.test.tsx, src/features/share/pages/WebShareModal.web.tsx, src/features/share/pages/WebShareModalBest.web.test.tsx, src/features/share/pages/WebShareModalBest.web.tsx, src/features/venue/components/VenueBodyNew/VenueBodyNew.tsx, src/libs/useCopyToClipboard/useCopyToClipboard.native.test.ts, src/libs/useCopyToClipboard/useCopyToClipboard.ts, src/libs/useCopyToClipboard/useCopyToClipboard.web.test.ts, src/libs/useCopyToClipboard/useCopyToClipboard.web.ts, src/shared/CopyToClipboardButton/CopyToClipboardButton.native.test.tsx, src/shared/CopyToClipboardButton/CopyToClipboardButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26161
I have:
| Platform         |  After |
| :--------------- | :-----------: | 
| iOS              |   [ios.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/3917b17f-8aa6-493a-9c7a-6a5332da416e)  |       
| Desktop - Chrome   |    [desktop.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/3e4c9cd5-fd7c-4d29-b700-9ea17f8cc1a5)           |      
=> (PC-26161) feat(clipboard): Use navigator instead of library in web

sonar-project.properties, src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx, src/features/home/components/modules/OffersModule.tsx, src/features/identityCheck/api/usePatchProfile.ts, src/features/identityCheck/pages/identification/educonnect/EduConnectForm.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/profile/components/Buttons/EditButton/EditButton.tsx, src/features/venue/components/ContactBlockNew/ContactBlockNew.tsx, src/libs/algolia/fetchAlgolia/fetchSearchResults/helpers/buildSearchVenuePosition.ts, src/libs/geolocation/LocationWrapper.tsx, src/libs/geolocation/getPosition.ts, src/libs/geolocation/getPosition.web.ts, src/ui/components/Playlist.tsx, src/ui/components/SectionWithDivider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26447
I have:
=> (PC-26447) fix(sonar): handle sonar issues

web/js/chunk-protection.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26382
I have:
=> (PC-26382) fix(web): fix error message for firefox

.vscode/settings.json, __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/offerv2/components/OfferBookingButton/OfferBookingButton.tsx, src/features/venue/components/VenueBodyNew/VenueBodyNew.tsx, src/features/venue/components/VenueCTA/VenueCTA.tsx, src/ui/components/BlurryWrapper/BlurryWrapper.tsx, src/ui/components/StickyBottomWrapper/StickyBottomWrapper.native.test.tsx, src/ui/components/StickyBottomWrapper/StickyBottomWrapper.stories.tsx, src/ui/components/StickyBottomWrapper/StickyBottomWrapper.tsx, src/ui/components/StickyWrapper/StickyWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26033
I have:
| Platform         | Mockup | After with FF on | After with FF off |
| iOS              | <img width="374" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/50e2f685-d965-4f11-bf67-e08bee518b36"> | <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/1e68c9d1-ecec-4752-b54a-6c682334e4bf"> |   |
| iOS scrolled down | <img width="348" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/4d6fe8dc-804a-4fd2-b959-f48195a11973"> | <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/9a76d …
=> (PC-26033) feat(venue): add background to venue cta

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26373
I have:
=> (PC-26373) feat(Search): add Feature Flag WIP_NEW_MAPPING_BOOKS

__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/offer/components/OfferWebMetaHeader.tsx, src/features/offer/pages/Offer/Offer.tsx, src/features/venue/components/VenueWebMetaHeader.tsx, src/features/venue/pages/Venue/Venue.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26257
- Pour info, je n'ai pas réussi a utiliser flexDirection: "column-reverse" car il y a des éléments en absolute. 
I have:
=> (PC-26257) refactor(venue): Fix tab navigation order for Venue and Offer

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, src/features/offerv2/components/OfferAccessibility/OfferAccessibility.native.test.tsx, src/ui/components/accessibility/AccessibilityAtom.tsx, src/ui/components/accessibility/AccessibilityBlock.native.test.tsx, src/ui/components/accessibility/AccessibilityBlock.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26471
I have:
| iOS              | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/e2a767e0-6421-447e-95bd-16902a07b590) | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/e363b772-884b-477c-9126-08138ed8bf1c) |
| Phone - Chrome   | ![Lieu (1)](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/d0bc1be5-1d02-44ed-b219-85116913b775) | ![Lieu](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/0bbe06fe-e9a8-45e8-aa84-844065da982b) |
| Desktop - Chrome | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/26742386/5 …
=> (PC-26471) fix(venue): stop cropping a11y info text

src/features/offerv2/components/OfferVenueBlock/OfferVenueBlock.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25497
I have:
| Desktop - Chrome | ![CleanShot 2023-12-19 at 15 46 06@2x](https://github.com/pass-culture/pass-culture-app-native/assets/114916654/5882c840-db6b-4d3a-a9c7-240dbb719e69) | ![CleanShot 2023-12-19 at 15 46 31@2x](https://github.com/pass-culture/pass-culture-app-native/assets/114916654/01fd5b47-b3f4-498d-992e-bef074d7a88e) |
=> (PC-25497) feat(offer): add missing space

src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx, src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx, src/features/navigation/RootNavigator/Header/Nav.tsx, src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/TabBarComponent.tsx, src/features/navigation/TabBar/__tests__/TabBar.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-25061
I have:
| iOS              |     https://github.com/pass-culture/pass-culture-app-native/assets/70148476/4670e056-0699-4e5f-9c60-82a1f9ccafbc        |     
| Android          |     https://github.com/pass-culture/pass-culture-app-native/assets/70148476/fdee5b92-a5ff-4656-98ea-fb5691774ecb        |  
| Phone - Chrome   |    https://github.com/pass-culture/pass-culture-app-native/assets/70148476/b4773319-d1c3-4ae5-b752-4aec34624db2           | 
| Desktop - Chrome |       https://github.com/pass-culture/pass-culture-app-native/assets/70148476/90340b2e-22d7-414a-9cfb-60bfbe078125        |
=> (PC-25061) feat(TabBar): reset search 

.github/workflows/dev_on_push_workflow_main.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26567
I have:
=> (PC-26567) ci(native): undo the deploy hard on testing using commit sha

.github/workflows/dev_on_push_workflow_main.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26567
relates to : 
- https://github.com/pass-culture/pass-culture-app-native/pull/5725 
- https://github.com/pass-culture/pass-culture-app-native/pull/5726
I have:
=> (PC-26567) ci(testing): fix deploy hard

src/features/offerv2/components/OfferMetadataItem/OfferMetadataItem.native.test.tsx, src/features/offerv2/components/OfferMetadataItem/OfferMetadataItem.stories.tsx, src/features/offerv2/components/OfferMetadataItem/OfferMetadataItem.tsx, src/features/offerv2/components/OfferMetadataList/OfferMetadataList.native.test.tsx, src/features/offerv2/components/OfferMetadataList/OfferMetadataList.stories.tsx, src/features/offerv2/components/OfferMetadataList/OfferMetadataList.tsx, src/features/offerv2/helpers/getOfferMetadata/getOfferMetadata.test.ts, src/features/offerv2/helpers/getOfferMetadata/getOfferMetadata.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25493
I have:
| Phone - Chrome   |               |<img width="359" alt="Capture d’écran 2023-12-20 à 11 08 55" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/c64e6800-a6b8-4926-a2bf-d9cdae2a26c9">|
| Desktop - Chrome |               |<img width="783" alt="Capture d’écran 2023-12-20 à 11 09 08" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/03ea2ad4-3517-4723-b215-a81419a8919a">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5 …
=> (PC-25493) feat(offer): add metadata list

src/features/home/components/modules/HighlightOfferModule.native.test.tsx, src/features/home/components/modules/HighlightOfferModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-24611
I have:
=> (PC-24611) feat(HighlightOfferModule): display public name

scripts/dead_code_snapshot.txt, src/features/bookings/helpers/expirationDateUtils.ts, src/features/navigation/RootNavigator/types.ts, src/features/offer/components/OfferTile/OfferTile.native.test.tsx, src/features/offer/components/OfferTile/OfferTile.tsx, src/features/offer/helpers/determinePlaylistType/determinePlaylistType.test.ts, src/features/offer/helpers/determinePlaylistType/determinePlaylistType.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26098
I have:
=> (PC-26098) feat(tracking): complete consult offer log with same artist playlist

src/features/bookOffer/components/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26543
I have:
=> (PC-26543) fix(sonar): Remove this use of the "void" operator"

doc/development/tests/unit-test/full-page-test.md, doc/development/tests/unit-test/troubleshooting.md, src/features/auth/pages/forgottenPassword/ForgottenPassword/ForgottenPassword.web.test.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.web.test.tsx, src/features/auth/pages/login/Login.web.test.tsx, src/features/auth/pages/signup/SignupForm.web.test.tsx, src/features/cookies/pages/CookiesDetails.web.test.tsx, src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.web.test.tsx, src/features/offer/pages/Offer/Offer.web.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.web.test.tsx, src/features/profile/pages/ChangePassword/ChangePassword.web.test.tsx, src/features/profile/pages/ConsentSettings/ConsentSettings.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26463
I have:
=> (PC-26463) feat(accessibility): fix CookiesDetails accessibility problem with UUIDV4 mock

src/libs/react-responsive/useMediaQuery.test.ts, src/libs/react-responsive/useMediaQuery.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21284
I have:
=> (PC-21284) refactor(useMediaQuery): reduce cognitive complexity

scripts/dead_code_snapshot.txt, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx, src/tests/utils.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26601
I have:
=> (PC-26601) test(waitFor): remove 10s timeout for waitfor

src/features/auth/api/useSignIn.ts, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.web.test.tsx, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx, src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.tsx, src/features/auth/pages/signup/SignupForm.web.test.tsx, src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26414
I have:
=> (PC-26414) feat(FeatureFlag): remove ff trusted device

src/features/home/components/modules/HighlightOfferModule.native.test.tsx, src/features/home/components/modules/HighlightOfferModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-24611
I have:
=> (PC-24611) feat(HighlightOfferModule): fallback on venue name if venue publicName is an empty string

scripts/dead_code_snapshot.txt, src/features/auth/api/useAccountSuspensionDate.native.test.ts, src/features/auth/api/useAccountSuspensionStatus.native.test.ts, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentPage.native.test.tsx, src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentPage.web.test.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/bookOffer/api/useBookOfferMutation.native.test.ts, src/features/home/components/modules/HomeModule.native.test.tsx, src/features/home/components/modules/HomeModule.web.test.tsx, src/features/identityCheck/api/useGetStepperInfo.native.test.ts, src/features/identityCheck/api/usePhoneValidationRemainingAttempts.native.test.ts, src/features/navigation/RootNavigator/RootNavigator.web.test.tsx, src/features/navigation/RootNavigator/useInitialScreenConfig.native.test.tsx, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx, src/features/trustedDevice/pages/AccountSecurityBuffer.native.test.tsx, src/features/venue/components/VenueMessagingAppsNew/VenueMessagingAppsNew.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26603
I have:
=> (PC-26603) test(msw): add some typing in mockServer calls

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_schedule_lighthouse.yml, .github/workflows/dev_on_workflow_check_folder_change.yml, .github/workflows/dev_on_workflow_check_proxy_version.yml, .github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml, .github/workflows/dev_on_workflow_install.yml, .github/workflows/dev_on_workflow_linter_ts.yml, .github/workflows/dev_on_workflow_tester.yml, .github/workflows/dev_on_workflow_ts_prune.yml, .github/workflows/dev_on_workflow_update_jira_issues.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml, .github/workflows/jira_create_and_push_staging_testing_deploy_tags.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26501
Notion: https://www.notion.so/passcultureapp/Rollback-self-hosted-sur-github-runner-bcdb3ec6d6674aa1a5a4bdb8119ccd79
Depends on: https://github.com/pass-culture/pass-culture-app-native/pull/5731
I have:
=> (PC-26501) ci(runner): reduce big to regular in unit tests

src/features/favorites/components/FavoritesResults.web.test.tsx, src/features/favorites/pages/Favorites.web.test.tsx, src/features/home/pages/GenericHome.native.test.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.web.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26576
I have:
=> (PC-26576) test(ci): skip flacky unit tests

__snapshots__/features/profile/pages/Accessibility/AccessibilityActionPlan.native.test.tsx.native-snap, __snapshots__/features/profile/pages/Accessibility/AccessibilityDeclaration.native.test.tsx.native-snap, src/features/profile/components/Buttons/ActionPlanTag/ActionPlanTag.stories.tsx, src/features/profile/components/Buttons/ActionPlanTag/ActionPlanTag.tsx, src/features/profile/pages/Accessibility/AccessibilityActionPlan.native.test.tsx, src/features/profile/pages/Accessibility/AccessibilityActionPlan.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26607
I have:
| iOS              |               |   ![Simulator Screenshot - iPhone 5 - 2023-12-26 at 18 43 02](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/dfb7bbdf-4528-458a-891f-70028a0b97af)    |
| Desktop - Chrome |               |    <img width="1440" alt="Capture d’écran 2023-12-26 à 18 43 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/dadb403a-3ffc-4806-9dd1-fc3713c2fc15">   |
=> (PC-26607) feat(accessibility): Update declaration and action plan

.maestro/README.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26615
I have:
=> (PC-26615) feat(maestro): ajout des variables dans le README

scripts/run_e2e_tests.sh
=> (BSR) chore(e2e): fix end to end script seems to have been renamed

scripts/run_e2e_tests.sh, src/libs/e2e/getIsMaestro.ts
=> (BSR) fix(e2e): hide yellow box on Android

ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26535
J'ai créé [ce ticket](https://passculture.atlassian.net/browse/PC-26625) pour checker si la MAJ corrige le bug.
I have:
=> (PC-26535) chore(appsflyer): Upgrade appsflyer

src/ui/components/buttons/externalLink/ExternalLink.web.tsx, src/ui/components/buttons/externalLink/__tests__/ExternalLink.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-21194
I have:
=> (PC-21194) test(externalLink): Unskip external link test

src/ui/components/inputs/Checkbox/Checkbox.web.test.tsx, src/ui/components/snackBar/SnackBar.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26461
I have:
=> (PC-26461) chore(tests): Unskip tests

__snapshots__/libs/recaptcha/ReCaptcha.native.test.tsx.native-snap, src/libs/recaptcha/webviewHTML.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26592
I have:
=> (PC-26592) fix(recaptcha): Use navigator.connection.type for android

.github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml
=> (BSR) ci(hard): fix cache name for node dependencies

src/features/bookings/components/EndedBookingsSection.tsx, src/features/identityCheck/components/StepButton.tsx, src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26624
I have:
=> (PC-26624) feat(sonar): Fix "React components should not be nested" issues

scripts/run_e2e_tests.sh
this allow to overwrite variables environments
https://passcultureteam.slack.com/archives/C05MH81G9LY/p1704283775826419?thread_ts=1704278214.433949&cid=C05MH81G9LY
=> (BSR) feat(e2e): allow to pass arbitrary arguments

src/features/auth/api/useOAuthState.native.test.ts, src/features/auth/api/useOAuthState.ts
=> (BSR) fix(sso): Fetch auth state when FF is active

src/features/search/components/SearchResults/SearchResults.tsx, src/shared/string/ellipseString.test.ts, src/shared/string/ellipseString.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25881
I have:
| iOS              |               |![Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-03 at 11 12 26](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/931fb13d-1e22-4b3c-9d1e-6f3debfc494b)|
| Android          |               | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-03 at 11 12 26](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/090d57a8-d9a3-42a2-a6b5-5bc2df325acc)|
| Desktop - Chrome |![Capture d’écran 2024-01-03 à 10 53 32](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/b95c6b04-4533 …
=> (PC-25881) feat(SearchResults): limit size venue name in pills

.github/dependabot.yml
=> (BSR) feat(dependabot): add github-actions review for Dependabot

.env.integration, .env.production, .env.staging, .env.testing, doc/development/how-to/sso.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26555
I have:
=> (PC-26555) feat(sso): Update client ids to allow access for all google accounts

src/features/favorites/components/FavoritesResults.web.test.tsx, src/features/favorites/pages/Favorites.web.test.tsx, src/features/home/pages/GenericHome.native.test.tsx, src/features/profile/pages/Accessibility/AccessibilityDeclaration.web.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx
=> (BSR) feat(lint): add eslint-disabled for all skipped tests

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, src/features/venue/components/TabLayout/InfoTab.tsx, src/features/venue/components/TabLayout/TabLayout.tsx, src/features/venue/components/TabLayout/TabLayout.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25763
I have:
| Desktop - Chrome |               |   [web.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/a462f94a-dce3-460d-a793-3069c58c3cb1)    |
=> (PC-25763) feat(venue): Add hover behavior to info tabs

package.json
=> (BSR) fix(CD): change version runtime in resolution

scripts/update_build_number_from_package_json_version.sh
=> (BSR) fix(scripts): Fix variable

src/features/home/components/modules/HomeModule.native.test.tsx, src/features/home/components/modules/HomeModule.tsx, src/features/home/types.ts, src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.tsx, src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26584
I have:
=> (PC-26584) fix(FeatureFlags): remove unnecessary feature flags

package.json, yarn.lock
=> (BSR) fix(CD): align versions used

src/features/venue/api/useVenueOffers.ts, src/features/venue/components/VenueBody/VenueBody.tsx, src/features/venue/components/VenueCTA/VenueCTA.native.test.tsx, src/features/venue/components/VenueCTA/VenueCTA.tsx, src/features/venue/components/VenueOffers/VenueOffers.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx, src/features/venue/helpers/useNavigateToSearchWithVenueOffers.native.test.ts, src/features/venue/helpers/useNavigateToSearchWithVenueOffers.ts, src/features/venue/helpers/useVenueSearchParameters/useVenueSearchParameters.native.test.ts, src/features/venue/helpers/useVenueSearchParameters/useVenueSearchParameters.ts, src/features/venue/pages/Venue/Venue.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26740
I have:
| iOS              |         [bug.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/08c2603d-e196-4f5e-a54d-27c213504e0a)      |     [fix.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/c92b37c4-486e-46c2-a348-9d50b5fd2011)  |
=> (PC-26740) refactor(venue): Remove redundant query to backend

.github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml, .github/workflows/dev_on_workflow_tester.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml
=> (BSR) ci(slack): update slack token location

scripts/dead_code_snapshot.txt, src/features/favorites/favoriteList/FakeDoor/FavoriteListBanner.tsx, src/features/home/components/banners/GeolocationBanner.tsx, src/features/identityCheck/components/IdentificationForkButton.tsx, src/features/identityCheck/components/StepButton.tsx, src/features/identityCheck/pages/identification/ubble/SelectIDOrigin.tsx, src/features/identityCheck/pages/identification/ubble/SelectIDStatus.tsx, src/features/identityCheck/pages/identification/ubble/SelectPhoneStatus.web.tsx, src/features/identityCheck/types.ts, src/features/internal/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/offerv2/components/OfferVenueButton/OfferVenueButton.tsx, src/features/profile/components/Header/CreditHeader/CreditHeader.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/tutorial/components/AgeButton.stories.tsx, src/features/tutorial/components/AgeButton.tsx, src/features/tutorial/components/AgeButtonContainer.tsx, src/features/tutorial/pages/AgeSelection.tsx, src/features/tutorial/types.ts, src/ui/components/ModuleBanner/BannerWithBackground.tsx, src/ui/components/ModuleBanner/GenericBanner.stories.tsx, src/ui/components/ModuleBanner/GenericBanner.tsx, src/ui/components/buttons/HeroButtonList.stories.tsx, src/ui/components/buttons/HeroButtonList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25880
I have:
=> (PC-25880) refactor(HeroButtonList): props icon from FunctionalComponent to ReactElement

__mocks__/react-query.ts, src/features/gtlPlaylist/hooks/useGTLPlaylists.native.test.ts, src/features/gtlPlaylist/hooks/useGTLPlaylists.ts, src/features/venue/components/VenueBodyNew/VenueBodyNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx, src/features/venue/pages/Venue/Venue.native.test.tsx, src/features/venue/pages/Venue/Venue.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26573
I have:
| Phone - Chrome   |(cf 57s avec arrêt sur image) https://github.com/pass-culture/pass-culture-app-native/assets/68000368/3d3266fc-e737-4294-99b1-2613186c2780 | (cf 1mn20) https://github.com/pass-culture/pass-culture-app-native/assets/68000368/f1a25b6b-d7b9-492a-8933-89ddbfba6441 |
=> (PC-26573) feat(Venue): add loading for offers and playlists

server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap
=> (BSR) fix(proxy): Upgrade snapshot due to sandbox change

src/api/useSearchVenuesOffer/useSearchVenueOffers.ts, src/features/bookOffer/components/BookingDetails.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx, src/features/offer/components/OfferPlace/OfferPlace.tsx, src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.test.ts, src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildGeolocationParameter.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildOfferSearchParameters.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/tests/buildGeolocationParameter.test.ts, src/libs/algolia/fetchAlgolia/fetchOffers.native.test.ts, src/libs/algolia/fetchAlgolia/fetchOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26723
I have:
| Phone - Chrome   |![Capture d’écran 2024-01-04 à 17 19 41](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/58965b91-1be4-4789-8bad-e539dae91325) ![Capture d’écran 2024-01-04 à 17 19 48](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/09c441f4-c63c-4c9a-8b04-b94c47ff6208) ![Capture d’écran 2024-01-04 à 17 20 22](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/27ce6a08-88b3-4b03-a00c-cfe85c9b0f1f) ![Capture d’écran 2024-01-04 à …
=> (PC-26723) fix(offer): possibility of using the position configured by the user and not necessarily his geolocation 

scripts/dead_code_snapshot.txt, src/api/apiHelpers.native.test.ts, src/api/apiHelpers.ts, src/features/auth/context/AuthContext.tsx, src/features/identityCheck/api/useGetStepperInfo.ts, src/features/identityCheck/pages/helpers/mapStepsDetails.ts, src/features/internal/cheatcodes/pages/CheatCodes/CheatCodes.tsx, src/libs/jwt/__mocks__/jwt.ts, src/libs/jwt/getTokenExpirationDate.ts, src/libs/jwt/jwt.ts, src/libs/monitoring/__mocks__/services.ts, src/libs/monitoring/services.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26757
I have:
=> (PC-26757) feat(stepper): send extra data to sentry to debug

scripts/run_e2e_tests.sh, src/libs/analytics/provider.ts
Made with @bruno-ebstein-pass-culture
=> (BSR) fix(e2e): tracker on android for physical devices

.github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_workflow_check_folder_change.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26828
I have:
=> (PC-26828) ci(proxy): fix deploy proxy to staging and production

src/ui/theme/typography.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26881
I have:
=> (PC-26881) test(UI): use unique story for typos

src/libs/algolia/fetchAlgolia/fetchVenues/buildFetchVenuesQueryParameters.native.test.ts, src/libs/algolia/fetchAlgolia/fetchVenues/buildFetchVenuesQueryParameters.ts, src/libs/algolia/fetchAlgolia/fetchVenues/fetchVenues.native.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-26656
I have:
=> (PC-26656) feat(buildFetchVenuesQueryParameters): hide venue with no offer in venueModal

__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap, __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap, ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24079
I have:
| iOS              |               |   ![IMG_6720](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/231fde5e-b03c-4bc7-829d-a14120b0b551)    |
| Android          |               | ![Screenshot_20240110-170756](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/249339d3-2f60-4b4b-aa1f-0ef62d46c76b)      |
=> (PC-24079) chore(libs): Update react-native-date-picker

.github/workflows/dev_on_workflow_update_jira_issues.yml, .jira.d/templates/edit
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24027
=> (PC-24027) feat(CI): set SafeToDeploy jira field

.github/dependabot.yml
=> (BSR) feat(dependabot): add server check for dependabot config

__snapshots__/features/favorites/components/NotConnectedFavorites.native.test.tsx.native-snap, __snapshots__/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx.native-snap, src/features/favorites/components/NotConnectedFavorites.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.tsx
I have:
| iOS              |   ![Capture d’écran 2024-01-12 à 15 18 49](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/d0430b25-6242-4dfa-867c-c8722323e989) ![Capture d’écran 2024-01-12 à 15 18 36](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/41919e98-f773-4fe9-a7a9-1bea0bb57915) | ![Capture d’écran 2024-01-12 à 15 41 12](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/02189e25-4226-4087-9a7b-16b48b5ad3eb)  ![Capture d’écran 2024-01-12 à 15 20 27](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/d3464e9b-5ba0-4629-8a8c-efad5cb2d374)  |
| Android          | …
=> (BSR) feat(offer): Fix cta position for signup signin offer to favorite

src/features/home/components/HomeBodyPlaceholder.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx, src/ui/components/placeholders/OfferPlaylistSkeleton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26902
https://sonarcloud.io/project/issues?resolved=false&rules=typescript:S6550&types=CODE_SMELL&id=pass-culture_pass-culture-app-native
=> (PC-26902) fix(Sonar): fix sonar issue offer skeleton

.github/dependabot.yml
=> chore(deps): update prefix commit message for depandabot config server

scripts/dead_code_snapshot.txt, src/features/auth/components/AuthenticationButton/AuthenticationButton.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx, src/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.tsx, src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.native.test.tsx, src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.tsx, src/features/tutorial/pages/onboarding/OnboardingAgeInformation.native.test.tsx, src/features/tutorial/pages/onboarding/OnboardingAgeInformation.tsx, src/features/tutorial/pages/onboarding/OnboardingWelcome.native.test.tsx, src/features/tutorial/pages/onboarding/OnboardingWelcome.tsx, src/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.tsx, src/shared/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx, src/shared/offer/components/AuthenticationModal/AuthenticationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26926
I have:
=> (PC-26926) refactor(Auth): remove unused nav params preventCancellation

src/service-worker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26473
https://sonarcloud.io/project/security_hotspots?id=pass-culture_pass-culture-app-native
=> (PC-26473) fix(Sonar): fix backtracing regex

__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, src/features/search/helpers/categoriesHelpers/mapping-tree.ts, src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.native.test.ts, src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26503
I have:
| Desktop - Chrome |![Capture d’écran 2024-01-15 à 17 04 17](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/697d79d2-3f35-41ec-a32b-8cdf00eb8860) |![Capture d’écran 2024-01-15 à 17 03 43](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/ed6598e0-0018-46df-aa4d-97922db01ab8)|
=> (PC-26503) feat(CategoriesModal): reorder categories filter

src/features/search/components/SearchList/SearchList.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26061
I have:
| Phone - Chrome   |<img width="393" alt="Capture d’écran 2024-01-16 à 10 15 18" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/c5094510-e7e8-4a25-a329-a64c50d8f17d">|<img width="392" alt="Capture d’écran 2024-01-16 à 10 15 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/f4e4433c-db27-49c5-bcfa-6b6477924343">|
| Desktop - Chrome |<img width="865" alt="Capture d’écran 2024-01-16 à 10 15 08" …
=> (PC-26061) fix(search): remove useless whitespace when there is not venues playlist

doc/development/tests/unit-test/cook-book.md, src/features/auth/context/AuthContext.native.test.tsx, src/features/identityCheck/pages/profile/SetAddress.native.test.tsx, src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.native.test.tsx, src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx, src/features/profile/pages/NotificationSettings/NotificationSettings.tsx, src/features/trustedDevice/pages/SuspensionChoice.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26767
=> (PC-26767) test(msw): use new msw server in some tests

__snapshots__/features/auth/pages/login/Login.native.test.tsx.native-snap, src/features/auth/api/useSignIn.ts, src/features/auth/components/SSOButton/SSOButton.stories.tsx, src/features/auth/components/SSOButton/SSOButton.tsx, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/login/Login.web.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.web.test.tsx, src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/ui/components/SeparatorWithText.stories.tsx, src/ui/components/SeparatorWithText.tsx, src/ui/svg/icons/socialNetwork/Google.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26911
I have:
| Platform      | After |
| :------------ | :---: |
| iOS              |                 <img width="300" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/e2445a6d-02d4-4ed2-ba4a-b66aaee0bbaa" /><img width="300" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/6a3a03f8-f26d-4812-9d7f-0b08c698c5ad"/>  |
| Android          |           <img width="300" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/9582a86e-f652-402c-9e36-7535e465cdb3"/> <img width="300" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/f0023722-9cf3-4f1f-b0fe-190625f1a671"/>           |
| Desktop - Chrome |                  <img …
=> (PC-26911) feat(sso): Add SSO button to signup and login

src/libs/analytics/provider.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26989
I have:
J'ai pas prit le temps de tester
=> (PC-26989) chore(e2e): fix checking trackers with iOS simulator

src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.native.test.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27022
I have:
=> (PC-27022) refactor(venueSelectionModal): remove geolocationActivationModal already in LocationWrapper

__snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap, src/features/search/pages/Search/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25003
I have:
| iOS              |<img width="434" alt="Capture d’écran 2024-01-19 à 10 23 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/fc25adf7-9a9c-4250-a7bb-32592c530845">|<img width="415" alt="Capture d’écran 2024-01-19 à 10 24 15" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/39d4fa90-2736-4e2a-b5fd-a7bd6e352ff3">|
| Android          |<img width="427" alt="Capture d’écran 2024-01-19 à 10 22 49" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0ea37d69-49d7-4214-842a-7728a7fe3f4c">|<img width="412" …
=> (PC-25003) fix(search): more spacing after search box

src/features/offer/components/OfferPlaylist/api/fetchOffersByArtist.test.ts, src/features/offer/components/OfferPlaylist/api/fetchOffersByArtist.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26891
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/a59fa111-8713-4bf3-9752-672367de2f74
=> (PC-26891) feat(SameArtistPlaylist): we don't want to display the same artist playlist if the name is "collectif"

src/features/auth/api/useOAuthState.ts, src/features/auth/components/SSOButton/SSOButton.native.test.tsx, src/features/auth/components/SSOButton/SSOButton.tsx, src/features/auth/components/SSOButton/SSOButtonBase.stories.tsx, src/features/auth/components/SSOButton/SSOButtonBase.tsx, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26914
I have:
=> (PC-26914) refactor(sso): Handle signin in button

ios/Podfile.lock, package.json, src/features/identityCheck/pages/identification/educonnect/EduConnectForm.tsx, web/config/webpack.config.js, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25575
@dependabot recreate
I have:
=> (PC-25575) chore(bsr): bump react native gesture handler

.github/workflows/dev_on_workflow_check_folder_change.yml
Deleted files were ignored. For example, when a file was deleted,
tests were not executed. We would like to execute tests when files are
deleted.
As per the docs (https://github.com/tj-actions/changed-files#outputs-):
any_changed: includes a combination of all added, copied, modified
and renamed files (ACMR)
any_modified: includes a combination of all added, copied,
modified, renamed, and deleted files (ACMRD).
=> (BSR) fix(ci): Detect deleted files in check_folder_changes workflow

ios/Podfile.lock, package.json, src/features/identityCheck/pages/identification/educonnect/EduConnectForm.tsx, web/config/webpack.config.js, yarn.lock
Reverts pass-culture/pass-culture-app-native#5874
=> (BSR) chore(bsr): revert bump react native gesture handler

src/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26684
I have:
=> (PC-26684) feat(VenueOffersNew): no limit on gtl playlists display

babel.config.js, ios/Podfile.lock, package.json, patches/react-native-reanimated+2.17.0.patch, src/features/identityCheck/pages/identification/educonnect/EduConnectForm.tsx, web/config/webpack.config.js, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27589
- all test pass
- local web works fine
- build web:testint wihout any warnings
- ios works fine
- android works fine
=> (PC-27589) chore(bsr): update react-native-gesture-handler

src/features/home/pages/GenericHome.native.test.tsx, src/features/search/pages/modals/LocationModal/LocationModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27547
J'ai pas reproduit en local, mais j'ai run les tests 5 fois, et ils n'ont pas cassé : à surveiller
=> (PC-27547) test(home): make a test not flaky anymore

src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/TabBar.web.tsx, src/features/navigation/TabBar/TabNavigator.tsx, src/features/navigation/TabBar/__tests__/TabBar.native.test.tsx, src/features/navigation/TabBar/useTabBar.tsx
=> (BSR) fix(web): Cannot update a component (_TabNavigationStateProvider)

src/features/search/helpers/useScrollToBottomOpacity/useScrollToBottomOpacity.ts, src/ui/components/Spinner.tsx, src/ui/components/animationUseNativeDriver.ts, src/ui/components/bars/AnimatedProgressBar.tsx
=> (BSR) fix(yellowbox): useNativeDriver is not supported because the native animated module is missing.

src/features/profile/pages/Accessibility/AccessibilityDeclaration.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27549
J'avais reproduit au 2ᵉ essai, fait ce fix, puis j'ai testé 6 fois et je n'ai pas reproduit.
=> (PC-27549) test(a11yDeclaration): fix flaky test

src/features/favorites/components/FavoritesResults.tsx, src/features/favorites/pages/Favorites.tsx, src/features/favorites/pages/Favorites.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27545
J'ai clean un peu la façon dont est fait le test et le code. J'ai lancé plusieurs fois en local et fais run plusieurs fois la CI.
Le test semble passer à chaque run.
=> (PC-27545) fix(Favorites): fix flakyness test Favorites.web

yarn.lock
=> (BSR) chore(deps): Update browserlist to latest

yarn.lock
This reverts commit df69cc821cecee911a7a88b2d264365513f1b334.
I have:
=> (BSR) chore(deps): Revert Update browserlist to latest (#5891) 

src/features/auth/helpers/useLogoutRoutine.native.test.ts, src/features/auth/helpers/useLogoutRoutine.ts
Added dependencies to useCallback, Run all async functions of Logout in parallel to improve speed, added sentry setUser to null, and added test
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26785
I have:
Tested by enabling Sentry in development (set eventMonitorin.init enabled to true in App.web.tsx if testing on web app), disconnecting, going to cheat menu to send a sentry exception, and checking on Sentry interface that no user id is in the exception report (it should be replaced by the user's IP).
=> (PC-26785) fix(Logout): removed information in sentry about user in logout

src/features/bookOffer/components/BookingDetails.native.test.tsx, src/features/bookOffer/components/BookingDetails.tsx, src/features/offer/components/OfferBody/OfferBody.tsx, src/features/offer/components/OfferPlaceOld/OfferPlaceOld.native.test.tsx, src/features/offer/components/OfferPlaceOld/OfferPlaceOld.tsx, src/features/offer/components/VenueSelectionList/VenueSelectionList.native.test.tsx, src/features/offer/components/VenueSelectionList/VenueSelectionList.stories.tsx, src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.native.test.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.stories.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx, src/features/offer/components/VenueSelectionModal/VenueSelectionModal.web.test.tsx, src/features/offer/helpers/getVenueSelectionHeaderMessage.ts, src/features/offerv2/components/OfferContent/OfferContent.tsx, src/features/offerv2/components/OfferPlace/OfferPlace.native.test.tsx, src/features/offerv2/components/OfferPlace/OfferPlace.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27024
I have:
=> (PC-27024) feat(VenueSelectionModal): transform into generic component

src/features/auth/constants.ts, src/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx, src/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/auth/pages/signup/SetPassword/SetPassword.native.test.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.tsx, src/features/auth/stepConfig.ts, src/features/auth/types.ts, src/features/internal/cheatcodes/pages/AppComponents/AppComponents.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25587
I have:
| iOS              |       [ios.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/21689569-ee8d-4bce-82b1-48f45a822719)   |
| Desktop - Chrome |     [web.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/5023998e-f78a-4fc5-8f4b-95d75564fb3)           |
=> (PC-25587) feat(sso): Redirect to birthday step for sso signup

src/features/bookOffer/components/BookingDetails.native.test.tsx, src/features/favorites/components/BicolorFavoriteCount.native.test.tsx, src/features/favorites/components/BicolorFavoriteCount.web.test.tsx, src/features/favorites/components/Favorite.native.test.tsx, src/features/favorites/helpers/simulateBackend.ts, src/features/home/components/modules/HighlightOfferModule.native.test.tsx, src/features/navigation/RootNavigator/Header/Header.web.test.tsx, src/features/offer/pages/Offer/Offer.perf.test.tsx, src/libs/firebase/analytics/__tests__/provider.web.test.ts, src/ui/components/buttons/FavoriteButton.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/81?selectedIssue=PC-26769
=> (PC-26279) refactor(msw): replace server use with msw

src/features/gtlPlaylist/api/gtlPlaylistApi.native.test.ts, src/features/gtlPlaylist/api/gtlPlaylistApi.ts, src/features/gtlPlaylist/components/GtlPlaylist.native.test.tsx, src/features/gtlPlaylist/fixtures/gtlPlaylistAlgoliaSnapshot.ts, src/features/gtlPlaylist/hooks/useGTLPlaylists.native.test.ts, src/features/gtlPlaylist/hooks/useGTLPlaylists.ts, src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx, src/features/venue/pages/Venue/Venue.native.test.tsx, src/features/venue/pages/Venue/Venue.perf.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26685
I have:
=> (PC-26685) feat(venue): display enough gtl playlists

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27721
=> (PC-27721) feat(config): add wipCinemaOfferVenueBlock feature flag

src/features/home/pages/GenericHome.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27779
=> (PC-27779) test(ci): skip flaky test GenericHome

src/features/home/api/useAlgoliaRecommendedOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27562
I have:
=> (PC-27562) fix(useAlgoliaRecommendedOffers): add ids to query keys

src/features/offerv2/helpers/getOfferTags/getOfferTags.test.ts, src/features/offerv2/helpers/getOfferTags/getOfferTags.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25615
I have:
=> (PC-25615) feat(tags): add cinema genres into tags list

__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap, src/features/auth/helpers/useDatePickerErrorHandler.native.test.tsx, src/features/auth/helpers/useDatePickerErrorHandler.tsx, src/features/auth/pages/signup/SetBirthday/SetBirthday.tsx, src/features/internal/marketingAndCommunication/atoms/DateChoice.native.test.tsx, src/features/internal/marketingAndCommunication/atoms/DateChoice.tsx, src/features/internal/marketingAndCommunication/atoms/DateChoice.web.test.tsx, src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.native.test.tsx, src/shared/date/getPastYears.native.test.ts, src/shared/date/getPastYears.ts, src/ui/components/inputs/DateInput/DateInput.native.test.tsx, src/ui/components/inputs/DateInput/DateInput.stories.tsx, src/ui/components/inputs/DateInput/DateInput.web.test.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.native.test.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.web.test.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.web.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.tsx, src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.web.tsx, src/ui/components/inputs/DateInput/DatePicker/types.ts, src/ui/components/inputs/DateInput/atoms/DateInputDesktop.web.tsx, src/ui/components/inputs/DateInput/hooks/useDatePickerOptions.ts, src/ui/components/inputs/DateInput/hooks/useDatePickerOptions.web.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27479
I have:
Concernant le générateur de deeplinks, j'ai vu avec Valentine avant d'enlever la possibilité de mettre une date dans la recherche seulement en native !
=> (PC-27479) refactor(DateInput): prepare to react hook formate set birthday

src/features/venue/components/VenueBodyNew/VenueBodyNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffersNew.tsx
Removed useIsFetching that was giving us inaccurate information about fetching state
Replaced by usage of isLoading of useVenueOffers
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27752
=> (PC-27752) fix(venue): removed useIsFetching

.maestro/README.md, scripts/run_e2e_tests.sh, src/libs/analytics/provider.ts
=> (BSR) fix(e2e): Fix analytics tests

src/features/offerv2/components/OfferVenueBlock/OfferVenueBlock.tsx, src/features/offerv2/components/OfferVenueButton/OfferVenueButton.native.test.tsx, src/features/offerv2/components/OfferVenueButton/OfferVenueButton.tsx, src/ui/components/hero/HeroHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25607
I have:
=> (PC-25607) fix(OfferV2): review ui and fix some bugs

src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/features/offerv2/components/OfferPlace/OfferPlace.native.test.tsx, src/features/offerv2/components/OfferPlace/OfferPlace.tsx, src/features/offerv2/components/OfferVenueBlock/OfferVenueBlock.native.test.tsx, src/features/offerv2/components/OfferVenueBlock/OfferVenueBlock.tsx, src/features/offerv2/components/OfferVenueBlock/OfferVenueBlockDeprecated.native.test.tsx, src/features/offerv2/components/OfferVenueBlock/OfferVenueBlockDeprecated.tsx, src/ui/svg/icons/RightFilled.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27719
I have:
| Platform         | Mockup/Before | After | After with distance | After non-permanent |
| :--------------- | :-----------: | :---: | :---: | :---: |
| iOS              | <img width="475" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/8b28d8ba-4b86-4db4-a909-bf1f1d69db6e"> | <img width="354" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/736f09d6-f42f-4a36-89e5-7f46532c8262"> | <img width="352" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/2f3264fa-fab5-4df9-998b-967303aa9c08"> | <img width="352" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/b6a …
=> (PC-27719) feat(offer): update offer venue block

src/features/offer/components/AddToFavoritesButton/AddToFavoritesButton.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26770
I have:
=> (PC-26770) refactor(AddToFavoriteButton): remove server.use and use msw mock for this test

src/features/offer/api/useSimilarOffers.native.test.ts, src/features/offer/api/useSimilarOffers.ts
…
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26922
I have:
=> (PC-26922) refactor(useSimilarOffers): use useQuery instead of useState/useEffect method

src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26915
I have:
###WEB
###IOS
=> (PC-26915) feat(SSO): Added error snackbar to SSO login/register

src/features/search/components/SearchSuggestions/SearchSuggestions.tsx, src/features/search/pages/SearchLanding/SearchLanding.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27869
I have:
| before | after |
| -------| -----|
| https://github.com/pass-culture/pass-culture-app-native/assets/70148476/a29bfb76-7653-48a2-bc1e-8dadea427ecd | https://github.com/pass-culture/pass-culture-app-native/assets/70148476/bacf9e5d-4f77-4dd0-a2d3-32a5e951c6f4   |
=> (PC-27869) fix(SearchSuggestions): fix hide suggestion on press venue

scripts/dead_code_snapshot.txt, src/api/gen/api.ts, src/features/offer/fixtures/offerResponse.ts, src/features/offerv2/components/OfferVenueBlock/OfferVenueBlock.native.test.tsx, src/features/offerv2/components/OfferVenueBlock/OfferVenueBlock.tsx, src/features/offerv2/components/OfferVenueBlock/useVenueBlock.ts, src/features/offerv2/components/OfferVenueButton/OfferVenueButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27720
I have:
| Platform         | Mockup/Before | After | After with placeholder |
| iOS              | <img width="600" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/467ab469-1964-4103-b21c-c5409bb54fbf"> | <img width="352" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/74a7c55b-1f7b-478d-b4ce-842a4f1aa296"> | <img width="353" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/0384d7e0-6b55-4454-975b-3255a48e068f"> |
| Desktop - Chrome | <img width="898" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/26e48121- …
=> (PC-27720) feat(offer): get venue image for venue block

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27695
=> (PC-27695) feat(ff): add venue map FFs

src/features/search/components/SearchBox/SearchBox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27903
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/70148476/f9437835-966b-4b7e-9c37-2f50b25de0a3
https://github.com/pass-culture/pass-culture-app-native/assets/70148476/a1e1b864-5512-491a-936b-fd73c428ef85
=> (PC-27903) fix(SearchBox): fix setQuery condition

src/features/offer/components/OfferPlaceOld/OfferPlaceOld.tsx, src/features/offerv2/components/OfferPlace/OfferPlace.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27917
I have:
=> (PC-27917) fix(offerPlace): use userPosition instead of geolocation

__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap, scripts/dead_code_snapshot.txt, src/features/auth/pages/login/Login.native.test.tsx, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx, src/features/auth/pages/signup/SetBirthday/SetBirthday.tsx, src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx, src/features/auth/pages/signup/SignupForm.native.test.tsx, src/features/auth/pages/signup/SignupForm.tsx, src/features/auth/types.ts, src/features/navigation/RootNavigator/types.ts
…ount does not existLink to JIRA ticket: https://passculture.atlassian.net/browse/PC-26916
I have:
| Platform        | After |
| :-------------- | :---: |
| iOS                             |    [ios.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/266f88dd-06a2-443f-8243-716228613a46)   |
| Desktop - Chrome               |  [web.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/68e697b6-50eb-4c63-82b0-fbd8dae39641)     |
=> (PC-26916) feat(sso): Redirect from login to signup when account does not exist

src/features/offer/helpers/useOfferSummaryInfoList/useOfferSummaryInfoList.native.test.tsx, src/features/offer/helpers/useOfferSummaryInfoList/useOfferSummaryInfoList.tsx, src/features/offerv2/components/OfferArtists/OfferArtists.tsx, src/features/offerv2/components/OfferContent/OfferContent.native.test.tsx, src/features/offerv2/components/OfferContent/OfferContent.tsx, src/features/offerv2/components/OfferSummaryInfoList/OfferSummaryInfoList.native.test.tsx, src/features/offerv2/components/OfferSummaryInfoList/OfferSummaryInfoList.stories.tsx, src/features/offerv2/components/OfferSummaryInfoList/OfferSummaryInfoList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27889
I have:
| Phone - Chrome   |<img width="390" alt="Capture d’écran 2024-02-12 à 09 48 01" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/e2c02fc9-3178-403a-8a06-e1a45cc62738">|<img width="391" alt="Capture d’écran 2024-02-12 à 09 48 40" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/a4bd9d41-9b65-41ca-93a0-23aef73a00d0">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6 …
=> (PC-27889) feat(OfferContent): correct spacings

__snapshots__/libs/recaptcha/ReCaptcha.native.test.tsx.native-snap, src/libs/recaptcha/ReCaptcha.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27590
I have:
| iOS              | ![Simulator Screen Shot - iPhone 14 Pro Max - 2023-10-05 at 10 44 13](https://github.com/pass-culture/pass-culture-app-native/assets/158567429/d562c550-1300-4282-a78d-dc73f7960f1f)              |<img width="370" alt="iphone15" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/51c83268-d289-4f16-84ca-5a45643e2caa">     |
| Android          |               |<img width="317" alt="androidWithNotch" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/41229a03-dc02-4ae3-846f-ab2448ea45b3">    | …
=> (PC-27590) fix(captcha): Fix captcha display when phonescreen has notches

scripts/dead_code_snapshot.txt, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/search/components/VenueMapBlock/VenueMapBlock.native.test.tsx, src/features/search/components/VenueMapBlock/VenueMapBlock.tsx, src/features/search/pages/VenueMap/VenueMap.native.test.tsx, src/features/search/pages/VenueMap/VenueMap.tsx, src/ui/components/headers/PageHeaderWithoutPlaceholder.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27592
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/b916bb46-e50e-4de2-bd8c-1a179a74591e
=> (PC-27592) feat(VenueMap): add venue map screen

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27933
I have:
=> (PC-27933) feat(Search): add Feature Flag WIP_SEARCH_ACCESSIBILITY_FILTERS

src/features/errors/pages/BannedCountryError.native.test.tsx, src/features/errors/pages/BannedCountryError.web.test.tsx, src/features/home/api/useShowSkeleton.native.test.ts, src/features/home/components/modules/OffersModule.native.test.tsx, src/features/home/components/modules/OffersModule.tsx, src/features/home/components/modules/RecommendationModule.native.test.tsx, src/features/home/components/modules/venues/VenueTile.native.test.tsx, src/features/home/components/modules/venues/VenuesModule.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22237
I have:
=> (PC-22237) test(home): Remove react-query mock

src/features/auth/api/useAccountUnsuspend.ts, src/features/auth/helpers/useLoginRoutine.native.test.ts, src/features/auth/helpers/useLogoutRoutine.native.test.ts, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.web.test.tsx, src/features/auth/pages/forgottenPassword/ResetPasswordExpiredLink/ResetPasswordExpiredLink.web.test.tsx, src/features/auth/pages/signup/SignupConfirmationExpiredLink/SignupConfirmationExpiredLink.web.test.tsx, src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.web.test.tsx, src/features/auth/pages/suspendedAccount/SuspendedAccountUponUserRequest/SuspendedAccountUponUserRequest.native.test.tsx, src/features/auth/pages/suspendedAccount/SuspendedAccountUponUserRequest/SuspendedAccountUponUserRequest.web.test.tsx, src/ui/components/snackBar/SnackBarContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22231
I have:
=> (PC-22231) test(reactQuery): remove react-query mock from auth feature

src/features/offerv2/components/OfferVenueBlock/OfferVenueBlock.tsx, src/ui/svg/icons/RightFilled.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27966
I have:
| Android          | <img width="387" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/bdc3d8e8-9f3d-4171-a47c-792c77a56f60"> | <img width="387" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/c4c264b1-14ac-4dac-8c40-8f522cef70b3"> |
| Phone - Chrome   | <img width="376" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/76a9ef54-2137-4a75-8416-e4bcdd0c7e88"> | <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/cb30ecb4-fb64-4b49-8158-e19e06ae41a0"> | …
=> (PC-27966) fix(offerVenueBlock): fix ui

src/features/identityCheck/pages/Stepper.native.test.tsx, src/features/identityCheck/pages/Stepper.web.test.tsx, src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx, src/features/identityCheck/pages/identification/errors/eduConnect/EduConnectErrorBoundary.native.test.tsx, src/features/identityCheck/pages/profile/SetAddress.web.test.tsx, src/features/identityCheck/pages/profile/SetCity.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22238
I have:
=> (PC-22238) test(IdentityCheck): remove react query mock

src/features/bookings/api/useCancelBookingMutation.test.ts, src/features/bookings/components/CancelBookingModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22334
I have:
=> (PC-22234) test(reactQuery): use reactQueryHOC instead of react-query in CancelBooking

src/features/offer/components/OfferBody/OfferBody.web.test.tsx, src/features/offer/components/VenueSection/VenueSection.native.test.tsx, src/shared/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx, src/shared/offer/components/ErrorApplicationModal/ErrorApplicationModal.native.test.tsx, src/shared/offer/helpers/useBookOfferModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22239
=> (PC-22239) test(offer): remove react-query mocks

src/features/bookOffer/components/BookDuoChoice.native.test.tsx, src/features/bookOffer/components/BookHourChoice.native.test.tsx, src/features/bookOffer/components/BookingEventChoices.native.test.tsx, src/features/bookOffer/components/BookingInformations.native.test.tsx, src/features/bookOffer/components/BookingOfferModalFooter.native.test.tsx, src/features/bookOffer/pages/BookingConfirmation.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22236
=> (PC-22236) test(bookOffer): remove react-query mock

src/features/search/components/NumberOfResults/NumberOfResults.native.test.tsx, src/features/search/components/SearchHeader/SearchHeader.web.test.tsx, src/features/search/components/SearchList/SearchList.native.test.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx, src/features/search/pages/Search/Search.native.test.tsx, src/features/search/pages/Search/Search.web.test.tsx, src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.web.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx, src/features/search/pages/modals/PriceModal/PriceModal.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22242
=> (PC-22242) test(Search): remove react query mock

.maestro/tests/SuppressionReactivationCompte.yml, scripts/run_e2e_tests.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27921
I have:
=> (PC-27921) feat(maestro): add new maestro email

src/features/bookings/components/OnGoingBookingsList.native.test.tsx, src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx, src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27985
I have:
=> (PC-27985) test(reactQuery): remove react query from bookings

src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx, src/features/search/helpers/useAppliedFilters/useAppliedFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27934
I have:
=> (PC-27934) feat(SearchResultsContent): add accessibilty filter button

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap, scripts/dead_code_snapshot.txt, src/features/auth/pages/suspendedAccount/SuspendedAccountUponUserRequest/SuspendedAccountUponUserRequest.web.test.tsx, src/features/bookOffer/pages/BookingOfferModal.web.test.tsx, src/features/offer/components/OfferBody/OfferBody.web.test.tsx, src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.web.test.tsx, src/features/profile/pages/ChangePassword/ChangePassword.web.test.tsx, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.native.test.tsx, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmail.web.test.tsx, src/features/profile/pages/ConsentSettings/ConsentSettings.web.test.tsx, src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx, src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.web.test.tsx, src/features/profile/pages/NotificationSettings/NotificationSettings.web.test.tsx, src/features/profile/pages/PersonalData/PersonalData.native.test.tsx, src/features/profile/pages/PersonalData/PersonalData.web.test.tsx, src/features/profile/pages/Profile.native.test.tsx, src/features/profile/pages/Profile.web.test.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.native.test.tsx, src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.web.test.tsx, src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.native.test.tsx, src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.web.test.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx, src/tests/utils.tsx, src/tests/utils/web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22241
I have:
=> (PC-22241) test(profile): Remove react-query mock

__snapshots__/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx.native-snap, src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/features/profile/components/Banners/UpdateAppBanner.tsx, src/features/profile/components/VerticalStepper/VerticalStepper.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChange.tsx, src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/getFeatureFlag.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.native.test.ts, src/libs/firebase/firestore/featureFlags/useFeatureFlag.ts, src/libs/firebase/firestore/types.ts, src/ui/svg/icons/StepperValidate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27868
I have:
| iOS              |![Simulator Screenshot - iPhone 13 - 2024-02-13 at 12 00 19](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/a53b6c71-f974-4146-8b42-98efe5b5f7df)     ![Simulator Screenshot - iPhone 13 - 2024-02-13 at 11 45 13](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/fbb11d43-da35-4762-a449-61d76f4612be)          |    ![Simulator Screenshot - iPhone 13 - 2024-02-13 at 11 43 29](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/4aea9949-c5ff-4d9b-91fc-5f9bf96ab1e2) ![Simulator Screenshot - iPhone 13 - 2024-02-13 at 11 44 …
=> (PC-27868) feat(ChangeEmail): Add banner when old email change is disabled

src/features/home/pages/GenericHome.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27690
J'ai relancé 10 fois la CI, insh' ça passe
=> (PC-27690) test(GenericHome): fix flaky test

__snapshots__/features/search/components/sections/Accessibility/Accessibility.native.test.tsx.native-snap, src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx, src/features/search/components/sections/Accessibility/Accessibility.native.test.tsx, src/features/search/components/sections/Accessibility/Accessibility.tsx, src/features/search/components/sections/index.ts, src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx, src/features/search/pages/SearchFilter/SearchFilter.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27934
I have:
##Info
J'ai envoyé un message à Agathe pour voir si on peut passer la description sur une ligne c'est plus logique niveau code et même niveau visuel je trouve
| iOS              | <img width="410" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/bd7c801d-75c4-4885-bf2b-6977a533fe5a">  |  <img width="412" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/8493291c-8bd4-4162-b5be-0806f5e580a6">  |
| Android          |  <img width="410" alt="image" …
=> (PC-27934) feat(SearchFilter): create accessibility section

src/features/identityCheck/pages/Stepper.web.test.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28001
=> (PC-28001) test(revert): fix broken tests

src/features/home/api/useHomeRecommendedOffers.ts, src/features/home/components/modules/RecommendationModule.tsx, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.ts, src/libs/subcategories/types.ts, src/types/RecordOfString.d.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-20799
=> (PC-20799) fix(reco): don't send null as subcategory

.github/workflows/dev_on_workflow_web_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27541
Exemple de run : https://github.com/pass-culture/pass-culture-app-native/actions/runs/7669791902/job/20904510290
I have:
=> (PC-27541) ci(web): deploy index.html after assets

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap, src/features/venue/components/VenueCTA/VenueCTA.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26720
I have:
| iOS              |    ![Simulator Screenshot - iPhone 5 - 2024-02-15 at 12 30 43](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/dd936e5a-d788-4b62-a726-5fdd6d0ca8aa)           |   ![Simulator Screenshot - iPhone 5 - 2024-02-15 at 12 09 20](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/2d6ba8e2-195c-462e-8182-0443c89a0dae)    |
| Android |     ![android-old](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/1846be00-f97a-4421-b03b-7f89352ce191)           |    ![android-new](https://github.com/pass-culture/pass-culture-app-native …
=> (PC-26720) feat(venue): Update styling

src/features/profile/pages/ValidateEmailChange/SubtitleComponent.tsx, src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27167
I have:
| iOS              |   ![Simulator Screenshot - iPhone 13 - 2024-02-15 at 16 36 34](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/0a167c54-2c03-4499-82b4-a6504df961e8)            |    ![Simulator Screenshot - iPhone 13 - 2024-02-15 at 16 31 49](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/0ef1d547-2488-4627-a69a-6bcca109c5ad) |
| Desktop - Chrome |         <img width="1189" alt="Capture d’écran 2024-02-15 à 16 36 46" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/e3f039b7-5ef0-4e5f-90c8-58e20a8fe508">      |     <img …
=> (PC-27167) feat(EmailChange): Change wording for email validation

src/features/venue/components/VenueOffers/VenueOffersNew.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27826
Pour info j'ai testé en web avec et sans usecallback dans le renderItem, le nombre de rerendu est le même
I have:
=> (PC-27826) refactor(VenueOffersNew): remove useless useCallbacks

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-28051
I have:
=> (PC-28051) feat(useFeatureFlag): add WIP_ENABLE_SELECT_CINEMA_MODAL feature flag

__snapshots__/ui/components/eventCard/EventCardList.native.test.tsx.native-snap, src/features/internal/cheatcodes/pages/AppComponents/MovieCalendar/CheatcodeMovieCalendar.tsx, src/ui/components/eventCard/EventCard.tsx, src/ui/components/eventCard/EventCardList.native.test.tsx, src/ui/components/eventCard/EventCardList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27844
I have:
=> (PC-27844) feat(EventCardList): update eventcard design

src/features/venuemap/components/VenueMapView/VenueMapView.tsx, src/features/venuemap/pages/VenueMap/VenueMap.native.test.tsx, src/features/venuemap/useGetAllVenues.native.test.ts, src/features/venuemap/useGetAllVenues.ts, src/libs/maps/maps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27594
I have:
| iOS              |               | <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/3482cfd6-2a75-4b3c-a577-fe2f4878fdd1"> |
| Android          |               | <img width="470" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/9b500703-dbd3-4aaa-a19e-145f509f033a"> |
=> (PC-27594) feat(venueMap): fetch venues on the map

.maestro/tests/ReservationOffreEvenement.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27922
I have:
=> (PC-27922) feat(maestro): added new maestro test for event reservation

__snapshots__/features/accessibility/AccessibilityFiltersModal.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx.native-snap, __snapshots__/features/search/components/sections/Accessibility/Accessibility.native.test.tsx.native-snap, __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap, src/features/accessibility/AccessibilityFiltersModal.native.test.tsx, src/features/accessibility/AccessibilityFiltersModal.tsx, src/features/accessibility/AccessibilityFiltersModal.web.test.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.tsx, src/features/search/components/sections/Accessibility/Accessibility.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27935
I have:
Maquette :  https://www.figma.com/file/g96t9IYtBhYKxJu4qwaL7s/Accessibilit%C3%A9-lieux-filtre?node-id=371%3A4907&mode=dev
Note : Vu avec Agathe pour les différences entre le composant Checkbox déjà existant qui n'est pas exactement comme sur la maquette => on garde le composant existant donc le padding entre la checkbox et le texte est plus important + la checkbox est plus foncée
=> (PC-27935) feat(Search): Create accessibility filters modal

package.json, src/features/venuemap/components/VenueMapView/VenueMapView.tsx, src/libs/maps/maps.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27809
I have:
| iOS              |               |![Capture d’écran 2024-02-22 à 09 35 33](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/e57598fd-33a7-42fe-b4f1-523db324ace9)|
| Android          |               |![Capture d’écran 2024-02-22 à 09 37 32](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/3ff2daee-61c9-4386-9de4-7b3635e32dea)|
=> (PC-27809) feat(VenueMapView): add clustering

src/libs/subcategories/fixtures/mappings.ts, src/libs/subcategories/mappings.ts, src/libs/subcategories/placeholderData.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28081
Il n'y a plus les anciennes sous-catégories sur Contentful testing, et j'ai créé les nouveaux champs pour Contentful prod (je n'ai pas encore supprimé les anciens)
=> (PC-28081) fix(subcategories): update subcategories via API call

src/features/home/api/useGetOffersData.ts, src/features/home/api/useVideoOffers.ts, src/features/home/types.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/fetchMultipleOffers.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistLocationParameters.native.test.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistLocationParameters.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.native.test.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/buildOffersModulesQueries.native.test.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/buildOffersModulesQueries.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/useAdaptOffersPlaylistParameters.ts, src/libs/algolia/fetchAlgolia/fetchOffersModules.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28127
I have:
| Desktop - Chrome |https://github.com/pass-culture/pass-culture-app-native/assets/47600889/9a2622b3-2027-446c-85cd-f15acf3e0ae4|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/b99249de-34e4-422c-8211-a09c86cc928a|
=> (PC-28127) fix(home): fix home located playlist

__snapshots__/features/auth/pages/login/Login.native.test.tsx.native-snap, __snapshots__/features/auth/pages/signup/AcceptCgu/AcceptCgu.native.test.tsx.native-snap, __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap, ios/Podfile.lock, src/features/auth/pages/login/Login.tsx, src/features/auth/pages/signup/AcceptCgu/AcceptCgu.tsx, src/shared/accessibilityProps/accessibleCheckboxProps.ts, src/shared/accessibilityProps/accessibleCheckboxProps.web.test.ts, src/shared/forms/controllers/CheckboxController.tsx, src/ui/components/inputs/Checkbox/Checkbox.stories.tsx, src/ui/components/inputs/Checkbox/Checkbox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27147
I have:
| :--------------- | :---: | :---: |
| iOS              | ![ios-login](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/b9ae6145-0ca9-4f61-abd2-8fcb189b20e0) ![ios-cgu](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/e4bafe62-0c73-42c2-b20f-e74f2878eeac) | ![simu-login](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/56441b4f-a9a3-4c4b-b71b-64ac8677f998) ![simu-cgu](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/33f8f789-6df7-400f-8804-e1d36862bea1)  |
| Android          |       ![android-login](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/5bfe45d7-2d7c- …
=> (PC-27147) fix(accessibility): Make sso accessible

src/features/venuemap/useGetAllVenues.native.test.ts, src/features/venuemap/useGetAllVenues.ts, src/libs/algolia/fetchAlgolia/fetchVenues/buildFetchVenuesQueryParameters.ts, src/libs/algolia/fetchAlgolia/fetchVenues/fetchVenues.ts, src/libs/algolia/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28156
I have:
| iOS              | <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/81e49b55-3b89-462a-93ee-4a959cd9c006"> | <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/0919d0f0-c267-4654-9756-956cfff6617c"> |
=> (PC-28156) feat(venueMap): fix number of venues on map

src/features/identityCheck/api/useGetStepperInfo.native.test.ts, src/features/identityCheck/api/useGetStepperInfo.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26801
I have:
=> (PC-26801) feat(useGetStepperInfo): fix sentry error cannot read property of undefined

src/features/venuemap/components/VenueMapView/VenueMapView.native.test.tsx, src/features/venuemap/components/VenueMapView/VenueMapView.tsx, src/features/venuemap/helpers/calculateDistanceMap.test.ts, src/features/venuemap/helpers/calculateDistanceMap.ts, src/features/venuemap/useGetAllVenues.native.test.ts, src/features/venuemap/useGetAllVenues.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildLocationParameter.ts, src/libs/maps/maps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27600
I have:
| iOS              |<img width="365" alt="Capture d’écran 2024-02-23 à 12 05 26" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/8da7ef0a-979c-4ed7-ab22-fa3d5eceb220">|<img width="440" alt="Capture d’écran 2024-02-23 à 12 09 07" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/54aea17c-1f08-460f-81df-2e4a98dcf356">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6 …
=> (PC-27600) feat(search): add search button on venue map

__snapshots__/ui/components/eventCard/EventCardList.native.test.tsx.native-snap, src/features/accessibility/AccessibilityFiltersModal.tsx, src/features/internal/cheatcodes/pages/AppComponents/MovieCalendar/CheatcodeMovieCalendar.tsx, src/ui/components/eventCard/EventCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27840
I have:
=> (PC-27840) fix(EventCard): fix android pressable

.maestro/tests/ReservationOffreEvenement.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28022
I have:
=> (PC-28022) feat(maestro): improved new offer event test

public/index.html, server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap, server/src/middlewares/tests/webAppProxyMiddleware.test.ts, server/src/services/entities/offer.ts, server/src/services/entities/types.ts, server/src/services/entities/venue.ts, server/src/services/tests/apiClient.test.tsx, server/src/utils/metas.ts, server/src/utils/tests/__snapshots__/metas.test.ts.snap, server/tests/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27010
I have:
=> (PC-27010) feat(metadata): Add keywords

src/features/home/helpers/selectHomepageEntry.native.test.ts, src/libs/firebase/remoteConfig/__mocks__/remoteConfigProvider.tsx, src/libs/firebase/remoteConfig/remoteConfig.constants.ts, src/libs/firebase/remoteConfig/remoteConfig.services.ts, src/libs/firebase/remoteConfig/remoteConfig.services.web.ts, src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27984
I have:
=> (PC-27984) feat(app): add sameAuthorPlaylist remote config

.maestro/tests/ReservationOffreEvenement.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27924
I have:
=> (PC-27924) feat(maestro): added schedule agnostic selection

src/shared/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx, src/ui/components/CollapsibleText/CollapsibleText.native.test.tsx, src/ui/components/CollapsibleText/useIsTextEllipsis.ios.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28119
I have:
=> (PC-28119) fix(collapsible): fix race condition

src/features/offerv2/components/OfferContent/OfferContent.native.test.tsx, src/features/offerv2/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx, src/features/offerv2/components/OfferPlaylistList/OfferPlaylistList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28011
I have:
=> (PC-28011) feat(offer): use sameAuthorPlaylist remote config to manage displaying playlist

.maestro/tests/AccesInscriptionDepuisPageAccueil.yml, .maestro/tests/AffichageBienvenueEtPasCredit.yml, .maestro/tests/BlocInvitationCreerCompte.yml, .maestro/tests/BoutonOeilAfficherMasquerMdp.yml, .maestro/tests/CentreAides.yml, .maestro/tests/ConnexionPossibleDepuisPageOffre.yml, .maestro/tests/ConnexionReussie.yml, .maestro/tests/Deconnexion.yml, .maestro/tests/InstallationOnboardingUneFoisParUtilisateur.yml, .maestro/tests/OffresDetailsPartielsComplets.yml, .maestro/tests/ReservationsMiseEnFavoris.yml, .maestro/tests/ReservationsOffresDuo.yml, .maestro/tests/ReservationsOffresEvent.yml, .maestro/tests/ReservationsOffresPhysiques.yml, .maestro/tests/SaisieMdp.yml, .maestro/tests/SectionAccessibilite.yml, .maestro/tests/SuppressionReactivationCompte.yml, .maestro/tests/reusableFlows/components/buttons/SimpleActionButtonBack.yml, .maestro/tests/reusableFlows/components/buttons/SimpleActionButtonReactivateAccount.yml, .maestro/tests/reusableFlows/components/buttons/SimpleActionButtonSelectionOfferPhysic.yml, .maestro/tests/reusableFlows/features/auth/CguPage.yml, .maestro/tests/reusableFlows/features/auth/QpiEvent.yml, .maestro/tests/reusableFlows/features/auth/QpiPhysical.yml, .maestro/tests/reusableFlows/features/location/resetLoc.yml, .maestro/tests/reusableFlows/features/profile/AccountCreationPage.yml, scripts/run_e2e_tests.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-24917
I have:
=> (PC-24917) feat(maestro): updated maestro workflow

src/features/venuemap/components/VenueMapView/VenueMapView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27709
I have:
=> (PC-27709) feat(search): navigate to venue page when pressing venue pin on map

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, __snapshots__/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx.native-snap, src/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChange.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.web.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContentDeprecated.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContentDeprecated.tsx, src/libs/firebase/firestore/types.ts, src/ui/components/StepButton/StepButton.native.test.tsx, src/ui/components/StepButton/StepButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27162
I have:
| iOS              |      ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/1a83f5e3-a5c4-4876-a7b3-c49a9d5e51e5) ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/32cf8b19-8769-4e80-8485-43b84b2e655a) ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/111a1751-46c7-4352-b869-18bdea95a2e4)    |    ![Simulator Screenshot - iPhone 13 - 2024-02-28 at 08 38 01](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/a129bb55-19cd-4b52-91bf-fbe0386674b7) ![Simulator Screenshot - iPhone 13 - 2024-02-28 at 08 44 …
=> (PC-27162) feat(TrackEmailChange): Design new stepper

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28205
I have:
=> (PC-28205) feat(offer): add preview feature flag

.env.production, .env.staging, .env.testing, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, doc/development/how-to/google-maps.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28118
I have:
=> (PC-28118) chore(android): handle google maps api keys

src/features/auth/pages/suspendedAccount/SuspendedAccountUponUserRequest/SuspendedAccountUponUserRequest.web.test.tsx, src/features/bookOffer/pages/BookingOfferModal.web.test.tsx, src/features/identityCheck/pages/Stepper.web.test.tsx, src/features/search/components/SearchList/SearchList.web.test.tsx, src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx, src/features/search/pages/SearchLanding/SearchLanding.web.test.tsx, src/features/trustedDevice/pages/AccountSecurity.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28042
I have:
=> (PC-28042) test(app): remove react query mock web tests

src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/ui/components/Tag/Tag.native.test.tsx, src/ui/components/Tag/Tag.stories.tsx, src/ui/components/Tag/Tag.tsx, src/ui/svg/icons/Camera.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26138
I have:
| iOS              |<img width="146" alt="Capture d’écran 2024-02-29 à 15 06 19" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/c458457e-924d-4ef7-805b-c9016ba0e4ee">|<img width="113" alt="Capture d’écran 2024-02-29 à 15 06 40" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/05c5dbb0-1ed1-48b6-92df-62a296799947">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6 …
=> (PC-26138) feat(ui): add possibility to use icon in tag

src/features/offerv2/components/OfferPlace/OfferPlace.tsx, src/shared/multiVenueOffer/getIsMultiVenueCompatibleOffer.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-26952
=> (PC-26952) feat(OfferPlace): use cinema modal feature flag

__snapshots__/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx.native-snap, src/ui/components/inputs/BaseTextInput.tsx, src/ui/components/inputs/InputContainer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27160
I have:
| iOS              |<img width="309" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/4918e02c-dbad-4393-bef6-bff7d88c66e5">|<img width="304" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/5ebb2513-4a81-4cf5-817e-86a28b543858">|
| Android          |<img width="402" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/10febb2e-8aba-4c29-b022-e9acedc21fcb">|<img width="399" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ae883c85-27f9-4ae6-a …
=> (PC-27160) fix(ChangeEmail): fix disabled input design in new change email

__snapshots__/features/home/components/modules/OffersModule.native.test.tsx.native-snap, src/features/home/components/modules/OffersModule.native.test.tsx, src/features/home/components/modules/OffersModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-28232
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/70148476/0d500525-d83e-4679-9c70-741fcdc9aac3
=> (PC-28232) feat(OfferModule): fix see more params

src/features/offerv2/components/OfferContent/OfferContent.native.test.tsx, src/features/offerv2/components/OfferContent/OfferContent.tsx, src/features/offerv2/components/OfferContent/OfferContent.web.test.tsx, src/ui/components/hero/Hero.tsx, src/ui/components/hero/__tests__/Hero.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25863
I have:
| iOS              |<img width="296" alt="Capture d’écran 2024-03-04 à 15 18 24" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/42c2a214-c029-45d3-afc0-852b2f912849">|<img width="435" alt="Capture d’écran 2024-03-04 à 15 19 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/40593d0c-bf64-45e1-ac13-63081db8cb28">|
| Android          |               |<img width="411" alt="Capture d’écran 2024-03-04 à 15 19 23" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/d0d2b51e-f7b1-45c1-9f26-6bc30254b4c4">|
| …
=> (PC-25863) feat(offer): add tag on offer image

.eslintrc.js, package.json, src/features/bookOffer/pages/BookingOfferModal.web.test.tsx, src/features/deeplinks/helpers/getScreenFromDeeplink.test.ts, src/features/navigation/RootNavigator/linking/getScreensConfig.ts, src/features/offer/components/OfferHeader/OfferHeader.native.test.tsx, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildNumericFilters.ts, src/libs/algolia/fetchAlgolia/transformOfferHit.ts, src/libs/location/LocationWrapper.tsx, src/types/react-native-flatlist.d.ts, src/ui/components/buttons/buttonWithLinearGradient/types.ts, src/ui/svg/TicketFooter.tsx, src/ui/svg/TicketHeader.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28394
=> (PC-28394) feat(eslint): upgrade eslint to 8.57.0

.maestro/testsV2/SearchAndBookCinemaOffer.yml, .maestro/testsV2/SearchAndBookDuoOffer.yml, .maestro/testsV2/analytics/clear.js, .maestro/testsV2/analytics/hasBeenCalled.js, .maestro/testsV2/reusableFlows/GoToProfileFromTabBar.yml, .maestro/testsV2/reusableFlows/GoToSearchFromTabBar.yml, .maestro/testsV2/reusableFlows/LaunchApp.yml, .maestro/testsV2/reusableFlows/StopApp.yml, .maestro/testsV2/reusableFlows/features/auth/LoginFromProfile.yml, .maestro/testsV2/reusableFlows/features/booking/BookCinemaOffer.yml, .maestro/testsV2/reusableFlows/features/booking/BookDuoOffer.yml, .maestro/testsV2/reusableFlows/features/cookies/AcceptCookies.yml, .maestro/testsV2/reusableFlows/features/search/SearchBookableCinemaOffer.yml, .maestro/testsV2/reusableFlows/features/search/SearchBookableDuoOffer.yml, .maestro/testsV2/reusableFlows/features/tutorial/onboarding/Onboard18.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28261
I have:
=> (PC-28261) feat(maestro): created V2 tree for e2e tests

server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap
=> (BSR) fix(proxy): Update venue snapshot

src/features/offer/components/OfferPlaceOld/OfferPlaceOld.native.test.tsx, src/features/offerv2/components/OfferPlace/OfferPlace.native.test.tsx, src/features/search/fixtures/mockedSearchHistory.ts, src/features/search/helpers/categoriesHelpers/mapping-tree.ts, src/features/search/helpers/categoriesHelpers/mappingFixture.ts, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/libs/subcategories/placeholderData.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27952
I have:
=> (PC-27952) feat(Categories): rename some native categories

src/features/offer/helpers/renderOfferPageTestUtil.tsx, src/features/offer/pages/Offer/Offer.native.test.tsx, src/features/offer/pages/Offer/Offer.tsx, src/features/offer/pages/Offer/Offer.web.test.tsx, src/features/offerv2/components/OfferContentPlaceholder/OfferContentPlaceholder.tsx, src/ui/components/placeholders/Placeholders.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27884
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/78556024/55833c4e-f700-451e-b157-fd7dd6bf6def
https://github.com/pass-culture/pass-culture-app-native/assets/78556024/73f79f34-1aa2-44c9-9815-554c78d1e4f0
=> (PC-27884) feat(offer): display placeholder during offer loading

scripts/dead_code_snapshot.txt, src/features/navigation/screenParamsUtils.ts, src/features/search/context/reducer.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts, src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts, src/features/search/helpers/categoriesHelpers/mapping-tree.ts, src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.native.test.ts, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesSection.tsx, src/features/search/types.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildFacetFilters.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildOfferSearchParameters.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.test.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.native.test.ts, src/libs/algolia/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28004
I have:
| Platform         | N2 | N1 | Video |  
| iOS              |![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-05 at 09 16 10](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/23007a30-5a8c-47dd-851e-787651d41450)|![simulator_screenshot_3192BF28-DFD7-4EEB-8DFF-429B5C849927](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/d89c5a0e-8398-4c90-b491-888baea21b1c)|https://github.com/pass-culture/pass-culture-app-native/assets/47600889/8fdc2282-5616-4bc4-a78c-68096ed83526|
| Desktop - Chrome |<img width="1512" alt="Capture d’écran 2024-03-05 à 09 20 04" …
=> (PC-28004) feat(search): plug new book categories mapping and gtls queries

__snapshots__/features/profile/pages/NewEmailSelection/NewEmailSelection.native.test.tsx.native-snap, scripts/dead_code_snapshot.txt, scripts/noUncheckedIndexedAccess_snapshot.txt, src/api/gen/api.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/profile/helpers/useNewEmailSelectionMutation.ts, src/features/profile/pages/NewEmailSelection/NewEmailSelection.native.test.tsx, src/features/profile/pages/NewEmailSelection/NewEmailSelection.tsx, src/features/profile/pages/NewEmailSelection/NewEmailSelection.web.test.tsx, src/features/profile/pages/NewEmailSelection/schema/newEmailSelectionSchema.native.test.ts, src/features/profile/pages/NewEmailSelection/schema/newEmailSelectionSchema.ts, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27163
I have:
| iOS              |       <img   width="800" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/0f14cf3e-1d70-4dc0-8977-e6a783328237"/>   |     <img width="230" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/ac30b627-2e90-4452-8d73-b159481259fc"/>  |
| Android          |        <img  width="800" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/0f14cf3e-1d70-4dc0-8977-e6a783328237"/>        |    <img width="250" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/1d7907ed-59ae-413e-90b7-e9e94310448a"/>    |
| Desktop - …
=> (PC-27163) feat(ChangeEmail): Add new email selection feature

src/features/venuemap/components/VenueMapView/VenueMapView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27604
I have:
| iOS              | <img width="317" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/1204450a-5b7a-4090-b83c-7206705fdb96">  |  <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/b882e05e-fd8e-425c-8f3b-da49bd38bd06"> |
| Android          |  <img width="317" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/1204450a-5b7a-4090-b83c-7206705fdb96">  | <img width="502" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/f1db6342-ca1f-4fb8-9e20-7631eb10b513"> …
=> (PC-27604) feat(map): select venue pin

ios/PassCulture.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock, package.json, yarn.lock
pr to fix bug after updating to xcode 15 and ios 17.4
fix flipper: https://github.com/facebook/react-native/issues/43335
updating rn to fix this bug: https://github.com/facebook/react-native/issues/37748
=> (BSR) fix(podfile): fix project after updating xcode 15 ios 17.4

src/features/venuemap/components/VenueMapView/VenueMapView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28373
I have:
=> (PC-28373) feat(search): pin deselection management

src/features/venuemap/components/VenueMapView/VenueMapView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28383
I have:
| iOS              |               |![Capture d’écran 2024-03-11 à 16 39 27](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/d947c70e-6061-4998-acdc-694702fb0176)|
| Android          |               |![Capture d’écran 2024-03-11 à 16 42 41](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/5cf127d1-c40d-4f64-aba4-8b815970f804)|
=> (PC-28383) feat(search): preserve the selected venue outside the current search area

src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-28478
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/70148476/9e29bd5e-e3f9-4ea6-8ce4-cda176fc0c7f
=> (PC-28478) fix(CategoriesModal): fix categories reset bug

.maestro/testsV2/SearchAndBookDigitalOffer.yml, .maestro/testsV2/reusableFlows/features/booking/BookDigitalOffer.yml, .maestro/testsV2/reusableFlows/features/search/SearchBookableDigitalOffer.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28441
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/153505101/06fa5141-5f89-4184-a7b6-25fc5ba22ad8
=> (PC-28441) feat(maestro): add new test to book digital offer

src/features/venuemap/components/VenueMapView/VenueMapView.tsx, src/features/venuemap/helpers/isGeolocValid.native.test.ts, src/features/venuemap/helpers/isGeolocValid.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28207
I have:
=> (PC-28207) feat(venueMap): do not display integer geoloc

scripts/dead_code_snapshot.txt, src/features/navigation/RootNavigator/types.ts, src/features/venuemap/components/VenueMapView/VenueMapView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28452
I have:
=> (PC-28452) feat(venueMap): send analytics when navigating to venue

.github/workflows/dev_on_workflow_environment_ios_deploy.yml
https://www.notion.so/passcultureapp/SDK-iOS-16-2-4dd531a7cc3740be9ff0d495e40bc39d#e13afd7491b6493eb93064a35211c07c
=> (BSR) feat(dev_on_workflow): update version macos

src/features/cookies/helpers/setMarketingParams.native.test.ts, src/libs/firebase/analytics/__tests__/useInit.native.test.ts, src/libs/firebase/analytics/useInit.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28218
I have:
=> (PC-28218) fix(firebase): Reset default parameters by nullifying them

__snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx.native-snap, __snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx.web-snap, src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx, src/features/search/helpers/useFilterCount/useFilterCount.native.test.ts, src/features/search/helpers/useFilterCount/useFilterCount.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28508
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/70148476/780511da-6e0d-498b-a4e0-b7067d6defbc
https://github.com/pass-culture/pass-culture-app-native/assets/70148476/f859ecdd-8b56-429b-86e8-e5767f220183
=> (PC-28508) feat(useFilterCount): delete localisation from filter count

__snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap, src/features/offer/components/OfferVenueBlock/OfferVenueBlock.native.test.tsx, src/features/offer/components/OfferVenueBlock/OfferVenueBlock.tsx, src/features/venuemap/components/VenueMapPreview/VenueMapPreview.native.test.tsx, src/features/venuemap/components/VenueMapPreview/VenueMapPreview.stories.tsx, src/features/venuemap/components/VenueMapPreview/VenueMapPreview.tsx, src/ui/components/VenuePreview/VenuePreview.native.test.tsx, src/ui/components/VenuePreview/VenuePreview.stories.tsx, src/ui/components/VenuePreview/VenuePreview.tsx, src/ui/components/headers/CloseButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27605
I have:
=> (PC-27605) feat(VenueMapPreview): add new venue map preview card

__snapshots__/features/notifications/pages/PushNotificationsModal.native.test.tsx.native-snap, src/features/notifications/pages/PushNotificationsModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28372
I have:
| iOS              |<img width="363" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ee6518e7-521e-4742-9d43-ac0cc11cb8a8">|<img width="293" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/feac7155-88a3-4f93-b655-1e6de860fdfe">|
| Android          |<img width="363" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ee6518e7-521e-4742-9d43-ac0cc11cb8a8">|<img width="401" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/9a24edbb-5986-4e8f-9 …
=> (PC-28372) feat(PushNotificationsModal): update illustration

__snapshots__/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx.web-snap, scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/accessibility/components/AccessibilityFiltersModal.tsx, src/features/accessibility/context/AccessibilityFiltersWrapper.tsx, src/features/accessibility/types.ts, src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx, src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx, src/features/navigation/RootNavigator/Header/Nav.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/__tests__/TabBar.native.test.tsx, src/features/navigation/TabBar/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/search/helpers/useFilterCount/useFilterCount.ts, src/features/search/helpers/useNavigateToSearch/useNavigateToSearch.ts, src/features/search/helpers/useSync/useSync.ts, src/features/search/pages/SearchFilter/SearchFilter.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27954
I have:
=> (PC-27954) feat(accessibility): add accessibilty filter params to search url 

scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/search/api/useSearchResults/useSearchResults.ts, src/libs/algolia/enums/facetsEnums.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildFacetFilters.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildOfferSearchParameters.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.test.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/tests/buildFacetFilters.test.ts, src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.test.ts, src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-27937
I have:
=> (PC-27937) feat(useSearchResults): add disabilities to algolia facet

src/features/offer/helpers/getOfferTags/getOfferTags.ts, src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchVenueItems/SearchVenueItem.native.test.tsx, src/features/search/components/SearchVenueItems/SearchVenueItem.stories.tsx, src/features/venue/types.ts, src/features/venuemap/components/VenueMapPreview/VenueMapPreview.native.test.tsx, src/features/venuemap/components/VenueMapPreview/VenueMapPreview.stories.tsx, src/features/venuemap/components/VenueMapPreview/VenueMapPreview.tsx, src/features/venuemap/components/VenueMapView/VenueMapView.tsx, src/features/venuemap/helpers/getVenueTags/getVenueTags.test.ts, src/features/venuemap/helpers/getVenueTags/getVenueTags.ts, src/libs/algolia/__mocks__/mockedAlgoliaResponse.ts, src/libs/algolia/fetchAlgolia/fetchVenues/adaptAlgoliaVenues.test.ts, src/libs/algolia/fetchAlgolia/fetchVenues/adaptAlgoliaVenues.ts, src/libs/algolia/fetchAlgolia/fetchVenues/fetchVenues.native.test.ts, src/libs/algolia/fetchAlgolia/fetchVenues/fixtures/AlgoliaVenuesFixture.ts, src/libs/algolia/types.ts, src/libs/venue/fixtures/mockedSuggestedVenues.ts, src/shared/string/isString.test.ts, src/shared/string/isString.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27606
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/e34c4459-5236-402b-91de-308c8a57f566
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/06f2b12d-d3b2-4063-9a62-f6922efd23e8
=> (PC-27606) feat(VenueMapView): display the venue map preview on selected venue

src/features/venuemap/components/VenueMapPreview/VenueMapPreview.tsx, src/features/venuemap/components/VenueMapView/VenueMapView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27607
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/07a5a8bd-c16d-45f6-a36c-ff0ec8e42bcf
=> (PC-27607) feat(VenueMapView): add log consult Venue on clicking to the preview

__snapshots__/features/trustedDevice/pages/AccountSecurity.native.test.tsx.native-snap, src/features/trustedDevice/pages/AccountSecurity.native.test.tsx, src/features/trustedDevice/pages/AccountSecurity.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26012
I have:
| Platform         | User connected with password | User disconnected or connected without password | 
| iOS              | <img width="304" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/1c2b1f91-e3d6-43c9-8e41-d8faa6d5d9c4"> | <img width="315" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/a166a544-a352-4764-8a80-2976c1a24dd0"> |
| Desktop - Chrome | <img width="1552" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/8095cf1e-049c-4b38-bc31-6fa86615bc61"> …
=> (PC-26012) feat(sso): AccountSecurity when no password

package.json
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
https://thevinaysingh.medium.com/ways-to-use-pre-commit-pre-push-hooks-in-react-react-native-22b851bc93
co-authored-by: @inesmouandjolobe 🔥
=> (BSR) feat(package): add pre-push rebase script

scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx, src/features/offer/components/MovieScreeningCalendar/useMovieScreeningCalendar.ts, src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28220
=> (PC-28220) feat(MovieScreeningCalendar): Fix date select reset when venue changes and when isDuo modal is open

src/libs/algolia/enums/facetsEnums.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.test.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.ts
gtlCodeLevel${gtlLevel}:${gtlCode}
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28575
linked to backend ticket : https://passculture.atlassian.net/browse/PC-28442
I have:
=> (PC-28575) feat(algolia): request new format 

.maestro/testsV2/SearchAndBookCinemaOffer.yml, .maestro/testsV2/SearchAndBookDigitalOffer.yml, .maestro/testsV2/SearchAndBookDuoOffer.yml, .maestro/testsV2/SearchAndBookPhysicalOffer.yml, .maestro/testsV2/SignupAndActivation.yml, .maestro/testsV2/reusableFlows/features/auth/ActivationPhoneNumberStep.yml, .maestro/testsV2/reusableFlows/features/auth/ActivationProfileStep.yml, .maestro/testsV2/reusableFlows/features/auth/GoToActivationFromProfile.yml, .maestro/testsV2/reusableFlows/features/auth/LoginFromProfileForBeneficiaryUser.yml, .maestro/testsV2/reusableFlows/features/auth/LoginFromProfileForUnregisteredUser.yml, .maestro/testsV2/reusableFlows/features/auth/SignupFromProfile.yml, .maestro/testsV2/reusableFlows/features/tutorial/onboarding/Onboard18.yml, scripts/run_e2e_tests.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27940
I have:
=> (PC-27940) feat(maestro): add Signup and Activation flow with phone number step

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28600
I have:
=> (PC-28600) feat(offer): add fakeDoorArtist feature flag

scripts/dead_code_snapshot.txt, src/features/offer/helpers/__mocks__/useTrackOfferSeenDuration.ts, src/features/venuemap/pages/VenueMap/VenueMap.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts, src/shared/useTrackSessionDuration.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28451
I have:
=> (PC-28451) feat(search): use SessionDurationFromVenueMap log on venue map

__snapshots__/features/trustedDevice/pages/AccountSecurity.native.test.tsx.native-snap, src/features/trustedDevice/pages/AccountSecurity.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-26012
I have:
| iOS              | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/418e5baf-b33d-46f9-9337-dc7f04fd4066) | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/6107ac99-326b-4242-9dfb-f9055970ac96) |
=> (PC-26012) fix(AccountSecurity): text for sso users

scripts/dead_code_snapshot.txt, src/features/home/components/SubscribeButton.stories.tsx, src/features/home/components/SubscribeButton.tsx, src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts, src/ui/svg/icons/BellFilled.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28527
I have:
| iOS              |    <img width="198" alt="Capture d’écran 2024-03-21 à 14 59 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/e7baeaac-7f99-4c3e-acb8-1add01a2a562">   <img width="168" alt="Capture d’écran 2024-03-21 à 14 59 41" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/a2b5b73e-a75f-49f0-9d83-d9ef8e55b1aa">     |  <img width="200" alt="Capture d’écran 2024-03-21 à 15 03 59" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/073033ed-bddc-4764-b410-3c760a4306f1">     |
| Android          |       <img width="198" …
=> (PC-28527) feat(ui): Design subscribe button

scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx, src/features/offer/components/MovieScreeningCalendar/useMovieScreeningCalendar.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28220
=> (PC-28220) fix(EventCard): branchement cartes seance

src/features/offer/components/OfferCTAButton/useOfferCTAButton.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28709
I have:
- [x ] Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
| Platform         | With FF on | With FF off |
| Desktop - Chrome |<img width="497" alt="Capture d’écran 2024-03-22 à 10 22 23" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/20cbfb0e-bfc7-4f1d-beec-95cbd27701b9">|<img width="497" alt="Capture d’écran 2024-03-22 à 10 22 03" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/3e73b13c-af73-4d62-b54c-9b4a1460bb35">|
=> (PC-28709) fix(offer): add cine feature flag to fix missing CTA on offer

__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.stories.tsx, src/features/search/helpers/categoriesHelpers/mappingFixture.ts, src/libs/subcategories/placeholderData.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28523
I have:
=> (PC-28523) feat(categories): rename 'bibliotheques, mediatheques' to 'abonnement...'

src/shared/culturalSurvey/shouldShowCulturalSurvey.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28157
I have:
=> (PC-28157) fix(CulturalSurvey): Simplify condition in helper

__snapshots__/ui/components/eventCard/EventCardList.native.test.tsx.native-snap, src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx, src/ui/components/eventCard/EventCard.tsx, src/ui/components/eventCard/EventCardList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28711
I have:
**[BEFORE]**
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/a192bc58-b244-432d-9811-74cbb267e861
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/538b972d-436d-4459-94fd-b47151730f6f
**[AFTER]**
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/9b31d1e0-570f-4799-8474-2bd0edc53a73
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/cf646fea-9694-4931-9aa7-8477ad2bcad1
=> (PC-28711) fix(EventCard): Fix onPress event and shadow

src/features/venuemap/components/VenueMapPreview/VenueMapPreview.tsx, src/features/venuemap/components/VenueMapView/VenueMapView.tsx, src/libs/maps/maps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27704
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/c87dcc20-44b7-4af8-b7f2-f7e9cc423f15
=> (PC-27704) feat(venue): center when pin is under the preview

__snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx.native-snap, src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
=> (BSR) fix(NotificationsSettings): remove only in test and fix everything

src/features/venuemap/components/VenueMapPreview/VenueMapPreview.tsx, src/theme/index.ts, src/ui/theme/colors.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28741
I have:
=> (PC-28741) fix(VenueMapPreview): fix missing shadow on venue map preview

src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27798
I have:
J'ai vérifié les cas suivants :
- Au click sur une eventCard cliquable, le tracker `logBookingProcessStart` s'envoie ✅ 
- Au click sur une eventCard disabled, le tracker `logBookingProcessStart` ne s'envoie pas ✅ 
- Au click sur le CTA `Changer de cinema`, puis en changeant de cinéma, le tracker `logConsultOffer` s'envoie ✅ 
- A l'abandon d'une réservation donc au clic sur une eventCard puis sur la croix de la modale de réservation, le tracker `logCancelBookingFunnel` s'envoie avec les bonnes données ✅ 
J'ai ajouté le tracker au clic sur une eventCard sur cette page notion : 
https://www.notion.so/passcultureapp/3bfe5fca46b54050b404f480b08b4098?v=08c247ca60244d6f9b107f85a7fdfd15
=> (PC-27798) feat(logAnalytics): Check log analytics when an eventcard is clicked and add more tests

__snapshots__/ui/components/eventCard/EventCardList.web.test.tsx.web-snap, src/ui/components/eventCard/EventCard.tsx, src/ui/components/eventCard/EventCardList.tsx, src/ui/components/eventCard/EventCardList.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-28589
I have:
=> (PC-28589) feat(EventList): implement web list

src/features/offer/components/OfferArtists/OfferArtists.native.test.tsx, src/features/offer/components/OfferArtists/OfferArtists.tsx, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28601
I have:
=> (PC-28601) feat(offer): add logConsultArtistFakeDoor when pressing artist button

src/features/navigation/RootNavigator/linking/getInitialUrl.ios.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-16812
I have:
=> (PC-16812) fix(navigation): remove useless timeout

src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts, src/libs/analytics/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28784
I have:
Vue avec Matthieu pour le wording ✅ 
Ce ticket fix aussi le wording sur l'event card quand la séance est complète
=> (PC-28784) fix(performSearch): Fix perform search error when selecting accessibility filter

.maestro/testsV2/SearchAndBookMusicalOffer.yml, .maestro/testsV2/reusableFlows/features/booking/BookMusicalOffer.yml, .maestro/testsV2/reusableFlows/features/search/SearchBookableMusicalOffer.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28626
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/153505101/ea219234-8f09-43f5-8cac-4aba0047dff7
=> (PC-28626) feat(maestro): add musical offer booking flow

__snapshots__/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx.native-snap, src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx, src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-28589
I have:
=> (PC-28589) feat(useSelectedDateScreening): sort screening

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28813
I have:
=> (PC-28813) feat(featureflag): add FF

.maestro/testsV2/reusableFlows/GoToProfileFromTabBar.yml, .maestro/testsV2/reusableFlows/features/auth/ActivationPhoneNumberStep.yml, .maestro/testsV2/reusableFlows/features/auth/ActivationProfileStep.yml, .maestro/testsV2/reusableFlows/features/auth/GoToActivationFromProfile.yml, .maestro/testsV2/reusableFlows/features/auth/LoginFromProfileForUnregisteredUser.yml, .maestro/testsV2/reusableFlows/features/auth/SignupFromProfile.yml, .maestro/testsV2/reusableFlows/features/booking/BookCinemaOffer.yml, .maestro/testsV2/reusableFlows/features/booking/BookDuoOffer.yml, .maestro/testsV2/reusableFlows/features/booking/BookPhysicalOffer.yml, .maestro/testsV2/reusableFlows/features/search/SearchBookableCinemaOffer.yml, .maestro/testsV2/reusableFlows/features/search/SearchBookableDuoOffer.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28682
I have:
=> (PC-28682) feat(maestro): update signup flow and fix e2e

src/shared/offer/components/ErrorApplicationModal/ErrorApplicationModal.native.test.tsx
=> (BSR) fix(tests): fix error application modal flaky test

src/libs/algolia/enums/facetsEnums.ts, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28850
I have:
| Desktop - Chrome |<img width="1512" alt="Capture d’écran 2024-03-27 à 16 34 14" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/ce124e03-0bcc-4bcb-bc0d-bdcba3b4820c">|<img width="1512" alt="Capture d’écran 2024-03-27 à 16 34 35" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/13c4c041-4e4c-4384-8efb-6d021471aa70">|
=> (PC-28850) fix(search): fix algolia gtl facet for query

src/features/search/components/SearchListHeader/SearchListHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28780
I have:
| iOS              |![Capture d’écran 2024-03-27 à 17 42 44](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/83458d0a-92e4-4184-9223-973f4ce86144)|![Capture d’écran 2024-03-27 à 17 42 29](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/80525625-2003-4b93-ba0b-68fde3907741)|
=> (PC-28780) feat(search): reduce spacing between title and see map button

scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/home/helpers/selectHomepageEntry.native.test.ts, src/features/identityCheck/pages/identification/IdentificationFork.native.test.tsx, src/features/identityCheck/pages/identification/IdentificationFork.tsx, src/features/offer/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx, src/libs/firebase/remoteConfig/remoteConfig.constants.ts, src/libs/firebase/remoteConfig/remoteConfig.services.ts, src/libs/firebase/remoteConfig/remoteConfig.services.web.ts, src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28472
I have:
=> (PC-28472) feat(Identification): add ubble reassurance ab test

src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx, src/features/venueMap/components/VenueMapView/VenueMapView.tsx, src/features/venueMap/components/VenueMapView/constant.ts, src/features/venueMap/hook/useCenterOnLocation.native.test.ts, src/features/venueMap/hook/useCenterOnLocation.ts, src/features/venueMap/pages/VenueMap/VenueMap.tsx, src/libs/maps/maps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28815
I have:
| iOS              |               |<img width="435" alt="Capture d’écran 2024-03-27 à 17 58 38" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/bfc69b85-487c-41ed-b44e-ec5257ff852f">|
=> (PC-28815) feat(VenueMap): add Filter banner for venue map

src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/venueMap/components/VenueMapView/VenueMapView.tsx, src/features/venueMap/hook/useGetVenuesInRegion.native.test.ts, src/features/venueMap/hook/useGetVenuesInRegion.ts, src/features/venueMap/useGetAllVenues.native.test.ts, src/features/venueMap/useGetAllVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28602
I have:
=> (PC-28602) feat(search): display venues playlist content on venue map

src/features/offer/components/OfferArtists/OfferArtists.native.test.tsx, src/features/offer/components/OfferArtists/OfferArtists.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28610
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/5c977593-36af-4db0-a60d-28efb9312275
=> (PC-28610) feat(OfferArtists): add qualtrics quizz url

src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx, src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28854
I have:
**Parcours non connecté** 
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/4efa7580-340b-490e-a17f-c4f96fa22cfe
**Parcours crédit non débloqué**
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/8a4a2bae-d7d5-412d-ae65-86400a913f72
**Parcours en attente de validation**
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/c5e4698a-1c6b-48bd-85d4-930157b5e0fe
=> (PC-28854) feat(eventCard): Allow click on event card when user has not finished subscription

__snapshots__/features/identityCheck/pages/Stepper.native.test.tsx.native-snap, __snapshots__/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx.native-snap, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.tsx, src/ui/components/StepButton/StepButton.tsx, src/ui/components/StepList/StepList.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28574
I have:
| iOS              | ![Capture d’écran 2024-03-28 à 14 34 03](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/2045c5f1-c1ce-451c-9ed9-18db7bbdb92d) |  ![Capture d’écran 2024-03-28 à 14 51 33](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/8162c2f1-c5a2-4773-9ef7-5247eb0b2dfc)  |
=> (PC-28574) feat(profile): Fix minHeight for StepButton in TrackEmailChange

src/features/home/components/modules/ThematicHighlightModule.native.test.tsx, src/features/home/components/modules/ThematicHighlightModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28858
=> (PC-28858) fix(home): fix thematic highlight module tracking

__snapshots__/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx.native-snap, scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/offer/components/MovieScreeningCalendar/enum.ts, src/features/offer/components/MovieScreeningCalendar/enums.ts, src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts, src/features/offer/components/OfferCTAButton/OfferCTAButton.tsx, src/features/offer/components/OfferCTAButton/useOfferCTAButton.ts, src/features/offer/components/StickyBookingButton/StickyBookingButton.native.test.tsx, src/features/offer/components/StickyBookingButton/StickyBookingButton.tsx, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28581
I have:
Platform         | Mockup/Before | After |
| Parcours déjà réservé |![Capture d’écran 2024-03-27 à 10 36 15](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/995b992b-517e-4782-8dc9-717b096b0c48) |![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-27 at 10 45 15](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/971e0b34-60f0-4431-af2c-189a19e4cb98)|
| Parcours crédit insuffisant  |![Capture d’écran 2024-03-27 à 10 35 44](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/625c7ae4-1add-44a7-8b08-dca60463643b)|![credit-insuffisant](https://github.com/pass-culture/pass-culture-app-native …
=> (PC-28581) feat(MovieOffers): add bottom banner

src/features/venueMap/pages/VenueMap/VenueMap.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28806
I have:
| iOS              |               |![Capture d’écran 2024-03-28 à 15 31 58](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/b975bc6b-b789-40f6-9bb0-a1d293d087b7)|
=> (PC-28806) feat(VenueMap): add venue type filter button

scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/home/helpers/selectHomepageEntry.native.test.ts, src/features/offer/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx, src/features/subscription/helpers/useMapSubscriptionHomeIdsToTheme.native.test.ts, src/features/subscription/helpers/useSubscriptionHomeIds.ts, src/libs/firebase/remoteConfig/remoteConfig.constants.ts, src/libs/firebase/remoteConfig/remoteConfig.services.ts, src/libs/firebase/remoteConfig/remoteConfig.services.web.ts, src/libs/firebase/remoteConfig/remoteConfig.types.ts, src/libs/firebase/shims/remote-config/index.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28618
I have:
=> (PC-28618) feat(Subscription): create firebase mapping for homeId

src/ui/components/VenuePreview/VenuePreview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28918
I have:
=> (PC-28918) fix(VenuePreview): venue name and address were not crop

src/features/offer/components/OfferVenueButton/OfferVenueButton.native.test.tsx, src/features/offer/components/OfferVenueButton/OfferVenueButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28909
I have:
=> (PC-28909) fix(offer): track navigation to venue

scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx, src/features/offer/components/MovieScreeningCalendar/types.ts, src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts, src/features/offer/components/OfferCTAButton/useOfferCTAButton.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28906
I have:
=> (PC-28906) fix(movieScreening): Small refacto to avoid duplicating booking logic

src/features/venueMap/components/VenueMapView/VenueMapView.tsx
Co-authored-by: Hugo Voisin <hugov@bam.tech>
Co-authored-by: YassinL <YassinL@users.noreply.github.com>
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28487
I have:
=> (PC-28487) feat(venueMap): add max zIndex for selected venue

src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx, src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28944
I have:
=> (PC-28944) feat(NotificationsSettings): fix some subscription bugs

__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap, src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx, src/features/search/helpers/useAppliedFilters/useAppliedFilters.ts, src/features/search/helpers/useFilterCount/useFilterCount.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28370 
I have:
[Enregistrement de l’écran 2024-04-02 à 15.45.46.zip](https://github.com/pass-culture/pass-culture-app-native/files/14839476/Enregistrement.de.l.ecran.2024-04-02.a.15.45.46.zip)
Uploading Enregistrement de l’écran 2024-04-02 à 15.45.46.mov…
=> (PC-28370) fix(SearchFilters): add params necessary to select filter pills and count them

__snapshots__/features/navigation/TabBar/__tests__/TabBar.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/navigation/TabBar/__tests__/TabBar.native.test.tsx, src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28689
https://passculture.atlassian.net/browse/PC-28688
https://passculture.atlassian.net/browse/PC-28687
https://passculture.atlassian.net/browse/PC-28686
I have:
=> (PC-28689) fix(tests): unskip venue tests + (PC-28688) + (PC-28687) + (PC-28686)

src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx, src/features/offer/helpers/getVenueSectionTitle/getVenueSectionTitle.test.ts, src/features/offer/helpers/getVenueSectionTitle/getVenueSectionTitle.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28992
I have:
=> (PC-28992) feat(CinemaOffers): change label above venue card

.github/workflows/dev_on_pull_request_reassure.yml, .github/workflows/dev_on_pull_request_title_checker.yml, .github/workflows/dev_on_push_workflow_main.yml, .github/workflows/dev_on_schedule_lighthouse.yml, .github/workflows/dev_on_workflow_check_folder_change.yml, .github/workflows/dev_on_workflow_check_proxy_version.yml, .github/workflows/dev_on_workflow_chromatic.yml, .github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml, .github/workflows/dev_on_workflow_install.yml, .github/workflows/dev_on_workflow_linter_ts.yml, .github/workflows/dev_on_workflow_tester.yml, .github/workflows/dev_on_workflow_ts_noUncheckedIndexedAccess.yml, .github/workflows/dev_on_workflow_ts_prune.yml, .github/workflows/dev_on_workflow_update_jira_issues.yml, .github/workflows/dev_on_workflow_web_deploy.yml, .github/workflows/dev_on_workflow_web_proxy_deploy.yml, .github/workflows/jira_create_and_push_staging_testing_deploy_tags.yml
=> (BSR) ci(name): Order workflows name

.github/workflows/dev_on_dispatch_service_worker_test.yml
=> (BSR) ci(name): service worker

src/features/home/components/modules/HomeModule.tsx, src/features/home/components/modules/VenueMapModule.native.test.tsx, src/features/home/components/modules/VenueMapModule.tsx, src/features/home/components/modules/VenueMapModule.web.test.tsx, src/features/home/types.ts, src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx, src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx, src/features/search/components/SearchListHeader/SearchListHeader.tsx, src/features/venueMap/components/VenueMapBlock/VenueMapBlock.tsx, src/features/venueMap/hook/useShouldDisplayVenueMap.native.test.ts, src/features/venueMap/hook/useShouldDisplayVenueMap.ts, src/features/venueMap/hook/useShouldDisplayVenueMap.web.test.ts, src/libs/contentful/adapters/adaptHomepageModules.ts, src/libs/contentful/adapters/modules/adaptVenueMapModule.native.test.ts, src/libs/contentful/adapters/modules/adaptVenueMapModule.ts, src/libs/contentful/fixtures/venueMapBlockContentModel.fixture.ts, src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28940
I have:
| iOS              |               |  <img width="534" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/ce554169-815e-43e4-94b9-7dcdc8782576"> |
| Desktop - Chrome |               | <img width="1512" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26742386/b2435db8-47d2-498f-9950-635a8a38b0ff"> |
=> (PC-28940) feat(home): add venue map block on home

.github/workflows/ dev_on_dispatch_create_and_push_ehp_deploy_tags.yml, .github/workflows/dev_on_workflow_environment_android_deploy.yml, .github/workflows/dev_on_workflow_environment_ios_deploy.yml, .github/workflows/dev_on_workflow_environment_soft_deploy.yml, .github/workflows/dev_on_workflow_install.yml
=> (BSR) ci(name): reorganize workflows

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28953
=> (PC-28953) feat(ff): add wipOfferPreviewWithCarousel

.maestro/testsV2/AccessSignupFromBlock.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28823
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/153505101/136f3e48-69c1-4ba9-904e-5c2cb9322c50
=> (PC-28823) feat(maestro): add test for signup from block

package.json, src/features/offer/components/PinchableBox/PinchableBox.tsx, src/features/offer/pages/OfferPreview/OfferPreview.native.test.tsx, src/features/offer/pages/OfferPreview/OfferPreview.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25857
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/bc6291b1-dfdc-4a71-9fc8-a9ed8b766631
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/d22f899c-1482-40d6-845d-26cdf823d377
=> (PC-25857) feat(offerPreview): add carousel

.maestro/testsV2/SignupAndLoginAvailable.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28824
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/153505101/4f1b1e16-7720-461e-b3d3-a968365e9590
=> (PC-28824) feat(maestro): add test for login and signup

scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/bookOffer/pages/BookingOfferModal.native.test.tsx, src/features/bookOffer/pages/BookingOfferModal.tsx, src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts, src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts, src/libs/analytics/__mocks__/logEventAnalytics.ts, src/libs/analytics/logEventAnalytics.ts, src/libs/firebase/analytics/events.ts, tsconfig.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28922
I have:
=> (PC-28922) fix(Offer): remove click book offer

src/features/venueMap/helpers/getVenueTypeLabel/getVenueTypeLabel.native.test.ts, src/features/venueMap/helpers/getVenueTypeLabel/getVenueTypeLabel.ts, src/features/venueMap/helpers/isVenueTypeLabelValid/isVenueTypeLabelValid.test.ts, src/features/venueMap/helpers/isVenueTypeLabelValid/isVenueTypeLabelValid.ts, src/features/venueMap/pages/VenueMap/VenueMap.tsx, src/features/venueMap/pages/modals/VenueTypeModal.tsx, src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/getVenueTypeFacetFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28812
I have:
| iOS              |               |![Capture d’écran 2024-04-08 à 18 35 51](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/6658393a-f99c-47ec-875c-44606c91bd25)![Capture d’écran 2024-04-08 à 18 36 01](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/e203f8ed-1866-45b8-b620-411017fefb61)![Capture d’écran 2024-04-08 à 18 36 12](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/7793b155-ed67-4e2d-92d0-b7de4c58cdf5)|
| Desktop - …
=> (PC-28812) feat(VenueMap): adapt venue type label

__snapshots__/features/venueMap/pages/modals/VenueTypeModal.native.test.tsx.native-snap, src/features/venueMap/components/VenueMapView/VenueMapView.tsx, src/features/venueMap/components/VenueTypeSection/VenueTypeSection.tsx, src/features/venueMap/context/reducer.test.ts, src/features/venueMap/context/reducer.ts, src/features/venueMap/helpers/getGeolocatedVenues/getGeolocatedVenues.test.ts, src/features/venueMap/helpers/getGeolocatedVenues/getGeolocatedVenues.ts, src/features/venueMap/helpers/getVenuesNumberByType/getVenuesNumberByType.test.ts, src/features/venueMap/helpers/getVenuesNumberByType/getVenuesNumberByType.ts, src/features/venueMap/hook/useGetVenuesInRegion.ts, src/features/venueMap/pages/VenueMap/VenueMap.tsx, src/features/venueMap/pages/modals/VenueTypeModal.native.test.tsx, src/features/venueMap/pages/modals/VenueTypeModal.tsx, src/features/venueMap/types.ts, src/features/venueMap/useGetAllVenues.native.test.ts, src/features/venueMap/useGetAllVenues.ts, src/fixtures/geolocatedVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28814
I have:
| iOS              |<img width="201" alt="Capture d’écran 2024-04-10 à 10 20 56" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/58f00b4b-7cbc-4ad5-9b99-687e811c9174">|<img width="395" alt="Capture d’écran 2024-04-10 à 10 18 30" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/f214d492-8fe8-441f-adf1-90927bb14af6">|
| Android          |               |<img width="412" alt="Capture d’écran 2024-04-10 à 10 24 18" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/79f600a7-d850-4360-9c21-604b8537345a">|
| …
=> (PC-28814) feat(venueMap): display venues number by type

src/features/offer/pages/OfferPreview/OfferPreview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29107
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/9e4826b3-2c16-422b-b603-b78cd5c31cb5 
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/4b6bdd5e-194d-4b5e-9267-260eda67e0c4
=> (PC-29107) feat(offerPreview): remove parallax from carousel

__snapshots__/features/favorites/pages/FavoritesSorts.native.test.tsx.native-snap, __snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap, __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap, __snapshots__/features/venueMap/pages/modals/VenueTypeModal.native.test.tsx.native-snap, scripts/noUncheckedIndexedAccess_snapshot.txt, src/features/favorites/pages/FavoritesSorts.tsx, src/features/internal/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/search/components/BookCategoriesSection/BookCategoriesSection.tsx, src/features/search/components/CategoriesSection/CategoriesSection.tsx, src/features/search/components/CategoriesSectionItem/CategoriesSectionItem.tsx, src/features/search/components/HoursSlider/HoursSlider.tsx, src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.tsx, src/features/venueMap/components/VenueTypeSection/VenueTypeSection.tsx, src/features/venueMap/pages/modals/VenueTypeModal.tsx, src/ui/components/radioButtons/RadioButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29025
I have:
=> (PC-29025) feat(ui): increase click box for all radio button

__snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx.native-snap, __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.web.test.tsx.web-snap, src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx, src/features/subscription/helpers/useThematicSubscription.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28569
I have:
| iOS              |<img width="313" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/0bb2654b-0b6f-46e8-95b0-f9561571e3f8">|<img width="316" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/a566b5cb-f1b5-4961-8ee4-255d375b46a2">|
=> (PC-28569) fix(subscription): fix somes subscription mistakes

src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29048
I have:
=> (PC-29048) fix(search): take into account that the category may not be in the tree

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28922
I have:
=> (PC-28922) feat(Venue): add wipEnableNewXpCineFromVenue feature flag

src/features/venue/components/PracticalInformation/PracticalInformation.native.test.tsx, src/features/venue/components/PracticalInformation/PracticalInformation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29100
I have:
| Platform         |Before | After |
| Desktop - Chrome |    <img width="1440" alt="Capture d’écran 2024-04-11 à 16 48 24" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/dfdc414e-0a87-4736-8a35-d90e67d6c32e">         |   <img width="1440" alt="Capture d’écran 2024-04-11 à 16 48 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/1996fd56-6a55-49ae-97c0-3a01099654ae">    |
=> (PC-29100) fix(venue): Hide contact block when unused info is provided

package.json, yarn.lock
by running `npx browserslist@latest --update-db`
=> (BSR) chore(deps): update caniuse

CODEOWNERS
=> (BSR) chore(github): update CODEOWNERS with new features

src/features/offer/pages/OfferPreview/OfferPreview.tsx, src/ui/CarouselDot/CarouselDot.native.test.tsx, src/ui/CarouselDot/CarouselDot.tsx, src/ui/components/headers/BlurFooter.tsx, src/ui/hooks/useGetFooterHeight/useGetFooterHeight.test.ts, src/ui/hooks/useGetFooterHeight/useGetFooterHeight.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25870
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/1d93b458-d9e8-4886-a143-131c50e7456b
=> (PC-25870) feat(OfferPreview): use and implement carousel dot

src/ui/components/Playlist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29235
I have:
| Phone - ARC   |<img width="442" alt="Capture d’écran 2024-04-15 à 11 30 06" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/9e10d84d-6f37-4aa2-a2a3-36541f2d04b6">| https://github.com/pass-culture/pass-culture-app-native/assets/144016890/f4b87f57-83bd-49ae-bc3a-c5fcb28ebf68 |
=> (PC-29235) fix(playlist): web mobile view missing arrow 

src/features/offer/components/OfferPlace/OfferPlace.tsx, src/features/offer/components/OfferVenueBlock/OfferVenueBlock.tsx, src/features/offer/components/OfferVenueBlock/OfferVenueBlockDeprecated.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29221
I have:
| Platform         | Mockup/Before                                                                                                                                                                                                                              | After                                                                                                                                                                                                              |
| :--------------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ …
=> (PC-29221) fix(Offer): fix calendar margin

CODEOWNERS
=> (BSR) chore(github): update CODEOWNERS

src/features/venueMap/components/VenueMapView/VenueMapView.tsx, src/features/venueMap/helpers/zoomOutIfMapEmpty.ts, src/features/venueMap/hook/useGetVenuesInRegion.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28985
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/be7a806d-2292-4966-9c0b-3195b0b8acca
https://github.com/pass-culture/pass-culture-app-native/assets/26742386/f2e9f3d2-8016-4da7-84dd-22f043497e2b
=> (PC-28985) feat(maps): zoom out when map is empty

src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/search/context/SearchWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28370
I have:
| Desktop - Chrome |  https://github.com/pass-culture/pass-culture-app-native/assets/158567429/b9149fd6-0808-4295-867e-5d40839c8ef5 |  https://github.com/pass-culture/pass-culture-app-native/assets/158567429/3684c192-bf06-40bb-bd89-3288ec05a993 |
| Desktop - Chrome | https://github.com/pass-culture/pass-culture-app-native/assets/158567429/88b308c7-f5e6-4d3d-91b6-cf89499d1cbb | https://github.com/pass-culture/pass-culture-app-native/assets/158567429/85ffd318-ad78-40b3-b29c-d0319cc390e6 |
=> (PC-28370) fix(deeplinks): Fix pills activated by deeplinks

__snapshots__/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.native.test.tsx.native-snap, src/api/gen/api.ts, src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx, src/features/internal/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/profile/helpers/useChangeEmailSetPasswordMutation.ts, src/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.native.test.tsx, src/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.tsx, src/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.web.test.tsx, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmailContent.native.test.tsx, src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmailContent.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.native.test.tsx, src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.web.test.tsx, src/shared/forms/schemas/newPasswordSchema.test.ts, src/shared/forms/schemas/newPasswordSchema.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28721
I have:
| iOS              |   ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/ac9f3e6c-b667-447b-99b6-02721f193028)            |      ![iphone-screen](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/f7a53ec6-c19a-4b25-b546-23bfbe9cf319) |
| Android          |        ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/4e1cd7db-1736-47b2-88b4-0d9b594693b4)       |   <img width="286" alt="Capture d’écran 2024-04-15 à 09 48 01" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/0a63a069-898a-47b1-ada5-c071e7a06adf">    |
| …
=> (PC-28721) feat(ChangeEmail): Add page to set password

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/81?label=frontend&selectedIssue=PC-29274
I have:
=> (PC-29274) feat(featureFlag): add ff enableMusicLiveBookingSurvey

__snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap, src/features/bookOffer/components/BookingEventChoices.native.test.tsx, src/features/home/components/modules/RecommendationModule.native.test.tsx, src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx, src/features/profile/pages/PersonalData/PersonalData.native.test.tsx, src/features/profile/pages/Profile.native.test.tsx, src/shared/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29022
I have:
=> (PC-29022) fix(tests): add missing msw request

__snapshots__/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.native.test.tsx.native-snap, src/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28721
I have:
| Platform         |Before | After |
| iOS              |               |    https://github.com/pass-culture/pass-culture-app-native/assets/46637324/bfc95a8a-79c3-4a2a-b017-ce58cd58c074   |
=> (PC-28721) feat(ChangeEmailSetPassword): Handle keyboard insets

__snapshots__/features/offer/components/MovieCalendar/MovieCalendar.native.test.tsx.native-snap, __snapshots__/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx.native-snap, __snapshots__/ui/components/eventCard/EventCardList.native.test.tsx.native-snap, __snapshots__/ui/components/eventCard/EventCardList.web.test.tsx.web-snap, src/features/offer/components/MovieCalendar/components/MovieCalendarDay.tsx, src/ui/components/eventCard/EventCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29132
I have:
=> feat(Offer): add test ids for e2e tests

__snapshots__/features/subscription/components/modals/OnboardingSubscriptionModal.native.test.tsx.native-snap, src/features/internal/cheatcodes/pages/NavigationSubscription/NavigationSubscription.tsx, src/features/subscription/components/modals/OnboardingSubscriptionModal.native.test.tsx, src/features/subscription/components/modals/OnboardingSubscriptionModal.tsx, src/features/subscription/components/modals/OnboardingSubscriptionModal.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29039
I have:
| iOS              | <img width="373" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/4111f5d1-3eca-4cb2-acd4-e13b1ff5ddf5"> | <img width="304" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/6283a38f-ade8-4262-818e-1b135da4eb6d"> |
| Desktop - Chrome |               |<img width="1022" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/6a2c19d0-cb68-4f58-b6c2-2565d0a25b15">|
[1]: …
=> (PC-29039) feat(OnboardingSubscriptionModal): Added modal to cheatcodes

src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistLocationParameters.native.test.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistLocationParameters.ts, src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/useAdaptOffersPlaylistParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29351
I have:
| Desktop - Chrome - Marseille |<img width="1512" alt="Capture d’écran 2024-04-18 à 15 19 43" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/de345631-ea1f-4af4-abe9-37639bd141c1">|<img width="1512" alt="Capture d’écran 2024-04-18 à 15 17 17" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/21c341de-33e1-4389-8744-88f3450fb1f5">|
| Desktop - Chrome - Paris |<img width="1512" alt="Capture d’écran 2024-04-18 à 15 22 28" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/2183c838-07ff-441d-96c1-ecee4248a463">|<img width="1512" …
=> (PC-29351) fix(localizedPlaylist): set location mode after playlist params instead of user

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts, src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29119
=> (PC-29119) feat(Search): add FF wipPageSearchN1

__snapshots__/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx.native-snap, __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap, src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx, src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx, src/features/venue/components/VenueBody/VenueBody.tsx, src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx, src/features/venue/components/VenueOffers/VenueOffers.tsx, src/features/venue/components/VenueOffers/VenueOffersList.tsx, src/features/venue/fixtures/venueOffersResponseSnap.ts, src/features/venue/pages/Venue/Venue.perf.test.tsx, src/features/venue/pages/Venue/Venue.web.test.tsx, src/shared/date/getDates.native.test.ts, src/shared/date/getDates.ts
Link to JIRA ticket: https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-28895
I have:
| iOS              |  <img width="177" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/afd2eccc-9c61-4692-8a91-4b2624b5bb5f">  |  <img width="420" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/fabfa879-e6b6-4b81-a78f-7158c2a9aeb8"> |
| Phone - Chrome   |               |  <img width="1440" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/70148476/8a99ba79-db44-41b8-b697-a40dc77f961e"> |
| Desktop - Chrome | <img width="511" alt="image" …
=> (PC-28895) feat(MoviesScreeningCalendar): create calendar component for cinema venue
