pass-culture/pass-culture-app-native

- src/features/birthdayNotifications/pages/RecreditBirthdayNotification.native.test.tsx
- src/features/birthdayNotifications/pages/RecreditBirthdayNotification.web.test.tsx
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22233
I have:
> (PC-22233) test(reactQuery): remove react query from birthday notifications

- __snapshots__/features/offerv2/components/MovieCalendar/MovieCalendar.native.test.tsx.native-snap
- src/features/offerv2/components/MovieCalendar/MovieCalendar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27872
| :-----------: | :---: |
| https://github.com/pass-culture/pass-culture-app-native/assets/144016890/87c6d126-39d1-4262-b320-8136774c17a5 |https://github.com/pass-culture/pass-culture-app-native/assets/144016890/14eafef1-eb43-4436-9939-dec1e0d442d1
> (PC-27872) fix(CinemaCalendar): add padding instead of margin

- src/features/gtlPlaylist/components/GtlPlaylist.native.test.tsx
- src/features/search/components/SearchHistory/SearchHistory.native.test.tsx
- src/features/search/pages/SearchLanding/SearchLanding.native.test.tsx
- src/features/search/pages/SearchResults/SearchResults.native.test.tsx
- src/ui/components/tiles/HorizontalOfferTile.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28041
I have:
> (PC-28041) test(ReactQuery): Remove last react query mocks in native

- src/ui/components/eventCard/EventCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27840
[Maquette ](https://www.figma.com/file/5QmI5xtsSGThRQrwhQ1yGP/%5BCin%C3%A9ma%5D-Parcours-de-r%C3%A9servation?node-id=3514%3A20263&mode=dev)
[Story](https://61fd537ecf081f003a135235-asickdjwqf.chromatic.com/?path=/story/ui-eventcard--event-card-default)
| Platform         | Design | Code |
| Default             | ![Capture d’écran 2024-02-13 à 11 54 33](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/4afa4775-d940-428b-a289-1b099743955c)| <img width="418" alt="Capture d’écran 2024-02-19 à 11 56 28" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/2a2686d3-afee-4053-b586-a3445d080b21">|
| Disabled          |![Capture …
> (PC-27840) feat(OfferCinemaSeance): fix UI

- src/api/apiHelpers.native.test.ts
- src/api/apiHelpers.ts
- src/features/auth/context/AuthContext.native.test.tsx
- src/features/auth/context/AuthContext.tsx
- src/features/auth/pages/login/Login.native.test.tsx
- src/features/auth/pages/login/Login.tsx
- src/features/auth/pages/login/Login.web.test.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
JIRA ticket: https://passculture.atlassian.net/browse/PC-24068
I have:
> (PC-24068) fix(auth): Redirect to login with info banner when refresh token expires

- src/features/search/components/VenueMapPin/VenueMapPin.native.test.tsx
- src/features/search/components/VenueMapPin/VenueMapPin.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27596
I have:
> (PC-27596) fix(search): not display counter when count = 1

- src/ui/components/buttons/externalLink/ExternalLink.tsx
- src/ui/components/buttons/externalLink/ExternalLink.web.tsx
- src/ui/svg/icons/ExternalSiteFilled.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25137
| Android          |![Screenshot_1707316012](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/182d0bfc-88c5-4bd2-8252-efd97172788b)|![Screenshot_1707315932](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/43e01d26-549c-486c-8003-a886e79fb5ee)|
| Desktop - Chrome |<img width="480" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/7675def3-0703-4c54-a96b-a9a979025449">|<img width="474" alt="image" …
> (PC-25137) fix(offer): align external link icon with text in offer description

- src/features/offerv2/components/OfferAbout/OfferAbout.tsx
when we don't have offer about section add a spacer of 8px + gap of 24px = 32px
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28117
I have:
| Phone - Chrome   |               |<img width="395" alt="Capture d’écran 2024-02-23 à 12 53 31" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/1c0e8c31-a6d5-48d9-8613-814a9b80af6d">|
> (PC-28117) fix(OfferContent): fix spacing

- .eslintrc.js
- doc/development/how-to/eslint-custom-rule.md
- src/features/venuemap/components/VenueMapCluster/VenueMapCluster.tsx
- src/libs/resizing-image-on-demand/Image.tsx
- src/ui/components/__tests__/AnimatedIcon.native.test.tsx
- src/ui/components/buttons/RoundedButton.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28303
si il y a plusieurs objets avec le name 'react-native', le dernier est le seul à être appliqué par react-native. Ils sont dons maintenant regroupé dans un seul objet qui malheureusement a donc un seul message avec les différentes consignes.
> (PC-28303) fix(eslint): restricted react native imports

- src/features/search/api/useSearchResults/useSearchResults.native.test.ts
- src/features/search/api/useSearchResults/useSearchResults.ts
Link to JIRA ticket:  https://passculture.atlassian.net/jira/software/c/projects/PC/boards/72?selectedIssue=PC-28287
I have:
> (PC-28287) feat(useSearchResults): fix algolia nbHits when nbHits=0 even when there is hits

- src/features/venue/pages/Venue/Venue.web.test.tsx
> feat(venue): skip flaky accessibility test for venue

- babel.config.js
- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28405
So that can have : 
```js
const EARTH_RADIUS = 6_378_137
```
instead of 
```js
const EARTH_RADIUS = 6378137
```
and improve readability
> (PC-28405) chore(babel): add numeric separator plugin

- src/features/offerv2/components/MovieCalendar/MovieCalendar.tsx
- src/features/offerv2/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx
- src/features/offerv2/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx
- src/features/offerv2/components/OfferContent/OfferContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28222
I have:
[AVANT - IOS]
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/f00b1259-a19b-4d3e-bbdf-ef30c10697e1
[APRES - IOS]
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/33aa9319-99e7-4f2a-a04b-560f59311a51
Pour tester :
- Rechercher le film "Dune" (le deuxième)
- Changer de lieu de projection (les cinémas **cinéma Boost** et **Madiana congres** ont beaucoup de dates de séances).
- Choisir la date la plus à droite puis changer de cinéma et constater que la première date du calendrier est selected + que le scroll est au début du calendrier.
> (PC-28222) fix(scroll): fix focus when movie location changes

- src/features/profile/pages/NotificationSettings/NotificationSettings.native.test.tsx
- src/features/profile/pages/NotificationSettings/NotificationSettings.tsx
- src/features/profile/pages/NotificationSettings/NotificationSettings.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28334
I have:
| Android          |![Screenshot_1709905863](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/20b651a9-5eb9-4c72-b1f0-5fe9dba10f5f) | ![Screenshot_1709905850](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/1e2fa015-783c-4b10-b81b-aa533dadcb53) |
> (PC-28334) feat(NotificationSettings): Make notification switch available on ios & android

- src/libs/algolia/enums/facetsEnums.ts
Unused since c07423326c551c7031f17c9cdf3 (and the corresponding
`stocksDateCreated` attribute will soon be removed from Algolia).
> (BSR) chore(algolia): Remove unused OFFER_STOCKS_DATE_CREATED

- src/features/profile/pages/PersonalData/PersonalData.native.test.tsx
- src/features/profile/pages/PersonalData/PersonalData.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28461
I have:
| iOS              |               |    ![Simulator Screenshot - iPhone 5 - 2024-03-12 at 08 20 44](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/314ed1dd-2a72-4c67-8fe7-30a4eb1874d3)   |
| Desktop - Chrome |               |   <img width="1440" alt="Capture d’écran 2024-03-12 à 08 22 35" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/01b8f019-47e3-434c-b39f-282ddb2119d7">    |
> (PC-28461) feat(PersonalData): Hide email edit button  when user has no password

- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
- src/features/internal/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/subscriptionRoutes.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/profile/components/SectionWithSwitch/SectionWithSwitch.tsx
- src/features/profile/pages/NotificationSettings/NotificationSettingsDeprecated.tsx
- src/features/profile/pages/NotificationSettings/NotificationSettingsDeprecated.web.test.tsx
- src/features/profile/pages/NotificationSettings/NotificationSettingsDeprectated.native.test.tsx
- src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
- src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
- src/features/profile/pages/NotificationSettings/NotificationsSettings.web.test.tsx
- src/features/profile/pages/NotificationSettings/usePushPermission.ts
- src/features/subscription/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28336
I have:
| iOS              |![image](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/539e82ff-3399-4202-b048-d20f73f82b9e)|![image](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/969382d4-705d-46ae-ae00-b218dd939975)|
| Android          |![image](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/eeb9c09e-d401-4593-9895-3f7b7ce33e2a) ![image](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/c5926ff1-de4e-4c76-a691-23c455d7f67a)|<img width="404" alt="image" …
> (PC-28336) feat(Notifications): add new notifs settings page

- __mocks__/@react-navigation/native.ts
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx
- src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
- src/features/culturalSurvey/pages/CulturalSurveyThanks.native.test.tsx
- src/features/culturalSurvey/pages/CulturalSurveyThanks.tsx
- src/features/identityCheck/pages/identification/educonnect/EduConnectValidation.native.test.tsx
- src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.native.test.tsx
- src/features/identityCheck/pages/profile/SetStatus.native.test.tsx
- src/ui/components/touchableLink/InternalTouchableLink.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28324
I have:
**_PROCEDURE TO SEE THE QPI:_**
Go to the backoffice testing - generate a test user.
Choose, 18, Ubble, and Identity verified.
Connect with the generated credentials.
Activate the credit within app.
The QPI should appear.
Web app after change to `ButtonTertiaryBlack`:
Navigation with TAB:
> (PC-28324) fix(CulturalSurveyIntro): Added reset on navigation from QPI

- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx.native-snap
- src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
- src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28337
I have:
| iOS              |<img width="347" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/4121f367-cd8d-49f7-a9ac-21bcd8241e45">|<img width="314" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/1b8b9a6a-cdd3-4e27-9c5e-d0a266ce913c">|
| Android          |<img width="347" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/8963d4e0-b63e-43ab-88cc-4c3e6c33751d">|<img width="403" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/56430339-bc9b-44b7-9 …
> (PC-28337) feat(NotificationsSettings): add disabled cases in notif settings

- src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx
- src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileSuccess.native.test.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileSuccess.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileSuccess.web.test.tsx
…ofile deletion success
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28157
I have:
| Platform      | After |
| :--------------- |  :---: |
| iOS              |         [fix-ios.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/af04659c-3b4d-47f3-a790-409099d845e9)            |
| Android          |          [android-fix.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/379378c9-c60b-4f05-bdd1-c513ebd129ce)         |
| Desktop - Chrome |            [fix-web.mov](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/083d83b2-3263-4c4c-ba23-018778098739)     |
> (PC-28157) fix(DeleteProfile): Reset navigation on profile deletion success

- src/features/offer/components/BookingButton/BookingButton.stories.tsx
- src/features/offer/components/BookingButton/BookingButton.tsx
- src/features/offer/components/CTAButton/CTAButton.tsx
- src/features/offer/components/OfferBookingButton/OfferBookingButton.tsx
- src/features/offer/components/OfferCTAButton/OfferCTAButton.tsx
- src/features/offer/components/StickyBookingButton/StickyBookingButton.native.test.tsx
- src/features/offer/components/StickyBookingButton/StickyBookingButton.stories.tsx
- src/features/offer/components/StickyBookingButton/StickyBookingButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-25665
I have:
| iOS              |![Capture d’écran 2024-03-18 à 09 45 39](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/dbfb3381-b725-4032-bb4b-de6f522181b4)|![Capture d’écran 2024-03-18 à 09 48 42](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/d38ef613-2a19-489a-87ec-d78e6829da39)|
| Android          |<img width="418" alt="Capture d’écran 2024-03-18 à 09 47 23" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0113424f-24f1-4bb1-9aa0-4a7f7f5b6d12">|<img width="418" alt="Capture d’écran 2024-03-18 à 09 48 33" …
> (PC-25665) refactor(offer): prepare use of booking button for web displaying

- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/features/offer/components/OfferPlace/OfferPlace.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28479
I have:
| iOS              |               |<img width="405" alt="Capture d’écran 2024-03-18 à 11 10 28" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/1ddbf8f0-398c-420a-bbde-d3be2829a10d">|
| Android          |               |<img width="424" alt="Capture d’écran 2024-03-18 à 11 10 18" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/a50b455d-c6df-4e8b-8cbf-d8071f6ba0ed">|
| Phone - Chrome   |               |<img width="424" alt="Capture d’écran 2024-03-18 à 11 09 12" src="https://github.com/pass-culture/pass-culture-app-native/assets/785 …
> (PC-28479) feat(offer): remove divider for desktop viewport

- __snapshots__/features/identityCheck/pages/identification/IdentificationFork.native.test.tsx.native-snap
- src/features/identityCheck/pages/identification/IdentificationFork.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28386
I have:
| iOS              | <img width="305" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/7b2b0db9-15ef-4cdb-85e8-6aacdff6bbd3"> | <img width="303" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/e50a44f0-80d2-4d25-874a-e0ec7b70c096"> |
> (PC-28386) fix(IdentificationFork): changed icon for link to EduConnect

- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.web.test.tsx.web-snap
- src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
- src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
- src/features/profile/pages/NotificationSettings/components/UnsavedSettingsModal.native.test.tsx
- src/features/profile/pages/NotificationSettings/components/UnsavedSettingsModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28339
I have:
| iOS              |               | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/a74bff1c-a193-434e-9ef8-40df1eed90da) |
| Phone - Chrome   |               | <img width="1552" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/b46b7868-08f6-4797-8065-1eb6800c9ce6"> |
| Desktop - Chrome |               | <img width="1440" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/1f57c43c-2b73-4498-92a0-f582754893bd"> |
> (PC-28339) feat(NotifSettings): added modal on go back unsaved changes

- src/features/profile/pages/NotificationSettings/components/UnsavedSettingsModal.tsx
I have:
| iOS              |               | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-03-25 at 15 40 15](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/761bcfc3-2755-4d8c-868c-569682c69894)  |
> (BSR) fix(NotifSettings): fix padding modal unsavedChanges

- ios/Podfile.lock
- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28805
BEFORE PR: for iOS 17, crash on press of start the cultural survey due to UIGraphicsBeginImageContext, discussed here: https://github.com/react-native-linear-gradient/react-native-linear-gradient/issues/637#issuecomment-1725219069
AFTER PR: no more crash
I have:
> (PC-28805) fix(LinearGradient): update of lib to fix crash UIGraphicsBeginImageContext

- .maestro/testsV2/InfoSectionNotShown.yml
- .maestro/testsV2/reusableFlows/features/search/SearchBookableCinemaOffer.yml
- .maestro/testsV2/reusableFlows/features/search/SearchBookableDuoOffer.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28825
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/153505101/d69bec9c-4562-497d-8b78-382426d52003
> (PC-28825) feat(maestro): add test for info section while not logged

- src/features/search/components/SearchBox/SearchBox.native.test.tsx
- src/features/search/components/SearchBox/SearchBox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28852
I have:
| Desktop - Chrome |<video src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/a882f7e8-a558-46ee-945d-1854ae0b7dae" controls="controls"></video>|<video src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/b0b89494-26a0-4281-8a63-c90c54acd2c9" controls="controls">
</video>|
> (PC-28852) feat(search): reset searchState on goBack to search landing

- scripts/create_and_push_tag_from_package_json_version.sh
- scripts/deploy_new_production_version.sh
There was an issue with the deployment scripts due to the pre-push hook. When we were performing a hotfix with the script, it retained the master version of the JSON packages, triggering a rebase or requiring conflict resolution. Consequently, the patch deployment resulted in an error.
> (BSR) fix(script): fix script on deployment

- __snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap
- __snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx.web-snap
- __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- src/features/search/components/SearchCustomModalHeader.tsx
- src/features/venue/components/VenueBody/VenueBody.tsx
- src/features/venueMap/components/VenueMapPreview/VenueMapPreview.tsx
- src/ui/InformationTags/InformationTags.tsx
- src/ui/components/headers/CloseButton.tsx
- src/ui/components/headers/PageHeaderSecondary.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28917
I have:
| iOS              |               |<img width="428" alt="Capture d’écran 2024-03-29 à 14 11 00" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/128cdbf6-9a65-4863-8fee-743d69fbc364">![Capture d’écran 2024-03-29 à 16 46 30](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/8c2c8010-a2fa-4f51-be72-a94f16a98c76)| …
> (PC-28917) fix(VenueMapPreview): correct ui when tags are in two lines

- scripts/dead_code_snapshot.txt
- src/features/home/components/SubscribeButtonWithTooltip.native.test.tsx
- src/features/home/components/SubscribeButtonWithTooltip.tsx
- src/features/internal/cheatcodes/pages/ThematicHomeHeaderCheatcode/ThematicHomeWithSubscribeCheatcode.tsx
- src/libs/storage.ts
- src/ui/components/Tooltip.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28570
I have:
| iOS              |    ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/404ff298-2f14-4fdf-90ee-cde79d0cf7cc)           |    ![Simulator Screenshot - iPhone 5 - 2024-04-04 at 17 36 46](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/03007daf-0b91-48ea-80b3-810f2ea9f6a1)   |
| Android          |      ![image](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/5960b28f-ef33-44df-8ea9-b1dd8645e29b)         |  <img width="287" alt="Capture d’écran 2024-04-06 à 15 13 36" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/eb5d5621-a2 …
> (PC-28570) feat(SubscribeButton): Handle tooltip display

- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/helpers/useOfferSummaryInfoList/useOfferSummaryInfoList.native.test.tsx
- src/features/offer/helpers/useOfferSummaryInfoList/useOfferSummaryInfoList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28943
I have:
| Phone - Chrome   |![Capture d’écran 2024-04-08 à 16 08 28](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/15a2edaa-d9c6-450c-a8d5-c1c1f038ce67)|![Capture d’écran 2024-04-08 à 16 08 08](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/c6271d67-4094-41a3-b335-d592953f1b21)|
> (PC-28943) feat(OfferBody): don't display offer venue button and summary info dates when this is a cinema offer

- src/features/home/types.ts
- src/libs/contentful/adapters/modules/adaptVenueMapModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptVenueMapModule.ts
On utilise l'id du module Contentful comme key sur la Home. Pour le module de carte des lieux, on ne gardait pas cet id : on avait donc `undefined` comme key -> warning sur la home en local
> (BSR) fix(home): fix warning

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/home/components/modules/RecommendationModule.native.test.tsx
- src/features/home/components/modules/RecommendationModule.tsx
- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/screenParamsUtils.ts
- src/features/offer/components/OfferPlaylistList/OfferPlaylistList.tsx
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/analytics/types.ts
- src/ui/components/buttons/FavoriteButton.native.test.tsx
- src/ui/components/buttons/FavoriteButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28822
I have:
| Mockup/Before | After |
| :-----------: | :---: |
| <img width="364" alt="ClickBookOffer_before" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/51cea35f-5797-4932-bdbc-e76737a4618a"> | <img width="466" alt="ClickBookOffer_after" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/ac70d26e-3267-46a3-9ece-51f76ac7610b"> |
| <img width="377" alt="hasAddedToFavorites_before" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/5236ef5e-8482-452c-badd-8e8dc8cb2fd4"> | <img width="466" alt="hasAddedToFavorites_after" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/a27c4b27-1178 …
> (PC-28822) fix(tracking): add api reco params to trackers when offers comes from a reco playlist

- src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx
- src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29078
I have:
| Platform| Default(non connecté/assez crédit)| Before | After |
| iOS |  ![PC-29078_enough-credit](https://github.com/pass-culture/pass-culture-app-native/assets/158567429/86540a40-387b-4136-9054-d3bf8dee0b04)| ![PC-29078_before](https://github.com/pass-culture/pass-culture-app-native/assets/158567429/a8142801-a732-4a85-9b58-aa06fdee00cb)| ![PC-29078_after](https://github.com/pass-culture/pass-culture-app-native/assets/158567429/183bccab-1459-48d9-b6a7-1ce4fa77f9b5)      |
> (PC-29078) fix(EventCard): Give user credit priority over screening status on movie screening event card

- __snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx.web-snap
- __snapshots__/features/errors/pages/AsyncErrorBoundary.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/components/layout/PageWithHeader.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/educonnect/EduConnectForm.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/educonnect/EduConnectValidation.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/identification/ubble/SelectPhoneStatus.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap
- __snapshots__/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.web.test.tsx.web-snap
- __snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx.web-snap
- __snapshots__/features/share/pages/WebShareModal.web.test.tsx.web-snap
- __snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
- __snapshots__/ui/components/buttons/AppButton/AppButton.web.test.tsx.web-snap
- __snapshots__/ui/components/buttons/ScrollButtonForNotTouchDevice.web.test.tsx.web-snap
- __snapshots__/ui/components/eventCard/EventCardList.web.test.tsx.web-snap
- package.json
- src/features/auth/helpers/contactSupport.ts
- yarn.lock
`satisfies` en typescript, est utilisé à partir de la version `4.9` de `typescript` et la version `7.20.0` de `@babel/core`.
`babel` est utilisé par `jest` pour les tests (dans `jest.config.js`)
Des paquets du scope de `babel` utilisaient une version inferieure à la version `7.20.0`, qui étaient retranscrits dans le `yarn.lock`, j'ai dû supprimer manuellement les versions obsolètes du `yarn.lock` et le regénérer.
Seules ces modifications étaient nécessaires pour l'utilisation du `satisfies`.
J'en ai également profité pour la mise à jour de tous les paquets du scope de `babel` à la dernière version pour uniformiser leur version utilisée
Les snapshots web ont dû être mis à jour
Il faudra lancer la commande `npx jest --clear-cache` une fois pour que les tests passent en local avec des …
> (BSR) chore(deps): upgrade babel

- junit.xml
- package.json
- yarn.lock
Dans la [documentation de Jest](https://jestjs.io/fr/docs/getting-started), il est spécifié que la configuration se fait soit avec `babel-jest` et `babel/preset-typescript` soit avec `ts-jest`.
Le projet utilisant `babel-jest` et `babel/preset-typescript`, `ts-jest` n'est pas utilisé.
> (BSR) chore(deps): remove ts-jest

- __snapshots__/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx.native-snap
- src/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx
- src/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.tsx
The deposit reset mention is only relevant when the user turns 18.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29024
| iOS              |               |   <img width="367" alt="Capture d’écran 2024-04-17 à 12 00 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/26348504/01d143f7-81bb-4de5-b63a-ce28f3fb414b">    |
| Android          |     |   <img width="425" alt="Capture d’écran 2024-04-16 à 18 39 46" src="https://github.com/pass-culture/pass-culture-app-native/assets/26348504/1ed6a94c-7f8a-40bf-8ac6-fdf03aa9d9ca">       |   
| Desktop - Chrome |               |   <img width="532" alt="Capture d’écran 2024-04-16 à 18 40 27" …
> (PC-29024) fix(subscription): hide deposit reset mention for most users

- src/features/search/context/SearchWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29251
Ce ticket fait suite à cette PR : https://github.com/pass-culture/pass-culture-app-native/pull/6283
J'ai supprimé le price range qui à priori n'est plus utilisé, donc j'ai également supprimé le useEffect qui mettait à jour le searchState avec le priceRange par défaut et à la suite de cela, la CI a remonté une augmentation de 5 re-renders sur la page Search Results. Suite à cela, j'ai remis le useEffect inutile (à priori) pour faire passer la CI (ce qui d'ailleurs faisait baisser le nombre de re-renders de 8 à 7), mais en gardant un ticket pour investiguer cette augmentation de re-renders.
Après investigation avec @aliraiki, on a remarqué qu'en fait, avec le useEffect, le test de perf de la page SearchResults testait en …
> (PC-29251) fix(Search): Remove temporary fix

- __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
- scripts/dead_code_snapshot.txt
- src/features/home/components/SubscribeButtonWithModals.native.test.tsx
- src/features/home/components/SubscribeButtonWithModals.tsx
- src/features/home/fixtures/homepage.fixture.ts
- src/features/home/pages/ThematicHome.native.test.tsx
- src/features/home/pages/ThematicHome.tsx
- src/features/subscription/helpers/useThematicSubscription.native.test.tsx
- src/features/subscription/helpers/useThematicSubscription.tsx
- src/features/subscription/helpers/useThematicSubscription.web.test.tsx
moving the modals state down the tree prevent flashes when a user subscribes to a home thematic.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29257
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26348504/d72bfb29-e807-4d83-bd18-92e69fca805b
> (PC-29257) refactor(subscription): group modals and button to prevent rerender

- src/libs/firebase/analytics/useInit.native.test.ts
- src/libs/firebase/analytics/useInit.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29383
I have:
> (PC-29383) fix(firebase): Reset default event params when no campaign date in storage

- src/features/home/components/headers/AnimatedCategoryThematicHomeHeader.tsx
- src/features/home/components/headers/AnimatedHighlightThematicHomeHeader.tsx
- src/features/home/pages/ThematicHome.tsx
redeclaring animated components create a new component, thus remounting all child components.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29257
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/26348504/bd8ddcec-1135-424a-b55b-08d305bbc8fb
> (PC-29257) refactor(subscription): move animated components outside

- src/ui/components/modals/SurveyModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29290
I have:
| iOS              |![Capture d’écran 2024-04-30 à 09 48 17](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/2df8fcc4-65ea-4a4c-ba86-714fbacc0cf0)|![Capture d’écran 2024-04-30 à 09 48 04](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/5d06f48c-4840-442d-88ac-d5eb8c9e96ad)|
| Android          |![Capture d’écran 2024-04-30 à 09 48 21](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/d84eada8-2018-419d-905e-443e03a1c8f9)|![Capture d’écran 2024-04-30 à 09 47 36](https://github.com/pass-culture/pass-culture-app-native/ass …
> (PC-29290) fix(ui): remove spacing when button not display for survey modal

- src/features/offer/components/StickyBookingButton/StickyBookingButton.tsx
- src/ui/components/BlurryWrapper/BlurryWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29395
I have:
| iOS              |<img width="445" alt="Capture d’écran 2024-04-29 à 16 11 28" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/7eeb41d2-7b15-4fc0-9672-7fe432b0650d">|<img width="447" alt="Capture d’écran 2024-04-29 à 16 10 51" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/2b587e26-2c9e-4c6b-8ce0-44a16c2fb67a">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6 …
> (PC-29395) fix(StickyBookingButton): fix the spacing between the bottom of the mobile and the blur

- src/features/search/api/useSearchResults/useSearchResults.native.test.ts
- src/features/search/components/SearchListHeader/SearchListHeader.tsx
- src/features/search/helpers/getSearchVenuePlaylistTitle/getSearchVenuePlaylistTitle.test.ts
- src/features/search/helpers/getSearchVenuePlaylistTitle/getSearchVenuePlaylistTitle.ts
- src/libs/algolia/enums/facetsEnums.ts
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildVenueSearchParameters/buildVenueSearchParameters.test.ts
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildVenueSearchParameters/buildVenueSearchParameters.ts
- src/libs/algolia/fetchAlgolia/buildVenuesQueryOptions.ts
- src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.test.ts
- src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.ts
- src/libs/algolia/fetchAlgolia/fetchVenues/buildFetchVenuesQueryParameters.native.test.ts
- src/libs/algolia/fetchAlgolia/fetchVenues/buildFetchVenuesQueryParameters.ts
- src/libs/algolia/fetchAlgolia/fetchVenues/fetchVenues.native.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29067
Les facets ont été ajoutées manuellement en tant que filtres uniquement dans Algolia :
- pour sandbox testing dans  index testing-venues
- pour production  dans venue-playlist-search-newest et venue-playlist-search
I have:
sans filtre d'accessibilité | avec un filtre d'accessibilité 
--- | --- 
https://github.com/pass-culture/pass-culture-app-native/assets/144016890/590d619a-c266-4913-aeb5-ef259989681b
> (PC-29067) feat(SearchVenuePlaylists): playlists responsive to accessibility filter

- src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx
- src/features/search/pages/SearchFilter/SearchFilter.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29591
I have:
| AVANT |
| :------------------: |
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/b435fe2c-9e99-4e59-a2a3-141ccbdc205a
| APRES |
| :------------------: |
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/b4f2b6e5-e90f-4c03-91e7-9d11003e5bec
> (PC-29591) fix(SearchFilters): Fix reset press by resetting gtls array on dispatch

- src/libs/recommendation/useHomeRecommendedIdsQuery.native.test.ts
- src/libs/recommendation/useHomeRecommendedIdsQuery.ts
- src/tests/mswServer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29925
Après discussion avec l'équipe data: 
1. Pas besoin de logguer une erreur si la liste des recos est vide:
- Retourner une liste de recos vide, c'est un comportement voulu dans quelques cas (Si on ne trouve pas de reco suffisamment pertinente, on préfère ne pas en retourner)
- Les cas où c'est non-optimal, c'est plutôt du côté de l'API reco que l'investigation aura lieu.
2. C'est mieux si on sépare les logs des erreurs par code d'erreur http, ça aidera à naviguer les erreurs sur Sentry pour tout le monde
I have:
| …
> (PC-29925) feat(log): improve sentry logs for reco endpoint

- __snapshots__/features/home/components/AttachedOfferCard.native.test.tsx.native-snap
- __snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap
- __snapshots__/features/home/components/modules/video/VideoModule.native.test.tsx.native-snap
- __snapshots__/features/home/components/modules/video/VideoMonoOfferTile.native.test.tsx.native-snap
- __snapshots__/features/home/components/modules/video/VideoMultiOfferTile.native.test.tsx.native-snap
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/home/components/AttachedOfferCard.native.test.tsx
- src/features/home/components/AttachedOfferCard.stories.tsx
- src/features/home/components/AttachedOfferCard.tsx
- src/features/home/components/AttachedOfferCardButton.native.test.tsx
- src/features/home/components/AttachedOfferCardButton.tsx
- src/features/home/components/modules/video/VideoModal.native.test.tsx
- src/features/home/components/modules/video/VideoModule.native.test.tsx
- src/features/home/components/modules/video/VideoModuleMobile.tsx
- src/features/home/components/modules/video/VideoMonoOfferTile.native.test.tsx
- src/features/home/components/modules/video/VideoMonoOfferTile.tsx
- src/features/home/components/modules/video/VideoMultiOfferTile.native.test.tsx
- src/features/home/components/modules/video/VideoMultiOfferTile.tsx
- src/features/internal/cheatcodes/pages/CheatMenu/Video9:16/Video916.tsx
- src/theme/index.ts
- src/ui/svg/icons/Play.tsx
- src/ui/theme/colors.ts
- src/ui/theme/gradientColorsMapping.ts
- src/ui/theme/videoModuleMobileColorsMapping.native.test.ts
- src/ui/theme/videoModuleMobileColorsMapping.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29724
I have:
| Desktop - Chrome - MonoOffre | <img width="431" alt="PC-29724-monooffer-before" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/687f8df0-923a-45fb-9e74-88ec66780863"> | <img width="433" alt="PC-29724-monooffer-after" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/374726ed-1dfc-43ff-89a1-721a82f143e0"> |
| Desktop - Chrome - MultiOffre | <img width="434" alt="PC-29724-multioffer-before" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/0c7431f8-71d8-4507-9910-6ea26551f477"> | <img width="431" …
> (PC-29724) feat(VideoModuleMobile): Refonte UI bloc mono/multi offre

- __snapshots__/features/home/components/modules/video/VideoModule.native.test.tsx.native-snap
- src/features/home/components/modules/video/VideoModuleMobile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29724
I have:
> (BSR) fix(VideoModuleMobile): Set borderRadius to 0 instead of unset

- src/features/home/components/modules/HighlightOfferModule.native.test.tsx
- src/features/home/components/modules/HighlightOfferModule.tsx
- src/features/home/components/modules/marketing/MarketingBlockContent.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29741
I have:
| iOS              |        <img width="285" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/169038942/b14b3ad3-3e18-4ca0-bd17-9e69225568e7">       |   ![image](https://github.com/pass-culture/pass-culture-app-native/assets/169038942/0d89736b-3dd9-4e24-a358-33c12f92eb57)    |
| Desktop - Chrome |       <img width="533" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/169038942/c5b20cee-7574-40ea-ac95-865ffcbe3022">        |    <img width="1512" …
> (PC-29734) feat(HighlightOfferModule): display new MarketingBlockExclusivity component with FF in HighlightOfferModule

- src/libs/keychain/keychain.native.test.ts
- src/libs/keychain/keychain.ts
Firebase sometimes overrides the credentials returned by Keychain.getGenericPassword. Since we store the refresh token there, the backend sometimes rightfully returns a 422 error because the refresh token is not one issued by the backend.
This bug only occurs on iOS, see oblador/react-native-keychain/issues/363.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29992
> (PC-29992) fix(auth): fix refresh token read on iOS

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/home/components/modules/video/OldVideoModuleDesktop.tsx
- src/features/home/components/modules/video/OldVideoModuleMobile.tsx
- src/features/home/components/modules/video/VideoModule.tsx
- src/features/home/components/modules/video/VideoModuleDesktop.tsx
- src/features/home/components/modules/video/VideoModuleMobile.tsx
- src/ui/theme/videoModuleColorsMapping.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30074
I have:
| Desktop - Chrome | <img width="1029" alt="Capture d’écran 2024-06-14 à 11 35 15" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/26fac027-bb96-420e-803f-c28a88d02b18"> | <img width="1026" alt="PC-30004-desktop3" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/a904fa52-6a0d-4f09-9439-707372dd2b97"> |
| Desktop - Chrome | <img width="1028" alt="Capture d’écran 2024-06-14 à 11 36 12" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/042bf68f-dfb1-4fd8-bc9b-35de450a9a48"> | <img width="1030" alt="PC-30004-desktop2" …
> (PC-30074) feat(VideoModuleDesktop): refonte ui de VideoModuleDesktop

- __snapshots__/features/favorites/pages/NotConnectedFavorites.native.test.tsx.native-snap
- src/features/favorites/pages/NotConnectedFavorites.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30156
I have:
| Desktop - Chrome | <img width="635" alt="Screenshot 2024-06-14 at 11 21 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/97eb07d7-5af4-42fc-b387-db47b2a6620d"> |  <img width="626" alt="Screenshot 2024-06-14 at 11 21 05" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/eb81b5af-b00e-4fe2-b48d-233f7ff71149"> |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e68 …
> (PC-30156) fix(NotConnectedFavorites): connect button is now responsive

- src/features/offer/api/useSimilarOffers.native.test.ts
- src/features/offer/api/useSimilarOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30362
I have:
> (PC-30362) fix(offer): not display Oups page when similar offers API not respond on offer page

- src/features/venue/components/OpeningHours/OpeningHours.native.test.tsx
- src/features/venue/components/OpeningHours/OpeningHours.tsx
- src/features/venue/components/PracticalInformation/PracticalInformation.native.test.tsx
- src/features/venue/components/VenueTopComponent/VenueTopComponent.native.test.tsx
- src/features/venue/fixtures/venueWithOpeningHours.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28774
I have:
| Platform         | Sans Zoom 200% | Avec Zoom 200% |
| iOS              |  <img width="478" alt="Capture d’écran 2024-06-21 à 15 47 01" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/1a2d0d00-760c-4ac1-a4b9-e3043b2da3b6"> <img width="474" alt="Capture d’écran 2024-06-21 à 14 17 04" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/6e9bc2fe-f9ee-4630-9064-136fd78ad7b1">  |  <img width="477" alt="Capture d’écran 2024-06-21 à 14 26 04" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/2da9f739-b4f2-400a-af7d-307717ead065"> <img width="472" …
> (PC-28774) feat(venue): Fix accessibility for opening hours

- src/features/home/components/modules/HighlightOfferModule.tsx
- src/features/home/components/modules/marketing/MarketingBlockExclusivity.native.test.tsx
- src/features/home/components/modules/marketing/MarketingBlockExclusivity.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30445
I have:
> (PC-30445) fix(MarketingBlockExclusivity): add homeEntryId to tracking

- src/features/offer/components/OfferImageContainer/OfferImageContainer.web.test.tsx
- src/features/venueMap/hook/useGetDefaultRegion.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30464
I have:
> (PC-30464) fix(home): use Paris coordinates to open venue map from trend button when user not share his position

- src/features/home/components/modules/video/VerticalVideoPlayer.tsx
- src/features/home/components/modules/video/VideoCarouselModule.tsx
- src/features/home/components/modules/video/useVerticalVideoPlayer.native.test.ts
- src/features/home/components/modules/video/useVerticalVideoPlayer.ts
- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30515
I have:
| iOS              |<img width="635" alt="Capture d’écran 2024-07-01 à 11 21 08" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/5856d2b6-1e71-4917-94e6-3d6771055148">|
> (PC-30515) feat(analytics): add video paused analytics params and round durations

- src/features/navigation/TabBar/TabBar.native.test.tsx
- src/features/navigation/TabBar/TabBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30586
I have:
| iOS              |<video src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/29a4d094-8047-4811-9d45-2e768a41de23"/>|<video src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/c579eae8-d5eb-47f7-a746-76d19d1cb3ff"/>|
> (PC-30586) fix(location): keep locationFilter on "Recherche" press in the tabBar

- src/features/home/components/modules/video/VideoCarouselModule.native.test.tsx
- src/features/home/components/modules/video/VideoCarouselModule.tsx
I have:
| iOS              |<img width="639" alt="Capture d’écran 2024-07-04 à 17 16 49" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/81cf3889-63e5-4f84-bee5-e46b1a2d7701">|
> (BSR) fix(analytics): make sure ConsultVideo is logged on first video autoplay

- src/features/home/components/modules/RecommendationModule.native.test.tsx
- src/features/home/components/modules/RecommendationModule.tsx
- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30709
I have:
> (PC-30709) fix(home): add only call_id from api reco params for ModuleDisplayedOnHomepage log

- __snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap
- __snapshots__/features/cookies/pages/CookiesConsent.native.test.tsx.native-snap
- __snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap
- __snapshots__/features/location/components/HomeLocationModal.native.test.tsx.native-snap
- __snapshots__/features/location/components/SearchLocationModal.native.test.tsx.native-snap
- __snapshots__/features/location/components/VenueMapLocationModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx.native-snap
- __snapshots__/features/venueMap/pages/modals/VenueTypeModal/VenueTypeModal.native.test.tsx.native-snap
- __snapshots__/ui/components/modals/AppModal.native.test.tsx.native-snap
- src/features/offer/components/OfferImageCarouselPagination/OfferImageCarouselPagination.web.tsx
- src/features/offer/components/OfferPreviewModal/OfferPreviewModal.tsx
- src/ui/CarouselDot/CarouselDot.tsx
- src/ui/components/modals/AppModal.tsx
- src/ui/components/modals/appModalContainerStyle.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30725
- Ajout d'une prop `desktopConstraints` dans `AppModal` permettant de gérer la taille de la modal en desktop
- Update visuel de la pagination en mode desktop
I have:
> (PC-30725) fix(offer): adapt modal size in desktop

- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/api/gen/api.ts
- src/features/gtlPlaylist/hooks/useGTLPlaylists.native.test.ts
- src/features/home/components/modules/venues/VenueTile.tsx
- src/features/offer/components/OfferPlace/OfferPlace.tsx
- src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.native.test.tsx
- src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.stories.tsx
- src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.tsx
- src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.native.test.ts
- src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.ts
- src/features/venue/components/VenueTopComponent/VenueTopComponent.tsx
- src/features/venue/fixtures/venueDataTest.ts
- src/libs/location/components/WhereSection.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28937
I have:
> (PC-28937) feat(GetOpeningHoursStatus): Add timezone to dynamic open status

- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30656
I have:
| iOS              |![Capture d’écran 2024-07-11 à 09 17 52](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/fb7f3120-113c-4e53-ad97-44297531f6c2)|![Capture d’écran 2024-07-11 à 09 16 39](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/bb809cdb-34c0-4fad-9cbc-882d08edd053)|
[1]: …
> (PC-30656) feat(venueMap): larger cluster and no animation in iOS

- src/features/home/components/AttachedModuleCard/AttachedCardDisplay.tsx
- src/features/home/components/modules/marketing/MarketingBlockExclusivity.tsx
- src/features/home/components/modules/marketing/MarketingBlockHighlight.tsx
- src/features/home/components/modules/video/VideoCarouselModule.tsx
- src/features/home/components/modules/video/VideoMonoOfferTile.tsx
- src/ui/components/ShadowWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30345
I have:
| iOS              | (pareil qu'après)      |<img width="373" alt="Capture d’écran 2024-07-11 à 10 22 32" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/47feec12-6867-4bf2-a20d-60b9cb081cd4">|
| Android          |<img width="341" alt="Capture d’écran 2024-07-11 à 10 35 01" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/56a53c71-dcf2-4d48-943e-f63466bddf88">|<img width="386" alt="Capture d’écran 2024-07-11 à 10 20 53" …
> (PC-30345) fix(AttachedCardDisplay): android weird shape on press

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/location/components/VenueMapLocationModal.native.test.tsx
- src/features/location/components/VenueMapLocationModal.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/screenParamsUtils.ts
- src/features/search/api/useSearchResults/useSearchResults.native.test.ts
- src/features/search/api/useSearchResults/useSearchResults.ts
- src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx
- src/features/search/components/SearchListHeader/SearchListHeader.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/constants.ts
- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.tsx
- src/features/venueMap/store/initialVenuesStore.native.test.ts
- src/features/venueMap/store/initialVenuesStore.ts
management of the height of the map in the tab
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30763
I have:
| iOS              |![Capture d’écran 2024-07-15 à 15 49 42](https://github.com/user-attachments/assets/73e784de-c66d-4e01-a42e-d7b2a67bde1a) ![Capture d’écran 2024-07-15 à 16 34 21](https://github.com/user-attachments/assets/86086151-b2a2-4a37-a999-45f8d2187970)|![Capture d’écran 2024-07-15 à 15 49 19](https://github.com/user-attachments/assets/114abbe0-0697-40a0-a291-359741947bf7) ![Capture d’écran 2024-07-15 à 16 34 …
> (PC-30763) feat(search): display search results venues playlist in the map

- __snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx.web-snap
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30770
I have:
| iOS              |![Capture d’écran 2024-07-16 à 14 31 08](https://github.com/user-attachments/assets/2aa3361e-41e0-470c-85c0-f1a35194661a)|![Capture d’écran 2024-07-16 à 14 30 35](https://github.com/user-attachments/assets/e3fc404d-3d4d-45c7-bbd9-6a792ed85e30)| …
> (PC-30770) refactor(SearchResultsContent): handle tabs and no search result with the empty states

- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/venue/components/TabLayout/TabLayout.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30927
I have:
Avant Android :
https://github.com/user-attachments/assets/db79ed23-7b15-42c3-99cb-7f0887b76dbf
Après Android :
https://github.com/user-attachments/assets/23773658-5b98-4241-89c4-24b12823ab81
Avant iOS :
https://github.com/user-attachments/assets/27b6833a-2447-413a-bf9e-643f02bc1024
Après iOS :
https://github.com/user-attachments/assets/636830ae-2601-49bd-b077-ddb37b5863af
> (PC-30927) feat(search): empty map tab when selected location mode is everywhere

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/helpers/getStringifySearchStateWithoutLocation/getStringifySearchStateWithoutLocation.test.ts
- src/features/search/helpers/getStringifySearchStateWithoutLocation/getStringifySearchStateWithoutLocation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30773
I have:
> (PC-30773) feat(search): reset tab to search results list when filter applied and filter is not location

- android/settings.gradle
After RN upgrade to RN 0.72 we had an issue building the APK :
https://github.com/react-native-netinfo/react-native-netinfo/issues/679#issuecomment-1786822460
> (BSR) chore(deps): fix android apk generation

- package.json
- src/features/venueMap/components/VenueMapBottomSheet/VenueMapBottomSheet.tsx
- src/features/venueMap/components/VenueMapBottomSheet/VenueOfferPlaylist.tsx
- src/features/venueMap/components/VenueMapPreview/VenueMapPreview.native.test.tsx
- src/features/venueMap/components/VenueMapPreview/VenueMapPreview.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.web.tsx
- src/features/venueMap/helpers/geoLocatedVenueToVenueResponse/geoLocatedVenueToVenueResponse.test.ts
- src/features/venueMap/helpers/geoLocatedVenueToVenueResponse/geoLocatedVenueToVenueResponse.ts
- src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.web.tsx
- src/features/venueMap/pages/VenueMap/VenueMapBase.tsx
- src/libs/algolia/fetchAlgolia/fetchVenues/fixtures/AlgoliaVenuesFixture.ts
- src/libs/algolia/fetchAlgolia/fetchVenues/fixtures/venuesFixture.ts
- src/tests/setupTests.js
- src/theme/index.ts
- src/ui/components/Playlist.tsx
- src/ui/components/headers/CloseButton.tsx
- src/ui/theme/layers.ts
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30769
Intégration d'un composant BottomSheet, comprenant les informations sur le lieu ainsi que la playlist des offres liées à ce lieu, dans la carte.
La gestion du recentrage auto de la carte sera gérée dans une autre PR.
⚠️ ~En attente de confirmation pour placer cette feature sous FF~
Validé avec @henrigarnier  : On prévoit la feature flag dans une autre PR
I have:
https://github.com/user-attachments/assets/e6ff0c38-0ad5-4f43-89d7-daee1340c3eb
https://github.com/user-attachments/assets/6488a520-03d4-4f36-913c-658f24cac994
[2]: …
> (PC-30769) feat(venueMap): bottom-sheet integration into venueMap

- src/features/search/components/SearchBox/SearchBox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30944
I have:
Avant : 
https://github.com/user-attachments/assets/37bb8ad2-bb49-40b0-a9b6-3d4492d640dc
Après: 
https://github.com/user-attachments/assets/685f1a10-02cc-4938-97de-49920932c466
> (PC-30944) fix(SearchBox): keep the location filter on go back in theSearch

- __snapshots__/features/profile/pages/Profile.web.test.tsx.web-snap
- src/features/profile/pages/Profile.web.test.tsx
We needed to mock the app version for not having to update the profile snapshot after each app version bump.
> (BSR) fix(profile): fix profile snapshot by mocking the app version

- __mocks__/react-native-map-clustering.ts
- jest/jest.setup.ts
- src/features/venueMap/components/VenueMapBottomSheet/VenueMapBottomSheet.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/features/venueMap/components/VenueMapView/constant.ts
- src/features/venueMap/hook/useCenterOnLocation.native.test.ts
- src/features/venueMap/hook/useCenterOnLocation.ts
- src/tests/setupTests.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30929
Prise en compte de l'occupation de la bottom sheet lors du recentrage d'un marker sur la carte.
I have:
https://github.com/user-attachments/assets/836d1d8e-74c5-40ca-acc8-615ec85f76c2
> (PC-30929) feat(venueMap): handle bottom sheet when center on location

- yarn.lock
On se permet ici de merger avec les tests de performance rouge pour justement les rétablir.
En effet, lors du bump de TypeScript dans [cette PR](https://github.com/pass-culture/pass-culture-app-native/pull/6718), le `yarn.lock` a été modifié avec une mauvaise version (1.0.9) de la lib `react-native-launch-navigator`. On la remet ici à 1.0.8.
I have:
[1]: …
> (PC-31001) fix(deps): downgrade react-native-launch-navigator in yarn.lock

- src/libs/jwt/jwt.test.ts
- src/libs/jwt/jwt.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31162
I have:
> (PC-31162) feat(jwt): add 1 minute buffer to verify token expiration

- android/build.gradle
- android/gradle.properties
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31308
I have:
The minSdkVersion has been upgraded to 24 according to [this](https://stackoverflow.com/questions/77910478/flutter-android-unable-to-build-failed-to-transform-kotlin-stdlib-1-9-10-jar)
> (PC-31308) chore(deps): upgrade target SDK 33 -> 34

- src/shared/hook/useTrackDuration.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31361
I have:
> (PC-31361) fix(shared): Reset refs to initial values after duration calculation in useTrackDuration hook

- src/features/home/components/modules/video/useVerticalVideoPlayer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31322
Made sure the tracker is logged when navigating in the app
I have:
> (PC-31322) feat(verticalVideo): make sure we log videoPaused on player state change

- .storybook/mocks/firebase.js
- __mocks__/@react-native-community/netinfo.ts
- __mocks__/@react-native-firebase/firestore.ts
- jest/jest.web.setup.ts
- src/libs/firebase/firestore/client.web.ts
- src/libs/firebase/firestore/getCookiesLastUpdate.native.test.ts
- src/libs/firebase/firestore/getCookiesLastUpdate.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-22093
I have:
> (PC-22093) fix(firestore): handle offline persistence + network

- .eslintrc.js
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/api/apiHelpers.ts
- src/features/auth/api/useSignIn.ts
- src/features/auth/pages/login/Login.native.test.tsx
- src/features/bookOffer/components/BookingOfferModalFooter.tsx
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
- src/features/tutorial/helpers/useUserRoleFromOnboarding.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30862
I have:
> (PC-30862) fix(useSignIn): better handling of accountState

- src/features/offer/api/useSimilarOffers.native.test.ts
- src/features/offer/api/useSimilarOffers.ts
I tried locally to send 2 events to Sentry: 
```javascript
eventMonitoring.captureException(new Error(`Error test`))
eventMonitoring.captureException(`Error test badly formatted`)
```
Here are the resulting events in Sentry:
So it is better to use a real error object.
This should help with these particular issues
I have:
> (BSR) chore(sentry): use error in capture exception for better formating

- src/libs/firebase/firestore/getCookiesLastUpdate.native.test.ts
- src/libs/firebase/firestore/getCookiesLastUpdate.ts
Fix sur les feature flags qui étaient inactifs côté web.
I have:
> (BSR) fix(firestore): feature flags for web

- src/features/offer/components/MoviesScreeningCalendar/MovieOfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31503
I have:
> (PC-31503) fix(movieScreening): get movie duration from extra data

- src/features/bookings/components/BicolorBookingsCountV2.native.test.tsx
- src/features/bookings/components/BicolorBookingsCountV2.tsx
- src/features/bookings/helpers/useBookingsAwaitingReaction.test.tsx
- src/features/bookings/helpers/useBookingsAwaitingReaction.ts
- src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx
- src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx
- src/features/navigation/RootNavigator/Header/Header.web.test.tsx
- src/features/navigation/RootNavigator/Header/Header.web.tsx
- src/features/navigation/RootNavigator/Header/Nav.tsx
- src/features/navigation/RootNavigator/Header/NavItem.tsx
- src/features/navigation/RootNavigator/RootNavigator.web.test.tsx
- src/features/navigation/TabBar/TabBar.native.test.tsx
- src/features/navigation/TabBar/TabBar.tsx
- src/features/navigation/TabBar/TabBarComponent.tsx
- src/features/navigation/TabBar/TabBarInnerComponent.tsx
- src/features/navigation/TabBar/TabBarInnerComponentV2.tsx
- src/features/navigation/TabBar/types.ts
- src/features/navigation/helpers/useTabBarItemBadges.test.ts
- src/features/navigation/helpers/useTabBarItemBadges.ts
- src/ui/svg/icons/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31387
Gestion du badge pour les réservations terminées dans la tabBar sur mobile et le Header pour le web.
I have:
> (PC-31387) feat(navigation): bookings reaction counter

- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31561
Fix sur le compteur de like dans la page offre,  qui n'était pas conditionné par un feature flag.
I have:
> (PC-31561) fix(offer): like counter visibility upon feature flag value

- src/features/venue/api/useVenueOffers.test.ts
- src/features/venue/api/useVenueOffers.ts
- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/fixtures/venueResponse.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31553
Branchement de la nouvelle multi-requete agolia pour la récupération des offres en fonction d'un lieu + attributs de recherche
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985a …
> (PC-31553) feat(venueMap): use multiOffer request for venu offers in bottom sheet

- __snapshots__/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.native.test.tsx.native-snap
- src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.native.test.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.web.test.tsx
- src/ui/pages/GenericInfoPageWhite.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31349
I have:
| iOS              |               |    ![image](https://github.com/user-attachments/assets/f8cfecb0-39b4-4097-bc62-8e6024ad3493)   |
| Desktop - Chrome |               |    <img width="1512" alt="image" src="https://github.com/user-attachments/assets/4144c646-5c60-443a-94c0-c9e5d2ffd603">   |
[2]: …
> (PC-31349) feat(DeleteProfileAccountNotDeletable): can not delete account screen

- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/pages/Offer/Offer.perf.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31654
Désactivation du lien vers la page artiste si l'artiste à moins de 2 offres
I have:
> (PC-31654) feat(offer): disable artist page link if artist has less than 2 offers

- .github/workflows/dev_on_workflow_environment_android_deploy.yml
I think we removed this by error when merging vite and it fails the android deploy
> (BSR) fix(deploy): android sentry config restoration

- src/features/bookings/components/EndedBookingItem.tsx
- src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.native.test.tsx
- src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.tsx
- src/features/home/constants.ts
- src/features/home/pages/Home.tsx
- src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.native.test.tsx
- src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx
- src/features/reactions/enum.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31711
I have:
> (PC-31711) feat(home): display reaction modal for bookings used for more than 24 hours

- src/features/offer/components/OfferPreviewModal/OfferPreviewModal.web.tsx
Remise en place de la modale d'aperçu des offres côté web.
I have:
> (BSR) fix(offer): restore offer preview modal for web

- .github/workflows/dev_on_push_workflow_main.yml
The idea is to trigger a production build for ios when we trigger a staging build as it will push a TestFlight version to AppStoreConnect
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31018
> (PC-31018) feat(CI): trigger ios prod build at the same time as a staging build

- __snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap
- src/api/gen/api.ts
- src/features/bookings/components/EndedBookingItem.tsx
- src/features/bookings/fixtures/bookingsSnap.ts
- src/features/bookings/pages/Bookings/Bookings.native.test.tsx
- src/features/bookings/pages/Bookings/Bookings.tsx
- src/features/bookings/pages/Bookings/Bookings.web.test.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx
- src/features/bookings/types.ts
- src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.native.test.tsx
- src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.tsx
- src/features/reactions/api/useReactionMutation.test.ts
- src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx
- src/features/venue/components/TabLayout/TabLayout.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31778
I have:
https://github.com/user-attachments/assets/4910b557-ceff-458e-8b7d-8b5e89f84bcc
> (PC-31778) feat(Bookings): post reaction on tab change or on change screen

- src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.native.test.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.tsx
https://passculture.atlassian.net/browse/PC-31943
I have:
> (PC-31943) fix(DeleteProfileSuccess): prevent redirection to connection after anonymization

- src/features/cookies/helpers/useIsCookiesListUpToDate.native.test.ts
- src/features/cookies/helpers/useIsCookiesListUpToDate.ts
- src/features/cookies/pages/PrivacyPolicy.native.test.tsx
- src/features/cookies/pages/PrivacyPolicy.tsx
- src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.native.test.tsx
- src/features/home/components/IncomingReactionModalContainer/IncomingReactionModalContainer.tsx
- src/features/navigation/RootNavigator/RootNavigator.web.test.tsx
- src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31805
I have:
J'ai remarqué un petit bug visuel en testant que j'ai fix au passage (visible en mode tablette) :
Avant :
Après :
> (PC-31805) feat(home): verify cookies consent before displaying reaction modal

- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.tsx
- src/libs/maps/maps.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32103
Ajout d'une prop permettant de masquer différents lieux inutiles pour soulager la carte visuellement
TODO: Mettre cette fonctionnalité sous FF
I have:
Android: 
iOS : 
> (PC-32103) feat(venueMap): add prop to hide points of interest

- src/features/offer/components/OfferNewXPCine/OfferNewXPCineBlock.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/ui/components/buttons/AppButton/types.ts
- src/ui/components/buttons/ButtonSecondary.ts
- src/ui/svg/icons/PlainMore.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31874
I have:
| iOS | Desktop - Chrome |
| :-----------: | :---: |
| <img width="520" alt="Simulator Screenshot - iPhone 15 - 2024-10-07 at 13 21 13" src="https://github.com/user-attachments/assets/5f00a40f-d130-4474-8dc7-054153a9071e" /> | <img width="1022" alt="Capture d’écran 2024-10-07 à 13 23 59" src="https://github.com/user-attachments/assets/421554b0-fc37-415a-9997-2911a14cb30a"> |
> (PC-31874) feat(Offer): Create `See more` button on new XP Cine block

- src/ui/components/tiles/HorizontalTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32245
I have:
| iOS              |<img width="436" alt="Capture d’écran 2024-10-08 à 11 01 51" src="https://github.com/user-attachments/assets/19dd5113-ffd1-47ea-833e-0ad0d6486831"> <img width="450" alt="Capture d’écran 2024-10-08 à 11 02 14" src="https://github.com/user-attachments/assets/b8c4bf78-c0ab-4f63-99c3-dd970b544db9">|![Capture d’écran 2024-10-08 à 11 31 52](https://github.com/user-attachments/assets/9241afd2-e88e-42e0-828d-ba084e31d109) ![Capture d’écran 2024-10-08 à 11 31 …
> (PC-32245) fix(ui): ellipsis for offer name on HorizontalTile

- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/components/OfferReactionSection/OfferReactionSection.native.test.tsx
- src/features/offer/components/OfferReactionSection/OfferReactionSection.tsx
- src/features/offer/components/OfferReactions/OfferReactions.native.test.tsx
- src/features/offer/components/OfferReactions/OfferReactions.tsx
- src/features/reactions/components/ReactionChoiceModalBodyWithValidation/ReactionChoiceModalBodyWithValidation.tsx
- src/features/reactions/components/ReactionChoiceValidation/ReactionChoiceValidation.native.test.tsx
- src/features/reactions/components/ReactionChoiceValidation/ReactionChoiceValidation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29416
I have:
| Desktop - Chrome |               |![Capture d’écran 2024-10-08 à 14 51 33](https://github.com/user-attachments/assets/81dfe4aa-e4b7-4596-b506-4aa5f6c3a8e3)| …
> (PC-29416) feat(ReactionChoiceValidation): add reactions buttons to Offer

- __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx.native-snap
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30876
I have:
> (PC-30876) feat(SetPhoneNumberWithoutValidation): Disable submit when phone is empty

- src/features/home/api/useHomeRecommendedOffers.ts
- src/libs/recommendation/useHomeRecommendedIdsQuery.native.test.ts
- src/libs/recommendation/useHomeRecommendedIdsQuery.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32015
I have:
> (PC-32015) fix(reco): query reco only if focus and internet is reachable

- src/features/culturalSurvey/helpers/useGetCulturalSurveyContent.ts
- src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx
- src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
- src/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.native.test.tsx
- src/features/culturalSurvey/pages/CulturalSurveyQuestions.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32319
I have:
| Phone - Chrome   |  <img width="374" alt="Capture d’écran 2024-10-14 à 14 42 03" src="https://github.com/user-attachments/assets/5b15ae50-3ad0-47bb-9bc2-ad98bc63d487">   |  <img width="376" alt="Capture d’écran 2024-10-14 à 14 34 54" src="https://github.com/user-attachments/assets/c5d37620-1aec-4f5a-bf57-0e49948b9abc">  |
[1]: …
> (PC-32319) feat(culturalSurvey): adapt CTA wording in Cultural Survey

- src/features/auth/components/SSOButton/SSOButton.native.test.tsx
- src/features/auth/pages/login/Login.native.test.tsx
- src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx
- src/features/auth/pages/signup/AccountCreated/AccountCreated.web.test.tsx
- src/features/auth/pages/signup/SetEmail/SetEmail.native.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.web.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryRequestSent.native.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryRequestSent.web.test.tsx
- src/features/navigation/RootNavigator/useInitialScreenConfig.native.test.tsx
- src/features/navigation/RootNavigator/useInitialScreenConfig.web.test.tsx
- src/shared/culturalSurvey/useShouldShowCulturalSurvey.native.test.ts
- src/shared/culturalSurvey/useShouldShowCulturalSurvey.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32380
I have:
> (PC-32380) feat(culturalSurvey): hide cultural survey after activation when in identity check

- src/features/bookings/pages/Bookings/Bookings.native.test.tsx
- src/features/bookings/pages/Bookings/Bookings.tsx
- src/features/bookings/pages/Bookings/Bookings.web.test.tsx
- src/features/venue/components/TabLayout/InfoTab.tsx
- src/features/venue/components/TabLayout/TabLayout.native.test.tsx
- src/features/venue/components/TabLayout/TabLayout.tsx
- src/features/venue/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32419
I have:
| iOS              |<img width="298" alt="Capture d’écran 2024-10-16 à 12 41 43" src="https://github.com/user-attachments/assets/efe39eea-5bb0-49c7-8895-556235a0288b">|![Capture d’écran 2024-10-16 à 13 03 51](https://github.com/user-attachments/assets/ce90c128-fa2a-439a-8884-63f085fc37e7)|
| Android          |               |![Capture d’écran 2024-10-16 à 13 05 12](https://github.com/user-attachments/assets/2bbdcf2d-0c4f-4088-af99-d65238a15a6e)|
| Phone - Chrome   |               |<img width="213" …
> (PC-32419) feat(booking): display a pastille in ended booking tab when user has bookings without reaction

- ios/PassCulture.xcodeproj/project.pbxproj
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31573
One of the things that caught my attention during my first hour of investigation, is that the Debug Symbols were being uploaded regularly and then suddenly, 14 months ago, they stopped.
_Please note: I chose to ignore the 3 latest debug files in march as they appear out of nowhere (my guess is that they were manually uploaded). Ignoring those 3 latest one in march, debug files were uploaded several times a week (probably during deploys of releases)._
14 months ago seems to coincide exactly with the moment at which `sentry/react-native` was updated ([from 4.2.2 to 5.3.0](https://github.com/getsentry/sentry-react-native/compare/4.2.2...5.3.0)). 
When looking in the breaking changes to rn-sentry 5:
The …
> (PC-31573) fix(sentry): usage of sentry-cli changed in 5.x.x

- package.json
- yarn.lock
Link to JIRA ticket: [passculture.atlassian.net/browse/PC-31728](https://passculture.atlassian.net/browse/PC-31728)
Bumps [workbox-navigation](https://developer.chrome.com/docs/workbox/modules/workbox-navigation-preload?hl=fr) from 8.7.0 to 9.14.1.
> (PC-31728) chore(deps): Bump workbox-navigation-preload from 6.1.5 7.1.0

- .github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml
- .github/workflows/dev_on_dispatch_service_worker_test.yml
- .github/workflows/dev_on_pull_request_reassure.yml
- .github/workflows/dev_on_pull_request_title_checker.yml
- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_check_folder_change.yml
- .github/workflows/dev_on_workflow_check_proxy_version.yml
- .github/workflows/dev_on_workflow_chromatic.yml
- .github/workflows/dev_on_workflow_environment_android_deploy.yml
- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- .github/workflows/dev_on_workflow_environment_soft_deploy.yml
- .github/workflows/dev_on_workflow_install.yml
- .github/workflows/dev_on_workflow_linter_ts.yml
- .github/workflows/dev_on_workflow_tester.yml
- .github/workflows/dev_on_workflow_ts_noUncheckedIndexedAccess.yml
- .github/workflows/dev_on_workflow_ts_prune.yml
- .github/workflows/dev_on_workflow_update_jira_issues.yml
- .github/workflows/dev_on_workflow_web_deploy.yml
- .github/workflows/dev_on_workflow_web_proxy_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32458
I have:
> (PC-32458) chore(pipeline): notify either it worked or failed

- src/features/offer/components/MoviesScreeningCalendar/MovieCalendarContext.tsx
- src/features/offer/components/MoviesScreeningCalendar/MovieOfferTile.tsx
- src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
- src/features/offer/components/MoviesScreeningCalendar/NextScreeningButton.tsx
- src/features/offer/components/MoviesScreeningCalendar/VenueCalendar.tsx
- src/features/offer/components/MoviesScreeningCalendar/hook/useMoviesScreeningsList.native.test.ts
- src/features/offer/components/MoviesScreeningCalendar/hook/useMoviesScreeningsList.ts
- src/features/offer/components/MoviesScreeningCalendar/moviesOffer.builder.ts
- src/features/offer/components/MoviesScreeningCalendar/offersStockResponse.builder.ts
- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/components/OfferEventCardList/OfferEventCardList.tsx
- src/features/offer/components/OfferNewXPCine/CineBlock.native.test.tsx
- src/features/offer/components/OfferNewXPCine/CineBlock.tsx
- src/features/offer/components/OfferNewXPCine/OfferNewXPCineBlock.native.test.tsx
- src/features/offer/components/OfferNewXPCine/OfferNewXPCineBlock.tsx
- src/features/offer/components/OfferNewXPCine/OfferNewXPCineContent.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.native.test.ts
- src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.ts
- src/features/venue/components/VenueContent/VenueContent.tsx
- src/ui/components/anchor/AnchorContext.tsx
- src/ui/components/anchor/anchor-name.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32301
I have:
> (PC-32301) feat(XPCine): add next movie feature

- .github/workflows/dev_on_workflow_environment_android_deploy.yml
- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- .github/workflows/dev_on_workflow_environment_soft_deploy.yml
- .github/workflows/dev_on_workflow_web_deploy.yml
- .github/workflows/dev_on_workflow_web_proxy_deploy.yml
> (PC-32510) chore(pipeline): slack message only on failure or success

- src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.native.test.tsx
- src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.tsx
- src/features/search/fixtures/autocompleteHits.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32585
I have:
| Desktop - Chrome | <img width="216" src="https://github.com/user-attachments/assets/c0738ad7-5010-4ff4-bd16-7c5d302b9481" alt="" /> | <img width="216" alt="Capture d’écran 2024-10-21 à 17 51 57" src="https://github.com/user-attachments/assets/b437db5b-889e-4b84-9b48-ac4f94066d28"> | …
> (PC-32585) fix(search): bug fix on autocomplete

- __snapshots__/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.native.test.tsx.native-snap
- src/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.native.test.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32377
I have:
> (PC-32377) fix(a11y): new delete profile deletion

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/home/api/useHomeRecommendedOffers.ts
- src/features/home/components/modules/OffersModule.tsx
- src/features/home/components/modules/RecommendationModule.native.test.tsx
- src/features/home/components/modules/RecommendationModule.tsx
- src/features/home/fixtures/homepage.fixture.ts
- src/features/home/types.ts
- src/libs/contentful/adapters/modules/adaptOffersModule.ts
- src/libs/contentful/adapters/modules/adaptRecommendationModule.ts
- src/libs/contentful/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31746
I have:
| Desktop - Chrome |<video src="https://github.com/user-attachments/assets/1cfca470-5379-4713-80aa-964932cadda1"/>|<video src="https://github.com/user-attachments/assets/433ed8f0-efd4-412a-93e9-c4b81fc5b286"/>|
> (PC-31746) feat(home): add hybrid playlist with recommendation

- src/features/bookings/components/OnGoingBookingsList.native.test.tsx
- src/features/bookings/components/OnGoingBookingsList.tsx
- src/features/bookings/pages/Bookings/Bookings.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.tsx
- src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32559
I have:
> (PC-32559) fix(EndedBookings): legacy endedBooking not working because of a refacto

- doc/development/tests/unit-test/component-test.md
- doc/development/tests/unit-test/general-guidelines.md
> (BSR) docs(test): userEvent using in native tests

- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/fixtures/mockSubcategory.ts
- src/features/offer/helpers/useOfferBatchTracking/useOfferBatchTracking.test.ts
- src/features/offer/helpers/useOfferBatchTracking/useOfferBatchTracking.ts
- src/libs/subcategories/fixtures/mappings.ts
- src/libs/subcategories/mappings.ts
- src/libs/subcategories/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32719
I have:
> (PC-32719) refactor(survey): use subcategories instead of native categories for survey trackers

- src/features/venueMap/helpers/venueMapCluster/getClusterColorByDominantVenueType.test.ts
- src/features/venueMap/helpers/venueMapCluster/getClusterColorByDominantVenueType.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32738
I have:
| iOS              |![Capture d’écran 2024-10-29 à 17 38 46](https://github.com/user-attachments/assets/2ee0ef1c-72d7-4eda-b84d-7629fb9803d8) ![Capture d’écran 2024-10-29 à 17 38 52](https://github.com/user-attachments/assets/4ba722af-aa73-488c-8323-6b9dda12320e)|![Capture d’écran 2024-10-29 à 17 39 39](https://github.com/user-attachments/assets/ecac23e1-d678-4524-923b-904e1c4aa199) ![Capture d’écran 2024-10-29 à 17 38 52](https://github.com/user-attachments/assets/4060326c-2591-409c-8266-ae2c78a55a2b) …
> (PC-32738) fix(venueMap): fix cluster confusion between cultural center and distribution store

- src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.native.test.ts
- src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.ts
- src/libs/algolia/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32766
I have:
| Desktop - Chrome | <img width="1024" alt="Capture d’écran 2024-10-30 à 18 17 07" src="https://github.com/user-attachments/assets/2c471ae9-4d59-4a5f-a004-a474aa42bc74"> | <img width="1022" alt="Capture d’écran 2024-10-30 à 18 15 49" src="https://github.com/user-attachments/assets/1fc240cf-f39a-433f-9ec0-d50cc71eba91"> |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v …
> (PC-32766) fix(Offer): fix xp cine offers when offer has no allocineId

- src/features/home/pages/ThematicHome.native.test.tsx
- src/features/home/pages/ThematicHome.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32744
I have:
> (PC-32744) fix(ThematicHome): selectedLocationMode is Everywhere when app is first oppened

- .eslintrc.js
- eslint-custom-rules/no-currency-symbols.js
- eslint-custom-rules/no-currency-symbols.test.js
- eslint-local-rules.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32705
I have:
| Platform          | problems |
| eslint              |     <img width="911" alt="Capture d’écran 2024-10-31 à 16 22 08" src="https://github.com/user-attachments/assets/6719ae9a-e79e-48cf-8b80-1d246af0e4be">   |
> (PC-32705) feat(NC): add no-currency-symbols eslint rule

- src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx
- src/features/search/components/SearchListHeader/SearchListHeader.tsx
- src/features/search/helpers/getSearchVenuePlaylistTitle/getSearchVenuePlaylistTitle.test.ts
- src/features/search/helpers/getSearchVenuePlaylistTitle/getSearchVenuePlaylistTitle.ts
- src/features/search/pages/Search/SearchN1/SearchN1.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32721
I have:
> (PC-32721) feat(venuePlalists): location indication comes from code instead of Algolia's rules

- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32617
Navigation vers la page du lieu sélectionné quand on force le swipe vers le haut sur la bottom-sheet dans la carte
I have:
iOS
https://github.com/user-attachments/assets/bc7ae1b4-495f-4371-8ca8-717d0aae3d8e
Android
https://github.com/user-attachments/assets/0451334b-77ad-4a83-af3f-799bef047d4b
> (PC-32617) feat(venueMap): navigate to venue page when fling on bottom-sheet

- src/ui/components/VenuePreview/VenuePreview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32810
I have:
| iOS              |               |![Capture d’écran 2024-11-04 à 16 51 33](https://github.com/user-attachments/assets/cef7d840-afa2-4d65-b2af-9d5142d94e93)|
| Desktop - Chrome |![Capture d’écran 2024-10-31 à 16 23 58](https://github.com/user-attachments/assets/c271616a-705f-43f4-b3b5-b9c8b9967f6a)|![Capture d’écran 2024-11-04 à 17 03 20](https://github.com/user-attachments/assets/a863099c-eb8d-4028-bfb4-2b440cadd7 …
> (PC-32810) fix(VenuePreview): correct UI

- yarn.lock
When running yarn install, I always get this change
> (BSR) chore(yarnLock): update lodash

- .gitignore
- doc/installation/iOS.md
- ios/PassCulture.xcodeproj/project.pbxproj
- ios/PassCulture/Firebase/README.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32834
Permet de builder l'app pour n'importe quel environnement sur ios sans devoir mettre à jour le fichier `GoogleService-Info.plist`
I have:
> (PC-32834) chore(ios): automatically get firebase config from env when building 

- src/features/search/pages/Search/ThematicSearch/ThematicSearch.tsx
> (BSR) fix(ThematicSearch): remove duplicate useEffect causing crashes

- src/features/offer/components/OfferVenueBlock/OfferVenueBlock.native.test.tsx
- src/features/offer/components/OfferVenueBlock/OfferVenueBlock.tsx
- src/features/offer/components/OfferVenueBlock/VenueBlock.tsx
- src/features/offer/components/OfferVenueBlock/useVenueBlock.native.test.ts
- src/features/offer/components/OfferVenueBlock/useVenueBlock.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32947
I have:
> (PC-32947) feat(VenueBlock): remove link if offer and venue address different

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
After the firebase split we need to give the right plist path in our GA workflow
> (BSR) fix(CI): set plist path output with correct env

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- .gitignore
- doc/installation/iOS.md
- ios/PassCulture.xcodeproj/project.pbxproj
- ios/PassCulture/Firebase/README.md
- Revert "(BSR) fix(CI): set plist path output with correct env" (commit d837e92ae7315a16bcf43618b5a55457a1fe706f).
- Revert "(PC-32834) chore: when building ios automatically get firebase config from env (#7141)".(This reverts commit 02d35828e571d7b95aa319aff530b59844ab02b2).
> (BSR) fix(CI): revert ios deploy config 

- .vscode/settings.json
j'en ai marre de faire kicker de Live Share parce qu'il y a une erreur de raccourci clavier (CMD+Q est juste à coté de CMD+S)
> (BSR) chore(vscode): confirm before closing VSCode

- doc/installation/Android.md
- scripts/generate_api_client_silicon.sh
Lorsque j'ai voulu suivre la [doc pour mettre à jour l'API avec le proxy](https://www.notion.so/passcultureapp/G-n-rer-les-sch-mas-d-API-83c8f44b019a436798995f9b8294ae2b?cookie_sync_completed=true), j'ai eu un problème de version de Java qui était dans mon .zshrc, car j'avais suivis la doc d'installation d'Android. 
I have:
> (BSR) docs(andorid): update android doc

- src/features/home/components/banners/GeolocationBanner.native.test.tsx
- src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.native.test.tsx
- src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/internal/marketingAndCommunication/config/deeplinksExportConfig.ts
- src/features/location/components/LocationSearchWidget.native.test.tsx
- src/features/location/components/LocationWidgetDesktop.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/helpers/useSync/useSync.native.test.ts
- src/features/search/helpers/useSync/useSync.ts
- src/features/search/pages/SearchResults/SearchResults.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32582
I have:
https://github.com/user-attachments/assets/0297ccc9-85ef-4852-ac3c-ff6eb8db4d8c
> (PC-32582) feat(deeplinks): AROUND-ME with all radius replace EVERYWHERE in SearchResults deeplinks

- src/features/bookings/helpers/useBookingsAwaitingReaction.test.tsx
- src/features/bookings/helpers/useBookingsAwaitingReaction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33140
I have:
> (PC-33140) fix(booking): no notification when booking without reaction cancelled

- src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx
- src/ui/components/SocialNetworkCard.tsx
- src/ui/components/touchableLink/TouchableLink.native.test.tsx
- src/ui/components/touchableLink/TouchableLink.tsx
- src/ui/components/touchableLink/TouchableLink.web.test.tsx
- src/ui/components/touchableLink/types.ts
- vite.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32805
I have:
<details>
Test specific:
</details>
> (PC-32805) fix(TouchableLink): add default debounce delay to avoid press spamming

- src/features/home/components/helpers/filterBookingsWithoutReaction/filterBookingsWithoutReaction.test.ts
- src/features/home/components/helpers/filterBookingsWithoutReaction/filterBookingsWithoutReaction.ts
- src/features/home/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33155
I have:
<details> …
> (PC-33155) fix(IncomingReactionModalContainer): display the modal 31 one days later for most of categories (except SEANCE_CINEMA)

- src/features/offer/components/OfferContent/OfferContent.web.test.tsx
- src/features/offer/components/OfferHeader/OfferHeader.web.test.tsx
- src/features/offer/components/OfferImageCarousel/OfferImageCarousel.web.test.tsx
- src/features/offer/components/OfferImageCarouselPagination/OfferImageCarouselPagination.web.test.tsx
- src/features/offer/components/OfferImageContainer/OfferImageContainer.web.test.tsx
- src/tests/utils/web.tsx
I have:
<details>
Test specific:
</details>
> (BSR) test(web): implements user-events for web + update some tests

- __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.stories.tsx
- src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
- src/features/venueMap/pages/VenueMap/VenueMapBase.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33184
I have:
<details>
Test specific:
</details>
> (PC-33184) refactor(filter): custom icon for SingleFilterButton

- __snapshots__/features/profile/pages/Achievements/Achievements.native.test.tsx.native-snap
- src/features/profile/components/Achievements/Badge.tsx
- src/features/profile/components/Modals/AchievementDetailsModal.tsx
- src/features/profile/pages/Achievements/Achievements.tsx
- src/features/profile/pages/Achievements/useAchievements.native.test.ts
- src/features/profile/pages/Achievements/useAchievements.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33066
I have:
| iOS              |               |   ![image](https://github.com/user-attachments/assets/cddde7f3-9030-4eda-ba0d-0e1b13c5793c)    ![image](https://github.com/user-attachments/assets/6aab518b-b8a8-4206-8ccf-4ced06f9da7d)|
[2]: …
> (PC-33066) feat(Achievements): hide locked badge title

- src/features/venueMap/components/FilterBannerContainer/FilterCategoriesBannerContainer.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/features/venueMap/hook/useVenueMapFilters.native.test.ts
- src/features/venueMap/hook/useVenueMapFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33153
I have:
iOS :
https://github.com/user-attachments/assets/086d7b1f-d9d1-478b-a3af-d0027c869218
<details>
Test specific:
- When you see a local variable that …
> (PC-33153) feat(VenueMapView): toggle filter and update result from it

- __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
- src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.tsx
- src/features/venueMap/components/FilterBannerContainer/FilterCategoriesBannerContainer.tsx
Fix sur le SingleFilterButton qui faisait planter la page de recherche côté web
I have:
<details>
Test specific: …
> (BSR) fix(filter): SingleFilterButton accessiblity props

- src/features/offer/components/MoviesScreeningCalendar/NextScreeningButton.tsx
- src/ui/components/banners/GenericColoredBanner.tsx
- src/ui/components/banners/InfoBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33149
I have:
| Android          | <img src="https://github.com/user-attachments/assets/2e8cba5a-97bb-4b19-a3ae-c2ebf1d3d43f" />             | <img src="https://github.com/user-attachments/assets/106f1973-c79c-4fd8-bd3c-d7932bcb79e7" /> |
<details>
- Remove …
> (PC-33149) fix(CineButton): center on android

- src/features/offer/components/OfferCine/CineContentCTA.tsx
- src/features/offer/components/OfferCine/OfferCineBlock.tsx
- src/features/offer/components/OfferContent/OfferCTAProvider.tsx
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/features/venue/components/VenueContent/VenueContent.native.test.tsx
- src/features/venue/components/VenueContent/VenueContent.tsx
- src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx
- src/features/venue/components/VenueOffers/VenueOffers.tsx
- src/features/venue/pages/Venue/Venue.tsx
- src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
- src/libs/firebase/remoteConfig/remoteConfig.constants.ts
- src/libs/firebase/remoteConfig/remoteConfig.types.ts
- src/ui/components/anchor/AnchorContext.tsx
- src/ui/components/anchor/anchor-name.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32111
I have:
https://github.com/user-attachments/assets/f10cea22-532f-4ac6-b0db-74901e0e301a
> (PC-32111) feat(XPCine): add a button anchor to access to screenings

- doc/installation/setup.md
- flake.nix
this was a false good idea
the Nix used is one in the daemon which is globally installed
having `nix` here can make confusions about which version is used
> (BSR) chore(setup): remove local Nix

- devbox.lock
- flake.lock
Partially Revert "(BSR) chore(deps): update tools (#7200)"
This reverts commit 332e3556bc52b111b5b3ccb2526ad26df82d0e59.
For some reasons, with the newer version when running the following command
```sh
yarn ios:testing
```
It outputs the following error
```txt
yarn run v1.22.22
$ yarn ios --scheme PassCulture-Testing
$ ./scripts/check_xcode_version.sh
warning: unhandled Target key DefaultVariant
warning: unhandled Target key SupportedTargets
warning: unhandled Target key VersionMap
warning: unhandled Target key Variants
warning: unhandled Target key DebuggerOptions
warning: unhandled Product key iOSSupportVersion
warning: unhandled Target key DefaultVariant
warning: unhandled Target key SupportedTargets
warning: unhandled Target key VersionMap
warning: unhandled Target key Variants …
```
> (BSR) chore(ios): fix CLI by using older DevBox version

- src/features/navigation/RootNavigator/RootNavigator.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33290
I have:
Avant :
https://github.com/user-attachments/assets/a8601c2c-f656-42f6-8a8e-e566e70315c8
https://github.com/user-attachments/assets/f2956925-5a84-49c5-9554-555d5568faa7
Après :
https://github.com/user-attachments/assets/46639cf0-e3c8-4287-82a2-9c2b8c907878
https://github.com/user-attachments/assets/b597415d-cb49-4e6d-8dce-14c761f044f4
<details>
- Remove non-null …
> (PC-33290) feat(venueMap): preserve safe area in venue map filters modal in Android

- __snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap
- src/features/internal/marketingAndCommunication/atoms/OfferCategoryChoices.native.test.tsx
- src/features/internal/marketingAndCommunication/atoms/OfferCategoryChoices.tsx
- src/features/internal/marketingAndCommunication/atoms/OfferNativeCategoryChoices.native.test.tsx
- src/features/internal/marketingAndCommunication/atoms/OfferNativeCategoryChoices.tsx
- src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.native.test.tsx
- src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
- src/features/internal/marketingAndCommunication/config/deeplinksExportConfig.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/SearchStackNavigator/types.ts
- src/features/search/enums.ts
- src/features/search/helpers/useAvailableCategories/useAvailableCategories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32644
I have:
https://github.com/user-attachments/assets/a7879761-4faa-4799-bc13-b4d75d6cff5e
<details>
Test specific:
- When you see a local variable that is …
> (PC-32644) feat(deeplinks): add ThematicSearch pages

- __snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap
- __snapshots__/features/auth/pages/signup/AcceptCgu/AcceptCgu.native.test.tsx.native-snap
- __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
- __snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap
- src/ui/components/inputs/Checkbox/Checkbox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33337
I have:
| iOS              |               |  <img width="346" alt="Capture d’écran 2024-11-28 à 18 46 02" src="https://github.com/user-attachments/assets/5a27596c-e936-4c1d-b3e5-50ffaedd26de"> <img width="344" alt="Capture d’écran 2024-11-28 à 18 45 34" src="https://github.com/user-attachments/assets/fbb34c98-4eef-40f5-88c5-26112f2b6af2"> |
[1]: …
> (PC-33337) feat(ui): fix flex Checkbox component

- src/shared/currency/useGetCurrencyToDisplay.native.test.ts
- src/shared/currency/useGetCurrencyToDisplay.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32821
I have:
| Phone - Chrome   |               |  ![Capture d’écran 2024-11-29 à 18 45 04](https://github.com/user-attachments/assets/b7f4ef03-ae6c-46fd-9492-34bbb9d64706) ![Capture d’écran 2024-11-29 à 18 43 02](https://github.com/user-attachments/assets/c92a7de9-242c-4b27-8929-dfeee34f5993) ![Capture d’écran 2024-11-29 à 18 43 30](https://github.com/user-attachments/assets/01e6c7e7-68b1-46c3-828d-5283c978e24a)  |
| Desktop - …
> (PC-32821) feat(NC): update conditions in useGetCurrencyToDisplay

- src/features/navigation/RootNavigator/types.ts
- src/features/profile/components/Achievements/BadgeBanner.tsx
- src/features/profile/components/Modals/AchievementSuccessModal.tsx
- src/features/profile/pages/Achievements/Achievements.tsx
- src/features/profile/pages/Achievements/useAchievements.native.test.ts
- src/features/profile/pages/Achievements/useAchievements.ts
- src/features/profile/pages/Profile.native.test.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32910
I have:
<details> …
> (PC-32910) feat(Achievements): add achievements tracker

- .envrc
- scripts/ensure_nix_use_certificate.sh
- scripts/is_proxy_enabled.sh
- scripts/load_certificate.sh
- scripts/start_android_emulator_with_certificate.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32488
pour tester, il faut
1. aller sur la branche
```sh
git fetch
git switch --detach origin/proxy_disabled
```
1. supprimer ses node_modules et/ou pods
```sh
rm -rf node_modules ios/Pods
```
1. réactiver direnv qui va essayer de réinstaller les dépendances vu que les dossiers sont absents
```sh
direnv allow
```
et tout devrait fonctionner normalement
> (PC-32488) chore(proxy): load certificate only when proxy is enabled

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/home/components/modules/OffersModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33308
I have:
| Desktop - Chrome | <img width="1027" alt="Capture d’écran 2024-12-02 à 13 06 20" src="https://github.com/user-attachments/assets/d292abfe-d8cc-4d46-89aa-580ef872937a"> | <img width="1034" alt="Capture d’écran 2024-12-02 à 13 05 18" src="https://github.com/user-attachments/assets/49734613-bd68-4941-a3e3-610c1a2ee77e"> |
> (PC-33308) fix(home): use releaseDate on home playlists

- src/libs/styled/useComputedTheme.ts
- src/ui/components/NewOfferCaption.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33411
I have:
Avant : 
Après : 
<details>
Test specific:
- Prefer `user` to …
> (PC-33411) fix(OfferTile): fix UI max height on Offer tile

- scripts/start_android_emulator_with_certificate.sh
> (BSR) fix(setup): start android from CLI

- package.json
- server/package.json
- server/yarn.lock
- yarn.lock
Versions of the package semver before 7.5.2 on the 7.x branch, before 6.3.1 on the 6.x branch, and all other versions before 5.7.2 are vulnerable to Regular Expression Denial of Service (ReDoS) via the function new Range, when untrusted user data is provided as a range.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33297
> (PC-33297) chore(deps): bump semver

- src/features/search/pages/ThematicSearch/Cinema/CinemaPlaylist.tsx
- src/features/search/pages/ThematicSearch/Films/FilmsPlaylist.tsx
- src/features/search/pages/ThematicSearch/Music/MusicPlaylist.tsx
- src/features/search/pages/ThematicSearch/api/fetchFilmsOffers.native.test.ts
- src/features/search/pages/ThematicSearch/api/fetchFilmsOffers.ts
- src/features/search/pages/ThematicSearch/api/fetchMusicOffers.native.test.ts
- src/features/search/pages/ThematicSearch/api/fetchMusicOffers.ts
- src/features/search/pages/ThematicSearch/api/useThematicSearchPlaylists.native.test.ts
- src/features/search/pages/ThematicSearch/api/useThematicSearchPlaylists.ts
- src/tests/mockBuilder.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33447
I have:
| Desktop - Chrome |<img width="1038" alt="Capture d’écran 2024-12-06 à 18 04 38" src="https://github.com/user-attachments/assets/0f62776c-3397-48dc-8373-87cf113fd6df"> | <img width="1032" alt="Capture d’écran 2024-12-06 à 18 04 17" src="https://github.com/user-attachments/assets/f6284d4d-36ed-48e9-9c9d-4ce4a24c741c"> |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v= …
> (PC-33447) feat(ThematicSearch): update playlist order and remove offers without images

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/accessibility/components/AccessibilityFiltersModal.tsx
- src/features/auth/pages/signup/SignupForm.tsx
I have:
<details>
Test specific:
</details>
> (BSR) refactor(auth): remove some @ts-expect-error

- src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
- src/features/bookOffer/pages/BookingOfferModal.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33181
I have:
| Platform         | Mobile | Web |
| Result |<img width="606" alt="Capture d’écran 2024-12-09 à 10 20 09" src="https://github.com/user-attachments/assets/f19c87dd-50d3-4f6d-a891-4b9030a32c00">|<img width="1512" alt="Capture d’écran 2024-12-09 à 10 12 07" src="https://github.com/user-attachments/assets/0eefa11c-7cd6-4524-ad5c-3cd81f41a616">|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d2 …
> (PC-33181) feat(cinema): add tracker for screening ab test

- src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.native.test.tsx
- src/features/search/helpers/categoriesHelpers/mapping-tree.ts
- src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx
- src/libs/subcategories/placeholderData.ts
- src/ui/components/buttons/SubcategoryButton/SubcategoryButtonListWrapper.native.test.tsx
- src/ui/components/buttons/SubcategoryButton/SubcategoryButtonListWrapper.tsx
- src/ui/components/tiles/HorizontalTile.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32251
I have:
no UI change :
avant :
après : 
<details>
Test specific:
- Prefer …
> (PC-32251) refactor(SubcategoryButtonListWrapper): remove hard coded nativeCategory label

- ios/PassCulture/Info.plist
- server/src/app.ts
- server/src/middlewares/tests/universalLinksMiddleware.test.ts
- server/src/middlewares/universalLinksMiddleware.ts
- src/features/navigation/RootNavigator/linking/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33435
- Ajout d'un middleware côté serveur pour gérer la redirection des appels venant d'une app Instagram / iOS
- Fix sur les URL Schemes côté react-navigation
I have:
<details>
- Remove non-null assertion operators (just like other type assertions, this doesn’t change the runtime behavior of your code, so it’s important to only use `!` when you know that the value can’t be `null` …
> (PC-33435) fix(ios): universal links with instagram

- src/features/profile/components/Modals/AchievementSuccessModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33372
I have:
<details>
If you …
> (PC-33372) fix(achievement): removed confetti

- src/libs/styled/useComputedTheme.ts
> (BSR) fix(tile): Remove 'px' for parsing

- .github/workflows/dev_on_workflow_environment_soft_deploy.yml
- .github/workflows/dev_on_workflow_run_e2e_android.yml
- .github/workflows/dev_on_workflow_web_deploy.yml
- .github/workflows/dev_on_workflow_web_proxy_deploy.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31397
I have:
<details>
If you …
> (PC-31397) fix(workflows): add corepack enable to use the proper yarn version

- src/features/profile/components/Header/ProfileHeader/ProfileHeader.tsx
- src/features/profile/components/Modals/useShouldShowAchievementSuccessModal.native.test.tsx
- src/features/profile/components/Modals/useShouldShowAchievementSuccessModal.tsx
- src/features/profile/pages/Profile.native.test.tsx
- src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
- src/libs/firebase/remoteConfig/remoteConfig.constants.ts
- src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33311
I have:
<details>
If you …
> (PC-33311) feat(achievements): added remote config

- src/ui/components/touchableLink/InternalTouchableLink.native.test.tsx
- src/ui/components/touchableLink/InternalTouchableLink.tsx
- src/ui/components/touchableLink/TouchableLink.native.test.tsx
- src/ui/components/touchableLink/TouchableLink.tsx
Pour éviter le spam de press sur les tuiles d'offres en mode push
I have:
<details>
If you can't …
> (BSR) fix(touchableLink): use throttle instead of debounce

- package.json
- yarn.lock
> (BSR) chore(husky): add to our dependencies

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- .gitignore
- doc/installation/iOS.md
- ios/PassCulture.xcodeproj/project.pbxproj
- ios/PassCulture/Firebase/README.md
This reverts commit 6513f9a6617d77d5068eb92ceb5d78b49cf923f9.
I have:
<details> …
> (BSR) feat(firebase): set env dynamic firebase ios config files - Revert

- __snapshots__/features/tutorial/pages/AgeSelection.native.test.tsx.native-snap
- src/features/tutorial/pages/AgeSelection.native.test.tsx
- src/features/tutorial/pages/AgeSelection.tsx
- src/features/tutorial/pages/AgeSelection.web.test.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33471
I have:
| iOS              |  ![image](https://github.com/user-attachments/assets/249bd2a5-98f6-4b88-ad75-cea87194b7c2) | ![image](https://github.com/user-attachments/assets/03607fca-352c-4112-a6d3-8dd9a203065d) |
| Android          |  ![image](https://github.com/user-attachments/assets/56c605c4-0f3f-45b7-9133-afa5ca43538c) |       |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887 …
> (PC-33471) feat(passForAll): AgeSelectionScreen

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/navigation/SearchStackNavigator/routes.ts
- src/features/navigation/screenParamsUtils.ts
- src/features/search/api/useSearchResults/useSearchResults.native.test.ts
- src/features/search/api/useSearchResults/useSearchResults.ts
- src/features/search/components/SearchBox/SearchBox.native.test.tsx
- src/features/search/components/SearchBox/SearchBox.tsx
- src/features/search/helpers/useNavigateToSearch/useNavigateToSearch.ts
- src/features/search/types.ts
- src/libs/algolia/doAlgoliaRedirect.native.test.ts
- src/libs/algolia/doAlgoliaRedirect.ts
- src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.ts
- src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
- src/libs/firebase/remoteConfig/remoteConfig.constants.ts
- src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30293
I have:
| Desktop - Chrome |               | <video src="https://github.com/user-attachments/assets/72e9a3d3-2e2a-4860-804d-f9e38913029f" /> |
<details>
- In the production code: remove type assertions with `as` (type assertions are removed …
> (PC-30293) feat(Algolia): trigger to thematic search on specific query

- __snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap
- src/features/home/components/modules/video/VideoCarouselModule.native.test.tsx
- src/features/search/components/sections/Category/Category.native.test.tsx
- src/features/search/constants.ts
- src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
- src/features/search/helpers/categoriesHelpers/mapping-tree.ts
- src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx
- src/libs/subcategories/fixtures/mappings.ts
- src/libs/subcategories/mappings.ts
- src/libs/subcategories/useSearchGroupLabel.native.test.ts
- src/libs/subcategories/useSearchGroupLabel.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33551
I have:
| Desktop - Chrome | <img width="518" alt="Capture d’écran 2024-12-14 à 23 34 46" src="https://github.com/user-attachments/assets/2005acbb-ca20-4b65-a486-abadd5169265" /> | <img width="478" alt="Capture d’écran 2024-12-14 à 23 35 27" src="https://github.com/user-attachments/assets/b90aa407-7201-4d63-9f3a-315d91116560" /> | …
> (PC-33551) fix(CategoriesModal): remove `NONE`

- src/features/home/components/modules/video/VideoCarouselModule.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/constants.ts
- src/features/venueMap/components/FilterBannerContainer/FilterBannerContainer.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.tsx
- src/features/venueMap/pages/VenueMap/VenueMapBase.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33548
Fix sur la hauteur de la map qui ne prenait pas tout l'espace disponible.
I have:
<details> …
> (PC-33548) fix(venueMap): VenueMap layout + centering method

- src/features/home/api/useActivationBanner.native.test.ts
- src/features/identityCheck/api/useGetStepperInfo.native.test.ts
- src/features/identityCheck/api/useGetStepperInfo.ts
- src/features/identityCheck/pages/identification/ubble/IdentityCheckEnd.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33369
I have:
| Desktop - Chrome |               |   <img width="1728" alt="Capture d’écran 2024-12-18 à 12 03 04" src="https://github.com/user-attachments/assets/4c854c15-cffd-461f-9679-4d6b4ab97901" /> | …
> (PC-33369) feat(NC): add enable: isLoggedIn in useGetStepperInfo

- src/libs/algolia/doAlgoliaRedirect.native.test.ts
- src/libs/algolia/doAlgoliaRedirect.ts
I have:
| Desktop - Chrome | <video src="https://github.com/user-attachments/assets/407112b8-7b61-454c-8a1d-dc0621c404f6" /> | <video src="https://github.com/user-attachments/assets/8c8178c7-916a-4535-9a76-518bb3d8ed10" /> |
<details>
- In …
> (BSR) fix(ThematicSearch): restore venue playlist after algolia redirect

- doc/development/general-info-web.md
- package.json
- src/web/SupportedBrowsersGate.tsx
- src/web/SupportedBrowsersGate.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33008
I have:
<details>
If you …
> (PC-33008) chore(config): tested browsers and updated list

- src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.test.ts
- src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.ts
… playlist
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33701
I have:
<details>
These rules apply to files that you make changes …
> (PC-33701) feat(useVenueOffersArtists): filter collective artists

- src/features/navigation/RootNavigator/linking/index.ts
Fix un bug sur ios qui affiche un écran "Page introuvable" au 1er démarrage de l'app.
I have:
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at …
> (BSR) fix(ios): screen not found at startup

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33354
I have:
<details>
If you …
> (PC-33354) chore(deps): add resolution for JSON5

- src/features/home/components/modules/categories/CategoryButton.tsx
- src/features/home/components/modules/categories/CategoryListModule.tsx
- src/features/home/components/modules/video/VideoCarouselModule.tsx
- src/features/search/components/Buttons/CategoryButton.tsx
- src/features/search/components/CategoriesListDumb/CategoriesListDumb.tsx
- src/ui/theme/colorMapping.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33484
I have:
<details> …
> (PC-33484) fix(CategoryButtonsHome): should be an InternalTouchableLink for accessibility

- __snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
- src/features/birthdayNotifications/pages/EighteenBirthday.tsx
- src/features/birthdayNotifications/pages/RecreditBirthdayNotification.tsx
- src/features/bookOffer/components/BookingInformations.native.test.tsx
- src/features/bookOffer/components/PriceLine.native.test.tsx
- src/features/bookOffer/components/PriceLine.tsx
- src/features/bookOffer/pages/BookingConfirmation.tsx
- src/features/bookings/components/BookingPropertiesSection.native.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
- src/features/profile/components/CreditInfo/CreditInfo.tsx
- src/features/tutorial/components/profileTutorial/EighteenBlockDescription.tsx
- src/libs/parsers/formatCurrencyFromCents.ts
- src/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.tsx
- src/shared/user/useDepositAmountsByAge.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33428
I have:
<details>
If you …
> (PC-33428) feat(NC): use formatCurrencyFromCents instead useFormatCurrencyFromCents

- src/features/search/pages/ThematicSearch/api/fetchCinemaOffers.native.test.ts
- src/features/search/pages/ThematicSearch/api/fetchCinemaOffers.ts
- src/features/search/pages/ThematicSearch/api/fetchFilmsOffers.native.test.ts
- src/features/search/pages/ThematicSearch/api/fetchFilmsOffers.ts
- src/features/search/pages/ThematicSearch/api/fetchMusicOffers.native.test.ts
- src/features/search/pages/ThematicSearch/api/fetchMusicOffers.ts
- src/features/search/pages/ThematicSearch/api/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33665
I have:
<details>
If you …
> (PC-33665) feat(ThematicSearch): update playlists

- __snapshots__/features/bookOffer/pages/BookingConfirmation.native.test.tsx.native-snap
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/bookOffer/components/BookDateChoice.tsx
- src/features/bookOffer/pages/BookingConfirmation.native.test.tsx
- src/features/bookOffer/pages/BookingConfirmation.tsx
- src/features/bookings/components/EndedBookingItem.native.test.tsx
- src/features/bookings/components/EndedBookingItem.tsx
- src/features/bookings/components/OnGoingBookingItem.native.test.tsx
- src/features/bookings/components/OnGoingBookingItem.tsx
- src/features/bookings/components/OnGoingBookingItem.web.test.tsx
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
- src/features/search/components/SearchSuggestions/SearchSuggestions.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
- src/libs/subcategories/fixtures/subcategoriesResponse.ts
- src/shared/location/LocationSearchInput.tsx
- src/tests/mockBuilder.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33118
I have:
<details>
If you …
> (PC-33118) feat(Booking): ViewedBookingPage tracker 

- src/ui/components/CollapsibleText/CollapsibleTextContent/CollapsibleTextContent.ios.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33764
I have:
https://github.com/user-attachments/assets/00c0e98a-32e0-4b72-90da-0fca6ddbafa9
<details>
- In the production code: remove …
> (PC-33764) fix(offer): allocine link in collapsible text (iOS only)

- .github/workflows/dev_on_workflow_linter_ts.yml
- .github/workflows/dev_on_workflow_tester.yml
The yarn-linter would often be canceled by the concurrency as the tester job was first executed, for example https://github.com/pass-culture/pass-culture-app-native/actions/runs/12630587585/job/35190784705
> (BSR) fix(CI): solve concurrency issue in GHA

- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/getCategoriesFacetFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33800
I have:
<details>
If you …
> (PC-33800) feat(contentful): add 'Musique' label for Contentful

- server/package.json
> (BSR) fix(proxy): add predeploy explicitly to deploy command

- .envrc
- scripts/get_version.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33767
I have:
<details>
If you …
> (PC-33767) fix(yarn): fix envrc

- src/cheatcodes/components/CheatcodesButtonList.tsx
- src/cheatcodes/components/CheatcodesSubscreenButtonList.tsx
- src/cheatcodes/components/LinkToScreen.tsx
- src/cheatcodes/hooks/filterAndSortCheatcodesButtons.ts
- src/cheatcodes/pages/CheatcodesMenu.tsx
- src/cheatcodes/pages/features/achievements/CheatcodesNavigationAchievements.tsx
- src/cheatcodes/pages/features/bookOffer/CheatcodesNavigationBookOffer.tsx
- src/cheatcodes/pages/features/culturalSurvey/CheatcodesNavigationCulturalSurvey.tsx
- src/cheatcodes/pages/features/home/CheatcodesNavigationHome.tsx
- src/cheatcodes/pages/features/identityCheck/CheatcodesNavigationIdentityCheck.tsx
- src/cheatcodes/pages/features/internal/CheatcodesNavigationInternal.tsx
- src/cheatcodes/pages/features/profile/CheatcodesNavigationProfile.tsx
- src/cheatcodes/pages/features/subscription/CheatcodesNavigationSubscription.tsx
- src/cheatcodes/pages/features/trustedDevice/CheatcodesNavigationTrustedDevice.tsx
- src/cheatcodes/pages/features/tutorial/CheatcodesNavigationTutorial.tsx
- src/cheatcodes/pages/others/CheatcodesNavigationAccountManagement.tsx
- src/cheatcodes/pages/others/CheatcodesNavigationErrors.tsx
- src/cheatcodes/pages/others/CheatcodesNavigationSignUp.tsx
- src/cheatcodes/types.ts
I have:
| iOS              |               |   ![Capture d’écran 2025-01-06 à 17 47 12](https://github.com/user-attachments/assets/e7d8fa40-ebec-4d09-9f01-b931892bad25)   |
| Desktop - Chrome |               |     |
> (BSR) feat(cheatcodes): add subscreens in cheatcodes search

- __snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- src/features/identityCheck/pages/identification/errors/eduConnect/NotEligibleEduConnect.tsx
- src/features/search/pages/SuggestedPlacesOrVenues/SuggestedPlaces.tsx
- src/ui/components/BulletListItem.tsx
- src/ui/components/CollapsibleText/useIsTextEllipsis.ts
- src/ui/components/CollapsibleText/useIsTextEllipsis.web.test.tsx
- src/ui/components/inputs/DropDown/DropDown.web.tsx
- src/ui/theme/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33849
I have:
<details>
If you …
> (PC-33849) refactor(TypoDS): missing typo body update and refacto 

- src/features/achievements/hooks/useShouldShowAchievementSuccessModal.native.test.ts
- src/features/achievements/hooks/useShouldShowAchievementSuccessModal.ts
- src/features/home/components/helpers/useBookingsReactionHelpers.native.test.ts
- src/features/home/components/helpers/useBookingsReactionHelpers.ts
- src/features/home/helpers/useWhichModalToShow.native.test.ts
- src/features/home/helpers/useWhichModalToShow.ts
- src/features/home/pages/Home.tsx
- src/features/home/pages/Home.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33818
I have:
<details>
If you …
> (PC-33818) fix(achievements): hook to handle bug

- src/features/identityCheck/components/modals/DMSModal.native.test.tsx
[PC-33894](https://passculture.atlassian.net/browse/PC-33894)
I have:
[PC-33894]: https://passculture.atlassian.net/browse/PC-33894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
> (PC-33894) feat(identityCheck): change tests name in DMSModal

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
> (BSR) fix(yarn): enable corepack after yarn setup

- src/features/achievements/hooks/useShouldShowAchievementSuccessModal.native.test.ts
- src/features/achievements/hooks/useShouldShowAchievementSuccessModal.ts
- src/features/home/components/helpers/useBookingsReactionHelpers.native.test.ts
- src/features/home/components/helpers/useBookingsReactionHelpers.ts
- src/features/home/helpers/useWhichModalToShow.native.test.ts
- src/features/home/helpers/useWhichModalToShow.ts
- src/features/home/pages/Home.tsx
- src/features/reactions/api/useAvailableReaction.test.ts
- src/features/reactions/api/useAvailableReaction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33882
I have:
<details>
If you …
> (PC-33882) fix(achievements): modals now wait for queries to finish

- src/features/offer/components/OfferVenueBlock/VenueBlock.tsx
- src/features/venueMap/components/VenueMapPreview/VenueMapPreview.tsx
- src/ui/components/InfoHeader/InfoHeader.stories.tsx
- src/ui/components/InfoHeader/InfoHeader.tsx
- src/ui/components/InfoHeader/ThumbnailPlaceHolder.tsx
- src/ui/components/VenueInfoHeader/VenueInfoHeader.native.test.tsx
- src/ui/components/VenueInfoHeader/VenueInfoHeader.tsx
- src/ui/components/VenuePreview/VenuePreview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33886
I have:
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be an exception or `null` generated if the type assertion is wrong). In certain cases `as const` is acceptable (for example when …
> (PC-33886) refactor(VenuePreview): Create a reusable/generic component InfoHeader

- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33781
I have:
<details>
If you …
> (PC-33781) chore(FF): remove wipAppV2SearchCategoryBlock

- scripts/dead_code_snapshot.txt
- src/features/chronicle/components/ChronicleCard/ChronicleCard.stories.tsx
- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
- src/ui/components/InfoHeader/InfoHeader.tsx
- src/ui/svg/BookClubCertification.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33887
I have:
<details> …
> (PC-33887) feat(ChronicleCard): add new component ChronicleCard

- src/features/artist/components/ArtistTopOffers/ArtistTopOffers.native.test.tsx
- src/features/artist/components/ArtistTopOffers/ArtistTopOffers.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33831
I have:
| iOS              |![Capture d’écran 2025-01-15 à 14 19 42](https://github.com/user-attachments/assets/7acc32ec-08d4-464f-b500-1c34d402c45f)|  ![Capture d’écran 2025-01-15 à 14 18 44](https://github.com/user-attachments/assets/1e7e5c5d-f9ca-4c84-b94f-6943ffae36b1)|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467d …
> (PC-33831) feat(artist): update top offers list title

- CODEOWNERS
- src/features/chronicle/components/ChroniclesHeader/ChroniclesHeader.native.test.tsx
- src/features/chronicle/components/ChroniclesHeader/ChroniclesHeader.tsx
- src/features/chronicle/components/ChroniclesWebMetaHeader/ChroniclesWebMetaHeader.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.native.test.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.tsx
- src/features/navigation/RootNavigator/routes.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/screenParamsUtils.ts
- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33893
I have:
| iOS              |![Capture d’écran 2025-01-15 à 11 02 56](https://github.com/user-attachments/assets/ca173897-8caa-453e-9566-e12094fa7fa0)|![Capture d’écran 2025-01-15 à 11 05 20](https://github.com/user-attachments/assets/d11a1604-4e30-4b6c-97ee-acc2ce48897d) ![Capture d’écran 2025-01-15 à 11 05 25](https://github.com/user-attachments/assets/98939730-7195-4a63-8b08-11c2a7f78dea) ![Capture d’écran 2025-01-15 à 11 05 33](https://github.com/user-attachments/assets/7dc2e72a-d684-4f2f-88e9-199c098fb6d1) …
> (PC-33893) feat(chronicle): add chronicle page + see all chronicles button on offer page

- src/features/search/components/SearchBox/SearchBox.native.test.tsx
- src/features/search/components/SearchBox/SearchBox.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33742
I have:
<details>
If you …
> (PC-33742) feat(SearchBox): add tracker HasSearchCinemaQuery

- src/features/cookies/helpers/useIsCookiesListUpToDate.native.test.ts
- src/features/cookies/helpers/useIsCookiesListUpToDate.ts
- src/features/cookies/pages/PrivacyPolicy.native.test.tsx
- src/features/home/components/helpers/useBookingsReactionHelpers.native.test.ts
- src/features/home/components/helpers/useBookingsReactionHelpers.ts
- src/features/home/helpers/useWhichModalToShow.native.test.ts
- src/features/home/helpers/useWhichModalToShow.ts
- src/features/home/pages/Home.tsx
- src/features/home/pages/Home.web.test.tsx
- src/features/navigation/RootNavigator/RootNavigator.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33870
I have:
<details>
If you …
> (PC-33870) feat(modals): integrate cookie check to reaction/achievement modal display logic

- src/features/bookings/components/Ticket/TicketSwiper.native.test.tsx
- src/features/bookings/components/TicketBody/SafeSeatWithQrCode/SafeSeatWithQrCode.tsx
- src/features/bookings/components/TicketBody/SafeSeatWithQrCode/useSafeSeatWithQrCode.native.test.ts
- src/features/bookings/components/TicketBody/SafeSeatWithQrCode/useSafeSeatWithQrCode.ts
- src/features/bookings/components/TicketBody/TicketBody.native.test.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33898
I have:
| iOS |![Capture d’écran 2025-01-16 à 16 12 45](https://github.com/user-attachments/assets/0f8bd91a-d8c3-4335-b859-f08e5f49bdfc)|![Simulator Screenshot - iPhone SE (3rd generation) - 2025-01-17 at 11 52 17](https://github.com/user-attachments/assets/acd324b2-3f92-4f1d-8eae-9edac3b11f79)|
<details> …
> (PC-33898) feat(SafeSeatWithQrCode): add FF

- src/features/favorites/components/Favorite.native.test.tsx
- src/features/home/components/AttachedModuleCard/AttachedOfferCard.native.test.tsx
- src/features/home/components/modules/marketing/MarketingBlockExclusivity.native.test.tsx
- src/features/home/components/modules/venues/VenueTile.native.test.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/features/offer/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx
- src/features/offer/components/OfferVenueBlock/OfferVenueBlock.native.test.tsx
- src/features/search/components/SearchVenueItems/SearchVenueItem.native.test.tsx
- src/libs/location/components/WhereSection.native.test.tsx
- src/ui/components/tiles/HorizontalOfferTile.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33565
I have:
<details>
If you …
> (PC-33565) fix(HorizontalOfferTile): flaky test

- src/features/home/components/modules/video/VideoModal.native.test.tsx
- src/features/home/components/modules/video/VideoModule.native.test.tsx
- src/features/home/components/modules/video/VideoMonoOfferTile.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33973
I have:
<details>
If you …
> (PC-33973) fix(VideoModal): remove unnecessary test

- package.json
- yarn.lock
> (PC-33363) chore(firebase): bump to 11.1.0

- src/features/venue/components/VenueOffers/VenueOffersList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33987
I have:
| iOS              | |![Capture d’écran 2025-01-16 à 18 05 11](https://github.com/user-attachments/assets/5342be2b-ad21-4cca-9b5c-6c4b96bc85fd)|
| Android          |               |<img width="407" alt="Capture d’écran 2025-01-20 à 10 02 23" src="https://github.com/user-attachments/assets/da39f8b8-85d7-4a42-888e-e5c2f936b6c1" />|
| Phone - Chrome   |               |![Capture d’écran 2025-01-16 à 18 06 21](https://github.com/user-attachments/assets/bc73385e-0fb9-4d1e-b28f-21093afad8e4)|
| Desktop - …
> (PC-33987) feat(venue): artist playlist moved higher

- __snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
- __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
- __snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- src/features/offer/components/OfferHeader/OfferHeader.tsx
- src/ui/components/headers/ContentHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34012
I have:
| iOS              |<img width="453" alt="Capture d’écran 2025-01-15 à 16 55 20" src="https://github.com/user-attachments/assets/59bcfaa2-67b2-4f9a-9935-f00676933b18" /> <img width="443" alt="Capture d’écran 2025-01-15 à 16 55 41" src="https://github.com/user-attachments/assets/5d956195-af09-42f5-afd8-2d1f949146a7" />|![Capture d’écran 2025-01-15 à 17 05 42](https://github.com/user-attachments/assets/1d39fbde-fb1b-452a-9185-1e564b117ec4) ![Capture d’écran 2025-01-15 à 17 05 …
> (PC-34012) fix(ui): 2 lines title on iOS in ContentHeader + improvements

- __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- scripts/dead_code_snapshot.txt
- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardList.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardList.web.test.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardList.web.tsx
- src/features/chronicle/components/ChronicleCardListBase/ChronicleCardListBase.native.test.tsx
- src/features/chronicle/components/ChronicleCardListBase/ChronicleCardListBase.tsx
- src/features/chronicle/constant.ts
- src/features/chronicle/fixtures/chroniclesSnap.ts
- src/features/chronicle/type.ts
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/ui/components/PassPlaylist.tsx
- src/ui/svg/BookClubCertification.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33888
I have:
<details>
If you …
> (PC-33888) feat(ChronicleCardList): add chronicle card list for mobile and web

- __snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
- src/features/offer/components/OfferImageCarousel/OfferImageCarousel.tsx
- src/features/offer/components/OfferImageContainer/OfferImageContainer.native.test.tsx
- src/features/offer/components/OfferImageContainer/OfferImageContainer.tsx
- src/features/offer/components/OfferImageContainer/OfferImageContainer.web.test.tsx
- src/features/offer/components/OfferImageContainer/OfferImageContainer.web.tsx
- src/features/offer/components/OfferImageContainer/OfferImageHeaderWrapper.tsx
- src/features/offer/components/OfferImageContainer/OfferImageRenderer.tsx
- src/features/offer/components/OfferImageWrapper/OfferImageWrapper.tsx
- src/features/offer/components/OfferImageWrapper/OfferImageWrapper.web.test.tsx
- src/ui/components/headers/HeaderWithImage.tsx
Fix sur le placeholder de l'image de preview d'une offre qui ne suit pas au scroll.
I have:
<details> …
> (BSR) fix(offer): preview image sticky position

- devbox.json
- devbox.lock
inclut le jdk17 dans nix
I have:
<details>
If you can't respect one of these rules, be sure to …
> (BSR) fix(nix): add jdk17

- .github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33727
Update mineure de la CI pour ne pas avoir `v` sans numéro de version dans route_usage_changelog
> (PC-33727) fix(ci): add testing version in route_usage_changelog

- src/features/identityCheck/pages/profile/store/addressStore.ts
- src/features/identityCheck/pages/profile/store/cityStore.ts
- src/features/identityCheck/pages/profile/store/nameStore.ts
- src/features/venueMap/store/initialVenuesStore.ts
- src/features/venueMap/store/selectedVenueStore.ts
- src/features/venueMap/store/venueTypeCodeStore.ts
- src/features/venueMap/store/venuesFilterStore.ts
- src/features/venueMap/store/venuesStore.ts
- src/libs/store/createStore.ts
- src/libs/store/store.types.ts
L'objectif de cette PR est de simplifier l'utilisation des selecteurs
Dans une fonction typescript:
```diff
const { select, selectors } = cityStore
- select(selectors.selectCity())
+ selectors.selectCity()
```
Dans un hook:
```diff
const { selectors, useStore, hooks } = cityStore
- useStore(selectors.selectCity())
+ hooks.useCity()
```
Ainsi nous pouvons écrire des tests métiers complètement découplés de React quand cela est possible et avoir des hooks auto-générés à partir des selecteurs côté React
> (BSR) feat(Zustand): Simplify selectors

- .github/workflows/dev_on_workflow_web_deploy.yml
- vite.config.js
https://github.com/vitejs/vite/issues/2433
Several people report that setting sourcemaps to false in the vite config solves the issue, but we want sourcemaps, so we will attempt to manually allocating RAM for Vite's initialization cycle.
> (BSR) fix(web): fix vite build error JavaScript heap out of memory

- src/features/home/types.ts
- src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts
- src/libs/contentful/fixtures/algoliaModules.fixture.ts
- src/libs/contentful/types.ts
Dans le cadre de  [ce ticket](https://passculture.atlassian.net/browse/PC-28834, j'avais crée un booléen dans Contentful mais nous avons finalement pris une autre direction donc j'ai supprimer le bouton sur contentful en testing et dans le code
> (BSR) refactor(Algolia): remove unused boolean

- doc/installation/Android.md
> (BSR) docs(java): a password is needed

- package.json
- yarn.lock
This reverts commit a2923246e11417d365994c8ab1d95b2609c64fc2.
Pour vérifier que la mise à jour Firebase est bien ok :
`rm -rf node_modules`
`direnv allow`
`yarn install`     
I have:
<details> …
> (BSR) chore(deps): restore firebase 9.6.11

- src/ui/components/tiles/HorizontalOfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34249
I have:
<details> …
> (PC-34249) fix(HorizontalOfferTile): flex was remove on refacto on HorizontalTile so now is missing

- .github/workflows/dev_on_schedule_e2e_android.yml
- .github/workflows/pr_e2e_android.yml
- .github/workflows/reusable_e2e_android.yml
> (BSR) feat(CI): add e2e pipeline

- .envrc
- flake.nix
c'est comme cette PR #7449 mais avec moins de commits
> (BSR) chore(setup): faster DirEnv

- src/features/chronicle/components/ChronicleCardList/ChronicleCardList.web.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardListBase.tsx
- src/features/chronicle/components/ChronicleOfferInfo/ChronicleOfferInfo.web.test.tsx
- src/features/chronicle/components/ChronicleOfferInfo/ChronicleOfferInfo.web.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.test.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33992
I have:
https://github.com/user-attachments/assets/076f3b55-9ed8-4b78-ad8d-665bd70599da
<details>
- In the production code: remove …
> (PC-33992) feat(chronicles): Chronicle page - desktop mode

- src/libs/keychain/keychain.native.test.ts
- src/libs/keychain/keychain.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34078
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be an exception or `null` …
> (PC-34078) feat(Keychain): add more precise error logs

- src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.tsx
- src/features/navigation/RootNavigator/Header/Nav.native.test.tsx
- src/features/navigation/RootNavigator/Header/Nav.tsx
- src/features/navigation/RootNavigator/Header/getTabNavigatorConfig.test.ts
- src/features/navigation/RootNavigator/Header/getTabNavigatorConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33896
I have:
| Desktop - Chrome | <img width="774" alt="Capture d’écran 2025-01-24 à 15 45 02" src="https://github.com/user-attachments/assets/e076d4e1-5c2f-467a-865a-60bfd8654bd0" /> | <img width="753" alt="Capture d’écran 2025-01-24 à 17 39 21" src="https://github.com/user-attachments/assets/ca53a5a1-8a93-4a45-9e97-5fc74be81176" /> | …
> (PC-33896) fix(Url): fix web app url preview

- src/features/search/components/SearchBox/SearchBox.native.test.tsx
- src/features/search/components/SearchBox/SearchBox.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34293
I have:
<details>
If you …
> (PC-34293) fix(cinema): remove shouldRedirectToThematicSearch on tracker

- .github/workflows/dev_on_workflow_update_jira_issues.yml
The `Impropre` field is deprecated and has been replaced by `safeToDeploy` in Jira
> (BSR) fix(CI): remove impropre field in Jira workflow

- doc/installation/setup.md
- scripts/load_certificate.sh
> (BSR) docs(setup): improve setup and dynamic path in a script

- src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.tsx
- src/features/profile/pages/Profile.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34263
I have:
<details>
If you …
> (PC-34263) feat(CreditV3): text logged out profile header

- .github/workflows/dev_on_schedule_run_e2e_android.yml
Le cron se lance actuellement une fois toutes les minutes, il faut le lancer une fois à minuit: https://github.com/pass-culture/pass-culture-app-native/actions/workflows/dev_on_schedule_run_e2e_android.yml
> (BSR) fix(ci): adjust cron to be triggered once

- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSection.native.test.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSection.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSection.web.test.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSection.web.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSectionBase.tsx
- src/features/offer/components/OfferContent/ChronicleSection/types.ts
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/pages/Offer/Offer.native.test.tsx
Faire en sorte d'être raccord avec le design pour afficher la section critique du book club
En lien avec le ticket https://passculture.atlassian.net/browse/PC-33991
I have:
Web Mobile
Web Desktop
<details>
If you consider correcting the issue is too time consuming/complex: create a ticket. Link the ticket in the …
> (BSR) feat(offer): chronicle section title in desktop web

- __snapshots__/features/bookings/pages/Bookings/Bookings.native.test.tsx.native-snap
- __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
- src/ui/components/Badge/Badge.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34297
I have:
iOS / Android
Web
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at …
> (PC-34297) fix(Badge): center text

- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33939
I have:
<details> …
> (PC-33939) fix(tracking): change achievement tracker naming

- src/features/chronicle/components/ChronicleCardList/ChronicleCardList.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34296
Ajout d'un dégradé sous les flèches du carousel
I have:
<details>
- In the production code: remove type assertions with `as` (type …
> (PC-34296) fix(offer): add gradient in chronicle list

- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- src/features/offer/components/MoviesScreeningCalendar/hook/getVenueMovieOffers.ts
- src/features/venue/components/VenueBody/VenueBody.native.test.tsx
- src/features/venue/components/VenueBody/VenueBody.tsx
- src/features/venue/components/VenueCTA/VenueCTA.native.test.tsx
- src/features/venue/components/VenueCTA/VenueCTA.tsx
- src/features/venue/components/VenueContent/VenueContent.native.test.tsx
- src/features/venue/components/VenueContent/VenueContent.tsx
- src/features/venue/components/VenueContent/VenueHeaderWrapper.tsx
- src/features/venue/components/VenueContent/VenueHeaderWrapper.web.tsx
- src/features/venue/components/VenueMessagingApps/VenueMessagingApps.tsx
- src/features/venue/components/VenueThematicSection/VenueThematicSection.tsx
- src/features/venue/components/VenueTopComponent/VenueTopComponentBase.tsx
- src/features/venue/components/VenueWebMetaHeader.tsx
- src/features/venue/pages/Venue/Venue.native.test.tsx
- src/features/venue/pages/Venue/Venue.tsx
- src/features/venue/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33463
Testé sur mobile & web. Pas de regressions constatées.
I have:
<details>
These …
> (PC-33463) refactor(Venue): refacto Venue page

- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/pages/Offer/Offer.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34153
Fix sur les ombres portées des cards dans les chroniques du Book Club. 
Ticket fait en MOB
I have:
iOS : 
Android : 
Web :
<details>
If you consider correcting the issue is too time consuming/complex: create a ticket. Link the ticket in the …
> (PC-34153) fix(ChronicleCard): drop shadow

- src/features/venueMap/pages/modals/VenueMapFiltersModal/VenueMapFiltersModal.native.test.tsx
- src/features/venueMap/pages/modals/VenueMapFiltersModal/VenueMapFiltersModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34130
I have:
| iOS              |               |![Capture d’écran 2025-02-03 à 18 28 06](https://github.com/user-attachments/assets/93c13432-6faa-4f7b-b908-35166c4b4ce3)|
| Android          |               |![Capture d’écran 2025-02-03 à 18 28 36](https://github.com/user-attachments/assets/34477a85-626a-47f0-a5f1-49e2ff0b2c0f)| …
> (PC-34130) feat(venueMap): add search and reset buttons on filters modal

- src/features/auth/api/useSignUp.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33990
Link to sentry : https://sentry.passculture.team/organizations/sentry/issues/1046950/?project=6&referrer=jira_integration
J'ai essayé de log plus d'information sur l'erreur, notamment si il s'agit d'une erreur en lien avec le SSO Google ou pas
I have:
> (PC-33990) feat(auth): log more informations in useSignUp catch error

- doc/development/general-info-web.md
- package.json
- scripts/dead_code_snapshot.txt
- sonar-project.properties
- src/features/navigation/RootNavigator/__mocks__/routes.tsx
- src/features/navigation/RootNavigator/routes.tsx
- vite.config.js
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34322
Using vite-bundle-analyzer, I found that achievement illustrations (around 1 MB total) were included in the main bundle of the web app. By dynamically loading the Achievements page, the illustrations are now in their own bundle that will no longer be downloaded at the start of the web app.
Note: the achievement feature is off for the web app anyways ATM.
Bundle analyzer after splitting illustrations:
There are still a few files for the Achievement feature that are included in the main bundle because they are being used on the home but they only are 6,38 KB.
The main bundle is now 11,87 MB without compression (12,95 MB before).
I …
> (PC-34322) feat(web): bundle split achievement illustrations

- android/app/build.gradle
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34334
Upgrade de [Maps SDK](https://play.google.com/sdks/details/com-google-android-gms-play-services-maps) à la dernière version (19)
Pas de regression constatée sur un build de release en staging 
Vérification sur logcat : 
I have:
<details>
If you …
> (PC-34334) chore(android): upgrade Google Map SDK to v19

- doc/installation/Android.md
- scripts/install_certificate_java.sh
> (BSR) docs(certificate): standardize password environment variable

- src/features/artist/components/ArtistPlaylist/ArtistPlaylist.native.test.tsx
- src/features/offer/components/OfferPlaylistItem/OfferPlaylistItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34448
I have:
| Desktop - Chrome | <img width="732" alt="image" src="https://github.com/user-attachments/assets/27e63538-673d-4be3-8462-e954e3d89ecb" />  | <img width="732" alt="image" src="https://github.com/user-attachments/assets/b23031ce-18fa-4556-872c-a1d0b36fe556" /> |
[2]: …
> (PC-34448) fix(OfferPlaylistItem): get category label from playlist item

- ios/Podfile.lock
- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34442
Checked on ios `src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx`:
Web:
For android we don't use the lib, so I just tested if I was able to open the app
> (PC-34442) chore(lib): upgrade blur

- src/features/offer/components/OfferVenueButton/OfferVenueButton.native.test.tsx
- src/features/offer/components/OfferVenueButton/OfferVenueButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32105
I have:
| iOS              |![Capture d’écran 2025-02-10 à 10 40 01](https://github.com/user-attachments/assets/d870e147-f9a8-48a0-a543-3f5bdff4e7d9)|![Capture d’écran 2025-02-10 à 10 39 27](https://github.com/user-attachments/assets/0dce4f4d-5f00-4811-8c9d-4036ca37d9b8)|
| Android          |![Capture d’écran 2025-02-10 à 10 39 56](https://github.com/user-attachments/assets/a46f3588-63bc-4c82-950a-d810a38583fe)|![Capture d’écran 2025-02-10 à 10 38 32](https://github.com/user-attachments/assets/dece9bea-e870-4d …
> (PC-32105) feat(offer): change venue button icon

- src/features/search/components/CategoriesList/CategoriesList.native.test.tsx
- src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34583
I have:
<details>
If you …
> (PC-34583) fix(nav): remove push and use navigate in search

- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildNumericFilters.ts
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildNumericFiltersHelpers/buildNumericFiltersHelpers.ts
Retrait du filtre numérique `isHeadlineUntil` sur la multi-requete Algolia pour afficher les offres à la une.
I have:
<details>
These rules apply to …
> (BSR) fix(venue): headline offer algolia  isHeadlineUntil filter

- doc/installation/Android.md
- doc/installation/iOS.md
> (BSR) docs(setup): add missing instructions

- src/features/chronicle/components/ChronicleCard/ChronicleCard.native.test.tsx
- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardList.web.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardListBase.native.test.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardListBase.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSection.web.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSectionBase.tsx
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34395
I have:
| iOS              |               |![Capture d’écran 2025-02-12 à 16 51 32](https://github.com/user-attachments/assets/83d079fa-e46d-4440-b0f6-2f1a38fd22f6)|
| Android          |               |![Capture d’écran 2025-02-13 à 09 54 39](https://github.com/user-attachments/assets/31c6f79b-6149-4e5e-a2be-b3f41138c902)|
| Phone - Chrome   |               |![Capture d’écran 2025-02-12 à 16 53 32](https://github.com/user-attachments/assets/f38c2ce5-9c0c-435f-a00d-d4e9d6a12a47)| …
> (PC-34395) feat(ChronicleCard): display button when the chronicle is too long

- src/cheatcodes/hooks/useFeatureFlagAll.ts
- src/cheatcodes/pages/others/CheatcodesScreenFeatureFlags.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34486
I have:
<details> …
> (PC-34486) feat(FF): added FF owners to cheatcodes page

- .storybook/main.js
- src/ui/storybook/Animations.stories.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34599
I have:
> (PC-34599) feat(storybook): remove jest.setTimeout in Animations stories

- __snapshots__/features/tutorial/pages/NotEligibleModal.native.test.tsx.native-snap
- __snapshots__/features/tutorial/pages/onboarding/OnboardingNotEligible.native.test.tsx.native-snap
- src/features/tutorial/pages/NotEligibleModal.native.test.tsx
- src/features/tutorial/pages/NotEligibleModal.tsx
- src/features/tutorial/pages/onboarding/OnboardingNotEligible.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34596
I have:
<details>
If you …
> (PC-34596) fix(NotEligible): wording

- __snapshots__/features/home/pages/Home.native.test.tsx.native-snap
- src/features/remoteBanner/components/RemoteBanner.native.test.tsx
- src/features/remoteBanner/components/RemoteBanner.tsx
- src/features/remoteBanner/components/RemoteBanner.web.test.tsx
- src/ui/components/ModuleBanner/BannerWithBackground.tsx
- src/ui/components/ModuleBanner/GenericBanner.stories.tsx
- src/ui/components/ModuleBanner/GenericBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34485
En utilisant onPress plutot que navigateTo, l'utilisation d'un composant Link disparait. J'ai ajouté des roles comme fix car c'est le plus simple pour ce cas très spécifique. 
J'ai aussi retiré l'accessibilité label "Nouvelle fenetre" qui pouvait encore être présent en web + store alors que c'est juste un bouton. 
Enfin, j'ai retiré l'icon si c'est un bouton. 
I have:
| iOS              |               |   ![Simulator Screenshot - iPhone 15 Pro Max - 2025-02-14 at 14 49 …
> (PC-34485) feat(a11y): update RemoteBanner accessibility

- scripts/install_certificate_java.sh
- scripts/start_android_emulator_with_certificate.sh
can be executed manually not only by DirEnv
I have:
<details>
These rules apply …
> (BSR) chore(script): help to debug scripts

- src/libs/monitoring/config.ts
- src/libs/monitoring/config.web.ts
- src/libs/monitoring/services.web.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34188
I have:
<details>
If you …
> (PC-34188) feat(sentry): ignore recaptcha timeout

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- Gemfile.lock
- fastlane/.env.staging
- fastlane/.env.testing
- fastlane/Fastfile
- fastlane/Pluginfile
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34515
I have:
<details>
If you …
> (PC-34515) feat(CI): add app distribution lane for ios

- src/features/search/components/NoSearchResults/NoSearchResult.native.test.tsx
- src/features/search/components/NoSearchResults/NoSearchResult.tsx
- src/features/search/components/SearchList/SearchList.tsx
- src/features/search/components/SearchList/SearchList.web.test.tsx
- src/features/search/components/SearchList/SearchList.web.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/helpers/useNavigateToSearch/useNavigateToSearch.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33844
I have:
| Desktop - Chrome | <img width="1024" alt="Capture d’écran 2025-02-20 à 09 53 33" src="https://github.com/user-attachments/assets/0b24ea78-6ffe-4a85-b202-3e19c6a1b987" />          | <video src="https://github.com/user-attachments/assets/06cb62a4-9213-44fa-821d-a65c91d84390" width="600" /> |
| ios | <img src="https://github.com/user-attachments/assets/cb880d24-54c3-4322-9786-7bd84ce3dea9" width="500" /> | <img src="https://github.com/user-attachments/assets/658b2427-1f51-4ab7-ade7-5241b26d8f89" width="500" …
> (PC-33844) feat(NoResults): add new no results view for located search

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- fastlane/Fastfile
> (BSR) fix(CI): limit app distribution to testing and fix the lane call

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- Gemfile.lock
- fastlane/.env.staging
- fastlane/.env.testing
- fastlane/Fastfile
- fastlane/Pluginfile
> (BSR) fix(CI): Revert temporary app distribution 

- src/features/chronicle/components/ChronicleOfferInfo/ChronicleOfferInfo.web.test.tsx
- src/features/chronicle/components/ChronicleOfferInfo/ChronicleOfferInfo.web.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
Fix sur la page des chroniques côté web, où l'image de l'offre ne s'affichait pas.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34626
I have:
Web
<details>
- In the production code: …
> (PC-34626) fix(chronicles): web - offer image

- src/features/chronicle/pages/Chronicles/Chronicles.native.test.tsx
- src/features/chronicle/pages/Chronicles/ChroniclesBase.tsx
- src/features/chronicle/pages/ChroniclesWritersModal/ChroniclesWritersModal.native.test.tsx
- src/features/chronicle/pages/ChroniclesWritersModal/ChroniclesWritersModal.tsx
- src/features/chronicle/pages/ChroniclesWritersModal/ChroniclesWritersModal.web.test.tsx
- src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34735
I have:
Before :
https://github.com/user-attachments/assets/15412b09-4d2a-4edd-a223-f6aa9ac1f741
After :
https://github.com/user-attachments/assets/c480f5fd-2e4e-4d97-8ee6-4c76be8d9c67
<details> …
> (PC-34735) feat(chronicle): improve close modal and redirection transition

- src/ui/components/Avatar/AvatarList.native.test.tsx
- src/ui/components/Avatar/AvatarListItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34591
I have:
<details>
If you …
> (PC-34591) fix(AvatarListItem): remove useless with push

- .github/dependabot.yml
- .github/workflows/dev_on_workflow_call_e2e_android.yml
- .github/workflows/dev_on_workflow_environment_android_deploy.yml
- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- .github/workflows/dev_on_workflow_environment_soft_deploy.yml
- .github/workflows/dev_on_workflow_install.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32312
I have:
<details>
If you …
> (PC-32312) chore(androidSDK): upgrade-tooling

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
- Gemfile.lock
- fastlane/.env.staging
- fastlane/.env.testing
- fastlane/Fastfile
- fastlane/Pluginfile
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34808
I have:
<details>
If you …
> (PC-34808) feat(CI): add ios app distribution 

- devbox.json
- devbox.lock
- flake.nix
> (BSR) feat(devbox): move watchman from nix to direnv

- src/libs/parsers/parseMarkdown/parseMarkdown.test.ts
- src/libs/parsers/parseMarkdown/parseMarkdown.ts
Fix qui corrige la transformation du markdown dans les URL
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34707
Web
iOS
I have:
<details> …
> (PC-34707) fix(offer): ignore URLs in markdown transformation

- .github/workflows/dev_on_workflow_environment_ios_deploy.yml
> (BSR) feat(CI): add json credentials to file

- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.web.test.tsx
- src/features/profile/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34826
I have:
| iOS              |               |![Simulator Screenshot - iPhone 13 - 2025-02-26 at 17 07 17](https://github.com/user-attachments/assets/5009fc83-d804-4651-a841-ab1674c8069b)|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701 …
> (PC-34826) feat(creditV3): show recredit amount instead of max amount

- __snapshots__/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.native.test.tsx.native-snap
- src/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.tsx
- src/features/offer/components/OfferFooter/StickyFooterContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34662
I have:
| Desktop - Chrome |               | <video src="https://github.com/user-attachments/assets/94c72ba8-1af0-4550-b022-89283cbfa816" /> |
<details>
If you can't respect one of these rules, be sure to …
> (PC-34662) feat(ComingSoon): fix auth modal

- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34826
I have:
Screenshots for 17 y.o.
| iOS              |![image](https://github.com/user-attachments/assets/97ffcdb8-6796-4930-a080-42f117154d66)|![image](https://github.com/user-attachments/assets/70b7ebf5-0c06-4618-809e-da593f5e85b7)|
[2]: …
> (PC-34826) fix(creditV3): fallback recredit amount

- src/api/apiHelpers.native.test.ts
- src/api/apiHelpers.ts
- src/api/refreshAccessToken.native.test.ts
- src/api/refreshAccessToken.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34186
I have:
<details> …
> (PC-34186) feat(token): more infos for Sentry error

- src/features/offer/components/OfferPlaylistItem/OfferPlaylistItem.tsx
- src/features/offer/components/OfferPlaylistList/OfferPlaylistList.tsx
- src/features/offer/components/OfferTile/OfferTile.native.test.tsx
- src/features/offer/components/OfferTile/OfferTile.tsx
- src/features/offer/types.ts
- src/shared/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34589
Mise en place d'une prop permettant de choisir la méthode de navigation depuis un composant `OfferTile`. Les  méthodes sont "navigate" (par défaut) ou "push"
I have:
<details>
If you consider correcting the issue is too time consuming/complex: …
> (PC-34589) fix(OfferTile): add navigation method prop

- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- ios/Podfile.lock
- jest/jest.web.setup.ts
- package.json
- src/features/home/components/modules/video/VideoCarouselModule.tsx
- src/features/offer/components/OfferImageCarouselPagination/OfferImageCarouselPagination.native.test.tsx
- src/features/offer/components/OfferImageCarouselPagination/OfferImageCarouselPagination.web.test.tsx
- src/ui/CarouselBar/CarouselBar.native.test.tsx
- src/ui/CarouselBar/CarouselBar.tsx
- src/ui/CarouselDot/CarouselDot.native.test.tsx
- src/ui/CarouselDot/CarouselDot.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34821
Tests réalisés sur web + iOS (émulateur) + android (device physique + émulateur)
Il faudra s'assurer du bon fonctionnement en mode release sur iOS
I have:
<details> …
> (PC-34821) build(reanimated): bump reanimated and reanimated carousel

- src/features/achievements/pages/Achievements.native.test.tsx
- src/features/auth/components/AuthenticationButton/AuthenticationButton.native.test.tsx
- src/features/auth/pages/forgottenPassword/ResetPasswordExpiredLink/ResetPasswordExpiredLink.native.test.tsx
- src/features/auth/pages/suspendedAccount/GenericSuspendedAccount/GenericSuspendedAccount.native.test.tsx
- src/features/birthdayNotifications/pages/EighteenBirthday.native.test.tsx
- src/features/bookOffer/components/BookDuoChoice.native.test.tsx
- src/features/bookOffer/components/BookingCloseInformation.native.test.tsx
- src/features/bookings/components/NoBookingsView.native.test.tsx
- src/features/bookings/pages/BookingNotFound/BookingNotFound.native.test.tsx
- src/features/favorites/components/Buttons/Sort.native.test.tsx
- src/features/navigation/RootNavigator/linking/getNestedNavigationFromState.ts
- src/features/navigation/RootNavigator/useScreenshotListener.ts
- src/features/navigation/helpers/isAppUrl.ts
- src/features/navigation/services.ts
I have:
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be …
> (BSR) refactor(tests): replace fireEvent by userEvent

- .github/workflows/dev_on_workflow_environment_android_deploy.yml
- fastlane/Fastfile
> (PC-34846) feat(CI): add app distribution lane android

- .maestro/tests/config.yaml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34929
I have:
**Before**
**After**
> (PC-34929) feat(e2e): remove legacy slack notifs on runs

- fastlane/Fastfile
> (BSR) fix(CI): remove app distribution release note for android

- doc/decision-records/DR002 - venue-map.md
Ajout d'un document expliquant la decision de refactoriser la partie "carte des lieux" de l'App Native
I have:
<details>
These rules apply to files …
> (BSR) docs(adr): add ADR doc for venueMap refactor

- __mocks__/react-native-map-clustering.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33564
I have:
<details> …
> (PC-33564) test(venueMap): fix skipped tests

- src/features/search/components/VenuePlaylist/VenuePlaylist.native.test.tsx
- src/features/search/components/VenuePlaylist/VenuePlaylist.tsx
- src/features/search/constants.ts
- src/features/search/helpers/getVenueTypesFromSearchGroup/getVenueTypesFromSearchGroup.test.ts
- src/features/search/helpers/getVenueTypesFromSearchGroup/getVenueTypesFromSearchGroup.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34926
I have:
Before :
https://github.com/user-attachments/assets/a1e4e986-df8a-48cd-85ab-5aa7e3ffc90a
After :
https://github.com/user-attachments/assets/ce7815cf-b338-4928-bdc2-ab31b157b66b
<details> …
> (PC-34926) feat(search): use associated venue types to search group to filter when pressing see map button

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34595
I have:
<details>
If you …
> (PC-34595) build(codePush): bump code-push

- src/features/bookings/components/BookingDetailsContent.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34793
I have:
| iOS              |<img width="289" alt="Screenshot 2025-03-04 at 11 47 51" src="https://github.com/user-attachments/assets/11f83ddf-a552-44fd-815d-42fbed99b7f3" />|![Simulator Screenshot - iPhone SE (3rd generation) - 2025-03-04 at 12 32 18](https://github.com/user-attachments/assets/c776926c-f50f-47e1-8a74-5a5221e09b2e)|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v= …
> (PC-34793) feat(BookingPage): disposal forbidden banner

- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_call_e2e_android.yml
- .github/workflows/dev_on_workflow_call_e2e_ios.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34929
I have:
Le nom de l'upload donnera ça :
> (PC-34929) feat(e2e): add e2e ios run on staging deploy

- src/features/bookings/components/BookingDetailsContent.tsx
- src/features/bookings/components/BookingPrecision.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34303
I have:
| iOS              |<img width="281" alt="Screenshot 2025-03-04 at 12 36 37" src="https://github.com/user-attachments/assets/4256f45c-907a-439e-8f7f-99a43169f405" />|![Simulator Screenshot - iPhone SE (3rd generation) - 2025-03-04 at 12 31 50](https://github.com/user-attachments/assets/d0f40c1e-fbca-49ef-98d2-d58b57adf3ed)
13c5e"|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481a …
> (PC-34303) feat(BookingPage): organizer section

- src/features/venueMap/components/FilterBannerContainer/SingleFilterBannerContainer.native.test.tsx
- src/features/venueMap/components/FilterBannerContainer/SingleFilterBannerContainer.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
- src/features/venueMap/pages/VenueMap/VenueMapBase.tsx
- src/features/venueMap/pages/modals/VenueTypeModal/VenueTypeModal.native.test.tsx
- src/features/venueMap/pages/modals/VenueTypeModal/VenueTypeModal.tsx
- src/features/venueMap/store/venueMapStore.test.ts
- src/features/venueMap/store/venueMapStore.ts
- src/features/venueMap/useVenuesInRegionQuery.native.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34936
I have:
<details> …
> (PC-34936) refactor(venueMap): remove setVenueTypeCode of venueMapStore

- src/features/location/components/LocationWidget.native.test.tsx
- src/features/location/components/LocationWidget.stories.tsx
- src/features/location/components/LocationWidget.tsx
- src/features/location/components/LocationWidgetDesktop.web.test.tsx
- src/features/location/components/LocationWidgetWrapperDesktop.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34965
I have:
| iOS              |![Capture d’écran 2025-03-05 à 17 16 01](https://github.com/user-attachments/assets/d21ccea8-1b85-4642-9714-2a57215f04d4) ![Capture d’écran 2025-03-05 à 17 16 11](https://github.com/user-attachments/assets/3eba6922-4a21-4646-9c38-ea85e1eebdd9)|![Capture d’écran 2025-03-05 à 17 27 58](https://github.com/user-attachments/assets/38a5afd1-5302-4534-9488-1521a3482c26) ![Capture d’écran 2025-03-05 à 17 28 06](https://github.com/user-attachments/assets/6069f443-db30-4362-b9d3-2414a674ae47) …
> (PC-34965) feat(location): remove wipAppV2LocationWidget FF

- ios/Podfile.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34595
I have:
<details>
If you …
> (PC-34595) build(pods): update podfile

- scripts/is_proxy_enabled.sh
> (BSR) chore(env): avoid spamming when proxy is not installed

- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
Dernières corrections sur des test flaky concernant la carte des lieux.
Avec une habile combinaison de `waitFor` et de `act`, ça tient 🤷 
I have:
<details> …
> (BSR) test(VenueMapContainer): fix flaky tests

- scripts/start_android_emulator_with_certificate.sh
> (BSR) build(Android): try to avoid flaky certificate added

- src/features/offer/components/OfferImageCarousel/OfferImageCarousel.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34882
Correction de la largeur du texte des crédits sur les images d'offre
I have:
iOS / Android
Web
<details>
- In the production code: …
> (PC-34882) fix(offer): image credits max width

- src/features/venueMap/components/VenueMapView/VenueMapView.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
- src/libs/firebase/firestore/types.ts
Ce FF permettait de masquer les noms des monuments entre autre sur la carte.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34974
I have:
| iOS              |               |![Capture d’écran 2025-03-06 à 17 27 03](https://github.com/user-attachments/assets/f3a7bae2-5b59-44b1-8cea-f6148f48fa1a)|
[2]: …
> (PC-34974) refactor(venueMap): remove wipVenueMapHiddenPOI FF

- doc/installation/Android.md
> (BSR) docs(android): how to create a working emulator

- src/features/artist/components/ArtistBody/ArtistBody.tsx
- src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.test.ts
- src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.ts
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/helpers/useArtistResults/useArtistResults.native.test.ts
- src/features/offer/helpers/useArtistResults/useArtistResults.tsx
L'accès à la page artiste dépendait en partie d'une condition au searchGroupName qui n'est plus associé à la subcategory. Cette condition se base maintenant sur l'id de la subcategory.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35092
I have:
Before :
https://github.com/user-attachments/assets/b09ad0ee-70ab-4756-9d5d-09fcda57415e
https://github.com/user-attachments/assets/dd0dbbdb-1032-4f4d-9cb7-9b073f51fe02
After :
https://github.com/user-attachments/assets/2df3008a-48b1-4caf-ae57-a3c3451326a1
https://github.com/user-attachments/assets/7c593eb4-cd22-4aba-af6d-e6429a319dca …
> (PC-35092) fix(artist): artist page access

- .maestro/tests/subFolder/booking/BookCinemaOffer.yml
- .maestro/tests/subFolder/booking/BookDuoOffer.yml
- .maestro/tests/subFolder/booking/BookPhysicalOffer.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35112
I have:
> (PC-35112) fix(e2e): update wording for book/cinema category

- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.tsx
- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34975
I have:
| iOS              |               |![Capture d’écran 2025-03-11 à 12 13 24](https://github.com/user-attachments/assets/7a87101b-9e38-4b6f-b89e-9053ac5e4acf)| …
> (PC-34975) refactor(venueMap): remove wipVenueMapPinV2 FF

- flake.nix
it is already installed with others tools
it seems to create some issues with the custom certificate authorities
the issues are not present when using `/usr/bin/git`
> (BSR) chore(setup): remove explicit dependency to git

- .storybook/main.js
- ios/Podfile.lock
- package.json
- src/features/bookings/components/TicketCutout.tsx
- src/ui/svg/Stroke.tsx
- src/ui/svg/TicketCutoutLeft.tsx
- src/ui/svg/TicketCutoutLeft.web.tsx
- src/ui/svg/TicketCutoutRight.tsx
- src/ui/svg/TicketCutoutRight.web.tsx
- vite.config.js
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34933
I have:
| iOS              | <img width="195" alt="Screenshot 2025-03-13 at 12 13 35" src="https://github.com/user-attachments/assets/7add6d56-a875-44c5-98fc-6793f23e9bfe" />| ![Simulator Screenshot - iPhone SE (3rd generation) - 2025-03-13 at 12 08 20](https://github.com/user-attachments/assets/d11c1f34-b991-4bac-a1cc-328a01a039eb)|
| Desktop - Chrome |               |<img width="1440" alt="Screenshot 2025-03-13 at 12 08 15" …
> (PC-34933) fix(TicketCutout): bump rn-svg to handle filters in native application

- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/components/OfferHeader/OfferReactionHeaderButton.native.test.tsx
- src/features/offer/components/OfferHeader/OfferReactionHeaderButton.tsx
- src/features/offer/components/OfferReactionSection/OfferReactionSection.native.test.tsx
- src/features/offer/components/OfferReactionSection/OfferReactionSection.tsx
- src/features/offer/helpers/renderOfferPageTestUtil.tsx
- src/features/offer/pages/Offer/Offer.native.test.tsx
- src/features/offer/pages/Offer/Offer.tsx
- src/features/offer/types.ts
- src/queries/bookings/useEndedBookingFromOfferIdQuery.ts
- src/queries/offer/useOfferQuery.native.test.ts
- src/queries/offer/useOfferQuery.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34992
Mise en place de la fonctionnalité de réaction à une offre via un bouton dans le header de la page Offre.
Suppression des boutons **J'aime / Je n'aime pas**
I have:
iOS
https://github.com/user-attachments/assets/f0114a5a-9661-4259-a92c-0cbb9afbc696
Android
https://github.com/user-attachments/assets/72a6ecb2-fc26-49be-8361-579646a8ed31
Web
https://github.com/user-attachments/assets/91317e47-d665-48f6-bf52-6a2d41b3605b
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb04cfee …
> (PC-34992) feat(offer): reaction feature from offer header

- .eslintrc.js
- .storybook/main.js
- babel.config.js
- doc/development/alias.md
- jest.config.js
- knip.ts
- tsconfig.json
- vite.config.js
Quand on ajoute un alias (c'est rare) souvent on oublie d'ajouter la config aux autres endroits
Cette PR tente de palier à ça en mettant un rappel qu'il faut changer aux autres endroits
> (BSR) docs(alias): try to not forgot aliases

- __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- src/features/offer/components/OfferPlaylist/OfferPlaylist.tsx
- src/features/offer/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx
- src/features/offer/components/OfferPlaylistList/OfferPlaylistList.tsx
- src/ui/components/PassPlaylist.tsx
- src/ui/components/Playlist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35130
Implémentation d'un prop `onPlaylistViewableItemsChanged` sur le composant `OfferPlaylistList` qui permet d'avoir une information sur les item d'offre visibles à l'écran
I have:
<details> …
> (PC-35130) refactor(OfferPlaylist): expose viewable items changed event

- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
La prop shouldTruncate doit être utilisée pour utiliser une maxHeight
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35094
I have:
Before :
https://github.com/user-attachments/assets/c07ac8dd-bb15-4a67-b3a7-44ceaef9491c
https://github.com/user-attachments/assets/2dcdb0b3-d623-4df4-9768-b0f1fabf29f0
After :
https://github.com/user-attachments/assets/aa1e8560-c63f-4913-a77c-0f6790af13de
https://github.com/user-attachments/assets/db5d8c9c-9a7f-467d-9614-1e8d7fde55f6 …
> (PC-35094) feat(ui): use shouldTruncate to use maxHeight on ChronicleCard

- src/features/offer/pages/Offer/Offer.native.test.tsx
- src/features/offer/pages/Offer/Offer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34992
Fix [de cette PR](https://github.com/pass-culture/pass-culture-app-native/pull/7849) qui fait en sorte d'appeler l'API de réservations uniquement si le jeune est loggé.
https://github.com/user-attachments/assets/4359f092-5b23-4540-9cba-94894a68c7a2
I have:
<details>
If you can't respect one of these rules, be sure to …
> (PC-34992) fix(offer): user needs to be logged in to call bookings

- flake.lock
- flake.nix
||Before|After|
|:--|:--|:--|
|`java --version`|openjdk 17.0.10 2024-01-16 LTS|openjdk 17.0.12 2024-07-16 LTS|
|`jq --version`|jq-1.7.1|jq-1.7.1|
|`python3 --version`|Python 3.12.5|Python 3.12.9|
|`act --version`|act version 0.2.66|act version 0.2.75|
|`gh --version`|gh version 2.55.0 (1980-01-01)|gh version 2.68.1 (1980-01-01)|
|`podman --version`|podman version 5.2.2|podman version 5.4.1|
- [Java](https://endoflife.date/azul-zulu) ✅ 
- [podman](https://endoflife.date/podman) ✅ 
- [python](https://endoflife.date/python) ✅ 
> (BSR) chore(dependencies): update some tools

- src/features/artist/components/ArtistPlaylist/ArtistPlaylist.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
- src/features/headlineOffer/adapters/offerToHeadlineOfferData.ts
- src/features/home/components/AttachedModuleCard/AttachedOfferCard.tsx
- src/features/home/components/modules/video/VideoMonoOfferTile.tsx
- src/features/home/components/modules/video/VideoMultiOfferTile.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/components/OfferPlaylistList/OfferPlaylistList.tsx
- src/features/offer/components/OfferTile/OfferTileWrapper.tsx
- src/features/venue/components/VenueOffers/VenueOffersList.tsx
- src/features/venueMap/components/VenueMapBottomSheet/VenueMapOfferPlaylist.tsx
- src/libs/parsers/getDisplayedPrice.native.test.ts
- src/libs/parsers/getDisplayedPrice.ts
- src/ui/components/tiles/HorizontalOfferTile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35258
I have:
<details> …
> (PC-35258) refactor(getDisplayedPrice): fix naming, introduce early return, add return for readability

- src/features/bookOffer/helpers/useModalContent.native.test.tsx
- src/features/search/pages/ThematicSearch/api/useThematicSearchPlaylists.native.test.ts
- src/queries/favorites/useAddFavoriteMutation.native.test.tsx
- src/shared/Banners/GeolocationBanner.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35280
I have:
<details>
If you …
> (PC-35280) feat(tests): add describe in some tests

- src/features/home/api/useHighlightOffer.ts
- src/libs/algolia/fetchAlgolia/fetchOffersByIds.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34883
I have:
| Desktop - Chrome |            |  ![Capture d’écran 2025-03-21 à 12 56 13](https://github.com/user-attachments/assets/cc89ada5-600c-410c-9c6e-65bb6883c511)     |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb …
> (PC-34883) fix(MarketingBloc): display future offers

- doc/development/general-info-web.md
- src/features/identityCheck/pages/identification/ubble/UbbleWebview.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34964
The issue occurs because navigate('IdentityCheckEnd') pushes a new screen within the existing navigation stack, keeping the web view active. When Ubble redirects back to the web app, it loads the app inside the web view, creating a nested app effect.
The fix is to use navigateFromRef('IdentityCheckEnd') instead, ensuring that navigation happens from the root level, just like navigateToHome. This prevents the web view from keeping the previous navigation context, avoiding the double navigation bar issue.
I have:
| iOS …
> (PC-34964) fix(IdentityCheck): attempt remove double navbar

- src/features/offer/components/OfferBody/ProposedBySection/ProposedBySection.tsx
- src/ui/components/Avatar/Avatar.stories.tsx
- src/ui/components/Avatar/Avatar.tsx
- src/ui/theme/constants.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35220
I have:
| iOS              |               |<img width="426" alt="Capture d’écran 2025-03-21 à 15 55 59" src="https://github.com/user-attachments/assets/cde1d868-223c-4e12-bbcf-b4fb685684d1" />|
| Phone - Chrome   |               |![Capture d’écran 2025-03-21 à 15 47 01](https://github.com/user-attachments/assets/87b1a006-a354-48e4-861d-3a7175d04c65)|
| Desktop - Chrome |               |![Capture d’écran 2025-03-21 à 15 48 …
> (PC-35220) feat(ProposedBySection): add a props borderRadius to have more control on Avatar component

- src/features/forceUpdate/helpers/useMinimalBuildNumber.ts
- src/features/forceUpdate/helpers/useMustUpdateApp.native.test.ts
- src/features/forceUpdate/helpers/useMustUpdateApp.ts
- src/features/forceUpdate/helpers/useResetOnMinimalBuild.native.test.ts
- src/features/forceUpdate/pages/ForceUpdateWithResetErrorBoundary.native.test.tsx
- src/features/forceUpdate/pages/ForceUpdateWithResetErrorBoundary.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34900
This error pops up every time we force an update on our users.
After 15 seconds, if the user is unable to get the minimal build number from firestoreRemoteStore we log to sentry.
My assumption is that this log is sent to sentry when the user has a degraded internet access.
There is a global effort led by the Architecture Guild to better handle degraded internet access in our app, so for the moment I'll attempt these quick changes: 
- log to sentry only if attempting to call firestore is done (and not stuck in loading in the case of a very slow connection). 
- get the error from useQuery and pass it to sentry in case getMinimalBuildNumber throws an error for more precise logging.
- remove the interval all together as …
> (PC-34900) fix(useMustUpdate): improve logging

- .github/workflows/dev_on_workflow_tester.yml
- doc/decision-records/DR004 - allure-report.md
Cette PR apporte les modifications suivantes dans le fichier .github/workflows/dev_app_workflow_tester.yml :
- Récupération de l’historique Allure depuis un bucket Google
- Génération du rapport Allure
- Synchronisation automatique de l’historique généré vers le bucket GCS pour une utilisation future.
- Utilisation de la commande gsutil pour transférer l’historique depuis/vers le bucket GCS.
- Vérification de l’existence du dossier allure-report/history avant la synchronisation pour éviter les erreurs lorsque le dossier est vide.
- Messages d’avertissement ou de confirmation intégrés (echo) pour mieux comprendre le statut de la synchronisation.
Amélioration du suivi des tests : conserver l’historique Allure d’une exécution à l’autre permet de visualiser l’évolution des tests dans le temps …
> (PC-35107) feat(allure): add allure history

- flake.nix
`maestro --version`
* avant : `1.37.9`
* arpès : `1.39.13`
I have:
> (BSR) chore(dependencies): upgrade Maestro

- __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/SetAddress.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/SetAddress.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/SetCity.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/profile/SetName.native.test.tsx.native-snap
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/SetCity.tsx
- src/features/identityCheck/pages/profile/SetName.native.test.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34982
I have:
<details>
If you …
> (PC-34982) feat(a11y): More precise accessibilityLabels when possible

- src/libs/contentful/adapters/adaptHomepageModules.native.test.ts
- src/libs/contentful/adapters/adaptHomepageModules.ts
- src/libs/contentful/adapters/contentfulAdapters.ts
- src/libs/contentful/adapters/modules/adaptBusinessModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptBusinessModule.ts
- src/libs/contentful/adapters/modules/adaptCategoryListModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptCategoryListModule.ts
- src/libs/contentful/adapters/modules/adaptExclusivityModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptExclusivityModule.ts
- src/libs/contentful/adapters/modules/adaptHighlightOfferModule.ts
- src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptOffersModule.ts
- src/libs/contentful/adapters/modules/adaptRecommendationModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptRecommendationModule.ts
- src/libs/contentful/adapters/modules/adaptThematicHighlightModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptThematicHighlightModule.ts
- src/libs/contentful/adapters/modules/adaptTrendsModule.ts
- src/libs/contentful/adapters/modules/adaptVenueMapModule.ts
- src/libs/contentful/adapters/modules/adaptVenuesModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptVenuesModule.ts
- src/libs/contentful/adapters/modules/adaptVideoCarouselModule.native.test.ts
- src/libs/contentful/adapters/modules/adaptVideoCarouselModule.ts
- src/libs/contentful/adapters/modules/adaptVideoModule.ts
- src/libs/contentful/types.ts
Reprise de: https://github.com/pass-culture/pass-culture-app-native/pull/6546
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34740
I have:
<details> …
> (PC-34740) refactor(contentful): adapter

- src/features/identityCheck/pages/identification/ubble/UbbleWebview.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34964
I have:
<details>
If you …
> (PC-34964) docs(Ubble): avoid double nav bar

- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.test.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferImageCarousel/OfferImageCarouselItem.tsx
- src/features/offer/helpers/useOfferImageContainerDimensions.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35355
I have:
| iOS              |               |<img width="424" alt="Capture d’écran 2025-03-26 à 15 52 52" src="https://github.com/user-attachments/assets/4ea4076c-802b-4c8b-a423-71784beb09dd" /><img width="424" alt="Capture d’écran 2025-03-26 à 15 53 14" src="https://github.com/user-attachments/assets/538cfd91-1d0f-4c84-b9a0-9b9d3e1d207e" />|
[1]: …
> (PC-35355) fix(OfferImage): correct condition for subcatgeories and aspectRatio

- src/features/offer/components/OfferContent/OfferContent.web.test.tsx
- src/features/offer/components/OfferTile/OfferTile.stories.tsx
- src/features/offer/components/OfferTile/OfferTile.tsx
- src/features/offer/components/OfferTile/PlaylistCardOffer.native.test.tsx
- src/features/offer/components/OfferTile/PlaylistCardOffer.tsx
- src/features/offer/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35367
Utilisation d'un ReactNode pour prévoir la possibilité d'avoir aussi bien un tag de likes, qu'un tag de recommandations ou encore un tag d'avis (1 seul tag d'interaction possible sur l'item d'une playlist)
I have:
| iOS              |               |![Capture d’écran 2025-03-26 à 17 20 47](https://github.com/user-attachments/assets/66ca809e-9e3b-4ec5-be6c-033b003c258b)|
| Android          |               |![Capture d’écran 2025-03-26 à 17 22 19](https://github.com/user-attachments/assets/34a28120-1c46-4059-8b31-f3 …
> (PC-35367) refactor(offer): use interaction tag react node rather than just likes counter

- src/features/offer/pages/Offer/Offer.native.test.tsx
- src/features/offer/pages/Offer/Offer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35360
Fix d'affiche du bouton de réaction dans le header de la page Offre. On vérifie que l'utilisateur a le droit de réagir avant d'afficher le bouton.
iOS
https://github.com/user-attachments/assets/e1efffa4-e179-464c-831b-d7ecd16a4970
I have:
<details>
If you can't respect one of these rules, be sure to explain why with a …
> (PC-35360) fix(Offer): header reaction button in header

- __snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap
- __snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap
- __snapshots__/features/home/pages/Home.native.test.tsx.native-snap
- __snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
- __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- scripts/noUncheckedIndexedAccess_snapshot.txt
- src/features/home/components/AccessibleTitle.native.test.tsx
- src/features/home/components/AccessibleTitle.tsx
- src/features/home/components/modules/HighlightOfferModule.tsx
- src/features/home/components/modules/HomeModule.native.test.tsx
- src/features/home/components/modules/HomeModule.web.test.tsx
- src/features/home/components/modules/categories/CategoryListModule.tsx
- src/features/home/components/modules/video/OldVideoModuleDesktop.tsx
- src/features/home/components/modules/video/OldVideoModuleMobile.tsx
- src/features/home/components/modules/video/VideoModule.native.test.tsx
- src/features/home/components/modules/video/VideoModuleDesktop.tsx
- src/features/home/components/modules/video/VideoModuleMobile.tsx
- src/features/home/components/modules/video/VideoMonoOfferTile.tsx
- src/features/home/pages/GenericHome.tsx
- src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
- src/features/venue/components/VenueOffers/VenueOffersList.tsx
- src/ui/components/PassPlaylist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34902
I have:
<details>
If you …
> (PC-34902) feat(HomePlaylistsTtitles): emojis should appear but not be readable by voicOver

- src/features/bookings/helpers/expirationDateUtils.test.ts
- src/features/bookings/helpers/expirationDateUtils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35259
I have:
<details> …
> (PC-35259) refactor(expirationDateUtils): add test and simplify code

- package.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35196
I have:
<details>
If you …
> (PC-35196) fix(lighthouse): restore command in package.json

- devbox.lock
- flake.nix
- scripts/load_certificate.sh
try to avoid the following error
```txt
/nix/store/559pz0w6zlvw8yyxah9s10fhaz400vaj-stdenv-darwin/setup: line 138: pop_var_context: head of shell_variables not a function context
```
which need to re-run `direnv allow`
`devbox version`
* before : `0.12.0`
* after : `0.14.0`
I have:
> (BSR) chore(dependencies): update devbox

- src/features/offer/components/InteractionTag/InteractionTag.native.test.tsx
- src/features/offer/components/InteractionTag/InteractionTag.tsx
- src/features/offer/components/InteractionTag/getTagConfig.test.ts
- src/features/offer/components/InteractionTag/getTagConfig.tsx
- src/features/offer/components/OfferTile/OfferTile.stories.tsx
- src/features/offer/components/OfferTile/PlaylistCardOffer.tsx
- src/shared/typeguards/isReactElement.test.tsx
- src/shared/typeguards/isReactElement.ts
- src/shared/typeguards/isStyledComponent.test.tsx
- src/shared/typeguards/isStyledComponent.ts
- src/ui/components/Tag/Tag.native.test.tsx
- src/ui/components/Tag/Tag.stories.tsx
- src/ui/components/Tag/Tag.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35361
I have:
| iOS              |               |<img width="442" alt="Capture d’écran 2025-03-31 à 11 04 08" src="https://github.com/user-attachments/assets/2d8c5c35-7971-4d74-a083-15224e88d1db" /> <img width="442" alt="Capture d’écran 2025-03-31 à 11 04 48" src="https://github.com/user-attachments/assets/dcf3b51f-3e95-4592-9c5e-e866dfa6ed74" /> <img width="446" alt="Capture d’écran 2025-03-31 à 11 05 21" src="https://github.com/user-attachments/assets/e1a24916-fcaa-41e9-b8d5-1304b4854719" />|
| Android          | …
> (PC-35361) feat(offer): add interaction tag to use it in playlist

- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/getCategoriesFacetFilters.ts
To prevent future bugs in case a deprecated category is selected on Contentful
> (BSR) fix(Home): add fallback for contenful categories

- scripts/check_xcode_version.sh
> (BSR) build(Xcode): update xcode supported version check

- src/features/tutorial/enums.ts
- src/features/tutorial/pages/AgeSelectionFork.native.test.tsx
- src/features/tutorial/pages/AgeSelectionFork.tsx
- src/features/tutorial/pages/AgeSelectionOther.native.test.tsx
- src/features/tutorial/pages/EligibleUserAgeSelection.tsx
- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35391
I have:
<details>
If you …
> (PC-35391) fix(Analytics): fix missing logSelectAge

- fastlane/Fastfile
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35466
I have:
<details>
If you …
> (PC-35466) fix(CI): fastlane sentry saas hard deploy

- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33854
I have:
| Desktop - Chrome |               | <img width="512" alt="Capture d’écran 2025-04-04 à 16 46 22" src="https://github.com/user-attachments/assets/2f5bfe01-778b-4783-8776-3799d8dfc92b" /> |
| Desktop - Chrome |               | <video src="https://github.com/user-attachments/assets/80b10909-303a-471a-bc80-6e438156bce5" /> |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v= …
> (PC-33854) feat(Search): add tracker on no result cta

- src/features/offer/components/InteractionTag/getTagConfig.test.ts
- src/features/offer/components/InteractionTag/getTagConfig.tsx
- src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
- src/libs/firebase/remoteConfig/remoteConfig.constants.ts
- src/libs/firebase/remoteConfig/remoteConfig.types.ts
Ce ticket prépare l'utilisation de remote config (pour pouvoir faire évoluer les compteurs plus facilement) quand la feature sera implémentée dans les items de playlist.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35427
I have:
<details> …
> (PC-35427) feat(offer): use minLikesValue and maxLikesValue as params for getTagConfig to prepare remote config use

- src/features/bookings/components/BookingDetailsContent.tsx
- src/features/bookings/components/LinkToOffer.tsx
- src/features/bookings/components/TicketCutout.native.test.tsx
- src/features/bookings/components/TicketCutout.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35306
I have:
| iOS              | <img width="245" alt="Screenshot 2025-04-04 at 17 46 16" src="https://github.com/user-attachments/assets/3c8927de-8d09-4b71-9110-dfbcff95605b" />|![Simulator Screenshot - iPhone SE (3rd generation) - 2025-04-04 at 18 07 31](https://github.com/user-attachments/assets/d49a6976-0f92-4006-9d1f-21ce643d1a0a)|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v …
> (PC-35306) feat(BookingDetails): add link to Offer page

- .storybook/preview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35384
I have:
<details> …
> (PC-35384) fix(Storybook): fix the stories order

- .gitignore
When triggering a testing or staging hard deploy, yarn will generate versions file in the .yarn folder.
We don't want to have those files in the git history
> (BSR) build(yarn): add yarn/versions to gitignore

- .eslintrc.js
- babel.config.js
- jest.config.js
- src/store/tracking/offerPlaylistTrackingStore.test.ts
- src/store/tracking/offerPlaylistTrackingStore.ts
- src/store/tracking/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35325
Création d'un store pour permettre de stocker les informations sur les offres vues sur une page afin de pouvoir ensuite les tracker.
I have:
<details>
If you consider correcting the issue is too time consuming/complex: create a ticket. Link the …
> (PC-35325) chore(offer): offer playlist view tracking store

- src/features/offer/queries/useFetchHeadlineOffersCountQuery.ts
Problème : L'ean n'était pas pré-chargé en venant de la recherche ce qui faisait que la query se faisait sans ean donc on avait le compteur total d'offres à la une
Fix : Ajout de l'ean en dépendance de la query pour qu'elle puisse se réexécuter une fois que l'ean est chargé depuis la page offre
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35497
I have:
https://github.com/user-attachments/assets/eda89f4c-c9b5-4b29-a47f-a8dfa678ebe0
https://github.com/user-attachments/assets/eaa27421-feb0-4bab-8282-6ab4bf68ac69
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1 …
> (PC-35497) feat(offer): add ean in queryKey array to refetch  headline offers count

- src/libs/firebase/remoteConfig/queries/useRemoteConfigQuery.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35479
We noticed very slow CTAs (impossible to click) on certain tasks like trying to reserve a movie.
We worked our way up the component tree: from `BookingEventChoices` (movie options modal) all the way to the `Home` by placing `console.log`s in the body of each component and observing an infinite loop.
Once in home, we created a minimal reproducible case with only one module: `VideoCarouselModule`.
To easily reproduce the issue, paste the following code as the `modules` prop of `GenericHome`:
```ts
[{
id: '5g5uj3AbY8X1COojsCMp4N',
type: 'VideoCarouselModule',
title: 'test emplacement video carousel',
color: 'Lilac',
items: [
{
id: '7ihPsS7RcX0WuLtCAJCI69',
title: 'Surprise',
youtubeVideoId: 'hkynlQWI6BI',
offerId: '1515', …
```
> (PC-35479) fix(home): infinite render loop fix add stale time to useRemoteConfigQuery

- .gitignore
To be able to keep several google-services for each env in the folder:
> (BSR) feat(gitignore): add google-services

- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/libs/analytics/logEventAnalytics.ts
Due to data demand, i am adding a  searchId parameter to the tracker logExtendSearchRadiusClicked
> (PC-33854) feat(SearchResults): add searchId to logExtendSearchRadiusClicked

- ios/Podfile.lock
- src/features/deeplinks/helpers/getScreenFromDeeplink.test.ts
- src/features/navigation/RootNavigator/rootRoutes.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/SearchStackNavigator/SearchStackNavigator.tsx
- src/features/navigation/SearchStackNavigator/searchRoutes.ts
- src/features/navigation/SearchStackNavigator/types.ts
- src/features/search/components/Buttons/FilterButton/FilterButton.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/helpers/useNavigateToSearchFilter/useNavigateToSearchFilter.ts
- src/features/search/pages/SearchFilter/SearchFilter.tsx
- src/features/search/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35529
I have:
<details>
If you …
> (PC-35529) fix(SearchFilter): revert move search filter

- .gitignore
So that sentryclirc, an important config file for sentry's config (used by fastlane) appears in the results of VS Code by default
> (BSR) chore(gitignore): don't ignore templates_github_ci/.sentryclirc

- src/libs/firebase/remoteConfig/queries/useRemoteConfigQuery.ts
L'objectif de cette PR était de vérifier le bon fonctionnement de react-query en cas d'erreur.
En utilisant useErrorBoundary: false cela permet de throw l'erreur et de la récupérer correctement dans error du useQuery sans afficher la page d'erreur.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35531
I have:
<details>
If you can't respect one of these rules, be sure to …
> (PC-35531) refactor(firebase): use throw and useErrorBoundary: false in useRemoteConfigQuery

- src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.test.ts
- src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35587
I have:
<details>
If you …
> (PC-35587) fix(OfferArtist): remove quotes from artist id filter

- .github/workflows/dev_on_workflow_tester.yml
Actuellement, le rapport Allure n'est pas généré lorsqu'au moins un des tests échoue. Cela empêche d'avoir une vue complète des tests flaky et des statistiques de test.
- Ajout de la condition `always()` dans le job `allure-report` pour qu'il s'exécute même en cas d'échec des tests
- Modification de la dépendance `needs` pour inclure à la fois `yarn_test_native` et `yarn_test_web`
- Le rapport Allure sera maintenant généré systématiquement sur la branche master, même si des tests échouent
- Meilleure visibilité sur les tests flaky
- Statistiques de test plus complètes
- Rapport unifié incluant les tests web et natifs
- Conservation de l'historique des tests même en cas d'échec
> (PC-35559) fix(allure): execute allure step even if a test failed

- src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx
- src/features/birthdayNotifications/pages/RecreditBirthdayNotification.native.test.tsx
- src/features/birthdayNotifications/pages/RecreditBirthdayNotification.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.web.test.tsx
- src/features/cookies/components/CookiesSettings.native.test.tsx
- src/features/cookies/pages/CookiesDetails.native.test.tsx
- src/features/cookies/pages/CookiesDetails.web.test.tsx
- src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.tsx
- src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx
- src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.native.test.tsx
- src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
- src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
- src/features/profile/pages/ChangeCity/ChangeCity.tsx
- src/features/profile/pages/ChangeStatus/useSubmitChangeStatus.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.tsx
- src/features/profile/pages/FeedbackInApp/FeedbackInApp.tsx
- src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
- src/features/profile/queries/useAnonymizeAccountMutation.ts
- src/features/profile/queries/useFeedbackMutation.ts
- src/features/profile/types.ts
- src/features/search/components/sections/Category/Category.native.test.tsx
- src/features/search/components/sections/Price/Price.native.test.tsx
- src/features/subscription/helpers/useThematicSubscription.tsx
- src/features/subscription/page/OnboardingSubscription.tsx
- src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.native.test.ts
- src/libs/utm/getUtmParamsConsent.native.test.ts
- src/queries/profile/usePatchProfileMutation.ts
- src/queries/profile/useResetRecreditAmountToShowMutation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34760
Refactor des queries dans `features/profile`
Certains hooks ont été bougé dans le dossier global `src/queries`
I have:
<details>
- …
> (PC-34760) refactor(profile): queries

- src/features/errors/pages/AsyncErrorBoundary.native.test.tsx
- src/features/home/components/modules/exclusivity/ExclusivityOffer.native.test.tsx
- src/features/home/components/modules/video/VideoPlayer.native.test.tsx
- src/features/identityCheck/components/modals/DMSModal.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx
- src/features/identityCheck/pages/profile/SetAddress.web.test.tsx
- src/features/location/components/LocationSearchWidget.native.test.tsx
- src/features/location/components/LocationWidgetDesktop.native.test.tsx
- src/features/profile/components/EmptyCredit/EmptyCredit.native.test.tsx
- src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx
- src/features/profile/components/Modals/DeleteProfileReasonNewEmailModal.native.test.tsx
- src/features/profile/components/Modals/ExpiredCreditModal.native.test.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.native.test.tsx
- src/features/profile/pages/FeedbackInApp/FeedbackInApp.native.test.tsx
- src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx
- src/features/share/components/MessagingApps/InstalledMessagingApps.native.test.tsx
- src/features/subscription/NotificationsLoggedOutModal.native.test.tsx
- src/features/subscription/components/modals/OnboardingSubscriptionModal.native.test.tsx
- src/features/subscription/components/modals/SubscriptionSuccessModal.native.test.tsx
- src/features/trustedDevice/pages/SuspiciousLoginSuspendedAccount.native.test.tsx
- src/features/tutorial/components/profileTutorial/EligibleFooter.native.test.tsx
- src/features/tutorial/pages/TutorialPage.native.test.tsx
- src/features/venue/components/TabLayout/TabLayout.native.test.tsx
- src/features/venue/components/VenueMessagingApps/VenueMessagingApps.native.test.tsx
I have:
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be …
> (BSR) refactor(tests): use userEvent instead of fireEvent

- src/features/offer/components/OfferContent/StickyFooterContent/StickyFooterContentBase.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35409
I have:
| iOS              |               | <img src="https://github.com/user-attachments/assets/9b75827d-50a3-488a-baf6-f7a069adb3a6" /> |
| Android          |               | <img src="https://github.com/user-attachments/assets/12316660-e887-43e4-896f-e9fb875fa452" />  |
<details> …
> (PC-35409) fix(Offer): fix ui on coming soon footer

- src/features/venue/components/VenueOffers/VenueOffersList.tsx
- src/ui/components/Avatar/Avatar.tsx
- src/ui/components/Avatar/AvatarList.native.test.tsx
- src/ui/components/Avatar/AvatarList.tsx
- src/ui/components/Avatar/AvatarListItem.native.test.tsx
- src/ui/components/Avatar/AvatarListItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35715
Ajout d'un prop `avatarConfig` au composant `AvatarList` pour plus de flexibilité dans la configuration des avatars
I have: …
> (PC-35715) refactor(AvatarList): add avatar config prop

- doc/decision-records/DR003 - queries.md
- src/features/home/api/helpers/mapOffersDataAndModules.ts
- src/features/home/api/useActivationBanner.native.test.ts
- src/features/home/api/useActivationBanner.ts
- src/features/home/api/useAlgoliaRecommendedOffers.native.test.ts
- src/features/home/api/useAlgoliaRecommendedOffers.ts
- src/features/home/api/useBanner.ts
- src/features/home/api/useExcluOffer.ts
- src/features/home/api/useGetOffersData.ts
- src/features/home/api/useHomeRecommendedOffers.ts
- src/features/home/api/useVideoOffers.native.test.ts
- src/features/home/api/useVideoOffers.ts
- src/features/home/components/modules/HomeModule.native.test.tsx
- src/features/home/components/modules/exclusivity/ExclusivityModule.native.test.tsx
- src/features/home/components/modules/exclusivity/ExclusivityOffer.native.test.tsx
- src/features/home/components/modules/exclusivity/helpers/useShouldDisplayExcluOffer.native.test.ts
- src/features/home/components/modules/exclusivity/helpers/useShouldDisplayExcluOffer.ts
- src/features/home/components/modules/video/VideoModule.native.test.tsx
- src/features/home/components/modules/video/VideoModule.tsx
- src/features/home/pages/GenericHome.tsx
Revert "(PC-35599) refactor(react-query): use react-query in home (#7993)"
This reverts commit e54ca3f0ab612fc9ebc0ca3de224404cfd0f3407.
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258 …
> (BSR) fix(pipeline): revert to fix the main branch

- src/libs/firebase/firestore/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35729
Ajout du FF `wipArtistPageInSearch` pour driver l'affichage des artistes dans la recherche
I have:
<details> …
> (PC-35729) chore(firebase): add wipArtistPageInSearch feature flag

- eslint-custom-rules/no-spacer.js
- eslint-custom-rules/no-spacer.test.js
- eslint-local-rules.js
- eslint-soft-rules.js
Cette PR vise à encourager l'utilisation de styles explicites (margin, padding, gap, etc.) dans les composants React Native à la place du composant utilitaire Spacer, en introduisant une règle ESLint personnalisée qui déclenche un warning à chaque utilisation d’un Spacer.
Le composant Spacer a été introduit pour simplifier la gestion des espacements verticaux/horizontaux via une API déclarative (<Spacer.Column numberOfSpaces={2} />). Cependant, après discussion au sein de la guilde Clean Code, plusieurs limites ont été identifiées :
- *Lisibilité réduite* :
L'intention visuelle de l'espacement n'est pas toujours claire, surtout pour les nouveaux arrivants. Il faut connaître la logique derrière getSpacing() et deviner l'impact visuel.
- *Fragmentation des styles* :
Le style se retrouve …
> (BSR) feat(Eslint): add warnings on Spacer components

- jest.web.config.js
- jest/AllureFixedJSDOMEnvironment.js
https://github.com/mswjs/jest-fixed-jsdom
When merging on master, the allure env is used, so we don't benefit from the fixes above.
In this PR we combine the allure env with the fixed env
> (BSR) fix(msw): web tests

- .vscode/settings.json
Certains développeurs se sont récemment plaint d'une disparité entre les résultats de la commande yarn:test:types et les erreurs Typescript indiquées dans l'IDE
Actuellement la version Typescript utilisée dans l'IDE est celle définie dans l'IDE par le développeur, l'ajout de cette ligne dans le `settings.json` palie à cela en autorisant l'apparition d'une popup (bloquée par défaut) proposant l'utilisation de la version Typescript du package.json dans l'IDE
> (BSR) fix(Typescript): match typescript vscode version with package.json version

- __snapshots__/features/identityCheck/pages/identification/errors/eduConnect/NotEligibleEduConnect.native.test.tsx.native-snap
- src/libs/styled/ThemeWrapper.tsx
- src/libs/styled/native/ThemeProvider.tsx
- src/libs/styled/useColorScheme.native.test.ts
- src/libs/styled/useColorScheme.tsx
- src/libs/styled/useComputedTheme.ts
- src/tests/computedTheme.tsx
- src/theme/index.ts
- src/ui/components/BlurView.tsx
- src/ui/components/headers/BlurHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35727
Description : En vue de la préparation et de la réfactorisation du theme pour le dark mode. 
Dans un premier temps réaliser un store de colorScheme afin de pouvoir récupérer et set la valeur du theme partout dans l'app en ajoutant cette option de persistance dans l'app. 
I have:
[1]: …
> (PC-35727) feat(DS): add color scheme store

- src/features/cookies/helpers/setMarketingParams.native.test.ts
- src/features/internal/components/DeeplinksGeneratorForm.tsx
- src/features/search/helpers/categoriesHelpers/mapping-tree.ts
- src/features/share/helpers/getShareOffer.tsx
- src/features/venueMap/helpers/venueMapCluster/getClusterColorByDominantVenueType.ts
- src/libs/analytics/utils.ts
- src/types.ts
Object.keys n'est nativement pas strictement typé, ce qui fait perdre le type dans des clés dans des objets inférés ou `as const`
Cette PR apporte un typage strict sur l'utilisation d'`Object.keys`
> (BSR) refactor(ObjectType): strict type Object.keys

- src/features/search/api/useSearchResults/useSearchResults.native.test.ts
- src/features/search/api/useSearchResults/useSearchResults.ts
- src/features/search/components/SearchList/SearchList.native.test.tsx
- src/features/search/components/SearchList/SearchList.web.test.tsx
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/offerAttributesToRetrieve.ts
- src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.test.ts
- src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.ts
- src/libs/algolia/fixtures/algoliaFixtures.ts
- src/shared/offer/getSimilarOrRecoOffersInOrder.test.ts
- src/shared/offer/offer.fixture.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35716
Prise en compte des artistes dans les résultats de recherche.
EDIT : Après discussion, on oublie la multi-query Algolia, à la place on crée une liste d'artistes à partir des offres récupérées.
I have:
<details>
If you consider correcting the …
> (PC-35716) feat(search): add artists in search multi-query

- .envrc
```txt
WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
Consider adding the following to ~/.profile:
export LANG=en_US.UTF-8
```
> (BSR) chore(ios): avoid CocoaPods warning

- .envrc
- .vscode/settings.json
- doc/installation/Android.md
- flake.nix
- package.json
> (BSR) chore(ios): fix iOS CLI

- jest.config.js
- jest.web.config.js
Les développeurs ont besoin de pas mal de scroll sur les ci de test à cause du rapport de coverage qui prend énormément de lignes.
Le coverage reste mais n'est plus loggé dans la console de ci
> (BSR) feat(ci): remove coverage logs

- src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
- src/libs/firebase/remoteConfig/remoteConfig.constants.ts
- src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35832
I have:
<details>
If you …
> (PC-35832) refactor(RemoteConfig): remove unused code

- __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35822
I have:
<details> …
> (PC-35822) refactor(SearchResults): moove Dates button

- src/libs/firebase/firestore/featureFlags/useFeatureFlagOptions.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35806
Method:
- Find cinema offer with options
- Start profiling
- Click on a time for a movie
- Opens a modal
- Close the modal
- Stop profiling
As we can see above, a big part of the app would render and it would happen several times during the profiling session described above.
I have:
[1]: …
> (PC-35806) perf(render): reduce renders by increasing staleTime FFs

- src/features/profile/pages/ChangeEmail/ChangeEmailExpiredLink.native.test.tsx
- src/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.native.test.tsx
- src/features/profile/pages/ChangePassword/ChangePassword.native.test.tsx
- src/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx
- src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx
- src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx
- src/features/profile/pages/NewEmailSelection/NewEmailSelection.native.test.tsx
- src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35813
I have:
<details> …
> (PC-35813) refactor(test): replace fireEvent.press by userEvent.press

- scripts/install_certificate_java.sh
- scripts/is_proxy_enabled.sh
I had red that to check if a bash variable is not empty we should do
```sh
if [ -n "${variable+x}" ]; then
```
the `+x` should be here to not fail if `set -o nounset` and the variable is not defined
in our case, the variables are defined
if the `+x` is added, the condition is resolved as not empty
but it was a mistake
to check if a variable is empty we should do
```sh
if [ -z "${variable+x}" ]; then
```
it seems that the `+x` should not be added for `-n`
this better handling than #7799
> (BSR) chore(setup): better proxy handling

- ios/Podfile.lock
There was an issue in a PR that included an old podfile:
https://github.com/pass-culture/pass-culture-app-native/pull/8039/commits/226308601f12d0a7afec5378850ed5c0b700e114#diff-b7d85c35701918f25c9b2c418249f9b66fd9b067676e295a9eff493b73ee1752
> (BSR) fix(Podfile): RN 0.73 Podfile

- src/features/search/helpers/getMarkedDates/getMarkedDates.test.ts
- src/features/search/helpers/getMarkedDates/getMarkedDates.ts
- src/features/search/helpers/getPastScrollRange/getPastScrollRange.test.ts
- src/features/search/helpers/getPastScrollRange/getPastScrollRange.ts
- src/features/search/helpers/schema/calendarSchema/calendarSchema.test.ts
- src/features/search/helpers/schema/calendarSchema/calendarSchema.ts
- src/features/search/pages/modals/CalendarModal/CalendarModal.native.test.tsx
- src/features/search/pages/modals/CalendarModal/CalendarModal.tsx
- src/features/search/types.ts
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildNumericFilters.ts
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildOfferSearchParameters.ts
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildNumericFiltersHelpers/buildNumericFiltersHelpers.test.ts
- src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildNumericFiltersHelpers/buildNumericFiltersHelpers.ts
- src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35834
I have:
| iOS              |![Capture d’écran 2025-04-29 à 11 19 09](https://github.com/user-attachments/assets/090e65c6-d7c4-4740-bf8d-00ca2a811554)|<img width="421" alt="Capture d’écran 2025-04-28 à 15 35 42" src="https://github.com/user-attachments/assets/52220002-41b3-4758-a552-e70261d9d7b9" />|
| Android          |               |<img width="431" alt="Capture d’écran 2025-04-28 à 15 35 32" src="https://github.com/user-attachments/assets/90a0516f-e9c1-4d58-8f6a-ca59b6fabffa" />| …
> (PC-35834) feat(search): add calendar modal

- __snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap
- __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
- knip.ts
- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/components/sections/CalendarFilter/CalendarFilter.native.test.tsx
- src/features/search/components/sections/CalendarFilter/CalendarFilter.tsx
- src/features/search/components/sections/index.ts
- src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx
- src/features/search/pages/SearchFilter/SearchFilter.tsx
- src/features/search/pages/modals/CalendarModal/CalendarModal.native.test.tsx
- src/features/search/pages/modals/CalendarModal/CalendarModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35835
I have:
| iOS              |![Capture d’écran 2025-04-30 à 15 08 00](https://github.com/user-attachments/assets/9534a475-7680-4f0d-bbde-45d14219d027)|![Capture d’écran 2025-04-30 à 15 02 03](https://github.com/user-attachments/assets/8cf06ffa-0738-4f97-a608-94686be1831c) ![Capture d’écran 2025-04-30 à 15 01 48](https://github.com/user-attachments/assets/7012dced-9e00-4453-b266-259fdb1fb76d) ![Capture d’écran 2025-04-30 à 15 01 27](https://github.com/user-attachments/assets/40041545-5723-4327-a329-62533ce28177) …
> (PC-35835) feat(search): use calendar modal in dates filter when wipTimeFilterV2 FF activated

- src/features/search/components/SearchList/SearchList.web.test.tsx
- src/features/search/components/SearchList/SearchList.web.tsx
- src/features/search/components/SearchListHeader/SearchListHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35237
I have:
| Phone - Chrome   |![Screenshot 2025-04-30 at 17 06 36](https://github.com/user-attachments/assets/8d649b94-93c6-41ea-934e-bf68d641744f)|![Screenshot 2025-04-30 at 17 06 20](https://github.com/user-attachments/assets/6211fa91-122a-45f0-96a1-dc31db3a5a71)|
<details> …
> (PC-35237) fix(SearchResults): better handle of searchresults header height on web app mobile view

- __snapshots__/features/onboarding/pages/onboarding/OnboardingGeolocation.native.test.tsx.native-snap
- src/features/onboarding/pages/onboarding/OnboardingGeolocation.native.test.tsx
- src/features/onboarding/pages/onboarding/OnboardingGeolocation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36023
Apple reject 338.1 because the design of the location dialog box include a button "Passer" and the label of the main button is not "Continuer".
So we change all this.
I have:
[2]: …
> (PC-36023) feat(location): to be compliant with apple design for location dialog boxes

- __snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
- src/features/search/components/SearchList/SearchList.tsx
- src/features/search/components/SearchList/SearchList.web.tsx
- src/features/search/components/SearchListHeader/ArtistSection.tsx
- src/features/search/components/SearchListHeader/SearchListHeader.tsx
- src/features/search/components/SearchListItem.web.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/features/search/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35833
I have:
<details> …
> (PC-35833) feat(search): trigger ConsultArtist log when pressing item on artists playlist + refacto

- src/cheatcodes/components/CrashTestButton.native.test.tsx
- src/features/search/pages/SuggestedPlacesOrVenues/SuggestedVenues.native.test.tsx
- src/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx
- src/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx
- src/features/subscription/NotificationsSettingsModal.native.test.tsx
- src/features/subscription/page/OnboardingSubscription.native.test.tsx
- src/features/trustedDevice/pages/SuspensionChoice.native.test.tsx
- src/features/trustedDevice/pages/SuspensionChoiceExpiredLink.native.test.tsx
- src/features/venue/components/ContactBlock/ContactBlock.native.test.tsx
- src/features/venue/components/VenueThematicSection/VenueThematicSection.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
- src/shared/forms/controllers/EmailInputController.native.test.tsx
- src/shared/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx
- src/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx
- src/ui/components/Accordion.native.test.tsx
- src/ui/components/SectionRowContent.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35976
I have:
<details>
If you …
> (PC-35976) test(app): replace some fireEvent.press by userEvent.press

- src/features/artist/components/ArtistBody/ArtistBody.native.test.tsx
- src/features/artist/pages/Artist.native.test.tsx
- src/features/artist/pages/Artist.tsx
- src/features/home/api/useAlgoliaRecommendedOffers.ts
- src/features/offer/components/MoviesScreeningCalendar/VenueCalendar.tsx
- src/features/offer/components/OfferBody/OfferBody.native.test.tsx
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/components/OfferCine/OfferCineContent.native.test.tsx
- src/features/offer/components/OfferCine/OfferCineContent.tsx
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.web.test.tsx
- src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.test.ts
- src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.ts
- src/features/offer/pages/Offer/Offer.native.test.tsx
- src/features/offer/pages/Offer/Offer.perf.test.tsx
- src/features/offer/queries/useArtistResultsQuery.native.test.ts
- src/features/offer/queries/useArtistResultsQuery.ts
- src/features/offer/queries/useFetchOffersQuery.ts
- src/features/offer/queries/useOffersStocksFromOfferQuery.native.test.ts
- src/features/offer/queries/useOffersStocksFromOfferQuery.ts
- src/features/offer/queries/useOffersStocksQuery.native.test.ts
- src/features/offer/queries/useOffersStocksQuery.ts
- src/features/offer/queries/useSimilarOffersQuery.native.test.ts
- src/features/offer/queries/useSimilarOffersQuery.ts
- src/queries/offer/useAlgoliaSimilarOffersQuery.native.test.ts
- src/queries/offer/useAlgoliaSimilarOffersQuery.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36045
I have:
<details>
If you …
> (PC-36045) refactor(Offer): querify query functions

- src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.tsx
- src/features/search/components/AutocompleteVenueItem/AutocompleteVenueItem.tsx
- src/features/search/components/Highlight/Highlight.native.test.tsx
- src/features/search/components/Highlight/Highlight.tsx
- src/features/search/components/SearchHistoryItem/SearchHistoryItem.tsx
- src/features/search/helpers/decodeHTMLValue/decodeHTMLValue.test.ts
- src/features/search/helpers/decodeHTMLValue/decodeHTMLValue.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35836
I have:
<details>
If you …
> (PC-35836) fix(HighLight): correct display for ascii code &

- src/features/bookings/components/BookingPrecision.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35759
I have:
| Phone - Chrome   |<img width="222" alt="Screenshot 2025-05-12 at 17 35 22" src="https://github.com/user-attachments/assets/a82d40c0-d37a-439f-a0e6-aa05bd2a3b61" />|<img width="347" alt="Screenshot 2025-05-12 at 17 22 23" src="https://github.com/user-attachments/assets/7a3d1ecb-ec38-46bc-ad32-7b6c146a09c1" />|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe472587014 …
> (PC-35759) fix(BookingDetails): email on two lines if small screen

- scripts/install_certificate_java.sh
> (BSR) fix(android): uncomment remove_certificate_safe in install_certificate_java

- __snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx.native-snap
- src/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx
- src/features/accessibility/components/AccessibilityFiltersModal.tsx
- src/features/search/components/FilterPageButtons/FilterPageButtons.tsx
- src/features/search/components/SearchFixedModalBottom.tsx
- src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx
- src/features/search/pages/SearchFilter/SearchFilter.tsx
- src/features/search/pages/modals/CalendarModal/CalendarModal.native.test.tsx
- src/features/search/pages/modals/CalendarModal/CalendarModal.tsx
- src/features/search/pages/modals/CalendarModal/CalendarModal.web.test.tsx
- src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx
- src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
- src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx
- src/features/search/pages/modals/OfferDuoModal/OfferDuoModal.tsx
- src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx
- src/features/search/pages/modals/PriceModal/PriceModal.tsx
- src/features/search/pages/modals/VenueModal/VenueModal.tsx
- src/features/search/pages/modals/VenueModal/type.ts
- src/features/search/pages/modals/VenueModal/useVenueModal.native.test.tsx
- src/features/search/pages/modals/VenueModal/useVenueModal.ts
- src/ui/components/Form.tsx
- src/ui/components/Form.web.tsx
L'objectif de cette PR est d'améliorer et d'harmoniser l'utilisation des filtres dans la recherche :
- Le bouton Réinitialiser est désactivé quand il n'y aucun filtre d'appliqué
- Le bouton Réinitialiser permet d'exécuter directement la recherche sans passer par le bouton Rechercher (comme pour le filtre des prix)
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36097
I have:
https://github.com/user-attachments/assets/97840a90-972a-4d4c-a385-4f6f32b23e84
Capture avec le lundi en 1er jour de semaine (fait après la vidéo) :
[2]: …
> (PC-36097) refactor(search): improve filter modals

- .eslintrc.js
- eslint-custom-rules/boundaries-rule.js
- eslint-soft-rules.js
- package.json
- yarn.lock
Cette nouvelle règle permet de signaler si une query est dans un dossier feature dans laquelle elle ne devrait pas être:
```ts
import { useGTLPlaylistsQuery } from 'features/gtlPlaylist/queries/useGTLPlaylistsQuery'
```
✅  utilisé seulement dans `features/gtlPlaylist`
❌  utilisé dans `features/gtlPlaylist` et `features/offer`, doit être déplacé dans `src/queries`
> (BSR) refactor(ESLint): create a rule to not import a query of a different feature

- src/features/offer/helpers/getIsFreeOffer/getIsFreeOffer.native.test.ts
- src/features/offer/helpers/getIsFreeOffer/getIsFreeOffer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35936
I have:
<details>
If you …
> (PC-35936) fix(IsFreeOffer): change behavior of isFreeOffer

- .github/workflows/dev_on_push_workflow_main.yml
Fix du workflow qui ne se lance pas car le job top level n'a pas les bonnes permissions : https://github.com/pass-culture/pass-culture-app-native/actions/runs/15137419371
> (IC-185) ci(allure): fix permissions for github_token

- .github/workflows/dev_on_push_workflow_main.yml
- .github/workflows/dev_on_workflow_tester.yml
To publish allure report we also need to be able to push on the repo so I'm adding permisisons to the github token
> (IC-185) ci(allure): allow github_token to push on repo

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36242
I have:
<details>
If you …
> (PC-36242) chore(deps): upgrade patch-package

- src/features/home/api/useHomepageData.ts
- src/features/home/queries/useGetHomepageListQuery.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36205
I have:
<details>
If you …
> (PC-36205) refactor(home): extract hook to queries

- .github/dependabot.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36311
I have:
<details>
If you …
> (PC-36311) chore(ci): add e2e label to Dependabot PR

- .eslintrc.js
- eslint-soft-rules.js
- src/features/auth/pages/signup/SignupForm.native.test.tsx
- src/features/bookings/components/OldBookingDetails/BookingDetailsCancelButton.native.test.tsx
- src/features/home/components/SubscribeButtonWithModals.native.test.tsx
- src/features/home/components/modules/video/VideoCarouselModule.native.test.tsx
- src/features/home/components/modules/video/VideoEndView.native.test.tsx
- src/features/location/components/HomeLocationModal.native.test.tsx
- src/features/location/components/SearchLocationModal.native.test.tsx
- src/features/location/components/VenueMapLocationModal.native.test.tsx
- src/features/offer/components/OfferArtists/OfferArtists.native.test.tsx
- src/features/offer/components/OfferCTAButton/OfferCTAButton.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36326
I have:
<details> …
> (PC-36326) test(app): manage last fireEvent.press + change rule configuration

- eslint-custom-rules/no-theme-colors.js
- eslint-custom-rules/no-theme-colors.test.js
- eslint-local-rules.js
- eslint-soft-rules.js
Cette règle permet a pour but de faciliter la mise en place du dark mode.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36357
I have:
<details> …
> (PC-36357) feat(eslint): add soft rule to avoid theme.colors use

- jest.config.js
- jest.web.config.js
- package.json
- src/ui/components/Avatar/Avatar.tsx
- src/ui/components/Ul.tsx
- src/ui/pages/GenericOfficialPage.tsx
- yarn.lock
https://yarnpkg.com/cli/dedupe
After running `yarn dedupe` I had to make the following adjustments:
TYPING ISSUES:
- issues on: Avatar.tsx, Ul.tsx, GenericOfficialPage.tsx.
- hypotheses: after version consolidation, the version of @types/react now used on the project doesn't allow fragments with only 1 child.
- fix: remove fragments with 1 child.
BROWSERSLIST ISSUE:
- test error: "TypeError: _browserslist.findConfigFile is not a function"
- fix: I removed browserslist from resolutions in package.json
ALGOLIA TEST ISSUE:
- test error: "SyntaxError: Unexpected token 'export'"
- after version consolidation the new state of node modules includes a version or resolution path for search-insights that Jest isn't configured to transpile by default. 
- fix: in the jest config, change `transform` …
> (BSR) chore(yarn): dedupe

- src/features/search/pages/modals/CalendarModal/CalendarModal.tsx
Un bug a été repéré par @cedricls1 après la MAJ de [](https://github.com/pass-culture/pass-culture-app-native/pull/8205)
| Phone - Chrome   |<img width="390" alt="Capture d’écran 2025-06-05 à 10 43 22" src="https://github.com/user-attachments/assets/fd1e8598-c9f8-4cf8-b2b2-829f1b8e9d02" />|<img width="392" alt="Capture d’écran 2025-06-05 à 10 41 16" src="https://github.com/user-attachments/assets/0a203173-810b-4e51-bf9e-0d46746c79c2" />|
| Desktop - Chrome |<img width="1120" alt="Capture d’écran 2025-06-05 à 10 42 49" src="https://github.com/user-attachments/assets/bf882526-1271-43f9-a021-fb3dc6a37cd6" />|<img width="1121" alt="Capture d’écran 2025-06-05 à 10 42 01" …
> (BSR) fix(Calendar): fix width after react-native-calendar update

- src/features/bookings/components/BookingDetailsContentMobile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34311
I have:
| iOS              |    ![simulator_screenshot_A3DC709D-06AD-4D5C-BACC-0514944F0233](https://github.com/user-attachments/assets/2014b1af-824e-4f74-adba-5a679cb87a62) |   ![Simulator Screenshot - iPhone 16 Pro - 2025-06-05 at 12 00 44](https://github.com/user-attachments/assets/58e58d19-933f-48b5-a737-4a08ee918c41) |
| Android          |  <img width="333" alt="Screenshot 2025-06-05 at 11 28 01" src="https://github.com/user-attachments/assets/87a3c70d-e9f0-4362-acee-2d90e9ce4f54" /> |<img width="331" …
> (PC-34311) fix(BookingDetails): missing margins in native

- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- src/features/venue/components/PracticalInformation/PracticalInformation.native.test.tsx
- src/features/venue/components/PracticalInformation/PracticalInformation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36444
I have:
| Desktop - Chrome |  ![Screenshot 2025-06-06 at 10 51 59](https://github.com/user-attachments/assets/2ae12d5d-af20-4b7b-804d-ad5ec3927410)  |  ![Screenshot 2025-06-06 at 10 51 36](https://github.com/user-attachments/assets/3a6ffc48-3e40-4537-9d28-3a25b22e8b04)|
<details> …
> (PC-36444) feat(VenuePage): should not display accessibility information when venue is not open to public

- doc/plan-archi.md
Link to JIRA ticket: https://passculture.atlassian.net/browsePC-36145
I have:
<details>
If you …
> (PC-36145) docs(docs): add architecture plan in docs

- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.native.test.tsx
- src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.tsx
- src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.native.test.ts
- src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.ts
- src/features/venue/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36329
I have:
| Desktop - Chrome |     ![Capture d’écran 2025-06-10 à 15 30 06](https://github.com/user-attachments/assets/790bf490-7024-4a7c-a6df-35da9543d93b)    |   ![Capture d’écran 2025-06-10 à 15 30 16](https://github.com/user-attachments/assets/77480d6a-f5f8-4119-9f87-e51fc71a6d50)  |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887 …
> (PC-36329) feat(venue): Hide hour label when no opening hours

- knip.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35779
I have:
<details>
If you …
> (PC-35779) fix(knip): booking list

- src/ui/components/CollapsibleText/CollapsibleText.tsx
- src/ui/components/CollapsibleText/CollapsibleTextBody/CollapsibleTextBody.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33655
Fix sur un problème d'affiche du CollapsibleText côté web.
I have:
<details> …
> (PC-33655) fix(CollapsibleText): web calculations

- __snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- __snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
- __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/IdentificationFork.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/identification/educonnect/EduConnectForm.web.test.tsx.web-snap
- __snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx.native-snap
- __snapshots__/features/identityCheck/pages/profile/SetName.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/DeleteProfile/DeleteProfileAccountHacked.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/NewEmailSelection/NewEmailSelection.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/TutorialAgeInformationCredit/ProfileTutorialAgeInformationCredit.native.test.tsx.native-snap
- __snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap
- __snapshots__/features/trustedDevice/pages/AccountSecurity.native.test.tsx.native-snap
- src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.tsx
- src/ui/components/ModuleBanner/BannerWithBackground.tsx
- src/ui/components/banners/ErrorBanner.tsx
- src/ui/components/banners/GenericColoredBanner.stories.tsx
- src/ui/components/banners/GenericColoredBanner.tsx
- src/ui/components/banners/InfoBanner.tsx
- src/ui/components/banners/WarningBanner.stories.tsx
- src/ui/components/banners/WarningBanner.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36424
I have:
| Desktop - Chrome |               |        |
<details>
If you …
> (PC-36424) refactor(ui): use design token for Banners

- src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx
- src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36422
Add null check for expiration timestamp in email validation and also validate token and device info.
Added the cleanup of the timer created by delayedReplace
I have:
[2]: …
> (PC-36422) fix(typeerror): type error due to unsetted variable

- src/libs/analytics/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36407
Fix sur le logPerformSearch qui n'envoyait pas le paramètre `searchDate`
I have:
<details> …
> (PC-36407) fix(tracking): log perform search date filters

- vite.config.js
Fix `yarn build:testing` broken after `react-native@0.75`
> (BSR) fix(vite): fix build with react-native-reanimated

- __snapshots__/features/auth/pages/suspendedAccount/FraudulentSuspendedAccount/FraudulentSuspendedAccount.native.test.tsx.native-snap
- __snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
- src/features/auth/pages/suspendedAccount/FraudulentSuspendedAccount/FraudulentSuspendedAccount.tsx
- src/features/bookOffer/components/Calendar/DayComponent.tsx
- src/features/bookOffer/components/Calendar/DiagonalStripe.tsx
- src/features/bookings/components/OldBookingDetails/ThreeShapesTicket.tsx
- src/features/bookings/helpers/useReactionIcon/useReactionIcon.tsx
- src/features/location/components/LocationWidgetWrapperDesktop.tsx
- src/features/navigation/RootNavigator/withWebWrapper.web.tsx
- src/features/navigation/TabBar/TabBarContainer.tsx
- src/features/offer/components/OfferBody/ProposedBySection/ProposedBySection.tsx
- src/features/offer/components/OfferContent/StickyFooterContent/StickyFooterContentBase.tsx
- src/features/search/components/SelectionLabel/SelectionLabel.tsx
- src/libs/itinerary/components/SeeItineraryButton.tsx
- src/ui/components/headers/HeaderWithImage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36608
I have:
<details>
If you …
> (PC-36608) feat(ui): use design token in some components

- src/features/venue/queries/useVenueQuery.native.test.ts
- src/features/venue/queries/useVenueQuery.ts
onError est exécutée à la fin du cycle de la requête. À ce moment, l’erreur est déjà gérée par React Query. Si on throw à ce moment, on crée une deuxième erreur asynchrone que React Query ne gère pas et Sentry la capture.
=> Du coup j'ai à peu près repris le code tel qu'il était avant la refacto de Xavier
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36419
I have:
| Desktop - Chrome |<img width="1721" alt="Capture d’écran 2025-06-23 …
> (PC-36419) fix(venue): avoid to catch Sentry error

- src/libs/analytics/utils.ts
- src/libs/firebase/analytics/utils.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36407
I have:
<details>
If you …
> (PC-36407) fix(tracking): logPerformSearch date filters

- src/features/identityCheck/components/AddressOption.tsx
- src/features/identityCheck/pages/profile/SetAddress.native.test.tsx
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/libs/place/fetchAddresses.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36320
I have:
| Phone - Chrome   |               |    ![Capture d’écran 2025-06-27 à 16 12 23](https://github.com/user-attachments/assets/35dbcce8-fa8e-46d8-80d8-04d887671408)  |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25 …
> (PC-36320) feat(identityCheck): update suggested address in SetAddress

- src/features/chronicle/adapters/offerChroniclesToChronicleCardData/offerChroniclesToChronicleCardData.test.ts
- src/features/chronicle/adapters/offerChroniclesToChronicleCardData/offerChroniclesToChronicleCardData.ts
- src/features/chronicle/api/useChronicles/useChronicles.test.ts
- src/features/chronicle/components/ChronicleCard/ChronicleCard.stories.tsx
- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardList.web.tsx
- src/features/chronicle/components/ChronicleCardList/ChronicleCardListBase.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
- src/features/offer/adapters/chroniclePreviewToChronicleCardData.test.ts
- src/features/offer/adapters/chroniclePreviewToChronicleCardData.ts
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSection.web.tsx
- src/features/offer/components/OfferContent/ChronicleSection/ChronicleSectionBase.tsx
- src/features/offer/components/OfferContent/ChronicleSection/types.ts
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.test.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/constant.tsx
- src/features/offer/fixtures/chronicleVariantInfo.ts
- src/features/offer/helpers/chronicleVariant/chronicleVariant.native.test.ts
- src/features/offer/helpers/chronicleVariant/chronicleVariant.ts
- src/features/offer/pages/Offer/Offer.native.test.tsx
- src/features/offer/pages/Offer/Offer.tsx
- src/features/offer/types.ts
- src/shared/chronicle/getChronicleCardTitle/getChronicleCardTitle.test.ts
- src/shared/chronicle/getChronicleCardTitle/getChronicleCardTitle.ts
- src/ui/svg/CineClubCertification.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36672
I have:
<details> …
> (PC-36672) feat(Chronicles): refacto and add Ciné club

- src/features/chronicle/helpers/isBookClubSubcategory.test.ts
- src/features/chronicle/helpers/isBookClubSubcategory.ts
- src/features/chronicle/pages/Chronicles/Chronicles.web.test.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
- src/features/offer/components/OfferCine/OfferCineBlock.tsx
- src/features/offer/components/OfferContent/ChronicleSection/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36679
I have:
https://github.com/user-attachments/assets/fe766dff-5949-42e8-971b-28294649f0c1
| Phone - Chrome   |               |<img width="375" alt="Capture d’écran 2025-07-07 à 14 19 11" src="https://github.com/user-attachments/assets/9fbd9afb-fd4b-433f-b71a-292aa11c091f" />|
| Desktop - Chrome |               |<img width="1724" alt="Capture d’écran 2025-07-07 à 14 19 01" …
> (PC-36679) feat(offer): scroll to cine sessions part when navigate from chronicles session button

- src/features/bookings/components/Ticket/Ticket.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/ExternalBookingTicket.native.test.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/ExternalBookingTicket.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/HiddenExternalBookingTicket.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/TicketSwiper.native.test.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/TicketSwiper.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/TicketSwiperControls.native.test.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/TicketSwiperControls.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/getHiddenQRCodeTextInfos.ts
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/getTickets.test.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/getTickets.tsx
- src/features/bookings/components/Ticket/TicketBottomPart/ExternalBookingTicket/index.ts
- src/features/bookings/components/Ticket/TicketBottomPart/TicketBottomPart.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36690
Sonarcloud n'est pas content pour des problèmes de couverture de code, mais le code va être refacto dans le ticket [suivant](https://passculture.atlassian.net/browse/PC-36879) donc on merge en l'état. 
I have:
[2]: …
> (PC-36690) feat(BookingDetails): add external bookings tickets

- src/features/home/components/modules/video/YoutubePlayer/YoutubePlayer.tsx
- src/features/navigation/RootNavigator/RootStackNavigator.tsx
- src/features/navigation/RootNavigator/linking/rootStackNavigatorPathConfig.ts
- src/features/navigation/RootNavigator/types.ts
- src/features/navigation/screenParamsUtils.ts
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/components/OfferImageContainer/OfferImageContainer.tsx
- src/features/offer/components/OfferImageContainer/OfferImageContainer.web.tsx
- src/features/offer/components/OfferImageContainer/OfferImageRenderer.tsx
- src/features/offer/fixtures/videoDataFixture.ts
- src/features/offer/pages/Offer/Offer.tsx
- src/features/offer/pages/OfferVideoPreview/OfferVideoPreview.native.test.tsx
- src/features/offer/pages/OfferVideoPreview/OfferVideoPreview.tsx
- src/ui/components/buttons/ButtonTertiaryBlack.ts
- src/ui/svg/icons/Play.tsx
Ajout du bouton Voir la vidéo sur la page offre + interaction du bouton qui ouvre une nouvelle page avec la vidéo associée à l'offre.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36869
I have:
| iOS              |<img width="296" alt="Capture d’écran 2025-07-08 à 17 46 00" src="https://github.com/user-attachments/assets/e096f232-8236-4dc3-aaf4-f1e25c7766a4" /> <img width="297" alt="Capture d’écran 2025-07-08 à 17 46 08" src="https://github.com/user-attachments/assets/172e5fc7-ca21-4d4a-92be-5ae16c3ad92f" />|<img width="423" alt="Capture d’écran 2025-07-08 à 17 …
> (PC-36869) feat(offer): add offer video preview page

- src/features/chronicle/pages/Chronicles/Chronicles.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
- src/features/chronicle/pages/Chronicles/ChroniclesBase.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36922
I have:
Web :
https://github.com/user-attachments/assets/d85a50f5-3051-46fc-b898-885a756367f9
iOS :
https://github.com/user-attachments/assets/5988cffa-affb-446e-b22c-3fa8916dba7f
<details> …
> (PC-36922) fix(chronicle): web redirection to thematic home

- src/libs/analytics/utils.ts
- src/libs/firebase/analytics/utils.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36928
Cette PR refactore la gestion du formatage des dates dans src/libs/analytics/utils.ts pour utiliser la fonction utilitaire existante formatDateToISOStringWithoutTime (présente dans libs/parsers/formatDates).
L'objectif est d'éviter la duplication de logique et d'assurer la cohérence du formatage des dates au format YYYY-MM-DD dans tout le projet.
> (PC-36928) fix(searchFilter): send dates to iso format

- src/features/navigation/ProfileStackNavigator/ProfileStackNavigator.tsx
- src/features/profile/pages/TutorialAgeInformationCredit/ProfileTutorialAgeInformationCredit.tsx
- src/ui/components/SectionRow.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36941
Navigation was failing because of a prop conflict in the SectionRow component. When you provided both an onPress prop (for analytics) and a navigateTo prop (for navigation), the component was incorrectly passing the same function to its child component under two different names: onPress and onBeforeNavigate.
The fix was to modify the SectionRow component. When a navigateTo prop is present, the function from the onPress prop is passed down only as onBeforeNavigate.
The child component now correctly runs the onBeforeNavigate function and then proceeds with the navigation as originally intended.
I have:
| …
> (PC-36941) fix(navigation): ProfileTutorialAgeInformationCredit

- __snapshots__/features/profile/pages/ChangeAddress/ChangeAddress.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx.web-snap
- __snapshots__/features/profile/pages/ChangeStatus/ChangeStatus.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap
- src/api/gen/api.ts
- src/cheatcodes/pages/features/profile/CheatcodesNavigationProfile.tsx
- src/features/identityCheck/pages/profile/SetCity.web.test.tsx
- src/features/navigation/ProfileStackNavigator/ProfileStackNavigator.tsx
- src/features/navigation/ProfileStackNavigator/ProfileStackTypes.ts
- src/features/navigation/ProfileStackNavigator/enums.ts
- src/features/navigation/ProfileStackNavigator/profileStackNavigatorPathConfig.ts
- src/features/profile/components/CitySearchInput/CitySearchInput.tsx
- src/features/profile/components/EditableFiled/EditableField.tsx
- src/features/profile/pages/ChangeAddress/ChangeAddress.native.test.tsx
- src/features/profile/pages/ChangeAddress/ChangeAddress.tsx
- src/features/profile/pages/ChangeAddress/useSubmitChangeAddress.ts
- src/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx
- src/features/profile/pages/ChangeCity/ChangeCity.tsx
- src/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx
- src/features/profile/pages/ChangeCity/useSubmitChangeCity.ts
- src/features/profile/pages/ChangeStatus/ChangeStatus.native.test.tsx
- src/features/profile/pages/ChangeStatus/useSubmitChangeStatus.tsx
- src/features/profile/pages/PersonalData/PersonalData.native.test.tsx
- src/features/profile/pages/PersonalData/PersonalData.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36308
I have:
<details>
If you …
> (PC-36308) feat(profile): add ChangeAddress screen

- src/cheatcodes/queries/useCheatcodesFeatureFlagQuery.ts
- src/features/auth/context/SettingsContext.tsx
- src/features/favorites/hooks/useFavorite.ts
- src/features/forceUpdate/helpers/useMinimalBuildNumber.ts
- src/features/search/pages/ThematicSearch/api/useThematicSearchPlaylists.ts
- src/libs/firebase/firestore/featureFlags/useFeatureFlagOptions.ts
- src/libs/react-query/usePersistQuery.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36961
| ⚙️ Version | 🏷️ Propriété        | 📖 Description                                                                                     |
|-----------|---------------------|-----------------------------------------------------------------------------------------------------|
| v3        | `isLoading`         | Vrai lors du tout premier chargement, quand `status === 'loading'`                            |
| v3        | `isFetching`        | Vrai à chaque fetch en cours, y compris lors d’un refetch avec cache                        |
| v3        | *(Pas de `isInitialLoading`)* | -                                                                                      |
| v4        | `isLoading`         | Toujours dérivé de …
> (PC-36961) fix(app): use isInitialLoading instead of isLoading

- ios/Podfile.lock
- src/features/identityCheck/helpers/useNavigateForwardToStepper.ts
- src/features/identityCheck/pages/identification/educonnect/EduConnectValidation.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.native.test.tsx
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/SetStatus.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36997
I have:
<details>
If you …
> (PC-36997) fix(activation): fix useNavigateForwardToStepper

- src/cheatcodes/pages/features/achievements/CheatcodesNavigationAchievements.tsx
- src/features/achievements/helpers/getAchievements.ts
- src/features/achievements/pages/Achievements.tsx
- src/features/navigation/RootNavigator/linking/rootStackNavigatorPathConfig.ts
- src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36098
I have:
| Desktop - Chrome |       <img width="712" height="539" alt="Capture d’écran 2025-07-18 à 10 16 47" src="https://github.com/user-attachments/assets/d2fa8583-26ff-4a36-94fa-1ddf482afc10" />        |   <img width="739" height="529" alt="Capture d’écran 2025-07-18 à 10 17 55" src="https://github.com/user-attachments/assets/524da5be-3ece-48ae-bce7-aaf9176ec4f9" />    |
|                  |       <img width="742" height="696" alt="Capture d’écran 2025-07-18 à 10 17 16" …
> (PC-36098) fix(achievements): allow undefined 'from' queryparam for achievements page

- src/features/search/components/SearchListHeader/SearchListHeader.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37172
I have:
<details> …
> (PC-37172) feat(GridList): add tracker on gridListToggle

- src/features/offer/components/OfferContent/VideoSection/FeedBackVideo.native.test.tsx
- src/features/offer/components/OfferContent/VideoSection/FeedBackVideo.tsx
- src/features/reactions/components/ReactionChoiceModalBodyWithValidation/ReactionChoiceModalBodyWithValidation.tsx
- src/features/reactions/components/ReactionChoiceValidation/ReactionChoiceValidation.native.test.tsx
- src/features/reactions/components/ReactionChoiceValidation/ReactionChoiceValidation.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37069
I have:
https://github.com/user-attachments/assets/f53b5e63-4e88-44e3-afe6-418af1aec0da
https://github.com/user-attachments/assets/6443a2d3-adbc-4152-b1be-bbed4f5a779b
<details>
If you consider correcting the issue is too time consuming/complex: …
> (PC-37069) feat(FeedBackVideo): remove button or quiz when we leave the screen

- .eslintignore
- .eslintrc.js
- eslint-custom-rules/apostrophe-in-text.js
- eslint-custom-rules/no-theme-from-theme.js
- eslint-custom-rules/no-theme-from-theme.test.js
- eslint-local-rules.js
- src/cheatcodes/components/CodePushButton.tsx
- src/features/home/components/helpers/getVideoPlayerDimensions.ts
- src/features/identityCheck/components/IconStepCurrent.tsx
- src/features/identityCheck/components/IconStepDisabled.tsx
- src/features/identityCheck/components/IconStepDone.tsx
- src/features/identityCheck/pages/profile/StatusFlatList.tsx
- src/features/offer/components/InteractionTag/InteractionTag.tsx
- src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx
- src/features/search/helpers/getGridTileRatio.ts
- src/features/venueMap/components/VenueMapTypeFilter/VenueMapTypeFilter.tsx
- src/features/venueMap/constant.ts
- src/libs/styled/ThemeWrapper.tsx
- src/tests/computedTheme.tsx
- src/ui/components/Avatar/Avatar.tsx
- src/ui/components/ModuleBanner/GenericBanner.tsx
- src/ui/components/inputs/BaseTextInput.tsx
- src/ui/components/inputs/types.ts
- src/ui/theme/customFocusOutline/customFocusOutline.web.ts
- src/ui/theme/typography.tsx
- src/ui/theme/videoModuleColorsMapping.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36901
I have:
<details>
If you …
> (PC-36901) feat(eslint): add rule to prevent theme from theme

- ios/Podfile.lock
> (BSR) fix(amplitude): update podfile lock after removal

- src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
- src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
- src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
- src/libs/firebase/remoteConfig/remoteConfig.constants.ts
- src/libs/firebase/remoteConfig/remoteConfig.types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36195
I have:
<details> …
> (PC-36195) feat(GridList): add remote config for ab test

- README.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37125
I have:
<details>
If you …
> (PC-37125) docs(perf): add about local & ci

- doc/development/how-to/state-management.md
- package.json
- src/App.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37196
NOT NEEDED AFTER RN 0.76
Source:
https://github.com/gusgard/react-native-devsettings?tab=readme-ov-file#react-native-devsettings
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe4725870142398 …
> (PC-37196) chore(lib): remove devsettings

- .github/workflows/dev_on_workflow_tester.yml
Le cache posait problème, il s'avère que l'on en a pas besoin dans ce job.
> (BSR) fix(ci): fix allure cache

- src/features/identityCheck/pages/Stepper.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37197
Running `src/features/identityCheck/pages/Stepper.native.test.tsx` 100 times on the PR:
```
--- Test Complete ---
All runs passed! 100/100 successful.
```
VS running the test on master:
```
--- Test Complete ---
Total failures: 13 out of 100 runs.
```
PR that introduces `waitForPromiseResolution`
```ts
async function waitForPromiseResolution() {
await act(async () => {
await new Promise((resolve) => setTimeout(resolve, 0))
})
}
```
I have:
| Android          | …
> (PC-37197) fix(stepper): make test more robust

- .github/workflows/dev_on_pull_request_run_e2e.yml
- .github/workflows/dev_on_schedule_flashlight_android.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37006
I have:
- Les métriques extraites (**score global**, **FPS moyen**, **RAM moyenne**, **CPU moyen**) sont affichées dans une notification Slack, envoyée à la fin de chaque run.
- Le format de la notification Slack a été aligné sur celui des notifications E2E web :
Présentation claire, titres, auteur, couleurs, émojis, et liens directs vers le workflow.
- Un comparatif automatique avec la mesure précédente (affichage de l’évolution des métriques) pourra être ajouté dans une prochaine PR, via l’utilisation d’artefacts GitHub pour stocker l’historique court terme.
> (PC-37006) feat(perfs): add slack notif and labeled run for performance test

- src/api/gen/api.ts
- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/fixtures/offerResponse.ts
- src/features/offer/fixtures/videoDataFixture.ts
- src/features/offer/helpers/extractYoutubeVideoId/extractYoutubeVideoId.native.test.ts
- src/features/offer/helpers/extractYoutubeVideoId/extractYoutubeVideoId.ts
- src/features/offer/pages/Offer/Offer.tsx
- src/features/offer/pages/OfferVideoPreview/OfferVideoPreview.tsx
- src/features/offer/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36872
I have:
https://github.com/user-attachments/assets/fec17e24-ae5a-4c98-9099-7da0bd93d955
https://github.com/user-attachments/assets/c4ca3d4e-6a8d-4124-9e78-8e494bb45a80
<details>
If you consider correcting the issue is too time consuming/complex: …
> (PC-36872) feat(VideoSection): link back to front for offer video

- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/components/OfferContent/VideoSection/FeedBackVideo.native.test.tsx
- src/features/offer/components/OfferContent/VideoSection/FeedBackVideo.tsx
- src/features/offer/components/OfferContent/VideoSection/VideoSection.native.test.tsx
- src/features/offer/components/OfferContent/VideoSection/VideoSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36913
I have:
<details> …
> (PC-36913) feat(offer): add offer subcategory for offer video qualtrics link

- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/components/OfferFooter/OfferFooter.tsx
- src/features/offer/helpers/getIsAComingSoonOffer.test.ts
- src/features/offer/helpers/getIsAComingSoonOffer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36799
I have:
<details>
If you …
> (PC-36799) feat(Offers): remove check on isReleased for future offers

- src/features/offer/components/OfferBody/OfferBody.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/components/OfferContent/VideoSection/FeedBackVideo.native.test.tsx
- src/features/offer/components/OfferContent/VideoSection/FeedBackVideo.tsx
- src/features/offer/components/OfferContent/VideoSection/VideoSection.tsx
- src/features/offer/pages/Offer/Offer.tsx
- src/features/offer/types.ts
- src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.native.test.tsx
- src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx
- src/features/reactions/enum.ts
- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36833
I have:
<details> …
> (PC-36833) feat(offer): trigger ValidateReaction log when pressing feedback video buttons

- src/ui/svg/HomeGradient.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37215
I have:
| iOS              |<img width="1179" height="2556" alt="simulator_screenshot_4A2E5392-5315-4B59-8AE8-ECD036426115" src="https://github.com/user-attachments/assets/7c29f04a-9770-46b5-ac9c-288819efd864" />|<img width="1179" height="2556" alt="Simulator Screenshot - iPhone 16 - 2025-07-28 at 16 40 57" src="https://github.com/user-attachments/assets/884828d2-69fa-4eeb-995c-11fe6b56373a" />|
[2]: …
> (PC-37215) fix(thematicHome): fix thematic home gradient

- src/features/home/components/modules/HighlightOfferModule.native.test.tsx
- src/features/home/components/modules/marketing/MarketingBlockExclusivity.native.test.tsx
- src/features/home/components/modules/marketing/MarketingBlockExclusivity.tsx
- src/features/offer/components/OfferContent/ComingSoonCTAs/FavoritesCTA.tsx
- src/features/offer/components/OfferContent/ComingSoonCTAs/RemindersCTA.tsx
- src/features/offer/components/OfferContent/OfferContent.web.test.tsx
- src/features/offer/components/OfferContent/OfferContentBase.tsx
- src/features/offer/components/OfferContent/StickyFooterContent/StickyFooterContent.tsx
- src/features/offer/components/OfferContent/StickyFooterContent/StickyFooterContentBase.tsx
- src/features/offer/components/OfferFooter/OfferContentCTAs.native.test.tsx
- src/features/offer/components/OfferFooter/OfferContentCTAs.tsx
- src/features/offer/helpers/getIsAComingSoonOffer.test.ts
- src/features/offer/helpers/getIsAComingSoonOffer.ts
- src/libs/algolia/types.ts
- src/ui/components/tiles/HorizontalOfferTile.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36840
I have:
| iOS              |               | <video src="https://github.com/user-attachments/assets/1de8d309-e62e-4579-a699-79c79f8eacc2" /> |
| Desktop - Chrome |               | <video src="https://github.com/user-attachments/assets/e2f1ab84-f9de-45a8-9152-ff658a747d7f" /> |
<details> …
> (PC-36840) feat(Offer): handle timestamp format and desktop cta

- src/features/navigation/RootNavigator/linking/getInitialUrl.ios.ts
- src/features/navigation/RootNavigator/linking/subscribe.ios.ts
- src/libs/firebase/shims/dynamic-links/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37211
I have:
<details> …
> (PC-37211) feat(navigation): remove Firebase Dynamic Links from iOS files

- __mocks__/@batch.com/react-native-plugin.ts
- src/App.native.test.tsx
- src/App.tsx
Now that requestNotificationAuthorization is no longer at start, we should refresh the token manually
- Using the above method, the push token will automatically be fetched by the SDK.
- Alternatively, you can call requestNotificationAuthorization later
- But, you should always refresh your token on each application start
- This will make sure that even if your user's token changes, you still get notifications
Source:
https://doc.batch.com/developer/sdk/react-native/sdk-integration/expo-integration#enable-push-notifications
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37158
I have:
| :--------------- | …
> (PC-37158) fix(permission): BatchPush.refreshToken

- src/features/identityCheck/pages/helpers/useStepperInfo.native.test.tsx
- src/features/identityCheck/pages/helpers/useStepperInfo.tsx
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/SetCity.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
- src/features/identityCheck/pages/profile/SetStatus.tsx
- src/features/identityCheck/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36891
I have:
<details>
If you …
> (PC-36891) feat(Stepper): added 'Confirme tes infos' when user already has completed profile

- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
- src/libs/analytics/__mocks__/logEventAnalytics.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/firebase/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37265
I have:
|Chrome - mobile              |<img width="1512" height="735" alt="Capture d’écran 2025-07-31 à 10 38 16" src="https://github.com/user-attachments/assets/ca9ec5c1-27e7-4ae9-b2f8-7e556c5f9430" />|
<details>
If you can't …
> (PC-37265) feat(offer): add tracker on fake door cta

- package.json
- src/features/chronicle/components/ChronicleCard/ChronicleCard.tsx
- src/libs/parsers/getLineHeightPx.native.test.ts
- src/libs/parsers/getLineHeightPx.ts
- src/ui/components/BulletListItem.tsx
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37272
La fonction est nécessaire car en mobile désormais on renvoie en number mais par contre en web on maintiens ce qu'on faisait avant et on renvoie le token en rem sous forme de string
I have:
<details>
If you consider correcting the issue is too …
> (PC-37272) feat(DS): update design system lib

- src/features/home/api/useActivationBanner.ts
- src/features/identityCheck/pages/helpers/useStepperInfo.native.test.tsx
- src/features/identityCheck/pages/helpers/useStepperInfo.tsx
- src/shared/user/useOverrideCreditActivationAmount.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35733
I have:
<details> …
> (PC-35733) fix(onboarding): display amount in the correct currency in the subtitle

- __snapshots__/features/home/components/modules/video/VideoModal.native.test.tsx.native-snap
- src/features/home/components/modules/video/YoutubePlayer/YoutubePlayer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37339
I have:
| iOS              |               |<img width="438" height="881" alt="Capture d’écran 2025-08-11 à 15 16 08" src="https://github.com/user-attachments/assets/4f992c2d-bd56-4dc6-b11c-e67720698103" /> <img width="462" height="929" alt="Capture d’écran 2025-08-11 à 15 16 24" src="https://github.com/user-attachments/assets/588cc1f9-dbe3-4bbe-9d60-467ae868d802" />|
| Android          |               |<img width="433" height="888" alt="Capture d’écran 2025-08-11 à 15 15 40" …
> (PC-37339) fix(offer): display YouTube player on web

- ios/Podfile
- ios/Podfile.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37406
I have:
<details>
If you …
> (PC-37406) chore(deps): enable new architecture on ios

- src/api/gen/api.ts
- src/features/navigation/RootNavigator/useShowMandatoryUpdatePersonalData.native.test.ts
- src/features/navigation/RootNavigator/useShowMandatoryUpdatePersonalData.ts
- src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
- src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
- src/fixtures/user.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37126
I have:
<details>
If you …
> (PC-37126) feat(navigation): should not navigate to MandatoryUpdatePersonalData when profile is not expired

- ios/Podfile
- ios/Podfile.lock
- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36894
- Update Batch with yarn
- Start an Android emulator in testing
- Copy the Batch installation ID
- In the [Batch testing env debug section](https://dashboard.batch.com/19363/projects/2pn8IHk/apps/35875/settings/debug), paste the Batch installation ID
- Press the "Send push test" button
- See if you have the notification on your Android emulator
- If successful, we consider the update is working
Repeat the same process on an iOS simulator.
- When trying to send the debug push on Android, I got an error:
```
Push test has failed This push token was registered with a Sender ID that doesn't match this authorization key
```
- I tried to check the testing push config but I have an "Access Denied - You don't have access to …
> (PC-36894) chore(batch): upgrade to 10

- android/app/src/main/AndroidManifest.xml
- ios/PassCulture/Info.plist
- src/libs/location/geolocation/checkGeolocPermission/checkGeolocPermission.android.test.ts
- src/libs/location/geolocation/checkGeolocPermission/checkGeolocPermission.android.ts
- src/libs/location/geolocation/requestGeolocPermission/requestGeolocPermission.android.test.ts
- src/libs/location/geolocation/requestGeolocPermission/requestGeolocPermission.android.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37217
I have:
<details> …
> (PC-37217) feat(location): use approximative geolocation

- ios/AppDelegate.mm
- ios/Dynamic.swift
- ios/PassCulture.xcodeproj/project.pbxproj
- ios/Podfile.lock
- package.json
- src/features/subscription/components/buttons/SubscribeButton.tsx
- yarn.lock
> (PC-37430) chore(deps): bump lottie-react-native

- .github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37453
I have:
<details>
If you …
> (PC-37453) fix(CI): use githubci app to push tag

- __snapshots__/features/identityCheck/pages/identification/ubble/SelectIDStatus.native.test.tsx.native-snap
- __snapshots__/features/onboarding/pages/onboarding/OnboardingAgeSelectionFork.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/TutorialAgeInformationCredit/ProfileTutorialAgeInformationCredit.native.test.tsx.native-snap
- src/cheatcodes/pages/others/CheatcodesNavigationNotScreensPages.tsx
- src/ui/components/accessibility/AccessibleUnorderedList.tsx
- src/web/BrowserNotSupportedPage.web.tsx
- src/web/SupportedBrowsersGate.web.test.tsx
- src/web/SupportedBrowsersGate.web.tsx
- src/web/supportedBrowsers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34229
I have:
| Desktop - Chrome |   <img width="500" height="998" alt="Capture d’écran 2025-08-13 à 18 05 52" src="https://github.com/user-attachments/assets/59e891c6-8c7f-4ab4-8312-3fd3166e506b" />   |   <img width="501" height="998" alt="Capture d’écran 2025-08-13 à 16 34 59" src="https://github.com/user-attachments/assets/8dd260cd-339f-468b-aa80-55d6f1e56c24" />   |
[1]: …
> (PC-34229) feat(web): update BrowserNotSupportedPage design

- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37411
I have:
| Desktop - Chrome |<img width="1484" height="738" alt="Capture d’écran 2025-08-19 à 10 51 43" src="https://github.com/user-attachments/assets/4906e591-45c8-48a7-8a5a-1ed96840a24c" />|<img width="1495" height="734" alt="Capture d’écran 2025-08-19 à 10 49 44" src="https://github.com/user-attachments/assets/479dca59-d5d6-4b48-afe5-c7fa8560a481" />|
<details>
If you can't respect one of these rules, be sure to explain why …
> (PC-37411) feat(offer): add id to loan fakedoor tracker

- __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- src/features/home/components/AccessibleTitle.tsx
- src/features/home/components/modules/venues/VenuesModule.tsx
- src/features/home/components/modules/video/VideoModuleMobile.tsx
- src/ui/components/PassPlaylist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37477
I have:
| Desktop - Chrome | <img width="219" height="472" alt="Capture d’écran 2025-08-21 à 12 55 19" src="https://github.com/user-attachments/assets/84472e3e-0b14-49ca-8a43-4b65f153f19b" /> | <img width="221" height="472" alt="Capture d’écran 2025-08-21 à 12 45 15" src="https://github.com/user-attachments/assets/395c929f-2698-46b0-a360-d122fc78463e" /> |
| Desktop - Chrome | <img width="223" height="475" alt="Capture d’écran 2025-08-21 à 12 54 50" src="https://github.com/user-attachments/assets/2a704364-9779-4 …
> (PC-37477) fix(Modules): increase horizontal margin

- package.json
- yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37559
`yarn trigger:testing:deploy` error:
`Usage Error: Couldn't find a script named "json".`
I have:
<details> …
> (PC-37559) fix(deps): restore json

- src/features/bookings/components/BookingDetailsContent.native.test.tsx
- src/features/bookings/components/Ticket/Ticket.tsx
- src/features/home/components/modules/venues/VenueTile.native.test.tsx
- src/features/home/components/modules/venues/VenueTile.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/features/offer/components/OfferPlace/OfferPlace.tsx
- src/features/offer/components/OfferVenueButton/OfferVenueButton.native.test.tsx
- src/features/offer/components/OfferVenueButton/OfferVenueButton.tsx
- src/features/search/components/SearchSuggestions/SearchSuggestions.tsx
- src/features/search/components/SearchVenueItems/SearchVenueItem.native.test.tsx
- src/features/search/components/SearchVenueItems/SearchVenueItem.tsx
- src/features/search/pages/SearchLanding/SearchLanding.native.test.tsx
- src/features/search/pages/SearchResults/SearchResults.native.test.tsx
- src/features/venue/pages/Venue/Venue.native.test.tsx
- src/features/venue/pages/Venue/Venue.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
- src/features/venueMap/components/VenueMapView/VenueMapViewContainer.tsx
- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37104
I have:
<details> …
> (PC-37104) refactor(venue): force venueId as string in ConsultVenue log

- src/features/identityCheck/queries/useIdentificationUrlMutation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37326
When there is an error in the `UbbleWebview` the `IdentityCheckUnavailable` screen is pushed in the stack. However, the `UbbleWebview` loads on repeat even if it is not the screen to be displayed but being still in the stack history, leading to new calls to ubble backend route and new errors. 
The fix proposed is tested in web (NOT in MOBILE):
- use replace instead of navigate to erase the stack and push the `IdentityCheckUnavailable` screen
- the back button in web still works and resets the stack to the step just before `UbbleWebview`
- anyway the history does not seem to be very important in that case since we propose the user to go back to the root of the app.
> (PC-37326) fix(UbbleWebView): replace stack with IdentityCheckUnavailable when error Ubble

- src/features/search/components/SearchListHeader/SearchListHeader.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37597
I have:
<details>
If you …
> (PC-37597) fix(test): skip SearchListHeader web

- src/features/chronicle/components/ChronicleCardListHeader/ChronicleCardListHeader.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.native.test.tsx
- src/features/chronicle/pages/Chronicles/Chronicles.web.test.tsx
- src/features/offer/pages/Offer/Offer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37425
I have:
| iOS              |<img width="170" height="246" alt="Capture d’écran 2025-08-26 à 10 41 18" src="https://github.com/user-attachments/assets/283ad53a-905a-4cc6-b58a-9ed2dda08c41" /> <img width="177" height="152" alt="Capture d’écran 2025-08-26 à 10 41 38" src="https://github.com/user-attachments/assets/e112adfa-7ad1-46d0-b13a-3ae427fb8542" />|       |
| Phone - Chrome   |               |<img width="401" height="693" alt="Capture d’écran 2025-08-26 à 10 22 …
> (PC-37425) feat(chronicle): update page title

- src/libs/parsers/highlightLinks.tsx
- src/ui/components/Markdown/Markdown.tsx
- src/ui/components/MarkdownPart/MarkdownPart.tsx
- src/ui/components/buttons/externalLink/ExternalLink.native.test.tsx
- src/ui/components/buttons/externalLink/ExternalLink.tsx
- src/ui/components/buttons/externalLink/ExternalLink.web.test.tsx
- src/ui/components/buttons/externalLink/ExternalLink.web.tsx
- src/ui/components/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37474
I have:
The Icon for external link is visible in the collapsible text when collapsed as it is not a `Text`.
We can remove the icon for now, as the accessibility enhancements that are going to be done will check and fix this types of links.
> (PC-37474) fix(OfferAbout): remove icon in Markdown text

- .github/workflows/dev_on_schedule_flashlight_android.yml
- scripts/run_flashlight_on_android.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37400
Learnings:
- The job started failing because the runner was out of disk space (see more details below in dedicated section).
- This test becomes flaky under certain conditions (see more details below in dedicated section).
If we look at the job that worked, we had this (from "Set up job"):
```
Runner Image
Image: ubuntu-24.04
Version: 20250720.1.0
```
And the job that failed:
```
Runner Image
Image: ubuntu-24.04
Version: 20250728.1.0
```
The version was bumped.
In the job that worked, we can see a link to the Image Release:
https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20250720.1
Click "Compare" and type the new version "20250728" and select: `ubuntu24/20250728.1`
If we compare the versions: …
> (PC-37400) fix(flashlight): free space

- src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
- src/features/bookOffer/pages/BookingOfferModal.tsx
- src/features/bookings/components/EndedBookingItem.native.test.tsx
- src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
- src/features/gtlPlaylist/components/GtlPlaylist.native.test.tsx
- src/features/home/components/modules/marketing/MarketingBlockExclusivity.native.test.tsx
- src/features/home/components/modules/video/VideoEndView.native.test.tsx
- src/features/home/components/modules/video/VideoMonoOfferTile.native.test.tsx
- src/features/home/components/modules/video/VideoMultiOfferTile.native.test.tsx
- src/features/navigation/RootNavigator/linking/getStateFromPath.test.ts
- src/features/offer/components/OfferCTAButton/OfferCTAButton.native.test.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/features/offer/components/OfferTile/OfferTile.native.test.tsx
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
- src/features/search/pages/ThematicSearch/ThematicSearchPlaylist.native.test.tsx
- src/features/venue/components/VenueBody/VenueBody.native.test.tsx
- src/libs/analytics/helpers/triggerLogConsultOffer/triggerConsultOfferLog.test.ts
- src/libs/analytics/helpers/triggerLogConsultOffer/triggerConsultOfferLog.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/analytics/types.ts
- src/ui/components/eventCard/EventCard.native.test.tsx
- src/ui/components/tiles/HorizontalOfferTile.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37103
I have:
<details>
If you …
> (PC-37103) fix(Log): inconsistency type of offerId and bookingId

- src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
- src/features/bookOffer/pages/BookingOfferModal.tsx
- src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
- src/features/offer/components/OfferTile/OfferTile.native.test.tsx
- src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
- src/libs/analytics/helpers/triggerLogConsultOffer/triggerConsultOfferLog.ts
- src/libs/analytics/logEventAnalytics.ts
- src/libs/analytics/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37107
I have:
<details>
If you …
> (PC-37107) fix(log): adjust type of params fromOfferId and fromMultivenueOfferId

- __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
- src/features/search/pages/ThematicSearch/ThematicSearch.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37638
I have:
| iOS              |               | <img width="1179" height="2556" alt="Simulator Screenshot - iPhone 15 Pro - 2025-08-29 at 12 35 16" src="https://github.com/user-attachments/assets/807c3b1e-dce5-46b5-8d24-d571157fb52b" />  |
| Android          |               |  <img width="1440" height="2960" alt="Screenshot_1756463707" src="https://github.com/user-attachments/assets/eddb35cc-6287-4958-a4a3-d981f7b3aa98" /> |
| Desktop - Chrome |               | <img width="514" height="577" alt="Capture d’écran …
> (PC-37638) fix(ThematiqueSearch): correct bottom margin

- README.md
- doc/installation/Android.md
- doc/installation/iOS.md
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37682
I have:
<details>
If you …
> (PC-37682) docs(installation): update des docs suite retour JL

- src/features/auth/pages/login/Login.tsx
- src/features/auth/pages/signup/AcceptCgu/AcceptCgu.tsx
- src/features/favorites/pages/FavoritesSorts.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumber.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.tsx
- src/features/identityCheck/pages/phoneValidation/SetPhoneValidationCode.tsx
- src/features/identityCheck/pages/profile/SetAddress.tsx
- src/features/identityCheck/pages/profile/SetName.tsx
- src/features/profile/components/CitySearchInput/CitySearchInput.tsx
- src/features/profile/pages/ChangeAddress/ChangeAddress.tsx
- src/features/profile/pages/Profile.tsx
- src/features/search/components/CalendarPicker/CalendarPicker.web.tsx
- src/features/search/components/PriceInputController/PriceInputController.tsx
- src/shared/forms/controllers/EmailInputController.tsx
- src/shared/forms/controllers/PasswordInputController.tsx
- src/ui/components/inputs/DateInput/DatePicker/DatePickerDropDown.web.tsx
- src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.tsx
- src/ui/components/inputs/DateInput/DatePicker/DatePickerSpinner.web.tsx
- src/ui/components/inputs/InputError.native.test.tsx
- src/ui/components/inputs/InputError.tsx
- src/ui/components/inputs/InputError.web.test.tsx
- src/ui/components/inputs/LargeTextInput/LargeTextInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37491
I have:
<details>
If you …
> (PC-37491) feat(a11y): rename messageId > errorMessage in InputError

- ios/Podfile.lock
- package.json
- src/features/venueMap/components/VenueMapLabel/LabelContainer.android.tsx
- src/features/venueMap/components/VenueMapView/Marker/Marker.tsx
- src/features/venueMap/constant.ts
- yarn.lock
Ce fix n'est pas optimale mais il permet tout de même d'avoir le label en dessous le pin pour Android.
Aucun changement pour iOS qui est déjà ok.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37424
I have:
| iOS              |               |<img width="447" height="920" alt="Capture d’écran 2025-09-02 à 14 16 03" src="https://github.com/user-attachments/assets/a2af9a78-2895-4115-bd71-352a6444a0bc" />|
| Android          |<img width="410" height="891" alt="Capture d’écran 2025-09-02 à 15 34 52" src="https://github.com/user-attachments/assets/dc9e975c-1229-4656-bc7f …
> (PC-37424) fix(venueMap): avoid label overlay pin in Android

- src/features/home/components/modules/venues/VenuesModule.tsx
- src/features/search/components/VenuePlaylist/VenuePlaylist.tsx
- src/ui/components/PassPlaylist.tsx
- src/ui/components/Playlist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37591
I have:
| iOS              |<img width="449" height="935" alt="Capture d’écran 2025-09-03 à 14 38 02" src="https://github.com/user-attachments/assets/37ab540b-db6f-459e-8402-808fc0134e8c" /> <img width="446" height="926" alt="Capture d’écran 2025-09-03 à 14 38 13" src="https://github.com/user-attachments/assets/c78a1c79-0d6a-486b-b733-a6a5cbf74cec" /> <img width="1179" height="2556" alt="Simulator Screenshot - iPhone 16 - 2025-09-03 at 14 47 13" src="https://github.com/user-attachments/assets/1e6a9e88-1686-4be4-b3 …
> (PC-37591) fix(app): padding horizontal for venue playlist

- jest/jest.setup.ts
- src/App.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37746
I have:
<details>
If you …
> (PC-37746) chore(warning): ignore contain units warning

- src/ui/components/Accordion.tsx
- src/ui/components/TouchableOpacity.tsx
- src/ui/components/touchableLink/TouchableLink.tsx
- src/ui/theme/customFocusOutline/customFocusOutline.ts
- src/ui/theme/customFocusOutline/customFocusOutline.web.ts
- src/ui/theme/customFocusOutline/touchableFocusOutline.native.test.tsx
- src/ui/theme/customFocusOutline/touchableFocusOutline.tsx
- src/ui/theme/customFocusOutline/touchableFocusOutline.web.test.tsx
- src/ui/theme/customFocusOutline/touchableFocusOutline.web.tsx
- src/ui/theme/customFocusOutline/type.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37485
I have:
| iOS              |     |       |
| Desktop - Chrome |   <img width="500" height="934" alt="Capture d’écran 2025-09-04 à 16 07 11" src="https://github.com/user-attachments/assets/0733dbda-708e-4a48-85fd-6af968e7fa08" />    |   <img width="499" height="934" alt="Capture d’écran 2025-09-04 à 16 06 53" src="https://github.com/user-attachments/assets/f0775871-05fb-4476-b03c-ab4c7ad30c85" />  |
[1]: …
> (PC-37485) feat(accessibility): add focus outline in Accordin component

- __snapshots__/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/DeleteProfile/SuspendAccountConfirmationWithoutAuthentication.native.test.tsx.native-snap
- __snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
- __snapshots__/features/trustedDevice/pages/SuspensionChoice.native.test.tsx.native-snap
- src/cheatcodes/pages/others/CheatcodesScreenFeatureFlags.tsx
- src/cheatcodes/pages/others/CheatcodesScreenRemoteConfig.tsx
- src/features/auth/components/AuthenticationButton/AuthenticationButton.tsx
- src/features/cookies/pages/CookiesDetails.tsx
- src/features/offer/components/OfferContent/VideoSection/FeedBackVideo.tsx
- src/features/profile/helpers/renderAccessibilityExternalLink.tsx
- src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileBase.tsx
- src/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.tsx
- src/features/profile/pages/Accessibility/AccessibilityEngagement.tsx
- src/features/profile/pages/Accessibility/RecommendedPaths.tsx
- src/features/profile/pages/ConsentSettings/ConsentSettings.tsx
- src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx
- src/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.tsx
- src/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.tsx
- src/features/profile/pages/DeleteProfile/SuspendAccountConfirmationWithoutAuthentication.tsx
- src/features/profile/pages/LegalNotices/LegalNotices.tsx
- src/features/trustedDevice/pages/SuspensionChoice.tsx
- src/ui/components/buttons/linkInsideText/LinkInsideText.native.test.tsx
- src/ui/components/buttons/linkInsideText/LinkInsideText.tsx
- src/ui/components/buttons/linkInsideText/LinkInsideText.web.tsx
- src/ui/components/buttons/linkInsideText/types.ts
> (BSR) feat(a11y): change role in Internal and External TouchableLink

- __snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
- __snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
- doc/decision-records/DR009 - accessibility-audit.md
- src/features/artist/components/ArtistPlaylist/ArtistPlaylist.native.test.tsx
- src/features/home/components/AccessibleTitle.tsx
- src/features/home/components/AccessibleTitle.web.test.tsx
- src/features/home/components/AccessibleTitle.web.tsx
- src/features/home/components/modules/HomeModule.native.test.tsx
- src/features/home/components/modules/OffersModule.native.test.tsx
- src/features/home/components/modules/video/VideoModule.native.test.tsx
- src/features/home/components/modules/video/VideoModuleDesktop.tsx
- src/features/home/components/modules/video/VideoModuleMobile.tsx
- src/features/home/helpers/separateTitleAndEmojis.native.test.ts
- src/features/home/helpers/separateTitleAndEmojis.ts
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferPlaylist/OfferPlaylist.native.test.tsx
- src/features/offer/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx
- src/features/search/pages/ThematicSearch/Book/BookPlaylists.native.test.tsx
- src/features/search/pages/ThematicSearch/Cinema/CinemaPlaylists.native.test.tsx
- src/features/search/pages/ThematicSearch/ConcertsAndFestivals/ConcertsAndFestivalsPlaylists.native.test.tsx
- src/features/search/pages/ThematicSearch/Films/FilmsPlaylists.native.test.tsx
- src/features/search/pages/ThematicSearch/Music/MusicPlaylists.native.test.tsx
- src/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx
- src/features/search/pages/ThematicSearch/ThematicSearchPlaylistList.native.test.tsx
- src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx
- src/ui/components/PassPlaylist.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37377
I have:
| iOS              |               |  <img width="985" height="723" alt="Capture d’écran 2025-09-15 à 16 51 33" src="https://github.com/user-attachments/assets/e2a855bc-5fae-477e-b0b0-a347c19706b7" />  |
| Desktop - Chrome |               |   <img width="521" height="938" alt="Capture d’écran 2025-09-15 à 16 50 14" src="https://github.com/user-attachments/assets/c3480b98-6fe0-458a-b2bd-604ff2dcb221" />  |
[1]: …
> (PC-37377) feat(a11y): hidden emoji in AccessibleTitle

- src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
- src/features/venueMap/pages/VenueMap/VenueMap.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37844
I have:
<details> …
> (PC-37844) fix(venueMap): modal filters use

- src/features/offer/pages/OfferVideoPreview/OfferVideoPreview.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37981
I have:
| iOS              |               |<img width="426" height="883" alt="Capture d’écran 2025-09-18 à 12 29 31" src="https://github.com/user-attachments/assets/7f8e48d6-bb77-44ca-b582-922cdd785245" />|
| Android          |               |<img width="424" height="904" alt="Capture d’écran 2025-09-18 à 12 34 39" src="https://github.com/user-attachments/assets/bb9dcc17-eca9-4178-a2c6-4a1dea7ba265" />|
| Phone - Chrome   |               |<img width="394" height="686" alt="Capture d’écran 2025-09-18 à 12 23 …
> (PC-37981) feat(offer): add title and duration on offer video preview page

- .github/workflows/dev_on_workflow_call_e2e_android.yml
- .github/workflows/dev_on_workflow_call_e2e_ios.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37942
I have:
- Ajout d'un timeout pour la CI attendent la fin de l'exécution des tests E2E avant de valider le job
> (PC-37942) feat(ci): add timeout to maestro cloud action

- src/features/identityCheck/queries/useIdentificationUrlMutation.native.test.ts
- src/features/identityCheck/queries/useIdentificationUrlMutation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37978
I have:
> (PC-37978) feat(ubble): add no retry in useIdentificationUrlMutation

- __snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
- __snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
- __snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap
- src/theme/index.ts
- src/ui/components/placeholders/SkeletonTile.tsx
- src/ui/theme/colors.stories.tsx
- src/ui/theme/colors.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37697
I have:
<details> …
> (PC-37697) fix(DS): use skeleton tokens

- src/features/home/components/modules/video/YoutubePlayer/YoutubePlayer.tsx
- src/features/offer/components/OfferContent/OfferContent.native.test.tsx
- src/features/offer/components/OfferContent/OfferContent.tsx
- src/features/offer/components/OfferContent/OfferContent.web.tsx
- src/features/offer/components/OfferContent/VideoSection/VideoSection.native.test.tsx
- src/features/offer/components/OfferContent/VideoSection/VideoSection.tsx
- src/features/offer/pages/OfferVideoPreview/OfferVideoPreview.native.test.tsx
- src/features/offer/pages/OfferVideoPreview/OfferVideoPreview.tsx
- src/libs/analytics/logEventAnalytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37971
I have:
<details>
If you …
> (PC-37971) fix(OfferVideo): to be more precise on log video

- __snapshots__/features/profile/pages/Accessibility/SiteMapScreen.native.test.tsx.native-snap
- doc/decision-records/DR009 - accessibility-audit.md
- src/features/profile/pages/Accessibility/SiteMapScreen.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-38204
I have:
<details>
If you …
> (PC-38204) fix(TalkBack): remove click sound between elements of site map

- src/ui/components/eventCard/EventCard.native.test.tsx
- src/ui/components/eventCard/EventCard.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37490
I have:
<details>
If you …
> (PC-37490) fix(test): un-group event card accessibilityLabel

- src/cheatcodes/pages/CheatcodesMenu.tsx
- src/cheatcodes/pages/features/bonification/CheatcodesNavigationBonification.tsx
- src/features/bonification/pages/BonificationBirthDate.native.test.tsx
- src/features/bonification/pages/BonificationBirthDate.tsx
- src/features/bonification/pages/BonificationBirthPlace.native.test.tsx
- src/features/bonification/pages/BonificationBirthPlace.tsx
- src/features/bonification/pages/BonificationError.native.test.tsx
- src/features/bonification/pages/BonificationError.tsx
- src/features/bonification/pages/BonificationIntroduction.native.test.tsx
- src/features/bonification/pages/BonificationIntroduction.tsx
- src/features/bonification/pages/BonificationNames.native.test.tsx
- src/features/bonification/pages/BonificationNames.tsx
- src/features/bonification/pages/BonificationRecap.native.test.tsx
- src/features/bonification/pages/BonificationRecap.tsx
- src/features/bonification/pages/BonificationTitle.native.test.tsx
- src/features/bonification/pages/BonificationTitle.tsx
- src/features/bonification/schemas/BonificationBirthPlaceSchema.ts
- src/features/bonification/schemas/BonificationNamesSchema.ts
- src/features/navigation/CheatcodesStackNavigator/CheatcodesStackNavigator.tsx
- src/features/navigation/CheatcodesStackNavigator/CheatcodesStackTypes.ts
- src/features/navigation/CheatcodesStackNavigator/cheatcodesStackNavigatorPathConfig.tsx
- src/features/navigation/RootNavigator/linking/rootStackNavigatorPathConfig.ts
- src/features/navigation/SubscriptionStackNavigator/SubscriptionStackNavigator.tsx
- src/features/navigation/SubscriptionStackNavigator/SubscriptionStackTypes.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-38131
Questions soulevés par le ticket:
- Revoir tous les wordings! Notamment pour les headers "informations personnelles" est trop générique
- Pour tous les écrans avec formulaires, il reste à ajouter la barre de progression, et une mention "n écran sur 5".
- Pour tous les formulaires, il faut ajouter l'enregistrement des infos dans un store, puis l'affichage de ces infos à partir du store dans l'écran de recap
- Existe t-il un template sans header? Pour l'instant je n'ai trouvé que `PageWithHeader` pour l'écran `BonificationIntroduction`
- Si on retire le header, quel exit pour la page d'intro?
- `BonificationNames`: il faudra ajouter un champ "prénoms"
- `BonificationTitle`: il faut trouver un moyen de ne montrer le champ …
> (PC-38131) feat(bonification): create screens in cheatcodes

- src/features/offer/components/MovieCalendar/MovieCalendar.native.test.tsx
- src/features/offer/components/MovieCalendar/MovieCalendar.tsx
- src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx
- src/features/offer/components/MoviesScreeningCalendar/MovieCalendarContext.tsx
- src/ui/hooks/useHorizontalFlatListScroll.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37578
La `FlatList` provoque un problème de rendu, qui sépare le rendu des sous composants de sa liste, la liste change donc de taille à plusieurs reprise (plus visible quand l'animation est retirée), je l'ai modifié pour utiliser `FlashList` qui corrige ce problème
Le problème du blink est dû aux animations qui ne sont pas fluides sur le device, j'ai tenté d'utiliser `react-native-reanimated`, et `react-native-reanimatable` sans succès, j'ai donc décidé de supprimer ces animations afin de privilégier une expérience d'utilisation plus fluide au dépit d'un UI plus agréable
Les performances de cette page ne nous laissent malheureusement pas le luxe d'avoir des animations pour l'instant.
| Platform         | Mockup/Before | …
> (PC-37578) fix(CineOffer): remove blink

- .github/workflows/dev_on_workflow_environment_soft_deploy.yml
- fastlane/Fastfile
- hot-updater.config.ts
- src/ui/hooks/useVersion.native.test.ts
- src/ui/hooks/useVersion.ts
> (BSR) feat(HotUpdater): improve ota workflow
