pass-culture/pass-culture-app-native

src/features/home/pages/ThematicHome.tsx
src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
src/features/profile/pages/NotificationSettings/helpers/hasUserChangedParameters.native.test.ts
src/features/profile/pages/NotificationSettings/helpers/hasUserChangedParameters.ts
src/features/subscription/helpers/useThematicSubscription.native.test.tsx
src/features/subscription/helpers/useThematicSubscription.tsx
src/features/subscription/helpers/useThematicSubscription.web.test.tsx
src/features/subscription/types.ts
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29012
I have:

(PC-29012) feat(subscription): add tracker to subscription feature

---

src/features/home/components/modules/VenueMapModule.tsx
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.native.test.tsx
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx
src/features/search/components/SearchListHeader/SearchListHeader.tsx
src/features/venueMap/components/VenueMapBlock/VenueMapBlock.tsx
src/features/venueMap/hook/useShouldDisplayVenueMap.native.test.ts
src/features/venueMap/hook/useShouldDisplayVenueMap.ts
src/features/venueMap/hook/useShouldDisplayVenueMap.web.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29128
I have:
| iOS              |               |![Capture d’écran 2024-04-22 à 15 06 05](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/7fcdbba5-8943-497d-ac79-a766d794f278)|

(PC-29128) feat(Search): display venue map block when the user is not geolocated and his position is set to everywhere

---

__snapshots__/features/search/pages/Search/Search.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.native.test.tsx
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx
src/features/search/components/IncentiveLocationModal/IncentiveLocationModal.native.test.tsx
src/features/search/components/IncentiveLocationModal/IncentiveLocationModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29130
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/6147b692-ce61-46ac-9eed-aec4b75586ca

(PC-29130) feat(CategoriesButtonsDisplay): add incentive location modal

---

__snapshots__/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.native.test.tsx.native-snap
src/features/profile/pages/ChangeEmailSetPassword/ChangeEmailSetPassword.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28720
I have:
| Platform         |   After |
| iOS              |             https://github.com/pass-culture/pass-culture-app-native/assets/46637324/a573b7a8-c04d-463f-8338-0e2a9817e3f2    |

(PC-28720) fix(ChangeEmailSetPassword): Fix keyboard and field behavior

---

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29291
I have:

(PC-29291) feat(FF): add new feature flag wipReactionFakeDoor

---

__snapshots__/features/search/pages/Search/SearchN1Books/SearchN1Books.native.test.tsx.native-snap
src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx
src/features/navigation/SearchStackNavigator/routes.ts
src/features/navigation/SearchStackNavigator/types.ts
src/features/navigation/screenParamsUtils.ts
src/features/search/pages/Search/SearchN1Books/SearchN1Books.native.test.tsx
src/features/search/pages/Search/SearchN1Books/SearchN1Books.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.stories.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29279
I have:
|           |<img width="435" alt="Capture d’écran 2024-04-24 à 12 11 20" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/19e9919f-548a-4147-9029-2794d1fdb2e2">|<img width="353" alt="Capture d’écran 2024-04-24 à 12 13 06" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/94e875bf-1583-4c62-8c10-1c7c9e72446d">|

(PC-29279) feat(SearchN1Books): SubcategoryButton

---

__snapshots__/features/auth/pages/signup/AcceptCgu/AcceptCgu.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
src/features/auth/pages/signup/AcceptCgu/AcceptCgu.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29195
I have:
| Platform         | Mockup | After |
| iOS              |    <img width="600"  src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/75a6b49d-56dc-4fb0-892a-ab94dae74479">      |    <img width="250"  src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/e2b0d5fb-afa2-4e40-bf06-b79ec3365a0e" >  |
| Desktop - Chrome |               |     <img width="1440" alt="Capture d’écran 2024-04-25 à 14 11 30" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/c41811db-2f2a-41cb-a318-6bd766cd11d6">  |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613467 …

(PC-29195) feat(AcceptCGU): Put marketing opt-in before required opt-ins

---

src/features/bookOffer/pages/BookingOfferModal.tsx
src/features/offer/components/OfferArtists/OfferArtists.tsx
src/ui/components/modals/SurveyModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29181
I have:

(BSR) refactor(SurveyMusicLive): remove useless state and other clean

---

src/features/venueMap/components/VenueMapView/VenueMapView.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29473
Solution possible trouvé ici : https://stackoverflow.com/questions/49941216/error-while-updating-property-coordinate-of-a-view-managed-by-airmapmarker-r
I have:

(PC-29473) fix(VenueMapView): fix sentry issue on Marker

---

__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
__snapshots__/features/subscription/page/OnboardingSubscription.native.test.tsx.native-snap
scripts/dead_code_snapshot.txt
src/features/home/components/SubscribeButton.stories.tsx
src/features/home/components/SubscribeButton.tsx
src/features/home/components/SubscribeButtonWithTooltip.tsx
src/features/subscription/components/SubscriptionThematicIllustration.stories.tsx
src/features/subscription/components/SubscriptionThematicIllustration.tsx
src/features/subscription/components/ThematicSubscriptionBlock.stories.tsx
src/features/subscription/components/ThematicSubscriptionBlock.tsx
src/features/subscription/components/buttons/SubscribeButton.stories.tsx
src/features/subscription/components/buttons/SubscribeButton.tsx
src/features/subscription/components/buttons/SubscriptionThematicButton.stories.tsx
src/features/subscription/components/buttons/SubscriptionThematicButton.tsx
src/features/subscription/helpers/mapSubscriptionThematicToBlockTitles.ts
src/features/subscription/helpers/mapSubscriptionThemeToIllustration.tsx
src/features/subscription/page/OnboardingSubscription.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29042
I have:
| Phone - Chrome   |               |<img width="413" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/c72557a4-4991-4465-bdd9-3cac8871d071">|
| Desktop - Chrome |               |<img width="829" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/90dbcefc-b4aa-4e95-81ac-081eec520022">|

(PC-29042) feat(Subscription): create venue subscription block

---

src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/ui/components/modals/SurveyModal.native.test.tsx
src/ui/components/modals/SurveyModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29290
I have:
| iOS              |<img width="281" alt="Capture d’écran 2024-04-29 à 14 29 23" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0183b28d-9638-4327-ae31-24eb07da31db">|<img width="398" alt="Capture d’écran 2024-04-29 à 14 28 52" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/c1840786-ee66-4898-9744-6c3a7056a165">|
| Android          |               |![Capture d’écran 2024-04-29 à 14 26 45](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/57cdb360-a321-40f7-86e0-de6c02d5bb2a)| …

(PC-29290) feat(offer): open survey modal when pressing react button

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/bookOffer/pages/BookingOfferModal.tsx
src/features/offer/components/OfferArtists/OfferArtists.native.test.tsx
src/ui/components/modals/SurveyModal.native.test.tsx
src/ui/components/modals/SurveyModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29181
I have:

(PC-29181) fix(MusicLiveOffers): survey modal on mobile

---

__snapshots__/features/home/components/modules/venues/VenueTile.native.test.tsx.native-snap
__snapshots__/features/home/components/modules/venues/VenuesModule.native.test.tsx.native-snap
src/libs/parsers/venueType.ts
src/libs/tileAccessibilityLabel.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29292
I have:

(PC-29292) feat(app): use MAP_VENUE_TYPE_TO_LABEL for accessibility labels

---

src/features/venueMap/components/VenueMapView/VenueMapView.tsx
src/features/venueMap/useGetAllVenues.native.test.ts
src/features/venueMap/useGetAllVenues.ts
src/libs/algolia/fetchAlgolia/buildVenuesQueryOptions.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29331
I have:
| iOS              |![Capture d’écran 2024-04-30 à 18 00 57](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/af8af64c-be49-4c3f-acdc-51b247f6591f) ![Capture d’écran 2024-04-30 à 18 01 03](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/4ce7e18f-0e8c-4dc7-9d74-48f9cce9d294)|![Capture d’écran 2024-04-30 à 17 57 14](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/0821aa13-b924-4519-877c-5701c16eef0e) ![Capture d’écran 2024-04-30 à 17 57 25](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/481d3959 …

(PC-29331) feat(venueMap): display filtered venues when type selected from modal

---

__snapshots__/features/venueMap/pages/modals/VenueTypeModal/VenueTypeModal.native.test.tsx.native-snap
src/features/venueMap/helpers/getVenueTypeIconName/getVenueTypeIconName.test.ts
src/features/venueMap/helpers/venueTypesMapping/venueTypesMapping.test.ts
src/features/venueMap/helpers/venueTypesMapping/venueTypesMapping.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29331
I have:
| iOS              |![Capture d’écran 2024-05-02 à 11 54 29](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/72ba7377-dfa3-4537-bd86-c33960184994) ![Capture d’écran 2024-05-02 à 11 17 20](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/f36c2360-6e86-477e-bc51-c1ea6c044e4f)|![Capture d’écran 2024-05-02 à 12 24 04](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/654d383f-c0ff-40fe-afdc-d1cb1646f450) ![Capture d’écran 2024-05-02 à 11 15 32](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/f50ccb2b …

(PC-29170) feat(venueMap): manage other venue type code 

---

src/features/location/components/VenueMapLocationModal.native.test.tsx
src/features/location/components/VenueMapLocationModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29287
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/8331b1f9-4973-40c8-a232-fe5876f54f8a

(PC-29287) feat(VenueMapLocationModal): on submit we navigate to venue map

---

scripts/dead_code_snapshot.txt
src/ui/components/CheckboxBlock/CheckboxBlock.stories.tsx
src/ui/components/CheckboxBlock/CheckboxBlock.tsx
src/ui/theme/customFocusOutline/customFocusOutline.tsx
src/ui/theme/customFocusOutline/customFocusOutline.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29569
I have:
| iOS              |    <img width="335" alt="Capture d’écran 2024-05-02 à 18 20 54" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/fd9b69e1-6bfb-4557-a2e4-071c8c79832a"><img width="338" alt="Capture d’écran 2024-05-02 à 18 21 01" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/39e03e5f-1396-4498-bbe6-2ba1cae6ca52"> |    <img width="750" alt="Capture d’écran 2024-05-03 à 08 21 11" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/03edb352-0e8b-4ba0-8a01-c5b88d8c1b59">   |
| Desktop - Chrome |               |   voir Storybook    |
[1]: …

(PC-29569) feat(ui): Add checkbox block component

---

src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.native.test.tsx
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx

…
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29433
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/2beeae52-f5e9-468d-8f4e-03f09cb2f9cf

(PC-29433) feat(CategoriesButtonsDisplay): on everywere position we want venue map block

---

__snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
src/features/profile/pages/LegalNotices/LegalNotices.tsx

(PC-29131) chore(LegalNotices): Update address

---

.env.integration
.env.production
.env.staging
.env.testing
__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
scripts/noUncheckedIndexedAccess_snapshot.txt
server/src/middlewares/tests/__snapshots__/webAppProxyMiddleware.test.ts.snap
src/features/bookings/helpers/buildBookingSurveyUrl.native.test.ts
src/features/bookings/helpers/buildBookingSurveyUrl.ts
src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.tsx
src/libs/environment/__mocks__/envFixtures.ts
src/libs/environment/schema.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29398
I have:
| iOS              |    <img width="224" alt="Capture d’écran 2024-05-07 à 16 40 18" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/355d8e80-7f0d-4df0-84ae-dec9fd3c4d7f">          |  <img width="200" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/1ca65537-955e-47c3-a28d-2eea312a5a65">     |
| Desktop - Chrome |               |   <img width="1440" alt="Capture d’écran 2024-05-06 à 14 44 32" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/6da565ec-cc7a-49fe-b3d3-faee3d2b234a">    |
[1]: …

(PC-29398) feat(booking): Add survey to booking details

---

__snapshots__/features/search/pages/Search/SearchN1Books/SearchN1Books.native.test.tsx.native-snap
__snapshots__/ui/components/buttons/SubcategoryButton/SubcategoryButton.native.test.tsx.native-snap
__snapshots__/ui/components/buttons/SubcategoryButton/SubcategoryButtonList.native.test.tsx.native-snap
scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx
src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
src/features/search/pages/Search/SearchN1Books/SearchN1Books.native.test.tsx
src/features/search/pages/Search/SearchN1Books/SearchN1Books.tsx
src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.native.test.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.stories.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButtonList.native.test.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButtonList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29105
I have:
| iOS - Cheatcodes |
| :--------------------------: |
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/312b4c6d-24e0-4d53-bdd1-687903d5fb11
| Chrome - Cheatcodes |
| :--------------------------: |
https://github.com/pass-culture/pass-culture-app-native/assets/158567429/47dad657-29ba-493c-8a30-2aa5e61f7be9

(PC-29105) feat(SearchN1Books): Création du composant carroussel

---

src/ui/components/CheckboxBlock/CheckboxBlock.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29438
Fix to not focus when click:

(PC-29438) fix(CheckboxBlock): removed focus onMouseDown

---

__snapshots__/features/subscription/page/OnboardingSubscription.native.test.tsx.native-snap
src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
src/features/subscription/components/modals/SubscriptionSuccessModal.native.test.tsx
src/features/subscription/components/modals/SubscriptionSuccessModal.web.test.tsx
src/features/subscription/page/OnboardingSubscription.tsx
src/features/subscription/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29439
I have:
| Platform         | Mockup | After |
| iOS              |       <img  width="200" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/71ee0641-1536-421c-aac2-c04332d42cba" >       | [ios_flou.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/e43c040c-29fd-426e-a18c-58e3e9ff2994)  |
| Android          | <img  width="200" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/1c8131fe-9201-48b7-bfaa-c281ba351991" >             |   [android_flou.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/fb5e005f-46de-4ded-9e45-b07a56986b56)    |
| Desktop - Chrome |     <img …

(PC-29439) feat(OnboardingSubscription): Add gradient to thematic list

---

src/features/profile/helpers/useChangeEmailMutationV2.native.test.ts
src/features/profile/helpers/useChangeEmailMutationV2.ts
src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmailContent.native.test.tsx
src/features/profile/pages/ConfirmChangeEmail/ConfirmChangeEmailContent.tsx
src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.native.test.tsx
src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.tsx
src/features/profile/pages/TrackEmailChange/TrackEmailChange.tsx
src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.native.test.tsx
src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.tsx
src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.native.test.tsx
src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28509
I have:

(PC-28509) feat(ChangeEmail): Improve navigation and scroll backs

---

src/libs/firebase/firestore/featureFlags/useFeatureFlag.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29386
I have:

(PC-29386) fix(app): add optionnal for set build number config

---

src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
src/features/culturalSurvey/pages/CulturalSurveyThanks.native.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyThanks.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
src/libs/storage.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28695
I have:

(PC-28695) feat(AppShareModal): remove share after credit

---

__snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
src/features/profile/pages/LegalNotices/LegalNotices.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29131
I have:
| Platform         |Before | After |
| Desktop - Chrome |        <img width="1440" alt="Capture d’écran 2024-05-16 à 11 49 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/3fc694d9-cc77-4b5e-aff9-e3ed6a716354">       |    <img width="1440" alt="Capture d’écran 2024-05-16 à 11 50 15" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/95ef7150-fcf5-47bf-b557-5ef292400276">   |

(PC-29131) fix(LegalNotices): Update wording

---

src/api/gen/api.ts
swagger_codegen/gen_templates/api.mustache

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29474
depends on : https://github.com/pass-culture/pass-culture-main/pull/12190
Pas de screen, c'est que du code généré par l'api
I have:

(PC-29474) fix(codegen): update query params handling in codegen

---

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29761
I have:

(PC-29761) feat(FF): add new feature flag wipAppV2VenueList

---

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29763
I have:

(PC-29763) feat(FF): add new feature flag wipAppV2LocationWidget

---

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29808
I have:

(PC-29808) feat(CategoryBlock): FF creation

---

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29746
I have:

(PC-29746) feat(FF): add new feature flag wipAppV2VenueMapBlock

---

__snapshots__/features/auth/pages/login/Login.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
__snapshots__/features/favorites/components/NotConnectedFavorites.native.test.tsx.native-snap
__snapshots__/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx.native-snap
__snapshots__/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx.native-snap
__snapshots__/features/subscription/NotificationsLoggedOutModal.native.test.tsx.native-snap
__snapshots__/features/tutorial/pages/onboarding/OnboardingWelcome.native.test.tsx.native-snap
__snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx.native-snap
__snapshots__/shared/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx.native-snap
src/features/auth/components/AuthenticationButton/AuthenticationButton.tsx
src/ui/components/buttons/buttonInsideText/ButtonInsideTextInner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28936
I have:

(PC-28936) feat(AuthenticationButton): Add connection button readable by voiceover

---

src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts
src/features/location/components/LocationWidget.native.test.tsx
src/features/location/components/LocationWidget.stories.tsx
src/features/location/components/LocationWidget.tsx
src/features/location/components/LocationWidget.web.test.tsx
src/features/location/components/LocationWidgetDesktop.native.test.tsx
src/features/location/components/LocationWidgetDesktop.web.test.tsx
src/features/location/components/LocationWidgetWrapperDesktop.tsx
src/ui/svg/icons/Location.tsx
src/ui/svg/icons/LocationPointerAppV2.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29762
I have:
| Phone - Chrome   |![Capture d’écran 2024-05-17 à 09 50 36](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/ffdefac0-47db-48b7-a860-f4f7e8d8d09b)|![Capture d’écran 2024-05-17 à 09 50 24](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/d12adf46-9b34-4f3b-9137-382c518a3a0b)|
| Desktop - Chrome |![Capture d’écran 2024-05-17 à 09 50 50](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/67e260fc-b312-48a7-946a-790c9f43b5bc)|![Capture …

(PC-29762) feat(LocationWidget): display conditionally location icon app v2

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/libs/contentful/adapters/modules/adaptAppV2VenuesModule.native.test.ts
src/libs/contentful/adapters/modules/adaptAppV2VenuesModule.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29784
I have:

(PC-29784) feat(adaptAppV2VenuesModule): add new the venues modules app v2 for contentful

---

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
src/features/profile/pages/Profile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29666
I have:
- [ x ] Made sure my feature is working on ios simulator

(PC-29666) fix(Profile): Added bounce when scrolling

---

server/src/index.ts
server/src/middlewares/tests/webAppProxyMiddleware.test.ts
server/src/middlewares/webAppProxyMiddleware.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29097
I have:

(PC-29097) fix(webproxy): Avoid returning 200 when not needed

---

__snapshots__/features/home/components/modules/venues/VenueTile.native.test.tsx.native-snap
__snapshots__/features/home/components/modules/venues/VenuesModule.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
src/features/home/components/modules/VenueListModule.native.test.tsx
src/features/home/components/modules/VenueListModule.stories.tsx
src/features/home/components/modules/VenueListModule.tsx
src/features/internal/cheatcodes/pages/AppComponents/iconsExports.ts
src/libs/algolia/fixtures/venuesSearchFixture.ts
src/ui/components/VenuePreview/VenuePreview.tsx
src/ui/svg/icons/ArrowRight.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29756
I have:

(PC-29756) feat(VenueListModule): add new venue list module app V2

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/venue/components/VenueBody/VenueBody.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29842
I have:
| iOS              |<img width="317" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/5c08dc7b-58e3-4de3-a05c-3b28baf2b8d7">|<img width="319" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ac860f21-309a-458d-acfc-a058e59dd7c8">|
| Android          |<img width="404" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/5351b441-b631-4264-aacf-4214f12c9285">|<img width="404" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/13b81be1-612f-474f-b …

(PC-29842) fix(venue): fix spacing in end of venue body

---

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29871
I have:

(PC-29871) feat(app): add wipAppV2SystemBlock feature flag

---

.github/dependabot.yml

feat(Dependabot): remove reviewers from dependabot.yml

---

doc/installation/Android.md
doc/installation/iOS.md

(BSR) docs(installation): move setup troubleshooting in docs

---

src/features/home/components/headers/HomeHeader.native.test.tsx
src/features/home/components/headers/HomeHeader.tsx
src/features/home/components/modules/banners/HomeBanner.native.test.tsx
src/features/home/components/modules/banners/HomeBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29804
I have:

(PC-29804) feat(HomeHeader): split Banner from Header

---

__snapshots__/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx.web-snap
__snapshots__/features/navigation/TabBar/TabBar.native.test.tsx.native-snap
src/features/favorites/components/BicolorFavoriteCount.native.test.tsx
src/features/favorites/components/BicolorFavoriteCount.tsx
src/features/favorites/components/BicolorFavoriteCountV2.tsx
src/features/favorites/helpers/useScaleFavoritesAnimation.ts
src/features/navigation/TabBar/TabBarComponent.tsx
src/features/navigation/TabBar/TabBarInnerComponentV2.tsx
src/features/navigation/TabBar/mapTabRouteToBicolorIcon.ts
src/ui/theme/constants.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29870
I have:
| iOS              |   <img width="293"  src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/a4cf65ba-223b-42a8-a456-91a70a2b4ded">  |  <img width="293"  src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/b216c360-860a-4962-8158-cff19484cc9a">     |
| Android          |      <img width="293"  src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/a4cf65ba-223b-42a8-a456-91a70a2b4ded">      |     <img width="293" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/36fcc3d6-4bb9-45e3-a3fc-50366a4235e1">    | …

(PC-29870) feat(tabbar): Add labels and counter

---

src/features/subscription/page/OnboardingSubscription.native.test.tsx
src/features/subscription/page/OnboardingSubscription.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29841
I have:
| iOS              | <img width="254" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/75068235/13128842-ca79-402d-86d1-7657ab9c000f"> | ![image](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/c11c2747-3c1a-48b4-a6ff-36ffc2a2fff5) |

(PC-29841) fix(OnboardingSubscription): fix wording

---

src/libs/firebase/firestore/featureFlags/getFeatureFlag.native.test.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29931
I have:

(PC-29931) feat(refonte): create FF for BusinessBlock and MultiVideoModule

---

src/features/home/components/SubscribeButtonWithModals.native.test.tsx
src/features/home/components/SubscribeButtonWithModals.tsx
src/features/home/pages/Home.native.test.tsx
src/features/home/pages/Home.tsx
src/features/subscription/helpers/useOnboardingSubscriptionModal.native.test.ts
src/features/subscription/helpers/useOnboardingSubscriptionModal.ts
src/features/venue/components/VenueThematicSection/VenueThematicSection.native.test.tsx
src/features/venue/components/VenueThematicSection/VenueThematicSection.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29809
I have:

(PC-29809) feat(subscription): hide subscription to non eligible users

---

__snapshots__/features/home/components/modules/venues/AppV2VenuesModule.native.test.tsx.native-snap
src/features/home/components/modules/HomeModule.native.test.tsx
src/features/home/components/modules/VenueListModule.native.test.tsx
src/features/home/components/modules/VenueListModule.tsx
src/features/home/components/modules/VenueListModule.web.test.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.native.test.tsx
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29899
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/62058919/494a099a-8125-4841-8a32-3a7203e2bd2e

(PC-29899) fix(VenueListModule): handle redirect to venueMap

---

src/features/subscription/page/OnboardingSubscription.native.test.tsx
src/features/subscription/page/OnboardingSubscription.tsx
src/ui/components/headers/EmptyHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29831

(PC-29831) feat(OnboardingSubscription): keep in storage view of sub page

---

__mocks__/@react-native-community/netinfo.ts
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts
src/libs/network/NetInfoWrapper.native.test.tsx
src/libs/network/NetInfoWrapper.tsx
src/libs/network/__mocks__/useNetInfo.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29927
I have:

(PC-29927) feat(NetInfo): add tracker for connection info

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29937
I have:

(PC-29937) feat(app): add wipAppV2SearchLandingHeader feature flag

---

src/features/home/components/modules/HomeModule.tsx
src/features/home/fixtures/homepage.fixture.ts
src/features/home/types.ts
src/libs/contentful/adapters/adaptHomepageModules.native.test.ts
src/libs/contentful/adapters/adaptHomepageModules.ts
src/libs/contentful/adapters/modules/adaptVideoCarouselModule.native.test.ts
src/libs/contentful/adapters/modules/adaptVideoCarouselModule.ts
src/libs/contentful/fixtures/videoCarousel.fixture.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29989
I have:

(PC-29989) feat(videoCarousel): add video carousel content model

---

__snapshots__/features/home/components/modules/categories/CategoryListModule.native.test.tsx.native-snap
src/features/home/components/modules/categories/CategoryBlock.tsx
src/features/home/components/modules/categories/CategoryListModule.tsx
src/features/search/components/CategoryButton/CategoryButtonV2.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29811
I have:
| IOS   |<img width="322" alt="PC-29805-avant" src="https://github.com/pass-culture/pass-culture-app-native/assets/163895831/fe1d8918-75d5-4dcf-9077-03dc96b4833e">|<img width="321" alt="Capture d’écran 2024-05-27 à 11 27 07" src="https://github.com/pass-culture/pass-culture-app-native/assets/163895831/d92566b0-1287-42fe-a8c9-9f5c01d632a0">|
| Desktop - Chrome |<img width="322" alt="PC-29805-avant" src="https://github.com/pass-culture/pass-culture-app-native/assets/163895831/fe1d8918-75d5-4dcf-9077-03dc96b4833e">|<img width="700" alt="PC-29805-avant" …

(PC-29811) feat(CategoryBlock): Add new category bloc design

---

tsconfig.json

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29982
I have:

(PC-29982) fix(sentry): fix sentry issue due to use of polyfill .at() in the search

---

__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
src/features/profile/pages/Profile.native.test.tsx
src/features/profile/pages/Profile.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29953
I have:

(PC-29953) feat(Profile): change wording geoloc

---

__snapshots__/features/home/components/modules/business/NewBusinessModule.native.test.tsx.native-snap
__snapshots__/features/home/components/modules/business/OldBusinessModule.native.test.tsx.native-snap
src/features/home/components/modules/HomeModule.web.test.tsx
src/features/home/components/modules/business/BusinessModule.tsx
src/features/home/components/modules/business/NewBusinessModule.native.test.tsx
src/features/home/components/modules/business/NewBusinessModule.tsx
src/features/home/components/modules/business/OldBusinessModule.native.test.tsx
src/features/home/components/modules/business/OldBusinessModule.tsx
src/features/home/fixtures/homepage.fixture.ts
src/features/home/types.ts
src/theme/index.ts
src/ui/components/buttons/ButtonPrimaryBlack.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29722
I have:
| iOS              |  <img width="205" alt="Capture d’écran 2024-05-28 à 11 24 18" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/00cd3e51-c509-4376-9495-47ba45d87e2e">|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-05-28 at 12 17 36](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/dc66a468-32ca-4998-928b-fd6b080ad194)|
| Desktop - Chrome |               |<img width="1072" alt="Capture d’écran 2024-05-28 à 12 02 54" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/f0da956d-5c5e-41cf-818b-35b5fd42 …

(PC-29722) feat(businessModule): new component

---

scripts/dead_code_snapshot.txt
src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/features/venue/components/VenueBody/VenueBody.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29425
I have:
| iOS              |        <img width="377" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/169038942/b3387916-629f-4e40-9da5-03d5d38fae83">       |     ![image](https://github.com/pass-culture/pass-culture-app-native/assets/169038942/8c4108a8-ae41-48d1-91c2-03b2c525bb15)  |
| Desktop - Chrome |               |    <img width="1512" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/169038942/3f474e68-21a2-4fed-bcab-368a3608275e">   |
[1]: …

(PC-29425) feat(VenuBody): display opening hours status

---

__snapshots__/features/navigation/RootNavigator/Header/Header.web.test.tsx.web-snap
src/features/navigation/RootNavigator/Header/Header.web.test.tsx
src/features/navigation/RootNavigator/Header/Nav.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30081
I have:
| Desktop - Chrome |               |    <img width="1440" alt="Capture d’écran 2024-05-30 à 09 46 52" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/b483ae5f-60a7-4b3a-a489-93bcc0d2561b">   |

(PC-30081) feat(nav): Use new icons when FF is enabled

---

scripts/appcenter-download-release.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30027
I have:

(PC-30027) fix(script): fix yarn appcenter

---

__snapshots__/features/search/components/SearchBox/SearchBox.native.test.tsx.native-snap
src/features/search/components/SearchBox/SearchBox.native.test.tsx
src/features/search/components/SearchMainInput/SearchMainInput.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29952
| iOS              |               |   <img width="345" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26348504/05f396fd-c13b-4425-b55b-7dec4c1d5fa9">    |
| Desktop - Chrome |               |   <img width="1155" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26348504/4c102e18-a725-441e-8ddb-6e48abd86864">    |

(PC-29952) feat(search): update search bar icon

---

src/features/home/components/BlackGradient.native.test.tsx
src/features/home/components/BlackGradient.tsx
src/features/home/components/modules/marketing/MarketingBlock.native.test.tsx
src/features/home/components/modules/marketing/MarketingBlock.tsx
src/features/home/components/modules/marketing/MarketingBlockContent.tsx
src/features/home/components/modules/marketing/MarketingBlockContentDesktop.tsx
src/features/home/components/modules/marketing/MarketingBlockExclusivity.native.test.tsx
src/features/home/components/modules/marketing/MarketingBlockExclusivity.stories.tsx
src/features/home/components/modules/marketing/MarketingBlockExclusivity.tsx
src/features/home/components/modules/marketing/MarketingBlockHighlight.native.test.tsx
src/features/home/components/modules/marketing/MarketingBlockHighlight.stories.tsx
src/features/home/components/modules/marketing/MarketingBlockHighlight.tsx
src/features/internal/cheatcodes/pages/MarketingBlocks.tsx
src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/libs/parsers/category.ts
src/ui/components/BlurryWrapper/BlurAmount.ts
src/ui/components/BlurryWrapper/BlurAmount.web.ts
src/ui/components/BlurryWrapper/BlurryWrapper.native.test.tsx
src/ui/components/BlurryWrapper/BlurryWrapper.tsx
src/ui/components/BlurryWrapper/BlurryWrapper.web.tsx
src/ui/theme/grid.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29958
I have:
| mobile              |     ![Capture d’écran 2024-06-03 à 08 46 39](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/ee9bbe6e-529d-474d-b6c8-117e0eefec2d) ![Capture d’écran 2024-06-03 à 08 46 31](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/7997e8f3-576f-4a66-918e-da2755b0bbe9) ![Capture d’écran 2024-06-03 à 08 46 22](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/6a4d44cf-a9fa-43dd-a0a5-4d0f719d385c) ![Capture d’écran 2024-06-03 à 08 46 13](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/ …

(PC-29958) feat(home): Add MarketingBlock

---

src/features/internal/cheatcodes/pages/CheatMenu/Video9:16/Video916.tsx
src/ui/CarouselBar/CarouselBar.native.test.tsx
src/ui/CarouselBar/CarouselBar.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30023
I have:
| Desktop - Chrome |<img width="529" alt="Capture d’écran 2024-06-03 à 09 54 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/be9a8e92-f0f1-4fbb-ad0b-14c1056db55a">|<img width="450" alt="Capture d’écran 2024-06-03 à 10 09 48" src="https://github.com/pass-culture/pass-culture-app-native/assets/144016890/b4ff54a3-5c1d-4a56-8585-e4146d4a592a">|

(PC-30023) feat(Video916): CarouselBar component

---

src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.native.test.tsx
src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.tsx
src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.native.test.ts
src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28849
I have:

(PC-28849) feat(OpeningHours): Update state automatically when change is imminent

---

__snapshots__/features/home/components/modules/categories/CategoryListModule.native.test.tsx.native-snap
src/features/home/components/modules/categories/CategoryBlock.tsx
src/features/home/components/modules/categories/CategoryListModule.native.test.tsx
src/features/home/components/modules/categories/CategoryListModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29811
I have:
| Desktop - Chrome |<img width="322" alt="PC-29805-avant" src="https://github.com/pass-culture/pass-culture-app-native/assets/163895831/64a0476f-bc3b-4915-bdde-411ba438c5f0">|<img width="700" alt="PC-29805-avant" src="https://github.com/pass-culture/pass-culture-app-native/assets/163895831/36f194bc-0a63-489a-bc51-a42181219bd0">|

(PC-29811) feat(Home): change CategoryBlockV2 size

---

src/features/search/components/SearchMainInput/SearchMainInput.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29952
| iOS              |               |    <img width="327" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26348504/bdf6ce2c-28ec-4e7b-b19b-4c66fe959179">   |
| Desktop - Chrome |               |  <img width="1045" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/26348504/3e6b6f14-4725-43b5-9b97-49aa1d1f1224">     |

(PC-29952) fix(search): fix icon color

---

CODEOWNERS
src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29420
I have:
| iOS              |<img width="353" alt="Capture d’écran 2024-06-04 à 10 38 21" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/183e95ab-f9b8-43fc-b819-ace496e6c32f">|<img width="455" alt="Capture d’écran 2024-06-04 à 10 37 56" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/14a8a6fb-b475-481d-a3d2-4be97066bf1d">|
| Phone - Chrome   |               |![Capture d’écran 2024-06-04 à 10 35 23](https://github.com/pass-culture/pass-culture-app-native/assets/78556024/87af9e7c-189f-4fa3-84fa-137 …

(PC-29420) refactor(reactions): graphic feedback

---

__snapshots__/features/home/components/modules/venues/AppV2VenuesModule.native.test.tsx.native-snap
src/features/home/components/modules/HomeModule.native.test.tsx
src/features/home/components/modules/VenueListModule.native.test.tsx
src/features/home/components/modules/VenueListModule.tsx
src/features/home/components/modules/VenueListModule.web.test.tsx
src/features/home/components/modules/VenueListModule.web.tsx
src/features/home/components/modules/VenueListModuleItem.native.test.tsx
src/features/home/components/modules/VenueListModuleItem.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.web.test.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.web.tsx
src/features/home/fixtures/homepage.fixture.ts
src/features/home/types.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/contentful/adapters/modules/adaptAppV2VenuesModule.native.test.ts
src/libs/contentful/adapters/modules/adaptAppV2VenuesModule.ts
src/libs/contentful/fixtures/appV2VenuesModule.fixture.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30077
I have:
| iOS              |               |<img width="432" alt="Capture d’écran 2024-06-04 à 11 01 31" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/dd2d07be-4cee-4fbc-a61d-e0075bfdacf6">|
| Phone - Chrome   |               |<img width="391" alt="Capture d’écran 2024-06-04 à 16 36 06" src="https://github.com/pass-culture/pass-culture-app-native/assets/62058919/77eb2d49-db8c-4ac9-aa88-9fa11dbb778e">|
| Desktop - Chrome |               |<img width="1262" alt="Capture d’écran 2024-06-04 à 16 34 46" …

(PC-30077) feat(VenueListModule): handle venue list module for web and web mobile

---

__snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap
__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
src/features/home/api/useVideoCarouselData.ts
src/features/home/components/headers/HomeHeader.tsx
src/features/home/components/helpers/getVideoPlayerDimensions.native.test.ts
src/features/home/components/helpers/getVideoPlayerDimensions.ts
src/features/home/components/helpers/videoSourceExtractor.ts
src/features/home/components/modules/categories/CategoryBlock.tsx
src/features/home/components/modules/video/ButtonWithCaption.tsx
src/features/home/components/modules/video/VerticalVideoEndView.tsx
src/features/home/components/modules/video/VerticalVideoPlayer.tsx
src/features/home/components/modules/video/VerticalVideoPlayer.web.tsx
src/features/home/components/modules/video/VideoCarouselModule.tsx
src/features/home/components/modules/video/VideoPlayer.tsx
src/features/home/components/modules/video/VideoPlayer.web.tsx
src/features/home/pages/GenericHome.tsx
src/features/home/pages/Home.tsx
src/features/home/types.ts
src/libs/algolia/fetchAlgolia/fetchCarouselVideoOffers.ts
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/buildVideoCarouselOffersQueries.native.test.ts
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/buildVideoCarouselOffersQueries.ts
src/libs/queryKeys.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29806
I have:

(PC-29806) feat(video): add video carousel

---

src/features/home/components/AttachedOfferCard.tsx
src/features/home/components/helpers/computeDateRangeDisplay.ts
src/features/home/components/modules/ThematicHighlightModule.native.test.tsx
src/features/home/components/modules/ThematicHighlightModule.tsx
src/features/home/components/modules/marketing/MarketingBlockContent.tsx
src/features/home/components/modules/marketing/MarketingBlockHighlight.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29839
I have:
| iOS              |![image](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/ec1c1533-02d6-4430-9449-9b630c949b21)|<img width="325" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/3aae4060-d2d2-4be7-810f-39957ca9cfcc">|
| Android          |![image](https://github.com/pass-culture/pass-culture-app-native/assets/68000368/45ad5c6e-c21e-4c36-89b3-84dc5a3c73b9)|<img width="381" alt="image" src="https://github.com/pass-culture/pass-culture-app-native/assets/68000368/60137c65-6287-41a8-b0d7-9a8e5cfaf08e">|
| Phone - Chrome …

(PC-29839) feat(Home): create new highlight module

---

src/features/home/components/banners/GeolocationBanner.native.test.tsx
src/features/home/components/banners/GeolocationBanner.tsx
src/features/home/pages/ThematicHome.native.test.tsx
src/features/home/pages/ThematicHome.tsx
src/features/offer/components/VenueSelectionList/VenueSelectionList.native.test.tsx
src/features/offer/components/VenueSelectionListHeader/VenueSelectionListHeader.native.test.tsx
src/features/offer/components/VenueSelectionModal/VenueSelectionModal.native.test.tsx
src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.native.test.tsx
src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
src/features/profile/pages/Profile.native.test.tsx
src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx
src/features/search/components/SearchListHeader/SearchListHeader.tsx
src/ui/components/ModuleBanner/GenericBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30076
I have:
| iOS              |               |<img width="464" alt="Capture d’écran 2024-06-03 à 16 37 02" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/13bdc7ca-f534-4e42-9430-38e7aa9f4cf3"> <img width="454" alt="Capture d’écran 2024-06-03 à 15 48 15" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/c226d7b3-847c-420c-bad1-4269216177dd">|
| Android          |               |<img width="412" alt="Capture d’écran 2024-06-03 à 15 48 25" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/e1b6034a-5b4f-4b1b-bab4-f3cfc9f …

(PC-30076) refactor(app): system banner harmonization

---

src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
src/features/offer/components/VenueSelectionList/VenueSelectionList.tsx
src/features/offer/components/VenueSelectionListHeader/VenueSelectionListHeader.tsx
src/features/offer/components/VenueSelectionModal/VenueSelectionModal.native.test.tsx
src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30175
I have:

(PC-30175) fix(offer): open location modal when pressing button on venue list

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/libs/firebase/remoteConfig/remoteConfig.constants.ts
src/libs/firebase/remoteConfig/remoteConfig.services.ts
src/libs/firebase/remoteConfig/remoteConfig.services.web.ts
src/libs/firebase/remoteConfig/remoteConfig.types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30172
I have:
[Remote config](https://console.firebase.google.com/u/0/project/passculture-native/config/env/firebase) (shouldApplyGraphicRedesign)
[AB Test](https://console.firebase.google.com/u/0/project/passculture-native/experiments/list) (Refonte graphique home staging iOS et Refonte graphique home staging Android)

(PC-30172) feat(firebase): add shouldApplyGraphicRedesign remote config

---

scripts/dead_code_snapshot.txt
src/features/home/components/AttachedOfferCard.tsx
src/features/home/components/modules/video/VerticalVideoEndView.tsx
src/features/home/components/modules/video/VerticalVideoPlayer.tsx
src/features/home/components/modules/video/VideoCarouselModule.tsx

BSR for making the player ready for demo
I have:

(BSR) feat(video): behavior adjustments

---

src/ui/components/ModuleBanner/SystemBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30176
I have:

(PC-30176) fix(SystemBanner): adjust the focus

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29449
I have:

(PC-29449) feat(FF): add new wipReactionFeature

---

__snapshots__/features/home/components/modules/OffersModule.native.test.tsx.native-snap
__snapshots__/features/offer/components/OfferTile/PlaylistCardOffer.native.test.tsx.native-snap
__snapshots__/ui/components/NewOfferCaption.native.test.tsx.native-snap
src/features/home/components/modules/video/VideoMultiOfferTile.tsx
src/features/offer/components/OfferTile/NewOfferTileContent.tsx
src/features/offer/components/OfferTile/OfferTile.tsx
src/features/offer/components/OfferTile/OldPlaylistCardOffer.tsx
src/features/offer/components/OfferTile/PlaylistCardOffer.native.test.tsx
src/features/offer/components/OfferTile/PlaylistCardOffer.tsx
src/ui/components/NewOfferCaption.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30148
I have:

(PC-30148) fix(NewOfferTileContent): use components form design system and rename to PlaylistCardOffer

---

src/features/home/components/modules/HighlightOfferModule.native.test.tsx
src/features/home/components/modules/HighlightOfferModule.tsx
src/features/home/components/modules/OffersModule.native.test.tsx
src/features/home/components/modules/OffersModule.tsx
src/features/home/components/modules/RecommendationModule.native.test.tsx
src/features/home/components/modules/RecommendationModule.tsx
src/features/home/components/modules/ThematicHighlightModule.native.test.tsx
src/features/home/components/modules/ThematicHighlightModule.tsx
src/features/home/components/modules/business/NewBusinessModule.native.test.tsx
src/features/home/components/modules/business/NewBusinessModule.tsx
src/features/home/components/modules/business/OldBusinessModule.native.test.tsx
src/features/home/components/modules/business/OldBusinessModule.tsx
src/features/home/components/modules/categories/CategoryListModule.native.test.tsx
src/features/home/components/modules/categories/CategoryListModule.tsx
src/features/home/components/modules/exclusivity/ExclusivityBanner.native.test.tsx
src/features/home/components/modules/exclusivity/ExclusivityBanner.tsx
src/features/home/components/modules/exclusivity/ExclusivityExternalLink.native.test.tsx
src/features/home/components/modules/exclusivity/ExclusivityExternalLink.tsx
src/features/home/components/modules/exclusivity/ExclusivityOffer.native.test.tsx
src/features/home/components/modules/exclusivity/ExclusivityOffer.tsx
src/features/home/components/modules/venues/VenuesModule.tsx
src/features/home/components/modules/video/VideoModule.native.test.tsx
src/features/home/components/modules/video/VideoModule.tsx
src/libs/analytics/logEventAnalytics.ts
src/libs/analytics/utils.ts
src/libs/firebase/analytics/utils.test.ts
src/shared/splitArrayIntoStrings/splitArrayIntoStrings.test.ts
src/shared/splitArrayIntoStrings/splitArrayIntoStrings.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30167
I have:

(PC-30167) feat(analytics): add offers and venues in ModuleDisplayedOnHomepage log

---

src/features/home/components/modules/TrendsModule.native.test.tsx
src/features/home/components/modules/TrendsModule.tsx

(BSR) fix(types): Fix params passed to analytics

---

.maestro/testsV2/AccessSignupFromBlock.yml
.maestro/testsV2/LoginAndSSO.yml
.maestro/testsV2/reusableFlows/GoToFavoritesFromTabBar.yml
.maestro/testsV2/reusableFlows/features/auth/LoginFromFavorites.yml
.maestro/testsV2/reusableFlows/features/auth/LoginGoogleFromProfil.yml
.maestro/testsV2/reusableFlows/features/auth/LoginWithWrongEmail.yml
.maestro/testsV2/reusableFlows/features/auth/LoginWithWrongPassword.yml
.maestro/testsV2/reusableFlows/features/auth/LogoutFromProfile.yml
.maestro/testsV2/reusableFlows/features/profil/HelpCenter.yml
.maestro/testsV2/reusableFlows/features/profil/SocialNetwork.yml
.maestro/testsV2/reusableFlows/features/search/SearchBookableCinemaOffer.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30085
I have:

(PC-30085) feat(maestro): add e2e test for login features and SSO

---

src/libs/analytics/utils.ts
src/libs/firebase/analytics/utils.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30167
I have:

(PC-30167) feat(analytics): update namming offers and venues params

---

src/features/home/components/modules/video/VerticalVideoPlayer.tsx

I have:
| Android          |         [before.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/9375986f-2295-49f4-8be0-86b9fae966b0)      |   [after.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/d7ead640-4584-4716-8de7-11a683bfd2aa)    |

(PC-30296) fix(YoutubePlayer): Tweak style to avoid crash on navigation

---

.maestro/testsV2/FirstLaunch.yml
.maestro/testsV2/reusableFlows/features/cookies/SelectOneCookie.yml
.maestro/testsV2/reusableFlows/features/cookies/SelectThreeCookies.yml
.maestro/testsV2/reusableFlows/features/cookies/SelectTwoCookies.yml
.maestro/testsV2/reusableFlows/features/tutorial/onboarding/Onboard16AndLocalization.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30255
I have:
(Vidéo dans le ticket jira)

(PC-30255) feat(maestro): add e2e test for first launch features

---

src/ui/components/ModuleBanner/SystemBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30176
I have:
| Desktop - Chrome |<img width="1188" alt="Capture d’écran 2024-06-12 à 17 34 57" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/58ed6a06-d23c-4f88-88dc-92471d7a30e4">|<img width="1077" alt="Capture d’écran 2024-06-12 à 17 34 41" src="https://github.com/pass-culture/pass-culture-app-native/assets/78556024/dda30ba5-b70d-436b-bc62-4b32b6a40be4">|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8 …

(PC-30176) fix(ui): graphic feedback focus system banner

---

__snapshots__/features/home/components/modules/business/NewBusinessModule.native.test.tsx.native-snap
src/features/home/components/modules/business/NewBusinessModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30060
Figma : https://www.figma.com/design/Q37VSWApslC2qsf2HrgguB/passCulture-V2-retravaille?node-id=4191-28105&m=dev
I have:
Phone - Chrome 
Desktop - Chrome

(PC-30060) fix(NewBusinessModule): typo

---

src/api/gen/api.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30327
I have:

(PC-30327) feat(AccesLibre): prepare feature

---

src/features/offer/components/OfferAccessibility/OfferAccessibility.tsx
src/features/venue/components/PracticalInformation/PracticalInformation.tsx
src/ui/components/Ul.tsx
src/ui/components/accessibility/AccessibilityBlock.native.test.tsx
src/ui/components/accessibility/AccessibilityBlock.tsx
src/ui/components/accessibility/BasicAccessibilityInfo.native.test.tsx
src/ui/components/accessibility/BasicAccessibilityInfo.stories.tsx
src/ui/components/accessibility/BasicAccessibilityInfo.tsx
src/ui/web/displayOnFocus/displayOnFocus.stories.tsx
src/ui/web/link/QuickAccess.stories.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28948
I have:
| Phone - Chrome   |               |  ![Capture d’écran 2024-06-13 à 14 23 00](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/c6b56cb3-c79e-4bd8-9623-dc34e98b80fa)  |
| Desktop - Chrome |               | ![Capture d’écran 2024-06-13 à 14 05 08](https://github.com/pass-culture/pass-culture-app-native/assets/62059034/0470773d-5a17-4e7b-adce-0b6a3ebab587) |

(PC-28948) feat(accessibility): Add BasicAccessibilityInfo component

---

__snapshots__/features/bookings/pages/Bookings/Bookings.native.test.tsx.native-snap
src/features/bookings/components/OnGoingBookingsList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30348
I have:
| iOS              |               |    ![Simulator Screenshot - iPhone 13 - 2024-06-14 at 16 42 42](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/8c621a1f-ec01-427a-8f8b-8def2e9a1ec3)   |
| Desktop - Chrome |               |     <img width="718" alt="Capture d’écran 2024-06-14 à 16 42 53" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/e97f4be3-a1e5-482d-a268-ebe915cced07">  |

(PC-30348) fix(bookings): Fix ended bookings position

---

src/features/auth/api/useSignIn.ts
src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx
src/features/auth/pages/signup/AccountCreated/AccountCreated.tsx
src/features/auth/pages/signup/AccountCreated/AccountCreated.web.test.tsx
src/features/culturalSurvey/api/useCulturalSurveyQuestions.ts
src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.web.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryRequestSent.native.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryRequestSent.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryRequestSent.web.test.tsx
src/features/navigation/RootNavigator/useInitialScreenConfig.native.test.tsx
src/features/navigation/RootNavigator/useInitialScreenConfig.tsx
src/libs/storage.ts
src/shared/culturalSurvey/shouldShowCulturalSurvey.ts
src/shared/culturalSurvey/useShouldShowCulturalSurvey.native.test.ts
src/shared/culturalSurvey/useShouldShowCulturalSurvey.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-18485
I have:

(PC-18485) feat(qpi): Limit cultural survey displays to 3 times

---

src/features/home/components/modules/video/VerticalVideoPlayer.tsx
src/features/home/components/modules/video/VideoCarouselModule.tsx
src/features/home/components/modules/video/useVerticalVideoPlayer.ts
src/features/navigation/RootNavigator/types.ts
src/libs/analytics/logEventAnalytics.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30275
I have:
| ConsultVideo              |<img width="655" alt="Capture d’écran 2024-06-14 à 16 29 15" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/4960d755-0622-4ba1-8c83-86226eae7d77">|
| HasSeenAllVideo              |<img width="650" alt="Capture d’écran 2024-06-17 à 11 22 39" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/41dc3bf6-e9c4-4e80-a7bd-a78c5a4a80aa">|

(PC-30275) feat(analytics): add trackers for video carousel

---

__snapshots__/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx.native-snap
src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30337
I have:
<video width="635" alt="Screenshot 2024-06-14 at 11 21 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/163895831/4649212d-d52d-43be-8fb8-f320dab7d361">|<video width="635" alt="Screenshot 2024-06-14 at 11 21 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/163895831/13427287-d212-447a-9205-6ceb13fa13fa">|

(PC-30337) feat(Venue): add animation

---

src/features/home/components/modules/video/VideoCarouselModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30278
I have:
| logModuleDisplayedOnHomepage |![image](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/e642d06d-b8c2-4c2c-90d1-05603c27a672)|

(PC-30278) feat(analytics): add tracker on video carousel module displayed

---

src/features/home/components/modules/OffersModule.native.test.tsx
src/features/home/components/modules/venues/VenueTile.tsx
src/features/home/components/modules/venues/VenuesModule.tsx
src/features/home/components/modules/video/VideoMultiOfferPlaylist.tsx
src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx
src/features/navigation/TabBar/TabBar.native.test.tsx
src/features/offer/components/OfferTile/OfferTile.tsx
src/libs/styled/useComputedTheme.ts
src/theme/index.ts
src/ui/components/PassPlaylist.tsx
src/ui/components/Playlist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30414
I have:
| Android              |     [bug.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/353bb0c8-93ee-43eb-9ac6-503dd5857330)      |    [fix.mp4](https://github.com/pass-culture/pass-culture-app-native/assets/46637324/579276c8-cc6f-4cd2-96a7-7a9b7cf4c243)   |

(PC-30414) fix(playlist): Add min height to display playlists on Android

---

src/features/home/components/modules/video/useVerticalVideoPlayer.ts
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30428
I have:
| VideoPaused              |<img width="647" alt="Capture d’écran 2024-06-19 à 15 31 57" src="https://github.com/pass-culture/pass-culture-app-native/assets/47600889/c2acae2e-cfb6-4dbc-a2ec-05d5549b469b">|

(PC-30428) feat(analytics): add video paused tracker

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/venue/components/VenueBody/VenueBanner.tsx
src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/features/venue/components/VenueBody/VenueBody.tsx
src/features/venue/components/VenueContent/VenueContent.native.test.tsx
src/features/venue/components/VenueContent/VenueContent.tsx
src/features/venue/components/VenueHeader/VenueHeader.native.test.tsx
src/features/venue/components/VenueHeader/VenueHeader.tsx
src/features/venue/components/VenueTopComponent/VenueTopComponent.native.test.tsx
src/features/venue/components/VenueTopComponent/VenueTopComponent.tsx
src/features/venue/pages/Venue/Venue.native.test.tsx
src/features/venue/pages/Venue/Venue.tsx
src/features/venue/pages/Venue/Venue.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27827
I have:

(PC-27827) refactor(venue): reorganize logic

---

package.json
src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.stories.tsx
src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.tsx
src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.native.test.ts
src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.ts
src/features/venue/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28847
I have:

(PC-28847) feat(getOpeningHoursStatus): opening hours details

---

src/App.tsx
src/features/navigation/RootNavigator/linking/getStateFromPath.test.ts
src/features/navigation/RootNavigator/linking/getStateFromPath.ts
src/libs/firebase/analytics/AnalyticsInitializer.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29766
I have:

(PC-29766) fix(firebase): Fix marketing event attribution

---

src/features/home/components/modules/venues/AppV2VenuesModule.native.test.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.web.test.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30429
I have:

(PC-30429) feat(home): use ModuleDisplayedOnHomepage log on AppV2VenuesModule

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30430
I have:
|Firestore|![image](https://github.com/pass-culture/pass-culture-app-native/assets/47600889/0b685a9f-4c04-4418-b35d-38a3dd1f3015)|

(PC-30430) feat(featureFlag): add FF for video 7:10 web version

---

package.json
yarn.lock

(BSR) chore(accessibility): Update jest axe and axe storybook testing

---

src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
src/features/venueMap/pages/VenueMap/VenueMap.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30404
I have:

(PC-30404) feat(venueMap): reset venue type code in store when pressing back button

---

src/features/home/components/banners/GeolocationBanner.tsx
src/features/home/components/banners/SignupBanner.tsx
src/features/home/components/modules/banners/HomeBanner.tsx
src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts
src/ui/components/ModuleBanner/SystemBanner.native.test.tsx
src/ui/components/ModuleBanner/SystemBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30447
I have:

(PC-30447) feat(SystemBanner): Add prop for analytics type

---

src/features/home/components/banners/GeolocationBanner.native.test.tsx
src/features/home/components/banners/GeolocationBanner.tsx
src/features/home/components/banners/SignupBanner.tsx
src/features/home/components/modules/banners/HomeBanner.tsx
src/features/home/pages/ThematicHome.tsx
src/features/offer/components/VenueSelectionListHeader/VenueSelectionListHeader.tsx
src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
src/features/search/components/SearchListHeader/SearchListHeader.tsx
src/libs/analytics/logEventAnalytics.ts
src/ui/components/ModuleBanner/SystemBanner.native.test.tsx
src/ui/components/ModuleBanner/SystemBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30447
I have:

(PC-30447) feat(SystemBanner): Add from param to tracker

---

src/features/home/components/modules/video/VerticalVideoPlayer.tsx
src/features/home/components/modules/video/VideoCarouselModule.tsx
src/features/home/components/modules/video/useVerticalVideoPlayer.ts

(BSR) fix(analytics): limit module displayed tracking and enhance video tracking behavior

---

src/features/home/components/modules/video/VideoCarouselModule.tsx

(BSR) fix(analytics): limit consultVideo tracker for web

---

yarn.lock

Commande : `npx yarn-audit-fix`
I have:
| command         | Before | After |
| yarn audit              |     <img width="379" alt="Capture d’écran 2024-06-20 à 17 48 00" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/ceab5d48-521e-4bb7-b2ce-1045b6815cb9"> |  <img width="378" alt="Capture d’écran 2024-06-20 à 17 45 58" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/099b315b-e8ac-4f94-ba1b-b475dcae2e7d">  |

(BSR) chore(deps): Use yarn-audit-fix to reduce some vulnerability

---

server/yarn.lock

Commande : `npx yarn-audit-fix`
I have:
| command         | Before | After |
| yarn audit              | <img width="348" alt="Capture d’écran 2024-06-20 à 17 48 25" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/d2b4742c-2beb-487e-808f-05ad178e4413">  |  <img width="345" alt="Capture d’écran 2024-06-20 à 17 49 29" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/e2b70ca3-fb6c-4330-be47-c50336df6dc2"> |

(BSR) chore(deps): Use yarn-audit-fix to reduce some vulnerability in server

---

src/features/cookies/components/CookiesAccordion.tsx
src/features/cookies/components/CookiesSettings.tsx
src/features/cookies/pages/CookiesDetails.tsx
src/features/internal/cheatcodes/pages/AppComponents/AppComponents.tsx
src/features/internal/marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
src/ui/components/Accordion.native.test.tsx
src/ui/components/Accordion.stories.tsx
src/ui/components/Accordion.tsx
src/ui/components/FilterSwitch.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28702
I have:
| iOS              |           <img width="400" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/88f808e1-91a2-4450-8868-e46dc11389aa">    |   <img width="500" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/199dcedc-559c-4045-9ed9-5ea6f897434e"> |
| Desktop - Chrome |       <img width="1440" alt="Capture d’écran 2024-06-21 à 15 06 22" src="https://github.com/pass-culture/pass-culture-app-native/assets/46637324/22518cb6-8b8c-4fa2-9f35-df48f434c1f6">        |   <img width="1440" alt="Capture d’écran 2024-06-21 à 15 05 40" …

(PC-28702) refactor(AccordionItem): Rename component

---

src/features/home/components/modules/VenueListModule.native.test.tsx
src/features/home/components/modules/VenueListModule.tsx
src/features/home/components/modules/VenueListModule.web.test.tsx
src/features/home/components/modules/VenueListModule.web.tsx
src/features/home/components/modules/VenueListModuleItem.native.test.tsx
src/features/home/components/modules/VenueListModuleItem.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.tsx
src/features/home/components/modules/venues/AppV2VenuesModule.web.tsx
src/libs/analytics/logEventAnalytics.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30506
I have:

(PC-30506) feat(venueListModule): update tracker params

---

src/features/offer/api/useSimilarOffers.native.test.ts
src/features/offer/api/useSimilarOffers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30526
I have:

(PC-30526) feat(offer): log sentry error when similar offers API responds an error

---

__snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap
src/features/bookings/components/EndedBookingItem.native.test.tsx
src/features/bookings/components/EndedBookingItem.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx
src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx
src/ui/components/buttons/RoundedButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29446
I have:
| iOS              |               |![Capture d’écran 2024-06-24 à 18 23 09](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/6f65cbc0-9396-4f7d-a574-47dce3c200d4)![Capture d’écran 2024-06-24 à 18 23 25](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/252b6fb7-74f4-452f-be95-de8e3e3b848f)|
| Desktop - Chrome |               |![Capture d’écran 2024-06-24 à 18 24 24](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/0a74972d-b335-41a3- …

(PC-29446) feat(EndedBookingItem): display reaction button

---

src/features/home/components/Trend.tsx
src/features/home/components/modules/TrendsModule.native.test.tsx
src/features/home/components/modules/TrendsModule.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30552
I have:

(PC-30552) feat(TrendsModule): complete tracker in trends module

---

src/features/home/components/modules/marketing/MarketingBlockExclusivity.stories.tsx
src/ui/components/ModuleBanner/SystemBanner.stories.tsx

(BSR) fix(storybook): repare broken stories

---

src/features/offer/components/OfferContent/OfferContent.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.tsx
src/features/offer/components/OfferPreviewModal/OfferPreviewModal.tsx
src/features/offer/components/OfferPreviewModal/OfferPreviewModal.web.test.tsx
src/ui/components/modals/AppModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30083
I have:
https://github.com/pass-culture/pass-culture-app-native/assets/173043140/ba3d701d-9bd0-4347-9f07-5f9d63a43ac1

(PC-30083) feat(Offer): display offer image/carousel in dedicated modal (web only)

---

package.json
server/package.json
server/yarn.lock
src/features/auth/pages/login/Login.native.test.tsx
src/features/home/components/modules/banners/HomeBanner.native.test.tsx
src/features/offer/components/OfferCTAButton/OfferCTAButton.native.test.tsx
yarn.lock

(BSR) feat(tests): Update msw from 0.49.0 to 1.2.3

---

src/features/bookOffer/components/CancellationDetails.native.test.tsx
src/features/bookOffer/components/CancellationDetails.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30079
I have:
| Desktop - Chrome | <img width="529" alt="Capture d’écran 2024-06-28 à 12 28 32" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/32f9020d-5333-44c7-82f4-d519f7712312"> | <img width="538" alt="Capture d’écran 2024-06-28 à 12 27 34" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/b4bc943e-ccdd-47bc-af07-bd6738d48525"> |

(PC-30079) feat(CGU): Update CGU for digital paid offers

---

src/libs/recommendation/useHomeRecommendedIdsQuery.native.test.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30593
I have:

(PC-30593) fix(home): prevent login screen when reco block appears

---

__snapshots__/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx.web-snap
__snapshots__/features/navigation/TabBar/TabBar.native.test.tsx.native-snap
src/ui/theme/constants.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30324
I have:
| iOS              | ![Simulator Screenshot - iPhone 13 - 2024-06-28 at 16 27 29](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/094bc1a4-1751-4c2f-9bb8-49000a4f89d0) | ![Simulator Screenshot - iPhone 13 - 2024-06-28 at 16 27 17](https://github.com/pass-culture/pass-culture-app-native/assets/75068235/35fb166d-38b5-40d5-a4dc-12947bdd6b2c)|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066c …

(PC-30324) fix(tabbar): reduced size mobile

---

src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.native.test.tsx
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.tsx
src/features/search/components/SearchListHeader/SearchListHeader.native.test.tsx
src/features/search/components/SearchListHeader/SearchListHeader.tsx
src/features/search/components/SearchListHeader/SearchListHeader.web.test.tsx
src/features/venueMap/pages/VenueMap/VenueMap.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-27697
I have:

(PC-27697) refactor(venueMap): use only wipVenueMap feature flag for the whole feature

---

src/features/gtlPlaylist/components/GtlPlaylist.tsx
src/features/offer/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx
src/features/offer/components/OfferPlaylistList/OfferPlaylistList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30594
I have:

(PC-30594) fix(OfferTile): Use V2 variant everywhere

---

src/features/culturalSurvey/api/useCulturalSurveyQuestions.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30593
I have:

(PC-30593) fix(Login): remove Login screen popup at app start

---

.github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml
scripts/get_used_routes.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28288
I have:

(PC-28288) ci(versioningApi): find routes used when creating tag

---

src/features/home/components/modules/RecommendationModule.native.test.tsx
src/features/home/components/modules/RecommendationModule.tsx
src/libs/analytics/logEventAnalytics.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30684
I have:

(PC-30684) fix(home): api reco params at the same level as the other params for ModuleDisplayedOnHomepage log

---

src/features/culturalSurvey/components/CulturalSurveyCheckbox.stories.tsx
src/features/search/components/SearchHistory/SearchHistory.tsx
src/features/search/components/SearchHistoryItem/SearchHistoryItem.stories.tsx
src/features/search/components/SearchHistoryItem/SearchHistoryItem.tsx
src/ui/components/radioButtons/RadioButton.stories.tsx

(BSR) feat(accessibility): Fix some storybook accessibility error

---

src/features/auth/pages/forgottenPassword/ResetPasswordExpiredLink/ResetPasswordExpiredLink.tsx
src/features/auth/pages/signup/SignupConfirmationEmailSent/EmailResendModal.tsx
src/features/auth/pages/signup/SignupConfirmationExpiredLink/SignupConfirmationExpiredLink.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.tsx
src/features/cookies/helpers/useCookies.ts
src/features/errors/pages/AsyncErrorBoundary.native.test.tsx
src/features/errors/pages/AsyncErrorBoundary.tsx
src/features/errors/pages/AsyncErrorBoundary.web.test.tsx
src/features/errors/pages/ScreenErrorProvider.tsx
src/features/home/api/useHomepageData.ts
src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx
src/features/internal/cheatcodes/pages/NavigationErrors/NavigationErrors.tsx
src/features/internal/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NavigationIdentityCheck.tsx
src/features/offer/api/useOffer.ts
src/features/offer/api/useOffersStocks.ts
src/features/profile/helpers/useEmailUpdateStatus.native.test.ts
src/features/profile/helpers/useEmailUpdateStatus.ts
src/features/search/helpers/useSearchHistory/useSearchHistory.ts
src/features/trustedDevice/pages/SuspensionChoice.tsx
src/features/venue/api/useVenue.ts
src/libs/firebase/firestore/featureFlags/useFeatureFlag.ts
src/libs/hooks/useLogTypeFromRemoteConfig.native.test.ts
src/libs/hooks/useLogTypeFromRemoteConfig.ts
src/libs/monitoring/errors.test.ts
src/libs/monitoring/errors.ts
src/libs/react-native-google-sso/useGoogleLogin.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30462
I have:

(PC-30462) feat(monitoring): improve Sentry error management and use of shouldLogInfo remote config

---

__snapshots__/features/home/components/modules/OffersModule.native.test.tsx.native-snap
__snapshots__/features/home/components/modules/venues/VenuesModule.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/home/components/headers/CategoryThematicHomeHeader.tsx
src/features/home/components/headers/DefaultThematicHomeHeader.tsx
src/ui/components/PassPlaylist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30525
I have:
| iOS              |      <img width="384" alt="Capture d’écran 2024-07-04 à 15 20 27" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/38020991-7617-4f05-a864-c16ba4463ede">  |  <img width="384" alt="Capture d’écran 2024-07-04 à 15 18 39" src="https://github.com/pass-culture/pass-culture-app-native/assets/62059034/fb129206-6422-455e-9f2c-4d8b757b3141">  | …

(PC-30525) feat(home): Remove fixed max height for playlist title

---

__snapshots__/features/offer/components/OfferTile/OfferTile.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
scripts/noUncheckedIndexedAccess_snapshot.txt
src/api/useSearchVenuesOffer/useSearchVenueOffers.native.test.ts
src/api/useSearchVenuesOffer/useSearchVenueOffers.ts
src/features/gtlPlaylist/components/GtlPlaylist.tsx
src/features/home/components/modules/OffersModule.tsx
src/features/home/components/modules/RecommendationModule.tsx
src/features/home/components/modules/VenueListModuleItem.tsx
src/features/home/components/modules/venues/VenueTile.native.test.tsx
src/features/home/components/modules/venues/VenueTile.stories.tsx
src/features/home/components/modules/venues/VenueTile.tsx
src/features/home/components/modules/venues/VenuesModule.tsx
src/features/home/components/modules/video/VideoMultiOfferTile.tsx
src/features/internal/cheatcodes/pages/AppComponents/AppComponents.tsx
src/features/offer/components/OfferContent/OfferContentBase.tsx
src/features/offer/components/OfferPlaylistList/OfferPlaylistList.native.test.tsx
src/features/offer/components/OfferPlaylistList/OfferPlaylistList.tsx
src/features/offer/components/OfferTile/OfferTile.native.test.tsx
src/features/offer/components/OfferTile/OfferTile.stories.tsx
src/features/offer/components/OfferTile/OfferTile.tsx
src/features/offer/types.ts
src/features/venue/components/VenueOfferTile/VenueOfferTile.native.test.tsx
src/features/venue/components/VenueOffers/VenueOffersList.tsx
src/libs/tileAccessibilityLabel.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29423
I have:
| Desktop - Chrome | <img width="400" alt="Capture d’écran 2024-07-03 à 20 48 17" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/8d07da30-7ca3-4bd3-8eb6-0a7b93b34901"> | <img width="400" alt="Capture d’écran 2024-07-03 à 20 45 03" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/afa2b203-b2e1-408b-9bb5-0d793d7b1cfe">  |

(PC-29423) feat(Localisation): suppression du repère géographique quand la geoloc est imprécise

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/venue/components/PracticalInformation/PracticalInformation.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts
src/shared/accessibility/AccessibilityBlock.native.test.tsx
src/shared/accessibility/AccessibilityBlock.tsx
src/ui/components/accessibility/DetailedAccessibilityInfo.native.test.tsx
src/ui/components/accessibility/DetailedAccessibilityInfo.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28781
I have:

(PC-28781) feat(accessibility): Add some analytics for acceslibre

---

src/features/bookOffer/components/BookingOfferModalFooter.native.test.tsx
src/features/bookOffer/components/BookingOfferModalFooter.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30674
I have:
| Platform         | Mockup|
| Desktop - Chrome | <img width="890" alt="Capture d’écran 2024-07-08 à 12 03 03" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/f6e54d7c-9e77-4f8e-a80b-340a5dd1f708"> |

(PC-30674) feat(tracking): ajout de tracker dans le parcours de résa

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/remoteConfig/__mocks__/remoteConfigProvider.tsx
src/libs/firebase/remoteConfig/remoteConfig.constants.ts
src/libs/firebase/remoteConfig/remoteConfig.services.ts
src/libs/firebase/remoteConfig/remoteConfig.services.web.ts
src/libs/firebase/remoteConfig/remoteConfig.types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30694
I have:

(PC-30694) feat(offer): use react button in more offer categories

---

__snapshots__/features/bookings/pages/Bookings/Bookings.native.test.tsx.native-snap
__snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/bookings/components/NoBookingsView.tsx
src/features/bookings/components/OnGoingBookingsList.native.test.tsx
src/features/bookings/components/OnGoingBookingsList.tsx
src/features/bookings/pages/Bookings/Bookings.native.test.tsx
src/features/bookings/pages/Bookings/Bookings.perf.test.tsx
src/features/bookings/pages/Bookings/Bookings.tsx
src/features/bookings/pages/Bookings/Bookings.web.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx
src/features/venue/components/TabLayout/InfoTab.tsx
src/features/venue/components/TabLayout/TabLayout.native.test.tsx
src/features/venue/components/TabLayout/TabLayout.tsx
src/features/venue/components/TabLayout/TabLayout.web.test.tsx
src/features/venue/components/TabLayout/useTabArrowNavigation.ts
src/features/venue/components/TabLayout/useTabArrowNavigation.web.ts
src/features/venue/components/VenueBody/VenueBody.tsx
src/features/venue/types.ts
src/libs/firebase/firestore/types.ts
src/ui/components/NoResultsView.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29447
I have:
| iOS              |![Capture d’écran 2024-07-08 à 15 15 40](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/ca487ecd-6011-437e-af63-7b436fb5a67e)![Capture d’écran 2024-07-08 à 15 15 50](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/55583970-08ed-4757-9512-32582d50b097)|![Capture d’écran 2024-07-08 à 15 13 22](https://github.com/pass-culture/pass-culture-app-native/assets/62058919/27e9031b-96b4-42de-a7a7-5b6f5305be34)![Capture d’écran 2024-07-08 à 15 …

(PC-29447) feat(Bookings): add Tabs for Bookings (on going bookings and ended bookings

---

src/features/offer/components/MovieCalendar/hooks/useMovieCalendarDay.ts
src/features/offer/components/MoviesScreeningCalendar/NextScreeningButton.native.test.tsx
src/features/offer/components/MoviesScreeningCalendar/NextScreeningButton.tsx
src/ui/components/banners/InfoBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30651
I have:
| Platform         | Mockup |
| iOS              | ![Simulator Screenshot - iPhone 15 - 2024-07-09 at 00 42 01](https://github.com/pass-culture/pass-culture-app-native/assets/158567429/22abd312-1c5d-4b22-947e-02dada7632c1) |
| Desktop - Chrome | <img width="1019" alt="Capture d’écran 2024-07-09 à 00 42 50" src="https://github.com/pass-culture/pass-culture-app-native/assets/158567429/85a8a065-86cd-49d8-9c1d-3e7ab2061af0"> |

(PC-30651) feat(Venue): Create NextScreeningButton

---

.maestro/tests/analytics/hasBeenCalled.js
.maestro/testsV2/UserNotConnectedMode.yml
.maestro/testsV2/VenueAndBookingSectionCheck.yml
.maestro/testsV2/config.yaml
.maestro/testsV2/subFolder/GoToBookingFromVenue.yml
.maestro/testsV2/subFolder/auth/LoginFromFavorites.yml
.maestro/testsV2/subFolder/auth/LoginFromModal.yml
.maestro/testsV2/subFolder/auth/LoginFromPhysicalOffer.yml
.maestro/testsV2/subFolder/auth/LoginFromProfileForBeneficiaryUser.yml
.maestro/testsV2/subFolder/booking/BookCinemaOffer.yml
.maestro/testsV2/subFolder/booking/BookDuoOffer.yml
.maestro/testsV2/subFolder/booking/BookingSectionNotAvailable.yml
.maestro/testsV2/subFolder/booking/CheckBookingSection.yml
.maestro/testsV2/subFolder/search/SearchBookablePhysicalOffer.yml
.maestro/testsV2/subFolder/venue/AccessVenueFromOffer.yml
.maestro/testsV2/subFolder/venue/VerifyOfferInfo.yml
.maestro/testsV2/subFolder/venue/VerifyVenueInfo.yml
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30537
I have:

feat(maestro): add P2 to not connected script

---

.eslintrc.js
eslint-custom-rules/no-empty-arrow-function.js
eslint-custom-rules/no-empty-arrow-function.test.js
eslint-local-rules.js
src/features/home/components/modules/video/VerticalVideoPlayer.native.test.tsx
src/features/offer/components/OfferPreviewModal/OfferPreviewModal.web.test.tsx
src/features/offer/components/OfferVenueBlock/OfferVenueBlock.native.test.tsx
src/features/offer/components/OfferVenueBlock/OfferVenueBlockDeprecated.native.test.tsx
src/features/search/components/CalendarPicker/CalendarPicker.web.test.tsx
src/features/trustedDevice/pages/AccountSecurityBuffer.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30767
I have:

(PC-30767) feat(eslint): add rule to use jest.fn() rather than () => {}

---

devbox.lock
flake.lock
package.json

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30749
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb04cfee

(PC-30749) chore(environment): add script to update tools easily

---

src/features/auth/api/useSignIn.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30772
I have:

(PC-30772) fix(Login): redirection after login from offer

---

src/features/navigation/RootNavigator/types.ts
src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/venue/components/TabLayout/TabLayout.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.tsx
src/features/venueMap/pages/VenueMap/VenueMap.tsx
src/libs/analytics/logEventAnalytics.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30765
I have:

(PC-30765) feat(tracker): add new tracker on map tab in search

---

__snapshots__/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx.native-snap
__snapshots__/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx.native-snap
src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.native.test.tsx
src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx
src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.test.ts
src/features/offer/components/MovieScreeningCalendar/useSelectedDateScreenings.ts
src/features/offer/components/MoviesScreeningCalendar/MovieOfferTile.tsx
src/ui/components/eventCard/EventCardList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30580
I have:
| iOS              | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-07-09 at 14 46 32](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/c856b167-7ec8-4706-98f6-4200972e8eb0) | ![Simulator Screenshot - iPhone 13 mini - 2024-07-09 at 12 43 15](https://github.com/pass-culture/pass-culture-app-native/assets/144016890/78152541-6cd4-461f-9011-98bd101ab212)|
| Phone - Chrome   |<img width="376" alt="Capture d’écran 2024-07-09 à 14 45 17" …

(PC-30580) fix(ui): margins of moviescreeningcalendar

---

__snapshots__/features/identityCheck/pages/profile/SetStatus.native.test.tsx.native-snap
src/features/identityCheck/pages/profile/SetStatus.tsx
src/features/subscription/helpers/useOnViewableItemsChanged.ts
src/features/subscription/page/OnboardingSubscription.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30735
I have:
| iOS              | ![Simulator Screenshot - iPhone 13 - 2024-07-14 at 20 42 40](https://github.com/user-attachments/assets/9a7766c4-15b9-4ef1-a0ed-5d586d523e73) |  ![Simulator Screenshot - iPhone 13 - 2024-07-14 at 20 40 34](https://github.com/user-attachments/assets/cf27a8b1-12b9-4333-93bc-3ddb50ce53e1) |
| Desktop - Chrome | <img width="1532" alt="image" src="https://github.com/user-attachments/assets/798a91c0-380a-4e …

(PC-30735) refactor(SetStatus): add fade on button

---

__snapshots__/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx.native-snap
__snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx.web-snap
__snapshots__/ui/components/tiles/HorizontalOfferTile.native.test.tsx.native-snap
__snapshots__/ui/components/tiles/HorizontalTile.native.test.tsx.native-snap
src/features/offer/components/MoviesScreeningCalendar/MovieOfferTile.tsx
src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx
src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
src/features/offer/components/MoviesScreeningCalendar/NextScreeningButton.tsx
src/features/offer/components/MoviesScreeningCalendar/createBuilder.ts
src/features/offer/components/MoviesScreeningCalendar/filterOffersStocks.test.ts
src/features/offer/components/MoviesScreeningCalendar/filterOffersStocksByDate.test.ts
src/features/offer/components/MoviesScreeningCalendar/filterOffersStocksByDate.ts
src/features/offer/components/MoviesScreeningCalendar/getNextMoviesByDate.test.ts
src/features/offer/components/MoviesScreeningCalendar/getNextMoviesByDate.ts
src/features/offer/components/MoviesScreeningCalendar/moviesOffer.builder.ts
src/features/offer/components/MoviesScreeningCalendar/offersStockResponse.builder.ts
src/features/venue/components/VenueOffers/VenueOffers.tsx
src/types.ts
src/ui/components/tiles/OfferName.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30629
I have:
| iOS              ||<img width="394" alt="Capture d’écran 2024-07-16 à 18 25 01" src="https://github.com/user-attachments/assets/685c30c7-33c3-4caa-b53b-831cff19965a">|
| Desktop - Chrome ||<img width="994" alt="Capture d’écran 2024-07-16 à 18 25 45" src="https://github.com/user-attachments/assets/7deef505-feba-4716-9807-558f3551cda9">|

(PC-30629) feat(XPCine): Add Next Screenings

---

ios/PassCulture.xcodeproj/project.pbxproj
ios/Podfile.lock

Podfile needed to be updated after this upgrade : https://passculture.atlassian.net/browse/PC-30653

(BSR) chore(deps): update pods after RNDeviceInfo upgrade

---

.storybook/preview-head.html
package.json
public/font-faces.css
public/index.html
yarn.lock

(BSR) feat(designSystem): implement pass culture design-system lib

---

src/features/home/api/asyncStorageAttrakdiff.native.test.ts
src/features/home/api/asyncStorageAttrakdiff.ts
src/features/home/api/useAttrakdiffModal.native.test.ts
src/features/home/api/useAttrakdiffModal.ts
src/features/home/pages/Home.tsx
src/features/identityCheck/api/useCreditActivation.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
src/libs/react-native-batch/enums.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30630
I have:

(PC-30630) feat(Attrakdiff): Add Batch Attrakdiff

---

src/features/home/components/modules/video/useVerticalVideoPlayer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30928
I have:

(PC-30928) fix(analytics): make sure logVideoPaused in called for every pause event

---

__snapshots__/features/identityCheck/pages/profile/SetStatus.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ChangeStatus/ChangeStatus.native.test.tsx.native-snap
src/features/identityCheck/pages/profile/SetStatus.tsx
src/features/identityCheck/pages/profile/StatusFlatList.tsx
src/features/internal/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/features/profile/pages/ChangeStatus/ChangeStatus.native.test.tsx
src/features/profile/pages/ChangeStatus/ChangeStatus.tsx
src/features/profile/pages/ChangeStatus/useSubmitChangeStatus.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30735
I have:
| iOS              | <img width="358" alt="image" src="https://github.com/user-attachments/assets/7f7a77d7-4523-4443-ae57-7eca48397d24"> | ![Simulator Screenshot - iPhone 13 - 2024-07-18 at 09 33 06](https://github.com/user-attachments/assets/536121a0-14ed-476f-bc4a-a4b5a2684225) |
| Desktop - Chrome |               | <img width="1440" alt="image" src="https://github.com/user-attachments/assets/2de8ef60-bab3-414b-864f-6f5 …

(PC-30735) feat(Profile): ChangeStatus screen

---

src/features/offer/components/OfferTile/OfferTile.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30837
La gestion du tracking avait déjà été faite ici : https://github.com/pass-culture/pass-culture-app-native/pull/6680
J'ai juste rajouté un test

(PC-30837) feat(tracking): add tracking test for searchN1

---

src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30974
I have:
https://github.com/user-attachments/assets/7e5623f6-0245-425e-83a2-cea94f51fbbd

(PC-30974) feat(Reaction): improve wording and button state

---

__snapshots__/features/identityCheck/pages/profile/SetStatus.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ChangeStatus/ChangeStatus.native.test.tsx.native-snap
src/features/identityCheck/pages/profile/StatusFlatList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30735
I have:
| Desktop - Chrome | <img width="1440" alt="image" src="https://github.com/user-attachments/assets/509484bf-c608-4eff-b234-1c1ff8e30160">  | <img width="1440" alt="image" src="https://github.com/user-attachments/assets/8b5fb2a8-1b03-4708-b7b0-aa39209e1ed5"> | 
[2]: …

(PC-30735) fix(StatusFlatList): for web add spacing before page title

---

src/api/gen/api.ts
src/features/home/pages/Home.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30934
I have:

(PC-30934) feat(Attrakdiff): add custom attributes batch

---

.github/workflows/dev_on_push_workflow_main.yml
.github/workflows/dev_on_worklow_run_e2e_android.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30998
The workflow has been tested on push on a specific branch.

(PC-30998) feat(CI): add e2e tests into ci

---

__mocks__/libs/react-native-batch.ts
src/features/home/api/useAttrakdiffModal.native.test.ts
src/features/home/api/useAttrakdiffModal.ts
src/features/home/pages/Home.tsx
src/libs/react-native-batch/index.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30934
I have:

(PC-30394) fix(Attrakdiff): Update user before send event

---

.storybook/preview.js
eslint-custom-rules/no-raw-text.js
eslint-custom-rules/no-raw-text.test.js
scripts/dead_code_snapshot.txt
src/theme/index.ts
src/ui/theme/designSystemTypographie.stories.tsx
src/ui/theme/designSystemTypographie.tsx
src/ui/theme/index.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30940
I have:

(PC-30940) feat(typo): implement typo from design system

---

__snapshots__/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx.native-snap
eslint-custom-rules/no-raw-text.js
eslint-custom-rules/no-raw-text.test.js
src/features/internal/cheatcodes/pages/AppComponents/AppComponents.tsx
src/features/profile/components/CreditInfo/CreditInfo.tsx
src/theme/index.ts
src/ui/theme/typography.stories.tsx
src/ui/theme/typography.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30995
I have:

(PC-30995) feat(Typo): replace and remove Hero typo

---

src/features/bookings/pages/EndedBookings/EndedBookings.tsx
src/features/reactions/api/useReactionMutation.ts
src/libs/queryKeys.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31027
I have:
https://github.com/user-attachments/assets/30c60ba2-3018-4775-81ee-0173b6071ad6

(PC-31027) fix(EndedBookings): fix the query mutation

---

__snapshots__/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx.native-snap
src/features/offer/components/MoviesScreeningCalendar/NextScreeningButton.tsx
src/features/offer/components/MoviesScreeningCalendar/moviesOffer.builder.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30632
I have:
| Platform         | hasDismissedModal | hasSeenAllVideos |
| Chrome              |<video src="https://github.com/user-attachments/assets/a75e24dc-8bf3-41b5-abcb-5ecd7857ce9f"/>|<video src="https://github.com/user-attachments/assets/23bd9c21-336d-486d-bd1d-78892f9d9caa"/>|

(PC-30632) feat(Venue): Make the next screening button entirely pressable

---

src/features/venueMap/components/VenueMapView/VenueMapView.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30945
Fix sur la carte quand on changeait de localisation, ce qui provoquait un zoom arrière non désiré.
I have:
https://github.com/user-attachments/assets/c3122e6b-8608-41c1-ba3a-5ebffafab773

(PC-30945) fix(venueMap): zoom out on mount

---

src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31029
I have:
https://github.com/user-attachments/assets/1a958ff1-c9a2-4599-97a5-f095fe5ad976

(PC-31029) fix(ReactionChoiceModal): fix the wording

---

__mocks__/react-native-youtube-iframe.ts
src/features/home/components/modules/video/VerticalVideoPlayer.native.test.tsx
src/features/home/components/modules/video/VerticalVideoPlayer.tsx
src/features/home/components/modules/video/VideoCarouselModule.native.test.tsx
src/features/home/components/modules/video/types.ts
src/features/home/components/modules/video/useVerticalVideoPlayer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30864
Optimisation de la progress bar sur le player video de la home.
I have:
https://github.com/user-attachments/assets/3ebde9d4-f579-423c-83f8-ddc0e6062ed1

(PC-30864) fix(videoPlayer): progress bar

---

src/features/venueMap/components/VenueMapBottomSheet/VenueMapBottomSheet.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30949
- Fix sur la bottom sheet pour les petits écrans
- Ajout d'un feature flag pour la list des offres dans la bottomSheet (wipOffersInBottomSheet)
I have:
https://github.com/user-attachments/assets/f71588e7-3566-4a49-8abf-eeda9fd4b80a

(PC-30949) chore(venuMap): add FF for offers in bottom sheet

---

src/features/home/components/modules/video/VerticalVideoPlayer.tsx

I have:
| iOS              |<video src="https://github.com/user-attachments/assets/c1daba4f-bf56-416d-94d3-8286795e9c18"/>|<video src="https://github.com/user-attachments/assets/14898e75-5cfc-4816-9dca-39dd86fff253"/>|

(BSR) fix(videoProgressBar): add missing background for video progressBar

---

src/features/cookies/helpers/setMarketingParams.native.test.ts
src/features/navigation/RootNavigator/linking/getStateFromPath.ts
src/libs/firebase/analytics/useInit.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30766
I have:

(PC-30766) refactor(firebase): utm issues investigation

---

__snapshots__/features/identityCheck/pages/profile/SetCity.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap
__snapshots__/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx.web-snap
src/api/gen/api.ts
src/features/home/components/SubscribeButtonWithModals.native.test.tsx
src/features/identityCheck/pages/profile/SetCity.native.test.tsx
src/features/identityCheck/pages/profile/SetCity.tsx
src/features/internal/cheatcodes/pages/NavigationProfile/NavigationProfile.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/features/profile/api/useUpdateProfileMutation.ts
src/features/profile/components/CitySearchInput/CitySearchInput.native.test.tsx
src/features/profile/components/CitySearchInput/CitySearchInput.tsx
src/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx
src/features/profile/pages/ChangeCity/ChangeCity.tsx
src/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx
src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
src/features/subscription/helpers/useThematicSubscription.native.test.tsx
src/features/subscription/page/OnboardingSubscription.native.test.tsx
src/features/venue/components/VenueThematicSection/VenueThematicSection.native.test.tsx
src/libs/place/fixtures/mockedSuggestedCities.ts
src/libs/place/useCities.ts
src/tests/mockServer.ts
src/tests/mswServer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30736
I have:
| iOS              |    <img width="376" alt="image" src="https://github.com/user-attachments/assets/105b6f43-b565-40dd-b83a-2a048b032453">          |   <img width="352" alt="image" src="https://github.com/user-attachments/assets/48c4cf9d-5445-4272-ad41-d729921cfb15">  <img width="347" alt="image" src="https://github.com/user-attachments/assets/d348c9c6-b005-4f1f-a173-b6d9a312abd1">  | …

(PC-30736) feat(ChangeCity): add postal code edition page

---

src/features/profile/pages/NotificationSettings/NotificationsSettings.native.test.tsx
src/features/profile/pages/NotificationSettings/NotificationsSettings.tsx
src/features/subscription/helpers/useThematicSubscription.native.test.tsx
src/features/subscription/helpers/useThematicSubscription.tsx
src/features/subscription/page/OnboardingSubscription.native.test.tsx
src/features/subscription/page/OnboardingSubscription.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30475
I have:

(PC-30475) feat(Subscription): add origin when the user subscribes (to log in backend)

---

.envrc
scripts/load_certificate.sh

(PC-30753) chore(dependencies): automatically install pods

---

__snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap
src/api/gen/api.ts
src/features/identityCheck/pages/profile/SetStatus.native.test.tsx
src/features/identityCheck/pages/profile/SetStatus.tsx
src/features/identityCheck/pages/profile/StatusFlatList.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/profile/pages/ChangeStatus/ChangeStatus.tsx
src/features/profile/pages/ChangeStatus/ChangeStatus.web.test.tsx
src/features/profile/pages/ChangeStatus/useSubmitChangeStatus.tsx
src/features/profile/pages/PersonalData/PersonalData.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30734
I have:
| iOS              |          <img width="408" alt="image" src="https://github.com/user-attachments/assets/ce6edbf2-fa4c-4439-9c8f-09c91b7031d4">     |  ![image](https://github.com/user-attachments/assets/cb647cde-eb9a-409a-a4fd-dd8d9d4ee548) |
[2]: …

(PC-30734) feat(ProfileData): add personnal datas in profile

---

src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31177
I have:
https://github.com/user-attachments/assets/681dbc89-97b1-403a-888e-e515b851d0f6

(PC-31177) fix(ReactionChoiceModal): wroding block on "Confirmer"

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30645

(PC-30645) feat(targetXPOfferCine): add FF

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/search/api/useSearchResults/useSearchResults.ts
src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx
src/features/search/pages/SearchResults/SearchResults.native.test.tsx
src/features/search/pages/SearchResults/SearchResults.web.test.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.tsx
src/features/venueMap/hook/useGetVenuesInRegion.ts
src/features/venueMap/hook/useVenuesMapData.native.test.ts
src/features/venueMap/hook/useVenuesMapData.ts
src/features/venueMap/pages/VenueMap/VenueMap.tsx
src/libs/algolia/fetchAlgolia/fetchVenues/fixtures/venuesFixture.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30794
I have:
https://github.com/user-attachments/assets/107aea3c-8914-4188-9df7-eee762fefef7

(PC-30794) feat(VenueMapView): refacto and adapt to use search venues from offer when we have no venues in search

---

src/features/artist/components/ArtistBody/ArtistBody.native.test.tsx
src/features/artist/components/ArtistBody/ArtistBody.tsx
src/features/artist/components/ArtistPlaylist/ArtistPlaylist.native.test.tsx
src/features/artist/components/ArtistPlaylist/ArtistPlaylist.tsx
src/features/artist/pages/Artist.tsx
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferPlaylistItem/OfferPlaylistItem.tsx
src/features/offer/components/OfferPlaylistList/OfferPlaylistList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30970
I have:
| iOS              |               |![Capture d’écran 2024-08-06 à 10 59 12](https://github.com/user-attachments/assets/e168064d-61f6-4fde-b500-a6b8d7bae4f3)|
| Desktop - Chrome |               |![Capture d’écran 2024-08-06 à 10 48 18](https://github.com/user-attachments/assets/d8e9c2ae-7679-42d7-afe2-b3fa26323f8e)| …

(PC-30970) feat(ArtistPlaylist): create Artist playlist

---

src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/features/offer/components/OfferContent/OfferContent.tsx
src/features/offer/components/OfferContent/OfferContent.web.test.tsx
src/features/offer/components/OfferContent/OfferContent.web.tsx
src/features/offer/components/OfferContent/OfferContentBase.tsx
src/features/offer/components/OfferImageCarousel.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.tsx
src/features/offer/components/OfferImageRenderer.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31069
I have:

(PC-31069) refactor(offer): remove wipOfferPreview feature flag use

---

src/features/artist/components/ArtistBody/ArtistBody.native.test.tsx
src/features/artist/components/ArtistBody/ArtistBody.tsx
src/features/artist/components/ArtistWebMetaHeader.tsx
src/features/artist/pages/Artist.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30968
I have:
| iOS              |![Capture d’écran 2024-08-06 à 14 17 45](https://github.com/user-attachments/assets/4045f78b-e21e-4dff-b88c-bfefa57fc1a1)|![Capture d’écran 2024-08-06 à 12 48 37](https://github.com/user-attachments/assets/90cb9620-7600-42db-8f48-0fadf39ca058) ![Capture d’écran 2024-08-06 à 12 48 49](https://github.com/user-attachments/assets/4047edc8-3d8d-4784-91e5-259ccdae611a)|
| Android          |               |![Capture d’écran 2024-08-06 à 12 48 …

(PC-30968) feat(artist): add header and title on artist page

---

src/features/bookOffer/components/BookingOfferModalFooter.native.test.tsx
src/features/bookOffer/components/BookingOfferModalFooter.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30922
I have:

(PC-30922) feat(OfferModal): add tracker HasChosenTime

---

__snapshots__/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx.native-snap
src/features/internal/cheatcodes/pages/AppComponents/illustrationsExports.ts
src/features/internal/cheatcodes/pages/NavigationAccountSuspension/NavigationAccountSuspension.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.web.test.tsx
src/features/profile/pages/PersonalData/PersonalData.native.test.tsx
src/features/profile/pages/PersonalData/PersonalData.tsx
src/features/subscription/helpers/useOnViewableItemsChanged.ts
src/ui/components/headers/PageHeaderWithoutPlaceholder.tsx
src/ui/svg/icons/BicolorSadFace.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31094
I have:
| iOS              | <img width="220" alt="image" src="https://github.com/user-attachments/assets/f0cfad63-ae14-4e36-985a-9f21372daddd"> | <img width="391" alt="image" src="https://github.com/user-attachments/assets/3e9ff330-1b9c-4f48-8480-03ca928c9832"> |
| Desktop - Chrome |               | <img width="1440" alt="image" src="https://github.com/user-attachments/assets/78a6456d-5fcf-4010-81db-b86c3e487f65"> |
[1]: …

(PC-31094) feat(DeleteProfileReason): Added new screen for mobile and web

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/offer/components/OfferBody/OfferBody.tsx
src/features/offer/components/OfferPlace/OfferPlace.tsx
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31064
I have:

(PC-31064) refactor(Offer): Remove wipEnableNewXpCineFromOffer feature flag

---

src/features/offer/components/OfferImageContainer/OfferImageContainer.native.test.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.web.test.tsx
src/features/offer/pages/OfferPreview/OfferPreview.native.test.tsx
src/features/offer/pages/OfferPreview/OfferPreview.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31070
I have:

(PC-31070) refactor(offer): remove wipOfferPreviewWithCarousel feature flag use

---

ios/Podfile.lock
package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31113
I have:

(PC-31113) chore(deps): bump react-native-screens

---

src/ui/components/headers/ContentHeader.stories.tsx

(BSR) fix(chromatic): Fix chromatic CI fail

---

sonar-project.properties

(BSR) feat(Sonar): ignore logEventAnalytics in sonar-project.propreties

---

__snapshots__/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.native.test.tsx.native-snap
src/api/gen/api.ts
src/features/bookOffer/fixtures/offer.ts
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/features/offer/components/OfferReactions/OfferReactions.native.test.tsx
src/features/offer/components/OfferReactions/OfferReactions.tsx
src/features/offer/components/OfferTile/OfferTile.native.test.tsx
src/features/offer/fixtures/offerResponse.ts
src/features/offer/fixtures/offersStocksResponse.ts
src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx
src/shared/offer/usePrePopulateOffer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29412
I have:
| iOS              |               |![Capture d’écran 2024-08-08 à 18 33 17](https://github.com/user-attachments/assets/797a0aca-4995-4b4e-8852-9f38aad4ad9d)![Capture d’écran 2024-08-08 à 18 33 32](https://github.com/user-attachments/assets/e5cb994b-a2ae-43f6-a60f-d79a08fb342f)|
| Desktop - Chrome |               |![Capture d’écran 2024-08-08 à 18 29 45](https://github.com/user-attachments/assets/dac5ab9e-6547-48a2- …

(PC-29412) feat(OfferReactions): add users reactions into the offer

---

src/features/bookings/fixtures/bookingsSnap.ts
src/features/home/pages/Home.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.web.test.tsx
src/features/subscription/helpers/shareAppTriggers/firstSessionAfterBookingTrigger.native.test.ts
src/features/subscription/helpers/shareAppTriggers/firstSessionAfterBookingTrigger.ts
src/features/subscription/helpers/shareAppTriggers/twoWeeksAfterCreditTrigger.native.test.ts
src/features/subscription/helpers/shareAppTriggers/twoWeeksAfterCreditTrigger.ts
src/features/subscription/helpers/useShareAppModalStore.ts
src/features/subscription/helpers/useShareAppModaleTrigger.native.test.ts
src/features/subscription/helpers/useShareAppModaleTrigger.ts
src/libs/firebase/remoteConfig/remoteConfig.constants.ts
src/libs/firebase/remoteConfig/remoteConfig.services.ts
src/libs/firebase/remoteConfig/remoteConfig.services.web.ts
src/libs/firebase/remoteConfig/remoteConfig.types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30517
I have:

(PC-30517) feat(ShareAppModale): A/B test share app trigger

---

src/features/offer/api/useSimilarOffers.native.test.ts
src/features/offer/api/useSimilarOffers.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.native.test.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31160
I have:

(PC-31160) feat(offer): refine api reco error

---

src/features/offer/helpers/formatDuration/formatDuration.test.ts
src/features/offer/helpers/formatDuration/formatDuration.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30943
I have:
| Desktop - Chrome | <img width="977" alt="Capture d’écran 2024-08-12 à 12 06 44" src="https://github.com/user-attachments/assets/4a373d82-8ac7-479a-8d49-1f4082546fe4"> | <img width="1022" alt="Capture d’écran 2024-08-12 à 12 07 20" src="https://github.com/user-attachments/assets/d58a1be4-59a9-4504-89b0-e17ed0bedb33"> |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v= …

(PC-30943) fix(Offer): Fix duration format on offer

---

__snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap
src/features/profile/api/useUpdateProfileMutation.ts
src/features/profile/pages/ChangeCity/ChangeCity.native.test.tsx
src/features/profile/pages/ChangeCity/ChangeCity.tsx
src/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx
src/features/profile/pages/ChangeStatus/ChangeStatus.native.test.tsx
src/features/profile/pages/ChangeStatus/ChangeStatus.web.test.tsx
src/features/profile/pages/ChangeStatus/useSubmitChangeStatus.tsx
src/features/profile/pages/PersonalData/PersonalData.tsx
src/fixtures/user.ts
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30955
I have:

(PC-30955) feat(ProfileData): add tracker on profile change fields

---

__snapshots__/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx.native-snap
src/features/navigation/RootNavigator/types.ts
src/features/profile/components/Modals/DeleteProfileReasonNewEmailModal.native.test.tsx
src/features/profile/components/Modals/DeleteProfileReasonNewEmailModal.tsx
src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx
src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31098
I have:
| iOS              |   ![Capture d’écran 2024-08-12 à 15 35 57](https://github.com/user-attachments/assets/4125ebf7-2cd7-4157-925d-58e14b80345d)   |  ![Capture d’écran 2024-08-12 à 15 40 09](https://github.com/user-attachments/assets/1ae83233-676d-40c8-80a2-458d544174d3) |
| Android          |               |  ![Capture d’écran 2024-08-12 à 15 34 57](https://github.com/user-attachments/assets/98cf9593-67f2-442f-918b-b2f9a702d6eb)  | …

(PC-31098) feat(profile): Add delete profile reason modal for new email redirection

---

src/features/home/types.ts
src/libs/contentful/adapters/modules/adaptOffersModule.native.test.ts
src/libs/contentful/fixtures/algoliaModules.fixture.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-28834
I have:
| Environment         | after |
| TESTING | <img width="1414" alt="Capture d’écran 2024-08-12 à 15 20 56" src="https://github.com/user-attachments/assets/d45e0d6f-e7ba-48c3-9275-22c28d98fd71"> |
| TESTING | <video src="https://github.com/user-attachments/assets/84e03598-64d9-4f8c-acc6-31a0df0c0b75" />  |

(PC-28834) feat(Algolia): Add checkbox as additional parameter to Algolia playlist content model

---

__snapshots__/features/home/components/modules/OffersModule.native.test.tsx.native-snap
__snapshots__/features/offer/components/OfferTile/PlaylistCardOffer.native.test.tsx.native-snap
src/features/home/components/modules/RecommendationModule.native.test.tsx
src/features/home/components/modules/RecommendationModule.tsx
src/features/offer/components/OfferTile/PlaylistCardOffer.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30865
If I had to re-run tests in the CI due to flakiness, I add the incident on Notion
I have:

(PC-30865) feat(home): Fix RecommandationModule playlist with new design

---

.github/workflows/dev_on_workflow_run_e2e_android.yml
.maestro/testsV2/AccessSignupFromBlock.yml
.maestro/testsV2/FirstLaunch.yml
.maestro/testsV2/InfoSectionNotShown.yml
.maestro/testsV2/LoginAndSSO.yml
.maestro/testsV2/ProfileSectionCheckAndReactivation.yml
.maestro/testsV2/SearchAndBookOffers.yml
.maestro/testsV2/SignupAndActivation.yml
.maestro/testsV2/UserNotConnectedMode.yml
.maestro/testsV2/VenueAndBookingSectionCheck.yml
.maestro/testsV2/subFolder/auth/LoginFromPhysicalOffer.yml
.maestro/testsV2/subFolder/booking/BookCinemaOffer.yml
.maestro/testsV2/subFolder/booking/BookDuoOffer.yml
.maestro/testsV2/subFolder/cloud/commands/DoubleTapOnBack.yml
.maestro/testsV2/subFolder/cloud/commands/TapOnBack.yml
.maestro/testsV2/subFolder/profil/AccessibilitySection.yml
.maestro/testsV2/subFolder/profil/HelpCenter.yml
.maestro/testsV2/subFolder/profil/LegalInfoSection.yml
.maestro/testsV2/subFolder/profil/SocialNetwork.yml
.maestro/testsV2/subFolder/tutorial/onboarding/Onboard16AndLocalization.yml
.maestro/testsV2/subFolder/venue/VerifyVenueInfo.yml
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31104
I have:

(PC-31104) fix(e2e): update script and tags exec

---

src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx
src/features/profile/pages/ChangeEmail/ChangeEmail.tsx
src/features/profile/pages/ChangeEmail/ChangeEmail.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31098
I have:

(PC-31098) feat(profile): Fix redirection for ChangeEmail

---

src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31039
I have:

(PC-31039) feat(offer): trigger ConsultArtist log when pressing artist button and wipArtistPage FF activated

---

devbox.lock
flake.lock
package.json

(BSR) chore(deps): update tools

---

src/features/offer/components/OfferCTAButton/OfferCTAButton.native.test.tsx
src/features/offer/components/OfferPreviewModal/OfferPreviewModal.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31303
I have:

(PC-31303) test(offer): fix flaky tests

---

__snapshots__/features/profile/pages/DeleteProfile/DeleteProfileContactSupport.native.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx.native-snap
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/features/profile/pages/DeleteProfile/DeleteProfileContactSupport.native.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileContactSupport.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileContactSupport.web.test.tsx
src/features/profile/pages/DeleteProfile/EmailProvider.native.test.ts
src/features/profile/pages/DeleteProfile/EmailProvider.ts
src/features/profile/pages/DeleteProfile/WebEmailProvider.web.ts
src/features/profile/pages/DeleteProfile/useContactSupportForDeletionProfile.native.test.ts
src/features/profile/pages/DeleteProfile/useContactSupportForDeletionProfile.ts
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31096
I have:
| iOS              |        <img width="376" alt="image" src="https://github.com/user-attachments/assets/cef1b2b8-f263-48da-aa63-e5e192c7859c">     |    ![image](https://github.com/user-attachments/assets/badb22b4-3b87-46ec-ae64-0a350894fbe9)   |
| Desktop - Chrome |               |   <img width="1512" alt="image" src="https://github.com/user-attachments/assets/344231dc-450c-4449-bb07-bf6ed071a709">    |
[1]: …

(PC-31096) feat(DeleteProfileContactSupport): account deletion support

---

__snapshots__/features/profile/pages/DeleteProfile/DeleteProfileAccountHacked.native.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfile/DeleteProfileEmailHacked.native.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx.native-snap
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/features/profile/pages/DeleteProfile/DeleteProfileAccountHacked.native.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileAccountHacked.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileAccountHacked.web.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileEmailHacked.native.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileEmailHacked.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileEmailHacked.web.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileSecureAccount.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31213
I have:
| iOS              |     ![image](https://github.com/user-attachments/assets/0eb902a0-7868-416b-882f-1e51aed2da1c)    |    ![image](https://github.com/user-attachments/assets/9dcd862e-f988-47e9-9769-6dfc886105f2)   |
| Desktop - Chrome |               |    <img width="1512" alt="image" src="https://github.com/user-attachments/assets/077efc22-f916-4385-8f65-c0498aafcfa7">   |
[1]: …

(PC-31213) feat(SecureAccount): account deletion secure account

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31380
I have:

(PC-31380) fix(search): transform AlgoliaVenue to Venue before use it in the map when search results has venues playlist

---

__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
__snapshots__/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx.web-snap
__snapshots__/features/errors/pages/AsyncErrorBoundary.web.test.tsx.web-snap
__snapshots__/features/identityCheck/components/layout/PageWithHeader.web.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/identification/educonnect/EduConnectForm.web.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/identification/educonnect/EduConnectValidation.web.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/identification/ubble/SelectPhoneStatus.web.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/profile/SetAddress.web.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/profile/SetCity.web.test.tsx.web-snap
__snapshots__/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx.web-snap
__snapshots__/features/navigation/RootNavigator/Header/Header.web.test.tsx.web-snap
__snapshots__/features/profile/pages/ChangeCity/ChangeCity.web.test.tsx.web-snap
__snapshots__/features/profile/pages/NotificationSettings/NotificationsSettings.web.test.tsx.web-snap
__snapshots__/features/profile/pages/Profile.web.test.tsx.web-snap
__snapshots__/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx.web-snap
__snapshots__/features/share/pages/WebShareModal.web.test.tsx.web-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
__snapshots__/ui/components/buttons/AppButton/AppButton.web.test.tsx.web-snap
__snapshots__/web/SupportedBrowsersGate.web.test.tsx.web-snap
package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31389
(https://github.com/jestjs/jest/releases?page=2)](https://github.com/jestjs/jest/releases/tag/v29.6.3)

(PC-31389) chore(jest): bump

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31396
I have:

(PC-31396) chore(bump): yarn upgrade babel-jest@29.6.3

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31416

(PC-31416) chore(bumps): pre React-native

---

src/libs/store/createStore.ts

(BSR) chore(Warning): Remove zustand warning

---

src/features/artist/components/ArtistPlaylist/ArtistPlaylist.tsx
src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.test.ts
src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.ts
src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.test.ts
src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.ts
src/features/offer/helpers/useSameArtistPlaylist/useSameArtistPlaylist.native.test.ts
src/features/offer/helpers/useSameArtistPlaylist/useSameArtistPlaylist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31382
I have:
From Harry Potter Tome 3 : Harry Potter et le prisonnier d'Azkaban
| iOS              |![Capture d’écran 2024-08-26 à 11 20 26](https://github.com/user-attachments/assets/daa13755-7587-435a-945f-34c27423327c)|    ![Capture d’écran 2024-08-26 à 11 19 44](https://github.com/user-attachments/assets/71fde3ac-8603-4708-8285-d51dadc7f4de)|
| Android          |![Capture d’écran 2024-08-26 à 11 20 35](https://github.com/user-attachments/assets/99aff5fb-9235-49bc-9ffc-762ee3128aad)|![Capture d’écran 2024-08-26 …

(PC-31382) feat(artist): remove condition from ean in artist playlist to see the offer from which the artist was consulted

---

src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.test.ts
src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31384
I have:

(PC-31384) feat(artist): limit of 100 items rather than 30 for playlist

---

__snapshots__/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.native.test.tsx.native-snap
src/features/auth/pages/suspendedAccount/SuspendedAccountUponUserRequest/SuspendedAccountUponUserRequest.tsx
src/features/internal/cheatcodes/pages/AppComponents/illustrationsExports.ts
src/features/internal/cheatcodes/pages/NavigationAccountSuspension/NavigationAccountSuspension.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.native.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.web.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileSuccess.tsx
src/ui/svg/icons/BicolorProfileDeletion.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31350
I have:
| iOS              |   <img width="378" alt="Capture d’écran 2024-08-27 à 12 36 44" src="https://github.com/user-attachments/assets/f3c7126b-cb0c-4fc0-beef-44d6d568d63c">   |   <img width="376" alt="Capture d’écran 2024-08-26 à 23 08 37" src="https://github.com/user-attachments/assets/0d233fe7-f34c-4a67-bc06-deee98d0d8ac">  |
| Desktop - Chrome |               |   <img width="1728" alt="Capture d’écran 2024-08-26 à …

(PC-31350) feat(profile): add DeleteProfileConfirmation screen  @Lucasbeneston

---

src/features/venueMap/pages/modals/VenueTypeModal/VenueTypeModal.native.test.tsx
src/features/venueMap/pages/modals/VenueTypeModal/VenueTypeModal.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31364
I have:

(PC-31364) feat(venueMap): trigger ApplyVenueMapFilter log when applying venue type filter

---

src/features/offer/api/useSimilarOffers.native.test.ts
src/features/offer/api/useSimilarOffers.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.native.test.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31279
I have:

(PC-31279) feat(recommendation): no log in Sentry of 5xx errors

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
src/features/venue/components/PracticalInformation/PracticalInformation.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31496
I have:
| Android          |<video src="https://github.com/user-attachments/assets/3b48a882-3431-42e8-97a3-77481e518df1"/>|<video src="https://github.com/user-attachments/assets/f5a8990d-b14c-42cd-8f50-9367eb5c1a50"/>|

(PC-31496) fix(venue): remove nested flatlist in scrollview to avoid scroll issue with android

---

src/libs/algolia/fetchAlgolia/fetchMultipleOffers/fetchMultipleOffers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31549
I have:

(PC-31549) feat(algolia): add index prop to fetchMultipleOffers

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/bookOffer/components/BookHourChoice.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31575
I have:

(PC-31575) fix(bookHour): add initial value to reduce call

---

src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
src/features/offer/components/MoviesScreeningCalendar/moviesOffer.builder.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31545
I have:
| iOS              |![simulator_screenshot_BD995B0C-42E3-4BF8-949A-C89A10F861F9](https://github.com/user-attachments/assets/9747476d-a40e-4c4b-8c58-efbe9a75099c)|![Simulator Screenshot - iPhone 15 - 2024-08-30 at 11 58 47](https://github.com/user-attachments/assets/cab7a0e3-f28e-43af-aa00-880279553e0f)|
| Desktop - Chrome |<img width="1512" alt="Capture d’écran 2024-08-30 à 12 01 41" src="https://github.com/user-attachments/assets/1e8bbe03-fd3f-4543-b428-1a75bbd00cee">|<img width="1512" alt="Capture …

(PC-31545) feat(moviePlaces): add dedicated playlist for non screening offers

---

src/features/offer/components/OfferReactions/OfferReactions.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31551
I have:

(PC-31551) fix(offer): improve condition

---

src/features/offer/api/useSimilarOffers.native.test.ts
src/features/offer/api/useSimilarOffers.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.native.test.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31586
I have:

(PC-31586) fix(sentry): handle <unknow> error from sentry

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/offer/enums.ts
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/venueMap/components/VenueMapBottomSheet/VenueMapBottomSheet.tsx
src/features/venueMap/components/VenueMapBottomSheet/VenueMapOfferPlaylist.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.tsx
src/features/venueMap/pages/VenueMap/VenueMap.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31504
I have:

(PC-31504) feat(venueMap): add playlist type to trigger ConsultOffer log on bottom sheet

---

src/features/cookies/helpers/setMarketingParams.ts
src/features/navigation/RootNavigator/linking/getStateFromPath.ts
src/libs/firebase/analytics/useInit.native.test.ts
src/libs/firebase/analytics/useInit.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31289
I have:

(PC-31289) fix(useInit): marketing params

---

src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
src/features/culturalSurvey/pages/CulturalSurveyThanks.native.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyThanks.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31344
I have:

(PC-31344) feat(CulturalSurvey): Delete share app modal after QPI

---

devbox.json
devbox.lock
doc/installation/setup.md

(BSR) feat(app): update direnv nix conf and doc

---

src/features/artist/components/ArtistBody/ArtistBody.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31660
I have:
| iOS              |               |![Capture d’écran 2024-09-05 à 17 29 19](https://github.com/user-attachments/assets/901d2e74-1c6e-43dc-b163-a47ee9edbecc)|
| Desktop - Chrome |               |![Capture d’écran 2024-09-05 à 17 29 28](https://github.com/user-attachments/assets/9663ac08-51a0-4a1a-a7ff-8d3f1bab91e5)| …

(PC-31660) feat(Artist): center artist title name

---

src/features/bookings/components/EndedBookingItem.native.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx
src/features/profile/pages/Accessibility/AccessibilityActionPlan.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31696

(PC-31696) fix(tests): skipped most flaky tests

---

src/features/bookings/components/EndedBookingItem.native.test.tsx
src/features/bookings/components/EndedBookingItem.tsx
src/ui/svg/icons/Pastille.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31547
I have:

(PC-31547) feat(bookings): add small badge on reaction button when offer needs a reaction

---

src/features/home/components/modules/video/VideoPlayerWeb.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31696

(PC-31696) fix(test): skip force video player web

---

src/features/home/components/modules/TrendsModule.native.test.tsx
src/features/home/components/modules/TrendsModule.tsx
src/features/home/components/modules/VenueListModule.native.test.tsx
src/features/home/components/modules/VenueListModule.tsx
src/features/location/components/VenueMapLocationModal.native.test.tsx
src/features/location/components/VenueMapLocationModal.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.native.test.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/venueMap/components/VenueMapBlock/VenueMapBlock.native.test.tsx
src/features/venueMap/components/VenueMapBlock/VenueMapBlock.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31640
I have:

(PC-31640) fix(venueMap): reset selected venue each time you arrive on the map

---

src/features/artist/components/ArtistBody/ArtistBody.native.test.tsx
src/features/artist/components/ArtistBody/ArtistBody.tsx
src/features/artist/pages/Artist.native.test.tsx
src/features/artist/pages/Artist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31662
I have:
| iOS              |               |![Capture d’écran 2024-09-06 à 16 07 20](https://github.com/user-attachments/assets/1dd03447-7e82-4365-8d0e-b50109c9f99a)|
| Phone - Chrome   |               |![Capture d’écran 2024-09-06 à 16 07 37](https://github.com/user-attachments/assets/2628c44d-e3c1-47f9-bec4-8b2f554ff0b1)|
| Desktop - Chrome |               |![Capture d’écran 2024-09-06 à 16 07 50](https://github.com/user-attachments/assets/bbe7c50f-8e1a-4009-a0d5-9f …

(PC-31662) feat(Artist): add artist description

---

src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31657
I have:
| iOS              |![Capture d’écran 2024-09-09 à 12 22 35](https://github.com/user-attachments/assets/7378c38c-af79-4968-8e5f-6c2123e6de6b)|![Capture d’écran 2024-09-09 à 12 18 03](https://github.com/user-attachments/assets/ac1a2f78-6f02-4447-8adb-f4d77f562581)|
| Android          |![Capture d’écran 2024-09-09 à 12 22 48](https://github.com/user-attachments/assets/396da595-84ae-4ae9-bd7d-bb03cecab54a)|![Capture d’écran 2024-09-09 à 12 18 56](https://github.com/user-attachments/assets/c1a5618d-f348-45 …

(PC-31657) feat(offer): no redirection on the artist page when the artist contains a comma or semicolon

---

src/features/artist/pages/Artist.tsx
src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.ts
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/features/offer/helpers/constants.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31652
I have:
| iOS              |![Capture d’écran 2024-09-09 à 14 54 46](https://github.com/user-attachments/assets/2f094e45-a3ae-4cf8-a2dd-432a9ad8697e)|![Capture d’écran 2024-09-09 à 14 54 25](https://github.com/user-attachments/assets/e6799b32-d128-4875-b2d4-dace6ab3331f)|
| Phone - Chrome   |![Capture d’écran 2024-09-09 à 14 55 17](https://github.com/user-attachments/assets/87b0c53b-5fe0-47e3-80fb-92c68be205b2)|![Capture d’écran 2024-09-09 à 14 53 …

(PC-31652) feat(Offer): don't allow user to click when artist is collectif

---

scripts/dead_code_snapshot.txt
src/features/artist/components/ArtistBody/ArtistBody.tsx
src/features/artist/components/ArtistHeader/ArtistHeader.tsx
src/features/artist/components/ArtistHeader/ArtistHeaderWrapper.tsx
src/features/artist/components/ArtistHeader/ArtistHeaderWrapper.web.tsx
src/ui/components/Avatar/Avatar.stories.tsx
src/ui/components/Avatar/Avatar.tsx
src/ui/theme/constants.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31659
I have:

(PC-31659) feat(artist): artist avatar

---

src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx

Fix the tests not passing introduced by https://github.com/pass-culture/pass-culture-app-native/pull/6845

(BSR) fix(Anchor): fix venue tests

---

src/features/search/components/BookCategoriesSection/BookCategoriesSection.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31743
| Desktop - Chrome |<img width="489" alt="Capture d’écran 2024-09-10 à 15 50 37" src="https://github.com/user-attachments/assets/598d1780-a2d5-4710-879a-7ad5dccc4a9e">|<img width="496" alt="Capture d’écran 2024-09-10 à 15 50 00" src="https://github.com/user-attachments/assets/5e87c171-3e85-4e9c-9935-65ee5e40395c">|

(PC-31543) feat(SearchBooks): remove 'Livres papier' from categories

---

src/features/artist/components/ArtistPlaylist/ArtistPlaylist.tsx
src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.test.ts
src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.ts
src/features/offer/components/OfferBody/OfferBody.tsx
src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.test.ts
src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.ts
src/features/offer/helpers/useSameArtistPlaylist/useSameArtistPlaylist.native.test.ts
src/features/offer/helpers/useSameArtistPlaylist/useSameArtistPlaylist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31677
I have:
Avant : 
Après : 
https://github.com/user-attachments/assets/35c12196-9357-4515-9355-7db9a2993ecb

(PC-31677) fix(ArtistPlaylist): correct Artist playlist limitation compared to the venue of the offer

---

src/features/offer/components/MoviesScreeningCalendar/MovieOfferTile.tsx
src/ui/components/eventCard/EventCard.native.test.tsx
src/ui/components/eventCard/EventCard.tsx
src/ui/components/eventCard/EventCardList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31608
I have:

(PC-31608) feat(tracking): Ajout du log consult offer au clique sur une eventCard

---

src/features/artist/components/ArtistPlaylist/ArtistPlaylist.tsx
src/features/offer/api/fetchOffersByArtist/fetchOffersByArtist.ts
src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/helpers/constants.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31769
I have:

(PC-31769) feat(Artist): extend artist page to CD_VINYLE_MUSIQUE_EN_LIGNE

---

__snapshots__/features/profile/pages/DeleteProfile/DeleteProfileContactSupport.native.test.tsx.native-snap
src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx
src/features/internal/cheatcodes/pages/NavigationAccountSuspension/NavigationAccountSuspension.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileContactSupport.tsx

Link to JIRA https://passculture.atlassian.net/browse/PC-31349
I have:
| Desktop - Chrome |               |    <img width="1512" alt="image" src="https://github.com/user-attachments/assets/8fc6a8b6-fbde-4d03-9167-a8b365197f49">   | …

(PC-31349) chore(DeleteProfileContactSupport): Change typoDS to Typo

---

__snapshots__/features/search/pages/Search/SearchN1/SearchN1.native.test.tsx.native-snap
src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31667
| Phone - Chrome   |<img width="1029" alt="Capture d’écran 2024-09-11 à 10 35 41" src="https://github.com/user-attachments/assets/9d4825a7-b791-426a-879e-830c263a2300">|<img width="1007" alt="Capture d’écran 2024-09-11 à 18 12 27" src="https://github.com/user-attachments/assets/e7cc3b6d-2452-4d6a-a439-ece277b7fbd7">
>|

(PC-31667) feat(SearchN1): add missing categories to SearchN1 books

---

src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
src/features/venue/api/useVenueOffers.test.ts
src/features/venue/api/useVenueOffers.ts
src/features/venue/components/VenueContent/VenueContent.native.test.tsx
src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx
src/features/venue/helpers/useVenueSearchParameters.native.test.ts
src/features/venue/helpers/useVenueSearchParameters.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31599
I have:

(PC-31599) fix(Venue): display 50 offers instead of 20

---

.github/workflows/dev_on_workflow_web_deploy.yml

We will see if it fixes the deploy, no way to test locally!

(BSR) fix(vite): fix web deploy

---

__snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
src/features/search/components/CategoriesButtonsDisplay/CategoriesButtonsDisplay.stories.tsx
src/features/search/components/CategoryButton/CategoryButtonV2.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30422
I have:
| Desktop - Chrome |<img width="985" alt="Capture d’écran 2024-09-12 à 12 00 40" src="https://github.com/user-attachments/assets/42838a73-3598-4e1f-8c56-995f1f8fc1e1">|<img width="997" alt="Capture d’écran 2024-09-12 à 11 59 56" src="https://github.com/user-attachments/assets/9bd25de1-44ea-4a93-abe5-fa26fcfce155">|

(PC-30422) feat(CategoryBlock): change category blocks text color to black

---

src/api/gen/api.ts
src/features/navigation/RootNavigator/routes.ts
src/features/profile/api/useAnonymizeAccount.ts
src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.native.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileConfirmation.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31539
I have:

(PC-31539) feat(DeleteProfileConfirmation): CTA anonymize account

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/features/search/api/useSearchResults/useSearchResults.ts
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx
src/features/search/helpers/useSearchAndPlaylistVenues/useSearchAndPlaylistVenues.native.test.ts
src/features/search/helpers/useSearchAndPlaylistVenues/useSearchAndPlaylistVenues.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31770
I have:
| iOS              |![Capture d’écran 2024-09-16 à 14 13 01](https://github.com/user-attachments/assets/8abe5bc2-49b9-4d09-96ac-846cf5c4769b) ![Capture d’écran 2024-09-16 à 14 14 21](https://github.com/user-attachments/assets/886aa9a4-0db7-450c-afde-993c4f955619)|![Capture d’écran 2024-09-16 à 14 18 00](https://github.com/user-attachments/assets/2d280909-d260-419b-868b-fb6247fdecaf)|
| Android          |![Capture d’écran 2024-09-16 à 14 12 43](https://github.com/user-attachments/assets/b2710265-6c50-4f …

(PC-31770) feat(search): merge venues playlist and search results offers venues and extract in a hook

---

.maestro/testsV2/config.yaml
.maestro/testsV2/subFolder/auth/LoginFromPhysicalOffer.yml
.maestro/testsV2/subFolder/cookies/SelectOneCookie.yml
.maestro/testsV2/subFolder/cookies/SelectThreeCookies.yml
.maestro/testsV2/subFolder/cookies/SelectTwoCookies.yml
.maestro/testsV2/subFolder/profil/DeletionReactivation.yml
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31847
I have:

(PC-31847) fix(e2e): update script v1.306.2

---

src/features/search/components/AutocompleteVenue/AutocompleteVenue.tsx
src/features/search/components/AutocompleteVenueItem/AutocompleteVenueItem.tsx
src/features/search/components/SearchSuggestions/SearchSuggestions.tsx
src/features/search/components/SearchVenueItems/SearchVenueItem.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31846
I have:

(PC-31846) fix(search): redirection since venues playlist and venues suggestions on Android

---

.env.integration
.env.production
.env.staging
.env.testing

feat(accessibility): change value for ACCESSIBILITY_LINK url

---

doc/development/alias.md

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31939
I have:

(PC-31939) docs(alias): add documentation for alias

---

__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/bookOffer/components/BookingDetails.native.test.tsx
src/features/bookOffer/components/BookingDetails.tsx
src/features/bookOffer/components/CguDetails.tsx
src/features/bookOffer/components/CguWithCheckbox.tsx
src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
src/ui/components/inputs/Checkbox/Checkbox.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31480
I have:
| Platform         | Desktop | IOS |
| Screenshot | <img width="598" alt="Capture d’écran 2024-09-19 à 13 37 59" src="https://github.com/user-attachments/assets/ad364a44-e18f-4ed0-86d3-c6e210fedcef"> | <img width="598" alt="Simulator Screenshot - iPhone 15 - 2024-09-19 at 13 28 43" src="https://github.com/user-attachments/assets/a8e0fe44-16a5-433b-8706-3f214836147f"> |

(PC-31480) feat(Booking): Add CGU to booking modal

---

scripts/mac_debug_env.sh

(BSR) chore(script): add script to debug mac

---

__snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap
src/features/internal/marketingAndCommunication/config/deeplinksExportConfig.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31920
I have:
❌ Made sure my feature is working on web.
✅ Made sure my feature is working on mobile (depending on relevance : real or virtual devices)
❌ Written **unit tests** native (and web when implementation is different) for my feature.
✅ Added a **screenshot** for UI tickets or deleted the screenshot section if no UI change
iOs
https://github.com/user-attachments/assets/5f98ac72-ec8b-4181-9d4b-d6736e7368a6
Android 
https://github.com/user-attachments/assets/dea39c43-e763-497f-8214-31a08d22d6bd
[2]: …

(PC-31920) feat(venueMap): add deeplink

---

src/features/artist/components/ArtistBody/ArtistBody.tsx
src/features/artist/pages/Artist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31966
I have:

(PC-31966) fix(Artist): remove lorem ipsum bio

---

src/features/venue/components/VenueContent/VenueContent.native.test.tsx
src/features/venue/components/VenueContent/VenueContent.tsx
src/features/venue/components/VideoSection/FakeVideoPlayer.tsx
src/features/venue/constants.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31855
Ajout d'une modal de fakedoor au press sur la video dans la page Venue.
I have:
iOS
https://github.com/user-attachments/assets/17d8130a-2d57-457e-a566-9847fe902cb6
Android
https://github.com/user-attachments/assets/53cf8cf2-59a8-4ad4-b662-7637ca4a18ac

(PC-31855) feat(venue): add survey modal for video player

---

CODEOWNERS

https://sentry.passculture.team/settings/sentry/projects/application-native/ownership/

(BSR) feat(codeowners): update codeowners with artist feature

---

.envrc
doc/installation/setup.md
doc/installation/web.md
scripts/install_node_modules_when_not_installed.sh
scripts/start_android_emulator_with_certificate.sh

(BSR) docs(setup): downloading everything takes times

---

src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.native.test.tsx
src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.tsx
src/features/search/fixtures/autocompleteHits.ts
src/libs/algolia/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31768
I have:

(PC-31768) feat(SearchN1): sort Algolia results by count

---

server/yarn.lock

J'ai fait : `npx yarn-audit-fix`
I have:
| Command         | Before | After |
| yarn audit              |     <img width="382" alt="Capture d’écran 2024-09-26 à 14 13 47" src="https://github.com/user-attachments/assets/a1480299-f503-4453-b791-79cda46b929b"> | <img width="394" alt="Capture d’écran 2024-09-26 à 14 16 36" src="https://github.com/user-attachments/assets/57e61054-1ae9-47a9-a957-9ba65a4f6348">  |

(BSR) feat(dependabot): fix server vulnerabilities with npx yarn-audit-fix

---

.maestro/mock_analytics_server/yarn.lock

J'ai fait : `npx yarn-audit-fix`
I have:
| Comand         | Before | After |
| yarn audit              |   <img width="407" alt="Capture d’écran 2024-09-26 à 14 50 16" src="https://github.com/user-attachments/assets/635fc31b-8a9b-4f9d-9b51-d7c1316f0b9b">  |  <img width="414" alt="Capture d’écran 2024-09-26 à 14 50 38" src="https://github.com/user-attachments/assets/0825a14c-4a60-42ff-8ff2-b39481f87875">  |

(BSR) feat(dependabot): fix maestro vulnerabilities with npx yarn-audit-fix

---

doc/entretien/yarn.lock

J'ai fait : `npx yarn-audit-fix`
I have:
| Comand         | Before | After |
| yarn audit             |   <img width="399" alt="Capture d’écran 2024-09-26 à 14 26 09" src="https://github.com/user-attachments/assets/eb76bfff-e1df-451e-a20f-7ef347e497b2"> |  <img width="398" alt="Capture d’écran 2024-09-26 à 14 26 20" src="https://github.com/user-attachments/assets/dfc9c26b-4539-41e2-b495-3fadd60cd946"> |

(BSR) feat(dependabot): fix entretien vulnerabilities with npx yarn-audit-fix

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/venue/components/VenueContent/VenueContent.tsx
src/features/venue/constants.ts
src/features/venue/pages/Venue/Venue.native.test.tsx
src/features/venue/pages/Venue/Venue.tsx
src/libs/storage.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32026
I have:
https://github.com/user-attachments/assets/d7e8d9df-260c-4dac-8c98-454930851263

(PC-32026) feat(venue): show video fakedoor only once

---

.maestro/testsV2/subFolder/auth/SignupFromProfile.yml
.maestro/testsV2/subFolder/booking/BookCinemaOffer.yml
.maestro/testsV2/subFolder/booking/BookDigitalOffer.yml
.maestro/testsV2/subFolder/booking/BookDuoOffer.yml
.maestro/testsV2/subFolder/booking/BookMusicalOffer.yml
.maestro/testsV2/subFolder/booking/BookPhysicalOffer.yml
.maestro/testsV2/subFolder/search/SearchBookablePhysicalOffer.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32082
I have:

(PC-32082) fix(e2e): update booking script v1.308.0

---

src/features/venue/components/VenueContent/VenueContent.tsx
src/features/venue/pages/Venue/Venue.native.test.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31857
I have:

(PC-31857) feat(venue): fakedoor tracking event

---

src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildFacetFilters.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.test.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32094
I have:
| Desktop - Chrome |<img width="1512" alt="Capture d’écran 2024-09-30 à 18 32 32" src="https://github.com/user-attachments/assets/2604609b-55eb-4614-90d9-ac1e2f621dfa">|<img width="1512" alt="Capture d’écran 2024-09-30 à 18 30 31" src="https://github.com/user-attachments/assets/f1b500d9-103d-4a3c-b8a5-b7b3d76b6022">|

(PC-32094) fix(algolia): add nativeCategory for front only books native categories

---

src/ui/components/eventCard/EventCard.tsx

(BSR) fix(EventCard): spacing event card after use of typo DS on Offer

---

src/features/venue/components/VenueContent/VenueContent.tsx
src/features/venue/pages/Venue/Venue.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32031
I have:

(PC-32031) feat(venue): add venue type in qualtrix url

---

__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/venue/pages/Venue/Venue.web.test.tsx

(BSR) feat(venue): skip venue web test

---

src/features/offer/components/MovieCalendar/MovieCalendar.tsx
src/features/offer/components/MovieScreeningCalendar/MovieScreeningCalendar.tsx
src/features/offer/components/MoviesScreeningCalendar/MovieOfferTile.tsx
src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
src/features/offer/components/OfferNewXPCine/CineBlock.tsx
src/features/offer/components/OfferNewXPCine/OfferNewXPCineBlock.tsx
src/features/offer/components/OfferPlace/OfferPlace.native.test.tsx
src/features/offer/components/OfferPlace/OfferPlace.tsx
src/features/offer/components/OfferVenueBlock/OfferVenueBlock.tsx
src/features/offer/components/OfferVenueBlock/VenueBlock.tsx
src/shared/multiVenueOffer/isMultiVenueCompatibleOffer.ts
src/ui/components/VenuePreview/VenuePreview.tsx
src/ui/components/eventCard/EventCardList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31867
I have:
| Platform         | BEFORE | AFTER|
| iOS              | <img width="513" alt="Simulator Screenshot - iPhone 15 - 2024-10-01 at 15 49 51" src="https://github.com/user-attachments/assets/0855756f-cb23-4682-ac94-e6525d0bbd96"> | <img width="513" alt="Simulator Screenshot - iPhone 15 - 2024-10-01 at 15 48 58" src="https://github.com/user-attachments/assets/93c11d52-d212-47b4-80e8-20baac05aa86"> |
| Desktop - Chrome | <img width="1011" alt="Capture d’écran 2024-10-01 à 15 49 36" src="https://github.com/user-attachments/assets/c750e33a-c770-45ba-a619-3698b …

(PC-31867) feat(Offer): Create new XP cine component and add FF

---

__snapshots__/features/profile/pages/FeedbackInApp/FeedbackInApp.native.test.tsx.native-snap
src/features/profile/pages/FeedbackInApp/FeedbackInApp.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31748
I have:
| iOS              |    ![Capture d’écran 2024-09-30 à 15 52 52](https://github.com/user-attachments/assets/f7d59d05-dc73-4267-ae8c-3ed58e3b96d3)   |    ![Capture d’écran 2024-09-30 à 15 46 56](https://github.com/user-attachments/assets/14af1c6f-957e-4970-b464-23449c9209b1)  |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e68870 …

(PC-31748) feat(profile): update feedback in app design

---

src/ui/components/eventCard/EventCard.tsx

(BSR) fix(EventCard): fix height for event card, we want the same size

---

src/api/apiHelpers.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.native.test.ts
src/libs/recommendation/useHomeRecommendedIdsQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31935
I have:

(PC-31935) feat(recommendation): more explicit error message

---

src/api/apiHelpers.ts
src/api/refreshAccessToken.native.test.ts
src/api/refreshAccessToken.ts
src/api/types.ts

Duplicated ticket: 
https://passculture.atlassian.net/browse/PC-31256
https://passculture.atlassian.net/browse/PC-31794
See JIRA ticket or Sentry issue for explanations

(PC-31794) fix(apiHelpers): attempt to reduce number of unknown safeFetch refresh token errors

---

src/features/navigation/RootNavigator/Header/Nav.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31959
I have:

(PC-31959) fix(nav): remove condition which blinks the selection of the search tab

---

src/App.tsx
src/App.web.tsx
src/features/auth/context/AuthContext.native.test.tsx
src/features/auth/context/AuthContext.tsx
src/features/auth/context/AuthWrapper.tsx
src/features/auth/helpers/useConnectServicesRequiringUserId.ts
src/features/auth/helpers/useLoginRoutine.ts
src/features/bookings/pages/Bookings/Bookings.perf.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.perf.test.tsx
src/features/favorites/pages/Favorites.perf.test.tsx
src/features/profile/pages/Profile.perf.test.tsx

Supprime le warning "require cycle" sur AuthContext
I have:

(BSR) fix(AuthContext): require cycle

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32176
Link to Firebase : https://console.firebase.google.com/u/0/project/passculture-native/firestore/databases/-default-/data/~2FfeatureFlags~2Ftesting
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v …

(PC-32176) feat(SearchN1Cinema): new FF

---

__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclaration.native.test.tsx.native-snap
src/features/profile/pages/Accessibility/AccessibilityDeclaration.tsx

I have:
| Phone - Chrome   |  ![Capture d’écran 2024-10-04 à 14 17 08](https://github.com/user-attachments/assets/af0446d6-c7f8-4f01-b53d-23f06737f311) |    ![Capture d’écran 2024-10-04 à 14 16 45](https://github.com/user-attachments/assets/b2aa9a46-3b63-49b3-bb45-74bb6703b795) |
[2]: …

feat(profile): update accessibility declaration

---

src/features/search/pages/Search/SearchN1/SearchN1.native.test.tsx
src/features/search/pages/Search/SearchN1/SearchN1.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31609
I have:
FF ON :
FF OFF :

(PC-31609) feat(SearchN1): FF indexation of search n-1 on replica

---

.maestro/testsV2/FavoriteSectionCheck.yml
.maestro/testsV2/subFolder/GoToBookingFromVenue.yml
.maestro/testsV2/subFolder/auth/LoginFromFavorites.yml
.maestro/testsV2/subFolder/auth/LoginFromProfileForBeneficiaryUser.yml
.maestro/testsV2/subFolder/booking/CheckBookingSection.yml
.maestro/testsV2/subFolder/booking/CheckDetailPage.yml
.maestro/testsV2/subFolder/favorite/AddToFavorite.yml
.maestro/testsV2/subFolder/favorite/DeleteFavorite.yml
.maestro/testsV2/subFolder/favorite/VerifyFavOrder.yml
.maestro/testsV2/subFolder/favorite/VerifyFavScreen.yml
.maestro/testsV2/subFolder/venue/VerifyOfferInfo.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32099
I have:
https://github.com/user-attachments/assets/23fad837-1674-49a4-af79-ec69fdfe8661

(PC-32099) feat(e2e): create favorite section test case

---

.maestro/testsV2/subFolder/search/SearchBookableCinemaOffer.yml
.maestro/testsV2/subFolder/search/SearchBookableDuoOffer.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32218
I have:

(PC-32218) fix(e2e): update search categories in booking scripts

---

src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.ts
src/ui/components/buttons/SubcategoryButton/SubcategoryButtonListWrapper.native.test.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButtonListWrapper.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32110
I have:

(PC-32110) feat(SearchN1): add SearchN1 Cinema

---

src/libs/algolia/fetchAlgolia/fetchVenues/adaptAlgoliaVenues.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32124
I have:

(PC-32124) fix(venueMap): set default value to "true" for isPermanent when adapting algolia venues

---

__snapshots__/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx.native-snap
src/api/gen/api.ts
src/features/auth/context/SettingsContext.tsx
src/features/identityCheck/pages/helpers/useStepperInfo.native.test.tsx
src/features/identityCheck/pages/helpers/useStepperInfo.tsx
src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx
src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.tsx
src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.web.test.tsx
src/features/internal/cheatcodes/pages/NavigationSignUp/NavigationIdentityCheck/NavigationIdentityCheck.tsx
src/features/navigation/RootNavigator/subscriptionRoutes.ts
src/features/navigation/RootNavigator/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-30876
I have:
| Desktop - Chrome |               |    <img width="1512" alt="image" src="https://github.com/user-attachments/assets/bb910a46-01f0-47c8-8145-34f7f60827ac">   | …

(PC-30876) feat(SetPhonenumberWitoutValidation): FF phone number validation

---

src/libs/firebase/firestore/client.web.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31793
I have:

(PC-31793) fix(Firestore): Allow multiple tabs in Firestore persistence

---

__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/ui/theme/designSystemTypographie.tsx

(BSR) fix(TypoDS): fixing Heading attrs

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32340
Link to Firestore Database : https://console.firebase.google.com/u/0/project/passculture-native/firestore/databases/-default-/data/~2FfeatureFlags~2Fproduction
I have:
[2]: …

(PC-32340) feat(SearchN1): FF Films, documentaires et series

---

src/features/search/helpers/useSync/useSync.ts
src/libs/location/hooks/useDistance.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32286
I have:
https://github.com/user-attachments/assets/5ccea431-2998-40c2-96d1-8773c202a873

(PC-32286) fix(distance): remove condition

---

.github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml
.github/workflows/dev_on_dispatch_service_worker_test.yml
.github/workflows/dev_on_pull_request_reassure.yml
.github/workflows/dev_on_pull_request_title_checker.yml
.github/workflows/dev_on_workflow_check_folder_change.yml
.github/workflows/dev_on_workflow_check_proxy_version.yml
.github/workflows/dev_on_workflow_chromatic.yml
.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_environment_soft_deploy.yml
.github/workflows/dev_on_workflow_install.yml
.github/workflows/dev_on_workflow_linter_ts.yml
.github/workflows/dev_on_workflow_run_e2e_android.yml
.github/workflows/dev_on_workflow_tester.yml
.github/workflows/dev_on_workflow_ts_noUncheckedIndexedAccess.yml
.github/workflows/dev_on_workflow_ts_prune.yml
.github/workflows/dev_on_workflow_update_jira_issues.yml
.github/workflows/dev_on_workflow_web_deploy.yml
.github/workflows/dev_on_workflow_web_proxy_deploy.yml

https://github.com/pass-culture/pass-culture-app-native/actions/runs/11271220892/job/31344359585#step:6:9
suite de #6991
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25b …

(BSR) build(pipeline): pin runner to have good Android version

---

src/features/offer/api/useAlgoliaSimilarOffers.ts
src/features/offer/api/useSimilarOffers.native.test.ts
src/features/offer/api/useSimilarOffers.ts
src/features/offer/helpers/useOfferPlaylist/useOfferPlaylist.ts
src/libs/queryKeys.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31963
I have:

(PC-31963) fix(offer): limit similar offers api call

---

src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.native.test.tsx
src/features/reactions/components/ReactionChoiceModal/ReactionChoiceModal.tsx
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32140
I have:

(PC-32140) feat(reaction): trigger ValidationReaction log

---

.github/workflows/dev_on_push_workflow_main.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32367

(PC-32367) ci(perf): Add deploy proxy for perf env

---

src/features/offer/components/OfferReactionSection/OfferReactionSection.native.test.tsx
src/features/offer/components/OfferReactionSection/OfferReactionSection.tsx
src/features/reactions/api/useReactionMutation.test.ts
src/features/reactions/api/useReactionMutation.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29453
I have:

(PC-29453) feat(offer): add J'aime button behavior

---

.env.perf
.github/workflows/dev_on_push_workflow_main.yml
package.json
server/.env.perf
server/package.json

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32367

(PC-32367) perf(server): Add perf script for deploying webproxy

---

src/features/offer/components/OfferReactionSection/OfferReactionSection.native.test.tsx
src/features/offer/components/OfferReactionSection/OfferReactionSection.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-29454
I have:

(PC-29454) feat(offer): add Je n'aime pas button behavior

---

src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32326
I have:

(PC-32326) fix(tests): SetPhoneNumberWithoutValidation

---

server/app.yaml
server/package.json
server/src/index.test.ts
server/src/libs/environment/env.ts
server/src/middlewares/webAppProxyMiddleware.ts
server/yarn.lock
src/features/identityCheck/pages/phoneValidation/SetPhoneNumberWithoutValidation.native.test.tsx

(BSR) fix(proxy): fix web deploy proxy

---

src/features/home/pages/ThematicHome.native.test.tsx
src/features/home/pages/ThematicHome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32399
I have:
| Platform         | Avec geoloc | Sans geoloc |
| iOS              |<video src="https://github.com/user-attachments/assets/f18e2e50-b0db-4181-92d3-2fa794f068f4"/>|<video src="https://github.com/user-attachments/assets/94878710-ce13-4cdb-8152-a177826bc0b7"/>|
| Desktop - Chrome |<video src="https://github.com/user-attachments/assets/28d8c8e1-af34-44ef-bc22-ada02cab4407"/>|<video src="https://github.com/user-attachments/assets/de465c4f-bd02-4a28-a046-b6ed0fc9ea2c"/>|

(PC-32399) fix(localization): localization from deeplink should be around_me if geolocated

---

src/features/venueMap/components/VenueMapLabel/VenueMapLabel.native.test.tsx
src/features/venueMap/components/VenueMapLabel/VenueMapLabel.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.native.test.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32293
I have:
| iOS              |               |![Capture d’écran 2024-10-15 à 12 12 20](https://github.com/user-attachments/assets/69df36b7-4f18-40f8-bb75-72c130434631)| …

(PC-32293) feat(VenueMap): add label on venue map pin (mob)

---

src/features/home/pages/ThematicHome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32399
I have:

(PC-32399) fix(loc): use switch true

---

__snapshots__/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx.native-snap
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.native.test.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31352
I have:

(PC-31352) feat(DeleteProfileReason): Use new route for delete

---

__snapshots__/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx.native-snap
__snapshots__/features/culturalSurvey/pages/CulturalSurveyThanks.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/confirmation/IdentityCheckHonor.native.test.tsx.native-snap
src/features/culturalSurvey/helpers/useGetCulturalSurveyContent.ts
src/features/culturalSurvey/pages/CulturalSurveyIntro.native.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyIntro.tsx
src/features/identityCheck/pages/confirmation/IdentityCheckHonor.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32317
I have:
| Phone - Chrome   |               |  ![Capture d’écran 2024-10-16 à 09 13 50](https://github.com/user-attachments/assets/66439c45-fce2-45ac-a87a-5764937200e8) ![Capture d’écran 2024-10-16 à 09 14 08](https://github.com/user-attachments/assets/128fc1c9-5568-4394-9e79-587f543b6172) ![Capture d’écran 2024-10-16 à 09 14 28](https://github.com/user-attachments/assets/0376a8ed-40bb-4c43-8239-611067901730) |
| Desktop - …

(PC-32317) feat(identityCheck): update wording for IdentityCheckHonor, CulturalSurveyIntro and CulturalSurveyThanks

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-PC-32206
I have:

(PC-32206) fix(algolia): bump version

---

ios/PassCulture.xcodeproj/project.pbxproj

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31573
Fixed the syntax

(PC-31573) fix(sentry): deploy ios

---

.github/workflows/dev_on_workflow_web_proxy_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32422
I have:

(PC-32422) fix(proxy): add corepack enable to web proxy deploy job

---

doc/installation/setup.md

(BSR) docs(install): update setup doc

---

src/features/search/components/AutocompleteOfferItem/AutocompleteOfferItem.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32151
I have:

(PC-32151) refactor(autocomplete): partially simplify autocompleteofferitem

---

src/features/bookings/pages/BookingDetails/BookingDetails.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32518
I have:
| Desktop - Chrome |<img width="1440" alt="Capture d’écran 2024-10-18 à 11 05 34" src="https://github.com/user-attachments/assets/135f5a8f-85b1-45ca-9bf0-a63b020239a4">|<img width="1440" alt="Capture d’écran 2024-10-18 à 11 04 53" src="https://github.com/user-attachments/assets/df918f29-90af-49e3-8fef-07d64bb880c9">|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10f …

(PC-32518) feat(BookingDetails): add coma

---

src/features/search/helpers/getSearchVenuePlaylistTitle/getSearchVenuePlaylistTitle.ts
src/features/search/pages/Search/SearchN1/SearchN1.native.test.tsx
src/features/search/pages/Search/SearchN1/SearchN1.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32118
I have:
| Platform         | pas localisé | localisé |
| Desktop - Chrome |<img width="1437" alt="Capture d’écran 2024-10-17 à 17 56 13" src="https://github.com/user-attachments/assets/9695e285-3b1e-42af-aea2-316c849f6649">|<img width="1440" alt="Capture d’écran 2024-10-17 à 17 56 28" src="https://github.com/user-attachments/assets/110750cb-8b37-4321-b858-da5229ca0fe0">|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=1 …

(PC-32118) feat(SearchN1Cinema): add Venue playlist

---

src/api/gen/api.ts
src/features/auth/fixtures/fixtures.ts
src/features/identityCheck/pages/Stepper.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32322
I have:

(PC-32322) chore(api): update schema api

---

src/features/artist/components/ArtistBody/ArtistBody.native.test.tsx
src/features/artist/components/ArtistBody/ArtistBody.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32439
I have:

(PC-32439) feat(artist): set avatar  with top offer image

---

.github/workflows/on_dispatch_deploy_perf_stack.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32476

(PC-32476) ci(perf): Add workflow to deploy perf

---

src/libs/styled/useComputedTheme.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32558
I have:

(PC-32558) fix(theme): fix the tiles size to adapt with the new typo

---

src/features/search/pages/Search/SearchN1/SearchN1.native.test.tsx
src/features/search/pages/Search/SearchN1/SearchN1.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32119
I have:
| Platform         | avec loc | sans loc  |
| iOS              |![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-21 at 17 24 02](https://github.com/user-attachments/assets/4bd4ae67-ce17-482f-8f2b-ac21a08c3aaf)|![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-21 at 17 24 14](https://github.com/user-attachments/assets/662fed71-6515-42cc-954f-5eabdfe7594f)|
[2]: …

(PC-32119) feat(SearchN1): venue playlist on SearchN1 Films, séries, documentaires

---

.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_environment_soft_deploy.yml
.github/workflows/dev_on_workflow_web_deploy.yml
.github/workflows/dev_on_workflow_web_proxy_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32510
I have:

(PC-32510) chore(pipeline): slack notification should not be skipped if job succeeded

---

src/features/auth/pages/signup/SignupForm.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32631

(PC-32631) fix(tests): deflakification SignupForm

---

__snapshots__/features/favorites/pages/Favorites.native.test.tsx.native-snap
__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
src/features/bookOffer/components/Calendar/Calendar.tsx
src/features/favorites/components/Buttons/Sort.tsx
src/features/home/components/modules/business/NewBusinessModule.tsx
src/features/reactions/components/ReactionChoiceModalBodyWithRedirection/ReactionChoiceModalBodyWithRedirection.tsx
src/features/search/components/Buttons/FilterButton/FilterButton.tsx
src/theme/index.ts
src/ui/animations/helpers/getAnimationState.ts
src/ui/components/BlurryWrapper/BlurryWrapper.tsx
src/ui/components/ScrollToTopButton.tsx
src/ui/theme/colors.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32638
I have:

(PC-32638) refactor(Colors): remove hard code colors from code

---

src/features/search/components/SearchBox/SearchBox.native.test.tsx
src/features/search/components/SearchBox/SearchBox.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.native.test.ts
src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.ts
src/features/search/pages/Search/SearchN1/SearchN1.native.test.tsx
src/features/search/pages/Search/SearchN1/SearchN1.tsx
src/features/search/pages/Search/SearchN1/SearchN1.web.test.tsx
src/features/search/pages/Search/SearchN1/SearchN1.web.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32487
I have:
| Desktop - Chrome | x |https://github.com/user-attachments/assets/b1dd28fa-c343-4b77-bf76-6ff0d2bcd8e5|

(PC-32487) fix(venuePlaylist): offerCategories should be in searchState on SearchN1

---

__snapshots__/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx
src/features/profile/pages/Accessibility/AccessibilityActionPlan.web.test.tsx
src/features/search/pages/modals/VenueModal/VenueModal.tsx
src/features/search/pages/modals/VenueModal/VenueModal.web.test.tsx
src/features/venue/pages/Venue/Venue.web.test.tsx

(BSR) fix(tests): fix Venue, AccessibilityPlanAction and EndedBookings web flaky tests

---

src/features/bookOffer/components/BookingDetails.native.test.tsx
src/features/offer/components/MoviesScreeningCalendar/MovieCalendarContext.tsx
src/features/offer/components/MoviesScreeningCalendar/moviesOffer.builder.test.ts
src/features/offer/components/MoviesScreeningCalendar/moviesOffer.builder.ts
src/features/offer/components/OfferNewXPCine/CineBlock.native.test.tsx
src/features/offer/components/OfferNewXPCine/CineBlock.tsx
src/features/offer/components/OfferNewXPCine/OfferNewXPCineBlock.tsx
src/features/offer/components/OfferNewXPCine/OfferNewXPCineContent.native.test.tsx
src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.native.test.ts
src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.ts
src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32303
I have:
| Desktop - Chrome | <img width="1034" alt="Capture d’écran 2024-10-23 à 16 07 21" src="https://github.com/user-attachments/assets/d8dc2eae-ae23-42a1-8cd0-3245c81a930f"> | <video src="https://github.com/user-attachments/assets/3c82542f-306f-42ac-9339-261380124ceb" width="526" /> |

(PC-32303) feat(Offer): Retours xp ciné

---

__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap

Fix to take in account these changes:
https://github.com/pass-culture/pass-culture-app-native/pull/7088/files

(BSR) fix(snap): Venue.web test snap

---

doc/ci-cd/deployment.md

(BSR) refactor(doc): clarify hotfix procedure in deployment.md

---

src/libs/subcategories/mappings.ts

(BSR) fix(mapping): remove usage of as in subcategories mappings

---

src/ui/components/tiles/HorizontalOfferTile.native.test.tsx
src/ui/components/tiles/HorizontalTile.tsx
src/ui/components/tiles/OfferName.tsx
src/ui/theme/colors.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32275
I have:
iOS
Android
Web

(PC-32275) feat(horizontalTile): set distange tag

---

src/features/home/api/useHomeRecommendedOffers.native.test.ts
src/features/home/api/useHomeRecommendedOffers.ts
src/features/home/components/modules/OffersModule.tsx
src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts
src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32332
I have:
| Platform         | Mockup After |
| :--------------- | :---------: |
| Desktop - Chrome | <video src="https://github.com/user-attachments/assets/da763ac6-7318-496d-8c19-8033d9f3b286" width="1012" /> |

(PC-32332) feat(Home): Retours playlist hybride

---

src/features/home/pages/ThematicHome.native.test.tsx
src/features/home/pages/ThematicHome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32690
I have:

(PC-32690) fix(HomeN1): localization from deeplink and in app

---

src/features/offer/components/OfferContent/OfferContent.web.tsx
src/features/offer/components/OfferContent/OfferContentBase.tsx
src/features/offer/helpers/getOfferImageUrls/getOfferImageUrls.ts
src/features/offer/pages/OfferPreview/OfferPreview.tsx
src/shared/getImagesUrls/getImagesUrls.test.ts
src/shared/getImagesUrls/getImagesUrls.ts
src/ui/components/ImagesCarousel/ImagesCarousel.native.test.tsx
src/ui/components/ImagesCarousel/ImagesCarousel.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32651
I have:

(PC-32651) feat(offer): use generic images carousel for offer preview

---

src/features/venueMap/components/VenueMapBottomSheet/VenueMapBottomSheet.tsx
src/features/venueMap/components/VenueMapView/VenueMapView.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32597
I have:

(PC-32597) feat(VenueMap): allow bottom sheet to close with swipe down

---

__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/home/api/helpers/useGetThematicHeaderHeight.ts
src/features/home/components/SubscribeButtonWithModals.tsx
src/features/home/components/SubscribeButtonWithTooltip.tsx
src/features/home/components/headers/AnimatedCategoryThematicHomeHeader.native.test.tsx
src/features/home/components/headers/AnimatedCategoryThematicHomeHeader.tsx
src/features/home/components/headers/CategoryThematicHomeHeader.native.test.tsx
src/features/home/components/headers/CategoryThematicHomeHeader.tsx
src/features/home/components/headers/DefaultThematicHomeHeader.tsx
src/features/home/components/headers/ThematicHomeHeader.native.test.tsx
src/features/home/components/headers/ThematicHomeHeader.tsx
src/features/home/pages/ThematicHome.tsx
src/features/internal/cheatcodes/pages/ThematicHomeHeaderCheatcode/CategoryThematicHomeHeaderCheatcode.tsx
src/features/internal/cheatcodes/pages/ThematicHomeHeaderCheatcode/DefaultThematicHomeHeaderCheatcode.tsx
src/features/internal/cheatcodes/pages/ThematicHomeHeaderCheatcode/HighlightThematicHomeHeaderCheatcode.tsx
src/features/subscription/components/buttons/SubscribeButton.tsx
src/ui/components/buttons/ToggleButton.stories.tsx
src/ui/components/buttons/ToggleButton.tsx
src/ui/components/headers/ContentHeader.tsx
src/ui/storybook/VariantsTemplate.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31197
I have:
| iOS              |               | https://github.com/user-attachments/assets/5e5bbeda-1eaa-45ec-bbbc-fad2d0709c83 |
| Desktop - Chrome |               | ![Capture d’écran 2024-10-28 à 09 38 01](https://github.com/user-attachments/assets/7b4825dd-f6cd-49bf-96e3-a7a189462f9f)  ![Capture d’écran 2024-10-28 à 09 39 44](https://github.com/user-attachments/assets/8b035f70-5d8b-4368-8322-e6ff2924ab1e) |
[1]: …

(PC-31197) feat(subscription): add SubscribeButton in ThematicHomeHeader

---

src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/features/navigation/screenParamsUtils.ts
src/features/venue/components/VenueBody/VenueBanner.native.test.tsx
src/features/venue/components/VenueBody/VenueBanner.tsx
src/features/venue/components/VenueBody/VenueBanner.web.test.tsx
src/features/venue/components/VenueTopComponent/VenueTopComponent.native.test.tsx
src/features/venue/components/VenueTopComponent/VenueTopComponent.tsx
src/features/venue/components/VenueTopComponent/VenueTopComponent.web.test.tsx
src/features/venue/pages/VenuePreviewCarousel/VenuePreviewCarousel.native.test.tsx
src/features/venue/pages/VenuePreviewCarousel/VenuePreviewCarousel.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32581
I have:
| iOS              |               |![Capture d’écran 2024-10-28 à 17 36 03](https://github.com/user-attachments/assets/0e4cb369-7830-4799-b70e-c37d93c4a9ff)|
| Android          |               |![Capture d’écran 2024-10-28 à 17 37 04](https://github.com/user-attachments/assets/88cfbf53-93a2-47c2-ae6e-f8abdf324c22)| …

(PC-32581) feat(venue): open venue preview carousel when pressing venue image in iOS and Android

---

__mocks__/react-native-reanimated-carousel.tsx
src/features/offer/components/ImagesCarouselModal/ImagesCarouselModal.native.test.tsx
src/features/offer/components/ImagesCarouselModal/ImagesCarouselModal.tsx
src/features/offer/components/ImagesCarouselModal/ImagesCarouselModal.web.test.tsx
src/features/offer/components/ImagesCarouselModal/ImagesCarouselModal.web.tsx
src/features/offer/components/OfferContent/OfferContent.web.tsx
src/features/offer/components/OfferPreviewModal/OfferPreviewModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32650
I have:

(PC-32650) refactor(offer): images carousel modal

---

src/libs/monitoring/config.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31627
I have:

(PC-31627) fix(sentry): avoid App hanging for at least 2000 ms.

---

.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_run_e2e_android.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32393
I have:

(PC-32393) chore(firebase): Update CI to match new secrets naming

---

.maestro/testsV2/ProfileAndDeletionSectionCheck.yml
.maestro/testsV2/SearchAndBookCinemaOffer.yml
.maestro/testsV2/SearchAndBookDuoOffer.yml
.maestro/testsV2/subFolder/LaunchAppWithPermissions.yml
.maestro/testsV2/subFolder/booking/BookCinemaOffer.yml
.maestro/testsV2/subFolder/booking/BookDuoOffer.yml
.maestro/testsV2/subFolder/cloud/commands/SetLocalizationToEverywhere.yml
.maestro/testsV2/subFolder/home/OpenActivationModuleFromHome.yml
.maestro/testsV2/subFolder/profil/DeletionNotAllowed.yml
.maestro/testsV2/subFolder/profil/DeletionReactivation.yml
.maestro/testsV2/subFolder/search/SearchBookableCinemaOffer.yml
.maestro/testsV2/subFolder/search/SearchBookableDuoOffer.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32604
I have:

(PC-32604) fix(e2e): v1.312.7

---

.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_run_e2e_android.yml

(BSR) chore(CI): fix environment variables for CI

---

src/ui/components/buttons/ButtonPrimary.stories.tsx
src/ui/components/buttons/ButtonPrimaryWhite.stories.tsx
src/ui/components/buttons/ToggleButton.stories.tsx
src/ui/components/buttons/buttonWithLinearGradient/ButtonWithLinearGradient.stories.tsx
src/ui/storybook/VariantsTemplate.tsx

I have:
| Platform         |  Example |
| Storybook              |      ![Capture d’écran 2024-10-30 à 13 12 46](https://github.com/user-attachments/assets/26c0592f-4717-4073-90dc-a9365a240c73) ![Capture d’écran 2024-10-30 à 13 12 06](https://github.com/user-attachments/assets/a7b87a3d-17f0-400d-9c27-c8d789d79f3c) ![Capture d’écran 2024-10-30 à 13 11 58](https://github.com/user-attachments/assets/d9eb9525-b930-48cc-b3b3-f2da97e240c4)    |   
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47 …

(BSR) feat(storybook): use VariantsTemplate for ButtonPrimaryWhite, ButtonPrimary dans ButtonWhitLinearGradient

---

.maestro/testsV2/subFolder/booking/BookCinemaOffer.yml
.maestro/testsV2/subFolder/booking/BookDuoOffer.yml

(BSR) fix(e2e): correct indentation error in runFlow command

---

src/ui/components/buttons/ToggleButton.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31197
I have:
| Desktop - Chrome |  ![Capture d’écran 2024-10-30 à 11 06 48](https://github.com/user-attachments/assets/250d950b-9a90-4925-ab44-8f6c42c0e289) |  ![Capture d’écran 2024-10-30 à 11 06 05](https://github.com/user-attachments/assets/2ecc5869-5bf6-4155-8bd2-d1d0902e53df) |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e6887066cf613 …

(PC-31197) feat(ui): update background and border color ToggleButton

---

src/features/offer/components/OfferArtists/OfferArtists.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32446
Limitation du nombre de lignes à 2 pour le nom de l'artiste.
I have:

(PC-32446) fix(artist): set max lines to artist name

---

.env.integration
.env.perf
.env.production
.env.staging
.env.testing
__snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
src/features/profile/pages/LegalNotices/LegalNotices.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32720
I have:

(PC-32720) feat(LegalNotice): add TVA text and update CGU link

---

.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml

Changed a condition for getting the right file

(BSR) fix(CI): change condition var for firebase file

---

src/features/internal/cheatcodes/pages/Navigation/Navigation.tsx
src/features/internal/cheatcodes/pages/NewCaledonia.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts
src/libs/firebase/firestore/exchangeRates/getExchangeRates.native.test.ts
src/libs/firebase/firestore/exchangeRates/getExchangeRates.ts
src/libs/firebase/firestore/exchangeRates/useGetEuroToCFPRate.native.test.ts
src/libs/firebase/firestore/exchangeRates/useGetEuroToCFPRate.ts
src/libs/firebase/firestore/types.ts
src/shared/currency/convertEuroToCFP.native.test.ts
src/shared/currency/convertEuroToCFP.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32779
I have:
| cheatcode              |    ![Capture d’écran 2024-11-04 à 16 36 36](https://github.com/user-attachments/assets/841bb3d3-47d5-4b1b-a4df-881065d40f3f)  |       

(PC-32779) feat(NC): get € to CFP rate from Firestore

---

eslint-custom-rules/nbsp-in-text.js
eslint-custom-rules/nbsp-in-text.test.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32790
I have:

(PC-32790) feat(NC): update nbsp-in-text ESLint rule for CSP

---

src/features/internal/cheatcodes/pages/NewCaledonia.tsx
src/shared/currency/convertEuroToCFP.native.test.ts
src/shared/currency/convertEuroToCFP.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32780
I have:
| iOS              |               |    <img width="322" alt="Capture d’écran 2024-11-05 à 10 49 51" src="https://github.com/user-attachments/assets/e3d6997b-6c7f-466e-af9f-8948d2b9d0f3">  |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb? …

(PC-32780) feat(NC): update convertEuroToCFP with rounded possibility

---

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
__snapshots__/features/bookings/pages/Bookings/Bookings.native.test.tsx.native-snap
__snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap
src/features/bookings/fixtures/bookingsSnap.ts
src/features/bookings/helpers/getLocationLabel.test.ts
src/features/bookings/helpers/getLocationLabel.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32019
I have:

(PC-32019) feat(getLocationLabel): use offer address in place of venue

---

src/features/search/pages/Search/ThematicSearch/ThematicSearch.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32718
I have:

(PC-32718) fix(search): filter on bookstore in thematic search

---

.eslintrc.js
__mocks__/react-native-map-clustering.tsx
__mocks__/react-native-reanimated-carousel.tsx
src/features/profile/pages/Achievements/Achievements.tsx
src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx

Co-authored-by: Mathieu Meissonnier <mmeissonnier-pass@users.noreply.github.com>
Co-authored-by: bpeyrou-pass <bpeyrou-pass@users.noreply.github.com>
Co-authored-by: Xavier Le Cunff <JohnBerd@users.noreply.github.com>
I have:

(BSR) chore(tests): fix some typescript warning

---

.github/workflows/dev_on_workflow_run_e2e_android.yml
.maestro/testsV2/VenueMapCheck.yml
.maestro/testsV2/subFolder/booking/BookCinemaOffer.yml
.maestro/testsV2/subFolder/booking/BookDuoOffer.yml
.maestro/testsV2/subFolder/cloud/commands/SetLocalizationToParis.yml
.maestro/testsV2/subFolder/venue/AccessVenueMapFromHome.yml
.maestro/testsV2/subFolder/venue/AccessVenueMapFromSearch.yml
.maestro/testsV2/subFolder/venue/AccessVenueMapFromSearchResult.yml
.maestro/testsV2/subFolder/venue/VerifyVenueMap.yml
.maestro/testsV2/subFolder/venue/VerifyVenueMapInResult.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32863
I have:

(PC-32863) feat(e2e): create test for venueMap

---

__snapshots__/features/venue/pages/Venue/Venue.web.test.tsx.web-snap
src/features/favorites/pages/Favorites.web.test.tsx
src/features/offer/pages/Offer/Offer.web.test.tsx
src/features/profile/pages/Accessibility/AccessibilityActionPlan.web.test.tsx
src/features/search/pages/SearchLanding/SearchLanding.web.test.tsx
src/features/venue/pages/Venue/Venue.web.test.tsx

Comme convenu lors de la synchro tech

(BSR) fix(tests): increase timeout on a11y tests

---

.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_environment_soft_deploy.yml
.github/workflows/dev_on_workflow_web_deploy.yml
.github/workflows/dev_on_workflow_web_proxy_deploy.yml
.vscode/extensions.json

(BSR) chore(ci): slack notification condition

---

src/features/bookOffer/components/Calendar/Calendar.test.tsx
src/features/bookOffer/components/Calendar/Calendar.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32820
I have:
| iOS              |    ![Capture d’écran 2024-11-08 à 11 40 46](https://github.com/user-attachments/assets/960bfb2a-4d1b-4838-928e-de216f5fae13)  | ![Capture d’écran 2024-11-08 à 12 08 21](https://github.com/user-attachments/assets/e3269678-825a-4a0b-b05d-b126506b0f62) | …

(PC-32820) feat(NC): fix display price in Calendar

---

src/features/profile/pages/Achievements/AchievementData.ts
src/features/profile/pages/Achievements/Achievements.tsx
src/features/profile/pages/Achievements/useAchievementDetails.ts
src/features/profile/pages/Achievements/useAchievements.native.test.ts
src/features/profile/pages/Achievements/useAchievements.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32684
I have:

(PC-32684) feat(Achievements): added real data

---

.eslintrc.js
src/features/search/components/sections/Price/Price.native.test.tsx
src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx
src/features/search/pages/modals/PriceModal/PriceModal.tsx
src/features/search/pages/modals/PriceModal/PriceModal.web.test.tsx
src/shared/currency/useGetCurrencyToDisplay.native.test.ts
src/shared/currency/useGetCurrencyToDisplay.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32819
I have:
| Desktop - Chrome |               |  ![Capture d’écran 2024-11-08 à 12 36 56](https://github.com/user-attachments/assets/68729c45-f396-4982-9b9f-709ddce7b8b8)  |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb …

(PC-32819) feat(NC): use correct currency in PriceModal

---

server/src/index.test.ts

Fix sur le test du contenu html côté server.
I have:

(BSR) fix(server): index compare method

---

src/shared/currency/useGetCurrencyToDisplay.native.test.ts
src/shared/currency/useGetCurrencyToDisplay.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32819
I have:
| Desktop - Chrome |               |  <img width="603" alt="Capture d’écran 2024-11-12 à 11 45 57" src="https://github.com/user-attachments/assets/07f4343f-9782-4ec2-9713-37e242bb9aec"> |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=1 …

(PC-32819) feat(NC): update pacific franc full wording

---

doc/installation/setup.md
fastlane/FastfileIOSSigning
package.json
yarn.lock

(BSR) chore(setup): update setup

---

src/features/profile/pages/DeleteProfileReason/DeleteProfileReason.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32885

(PC-32885) fix(DeleteProfileReason): remove non-null-assertion

---

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
src/features/bookings/components/BookingDetailsCancelButton.tsx
src/features/bookings/components/Ticket/TicketSwiper.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.tsx
src/ui/components/headers/HeaderWithImage.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32986
I have:
| iOS              |![Capture d’écran 2024-11-13 à 14 39 49](https://github.com/user-attachments/assets/47ce2b30-e5ac-4879-b2f1-50378cef46ef)|![Capture d’écran 2024-11-13 à 14 50 07](https://github.com/user-attachments/assets/bec56ffd-519b-4103-9393-e2dcbdfbcf1c)|
| Android          |![Capture d’écran 2024-11-13 à 14 47 06](https://github.com/user-attachments/assets/d7d38799-7d71-4be9-9d9c-0c01bff4b3c3)|![Capture d’écran 2024-11-13 à 14 55 56](https://github.com/user-attachments/assets/495bf40f-aa04-43 …

(PC-32986) feat(booking): remove BookingDetails Spacer.Column

---

src/features/internal/cheatcodes/pages/AppComponents/Icons.stories.tsx
src/features/internal/cheatcodes/pages/AppComponents/IconsContainer.tsx
src/features/internal/cheatcodes/pages/AppComponents/Illustrations.stories.tsx
src/ui/theme/colors.stories.tsx
src/ui/theme/designSystemTypographie.stories.tsx
src/ui/theme/typography.stories.tsx

Passage de 396 > 387 stories 
Lien pour tester : https://61fd537ecf081f003a135235-pvwenipyek.chromatic.com/?path=/story/design-system-typographies--typographies
I have:
| Storybook              |       ![Capture d’écran 2024-11-13 à 19 21 11](https://github.com/user-attachments/assets/e1b4f2df-3d16-49f2-842b-f29eb83f0f7b) ![Capture d’écran 2024-11-13 à 19 21 38](https://github.com/user-attachments/assets/d5c7449e-84ff-4418-8f16-532aee499778) ![Capture d’écran 2024-11-13 à 19 21 29](https://github.com/user-attachments/assets/6308e54f-d324-448c-81d5-827351e31e2a) ![Capture d’écran 2024-11-13 à 19 21 …

(BSR) feat(storybook): merge fondations stories

---

src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32598
I added an optional chaining to avoid errors if category does not exist in tree.
I have:

(PC-32598) fix(categories): add optional chaining to avoid errors

---

vite.config.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31602

(PC-31602) chore(test): useless commit for codepush test

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32186
I have:

(PC-32186) feat(ThematicSearchMusic): add FF

---

src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32183
I have:

(PC-32183) feat(ThematicSearch): add Music

---

src/features/home/components/headers/AnimatedCategoryThematicHomeHeader.tsx
src/features/home/components/headers/CategoryThematicHomeHeader.tsx
src/features/offer/components/OfferImageWrapper/OfferImageWrapper.tsx
src/features/venue/components/VenueBody/VenueBanner.tsx
src/features/venueMap/components/VenueMapBlock/VenueMapBlock.tsx
src/libs/recaptcha/ReCaptcha.tsx
src/ui/animations/helpers/getAnimationState.ts
src/ui/components/VerticalStepper/VerticalStepper.stories.tsx
src/ui/theme/colors.stories.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33017
I have:

(PC-33017) refactor(colors): replace hard code rgb colors by color from theme

---

__snapshots__/features/profile/pages/Achievements/Achievements.native.test.tsx.native-snap
src/features/profile/components/Achievements/Badge.tsx
src/features/profile/components/Modals/AchievementDetailsModal.tsx
src/features/profile/pages/Achievements/AchievementData.ts
src/features/profile/pages/Achievements/Achievements.native.test.tsx
src/features/profile/pages/Achievements/Achievements.tsx
src/features/profile/pages/Achievements/useAchievements.native.test.ts
src/features/profile/pages/Achievements/useAchievements.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32683
I have:
| iOS              |        <img width="292" alt="image" src="https://github.com/user-attachments/assets/6d5ea1d2-5fbe-4e25-ab5d-2de87f172d85">       |    ![image](https://github.com/user-attachments/assets/aff6c9fb-871d-41b3-a565-65b39331cb7e)  |
| Desktop - Chrome |               |    <img width="1027" alt="image" src="https://github.com/user-attachments/assets/60acad62-794c-4e6f-8e79-d3f074821eb8">   |
[1]: …

(PC-32683) feat(Achievements): Change achievements page UI

---

.maestro/tests/UserNotConnectedMode.yml
.maestro/tests/VenueMapCheck.yml
.maestro/tests/subFolder/auth/LoginFromPhysicalOffer.yml
.maestro/tests/subFolder/search/SearchBookablePhysicalOffer.yml
.maestro/tests/subFolder/search/SearchOfferFromText.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33083
I have:

(PC-33083) test(e2e): add test for searchBar and SearchFilters

---

src/features/tutorial/components/AgeButton.stories.tsx
src/features/tutorial/components/CreditBlock.stories.tsx
src/features/tutorial/components/CreditStatusTag.stories.tsx
src/features/tutorial/components/profileTutorial/EighteenBlockDescription.stories.tsx
src/features/tutorial/components/profileTutorial/InformationStepContent.stories.tsx
src/features/tutorial/components/profileTutorial/UnderageBlockDescription.stories.tsx
src/features/venue/components/OpeningHoursStatus/OpeningHoursStatus.stories.tsx
src/ui/Playlist/PlaylistArrowButton.stories.tsx
src/ui/components/CheckboxBlock/CheckboxBlock.stories.tsx
src/ui/components/FilterSwitch.stories.tsx
src/ui/components/ModuleBanner/BannerWithBackground.stories.tsx
src/ui/components/ModuleBanner/GenericBanner.stories.tsx
src/ui/components/ModuleBanner/SystemBanner.stories.tsx
src/ui/components/banners/AlertBanner.stories.tsx
src/ui/components/banners/ErrorBanner.stories.tsx
src/ui/components/banners/GenericColoredBanner.stories.tsx
src/ui/components/banners/InfoBanner.stories.tsx
src/ui/components/buttons/HeroButtonList.stories.tsx
src/ui/components/buttons/buttonInsideText/ButtonInsideText.stories.tsx
src/ui/components/snackBar/SnackBar.stories.tsx
src/ui/storybook/VariantsTemplate.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33062
I have:

(PC-33062) feat(storybook): use VariantsTemplate in some stories

---

src/features/profile/components/CitySearchInput/CitySearchInput.native.test.tsx
src/features/profile/components/CitySearchInput/CitySearchInput.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32699
I have:

(PC-32699) feat(NC): update banner wording in CitySearchInput

---

src/api/gen/api.ts
src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
src/fixtures/user.ts
src/shared/currency/useGetCurrencyToDisplay.native.test.ts
src/shared/currency/useGetCurrencyToDisplay.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32814
I have:

(PC-32814) feat(NC): add user currency test in useGetCurrencyToDisplay()

---

src/ui/components/buttons/ToggleButton.stories.tsx
src/ui/components/buttons/buttonWithLinearGradient/ButtonWithLinearGradient.stories.tsx
src/ui/components/headers/RightButtonText.stories.tsx
src/ui/components/inputs/DateInput/DateInput.stories.tsx
src/ui/storybook/VariantsTemplate.tsx

(BSR) fix(storybook): replace fake function with action

---

__snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts
src/features/search/helpers/useSortedSearchCategories/useSortedSearchCategories.native.test.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/getCategoriesFacetFilters.ts
src/libs/subcategories/fixtures/mappings.ts
src/libs/subcategories/placeholderData.ts
src/libs/subcategories/useSearchGroupLabel.native.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32526
I have:
<details> …

(PC-32526) feat(categories): change Films, séries et documentaires label

---

src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/getCategoriesFacetFilters.ts

I have:
<details>
- Remove non-null assertion operators (just like other type assertions, this doesn’t change the runtime behavior of your code, so …

(BSR) fix(contentful): keep old label for Contentful

---

ios/Podfile.lock
package.json
yarn.lock

After running `bundle exec pod install`, I built the ios app and navigated through a few pages with no issues.

(BSR) chore(deps): remove unused lib

---

src/features/internal/cheatcodes/pages/NewCaledonia.tsx
src/shared/currency/useGetCurrencyToDisplay.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32814
I have:
| Platform         | NewCaledonia |
| :--------------- |  :---: |
| Cheatcode |      ![Capture d’écran 2024-11-22 à 11 56 36](https://github.com/user-attachments/assets/a626dbea-871d-46c5-b818-4394fe9aabb2)  |
<details>
- Remove non-null assertion operators (just like other type assertions, this doesn’t change the runtime behavior of …

(PC-32814) feat(NC): update useGetCurrencyToDisplay

---

src/features/auth/components/AuthenticationButton/AuthenticationButton.stories.tsx
src/ui/components/IconWithCaption.stories.tsx

(BSR) feat(storybook): enable chromatic

---

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
__snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap
src/features/bookings/components/EndedBookingInteractionButtons/EndedBookingInteractionButtons.native.test.tsx
src/features/bookings/components/EndedBookingInteractionButtons/EndedBookingInteractionButtons.tsx
src/features/bookings/components/EndedBookingItem.native.test.tsx
src/features/bookings/components/EndedBookingItem.tsx
src/features/bookings/components/EndedBookingReason/EndedBookingReason.native.test.tsx
src/features/bookings/components/EndedBookingReason/EndedBookingReason.tsx
src/features/bookings/components/OnGoingBookingItem.tsx
src/features/bookings/components/SmallBadgedButton.tsx
src/features/bookings/helpers/getEndedBookingDateLabel/getEndedBookingDateLabel.test.ts
src/features/bookings/helpers/getEndedBookingDateLabel/getEndedBookingDateLabel.ts
src/features/bookings/helpers/useReactionIcon/useReactionIcon.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.tsx
src/features/bookings/types.ts
src/ui/components/WithSmallBadge.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31176
I have:
<details>
Test specific:
</details>

(PC-31176) refactor(booking): EndedBookingItem

---

__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
src/features/search/components/Buttons/FilterButton/FilterButton.native.test.tsx
src/features/search/components/Buttons/FilterButton/FilterButton.tsx
src/features/search/components/Buttons/SingleFilterButton/SingleFilterButton.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/venueMap/components/FilterBannerContainer/FilterBannerContainer.native.test.tsx
src/features/venueMap/components/FilterBannerContainer/FilterBannerContainer.tsx
src/features/venueMap/components/FilterBannerContainer/FilterCategoriesBannerContainer.native.test.tsx
src/features/venueMap/components/FilterBannerContainer/FilterCategoriesBannerContainer.tsx
src/features/venueMap/components/FilterBannerContainer/SingleFilterBannerContainer.native.test.tsx
src/features/venueMap/components/FilterBannerContainer/SingleFilterBannerContainer.tsx
src/features/venueMap/hook/useVenueMapFilters.native.test.ts
src/features/venueMap/hook/useVenueMapFilters.ts
src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
src/features/venueMap/pages/VenueMap/VenueMapBase.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33099
I have:
iOS
https://github.com/user-attachments/assets/e87af95f-8ebc-44e6-9bda-39f8bdedaafc
Android
https://github.com/user-attachments/assets/bcd6164c-eca9-4bb0-9de2-f27383ea01d7
<details>
- Remove non-null assertion operators (just like other type assertions, this doesn’t change the runtime behavior of your code, so it’s important to only use `!` when you know that the …

(PC-33099) feat(venueMap): filter header v2

---

.github/workflows/dev_on_workflow_run_e2e_android.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33257
I have:

(PC-33257) feat(e2e): replace maestro cloud config with Robin

---

server/.eslintrc.js

(BSR) feat(eslint): disabled no-currency-symbols in server

---

src/features/navigation/VenueMapFiltersStackNavigator/types.ts
src/features/venueMap/components/FilterBannerContainer/FilterCategoriesBannerContainer.tsx
src/features/venueMap/components/VenueMapFiltersList/VenueMapFiltersList.native.test.tsx
src/features/venueMap/components/VenueMapFiltersList/VenueMapFiltersList.tsx
src/features/venueMap/components/VenueMapTypeFilter/VenueMapTypeFilter.native.test.tsx
src/features/venueMap/components/VenueMapTypeFilter/VenueMapTypeFilter.tsx
src/features/venueMap/pages/VenueMap/VenueMapBase.tsx
src/features/venueMap/pages/modals/VenueMapFiltersModal/VenueMapFiltersModal.tsx
src/features/venueMap/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33158
I have:
| iOS              |![Capture d’écran 2024-11-27 à 11 03 48](https://github.com/user-attachments/assets/f98e178b-3ab3-4e1b-b604-f1066e1a6e0f)|<img width="427" alt="Capture d’écran 2024-11-26 à 18 11 27" src="https://github.com/user-attachments/assets/15d90a40-3aca-4ef3-9e56-1f39b8184809"> <img width="443" alt="Capture d’écran 2024-11-26 à 18 11 32" src="https://github.com/user-attachments/assets/9205f4a0-5778-4794-9fe1-f386a0dd9bf0"> <img width="439" alt="Capture d’écran 2024-11-26 à 18 11 41" …

(PC-33158) feat(venueMap): display checkboxes associated to venue type filter group

---

src/features/venueMap/components/FilterBannerContainer/FilterCategoriesBannerContainer.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33306
I have:
| iOS              |<img width="427" alt="Capture d’écran 2024-11-28 à 17 05 27" src="https://github.com/user-attachments/assets/2bd39182-45c5-46b1-80fb-d7bbb49919c8">|<img width="432" alt="Capture d’écran 2024-11-28 à 17 06 21" src="https://github.com/user-attachments/assets/b16e17b1-8aa9-46e3-9254-b856deed8b11">|
| Android          |<img width="404" alt="Capture d’écran 2024-11-28 à 17 05 20" src="https://github.com/user-attachments/assets/9367fbbe-47d3-4875-9827-15efe77e0c97">|<img width="408" …

(PC-33306) fix(venueMap): venue map filter buttons centered in container

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33300
I have:
<details> …

(PC-33300) chore(dependencies): bump cross-spawn

---

src/features/offer/api/useOffersStocks.ts
src/features/offer/components/ExpandingFlatlist/ExpandingFlatList.stories.tsx
src/features/offer/components/ExpandingFlatlist/ExpandingFlatList.tsx
src/features/offer/components/MovieCalendar/MovieCalendar.tsx
src/features/offer/components/MovieCalendar/components/MovieCalendarDay.tsx
src/features/offer/components/MoviesScreeningCalendar/MovieCalendarContext.tsx
src/features/offer/components/MoviesScreeningCalendar/MoviesScreeningCalendar.tsx
src/features/offer/components/MoviesScreeningCalendar/hook/useMoviesScreeningsList.native.test.ts
src/features/offer/components/OfferCine/CineBlock.native.test.tsx
src/features/offer/components/OfferCine/CineBlock.tsx
src/features/offer/components/OfferCine/CineBlockSkeleton.tsx
src/features/offer/components/OfferCine/OfferCineBlock.tsx
src/features/offer/components/OfferCine/OfferCineContent.native.test.tsx
src/features/offer/components/OfferCine/OfferCineContent.tsx
src/features/offer/helpers/useDaysSelector/useDaysSelector.native.test.ts
src/features/offer/helpers/useDaysSelector/useDaysSelector.ts
src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.native.test.ts
src/features/offer/helpers/useGetVenueByDay/useGetVenuesByDay.ts
src/features/offer/helpers/useListExpander/useListExpander.native.test.ts
src/features/offer/helpers/useListExpander/useListExpander.ts
src/features/offer/helpers/useOffersStocksFromOfferQuery/useOffersStocksFromOfferQuery.native.test.ts
src/features/offer/helpers/useOffersStocksFromOfferQuery/useOffersStocksFromOfferQuery.ts
src/features/offer/helpers/useUserLocation/useUserLocation.ts
src/tests/mockBuilder.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32762
I have:

(PC-32762) feat(XPCine): add disabled dates to calendar

---

.maestro/tests/subFolder/cloud/commands/SetLocalizationToEverywhere.yml
.maestro/tests/subFolder/search/SearchBookablePhysicalOffer.yml
.maestro/tests/subFolder/search/SearchOfferFromText.yml
__snapshots__/features/location/components/HomeLocationModal.native.test.tsx.native-snap
__snapshots__/features/location/components/SearchLocationModal.native.test.tsx.native-snap
__snapshots__/features/search/pages/Search/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
src/features/home/components/headers/HomeHeader.native.test.tsx
src/features/internal/marketingAndCommunication/atoms/LocationFilterChoice.native.test.tsx
src/features/internal/marketingAndCommunication/atoms/LocationFilterChoice.tsx
src/features/location/components/HomeLocationModal.tsx
src/features/location/components/LocationModal.tsx
src/features/location/components/LocationSearchWidget.native.test.tsx
src/features/location/components/LocationWidgetDesktop.native.test.tsx
src/features/location/components/SearchLocationModal.tsx
src/features/location/components/VenueMapLocationModal.tsx
src/features/location/helpers/getLocationTitle.ts
src/features/search/components/SearchBox/SearchBox.native.test.tsx
src/features/search/components/SearchHeader/SearchHeader.native.test.tsx
src/features/search/context/SearchWrapper.native.test.tsx
src/libs/location/types.ts

…rance entière'
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33068
I have:
| iOS              |![Simulator Screenshot - iPhone SE (3rd generation) - 2024-11-15 at 10 21 46](https://github.com/user-attachments/assets/8f2324c8-a51b-4704-84a7-16b393a76611)|  ![simulator_screenshot_D912E83D-6CE6-43D4-825E-EAF9993F1009](https://github.com/user-attachments/assets/9f33d8e6-c8d3-4a09-9ca5-9afdc895329b)|
| Android          |               |<img width="310" alt="Capture d’écran 2024-11-21 à 15 42 06" src="https://github.com/user-attachments/assets/578e9e8e-76a4-4d7a-b3e4-8a93 …

(PC-33068) feat(Localization): Partout and Me localiser become France entière

---

.maestro/tests/subFolder/booking/BookMusicalOffer.yml
.maestro/tests/subFolder/booking/BookPhysicalOffer.yml
.maestro/tests/subFolder/booking/CheckDetailPage.yml
.maestro/tests/subFolder/favorite/AddToFavorite.yml
.maestro/tests/subFolder/search/SearchBookableMusicalOffer.yml
.maestro/tests/subFolder/search/SearchOfferFromText.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33350
I have:

(PC-33350) fix(e2e): v1.317.0

---

src/features/artist/pages/Artist.native.test.tsx
src/features/auth/api/useOAuthState.native.test.ts
src/features/auth/pages/login/Login.native.test.tsx
src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx
src/features/birthdayNotifications/pages/EighteenBirthday.web.test.tsx
src/features/birthdayNotifications/pages/RecreditBirthdayNotification.web.test.tsx
src/features/bookOffer/pages/BookingConfirmation.web.test.tsx
src/features/bookOffer/pages/BookingOfferModal.web.test.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.web.test.tsx
src/features/culturalSurvey/pages/CulturalSurveyIntro.web.test.tsx
src/features/home/components/modules/HomeModule.web.test.tsx
src/features/home/components/modules/TrendsModule.web.test.tsx
src/features/home/components/modules/video/VideoModal.web.test.tsx
src/features/home/pages/Home.web.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.web.test.tsx
src/features/navigation/RootNavigator/Header/AccessibleTabBar.web.test.tsx
src/features/navigation/RootNavigator/Header/Header.web.test.tsx
src/features/offer/components/OfferContent/OfferContent.web.test.tsx
src/features/offer/pages/Offer/Offer.web.test.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
src/features/search/components/SearchList/SearchList.web.test.tsx
src/features/search/components/SearchListHeader/SearchListHeader.web.test.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.web.test.tsx
src/features/search/components/VenuePlaylist/VenuePlaylist.web.test.tsx
src/features/search/pages/SearchFilter/SearchFilter.web.test.tsx
src/features/search/pages/modals/PriceModal/PriceModal.web.test.tsx
src/libs/firebase/firestore/featureFlags/__tests__/setFeatureFlags.tsx

(BSR) refactor(tests): remove duplicate usage of activateFeatureFlags in web tests

---

src/features/profile/components/Modals/AchievementDetailsModal.tsx
src/features/profile/components/Modals/useAchievementDetails.native.test.ts
src/features/profile/components/Modals/useAchievementDetails.ts
src/features/profile/pages/Achievements/AchievementData.ts
src/libs/analytics/__mocks__/logEventAnalytics.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/analytics/events.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32911
I have:
<details>
Test specific:
</details>

(PC-32911) feat(Achievements): add tracking to badge details

---

src/features/profile/pages/Achievements/AchievementData.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32911
I have:
<details>
Test specific:
</details>

(PC-32911) fix(Achievements): Fix tests error

---

__snapshots__/features/search/components/sections/Accessibility/Accessibility.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchFilter/SearchFilter.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
scripts/dead_code_snapshot.txt
src/features/search/components/FilterRow/FilterRow.tsx
src/features/venueMap/components/FilterBannerContainer/FilterCategoriesBannerContainer.tsx
src/features/venueMap/components/VenueMapFiltersList/VenueMapFiltersList.native.test.tsx
src/features/venueMap/components/VenueMapFiltersList/VenueMapFiltersList.tsx
src/features/venueMap/constant.ts
src/features/venueMap/helpers/getFilterDescription/getFilterDescription.test.ts
src/features/venueMap/helpers/getFilterDescription/getFilterDescription.ts
src/features/venueMap/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33105
I have:
| iOS              |![Capture d’écran 2024-12-02 à 15 52 07](https://github.com/user-attachments/assets/6bb72d70-b01f-4fe9-a3cf-87952372c1e8)|![Capture d’écran 2024-12-02 à 15 51 02](https://github.com/user-attachments/assets/2ceae06c-8a8d-4004-8afd-36b20e161d22)|
| Android          |![Capture d’écran 2024-12-02 à 15 52 00](https://github.com/user-attachments/assets/15aa8af8-f033-4402-991b-3709e7444ef0)|![Capture d’écran 2024-12-02 à 15 51 35](https://github.com/user-attachments/assets/0ac99fc4-308c-4e …

(PC-33105) feat(venueMap): display applied filters in list filters

---

src/features/offer/components/OfferContent/OfferCTAProvider.tsx
src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/features/venue/components/VenueContent/VenueContent.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32111
I have:

(PC-32111) feat(showScreeningButton): remove conditional display

---

__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
src/features/offer/components/MovieCalendar/components/MovieCalendarDay.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32762

(PC-32762) feat(XPCine): change calendar disabled color

---

__snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/AcceptCgu/AcceptCgu.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
__snapshots__/features/internal/marketingAndCommunication/pages/DeeplinksGenerator.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
src/features/profile/components/Modals/useAchievementDetails.native.test.ts
src/features/venueMap/components/VenueMapTypeFilter/VenueMapTypeFilter.native.test.tsx
src/features/venueMap/components/VenueMapTypeFilter/VenueMapTypeFilter.tsx
src/features/venueMap/hook/useVenueMapFilters.native.test.ts
src/features/venueMap/hook/useVenueMapFilters.ts
src/theme/index.ts
src/ui/components/inputs/Checkbox/Checkbox.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33273
Retours sur ce ticket : 
- Mettre en gras les labels des checkbox selected
EDIT: Après review design + fonctionnelle (voir video ci-dessous) : 
- La checkbox "Tout afficher" devient "Tout selectionner" et sert à sélectionner toutes les checkbox du dessous
- Quand on sélectionne une seule checkbox filtre, et que côté carte on déselectionne le bouton de la famille, cela déselectionne toute la famille.
- Par souci de cohérence entre les boutons côté carte et les checkbox list de filtres, les checkbox sont toutes déselectionnées par défaut
I have:
iOS
https://github.com/user-attachments/assets/6738949c-9837-4561-9cfa-7acb119bcc1a
[1]: …

(PC-33273) feat(venueMap): filters modal checkbox

---

.github/workflows/dev_on_workflow_tester.yml

I have:
<details>
- Remove non-null assertion operators (just like other type assertions, this doesn’t change the runtime behavior of your code, so …

(BSR) chore(gitHubActions): fix missing restore-key

---

src/features/search/components/SearchMainInput/SearchMainInput.stories.tsx
src/features/subscription/components/ThematicSubscriptionBlock.stories.tsx
src/ui/components/inputs/SearchInput.stories.tsx
src/ui/components/inputs/TextInput.stories.tsx

(PC-33388) fix(storybook): yarn bump revealed errors

---

.maestro/tests/SearchJourney.yml
.maestro/tests/subFolder/profil/SocialNetwork.yml
.maestro/tests/subFolder/search/ResetSearchFilters.yml
.maestro/tests/subFolder/search/SearchForNoResult.yml
.maestro/tests/subFolder/venue/AccessPreviewModule.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33401
I have:

(PC-33401) feat(e2e): add P0 to searchJourney flow

---

src/features/offer/components/OfferCine/CineContentCTA.tsx
src/features/offer/components/OfferCine/OfferCineBlock.tsx
src/features/offer/components/OfferContent/OfferCTAProvider.tsx
src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/features/venue/components/VenueContent/VenueContent.native.test.tsx
src/features/venue/components/VenueOffers/VenueOffers.tsx

(BSR) fix(XPCine): remove button when no text

---

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
src/features/location/components/LocationWidget.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33068
I have:
<details>
Test specific:
</details>

(PC-33068) feat(LocationWidget): bigger width for location title

---

src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.native.test.tsx
src/features/auth/pages/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSentPage.native.test.tsx
src/features/auth/pages/signup/SignupForm.native.test.tsx
src/features/bookOffer/components/BookingImpossible.native.test.tsx
src/features/bookings/pages/Bookings/Bookings.native.test.tsx
src/features/favorites/components/Favorite.native.test.tsx
src/features/profile/pages/Profile.native.test.tsx

(BSR) chore(tests): use findByText instead await act async

---

.maestro/tests/subFolder/booking/BookCinemaOffer.yml
.maestro/tests/subFolder/booking/BookDuoOffer.yml
.maestro/tests/subFolder/booking/BookMusicalOffer.yml
.maestro/tests/subFolder/booking/CheckDetailPage.yml
.maestro/tests/subFolder/cloud/commands/SetLocalizationFromEverywhereToParis.yml
.maestro/tests/subFolder/favorite/AddToFavorite.yml
.maestro/tests/subFolder/profil/SocialNetwork.yml
.maestro/tests/subFolder/search/SearchForNoResult.yml
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33491
I have:

(PC-33491) fix(e2e): fix v1.318.1 + refactor bash layer for Robin usage

---

src/features/profile/components/Modals/AchievementSuccessModal.tsx
src/features/profile/components/Modals/useShouldShowAchievementSuccessModal.native.test.tsx
src/features/profile/components/Modals/useShouldShowAchievementSuccessModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33272
@cedricls1 ran into the following issue on android:

(PC-33272) feat(achievement): fixes

---

src/features/artist/components/ArtistHeader/ArtistHeader.tsx
src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.test.ts
src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.ts
src/features/venue/types.ts
src/ui/components/Avatar/Avatar.stories.tsx
src/ui/components/Avatar/Avatar.tsx
src/ui/components/Avatar/AvatarList.native.test.tsx
src/ui/components/Avatar/AvatarList.tsx
src/ui/components/Avatar/AvatarListItem.native.test.tsx
src/ui/components/Avatar/AvatarListItem.tsx
src/ui/components/Avatar/DefaultAvatar.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33458
I have:
<details>
- In the production code: remove type assertions with `as` (type assertions are …

(PC-33458) feat(AvatarList): add new Avatar List

---

src/features/offer/components/OfferTile/OfferTile.native.test.tsx
src/features/offer/components/OfferTile/OfferTile.tsx
src/libs/styled/useComputedTheme.ts
src/theme/index.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33547
I have:
| iOS              |               |![Capture d’écran 2024-12-11 à 16 17 50](https://github.com/user-attachments/assets/6216dbe3-e306-4810-9f84-a8cf4f00b328)|
| Android          |               |![Capture d’écran 2024-12-11 à 16 17 44](https://github.com/user-attachments/assets/c79d23fd-9d6f-4f42-a128-6b2150bfb2c1)|
| Phone - Chrome   |               |![Capture d’écran 2024-12-11 à 16 13 48](https://github.com/user-attachments/assets/2b9f0e01-3884-4d0c-8fd2-bda19efb3075)| …

(PC-33547) fix(OfferTile): fix spacing 

---

.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.gitignore
doc/installation/iOS.md
ios/PassCulture.xcodeproj/project.pbxproj
ios/PassCulture/Firebase/README.md

(BSR) feat(firebase): set env dynamic firebase ios config files 

---

src/features/home/components/modules/OffersModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browsePC-33342
I have:
<details> …

(PC-33342) fix(hybridPlaylist): fix offers listed in tracker

---

src/features/offer/components/OfferImageCarousel/OfferImageCarousel.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33457
I have:
https://github.com/user-attachments/assets/01363dd5-81a8-45a8-8626-e53ec8f0f205
<details>
- In the production code: remove …

(PC-33457) fix(offer): carousel boundings on web

---

.maestro/tests/AccessSignupFromBlock.yml
.maestro/tests/SignupAndActivation.yml
.maestro/tests/subFolder/auth/AgeStepInfoLoss.yml
.maestro/tests/subFolder/auth/PasswordStepInfoLoss.yml
.maestro/tests/subFolder/home/AccessOfferFromCarousel.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33606
I have:

(PC-33606) feat(e2e): create InfoLoss and carousel offer test case

---

__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButtonList.tsx

I have:
| Desktop - Chrome |<video src="https://github.com/user-attachments/assets/195f8fb7-268a-47bb-8551-b15dddc2e305" /> | <video src="https://github.com/user-attachments/assets/21e8e058-05a1-434e-b95d-a7e87beabcc6" /> |
| Android          | <img width="281" alt="Capture d’écran 2024-12-13 à 12 25 38" src="https://github.com/user-attachments/assets/fcb992be-456f-4bb4-9417-492efdf28afd" /> | <img width="322" alt="Capture d’écran 2024-12-13 à 12 25 07" src="https://github.com/user-attachments/assets/bfed216e-0cca …

(BSR) fix(ThematicSearh): simplify code to fix carousel rendering issues

---

src/features/home/api/useActivationBanner.native.test.ts
src/features/home/api/useActivationBanner.ts
src/features/home/api/useBanner.ts
src/features/home/components/modules/banners/HomeBanner.native.test.tsx
src/features/home/components/modules/banners/HomeBanner.tsx
src/features/home/pages/Home.native.test.tsx
src/features/profile/components/Badges/IdentityCheckPendingBadge.tsx
src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.native.test.tsx
src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
src/shared/currency/useGetCurrencyToDisplay.native.test.ts
src/shared/currency/useGetCurrencyToDisplay.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33369
I have:
| Phone - Chrome   |     ![IMG_3931 (1)](https://github.com/user-attachments/assets/b812a726-fc7b-4805-82cd-f1c5361adfc9)          |  ![Capture d’écran 2024-12-16 à 09 46 35](https://github.com/user-attachments/assets/533614ec-c27c-4242-ae3e-ed10d67ac043) ![Capture d’écran 2024-12-16 à 09 46 15](https://github.com/user-attachments/assets/0da9c36f-f63d-4c13-99b8-d14e5c0c1e92) ![Capture d’écran 2024-12-16 à 09 43 …

(PC-33369) feat(NC): Add dynamic title in activation banner

---

scripts/noUncheckedIndexedAccess_snapshot.txt
src/api/gen/api.ts
src/features/search/components/BookCategoriesSection/BookCategoriesSection.tsx
src/features/search/components/CategoriesSection/CategoriesSection.tsx
src/features/search/components/CategoriesSectionItem/CategoriesSectionItem.tsx
src/features/search/components/sections/Category/Category.native.test.tsx
src/features/search/components/sections/Category/Category.tsx
src/features/search/constants.ts
src/features/search/helpers/categoriesHelpers/categoriesHelpers.test.ts
src/features/search/helpers/categoriesHelpers/categoriesHelpers.ts
src/features/search/helpers/categoriesHelpers/mapping-tree.test.ts
src/features/search/helpers/categoriesHelpers/mapping-tree.ts
src/features/search/helpers/categoriesHelpers/mappingFixture.ts
src/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx
src/features/search/pages/modals/CategoriesModal/CategoriesModal.tsx
src/libs/subcategories/fixtures/mappings.ts
src/libs/subcategories/mappings.ts
src/libs/subcategories/useSearchGroupLabel.native.test.ts
src/libs/subcategories/useSearchGroupLabel.ts
src/ui/components/buttons/SubcategoryButton/SubcategoryButton.tsx
src/ui/components/buttons/SubcategoryButton/SubcategoryButtonListWrapper.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33222
I have:
| Phone - Chrome   | <img width="389" alt="image" src="https://github.com/user-attachments/assets/ce3a30f0-e2ca-45c9-aab4-0277aeb60bb0" />  <img width="389" alt="image" src="https://github.com/user-attachments/assets/adf4bc43-1f7d-4b50-9719-095b55a32a27" /> | <img width="389" alt="image" src="https://github.com/user-attachments/assets/6a732127-dd97-4fa2-86c0-013420999be7" /> <img width="389" alt="image" …

(PC-33222) feat(categories): handle native category positions

---

src/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx
src/features/auth/pages/signup/SetBirthday/SetBirthday.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33473
I have:
| iOS              |               |   <img width="432" alt="Capture d’écran 2024-12-17 à 11 16 27" src="https://github.com/user-attachments/assets/531df405-241e-4e83-b3a8-bd5baa1e4583" /> <img width="432" alt="Capture d’écran 2024-12-17 à 11 15 29" src="https://github.com/user-attachments/assets/e157245d-314a-448f-954c-972633affc7b" />  |
[1]: …

(PC-33473) feat(auth): add general public banner in SetBirthday

---

__snapshots__/features/auth/pages/login/Login.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
__snapshots__/features/cookies/pages/CookiesDetails.native.test.tsx.native-snap
__snapshots__/features/favorites/pages/NotConnectedFavorites.native.test.tsx.native-snap
__snapshots__/features/offer/components/SignUpSignInChoiceOfferModal/SignUpSignInChoiceOfferModal.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityActionPlan.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclaration.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityEngagement.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/RecommendedPaths.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ConsentSettings/ConsentSettings.native.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfile/ConfirmDeleteProfile.native.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfile/DeleteProfileAccountNotDeletable.native.test.tsx.native-snap
__snapshots__/features/profile/pages/DeleteProfile/SuspendAccountConfirmationWithoutAuthentication.native.test.tsx.native-snap
__snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Profile.web.test.tsx.web-snap
__snapshots__/features/subscription/NotificationsLoggedOutModal.native.test.tsx.native-snap
__snapshots__/features/trustedDevice/pages/SuspensionChoice.native.test.tsx.native-snap
__snapshots__/features/tutorial/pages/onboarding/OnboardingWelcome.native.test.tsx.native-snap
__snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx.native-snap
__snapshots__/shared/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx.native-snap
src/ui/components/buttons/buttonInsideText/ButtonInsideTextInner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33525
I have:
| iOS              |               |   <img width="394" alt="Capture d’écran 2024-12-17 à 18 20 57" src="https://github.com/user-attachments/assets/5b8fa4c5-454a-41bf-b760-47b6e28373e9" />  |
| Desktop - Chrome |               |  <img width="501" alt="Capture d’écran 2024-12-17 à 18 20 24" src="https://github.com/user-attachments/assets/6e4c9897-5e35-4c3c-99fc-0fc40373955e" />    |
[1]: …

(PC-33525) feat(profile): fix icon position in ButtonInsideTextInner

---

.maestro/tests/FirstLaunch.yml
.maestro/tests/subFolder/auth/LoginFromProfileForBeneficiaryUser.yml
.maestro/tests/subFolder/profil/CheckCreditAmount.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33647
I have:

(PC-33647) feat(e2e): create test case for credit amount

---

src/features/search/api/useSearchResults/useSearchResults.ts
src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.test.ts
src/libs/algolia/fetchAlgolia/fetchSearchResults/fetchSearchResults.ts
src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
src/libs/firebase/remoteConfig/remoteConfig.constants.ts
src/libs/firebase/remoteConfig/remoteConfig.types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33441
I have:
| Platform         | FB config | Result |
| Desktop - Chrome |<img width="1166" alt="Capture d’écran 2024-12-17 à 18 02 28" src="https://github.com/user-attachments/assets/3fcea2f3-b32d-49c8-829e-7301227966f9" />|<img width="1512" alt="Capture d’écran 2024-12-17 à 18 01 25" src="https://github.com/user-attachments/assets/dcff51bf-f89c-4b10-b377-347a6a53b19e" />|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10 …

(PC-33441) feat(search): set around precision ab test

---

.maestro/tests/subFolder/favorite/VerifyFavScreen.yml

(BSR) refactor(e2e): clear fav list when offers are still present

---

src/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx

Run example that fails: https://github.com/pass-culture/pass-culture-app-native/actions/runs/12395952811/job/34603172443?pr=7399

(BSR) fix(test): flaky test change email

---

src/features/navigation/RootNavigator/linking/getStateFromPath.ts
src/libs/firebase/analytics/useInit.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33002

(PC-33002) chore(eventMonitoring): removed logs on old marketing campaigns

---

sonar-project.properties

Context: https://passcultureteam.slack.com/archives/C01C85B6DHA/p1734705631325539

(BSR) fix(sonar): added src/index.html to exclusions

---

src/features/venue/components/VenueOffers/VenueOffersList.tsx
src/ui/components/Avatar/AvatarListItem.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33681
I have:
iOS
Android 
Web 
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at …

(PC-33681) fix(avatarList): item shadow

---

src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx
src/features/venue/components/VenueOffers/VenueOffersList.tsx
src/libs/analytics/logEventAnalytics.ts
src/ui/components/Avatar/AvatarList.native.test.tsx
src/ui/components/Avatar/AvatarList.tsx
src/ui/components/Avatar/AvatarListItem.native.test.tsx
src/ui/components/Avatar/AvatarListItem.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33634
I have:
<details> …

(PC-33634) feat(venue): trigger ConsultArtist log when pressing artist in venue artists playlist

---

src/cheatcodes/components/CheatMenuButton.tsx
src/cheatcodes/components/LinkToComponent.tsx
src/cheatcodes/components/LinkToScreen.tsx
src/cheatcodes/pages/CheatcodesMenu.tsx
src/cheatcodes/pages/features/achievements/CheatcodesNavigationAchievements.tsx
src/cheatcodes/pages/features/bookOffer/CheatcodesNavigationBookOffer.tsx
src/cheatcodes/pages/features/culturalSurvey/CheatcodesNavigationCulturalSurvey.tsx
src/cheatcodes/pages/features/home/CheatcodesNavigationHome.tsx
src/cheatcodes/pages/features/identityCheck/CheatcodesNavigationIdentityCheck.tsx
src/cheatcodes/pages/features/identityCheck/CheatcodesNavigationNewIdentificationFlow.tsx
src/cheatcodes/pages/features/internal/CheatcodesNavigationInternal.tsx
src/cheatcodes/pages/features/other/CheatcodesNavigationAccountManagement.tsx
src/cheatcodes/pages/features/other/CheatcodesNavigationErrors.tsx
src/cheatcodes/pages/features/other/CheatcodesNavigationNotScreensPages.tsx
src/cheatcodes/pages/features/other/CheatcodesNavigationSignUp.tsx
src/cheatcodes/pages/features/other/CheatcodesScreenDebugInformations.native.test.tsx
src/cheatcodes/pages/features/other/CheatcodesScreenDebugInformations.tsx
src/cheatcodes/pages/features/profile/CheatcodesNavigationProfile.tsx
src/cheatcodes/pages/features/share/CheatcodesNavigationShare.tsx
src/cheatcodes/pages/features/subscription/CheatcodesNavigationSubscription.tsx
src/cheatcodes/pages/features/trustedDevice/CheatcodesNavigationTrustedDevice.tsx
src/cheatcodes/pages/features/tutorial/CheatcodesNavigationOnboarding.tsx
src/cheatcodes/pages/features/tutorial/CheatcodesNavigationProfileTutorial.tsx
src/cheatcodes/pages/features/tutorial/CheatcodesNavigationTutorial.tsx
src/features/navigation/CheatcodesStackNavigator/CheatcodesStackNavigator.tsx
src/features/navigation/CheatcodesStackNavigator/types.ts
src/features/navigation/RootNavigator/RootNavigator.tsx
src/features/navigation/RootNavigator/routes.ts
src/features/navigation/RootNavigator/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33523
If I had to re-run tests in the CI due to flakiness, I add the incident on Notion
I have:

(PC-33523) feat(cheatcode): add cheatcodes stack navigation

---

src/cheatcodes/hooks/useFeatureFlagAll.ts
src/cheatcodes/pages/CheatcodesMenu.tsx
src/cheatcodes/pages/features/other/CheatcodesScreenFeatureFlags.tsx
src/cheatcodes/pages/features/other/CheatcodesScreenRemoteConfig.tsx
src/features/navigation/CheatcodesStackNavigator/CheatcodesStackNavigator.tsx
src/features/navigation/CheatcodesStackNavigator/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33689
I have:
| Desktop - Chrome |               |   ![Capture d’écran 2024-12-31 à 15 21 43](https://github.com/user-attachments/assets/aa0151fd-f66e-4046-ad8e-93b8fdab134d) ![Capture d’écran 2024-12-31 à 15 21 06](https://github.com/user-attachments/assets/bc27b02e-5b18-4878-8b6a-318c0fbcaf23)   |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a …

(PC-33689) feat(cheatcode): add CheatcodesScreenFeatureFlags in cheatcodes

---

src/cheatcodes/pages/CheatcodesMenu.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33756
I have:
| Desktop - Chrome |               |    ![Capture d’écran 2025-01-02 à 14 49 28](https://github.com/user-attachments/assets/f4db5ab5-7daa-458b-b354-549606742a2c) ![Capture d’écran 2025-01-02 à 14 49 16](https://github.com/user-attachments/assets/a0e868fc-7684-4ff7-b7e6-0752595040b2)  |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a …

(PC-33756) feat(cheatcode): add input search in CheatcodesMenu

---

src/features/search/context/reducer.ts
src/features/search/helpers/getStringifySearchStateWithoutLocation/getStringifySearchStateWithoutLocation.native.test.ts
src/features/search/helpers/useShowResultsForCategory/useShowResultsForCategory.native.test.ts
src/features/search/pages/SearchFilter/SearchFilter.native.test.tsx
src/features/search/pages/SearchFilter/SearchFilter.tsx
src/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx
src/features/search/pages/modals/PriceModal/PriceModal.tsx
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.native.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33745
I have:

(PC-33745) feat(NC): add reset and dispatch PriceModal value when currency change

---

src/features/home/components/modules/RecommendationModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33748
I have:
| Desktop - Chrome |<img width="1512" alt="Capture d’écran 2025-01-06 à 10 51 10" src="https://github.com/user-attachments/assets/db4f7ff3-d1df-4c3f-94bd-5dd6dd46e43b" />|<img width="1512" alt="Capture d’écran 2025-01-06 à 10 50 43" src="https://github.com/user-attachments/assets/972c815a-6b63-457b-a738-684b090ffbbe" />|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v …

(PC-33748) fix(recoModule): add homeEntryId param

---

src/features/offer/components/OfferBody/OfferBody.native.test.tsx
src/features/offer/components/OfferBody/OfferBody.tsx
src/features/offer/helpers/constants.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33695
Suppression de la fakedoor de la page artist sur l'offre
I have:
<details>
- In the production code: remove type assertions with …

(PC-33695) refactor(offer): delete artist fakedoor

---

server/.yarnrc.yml

(BSR) fix(proxy): add nodeLinker option

---

src/features/navigation/RootNavigator/RootNavigator.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33524
I have:
| Desktop - Chrome |               |   <img width="601" alt="Capture d’écran 2025-01-08 à 09 59 39" src="https://github.com/user-attachments/assets/f3b02fad-1183-46d5-8778-325588d46097" /> |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb? …

(PC-33524) feat(cheatcodes): create dedicated stack for CheatcodesNavigationStack

---

.envrc
devbox.json
doc/installation/Android.md
scripts/add_certificate_to_ios_simulator.sh
scripts/ensure_nix_use_certificate.sh
scripts/install_certificate_java.sh
scripts/is_proxy_enabled.sh
scripts/load_certificate.sh
scripts/start_android_emulator_with_certificate.sh

(BSR) docs(android): improve setup for Android

---

src/ui/components/touchableLink/InternalTouchableLink.tsx

I have:
| Desktop - Chrome |               |  <img width="793" alt="Capture d’écran 2025-01-09 à 13 37 52" src="https://github.com/user-attachments/assets/cb1e4e9a-6b87-4d67-8d31-619a8428bdc7" />   |

(BSR) feat(navigator): fix path in tabNavigator

---

src/features/home/components/modules/HomeModule.native.test.tsx
src/features/home/components/modules/TrendsModule.native.test.tsx
src/features/home/components/modules/TrendsModule.tsx
src/features/home/components/modules/TrendsModule.web.test.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33782
I have:
| iOS              |               | <img width="386" alt="Capture d’écran 2025-01-13 à 14 26 42" src="https://github.com/user-attachments/assets/b2d97c13-d721-4489-b206-cd2fb3ae4bdd" />   <img width="392" alt="Capture d’écran 2025-01-13 à 14 28 01" src="https://github.com/user-attachments/assets/50e7d71a-5274-4641-977a-cf406d3273ac" /> |
[1]: …

(PC-33782) feat(V2): remove wipAppV2CircleNavButtons feature flags

---

src/shared/offer/usePrePopulateOffer.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33904
I have:
<details> …

(PC-33904) fix(offer): avoid reaction count reset when component re-render

---

__snapshots__/features/tutorial/pages/onboarding/OnboardingWelcome.native.test.tsx.native-snap
src/features/home/components/banners/SignupBanner.native.test.tsx
src/features/home/components/banners/SignupBanner.tsx
src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.native.test.tsx
src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.tsx
src/features/tutorial/pages/onboarding/OnboardingWelcome.native.test.tsx
src/features/tutorial/pages/onboarding/OnboardingWelcome.tsx
src/libs/firebase/firestore/types.ts
src/shared/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx
src/shared/offer/components/AuthenticationModal/AuthenticationModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33962
I have:
| iOS              |               |  ![Capture d’écran 2025-01-15 à 12 17 15](https://github.com/user-attachments/assets/b51e3e6b-37d8-45c7-82cf-1537a1644dcd)  |
| Desktop - Chrome |               |  ![Capture d’écran 2025-01-15 à 12 21 06](https://github.com/user-attachments/assets/83d7abcf-2c8a-4a01-a09a-4ea154e266cc) ![Capture d’écran 2025-01-15 à 12 20 …

(PC-33962) feat(credtiV3): add enableCreditV3 and use it in home banner and profile

---

__snapshots__/features/tutorial/pages/onboarding/OnboardingAgeInformation.native.test.tsx.native-snap
__snapshots__/features/tutorial/pages/profileTutorial/ProfileTutorialAgeInformation.native.test.tsx.native-snap
src/features/tutorial/components/CreditTimeline.tsx
src/features/tutorial/components/onboarding/OnboardingTimeline.native.test.tsx
src/features/tutorial/components/onboarding/OnboardingTimeline.tsx
src/features/tutorial/pages/onboarding/OnboardingAgeInformation.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33955
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33956
I have:
| iOS              |               |   ![Capture d’écran 2025-01-16 à 15 08 45](https://github.com/user-attachments/assets/33020545-6ade-45a1-b199-a314abaf7fc9) ![Capture d’écran 2025-01-16 à 15 08 34](https://github.com/user-attachments/assets/c2af3b89-d24a-4bfb-ae78-e6261e671e46)  |
[1]: …

(PC-33955) feat(creditV3): update onboarding timeline for 17 and 18 years old (PC-33956)

---

src/features/auth/helpers/useLogoutRoutine.native.test.ts
src/features/auth/helpers/useLogoutRoutine.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33897
I have:

(PC-33897) feat(batch): remove batch attributes when logged out

---

__snapshots__/features/tutorial/pages/onboarding/OnboardingAgeInformation.native.test.tsx.native-snap
src/features/home/components/banners/SignupBanner.native.test.tsx
src/features/home/components/banners/SignupBanner.tsx
src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.native.test.tsx
src/features/profile/components/Header/LoggedOutHeader/LoggedOutHeader.tsx
src/features/tutorial/components/onboarding/OnboardingTimeline.native.test.tsx
src/features/tutorial/components/onboarding/OnboardingTimeline.tsx
src/features/tutorial/pages/AgeSelectionFork.native.test.tsx
src/features/tutorial/pages/AgeSelectionFork.tsx
src/features/tutorial/pages/AgeSelectionFork.web.test.tsx
src/features/tutorial/pages/NonEligibleModal.native.test.tsx
src/features/tutorial/pages/NonEligibleModal.tsx
src/features/tutorial/pages/onboarding/OnboardingAgeInformation.native.test.tsx
src/features/tutorial/pages/onboarding/OnboardingWelcome.native.test.tsx
src/features/tutorial/pages/onboarding/OnboardingWelcome.tsx
src/libs/firebase/firestore/types.ts
src/shared/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx
src/shared/offer/components/AuthenticationModal/AuthenticationModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34008
I have:
<details> …

(PC-34008) feat(CreditV3): replace firebase FF by backend FF for enableCreditV3

---

ios/PassCulture/AppDelegate.mm

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34095
I have:
| iOS              |               |  <img width="362" alt="Capture d’écran 2025-01-21 à 11 04 54" src="https://github.com/user-attachments/assets/b2e08e17-bd0f-4523-ad36-f6672abfa8b3" />   | …

(PC-34095) feat(batch): fix update SDK

---

src/features/home/api/useGetVenuesData.ts
src/features/home/types.ts
src/libs/algolia/fetchAlgolia/fetchVenuesModule.test.tsx
src/libs/algolia/fetchAlgolia/fetchVenuesModules.ts
src/libs/algolia/fetchAlgolia/helpers/buildVenuesModulesQueries.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33984
I have:
Pour une playlist géolocalisée avec un rayon de 100km : 
| Autour de moi (Paris)             |<img width="540" alt="Capture d’écran 2025-01-21 à 13 45 25" src="https://github.com/user-attachments/assets/3763a64a-e39a-44cb-a614-1ecdedca8033" />|<img width="540" alt="Capture d’écran 2025-01-21 à 13 45 37" src="https://github.com/user-attachments/assets/afc330bc-9aa2-4308-921b-292e152cd1cf" />|
| Fort de France          |<img width="540" alt="Capture d’écran 2025-01-21 à 13 48 24" …

(PC-33984) fix(venuesModule): use location venue module params

---

__snapshots__/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx.native-snap
src/features/birthdayNotifications/pages/RecreditBirthdayNotification.native.test.tsx
src/features/birthdayNotifications/pages/RecreditBirthdayNotification.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.native.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34084
I have:
| iOS              |  ![Simulator Screenshot - iPhone 15 - 2025-01-21 at 15 55 17](https://github.com/user-attachments/assets/e1ab0df5-ea49-4e45-a206-d89eb086e068)     |    ![Simulator Screenshot - iPhone 15 - 2025-01-21 at 15 54 31](https://github.com/user-attachments/assets/3a73457b-b9cb-4d46-801f-66817f50831b)  |
[1]: …

(PC-34084) feat(creditV3): Change BeneficiaryAccountCreated text

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33785
I have:
<details> …

(PC-33785) feat(FF): remove wipNewExclusivityModule

---

src/api/gen/api.ts
src/features/auth/fixtures/fixtures.ts
src/features/profile/components/CitySearchInput/CitySearchInput.native.test.tsx
src/features/profile/components/CitySearchInput/CitySearchInput.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33355
I have:
<details> …

(PC-33355) refactor(CitySearchInput): use backend ineligiblePostalCodes

---

__snapshots__/features/tutorial/pages/onboarding/OnboardingWelcome.native.test.tsx.native-snap
src/features/tutorial/pages/onboarding/OnboardingWelcome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34100
I have:
<details>
- In the production code: remove type assertions with `as` (type …

(PC-34100) fix(OnboardingWelcome): delete white space

---

src/features/home/components/modules/ThematicHighlightModule.native.test.tsx
src/features/home/components/modules/ThematicHighlightModule.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33784
I have:
<details> …

(PC-33784) feat(FF): remove wipNewHighlightThematicModule

---

src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.native.test.tsx
src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.tsx
src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.web.test.tsx
src/features/forceUpdate/helpers/useShowForceUpdateWhenDisableActivation.native.test.ts
src/features/forceUpdate/helpers/useShowForceUpdateWhenDisableActivation.ts
src/features/identityCheck/pages/Stepper.native.test.tsx
src/features/identityCheck/pages/Stepper.tsx
src/features/identityCheck/pages/Stepper.web.test.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34157
I have:
| iOS              |               |  https://github.com/user-attachments/assets/7107e17c-97fc-468d-b93d-916ffb2a3182 https://github.com/user-attachments/assets/c2364d8d-a3e7-4e4e-b2c2-0c3a8927dc96 |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e148 …

(PC-34157) feat(creditV3): use useShowForceUpdateWhenDisableActivation in VerifyEligibility and Stepper

---

src/features/cookies/helpers/useIsCookiesListUpToDate.native.test.ts
src/features/cookies/helpers/useIsCookiesListUpToDate.ts
src/features/home/pages/Home.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34054
I have:
<details> …

(PC-34054) fix(cookies): revert usage of query for cookies up to date

---

.github/workflows/dev_on_schedule_run_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_run_e2e_android.yml

Le cron est passé mais n'a pas trouvé le fichier à appeler car j'ai manqué le changement de naming dans le dit fichier
Le cron est passé à 23h au lieu de minuit, donc l'heure a été réajustée

(BSR) fix(Ci): adjust UTC schedule time + fix cron not called

---

vite.config.js

(BSR) fix(vite): remove sentry auth token warning

---

.maestro/tests/subFolder/profil/AccessibilitySection.yml
__snapshots__/features/profile/pages/Accessibility/Accessibility.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobile.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/RecommendedPaths.native.test.tsx.native-snap
src/features/navigation/RootNavigator/accessibilityRoutes.ts
src/features/navigation/RootNavigator/types.ts
src/features/profile/pages/Accessibility/Accessibility.native.test.tsx
src/features/profile/pages/Accessibility/Accessibility.tsx
src/features/profile/pages/Accessibility/AccessibilityDeclarationMobile.native.test.tsx
src/features/profile/pages/Accessibility/AccessibilityDeclarationMobile.tsx
src/features/profile/pages/Accessibility/AccessibilityDeclarationMobile.web.test.tsx
src/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.native.test.tsx
src/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.tsx
src/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.web.test.tsx
src/features/profile/pages/Accessibility/RecommendedPaths.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34331
I have:
| iOS              |               |   ![Capture d’écran 2025-01-30 à 16 38 49](https://github.com/user-attachments/assets/06fe7b1d-f43c-4ee5-97c2-caf1a0e2052e)  ![simulator_screenshot_B4785C68-A6F5-4A2E-96C6-3F7137D9A6B0](https://github.com/user-attachments/assets/ceedfa36-8ed6-417a-ae8b-67177146f65e) |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-le …

(PC-34331) feat(a11y): Add AccessibilityDeclarationMobile

---

src/features/gtlPlaylist/api/fetchGTLPlaylistConfig.ts
src/features/search/pages/ThematicSearch/ThematicSearch.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-31482
I have:
| Desktop - Chrome | <img width="622" alt="Capture d’écran 2025-01-30 à 10 59 42" src="https://github.com/user-attachments/assets/2c65be3b-d3eb-4bbf-8c96-7ac446b1d595" /> | <img width="728" alt="Capture d’écran 2025-01-30 à 10 58 31" src="https://github.com/user-attachments/assets/b98d7fa1-9075-4886-96ae-7f415751a442" /> | …

(PC-31482) feat(GtlPlaylist): allow categories filtering

---

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
src/ui/components/ModuleBanner/BannerWithBackground.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34291
I have:
| iOS              |    ![Simulator Screenshot - iPhone 15 Pro Max - 2025-01-31 at 13 26 46](https://github.com/user-attachments/assets/34f1380a-5268-4e94-92c4-fc351192f4da)   |   ![Simulator Screenshot - iPhone 15 Pro Max - 2025-01-31 at 13 24 52](https://github.com/user-attachments/assets/e5a0c312-faa1-41b3-b9cd-7f614a56974b)   |
[1]: …

(PC-34291) feat(ui): remove border in BannerWithBackground

---

src/cheatcodes/components/CheatcodesButtonList.tsx
src/cheatcodes/components/CheatcodesSubscreenButtonList.tsx
src/cheatcodes/pages/CheatcodesMenu.tsx
src/cheatcodes/pages/features/achievements/CheatcodesNavigationAchievements.tsx
src/cheatcodes/pages/features/forceUpdate/cheatcodesNavigationForceUpdate.tsx
src/cheatcodes/pages/features/identityCheck/CheatcodesNavigationIdentityCheck.tsx
src/cheatcodes/pages/features/profile/CheatcodesNavigationProfile.tsx
src/cheatcodes/pages/features/subscription/CheatcodesNavigationSubscription.tsx
src/cheatcodes/pages/features/trustedDevice/CheatcodesNavigationTrustedDevice.tsx
src/cheatcodes/pages/others/CheatcodesNavigationErrors.tsx
src/cheatcodes/pages/others/CheatcodesNavigationSignUp.tsx
src/cheatcodes/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33858
I have:
| Desktop - Chrome |               |   ![Capture d’écran 2025-01-31 à 19 39 42](https://github.com/user-attachments/assets/bae5e9bd-4130-47cc-8f2e-9772220a43e3) ![Capture d’écran 2025-01-31 à 19 39 27](https://github.com/user-attachments/assets/abe33c4c-2a3b-47e6-be95-0207a11e7307) |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a75 …

(PC-33858) feat(cheatcodes): add all buttons in cheatcodes search

---

src/features/venueMap/components/VenueMapTypeFilter/VenueMapTypeFilter.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34128
I have:
https://github.com/user-attachments/assets/faedea1c-ff63-4e54-b7de-eafdeb9b92a6
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be an exception or `null` generated if the type assertion is wrong). In certain …

(PC-34128) fix(VenueMapTypeFilter): fix label offset

---

src/features/home/api/useScreenSeenCount.native.test.ts
src/features/home/pages/GenericHome.native.test.tsx
src/features/home/pages/GenericHome.tsx
src/libs/react-native-batch/enums.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34183
Sentry : https://sentry.passculture.team/organizations/sentry/issues/1627027/?project=6&referrer=jira_integration
I have:

(PC-34183) feat(batch): try to fix sentry issue

---

.maestro/tests/SearchAndBookCinemaOffer.yml
.maestro/tests/SearchAndBookDuoOffer.yml
.maestro/tests/UserNotConnectedMode.yml
.maestro/tests/subFolder/auth/LogoutFromProfile.yml
.maestro/tests/subFolder/booking/BookDuoOffer.yml
.maestro/tests/subFolder/home/AccessOfferFromCarousel.yml
.maestro/tests/subFolder/profil/AccessibilitySection.yml
.maestro/tests/subFolder/search/SearchBookableCinemaOffer.yml
.maestro/tests/subFolder/venue/AccessVenueMapFromHome.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-32889
I have:

(PC-32889) fix(e2e): migrate Maestro tests from RhinoJs to GraalJs + maintenance for v1.325.0

---

src/features/navigation/RootNavigator/types.ts
src/features/navigation/screenParamsUtils.ts
src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/features/offer/components/OfferContent/OfferContentBase.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34316
I have:
<details> …

(PC-34316) feat(chronicle): add from route params for clickBookOffer log

---

jest/jest.setup.ts
src/features/share/pages/WebShareModal.web.test.tsx
src/features/venue/pages/Venue/Venue.web.test.tsx

(BSR) fix(tests): hide "memo received undefined" warning

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/features/venue/components/VenueBody/VenueBody.tsx
src/features/venue/pages/Venue/Venue.native.test.tsx
src/features/venue/pages/Venue/Venue.tsx
src/libs/firebase/firestore/types.ts

Ajout d'un FF pour la partie offre à la une
I have:
<details>
- In the production code: remove type assertions with `as` (type …

(BSR) fix(Venue): add FF for headline offer feature

---

src/features/auth/pages/signup/AccountCreated/AccountCreated.native.test.tsx
src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.native.test.tsx
src/features/auth/pages/signup/VerifyEligiblity/VerifyEligibility.tsx
src/libs/react-native-batch/enums.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34470
I have:

(PC-34470) feat(auth): add trigger batch in VerifyEligibility

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34372
I have:
<details> …

(PC-34372) feat(BookingPage): add FF

---

README.md

(BSR) docs(README): Replace logo in README

---

src/features/forceUpdate/helpers/onPressStoreLink.ts
src/features/forceUpdate/helpers/onPressStoreLink.web.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34565
I have:

(PC-34565) feat(forceUpdate): add clear storage in onPressStoreLink

---

src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/offerAttributesToRetrieve.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34199
I have:
<details>
If you …

(PC-34199) feat(comingSoon): add publicationDate to attribute to retrieve

---

src/features/profile/components/EmptyCredit/EmptyCredit.native.test.tsx
src/features/profile/components/EmptyCredit/EmptyCredit.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34550
I have:
| iOS              |               | ![image](https://github.com/user-attachments/assets/da8de6c4-10a0-4c02-b690-8e8710cffee7) (pour bénéficiare de 15 ans ayant dépensé son crédit) |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe4725 …

(PC-34550) feat(creditV3): Show credit at 17 for 15+16 yo users with 0€

---

src/features/home/types.ts
src/features/venue/api/useVenueOffers.test.ts
src/features/venue/api/useVenueOffers.ts
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/fetchMultipleOffers.test.ts
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/fetchMultipleOffers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34574
I have:
<details> …

(PC-34574) feat(venue): specify Algolia index name in each queries of useVenueOffers hook

---

src/ui/storybook/Animations.stories.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34599
I have:
| Desktop - Chrome |               |   <img width="1728" alt="Capture d’écran 2025-02-13 à 17 54 28" src="https://github.com/user-attachments/assets/9a985819-0aa0-4844-b310-004c10735c5b" /> | …

(PC-34599) feat(storybook): add Animations

---

src/cheatcodes/pages/others/CheatcodesScreenRemoteConfig.tsx
src/features/accessibility/components/AccessibilityFiltersModal.tsx
src/features/bookOffer/components/Calendar/useMarkedDates.ts
src/features/cookies/helpers/useCookies.ts
src/features/home/helpers/selectHomepageEntry.native.test.ts
src/features/home/helpers/selectHomepageEntry.ts
src/features/identityCheck/pages/profile/SetAddress.tsx
src/features/internal/components/DeeplinksGeneratorForm.tsx
src/features/navigation/sanitizeNavigationState.ts
src/features/profile/components/CitySearchInput/CitySearchInput.tsx
src/features/search/components/SearchBox/SearchBox.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/search/helpers/availableCategories/availableCategories.test.ts
src/features/search/helpers/availableCategories/availableCategories.ts
src/features/search/helpers/useSync/useSync.ts
src/features/search/pages/SuggestedPlacesOrVenues/SuggestedPlaces.tsx
src/features/venue/api/useVenueOffers.ts
src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.test.ts
src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.ts
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.native.test.ts
src/libs/contentful/adapters/adaptHomepageModules.ts
src/shared/date/days.ts
src/shared/date/getDatesInMonth.ts
src/shared/date/getPastYears.ts
src/shared/date/getYears.ts

BEFORE:
AFTER:
Not a hug optimization, but a POC for further optimizations

(BSR) refactor(web): reduced size of lodash in bundle

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/headlineOffer/components/HeadlineOffer/HeadlineOffer.stories.tsx
src/features/headlineOffer/components/HeadlineOffer/HeadlineOffer.tsx
src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/features/venue/components/VenueBody/VenueBody.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34598
I have:
https://github.com/user-attachments/assets/5d37c769-271c-4b9e-9e1b-5cf6cc8fbe01
https://github.com/user-attachments/assets/6cdc1bb5-d202-4504-b29e-c86a7d6c2bb0
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t …

(PC-34598) feat(HeadlineOffer): add the possibility to click on headline offer

---

__snapshots__/features/profile/pages/Profile.web.test.tsx.web-snap
src/features/profile/pages/Profile.tsx

(BSR) feat(web): add commit hash to profile

---

src/features/home/api/helpers/mapOffersDataAndModules.ts
src/features/home/api/useAlgoliaRecommendedOffers.native.test.ts
src/features/home/api/useVideoCarouselData.ts
src/features/offer/api/useAlgoliaSimilarOffers.native.test.ts
src/features/offer/api/useAlgoliaSimilarOffers.ts
src/features/search/pages/ThematicSearch/api/useThematicSearchPlaylists.ts
src/features/venue/api/useVenueOffers.test.ts
src/features/venue/api/useVenueOffers.ts
src/features/venueMap/components/VenueMapView/VenueMapView.tsx
src/libs/algolia/fetchAlgolia/transformOfferHit.test.ts
src/libs/algolia/fetchAlgolia/transformOfferHit.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34573
I have:
| iOS              |               |![Capture d’écran 2025-02-13 à 17 14 13](https://github.com/user-attachments/assets/8c2dfd73-d882-4247-92f9-c01db9b5499c)| …

(PC-34573) feat(venueMap): display in bottom sheet playlist offers without image

---

.github/workflows/dev_on_schedule_run_e2e_android.yml

(BSR) feat(e2e): update cron schedule to run only Monday to Friday

---

src/features/chronicle/pages/Chronicles/Chronicles.native.test.tsx
src/features/chronicle/pages/Chronicles/Chronicles.tsx
src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
src/features/chronicle/pages/Chronicles/ChroniclesBase.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34411
I have:
| iOS              |![Capture d’écran 2025-02-17 à 16 17 49](https://github.com/user-attachments/assets/1e4456d6-1f15-4ce5-a9b2-00fdf785eaef)|![Capture d’écran 2025-02-17 à 16 18 04](https://github.com/user-attachments/assets/f0a7185d-1c56-4168-acf7-4c481579b8ad)|
| Phone - Chrome   |![Capture d’écran 2025-02-17 à 16 15 28](https://github.com/user-attachments/assets/de7a1651-48a7-4559-a1a3-4223fa7653c2)|<img width="381" alt="Capture d’écran 2025-02-17 à 16 …

(PC-34411) fix(offer): not display booking modal on offer page when navigate to chronicles page and use back button on it

---

.github/workflows/dev_on_workflow_environment_ios_deploy.yml

(BSR) fix(CI): condition firebase token retrieval to env

---

src/features/remoteBanner/components/RemoteBanner.native.test.tsx
src/features/remoteBanner/components/RemoteBanner.tsx
src/features/remoteBanner/components/RemoteBanner.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34485
I have:
| Desktop - Chrome |               |  ![Capture d’écran 2025-02-24 à 12 20 36](https://github.com/user-attachments/assets/a3b70ddc-9ae4-4a7e-b786-45fcf84043c7)   |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25b …

(PC-34485) feat(a11y): update RemoteBanner accessibility

---

src/features/navigation/TabBar/TabNavigationStateContext.tsx
src/ui/components/snackBar/SnackBar.tsx

Link to Sonar : https://sonarcloud.io/project/issues?impactSoftwareQualities=RELIABILITY&issueStatuses=OPEN%2CCONFIRMED&id=pass-culture_pass-culture-app-native
Exemple de "bug" détecté par Sonar : 
```
[React Hook "useAuthContext" is called in function "_TabNavigationStateProvider" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter. React Hook names must start with the word "use".](https://sonarcloud.io/project/issues?open=AZUU23EkFTr8q5-hLVLS&id=pass-culture_pass-culture-app-native)
```
I have:
[2]: …

(BSR) feat(sonar): Fix some bugs

---

.github/PULL_REQUEST_TEMPLATE.md

(BSR) docs(PRtemplate): add null != undefined to best practices

---

.github/workflows/dev_on_schedule_run_e2e_ios.yml
.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_ios.yml
.maestro/tests/subFolder/auth/InputEmail.yml
.maestro/tests/subFolder/auth/LoginAndReactivation.yml
.maestro/tests/subFolder/auth/LoginFromFavorites.yml
.maestro/tests/subFolder/auth/LoginFromModal.yml
.maestro/tests/subFolder/auth/LoginFromProfileForBeneficiaryUser.yml
.maestro/tests/subFolder/auth/LoginWithWrongPassword.yml
.maestro/tests/subFolder/profil/LegalInfoSection.yml
.maestro/tests/subFolder/profil/SocialNetwork.yml
fastlane/.env.staging
fastlane/Fastfile
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34693
I have:

(PC-34693) chore(e2e): add build_e2e ios lane

---

src/features/offer/helpers/useOfferSummaryInfoList/useOfferSummaryInfoList.native.test.tsx
src/features/offer/helpers/useOfferSummaryInfoList/useOfferSummaryInfoList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34541
I have:
| iOS              |               |<img width="419" alt="Capture d’écran 2025-02-26 à 11 56 30" src="https://github.com/user-attachments/assets/ab4dc8d5-ea59-48ce-b14a-dd099aa40e05" />|
| Phone - Chrome   |               |![Capture d’écran 2025-02-26 à 11 56 01](https://github.com/user-attachments/assets/fc2ef2cc-6d93-42cc-bb18-3d3fc84f449b)|
| Desktop - Chrome |               |![Capture d’écran 2025-02-26 à 11 55 …

(PC-34541) feat(SummaryInfoList): add offer address

---

.maestro/tests/subFolder/auth/LogoutFromProfile.yml
.maestro/tests/subFolder/auth/SignupFromProfile.yml
.maestro/tests/subFolder/tutorial/onboarding/Onboard16AndLocalization.yml
.maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34806
I have:

(PC-34806) fix(e2e): handle PassForAll activation on Android run

---

src/features/offer/api/useSimilarOffers.native.test.ts
src/features/offer/api/useSimilarOffers.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34237
I have:
<details> …

(PC-34237) feat(offer): use onlineManager to avoid API call when network disable

---

src/features/venue/api/useVenueOffers.test.ts
src/features/venue/api/useVenueOffers.ts
src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.test.ts
src/features/venue/api/useVenueOffersArtists/useVenueOffersArtists.ts
src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/features/venue/components/VenueOffers/VenueOffers.tsx
src/features/venue/pages/Venue/Venue.native.test.tsx
src/features/venue/pages/Venue/Venue.tsx
src/features/venueMap/components/VenueMapView/VenueMapViewContainer.native.test.tsx
src/features/venueMap/components/VenueMapView/VenueMapViewContainer.tsx
src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx
src/fixtures/venueSearchParams.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-33493
I have:
<details> …

(PC-33493) refactor(venue): remove all hooks in useVenueOffers and use hooks directly on parent components

---

__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
src/cheatcodes/pages/features/remoteBanners/CheatcodesScreenRemoteBanners.tsx
src/features/home/components/banners/SignupBanner.tsx
src/features/home/components/modules/banners/HomeBanner.tsx
src/features/offer/components/VenueSelectionListHeader/VenueSelectionListHeader.native.test.tsx
src/features/profile/components/Badges/SubscriptionMessageBadge.tsx
src/features/profile/components/Header/NonBeneficiaryHeader/NonBeneficiaryHeader.tsx
src/features/remoteBanners/banners/RemoteActivationBanner.native.test.tsx
src/features/remoteBanners/banners/RemoteActivationBanner.tsx
src/features/remoteBanners/banners/RemoteGenericBanner.native.test.tsx
src/features/remoteBanners/banners/RemoteGenericBanner.tsx
src/features/remoteBanners/components/RemoteBanner.native.test.tsx
src/features/remoteBanners/components/RemoteBanner.tsx
src/features/remoteBanners/components/RemoteBanner.web.test.tsx
src/features/remoteBanners/utils/remoteBannerSchema.ts
src/libs/analytics/logEventAnalytics.ts
src/libs/firebase/firestore/types.ts
src/shared/Banners/GeolocationBanner.tsx
src/ui/components/ModuleBanner/SystemBanner.native.test.tsx
src/ui/components/ModuleBanner/SystemBanner.stories.tsx
src/ui/components/ModuleBanner/SystemBanner.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34682
I have:
| iOS              |               |  ![Simulator Screenshot - iPhone 15 - 2025-03-05 at 11 35 22](https://github.com/user-attachments/assets/8b59b341-31ef-4848-9870-d388a5571da6) ![Capture d’écran 2025-03-04 à 17 10 53](https://github.com/user-attachments/assets/8d8a3ca5-1cc0-4e0f-a8cb-6845aca25052)    |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-l …

(PC-34682) feat(ui): Add SystemBanner with background

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34967
I have:
<details> …

(PC-34967) feat(featureFlag): remove wipAppV2SystemBlock FF

---

.github/PULL_REQUEST_TEMPLATE.md

suite de https://github.com/pass-culture/pass-culture-app-native/pull/7752

(BSR) docs(practice): ours request usage

---

__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
src/features/home/components/headers/AnimatedCategoryThematicHomeHeader.native.test.tsx
src/features/home/components/headers/AnimatedCategoryThematicHomeHeader.tsx
src/features/home/components/headers/CategoryThematicHomeHeader.native.test.tsx
src/features/home/components/headers/CategoryThematicHomeHeader.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34968
I have:
| iOS              |![Capture d’écran 2025-03-06 à 12 15 03](https://github.com/user-attachments/assets/5533f817-c4a5-49d1-aaf0-fdffc2a4fcc3)|![Capture d’écran 2025-03-06 à 12 15 40](https://github.com/user-attachments/assets/5e37f3c1-5d46-49cc-b7f6-355a29283728)|
| Desktop - Chrome |<img width="1724" alt="Capture d’écran 2025-03-06 à 12 15 12" src="https://github.com/user-attachments/assets/c1619b74-ba00-4a98-bec1- …

(PC-34968) refactor(home): remove wipAppV2ThematicHomeHeader FF

---

src/features/location/components/LocationSearchWidget.stories.tsx
src/features/profile/components/BeneficiaryCeilings/BeneficiaryCeilings.native.test.tsx
src/features/profile/components/BeneficiaryCeilings/BeneficiaryCeilings.tsx
src/features/profile/components/Header/CreditHeader/CreditHeader.native.test.tsx
src/features/profile/components/Header/CreditHeader/CreditHeader.stories.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
src/features/profile/fixtures/domainsCredit.ts
src/features/profile/helpers/computeCredit.native.test.ts
src/features/profile/pages/Profile.native.test.tsx
src/features/tutorial/components/profileTutorial/EighteenBlockDescription.tsx
src/shared/credits/defaultCreditByAge.ts
src/shared/credits/defaultDigitalCredit.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34660
I have:

(PC-34660) feat(creditV3): remove credit V1

---

__snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
src/features/profile/pages/LegalNotices/LegalNotices.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34887
I have:
| Desktop - Chrome |        |    ![Capture d’écran 2025-03-06 à 18 44 33](https://github.com/user-attachments/assets/c6078271-ac5e-437e-9075-34fad2075c16)   |   
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb0 …

(PC-34887) feat(profile): update LegalNotices informations

---

.envrc
package.json
scripts/remove-unused-hooks.sh
yarn.lock

(BSR) fix(husky): remove husky warning

---

doc/installation/Android.md
doc/installation/reset.md

zulu was usefull when Mac ARM was just released because temurin didn't support Mac ARM at this time
now, temurin supports Mac ARM
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at …

(BSR) docs(java): ensure to use the same java distribution everywhere

---

.maestro/tests/subFolder/booking/BookPhysicalOffer.yml
.maestro/tests/subFolder/favorite/AddToFavorite.yml
.maestro/tests/subFolder/search/SearchOfferFromText.yml
.maestro/tests/subFolder/venue/AccessPreviewModule.yml

(BSR) fix(e2e): replace category with nativeCagetory in search

---

src/features/venue/components/VenueBody/VenueBody.native.test.tsx
src/features/venue/components/VenueBody/VenueBody.tsx
src/libs/analytics/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35002
I have:
<details> …

(PC-35002) feat(venue): trigger ConsultOffer log when pressing headline offer

---

.github/workflows/dev_on_pull_request_run_e2e.yml
.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_ios.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35008
I have:

(PC-35008) chore(e2e): add label-triggered E2E tests for iOS and Android

---

.maestro/tests/subFolder/booking/BookCinemaOffer.yml
.maestro/tests/subFolder/booking/BookDuoOffer.yml
.maestro/tests/subFolder/booking/DaySelectionCinema.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35138
I have:

(PC-35138) refactor(e2e): optimize booking tests to reduce flakiness and complexity

---

__snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
src/features/search/components/SearchHeader/SearchHeader.tsx
src/features/search/pages/SearchLanding/SearchLanding.native.test.tsx
src/features/search/pages/SearchLanding/SearchLanding.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35186
I have:
| iOS |![Simulator Screenshot - iPhone SE (3rd generation) - 2025-03-17 at 11 18 22](https://github.com/user-attachments/assets/06a3699b-668e-485d-ae03-ba66dcb92a05)|![Simulator Screenshot - iPhone SE (3rd generation) - 2025-03-17 at 11 16 57](https://github.com/user-attachments/assets/0565d621-4946-47e7-a281-fcf6823460bb)|
| Desktop - Chrome |![Screenshot 2025-03-17 at 10 27 58](https://github.com/user-attachments/assets/bf0a2298-0ad6-4511-9108-b94ca9981c2e)| ![Screenshot 2025-03-17 at 10 27 …

(PC-35186) feat(SearchLanding): remove gradient in header

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/venue/components/VenueTopComponent/VenueTopComponent.native.test.tsx
src/features/venue/components/VenueTopComponent/VenueTopComponentBase.tsx
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34972
I have:
| iOS              |               |![Capture d’écran 2025-03-19 à 10 00 11](https://github.com/user-attachments/assets/bc5da969-2469-47e6-a83e-9a3b836db294)|
| Desktop - Chrome |               |![Capture d’écran 2025-03-19 à 09 57 21](https://github.com/user-attachments/assets/a7c0802b-fc95-459c-8f44-e9fe08d3ad33)| …

(PC-34972) feat(venue): remove wipEnableDynamicOpeningHours FF

---

.github/workflows/README.md
.github/workflows/dev_on_schedule_lighthouse.yml
package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35196
I have:

(PC-35196) feat(tests): add lighthouse in CI

---

__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/venue/api/useVenueOffers.ts
src/features/venue/components/VenueOffers/VenueOffersList.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35233
Fix sur la playlist des offres relatives à un lieu.
I have:
iOS
Android
Web
<details> …

(PC-35233) fix(venue): Venue offer list

---

.github/workflows/dev_on_workflow_call_e2e_ios.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35292
I have:
<details>
If you …

(PC-35292) build(CI): bump macos runner

---

src/features/offer/components/OfferReactionSection/OfferReactionSection.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35291
I have:
| Phone - Chrome   |![Capture d’écran 2025-03-20 à 17 18 14](https://github.com/user-attachments/assets/cc974034-f6a7-4500-80fa-32a00cf0781b)|![Capture d’écran 2025-03-20 à 17 24 12](https://github.com/user-attachments/assets/af264791-b024-4a2b-ab34-e509ed3b5775)| …

(PC-35291) fix(OffreReactions): gap issue

---

.maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35298
I have:
| iOS              |       ![Capture d’écran 2025-03-21 à 09 49 30](https://github.com/user-attachments/assets/c9e02727-2eed-46f4-bc5b-292877550fda) |  ![Capture d’écran 2025-03-21 à 10 54 52](https://github.com/user-attachments/assets/708574d5-5218-449f-8e15-6da115b473bb)  | …

(PC-35298) fix(e2e): change skip accessiblity label in Onboard18

---

.github/workflows/dev_on_schedule_lighthouse.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35196
https://github.com/pass-culture/pass-culture-app-native/actions/runs/14023393155/job/39258274185
I have:
<details> …

(PC-35196) fix(lighthouse): yarn 3 fix (no more global)

---

src/features/chronicle/components/ChronicleOfferInfo/ChronicleOfferInfo.web.test.tsx
src/features/chronicle/components/ChronicleOfferInfo/ChronicleOfferInfo.web.tsx
src/features/chronicle/pages/Chronicles/Chronicles.web.tsx
src/features/offer/components/OfferBodyImage.tsx
src/features/offer/components/OfferContent/OfferContentBase.tsx
src/features/offer/components/OfferImageCarousel/OfferImageCarousel.native.test.tsx
src/features/offer/components/OfferImageCarousel/OfferImageCarousel.tsx
src/features/offer/components/OfferImageCarousel/OfferImageCarousel.web.test.tsx
src/features/offer/components/OfferImageCarousel/OfferImageCarouselItem.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.native.test.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.web.test.tsx
src/features/offer/components/OfferImageContainer/OfferImageContainer.web.tsx
src/features/offer/components/OfferImageContainer/OfferImageRenderer.tsx
src/features/offer/components/OfferImageWrapper/OfferImageWrapper.native.test.tsx
src/features/offer/components/OfferImageWrapper/OfferImageWrapper.tsx
src/features/offer/components/OfferImageWrapper/OfferImageWrapper.web.test.tsx
src/features/offer/fixtures/offerImageDimensions.ts
src/features/offer/helpers/useOfferImageContainerDimensions.ts
src/features/offer/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35270
I have:
| iOS              |               |<img width="432" alt="Capture d’écran 2025-03-24 à 16 48 11" src="https://github.com/user-attachments/assets/c123ebc2-3922-4d87-a81f-74b03f8cb92c" />|
| Phone - Chrome   |               |<img width="418" alt="Capture d’écran 2025-03-24 à 16 46 00" src="https://github.com/user-attachments/assets/e742c75a-4892-4240-8d7a-8b008ba2c4c4" />|
| Desktop - Chrome |               |<img width="1144" alt="Capture d’écran 2025-03-24 à …

(PC-35270) feat(OfferImage): Adapt offer image for CD or Vinyl offers to square

---

__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
src/features/offer/components/OfferTile/OfferTile.stories.tsx
src/features/offer/components/OfferTile/OfferTile.tsx
src/features/offer/components/OfferTile/PlaylistCardOffer.native.test.tsx
src/features/offer/components/OfferTile/PlaylistCardOffer.tsx
src/features/offer/types.ts
src/ui/components/Tag/Tag.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35336
Ajout d'un Tag dans la tuile offre qui donne une information sur le nombre de likes.
I have:
iOS
Storybook 
<details>
- In the …

(PC-35336) feat(OfferTile): add likes tag

---

__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
src/features/gtlPlaylist/components/GtlPlaylist.tsx
src/features/offer/components/OfferTile/OfferTile.tsx
src/features/search/components/VenuePlaylist/VenuePlaylist.tsx
src/features/search/pages/ThematicSearch/Book/BookPlaylists.tsx
src/features/search/pages/ThematicSearch/ThematicSearch.tsx
src/features/search/pages/ThematicSearch/ThematicSearchPlaylist.tsx
src/features/search/pages/ThematicSearch/ThematicSearchPlaylistList.tsx
src/ui/components/PassPlaylist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35281
I have:
| Desktop - Chrome | ![Screenshot 2025-03-24 at 11 10 07](https://github.com/user-attachments/assets/7cebbd7e-979f-4e6b-a5d4-6dbead4a78cd)|![Screenshot 2025-03-24 at 10 24 06](https://github.com/user-attachments/assets/a99db564-6816-42c9-93fa-946583c93e71)|
<details> …

(PC-35281) feat(ThematicSearch): harmonize spaces between playlists

---

__snapshots__/features/location/components/HomeLocationModal.native.test.tsx.native-snap
__snapshots__/features/location/components/SearchLocationModal.native.test.tsx.native-snap
__snapshots__/features/profile/pages/ChangeEmail/ChangeEmail.native.test.tsx.native-snap
jest.config.js
jest.web.config.js
package.json
src/features/auth/pages/login/Login.tsx
src/features/location/components/LocationModal.tsx
src/shared/illustrations/getPrimaryIllustration.tsx
src/ui/components/buttons/ButtonPrimary.ts
src/ui/components/buttons/ButtonSecondary.ts
src/ui/components/snackBar/SnackBarContext.tsx
src/ui/components/snackBar/mapSnackBarTypeToStyle.tsx
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35256
I have:
<details>
If you …

(PC-35256) refactor(DS): missing design tokens and correct wording

---

.maestro/tests/subFolder/profil/LegalInfoSection.yml
__snapshots__/features/profile/pages/LegalNotices/LegalNotices.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Profile.web.test.tsx.web-snap
src/features/profile/pages/LegalNotices/LegalNotices.tsx
src/shared/AccessibilityFooter/AccessibilityFooter.tsx
src/shared/AccessibilityFooter/AccessibilityFooter.web.test.tsx

I have:
| Desktop - Chrome |               |  ![Capture d’écran 2025-03-31 à 13 51 16](https://github.com/user-attachments/assets/a06ac99d-2396-4b12-b5ba-38613a482ac4)  |

(BSR) feat(ui): update design in LegalNotices screen

---

.maestro/tests/subFolder/auth/AgeStepInfoLoss.yml
.maestro/tests/subFolder/auth/SignupFromProfile.yml
__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/SetBirthday/SetBirthday.web.test.tsx.web-snap
__snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
src/features/auth/pages/signup/SetBirthday/SetBirthday.native.test.tsx
src/features/auth/pages/signup/SetBirthday/SetBirthday.tsx
src/features/auth/pages/signup/SignupForm.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35191
I have:
| Desktop - Chrome |               |   ![Capture d’écran 2025-03-31 à 15 00 56](https://github.com/user-attachments/assets/617e2775-778f-41e2-aac8-dd1851643f1e)  |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25b …

(PC-35191) feat(auth): update wording in SetBirthday

---

__snapshots__/features/auth/pages/signup/QuitSignupModal/QuitSignupModal.native.test.tsx.native-snap
__snapshots__/features/identityCheck/components/modals/QuitIdentityCheckModal.native.test.tsx.native-snap
src/ui/components/modals/AppFullPageModal.tsx

I have:
| Desktop - Chrome |   ![Capture d’écran 2025-04-02 à 15 10 23](https://github.com/user-attachments/assets/fe2e3477-c2da-4132-b97e-1cfb18714172) |  ![Capture d’écran 2025-04-02 à 15 09 58](https://github.com/user-attachments/assets/2d2910f1-df84-4f1d-a141-db837d37160c)   |
[2]: …

(BSR) feat(ui): fix AppFullPageModal in web

---

fastlane/Fastfile

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35466
I have:
<details>
If you …

(PC-35466) fix(CI): fastlane sentry saas

---

fastlane/Fastfile

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35466
I have:
<details>
If you …

(PC-35466) fix(CI): fastlane sentry saas, add org & project

---

fastlane/Fastfile
templates_github_ci/.sentryclirc

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35466
I have:
<details>
If you …

(PC-35466) fix(CI): fastlane sentry saas final fix

---

src/ui/components/modals/AppInformationModal.tsx
src/ui/components/modals/ModalHeader.tsx
src/ui/components/modals/appModalContainerStyle.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35535
I have:
| iOS              |     ![Simulator Screenshot - iPhone 15 - 2025-04-07 at 18 20 07](https://github.com/user-attachments/assets/317badad-3b21-4ccf-9198-c4f6ad6fd3f8)   ![Simulator Screenshot - iPhone 15 - 2025-04-07 at 20 02 49](https://github.com/user-attachments/assets/559aeada-5bf0-40e6-93d8-405ada2bdb9c)   |  ![Simulator Screenshot - iPhone 15 - 2025-04-07 at 20 51 17](https://github.com/user-attachments/assets/b4f000a8-4d79-431e-8e21-c3430c004877) ![Simulator Screenshot - iPhone 15 - 2025-04-07 at 18 30 …

(PC-35535) feat(ui): use designToken in AppInformationModal and AppModal

---

.maestro/tests/AccessSignupFromBlock.yml
.maestro/tests/VenueMapCheck.yml
.maestro/tests/subFolder/home/OpenActivationModuleFromHome.yml
.maestro/tests/subFolder/profil/DeletionReactivation.yml
.maestro/tests/subFolder/profil/LegalInfoSection.yml
.maestro/tests/subFolder/venue/VerifyVenueMap.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35523
I have:

(PC-35523) fix(e2e): update deletion scenario, avoid hidekeyboard flakiness

---

.maestro/tests/subFolder/booking/BookMusicalOffer.yml
.maestro/tests/subFolder/home/OpenActivationModuleFromHome.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35578
I have:

(PC-35578) fix(e2e): bypass localization poppin in home

---

.github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml
.github/workflows/dev_on_pull_request_reassure.yml
.github/workflows/dev_on_pull_request_title_checker.yml
.github/workflows/dev_on_schedule_lighthouse.yml
.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_check_deadcode.yml
.github/workflows/dev_on_workflow_check_folder_change.yml
.github/workflows/dev_on_workflow_check_proxy_version.yml
.github/workflows/dev_on_workflow_chromatic.yml
.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_environment_soft_deploy.yml
.github/workflows/dev_on_workflow_install.yml
.github/workflows/dev_on_workflow_linter_ts.yml
.github/workflows/dev_on_workflow_pr_preview.yml
.github/workflows/dev_on_workflow_tester.yml
.github/workflows/dev_on_workflow_ts_noUncheckedIndexedAccess.yml
.github/workflows/dev_on_workflow_update_jira_issues.yml
.github/workflows/dev_on_workflow_web_deploy.yml
.github/workflows/dev_on_workflow_web_proxy_deploy.yml

(BSR) fix(CI): bump ubuntu

---

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
src/features/profile/components/VerticalDots/VerticalDots.stories.tsx
src/features/profile/components/VerticalDots/VerticalDots.tsx
src/ui/components/headers/HeaderWithImage.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35604
I have:
<details> …

(PC-35604) refactor(app): remove useless props

---

.github/workflows/dev_on_push_workflow_main.yml

Temporary disable soft deploy as we dont't have a OTA service alternative to CodePush yet

(BSR) feat(CI): temporary disable soft deploy

---

.github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml
.github/workflows/dev_on_pull_request_reassure.yml
.github/workflows/dev_on_pull_request_title_checker.yml
.github/workflows/dev_on_schedule_lighthouse.yml
.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_ios.yml
.github/workflows/dev_on_workflow_check_deadcode.yml
.github/workflows/dev_on_workflow_check_folder_change.yml
.github/workflows/dev_on_workflow_check_proxy_version.yml
.github/workflows/dev_on_workflow_chromatic.yml
.github/workflows/dev_on_workflow_environment_android_deploy.yml
.github/workflows/dev_on_workflow_environment_ios_deploy.yml
.github/workflows/dev_on_workflow_environment_soft_deploy.yml
.github/workflows/dev_on_workflow_install.yml
.github/workflows/dev_on_workflow_linter_ts.yml
.github/workflows/dev_on_workflow_pr_preview.yml
.github/workflows/dev_on_workflow_tester.yml
.github/workflows/dev_on_workflow_ts_noUncheckedIndexedAccess.yml
.github/workflows/dev_on_workflow_update_jira_issues.yml
.github/workflows/dev_on_workflow_web_deploy.yml
.github/workflows/dev_on_workflow_web_proxy_deploy.yml

<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be an exception or `null` generated if the type assertion is wrong). In certain cases `as const` is acceptable (for example when defining readonly arrays/objects). Using `as` in tests is tolerable.
- Remove bypass type checking with `any` (when you want to accept anything because you will be blindly passing it through without …

(BSR) ci(timeout): reduce timeout from default six hours to one hour

---

src/features/achievements/hooks/useShouldShowAchievementSuccessModal.native.test.ts
src/features/achievements/hooks/useShouldShowAchievementSuccessModal.ts
src/features/achievements/hooks/useShouldShowAchievementSuccessModal.web.test.ts
src/features/home/helpers/useWhichModalToShow.native.test.ts
src/features/profile/components/Header/ProfileHeader/ProfileHeader.native.test.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.web.test.tsx
src/features/profile/pages/Profile.native.test.tsx
src/features/profile/pages/Profile.tsx
src/libs/firebase/firestore/types.ts
src/libs/firebase/remoteConfig/helpers/getRemoteConfigFromConfigValues.ts
src/libs/firebase/remoteConfig/remoteConfig.constants.ts
src/libs/firebase/remoteConfig/remoteConfig.types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35514
I have:
| iOS              |               |   ![simulator_screenshot_11D142E5-0572-47A4-A848-E4AE45FB07CB](https://github.com/user-attachments/assets/c8cda12b-8750-4f03-83c9-826d381ec48e)   |

(PC-35514) feat(achievements): remove FF and remoteConfig

---

devbox.json
devbox.lock
flake.lock
flake.nix

(BSR) chore(dependencies): update watchman

---

src/shared/hook/useOrientationLocked.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35696
I have:

(PC-35696) feat(a11y): lock orientation when install app for first time

---

.github/workflows/dev_on_pull_request_run_e2e.yml
.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_ios.yml
.maestro/README.md
.maestro/tests/AccessSignupFromBlock.yml
.maestro/tests/FavoriteSectionCheck.yml
.maestro/tests/FirstLaunch.yml
.maestro/tests/ProfileAndDeletionSectionCheck.yml
.maestro/tests/SearchAndBookCinemaOffer.yml
.maestro/tests/SearchAndBookDuoOffer.yml
.maestro/tests/SearchAndBookOffers.yml
.maestro/tests/SearchJourney.yml
.maestro/tests/SignupAndActivation.yml
.maestro/tests/UserNotConnectedMode.yml
.maestro/tests/VenueMapCheck.yml
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35498
I have:

(PC-35498) feat(e2e): add modular test tags for functional scopes

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35825
I have:
<details> …

(PC-35825) feat(search): add wipTimeFilterV2 FF

---

__snapshots__/features/identityCheck/pages/profile/SetProfileBookingError.native.test.tsx.native-snap
src/cheatcodes/pages/features/identityCheck/CheatcodesNavigationIdentityCheck.tsx
src/features/identityCheck/pages/profile/SetProfileBookingError.native.test.tsx
src/features/identityCheck/pages/profile/SetProfileBookingError.tsx
src/features/identityCheck/pages/profile/SetProfileBookingError.web.test.tsx
src/features/identityCheck/pages/profile/SetStatus.native.test.tsx
src/features/identityCheck/pages/profile/SetStatus.tsx
src/features/navigation/RootNavigator/subscriptionRoutes.ts
src/features/navigation/RootNavigator/types.ts
src/features/offer/components/BookingButton/BookingButton.tsx
src/features/offer/components/StickyBookingButton/StickyBookingButton.tsx
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
src/fixtures/user.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35543
I have:
| iOS              |  ![Simulator Screenshot - iPhone 15 Pro Max - 2025-04-24 at 17 15 59](https://github.com/user-attachments/assets/36cd9278-edb7-4858-951b-3973ec1a3b7a)             |     ![Simulator Screenshot - iPhone 15 Pro Max - 2025-04-24 at 17 16 06](https://github.com/user-attachments/assets/d6ab22b2-746e-4b55-b1de-646c59afb116)   |
[1]: …

(PC-35543) feat(identityCheck): add SetProfileBookingError screen

---

src/features/home/components/modules/TrendsModule.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35824
Description : Dans ce ticket la majorité a été réalisé dans Contentful, il fallait ajouter le module tendance A venir. 
Il y avait un paramètre qui bloquait le module à seulement 4 items que j'ai retiré car désormais on veut une liste avec minimum 5. 
Et dans un second temps il a fallu ajouter la possibilité de scroll
I have:
| iOS              |               |![Simulator Screenshot - iPhone 15 Pro - 2025-04-30 at 17 10 27](https://github.com/user-attachments/assets/d749907a-67b7-4d7d-a76f-11416bb3c3f5)|
| Android …

(PC-35824) feat(TrendsModule): add the possibility to scroll

---

src/features/search/pages/ThematicSearch/ThematicSearchPlaylist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35910
Description : Après la réfacto des tuiles des playlist, il manquait l'ajout de la props dans la playlist des ThematicSearch
I have:
| Desktop - Chrome |<img width="1043" alt="image-20250429-085804" src="https://github.com/user-attachments/assets/9a42d893-bc38-48c5-9e1c-8d3262cb7cb5" />|![Capture d’écran 2025-05-05 à 11 29 38](https://github.com/user-attachments/assets/ca2518e7-591d-4 …

(PC-35910) fix(ThematicSearch): missing props on this screen

---

.github/workflows/dev_on_push_workflow_main.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35938
I have:
<details>
If you …

(PC-35938) feat(ci): remove yarn-ts-noUncheckedIndexedAccess of dev_on_push_worflow

---

.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_ios.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35990
I have:

(PC-35990) refactor(ci): remove unecessary yarn and java in workflow

---

package.json
scripts/eslint-warnings.sh

Pas mal de règles en soft rules ont été ajoutées et il nous faut un sommaire claire du nombre d'erreurs pour plus de visibilité sur l'avancée du travail

(BSR) feat(eslint): add a warning counter script

---

fastlane/Fastfile

(BSR) feat(AppDistribution): add app distribution tester groups

---

__snapshots__/features/favorites/pages/Favorites.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/search/pages/SearchResults/SearchResults.tsx
src/ui/components/placeholders/Placeholders.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34382
I have:
| Android          |   ![Screenshot_1746626446](https://github.com/user-attachments/assets/9ec10c98-e25a-412b-afdf-11b9231521b0) | ![Screenshot_1746626467](https://github.com/user-attachments/assets/58b65aee-b292-4bdc-9db1-0172f88539a0)|
| Desktop - Chrome | ![Screenshot 2025-05-07 at 15 59 54](https://github.com/user-attachments/assets/4a5d68a3-93e5-429b-a956-6f661c2255bf)|![Screenshot 2025-05-07 at 15 58 53](https://github.com/user-attachments/assets/e71bd6eb-4863-4173-8904-2826feb20da1)|
[1]: …

(PC-34382) feat(SearchResults): improve skeleton

---

__snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap
src/cheatcodes/pages/features/trustedDevice/CheatcodesNavigationTrustedDevice.tsx
src/cheatcodes/pages/features/trustedDevice/CheatcodesScreenTrustedDeviceInfos.tsx
src/cheatcodes/pages/others/CheatcodesScreenAccesLibre.tsx
src/cheatcodes/pages/others/CheatcodesScreenFeatureFlags.tsx
src/cheatcodes/pages/others/CheatcodesScreenNewCaledonia.tsx
src/cheatcodes/pages/others/CheatcodesScreenRemoteConfig.tsx
src/features/accessibility/components/AccessibilityFiltersModal.tsx
src/features/artist/components/ArtistTopOffers/ArtistTopOffers.tsx
src/features/offer/components/VenueDetails/VenueDetails.tsx
src/features/offer/components/VenueSelectionModal/VenueSelectionModal.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36033
I have:
<details> …

(PC-36033) refactor(app): remove some Spacer

---

.github/workflows/dev_on_workflow_call_e2e_ios.yml
.maestro/tests/subFolder/auth/LoginFromProfileForBeneficiaryUser.yml
.maestro/tests/subFolder/commons/getCurrentDay.js
.maestro/tests/subFolder/search/SearchBookableCinemaOffer.yml
.maestro/tests/subFolder/search/SearchBookableDuoOffer.yml
.maestro/tests/subFolder/search/SearchOfferFromText.yml
.maestro/tests/subFolder/tutorial/onboarding/Onboard16AndLocalization.yml
.maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36021
I have:

(PC-36021) refactor(e2e): Replace conditional date logic with dynamic JS for D+3

---

src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36091
I have:
| Desktop - Chrome |               |   ![Capture d’écran 2025-05-13 à 15 01 24](https://github.com/user-attachments/assets/0df5fcde-7ad2-429f-b4d3-343055d7c5be) ![Capture d’écran 2025-05-13 à 15 04 37](https://github.com/user-attachments/assets/3fd1ef09-434c-4d48-99f3-8266a1245397) ![Capture d’écran 2025-05-13 à 15 04 …

(PC-36091) feat(booking): disable offer CTA when is not free offer

---

src/features/home/components/modules/HomeModule.native.test.tsx
src/features/home/components/modules/video/VideoModule.native.test.tsx
src/features/home/components/modules/video/VideoModule.tsx
src/features/home/queries/useVideoOffersQuery.native.test.ts
src/features/home/queries/useVideoOffersQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36085

(PC-36085) refactor(home): queryfy useVideoOffers

---

src/features/offer/components/InteractionTag/getTagConfig.test.ts
src/features/offer/components/InteractionTag/getTagConfig.tsx
src/features/offer/components/OfferPlaylistItem/OfferPlaylistItem.tsx
src/features/offer/components/OfferTile/OfferTileWrapper.tsx
src/features/venue/components/VenueOffers/VenueOffersList.tsx
src/features/venueMap/components/VenueMapBottomSheet/VenueMapOfferPlaylist.tsx
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/offerAttributesToRetrieve.ts
src/libs/algolia/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36044
Description : Ajout du tag "Bientôt dispo". pas grand chose à dire de plus techniquement il reste dans la continuité des autres tags.
I have:
| iOS              |               |![Simulator Screenshot - iPhone 15 Pro - 2025-05-13 at 18 02 04](https://github.com/user-attachments/assets/7735c01d-20e0-48be-b41f-2a57a908bc6c)![Simulator Screenshot - iPhone 15 Pro - 2025-05-13 at 18 02 25](https://github.com/user-attachments/assets/b59de969-5ca4-466a-86fa-f3e95a4c4b34)|
| Phone …

(PC-36044) feat(InteractionTag): add soon offer tag

---

src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/features/offer/components/OfferContent/OfferContent.tsx
src/features/offer/components/OfferContent/OfferContent.web.test.tsx
src/features/offer/components/OfferContent/OfferContent.web.tsx
src/features/offer/components/OfferContent/OfferContentBase.tsx
src/features/offer/components/OfferContent/StickyFooterContent/StickyFooterContentBase.tsx
src/features/offer/components/OfferFooter/OfferFooter.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35793
I have:
| iOS              | <img width="426" alt="Capture d’écran 2025-05-14 à 09 38 49" src="https://github.com/user-attachments/assets/b5ae7c29-ec60-417d-a8ca-2700037ea523" /> | <img src="https://github.com/user-attachments/assets/2183f824-1995-4cf5-aba3-0c69dce2d342" /> |

(PC-35793) fix(Offer): fix coming soon footer display

---

.github/workflows/dev_on_pull_request_run_e2e_web.yml
.maestro/tests/SmokeTestWeb.yaml
.maestro/tests/subFolder/booking/BookMusicalOffer.yml
.maestro/tests/subFolder/commons/GoToFavoritesFromTabBar.yml
.maestro/tests/subFolder/commons/GoToProfileFromTabBar.yml
.maestro/tests/subFolder/cookies/AcceptCookies.yml
.maestro/tests/subFolder/favorite/VerifyUnloggedFavorite.yml
.maestro/tests/subFolder/home/VerifyHomeScreen.yml
.maestro/tests/subFolder/profil/CheckSignupAndLogin.yml
.maestro/tests/subFolder/profil/VerifyProfilePage.yml
.maestro/tests/subFolder/search/NavigateToCinemaCategory.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35750
I have:

(PC-35750) feat(e2e): add smoke test for web app

---

.maestro/tests/subFolder/tutorial/onboarding/Onboard16AndLocalization.yml
.maestro/tests/subFolder/tutorial/onboarding/Onboard18.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36126
I have:

(PC-36126) fix(e2e): update ios localization screen wording

---

src/features/gtlPlaylist/queries/useGTLPlaylistsQuery.native.test.ts
src/features/gtlPlaylist/queries/useGTLPlaylistsQuery.ts
src/features/gtlPlaylist/queries/useGetFormattedAndFilteredOffersByGtl.test.ts
src/features/gtlPlaylist/queries/useGetOffersByGtlQuery.ts
src/features/gtlPlaylist/types.ts
src/features/search/pages/ThematicSearch/Book/BookPlaylists.tsx
src/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx
src/features/venue/pages/Venue/Venue.tsx
src/libs/queryKeys.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36146

(PC-36146) feat(GtlPlaylist): update query dependency array

---

src/features/bookOffer/components/BookingDetails.native.test.tsx
src/features/bookOffer/components/BookingDetails.tsx
src/features/bookOffer/pages/BookingConfirmation.native.test.tsx
src/features/bookOffer/pages/BookingConfirmation.tsx
src/features/home/components/headers/HomeHeader.native.test.tsx
src/features/home/components/headers/HomeHeader.tsx
src/features/profile/components/EmptyCredit/EmptyCredit.native.test.tsx
src/features/profile/components/EmptyCredit/EmptyCredit.tsx
src/features/profile/components/Header/CreditHeader/CreditHeader.tsx
src/features/profile/components/Header/ProfileHeader/ProfileHeader.tsx
src/features/profile/helpers/getHeaderSubtitleProps.native.test.ts
src/features/profile/helpers/getHeaderSubtitleProps.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36093
I have:
| Desktop - Chrome |               | <img width="718" alt="Capture d’écran 2025-05-14 à 18 03 43" src="https://github.com/user-attachments/assets/f21366d4-e790-4b5f-bb3e-bef08d0eb035" /> ![Capture d’écran 2025-05-14 à 16 19 53](https://github.com/user-attachments/assets/36ec3529-01a1-4b68-a4ba-df7f703a30c8)  ![Capture d’écran 2025-05-14 à 09 23 …

(PC-36093) feat(booking): hide 0 credit mentions

---

src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36091
I have:

(PC-36091) feat(booking): update wording in useCtaWordingAndAction

---

.eslintrc.js
src/features/home/components/modules/banners/HomeBanner.native.test.tsx
src/features/home/pages/GenericHome.native.test.tsx

Link to JIRA ticket: [PC-36158](https://passculture.atlassian.net/browse/PC-36158)
[PC-36158]: https://passculture.atlassian.net/browse/PC-36158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

(PC-36158) feat(test): remove last toHaveBeenCalled

---

src/features/home/api/helpers/mapOffersDataAndModules.ts
src/features/home/pages/GenericHome.tsx
src/features/home/queries/useGetOffersDataQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36086

(PC-36086) refactor(home): queryfy useGetOffersData

---

.maestro/tests/subFolder/booking/BookCinemaOffer.yml
.maestro/tests/subFolder/booking/BookDuoOffer.yml
.maestro/tests/subFolder/booking/DaySelectionCinema.yml
.maestro/tests/subFolder/commons/getCurrentDay.js
.maestro/tests/subFolder/search/SearchBookableCinemaOffer.yml
.maestro/tests/subFolder/search/SearchBookableDuoOffer.yml

(BSR) fix(e2e): use only days instead of full date

---

__snapshots__/features/profile/pages/DebugScreen/DebugScreen.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Profile.native.test.tsx.native-snap
src/cheatcodes/pages/others/CheatcodesNavigationAccountManagement.tsx
src/features/auth/components/SSOButton/SSOButton.native.test.tsx
src/features/auth/pages/forgottenPassword/ReinitializePassword/ReinitializePassword.native.test.tsx
src/features/auth/pages/login/Login.native.test.tsx
src/features/auth/pages/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.native.test.tsx
src/features/auth/pages/signup/SignupForm.native.test.tsx
src/features/navigation/ProfileStackNavigator/ProfileStack.ts
src/features/navigation/ProfileStackNavigator/ProfileStackNavigator.tsx
src/features/navigation/ProfileStackNavigator/profileRoutes.ts
src/features/profile/pages/DebugScreen/DebugScreen.native.test.tsx
src/features/profile/pages/DebugScreen/DebugScreen.tsx
src/features/profile/pages/DebugScreen/DebugScreen.web.test.tsx
src/features/profile/pages/Profile.native.test.tsx
src/features/profile/pages/Profile.tsx
src/features/trustedDevice/helpers/useDeviceInfo.ts
src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35467
I have:
| Desktop - Chrome |               |   ![Capture d’écran 2025-05-19 à 13 23 31](https://github.com/user-attachments/assets/2afbdf59-8c05-499e-a741-c410654ee774) ![Capture d’écran 2025-05-19 à 13 23 43](https://github.com/user-attachments/assets/baf743b6-bd9d-4a13-ba63-67391df1a970)  |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a7 …

(PC-35467) feat(profile): add DebugScreen

---

__snapshots__/features/identityCheck/pages/profile/ProfileInformationValidation.native.test.tsx.native-snap
__snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap
src/cheatcodes/pages/features/identityCheck/CheatcodesNavigationIdentityCheck.tsx
src/features/identityCheck/helpers/getActivityLabel.native.test.ts
src/features/identityCheck/helpers/getActivityLabel.ts
src/features/identityCheck/pages/helpers/useStoredProfileInfos.native.test.ts
src/features/identityCheck/pages/helpers/useStoredProfileInfos.ts
src/features/identityCheck/pages/profile/ProfileInformationValidation.native.test.tsx
src/features/identityCheck/pages/profile/ProfileInformationValidation.tsx
src/features/identityCheck/pages/profile/ProfileInformationValidation.web.test.tsx
src/features/identityCheck/pages/profile/SetCity.tsx
src/features/identityCheck/pages/profile/SetStatus.native.test.tsx
src/features/identityCheck/pages/profile/SetStatus.tsx
src/features/identityCheck/pages/profile/store/nameStore.ts
src/features/identityCheck/pages/profile/store/resetProfileStores.ts
src/features/identityCheck/pages/profile/store/statusStore.ts
src/features/identityCheck/queries/profileSubmissionHandlers.ts
src/features/navigation/RootNavigator/subscriptionRoutes.ts
src/features/navigation/RootNavigator/types.ts
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.native.test.ts
src/features/offer/helpers/useCtaWordingAndAction/useCtaWordingAndAction.ts
src/features/profile/pages/PersonalData/PersonalData.tsx
src/libs/storage.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35547
I have:
| Desktop - Chrome |               | ![Capture d’écran 2025-05-16 à 17 03 26](https://github.com/user-attachments/assets/f672a2c1-99dd-4a3e-8141-897da035478e)  |
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb0 …

(PC-35547) feat(identityCheck): add status store

---

.github/pr-title-checker.test.ts

Allow tickets from IC team in PR titles
I have:
<details>
If you can't respect one of these …

(BSR) ci(checks): allow IC tickets in PRs

---

.github/workflows/dev_on_schedule_run_e2e_android.yml
.github/workflows/dev_on_schedule_run_e2e_ios.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36214
I have:

(PC-36214) refactor(e2e): change cron schedule from 11pm to 5am

---

doc/development/general-info-web.md
src/libs/monitoring/config.web.ts
vite.config.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36179
I have:

(PC-36179) chore(sentry): remove legacy web option now that we have sentry latest version

---

.maestro/tests/subFolder/booking/BookPhysicalOffer.yml
.maestro/tests/subFolder/commons/getCurrentDay.js

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36254
I have:

(PC-36254) fix(e2e): make date iso on cloud runs and fix offer selection

---

src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.native.test.ts
src/features/venue/components/OpeningHoursStatus/getOpeningHoursStatus.ts

La boucle infinie se présentait si les horaires d'ouverture du lieu étaient tous à 00h.
Pour l'éviter on s'arrête à 7 passages dans la fonction pour être quand même sûr d'avoir les horaires de chaque jour de la semaine.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36150
I have:
| iOS              |![Capture d’écran 2025-05-26 à 17 39 01](https://github.com/user-attachments/assets/085051c0-b376-47ac-b650-a4d616fc803a)|![Capture d’écran 2025-05-26 à 17 38 41](https://github.com/user-attachments/assets/0630d71d-0737-42c5-8f4b-5a8e2d10d05d)|
| Android          | …

(PC-36150) fix(venue): avoid infinite loop due to venue opening hours

---

src/features/venue/helpers/getVenueOffersArtists.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36046
I have:
| iOS              |![Capture d’écran 2025-05-27 à 11 03 34](https://github.com/user-attachments/assets/5fc489b6-0a0a-4252-91ce-3e22b5fbb280)|![Capture d’écran 2025-05-27 à 11 03 21](https://github.com/user-attachments/assets/fbcec53e-b026-4f13-83bc-575550f56517)|
| Desktop - Chrome |<img width="1726" alt="Capture d’écran 2025-05-27 à 11 04 41" src="https://github.com/user-attachments/assets/2152bcac-a630-4a38-918e- …

(PC-36046) fix(venue): avoid artists duplication on playlist

---

src/features/profile/pages/Accessibility/SiteMapScreen.native.test.tsx
src/features/profile/pages/Accessibility/SiteMapScreen.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35190
I have:

(PC-35190) feat(profile): fix SiteMapScreen navigation

---

src/features/offer/helpers/getIsFreeOffer/getIsFreeOffer.native.test.ts
src/features/offer/helpers/getIsFreeOffer/getIsFreeOffer.ts
src/features/offer/helpers/useHasEnoughCredit/useHasEnoughCredit.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36239
I have:
<details>
If you …

(PC-36239) fix(credit): first check if offer is free before checking if user has credit

---

package.json
yarn.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36529
Des tags ont été supprimés côté répo design-system. Ces tags étaient des tests. 
Ils ont été supprimés, il faut donc mettre à jour la lib avec le bon tag
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481 …

(PC-36529) refactor(DS): update lib

---

__snapshots__/features/offer/components/FavoriteAuthModal/FavoriteAuthModal.native.test.tsx.native-snap
__snapshots__/features/offer/components/NotificationAuthModal/NotificationAuthModal.native.test.tsx.native-snap
__snapshots__/features/subscription/NotificationsLoggedOutModal.native.test.tsx.native-snap
__snapshots__/features/subscription/components/modals/OnboardingSubscriptionModal.native.test.tsx.native-snap
__snapshots__/features/subscription/components/modals/SubscriptionSuccessModal.native.test.tsx.native-snap
__snapshots__/features/subscription/components/modals/UnsubscribingConfirmationModal.native.test.tsx.native-snap
__snapshots__/shared/offer/components/ApplicationProcessingModal/ApplicationProcessingModal.native.test.tsx.native-snap
__snapshots__/shared/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx.native-snap
__snapshots__/shared/offer/components/ErrorApplicationModal/ErrorApplicationModal.native.test.tsx.native-snap
__snapshots__/shared/offer/components/FinishSubscriptionModal/FinishSubscriptionModal.native.test.tsx.native-snap
src/ui/components/modals/AppModalWithIllustration.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36533
I have:
| iOS              |               |![Simulator Screenshot - iPhone 15 Pro - 2025-06-12 at 15 18 54](https://github.com/user-attachments/assets/4bfe94ff-d375-4e88-898f-957bca3f9500)|
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe4725 …

(PC-36533) fix(AppModalWithIllustration): to much blank spacing

---

android/build.gradle

23 and 24 crash on my simulator
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36579
I have:
<details>
These rules apply to files …

(PC-36579) chore(Android): bump minimal Android SDK version to 25

---

.github/workflows/dev_on_schedule_lighthouse.yml
lighthouserc.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35532
Example of a successful run: https://github.com/pass-culture/pass-culture-app-native/actions/runs/15726692233
I have:
[2]: https://www.notion.so/passcultureapp/cb45383351b44723a6f2d9e1481ad6bb?v=10fe47258701423985aa7d25bb04cfee&pvs …

(PC-35532) perf(web): lighthouse

---

.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_ios.yml
.maestro/tests/subFolder/search/SearchOfferFromText.yml
scripts/run_e2e_tests.sh

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36594
I have:

(PC-36594) fix(e2e): replace regex selection with AI assertion

---

.github/workflows/dev_on_schedule_lighthouse.yml
lighthouserc.yml

Example run with changes:
https://github.com/pass-culture/pass-culture-app-native/actions/runs/15734624962/job/44343921863

(BSR) feat(lighthouse): log app version

---

ios/Podfile.lock

(BSR) fix(podfile): update

---

src/libs/firebase/firestore/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36505
I have:
<details> …

(PC-36505) feat(offer): add wipOfferVideoSection feature flag

---

src/features/home/helpers/enrichModulesWithData.native.test.ts
src/features/home/helpers/enrichModulesWithData.ts
src/features/home/pages/GenericHome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36602
I have:
| Desktop - Chrome |<video src="https://github.com/user-attachments/assets/6585bc09-7e5c-4c08-8652-6d49f7346b28"/>|<video src="https://github.com/user-attachments/assets/c60d2f3d-0ab8-4733-b92e-8184f760c3ee"/>|
<details>
These rules apply to files …

(PC-36602) fix(home): fix home loading

---

src/features/navigation/OnboardingStackNavigator/OnboardingStackNavigator.tsx
src/features/navigation/ProfileStackNavigator/ProfileStackNavigator.tsx
src/features/navigation/RootNavigator/RootStackNavigator.tsx
src/features/navigation/RootNavigator/SuspenseAchievements.tsx
src/features/navigation/SearchStackNavigator/SearchStackNavigator.tsx
src/features/navigation/TabBar/TabStackNavigator.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-35664
I have:
<details>
If you …

(PC-35664) refactor(navigation): include withAsyncErrorBoundary

---

__snapshots__/features/home/pages/GenericHome.native.test.tsx.native-snap
__snapshots__/features/home/pages/Home.native.test.tsx.native-snap
__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
src/features/home/pages/GenericHome.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36602
I have:
<details>
If you …

(PC-36602) fix(home): upgrade initial number of modules to render

---

src/features/bookOffer/components/Calendar/Calendar.tsx
src/features/bookOffer/components/Calendar/DayComponent.tsx
src/features/bookOffer/components/Calendar/DiagonalStripe.tsx
src/features/bookOffer/components/ChoiceBloc.tsx
src/features/bookings/helpers/useReactionIcon/useReactionIcon.tsx
src/features/location/components/LocationWidgetWrapperDesktop.tsx
src/features/offer/components/OfferBody/ProposedBySection/ProposedBySection.tsx
src/features/offer/components/OfferContent/StickyFooterContent/StickyFooterContentBase.tsx
src/features/offer/components/OfferHeader/OfferReactionHeaderButton.tsx
src/features/offer/components/OfferImageWrapper/OfferImageWrapper.tsx
src/features/reactions/components/ReactionChoiceModalBodyWithRedirection/ReactionChoiceModalBodyWithRedirection.tsx
src/features/search/components/SelectionLabel/SelectionLabel.tsx
src/features/venue/components/TabLayout/TabLayout.web.test.tsx
src/features/venue/components/VenueBody/VenueBanner.tsx
src/features/venueMap/components/VenueMapBottomSheet/VenueMapBottomSheet.tsx
src/features/venueMap/components/VenueMapFiltersList/VenueMapFiltersList.tsx
src/features/venueMap/components/VenueMapLabel/LabelContainer.android.tsx
src/features/venueMap/components/VenueMapLabel/LabelContainer.tsx
src/features/venueMap/components/VenueMapPreview/VenueMapPreview.tsx
src/features/venueMap/pages/VenueMap/VenueMapBase.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36667
I have:
<details> …

(PC-36667) refactor(app): replace some theme.colors by theme.designSystem.color

---

__snapshots__/features/profile/pages/PersonalData/PersonalData.native.test.tsx.native-snap
src/features/profile/components/EditableFiled/EditableField.stories.tsx
src/features/profile/components/EditableFiled/EditableField.tsx
src/features/profile/pages/PersonalData/PersonalData.native.test.tsx
src/features/profile/pages/PersonalData/PersonalData.tsx
src/features/profile/pages/PersonalData/PersonalData.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36511
I have:
| Desktop - Chrome |     ![Capture d’écran 2025-06-27 à 11 57 24](https://github.com/user-attachments/assets/cb48655f-4235-48d4-9de6-91e0946032d7)    |   ![Capture d’écran 2025-06-27 à 11 50 06](https://github.com/user-attachments/assets/9118b48d-76e3-4306-9bce-33d26ece8391) |
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-sur-les-bugs-5dd6df8f6a754e68870 …

(PC-36511) feat(profile): update PersonalData

---

.github/workflows/dev_on_dispatch_create_and_push_ehp_deploy_tags.yml

Correction des erreurs dans : https://github.com/pass-culture/pass-culture-app-native/actions/runs/15906593452/job/44908389939

(BSR) ci(tag): remove useless token from tag creation workflow

---

.maestro/tests/SignupJourney.yml
.maestro/tests/subFolder/favorite/AddToFavorite.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-34673
I have:

(PC-34673) fix(e2e): remove useless case and add scroll for favorite ios flow

---

src/features/auth/pages/suspendedAccount/AccountReactivationSuccess/AccountReactivationSuccess.web.test.tsx
src/features/bookings/pages/BookingNotFound/BookingNotFound.web.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryAccountCreated.web.test.tsx
src/features/identityCheck/pages/confirmation/BeneficiaryRequestSent.web.test.tsx
src/features/identityCheck/pages/identification/ubble/ComeBackLater.web.test.tsx
src/features/offer/components/VenueSelectionModal/VenueSelectionModal.web.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileContactSupport.web.test.tsx
src/features/profile/pages/DeleteProfile/DeleteProfileEmailHacked.web.test.tsx
src/features/search/components/SearchListHeader/SearchListHeader.web.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36832

(PC-36832) test(worksOffline): unit tests should work offline and not perform actual request

---

__snapshots__/features/accessibility/components/AccessibilityFiltersModal.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/CategoriesModal/CategoriesModal.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/DatesHoursModal/DatesHoursModal.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/OfferDuoModal/OfferDuoModal.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/PriceModal/PriceModal.native.test.tsx.native-snap
__snapshots__/features/search/pages/modals/VenueModal/VenueModal.native.test.tsx.native-snap
src/features/search/components/SearchFixedModalBottom.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36724
I have:
| iOS              |![Simulator Screenshot - iPhone 15 Pro - 2025-07-04 at 15 02 24](https://github.com/user-attachments/assets/c5e38159-1047-41e1-ab82-baed894c747b)|![Simulator Screenshot - iPhone 15 Pro - 2025-07-04 at 15 02 16](https://github.com/user-attachments/assets/8ff59adf-c08b-4ba1-b451-c726f124b6ee)|
[1]: https://www.notion.so/passcultureapp/R-solution-de-probl-mes-s …

(PC-36724) fix(SearchFixedModalBottom): add a backgroundColor

---

src/features/bookings/components/Ticket/TicketBottomPart/CinemaBookingTicket/CinemaBookingTicket.native.test.tsx
src/features/bookings/components/Ticket/TicketBottomPart/CinemaBookingTicket/CinemaBookingTicket.tsx
src/features/bookings/components/Ticket/TicketBottomPart/TicketBottomPart.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36874
I have:
| Desktop - Chrome | <img width="514" alt="Capture d’écran 2025-07-07 à 09 32 20" src="https://github.com/user-attachments/assets/5433f9bd-4c33-44ae-9192-b888cac01876" /> | <img width="515" alt="Capture d’écran 2025-07-07 à 09 28 51" src="https://github.com/user-attachments/assets/a2fe601e-d0a2-415d-8112-f328c293734b" /> |

(PC-36874) feat(Bookings): cinema bookings

---

src/shared/forms/schemas/emailSchema.test.ts
src/shared/forms/schemas/emailSchema.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36692
I have:
| Desktop - Chrome |    <img width="499" alt="Capture d’écran 2025-07-08 à 12 07 46" src="https://github.com/user-attachments/assets/d69d9e18-be18-4dc8-aa30-e9fa676bcf93" /> <img width="500" alt="Capture d’écran 2025-07-08 à 12 07 36" src="https://github.com/user-attachments/assets/57ea6955-ee18-4278-aa18-093d6c783479" /> <img width="499" alt="Capture d’écran 2025-07-08 …

(PC-36692) feat(profile): update email schema rules

---

fastlane/Fastfile

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36974
I have:
<details>
If you …

(PC-36974) fix(build): fix release build with Fastlane for Android

---

src/features/bookOffer/components/BookingEventChoices.tsx
src/features/navigation/SearchStackNavigator/SearchStackNavigator.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36929
I have:
<details> …

(PC-36929) fix(navigation): remove withAsyncErrorBoundary causing endless calls and blank page in search

---

src/features/auth/context/AuthWrapper.tsx
src/features/auth/pages/suspendedAccount/AccountStatusScreenHandler/AccountStatusScreenHandler.tsx
src/features/bookings/components/OnGoingBookingsList.native.test.tsx
src/features/bookings/components/OnGoingBookingsList.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.tsx
src/features/favorites/components/FavoritesResults.native.test.tsx
src/features/favorites/components/FavoritesResults.tsx
src/features/home/pages/Home.tsx
src/features/identityCheck/pages/profile/SetAddress.tsx
src/features/offer/components/OfferCine/OfferCineContent.native.test.tsx
src/features/offer/components/OfferCine/OfferCineContent.tsx
src/features/offer/pages/Offer/Offer.tsx
src/features/offer/pages/Offer/Offer.web.test.tsx
src/features/offer/tests/renderOfferPageTestUtil.tsx
src/features/profile/components/CitySearchInput/CitySearchInput.tsx
src/features/profile/pages/SuspendAccountConfirmation/SuspendAccountConfirmation.tsx
src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.tsx
src/features/profile/pages/ValidateEmailChange/ValidateEmailChange.tsx
src/features/search/pages/SearchResults/SearchResults.tsx
src/features/search/pages/SuggestedPlacesOrVenues/SuggestedPlaces.tsx
src/features/search/pages/SuggestedPlacesOrVenues/SuggestedVenues.tsx
src/features/search/pages/ThematicSearch/Book/BookPlaylists.native.test.tsx
src/features/search/pages/ThematicSearch/Book/BookPlaylists.tsx
src/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx
src/features/trustedDevice/pages/AccountSecurityBuffer.tsx
src/features/venue/components/VenueOffers/VenueOffers.native.test.tsx
src/features/venue/components/VenueOffers/VenueOffers.tsx
src/features/venue/pages/Venue/Venue.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36961

(PC-36961) fix(Offers): replace isLoading by isInitialLoading

---

src/features/venue/helpers/useNavigateToSearchWithVenueOffers.ts
src/features/venue/helpers/useVenueSearchParameters.ts

(PC-36931) fix(searchOffer): correct freeze issue on search offer

---

src/features/offer/components/OfferImageCarousel/OfferImageCarousel.tsx
src/ui/components/CarouselDot/CarouselDot.native.test.tsx
src/ui/components/CarouselDot/CarouselDot.tsx
src/ui/components/CarouselPagination/CarouselPaginationBase.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36616
I have:
| iOS              |<img width="302" height="423" alt="Capture d’écran 2025-07-15 à 18 03 23" src="https://github.com/user-attachments/assets/10bc3183-41e2-4d70-9165-e07faf67ce0a" />|<img width="444" height="901" alt="Capture d’écran 2025-07-15 à 17 53 13" src="https://github.com/user-attachments/assets/528658ff-7f4c-497f-8bea-8092917d5354" />|
| Phone - Chrome   |          |<img width="400" height="808" alt="Capture d’écran 2025-07-15 à 18 02 25" …

(PC-36616) refactor(offer): update carousel design

---

__snapshots__/shared/offer/components/AuthenticationModal/AuthenticationModal.native.test.tsx.native-snap
src/features/offer/components/OfferCTAButton/OfferCTAButton.native.test.tsx
src/shared/offer/components/AuthenticationModal/AuthenticationModal.tsx
src/shared/offer/helpers/useBookOfferModal.native.test.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36553
I have:
| Desktop - Chrome |    <img width="516" height="933" alt="Capture d’écran 2025-07-17 à 14 19 48" src="https://github.com/user-attachments/assets/130b843c-e485-4ad2-b847-10385705955d" />    |    <img width="515" height="933" alt="Capture d’écran 2025-07-17 à 14 27 55" src="https://github.com/user-attachments/assets/593a8bb7-07e5-450c-affe-f2b120f72d9a" />  |
[1]: …

(PC-36553) feat(offer): update AuthenticationModal wording

---

src/features/search/pages/ThematicSearch/Cinema/CinemaPlaylists.tsx
src/features/search/pages/ThematicSearch/ConcertsAndFestivals/ConcertsAndFestivalsPlaylists.tsx
src/features/search/pages/ThematicSearch/Films/FilmsPlaylists.tsx
src/features/search/pages/ThematicSearch/Music/MusicPlaylists.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36958
I have:
| Desktop - Chrome | https://github.com/user-attachments/assets/325b734d-055f-411b-8f93-891ea0961133 |https://github.com/user-attachments/assets/ed234ead-800c-423f-a792-4d387dc19d95|
<details>
If …

(PC-36958) fix(ThematicSearch): add userLocation to query

---

src/features/search/pages/SuggestedPlacesOrVenues/SuggestedPlaces.native.test.tsx
src/queries/bookOffer/useBookOfferMutation.native.test.ts
src/tests/reactQueryProviderHOC.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36586

(PC-36586) feat(tests): unskip some tests

---

doc/bump-react-native.md

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36908
Documentation qui permettra aux développeurs d'avoir des guidelines pour mettre à jour `React Native`

(PC-36908) docs(bumpRN): add bump react-native package documentation

---

src/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.tsx
src/features/bookings/pages/BookingDetails/BookingDetails.web.test.tsx
src/queries/bookOffer/useBookOfferMutation.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37163
I have:
| Desktop - Chrome | <video src="https://github.com/user-attachments/assets/e4611c64-497d-42cd-a053-cac6e1b90aca" /> | <video src="https://github.com/user-attachments/assets/a189f8f4-3eef-402d-abe1-3b81111bdb1c" /> |

(PC-37163) fix(Bookings): invalidate query and fix boolean logic

---

src/features/venueMap/components/VenueMapBottomSheet/VenueMapOfferPlaylist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36002
I have:
| iOS              |               |<img width="1179" height="2556" alt="Simulator Screenshot - iPhone 15 Pro - 2025-07-23 at 17 17 05" src="https://github.com/user-attachments/assets/623458c0-bd8a-459d-8e79-4ce40a4106bf" />|
[2]: …

(PC-36002) fix(VenueMapOfferPlaylist): fix spacing

---

.github/workflows/dev_on_workflow_tester.yml
README.md

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36492
I have:
<details>
If you …

(PC-36492) fix(Allure): move allure report to another repo

---

src/libs/campaign/campaignTracker.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37198
I have:

(PC-37198) feat(e2e): handle appsFlyer trackers in E2E proxy

---

.github/workflows/dev_on_schedule_flashlight_android.yml

Seems like we run into the timeout:
https://github.com/pass-culture/pass-culture-app-native/actions/runs/16569713740/job/46858410292?pr=8467

(BSR) fix(flashlight): increase timeout

---

__snapshots__/features/identityCheck/pages/identification/educonnect/EduConnectValidation.native.test.tsx.native-snap
__snapshots__/features/identityCheck/pages/identification/educonnect/EduConnectValidation.web.test.tsx.web-snap
__snapshots__/features/identityCheck/pages/profile/ProfileInformationValidationCreate.native.test.tsx.native-snap
__snapshots__/features/profile/pages/MandatoryUpdatePersonalData/ProfileInformationValidationUpdate.native.test.tsx.native-snap
src/features/identityCheck/components/Summary.tsx
src/features/navigation/RootNavigator/useShowMandatoryUpdatePersonalData.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36758
navigationRef.isReady() empêche l’appel prématuré. Sans cette vérification, le code essaie d’appeler navigationRef.current.reset() avant que le NavigationContainer soit monté. 
Avant que le container soit monté, navigationRef.current est null, ce qui déclenche l’erreur "navigation object hasn't been initialized yet". 
Avec navigationRef.isReady(), tu exécutes reset() uniquement après l’événement onReady du NavigationContainer, donc quand la navigation est initialisée et prête.
L'utilisation d'une FlatList imbriquée dans ScrollView gènere cette erreur car cela provoque des problèmes de performance et de gestion du scrolling. 
I have: …

(PC-36758) feat(navigation): Fix navigation error

---

ios/Podfile.lock

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37325
Following [this PR](https://github.com/pass-culture/pass-culture-app-native/pull/8504), we need to update podfile

(PC-37325) feat(app): update podfile

---

__snapshots__/features/auth/pages/signup/AcceptCgu/AcceptCgu.native.test.tsx.native-snap
__snapshots__/features/auth/pages/signup/SignupForm.native.test.tsx.native-snap
__snapshots__/features/internal/pages/DeeplinksGenerator.native.test.tsx.native-snap
src/ui/components/inputs/Checkbox/Checkbox.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37256
I have:
| iOS              |    <img width="1179" height="2556" alt="Simulator Screenshot - iPhone 15 - 2025-08-06 at 17 53 53" src="https://github.com/user-attachments/assets/5405c037-849e-42cc-86ad-35c657c0cdd6" />   |    <img width="1179" height="2556" alt="Simulator Screenshot - iPhone 15 - 2025-08-06 at 17 53 18" src="https://github.com/user-attachments/assets/21f8ed71-cecc-4d00-96d8-14afbcc690c7" /> | …

(PC-37256) feat(ui): fix color label in Checkbox

---

__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
src/features/search/components/NumberOfResults/NumberOfResults.tsx
src/features/search/components/SearchListHeader/ArtistSection.tsx
src/features/search/components/SearchListHeader/SearchListHeader.tsx
src/features/search/components/VenuePlaylist/VenuePlaylist.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37402
I have:
| Platform         | Mockup/Before | After |        |
| Desktop - Chrome | <img width="400" height="600" alt="Capture d’écran 2025-08-12 à 09 26 50" src="https://github.com/user-attachments/assets/e1a48af0-875e-4db0-9dcc-6810b24f0122" /> | <img width="928" height="636" alt="Capture d’écran 2025-08-12 à 10 45 14" src="https://github.com/user-attachments/assets/800c825c-af20-43a9-9d87-b63dbeb720bb" /> | <img width="927" height="635" alt="Capture d’écran 2025-08-12 à 10 45 25" src="https://github.com/user-attachments/assets/708066e0-af49-4268- …

(PC-37402) fix(VenuePlaylist): fix margin issues

---

__snapshots__/features/profile/pages/MandatoryUpdatePersonalData/MandatoryUpdatePersonalData.native.test.tsx.native-snap
__snapshots__/features/profile/pages/MandatoryUpdatePersonalData/ProfileInformationValidationUpdate.native.test.tsx.native-snap
src/features/profile/pages/MandatoryUpdatePersonalData/MandatoryUpdatePersonalData.native.test.tsx
src/features/profile/pages/MandatoryUpdatePersonalData/MandatoryUpdatePersonalData.tsx
src/features/profile/pages/MandatoryUpdatePersonalData/ProfileInformationValidationUpdate.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37385
I have:
| Desktop - Chrome |  <img width="500" height="937" alt="Capture d’écran 2025-08-14 à 16 35 54" src="https://github.com/user-attachments/assets/655c8703-1827-4fc8-8b06-33ff03c870c1" /> <img width="499" height="935" alt="Capture d’écran 2025-08-14 à 16 36 05" src="https://github.com/user-attachments/assets/4f31925a-6b50-4cfe-ad76-30e4f06b90b7" /> |  <img width="500" …

(PC-37385) feat(profile): udpate informations in MandatoryUpdatePersonalData screens

---

__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
src/features/search/pages/ThematicSearch/ThematicSearch.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37422
I have:
| Desktop - Chrome | <img width="221" height="467" alt="Capture d’écran 2025-08-21 à 12 28 47" src="https://github.com/user-attachments/assets/d33c2b45-f8c6-4050-a906-17785f49a0be" /> | <img width="217" height="465" alt="Capture d’écran 2025-08-21 à 12 25 22" src="https://github.com/user-attachments/assets/f9b3ddf4-aa1f-4b82-8bec-1ef5533c0576" /> |

(PC-37422) fix(ThematicSearch): increase page bottom margin

---

src/features/venueMap/pages/VenueMap/VenueMap.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37532
I have:
Before :
https://github.com/user-attachments/assets/105301f3-ecfa-434d-b5cb-51ea2064929a
After :
https://github.com/user-attachments/assets/02156688-5cd4-43f2-b7b4-5540fd50a15f
<details> …

(PC-37532) fix(venueMap): use good location depending on the location mode

---

package.json
src/features/navigation/NavigationContainer/NavigationContainer.tsx
yarn.lock

Add react-navigation-devtools to help track the navigation state and actions in the app.

(BSR) feat(Navigation): add react-navigation devtools

---

__snapshots__/features/profile/pages/TrackEmailChange/TrackEmailChange.native.test.tsx.native-snap
src/cheatcodes/pages/features/profile/CheatcodesNavigationProfile.tsx
src/features/profile/pages/TrackEmailChange/TrackEmailChangeContent.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37633
I have:
| iOS              |      <img width="1170" height="2532" alt="Simulator Screenshot - iPhone 14 - 2025-08-27 at 12 39 14" src="https://github.com/user-attachments/assets/5bd128f4-4859-48b8-9507-a5fdea1e9778" />        |   <img width="1170" height="2532" alt="Simulator Screenshot - iPhone 14 - 2025-08-27 at 12 39 11" src="https://github.com/user-attachments/assets/6b69bea8-05de-4184-a0f9-35ffebf69c1f" />   |
| Desktop - …

(PC-37633) feat(profile): fix TrackEmailChange design

---

.maestro/README.md
.maestro/tests/subFolder/auth/LoginFromFavorites.yml
.maestro/tests/subFolder/auth/LoginFromPhysicalOffer.yml
.maestro/tests/subFolder/auth/LoginWithWrongEmail.yml
.maestro/tests/subFolder/auth/LoginWithWrongPassword.yml
.maestro/tests/subFolder/booking/BookDigitalOffer.yml
.maestro/tests/subFolder/booking/BookMusicalOffer.yml
.maestro/tests/subFolder/booking/BookPhysicalOffer.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37708
I have:

(PC-37706) fix(e2e): update digital booking funnel test

---

src/ui/components/Accordion.tsx
src/ui/theme/customFocusOutline/touchableFocusOutline.web.test.tsx
src/ui/theme/customFocusOutline/touchableFocusOutline.web.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37485
I have:
| Desktop - Chrome |               | <img width="1728" height="958" alt="Capture d’écran 2025-09-05 à 17 57 16" src="https://github.com/user-attachments/assets/e101e124-fede-47a7-b49f-f45dab8fa810" /> <img width="1728" height="959" alt="Capture d’écran 2025-09-05 à 17 57 08" src="https://github.com/user-attachments/assets/01dc161e-175e-484e-893c-e5eac7b09bf3" /> <img …

(PC-37485) feat(ui): fix focus outline

---

__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
package.json
src/features/home/components/modules/OffersModule.tsx
src/features/home/pages/GenericHome.tsx
src/shared/IntersectionObserver/IntersectionObserver.native.test.tsx
src/shared/IntersectionObserver/IntersectionObserver.tsx
src/shared/IntersectionObserver/IntersectionObserver.web.test.tsx
src/shared/IntersectionObserver/IntersectionObserver.web.tsx
src/shared/IntersectionObserver/helpers.test.ts
src/shared/IntersectionObserver/helpers.ts
src/shared/IntersectionObserver/types.ts
src/shared/analytics/logViewItem.ts
yarn.lock

Architecture et organisation du code :
- ✨ Création d'une version web spécifique (IntersectionObserver.web.tsx) utilisant l'API native du
navigateur
- 📦 Extraction de la fonction parseThreshold depuis types.ts vers un nouveau fichier helpers.ts pour une
meilleure séparation des responsabilités
- 🧪 Ajout de tests unitaires complets pour les versions web et native
Améliorations fonctionnelles :
- 🔍 Ajout de logs de debug pour le tracking des playlists (désactivables via feature flag)
- 📊 Amélioration du système de tracking des modules visibles dans les pages d'accueil
- 🎯 Gestion dynamique du threshold basée sur la hauteur réelle du conteneur (avec fallback)
- ⚡ Optimisation de la détection d'intersection sur web et native
Corrections :
- 🐛 Correction du calcul des pourcentages pour le …

(PC-36427) feat(interesectionobserver): refacto intersection observer

---

.maestro/tests/subFolder/auth/LoginWithWrongEmail.yml
.maestro/tests/subFolder/auth/LoginWithWrongPassword.yml
.maestro/tests/subFolder/auth/SignupFromProfile.yml
.maestro/tests/subFolder/booking/BookDigitalOffer.yml
.maestro/tests/subFolder/booking/BookMusicalOffer.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37802
I have:

(PC-37802) fix(e2e): update wording in booking and search funnel

---

.github/workflows/dev_on_schedule_testing_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37779
- Use Storybook
- Use pair programming/mobs
</details>

(PC-37779) feat(App): deploy testing daily

---

.github/workflows/dev_on_schedule_testing_deploy.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37779
I have:

(PC-37779) fix(ci): second attempt

---

.github/workflows/dev_on_schedule_deploy_testing_tag.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37910
I have:

(PC-37910) fix(ci): refactor cron for automated testing hard deploy

---

__snapshots__/features/bookings/pages/Bookings/Bookings.native.test.tsx.native-snap
__snapshots__/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx.native-snap
src/features/bookings/components/OnGoingBookingsList.native.test.tsx
src/features/bookings/components/OnGoingBookingsList.tsx
src/features/bookings/helpers/v2/getBookingLabels.test.ts
src/features/bookings/helpers/v2/getBookingLabels.ts
src/features/bookings/pages/Bookings/Bookings.native.test.tsx
src/features/bookings/pages/Bookings/Bookings.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.tsx
src/features/bookings/queries/selectors/convertOffererDatesToTimezone.test.ts
src/features/bookings/queries/selectors/convertOffererDatesToTimezone.ts
src/features/bookings/queries/selectors/findOngoingOrEndedBooking.test.ts
src/features/bookings/queries/selectors/findOngoingOrEndedBooking.ts
src/features/bookings/queries/useOngoingOrEndedBookingQuery.ts
src/features/offer/queries/useGetRemindersQuery.test.ts
src/fixtures/booking.ts
src/libs/parsers/formatDates.ts
src/queries/bookings/useBookingsQuery.ts
src/tests/mockBuilder.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37546
I have:
<details>
If you …

(PC-37546) fix(Bookings): add timezone

---

src/features/bookOffer/components/BookDuoChoice.native.test.tsx
src/features/bookOffer/components/BookHourChoice.native.test.tsx
src/features/bookOffer/components/BookHourChoice.tsx
src/features/bookOffer/components/BookingDetails.native.test.tsx
src/features/bookOffer/components/BookingDetails.tsx
src/features/bookOffer/components/BookingEventChoices.native.test.tsx
src/features/bookOffer/components/BookingInformations.native.test.tsx
src/features/bookOffer/components/BookingInformations.tsx
src/features/bookOffer/components/CancellationDetails.native.test.tsx
src/features/bookOffer/components/CancellationDetails.tsx
src/features/bookOffer/components/DuoChoiceSelector.tsx
src/features/bookOffer/helpers/useBookingOffer.tsx
src/features/bookOffer/helpers/useBookingStock.tsx
src/features/bookOffer/helpers/useModalContent.native.test.tsx
src/features/bookOffer/helpers/useModalContent.tsx
src/features/bookOffer/pages/BookingOfferModal.native.test.tsx
src/features/bookOffer/pages/BookingOfferModal.web.test.tsx
src/features/bookings/components/OnGoingBookingsList.native.test.tsx
src/features/bookings/components/OnGoingBookingsList.tsx
src/features/bookings/pages/Bookings/Bookings.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.web.test.tsx
src/features/bookings/queries/selectors/convertOffererDatesToTimezone.test.ts
src/features/home/pages/Home.tsx
src/features/offer/queries/selectors/convertOffererDatesToTimezone.ts
src/queries/offer/selectors/convertOfferDatesToTimezone.test.ts
src/queries/offer/selectors/convertOfferDatesToTimezone.ts
src/queries/offer/useBookingOfferQuery.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37991
I have:
| Desktop - Chrome | <img width="480" height="361" alt="Capture d’écran 2025-09-23 à 16 16 46" src="https://github.com/user-attachments/assets/05beb364-ba8b-405c-b0f6-3d6db06659b8" /> | <img width="498" height="375" alt="Capture d’écran 2025-09-23 à 16 15 49" src="https://github.com/user-attachments/assets/5209cc4d-148b-4f85-9e5e-1492a7df4a80" /> |

(PC-37991) feat(Offer): add timezone to booking journey

---

src/features/bookings/pages/EndedBookings/EndedBookings.native.test.tsx
src/features/bookings/pages/EndedBookings/EndedBookings.tsx
src/features/reactions/helpers/addReactionsToBookings/addReactionsToBookings.ts
src/features/reactions/queries/useReactionMutation.test.ts
src/features/reactions/queries/useReactionMutation.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-38068
I have:
https://github.com/user-attachments/assets/069bd8ac-50ae-4269-913e-22914f7e0574
<details>
- In the production code: remove type assertions with `as` (type assertions are removed at compile-time, there is no runtime checking associated with a type assertion. There won’t be an exception or `null` generated if the type assertion is wrong). In certain …

(PC-38068) fix(Reactions): fix the possibility ton react on Offer/EndedBookings

---

src/features/bookings/queries/useOngoingOrEndedBookingQuery.native.test.ts
src/features/gtlPlaylist/queries/useGTLPlaylistsQuery.native.test.ts
src/features/navigation/RootNavigator/RootStackNavigator.native.test.tsx
src/features/offer/components/OfferCTAButton/OfferCTAButton.native.test.tsx
src/features/offer/components/OfferContent/OfferContent.native.test.tsx
src/features/offer/components/OfferContent/OfferContentBase.tsx
src/libs/analytics/logEventAnalytics.ts
src/queries/bookings/useEndedBookingFromOfferIdQuery.native.test.ts
src/queries/venueMap/useVenuesInRegionQuery.native.test.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-38067
I have:
<details> …

(PC-38067) feat(offer): add categoryName param to ClickInfoReview log

---

src/features/bookings/components/Ticket/Ticket.tsx
src/features/bookings/components/Ticket/TicketTopPart.native.test.tsx
src/features/bookings/components/Ticket/TicketTopPart.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37899
I have:
| iOS              |<img width="1179" height="2556" alt="Simulator Screenshot - iPhone 16 - 2025-09-24 at 15 12 32" src="https://github.com/user-attachments/assets/18f34a8c-2844-4e57-8b4f-cdf77f9a3a6a" />|<img width="1179" height="2556" alt="Simulator Screenshot - iPhone 16 - 2025-09-24 at 15 12 17" src="https://github.com/user-attachments/assets/62b23812-8b75-483b-88ec-aeb8bf242fa3" />|
| Desktop - Chrome |<img width="1512" height="735" alt="Capture d’écran 2025-09-24 à 15 16 18" …

(PC-37899) feat(booking): add user firstname and lastname on booking

---

src/features/home/components/modules/OffersModule.native.test.tsx
src/features/home/types.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildFacetFilters.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/buildOfferSearchParameters.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.test.ts
src/libs/algolia/fetchAlgolia/buildAlgoliaParameters/helpers/buildFacetFiltersHelpers/buildFacetFiltersHelpers.ts
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.native.test.ts
src/libs/algolia/fetchAlgolia/fetchMultipleOffers/helpers/adaptOffersPlaylistParameters.ts
src/libs/algolia/fetchAlgolia/utils.test.ts
src/libs/algolia/fetchAlgolia/utils.ts
src/libs/algolia/types.ts
src/libs/contentful/types.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-36212
I have:
| Platform         | Config | Result |
| iOS              |<img width="1512" height="730" alt="Capture d’écran 2025-09-23 à 16 45 24" src="https://github.com/user-attachments/assets/f67865ed-0652-4754-8e5c-588e8a16d70a" />|<img width="1179" height="2556" alt="simulator_screenshot_2256672E-D36F-4CC2-A411-D221490A9765" src="https://github.com/user-attachments/assets/e01cd1ff-47d2-4717-8f3c-ed8bc9d5f756" />|
| Desktop - Chrome |<img width="1512" height="730" alt="Capture d’écran 2025-09-23 à 16 45 24" src="https://github.com/user-attachments/assets/f67865ed-0652-4754-8e5c-588e8a16d …

(PC-36212) feat(home): add allocine ids params for offer playlist

---

src/features/venueMap/pages/VenueMap/VenueMap.native.test.tsx

Création du ticket:
https://passculture.atlassian.net/browse/PC-38119

(BSR) chore(test): skip flaky test in VenueMap

---

.github/workflows/dev_on_workflow_call_e2e_android.yml
.github/workflows/dev_on_workflow_call_e2e_ios.yml
.maestro/tests/CookiesPolicy.yml
.maestro/tests/FavoriteJourney.yml
.maestro/tests/SearchJourney.yml
.maestro/tests/subFolder/booking/CheckDetailPage.yml
.maestro/tests/subFolder/favorite/AddToFavorite.yml
.maestro/tests/subFolder/profil/DeletionReactivation.yml
.maestro/tests/subFolder/profil/LegalInfoSection.yml
.maestro/tests/subFolder/profil/SocialNetwork.yml
.maestro/tests/subFolder/search/SearchBookableCinemaOffer.yml
.maestro/tests/subFolder/venue/AccessPreviewModule.yml
.maestro/tests/subFolder/venue/AccessVenueMapFromSearchResult.yml

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-38052
I have:
Ajout de 3 tests déjà présent dans la couverture Android :
- **CookiesPolicy** (teste l'écran de choix des cookies)
- **FavoriteJourney** (teste l'ajout et suppression des favs)
- **SearchJourney** (teste la search sans résultats et avec résultats cohérents)
- Augmentation du timeout des jobs E2E pour avoir du vert si tout les tests passent et pas seulement la moitié de la run
- Clean du cache du runner avant le build

(PC-38052) feat(e2e): increase ios e2e coverage and update wording in search funnel

---

__snapshots__/features/bookings/pages/BookingDetails/BookingDetails.native.test.tsx.native-snap
__snapshots__/features/home/pages/ThematicHome.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobileAndroid.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.native.test.tsx.native-snap
__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.native.test.tsx.native-snap
__snapshots__/features/profile/pages/TutorialAgeInformationCredit/ProfileTutorialAgeInformationCredit.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchLanding/SearchLanding.native.test.tsx.native-snap
__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
__snapshots__/features/search/pages/ThematicSearch/ThematicSearch.native.test.tsx.native-snap
__snapshots__/features/venue/pages/Venue/Venue.native.test.tsx.native-snap
doc/decision-records/DR009 - accessibility-audit.md
src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileBase.tsx
src/features/profile/pages/Accessibility/AccessibilityDeclarationWeb.tsx
src/features/search/components/NumberOfResults/NumberOfResults.tsx
src/features/search/components/SearchTitleAndWidget/SearchTitleAndWidget.tsx
src/features/subscription/components/ThematicSubscriptionBlock.tsx
src/features/venue/components/PracticalInformation/PracticalInformation.tsx
src/ui/components/headers/ContentHeader.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-38205
I have:
| iOS              |   <img width="1093" height="766" alt="Capture d’écran 2025-10-02 à 08 04 55" src="https://github.com/user-attachments/assets/d489b183-3a25-4f22-bb1b-836d9ef88754" />  <img width="1094" height="768" alt="Capture d’écran 2025-10-02 à 08 08 32" src="https://github.com/user-attachments/assets/6d176915-4577-4494-b960-bcc182722c7d" /> <img width="1094" height="765" alt="Capture d’écran 2025-10-02 à 08 10 32" src="https://github.com/user-attachments/assets/9809be82-643c-403f-84ee-5814dca15c …

(PC-38205) feat(a11y): add new heading in AccessibilityDeclaration

---

__snapshots__/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.native.test.tsx.native-snap
doc/decision-records/DR009 - accessibility-audit.md
src/features/profile/pages/Accessibility/AccessibilityDeclarationMobileIOS.tsx

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-38208
I have:

(PC-38208) feat(a11y): update iOS accessiblity value

---

.maestro/tests/subFolder/auth/LoginGoogleFromProfil.yml
.maestro/tests/subFolder/auth/SignupFromProfile.yml
.maestro/tests/subFolder/booking/BookCinemaOffer.yml
.maestro/tests/subFolder/booking/BookDuoOffer.yml
.maestro/tests/subFolder/booking/BookMusicalOffer.yml
.maestro/tests/subFolder/booking/BookPhysicalOffer.yml
.maestro/tests/subFolder/commons/GoToBookingFromVenue.yml

(BSR) fix(e2e): update checkbox required label

---

__snapshots__/features/search/pages/SearchResults/SearchResults.native.test.tsx.native-snap
src/features/search/components/SearchList/SearchList.tsx
src/features/search/components/SearchList/SearchList.web.tsx
src/features/search/components/SearchListHeader/SearchListHeader.tsx
src/features/search/components/SearchListItem.web.tsx
src/features/search/components/SearchResultsContent/SearchResultsContent.tsx
src/features/search/pages/SearchResults/SearchResults.tsx
src/features/search/types.ts
src/shared/tracking/TrackingManager.ts
src/shared/tracking/__tests__/useViewableItemsTracker.test.ts
src/shared/tracking/usePageTracking.ts
src/shared/tracking/useViewableItemsTracker.ts

Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-37507
I have:
<details> …

(PC-37507) feat(search): use viewable items tracking for search results playlist
