pass-culture/pass-culture-app-native

src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/__tests__/BookHourChoice.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookHourChoice.test.tsx.snap, src/features/bookOffer/components/tests/__snapshots__/BookingEventChoices.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6701
I have:
=> (PC-6701) debounce selected hour

.env.staging, .env.testing, src/features/favorites/atoms/Favorite.tsx, src/ui/components/buttons/AppButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7023
I have:
=> (PC-7023) Affichage des boutons "Réserver" pour chaque favori sur l'écran des favoris

src/features/auth/AuthContext.tsx, src/features/profile/pages/Profile.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6900
I have:
=> (PC-6900) logout: remove identifier from batch when user logs out

src/features/profile/pages/ConsentSettings.test.tsx, src/features/profile/pages/ConsentSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7532
I have:
=> (PC-7532) ConsentSettings: goBack on press save

jest/jest.setup.ts, src/features/favorites/atoms/__tests__/BicolorFavoriteCount.test.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/favorites/pages/__mocks__/FavoritesWrapper.tsx, src/features/favorites/pages/__tests__/useFavorites.test.tsx, src/features/favorites/pages/__tests__/useFavoritesResults.test.tsx, src/features/offer/components/__tests__/OfferHeader.test.tsx, src/features/offer/pages/tests/Offer.analytics.test.tsx, src/features/offer/pages/tests/Offer.test.tsx, src/features/offer/pages/tests/renderOfferPageTestUtil.tsx, src/tests/reactQueryProviderHOC.tsx
=> (Tech) improve favorite tests and clean warnings

src/features/navigation/TabBar/TabNavigator.tsx, src/features/navigation/TabBar/__tests__/TabNavigator.test.tsx, src/features/navigation/TabBar/helpers.ts, src/features/navigation/TabBar/types.ts, src/features/profile/pages/NotificationSettings.test.tsx, src/features/profile/pages/NotificationSettings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7397
I have:
- [-] Added a **screenshot** for UI tickets.
=> (PC-7397) Conditional displaying of the bookings icon in the tabbar

src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/BookingEventChoices.tsx, src/features/bookOffer/components/__tests__/BookingDetails.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookingDetails.test.tsx.snap, src/features/bookOffer/fixtures/offer.ts, src/features/bookOffer/services/useModalContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7570
=> (PC-7570) Add initilization of state when offer is thing

src/features/bookOffer/components/__tests__/__snapshots__/BookingDetails.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7570
I have:
=> (PC-7570) fix snapshot

.env.production, .env.staging, .env.testing
=> (PC-7594) Modify CGU and Privacy Policy URLs

src/features/auth/forgottenPassword/ReinitializePassword.test.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent.test.tsx, src/features/auth/forgottenPassword/ResetPasswordExpiredLink.test.tsx, src/features/auth/login/Login.test.tsx, src/features/auth/signup/SignupConfirmationExpiredLink.test.tsx, src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.test.tsx, src/features/favorites/atoms/__tests__/BicolorFavoriteCount.test.tsx, src/features/home/components/tests/BusinessModule.test.tsx, src/features/home/pages/tests/Home.test.tsx, src/features/navigation/__tests__/useGetInitialScreenConfig.test.tsx, src/features/offer/components/__tests__/OfferHeader.test.tsx, src/features/offer/pages/tests/OfferDescription.test.tsx, src/features/profile/pages/ChangePassword.test.tsx, src/features/profile/pages/PersonalData.test.tsx, src/features/profile/pages/Profile.test.tsx, src/tests/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6360
Task: Clean `console` usage in test history 
I have:
=> (PC-6360) App Native - Améliorations tech - Supprimer / ignorer les warnings affichés durant l'execution des tests

src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap, src/features/profile/pages/__snapshots__/ChangePassword.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6360
I have:
=> Fix snapshots

src/features/offer/components/__tests__/OfferHeader.test.tsx
=> Temporary fix for favorites : skip all tests using react query cache

src/api/gen/api.ts, src/features/bookings/api.ts, src/features/bookings/api/bookingsSnap.ts, src/features/bookings/pages/Bookings.test.tsx, src/features/bookings/pages/Bookings.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/features/profile/pages/NotificationSettings.test.tsx, src/tests/server.ts, src/ui/components/headers/SvgPageHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7399
I have:
| ![image](https://user-images.githubusercontent.com/6025710/111339696-42368980-8678-11eb-8171-4eb93e134aa4.png) |                          |                       |                       |
=> (PC-7399) Fetch bookings & display count

doc/standards/testStrategy.md
=> (Tech) improve test strategy documentation

src/features/auth/forgottenPassword/ResetPasswordEmailSent.test.tsx, src/features/auth/forgottenPassword/__snapshots__/ForgottenPassword.test.tsx.snap, src/features/auth/login/__snapshots__/Login.test.tsx.snap, src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetEmail.test.tsx, src/features/auth/signup/SetPassword.test.tsx, src/features/auth/signup/__snapshots__/SetBirthday.test.tsx.snap, src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/home/services/useAvailableCredit.ts, src/features/offer/pages/tests/__snapshots__/Offer.test.tsx.snap, src/features/profile/pages/NotificationSettings.test.tsx, src/features/search/atoms/Buttons/__tests__/ShowResults.test.tsx, src/features/search/pages/__tests__/__snapshots__/SearchFilter.test.tsx.snap, src/ui/components/buttons/ButtonPrimary.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7149
I have:
| \*iOS - [Phone name] | \*Android - [S9] | Tablet - [Phone name] | Little - [Phone name] |
|                      | ![image](https://user-images.githubusercontent.com/77674046/111338429-38605680-8677-11eb-9389-572955a19da9.png) |                       |                       |
=> (PC-7149) App native - Favoris - Bouton "Crédit insuffisant"

src/features/bookOffer/atoms/ChoiceBloc.tsx, src/features/bookOffer/atoms/HourChoice.tsx, src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/__tests__/BookHourChoice.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookHourChoice.test.tsx.snap, src/features/bookOffer/fixtures/offer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6699
I have:
| \*iOS - [Phone name] | \*Android - [Phone name] | Little - [Phone name] | Maquette |
| -------------------- | :----------------------: | :--------------------: | ----------------------: |
| ![image](https://user-images.githubusercontent.com/50346870/111351055-0f45c300-8683-11eb-81a9-a2791b1d40a8.png) | ![image](https://user-images.githubusercontent.com/50346870/111350890-e0c7e800-8682-11eb-99f6-c475868e232d.png) | ![image](https://user-images.githubusercontent.com/50346870/111350969-f5a47b80-8682-11eb-917c-dc2e5e78fa02.png) | ![image](https://user-images.githubusercontent.com/50346870/111351405-6ea3d300-8683-11eb-939f-230fc87a4948 …
=> (PC-6699) unavailable hour booking offer

.env.production, .env.staging, .env.testing, jest/jest.setup.ts, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.test.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicyModal.test.tsx.snap, src/features/profile/pages/ConsentSettings.test.tsx, src/features/profile/pages/ConsentSettings.tsx, src/libs/environment/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6827
I have:
=> (PC-6827) App native - Tutoriels & Typeform - Ajouter le lien vers la politique de cookies

ios/PassCulture-tvOS/Info.plist, ios/PassCulture/Info.plist
=> Add ios missing key

src/features/bookOffer/components/BookDuoChoice.tsx, src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/BookingEventChoices.tsx, src/features/bookOffer/components/__tests__/BookHourChoice.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookHourChoice.test.tsx.snap, src/features/bookOffer/components/tests/BookingEventChoices.test.tsx, src/features/bookOffer/components/tests/__snapshots__/BookingEventChoices.test.tsx.snap, src/features/bookOffer/pages/__tests__/reducer.test.ts, src/features/bookOffer/pages/reducer.ts, src/features/bookOffer/services/useModalContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7469
I have:
=> (PC-7469) solo duo section behavior

src/features/bookOffer/components/__tests__/BookingDetails.test.tsx, src/features/bookOffer/services/__tests__/useBookOfferMutation.test.ts, src/features/bookOffer/services/useBookOfferMutation.ts
c'est la même route, mais avec un nom plus standard
=> Renaming: use post /bookings route instead of /book_offer

src/features/bookings/pages/Bookings.tsx, src/locales/fr/messages.po, src/tests/setupTests.js
=> Fix jest setup file to prevent the crash of the translation script

src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.test.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.test.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7608
I have:
=> (PC-7608) App native - Tutoriels - Désactiver les trackers quand l'utilisateur clique sur la Croix de la modale

package.json, src/features/deeplinks/routing.test.ts, src/features/deeplinks/routing.ts, src/features/deeplinks/types.ts, src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/home/atoms/OfferTile.tsx, src/features/home/atoms/tests/OfferTile.test.tsx, src/features/home/components/ExclusivityModule.tsx, src/features/home/components/tests/ExclusivityModule.test.tsx, src/features/navigation/RootNavigator/types.ts, src/features/offer/components/OfferHeader.tsx, src/features/offer/components/__tests__/OfferHeader.test.tsx, src/features/search/atoms/Hit.tsx, src/features/search/atoms/__tests__/Hit.test.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts, src/ui/components/modals/ModalHeader.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7028
Also:
- https://passculture.atlassian.net/browse/PC-7179
I have:
=> (PC-7028) App native - Favoris - Tracking ajout de favoris (recherche, home, deeplink)

src/features/auth/forgottenPassword/ForgottenPassword.test.tsx, src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent.tsx, src/features/auth/forgottenPassword/__snapshots__/ForgottenPassword.test.tsx.snap, src/features/auth/signup/AcceptCgu.test.tsx, src/features/auth/signup/AcceptCgu.tsx, src/features/auth/signup/SignupConfirmationEmailSent.tsx, src/features/navigation/RootNavigator/types.ts, src/libs/recaptcha/ReCaptcha.test.tsx, src/libs/recaptcha/ReCaptcha.tsx, src/libs/recaptcha/__snapshots__/ReCaptcha.test.tsx.snap, src/libs/recaptcha/webviewHTML.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7595
I have:
=> (PC-7595) ReCAPTCHA : rerender component after first try + block back navigation

src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXX ==> N/A
I have:
=> Typing useNavigation : be more precised with respect to type of navigator used

src/api/gen/api.ts, src/features/bookOffer/fixtures/offer.ts, src/features/bookings/api/bookingsSnap.ts, src/features/home/atoms/OfferTile.tsx, src/features/home/atoms/tests/OfferTile.test.tsx, src/features/offer/api/snaps/offerResponseSnap.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7027
I have:
=> (PC-7027) Update bookOffer, booking and favorite APIs

src/features/bookOffer/pages/BookingOfferModal.tsx, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicyModal.test.tsx.snap, src/features/home/pages/tests/__snapshots__/Home.test.tsx.snap, src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap, src/features/offer/pages/tests/__snapshots__/Offer.test.tsx.snap, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7348
I have:
=> (PC-7348) spike scrollview modal 

src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx
=> (PC-7701) Fix goback from ConsentSetting page to Achievements

ios/PassCulture/PassCulture.entitlements, src/features/deeplinks/utils.test.ts, src/features/deeplinks/utils.ts, src/features/home/components/tests/BusinessModule.utils.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7092
I have:
=> (PC-7092) Migration vers universal links sur Staging et Production

src/libs/parsers/formatDates.ts, src/libs/parsers/tests/formatDates.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7671
I have:
=> (PC-7671) Mauvaise concaténation sur certaines dates

src/features/favorites/atoms/BicolorFavoriteCount.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7149
I have:
=> (PC-7149) App native - Favoris - Bouton Crédit insuffisant

src/features/auth/hooks/useKeyboardAdjustFixIdCheck.android.ts, src/features/auth/hooks/useKeyboardAdjustFixIdCheck.d.ts, src/features/auth/hooks/useKeyboardAdjustFixIdCheck.ios.ts, src/features/auth/signup/IdCheck.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7593
I have:
=> (PC-7593) App native - Inscription - Arrêt du parcours ID Check à l'étape de profil

src/features/auth/forgottenPassword/ForgottenPassword.test.tsx, src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent.test.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent.tsx, src/features/auth/signup/AcceptCgu.test.tsx, src/features/auth/signup/AcceptCgu.tsx, src/features/auth/signup/SignupConfirmationEmailSent.test.tsx, src/features/auth/signup/SignupConfirmationEmailSent.tsx, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7595
I have:
=> (PC-7595) Do not display back button if previous screen was using reCAPTCHA (i.e. AcceptCgu and ForgottenPassword)

src/features/auth/AuthContext.tsx, src/features/auth/login/Login.test.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7574
I have:
=> [PC-7574] Rattacher les événements firebase à l'userID

src/features/bookOffer/atoms/HourChoice.tsx, src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/__tests__/BookHourChoice.test.tsx, src/features/bookOffer/components/__tests__/BookingEventChoices.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookHourChoice.test.tsx.snap, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6700
I have:
=> (PC-6700) Show hours where the credit is not enough

src/api/gen/api.ts, src/features/favorites/api/snaps/favorisResponseSnap.ts, src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/offer/services/__tests__/useHasEnoughCredit.test.ts, src/features/offer/services/useHasEnoughCredit.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7027
I have:
| \*iOS - iPhone 11 |
| <img width="349" alt="Capture d’écran 2021-03-22 à 11 55 16" src="https://user-images.githubusercontent.com/22399093/111979536-7b05b100-8b05-11eb-9b6a-e13ebd3b14a7.png">  |
=> (PC-7027) Add expired and exhausted offers cases to favorite's booking button displays

src/features/bookOffer/atoms/ChoiceBloc.tsx, src/features/bookOffer/atoms/DuoChoice.tsx, src/features/bookOffer/atoms/HourChoice.tsx, src/features/bookOffer/components/BookDuoChoice.tsx, src/features/bookOffer/components/__tests__/BookDuoChoice.test.tsx, src/features/bookOffer/components/__tests__/BookHourChoice.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookDuoChoice.test.tsx.snap, src/features/bookOffer/components/__tests__/__snapshots__/BookingEventChoices.test.tsx.snap, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6703
I have:
| ![image](https://user-images.githubusercontent.com/50346870/112143486-39920600-8bd8-11eb-9498-432c2ff3b2fc.png) | ![image](https://user-images.githubusercontent.com/50346870/112143528-47478b80-8bd8-11eb-8e6a-4fe434668339.png) |
=> (PC-6703) insuffisant credit duo section

src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookingImpossible.test.tsx.snap, src/features/offer/components/OfferHeader.tsx, src/features/offer/components/__tests__/OfferHeader.test.tsx, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6718
I have:
=> (PC-6718) Ability to favourite an offer from the BookingImpossible page

src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/components/Calendar/Calendar.tsx, src/features/bookOffer/components/Calendar/DayComponent.tsx, src/features/offer/pages/tests/__snapshots__/Offer.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7288
I have:
| \*iOS - [Phone name] |
| ![image](https://user-images.githubusercontent.com/50346870/112168765-e2009400-8bf1-11eb-995c-07bfbd3661d1.png) |
=> (PC-7288) sparkles booking offer

src/api/gen/api.ts, src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/home/api.test.ts, src/features/offer/components/__tests__/OfferIconCaptions.test.tsx, src/features/profile/components/ProfileHeader.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7652
I have:
| \*iOS - iPhone 11 | 
| <img width="341" alt="Capture d’écran 2021-03-23 à 17 58 06" src="https://user-images.githubusercontent.com/22399093/112186378-5b53b300-8c01-11eb-99f0-fd6e471b4172.png">  |
=> (PC-7652) Favorites screen : add booked offer display to favorite item

src/features/favorites/atoms/Buttons/Sort.tsx, src/features/favorites/atoms/Buttons/__tests__/Sort.test.tsx, src/features/favorites/atoms/Favorite.tsx, src/features/favorites/components/FavoritesResults.tsx, src/features/favorites/components/__tests__/FavoritesResults.test.tsx, src/features/favorites/pages/Favorites.tsx, src/features/favorites/pages/FavoritesSorts.tsx, src/features/favorites/pages/FavoritesWrapper.tsx, src/features/favorites/pages/__tests__/Favorites.test.tsx, src/features/favorites/pages/__tests__/FavoritesSorts.test.tsx, src/features/favorites/pages/__tests__/__snapshots__/Favorites.test.tsx.snap, src/features/favorites/pages/__tests__/__snapshots__/FavoritesSorts.test.tsx.snap, src/features/favorites/pages/__tests__/reducer.test.ts, src/features/favorites/pages/__tests__/useFavoritesResults.test.tsx, src/features/favorites/pages/reducer.ts, src/features/favorites/pages/useFavoritesResults.ts, src/features/favorites/pages/utils/__tests__/sorts.test.ts, src/features/favorites/pages/utils/sorts.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/ui/svg/icons/Sort.tsx
(PC-7722) App native - Favoris - Tri par distance, prix et ajout récent
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7722
I have:
| \*iOS - [Phone name] | \*Android - [S9] | Tablet - [Phone name] | Little - [Phone name] |
|                      | ![image](https://user-images.githubusercontent.com/77674046/112133508-0fd2e200-8bcc-11eb-913e-313804640cd5.png) |                       |                       |
=> (PC-7722) App native - Favoris - Tri par distance, prix et ajout récent

src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/__tests__/BookingDetails.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6726
I have:
=> [PC-6723-6724-6725-6726] Tunnel de réservation - Réservation confirmée - Cas d'erreur 

src/api/gen/api.ts, src/features/bookOffer/fixtures/offer.ts, src/features/favorites/atoms/BookingButton.tsx, src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/BookingButton.test.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/favorites/components/FavoritesResults.tsx, src/features/home/atoms/OfferTile.tsx, src/features/home/atoms/tests/OfferTile.test.tsx, src/features/offer/api/snaps/offerResponseSnap.ts, src/features/offer/components/__tests__/OfferIconCaptions.test.tsx, src/features/offer/services/useCtaWordingAndAction.testsFixtures.ts, src/features/profile/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXX ==> NA
I have:
=> Refacto favorite item + new fields on offers and stocks

src/features/bookings/pages/Bookings.test.tsx
=> (Tech) fix test Bookings.test.tsx

src/libs/geolocation/GeolocationWrapper.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7756
I have:
=> (Tech) (PC-7756) App Native - Android - La position de l'utilisateur n'est pas actualisé

src/features/offer/components/OfferHeader.tsx, src/features/offer/components/__tests__/OfferHeader.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7677
I have:
=> (PC-7677): App native - Favoris - Afficher un message d'erreur à l'ajout des favoris si trop de favoris

.circleci/config.yml, package.json, scripts/deploy_new_production_version.sh, scripts/deploy_new_staging_version.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7239
I have:
=> [PC-7239] Config Circle auto deploy android prod hard

ios/PassCulture/Info.plist, src/ui/components/socials/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7622
I have:
=> (PC-7622) change url for facebook

src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.test.tsx, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicyModal.test.tsx.snap, src/features/home/pages/tests/__snapshots__/Home.test.tsx.snap, src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap, src/features/offer/pages/tests/__snapshots__/Offer.test.tsx.snap, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7739
I have:
=> (PC-7739) App native - Tutoriels - Ne pas autoriser le clic en dehors de la modale 'Respect de ta vie privée'

src/features/favorites/components/FavoritesResults.tsx, src/features/favorites/pages/utils/__tests__/sorts.test.ts, src/features/favorites/pages/utils/sorts.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7722
I have:
=> (PC-7722) App native - Favoris - Tri par distance, prix et ajout récent fix id desc

README.md, doc/deployment/deployment.md, scripts/deploy_new_production_version.sh, scripts/deploy_new_staging_version.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7239
I have:
=> [PC-7239] Remove force push on staging & production branches

src/features/profile/components/LoggedOutHeader.test.tsx, src/features/profile/components/LoggedOutHeader.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7694
I have:
=> (PC-7694) App Native - Profil - Tracking - Accès à la modale de souscription depuis profil

src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7696
I have:
=> (PC-7696) App Native - Profil - Tracking - Déconnexion

src/features/auth/forgottenPassword/ReinitializePassword.test.tsx, src/features/auth/forgottenPassword/ReinitializePassword.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7682
I have:
=> (PC-7682) App Native - Profil - Tracking - Changement de mot de passe

src/features/profile/pages/NotificationSettings.test.tsx, src/features/profile/pages/NotificationSettings.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7686
I have:
=> (PC-7686) App Native - Profil - Tracking - Activation/Desactivation de notifications

src/features/profile/components/LoggedOutHeader.test.tsx, src/features/profile/components/LoggedOutHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7694
I have:
\## Deploy hard
=> (PC-7694) App Native - Profil - Tracking - Accès à la modale de souscription depuis profil fix

src/features/bookings/components/OnGoingBookingItem.test.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7404
I have:
=> (PC-7404) Clicking on booking item redirects to the booking details page

package.json, src/App.tsx, yarn.lock
=> Fix intl bug for translations

src/libs/__mocks__/analytics.ts, src/libs/analytics.ts, src/libs/geolocation/components/GeolocationActivationModal.tsx, src/libs/geolocation/components/__tests__/GeolocationActivationModal.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7685
I have:
=> (PC-7685) App Native - Profil - Tracking - Redirection dans les réglages systèmes depuis la modale géolocalisation

src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7695
I have:
=> (PC-7695) App Native - Profil - Tracking - Accès à l'ID check depuis profil non bénéficiaire

src/features/offer/components/OfferHeader.tsx, src/features/offer/components/__tests__/OfferHeader.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7499
I have:
| \*iOS - [Phone name] | 
| -------------------- | 
|                      |
=> (PC-7499) Offer page : do not display snackbar on successful removal of favorite

src/features/profile/components/BeneficiaryCeilings.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7808
Ticket Sherif
=> (PC-7808) Add text in ceilingsDescription

README.md, doc/deployment/deployment.md, scripts/deploy_new_staging_version.sh
=> Fix MES process

src/features/bookOffer/components/Calendar/Calendar.tsx, src/features/bookOffer/components/Calendar/useMarkedDates.ts, src/features/bookOffer/components/__tests__/Calendar.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7757
I have:
=> (PC-7757) calendar to first available date

src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/bookings/components/OnGoingTicket.tsx, src/ui/components/ClippedImage.tsx
=> (PC-7404) Fix alternative icons and subtitle

src/features/favorites/pages/FavoritesSorts.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7722
I have:
=> (PC-7722) App native - Favoris - Tri par distance, prix et ajout récent fix

src/features/auth/AuthContext.tsx, src/features/favorites/pages/useFavorites.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7820
I have:
=> (PC-7820) App native - Favoris - L'icône favoris est rempli sur certaines offres alors que je suis dans un état déconnecté

src/features/cheatcodes/pages/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6693
I have:
=> (PC-6693) remove calendar page

src/features/bookings/components/OnGoingBookingsList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7408?focusedCommentId=22023
I have:
|![Simulator Screen Shot - iPhone 12 - 2021-03-29 at 12 13 31](https://user-images.githubusercontent.com/22886846/112822708-91bd8200-9088-11eb-83c6-00bcd6b202ba.png)
=> (PC-7408) bookings: fix margin

src/features/offer/atoms/HeaderIcon.tsx, src/features/offer/components/OfferHeader.tsx, src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7499
I have:
=> (PC-7499) Add scale animation to favorite filled icon on offer screen

src/features/bookings/components/EndedBookingItem.test.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/EndedBookingList.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/components/types.ts, src/features/bookings/pages/EndedBookings.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7431
I have:
|![Simulator Screen Shot - iPhone 12 - 2021-03-26 at 16 59 40](https://user-images.githubusercontent.com/22886846/112675777-dd451580-8e67-11eb-94d1-7d4e9ef95fcc.png)|                          |                       |                       |
- if you want an hard deployment of the testing environment, use …
=> (PC-7431) liste des réservations terminées (sans design)

package.json, src/features/cheatcodes/pages/AppComponents.tsx, src/locales/fr/messages.po, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7472
I have:
|<img width="444" alt="image" src="https://user-images.githubusercontent.com/6025710/112847991-e6bcc080-90a7-11eb-8dc1-bba5ec7ca893.png">|                          |                       |                       | …
=> (PC-7472) SPIKE: component that generates QR codes from a string

src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7767
I have:
=> (PC-7767) App Native - Profil - Tracking - Scroll jusqu'en bas de la page

src/features/profile/pages/Profile.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7684
I have:
=> (PC-7684) App Native - Profil - Tracking - Activation/Desactivation de géolocalisation

src/features/bookings/components/BookingItemTitle.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/EndedBookingTicket.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/pages/EndedBookings.tsx, src/features/cheatcodes/pages/AppComponents.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7403
I have:
|![simulator_screenshot_D3F9D5F9-5093-4987-80BE-837190BC7956](https://user-images.githubusercontent.com/22886846/112682541-8728a000-8e70-11eb-9ecb-29b5e63de04c.png)![Simulator Screen Shot - iPhone 12 - 2021-03-29 at 16 51 18](https://user-images.githubusercontent.com/22886846/112861964-951b3280-90b5-11eb-901f-288288597d32.png)|                          |                       |                       |
If native code (ios/android) was …
=> (PC-7430) liste des réservations terminées: design

src/features/bookings/components/EndedBookingItem.test.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/EndedBookingList.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7432
I have:
=> (PC-7432) EndedBookings: navigate to offer page on press item

src/features/auth/api.ts, src/features/auth/login/Login.test.tsx, src/features/auth/login/Login.tsx, src/features/auth/login/__snapshots__/Login.test.tsx.snap
I have:
|        iphone 11                 |                       |                       |                       |
=> (PC-7861) Add specific error message when login rate limit is exceeded

src/features/favorites/components/FavoritesResults.tsx, src/features/favorites/pages/utils/sorts.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7856
I have:
=> (PC-7856) (Tech) App Native - Front - Les favoris expirés ne sont plus affichés en fin de la liste (Tri par distance)

src/features/bookings/components/BookingItemTitle.tsx, src/features/bookings/components/OnGoingBookingItem.tsx
=> (PC-7401) Fix date label width

src/features/auth/signup/IdCheck.test.tsx, src/features/auth/signup/IdCheck.tsx, src/features/auth/signup/__snapshots__/IdCheck.test.tsx.snap, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7844
I have:
=> (PC-7844) Add user_consent_data_collection query param to id check url

src/features/bookings/components/ThreeShapesTicket.tsx, src/features/cheatcodes/pages/AppComponents.tsx, src/ui/svg/TicketFooter.tsx, src/ui/svg/TicketHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7463
I have:
| <img width="380" alt="image" src="https://user-images.githubusercontent.com/6025710/113160066-6d56d680-923d-11eb-8576-089347e428e8.png"> | <img width="391" alt="image" src="https://user-images.githubusercontent.com/6025710/113159624-0b966c80-923d-11eb-9320-8cebaea4c92a.png"> |                       |                       |
If native code (ios/android) was modified, **after** the PR is merged, on the master branch, upgrade the **app …
=> (PC-7463) Create the 3 shapes ticket component

src/api/gen/api.ts, src/api/helpers.ts, src/features/auth/api.ts, src/features/auth/signup/VerifyEligibility.test.tsx, src/features/auth/signup/VerifyEligibility.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7880
I have:
=> [PC-7880] Affichage du crédit à 500€ sur l'écran de confirmation de création de compte

src/features/firstTutorial/pages/FirstTutorial/FirstTutorial.test.tsx, src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.test.tsx, src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7877
I have:
=> (PC-7877) Affichage du crédit à 500€ sur la 2ème carte tuto

src/api/gen/api.ts, src/features/bookings/api.ts, src/features/bookings/api/bookingsSnap.ts, src/features/bookings/api/queries.ts, src/features/bookings/components/BookingItemTitle.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/helpers.ts, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/Bookings.tsx, src/features/bookings/pages/EndedBookings.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7475
I have:
| <img width="703" alt="image" src="https://user-images.githubusercontent.com/6025710/113168996-7481e280-9245-11eb-9bc7-68864ee89739.png">|                          |                       |                       | …
=> (PC-7475) Display rules about the ticket based on the type of the offer

src/features/bookOffer/components/BookDateChoice.tsx, src/features/bookOffer/components/Calendar/Calendar.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7847
Pareil que #811 : **vérifier que l'intégration correspond à ce qui est demandé**
I have:
=> (PC-7847) App Native - Tunnel de résa - Tracking - Clic sur une date disponible

src/features/profile/pages/ChangePassword.test.tsx, src/features/profile/pages/ChangePassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7614
I have:
=> (PC-7614) fix incorrect password behavior

src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/favorites/components/FavoritesResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7499
I have:
=> (PC-7499) Divers fixes pour les favoris : enlever snackbar de succès, ne pas déclencher le scroll au changement du nombre de favoris

src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/pages/EndedBookings.tsx, src/features/favorites/pages/__tests__/__snapshots__/FavoritesSorts.test.tsx.snap, src/features/offer/pages/tests/__snapshots__/OfferDescription.test.tsx.snap, src/features/search/pages/__tests__/__snapshots__/Categories.test.tsx.snap, src/features/search/pages/__tests__/__snapshots__/LocationFilter.test.tsx.snap, src/features/search/pages/__tests__/__snapshots__/SearchFilter.test.tsx.snap, src/ui/components/headers/PageHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7430
I have:
|![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-01 at 10 51 41](https://user-images.githubusercontent.com/22886846/113297388-d6505400-92fa-11eb-9d56-9676717d1615.png)|![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-01 at 12 19 30](https://user-images.githubusercontent.com/22886846/113297400-d94b4480-92fa-11eb-8af5-e21a252ba877.png)|
|![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-01 at 12 25 …
=> (PC-7430) retours graphiques sur les listes de bookings + PageHeader

src/features/eighteenBirthday/pages/__snapshots__/EighteenBirthday.test.tsx.snap, src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.test.tsx, src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.tsx, src/features/eighteenBirthday/pages/components/__snapshots__/EighteenBirthdayCard.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7936
I have:
=> (PC-7936) Correct syntax of 'vérifier mon identité'

src/features/favorites/atoms/Buttons/__tests__/Sort.test.tsx, src/features/favorites/components/FavoritesResults.tsx, src/features/favorites/components/__tests__/FavoritesResults.test.tsx, src/features/favorites/pages/FavoritesSorts.tsx, src/features/favorites/pages/__tests__/FavoritesSorts.test.tsx, src/features/favorites/pages/__tests__/reducer.test.ts, src/features/favorites/pages/reducer.ts, src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXX ==> N/A
I have:
=> Remove notion of "filter" from favorites and use only notion of "sortBy"

src/features/favorites/components/FavoritesResults.tsx, src/features/search/atoms/FadeScrollingView.tsx, src/features/search/components/SearchResults.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7503
I have:
=> (PC-7503) fix filter button animation by renaming handleIsScrollingFactory

.circleci/config.yml
=> Fix staging (and prod and hotfix) trigger deployment

src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.test.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7851
I have:
=> (PC-7851) Affichage de la modale impossible de réserver une offre sous IOS

src/libs/i18n.ts
=> (Tech): switch i18n.plural to i18n._

src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/__tests__/BookingDetails.test.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7852
I have:
=> (PC-7852) Erreur conflit de réservation

src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.test.tsx, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7854
I have:
=> [PC-7854] Mise en favori depuis la modale offre numérique payante iOS

src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/YoungerBadge.test.tsx, src/features/profile/components/YoungerBadge.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7876
I have:
=> (PC-7876) Make YoungerBadge text depends on feature flag

src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7879
I have:
=> (PC-7879) Adapt text on Birthday modal with deposit amount

src/api/gen/api.ts, src/features/favorites/api/snaps/favorisResponseSnap.ts, src/features/favorites/atoms/BookingButton.tsx, src/features/favorites/atoms/__tests__/BookingButton.test.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/favorites/pages/utils/__tests__/sorts.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7919
I have:
=> (PC-7919) Favorite CTA button : display expired offer if isReleased is false

src/features/bookings/components/BookingPropertiesSection.test.tsx, src/features/bookings/components/BookingPropertiesSection.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/helpers.ts, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/locales/fr/messages.po, src/ui/components/SectionRow.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7476
I have:
|![simulator_screenshot_BEF241F3-1503-4EE1-B2F7-C52FCCDF09B8](https://user-images.githubusercontent.com/22886846/113432602-f6a50f00-93dd-11eb-96c2-27c6a6637ea8.png)|![Screenshot from 2021-04-02 09-33-42](https://user-images.githubusercontent.com/22886846/113393354-d736c380-9396-11eb-8ed1-f7671c50d229.png)|                       |                       |
If native code (ios/android) was modified, **after** the PR is merged, on the …
=> (PC-7476) BookingDetails: section "Ma réservation"

src/features/profile/components/YoungerBadge.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7876
I have:
=> (PC-7876) fix wording - add departments condition in younger badge

src/features/bookings/components/BookingDetailsHeader.tsx, src/features/bookings/components/ThreeShapesTicket.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/offer/components/OfferHeader.tsx, src/features/offer/pages/Offer.tsx, src/ui/components/headers/animationHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7763
I have:
|                      |![Screenshot from 2021-04-06 12-57-33](https://user-images.githubusercontent.com/22886846/113702314-a679c580-96d9-11eb-9050-d163446ec6bb.png)![Screenshot from 2021-04-06 12-57-48](https://user-images.githubusercontent.com/22886846/113702329-aa0d4c80-96d9-11eb-842c-bfc00713249c.png)|                       |                       |
If native code (ios/android) was modified, **after** the PR is merged, on the …
=> (PC-7763) ajout du header sur la page de détail de réservation

src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/__snapshots__/SetBirthday.test.tsx.snap, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7879
I have:
=> (PC-7879) fix wording in information modal why

src/features/bookings/helpers.ts, src/features/bookings/pages/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7763
https://passculture.atlassian.net/browse/PC-7476
I have:
=> (PC-7763) BookingDetails: fix scrollview for iOS + dateLabel

src/features/auth/signup/AcceptCgu.test.tsx, src/features/auth/signup/AcceptCgu.tsx, src/features/auth/signup/QuitSignupModal.tsx, src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/SetEmail.test.tsx, src/features/auth/signup/SetEmail.tsx, src/features/auth/signup/SetPassword.test.tsx, src/features/auth/signup/SetPassword.tsx, src/features/auth/signup/SetPostalCode.test.tsx, src/features/auth/signup/SetPostalCode.tsx, src/features/auth/signup/__snapshots__/SetBirthday.test.tsx.snap, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7940
I have:
| \*iOS arrivée sur la page code postal | iOS 5 chiffres max |
| ![image](https://user-images.githubusercontent.com/50346870/113423072-24825780-93ce-11eb-9443-153954d5b00a.png) | ![image](https://user-images.githubusercontent.com/50346870/113423093-2d732900-93ce-11eb-8b27-d8fe213cf1ad.png) | 
=> (PC-7940) add postal code sign up 

src/features/bookings/helpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7476
I have:
=> (PC-7476) BookingDetails: fix date label

.eslintrc.js, src/features/auth/signup/SetPostalCode.test.tsx, src/features/profile/pages/NotificationSettings.test.tsx, src/tests/utils.tsx, src/ui/components/StepDots.test.tsx
=> (Tech) added @testing-library/react-native to forbidden import

src/api/gen/api.ts, src/features/bookings/api/bookingsSnap.ts, src/features/bookings/components/ThreeShapesTicket.tsx, src/features/bookings/helpers.ts, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/profile/components/BeneficiaryHeader.tsx, src/features/profile/pages/Profile.tsx, src/locales/fr/messages.po, src/ui/svg/TicketHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7471
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7473
I have:
| \*iOS - [Phone name] | \*Android - [Phone name] | Tablet - [Phone name] | Little - [Phone name]|
|![Simulator Screen Shot - iPhone 8 - 2021-04-07 at 14 27 20](https://user-images.githubusercontent.com/22886846/113874194-d3030f80-97b5-11eb-9d59-a9010f53ad4e.png)|![Screenshot from 2021-04-06 19-45-11](https://user-images.githubusercontent.com/22886846/113755886-19526300-9711-11eb-8c6c-a9bb9b82332a.png)![Screenshot from 2021-04-06 …
=> (PC-7471/PC-7473) ajout des informations de réservations sur le header du détail de réservation

src/features/auth/signup/SetBirthday.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7940
I have:
=> (PC-7940) fix navigation bug

scripts/deploy_new_staging_version.sh, scripts/deploy_new_testing_version.sh
=> [Deploy Scripts] Fix script (align version and tag)

package.json
=> (Tech) reconciliate build version

package.json
=> V1.130.1 fix

src/api/gen/api.ts, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7471
I have:
=> (PC-7471) BookingsDetails: update offer url field on /bookings

src/features/auth/signup/SetPostalCode.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7940
I have:
=> (PC-7940) fix wording in postalcode

src/features/auth/api.ts, src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/VerifyEligibility.test.tsx, src/features/auth/signup/VerifyEligibility.tsx, src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.test.tsx, src/features/firstTutorial/pages/FirstTutorial/components/SecondCard.tsx, src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/features/profile/components/YoungerBadge.test.tsx, src/features/profile/components/YoungerBadge.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8038
I have:
=> [PC-8038] flip deposit amount non beneficiary header

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7475
I have:
=> (PC-7475) Fix offer rules displaying

src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/Favorite.test.tsx, src/features/favorites/atoms/__tests__/__snapshots__/Favorite.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7974
I have:
=> (PC-7974) App Native - Favoris - Animation à la suppression de Favoris

src/features/bookings/components/BookingDetailsHeader.tsx, src/features/bookings/components/ThreeShapesTicket.tsx, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/features/cheatcodes/pages/AppComponents.tsx, src/features/offer/components/OfferHero.tsx, src/features/offer/components/__tests__/OfferHero.test.tsx, src/features/offer/components/index.ts, src/features/offer/pages/OfferBody.tsx, src/features/offer/pages/tests/__snapshots__/OfferBody.test.tsx.snap, src/ui/components/headers/HeroHeader.tsx, src/ui/svg/BackgroundPlaceholder.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7474
I have:
|![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-04-12 at 12 22 16](https://user-images.githubusercontent.com/22886846/114380007-d7e70b00-9b89-11eb-9378-9ebe7a4a974a.png)|![Screenshot from 2021-04-12 11-40-02](https://user-images.githubusercontent.com/22886846/114374615-242f4c80-9b84-11eb-8e9d-0b6ee16f7a0e.png)|                       |![Screenshot from 2021-04-12 11-42-05](https://user-images.githubusercontent.com/22886846/1 …
=> (PC-7474) header de la page de détail de réservation

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7478
I have:
| <img width="365" alt="image" src="https://user-images.githubusercontent.com/6025710/114373759-365cbb00-9b83-11eb-963d-5731ce83d3b5.png"> |                          |                       |                       | …
=> (PC-7478) Display withdraw conditions

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7479
I have:
| <img width="352" alt="image" src="https://user-images.githubusercontent.com/6025710/114401561-52705480-9ba3-11eb-84cc-def2fcb425ce.png"> |                          |                       |                       | …
=> (PC-7479) Display the button that redirects to the detailed offer page

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7480
I have:
|                      |![Screenshot from 2021-04-12 16-25-17](https://user-images.githubusercontent.com/22886846/114410512-b9920700-9bab-11eb-86b5-55eff498e7a4.png)![Screenshot from 2021-04-12 16-24-37](https://user-images.githubusercontent.com/22886846/114410516-ba2a9d80-9bab-11eb-9e43-f46c6d7ffb43.png)![Screenshot from 2021-04-12 16-24-23](https://user-images.githubusercontent.com/22886846/114410518-bac33400-9bab-11eb-8721-10c06af898 …
=> (PC-7480) BookingDetails: add cancellation button

src/features/bookings/components/OnGoingBookingsList.test.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8029
I have:
=> (PC-8029) Log event when reaching bottom of Bookings page

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/home/atoms/OfferTile.tsx, src/features/home/atoms/tests/OfferTile.test.tsx, src/features/search/atoms/Hit.tsx, src/features/search/atoms/__tests__/Hit.test.tsx, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8031
I have:
=> (PC-8031) consult offer from bookings page

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8032
I have:
=> (PC-8032) Log event on cancel booking

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8036
I have:
=> (PC-8036) Log event on open external offer url

src/features/bookings/components/CancelBookingModal.test.tsx, src/features/bookings/components/CancelBookingModal.tsx, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7481
I have:
|                      |![Screenshot from 2021-04-13 12-32-37](https://user-images.githubusercontent.com/22886846/114539107-6d4ed180-9c54-11eb-9a50-e96f35ac99f6.png)![Screenshot from 2021-04-13 12-33-53](https://user-images.githubusercontent.com/22886846/114539209-8ce5fa00-9c54-11eb-9fbe-8a2a7addd2af.png)|                       |                       |
If native code (ios/android) was modified, **after** the PR is merged, on the …
=> (PC-7481) ajout de la modale d'annulation de réservation

src/tests/utils.tsx
=> (Tech) fix detect open handles

src/features/bookings/pages/BookingDetails.tsx, src/features/offer/components/OfferWhereSection.tsx, src/features/offer/components/__tests__/OfferWhereSection.test.tsx, src/libs/analytics.ts, src/libs/parsers/formatDates.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8034
I have:
=> (PC-8034) add property from to ConsultItinerary event

src/features/bookings/components/CancelBookingModal.test.tsx, src/features/bookings/components/CancelBookingModal.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8033
I have:
=> (PC-8033) Log event on confirm booking cancellation

doc/i18n/add-language.md, doc/i18n/add-translation.md, doc/i18n/getting-started.md
=> (Tech) ajout d'un readme sur la migration traduction

__mocks__/react-query.ts, jest/jest.setup.ts, src/api/__mocks__/api.ts, src/features/bookings/components/CancelBookingModal.test.tsx, src/features/bookings/components/CancelBookingModal.tsx, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/services/__tests__/useCancelBookingMutation.test.ts, src/features/bookings/services/useCancelBookingMutation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7482
I have:
=> [PC-7482] on cancel booking success

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7477
I have:
=> (PC-7477) Fix conditions that display the itinerary button

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts, src/ui/components/headers/HeroHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8035
I have:
=> (PC-8035) Tracking - Scroll jusqu'en bas de la page de détail de résa

src/features/deeplinks/useDeeplinkUrlHandler.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7841
I have:
=> (PC-7841) Remove snackbar automatically after deeplink 'incorrect link' warning

.env.production, .env.staging, .env.testing, ios/PassCulture/PassCulture.entitlements, src/features/deeplinks/listener.ios.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7844
=> (PC-7844) new firebase links

src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx
=> (PC-7477) Fix conditions to display the itinerary button

src/features/deeplinks/useDeeplinkUrlHandler.test.ts, src/features/deeplinks/useDeeplinkUrlHandler.ts
Le problème était que l’url était mal parsée. une double égalité dans la valeur d’un paramètre était mal interprétée et coupée en 2.
- conséquence : si le parsing échouait, on avait un crash “url incorrect“ => ❌ ce qui arrive dans notre cas
La PR modifie le système de parsing.
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8098
I have:
If native code (ios/android) was modified, **after** the PR …
=> (PC-8098) Fix incorrect parsing of deeplink: use simple manual parsing

src/features/bookOffer/pages/BookingConfirmation.tsx, src/features/favorites/components/FavoritesResults.tsx, src/features/favorites/components/__tests__/FavoritesResults.test.tsx, src/features/navigation/TabBar/__tests__/TabNavigator.test.tsx, src/features/navigation/TabBar/helpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8109
I have:
=> [PC-8109] Remove feature flipping

src/features/home/pages/Home.tsx, src/features/home/pages/tests/HomeWithModal.test.tsx, src/features/profile/pages/Profile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7482
I have:
=> (PC-7482) profile & home: refetch /me on focus to update get credit update

android/app/src/main/res/layout/launch_screen.xml, doc/customize/splash-screen.md, ios/SplashScreen.storyboard
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7938
I have:
|![image](https://user-images.githubusercontent.com/77674046/114866338-b8531b00-9df3-11eb-94ab-d36f614bd2ea.png)|                          |                       |                       |
=> (PC-7938) splash screen on ios resized from cover to contain and update doc

src/features/profile/pages/Profile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7613
I have:
=> (PC-7613) App Native - Profil : Bug Ecran blanc au tap sur Déconnexion

src/features/auth/AuthContext.tsx, src/features/auth/api.ts, src/features/auth/forgottenPassword/ResetPasswordExpiredLink.tsx, src/features/auth/signup/SignupConfirmationExpiredLink.tsx, src/features/bookOffer/services/useBookOfferMutation.ts, src/features/bookings/api/queries.ts, src/features/bookings/services/__tests__/useCancelBookingMutation.test.ts, src/features/bookings/services/useCancelBookingMutation.ts, src/features/cheatcodes/pages/Navigation.tsx, src/features/favorites/pages/useFavorites.ts, src/features/home/api.ts, src/features/home/pages/useHomeRecommendedHits.ts, src/features/offer/api/useOffer.ts, src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7482
I have:
=> (PC-7482) Annulation de réservation: invalider le cache de /me correctement

src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookingImpossible.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7824
I have:
=> [PC-7824] Improvement Booking impossible ios

src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7480
I have:
|                      |![Screenshot from 2021-04-15 18-14-48](https://user-images.githubusercontent.com/22886846/114903078-b6e71a00-9e16-11eb-9954-2b725a75060d.png)|                       |                       | …
=> (PC-7480) BookingDetails: fix bottom margin (paillette)

src/features/bookOffer/pages/BookingConfirmation.tsx, src/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx
=> [PC-8151] handle back from booking details

src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/features/profile/components/ProfileHeader.tsx, src/features/profile/pages/Profile.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8114
I have:
| \*iOS - [Phone name] |
| ![image](https://user-images.githubusercontent.com/50346870/115027202-b22c6f80-9ec3-11eb-910b-3e16eee59107.png) |
=> (PC-8114) Add profile header for non elligible department

src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/ui/svg/TicketFooter.tsx
I have:
- [ 
https://user-images.githubusercontent.com/43779561/115044554-ead54480-9ed5-11eb-84db-439644956570.mp4
] Written **unit tests** for my feature.
- if you want an hard deployment of the testing …
=> [PC-8076] design

src/api/gen/api.ts, src/api/helpers.ts, src/features/auth/login/Login.tsx, src/features/favorites/pages/__tests__/FavoritesSorts.test.tsx, src/features/home/api.test.ts, src/features/home/pages/useShowSkeleton.ts, src/features/navigation/NavigationContainer.tsx, src/features/navigation/RootNavigator/useInitialScreenConfig.tsx, src/features/navigation/navigationRef.ts, src/features/offer/components/__tests__/OfferIconCaptions.test.tsx, src/features/profile/components/ProfileHeader.test.tsx, src/libs/geolocation/GeolocationWrapper.tsx, src/libs/hooks/index.ts, src/libs/hooks/useIsMounted.ts, src/libs/hooks/useSafeState.ts, src/libs/parsers/formatDates.ts, src/libs/splashscreen.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8066
I have:
=> [PC-8066] Empecher que l'app freeze en cas d'erreur reseau sur la route refresh token

src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8177
I have:
| \*déjà en favori | \*pas en favori |
| ![image](https://user-images.githubusercontent.com/50346870/115220200-8d750980-a108-11eb-8062-a75797f1e57a.png) | ![image](https://user-images.githubusercontent.com/50346870/115220276-a382ca00-a108-11eb-9c23-520fd0fe2809.png) |
=> (PC-8177) Add conditional wording for impossible bookings

src/features/bookings/components/ThreeShapesTicket.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/ui/components/headers/animationHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8078
I have:
|                 
=> [PC-8078] design on ticket

android/app/src/main/java/com/passculture/MainApplication.java, ios/Podfile.lock, src/libs/errorMonitoring/ErrorMonitoringProvider.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8020
I have:
=> (PC-8020)(Tech) Sentry amélioration retour Antoine

src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/features/profile/components/NonEligibleDepartmentBadge.tsx, src/features/profile/components/NonElligibleDepartmentBadge.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8114
I have:
| \*iOS - [Phone name] | \*Maquette | 
| ![image](https://user-images.githubusercontent.com/50346870/115372139-e4431780-a1ca-11eb-9ed1-a335eebe34f0.png) | ![image](https://user-images.githubusercontent.com/50346870/115372159-e907cb80-a1ca-11eb-94b4-85016a744070.png) |
=> (PC-8114) add non elligible department banner

src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicyModal.test.tsx.snap, src/features/home/pages/tests/__snapshots__/Home.test.tsx.snap, src/features/home/pages/tests/__snapshots__/HomeWithModal.test.tsx.snap, src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8176
I have:
=> (PC-8176) [Android] handle hardware back on modal

src/features/cheatcodes/pages/AppComponents.tsx, src/ui/components/inputs/CodeInput.test.tsx, src/ui/components/inputs/CodeInput.tsx, src/ui/components/inputs/ShortInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8213
I have:
| <img width="357" alt="image" src="https://user-images.githubusercontent.com/6025710/115408838-7cec8e00-a1f1-11eb-814c-6943130bc150.png">|                          |                       |                       | …
=> (PC-8213) Customisable CodeInput

src/features/bookOffer/components/CancellationDetails.tsx, src/features/bookOffer/components/__tests__/CancellationDetails.test.tsx, src/libs/parsers/formatDates.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8204
I have:
| \*iOS - [Phone name] |
| ![image](https://user-images.githubusercontent.com/50346870/115419048-4bc48b80-a1fa-11eb-9626-ac55ba19eebc.png) | 
=> (PC-8204) fix cancellation details hour

src/features/bookOffer/services/__tests__/useModalContent.test.tsx, src/features/bookOffer/services/useModalContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8214
I have:
=> (PC-8214) Allow iOS users to book free digital offers

src/features/cheatcodes/pages/AppComponents.tsx, src/ui/components/inputs/CodeInput.test.tsx, src/ui/components/inputs/CodeInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8219
I have:
Rules: 
- code: 5 digits at least
- input: only digit, no letter
|  <5 digits KO | letter: KO| 5 digits OK |  |
| <img width="360" alt="image" src="https://user-images.githubusercontent.com/6025710/115511924-b240bc80-a281-11eb-9130-f2865ba9a39d.png">| <img width="370" alt="image" src="https://user-images.githubusercontent.com/6025710/115512054-d6040280-a281-11eb-95fb-977e1a077a8a.png"> | <img width="356" alt="image" src="https://user-images.githubusercontent.com/6025710/115512744-97bb1300-a282-11eb-9f06-14d8a84545ea.png"> | …
=> (PC-8219) CodeInput - validation

src/features/bookings/components/ThreeShapesTicket.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/ui/components/headers/HeroHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8208
I have:
|       
=> [PC-8208] fix booking details design overlap

.env.testing
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8099
I have:
=> (PC-8099) Change universal links for testing environment

src/features/auth/forgottenPassword/__snapshots__/ResetPasswordEmailSent.test.tsx.snap, src/features/auth/login/Login.tsx, src/features/auth/signup/__snapshots__/SetBirthday.test.tsx.snap, src/ui/components/BottomContentPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7937
I have:
=> (PC-7937) fix design review

src/ui/components/achievements/components/GenericAchievement.test.tsx, src/ui/components/achievements/components/GenericAchievement.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7631
I have:
=> (PC-7631) Override goback and pop screen behaviour for both iOS and Android on Achievements slider

src/features/auth/forgottenPassword/__snapshots__/ForgottenPassword.test.tsx.snap, src/features/auth/forgottenPassword/__snapshots__/ReinitializePassword.test.tsx.snap, src/features/auth/forgottenPassword/__snapshots__/ResetPasswordEmailSent.test.tsx.snap, src/features/auth/login/__snapshots__/Login.test.tsx.snap, src/features/auth/signup/__snapshots__/SetBirthday.test.tsx.snap, src/locales/fr/messages.po, src/ui/components/BottomContentPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8253
I have:
=> (PC-8253) add props to handle tap in sign up modal

.env.production, .env.staging
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8099
I have:
=> (PC-8099) Update universal links domains for staging and prodduction

ios/PassCulture.xcodeproj/project.pbxproj, src/features/profile/components/BeneficiaryHeader.tsx, src/features/profile/components/ExBeneficiaryHeader.test.tsx, src/features/profile/components/ExBeneficiaryHeader.tsx, src/features/profile/components/LoggedOutHeader.tsx, src/features/profile/components/ProfileHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8348
I have:
| \*iOS - [Phone name] | \*Android - [Galaxy] | Tablet - [Phone name] | Little - [Phone name] |
|                      |   ![Capture d’écran 2021-04-27 à 11 28 28](https://user-images.githubusercontent.com/62059034/116219273-b8381100-a74b-11eb-913e-1e06490fa602.png)                       |                       |                       |
- if you want an hard deployment of the testing environment, use …
=> (PC-8348) - App Native - Profil -  Personnaliser l'intitulé des profils des ex-bénéficaires

__mocks__/package.json, jest/jest.setup.ts, src/api/__tests__/helpers.test.ts, src/api/helpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8362
I have:
=> (PC-8362) add version header

.env.production, .env.staging, .env.testing, ios/Podfile.lock, jest/jest.setup.ts, package.json, src/App.tsx, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts, src/libs/campaign/client.ts, src/libs/campaign/index.ts, src/libs/environment/index.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8338
I have:
=> [PC-8338] Integrate AppsFlyer

.env.production
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8385
I have:
=> (PC-8385) change android app id

.circleci/config.yml, scripts/upload_sourcemaps_to_sentry.sh, src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookingDetails.test.tsx.snap, src/locales/fr/messages.po
=> Fix wording + circleCI

src/features/home/pages/Home.tsx, src/features/home/pages/tests/Home.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8339
I have:
=> (8339) Do not show credit to non beneficiary users

src/features/offer/components/CallToAction.tsx, src/features/offer/components/__tests__/__snapshots__/CallToAction.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8395
I have:
| \*iOS - [Phone name] | \*Android - [Galaxy] | Tablet - [Phone name] | Little - [Phone name] |
|                      | Before ![image-20210427-132907](https://user-images.githubusercontent.com/62059034/116399689-7b424c00-a829-11eb-8a77-68959785ac0f.png) <img width="271" alt="Capture d’écran 2021-04-28 à 11 07 59" src="https://user-images.githubusercontent.com/62059034/116389520-51832800-a81d-11eb-9731-925f74face92.png">  |                       |                       |
If native code (ios/android) was modified, **after** the PR …
=> (PC-8395) - App Native - Détail de l'offre - [Bug graphique] Picto accéder à l'offre KO

src/features/favorites/pages/FavoritesSorts.tsx, src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx, src/libs/geolocation/GeolocationWrapper.android.test.tsx, src/libs/geolocation/GeolocationWrapper.ios.test.tsx, src/libs/geolocation/GeolocationWrapper.tsx, src/libs/geolocation/components/GeolocationActivationModal.tsx, src/libs/geolocation/components/__tests__/GeolocationActivationModal.test.tsx, src/libs/storage.ts, src/ui/components/FilterSwitch.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8372
I have:
| \*iOS - iPhone 11 | \*Android - [Phone name] |
|  ![Capture d’écran 2021-04-27 à 18 04 11](https://user-images.githubusercontent.com/22399093/116274499-061c3b80-a783-11eb-86fa-fe1df885b385.png)                    |                          |
=> (PC-8372) Redirect user to settings when they want to deactivate geoloc from profile screen

src/features/auth/signup/IdCheck.test.tsx, src/features/auth/signup/IdCheck.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8336
I have:
=> (PC-8336) redirection vers la homepage bénéficiaire en sortie d'idcheck

src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts, src/features/offer/services/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8401
I have:
=> (PC-8401) do not show modal when opening external links

src/features/home/pages/tests/useHomeAlgoliaModules.test.ts, src/features/home/pages/useHomeAlgoliaModules.ts, src/features/home/pages/useShowSkeleton.ts, src/libs/geolocation/GeolocationWrapper.tsx, src/libs/queryKeys.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8463
I have:
=> (PC-8463) Les playlists géolocalisées ne fonctionnent pas sur iOS et Androïd

src/features/bookings/components/NoBookingsView.test.tsx, src/features/bookings/components/NoBookingsView.tsx, src/features/bookings/components/OnGoingBookingsList.test.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/bookings/pages/Bookings.tsx, src/features/bookings/pages/EndedBookingsSection.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8337
I have:
| ios with booking | ios with no booking |
| --- | --- |
|  ![image](https://user-images.githubusercontent.com/10118284/116597261-b1fd8c80-a925-11eb-819c-a3e98eb6501e.png) | ![image](https://user-images.githubusercontent.com/10118284/116667809-e52f3280-a99c-11eb-9439-9d3e913c39dd.png) |
=> (PC-8337) Show ended bookings even if no booking

src/features/profile/components/ExBeneficiaryHeader.test.tsx, src/features/profile/components/ExBeneficiaryHeader.tsx, src/features/profile/components/ProfileHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8348
I have:
| \*iOS - [Phone name] | \*Android - [Galaxy] | Tablet - [Phone name] | Little - [Phone name] |
|                      | <img width="273" alt="Capture d’écran 2021-04-30 à 09 47 27" src="https://user-images.githubusercontent.com/62059034/116664754-2de4ec80-a999-11eb-92f7-29bac7143618.png">         |                       |                       |
- if you want an hard deployment of the testing …
=> (PC-8348) - Profil - Ex-bénéficiaire ne pas afficher le montant de 0 €

.env.production, .env.staging, .env.testing, android/app/build.gradle, ios/PassCulture/Info.plist
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8466
I have:
=> [PC-8466] rename to meet pass Culture name

src/features/offer/components/CallToAction.tsx, src/features/offer/components/__tests__/__snapshots__/CallToAction.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8395
I have:
=> (PC-8395) Fix external link icon

src/features/bookings/components/NoBookingsView.tsx, src/features/home/pages/useHomeRecommendedHits.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8337
+ un peu de  https://passculture.atlassian.net/browse/PC-8477
I have:
=> (PC-8477) Handle reco API down

src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/signup/AcceptCgu.tsx
=> Add error monitoring to screens where ReCaptcha is used

src/features/auth/forgottenPassword/ForgottenPassword.test.tsx, src/features/auth/signup/AcceptCgu.test.tsx, src/libs/recaptcha/__snapshots__/ReCaptcha.test.tsx.snap, src/libs/recaptcha/webviewHTML.ts, src/tests/server.ts
=> Add tests for error monitoring on screens where ReCaptcha is used

src/api/gen/api.ts, src/features/auth/__mocks__/settings.ts, src/features/auth/api.ts, src/features/auth/forgottenPassword/ForgottenPassword.test.tsx, src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/settings.ts, src/features/auth/signup/AcceptCgu.test.tsx, src/features/auth/signup/AcceptCgu.tsx, src/tests/server.ts
=> Add feature flip on ReCaptcha token generation

src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/signup/AcceptCgu.tsx
=> Fix feature flip recaptcha

src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8498
I have:
=> (PC-8498) Avoid sentry error

src/features/bookings/components/NoBookingsView.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/bookings/pages/EndedBookingsSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8337
I have:
=> (PC-8337) Do not show separator if no ended bookings

src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.tsx, src/features/home/components/SignUpSignInChoiceModal.tsx, src/features/home/components/tests/SignUpSignInChoiceModal.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8509
I have:
=> [PC-8509] :sparkles: (Deposit) add feature flag on last app components

src/libs/recaptcha/__snapshots__/ReCaptcha.test.tsx.snap, src/libs/recaptcha/webviewHTML.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8492
I have:
=> (PC-8492) Use a simpler technical solution for ReCAPTCHA

src/features/auth/signup/IdCheck.tsx, src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8513
I have:
=> (PC-8513) profile: afficher profil grand public si l'utilisateur a terminé id check

ios/PassCulture.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8507
I have:
=> (PC-8507) install firestore

src/App.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-XXX ==> No ticket
I have:
=> Refetch react query when app becomes active

src/features/auth/signup/SetPhoneNumberValidationCode.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicy.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/__snapshots__/PrivacyPolicyModal.test.tsx.snap, src/features/home/pages/tests/__snapshots__/Home.test.tsx.snap, src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8475
I have:
|![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-30 at 17 48 16](https://user-images.githubusercontent.com/22886846/116720498-8c7f8a00-a9dc-11eb-90b5-a04b0c35b439.png)|![Screenshot![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-30 at 17 48 16](https://user-images.githubusercontent.com/22886846/116720498-8c7f8a00-a9dc-11eb-90b5-a04b0c35b439.png)from 2021-04-30 13-56-31](https://user-images.githubusercontent.com/22886846/11669 …
=> (PC-8475) AppModal: set modal position with keyboard height

src/features/bookings/components/NoBookingsView.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8337
I have:
=> (PC-8337) Fix design of ended bookings section

src/ui/components/inputs/CodeInput.test.tsx, src/ui/components/inputs/CodeInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8255
I have:
=> (PC-8255) Fix backspace animation on android

src/App.tsx, src/libs/campaign/client.ts, src/libs/campaign/isCompatible.ts, src/libs/campaign/tests/isCompatible.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8338
=> (PC-8338) Disable AppsFlyer for iOS 14.5 and above

jest/jest.setup.ts, src/features/auth/signup/AcceptCgu.test.tsx, src/features/auth/signup/AcceptCgu.tsx, src/libs/recaptcha/__snapshots__/ReCaptcha.test.tsx.snap
=> Add more details in error log of sign up failures

src/features/auth/signup/SetPhoneNumberModal.test.tsx, src/features/auth/signup/SetPhoneNumberModal.tsx, src/features/cheatcodes/pages/AppComponents.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8137
I have:
| \*iOS - empty | \* iOS - fulfilled |
|<img width="442" alt="image" src="https://user-images.githubusercontent.com/6025710/117260174-17cea480-ae4f-11eb-806b-d920d9ff7ff7.png">|<img width="559" alt="image" src="https://user-images.githubusercontent.com/6025710/117260292-359c0980-ae4f-11eb-8cfb-f3eebfc34204.png"> | 
=> (PC-8137) Phone number modal

src/features/auth/signup/SetPhoneNumberModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8136
I have:
=> (PC-8136) Fix cropped shaddows

src/features/auth/__mocks__/support.services.ts, src/features/auth/signup/SetPhoneNumberValidationCode.test.tsx, src/features/auth/signup/SetPhoneNumberValidationCode.tsx, src/features/auth/support.services.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8138
I have:
|                      |![Screenshot from 2021-05-07 08-51-51](https://user-images.githubusercontent.com/22886846/117410581-e9b29880-af12-11eb-85c3-06df7195edc5.png)|                       |                       | …
=> (PC-8138)modale de saisie du code de vérification du numéro de téléphone: contacter le support

ios/Podfile, jest/jest.setup.ts, package.json, src/features/firstTutorial/pages/FirstTutorial/components/FirstCard.tsx, yarn.lock
=> Id check universal native input mask

__mocks__/@pass-culture/id-check.ts, __mocks__/@pass-culture/id-check.tsx, src/App.test.tsx, src/App.tsx
=> Fix mock in App.test following change in AppNavigationContainer

src/api/gen/api.ts, src/features/auth/settings.ts, src/features/bookOffer/components/CancellationDetails.tsx, src/features/bookOffer/components/__tests__/CancellationDetails.test.tsx, src/locales/fr/messages.po, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7887
I have:
| Feature not available | <img width="365" alt="image" src="https://user-images.githubusercontent.com/6025710/117657842-58edee00-b19a-11eb-9759-1355db59ffca.png"> |                       |                       | …
=> (PC-7887) change the cancellation condition for digital booking

src/App.tsx
=> (Tech) remove id check logging

package.json, yarn.lock
=> (PC-6982) update id check to 0.0.8

src/features/firstTutorial/pages/FirstTutorial/__snapshots__/FirstTutorial.test.tsx.snap, src/features/firstTutorial/pages/FirstTutorial/components/FirstCard.tsx, src/features/firstTutorial/pages/FirstTutorial/components/__snapshots__/FirstCard.test.tsx.snap
=> (Tech) changement du wording first tutorial card

.github/PULL_REQUEST_TEMPLATE.md
=> :wrench: (PR template) add doc writting chekc box

src/features/deeplinks/useDeeplinkUrlHandler.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8681
I have:
=> (PC-8681) FIX: unescape universal links since they are now uri-encoded

src/api/gen/api.ts, src/features/auth/api.ts, src/features/auth/signup/SetPhoneNumberModal.test.tsx, src/features/auth/signup/SetPhoneNumberModal.tsx, src/features/auth/signup/SetPhoneNumberValidationCodeModal.test.tsx, src/features/auth/signup/SetPhoneValidationCodeModal.tsx, src/features/auth/signup/TemporaryIdCheck.tsx, src/libs/queryKeys.ts, src/libs/storage.ts, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8165
I have:
=> (PC-8165) send phone validation code

src/features/bookings/components/BookingDetailsCancelButton.test.tsx, src/features/bookings/components/BookingDetailsCancelButton.tsx, src/features/bookings/components/OnGoingBookingItem.test.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/helpers.test.ts, src/features/bookings/helpers.ts, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8280
I have:
|<img width="352" alt="image" src="https://user-images.githubusercontent.com/6025710/118261364-b55f4f00-b4b3-11eb-8f5b-4ff1ba7bed1a.png">|     |                       |                       |
=> (PC-8280) Change getBookingLabels to handle digital offers with activation code

src/features/bookings/helpers.test.ts, src/features/bookings/helpers.ts
=> Fix getBookingLabelForActivationCode

src/features/bookings/api/helpers.ts, src/features/bookings/api/mutations.ts, src/features/bookings/components/ArchiveBookingModal.test.tsx, src/features/bookings/components/ArchiveBookingModal.tsx, src/features/bookings/components/CancelBookingModal.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8357
I have:
| <img width="508" alt="image" src="https://user-images.githubusercontent.com/6025710/118266660-3241f700-b4bb-11eb-96ed-88edacfef217.png"> |                          |                       |                       | …
=> (PC-8357)  Create ArchiveBookingModal

src/features/bookings/components/BookingPropertiesSection.tsx, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8354
I have:
=> (PC-8354) Hide Calendar when date label is empty

src/features/home/components/HomeHeader.tsx, src/features/home/components/index.ts, src/features/home/pages/Home.tsx, src/features/home/pages/tests/useShowSkeleton.test.ts, src/features/home/pages/useShowSkeleton.ts, src/features/navigation/__tests__/useInitialScreenConfig.test.tsx, src/libs/splashscreen.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8515
I have:
=> (PC-8515) Remove setTimeout for hiding splashscreen

src/features/favorites/pages/FavoritesSorts.tsx, src/features/favorites/pages/__tests__/FavoritesSorts.test.tsx, src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx, src/features/search/pages/LocationFilter.tsx, src/features/search/pages/__tests__/LocationFilter.test.tsx
I have:
| \*iOS - [Phone name] | \*Android - OnePlus 5 | 
|                      |  ![image](https://user-images.githubusercontent.com/22399093/118521369-409e4600-b73b-11eb-97b2-af1dbb84a4f3.png) |
=> (PC-8696) Add error log to features needing positions when position is unavailable

scripts/check_branch.sh, scripts/deploy_new_production_version.sh, scripts/deploy_new_version.sh, scripts/update_app_version.sh, scripts/upload_sourcemaps_to_sentry.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8780
I have:
=> (PC-8780) App Native - Script de déploiement - Rendre les scripts de déploiement compatible linux

src/features/bookings/components/BookingPropertiesSection.test.tsx, src/features/bookings/components/BookingPropertiesSection.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/helpers.ts, src/features/bookings/pages/BookingDetails.tsx
=> Set third argument of getBookingLabels not optional

ios/PassCulture/AppDelegate.m, ios/Podfile, ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8768
I have:
=> [PC-8768] Afficher une notification push lorsque l'app est ouverte

src/features/favorites/pages/FavoritesSorts.tsx, src/features/favorites/pages/__tests__/FavoritesSorts.test.tsx, src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx, src/features/search/pages/LocationFilter.tsx, src/features/search/pages/__tests__/LocationFilter.test.tsx
=> (PC-8696) New wording for geoloc error message

package.json, yarn.lock
=> (Tech) using @pass-culture/id-check@^2.0.1

.circleci/config.yml
https://passculture.atlassian.net/browse/PC-8536
=> [PC-8536] notify CI deployements

src/features/auth/signup/SetPhoneNumberModal.test.tsx, src/features/auth/signup/SetPhoneNumberModal.tsx, src/features/auth/signup/SetPhoneNumberValidationCodeModal.test.tsx, src/features/auth/signup/SetPhoneValidationCodeModal.tsx, src/libs/timer.test.ts, src/libs/timer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8374
I have:
| ![ModalTimerIOS](https://user-images.githubusercontent.com/6025710/118615490-142d0d00-b7c1-11eb-9273-261919e76644.gif) |![ModalTimerAndroid](https://user-images.githubusercontent.com/6025710/118615533-1f803880-b7c1-11eb-8737-5416e01532f0.gif) |                       |                       |
- if you …
=> (PC-8374) SetPhoneNumberModal: display timer on button Continuer

src/features/bookings/components/ArchiveBookingModal.test.tsx, src/features/bookings/components/ArchiveBookingModal.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8357
I have:
=> (PC-8357) Change wording & add success snackbar message

src/features/auth/signup/idCheck/useNavigateToIdCheck.ts
=> Add redirection to idcheck v2 in useNavigateToIdCheck()

package.json
=> (Tech) revert pkg

src/App.tsx, src/locales/fr/messages.po
I have:
|                      |  ![Capture d’écran 2021-05-18 à 17 54 32](https://user-images.githubusercontent.com/62059034/118684512-92f66a00-b802-11eb-95b7-0c5d01d729fa.png)                         |                       |                       |
- if you want an hard deployment of the testing environment, …
=> (Tech) Update wording

src/api/gen/api.ts, src/features/auth/__mocks__/settings.ts, src/features/auth/api.ts, src/features/auth/signup/AcceptCgu.tsx, src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/SetEmail.test.tsx, src/features/auth/signup/SetEmail.tsx, src/features/auth/signup/SetPassword.test.tsx, src/features/auth/signup/SetPassword.tsx, src/features/auth/signup/SetPostalCode.test.tsx, src/features/auth/signup/SetPostalCode.tsx, src/features/bookings/components/BookingPropertiesSection.test.tsx, src/features/cheatcodes/pages/AppComponents.tsx, src/features/navigation/RootNavigator/types.ts, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8728
I have:
[PC-8728]: https://passculture.atlassian.net/browse/PC-8728
=> [PC-8728] do not show postal code

package.json, yarn.lock
=> (Tech) update @pass-culture/id-check to 2.0.2

ios/PassCulture/Info.plist
=> (Tech) added photo library camera description

scripts/deploy.sh, scripts/deploy_new_production_version.sh, scripts/generate_api_client.sh, scripts/print_project_version.sh
=> (Tech) sanitize bash

src/features/auth/components/QuitSignupModal.test.tsx, src/features/auth/components/QuitSignupModal.tsx, src/features/auth/forgottenPassword/ForgottenPassword.test.tsx, src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/forgottenPassword/ReinitializePassword.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent.test.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent.tsx, src/features/auth/forgottenPassword/ResetPasswordExpiredLink.test.tsx, src/features/auth/forgottenPassword/ResetPasswordExpiredLink.tsx, src/features/auth/login/Login.test.tsx, src/features/auth/login/Login.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer.tsx, src/features/auth/signup/IdCheck.tsx, src/features/auth/signup/SignupConfirmationEmailSent.test.tsx, src/features/auth/signup/SignupConfirmationEmailSent.tsx, src/features/auth/signup/SignupConfirmationExpiredLink.test.tsx, src/features/auth/signup/SignupConfirmationExpiredLink.tsx, src/features/auth/signup/VerifyEligibility.test.tsx, src/features/auth/signup/VerifyEligibility.tsx, src/features/bookOffer/pages/BookingConfirmation.tsx, src/features/cheatcodes/components/NavigateHomeButton/NavigateHomeButton.test.tsx, src/features/cheatcodes/components/NavigateHomeButton/NavigateHomeButton.tsx, src/features/firstLogin/CulturalSurvey.test.tsx, src/features/firstLogin/CulturalSurvey.tsx, src/features/navigation/__mocks__/helpers.ts, src/features/navigation/backNavigation.ts, src/features/navigation/helpers.ts
=> Add function navigateToHome() to replace all navigate('Home')

android/build.gradle
=> (Tech) gradle options --debug --stacktrace

.circleci/config.yml, android/build.gradle, metro.config.js
=> (Tech) restore ci tests and caching

src/features/deeplinks/analytics.test.ts, src/features/deeplinks/typeGuard.ts, src/features/deeplinks/useDeeplinkUrlHandler.test.ts, src/features/deeplinks/useDeeplinkUrlHandler.ts
=> Add navigateToIdCheck() in deeplink handler

package.json, yarn.lock
=> (Tech) bump to 2.0.4 @pass-culture/id-check

package.json, yarn.lock
=> (Tech) bump to 2.0.6 @pass-culture/id-check

android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, ios/PassCulture/AppDelegate.m, ios/Podfile, ios/Podfile.lock, package.json, react-native.config.js, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8768
I have:
See revert PR: https://github.com/pass-culture/pass-culture-app-native/pull/1072
=> [PC-8768] Reinstate Open app notifications [build android fixed]

src/features/deeplinks/utils.ts, src/features/offer/components/__tests__/OfferHeader.test.tsx, src/features/offer/services/useShareOffer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8271
I have:
=> (PC-8271) share offer with webapp compatibility

android/gradle.properties
=> :wrench: (hard deploy android) try reduce memory issues

src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/signup/AcceptCgu.tsx
=> (Tech) sentry add log for email registration

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8858
I have:
=> (PC-8858) bump to 2.0.8 @pass-culture/id-check

src/features/firstLogin/PrivacyPolicy/PrivacyPolicy.test.tsx
=> (Tech) less flacky test

src/features/auth/signup/idCheck/DenyAccessToIdCheck.tsx, src/features/auth/signup/idCheck/__snapshots__/DenyAccessToIdCheck.test.tsx.snap, src/features/bookOffer/services/__tests__/useModalContent.test.tsx, src/features/bookOffer/services/useModalContent.tsx, src/features/eighteenBirthday/pages/__snapshots__/EighteenBirthday.test.tsx.snap, src/features/eighteenBirthday/pages/components/__snapshots__/EighteenBirthdayCard.test.tsx.snap, src/features/firstTutorial/pages/FirstTutorial/__snapshots__/FirstTutorial.test.tsx.snap, src/features/firstTutorial/pages/FirstTutorial/components/FirstCard.tsx, src/features/firstTutorial/pages/FirstTutorial/components/__snapshots__/FirstCard.test.tsx.snap, src/libs/geolocation/components/GeolocationActivationModal.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8808
I have:
=> (PC-8808) paillettes wording

src/features/auth/api.ts, src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/features/profile/components/YoungerBadge.tsx
=> (PC-8867) App Native - Id Check - Rate limiting id check frontend

src/features/deeplinks/pages/DeeplinkImporter.test.tsx, src/features/deeplinks/pages/DeeplinkImporter.tsx
=> (PC-8863) App Native - HotFix - Page d'import des liens dynamics

src/features/auth/forgottenPassword/ResetPasswordExpiredLink.test.tsx, src/features/auth/forgottenPassword/ResetPasswordExpiredLink.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8898
I have:
| \*iOS - iPhone 11 | \*Android - OnePlus 5 | 
| ![simulator_screenshot_FA4BC028-3B92-4CE1-A1BB-E66E07743CA8](https://user-images.githubusercontent.com/22399093/119220723-2cb46480-baec-11eb-993e-df61cc6df9a4.png)  | ![Screenshot_20210522-105943](https://user-images.githubusercontent.com/22399093/119220917-1064f780-baed-11eb-87e7-0941d1351a99.jpg) |
=> (PC-8898) Remove contact support on ResetPasswordExpiredLink

src/features/auth/login/Login.test.tsx, src/features/auth/login/Login.tsx, src/features/auth/signup/AccountCreated.test.tsx, src/features/auth/signup/AccountCreated.tsx, src/features/navigation/RootNavigator/useInitialScreenConfig.tsx, src/features/navigation/__tests__/useInitialScreenConfig.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8900
I have:
| \*iOS - [Phone name] | \*Android - OnePlus 5 |
|                      |  ![Screenshot_20210522-152523](https://user-images.githubusercontent.com/22399093/119228178-14574080-bb12-11eb-9032-15f4e9dbb2fc.jpg)      |
=> (PC-8900) Do not display CulturalSurvey to non-beneficiaries

package.json, yarn.lock
=> (Tech) bump to 2.0.9 @pass-culture/id-check

src/features/eighteenBirthday/pages/__snapshots__/EighteenBirthday.test.tsx.snap, src/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.tsx, src/features/profile/pages/ConsentSettings.tsx, src/locales/fr/messages.po
=> (Tech) fixed broken translations and tests

src/features/auth/forgottenPassword/ResetPasswordEmailSent.test.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent.tsx, src/features/auth/forgottenPassword/__snapshots__/ResetPasswordEmailSent.test.tsx.snap, src/features/auth/signup/SignupConfirmationExpiredLink.test.tsx, src/features/auth/signup/SignupConfirmationExpiredLink.tsx
=> (PC-8906) Comment contact support button on email password sent

src/features/auth/forgottenPassword/ResetPasswordEmailSent.tsx, src/features/auth/forgottenPassword/ResetPasswordExpiredLink.tsx, src/features/auth/forgottenPassword/__snapshots__/ResetPasswordEmailSent.test.tsx.snap, src/features/auth/signup/SignupConfirmationExpiredLink.tsx
=> (PC-8907) Replace mail to support with link to cgu

src/features/auth/forgottenPassword/ResetPasswordEmailSent.tsx, src/features/auth/forgottenPassword/__snapshots__/ResetPasswordEmailSent.test.tsx.snap, src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.deprecated.test.tsx, src/locales/fr/messages.po
=> (Tech) fix message support

src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetBirthday.tsx
=> (Tech) disable postal code permanently

src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.deprecated.test.tsx, src/locales/fr/messages.po
=> (Tech) mets tes offres en favoris avec un s

src/features/bookOffer/components/BookingImpossible.tsx, src/features/bookOffer/components/__tests__/BookingImpossible.deprecated.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookingImpossible.deprecated.test.tsx.snap
=> (Tech) fixed text on BookingImpossible

doc/deployment/deployment.md
=> Add cherry-pick informations in doc deployment

src/api/gen/api.ts, src/features/auth/api.ts, src/features/auth/signup/BeneficiaryRequestSent.test.tsx, src/features/auth/signup/BeneficiaryRequestSent.tsx, src/features/bookings/components/BookingPropertiesSection.test.tsx, src/features/home/api.test.ts, src/features/offer/components/__tests__/OfferIconCaptions.test.tsx, src/features/profile/components/ProfileHeader.test.tsx, src/tests/server.ts
=> [PC-8913] notify backend id check done

src/features/auth/signup/IdCheck.tsx, src/features/profile/components/IdCheckProcessingBadge.tsx, src/features/profile/components/NonBeneficiaryHeader.test.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, src/features/profile/components/ProfileBadge.tsx, src/features/profile/components/ProfileHeader.tsx, src/features/profile/components/YoungerBadge.tsx, src/libs/storage.ts
=> [PC-8914] id check badge

package.json, src/features/cheatcodes/pages/Navigation.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx, yarn.lock
=> (Tech) bump to 2.0.10 @pass-culture/id-check

src/features/profile/components/NonBeneficiaryHeader.tsx
=> (Tech) lint fix

src/features/profile/components/NonBeneficiaryHeader.tsx
=> (Tech) fix imports

src/features/auth/signup/SetBirthday.tsx
=> (Tech) remove gen

src/locales/fr/messages.po
=> (Tech) update message

src/features/auth/api.ts, src/features/auth/signup/AcceptCgu.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/SetPassword.test.tsx, src/features/auth/signup/SetPostalCode.test.tsx
=> (Tech) remove all flag gen

src/features/bookOffer/services/__tests__/useModalContent.test.tsx, src/features/bookOffer/services/useModalContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8931
I have:
=> [PC-8931] cinema is ok to be paid on ios

src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/SetPhoneValidationCodeModal.tsx, src/features/auth/signup/__snapshots__/SetBirthday.test.tsx.snap, src/features/profile/components/YoungerBadge.test.tsx, src/features/profile/components/YoungerBadge.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8134
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8947
I have:
|                      |![Screenshot from 2021-05-24 14-47-45](https://user-images.githubusercontent.com/22886846/119351462-c3298700-bca0-11eb-9f22-208c2a8ab3cc.png)![Screenshot from 2021-05-24 14-50-20](https://user-images.githubusercontent.com/22886846/119351468-c4f34a80-bca0-11eb-865f-c98700011cab.png)|                       |                       |
If native …
=> (PC-8134/8947) fix SetPhoneValidationCodeModal input + update wording (profile & SetBirthday)

src/features/profile/components/NonBeneficiaryHeader.tsx
=> (Tech) bump to 2.0.11 @pass-culture/id-check

package.json, yarn.lock
=> (Tech) bump to 2.0.12 @pass-culture/id-check

src/features/auth/signup/SetPhoneValidationCodeModal.tsx, src/ui/components/inputs/CodeInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8134
I have:
=> (PC-8134) CodeInput: set minimum height

src/features/auth/__mocks__/settings.ts, src/features/auth/signup/TemporaryIdCheck.test.tsx, src/features/auth/signup/TemporaryIdCheck.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8783
I have:
=> (PC-8783) feature flag enable_phone_validation

package.json, src/App.test.tsx, src/features/auth/signup/idCheck/DenyAccessToIdCheck.tsx, src/features/auth/signup/idCheck/__snapshots__/DenyAccessToIdCheck.test.tsx.snap, src/features/errors/pages/AsyncErrorBoundary.tsx, src/features/errors/pages/tests/__snapshots__/AsyncErrorBoundary.test.tsx.snap, src/locales/fr/messages.po, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8982
I have:
=> (PC-8982) bump to 2.0.13 @pass-culture/id-check

src/features/auth/signup/SetPhoneValidationCodeModal.test.tsx, src/features/auth/signup/SetPhoneValidationCodeModal.tsx, src/features/auth/signup/TooManyAttempts.test.tsx, src/features/auth/signup/TooManyAttempts.tsx, src/features/cheatcodes/pages/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8545
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8135
I have:
|                      |![Screenshot from 2021-05-25 18-31-47](https://user-images.githubusercontent.com/22886846/119627257-50d5b580-be0c-11eb-8374-441d232e10ac.png)|                       |                       |
- if you want an hard …
=> (PC-8135/8545) Redirection vers l'écran d'erreur "trop de tentatives" suite à 3 saisies de code erroné

src/features/favorites/pages/FavoritesSorts.tsx, src/features/favorites/pages/__tests__/FavoritesSorts.test.tsx, src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx, src/features/search/pages/LocationFilter.tsx, src/features/search/pages/__tests__/LocationFilter.test.tsx, src/libs/geolocation/GeolocationWrapper.android.test.tsx, src/libs/geolocation/GeolocationWrapper.ios.test.tsx, src/libs/geolocation/GeolocationWrapper.tsx, src/libs/geolocation/getPosition.test.ts, src/libs/geolocation/getPosition.ts
=> (PC-8696) Add more logs and display position error message only when our geoloc lobrary actually encounter an error

package.json, src/api/gen/api.ts, src/features/auth/__mocks__/settings.ts, src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx, src/features/auth/signup/IdCheck.tsx, src/features/auth/signup/IdCheckV2.tsx, src/features/auth/signup/SetBirthday.test.tsx, src/features/bookings/components/BookingPropertiesSection.test.tsx, src/tests/server.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8979
I have:
=> [PC-8979] flag dms

src/libs/geolocation/getPosition.ts
=> (PC-8696) Use different names for PositionError logs

src/features/auth/signup/IdCheckV2.tsx
=> (PC-9003) Wait before navigating

src/features/auth/signup/IdCheckV2.tsx
=> (PC-9003) delete hard cache

package.json, src/features/auth/signup/IdCheckV2.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9002
I have:
=> (PC-9002) bump to 2.0.16 @pass-culture/id-check

doc/deployment/deployment.md
=> :wrench: (deployment) update modop gain CI time

src/features/auth/signup/PhoneValidation.test.tsx, src/features/auth/signup/PhoneValidation.tsx, src/features/cheatcodes/pages/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8375
I have:
=> (PC-8375) Replace TemporaryIdCheck with PhoneValidation

src/features/auth/signup/SetPhoneNumberModal.test.tsx, src/features/auth/signup/SetPhoneNumberModal.tsx
=> (PC-8702) gestion des erreurs de /send_validation_code sur la modale de saisie du numéro de téléphone

package.json, yarn.lock
=> (PC-8953) bump to 2.0.18 @pass-culture/id-check

scripts/check_branch.sh
=> :wrench: (deployment) enable deploy othrr branch for hard hotfix

package.json, src/api/gen/api.ts, src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx, src/features/auth/signup/IdCheckV2.tsx, src/features/bookings/components/BookingPropertiesSection.test.tsx, src/features/home/api.test.ts, src/features/offer/components/__tests__/OfferIconCaptions.test.tsx, src/features/profile/components/ProfileHeader.test.tsx, src/libs/idCheckAnalytics.ts, src/tests/server.ts, yarn.lock
=> (Tech) added debugging mode in id check

src/features/auth/signup/SetPhoneNumberModal.test.tsx
=> ✅ : (setPhonNumberModal) make tests independant

package.json, yarn.lock
=> (Tech) bump to 2.0.22 @pass-culture/id-check

package.json, src/features/auth/signup/SetPhoneNumberModal.test.tsx, src/features/auth/signup/SetPhoneNumberModal.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8987
I have:
|![Simulator Screen Shot - iPhone 8 - 2021-06-01 at 09 39 47](https://user-images.githubusercontent.com/22886846/120285579-ac48ed00-c2bd-11eb-88b6-7d0800ba17d2.png)![Simulator Screen Shot - iPhone 8 - 2021-06-01 at 09 39 52](https://user-images.githubusercontent.com/22886846/120285583-aeab4700-c2bd-11eb-9d84-0be673b31c46.png)|https://user-images.githubusercontent.com/22886846/120284036-1f516400-c2bc-11eb-807b-6b8d1c3ebe2e.mp4| …
=> (PC-8987) SetPhoneNumberModal: use country picker to choose international phone number code

ios/Podfile.lock, package.json, yarn.lock
I have:
|                      |                          | 
=> Upgrade geolocation service to fix no position on devices without google play service

package.json, src/features/auth/signup/IdCheck.tsx, src/features/auth/signup/IdCheckV2.tsx, src/libs/errorMonitoring/__mocks__/services.ts, src/libs/errorMonitoring/services.ts, yarn.lock
=> (Tech) bump to 2.0.23 @pass-culture/id-check

src/features/bookOffer/pages/BookingConfirmation.tsx, src/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx, src/features/bookOffer/services/useBookOfferMutation.ts, src/features/bookings/api/queries.ts, src/features/bookings/components/BookingDetailsTicketContent.tsx, src/features/bookings/components/OnGoingBookingItem.test.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/components/OnGoingBookingsList.tsx, src/features/bookings/components/ThreeShapesTicket.constants.ts, src/features/bookings/components/ThreeShapesTicket.tsx, src/features/bookings/helpers.ts, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/bookings/pages/Bookings.test.tsx, src/features/bookings/pages/Bookings.tsx, src/features/bookings/pages/EndedBookings.test.tsx, src/features/bookings/pages/EndedBookings.tsx, src/features/bookings/pages/EndedBookingsSection.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/features/cheatcodes/pages/AppComponents.tsx, src/features/navigation/RootNavigator/types.ts, src/features/offer/pages/tests/__snapshots__/OfferBody.test.tsx.snap, src/ui/components/ClippedImage.test.tsx, src/ui/components/ClippedImage.tsx, src/ui/components/headers/HeroHeader.tsx, src/ui/svg/TicketFooter.tsx, src/ui/svg/TicketHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8272
I have:
=> (PC-8272) Refonte de la page BookingDetails

src/features/auth/signup/SetPhoneNumberModal.tsx, src/features/auth/signup/SetPhoneValidationCodeModal.tsx, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8139
I have:
=> (PC-8139) modale de saisie du code: retours graphiques + gestion d'erreurs

src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/TabBarComponent.tsx, src/features/navigation/TabBar/__tests__/TabBar.test.tsx, src/features/navigation/TabBar/__tests__/__snapshots__/TabBar.test.tsx.snap, src/tests/utils.tsx, src/ui/svg/icons/BicolorSelector.tsx, src/ui/svg/icons/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9201
I have:
=> (PC-9201) Add accessibility labels to tabs (for android E2E tests)

src/features/auth/__mocks__/settings.ts, src/features/bookOffer/components/BookingInformations.tsx, src/features/bookOffer/components/__tests__/BookingInformations.test.tsx, src/features/bookOffer/components/__tests__/__snapshots__/BookingInformations.test.tsx.snap, src/features/bookOffer/pages/__mocks__/BookingOfferWrapper.tsx, src/libs/parsers/formatDates.ts, src/libs/parsers/tests/formatDates.test.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8667
I have:
|            
=> [PC-8667] cancellation date

src/features/profile/pages/Profile.test.tsx, src/features/profile/pages/Profile.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9201
I have:
=> (PC-9201) Add accessibilityLabel to logout button

src/libs/geolocation/getPosition.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9110
I have:
=> (PC-9110) Modify custom error messages for position errors

src/features/auth/login/Login.test.tsx, src/features/auth/login/Login.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer.tsx, src/features/deeplinks/routing.test.ts, src/features/deeplinks/routing.ts, src/features/deeplinks/typeGuard.ts, src/features/deeplinks/types.ts, src/features/deeplinks/useDeeplinkUrlHandler.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9212
Related to PC-9026
I have:
=> (PC-9212) deep link anniversaire 18 ans redirige vers la home alors qu on est connecté.

.eslintrc.js, eslint-custom-rules/independant-mocks.js, eslint-local-rules.js, src/features/auth/signup/AcceptCgu.test.tsx, src/features/auth/signup/AccountCreated.test.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx, src/features/auth/signup/BeneficiaryRequestSent.test.tsx, src/features/auth/signup/EligibilityConfirmed.test.tsx, src/features/auth/signup/SetBirthday.test.tsx, src/features/auth/signup/SetPhoneValidationCodeModal.test.tsx, src/features/auth/signup/SignupConfirmationEmailSent.test.tsx, src/features/bookOffer/components/__tests__/BookingEventChoices.test.tsx, src/features/deeplinks/routing.test.ts, src/features/errors/pages/tests/AsyncErrorBoundary.test.tsx, src/features/favorites/components/__tests__/FavoritesResults.test.tsx, src/features/favorites/pages/__tests__/useFavorites.test.tsx, src/features/firstLogin/CulturalSurvey.test.tsx, src/features/home/components/tests/BusinessModule.test.tsx, src/features/navigation/__tests__/RootNavigator.test.tsx, src/features/offer/components/__tests__/OfferHeader.test.tsx, src/features/profile/pages/ChangePassword.test.tsx, src/features/profile/pages/Profile.test.tsx, src/features/search/pages/__tests__/Search.test.tsx, src/libs/ABTesting/ABTestingProvider.test.tsx, src/libs/algolia/__tests__/fetchAlgolia.test.ts, src/libs/algolia/datetime/__tests__/date.test.ts, src/libs/geolocation/requestGeolocPermission.android.test.ts, src/libs/geolocation/requestGeolocPermission.ios.test.ts, src/libs/timer.test.ts
=> Independant tests

src/features/auth/signup/AfterSignupEmailValidationBuffer.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9212
I have:
=> (PC-9212) redirect to id check if user is eligible

src/api/gen/api.ts, src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer.tsx, src/features/bookings/components/BookingPropertiesSection.test.tsx, src/tests/server.ts
=> (Tech) update API schema

src/features/auth/login/Login.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer.test.tsx, src/features/deeplinks/routing.test.ts, src/features/deeplinks/routing.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9204
I have:
=> (PC-9204) App Native - Sécurité - Deeplink pour accéder au parcours de vérifier du num

src/features/navigation/__tests__/RootNavigator.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6360
I have:
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10118284/120999679-ace3f680-c789-11eb-9f3b-88d58fe9c0d9.png) | ![image](https://user-images.githubusercontent.com/10118284/120999741-bc633f80-c789-11eb-9339-5997bd40378e.png) |
=> (PC-6360) Supprimer les warnings de RootNavigator.test

src/features/offer/pages/OfferBody.tsx, src/features/offer/pages/tests/OfferBody.test.tsx, src/features/offer/pages/tests/renderOfferPageTestUtil.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9126
I have:
=> (PC-9126) Only show withdrawal details for beneficiary users

src/libs/analytics.test.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8191
I have:
=> (PC-8191) Firebase event: convert offerId to string

src/features/auth/signup/IdCheckV2.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9223
I have:
=> (PC-9223) Add steps configs for id check

src/locales/fr/messages.po
=> (Tech) update messages.po

src/features/navigation/__tests__/helpers.test.ts, src/features/navigation/helpers.ts, src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts, src/features/offer/services/useCtaWordingAndAction.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7496
I have:
|         
=> [PC-7496] do not re book offer

package.json, src/libs/idCheckRetentionClient.ts, yarn.lock
=> (Tech) Id check v2.1.3 - fix retention currentUser and re-upload

src/features/profile/components/IdCheckProcessingBadge.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9220
I have:
=> (PC-9220) App Native - ID Check - Bassin de rétention - Version alternative de la bannière dossier déposé sur la page profil

src/libs/idCheckRetentionClient.ts
=> (Tech) add log to sentry in id check retention client

src/features/auth/AuthContext.tsx
=> (Tech) clear id check localstorage when logging out

src/features/auth/AuthContext.tsx
=> (Tech) logout logging

package.json, yarn.lock
=> (Tech) bump to 2.1.5 @pass-culture/id-check

src/features/deeplinks/routing.ts, src/features/deeplinks/types.ts, src/features/home/api.test.ts, src/features/home/api.ts, src/features/home/contentful/__snapshots__/processHomepageEntry.test.ts.snap, src/features/home/contentful/contentful.ts, src/features/home/contentful/index.ts, src/features/home/contentful/processHomepageEntry.test.ts, src/features/home/contentful/processHomepageEntry.ts, src/features/home/pages/Home.tsx, src/features/home/pages/tests/Home.test.tsx, src/features/home/pages/useDisplayedHomeModules.ts, src/features/navigation/TabBar/types.ts, src/tests/fixtures/homepageEntries.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8969
I have:
=> (PC-8969) Affichage d'une page d'accueil customisée

fastlane/.env, fastlane/Appfile, ios/PassCulture.xcodeproj/project.pbxproj
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9328
I have:
=> [PC -9328] image on store

README.md
=> (Tech) Udpate README for Start the app on your Apple device (with Xcode)

package.json, src/App.tsx, src/features/favorites/pages/__tests__/__snapshots__/Favorites.test.tsx.snap, src/features/home/atoms/SkeletonTile.tsx, src/features/home/components/ExclusivityModule.tsx, src/features/home/components/HomeBodyPlaceholder.tsx, src/features/home/components/tests/__snapshots__/ExclusivityModule.test.tsx.snap, src/features/home/components/tests/__snapshots__/HomeBodyPlaceholder.test.tsx.snap, src/features/search/components/Placeholders.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9075
I have:
Most of the crashes of old Android version  / old devices were due to OutOfMemory error.
=> [PC-9075] New skeleton to avoid crash

package.json
=> (Tech) down package.json version for re-release

package.json
=> (Tech) downgrade version to re mes

android/build.gradle, android/settings.gradle, ios/Podfile.lock, package.json
=> (Tech) try to fix profiling

package.json
=> (Tech) down to release

android/build.gradle, ios/Podfile.lock, package.json
=> (Tech) fix profiling

package.json, yarn.lock
=> (Tech) bump to 2.1.8 @pass-culture/id-check

.circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8847
I have:
=> (PC-8847) upgrade docker executor for hard android jobs from medium to medium+

src/features/bookings/components/BookingDetailsHeader.tsx, src/features/bookings/pages/__snapshots__/BookingDetails.test.tsx.snap, src/features/favorites/pages/__tests__/__snapshots__/FavoritesSorts.test.tsx.snap, src/features/offer/atoms/HeaderIcon.tsx, src/features/offer/atoms/__tests__/HeaderIcon.test.tsx, src/features/offer/components/OfferHeader.tsx, src/features/offer/components/__tests__/__snapshots__/OfferHeader.test.tsx.snap, src/features/offer/pages/tests/__snapshots__/OfferDescription.test.tsx.snap, src/features/search/pages/__tests__/__snapshots__/Categories.test.tsx.snap, src/features/search/pages/__tests__/__snapshots__/LocationFilter.test.tsx.snap, src/features/search/pages/__tests__/__snapshots__/SearchFilter.test.tsx.snap, src/ui/components/headers/PageHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9201
I have:
=> (PC-9201) Add accessbilityLabel and testID on header icons

.circleci/config.yml, scripts/deploy.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9384
I have:
=> (PC-9384) download cert on ios hard build

src/libs/idCheckRetentionClient.ts
=> (Tech) handle 413 as file size exceeded always

package.json, yarn.lock
=> (Tech) bump to 2.1.9 @pass-culture/id-check

src/features/auth/forgottenPassword/__snapshots__/ReinitializePassword.test.tsx.snap, src/features/auth/login/__snapshots__/Login.test.tsx.snap, src/features/favorites/pages/FavoritesSorts.tsx, src/features/favorites/pages/__tests__/__snapshots__/FavoritesSorts.test.tsx.snap, src/features/profile/pages/__snapshots__/ChangePassword.test.tsx.snap, src/features/search/pages/LocationFilter.tsx, src/features/search/pages/__tests__/__snapshots__/LocationFilter.test.tsx.snap, src/ui/components/inputs/rules/InputRule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9110
I have:
=> (PC-9110) Fix position error message go beyound screen view

src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/SetEmail.tsx, src/features/auth/signup/SetPassword.tsx, src/features/auth/signup/SetPostalCode.tsx, src/libs/environment/index.ts, src/libs/random.ts, src/ui/components/inputs/DateInput.tsx
Link to JIRA ticket: no ticket
I have:
=> (Tech) Use developement env variables to accelerate signup for devs

package.json, yarn.lock
=> (Tech) bump to 2.1.10 @pass-culture/id-check

src/features/favorites/pages/FavoritesSorts.tsx, src/features/profile/pages/Profile.tsx, src/features/search/pages/LocationFilter.tsx
Link to JIRA ticket: ==> no ticket
Demande OPS (@mmachado-pass ) pour de-flooder le Sentry.
I have:
=> Remove NoPosition errors to deflood Sentry (we still have PositionError_...)

src/features/auth/signup/AccountCreated.tsx, src/libs/campaign/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9324
I have:
=> (PC-9324) add in-app event for grand public

src/features/auth/signup/SetPhoneNumberModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9119
I have:
=> (PC-9119) SetPhoneNumberModal: open CountryPicker modal on press arrow

__mocks__/@react-native-firebase/firestore.ts, src/App.tsx, src/features/maintenance/useMaintenance.tsx, src/libs/__tests__/remoteStore.test.ts, src/libs/remoteStore.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7109
I have:
- [] Written **documentation on Notion** for my feature.
=> [PC-7109] firestore maintenance

src/features/bookOffer/components/CancellationDetails.tsx, src/features/bookOffer/components/__tests__/CancellationDetails.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9514
I have:
=> (PC-9514) Digital bookings with activation code are not cancellable

android/app/build.gradle, android/build.gradle, ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9373
I have:
=> [PC-9373]  init RN performance

__snapshots__/features/search/pages/__tests__/Search.test.tsx.native-snap, src/features/search/atoms/Buttons/Search.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9397
I have:
=> (PC-9397) Add accessibilityLabel/testID to Offer Search button

__mocks__/react-native-appsflyer.ts, src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/__tests__/BookingDetails.test.tsx, src/libs/campaign/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9657
I have:
=> (PC-9657) add in-app event for book offer

package.json, yarn.lock
=> (Tech) bump to 2.2.2 @pass-culture/id-check

android/app/build.gradle, ios/PassCulture/AppDelegate.m, ios/Podfile, ios/Podfile.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9507
On a besoin d'installer le dispatcher pour remonter le trafic et les données comportementales liées aux campagnes de notifications batch. 
J'ai suivi cette doc : https://doc.batch.com/ios/advanced/event-dispatchers#firebase et https://doc.batch.com/android/advanced/event-dispatchers#firebase
I have:
If native code (ios/android) was modified, …
=> (PC-9507) install BatchFirebaseDispatcher

package.json, yarn.lock
=> (Tech) bump to 2.3.0 @pass-culture/id-check

package.json, yarn.lock
=> (Tech) bump to 2.3.1 @pass-culture/id-check

package.json, src/features/home/contentful/contentful.ts, src/features/home/contentful/index.ts, src/libs/itinerary/useItinerary.ts, src/libs/search/index.ts, src/libs/timer.test.ts, src/ui/components/achievements/index.ts, src/ui/svg/icons/BicolorLogo.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9742
I have:
=> (PC-9742) App Native - Decli Web - Mettre à jour Jest en >=26.0.0 nécessaire pour la décli web

tsconfig.json
=> (Tech) add jest.config.web.js and lingui.config.js to exclude

__snapshots__/features/navigation/TabBar/__tests__/TabBar.test.tsx.web-snap, __snapshots__/features/navigation/__tests__/RootNavigator.test.tsx.web-snap, __snapshots__/features/search/pages/__tests__/SearchFilter.test.tsx.web-snap, jest.config.web.js, jest/jest.setup.ts, web/config/webpack.config.js
=> (Tech) fix webpack configuration

__mocks__/fragmentMock.ts
=> (Tech) fix fragment Mock

android/app/build.gradle, patches/react-native+0.63.3.patch
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9374
[x] code push OK
[x] traductions OK (mêmes les pluriels)
=> [PC-9374] enable hermes

__mocks__/fixtures/booking.ts, __mocks__/react-query.ts, src/features/bookings/api/__tests__/queries.test.ts, src/features/bookings/api/queries.ts, src/features/bookings/pages/BookingDetails.test.tsx, src/features/bookings/pages/BookingDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9733
I have:
=> [PC-9733] fix booking display

ios/PassCulture-tvOS/Info.plist, ios/PassCulture-tvOSTests/Info.plist, ios/PassCulture.xcodeproj/project.pbxproj, ios/PassCulture/Info.plist
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9328
I have:
=> [PC-9328] display french lang on stores

src/features/deeplinks/analytics.test.ts, src/features/deeplinks/analytics.ts, src/libs/__mocks__/analytics.ts, src/libs/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9544
I have:
=> (PC-9544) merge DeeplinkConsultOffer into ConsultOffer

package.json, yarn.lock
=> (Tech) bump to 2.3.2 @pass-culture/id-check

src/features/bookings/components/BookingDetailsCancelButton.native.test.tsx, src/features/bookings/components/BookingDetailsCancelButton.tsx, src/features/bookings/components/BookingDetailsCancelButton.web.test.tsx, src/features/home/__mocks__/api.ts, src/features/home/services/__mocks__/useAvailableCredit.ts, src/features/profile/__mocks__/utils.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7777
I have:
|          
=> [PC-7777] ex beneficiary cancel message

package.json, yarn.lock
=> (Tech) bump to 2.3.4 @pass-culture/id-check

package.json, src/libs/idCheckAnalytics.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9853
I have:
=> (PC-9853) Add idDocumentAcquisitionType() method to idcheck analytics interface

package.json, yarn.lock
=> (Tech) bump to 2.4.1 @pass-culture/id-check

public/index.html, web/config/env.js
=> (PC-8708) Added meta tag with version number in head of index.html

ios/Podfile.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9784
I have:
=> [PC-9784] (deploy ios) match pod lock

src/features/cheatcodes/pages/AppComponents.tsx, src/features/offer/components/ReportOfferDescriptionModal.tsx, src/features/offer/components/ReportOfferReasonModal.tsx, src/features/offer/pages/OfferBody.tsx, src/ui/components/RadioButton.tsx, src/ui/components/SectionRow.tsx, src/ui/components/modals/useModalNavigation.ios.ts, src/ui/components/modals/useModalNavigation.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9483
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9484
I have:
|![Simulator Screen Shot - iPhone 12 - 2021-07-05 at 08 54 02](https://user-images.githubusercontent.com/22886846/124432599-15ff5f80-dd72-11eb-81f6-b353a5a88724.png) …
=> (PC-9483/9484) add RadioButton component and ReportOfferReasonModal

ios/Podfile.lock
=> (Tech) Update podfile

.circleci/config.yml, scripts/check_diff.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9894
Ajout d'un script vérifiant si la diff du merge request inclus des changements hors `^(src|web|public)/`, et skip le build hard si ce n'est pas le cas.
I have:
=> (PC-9894) App Native - Amélioration tech - CI - Réduire les build hard systématiques sur Circle

src/features/offer/services/__tests__/dehumanizeId.test.ts, src/features/offer/services/dehumanizeId.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9867
I have:
=> (PC-9867) fix dehumanizeId for big id

android/app/build.gradle, ios/Podfile.lock
=> :wrench: (ios build) prevent from having files diff

src/api/gen/api.ts, src/features/bookOffer/fixtures/offer.ts, src/features/home/atoms/OfferTile.tsx, src/features/home/atoms/tests/OfferTile.native.test.tsx, src/features/offer/api/snaps/offerResponseSnap.ts, src/features/offer/components/ReportOfferReasonModal.tsx, src/features/offer/components/__tests__/ReportOfferReasonModal.native.test.tsx, src/features/offer/pages/OfferBody.tsx, src/features/offer/services/useReportOffer.ts, src/libs/queryKeys.ts, src/ui/components/RadioButton.tsx, src/ui/components/buttons/ButtonTertiaryBlack.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9491
I have:
|![Simulator Screen Shot - iPhone 12 - 2021-07-13 at 09 23 45](https://user-images.githubusercontent.com/22886846/125437726-e4b10482-bf85-4ac7-bf17-6f38406fb02c.png)|                          |                       |                       |
- if you want an hard deployment of the testing environment, use …
=> (PC-9491) Report offer on reason modal

ios/PassCulture.xcodeproj/project.pbxproj, ios/Podfile, ios/Podfile.lock, patches/react-native+0.64.2.patch
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9969
- Commented `node_modules/react-native/scripts/find-node.sh` with patch-package.
- Upgrade flipper & co as recommended in https://github.com/aiba/react-native-m1/blob/main/README.md and https://github.com/facebook/react-native/issues/31480
- Added `react_native_post_install(installer)` in `Podfile`: https://stackoverflow.com/a/67336115/2127277
- keep react-native 0.64.2 and disable hermes
- keep react-native 0.64.2, keep hermes, disable Flipper in Podfile
- we did not add the Apple M1 Podfile fix, we'll do if necessary
- seems like flipper does not need the extra Podfile fix replacement anymore, at least in my case
- If CI/Fastlane relies on nvm and nvm is not initialized in the shell process, it may break, but it is …
=> (PC-9969) App Native - Amélioration tech - fix upgrade react-native

.env.production, .env.staging, .env.testing
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9844
I have:
=> (PC-9844) Update App Search credentials

src/features/auth/forgottenPassword/ForgottenPassword.tsx, src/features/auth/signup/AcceptCgu.tsx, src/libs/idCheckRetentionClient.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10004
I have:
=> (PC-10004) reduce sentry logging

__snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, src/api/__mocks__/api.ts, src/features/offer/pages/OfferBody.tsx, src/features/offer/pages/tests/OfferBody.native.test.tsx, src/features/offer/pages/tests/renderOfferPageTestUtil.tsx, src/ui/components/inputs/LargeInputContainer.tsx
=> (PC-9491) FIX: call /offers/reports only for logged in users

__snapshots__/features/home/components/tests/HomeBodyPlaceholder.test.tsx.native-snap, __snapshots__/features/home/components/tests/HomeBodyPlaceholder.test.tsx.web-snap, __snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap, __snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap, package.json, src/features/home/components/HomeBody.tsx, src/features/home/components/HomeBodyPlaceholder.tsx, src/features/home/components/OffersModule.tsx, src/features/home/pages/Home.tsx, src/features/home/pages/tests/Home.native.test.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9844
I have:
=> [PC-9844] improve perf

src/features/auth/api.ts, src/features/auth/components/QuitSignupModal.native.test.tsx, src/features/auth/components/QuitSignupModal.tsx, src/features/auth/components/signupComponents.tsx, src/features/auth/projectRedactorSignup/AcceptRedactorCgu.native.test.tsx, src/features/auth/projectRedactorSignup/AcceptRedactorCgu.tsx, src/features/auth/projectRedactorSignup/AcceptRedactorCgu.web.test.tsx, src/features/auth/projectRedactorSignup/RedactorSignupConfirmationEmailSent.native.test.tsx, src/features/auth/projectRedactorSignup/RedactorSignupConfirmationEmailSent.tsx, src/features/auth/projectRedactorSignup/RedactorSignupConfirmationEmailSent.web.test.tsx, src/features/auth/projectRedactorSignup/SetRedactorEmail.native.test.tsx, src/features/auth/projectRedactorSignup/SetRedactorEmail.tsx, src/features/auth/projectRedactorSignup/SetRedactorPassword.native.test.tsx, src/features/auth/projectRedactorSignup/SetRedactorPassword.tsx, src/features/auth/signup/AcceptCgu.tsx, src/features/auth/signup/SetEmail.tsx, src/features/auth/signup/SetPassword.tsx, src/features/auth/signup/SignupConfirmationEmailSent.tsx, src/features/cheatcodes/pages/Navigation.tsx, src/features/navigation/RootNavigator/routes.tsx, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9764
I have:
|![Simulator Screen Shot - iPhone 12 - 2021-07-15 at 17 10 34](https://user-images.githubusercontent.com/22886846/125813992-3373da1d-dede-4935-8dfb-9c90cf09513b.png)
=> (PC-9764) add project redactor signup process

__snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap
=> (PC-9492) Update OfferBody snapshot

__snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap, src/features/home/components/HomeBody.tsx, src/features/home/pages/useHomeModules.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9844
I have:
=> [PC-9844] improve perf bis

__snapshots__/features/auth/signup/SetBirthday.native.test.tsx.native-snap, src/api/helpers.ts, src/features/auth/__mocks__/api.ts, src/features/auth/api.ts, src/features/auth/projectRedactorSignup/AcceptRedactorCgu.native.test.tsx, src/features/auth/projectRedactorSignup/AcceptRedactorCgu.tsx, src/features/auth/projectRedactorSignup/AcceptRedactorCgu.web.test.tsx, src/features/auth/signup/AcceptCgu.tsx, src/features/auth/signup/AccountCreated.native.test.tsx, src/features/auth/signup/AccountCreated.tsx, src/features/auth/signup/SetBirthday.native.test.tsx, src/features/auth/signup/SetBirthday.tsx, src/features/auth/signup/SetEmail.native.test.tsx, src/features/auth/signup/SetEmail.tsx, src/features/auth/signup/SetPassword.tsx, src/features/auth/signup/SetPostalCode.tsx, src/features/cheatcodes/pages/AppComponents.tsx, src/features/offer/pages/OfferBody.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9925
I have:
|![Simulator Screen Shot - iPhone 12 mini - 2021-07-20 at 17 11 05](https://user-images.githubusercontent.com/22886846/126351918-03dbff69-582c-4802-82ba-1fd611f06edb.png)
=> (PC-9925) project redactor signup

src/App.tsx
Related to https://github.com/lingui/js-lingui/issues/1099
=> (Tech) ignore warning for I18nProvider

__snapshots__/features/auth/signup/idCheck/DenyAccessToIdCheck.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap, __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap, __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap, __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, src/ui/components/modals/AppModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10051
I have:
avant : zone bleue cliquable (qui fermait la modale)
après : zone bleue non cliquable
|                      |                          |           
|                       |
=> [PC-10051] fix pressable areas

__snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, src/features/auth/forgottenPassword/ResetPasswordEmailSent.native.test.tsx, src/features/cheatcodes/pages/AppComponents.tsx, src/features/offer/components/ReportOfferReasonModal.tsx, src/features/offer/components/__tests__/ReportOfferReasonModal.native.test.tsx, src/features/offer/pages/tests/OfferBody.native.test.tsx, src/features/offer/services/useReasonsForReporting.ts, src/libs/queryKeys.ts, src/ui/components/RadioButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9943
I have:
|                      |  <img width="378" alt="Capture d’écran 2021-07-13 à 12 36 03" src="https://user-images.githubusercontent.com/62059034/125437881-caf63a05-aeb4-4935-833b-1d453a5bf5cc.png"> <img width="381" alt="Capture d’écran 2021-07-13 à 12 35 50" src="https://user-images.githubusercontent.com/62059034/125437893-8fcc8874-047b-47e8-a2d7-23b2a24b9d1b.png">
|                       |                       |
If native code …
=> (PC-9943) Appel au back pour récupérer la liste des raisons de signalement

android/build.gradle, fastlane/.env.production
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10002
I have:
=> [PC-10002] meet android spec novembre

src/libs/search/filters/buildFacetFilters.ts, src/libs/search/filters/tests/buildFacetFilters.test.ts, src/types/@elastic/app-search-javascript/index.d.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9515
I have:
=> (PC-9515) make sure search by offer types works

src/features/offer/api/snaps/offerReportReasonSnap.ts, src/features/offer/services/__tests__/useReasonsForReporting.test.ts, src/features/offer/services/useReasonsForReporting.ts
=> (Tech) Fix crash related to API call getnativev1offerreportreasons

src/features/navigation/RootNavigator/RootNavigator.tsx, src/features/navigation/RootNavigator/navigationOptions.ts, src/features/navigation/RootNavigator/navigationOptions.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10123
I have:
=> (PC-10123) Fix design animation

fastlane/.env.production
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10002
I have:
=> [PC-10002]:wrench: (android build) update bundle path

src/features/deeplinks/routing.test.ts, src/features/deeplinks/routing.ts, src/features/deeplinks/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10033
I have:
=> (PC-10033) Add new deeplink for venue

src/features/bookOffer/components/Calendar/Calendar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8273
I have:
| avant | après |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/50346870/126768297-4b5bf646-f0e7-47cb-9e63-f2bfcd6f9ab9.png) | ![image](https://user-images.githubusercontent.com/50346870/126768258-7cbf1f4b-ac74-4209-8e66-7b56ee86f795.png) |
=> (PC-8273) remove height on touchableOpacity

__snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, src/ui/components/RadioButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10110
I have:
| \*iOS - [Phone name] | \*Android - Galaxy Nexus (720 x 1280) | Tablet - [Phone name] | Little - [Phone name] |
|                      | <img width="379" alt="Capture d’écran 2021-07-26 à 11 03 10" src="https://user-images.githubusercontent.com/62059034/126964585-a4a3080b-74f1-49a5-8a0c-1e88a886bf65.png"> |                       |                       |
=> (PC-10110) Bug graphique sur la modale de choix de raison de signalement

.circleci/config.yml, .env.production, .env.staging, scripts/deploy.sh
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7507
Pour pouvoir builder stagind ou prod en local, il faut en plus aujourd'hui copier ce qu'il y a dans le 1password
app native production secrets => .env.production
ou 
app native staging secrets => .env.staging
=> [PC-7507] remove secrets from github

__snapshots__/libs/navigation/tests/Link.test.tsx.native-snap, __snapshots__/libs/navigation/tests/Link.test.tsx.web-snap, src/features/navigation/RootNavigator/routes.web.tsx, src/libs/navigation/Link.tsx, src/libs/navigation/tests/Link.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10132
I have:
=> (PC-10132) Enhanced link with route.params for Web

__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent.native.test.tsx.native-snap, __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent.web.test.tsx.web-snap, __snapshots__/features/auth/signup/AccountCreated.native.test.tsx.native-snap, __snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.web-snap, __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap, __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.native.test.tsx.native-snap, __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.web.test.tsx.web-snap, __snapshots__/features/favorites/components/__tests__/NotConnectedFavorites.test.tsx.native-snap, __snapshots__/features/favorites/components/__tests__/NotConnectedFavorites.test.tsx.web-snap, __snapshots__/features/firstLogin/CulturalSurvey.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap, __snapshots__/features/forceUpdate/__tests__/ForceUpdate.test.tsx.native-snap, __snapshots__/features/forceUpdate/__tests__/ForceUpdate.test.tsx.web-snap, __snapshots__/features/navigation/__tests__/RootNavigator.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ConfirmDeleteProfile.test.tsx.native-snap, __snapshots__/features/profile/pages/ConfirmDeleteProfile.test.tsx.web-snap, __snapshots__/features/profile/pages/DeleteProfileSuccess.test.tsx.native-snap, __snapshots__/features/profile/pages/DeleteProfileSuccess.test.tsx.web-snap, __snapshots__/ui/components/achievements/components/GenericAchievement.native.test.tsx.native-snap, __snapshots__/ui/components/achievements/components/GenericAchievement.web.test.tsx.web-snap, src/ui/svg/Background.tsx
=> (Tech) restore bg

__snapshots__/features/venue/components/__tests__/VenueHeader.native.test.tsx.native-snap, __snapshots__/features/venue/components/__tests__/VenueHeader.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/venue/components/VenueHeader.tsx, src/features/venue/components/__tests__/VenueHeader.native.test.tsx, src/features/venue/components/__tests__/VenueHeader.web.test.tsx, src/features/venue/pages/Venue.tsx, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/VenueBody.native.test.tsx, src/features/venue/pages/__tests__/VenueBody.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10039
I have:
|                      | ![scroll_venue](https://user-images.githubusercontent.com/62059034/127118274-970e59cf-9bef-459f-8dea-62a2b2ab0ff4.gif) |                       |                       |
=> (PC-10039) Add header icons appear when scrolling 

__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent.web.test.tsx.web-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.web-snap, __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.web.test.tsx.web-snap, __snapshots__/features/favorites/components/__tests__/NotConnectedFavorites.test.tsx.web-snap, __snapshots__/features/forceUpdate/__tests__/ForceUpdate.test.tsx.web-snap, __snapshots__/features/profile/pages/ConfirmDeleteProfile.test.tsx.web-snap, __snapshots__/features/profile/pages/DeleteProfileSuccess.test.tsx.web-snap, __snapshots__/ui/components/achievements/components/GenericAchievement.web.test.tsx.web-snap, src/ui/svg/Background.web.tsx
=> (Tech) restore Web specific Background SVG

src/features/navigation/RootNavigator/routes.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10147
I have:
=> (PC-10147) App Native - Decli Web - Page de maintenance

src/libs/geolocation/components/WhereSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9612
I have:
=> (PC-9612) Fix analytics.logConsultItinerary typing error

src/features/profile/components/ProfileHeader.native.test.tsx, src/features/profile/components/ProfileHeader.tsx, src/features/profile/components/ProfileHeader.web.test.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10172
I have:
| --- | --- |
| <img width="318" alt="avant" src="https://user-images.githubusercontent.com/10118284/127291690-ea6666ae-20af-40f5-832b-02d3078342a7.png"> | <img width="312" alt="après" src="https://user-images.githubusercontent.com/10118284/127291696-8485522a-901c-43bf-b4dd-eff3f14e46f9.png"> |
=> (PC-10172) Profil : Ajout de l'heure d'expiration du crédit

.circleci/config.yml, src/libs/navigation/Link.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9850
Related to:
https://github.com/pass-culture/pass-culture-app-native/pull/1404 / https://passculture.atlassian.net/browse/PC-9612
I have: …
=> [PC-9850] Decli Web mettre en place la ci pour les environnement testing

__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/venue/api/__mocks__/useVenue.ts, src/features/venue/fixtures/venueResponseSnap.ts, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/Venue.native.test.tsx, src/features/venue/pages/__tests__/Venue.web.test.tsx, src/features/venue/pages/__tests__/VenueBody.native.test.tsx, src/features/venue/pages/__tests__/VenueBody.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10040
I have:
| \*iOS - [Phone name] |
| ![image](https://user-images.githubusercontent.com/50346870/127176842-ed54930f-9814-442a-8510-3b9a8eb42a2b.png) |
=> (PC-10040) Add venue address

__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/VenueBody.native.test.tsx, src/features/venue/pages/__tests__/VenueBody.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10058
I have:
|         
=> [PC-10058] show itinerarysection

.env.production, .env.staging, .env.testing, scripts/generate_api_client.sh, src/api/gen/api.ts, src/api/gen/custom.d.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10184
I have:
=> [PC-10184] redirect to new dns

src/features/offer/pages/OfferBody.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10115
I have:
=> (PC-10115) Activate offer signaling

src/features/search/pages/reducer.ts, src/libs/search/fetch/search.ts, src/libs/search/filters/buildBoosts.ts, src/libs/search/filters/index.ts, src/libs/search/filters/tests/buildBoosts.test.ts, src/types/@elastic/app-search-javascript/index.d.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9990
I have:
| Partout | Autour de moi | Autour de moi + boosted proximity |
| --- | --- | --- |
| <img width="314" alt="partout" src="https://user-images.githubusercontent.com/10118284/127193108-0679690c-12a5-41d9-9514-a289f60d5796.png"> | <img width="318" alt="autour" src="https://user-images.githubusercontent.com/10118284/127193146-e8238bb6-80ab-445c-8169-5015f55c25c4.png"> | <img width="319" alt="boosted" src="https://user-images.githubusercontent.com/10118284/127193132-9082677f-ff29-41d4-93a4-cf4a81afc215.png"> |
=> [PC-9990] App Search: configurer le tri par proximité

src/libs/search/datetime/__tests__/date.test.ts, src/libs/search/datetime/__tests__/time.test.ts, src/libs/search/datetime/date.ts, src/libs/search/datetime/time.ts, src/libs/search/filters/buildNumericFilters.ts, src/libs/search/filters/tests/buildNumericFilters.test.ts, src/libs/search/filters/tests/buildQueryOptions.test.ts, src/libs/search/filters/tests/timeFilters.test.ts, src/libs/search/filters/timeFilters.ts, src/libs/search/utils/buildAlgoliaHit.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10156
I have:
=> [PC-10156] Amélioration perfs AppSearch

src/App.tsx, src/features/auth/AuthContext.tsx, src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx, src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx, src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.native.test.tsx, src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.web.test.tsx, src/features/favorites/pages/FavoritesWrapper.tsx, src/features/favorites/pages/__mocks__/FavoritesWrapper.tsx, src/features/navigation/__tests__/RootNavigator.native.test.tsx, src/features/offer/pages/tests/OfferDescription.native.test.tsx, src/features/offer/pages/tests/renderOfferPageTestUtil.tsx, src/features/profile/pages/Profile.native.test.tsx, src/features/search/pages/SearchWrapper.tsx, src/features/search/pages/__mocks__/SearchWrapper.tsx, src/libs/ABTesting/ABTestingProvider.tsx, src/libs/geolocation/GeolocationWrapper.tsx, src/libs/idCheck/IdCheckContextProvider.tsx, src/libs/splashscreen.tsx, src/ui/components/inputs/CodeInput.tsx, src/ui/components/snackBar/SnackBarContext.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10129
I have:
|![Simulator Screen Shot - iPhone 12 mini - 2021-07-23 at 17 18 34](https://user-images.githubusercontent.com/22886846/126805110-5592d286-df25-4032-bc4f-2225d288d223.png)
=> (PC-10129) phone validation logs + use input mask for code

__snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/api/helpers.ts, src/features/bookings/components/BookingDetailsHeader.tsx, src/features/bookings/pages/BookingDetails.tsx, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/offer/components/OfferHeader.tsx, src/features/offer/pages/Offer.tsx, src/features/offer/pages/OfferBody.tsx, src/features/venue/components/VenueHeader.tsx, src/features/venue/components/__tests__/VenueHeader.native.test.tsx, src/features/venue/pages/Venue.tsx, src/features/venue/pages/VenueBody.tsx, src/features/venue/services/useShareVenue.ts, src/locales/fr/messages.po, src/ui/components/headers/animationHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10037
I have:
example d'url généré: https://passcultureapptesting.page.link/?link=https://app-native.testing.internal-passculture.app/venue?id=5591&apn=app.passculture.testing&isi=1557887412&ibi=app.passculture.test&efr=1
=> (PC-10037) Je peux partager la page de détail d'un lieu

src/features/auth/signup/PhoneValidation/SetPhoneNumber.tsx
=> (Tech) fix web typing for building the web app

__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/venue/api/useVenueOffers.ts, src/features/venue/components/VenueOffers.tsx, src/features/venue/pages/Venue.tsx, src/features/venue/pages/VenueBody.tsx, src/libs/queryKeys.ts, src/libs/search/fetch/index.tsx, src/libs/search/fetch/search.ts, src/libs/search/index.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10043
I have:
=> [PC-10043] Je vois la liste d'offres disponibles d'un lieu en mode carrousel [Partie 1/2]

src/libs/errorMonitoring/services.ts
=> (readibility) errorMonitoring module

web/config/paths.js, web/config/webpack.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9625
Pour FIX le build de la web app
https://app.circleci.com/pipelines/github/pass-culture/pass-culture-app-native/7294/workflows/a65aea47-69d5-40ee-bc97-e907423fa14d/jobs/12271
I have:
- if you want an hard deployment …
=> (Web) Fix build with inject manifest for sw

public/index.html
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10250
I have:
=> (Tech) fix bg background color on chrome

src/service-worker.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9625
Il manquait l'import du script dans le sw:
https://doc.batch.com/web/advanced/integrating-batch-with-existing-service-worker
I have: …
=> (PC-9625) Import batch into sw for Web

src/ui/svg/icons/categories/bicolor/Exposition.tsx
=> (Tech) fix Expositon svg for the web

__snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/ui/components/hero/useHeroDimensions.tsx
I have:
|                      |  <img width="338" alt="Capture d’écran 2021-08-03 à 14 27 29" src="https://user-images.githubusercontent.com/62059034/128016049-5ee4bfd0-d090-4610-9b52-9a0e5490476c.png"> <img width="337" alt="Capture d’écran 2021-08-03 à 14 27 47" src="https://user-images.githubusercontent.com/62059034/128016063-df3769da-b746-4caf-9899-d8a6fed1ba99.png"> <img width="339" alt="Capture d’écran 2021-08-03 à 14 27 12" src="https://user-images.githubusercontent.com/62059034/128016079-5cd88126-425d-4c10-92e2-f9aa54275249.png"> <img width="340" alt="Capture d’écran 2021-08-03 …
=> (Tech) Fix correct height for Hero Venue / Offer

src/features/navigation/RootNavigator/routes.web.tsx
=> (PC-10275) add web route to venue

__snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/ui/components/hero/useHeroDimensions.tsx
I have:
| \*Web - [landscape] | \*Web - [Portrait] | Android - [Portrait] | Android - [Landscape] |
| ![image](https://user-images.githubusercontent.com/77674046/128176370-bb0f7b2d-af81-4a0e-879a-0280129fc60c.png) | ![image](https://user-images.githubusercontent.com/77674046/128176481-33a4af8b-d513-44d2-8cad-e4a29194da55.png) | ![image](https://user-images.githubusercontent.com/77674046/128178352-e89154e8-0863-4282-af7a-bfea6423d777.png) | ![image](https://user-images.githubusercontent.com/77674046/128178365-3a9e4b55-e61d-4603-bd01-b69eb73ecdf …
=> (Tech) fix product image dimensions

src/features/auth/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx, src/features/auth/signup/idCheck/useNavigateToIdCheck.ts, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/deeplinks/listener.web.ts, src/features/deeplinks/routing.test.ts, src/features/deeplinks/routing.ts, src/features/navigation/RootNavigator/routes.tsx, src/features/navigation/RootNavigator/routes.web.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/TabBar/routes.tsx, src/features/navigation/screenParamsParser.ts
=> (PC-10260) Make signup email confirmation work on the web

src/libs/react-native-batch.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9625
I have:
=> (PC-9625) prod like batch settings

src/features/bookings/api/queries.ts, src/features/navigation/RootNavigator/routes.web.tsx, src/features/navigation/screenParamsParser.ts, web/config/webpack.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10219
I have:
=> (PC-10219) Web version bookings

public/.well-known/apple-app-site-association, public/.well-known/assetlinks-production.json, public/.well-known/assetlinks-staging.json, public/.well-known/assetlinks-testing.json
=> (PC-10260) Add config files to identify the native app relative to the web app

__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/venue/pages/VenueBody.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10040
I have:
|                      | <img width="385" alt="Capture d’écran 2021-08-05 à 15 51 09" src="https://user-images.githubusercontent.com/62059034/128362495-9a8ded7c-fefd-46f4-b154-3d8aa565bf55.png">  |                       |                       |
=> (PC-10040) Center venue address container

.env.testing
=> (PC-10260) Modify UNIVERSAL_LINK to use new web app v2

__mocks__/@react-navigation/native.ts, __snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap, src/features/auth/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx, src/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx, src/features/auth/signup/NextBeneficiaryStep/tests/NextBeneficiaryStep.native.test.tsx, src/features/deeplinks/routing.test.ts, src/features/deeplinks/routing.ts, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsParser.ts
=> (PC-10260) Make reset password work on the web

src/libs/react-native-batch.web.ts, src/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10362
I have:
=> (PC-10362): Web implementation of push notifications

src/libs/react-native-batch.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10362
I have:
=> (PC-10362) fix web push notification in testing env

src/libs/react-native-batch.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10362
I have:
[PC-10362]: https://passculture.atlassian.net/browse/PC-10362
=> (PC-10362) web notification icon for firefox

src/libs/jwt.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10194
La mise à jour de Flask-JWT-Extended dans [cette PR](https://github.com/pass-culture/pass-culture-api/pull/2934/files) a donné lieu à un rapprochement vers [le standard utilisé un peu partout](https://auth0.com/docs/tokens/json-web-tokens/json-web-token-claims#reserved-claims), c'est à dire mettre l'identification dans un champ sub
=> (PC-10194) Change identity key

__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/auth/__mocks__/settings.ts, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/Venue.native.test.tsx, src/features/venue/pages/__tests__/Venue.web.test.tsx, src/features/venue/pages/__tests__/VenueBody.native.test.tsx, src/features/venue/pages/__tests__/VenueBody.web.test.tsx
=> (Flaky test) Mock useAppSettings in Venue* tests and remove react-query mock and HOC

ios/Podfile.lock, src/features/auth/login/Login.tsx, src/features/deeplinks/routing.test.ts, src/features/deeplinks/routing.ts, src/features/deeplinks/useDeeplinkUrlHandler.test.ts, src/features/deeplinks/useDeeplinkUrlHandler.ts, src/features/deeplinks/utils.ts, src/features/navigation/RootNavigator/routes.web.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/TabBar/routes.tsx, src/features/navigation/TabBar/types.ts, src/features/navigation/screenParamsParser.ts
=> (PC-10260) Add query param parser to all deeplinks related routes

src/features/navigation/screenParamsParser.ts
=> (PC-10260) Fix unexpected any with identityFn of screenParamsParser

.env.production, .env.staging
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10362
I have:
=> (PC-10362) Web push notifications prod and staging envs

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap, src/features/search/pages/SearchFilter.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8593
I have:
| <img width="374" alt="Capture d’écran 2021-08-11 à 15 20 47" src="https://user-images.githubusercontent.com/62059034/129037982-d77535dd-bd35-445c-9086-434c2aae1b0d.png"> |            | <img width="1100" alt="Capture d’écran 2021-08-11 à 15 22 28" src="https://user-images.githubusercontent.com/62059034/129038033-d3d6c175-6492-41c9-ac36-60a8ba39f17f.png">  |                       |
=> (PC-8593) Fix results button center on tablet

__snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, __snapshots__/ui/components/buttons/ButtonWithLinearGradient.test.tsx.native-snap, __snapshots__/ui/components/buttons/ButtonWithLinearGradient.test.tsx.web-snap, src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/offer/components/index.ts, src/features/offer/pages/Offer.tsx, src/features/search/atoms/Buttons/Search.tsx, src/features/venue/components/VenueOffers.tsx, src/ui/components/buttons/ButtonWithLinearGradient.test.tsx, src/ui/components/buttons/ButtonWithLinearGradient.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10044
I have:
| <img width="377" alt="Capture d’écran 2021-08-12 à 09 41 41" src="https://user-images.githubusercontent.com/62059034/129157719-93eb2138-f87d-4844-ab03-d3cb31de8d7c.png"> <img width="376" alt="Capture d’écran 2021-08-12 à 11 56 05" src="https://user-images.githubusercontent.com/62059034/129177923-c0de8e6f-0c99-4f02-bc2d-83d37bc66346.png"> |                          |                       |                       |
=> (PC-10044) Add See all offers button (design)

src/features/auth/components/QuitSignupModal.native.test.tsx, src/features/auth/components/QuitSignupModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10262
I have:
| <img width="376" alt="Capture d’écran 2021-08-13 à 10 49 59" src="https://user-images.githubusercontent.com/62059034/129331226-e831cdd6-8db0-4157-bd43-fa5786566d48.png"> |                          |                       |                       |
=> (PC-10262) Fix bugs wording - App native

src/features/auth/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9085
I have:
|                      |                          |                       | <img width="546" alt="Capture d’écran 2021-08-13 à 17 46 31" src="https://user-images.githubusercontent.com/62059034/129385035-d939b3aa-817b-411d-800d-f727175bf101.png"> |
=> (PC-9085) Fix non centered text for long email address

__snapshots__/features/home/components/tests/BusinessModule.native.test.tsx.native-snap, __snapshots__/features/home/components/tests/BusinessModule.web.test.tsx.web-snap, src/features/home/components/BusinessModule.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-6479
I have:
| \*iOS - iPhone X | \*Android - [Phone name] | Tablet - [Phone name] | Little - iPhone 5 |
| <img width="392" alt="after_X" src="https://user-images.githubusercontent.com/62059034/129530254-ceaf00a2-e2ed-4e79-992b-455e948e4f0f.png"> |                          |                       |  <img width="694" alt="Capture d’écran 2021-08-16 à 09 54 23" src="https://user-images.githubusercontent.com/62059034/129530233-630d66e4-4b39-4f3d-bff5-bf5f010591ce.png"> |
=> (PC-6479) Fix the line break of the business block (small devices)

__snapshots__/features/search/pages/__tests__/SearchFilter.native.test.tsx.native-snap, src/ui/components/FilterSwitch.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8855
I have:
| \*iOS - iPhone X | \*Android - [Phone name] | Tablet - [Phone name] | Little - iPhone 5 |
| <img width="582" alt="Capture d’écran 2021-08-16 à 16 47 46" src="https://user-images.githubusercontent.com/62059034/129583015-560f3516-3ec3-4d9a-ad78-1efe2882c408.png"> <img width="573" alt="Capture d’écran 2021-08-16 à 16 47 32" src="https://user-images.githubusercontent.com/62059034/129583016-2c0fbcf4-74de-440c-879c-ebfd77460dde.png"> |                          |                       | <img width="471" alt="Capture d’écran 2021-08-16 à 16 48 15" src="https://user-images.githubusercontent.com/62059034/129583054-e7 …
=> (PC-8855) Adjusting the margins of the FilterSwitch toggle

__snapshots__/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx.native-snap, __snapshots__/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx.web-snap, src/features/search/atoms/Buttons/Filter.tsx, src/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx, src/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8688
I have:
|          <img width="331" alt="Capture d’écran 2021-08-16 à 17 26 00" src="https://user-images.githubusercontent.com/44037911/129588566-2372fb63-330f-4b23-b4f5-77380fa48eaa.png">            |      <img width="331" alt="Capture d’écran 2021-08-16 à 17 19 15" src="https://user-images.githubusercontent.com/44037911/129588248-6f4b26c2-d6a0-4238-8fc6-be8725d44cc7.png"> |                       |                       |
If native code …
=> 🐛 [PC-8688] filter button - delete extra whitespace

src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx, src/features/bookOffer/fixtures/offer.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10285
I have:
=> (PC-10285) Only book bookable stocks for Thing offers

src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts, src/features/offer/services/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9774
I have:
=> (PC-9774) beneficiary users should not be able to book educational offers

.circleci/config.yml
=> [PC-9851]Decli Web mettre en place la ci pour les environnement staging

src/features/offer/services/__tests__/dehumanizeId.test.ts, src/features/offer/services/dehumanizeId.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10375
I have:
=> (PC-10375) fix bug on offer id

src/features/venue/pages/__tests__/Venue.native.test.tsx, src/features/venue/pages/__tests__/Venue.web.test.tsx, src/features/venue/pages/__tests__/VenueBody.native.test.tsx, src/features/venue/pages/__tests__/VenueBody.web.test.tsx
=> (Tech) Fix flaky tests for VenueBody

package.json, yarn.lock
=> (Tech) bump to 2.4.5 @pass-culture/id-check

.circleci/config.yml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10506
I have:
=> (PC-10506) Optimisation du temps de tests en CI

ios/Podfile.lock, package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10507
I have:
=> (PC-10507) SearchFilters : selection par date génère une erreur sur le Web

src/features/offer/components/OfferHeader.tsx, src/features/offer/services/isSharingSupported.ts, src/features/venue/components/VenueHeader.tsx, src/tests/setupTests.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10510
I have:
=> (PC-10510) Show "share" buttons only if sharing is supported

README.md
=> (Tech) improve readme ios configuration

package.json, yarn.lock
=> (PC-9663) Ajout de react-helmet

package.json, src/App.web.tsx, src/features/offer/pages/Offer.tsx, src/features/offer/pages/OfferWebHead/OfferWebHead.tsx, src/libs/appWebHead.tsx, src/libs/idCheck/IdCheckContextProvider.tsx, src/libs/react-helmet/Helmet.tsx, src/libs/react-helmet/Helmet.web.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9663
I have:
=> (PC-9663) Using global helmet and offer helmet

__snapshots__/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx.native-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.web-snap, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/errors/index.ts, src/features/errors/pages/OfferNotFoundErrorBoundary.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/screenParamsUtils.ts, src/features/offer/api/useOffer.ts, src/features/offer/pages/Offer.tsx, src/libs/compose.ts, src/libs/errorMonitoring/errors.ts, src/libs/errorMonitoring/index.ts, src/ui/components/GenericInfoPage.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10359
I have:
| \*iOS - [Phone name] | \*Android - OnePlus 5 | Desktop (Chrome) |
| -------------------- | :---------------------- |----------------------|
|                      | ![image](https://user-images.githubusercontent.com/22399093/130461423-13966ca4-e79f-4ce7-b08f-8f201ef6278a.png)  |  ![image](https://user-images.githubusercontent.com/22399093/130461183-03dae6e1-2d06-43ce-bb0e-a79fe89ed92f.png) |
=> (PC-10359) Display error component when offer is not found

__snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/home/atoms/SeeMore.tsx, src/features/home/atoms/tests/SeeMore.native.test.tsx, src/features/home/components/OffersModule.tsx, src/features/offer/pages/OfferBody.tsx, src/features/venue/api/__mocks__/useVenueOffers.ts, src/features/venue/api/useVenueOffers.ts, src/features/venue/components/VenueOffers.tsx, src/features/venue/pages/VenueBody.tsx, src/libs/search/fetch/search.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10478
I have:
=> (PC-10478) Je vois le bouton 'voir plus' du carrousel des offres

public/index.html, src/features/offer/pages/OfferWebHead/OfferWebHead.tsx, src/libs/appWebHead.tsx, src/libs/react-helmet/metas/openGraphMetas.tsx, src/libs/react-helmet/metas/twitterMetas.tsx, web/config/webpack.config.js
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9663
I have:
=> (PC-9663) Added twitterMetas and openGraphMetas, set metas for offer (testing)

src/features/errors/index.ts, src/features/errors/pages/OfferNotFoundErrorBoundary.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10359
I have:
=> (PC-10359) Fix error fallback not removed after navigating back to an offer page

src/features/offer/pages/OfferWebHead/OfferWebHead.tsx
=> (Tech) Web: testing offer with fixed og and twitter metas

.circleci/config.yml
=> [PC-9852]App Native - Decli Web mettre en place la ci pour les env prod

.circleci/config.yml
=> [PC-10537] Fix-CI-after-merge-PC9852

src/features/navigation/NavigationContainer/index.web.tsx, src/features/offer/pages/OfferWebHead/OfferWebHead.tsx
=> (Tech) WebApp - testing metas

public/index.html
=> (PC-9663) Rename name to property for twitter metas

public/index.html
=> (Tech) WebApp - setting name instead of property for all twitter metas

src/features/navigation/RedirectWebToNative.tsx, src/features/navigation/RootNavigator/linking/index.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/navigation/TabBar/routes.ts, src/libs/web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10615
I have:
| Desktop web |
| -------------------- | 
| ![Screenshot 2021-08-30 at 12 10 35](https://user-images.githubusercontent.com/22399093/131323778-a0667598-38b5-49b3-9263-81acf92ab9a7.png) |
=> (PC-10615) Redirection des pages web qui ne sont pas encore prêtes pour la prod

src/features/navigation/TabBar/TabNavigator.tsx, src/features/offer/components/OfferHeader.tsx, src/libs/web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10615
I have:
=> (PC-10615) Désactivation de certaines fonctionnalités pour le web de prod

android/app/build.gradle
Second part of https://github.com/pass-culture/pass-culture-app-native/pull/1585
=> (Tech) disable LeakCanary (part 2)

src/features/search/sections/Location.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10075
I have:
=> (PC-10075) Make sure icon color is black on location section

src/features/search/utils/getFilterCount.ts, src/features/search/utils/tests/getFilterCount.test.ts
…or location filter
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10075
I have:
=> (PC-10075) Je peux filtrer mes résultats de recherche sur un lieu spécifique (part 2)

.env.production
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10681
I have:
=> (PC-10681) App Native - Décli Web - Configuration de production de APP_PUBLIC_URL

src/features/navigation/helpers.ts, src/ui/components/SocialNetworkCard.tsx, src/ui/components/socials/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8595
I have:
=> (PC-8595) Add condition for facebook link to open when app is not installed

src/features/auth/AuthContext.tsx, src/features/home/components/OffersModule.tsx, src/features/home/pages/tests/useHomeModules.test.ts, src/features/home/pages/useHomeModules.ts, src/features/profile/utils.ts, src/features/search/components/SearchLandingPage.tsx, src/features/search/enums.ts, src/features/search/pages/Categories.tsx, src/features/search/pages/__tests__/Categories.test.tsx, src/features/search/pages/useSearchResults.ts, src/features/search/sections/Category.tsx, src/features/search/sections/tests/Category.test.tsx, src/features/search/sections/tests/analytics.native.test.tsx, src/features/search/utils/tests/useAvailableCategories.test.ts, src/features/search/utils/tests/useAvailableSearchCategories.test.ts, src/features/search/utils/useAvailableCategories.ts, src/features/search/utils/useAvailableSearchCategories.ts, src/libs/search/__tests__/parseSearchParameters.test.ts, src/libs/search/index.ts, src/libs/search/parseSearchParameters.ts, src/libs/search/useParseSearchParameters.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10501
I have:
|Underage beneficiary | Other|
|![Simulator Screen Shot - iPhone 12 mini - 2021-08-31 at 17 29 56](https://user-images.githubusercontent.com/22886846/131534391-96f390a5-8ad6-4c70-80c6-674e4d847098.png)![Simulator Screen Shot - iPhone 12 mini - 2021-08-31 at 17 28 07](https://user-images.githubusercontent.com/22886846/131534385-c00ec3d9-adee-4a82-a14e-2c951336b626.png)<img width="306" alt="Capture d’écran 2021-08-31 à 17 54 08" src="https://user-images.githubusercontent.com/22886846/131535666-89d4b334-82f4-402b-b4b9-363c01aff102.png">|![Simulator Screen Shot - iPhone 12 mini - …
=> (PC-10501) bénéficiaires mineurs: ne pas afficher les offres jeux vidéos

__snapshots__/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx.native-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.web-snap, src/ui/components/GenericInfoPage.tsx, src/ui/components/modals/AppFullPageModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10699
I have:
| \*iOS - [Phone name] | \*Android - [Galaxy S9] | Tablet - [Phone name] | Web - [Desktop] |
|                      | ![image](https://user-images.githubusercontent.com/77674046/132217764-0e7fae92-4196-44af-90d9-b0e147b9f811.png) |                       | ![image](https://user-images.githubusercontent.com/77674046/132217500-9b5ec07d-501a-4078-8fc6-08bf8b5bdf19.png) |
- if you want an hard deployment of …
=> (PC-10699) Decli Web - Fix - Regression bouton close sur le parcours d inscription

src/libs/search/fetch/search.ts
=> (Tech) fix error with algolia search.ts nbHits

__snapshots__/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx.native-snap, __snapshots__/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx.web-snap, __snapshots__/features/venue/components/__tests__/VenueOffers.test.tsx.native-snap, __snapshots__/features/venue/components/__tests__/VenueOffers.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/venue/atoms/VenueOfferTile.tsx, src/features/venue/fixtures/venueResponseSnap.ts, src/features/venue/pages/VenueBody.tsx, src/ui/components/PartialAccordionDescription.tsx, src/ui/components/__tests__/PartialAccordionDescription.native.test.tsx, src/ui/svg/icons/ArrowDown.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10041
I have:
| <img width="375" alt="Capture d’écran 2021-09-06 à 11 41 37" src="https://user-images.githubusercontent.com/62059034/132196607-141a335a-5d80-47b6-beb5-a352c8b91e0e.png"> <img width="375" alt="Capture d’écran 2021-09-06 à 11 40 58" src="https://user-images.githubusercontent.com/62059034/132196615-2142b3cf-748b-46a4-aa61-f5d9928112f6.png"> <img width="375" alt="Capture d’écran 2021-09-06 à 11 40 47" src="https://user-images.githubusercontent.com/62059034/132196620-31a0c053-d218-45ee-a0a8-b5c0f8700994.png"> | …
=> (PC-10041) Je vois la description du lieu

src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts, src/features/offer/services/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10502
I have:
Dans le cadre du chantier EAC individuel, on restreint l'accès à certaines catégories d'offres (jeux vidéos par exemples). Dans le ticket 10501 on a mis en place la notion de catégories autorisées dans l'app en fonction du rôle de l'utilisateur (cf useAvailableCategories) et un préfiltrage du catalogue des offres. Dans le ticket 10502 …
=> (PC-10502) restrict access to book offer cta if offer category is not allowed

__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/ui/components/PartialAccordionDescription.tsx, src/ui/components/__tests__/PartialAccordionDescription.native.test.tsx, src/ui/hooks/useElementHeight.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10041
I have:
|  ![Simulator Screen Recording - iPhone 8 - 2021-09-08 at 15 22 24](https://user-images.githubusercontent.com/62059034/132517897-13ef0227-b9fa-4e01-bf68-44ee0b5ddc69.gif) |                          |                       |                       |
=> (PC-10041) Fix "voir plus" button for PartialAccordionDescription

package.json, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts, yarn.lock
=> (Tech) upgrade @pass-culture/id-check to v2.5.1 (include preview)

__snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.native-snap, __snapshots__/libs/geolocation/components/__tests__/WhereSection.test.tsx.web-snap, src/libs/geolocation/components/WhereSection.tsx, src/ui/components/PartialAccordionDescription.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10072
I have:
| <img width="376" alt="Capture d’écran 2021-09-09 à 11 44 56" src="https://user-images.githubusercontent.com/62059034/132664318-26e7b530-5e76-4cb3-8b58-096fec03cdd7.png"> <img width="376" alt="Capture d’écran 2021-09-09 à 11 47 43" src="https://user-images.githubusercontent.com/62059034/132664324-d546653a-a8d7-4911-89c5-a3bbda9190c4.png">  |                          |                       |                       |
=> (PC-10072) Add new WhereSection design for offerBody

__snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/venue/atoms/__tests__/IconWithCaption.test.tsx, src/features/venue/components/__tests__/VenueIconCaption.native.test.tsx, src/features/venue/components/__tests__/VenueIconCaption.web.test.tsx, src/libs/parsers/venueType.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10730
I have:
| <img width="376" alt="Capture d’écran 2021-09-09 à 12 18 47" src="https://user-images.githubusercontent.com/62059034/132669810-742d3fa4-f1b3-464f-ae78-397aa7b76aa5.png">  |                          |                       |                       |
=> (PC-10730) Update wording for other venue type

__snapshots__/features/venue/atoms/__tests__/IconWithCaption.test.tsx.native-snap, __snapshots__/features/venue/atoms/__tests__/IconWithCaption.test.tsx.web-snap, __snapshots__/features/venue/atoms/__tests__/VenueType.test.tsx.native-snap, __snapshots__/features/venue/atoms/__tests__/VenueType.test.tsx.web-snap, __snapshots__/features/venue/components/__tests__/VenueIconCaption.native.test.tsx.native-snap, __snapshots__/features/venue/components/__tests__/VenueIconCaption.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/features/venue/atoms/IconWithCaption.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10730
I have:
| <img width="376" alt="Capture d’écran 2021-09-09 à 18 21 35" src="https://user-images.githubusercontent.com/62059034/132724364-b9b0480e-bc1f-495a-b481-7a41ec05773e.png"> |                          |                       |                       |
=> (PC-10730) Fix space betwen venue type and icon

src/features/offer/pages/tests/OfferBody.native.test.tsx, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts, src/libs/geolocation/components/WhereSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10762
I have:
=> (PC-10762) Tracking - Clic sur la consultation d'un lieu

src/features/venue/components/__tests__/VenueHeader.native.test.tsx, src/features/venue/components/__tests__/VenueHeader.web.test.tsx, src/features/venue/services/useShareVenue.ts, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10761
I have:
=> (PC-10761) Tracking - Clic sur le bouton de partage d'un lieu

src/features/venue/atoms/VenueOfferTile.tsx, src/features/venue/atoms/__tests__/VenueOfferTile.native.test.tsx, src/features/venue/atoms/__tests__/VenueOfferTile.web.test.tsx, src/features/venue/components/VenueOffers.tsx, src/libs/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10756
I have:
=> (PC-10756) Tracking - Clic sur la consultation d'une offre

src/features/venue/components/VenueOffers.tsx, src/features/venue/components/__tests__/VenueOffers.test.tsx, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10756
I have:
=> (PC-10758) Tracking - Clic sur le bouton voir plus du carroussel

src/features/offer/pages/OfferBody.tsx, src/features/offer/pages/tests/Offer.analytics.native.test.tsx, src/features/venue/components/__tests__/VenueOffers.test.tsx, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/Venue.analytics.native.test.tsx, src/features/venue/pages/__tests__/Venue.native.test.tsx, src/features/venue/pages/__tests__/Venue.web.test.tsx, src/features/venue/pages/__tests__/VenueBody.native.test.tsx, src/features/venue/pages/__tests__/VenueBody.web.test.tsx, src/libs/analytics/analytics.ts, src/ui/components/AccordionItem.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10755
I have:
=> (PC-10755) Tracking - Clic sur les modalités de retrait

src/features/offer/pages/OfferBody.tsx, src/features/offer/pages/tests/Offer.analytics.native.test.tsx, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/Venue.analytics.native.test.tsx, src/libs/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10754
I have:
=> (PC-10754) Tracking - Clic sur les modalités d'accessibilité

src/features/bookings/pages/BookingDetails.tsx, src/features/offer/pages/OfferBody.tsx, src/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/Venue.analytics.native.test.tsx, src/libs/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10753
I have:
=> (PC-10753) Tracking - Clic sur l'itinéraire d'un lieu

src/features/forceUpdate/ForceUpdate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9949
I have:
=> [PC-9949] (ForceUpdate) use correct links

src/features/profile/components/BeneficiaryHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10304
I have:
| \*iOS - [Phone name] | \*Android - [Phone name] | Desktop - [Phone name] | Little - [Phone name] |
| ![image](https://user-images.githubusercontent.com/77674046/133109272-8c80d5cb-51a3-4a8c-bf2c-33e640659aab.png)  | ![image](https://user-images.githubusercontent.com/77674046/133108928-009d3dba-4cc3-4ea1-a4b7-ee4f1acf4070.png) | ![image](https://user-images.githubusercontent.com/77674046/133105551-09924137-848e-4414-9d54-708545167aac.png)
|                       |
If native code (ios/android) was modified, **after** the PR is …
=> (PC-10304) Ecran profil connecté bénéficiaire, background fix

__mocks__/@react-native-firebase/firestore.ts, jest/jest.setup.ts, src/features/home/pages/useHomeModules.ts, src/features/maintenance/useMaintenance.tsx, src/features/search/pages/useSearchResults.ts, src/libs/firestore/__tests__/maintenance.test.ts, src/libs/firestore/__tests__/searchLoad.test.ts, src/libs/firestore/client.ts, src/libs/firestore/maintenance.ts, src/libs/firestore/searchLoad.ts, src/libs/firestore/types.ts, src/libs/queryKeys.ts, src/libs/search/__mocks__/useSendAdditionalRequestToAppSearch.ts, src/libs/search/useSendAdditionalRequestToAppSearch.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10774
I have:
=> (PC-10774) Systématiquement requêter App Search en tâche de fond depuis l'app native (de façon contrôlée)

src/libs/firestore/__tests__/searchLoad.test.ts
fix linter error => due to https://github.com/pass-culture/pass-culture-app-native/commit/dc726366bb1f7c09a4e84782b634294cbc4af4a7
=> fix linter error

src/libs/analytics/analytics.ts, src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10760
I have:
=> (PC-10760) Fix analytics event VenueContact

src/features/auth/signup/PhoneValidation/PhoneValidationTooManyAttempts/tests/PhoneValidationTooManyAttempts.native.test.tsx, src/features/auth/signup/PhoneValidation/PhoneValidationTooManyAttempts/tests/PhoneValidationTooManyAttempts.web.test.tsx, src/features/auth/signup/PhoneValidation/PhoneValidationTooManySMSSent/PhoneValidationTooManySMSSent.tsx, src/features/auth/signup/PhoneValidation/PhoneValidationTooManySMSSent/index.tsx, src/features/auth/signup/PhoneValidation/PhoneValidationTooManySMSSent/tests/PhoneValidationTooManySMSSent.native.test.tsx, src/features/auth/signup/PhoneValidation/PhoneValidationTooManySMSSent/tests/PhoneValidationTooManySMSSent.web.test.tsx, src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10745
I have:
=> [PC-10745] add error page phone validation

src/features/deeplinks/getScreenFromDeeplink.ts, src/features/deeplinks/listener.android.ts, src/features/home/pages/Home.tsx, src/features/navigation/NavigationContainer/NavigationContainer.tsx, src/features/navigation/RootNavigator/linking/getPathFromState.ts, src/features/navigation/RootNavigator/linking/getStateFromPath.ts, src/features/navigation/RootNavigator/linking/index.ts, src/libs/typesUtils/typeHelpers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10796
I have:
=> (PC-10796) Use custom listener for iOS deeplinks instead of R.Nav.

src/features/home/pages/tests/useHomeModules.test.ts, src/libs/search/useSendAdditionalRequestToAppSearch.web.ts
=> (Tech) fix web build

src/features/search/api/useVenues.ts, src/features/search/pages/SuggestedPlaces.tsx, src/features/search/pages/__tests__/SuggestedPlaces.native.test.tsx, src/features/search/pages/__tests__/SuggestedPlaces.web.test.tsx, src/features/search/pages/reducer.ts, src/features/search/types.ts, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts, src/libs/place/types.ts, src/libs/search/fetch/search.ts, src/libs/search/utils/buildAlgoliaHit.ts, src/libs/venue/fixtures/mockedSuggestedVenues.ts, src/libs/venue/index.ts, src/libs/venue/types.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10763
I have:
=> (PC-10763) Tracking - Clic sur une localisation sur un lieu

package.json, yarn.lock
=> (Tech) bump to 2.5.2 @pass-culture/id-check

__snapshots__/features/bookOffer/components/__tests__/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/bookOffer/components/__tests__/BookingEventChoices.native.test.tsx.native-snap, __snapshots__/features/bookOffer/components/__tests__/BookingEventChoices.web.test.tsx.web-snap, src/features/bookOffer/components/BookingDetails.tsx, src/features/bookOffer/components/BookingEventChoices.tsx, src/features/bookOffer/components/CancellationDetails.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9282
I have:
| Little - [Phone name] |
| :--------------------: |
| <img width="651" alt="Capture d’écran 2021-09-15 à 14 53 03" src="https://user-images.githubusercontent.com/62059034/133437033-b78b66ed-e49d-4e79-85b6-73292749bde0.png"><img width="650" alt="Capture d’écran 2021-09-15 à 14 53 16" src="https://user-images.githubusercontent.com/62059034/133437039-73e2ffe7-7d92-4c33-a4a6-b0aa2ecfb7cd.png"><img width="652" alt="Capture d’écran 2021-09-15 à 14 53 29" src="https://user-images.githubusercontent.com/62059034/133437040-7a784c75-2719-4c91-a70c-ecbfe02bb0ea.png"> |
=> (PC-9282) Fix booking modal design for small device

src/features/home/pages/Home.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10876
I have:
=> (PC-10876) Fix iOS deeplinks opened temporarily the, redirected to home

__snapshots__/features/bookOffer/components/__tests__/BookHourChoice.native.test.tsx.native-snap, __snapshots__/features/bookOffer/components/__tests__/BookingEventChoices.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/favorites/pages/__tests__/Favorites.native.test.tsx.native-snap, __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, __snapshots__/features/search/atoms/__tests__/Hit.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, src/features/bookOffer/atoms/ChoiceBloc.tsx, src/features/bookings/components/BookingItemTitle.tsx, src/features/bookings/components/EndedBookingItem.tsx, src/features/bookings/components/EndedBookingTicket.tsx, src/features/bookings/components/OnGoingBookingItem.tsx, src/features/bookings/components/OnGoingTicket.tsx, src/features/profile/components/BeneficiaryHeader.tsx, src/features/profile/components/ExBeneficiaryHeader.tsx, src/features/profile/components/LoggedOutHeader.tsx, src/features/search/atoms/Hit.tsx, src/ui/components/headers/SvgPageHeader.tsx, src/ui/components/hero/HeroHeader.tsx, src/ui/theme/dimensions.ts, src/ui/theme/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10541
I have:
=> (PC-10541)  Dynamic resizing : remove all Dimensions.get but one

__snapshots__/features/auth/forgottenPassword/ReinitializePassword/tests/ReinitializePassword.native.test.tsx.native-snap, src/features/auth/forgottenPassword/ReinitializePassword/ReinitializePassword.tsx, src/features/auth/signup/SetEmail/SetEmail.tsx, src/features/auth/signup/SetPassword/SetPassword.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10325
I have:
=> (PC-10325) Web - Submit on enter sur les formulaires d inscriptions

__snapshots__/features/search/components/__tests__/CalendarPicker.web.test.tsx.web-snap, package.json, src/features/search/components/CalendarPicker.web.tsx, src/features/search/components/__tests__/CalendarPicker.web.test.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9629
Add iOS datepicker style for mobile and full calendar for desktop
I have:
| \*iOS - [iPhone Safari] | \*iOS - [iPhone Chrome] |
|![IMG_6269](https://user-images.githubusercontent.com/90036171/133591665-339af3de-30f7-4419-bbd0-2ab95358b36e.PNG) |![IMG_6268](https://user-images.githubusercontent.com/90036171/133591636-b5749a90-8255-4210-bec6-40ff1c92c576.PNG)  |![IMG_6269](https://user-images.githubusercontent.com/90036171/133591665-339af3de-30f7-4419-bbd0-2ab95358b36e.PNG)  | 
| \*Tablet - [Chrome] | 
| --------------------: | 
|<img width="1085" alt="Schermata 2021-09-16 alle 11 49 11" …
=> (PC-9629) Datepickers pour navigateurs desktop et mobile

__snapshots__/features/auth/signup/AccountCreated/tests/AccountCreated.native.test.tsx.native-snap, __snapshots__/features/bookOffer/pages/__tests__/BookingConfirmation.test.tsx.native-snap, __snapshots__/features/eighteenBirthday/pages/EighteenBirthday.native.test.tsx.native-snap, __snapshots__/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx.native-snap, __snapshots__/features/errors/pages/tests/AsyncErrorBoundary.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/FirstTutorial.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FirstCard.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/components/FourthCard.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/components/SecondCard.native.test.tsx.native-snap, __snapshots__/features/firstTutorial/pages/FirstTutorial/components/ThirdCard.native.test.tsx.native-snap, __snapshots__/features/forceUpdate/__tests__/ForceUpdate.test.tsx.native-snap, __snapshots__/features/home/pages/tests/Home.native.test.tsx.native-snap, __snapshots__/features/navigation/__tests__/RootNavigator.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ConfirmDeleteProfile.test.tsx.native-snap, __snapshots__/features/profile/pages/DeleteProfileSuccess.test.tsx.native-snap, src/features/home/pages/Home.tsx, src/ui/components/achievements/components/GenericAchievementCard.tsx, src/ui/theme/grid.ts, src/ui/theme/typography.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10541
I have:
=> (PC-10541) Use dynamic dimensions for grid functionality

src/features/home/pages/tests/useHomeModules.test.ts, src/features/home/pages/tests/useHomeRecommendedHits.test.ts, src/features/home/pages/useHomeModules.ts, src/features/home/pages/useHomeRecommendedHits.ts, src/features/profile/utils.ts, src/features/search/pages/useSearchResults.ts, src/features/venue/api/useVenueOffers.ts, src/libs/search/__tests__/parseSearchParameters.test.ts, src/libs/search/fetch/search.ts, src/libs/search/filters/buildFacetFilters.ts, src/libs/search/filters/index.ts, src/libs/search/filters/tests/buildFacetFilters.test.ts, src/libs/search/filters/tests/buildQueryOptions.test.ts, src/libs/search/parseSearchParameters.ts, src/libs/search/useParseSearchParameters.ts, src/libs/search/utils/filterAvailableCategories.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10666
I have:
=> [PC-10666] filtrer les offres digitales payantes hors presse pour les <18 ans

__snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.native.test.tsx.native-snap, __snapshots__/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx.web-snap, __snapshots__/features/search/components/__tests__/CalendarPicker.web.test.tsx.web-snap, src/features/auth/components/OpenInboxButton.tsx, src/features/auth/components/OpenInboxButton.web.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent/ResetPasswordEmailSent.tsx, src/features/auth/forgottenPassword/ResetPasswordEmailSent/tests/ResetPasswordEmailSent.web.test.tsx, src/features/auth/signup/SignupConfirmationEmailSent/SignupConfirmationEmailSent.tsx, src/features/auth/signup/SignupConfirmationExpiredLink/tests/SignupConfirmationEmailSent.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9632
I have:
=> (PC-9632) Web - Ne plus afficher le bouton Consulter ma boite e-mails

__snapshots__/features/search/components/__tests__/CalendarPicker.web.test.tsx.web-snap, src/features/bookings/components/BookingDetailsTicketContent.tsx, src/features/bookings/components/ThreeShapesTicket.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10294
I have:
| \*Web - [Chrome] | \*Android - [Phone name] | Tablet - [Phone name] | Little - [Phone name] |
| ![image](https://user-images.githubusercontent.com/77674046/133768678-8d729b56-e981-40b4-a0d2-6b6228700fb8.png)
=> (PC-10294) Booking Details, retravailler le QR code pour le Web

src/features/bookOffer/components/BookDuoChoice.tsx, src/features/bookOffer/components/BookHourChoice.tsx, src/features/bookOffer/pages/BookingOfferWrapper.tsx, src/features/offer/services/useHasEnoughCredit.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10601
Fix linter typing errors
I have:
No screenshot needed
[PC-10601]: https://passculture.atlassian.net/browse/PC-10601
=> (PC-10601) Faire une version web desktop du calendar / datepicker

.env.production, .env.staging, .env.testing
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10937
I have:
=> (PC-10937) change DMS links to lowercase

__snapshots__/features/home/atoms/tests/VenueCaption.test.tsx.native-snap, __snapshots__/features/home/atoms/tests/VenueCaption.test.tsx.web-snap, __snapshots__/features/home/atoms/tests/VenueTile.test.tsx.native-snap, __snapshots__/features/home/atoms/tests/VenueTile.test.tsx.web-snap, __snapshots__/features/home/components/tests/VenuesModule.test.tsx.native-snap, __snapshots__/features/home/components/tests/VenuesModule.test.tsx.web-snap, src/features/home/atoms/VenueCaption.tsx, src/features/home/atoms/VenueTile.tsx, src/features/home/atoms/tests/VenueCaption.test.tsx, src/features/home/atoms/tests/VenueTile.test.tsx, src/features/home/components/VenuesModule.tsx, src/libs/parsers/venueType.ts, src/libs/search/fetch/search.ts, src/libs/search/index.ts, src/libs/search/utils/buildVenueHits.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10066
I have:
| <img width="359" alt="Capture d’écran 2021-09-20 à 13 46 21" src="https://user-images.githubusercontent.com/62059034/133996989-dfaa28ce-553e-427c-9213-83489956eef6.png">   |                       |                       |                       |
=> (PC-10066) Je vois le type de lieu avec l'icône correspondante

src/features/auth/signup/SetEmail/SetEmail.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10598
I have:
=> (PC-10598) Fix RenderError due to string not child of Text component

src/App.native.test.tsx, src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.native.test.tsx, src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.web.test.tsx, src/features/auth/signup/VerifyEligiblity/tests/VerifyEligibility.test.tsx, src/features/auth/signup/idCheck/useNavigateToIdCheck.test.tsx, src/features/auth/signup/idCheck/useNavigateToIdCheck.ts, src/features/auth/signup/useBeneficiaryValidationNavigation.test.ts, src/features/auth/signup/useBeneficiaryValidationNavigation.ts, src/features/deeplinks/getScreenFromDeeplink.test.ts, src/features/deeplinks/getScreenFromDeeplink.ts, src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.native.test.tsx, src/features/eighteenBirthday/pages/components/EighteenBirthdayCard.tsx, src/features/errors/pages/tests/AsyncErrorBoundary.native.test.tsx, src/features/navigation/RootNavigator/__mocks__/routes.ts, src/features/navigation/RootNavigator/linking/index.ts, src/features/navigation/__tests__/helpers.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10796
I have:
=> (PC-10796) Make getScreenFromDeeplink rely uniquely on linking conf + tests

__snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap, src/features/navigation/__tests__/RootNavigator.web.test.tsx, src/index.tsx
=> (PC-10931) Stratégie d'invalidation du cache pour avoir les MaJ des nouvelles versions de l app

src/features/auth/signup/SetEmail/SetEmail.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10598
I have:
=> (PC-10598) SetEmail - La checkbox n est pas cliquable.

ios/PassCulture.xcodeproj/xcshareddata/xcschemes/PassCulture-Production.xcscheme, ios/PassCulture.xcodeproj/xcshareddata/xcschemes/PassCulture-Staging.xcscheme, ios/PassCulture.xcodeproj/xcshareddata/xcschemes/PassCulture-Testing.xcscheme, ios/Podfile.lock, src/libs/trackingConsent/useTrackingConsent.ts
=> (Fix ATT) new podfile and iOS config

.circleci/config.yml
Référence: https://developer.apple.com/forums/thread/682067
=> (Tech) build app on xcode 12.5.1 so that it signs for iOS15

src/features/auth/signup/SetEmail/SetEmail.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11031
I have:
|  <img width="359" alt="Capture d’écran 2021-09-24 à 11 17 13" src="https://user-images.githubusercontent.com/62059034/134650677-cfbd8e18-afec-44b8-be33-fd0b96bb398a.png">                    |                         |                       |                       |
=> (PC-11031) Update wording for SetEmail

__snapshots__/features/venue/components/__tests__/VenueHeader.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, src/features/venue/components/VenueHeader.tsx, src/features/venue/components/VenueWebHeader.tsx, src/features/venue/pages/Venue.tsx, src/features/venue/pages/VenueBody.tsx, src/features/venue/pages/__tests__/Venue.native.test.tsx, src/features/venue/pages/__tests__/Venue.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11039
I have:
| \*iOS - [Phone name] | \*Android - [Phone name] | Tablet - [Phone name] |  Web |
|                      |                          |                       | <img width="1792" alt="Capture d’écran 2021-09-24 à 12 18 42" src="https://user-images.githubusercontent.com/62059034/134659223-33f1e8c4-d8d1-431b-b38b-d8dbeb00efe1.png">|
=> (PC-11039) Permettre le scroll de la page Lieu sur navigateur web + Ajout d'un Header adapté au web

src/features/forceUpdate/useMustUpdateApp.web.ts, src/web/serviceWorkerRegistration.ts, src/web/useServiceWorker.tsx
=> (PC-10931) service-worker react: remove unecessary logs, improve typing

src/libs/geolocation/checkGeolocPermission.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10545
I have:
=> (PC-10545) Profile - Afficher la modale de Geolocalisation lorsque le status est block (denied)

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/home/pages/useHomeModules.ts, src/features/home/pages/useHomeRecommendedHits.ts, src/features/profile/components/BeneficiaryCeilings.native.test.tsx, src/features/profile/components/BeneficiaryCeilings.tsx, src/features/profile/components/BeneficiaryCeilings.web.test.tsx, src/features/profile/components/BeneficiaryHeader.native.test.tsx, src/features/profile/components/BeneficiaryHeader.tsx, src/features/profile/components/BeneficiaryHeader.web.test.tsx, src/features/profile/components/CreditCeiling.native.test.tsx, src/features/profile/components/CreditCeiling.tsx, src/features/profile/components/CreditCeiling.web.test.tsx, src/features/profile/components/ProfileHeader.native.test.tsx, src/features/profile/components/ProfileHeader.web.test.tsx, src/features/profile/utils.ts, src/features/search/pages/useSearchResults.ts, src/features/search/utils/useAvailableCategories.ts, src/features/venue/api/useVenueOffers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10498
I have:
|![Simulator Screen Shot - iPhone 12 mini - 2021-09-24 at 17 58 43](https://user-images.githubusercontent.com/22886846/134705902-539075b4-37d0-4ec2-adde-ce5170db0b20.png)![Simulator Screen Shot - iPhone 12 mini - 2021-09-24 at 17 59 42](https://user-images.githubusercontent.com/22886846/134705909-e4721cb0-d7f3-4624-8ddd-df45a8458ef1.png)|                          |                       |                       |
=> (PC-10498) underage profile header

src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx, src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10840
I have:
=> [Pc-10840] re send sms

src/features/search/atoms/Buttons/Filter.tsx, src/features/search/atoms/Buttons/__tests__/Filter.native.test.tsx, src/features/search/atoms/Buttons/__tests__/Filter.web.test.tsx, src/features/search/pages/SearchWrapper.tsx, src/features/search/sections/Price.tsx, src/features/search/sections/tests/Price.native.test.tsx, src/features/search/utils/tests/useFilterCount.test.ts, src/features/search/utils/tests/useMaxPrice.test.ts, src/features/search/utils/useFilterCount.ts, src/features/search/utils/useMaxPrice.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10499
I have:
=> (PC-10499) update price filter for beneficiary users under 18

public/index.html
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10839
Remove double font
I have:
[PC-10839]: https://passculture.atlassian.net/browse/PC-10839
=> (PC-10839) Remove double Montserrat-ExtraBoldItalic

__snapshots__/features/home/components/tests/OffersModule.native.test.tsx.native-snap, src/features/home/components/OffersModule.tsx, src/features/home/components/RecommendationModule.tsx, src/features/home/hooks/useLayoutHits.ts, src/features/home/hooks/useLayoutHits.web.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-9603
I have:
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10118284/135242755-dda79fad-0d4d-4501-80f8-165d842eb892.png) |  ![image](https://user-images.githubusercontent.com/10118284/135242615-f1811c81-081f-4906-ad74-8b2d959ce3e0.png) |
=> (FIX-9603) make hook useLayoutHits web only as it breaks layout on mobile

src/features/firstTutorial/pages/FirstTutorial/FirstTutorial.tsx, src/features/home/pages/Home.tsx, src/features/navigation/NavigationContainer/NavigationContainer.tsx, src/features/navigation/RootNavigator/RootNavigator.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/RootNavigator/useInitialScreenConfig.tsx, src/features/navigation/__tests__/RootNavigator.native.test.tsx, src/features/navigation/__tests__/RootNavigator.web.test.tsx, src/features/navigation/__tests__/useInitialScreenConfig.native.test.tsx
=> Use RN exclusively for all screen initialization logic and deeplinks

src/features/errors/pages/ScreenErrorProvider.tsx
=> (Tech) fix maintenance screen for redirect

src/features/navigation/RootNavigator/useInitialScreenConfig.tsx
=> (Tech) add a try catch block

package.json, src/features/auth/signup/IdCheckV2.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11044
I have:
|          
=> [PC-11044] (idCheckSteps) rename steps

src/features/favorites/pages/useFavorites.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-8434
I have:
=> (PC-8434) avoid crash on adding to favorite

__snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/Venue.web.test.tsx.web-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.native.test.tsx.native-snap, __snapshots__/features/venue/pages/__tests__/VenueBody.web.test.tsx.web-snap, src/ui/components/accessibility/AccessibilityAtom.tsx, src/ui/components/accessibility/AccessibilityBlock.tsx, src/ui/components/contact/ContactBlock.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10782
I have:
|  <img width="358" alt="Capture d’écran 2021-09-29 à 13 55 51" src="https://user-images.githubusercontent.com/62059034/135263660-3c5e4722-d255-49d1-b173-7102c0682904.png"> |                          |                       |                       |
=> (PC-10782) [Paillette] Ajustement du bloc accessibilité

src/libs/geolocation/components/WhereSection.tsx
=> (Tech) Show venue page on staging

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/cheatcodes/pages/AppComponents/useStorageInformation.ts, src/features/navigation/RootNavigator/linking/__tests__/getStateFromPath.test.ts, src/features/navigation/RootNavigator/linking/getStateFromPath.ts, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11021
I have:
=> (PC-11021) tracking metabase

src/libs/parsers/formatDates.ts, src/libs/parsers/tests/formatDates.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10659
I have:
=> (PC-10659) save input birthday without timezone offset

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/libs/analytics/analytics.ts, src/libs/storage.ts, src/libs/utm/storeUtmParams.ts, src/libs/utm/useUtmParams.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11023
I have:
| Avant réinitialisation | Après réinitialisation |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10118284/135616921-6d19656d-4e2a-4912-a3ad-29a9db96a264.png) | ![image](https://user-images.githubusercontent.com/10118284/135616824-db30147c-7698-4717-8f53-9b73d06d1e5d.png) |
=> [PC-11023] Reinitialiser les paramètres au bout de 48h (3/3)

src/features/venue/components/VenueWebHeader.tsx, src/features/venue/pages/VenueBody.tsx, src/libs/geolocation/components/WhereSection.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11137
I have:
| <img width="500" alt="Capture d’écran 2021-10-01 à 15 17 32" src="https://user-images.githubusercontent.com/62059034/135626344-296a7f58-74d5-4b09-ab57-de037f94d05a.png"> |                          |                       |                       |
=> (PC-11137) On affiche le nom de la structure et non celle du lieu

src/web/useServiceWorker.tsx
=> (Tech) added logging in testing for ForceUpdate web

src/libs/web.ts
=> Release web app entirely on staging environment

src/api/gen/api.ts, src/features/auth/__mocks__/settings.ts, src/features/bookings/components/BookingPropertiesSection.native.test.tsx, src/features/bookings/components/BookingPropertiesSection.web.test.tsx, src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/home/atoms/VenueCaption.tsx, src/features/home/atoms/tests/VenueCaption.test.tsx, src/features/search/enums.ts, src/features/venue/atoms/VenueType.tsx, src/features/venue/atoms/__tests__/IconWithCaption.test.tsx, src/features/venue/atoms/__tests__/VenueType.test.tsx, src/features/venue/components/VenueIconCaptions.tsx, src/features/venue/components/__tests__/VenueIconCaption.native.test.tsx, src/features/venue/components/__tests__/VenueIconCaption.web.test.tsx, src/libs/parsers/venueType.ts, src/libs/search/fixtures/mockedSearchResponse.tsx, src/libs/search/utils/buildVenueHits.ts, src/tests/server.ts, src/ui/components/hero/Hero.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11199
I have:
=> (PC-11199) Regenerer API schema

src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts, src/features/search/utils/tests/useAvailableCategories.test.ts, src/features/search/utils/tests/useAvailableSearchCategories.test.ts, src/features/search/utils/useAvailableCategories.ts, src/libs/search/filters/buildQueryOptions.ts, src/libs/search/filters/tests/buildQueryOptions.test.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11099
I have:
=> [PC-11099] filtrer some "JEU" subcategories for underage

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/profile/utils.test.ts, src/features/profile/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10973
I have:
Testable on cheatcodes in Profile Components
=> [PC-10973] show default icon if unknown icon name comm in app

__snapshots__/features/profile/components/IdCheckProcessingBadge.native.test.tsx.native-snap, src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/profile/components/IdCheckProcessingBadge.native.test.tsx, src/features/profile/components/IdCheckProcessingBadge.tsx, src/features/profile/components/NonBeneficiaryHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11196
I have:
|  <img width="355" alt="Capture d’écran 2021-10-08 à 15 14 42" src="https://user-images.githubusercontent.com/44037911/136563621-28c19a64-db52-479c-a155-43dbfb4c9d93.png"> |         |                 |                  |                  |
=> [PC-11196] Add last update date communication inapp

__snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap, src/features/bookings/components/BookingDetailsCancelButton.tsx, src/features/bookings/pages/BookingDetails.tsx, src/ui/components/buttons/AppButton.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10561
I have:
|     |         | ![image](https://user-images.githubusercontent.com/77674046/136819420-091f7f6c-19fb-405b-a7dc-661ba276cc49.png) |                  |                  |
=> (PC-10561) BookingDetails - les buttons en fullWidth

.eslintrc.js, babel.config.js, jest.config.js, src/features/profile/utils.test.ts, src/features/profile/utils.ts, src/fixtures/credit.ts, src/fixtures/user.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11164
I have:
=> [Pc-11164] underage ex bene

src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/profile/utils.test.ts, src/features/profile/utils.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10974
I have:
=> [pc-10974] change logic to SVG helper and add test

package.json, src/features/navigation/RootNavigator/routes.ts, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11311
I have:
=> (PC-11311) (IdCheck) Use French paths for screens

package.json, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/cheatcodes/pages/NavigationIdCheckErrors/NavigationIdCheckErrors.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11168
I have:
=> [PC-11168] navigate to home

__snapshots__/features/navigation/TabBar/__tests__/TabBar.native.test.tsx.native-snap, __snapshots__/features/navigation/TabBar/__tests__/TabBar.web.test.tsx.web-snap, __snapshots__/features/navigation/__tests__/RootNavigator.web.test.tsx.web-snap, src/features/cheatcodes/pages/AppComponents/AppComponents.tsx, src/features/navigation/RootNavigator/Header/NavItem.tsx, src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/TabBarComponent.tsx, src/ui/svg/icons/BicolorSelector.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11385
I have:
| Before - iphone X | After - iphone X | 
| --: | ------: | 
| ![image](https://user-images.githubusercontent.com/22399093/137934477-cb48a98d-d5cd-495c-a49e-51e2a67000d9.png) | ![image](https://user-images.githubusercontent.com/22399093/137947869-d8fcc626-44e2-43ef-96b4-498b14a873ae.png) |  
| Before - ipad | After - ipad | 
| --: | ------: | 
| ![image](https://user-images.githubusercontent.com/22399093/137948183-7a1643be-6fc1-492f-b1b5-1a64b3be12e8.png) | ![image](https://user-images.githubusercontent.com/22399093/137948066-348b21a7-047b-490e-bdfb-72c983fd32a4.png) |
=> (PC-11385) Make tabbar takes full width of app

__snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap, src/features/bookings/components/BookingDetailsTicketContent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10561
I have:
| iOS | Android | Mobile - Chrome | Desktop - Chrome (before) | Desktop - Chrome (after) |
|     | ![image](https://user-images.githubusercontent.com/77674046/138078768-ab04fb18-4ca7-4700-898c-c30488895982.png) |                 ![image](https://user-images.githubusercontent.com/77674046/138078896-5b83bc75-3b15-4a4b-b438-5f948d11542c.png) | ![image](https://user-images.githubusercontent.com/77674046/138078607-08d23995-5485-4c24-93c1-b65cc1fb64b9.png) | ![image](https://user-images.githubusercontent.com/77674046/138078618-69d5fe72-abdf-49f7-964f-d223457a5fec.png) |
=> (PC-10561) QR code Web support long titre

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11383
I have:
=> (PC-11383) (id-check@2.9.2) Do not use authorization header in generic client

src/features/bookings/components/ThreeShapesTicket.web.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10561
I have:
| iOS | Android | Mobile - Chrome | Desktop - Avant | Desktop - Après |
|     |         |                 | ![image](https://user-images.githubusercontent.com/77674046/138136144-dfac467d-2d02-4207-892b-d6ce90d42cab.png) |![image](https://user-images.githubusercontent.com/77674046/138136216-32a4c04c-6c82-4bcd-bf8f-5c4038965875.png)|
=> (PC-10561) fixed a small glitch on the web

package.json, yarn.lock
=> (PC-11383) Bump to 2.9.3 @pass-culture/id-check

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11614
Related to https://github.com/pass-culture/id-check-front/pull/254
I have:
=> (PC-11614) Upgrade @pass-culture/id-check to v2.10.11

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11597
I have:
=> [PC-11597]upgrade id-check to fix nav regression

src/features/auth/signup/underageSignup/SelectSchoolHome.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11616
I have:
|     |         |                 |<img width="1920" alt="Schermata 2021-11-02 alle 15 51 21" src="https://user-images.githubusercontent.com/90036171/139871221-6ac35ead-0f31-4975-bdf9-a8073cc9f576.png">|                  |
[PC-11616]: https://passculture.atlassian.net/browse/PC-11616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-11616] Center content for web version

__snapshots__/features/auth/signup/idCheck/DenyAccessToIdCheck.native.test.tsx.native-snap, __snapshots__/features/bookings/pages/BookingDetails.native.test.tsx.native-snap, __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicy.native.test.tsx.native-snap, __snapshots__/features/firstLogin/PrivacyPolicy/PrivacyPolicyModal.native.test.tsx.native-snap, __snapshots__/features/offer/components/__tests__/OfferHeader.native.test.tsx.native-snap, __snapshots__/features/offer/components/__tests__/OfferHeader.web.test.tsx.web-snap, __snapshots__/features/offer/components/__tests__/ReportOffer.native.test.tsx.native-snap, __snapshots__/features/offer/pages/tests/OfferBody.deprecated.native.test.tsx.native-snap, __snapshots__/features/offer/pages/tests/OfferBody.native.test.tsx.native-snap, src/libs/styled/ThemeProvider.tsx, src/ui/components/modals/AppModal.tsx, src/ui/components/snackBar/SnackBar.tsx, src/ui/theme/layers.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11563
I have:
|     |         |  ![image](https://user-images.githubusercontent.com/22399093/139878470-ca1d9ed7-b651-4f3b-a2a8-21843b762141.png)  | ![image](https://user-images.githubusercontent.com/22399093/139878236-af740a61-7efa-4a93-943c-e6254f0b7ebb.png)  |                  |
=> (PC-11563) On desktop screens, show snackbar below menu in the top right-hand corner of the screen

src/features/auth/signup/underageSignup/SelectSchool.tsx, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11402
I have:
=> (PC-11402) SelectSchool: add tracker on school selection

src/features/profile/__mocks__/utils.ts, src/features/profile/components/ProfileHeader.native.test.tsx, src/features/profile/components/ProfileHeader.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11632
I have:
|     |     
=> [PC-11632] display adapted wording deposit validation

src/App.tsx, src/features/auth/AuthContext.tsx, src/features/auth/__mocks__/AuthContext.tsx, src/features/auth/signup/AfterSignupEmailValidationBuffer/AfterSignupEmailValidationBuffer.tsx, src/features/auth/signup/IdCheckV2.tsx, src/features/home/api.ts, src/features/home/components/BusinessModule.tsx, src/features/home/services/useAvailableCredit.ts, src/features/profile/pages/ChangeEmail/ChangeEmail.tsx, src/features/profile/pages/ChangeEmail/utils/useValidateEmail.test.ts, src/features/profile/pages/ChangeEmail/utils/useValidateEmail.ts, src/features/profile/pages/Profile.native.test.tsx, src/features/profile/pages/Profile.tsx, src/features/profile/utils.ts, src/ui/components/inputs/emailCheck.test.ts, src/ui/components/inputs/emailCheck.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-7709
In this PR: mainly caching of `/native/v1/me` + several tiny clarifications.
I have:
See below the number of calls to `/native/v1/me` for the user journey:
- open the app as not logged in
- go to profile and log in
- click on tabs Home, Search, Favorites, Bookings and Profile
- Log out
**Note**: this is not the only demanding user journey in terms of number of requests to `/native/v1/me`. The process to book an offer is another one.
=> [PC-7709] perf: Diminuer le nombre d'appel à la route /me

src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts, src/features/offer/services/useCtaWordingAndAction.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11600
I have:
=> (PC-11600) offer: update insufficient credit for underage benef

package.json, src/libs/eduConnectClient.ts, src/libs/environment/env.web.ts, web/config/webpackDevServer.config.js, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11586
Related to https://github.com/pass-culture/id-check-front/pull/251
I have:
=> (PC-11586) EduConnect Web app v2

src/features/home/pages/tests/useHomeModules.test.ts, src/features/home/pages/useHomeModules.ts, src/libs/algolia/fetchAlgolia/AlgoliaError.ts, src/libs/algolia/fetchAlgolia/fetchAlgolia.facetFilters.ts, src/libs/algolia/fetchAlgolia/fetchAlgolia.ts, src/libs/algolia/fetchAlgolia/fetchVenues.ts
Le but de cette PR est de 'catcher' tous les calls à Algolia qui échouent, de les regrouper selon le type d'erreur et d'avoir plus d'info sur la stacktrace.
=> (Tech) Improve Algolia error handling

src/libs/environment/env.web.ts
=> (Tech) fixing env web

src/features/forceUpdate/ForceUpdate.tsx
=> (Tech) using location reload instead of repalce

src/features/auth/signup/IdCheckV2.tsx
=> (Tech) fix id check

doc/deployment/deployment.md, scripts/check_branch.sh
=> use release branch

__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.web.test.tsx.web-snap, src/features/auth/__mocks__/support.services.ts, src/features/auth/support.services.ts, src/features/profile/pages/ChangeEmail/ChangeEmailExpiredLink.tsx, src/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx, src/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.web.test.tsx, src/libs/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11602
I have:
|     |         |                 |  ![Capture d’écran 2021-11-03 à 16 38 28](https://user-images.githubusercontent.com/62059034/140095267-10f1246e-45d5-4825-9538-bbbbef8d8f4f.png)  |                  |
=> feat(PC-11602) Add contact support for change email expired link

src/features/auth/signup/underageSignup/SelectSchoolHome.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11616
I have:
[PC-11616]: https://passculture.atlassian.net/browse/PC-11616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PC-11616] Change window size break point for logo size

__snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx.native-snap, __snapshots__/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.web.test.tsx.web-snap, src/features/profile/__mocks__/mutations.ts, src/features/profile/mutations.ts, src/features/profile/pages/ChangeEmail/ChangeEmail.tsx, src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11395
I have:
|  ![image](https://user-images.githubusercontent.com/26742386/140299282-6732a64a-cb14-4639-8098-2c328b6022ca.png) |         |                 |  ![image](https://user-images.githubusercontent.com/26742386/140299550-d56c1fb9-8ea4-41ed-a988-24e3d8949fa0.png) |                  |
=> [PC-11395] show error message on changeEmail screen when having the wrong credentials

src/features/auth/signup/underageSignup/eligibleSchools.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11674
I have:
=> (PC-11674) SelectSchool: fix school names and order

package.json, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11680
I have:
=> (PC-11680) Gérer la panne du service educonnect

src/features/venue/api/__tests__/useVenueSearchParameters.test.ts, src/features/venue/api/useVenueSearchParameters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11685
I have:
=> (PC-11685) Absence du label de l'intitulé des lieux qui ont un "name" mais pas de "publicName"

src/libs/parsers/venueType.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11607
I have:
=> fix(PC-11607) VenueType : switch BOOKSTORE / LIBRARY mapping title

src/features/auth/signup/underageSignup/SelectSchoolHome.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11616
I have:
| Web iPhone X | Web iPhone 8 max | Web iPhone 8 | Web iPhone 5S |
| --: | ------: | --------------: | ---------------: |
|<img width="382" alt="ios iphone x" src="https://user-images.githubusercontent.com/90036171/140530916-3d10ec37-c336-4ae1-b0cd-e31d8548c9d5.png">|<img width="423" alt="ios iphone 8 max" src="https://user-images.githubusercontent.com/90036171/140530922-0fb08b56-703e-4fb6-9c5a-155827296caf.png">|<img width="382" alt="ios iphone 8" src="https://user-images.githubusercontent.com/90036171/140530924-b96aa878-fb13-4b79-b443-128d4f6e0826.png">|<img width="329" alt="ios iphone 5s" src="https://user-images.githubusercontent.com/90036171/140530925-2c8561fb-28c8-4990-8298-93df6910513a.png">|
| iOS - …
=> [PC-11616] Review all screen resolutions web and mobile

src/libs/algolia/algolia.d.ts, src/libs/algolia/fetchAlgolia/fetchVenues.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11611
I have:
=> (PC-11611) show city as venue label in suggested places if available

.eslintrc.js, src/features/favorites/atoms/Favorite.tsx, src/features/navigation/RootNavigator/Header/Header.web.tsx, src/features/navigation/RootNavigator/Header/tests/Header.web.test.tsx, src/features/navigation/TabBar/TabNavigator.tsx, src/features/profile/pages/ChangeEmail/ChangeEmail.tsx, src/features/profile/pages/ChangePassword/ChangePassword.tsx, src/features/search/components/CalendarPicker.web.tsx, src/libs/itinerary/useItinerary.web.ts, src/libs/styled/ThemeProvider.tsx, src/theme/index.ts, src/ui/components/snackBar/SnackBar.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11389
I have:
=> (PC-11389) Name explicitly viewport/platform-related variables

src/features/navigation/NavigationContainer/NavigationContainer.tsx, src/features/navigation/services.ts, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11381
I have:
=> (PC-11381) Remove navigation state persistence on web following bug with links

__snapshots__/features/home/atoms/tests/VenueCaption.test.tsx.native-snap, __snapshots__/features/home/atoms/tests/VenueTile.native.test.tsx.native-snap, __snapshots__/features/home/atoms/tests/VenueTile.web.test.tsx.web-snap, __snapshots__/features/home/components/tests/VenuesModule.test.tsx.native-snap, __snapshots__/features/home/components/tests/VenuesModule.test.tsx.web-snap, __snapshots__/ui/components/__tests__/ImageTile.native.test.tsx.native-snap, src/features/home/atoms/OfferTile.tsx, src/features/home/atoms/VenueCaption.tsx, src/features/home/atoms/VenueTile.tsx, src/features/home/atoms/tests/VenueCaption.test.tsx, src/features/home/atoms/tests/VenueTile.native.test.tsx, src/features/home/atoms/tests/VenueTile.web.test.tsx, src/features/home/components/VenuesModule.tsx, src/features/venue/atoms/VenueOfferTile.tsx, src/ui/components/ImageCaption.tsx, src/ui/components/ImageTile.tsx, src/ui/components/__tests__/ImageCaption.native.test.tsx, src/ui/components/__tests__/ImageCaption.web.test.tsx, src/ui/components/__tests__/ImageTile.native.test.tsx, src/ui/components/__tests__/ImageTile.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11389
I have:
=> (PC-11389) New playlist UX for VenuesModule

src/features/_marketingAndCommunication/atoms/DeeplinkItem.tsx, src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/_marketingAndCommunication/components/DeeplinksHistory.tsx, src/features/_marketingAndCommunication/components/DeeplinksResult.tsx, src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts, src/features/_marketingAndCommunication/pages/DeeplinksGenerator.tsx, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/deeplinks/utils.test.ts, src/features/deeplinks/utils.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po, src/theme/index.ts, src/ui/components/inputs/TextInput.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10800
I have:
| iOS | Android | Mobile - Chrome | Desktop - Chrome | Desktop - Chrome |
|     |         | ![image](https://user-images.githubusercontent.com/77674046/141080725-fb688db3-e117-486e-83c3-e8654334d8f9.png) | ![image](https://user-images.githubusercontent.com/77674046/141094314-fca7553a-47d9-4f5c-ae76-710e0516e367.png) | ![image](https://user-images.githubusercontent.com/77674046/141080603-767a2666-38f2-4aa9-ad94-9a763de5b222.png) | 
| validation `id` KO | 
| --: |
| ![image](https://user-images.githubusercontent.com/77674046/141098947-4e3a9838-7850-4335-b1c1-62013d8ba477.png) |
=> (PC-10800) Générateur de deeplinks

src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-10800
Amélioration du texte des params description
I have:
=> (PC-10800) Deeplink generator shorten params description (tech)

.env.production, .env.staging, .env.testing, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/cheatcodes/pages/NavigationIdCheck/NavigationIdCheck.tsx, src/features/cheatcodes/pages/NavigationIdCheck/index.tsx, src/features/idcheck/pages/Stepper.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/libs/environment/__mocks__/envFixtures.ts, src/libs/environment/types.ts, src/ui/svg/icons/Invalidate.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11741
I have:
=> (PC-11741) Rapatriement l'écran de stepper

__snapshots__/features/profile/pages/AfterChangeEmailValidationBuffer/__tests__/AfterChangeEmailValidationBuffer.native.test.tsx.native-snap, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/navigation/screenParamsUtils.ts, src/features/profile/__mocks__/mutations.ts, src/features/profile/mutations.ts, src/features/profile/pages/AfterChangeEmailValidationBuffer/AfterChangeEmailValidationBuffer.tsx, src/features/profile/pages/AfterChangeEmailValidationBuffer/__tests__/AfterChangeEmailValidationBuffer.native.test.tsx, src/features/profile/pages/AfterChangeEmailValidationBuffer/index.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11626
I have:
=> [PC-11626] feat: handle email change link redirection from email

__snapshots__/features/profile/components/CreditCeiling.native.test.tsx.native-snap, __snapshots__/features/profile/components/CreditCeiling.web.test.tsx.web-snap, __snapshots__/ui/components/bars/ProgressBar.native.test.tsx.native-snap, __snapshots__/ui/components/bars/ProgressBar.web.test.tsx.web-snap, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/features/recreditBirthdayNotification/pages/components/RecreditBirthdayNotification.tsx, src/libs/storage.ts, src/locales/fr/messages.po, src/ui/components/bars/ProgressBar.native.test.tsx, src/ui/components/bars/ProgressBar.tsx, src/ui/components/bars/ProgressBar.web.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11650
I have:
| Desktop Chrome | iOS iPhone SE | iOS - iPhone 12 |
| -------------: | ------: | ------: |
|<img width="1920" alt="Schermata 2021-11-05 alle 17 18 08" src="https://user-images.githubusercontent.com/90036171/140543738-abf1551b-f8b5-4f58-9ab4-3c448e81c064.png">|<img width="361" alt="Schermata 2021-11-05 alle 17 17 57" src="https://user-images.githubusercontent.com/90036171/140543760-c4ddd99f-6f8e-4460-a547-2decaf72faa5.png">|<img width="456" alt="Schermata 2021-11-05 alle 17 17 44" src="https://user-images.githubusercontent.com/90036171/140543770-9dcb26ca-07a7-4c58-8f56-6f640b4f22a8.png">|
[PC-11650]: https://passculture.atlassian.net/browse/PC-11650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> [PC-11650] Create Birthday Notification for 15, 16, 17 years old

src/features/navigation/NavigationContainer/NavigationContainer.tsx, src/features/navigation/services.ts, src/libs/storage.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11381
I have:
=> (PC-11381) Restore nav state on web window reload

src/features/profile/mutations.ts, src/features/profile/pages/ChangeEmail/ChangeEmail.tsx, src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11734
I have:
=> [PC-11734] feat(analytics): log event when submitting a new email

src/App.tsx, src/features/navigation/RootNavigator/Header/Nav.tsx, src/features/navigation/RootNavigator/Header/NavItem.tsx, src/features/navigation/RootNavigator/RootNavigator.tsx, src/features/navigation/TabBar/TabBar.tsx, src/features/navigation/TabBar/TabBarComponent.tsx, src/features/navigation/TabBar/TabNavigator.tsx, src/features/navigation/TabBar/mapTabRouteToBicolorIcon.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11392
I have:
=> (PC-11392) Clean tab nav UI and add some space between items

android/app/src/main/AndroidManifest.xml, android/app/src/main/res/values/strings.xml, public/.well-known/assetlinks-production.json, public/.well-known/assetlinks-staging.json, public/.well-known/assetlinks-testing.json
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11770
I have:
=> (PC-11770) Add login_creds relation in digital asset links

__snapshots__/features/navigation/TabBar/__tests__/TabBar.native.test.tsx.native-snap, src/features/navigation/RootNavigator/Header/NavItem.tsx, src/features/navigation/TabBar/TabBarComponent.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11392
I have:
=> (PC-11392) Fixes pour tabbar et menu web

src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx, src/features/identityCheck/atoms/form/RadioButton.tsx, src/features/identityCheck/components/layout/PageWithHeader.tsx, src/features/identityCheck/pages/profile/Status.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po
I have:
| iOS | iOS Selected | Mobile - Chrome | Desktop - Chrome | 
| --: | ------: | --------------: | ---------------: | 
| ![image](https://user-images.githubusercontent.com/10118284/141472438-09e95c60-56f9-4e98-bf5f-107657caadd7.png) | ![image](https://user-images.githubusercontent.com/10118284/141472418-544a2309-09ce-4fd6-ac01-5e4785bdb82e.png) | ![image](https://user-images.githubusercontent.com/10118284/141472502-10826bfe-1da6-412e-af85-a4ec471eef13.png) |  ![image](https://user-images.githubusercontent.com/10118284/141472350-3f18eb76-1a98-40d3-94be-a10d3aeefd83.png) |
=> feat(PC-11740) CheatCode: Add Status page

__snapshots__/features/search/pages/__tests__/Search.native.test.tsx.native-snap, src/features/navigation/RootNavigator/Header/Header.web.tsx, src/features/search/components/SearchLandingPage.tsx, src/libs/react-responsive/tests/useMediaQuery.test.ts, src/libs/react-responsive/useMediaQuery.ts, src/libs/styled/ThemeProvider.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11505
I have:
|     | ![image](https://user-images.githubusercontent.com/77674046/141501110-a17ac571-41c9-46fd-b072-cf002e0b6bd5.png) |                 |                  |                  |
=> (PC-11505) SearchHome button plus absolute si petit viewport height (web)

src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx, src/features/_marketingAndCommunication/config/deeplinksExportConfig.ts, src/features/navigation/RootNavigator/Header/Nav.tsx, src/features/navigation/RootNavigator/Header/NavItem.tsx, src/features/navigation/RootNavigator/types.ts, src/features/navigation/TabBar/routes.ts, src/features/navigation/TabBar/types.ts, src/libs/analytics/analytics.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11748
I have:
=> (PC-11748) Add typing to deeplink generator configs

src/features/bookings/components/BookingDetailsCancelButton.tsx, src/features/bookings/components/CancelBookingModal.native.test.tsx, src/features/bookings/components/CancelBookingModal.tsx, src/features/favorites/atoms/BookingButton.tsx, src/features/favorites/atoms/Favorite.tsx, src/features/favorites/atoms/__tests__/BookingButton.test.tsx, src/features/favorites/atoms/__tests__/Favorite.native.test.tsx, src/features/favorites/components/FavoritesResults.tsx, src/features/home/services/__mocks__/useAvailableCredit.ts, src/features/home/services/useAvailableCredit.ts, src/features/offer/pages/OfferBody.tsx, src/features/profile/__mocks__/utils.ts, src/features/profile/utils.test.ts, src/features/profile/utils.ts, src/features/search/utils/tests/useMaxPrice.test.ts, src/features/search/utils/useMaxPrice.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11313
I have:
|   <img width="345" alt="Capture d’écran 2021-11-15 à 12 23 01" src="https://user-images.githubusercontent.com/44037911/141773731-5c81fd10-96fa-45ef-8063-d570ca3430fd.png">  |         |       |                  |                  |
=> [PC-11313]- fix Max price filter for exunderage beneficiaries

src/features/bookings/components/BookingItemTitle.tsx, src/ui/theme/typography.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11808
Also include :
- https://passculture.atlassian.net/browse/PC-11506
I have:
|![image](https://user-images.githubusercontent.com/77674046/141823575-f0d76ebb-5fe2-4581-a09b-9236b71596e0.png)|![image](https://user-images.githubusercontent.com/77674046/141823713-8351d1d9-69bd-4800-b5cc-3b9bfd06ff4c.png)|
=> PC-11808 feat(Typography): added shrink mode to ButtonText

src/features/identityCheck/atoms/layout/PageHeader.tsx, src/features/identityCheck/components/layout/PageWithHeader.web.tsx, src/features/identityCheck/pages/identification/IdentityCheckStart.tsx, src/features/identityCheck/pages/profile/Status.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11785
I have:
| iOS | Status | Mobile - Chrome | Desktop - Chrome |
| --: | ------: | --------------: | ---------------: |
|  ![image](https://user-images.githubusercontent.com/10118284/141821296-a724d1bc-5c19-4173-be54-e58144dd11fa.png) | ![image](https://user-images.githubusercontent.com/10118284/141821338-2ca1167b-ae8f-4a8a-bdc9-514b779a8f80.png) | ![image](https://user-images.githubusercontent.com/10118284/141821411-7d6c108c-cd75-4e57-82d8-819cf67dc607.png) | ![image](https://user-images.githubusercontent.com/10118284/141821493-cda6557d-1e27-48aa-918f-c9f40244e84e.png) |
=> (PC-11785) feat(PageWithHeader): redesign PageWithHeader component

src/features/search/atoms/NoSearchResult.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11508
I have:
| iOS | Before | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|     | ![image](https://user-images.githubusercontent.com/77674046/141827621-c6c5d371-9d62-4a22-a090-cc1a010230d9.png) | ![image](https://user-images.githubusercontent.com/77674046/141826901-036762c5-b710-4906-8c49-12133ecb33db.png) | ![image](https://user-images.githubusercontent.com/77674046/141826943-a0c89c41-1514-4bd9-b478-4e01c66932ce.png) |                  |
=> PC-11508 fix(Search): NoSearchResults now have a minHeight: 250

src/features/auth/components/QuitSignupModal.tsx, src/features/auth/signup/SetName/SetName.native.test.tsx, src/features/auth/signup/SetName/SetName.tsx, src/features/auth/signup/SetName/index.ts, src/features/cheatcodes/pages/NavigationIdentityCheck/NavigationIdentityCheck.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po, src/ui/components/inputs/TextInput.tsx, src/ui/components/inputs/nameCheck.test.ts, src/ui/components/inputs/nameCheck.ts
I have:
| <img width="381" alt="Capture d’écran 2021-11-15 à 18 21 01" src="https://user-images.githubusercontent.com/62059034/141825961-a116912b-d0d5-44ce-be82-25fdd891264f.png"> <img width="381" alt="Capture d’écran 2021-11-15 à 18 21 15" src="https://user-images.githubusercontent.com/62059034/141825965-e0e79db8-5519-440f-8cf3-558361fd0258.png"> |         |                 |   <img width="1792" alt="Capture d’écran 2021-11-15 à 18 19 58" src="https://user-images.githubusercontent.com/62059034/141826012-029f4bb0-22f8-4958-a130-e6aba34743c1.png"> <img width="1792" …
=> PC-11724 feat(signup): add screen for requesting the user's last name / first name

src/features/favorites/atoms/__tests__/BookingButton.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11313
I have:
=> [pc-11313] refactor(bookingButton): improve test syntax and delete unused code

__snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap, src/ui/components/modals/AppInformationModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11539
I have:
|     |         | ![image](https://user-images.githubusercontent.com/77674046/142004825-e5f51761-edd3-438e-81b4-e1a2288befdc.png) | ![image](https://user-images.githubusercontent.com/77674046/142004974-84074b20-6e1d-42bb-bba9-409c4e17eac6.png)  |![image](https://user-images.githubusercontent.com/77674046/142004934-2c374f30-268a-4b41-97e6-dfbb9fe2649e.png)|
=> (PC-11539) fix(AppInformationModal): viewport: mobile use dynamic width, tablet and desktop use maxWidth 564

src/features/navigation/RootNavigator/Header/Header.web.tsx, src/features/navigation/RootNavigator/Header/tests/Header.web.test.tsx, src/features/navigation/RootNavigator/RootNavigator.tsx, src/features/navigation/TabBar/TabNavigator.tsx, src/libs/styled/ThemeProvider.tsx, src/theme/index.ts
=> (Tech) refactor(theme): rename showTabbar in showTabBar

package.json, src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx, src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.native.test.tsx, src/features/auth/signup/PhoneValidation/tests/SetPhoneValidationCode.web.test.tsx, yarn.lock
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11265
I have:
=> (PC-11265) feat(SAHI): add testID to create account button and inputs

src/features/auth/signup/PhoneValidation/SetPhoneValidationCode.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11816
I have:
=> (PC-11816) fix(signup): wait for userProfiling response before navigate to next step

src/features/_marketingAndCommunication/components/DeeplinksGeneratorForm.tsx
I have:
From:
`https://passcultureapptesting.page.link/?link=https%3A%2F%2Fapp.testing.passculture.team%2Foffre%2F3200&apn=app.passculture.testing&isi=1557887412&ibi=app.passculture.test&efr=1&utm_campaign=push_offre_local&utm_source=push&utm_medium=batch&ofl=https://app.testing.passculture.team/offre/3200?from=offer`
to
`https://passcultureapptesting.page.link/?link=https%3A%2F%2Fapp.testing.passculture.team%2Foffre%2F3200%3F**utm_campaign%3Dpush_offre_local%26utm_medium%3Dbatch%26utm_source%3Dpush**&apn=app.passculture.testing&isi=1557887412&ibi=app.passculture.test&efr=1&ofl=https://app.testing.passculture.team/offre/3200?from=offer`
=> (PC-11860) fix(linkGenerator): add marketing params in the universal link

src/features/identityCheck/pages/QuitIdentityCheckModal.tsx, src/features/identityCheck/pages/Stepper.tsx, src/features/identityCheck/pages/__test__/QuitIdentityCheckModal.native.test.tsx, src/features/identityCheck/pages/__test__/QuitIdentityCheckModal.web.test.tsx, src/locales/fr/messages.po, src/ui/components/modals/AppFullPageModal.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11813
I have:
|  <img width="379" alt="Capture d’écran 2021-11-16 à 14 02 16" src="https://user-images.githubusercontent.com/62059034/141990011-9bc3d61c-a2ed-4e9c-a843-549182973d49.png"> |       |   | ![Capture d’écran 2021-11-16 à 16 20 08](https://user-images.githubusercontent.com/62059034/142014098-c993faa0-1ec7-4ef4-b139-8af1b7f0d9fe.png)          |                  |
=> (PC-11813) feat(identityCheck): Add quit identity check screen

src/features/profile/pages/PersonalData.native.test.tsx, src/features/profile/pages/PersonalData.tsx, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11733
I have:
=> (PC-11733) feat(personalData): log ModifyMail event on button click

src/features/profile/pages/ChangeEmail/ChangeEmailExpiredLink.tsx, src/features/profile/pages/ChangeEmail/__tests__/ChangeEmailExpiredLink.native.test.tsx, src/libs/analytics/__mocks__/analytics.ts, src/libs/analytics/analytics.ts, src/libs/analytics/events.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11738
I have:
=> (PC-11738) feat(changeEmailExpiredLink): log event when resending an email

.circleci/config.yml, android/app/src/main/res/values/strings.xml
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11770
I have:
=> (PC-11770) feat(login): Make available the assetlinks.json file

package.json, src/features/bookings/pages/BookingNotFound.tsx, src/features/home/components/HomeBody.tsx, src/features/home/pages/useHomeModules.ts, src/features/home/pages/useHomeVenueModules.ts, src/features/search/pages/useSearchResults.ts, yarn.lock
A lot of bug fixes and new features coming with react-query. See [releases](https://github.com/tannerlinsley/react-query/releases)
=> build(reactquery): bump react-query version

.github/PULL_REQUEST_TEMPLATE.md, src/api/gen/api.ts, src/features/identityCheck/api.ts, src/features/identityCheck/components/SomeAdviceBeforeIdentityCheckModal.tsx, src/features/identityCheck/pages/identification/IdentityCheckWebview.tsx, src/features/navigation/RootNavigator/identityCheckRoutes.ts, src/features/navigation/RootNavigator/types.ts, src/libs/queryKeys.ts, src/locales/fr/messages.po, src/tests/server.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11727
I have:
=> (PC-11727) feat(IdentityCheck): add redirection to Ubble webview

__snapshots__/features/auth/signup/SetBirthday/SetBirthday.native.test.tsx.native-snap, src/features/auth/signup/SetBirthday/SetBirthday.tsx, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11615
I have:
| iOS 18 ans | iOS généralisation | Mobile - Chrome | Desktop - Chrome | Desktop - Safari |
|   <img width="361" alt="Capture d’écran 2021-11-19 à 14 31 56" src="https://user-images.githubusercontent.com/44037911/142630976-071aa478-d638-4b19-ba0e-14db17d258f3.png"> |    <img width="361" alt="Capture d’écran 2021-11-19 à 14 32 52" src="https://user-images.githubusercontent.com/44037911/142631081-34eea3f6-e169-4978-8ae4-b3025f585296.png">     |                 |                  |                  |
[2]: …
=> (PC-11615) fix(setBirthday): update 'why birthday' wording

__snapshots__/features/auth/signup/VerifyEligiblity/tests/NotYetUnderageEligibility.test.tsx.native-snap, __snapshots__/features/auth/signup/VerifyEligiblity/tests/NotYetUnderageEligibility.test.tsx.web-snap, src/features/auth/signup/VerifyEligiblity/NotYetUnderageEligibility.tsx, src/features/auth/signup/VerifyEligiblity/tests/NotYetUnderageEligibility.test.tsx, src/features/cheatcodes/pages/Navigation/Navigation.tsx, src/features/navigation/RootNavigator/routes.ts, src/features/navigation/RootNavigator/types.ts, src/locales/fr/messages.po
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11761
I have:
|     |     
=> (PC-11761) feat(checkEligibility): add page for non elligible underage

src/api/gen/api.ts, src/features/profile/__mocks__/mutations.ts, src/features/profile/api.ts, src/features/profile/mutations.ts, src/features/profile/pages/ChangeEmail/ChangeEmail.tsx, src/features/profile/pages/ChangeEmail/__tests__/ChangeEmail.native.test.tsx
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11573
I have:
=> (PC-11573) feat(changeEmail): connect change email call to api

src/features/offer/services/__tests__/useCtaWordingAndAction.test.ts, src/features/offer/services/useCtaWordingAndAction.ts, src/libs/algolia/fetchAlgolia/fetchAlgolia.facetFilters.ts
Link to JIRA ticket: https://passculture.atlassian.net/browse/PC-11861
I have:
=> (PC-11861) fix(offerCTA): add missing unavailable underage categories
